/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Andhra_Pradesh {
public static final String[][] green_bucket = {
{"Andhra Pradesh",  "3154", "Amalapuram", "Mortha Sivarama Krishna", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5769",  "आन्ध्र प्रदेश",  "अमलापुरम", "मर्तव शिवराम कृष्ण", "पिरामिड पार्टी ऑफ इंडिया", ""}, 
{"Andhra Pradesh",  "3160", "Amalapuram", "Ganti Harish Madhur", "Telugu Desam Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5026",  "आन्ध्र प्रदेश",  "अमलापुरम", "गँती हरीश मधुर", "तेलुगु देशम पार्टी", ""}, 
{"Andhra Pradesh",  "3161", "Amalapuram", "Rajani Chelle", "Jana Jagruti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5771",  "आन्ध्र प्रदेश",  "अमलापुरम", "रजनी चेल्ले", "जन जागृति पार्टी", ""}, 
{"Andhra Pradesh",  "3162", "Amalapuram", "Chinta Anuradha", "YSR Congress Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5028",  "आन्ध्र प्रदेश",  "अमलापुरम", "चिन्ता अनुराधा", "वाईएसआर कांग्रेस पार्टी", ""}, 
{"Andhra Pradesh",  "3128", "Anakapalle", "Chintala Partha Sarathi", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6201",  "आन्ध्र प्रदेश",  "अनकापल्ली", "चिन्तला पार्थ सारथी", "जनसेना पार्टी", ""}, 
{"Andhra Pradesh",  "3129", "Anakapalle", "Vadlamuri Krishna Swaroop", "Dalita Bahujana Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4676",  "आन्ध्र प्रदेश",  "अनकापल्ली", "वडलामुरी कृष्ण स्वरूप", "दलिता बहुजन पार्टी", ""}, 
{"Andhra Pradesh",  "3133", "Anakapalle", "K B Swaroop", "Jana Jagruti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4677",  "आन्ध्र प्रदेश",  "अनकापल्ली", "केबी स्वरूप", "जन जागृति पार्टी", ""}, 
{"Andhra Pradesh",  "3134", "Anakapalle", "Dr.Beesetti Venkata Satyavathi", "YSR Congress Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5018",  "आन्ध्र प्रदेश",  "अनकापल्ली", "डॉ। बिसेती वेंकट सत्यवती", "वाईएसआर कांग्रेस पार्टी", ""}, 
{"Andhra Pradesh",  "3319", "Anantapur", "Viswa Prasad Yadav Sankireddy", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4714",  "आन्ध्र प्रदेश",  "अनंतपुर", "विश्व प्रसाद यादव सांकड़ेड्डी", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3320", "Anantapur", "Juturu Chinna Reddy Pavan Reddy", "Telugu Desam Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4623",  "आन्ध्र प्रदेश",  "अनंतपुर", "जटुरु चिन्ना रेड्डी पावन रेड्डी", "तेलुगु देशम पार्टी", ""}, 
{"Andhra Pradesh",  "3322", "Anantapur", "Giddama Ranganayakulu", "Vishwa Jana Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6941",  "आन्ध्र प्रदेश",  "अनंतपुर", "गिडामा रंगनायकुलु", "विश्व जन पार्टी", ""}, 
{"Andhra Pradesh",  "3326", "Anantapur", "G. Lalitha", "Socialist Unity Centre of India (Communist)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4806",  "आन्ध्र प्रदेश",  "अनंतपुर", "जी। ललिता", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Andhra Pradesh",  "3327", "Anantapur", "Padchuri Radha Krishna", "Radical Democrats Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6945",  "आन्ध्र प्रदेश",  "अनंतपुर", "पद्चुरी राधा कृष्ण", "कट्टरपंथी डेमोक्रेट पार्टी", ""}, 
{"Andhra Pradesh",  "3082", "Araku", "Swamula Subrahamanyam", "Jana Jagruti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4786",  "आन्ध्र प्रदेश",  "अरकू", "स्वमुला सुब्रह्मण्यम", "जन जागृति पार्टी", ""}, 
{"Andhra Pradesh",  "3086", "Araku", "Goddeti Madhavi", "YSR Congress Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4784",  "आन्ध्र प्रदेश",  "अरकू", "देवी माधवी", "वाईएसआर कांग्रेस पार्टी", ""}, 
{"Andhra Pradesh",  "3090", "Araku", "Anumula Vamsi Krishna", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6174",  "आन्ध्र प्रदेश",  "अरकू", "अनामुला वामसी कृष्ण", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3256", "Bapatla", "Gadde Haribabu", "Navodayam Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6308",  "आन्ध्र प्रदेश",  "बापतला", "गद्दे हरिबाबू", "नवोदय पार्टी", ""}, 
{"Andhra Pradesh",  "3260", "Bapatla", "China Nageswara Rao Sadhu", "Mundadugu Praja Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6305",  "आन्ध्र प्रदेश",  "बापतला", "चीन नागेश्वर राव साधु", "मुंडदुगु प्रजा पार्टी", ""}, 
{"Andhra Pradesh",  "3263", "Bapatla", "Thumati Ravi", "All Peoples Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7207",  "आन्ध्र प्रदेश",  "बापतला", "ठुमती रवि", "ऑल पीपुल्स पार्टी", ""}, 
{"Andhra Pradesh",  "3264", "Bapatla", "Gella Nagamalli", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6310",  "आन्ध्र प्रदेश",  "बापतला", "गेला नागामल्ली", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3265", "Bapatla", "Kanthiraj Devanand", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6306",  "आन्ध्र प्रदेश",  "बापतला", "कांतिराज देवानंद", "बहुजन समाज पार्टी", ""}, 
{"Andhra Pradesh",  "3267", "Bapatla", "Golla Baburao", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7206",  "आन्ध्र प्रदेश",  "बापतला", "गोल्ला बाबूराव", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3391", "Chittoor", "P. Ramachandran", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6283",  "आन्ध्र प्रदेश",  "चित्तूर", "पी। रामचंद्रन", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3394", "Chittoor", "Pallipattu. Abhinav Vishnu", "Mundadugu Praja Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4821",  "आन्ध्र प्रदेश",  "चित्तूर", "Pallipattu। अभिनव विष्णु", "मुंडदुगु प्रजा पार्टी", ""}, 
{"Andhra Pradesh",  "3191", "Eluru", "Sridhar Kotagiri", "YSR Congress Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4682",  "आन्ध्र प्रदेश",  "एलुरु", "श्रीधर कोटागिरी", "वाईएसआर कांग्रेस पार्टी", ""}, 
{"Andhra Pradesh",  "3196", "Eluru", "Josyula China Venkata Suryanarayana", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4620",  "आन्ध्र प्रदेश",  "एलुरु", "जोसियुला चीन वेंकट सूर्यनारायण", "पिरामिड पार्टी ऑफ इंडिया", ""}, 
{"Andhra Pradesh",  "3229", "Guntur", "Umar Basha Shaik", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6290",  "आन्ध्र प्रदेश",  "गुंटूर", "उमर बाशा शैक", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3233", "Guntur", "Sarabandi Raju Sikhinam", "Indian Labour Party (Ambedkar Phule)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6291",  "आन्ध्र प्रदेश",  "गुंटूर", "सरबंदी राजू सिखिनम", "भारतीय मजदूर पार्टी (अम्बेडकर फुले)", ""}, 
{"Andhra Pradesh",  "3234", "Guntur", "Yanamadala Venkata Suresh", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6294",  "आन्ध्र प्रदेश",  "गुंटूर", "यनामदला वेंकट सुरेश", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3235", "Guntur", "Mannava Hariprasad", "Communist Party of India (Marxist–Leninist) Red Star", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5040",  "आन्ध्र प्रदेश",  "गुंटूर", "मानवा हरिप्रसाद", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) रेड स्टार", ""}, 
{"Andhra Pradesh",  "3237", "Guntur", "Ullagi David Jayakumar", "Hardam Manavtawadi Rashtriya Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6292",  "आन्ध्र प्रदेश",  "गुंटूर", "उल्लागी डेविड जयकुमार", "हरदम मानवतवादी राष्ट्रीय दल", ""}, 
{"Andhra Pradesh",  "3238", "Guntur", "Doppalapudi Veera Das", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6264",  "आन्ध्र प्रदेश",  "गुंटूर", "डोपलापुडी वीरा दास", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3241", "Guntur", "Jayadev Galla", "Telugu Desam Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5037",  "आन्ध्र प्रदेश",  "गुंटूर", "जयदेव गल्ला", "तेलुगु देशम पार्टी", ""}, 
{"Andhra Pradesh",  "3334", "Hindupur", "Gogula Pulakunta Jayanth", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6950",  "आन्ध्र प्रदेश",  "हिन्दुपुर", "गोगुला पुलकुंता जयंत", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3335", "Hindupur", "Mugi Surya Prakash", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6953",  "आन्ध्र प्रदेश",  "हिन्दुपुर", "मुगी सूर्य प्रकाश", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3338", "Hindupur", "S.R.Anjaneyulu", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6954",  "आन्ध्र प्रदेश",  "हिन्दुपुर", "SRAnjaneyulu", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3341", "Kadapa", "Siva Chandra Reddy Komma", "Anna YSR Congress Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4625",  "आन्ध्र प्रदेश",  "कडपा", "शिव चंद्र रेड्डी कोमा", "अन्ना वाईएसआर कांग्रेस पार्टी", ""}, 
{"Andhra Pradesh",  "3343", "Kadapa", "Nyamatulla Shaik", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6956",  "आन्ध्र प्रदेश",  "कडपा", "न्यामतुल्ला शिक", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3344", "Kadapa", "Ameen Peeran Shaik", "Ambedkar National Congress", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4624",  "आन्ध्र प्रदेश",  "कडपा", "अमीन पीरन शैक", "अंबेडकर राष्ट्रीय कांग्रेस", ""}, 
{"Andhra Pradesh",  "3349", "Kadapa", "Chadipirala Adi Narayana Reddy", "Telugu Desam Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4816",  "आन्ध्र प्रदेश",  "कडपा", "चादीपिरला आदि नारायण रेड्डी", "तेलुगु देशम पार्टी", ""}, 
{"Andhra Pradesh",  "3353", "Kadapa", "Pedakala Varalakshmi", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4815",  "आन्ध्र प्रदेश",  "कडपा", "पेदाकाला वरलक्ष्मी", "पिरामिड पार्टी ऑफ इंडिया", ""}, 
{"Andhra Pradesh",  "3138", "Kakinada", "Godugu Satyanarayana", "Communist Party of India (Marxist–Leninist) Liberation", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5023",  "आन्ध्र प्रदेश",  "काकीनाडा", "गोडुगु सत्यनारायण", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) मुक्ति", ""}, 
{"Andhra Pradesh",  "3143", "Kakinada", "Donam Neelakantam", "All India Praja Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6209",  "आन्ध्र प्रदेश",  "काकीनाडा", "डोनम नीलकांतम", "अखिल भारतीय प्रजा पार्टी", ""}, 
{"Andhra Pradesh",  "3144", "Kakinada", "Sunil Kumar Chalamalasetty", "Telugu Desam Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5022",  "आन्ध्र प्रदेश",  "काकीनाडा", "सुनील कुमार चलमलासट्टी", "तेलुगु देशम पार्टी", ""}, 
{"Andhra Pradesh",  "3147", "Kakinada", "Vanga Geetha Viswanatham", "YSR Congress Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5021",  "आन्ध्र प्रदेश",  "काकीनाडा", "वंगा गीता विश्वनाथम्", "वाईएसआर कांग्रेस पार्टी", ""}, 
{"Andhra Pradesh",  "3152", "Kakinada", "Appalakonda Vangalapudi", "Mundadugu Praja Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6213",  "आन्ध्र प्रदेश",  "काकीनाडा", "अपलाकोंडा वंगलपुडी", "मुंडदुगु प्रजा पार्टी", ""}, 
{"Andhra Pradesh",  "3304", "Kurnool", "S.Md. Shafath", "Rayalaseema Rashtra Samithi", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6939",  "आन्ध्र प्रदेश",  "कुरनूल", "S.Md. Shafath", "रायलसीमा राष्ट्र समिति", ""}, 
{"Andhra Pradesh",  "3310", "Kurnool", "Dandu Seshu Yadav", "Samajwadi Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6934",  "आन्ध्र प्रदेश",  "कुरनूल", "दंडू शेष यादव", "समाजवादी पार्टी", ""}, 
{"Andhra Pradesh",  "3311", "Kurnool", "Dr Sanjeev Kumar", "YSR Congress Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5054",  "आन्ध्र प्रदेश",  "कुरनूल", "डॉ संजीव कुमार", "वाईएसआर कांग्रेस पार्टी", ""}, 
{"Andhra Pradesh",  "3313", "Kurnool", "T. Beechupally", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6940",  "आन्ध्र प्रदेश",  "कुरनूल", "टी। बिचुपल्ली", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3316", "Kurnool", "P.V. Srihari", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6938",  "आन्ध्र प्रदेश",  "कुरनूल", "पीवी श्रीहरि", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3201", "Machilipatnam", "Bandreddi Ramakrishna", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6248",  "आन्ध्र प्रदेश",  "मछलीपट्टनम", "बंदेर्धारी रामकृष्ण", "जनसेना पार्टी", ""}, 
{"Andhra Pradesh",  "3205", "Machilipatnam", "Vijaya Lakshmi Chalapaka", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6247",  "आन्ध्र प्रदेश",  "मछलीपट्टनम", "विजया लक्ष्मी चलपका", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3208", "Machilipatnam", "Nadakuditi Naga Gayathri", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6250",  "आन्ध्र प्रदेश",  "मछलीपट्टनम", "नादकुदिति नागा गायत्री", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3285", "Nandyal", "Elluri Bhupal", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4720",  "आन्ध्र प्रदेश",  "नांदयाल", "एलुरी भूपल", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3289", "Nandyal", "Mandra Sivananda Reddy", "Telugu Desam Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4805",  "आन्ध्र प्रदेश",  "नांदयाल", "मंद्रा शिवानंद रेड्डी", "तेलुगु देशम पार्टी", ""}, 
{"Andhra Pradesh",  "3292", "Nandyal", "S. A. Indumathi", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6928",  "आन्ध्र प्रदेश",  "नांदयाल", "एसए इंदुमति", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3294", "Nandyal", "Dr. Lakshmi Kantha Reddy Chitla", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6922",  "आन्ध्र प्रदेश",  "नांदयाल", "डॉ। लक्ष्मी कांथा रेड्डी चितला", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3246", "Narasaraopet", "Kante Sayanna", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5043",  "आन्ध्र प्रदेश",  "नरसरोपेट", "कांटे स्याना", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3247", "Narasaraopet", "Lavu Sri Krishna Devarayalu", "YSR Congress Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4802",  "आन्ध्र प्रदेश",  "नरसरोपेट", "लावु श्री कृष्ण देवरयालु", "वाईएसआर कांग्रेस पार्टी", ""}, 
{"Andhra Pradesh",  "3249", "Narasaraopet", "Allu Venkata Reddy", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4801",  "आन्ध्र प्रदेश",  "नरसरोपेट", "अल्लू वेंकट रेड्डी", "पिरामिड पार्टी ऑफ इंडिया", ""}, 
{"Andhra Pradesh",  "3250", "Narasaraopet", "Gaddala Venu", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6303",  "आन्ध्र प्रदेश",  "नरसरोपेट", "गद्दाला वेणु", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3175", "Narsapuram", "Nagababu Konidela", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5035",  "आन्ध्र प्रदेश",  "नरसापुरम", "नागबाबू कोनिदेला", "जनसेना पार्टी", ""}, 
{"Andhra Pradesh",  "3176", "Narsapuram", "Nallam Surya Chandra Rao", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6231",  "आन्ध्र प्रदेश",  "नरसापुरम", "नालम सूर्य चंद्र राव", "पिरामिड पार्टी ऑफ इंडिया", ""}, 
{"Andhra Pradesh",  "3178", "Narsapuram", "Ganji Purnima", "Republican Party of India (Athawale)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6240",  "आन्ध्र प्रदेश",  "नरसापुरम", "गंजी पूर्णिमा", "भारतीय रिपब्लिकन पार्टी (अठावले)", ""}, 
{"Andhra Pradesh",  "3187", "Narsapuram", "Gottumukkala Shivaji", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6230",  "आन्ध्र प्रदेश",  "नरसापुरम", "गोतमुक्कल शिवाजी", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3188", "Narsapuram", "Yella Venugopal Rao", "Nava Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4789",  "आन्ध्र प्रदेश",  "नरसापुरम", "येला वेणुगोपाल राव", "नव समाज पार्टी", ""}, 
{"Andhra Pradesh",  "3357", "Nellore", "Dr. S. Suresh Babu", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6974",  "आन्ध्र प्रदेश",  "नेल्लोर", "डॉ। एस सुरेश बाबू", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3360", "Nellore", "Beeda Masthan Rao", "Telugu Desam Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6972",  "आन्ध्र प्रदेश",  "नेल्लोर", "बीदा मस्तान राव", "तेलुगु देशम पार्टी", ""}, 
{"Andhra Pradesh",  "3366", "Nellore", "Butti Nagaraju", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5057",  "आन्ध्र प्रदेश",  "नेल्लोर", "बुटी नागराजू", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3270", "Ongole", "Sidda Raghava Rao", "Telugu Desam Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4723",  "आन्ध्र प्रदेश",  "ओंगोल", "सिद्ध राघव राव", "तेलुगु देशम पार्टी", ""}, 
{"Andhra Pradesh",  "3272", "Ongole", "Maram Srinivasa Reddy", "Praja Shanthi Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6910",  "आन्ध्र प्रदेश",  "ओंगोल", "मरम श्रीनिवास रेड्डी", "प्रजा शांति पार्टी", ""}, 
{"Andhra Pradesh",  "3277", "Ongole", "Madhu Yattapu", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4725",  "आन्ध्र प्रदेश",  "ओंगोल", "मधु यतापु", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3278", "Ongole", "Mohan Ayyappa", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6913",  "आन्ध्र प्रदेश",  "ओंगोल", "मोहन अयप्पा", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3280", "Ongole", "Bellamkonda Saibabu", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6909",  "आन्ध्र प्रदेश",  "ओंगोल", "बेलमकोंडा साईंबु", "जनसेना पार्टी", ""}, 
{"Andhra Pradesh",  "3281", "Ongole", "Venkatesan Baburao", "India Praja Bandhu Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6914",  "आन्ध्र प्रदेश",  "ओंगोल", "वेंकटेशन बाबूराव", "भारत प्रजा बंधु पार्टी", ""}, 
{"Andhra Pradesh",  "3164", "Rajahmundry", "Roopa Rammohan Maganti", "Telugu Desam Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4679",  "आन्ध्र प्रदेश",  "राजमुंदरी", "रूप राममोहन मगंति", "तेलुगु देशम पार्टी", ""}, 
{"Andhra Pradesh",  "3168", "Rajahmundry", "Akula Satyanarayana", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6224",  "आन्ध्र प्रदेश",  "राजमुंदरी", "अकुला सत्यानारायण", "जनसेना पार्टी", ""}, 
{"Andhra Pradesh",  "3386", "Rajampet", "Pasupuleti Venkataramana", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5063",  "आन्ध्र प्रदेश",  "राजमपेट", "पसुपुलेटि वेंकटरामण", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3387", "Rajampet", "Karimulla Khan Pattan", "Navataram Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6288",  "आन्ध्र प्रदेश",  "राजमपेट", "करीमुल्ला खान पट्टन", "नवताराम पार्टी", ""}, 
{"Andhra Pradesh",  "3093", "Srikakulam", "Metta Ramarao", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5009",  "आन्ध्र प्रदेश",  "श्रीकाकुलम", "मेटता रामाराव", "जनसेना पार्टी", ""}, 
{"Andhra Pradesh",  "3095", "Srikakulam", "Betha Vivekananda Maharaj", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5011",  "आन्ध्र प्रदेश",  "श्रीकाकुलम", "बैथा विवेकानंद महाराज", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3096", "Srikakulam", "Matta Satish Chakravarthy", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6179",  "आन्ध्र प्रदेश",  "श्रीकाकुलम", "मटका सतीश चक्रवर्ती", "पिरामिड पार्टी ऑफ इंडिया", ""}, 
{"Andhra Pradesh",  "3098", "Srikakulam", "Naidugari Rajasekhar", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5007",  "आन्ध्र प्रदेश",  "श्रीकाकुलम", "नादुगारी राजशेखर", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3369", "Tirupati", "Neeruguttu Nagesh, M.A., Philosophy", "Janapaalana Party (Democratic)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7011",  "आन्ध्र प्रदेश",  "तिरुपति", "नीरूगुट्टू नागेश, एमए, दर्शनशास्त्र", "जनपालन पार्टी (लोकतांत्रिक)", ""}, 
{"Andhra Pradesh",  "3371", "Tirupati", "Panabaka Lakshmi", "Telugu Desam Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4729",  "आन्ध्र प्रदेश",  "तिरुपति", "पनाबका लक्ष्मी", "तेलुगु देशम पार्टी", ""}, 
{"Andhra Pradesh",  "3372", "Tirupati", "Viruvuru Sudhakar", "Vishwa Jana Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7013",  "आन्ध्र प्रदेश",  "तिरुपति", "विरुवरु सुधाकर", "विश्व जन पार्टी", ""}, 
{"Andhra Pradesh",  "3373", "Tirupati", "Balli Durgaprasad Rao", "YSR Congress Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5060",  "आन्ध्र प्रदेश",  "तिरुपति", "बल्ली दुर्गाप्रसाद राव", "वाईएसआर कांग्रेस पार्टी", ""}, 
{"Andhra Pradesh",  "3376", "Tirupati", "B Ramesh", "Viduthalai Chiruthaigal Katchi", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7006",  "आन्ध्र प्रदेश",  "तिरुपति", "B रमेश", "विदुथलाई चिरुथिगाल काची", ""}, 
{"Andhra Pradesh",  "3377", "Tirupati", "Kattamanchi Prabhakar", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5062",  "आन्ध्र प्रदेश",  "तिरुपति", "कट्टमंचि प्रभाकर", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3378", "Tirupati", "Doctor Daggumati Sreehari Rao", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7008",  "आन्ध्र प्रदेश",  "तिरुपति", "डॉक्टर दग्गुमती श्रीहरि राव", "बहुजन समाज पार्टी", ""}, 
{"Andhra Pradesh",  "3210", "Vijayawada", "Nandini Nallaghatla", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6258",  "आन्ध्र प्रदेश",  "विजयवाड़ा", "नंदिनी नल्लाघाटला", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3223", "Vijayawada", "Andukuri Vijaya Bhaskar", "India Praja Bandhu Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6262",  "आन्ध्र प्रदेश",  "विजयवाड़ा", "अंदुकुरी विजया भास्कर", "भारत प्रजा बंधु पार्टी", ""}, 
{"Andhra Pradesh",  "3116", "Visakhapatnam", "Bharat Mathukumilli", "Telugu Desam Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4675",  "आन्ध्र प्रदेश",  "विशाखापत्तनम", "भरत मथुकुमिलि", "तेलुगु देशम पार्टी", ""}, 
{"Andhra Pradesh",  "3119", "Visakhapatnam", "George Bangari", "Viduthalai Chiruthaigal Katchi", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6191",  "आन्ध्र प्रदेश",  "विशाखापत्तनम", "जॉर्ज बंगारी", "विदुथलाई चिरुथिगाल काची", ""}, 
{"Andhra Pradesh",  "3120", "Visakhapatnam", "V.V. Lakshmi Narayana", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5016",  "आन्ध्र प्रदेश",  "विशाखापत्तनम", "वीवी लक्ष्मी नारायण", "जनसेना पार्टी", ""}, 
{"Andhra Pradesh",  "3124", "Visakhapatnam", "Anmish Varma", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6195",  "आन्ध्र प्रदेश",  "विशाखापत्तनम", "अनमिश वर्मा", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3126", "Visakhapatnam", "Durgaprasad. Guntu", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6194",  "आन्ध्र प्रदेश",  "विशाखापत्तनम", "दुर्गाप्रसाद। Guntu", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3127", "Visakhapatnam", "Pulapaka Raja Sekhar", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6197",  "आन्ध्र प्रदेश",  "विशाखापत्तनम", "पुलकक राजा शेखर", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3102", "Vizianagaram", "Dhanalakoti Ramana", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6186",  "आन्ध्र प्रदेश",  "विजयनगरम", "धनलकोटी रमना", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3105", "Vizianagaram", "Venkata Trindha Rao Veluri", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6185",  "आन्ध्र प्रदेश",  "विजयनगरम", "वेंकट त्रिधा राव वेलुरी", "निर्दलीय", ""}, 
{"Andhra Pradesh",  "3112", "Vizianagaram", "Govinda Rao Lagudu", "Jana Jagruti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6183",  "आन्ध्र प्रदेश",  "विजयनगरम", "गोविंदा राव लगुडू", "जन जागृति पार्टी", ""}, 
};

public static final String[][] red_bucket = {
{ "Andhra Pradesh",  "3153",  "Amalapuram", "Manepalli Ayyaji Vema", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "अमलापुरम", "मनपल्ली अय्याजी वेमा", " "}, 
{ "Andhra Pradesh",  "3155",  "Amalapuram", "Panthagada Vijaya Chakravarthy", "OverAged",  " ","आन्ध्र प्रदेश",  "अमलापुरम", "पंथगदा विजया चक्रवर्ती", " "}, 
{ "Andhra Pradesh",  "3156",  "Amalapuram", "Janga Goutham", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "अमलापुरम", "जंगा गौतम", " "}, 
{ "Andhra Pradesh",  "3157",  "Amalapuram", "Mojas Raja Sekhar Duggirala", "CriminalCases",  " ","आन्ध्र प्रदेश",  "अमलापुरम", "मोजज राजा शेखर दुग्गीराला", " "}, 
{ "Andhra Pradesh",  "3158",  "Amalapuram", "Revu Sudhakar", "NotGraduate",  " ","आन्ध्र प्रदेश",  "अमलापुरम", "रेवु सुधाकर", " "}, 
{ "Andhra Pradesh",  "3159",  "Amalapuram", "Muralikrishna Kanderi", "NotGraduate",  " ","आन्ध्र प्रदेश",  "अमलापुरम", "मुरलीकृष्ण कंधारी", " "}, 
{ "Andhra Pradesh",  "3130",  "Anakapalle", "Adari Anand Kumar", "NotGraduate",  " ","आन्ध्र प्रदेश",  "अनकापल्ली", "आदिारी आनंद कुमार", " "}, 
{ "Andhra Pradesh",  "3131",  "Anakapalle", "Taadi Veera Jagadeeshwari", "OverAged",  " ","आन्ध्र प्रदेश",  "अनकापल्ली", "ताड़ी वीरा जगदेश्वरी", " "}, 
{ "Andhra Pradesh",  "3132",  "Anakapalle", "Dr Gandi Venkata Satyanarayana Rao", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "अनकापल्ली", "डॉ। गांडी वेंकट सत्यनारायण राव", " "}, 
{ "Andhra Pradesh",  "3135",  "Anakapalle", "P.S.Ajay Kumar", "CriminalCases",  " ","आन्ध्र प्रदेश",  "अनकापल्ली", "पीएसअजय कुमार", " "}, 
{ "Andhra Pradesh",  "3136",  "Anakapalle", "Appala Naidu Tummagonta", "NotGraduate",  " ","आन्ध्र प्रदेश",  "अनकापल्ली", "अप्पला नायडू तुममगोंता", " "}, 
{ "Andhra Pradesh",  "3137",  "Anakapalle", "Ruthala Srirama Murthy", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "अनकापल्ली", "रुतला श्रीराम मूर्ति", " "}, 
{ "Andhra Pradesh",  "3328",  "Anantapur", "Jagadeesh Devaragudi", "CriminalCases",  " ","आन्ध्र प्रदेश",  "अनंतपुर", "जगदीश देवरगुडी", " "}, 
{ "Andhra Pradesh",  "3329",  "Anantapur", "Talari Rangaiah", "CriminalCases",  " ","आन्ध्र प्रदेश",  "अनंतपुर", "तलारी रंगिया", " "}, 
{ "Andhra Pradesh",  "3330",  "Anantapur", "K Rajiv Reddy", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "अनंतपुर", "के राजीव रेड्डी", " "}, 
{ "Andhra Pradesh",  "3331",  "Anantapur", "Somanath Deshmukh", "NotGraduate",  " ","आन्ध्र प्रदेश",  "अनंतपुर", "सोमनाथ देशमुख", " "}, 
{ "Andhra Pradesh",  "3318",  "Anantapur", "Vadde Kasinath", "NotGraduate",  " ","आन्ध्र प्रदेश",  "अनंतपुर", "वाडडे काशीनाथ", " "}, 
{ "Andhra Pradesh",  "3321",  "Anantapur", "M.Venkatesulu", "NotGraduate",  " ","आन्ध्र प्रदेश",  "अनंतपुर", "M.Venkatesulu", " "}, 
{ "Andhra Pradesh",  "3323",  "Anantapur", "Lingutla Rangaiah", "OverAged",  " ","आन्ध्र प्रदेश",  "अनंतपुर", "लिंगुतला रंगैया", " "}, 
{ "Andhra Pradesh",  "3324",  "Anantapur", "Pothuru Rangaiah", "NotGraduate",  " ","आन्ध्र प्रदेश",  "अनंतपुर", "पोथुरू रंगाया", " "}, 
{ "Andhra Pradesh",  "3325",  "Anantapur", "Hamsa Devineni", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "अनंतपुर", "हम्सा देवीनेनी", " "}, 
{ "Andhra Pradesh",  "3081",  "Araku", "Vyricherla Kishore Chandra Suryanarayana Deo", "OverAged",  " ","आन्ध्र प्रदेश",  "अरकू", "विरिचरला किशोर चन्द्र सूर्यनारायण देव", " "}, 
{ "Andhra Pradesh",  "3083",  "Araku", "Dr. Kasi Viswanadha Veera Venkata Satyanarayana Reddy Kosuri", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "अरकू", "डॉ। काशी विश्वनाथ वीरा वेंकट सत्यनारायण रेड्डी कोसुरी", " "}, 
{ "Andhra Pradesh",  "3084",  "Araku", "Narava Satyavathi", "NotGraduate",  " ","आन्ध्र प्रदेश",  "अरकू", "नरवा सत्यवती", " "}, 
{ "Andhra Pradesh",  "3085",  "Araku", "Kangala Baladora", "NotGraduate",  " ","आन्ध्र प्रदेश",  "अरकू", "कंगला बलाडोरा", " "}, 
{ "Andhra Pradesh",  "3087",  "Araku", "Vampuru Gangulaiah", "CriminalCases",  " ","आन्ध्र प्रदेश",  "अरकू", "वैम्पुरु गंगुलाया", " "}, 
{ "Andhra Pradesh",  "3088",  "Araku", "Biddika Ramaiah", "NotGraduate",  " ","आन्ध्र प्रदेश",  "अरकू", "बिद्दिका रमैया", " "}, 
{ "Andhra Pradesh",  "3089",  "Araku", "Shruti Devi Vyricherla", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "अरकू", "श्रुति देवी विरंचेरला", " "}, 
{ "Andhra Pradesh",  "3257",  "Bapatla", "Challagali Kishore Kumar", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "बापतला", "चेलगाली किशोर कुमार", " "}, 
{ "Andhra Pradesh",  "3258",  "Bapatla", "Jesudasu Seelam", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "बापतला", "येसुदासु सीलम", " "}, 
{ "Andhra Pradesh",  "3259",  "Bapatla", "Nuthakki Rama Rao", "OverAged",  " ","आन्ध्र प्रदेश",  "बापतला", "नथत्की रामा राव", " "}, 
{ "Andhra Pradesh",  "3261",  "Bapatla", "Kattepogu Vijay Kumar", "NotGraduate",  " ","आन्ध्र प्रदेश",  "बापतला", "कट्टेपोगु विजय कुमार", " "}, 
{ "Andhra Pradesh",  "3262",  "Bapatla", "Malyadri Sriram", "OverAged",  " ","आन्ध्र प्रदेश",  "बापतला", "मलयाद्री श्रीराम", " "}, 
{ "Andhra Pradesh",  "3266",  "Bapatla", "Suresh Babu Nandigam", "NotGraduate",  " ","आन्ध्र प्रदेश",  "बापतला", "सुरेश बाबू नंदीग्राम", " "}, 
{ "Andhra Pradesh",  "3268",  "Bapatla", "Bussa Nagaraju", "CriminalCases",  " ","आन्ध्र प्रदेश",  "बापतला", "बुसा नागराजू", " "}, 
{ "Andhra Pradesh",  "3388",  "Chittoor", "C. Punyamurthy", "CriminalCases",  " ","आन्ध्र प्रदेश",  "चित्तूर", "सी। पुण्यमूर्ति", " "}, 
{ "Andhra Pradesh",  "3389",  "Chittoor", "Jayaram Duggani", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "चित्तूर", "जयराम दुग्गानी", " "}, 
{ "Andhra Pradesh",  "3390",  "Chittoor", "Cheemala. Rangappa", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "चित्तूर", "Cheemala। रंगप्पा", " "}, 
{ "Andhra Pradesh",  "3392",  "Chittoor", "N. Reddeppa", "OverAged",  " ","आन्ध्र प्रदेश",  "चित्तूर", "एन। रेड्डीप्पा", " "}, 
{ "Andhra Pradesh",  "3393",  "Chittoor", "A. Hemanth", "NotGraduate",  " ","आन्ध्र प्रदेश",  "चित्तूर", "ए। हेमंत", " "}, 
{ "Andhra Pradesh",  "3395",  "Chittoor", "Naramalli Siva Prasad", "OverAged",  " ","आन्ध्र प्रदेश",  "चित्तूर", "नारमल्ली शिव प्रसाद", " "}, 
{ "Andhra Pradesh",  "3189",  "Eluru", "Gurunadha Rao Jetti", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "एलुरु", "गुरुनधान राव जेट्टी", " "}, 
{ "Andhra Pradesh",  "3190",  "Eluru", "Maganti Venkateswara Rao", "CriminalCases",  " ","आन्ध्र प्रदेश",  "एलुरु", "मगंति वेंकटेश्वर राव", " "}, 
{ "Andhra Pradesh",  "3192",  "Eluru", "Chinnam Rama Kotayya", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "एलुरु", "छिन्नम राम कोटाय", " "}, 
{ "Andhra Pradesh",  "3193",  "Eluru", "Mathe Bobby", "NotGraduate",  " ","आन्ध्र प्रदेश",  "एलुरु", "माथे बॉबी", " "}, 
{ "Andhra Pradesh",  "3194",  "Eluru", "V Siva Rama Krishna", "NotGraduate",  " ","आन्ध्र प्रदेश",  "एलुरु", "वी शिव राम कृष्ण", " "}, 
{ "Andhra Pradesh",  "3195",  "Eluru", "Alaga Ravi Kumar", "NotGraduate",  " ","आन्ध्र प्रदेश",  "एलुरु", "अलागा रवि कुमार", " "}, 
{ "Andhra Pradesh",  "3197",  "Eluru", "Mendem Santhosh Kumar", "NotGraduate",  " ","आन्ध्र प्रदेश",  "एलुरु", "मेंडेम संतोष कुमार", " "}, 
{ "Andhra Pradesh",  "3225",  "Guntur", "Araveti Hazarath Rao", "OverAged",  " ","आन्ध्र प्रदेश",  "गुंटूर", "अरवेती हज़रत राव", " "}, 
{ "Andhra Pradesh",  "3226",  "Guntur", "Jayaprakash Narayana Valluru", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "गुंटूर", "जयप्रकाश नारायण वल्लुरु", " "}, 
{ "Andhra Pradesh",  "3227",  "Guntur", "Dasari Kiran Babu", "NotGraduate",  " ","आन्ध्र प्रदेश",  "गुंटूर", "दसारी किरन बाबू", " "}, 
{ "Andhra Pradesh",  "3228",  "Guntur", "Modugula Venugopala Reddy", "CriminalCases",  " ","आन्ध्र प्रदेश",  "गुंटूर", "मोडुगुला वेणुगोपाला रेड्डी", " "}, 
{ "Andhra Pradesh",  "3230",  "Guntur", "Samudrala Chinna Kotaiah", "NotGraduate",  " ","आन्ध्र प्रदेश",  "गुंटूर", "समुद्राला चिन्ना कोटािया", " "}, 
{ "Andhra Pradesh",  "3231",  "Guntur", "Jeldi Raja Mohan", "NotGraduate",  " ","आन्ध्र प्रदेश",  "गुंटूर", "जेल्डी राजा मोहन", " "}, 
{ "Andhra Pradesh",  "3232",  "Guntur", "Shaik Jaleel", "NotGraduate",  " ","आन्ध्र प्रदेश",  "गुंटूर", "शैक जलील", " "}, 
{ "Andhra Pradesh",  "3236",  "Guntur", "Bonaboyina Srinivasa Rao", "CriminalCases",  " ","आन्ध्र प्रदेश",  "गुंटूर", "बोनाबोयिना श्रीनिवास राव", " "}, 
{ "Andhra Pradesh",  "3239",  "Guntur", "Jacob Vidyasagar Nakka", "CriminalCases",  " ","आन्ध्र प्रदेश",  "गुंटूर", "जैकब विद्यासागर नक्का", " "}, 
{ "Andhra Pradesh",  "3240",  "Guntur", "Ramarao Simhadri", "NotGraduate",  " ","आन्ध्र प्रदेश",  "गुंटूर", "रामाराव सिम्हाद्रि", " "}, 
{ "Andhra Pradesh",  "3242",  "Guntur", "Shaik Mastanvali", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "गुंटूर", "शेख मस्तनवाली", " "}, 
{ "Andhra Pradesh",  "3332",  "Hindupur", "S.Ram Mohan", "NotGraduate",  " ","आन्ध्र प्रदेश",  "हिन्दुपुर", "एस.राम मोहन", " "}, 
{ "Andhra Pradesh",  "3333",  "Hindupur", "Ramamohan D.G.", "NotGraduate",  " ","आन्ध्र प्रदेश",  "हिन्दुपुर", "राममोहन डीजी", " "}, 
{ "Andhra Pradesh",  "3336",  "Hindupur", "Kuruva Gorantla Madhav", "CriminalCases",  " ","आन्ध्र प्रदेश",  "हिन्दुपुर", "कुरुवा गोरान्तला माधव", " "}, 
{ "Andhra Pradesh",  "3337",  "Hindupur", "Mitta Parthasarathi", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "हिन्दुपुर", "मित्ता पार्थसारथी", " "}, 
{ "Andhra Pradesh",  "3339",  "Hindupur", "N.Kristappa", "CriminalCases",  " ","आन्ध्र प्रदेश",  "हिन्दुपुर", "N.Kristappa", " "}, 
{ "Andhra Pradesh",  "3340",  "Hindupur", "K.T.Sreedhar", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "हिन्दुपुर", "KTSreedhar", " "}, 
{ "Andhra Pradesh",  "3342",  "Kadapa", "Yeduguri Sandinti Avinash Reddy", "CriminalCases",  " ","आन्ध्र प्रदेश",  "कडपा", "यदुगुड़ी संदींति अविनाश रेड्डी", " "}, 
{ "Andhra Pradesh",  "3345",  "Kadapa", "Jakku Chenna Krishna Reddy", "CriminalCases",  " ","आन्ध्र प्रदेश",  "कडपा", "जक्कू चेन्ना कृष्णा रेड्डी", " "}, 
{ "Andhra Pradesh",  "3346",  "Kadapa", "Lakshmi Reddy Putha", "CriminalCases",  " ","आन्ध्र प्रदेश",  "कडपा", "लक्ष्मी रेड्डी पुथा", " "}, 
{ "Andhra Pradesh",  "3347",  "Kadapa", "Chadipiralla Siva Narayana Reddy", "NotGraduate",  " ","आन्ध्र प्रदेश",  "कडपा", "चादिपिरल्ला शिव नारायण रेड्डी", " "}, 
{ "Andhra Pradesh",  "3348",  "Kadapa", "Venu Gopal Rachineni", "NotGraduate",  " ","आन्ध्र प्रदेश",  "कडपा", "वेणु गोपाल रचिनीनी", " "}, 
{ "Andhra Pradesh",  "3350",  "Kadapa", "Gundlakunta Sreeramulu", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "कडपा", "गुंडलाकुंटा श्रीरामुलु", " "}, 
{ "Andhra Pradesh",  "3351",  "Kadapa", "Gujjula Eswaraiah", "CriminalCases",  " ","आन्ध्र प्रदेश",  "कडपा", "गुजुला ईस्वरैया", " "}, 
{ "Andhra Pradesh",  "3352",  "Kadapa", "Gona Purushottam Reddy", "CriminalCases",  " ","आन्ध्र प्रदेश",  "कडपा", "गोना पुरुषोत्तम रेड्डी", " "}, 
{ "Andhra Pradesh",  "3354",  "Kadapa", "Sri Rama Chandra Singareddy", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "कडपा", "श्री राम चंद्र सिंगारेड्डी", " "}, 
{ "Andhra Pradesh",  "3139",  "Kakinada", "Sathi Veera Lakshmi", "NotGraduate",  " ","आन्ध्र प्रदेश",  "काकीनाडा", "सती वीरा लक्ष्मी", " "}, 
{ "Andhra Pradesh",  "3140",  "Kakinada", "Ankadi Sathibabu", "NotGraduate",  " ","आन्ध्र प्रदेश",  "काकीनाडा", "अनादि सतिबाबू", " "}, 
{ "Andhra Pradesh",  "3141",  "Kakinada", "Mallipudi Sri Ramachandra Murthy", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "काकीनाडा", "मल्लीपुड़ी श्री रामचंद्र मूर्ति", " "}, 
{ "Andhra Pradesh",  "3142",  "Kakinada", "Buddala Geetha Devi", "NotGraduate",  " ","आन्ध्र प्रदेश",  "काकीनाडा", "बुद्धाला गीता देवी", " "}, 
{ "Andhra Pradesh",  "3145",  "Kakinada", "Yalla Venkata Rama Mohana Rao", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "काकीनाडा", "यल्ला वेंकट राम मोहना राव", " "}, 
{ "Andhra Pradesh",  "3146",  "Kakinada", "Medisetti Vijaya Kumar", "CriminalCases",  " ","आन्ध्र प्रदेश",  "काकीनाडा", "मेदिसेटि विजया कुमार", " "}, 
{ "Andhra Pradesh",  "3148",  "Kakinada", "Peddimsetti Venkateswara Rao", "CriminalCases",  " ","आन्ध्र प्रदेश",  "काकीनाडा", "पेद्दिस्मेट्टी वेंकटेश्वर राव", " "}, 
{ "Andhra Pradesh",  "3149",  "Kakinada", "Kakileti Ravindra", "NotGraduate",  " ","आन्ध्र प्रदेश",  "काकीनाडा", "काकेली रविंद्र", " "}, 
{ "Andhra Pradesh",  "3150",  "Kakinada", "Jyothula Venkateswara Rao", "NotGraduate",  " ","आन्ध्र प्रदेश",  "काकीनाडा", "ज्योथुला वेंकटेश्वर राव", " "}, 
{ "Andhra Pradesh",  "3151",  "Kakinada", "Vasamsetty Venakta Ramana", "NotGraduate",  " ","आन्ध्र प्रदेश",  "काकीनाडा", "वसामस्ति वेंकट रमणा", " "}, 
{ "Andhra Pradesh",  "3302",  "Kurnool", "G Sanjeeva Kumar", "NotGraduate",  " ","आन्ध्र प्रदेश",  "कुरनूल", "जी संजीव कुमार", " "}, 
{ "Andhra Pradesh",  "3303",  "Kurnool", "B. Shiva Kumar", "NotGraduate",  " ","आन्ध्र प्रदेश",  "कुरनूल", "बी। शिव कुमार", " "}, 
{ "Andhra Pradesh",  "3305",  "Kurnool", "Abdul Waris", "CriminalCases",  " ","आन्ध्र प्रदेश",  "कुरनूल", "अब्दुल वारिस", " "}, 
{ "Andhra Pradesh",  "3306",  "Kurnool", "Kotla Jaya Surya Prakash Reddy", "OverAged",  " ","आन्ध्र प्रदेश",  "कुरनूल", "कोटला जया सूर्य प्रकाश रेड्डी", " "}, 
{ "Andhra Pradesh",  "3307",  "Kurnool", "Kasula Rajasekhar", "NotGraduate",  " ","आन्ध्र प्रदेश",  "कुरनूल", "कसुला राजशेखर", " "}, 
{ "Andhra Pradesh",  "3308",  "Kurnool", "Devarapogu Maddilety", "CriminalCases",  " ","आन्ध्र प्रदेश",  "कुरनूल", "देवरपोगु मडिलिटी", " "}, 
{ "Andhra Pradesh",  "3309",  "Kurnool", "Kommireddy Prabhakar Reddy", "CriminalCases",  " ","आन्ध्र प्रदेश",  "कुरनूल", "कोमिरेड्डी प्रभाकर रेड्डी", " "}, 
{ "Andhra Pradesh",  "3312",  "Kurnool", "Hatcholi Thomas", "NotGraduate",  " ","आन्ध्र प्रदेश",  "कुरनूल", "हैचोली थॉमस", " "}, 
{ "Andhra Pradesh",  "3314",  "Kurnool", "M. Naganna", "CriminalCases",  " ","आन्ध्र प्रदेश",  "कुरनूल", "एम। नागन्ना", " "}, 
{ "Andhra Pradesh",  "3315",  "Kurnool", "Ahmed Ali Khan", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "कुरनूल", "अहमद अली खान", " "}, 
{ "Andhra Pradesh",  "3317",  "Kurnool", "P.V. Parthasarathi", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "कुरनूल", "पीवी पार्थसारथी", " "}, 
{ "Andhra Pradesh",  "3198",  "Machilipatnam", "Gollu Krishna", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "मछलीपट्टनम", "गोलू कृष्ण", " "}, 
{ "Andhra Pradesh",  "3199",  "Machilipatnam", "Balashowry Vallabhaneni", "CriminalCases",  " ","आन्ध्र प्रदेश",  "मछलीपट्टनम", "बालाशोवरी वल्लभानेनी", " "}, 
{ "Andhra Pradesh",  "3200",  "Machilipatnam", "Gudivaka Venkata Naga Basava Rao", "NotGraduate",  " ","आन्ध्र प्रदेश",  "मछलीपट्टनम", "गुडीवाका वेंकट नाग बासावा राव", " "}, 
{ "Andhra Pradesh",  "3202",  "Machilipatnam", "Konakalla Narayana Rao", "OverAged",  " ","आन्ध्र प्रदेश",  "मछलीपट्टनम", "कोनकल्ला नारायण राव", " "}, 
{ "Andhra Pradesh",  "3203",  "Machilipatnam", "Peram Siva Nageswara Rao", "NotGraduate",  " ","आन्ध्र प्रदेश",  "मछलीपट्टनम", "पेरम शिव नागेश्वर राव", " "}, 
{ "Andhra Pradesh",  "3204",  "Machilipatnam", "Gudivaka Ramanjaneyulu", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "मछलीपट्टनम", "गुडीवाका रमनंजयुलु", " "}, 
{ "Andhra Pradesh",  "3206",  "Machilipatnam", "Valluru Venkateswara Rao", "OverAged",  " ","आन्ध्र प्रदेश",  "मछलीपट्टनम", "वल्लुरु वेंकटेश्वर राव", " "}, 
{ "Andhra Pradesh",  "3207",  "Machilipatnam", "Gandhi Dhanekula", "OverAged",  " ","आन्ध्र प्रदेश",  "मछलीपट्टनम", "गांधी धनकुला", " "}, 
{ "Andhra Pradesh",  "3209",  "Machilipatnam", "Yarlagadda Rama Mohana Rao", "NotGraduate",  " ","आन्ध्र प्रदेश",  "मछलीपट्टनम", "यारलागड्डा राम मोहना राव", " "}, 
{ "Andhra Pradesh",  "3282",  "Nandyal", "C. Surendra Nath Reddy", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नांदयाल", "सी। सुरेन्द्र नाथ रेड्डी", " "}, 
{ "Andhra Pradesh",  "3283",  "Nandyal", "Jestadi Sudhakar", "CriminalCases",  " ","आन्ध्र प्रदेश",  "नांदयाल", "जस्तेदी सुधाकर", " "}, 
{ "Andhra Pradesh",  "3284",  "Nandyal", "Ruddireddy Radhakrishna", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नांदयाल", "रुद्धिरड्डी राधाकृष्ण", " "}, 
{ "Andhra Pradesh",  "3286",  "Nandyal", "Poluru Guruvaiah", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नांदयाल", "पोलुरु गुरुवा", " "}, 
{ "Andhra Pradesh",  "3287",  "Nandyal", "Vangala Parameswara Reddy.", "CriminalCases",  " ","आन्ध्र प्रदेश",  "नांदयाल", "वंगला परमेश्वर रेड्डी।", " "}, 
{ "Andhra Pradesh",  "3288",  "Nandyal", "Bhuma Kishor Reddy", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नांदयाल", "भूमा किशोर रेड्डी", " "}, 
{ "Andhra Pradesh",  "3290",  "Nandyal", "D. Mahammad Rafi", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नांदयाल", "डी। महम्मद रफ़ी", " "}, 
{ "Andhra Pradesh",  "3291",  "Nandyal", "K.P. Kambagiriswamy", "CriminalCases",  " ","आन्ध्र प्रदेश",  "नांदयाल", "केपी कांबगीरीस्वामी", " "}, 
{ "Andhra Pradesh",  "3293",  "Nandyal", "D. P. Jamal Basha", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नांदयाल", "डीपी जमाल बाशा", " "}, 
{ "Andhra Pradesh",  "3295",  "Nandyal", "B.C. Ramanatha Reddy", "CriminalCases",  " ","आन्ध्र प्रदेश",  "नांदयाल", "बीसी रमानाथ रेड्डी", " "}, 
{ "Andhra Pradesh",  "3296",  "Nandyal", "Pula. Nagamaddilety", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नांदयाल", "पुला। Nagamaddilety", " "}, 
{ "Andhra Pradesh",  "3297",  "Nandyal", "S.P.Y. Reddy", "CriminalCases",  " ","आन्ध्र प्रदेश",  "नांदयाल", "एसपीवाई रेड्डी", " "}, 
{ "Andhra Pradesh",  "3298",  "Nandyal", "Adinarayana Inty", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "नांदयाल", "आदिनारायण इं", " "}, 
{ "Andhra Pradesh",  "3299",  "Nandyal", "Lakshmi Narasaiah Jangiti", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "नांदयाल", "लक्ष्मी नारसहाय जंगीति", " "}, 
{ "Andhra Pradesh",  "3300",  "Nandyal", "I.V. Pakkir Reddy", "CriminalCases",  " ","आन्ध्र प्रदेश",  "नांदयाल", "IV पाकीर रेड्डी", " "}, 
{ "Andhra Pradesh",  "3301",  "Nandyal", "Pocha Brahmananda Reddy", "CriminalCases",  " ","आन्ध्र प्रदेश",  "नांदयाल", "पोचा ब्रह्मानंद रेड्डी", " "}, 
{ "Andhra Pradesh",  "3243",  "Narasaraopet", "Reddyboina Prasanna Kumar", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नरसरोपेट", "रेड्डीबोनी प्रसन्ना कुमार", " "}, 
{ "Andhra Pradesh",  "3244",  "Narasaraopet", "Rayapati Sambasiva Rao", "OverAged",  " ","आन्ध्र प्रदेश",  "नरसरोपेट", "रायपट्टी सांबशिव राव", " "}, 
{ "Andhra Pradesh",  "3245",  "Narasaraopet", "Durgampudi Rami Reddy", "OverAged",  " ","आन्ध्र प्रदेश",  "नरसरोपेट", "दुर्गमपुदी रामी रेड्डी", " "}, 
{ "Andhra Pradesh",  "3248",  "Narasaraopet", "Kanakam Srinivasarao", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नरसरोपेट", "कनकम श्रीनिवासराव", " "}, 
{ "Andhra Pradesh",  "3251",  "Narasaraopet", "Surabhi Devasahayam", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नरसरोपेट", "सुरभि देवसहायम्", " "}, 
{ "Andhra Pradesh",  "3252",  "Narasaraopet", "Pakkala Suribabu", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "नरसरोपेट", "पक्कल सुरिबू", " "}, 
{ "Andhra Pradesh",  "3253",  "Narasaraopet", "Narasimharao Parimi", "CriminalCases",  " ","आन्ध्र प्रदेश",  "नरसरोपेट", "नरसिंहराव परिमी", " "}, 
{ "Andhra Pradesh",  "3254",  "Narasaraopet", "Kanna Lakshmi Narayana", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "नरसरोपेट", "कन्ना लक्ष्मी नारायण", " "}, 
{ "Andhra Pradesh",  "3255",  "Narasaraopet", "Shaik Nayub Kamal", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नरसरोपेट", "शैक नायब कमल", " "}, 
{ "Andhra Pradesh",  "3174",  "Narsapuram", "Kanumuru Raghu Rama Krishna Raju", "CriminalCases",  " ","आन्ध्र प्रदेश",  "नरसापुरम", "कानमुरु रघु राम कृष्ण राजू", " "}, 
{ "Andhra Pradesh",  "3177",  "Narsapuram", "Medapati Varahala Reddy", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नरसापुरम", "मेदापति वराहला रेड्डी", " "}, 
{ "Andhra Pradesh",  "3179",  "Narsapuram", "Dasari Krishna Murthy", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नरसापुरम", "दसारी कृष्ण मूर्ति", " "}, 
{ "Andhra Pradesh",  "3180",  "Narsapuram", "Nalli Rajesh", "CriminalCases",  " ","आन्ध्र प्रदेश",  "नरसापुरम", "नल्ली राजेश", " "}, 
{ "Andhra Pradesh",  "3181",  "Narsapuram", "Pydikondala Manikyala Rao", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "नरसापुरम", "पाइदिकोंडला माणिक्यला राव", " "}, 
{ "Andhra Pradesh",  "3182",  "Narsapuram", "Venkata Sivarama Raju Vetukuri", "CriminalCases",  " ","आन्ध्र प्रदेश",  "नरसापुरम", "वेंकट शिवराम राजू वेतुकुरी", " "}, 
{ "Andhra Pradesh",  "3183",  "Narsapuram", "Kanumuru Bapiraju", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "नरसापुरम", "कानमुरु बापिराजू", " "}, 
{ "Andhra Pradesh",  "3184",  "Narsapuram", "K.A.Paul", "CriminalCases",  " ","आन्ध्र प्रदेश",  "नरसापुरम", "KAPaul", " "}, 
{ "Andhra Pradesh",  "3185",  "Narsapuram", "G S Raju", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नरसापुरम", "जीएस राजू", " "}, 
{ "Andhra Pradesh",  "3186",  "Narsapuram", "Gurugubilli Rambabu", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नरसापुरम", "गुरुगुबिली रामबाबू", " "}, 
{ "Andhra Pradesh",  "3355",  "Nellore", "Sannapureddy Suresh Reddy", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "नेल्लोर", "सन्निपुरेड्डी सुरेश रेड्डी", " "}, 
{ "Andhra Pradesh",  "3356",  "Nellore", "Narasapuram Prasad", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नेल्लोर", "नरसापुरम प्रसाद", " "}, 
{ "Andhra Pradesh",  "3358",  "Nellore", "Chandra Rajagopal", "CriminalCases",  " ","आन्ध्र प्रदेश",  "नेल्लोर", "चन्द्र राजगोपाल", " "}, 
{ "Andhra Pradesh",  "3359",  "Nellore", "Chevuru Devakumar Reddy", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "नेल्लोर", "शेवरु देवकुमार रेड्डी", " "}, 
{ "Andhra Pradesh",  "3361",  "Nellore", "Chinni Venkateswarlu", "OverAged",  " ","आन्ध्र प्रदेश",  "नेल्लोर", "चिन्नी वेंकटेश्वरलु", " "}, 
{ "Andhra Pradesh",  "3362",  "Nellore", "Meda Malla Reddy", "OverAged",  " ","आन्ध्र प्रदेश",  "नेल्लोर", "मेदा मल्ला रेड्डी", " "}, 
{ "Andhra Pradesh",  "3363",  "Nellore", "Kankanala Penchala Naidu", "NotGraduate",  " ","आन्ध्र प्रदेश",  "नेल्लोर", "कंकनमाला पेन्चाला नायडू", " "}, 
{ "Andhra Pradesh",  "3364",  "Nellore", "Adala Prabhakara Reddy", "OverAged",  " ","आन्ध्र प्रदेश",  "नेल्लोर", "अदला प्रभाकर रेड्डी", " "}, 
{ "Andhra Pradesh",  "3365",  "Nellore", "Shaik Mahaboob Basha (Mabu)", "CriminalCases",  " ","आन्ध्र प्रदेश",  "नेल्लोर", "शैक महबूब बाशा (माबु)", " "}, 
{ "Andhra Pradesh",  "3269",  "Ongole", "Konda Praveen Kumar", "NotGraduate",  " ","आन्ध्र प्रदेश",  "ओंगोल", "कोंडा प्रवीण कुमार", " "}, 
{ "Andhra Pradesh",  "3271",  "Ongole", "Venkatesh Vepuri", "NotGraduate",  " ","आन्ध्र प्रदेश",  "ओंगोल", "वेंकटेश वेपुरी", " "}, 
{ "Andhra Pradesh",  "3273",  "Ongole", "Dr Sirivella Prasad", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "ओंगोल", "डॉ। सिरिवला प्रसाद", " "}, 
{ "Andhra Pradesh",  "3274",  "Ongole", "Billa Chennaiah", "NotGraduate",  " ","आन्ध्र प्रदेश",  "ओंगोल", "बिल्ला चेन्नाया", " "}, 
{ "Andhra Pradesh",  "3275",  "Ongole", "Thoganti Sreenivasulu", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "ओंगोल", "थोगन्ति श्रीनिवासुलु", " "}, 
{ "Andhra Pradesh",  "3276",  "Ongole", "Magunta Sreenivasulu Reddy", "OverAged",  " ","आन्ध्र प्रदेश",  "ओंगोल", "मगुंटा श्रीनिवासुलु रेड्डी", " "}, 
{ "Andhra Pradesh",  "3279",  "Ongole", "Kavuri Venu Babu Naidu", "NotGraduate",  " ","आन्ध्र प्रदेश",  "ओंगोल", "कवुरी वेणु बाबू नायडू", " "}, 
{ "Andhra Pradesh",  "3163",  "Rajahmundry", "Venu Kollapu", "CriminalCases",  " ","आन्ध्र प्रदेश",  "राजमुंदरी", "वेणु कोल्लापु", " "}, 
{ "Andhra Pradesh",  "3165",  "Rajahmundry", "Margani Bharat Ram", "CriminalCases",  " ","आन्ध्र प्रदेश",  "राजमुंदरी", "मरगनी भरत राम", " "}, 
{ "Andhra Pradesh",  "3166",  "Rajahmundry", "Geddam David Nelson Babu", "CriminalCases",  " ","आन्ध्र प्रदेश",  "राजमुंदरी", "गेड्डम डेविड नेल्सन बाबू", " "}, 
{ "Andhra Pradesh",  "3167",  "Rajahmundry", "Bandaru Rajeswara Rao", "NotGraduate",  " ","आन्ध्र प्रदेश",  "राजमुंदरी", "बंडारू राजेश्वर राव", " "}, 
{ "Andhra Pradesh",  "3169",  "Rajahmundry", "Meda Srinivasa Rao", "CriminalCases",  " ","आन्ध्र प्रदेश",  "राजमुंदरी", "मेदा श्रीनिवास राव", " "}, 
{ "Andhra Pradesh",  "3170",  "Rajahmundry", "Kuruvella Bhanu Chandar", "NotGraduate",  " ","आन्ध्र प्रदेश",  "राजमुंदरी", "कुरुवेलला भानु चंदर", " "}, 
{ "Andhra Pradesh",  "3171",  "Rajahmundry", "Nalluri Vijaya Srinivasa Rao", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "राजमुंदरी", "नल्लूरी विजया श्रीनिवास राव", " "}, 
{ "Andhra Pradesh",  "3172",  "Rajahmundry", "Srinivasa Rao Sangisetti", "NotGraduate",  " ","आन्ध्र प्रदेश",  "राजमुंदरी", "श्रीनिवास राव संगीसेटी", " "}, 
{ "Andhra Pradesh",  "3173",  "Rajahmundry", "Paravasthu Satya Gopinath Das", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "राजमुंदरी", "परवस्तु सत्य गोपीनाथ दास", " "}, 
{ "Andhra Pradesh",  "3379",  "Rajampet", "M.Shajahan Basha", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "राजमपेट", "एम। शाहजहां बाशा", " "}, 
{ "Andhra Pradesh",  "3380",  "Rajampet", "Mukram Syed", "NotGraduate",  " ","आन्ध्र प्रदेश",  "राजमपेट", "मुकर्रम सैयद", " "}, 
{ "Andhra Pradesh",  "3381",  "Rajampet", "Asadi Venkatadri", "NotGraduate",  " ","आन्ध्र प्रदेश",  "राजमपेट", "असदी वेंकटाद्रि", " "}, 
{ "Andhra Pradesh",  "3382",  "Rajampet", "Naresh Kumar Poojala", "NotGraduate",  " ","आन्ध्र प्रदेश",  "राजमपेट", "नरेश कुमार पूजला", " "}, 
{ "Andhra Pradesh",  "3383",  "Rajampet", "Khader Valli Shaik", "NotGraduate",  " ","आन्ध्र प्रदेश",  "राजमपेट", "खदर वल्ली शेख", " "}, 
{ "Andhra Pradesh",  "3384",  "Rajampet", "P.V.Midhun Reddy", "CriminalCases",  " ","आन्ध्र प्रदेश",  "राजमपेट", "पीवीमधुन रेड्डी", " "}, 
{ "Andhra Pradesh",  "3385",  "Rajampet", "D.A. Sathya Prabha", "OverAged",  " ","आन्ध्र प्रदेश",  "राजमपेट", "डीए सत्य प्रभा", " "}, 
{ "Andhra Pradesh",  "3091",  "Srikakulam", "Perla Samba Murthy", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "श्रीकाकुलम", "पेरला सांबा मूर्ति", " "}, 
{ "Andhra Pradesh",  "3092",  "Srikakulam", "Namballa Krishna Mohan", "CriminalCases",  " ","आन्ध्र प्रदेश",  "श्रीकाकुलम", "नंबल्ला कृष्ण मोहन", " "}, 
{ "Andhra Pradesh",  "3094",  "Srikakulam", "Srinivas Duvvada", "CriminalCases",  " ","आन्ध्र प्रदेश",  "श्रीकाकुलम", "श्रीनिवास दुव्वादा", " "}, 
{ "Andhra Pradesh",  "3097",  "Srikakulam", "Dola Jagan Mohana Rao", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "श्रीकाकुलम", "डोला जगन मोहन राव", " "}, 
{ "Andhra Pradesh",  "3099",  "Srikakulam", "Rammohannaidu Kinjarapu", "CriminalCases",  " ","आन्ध्र प्रदेश",  "श्रीकाकुलम", "राममोहननिदु किंजरापु", " "}, 
{ "Andhra Pradesh",  "3367",  "Tirupati", "Karra Siva", "NotGraduate",  " ","आन्ध्र प्रदेश",  "तिरुपति", "कर्रा शिव", " "}, 
{ "Andhra Pradesh",  "3368",  "Tirupati", "K.S. Munirathnam", "OverAged",  " ","आन्ध्र प्रदेश",  "तिरुपति", "केएस मुनिरत्नम", " "}, 
{ "Andhra Pradesh",  "3370",  "Tirupati", "Bommi Srihari Rao", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "तिरुपति", "बोम्मी श्रीहरि राव", " "}, 
{ "Andhra Pradesh",  "3374",  "Tirupati", "Chinta Mohan", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "तिरुपति", "चिन्ता मोहन", " "}, 
{ "Andhra Pradesh",  "3375",  "Tirupati", "M. Solomon", "OverAged",  " ","आन्ध्र प्रदेश",  "तिरुपति", "एम। सोलोमन", " "}, 
{ "Andhra Pradesh",  "3211",  "Vijayawada", "Naraharisetty Narasimha Rao", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "विजयवाड़ा", "नरहरिसट्टी नरसिम्हा राव", " "}, 
{ "Andhra Pradesh",  "3212",  "Vijayawada", "Mohammad Ishaq", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विजयवाड़ा", "मोहम्मद इशाक", " "}, 
{ "Andhra Pradesh",  "3213",  "Vijayawada", "Muttamasetty Lakshmana Siva Prasad Babu", "OverAged",  " ","आन्ध्र प्रदेश",  "विजयवाड़ा", "मुत्तमासतेति लक्ष्मणा शिव प्रसाद बाबू", " "}, 
{ "Andhra Pradesh",  "3214",  "Vijayawada", "Anil Kumar Maddineni", "CriminalCases",  " ","आन्ध्र प्रदेश",  "विजयवाड़ा", "अनिल कुमार मद्दीनैनी", " "}, 
{ "Andhra Pradesh",  "3215",  "Vijayawada", "Siva Prasad Padala", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विजयवाड़ा", "शिव प्रसाद पाडला", " "}, 
{ "Andhra Pradesh",  "3216",  "Vijayawada", "Srinivas Kesineni", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विजयवाड़ा", "श्रीनिवास केसिनेनी", " "}, 
{ "Andhra Pradesh",  "3217",  "Vijayawada", "Bolisetty Hari Babu", "CriminalCases",  " ","आन्ध्र प्रदेश",  "विजयवाड़ा", "बोलिस्ति हरि बाबू", " "}, 
{ "Andhra Pradesh",  "3218",  "Vijayawada", "Prasad Veera Potluri", "CriminalCases",  " ","आन्ध्र प्रदेश",  "विजयवाड़ा", "प्रसाद वीरा पोटुलुरी", " "}, 
{ "Andhra Pradesh",  "3219",  "Vijayawada", "Dileep Kilaru", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "विजयवाड़ा", "दिलीप किलरू", " "}, 
{ "Andhra Pradesh",  "3220",  "Vijayawada", "Gandhi Dhanekula", "OverAged",  " ","आन्ध्र प्रदेश",  "विजयवाड़ा", "गांधी धनकुला", " "}, 
{ "Andhra Pradesh",  "3221",  "Vijayawada", "Madabathula Chandra Sekhar", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विजयवाड़ा", "मदबथुला चन्द्रशेखर", " "}, 
{ "Andhra Pradesh",  "3222",  "Vijayawada", "Lurthu Meri Daila", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विजयवाड़ा", "लरतथु मारी डेला", " "}, 
{ "Andhra Pradesh",  "3224",  "Vijayawada", "Riyaz Dada Miya Shaik", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विजयवाड़ा", "रियाज दादा मिया शेख", " "}, 
{ "Andhra Pradesh",  "3114",  "Visakhapatnam", "Gannu Mallayya", "OverAged",  " ","आन्ध्र प्रदेश",  "विशाखापत्तनम", "गन्नू मलैया", " "}, 
{ "Andhra Pradesh",  "3115",  "Visakhapatnam", "Kothapalli Geetha", "CriminalCases",  " ","आन्ध्र प्रदेश",  "विशाखापत्तनम", "कोथपल्ली गीथा", " "}, 
{ "Andhra Pradesh",  "3117",  "Visakhapatnam", "Pedada Ramanikumari", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "विशाखापत्तनम", "पेड़ा रमानीकुमारी", " "}, 
{ "Andhra Pradesh",  "3118",  "Visakhapatnam", "B. Jaya Venu Gopal", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विशाखापत्तनम", "बी जया वेणु गोपाल", " "}, 
{ "Andhra Pradesh",  "3121",  "Visakhapatnam", "R. Udaya Gowri", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विशाखापत्तनम", "आर। उदय गौरी", " "}, 
{ "Andhra Pradesh",  "3122",  "Visakhapatnam", "Gampala Somasundaram", "OverAged",  " ","आन्ध्र प्रदेश",  "विशाखापत्तनम", "गम्पला सोमसुंदरम", " "}, 
{ "Andhra Pradesh",  "3123",  "Visakhapatnam", "M V V Satyanarayana", "CriminalCases",  " ","आन्ध्र प्रदेश",  "विशाखापत्तनम", "एमवीवी सत्यनारायण", " "}, 
{ "Andhra Pradesh",  "3125",  "Visakhapatnam", "Daggubati Purandeswari", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "विशाखापत्तनम", "दग्गुबाती पुरंदेश्वरी", " "}, 
{ "Andhra Pradesh",  "3100",  "Vizianagaram", "Yella Rao Siyyadula", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विजयनगरम", "येला राव सियादुला", " "}, 
{ "Andhra Pradesh",  "3101",  "Vizianagaram", "Adiraju Yedla", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "विजयनगरम", "आदिराजु येदला", " "}, 
{ "Andhra Pradesh",  "3103",  "Vizianagaram", "Ashok Gajapathi Raju Pusapati", "OverAged",  " ","आन्ध्र प्रदेश",  "विजयनगरम", "अशोक गजपति राजू पुष्पति", " "}, 
{ "Andhra Pradesh",  "3104",  "Vizianagaram", "Pentapati Rajesh", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विजयनगरम", "पेंटापति राजेश", " "}, 
{ "Andhra Pradesh",  "3106",  "Vizianagaram", "Kovvuri Surya Bhavani", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विजयनगरम", "कोव्वुरी सूर्य भवानी", " "}, 
{ "Andhra Pradesh",  "3107",  "Vizianagaram", "Lingala Chiranjeevi", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विजयनगरम", "लिंगाला चिरंजीवी", " "}, 
{ "Andhra Pradesh",  "3108",  "Vizianagaram", "Ramu Naidu Yijurothu", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विजयनगरम", "रामू नायडू यिजुरथु", " "}, 
{ "Andhra Pradesh",  "3109",  "Vizianagaram", "Anandsagar Pogru", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विजयनगरम", "अनंदसागर पोगरू", " "}, 
{ "Andhra Pradesh",  "3110",  "Vizianagaram", "Sanyasi Raju Pakalapati", "ForeignFunding",  " ","आन्ध्र प्रदेश",  "विजयनगरम", "सन्यासी राजू पकलपति", " "}, 
{ "Andhra Pradesh",  "3111",  "Vizianagaram", "Bellana Chandra Sekhar", "CriminalCases",  " ","आन्ध्र प्रदेश",  "विजयनगरम", "बेलना चंद्र शेखर", " "}, 
{ "Andhra Pradesh",  "3113",  "Vizianagaram", "Mukka Sreenivasa Rao", "NotGraduate",  " ","आन्ध्र प्रदेश",  "विजयनगरम", "मुक्का श्रीनिवास राव", " "}, 
};

}