/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Andhra_Pradesh {
public static final String[][] green_bucket = {
{"Andhra Pradesh",  "3154", "Amalapuram", "Mortha Sivarama Krishna", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5769",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3160", "Amalapuram", "Ganti Harish Madhur", "TDP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5026",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3161", "Amalapuram", "Rajani Chelle", "Jana Jagruti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5771",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3162", "Amalapuram", "Chinta Anuradha", "YSRCP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5028",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3128", "Anakapalle", "Chintala Partha Sarathi", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6201",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3129", "Anakapalle", "Vadlamuri Krishna Swaroop", "Dalita Bahujana Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4676",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3133", "Anakapalle", "K B Swaroop", "Jana Jagruti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4677",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3134", "Anakapalle", "Dr.Beesetti Venkata Satyavathi", "YSRCP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5018",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3319", "Anantapur", "Viswa Prasad Yadav Sankireddy", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4714",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3320", "Anantapur", "Juturu Chinna Reddy Pavan Reddy", "TDP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4623",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3322", "Anantapur", "Giddama Ranganayakulu", "Vishwa Jana Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6941",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3326", "Anantapur", "G. Lalitha", "SUCI(C)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4806",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3327", "Anantapur", "Padchuri Radha Krishna", "Radical Democrats Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6945",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3082", "Araku", "Swamula Subrahamanyam", "Jana Jagruti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4786",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3086", "Araku", "Goddeti Madhavi", "YSRCP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4784",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3090", "Araku", "Anumula Vamsi Krishna", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6174",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3256", "Bapatla", "Gadde Haribabu", "Navodayam Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6308",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3260", "Bapatla", "China Nageswara Rao Sadhu", "Mundadugu Praja Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6305",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3263", "Bapatla", "Thumati Ravi", "All Peoples Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7207",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3264", "Bapatla", "Gella Nagamalli", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6310",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3265", "Bapatla", "Kanthiraj Devanand", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6306",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3267", "Bapatla", "Golla Baburao", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7206",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3391", "Chittoor", "P. Ramachandran", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6283",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3394", "Chittoor", "Pallipattu. Abhinav Vishnu", "Mundadugu Praja Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4821",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3191", "Eluru", "Sridhar Kotagiri", "YSRCP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4682",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3196", "Eluru", "Josyula China Venkata Suryanarayana", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4620",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3229", "Guntur", "Umar Basha Shaik", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6290",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3233", "Guntur", "Sarabandi Raju Sikhinam", "Indian Labour Party (Ambedkar Phule)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6291",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3234", "Guntur", "Yanamadala Venkata Suresh", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6294",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3235", "Guntur", "Mannava Hariprasad", "CPI(ML) Red Star", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5040",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3237", "Guntur", "Ullagi David Jayakumar", "Hardam Manavtawadi Rashtriya Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6292",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3238", "Guntur", "Doppalapudi Veera Das", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6264",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3241", "Guntur", "Jayadev Galla", "TDP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5037",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3334", "Hindupur", "Gogula Pulakunta Jayanth", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6950",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3335", "Hindupur", "Mugi Surya Prakash", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6953",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3338", "Hindupur", "S.R.Anjaneyulu", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6954",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3341", "Kadapa", "Siva Chandra Reddy Komma", "Anna YSR Congress Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4625",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3343", "Kadapa", "Nyamatulla Shaik", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6956",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3344", "Kadapa", "Ameen Peeran Shaik", "Ambedkar National Congress", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4624",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3349", "Kadapa", "Chadipirala Adi Narayana Reddy", "TDP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4816",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3353", "Kadapa", "Pedakala Varalakshmi", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4815",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3138", "Kakinada", "Godugu Satyanarayana", "CPI(ML)(L)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5023",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3143", "Kakinada", "Donam Neelakantam", "All India Praja Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6209",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3144", "Kakinada", "Sunil Kumar Chalamalasetty", "TDP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5022",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3147", "Kakinada", "Vanga Geetha Viswanatham", "YSRCP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5021",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3152", "Kakinada", "Appalakonda Vangalapudi", "Mundadugu Praja Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6213",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3304", "Kurnool", "S.Md. Shafath", "Rayalaseema Rashtra Samithi", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6939",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3310", "Kurnool", "Dandu Seshu Yadav", "SP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6934",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3311", "Kurnool", "Dr Sanjeev Kumar", "YSRCP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5054",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3313", "Kurnool", "T. Beechupally", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6940",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3316", "Kurnool", "P.V. Srihari", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6938",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3201", "Machilipatnam", "Bandreddi Ramakrishna", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6248",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3205", "Machilipatnam", "Vijaya Lakshmi Chalapaka", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6247",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3208", "Machilipatnam", "Nadakuditi Naga Gayathri", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6250",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3285", "Nandyal", "Elluri Bhupal", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4720",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3289", "Nandyal", "Mandra Sivananda Reddy", "TDP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4805",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3292", "Nandyal", "S. A. Indumathi", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6928",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3294", "Nandyal", "Dr. Lakshmi Kantha Reddy Chitla", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6922",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3246", "Narasaraopet", "Kante Sayanna", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5043",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3247", "Narasaraopet", "Lavu Sri Krishna Devarayalu", "YSRCP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4802",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3249", "Narasaraopet", "Allu Venkata Reddy", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4801",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3250", "Narasaraopet", "Gaddala Venu", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6303",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3175", "Narsapuram", "Nagababu Konidela", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5035",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3176", "Narsapuram", "Nallam Surya Chandra Rao", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6231",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3178", "Narsapuram", "Ganji Purnima", "RPI(A)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6240",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3187", "Narsapuram", "Gottumukkala Shivaji", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6230",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3188", "Narsapuram", "Yella Venugopal Rao", "Nava Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4789",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3357", "Nellore", "Dr. S. Suresh Babu", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6974",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3360", "Nellore", "Beeda Masthan Rao", "TDP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6972",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3366", "Nellore", "Butti Nagaraju", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5057",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3270", "Ongole", "Sidda Raghava Rao", "TDP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4723",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3272", "Ongole", "Maram Srinivasa Reddy", "Praja Shanthi Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6910",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3277", "Ongole", "Madhu Yattapu", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4725",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3278", "Ongole", "Mohan Ayyappa", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6913",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3280", "Ongole", "Bellamkonda Saibabu", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6909",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3281", "Ongole", "Venkatesan Baburao", "India Praja Bandhu Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6914",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3164", "Rajahmundry", "Roopa Rammohan Maganti", "TDP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4679",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3168", "Rajahmundry", "Akula Satyanarayana", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6224",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3386", "Rajampet", "Pasupuleti Venkataramana", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5063",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3387", "Rajampet", "Karimulla Khan Pattan", "Navataram Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6288",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3093", "Srikakulam", "Metta Ramarao", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5009",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3095", "Srikakulam", "Betha Vivekananda Maharaj", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5011",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3096", "Srikakulam", "Matta Satish Chakravarthy", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6179",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3098", "Srikakulam", "Naidugari Rajasekhar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5007",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3369", "Tirupati", "Neeruguttu Nagesh, M.A., Philosophy", "Janapaalana Party (Democratic)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7011",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3371", "Tirupati", "Panabaka Lakshmi", "TDP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4729",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3372", "Tirupati", "Viruvuru Sudhakar", "Vishwa Jana Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7013",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3373", "Tirupati", "Balli Durgaprasad Rao", "YSRCP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5060",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3376", "Tirupati", "B Ramesh", "Viduthalai Chiruthaigal Katchi", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7006",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3377", "Tirupati", "Kattamanchi Prabhakar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5062",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3378", "Tirupati", "Doctor Daggumati Sreehari Rao", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7008",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3210", "Vijayawada", "Nandini Nallaghatla", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6258",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3223", "Vijayawada", "Andukuri Vijaya Bhaskar", "India Praja Bandhu Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6262",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3116", "Visakhapatnam", "Bharat Mathukumilli", "TDP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4675",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3119", "Visakhapatnam", "George Bangari", "Viduthalai Chiruthaigal Katchi", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6191",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3120", "Visakhapatnam", "V.V. Lakshmi Narayana", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5016",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3124", "Visakhapatnam", "Anmish Varma", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6195",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3126", "Visakhapatnam", "Durgaprasad. Guntu", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6194",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3127", "Visakhapatnam", "Pulapaka Raja Sekhar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6197",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3102", "Vizianagaram", "Dhanalakoti Ramana", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6186",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3105", "Vizianagaram", "Venkata Trindha Rao Veluri", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6185",  "",  "", "", "", ""}, 
{"Andhra Pradesh",  "3112", "Vizianagaram", "Govinda Rao Lagudu", "Jana Jagruti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6183",  "",  "", "", "", ""}, 
};

public static final String[][] red_bucket = {
{ "Andhra Pradesh",  "3153",  "Amalapuram", "Manepalli Ayyaji Vema", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3155",  "Amalapuram", "Panthagada Vijaya Chakravarthy", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3156",  "Amalapuram", "Janga Goutham", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3157",  "Amalapuram", "Mojas Raja Sekhar Duggirala", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3158",  "Amalapuram", "Revu Sudhakar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3159",  "Amalapuram", "Muralikrishna Kanderi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3130",  "Anakapalle", "Adari Anand Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3131",  "Anakapalle", "Taadi Veera Jagadeeshwari", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3132",  "Anakapalle", "Dr Gandi Venkata Satyanarayana Rao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3135",  "Anakapalle", "P.S.Ajay Kumar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3136",  "Anakapalle", "Appala Naidu Tummagonta", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3137",  "Anakapalle", "Ruthala Srirama Murthy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3328",  "Anantapur", "Jagadeesh Devaragudi", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3329",  "Anantapur", "Talari Rangaiah", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3330",  "Anantapur", "K Rajiv Reddy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3331",  "Anantapur", "Somanath Deshmukh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3318",  "Anantapur", "Vadde Kasinath", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3321",  "Anantapur", "M.Venkatesulu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3323",  "Anantapur", "Lingutla Rangaiah", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3324",  "Anantapur", "Pothuru Rangaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3325",  "Anantapur", "Hamsa Devineni", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3081",  "Araku", "Vyricherla Kishore Chandra Suryanarayana Deo", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3083",  "Araku", "Dr. Kasi Viswanadha Veera Venkata Satyanarayana Reddy Kosuri", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3084",  "Araku", "Narava Satyavathi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3085",  "Araku", "Kangala Baladora", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3087",  "Araku", "Vampuru Gangulaiah", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3088",  "Araku", "Biddika Ramaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3089",  "Araku", "Shruti Devi Vyricherla", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3257",  "Bapatla", "Challagali Kishore Kumar", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3258",  "Bapatla", "Jesudasu Seelam", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3259",  "Bapatla", "Nuthakki Rama Rao", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3261",  "Bapatla", "Kattepogu Vijay Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3262",  "Bapatla", "Malyadri Sriram", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3266",  "Bapatla", "Suresh Babu Nandigam", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3268",  "Bapatla", "Bussa Nagaraju", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3388",  "Chittoor", "C. Punyamurthy", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3389",  "Chittoor", "Jayaram Duggani", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3390",  "Chittoor", "Cheemala. Rangappa", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3392",  "Chittoor", "N. Reddeppa", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3393",  "Chittoor", "A. Hemanth", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3395",  "Chittoor", "Naramalli Siva Prasad", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3189",  "Eluru", "Gurunadha Rao Jetti", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3190",  "Eluru", "Maganti Venkateswara Rao", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3192",  "Eluru", "Chinnam Rama Kotayya", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3193",  "Eluru", "Mathe Bobby", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3194",  "Eluru", "V Siva Rama Krishna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3195",  "Eluru", "Alaga Ravi Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3197",  "Eluru", "Mendem Santhosh Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3225",  "Guntur", "Araveti Hazarath Rao", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3226",  "Guntur", "Jayaprakash Narayana Valluru", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3227",  "Guntur", "Dasari Kiran Babu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3228",  "Guntur", "Modugula Venugopala Reddy", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3230",  "Guntur", "Samudrala Chinna Kotaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3231",  "Guntur", "Jeldi Raja Mohan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3232",  "Guntur", "Shaik Jaleel", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3236",  "Guntur", "Bonaboyina Srinivasa Rao", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3239",  "Guntur", "Jacob Vidyasagar Nakka", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3240",  "Guntur", "Ramarao Simhadri", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3242",  "Guntur", "Shaik Mastanvali", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3332",  "Hindupur", "S.Ram Mohan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3333",  "Hindupur", "Ramamohan D.G.", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3336",  "Hindupur", "Kuruva Gorantla Madhav", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3337",  "Hindupur", "Mitta Parthasarathi", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3339",  "Hindupur", "N.Kristappa", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3340",  "Hindupur", "K.T.Sreedhar", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3342",  "Kadapa", "Yeduguri Sandinti Avinash Reddy", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3345",  "Kadapa", "Jakku Chenna Krishna Reddy", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3346",  "Kadapa", "Lakshmi Reddy Putha", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3347",  "Kadapa", "Chadipiralla Siva Narayana Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3348",  "Kadapa", "Venu Gopal Rachineni", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3350",  "Kadapa", "Gundlakunta Sreeramulu", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3351",  "Kadapa", "Gujjula Eswaraiah", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3352",  "Kadapa", "Gona Purushottam Reddy", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3354",  "Kadapa", "Sri Rama Chandra Singareddy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3139",  "Kakinada", "Sathi Veera Lakshmi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3140",  "Kakinada", "Ankadi Sathibabu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3141",  "Kakinada", "Mallipudi Sri Ramachandra Murthy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3142",  "Kakinada", "Buddala Geetha Devi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3145",  "Kakinada", "Yalla Venkata Rama Mohana Rao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3146",  "Kakinada", "Medisetti Vijaya Kumar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3148",  "Kakinada", "Peddimsetti Venkateswara Rao", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3149",  "Kakinada", "Kakileti Ravindra", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3150",  "Kakinada", "Jyothula Venkateswara Rao", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3151",  "Kakinada", "Vasamsetty Venakta Ramana", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3302",  "Kurnool", "G Sanjeeva Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3303",  "Kurnool", "B. Shiva Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3305",  "Kurnool", "Abdul Waris", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3306",  "Kurnool", "Kotla Jaya Surya Prakash Reddy", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3307",  "Kurnool", "Kasula Rajasekhar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3308",  "Kurnool", "Devarapogu Maddilety", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3309",  "Kurnool", "Kommireddy Prabhakar Reddy", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3312",  "Kurnool", "Hatcholi Thomas", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3314",  "Kurnool", "M. Naganna", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3315",  "Kurnool", "Ahmed Ali Khan", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3317",  "Kurnool", "P.V. Parthasarathi", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3198",  "Machilipatnam", "Gollu Krishna", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3199",  "Machilipatnam", "Balashowry Vallabhaneni", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3200",  "Machilipatnam", "Gudivaka Venkata Naga Basava Rao", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3202",  "Machilipatnam", "Konakalla Narayana Rao", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3203",  "Machilipatnam", "Peram Siva Nageswara Rao", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3204",  "Machilipatnam", "Gudivaka Ramanjaneyulu", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3206",  "Machilipatnam", "Valluru Venkateswara Rao", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3207",  "Machilipatnam", "Gandhi Dhanekula", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3209",  "Machilipatnam", "Yarlagadda Rama Mohana Rao", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3282",  "Nandyal", "C. Surendra Nath Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3283",  "Nandyal", "Jestadi Sudhakar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3284",  "Nandyal", "Ruddireddy Radhakrishna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3286",  "Nandyal", "Poluru Guruvaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3287",  "Nandyal", "Vangala Parameswara Reddy.", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3288",  "Nandyal", "Bhuma Kishor Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3290",  "Nandyal", "D. Mahammad Rafi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3291",  "Nandyal", "K.P. Kambagiriswamy", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3293",  "Nandyal", "D. P. Jamal Basha", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3295",  "Nandyal", "B.C. Ramanatha Reddy", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3296",  "Nandyal", "Pula. Nagamaddilety", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3297",  "Nandyal", "S.P.Y. Reddy", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3298",  "Nandyal", "Adinarayana Inty", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3299",  "Nandyal", "Lakshmi Narasaiah Jangiti", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3300",  "Nandyal", "I.V. Pakkir Reddy", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3301",  "Nandyal", "Pocha Brahmananda Reddy", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3243",  "Narasaraopet", "Reddyboina Prasanna Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3244",  "Narasaraopet", "Rayapati Sambasiva Rao", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3245",  "Narasaraopet", "Durgampudi Rami Reddy", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3248",  "Narasaraopet", "Kanakam Srinivasarao", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3251",  "Narasaraopet", "Surabhi Devasahayam", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3252",  "Narasaraopet", "Pakkala Suribabu", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3253",  "Narasaraopet", "Narasimharao Parimi", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3254",  "Narasaraopet", "Kanna Lakshmi Narayana", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3255",  "Narasaraopet", "Shaik Nayub Kamal", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3174",  "Narsapuram", "Kanumuru Raghu Rama Krishna Raju", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3177",  "Narsapuram", "Medapati Varahala Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3179",  "Narsapuram", "Dasari Krishna Murthy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3180",  "Narsapuram", "Nalli Rajesh", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3181",  "Narsapuram", "Pydikondala Manikyala Rao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3182",  "Narsapuram", "Venkata Sivarama Raju Vetukuri", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3183",  "Narsapuram", "Kanumuru Bapiraju", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3184",  "Narsapuram", "K.A.Paul", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3185",  "Narsapuram", "G S Raju", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3186",  "Narsapuram", "Gurugubilli Rambabu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3355",  "Nellore", "Sannapureddy Suresh Reddy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3356",  "Nellore", "Narasapuram Prasad", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3358",  "Nellore", "Chandra Rajagopal", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3359",  "Nellore", "Chevuru Devakumar Reddy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3361",  "Nellore", "Chinni Venkateswarlu", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3362",  "Nellore", "Meda Malla Reddy", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3363",  "Nellore", "Kankanala Penchala Naidu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3364",  "Nellore", "Adala Prabhakara Reddy", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3365",  "Nellore", "Shaik Mahaboob Basha (Mabu)", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3269",  "Ongole", "Konda Praveen Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3271",  "Ongole", "Venkatesh Vepuri", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3273",  "Ongole", "Dr Sirivella Prasad", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3274",  "Ongole", "Billa Chennaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3275",  "Ongole", "Thoganti Sreenivasulu", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3276",  "Ongole", "Magunta Sreenivasulu Reddy", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3279",  "Ongole", "Kavuri Venu Babu Naidu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3163",  "Rajahmundry", "Venu Kollapu", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3165",  "Rajahmundry", "Margani Bharat Ram", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3166",  "Rajahmundry", "Geddam David Nelson Babu", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3167",  "Rajahmundry", "Bandaru Rajeswara Rao", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3169",  "Rajahmundry", "Meda Srinivasa Rao", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3170",  "Rajahmundry", "Kuruvella Bhanu Chandar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3171",  "Rajahmundry", "Nalluri Vijaya Srinivasa Rao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3172",  "Rajahmundry", "Srinivasa Rao Sangisetti", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3173",  "Rajahmundry", "Paravasthu Satya Gopinath Das", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3379",  "Rajampet", "M.Shajahan Basha", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3380",  "Rajampet", "Mukram Syed", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3381",  "Rajampet", "Asadi Venkatadri", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3382",  "Rajampet", "Naresh Kumar Poojala", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3383",  "Rajampet", "Khader Valli Shaik", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3384",  "Rajampet", "P.V.Midhun Reddy", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3385",  "Rajampet", "D.A. Sathya Prabha", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3091",  "Srikakulam", "Perla Samba Murthy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3092",  "Srikakulam", "Namballa Krishna Mohan", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3094",  "Srikakulam", "Srinivas Duvvada", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3097",  "Srikakulam", "Dola Jagan Mohana Rao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3099",  "Srikakulam", "Rammohannaidu Kinjarapu", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3367",  "Tirupati", "Karra Siva", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3368",  "Tirupati", "K.S. Munirathnam", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3370",  "Tirupati", "Bommi Srihari Rao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3374",  "Tirupati", "Chinta Mohan", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3375",  "Tirupati", "M. Solomon", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3211",  "Vijayawada", "Naraharisetty Narasimha Rao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3212",  "Vijayawada", "Mohammad Ishaq", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3213",  "Vijayawada", "Muttamasetty Lakshmana Siva Prasad Babu", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3214",  "Vijayawada", "Anil Kumar Maddineni", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3215",  "Vijayawada", "Siva Prasad Padala", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3216",  "Vijayawada", "Srinivas Kesineni", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3217",  "Vijayawada", "Bolisetty Hari Babu", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3218",  "Vijayawada", "Prasad Veera Potluri", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3219",  "Vijayawada", "Dileep Kilaru", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3220",  "Vijayawada", "Gandhi Dhanekula", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3221",  "Vijayawada", "Madabathula Chandra Sekhar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3222",  "Vijayawada", "Lurthu Meri Daila", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3224",  "Vijayawada", "Riyaz Dada Miya Shaik", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3114",  "Visakhapatnam", "Gannu Mallayya", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3115",  "Visakhapatnam", "Kothapalli Geetha", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3117",  "Visakhapatnam", "Pedada Ramanikumari", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3118",  "Visakhapatnam", "B. Jaya Venu Gopal", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3121",  "Visakhapatnam", "R. Udaya Gowri", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3122",  "Visakhapatnam", "Gampala Somasundaram", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3123",  "Visakhapatnam", "M V V Satyanarayana", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3125",  "Visakhapatnam", "Daggubati Purandeswari", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3100",  "Vizianagaram", "Yella Rao Siyyadula", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3101",  "Vizianagaram", "Adiraju Yedla", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3103",  "Vizianagaram", "Ashok Gajapathi Raju Pusapati", "OverAged",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3104",  "Vizianagaram", "Pentapati Rajesh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3106",  "Vizianagaram", "Kovvuri Surya Bhavani", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3107",  "Vizianagaram", "Lingala Chiranjeevi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3108",  "Vizianagaram", "Ramu Naidu Yijurothu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3109",  "Vizianagaram", "Anandsagar Pogru", "NotGraduate",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3110",  "Vizianagaram", "Sanyasi Raju Pakalapati", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3111",  "Vizianagaram", "Bellana Chandra Sekhar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Andhra Pradesh",  "3113",  "Vizianagaram", "Mukka Sreenivasa Rao", "NotGraduate",  " ","",  "", "", " "}, 
};

}