/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Andhra_Pradesh {
public static final String[][] green_bucket = {
        {"Andhra Pradesh", "Amalapuram", "Mortha Sivarama Krishna", "Pyramid Party of India", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5769", "आन्ध्र प्रदेश", "अमलापुरम", "मर्तव शिवराम कृष्ण", "पिरामिड पार्टी ऑफ इंडिया"},
        {"Andhra Pradesh", "Amalapuram", "Ganti Harish Madhur", "Telugu Desam Party", "7.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5026", "आन्ध्र प्रदेश", "अमलापुरम", "गँती हरीश मधुर", "तेलुगु देशम पार्टी"},
        {"Andhra Pradesh", "Amalapuram", "Rajani Chelle", "Jana Jagruti Party", "2.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5771", "आन्ध्र प्रदेश", "अमलापुरम", "रजनी चेल्ले", "जन जागृति पार्टी"},
        {"Andhra Pradesh", "Amalapuram", "Chinta Anuradha", "YSR Congress Party", "8.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5028", "आन्ध्र प्रदेश", "अमलापुरम", "चिन्ता अनुराधा", "वाईएसआर कांग्रेस पार्टी"},
        {"Andhra Pradesh", "Anakapalle", "Chintala Partha Sarathi", "Janasena Party", "33.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6201", "आन्ध्र प्रदेश", "अनकापल्ली", "चिन्तला पार्थ सारथी", "जनसेना पार्टी"},
        {"Andhra Pradesh", "Anakapalle", "Vadlamuri Krishna Swaroop", "Dalita Bahujana Party", "16500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4676", "आन्ध्र प्रदेश", "अनकापल्ली", "वडलामुरी कृष्ण स्वरूप", "दलिता बहुजन पार्टी"},
        {"Andhra Pradesh", "Anakapalle", "K B Swaroop", "Jana Jagruti Party", "2.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4677", "आन्ध्र प्रदेश", "अनकापल्ली", "केबी स्वरूप", "जन जागृति पार्टी"},
        {"Andhra Pradesh", "Anakapalle", "Dr.Beesetti Venkata Satyavathi", "YSR Congress Party", "9.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5018", "आन्ध्र प्रदेश", "अनकापल्ली", "डॉ। बिसेती वेंकट सत्यवती", "वाईएसआर कांग्रेस पार्टी"},
        {"Andhra Pradesh", "Anantapur", "Viswa Prasad Yadav Sankireddy", "Independent", "41.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4714", "आन्ध्र प्रदेश", "अनंतपुर", "विश्व प्रसाद यादव सांकड़ेड्डी", "निर्दलीय"},
        {"Andhra Pradesh", "Anantapur", "Juturu Chinna Reddy Pavan Reddy", "Telugu Desam Party", "37.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4623", "आन्ध्र प्रदेश", "अनंतपुर", "जटुरु चिन्ना रेड्डी पावन रेड्डी", "तेलुगु देशम पार्टी"},
        {"Andhra Pradesh", "Anantapur", "Giddama Ranganayakulu", "Vishwa Jana Party", "6.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6941", "आन्ध्र प्रदेश", "अनंतपुर", "गिडामा रंगनायकुलु", "विश्व जन पार्टी"},
        {"Andhra Pradesh", "Anantapur", "G. Lalitha", "Socialist Unity Centre of India (Communist)", "12.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4806", "आन्ध्र प्रदेश", "अनंतपुर", "जी। ललिता", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Andhra Pradesh", "Anantapur", "Padchuri Radha Krishna", "Radical Democrats Party", "10.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6945", "आन्ध्र प्रदेश", "अनंतपुर", "पद्चुरी राधा कृष्ण", "कट्टरपंथी डेमोक्रेट पार्टी"},
        {"Andhra Pradesh", "Araku", "Swamula Subrahamanyam", "Jana Jagruti Party", "21Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4786", "आन्ध्र प्रदेश", "अरकू", "स्वमुला सुब्रह्मण्यम", "जन जागृति पार्टी"},
        {"Andhra Pradesh", "Araku", "Goddeti Madhavi", "YSR Congress Party", "1.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4784", "आन्ध्र प्रदेश", "अरकू", "देवी माधवी", "वाईएसआर कांग्रेस पार्टी"},
        {"Andhra Pradesh", "Araku", "Anumula Vamsi Krishna", "Independent", "50000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6174", "आन्ध्र प्रदेश", "अरकू", "अनामुला वामसी कृष्ण", "निर्दलीय"},
        {"Andhra Pradesh", "Bapatla", "Gadde Haribabu", "Navodayam Party", "20000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6308", "आन्ध्र प्रदेश", "बापतला", "गद्दे हरिबाबू", "नवोदय पार्टी"},
        {"Andhra Pradesh", "Bapatla", "China Nageswara Rao Sadhu", "Mundadugu Praja Party", "12.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6305", "आन्ध्र प्रदेश", "बापतला", "चीन नागेश्वर राव साधु", "मुंडदुगु प्रजा पार्टी"},
        {"Andhra Pradesh", "Bapatla", "Thumati Ravi", "All Peoples Party", "34.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7207", "आन्ध्र प्रदेश", "बापतला", "ठुमती रवि", "ऑल पीपुल्स पार्टी"},
        {"Andhra Pradesh", "Bapatla", "Gella Nagamalli", "Independent", "4.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6310", "आन्ध्र प्रदेश", "बापतला", "गेला नागामल्ली", "निर्दलीय"},
        {"Andhra Pradesh", "Bapatla", "Kanthiraj Devanand", "Bahujan Samaj Party", "3.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6306", "आन्ध्र प्रदेश", "बापतला", "कांतिराज देवानंद", "बहुजन समाज पार्टी"},
        {"Andhra Pradesh", "Bapatla", "Golla Baburao", "Independent", "78000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7206", "आन्ध्र प्रदेश", "बापतला", "गोल्ला बाबूराव", "निर्दलीय"},
        {"Andhra Pradesh", "Chittoor", "P. Ramachandran", "Independent", "35.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6283", "आन्ध्र प्रदेश", "चित्तूर", "पी। रामचंद्रन", "निर्दलीय"},
        {"Andhra Pradesh", "Chittoor", "Pallipattu. Abhinav Vishnu", "Mundadugu Praja Party", "92600", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4821", "आन्ध्र प्रदेश", "चित्तूर", "Pallipattu। अभिनव विष्णु", "मुंडदुगु प्रजा पार्टी"},
        {"Andhra Pradesh", "Eluru", "Sridhar Kotagiri", "YSR Congress Party", "46.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4682", "आन्ध्र प्रदेश", "एलुरु", "श्रीधर कोटागिरी", "वाईएसआर कांग्रेस पार्टी"},
        {"Andhra Pradesh", "Eluru", "Josyula China Venkata Suryanarayana", "Pyramid Party of India", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4620", "आन्ध्र प्रदेश", "एलुरु", "जोसियुला चीन वेंकट सूर्यनारायण", "पिरामिड पार्टी ऑफ इंडिया"},
        {"Andhra Pradesh", "Guntur", "Umar Basha Shaik", "Independent", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6290", "आन्ध्र प्रदेश", "गुंटूर", "उमर बाशा शैक", "निर्दलीय"},
        {"Andhra Pradesh", "Guntur", "Sarabandi Raju Sikhinam", "Indian Labour Party (Ambedkar Phule)", "30000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6291", "आन्ध्र प्रदेश", "गुंटूर", "सरबंदी राजू सिखिनम", "भारतीय मजदूर पार्टी (अम्बेडकर फुले)"},
        {"Andhra Pradesh", "Guntur", "Yanamadala Venkata Suresh", "Independent", "13Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6294", "आन्ध्र प्रदेश", "गुंटूर", "यनामदला वेंकट सुरेश", "निर्दलीय"},
        {"Andhra Pradesh", "Guntur", "Mannava Hariprasad", "Communist Party of India (Marxist–Leninist) Red Star", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5040", "आन्ध्र प्रदेश", "गुंटूर", "मानवा हरिप्रसाद", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) रेड स्टार"},
        {"Andhra Pradesh", "Guntur", "Ullagi David Jayakumar", "Hardam Manavtawadi Rashtriya Dal", "1.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6292", "आन्ध्र प्रदेश", "गुंटूर", "उल्लागी डेविड जयकुमार", "हरदम मानवतवादी राष्ट्रीय दल"},
        {"Andhra Pradesh", "Guntur", "Doppalapudi Veera Das", "Independent", "59.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6264", "आन्ध्र प्रदेश", "गुंटूर", "डोपलापुडी वीरा दास", "निर्दलीय"},
        {"Andhra Pradesh", "Guntur", "Jayadev Galla", "Telugu Desam Party", "305.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5037", "आन्ध्र प्रदेश", "गुंटूर", "जयदेव गल्ला", "तेलुगु देशम पार्टी"},
        {"Andhra Pradesh", "Hindupur", "Gogula Pulakunta Jayanth", "Independent", "32Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6950", "आन्ध्र प्रदेश", "हिन्दुपुर", "गोगुला पुलकुंता जयंत", "निर्दलीय"},
        {"Andhra Pradesh", "Hindupur", "Mugi Surya Prakash", "Independent", "4.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6953", "आन्ध्र प्रदेश", "हिन्दुपुर", "मुगी सूर्य प्रकाश", "निर्दलीय"},
        {"Andhra Pradesh", "Hindupur", "S.R.Anjaneyulu", "Independent", "43000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6954", "आन्ध्र प्रदेश", "हिन्दुपुर", "SRAnjaneyulu", "निर्दलीय"},
        {"Andhra Pradesh", "Kadapa", "Siva Chandra Reddy Komma", "Anna YSR Congress Party", "51.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4625", "आन्ध्र प्रदेश", "कडपा", "शिव चंद्र रेड्डी कोमा", "अन्ना वाईएसआर कांग्रेस पार्टी"},
        {"Andhra Pradesh", "Kadapa", "Nyamatulla Shaik", "Independent", "49.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6956", "आन्ध्र प्रदेश", "कडपा", "न्यामतुल्ला शिक", "निर्दलीय"},
        {"Andhra Pradesh", "Kadapa", "Ameen Peeran Shaik", "Ambedkar National Congress", "83993", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4624", "आन्ध्र प्रदेश", "कडपा", "अमीन पीरन शैक", "अंबेडकर राष्ट्रीय कांग्रेस"},
        {"Andhra Pradesh", "Kadapa", "Chadipirala Adi Narayana Reddy", "Telugu Desam Party", "3.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4816", "आन्ध्र प्रदेश", "कडपा", "चादीपिरला आदि नारायण रेड्डी", "तेलुगु देशम पार्टी"},
        {"Andhra Pradesh", "Kadapa", "Pedakala Varalakshmi", "Pyramid Party of India", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4815", "आन्ध्र प्रदेश", "कडपा", "पेदाकाला वरलक्ष्मी", "पिरामिड पार्टी ऑफ इंडिया"},
        {"Andhra Pradesh", "Kakinada", "Godugu Satyanarayana", "Communist Party of India (Marxist–Leninist) Liberation", "28000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5023", "आन्ध्र प्रदेश", "काकीनाडा", "गोडुगु सत्यनारायण", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) मुक्ति"},
        {"Andhra Pradesh", "Kakinada", "Donam Neelakantam", "All India Praja Party", "14.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6209", "आन्ध्र प्रदेश", "काकीनाडा", "डोनम नीलकांतम", "अखिल भारतीय प्रजा पार्टी"},
        {"Andhra Pradesh", "Kakinada", "Sunil Kumar Chalamalasetty", "Telugu Desam Party", "25.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5022", "आन्ध्र प्रदेश", "काकीनाडा", "सुनील कुमार चलमलासट्टी", "तेलुगु देशम पार्टी"},
        {"Andhra Pradesh", "Kakinada", "Vanga Geetha Viswanatham", "YSR Congress Party", "20.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5021", "आन्ध्र प्रदेश", "काकीनाडा", "वंगा गीता विश्वनाथम्", "वाईएसआर कांग्रेस पार्टी"},
        {"Andhra Pradesh", "Kakinada", "Appalakonda Vangalapudi", "Mundadugu Praja Party", "5.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6213", "आन्ध्र प्रदेश", "काकीनाडा", "अपलाकोंडा वंगलपुडी", "मुंडदुगु प्रजा पार्टी"},
        {"Andhra Pradesh", "Kurnool", "S.Md. Shafath", "Rayalaseema Rashtra Samithi", "50Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6939", "आन्ध्र प्रदेश", "कुरनूल", "S.Md. Shafath", "रायलसीमा राष्ट्र समिति"},
        {"Andhra Pradesh", "Kurnool", "Dandu Seshu Yadav", "Samajwadi Party", "19.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6934", "आन्ध्र प्रदेश", "कुरनूल", "दंडू शेष यादव", "समाजवादी पार्टी"},
        {"Andhra Pradesh", "Kurnool", "Dr Sanjeev Kumar", "YSR Congress Party", "32.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5054", "आन्ध्र प्रदेश", "कुरनूल", "डॉ संजीव कुमार", "वाईएसआर कांग्रेस पार्टी"},
        {"Andhra Pradesh", "Kurnool", "T. Beechupally", "Independent", "1.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6940", "आन्ध्र प्रदेश", "कुरनूल", "टी। बिचुपल्ली", "निर्दलीय"},
        {"Andhra Pradesh", "Kurnool", "P.V. Srihari", "Independent", "2.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6938", "आन्ध्र प्रदेश", "कुरनूल", "पीवी श्रीहरि", "निर्दलीय"},
        {"Andhra Pradesh", "Machilipatnam", "Bandreddi Ramakrishna", "Janasena Party", "10.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6248", "आन्ध्र प्रदेश", "मछलीपट्टनम", "बंदेर्धारी रामकृष्ण", "जनसेना पार्टी"},
        {"Andhra Pradesh", "Machilipatnam", "Vijaya Lakshmi Chalapaka", "Independent", "12.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6247", "आन्ध्र प्रदेश", "मछलीपट्टनम", "विजया लक्ष्मी चलपका", "निर्दलीय"},
        {"Andhra Pradesh", "Machilipatnam", "Nadakuditi Naga Gayathri", "Independent", "89.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6250", "आन्ध्र प्रदेश", "मछलीपट्टनम", "नादकुदिति नागा गायत्री", "निर्दलीय"},
        {"Andhra Pradesh", "Nandyal", "Elluri Bhupal", "Independent", "20000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4720", "आन्ध्र प्रदेश", "नांदयाल", "एलुरी भूपल", "निर्दलीय"},
        {"Andhra Pradesh", "Nandyal", "Mandra Sivananda Reddy", "Telugu Desam Party", "34.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4805", "आन्ध्र प्रदेश", "नांदयाल", "मंद्रा शिवानंद रेड्डी", "तेलुगु देशम पार्टी"},
        {"Andhra Pradesh", "Nandyal", "S. A. Indumathi", "Independent", "19.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6928", "आन्ध्र प्रदेश", "नांदयाल", "एसए इंदुमति", "निर्दलीय"},
        {"Andhra Pradesh", "Nandyal", "Dr. Lakshmi Kantha Reddy Chitla", "Independent", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6922", "आन्ध्र प्रदेश", "नांदयाल", "डॉ। लक्ष्मी कांथा रेड्डी चितला", "निर्दलीय"},
        {"Andhra Pradesh", "Narasaraopet", "Kante Sayanna", "Independent", "22.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5043", "आन्ध्र प्रदेश", "नरसरोपेट", "कांटे स्याना", "निर्दलीय"},
        {"Andhra Pradesh", "Narasaraopet", "Lavu Sri Krishna Devarayalu", "YSR Congress Party", "17.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4802", "आन्ध्र प्रदेश", "नरसरोपेट", "लावु श्री कृष्ण देवरयालु", "वाईएसआर कांग्रेस पार्टी"},
        {"Andhra Pradesh", "Narasaraopet", "Allu Venkata Reddy", "Pyramid Party of India", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4801", "आन्ध्र प्रदेश", "नरसरोपेट", "अल्लू वेंकट रेड्डी", "पिरामिड पार्टी ऑफ इंडिया"},
        {"Andhra Pradesh", "Narasaraopet", "Gaddala Venu", "Independent", "15000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6303", "आन्ध्र प्रदेश", "नरसरोपेट", "गद्दाला वेणु", "निर्दलीय"},
        {"Andhra Pradesh", "Narsapuram", "Nagababu Konidela", "Janasena Party", "36.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5035", "आन्ध्र प्रदेश", "नरसापुरम", "नागबाबू कोनिदेला", "जनसेना पार्टी"},
        {"Andhra Pradesh", "Narsapuram", "Nallam Surya Chandra Rao", "Pyramid Party of India", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6231", "आन्ध्र प्रदेश", "नरसापुरम", "नालम सूर्य चंद्र राव", "पिरामिड पार्टी ऑफ इंडिया"},
        {"Andhra Pradesh", "Narsapuram", "Ganji Purnima", "Republican Party of India (Athawale)", "99000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6240", "आन्ध्र प्रदेश", "नरसापुरम", "गंजी पूर्णिमा", "भारतीय रिपब्लिकन पार्टी (अठावले)"},
        {"Andhra Pradesh", "Narsapuram", "Gottumukkala Shivaji", "Independent", "80.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6230", "आन्ध्र प्रदेश", "नरसापुरम", "गोतमुक्कल शिवाजी", "निर्दलीय"},
        {"Andhra Pradesh", "Narsapuram", "Yella Venugopal Rao", "Nava Samaj Party", "10Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4789", "आन्ध्र प्रदेश", "नरसापुरम", "येला वेणुगोपाल राव", "नव समाज पार्टी"},
        {"Andhra Pradesh", "Nellore", "Dr. S. Suresh Babu", "Independent", "95.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6974", "आन्ध्र प्रदेश", "नेल्लोर", "डॉ। एस सुरेश बाबू", "निर्दलीय"},
        {"Andhra Pradesh", "Nellore", "Beeda Masthan Rao", "Telugu Desam Party", "165.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6972", "आन्ध्र प्रदेश", "नेल्लोर", "बीदा मस्तान राव", "तेलुगु देशम पार्टी"},
        {"Andhra Pradesh", "Nellore", "Butti Nagaraju", "Independent", "94.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5057", "आन्ध्र प्रदेश", "नेल्लोर", "बुटी नागराजू", "निर्दलीय"},
        {"Andhra Pradesh", "Ongole", "Sidda Raghava Rao", "Telugu Desam Party", "91.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4723", "आन्ध्र प्रदेश", "ओंगोल", "सिद्ध राघव राव", "तेलुगु देशम पार्टी"},
        {"Andhra Pradesh", "Ongole", "Maram Srinivasa Reddy", "Praja Shanthi Party", "52197", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6910", "आन्ध्र प्रदेश", "ओंगोल", "मरम श्रीनिवास रेड्डी", "प्रजा शांति पार्टी"},
        {"Andhra Pradesh", "Ongole", "Madhu Yattapu", "Independent", "28Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4725", "आन्ध्र प्रदेश", "ओंगोल", "मधु यतापु", "निर्दलीय"},
        {"Andhra Pradesh", "Ongole", "Mohan Ayyappa", "Independent", "1.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6913", "आन्ध्र प्रदेश", "ओंगोल", "मोहन अयप्पा", "निर्दलीय"},
        {"Andhra Pradesh", "Ongole", "Bellamkonda Saibabu", "Janasena Party", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6909", "आन्ध्र प्रदेश", "ओंगोल", "बेलमकोंडा साईंबु", "जनसेना पार्टी"},
        {"Andhra Pradesh", "Ongole", "Venkatesan Baburao", "India Praja Bandhu Party", "8.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6914", "आन्ध्र प्रदेश", "ओंगोल", "वेंकटेशन बाबूराव", "भारत प्रजा बंधु पार्टी"},
        {"Andhra Pradesh", "Rajahmundry", "Roopa Rammohan Maganti", "Telugu Desam Party", "43.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4679", "आन्ध्र प्रदेश", "राजमुंदरी", "रूप राममोहन मगंति", "तेलुगु देशम पार्टी"},
        {"Andhra Pradesh", "Rajahmundry", "Akula Satyanarayana", "Janasena Party", "67.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6224", "आन्ध्र प्रदेश", "राजमुंदरी", "अकुला सत्यानारायण", "जनसेना पार्टी"},
        {"Andhra Pradesh", "Rajampet", "Pasupuleti Venkataramana", "Independent", "6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5063", "आन्ध्र प्रदेश", "राजमपेट", "पसुपुलेटि वेंकटरामण", "निर्दलीय"},
        {"Andhra Pradesh", "Rajampet", "Karimulla Khan Pattan", "Navataram Party", "16.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6288", "आन्ध्र प्रदेश", "राजमपेट", "करीमुल्ला खान पट्टन", "नवताराम पार्टी"},
        {"Andhra Pradesh", "Srikakulam", "Metta Ramarao", "Janasena Party", "6.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5009", "आन्ध्र प्रदेश", "श्रीकाकुलम", "मेटता रामाराव", "जनसेना पार्टी"},
        {"Andhra Pradesh", "Srikakulam", "Betha Vivekananda Maharaj", "Independent", "1.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5011", "आन्ध्र प्रदेश", "श्रीकाकुलम", "बैथा विवेकानंद महाराज", "निर्दलीय"},
        {"Andhra Pradesh", "Srikakulam", "Matta Satish Chakravarthy", "Pyramid Party of India", "14.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6179", "आन्ध्र प्रदेश", "श्रीकाकुलम", "मटका सतीश चक्रवर्ती", "पिरामिड पार्टी ऑफ इंडिया"},
        {"Andhra Pradesh", "Srikakulam", "Naidugari Rajasekhar", "Independent", "41500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5007", "आन्ध्र प्रदेश", "श्रीकाकुलम", "नादुगारी राजशेखर", "निर्दलीय"},
        {"Andhra Pradesh", "Tirupati", "Neeruguttu Nagesh, M.A., Philosophy", "Janapaalana Party (Democratic)", "13.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7011", "आन्ध्र प्रदेश", "तिरुपति", "नीरूगुट्टू नागेश, एमए, दर्शनशास्त्र", "जनपालन पार्टी (लोकतांत्रिक)"},
        {"Andhra Pradesh", "Tirupati", "Panabaka Lakshmi", "Telugu Desam Party", "9.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4729", "आन्ध्र प्रदेश", "तिरुपति", "पनाबका लक्ष्मी", "तेलुगु देशम पार्टी"},
        {"Andhra Pradesh", "Tirupati", "Viruvuru Sudhakar", "Vishwa Jana Party", "11.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7013", "आन्ध्र प्रदेश", "तिरुपति", "विरुवरु सुधाकर", "विश्व जन पार्टी"},
        {"Andhra Pradesh", "Tirupati", "Balli Durgaprasad Rao", "YSR Congress Party", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5060", "आन्ध्र प्रदेश", "तिरुपति", "बल्ली दुर्गाप्रसाद राव", "वाईएसआर कांग्रेस पार्टी"},
        {"Andhra Pradesh", "Tirupati", "B Ramesh", "Viduthalai Chiruthaigal Katchi", "21.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7006", "आन्ध्र प्रदेश", "तिरुपति", "B रमेश", "विदुथलाई चिरुथिगाल काची"},
        {"Andhra Pradesh", "Tirupati", "Kattamanchi Prabhakar", "Independent", "3.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5062", "आन्ध्र प्रदेश", "तिरुपति", "कट्टमंचि प्रभाकर", "निर्दलीय"},
        {"Andhra Pradesh", "Tirupati", "Doctor Daggumati Sreehari Rao", "Bahujan Samaj Party", "60.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7008", "आन्ध्र प्रदेश", "तिरुपति", "डॉक्टर दग्गुमती श्रीहरि राव", "बहुजन समाज पार्टी"},
        {"Andhra Pradesh", "Vijayawada", "Nandini Nallaghatla", "Independent", "5.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6258", "आन्ध्र प्रदेश", "विजयवाड़ा", "नंदिनी नल्लाघाटला", "निर्दलीय"},
        {"Andhra Pradesh", "Vijayawada", "Andukuri Vijaya Bhaskar", "India Praja Bandhu Party", "5000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6262", "आन्ध्र प्रदेश", "विजयवाड़ा", "अंदुकुरी विजया भास्कर", "भारत प्रजा बंधु पार्टी"},
        {"Andhra Pradesh", "Visakhapatnam", "Bharat Mathukumilli", "Telugu Desam Party", "232.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4675", "आन्ध्र प्रदेश", "विशाखापत्तनम", "भरत मथुकुमिलि", "तेलुगु देशम पार्टी"},
        {"Andhra Pradesh", "Visakhapatnam", "George Bangari", "Viduthalai Chiruthaigal Katchi", "12Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6191", "आन्ध्र प्रदेश", "विशाखापत्तनम", "जॉर्ज बंगारी", "विदुथलाई चिरुथिगाल काची"},
        {"Andhra Pradesh", "Visakhapatnam", "V.V. Lakshmi Narayana", "Janasena Party", "8.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5016", "आन्ध्र प्रदेश", "विशाखापत्तनम", "वीवी लक्ष्मी नारायण", "जनसेना पार्टी"},
        {"Andhra Pradesh", "Visakhapatnam", "Anmish Varma", "Independent", "75000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6195", "आन्ध्र प्रदेश", "विशाखापत्तनम", "अनमिश वर्मा", "निर्दलीय"},
        {"Andhra Pradesh", "Visakhapatnam", "Durgaprasad. Guntu", "Independent", "38Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6194", "आन्ध्र प्रदेश", "विशाखापत्तनम", "दुर्गाप्रसाद। Guntu", "निर्दलीय"},
        {"Andhra Pradesh", "Visakhapatnam", "Pulapaka Raja Sekhar", "Independent", "67295", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6197", "आन्ध्र प्रदेश", "विशाखापत्तनम", "पुलकक राजा शेखर", "निर्दलीय"},
        {"Andhra Pradesh", "Vizianagaram", "Dhanalakoti Ramana", "Independent", "8.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6186", "आन्ध्र प्रदेश", "विजयनगरम", "धनलकोटी रमना", "निर्दलीय"},
        {"Andhra Pradesh", "Vizianagaram", "Venkata Trindha Rao Veluri", "Independent", "94198", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6185", "आन्ध्र प्रदेश", "विजयनगरम", "वेंकट त्रिधा राव वेलुरी", "निर्दलीय"},
        {"Andhra Pradesh", "Vizianagaram", "Govinda Rao Lagudu", "Jana Jagruti Party", "2.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6183", "आन्ध्र प्रदेश", "विजयनगरम", "गोविंदा राव लगुडू", "जन जागृति पार्टी"},
};

public static final String[][] red_bucket = {
        {"Andhra Pradesh", "Amalapuram", "Manepalli Ayyaji Vema", "1", " ", "आन्ध्र प्रदेश", "अमलापुरम", "मनपल्ली अय्याजी वेमा", " "},
        {"Andhra Pradesh", "Amalapuram", "Panthagada Vijaya Chakravarthy", "3", " ", "आन्ध्र प्रदेश", "अमलापुरम", "पंथगदा विजया चक्रवर्ती", " "},
        {"Andhra Pradesh", "Amalapuram", "Janga Goutham", "1", " ", "आन्ध्र प्रदेश", "अमलापुरम", "जंगा गौतम", " "},
        {"Andhra Pradesh", "Amalapuram", "Mojas Raja Sekhar Duggirala", "2", " ", "आन्ध्र प्रदेश", "अमलापुरम", "मोजज राजा शेखर दुग्गीराला", " "},
        {"Andhra Pradesh", "Amalapuram", "Revu Sudhakar", "4", " ", "आन्ध्र प्रदेश", "अमलापुरम", "रेवु सुधाकर", " "},
        {"Andhra Pradesh", "Amalapuram", "Muralikrishna Kanderi", "4", " ", "आन्ध्र प्रदेश", "अमलापुरम", "मुरलीकृष्ण कंधारी", " "},
        {"Andhra Pradesh", "Anakapalle", "Adari Anand Kumar", "4", " ", "आन्ध्र प्रदेश", "अनकापल्ली", "आदिारी आनंद कुमार", " "},
        {"Andhra Pradesh", "Anakapalle", "Taadi Veera Jagadeeshwari", "3", " ", "आन्ध्र प्रदेश", "अनकापल्ली", "ताड़ी वीरा जगदेश्वरी", " "},
        {"Andhra Pradesh", "Anakapalle", "Dr Gandi Venkata Satyanarayana Rao", "1", " ", "आन्ध्र प्रदेश", "अनकापल्ली", "डॉ। गांडी वेंकट सत्यनारायण राव", " "},
        {"Andhra Pradesh", "Anakapalle", "P.S.Ajay Kumar", "2", " ", "आन्ध्र प्रदेश", "अनकापल्ली", "पीएसअजय कुमार", " "},
        {"Andhra Pradesh", "Anakapalle", "Appala Naidu Tummagonta", "4", " ", "आन्ध्र प्रदेश", "अनकापल्ली", "अप्पला नायडू तुममगोंता", " "},
        {"Andhra Pradesh", "Anakapalle", "Ruthala Srirama Murthy", "1", " ", "आन्ध्र प्रदेश", "अनकापल्ली", "रुतला श्रीराम मूर्ति", " "},
        {"Andhra Pradesh", "Anantapur", "Jagadeesh Devaragudi", "2", " ", "आन्ध्र प्रदेश", "अनंतपुर", "जगदीश देवरगुडी", " "},
        {"Andhra Pradesh", "Anantapur", "Talari Rangaiah", "2", " ", "आन्ध्र प्रदेश", "अनंतपुर", "तलारी रंगिया", " "},
        {"Andhra Pradesh", "Anantapur", "K Rajiv Reddy", "1", " ", "आन्ध्र प्रदेश", "अनंतपुर", "के राजीव रेड्डी", " "},
        {"Andhra Pradesh", "Anantapur", "Somanath Deshmukh", "4", " ", "आन्ध्र प्रदेश", "अनंतपुर", "सोमनाथ देशमुख", " "},
        {"Andhra Pradesh", "Anantapur", "Vadde Kasinath", "4", " ", "आन्ध्र प्रदेश", "अनंतपुर", "वाडडे काशीनाथ", " "},
        {"Andhra Pradesh", "Anantapur", "M.Venkatesulu", "4", " ", "आन्ध्र प्रदेश", "अनंतपुर", "M.Venkatesulu", " "},
        {"Andhra Pradesh", "Anantapur", "Lingutla Rangaiah", "3", " ", "आन्ध्र प्रदेश", "अनंतपुर", "लिंगुतला रंगैया", " "},
        {"Andhra Pradesh", "Anantapur", "Pothuru Rangaiah", "4", " ", "आन्ध्र प्रदेश", "अनंतपुर", "पोथुरू रंगाया", " "},
        {"Andhra Pradesh", "Anantapur", "Hamsa Devineni", "1", " ", "आन्ध्र प्रदेश", "अनंतपुर", "हम्सा देवीनेनी", " "},
        {"Andhra Pradesh", "Araku", "Vyricherla Kishore Chandra Suryanarayana Deo", "3", " ", "आन्ध्र प्रदेश", "अरकू", "विरिचरला किशोर चन्द्र सूर्यनारायण देव", " "},
        {"Andhra Pradesh", "Araku", "Dr. Kasi Viswanadha Veera Venkata Satyanarayana Reddy Kosuri", "1", " ", "आन्ध्र प्रदेश", "अरकू", "डॉ। काशी विश्वनाथ वीरा वेंकट सत्यनारायण रेड्डी कोसुरी", " "},
        {"Andhra Pradesh", "Araku", "Narava Satyavathi", "4", " ", "आन्ध्र प्रदेश", "अरकू", "नरवा सत्यवती", " "},
        {"Andhra Pradesh", "Araku", "Kangala Baladora", "4", " ", "आन्ध्र प्रदेश", "अरकू", "कंगला बलाडोरा", " "},
        {"Andhra Pradesh", "Araku", "Vampuru Gangulaiah", "2", " ", "आन्ध्र प्रदेश", "अरकू", "वैम्पुरु गंगुलाया", " "},
        {"Andhra Pradesh", "Araku", "Biddika Ramaiah", "4", " ", "आन्ध्र प्रदेश", "अरकू", "बिद्दिका रमैया", " "},
        {"Andhra Pradesh", "Araku", "Shruti Devi Vyricherla", "1", " ", "आन्ध्र प्रदेश", "अरकू", "श्रुति देवी विरंचेरला", " "},
        {"Andhra Pradesh", "Bapatla", "Challagali Kishore Kumar", "1", " ", "आन्ध्र प्रदेश", "बापतला", "चेलगाली किशोर कुमार", " "},
        {"Andhra Pradesh", "Bapatla", "Jesudasu Seelam", "1", " ", "आन्ध्र प्रदेश", "बापतला", "येसुदासु सीलम", " "},
        {"Andhra Pradesh", "Bapatla", "Nuthakki Rama Rao", "3", " ", "आन्ध्र प्रदेश", "बापतला", "नथत्की रामा राव", " "},
        {"Andhra Pradesh", "Bapatla", "Kattepogu Vijay Kumar", "4", " ", "आन्ध्र प्रदेश", "बापतला", "कट्टेपोगु विजय कुमार", " "},
        {"Andhra Pradesh", "Bapatla", "Malyadri Sriram", "3", " ", "आन्ध्र प्रदेश", "बापतला", "मलयाद्री श्रीराम", " "},
        {"Andhra Pradesh", "Bapatla", "Suresh Babu Nandigam", "4", " ", "आन्ध्र प्रदेश", "बापतला", "सुरेश बाबू नंदीग्राम", " "},
        {"Andhra Pradesh", "Bapatla", "Bussa Nagaraju", "2", " ", "आन्ध्र प्रदेश", "बापतला", "बुसा नागराजू", " "},
        {"Andhra Pradesh", "Chittoor", "C. Punyamurthy", "2", " ", "आन्ध्र प्रदेश", "चित्तूर", "सी। पुण्यमूर्ति", " "},
        {"Andhra Pradesh", "Chittoor", "Jayaram Duggani", "1", " ", "आन्ध्र प्रदेश", "चित्तूर", "जयराम दुग्गानी", " "},
        {"Andhra Pradesh", "Chittoor", "Cheemala. Rangappa", "1", " ", "आन्ध्र प्रदेश", "चित्तूर", "Cheemala। रंगप्पा", " "},
        {"Andhra Pradesh", "Chittoor", "N. Reddeppa", "3", " ", "आन्ध्र प्रदेश", "चित्तूर", "एन। रेड्डीप्पा", " "},
        {"Andhra Pradesh", "Chittoor", "A. Hemanth", "4", " ", "आन्ध्र प्रदेश", "चित्तूर", "ए। हेमंत", " "},
        {"Andhra Pradesh", "Chittoor", "Naramalli Siva Prasad", "3", " ", "आन्ध्र प्रदेश", "चित्तूर", "नारमल्ली शिव प्रसाद", " "},
        {"Andhra Pradesh", "Eluru", "Gurunadha Rao Jetti", "1", " ", "आन्ध्र प्रदेश", "एलुरु", "गुरुनधान राव जेट्टी", " "},
        {"Andhra Pradesh", "Eluru", "Maganti Venkateswara Rao", "2", " ", "आन्ध्र प्रदेश", "एलुरु", "मगंति वेंकटेश्वर राव", " "},
        {"Andhra Pradesh", "Eluru", "Chinnam Rama Kotayya", "1", " ", "आन्ध्र प्रदेश", "एलुरु", "छिन्नम राम कोटाय", " "},
        {"Andhra Pradesh", "Eluru", "Mathe Bobby", "4", " ", "आन्ध्र प्रदेश", "एलुरु", "माथे बॉबी", " "},
        {"Andhra Pradesh", "Eluru", "V Siva Rama Krishna", "4", " ", "आन्ध्र प्रदेश", "एलुरु", "वी शिव राम कृष्ण", " "},
        {"Andhra Pradesh", "Eluru", "Alaga Ravi Kumar", "4", " ", "आन्ध्र प्रदेश", "एलुरु", "अलागा रवि कुमार", " "},
        {"Andhra Pradesh", "Eluru", "Mendem Santhosh Kumar", "4", " ", "आन्ध्र प्रदेश", "एलुरु", "मेंडेम संतोष कुमार", " "},
        {"Andhra Pradesh", "Guntur", "Araveti Hazarath Rao", "3", " ", "आन्ध्र प्रदेश", "गुंटूर", "अरवेती हज़रत राव", " "},
        {"Andhra Pradesh", "Guntur", "Jayaprakash Narayana Valluru", "1", " ", "आन्ध्र प्रदेश", "गुंटूर", "जयप्रकाश नारायण वल्लुरु", " "},
        {"Andhra Pradesh", "Guntur", "Dasari Kiran Babu", "4", " ", "आन्ध्र प्रदेश", "गुंटूर", "दसारी किरन बाबू", " "},
        {"Andhra Pradesh", "Guntur", "Modugula Venugopala Reddy", "2", " ", "आन्ध्र प्रदेश", "गुंटूर", "मोडुगुला वेणुगोपाला रेड्डी", " "},
        {"Andhra Pradesh", "Guntur", "Samudrala Chinna Kotaiah", "4", " ", "आन्ध्र प्रदेश", "गुंटूर", "समुद्राला चिन्ना कोटािया", " "},
        {"Andhra Pradesh", "Guntur", "Jeldi Raja Mohan", "4", " ", "आन्ध्र प्रदेश", "गुंटूर", "जेल्डी राजा मोहन", " "},
        {"Andhra Pradesh", "Guntur", "Shaik Jaleel", "4", " ", "आन्ध्र प्रदेश", "गुंटूर", "शैक जलील", " "},
        {"Andhra Pradesh", "Guntur", "Bonaboyina Srinivasa Rao", "2", " ", "आन्ध्र प्रदेश", "गुंटूर", "बोनाबोयिना श्रीनिवास राव", " "},
        {"Andhra Pradesh", "Guntur", "Jacob Vidyasagar Nakka", "2", " ", "आन्ध्र प्रदेश", "गुंटूर", "जैकब विद्यासागर नक्का", " "},
        {"Andhra Pradesh", "Guntur", "Ramarao Simhadri", "4", " ", "आन्ध्र प्रदेश", "गुंटूर", "रामाराव सिम्हाद्रि", " "},
        {"Andhra Pradesh", "Guntur", "Shaik Mastanvali", "1", " ", "आन्ध्र प्रदेश", "गुंटूर", "शेख मस्तनवाली", " "},
        {"Andhra Pradesh", "Hindupur", "S.Ram Mohan", "4", " ", "आन्ध्र प्रदेश", "हिन्दुपुर", "एस.राम मोहन", " "},
        {"Andhra Pradesh", "Hindupur", "Ramamohan D.G.", "4", " ", "आन्ध्र प्रदेश", "हिन्दुपुर", "राममोहन डीजी", " "},
        {"Andhra Pradesh", "Hindupur", "Kuruva Gorantla Madhav", "2", " ", "आन्ध्र प्रदेश", "हिन्दुपुर", "कुरुवा गोरान्तला माधव", " "},
        {"Andhra Pradesh", "Hindupur", "Mitta Parthasarathi", "1", " ", "आन्ध्र प्रदेश", "हिन्दुपुर", "मित्ता पार्थसारथी", " "},
        {"Andhra Pradesh", "Hindupur", "N.Kristappa", "2", " ", "आन्ध्र प्रदेश", "हिन्दुपुर", "N.Kristappa", " "},
        {"Andhra Pradesh", "Hindupur", "K.T.Sreedhar", "1", " ", "आन्ध्र प्रदेश", "हिन्दुपुर", "KTSreedhar", " "},
        {"Andhra Pradesh", "Kadapa", "Yeduguri Sandinti Avinash Reddy", "2", " ", "आन्ध्र प्रदेश", "कडपा", "यदुगुड़ी संदींति अविनाश रेड्डी", " "},
        {"Andhra Pradesh", "Kadapa", "Jakku Chenna Krishna Reddy", "2", " ", "आन्ध्र प्रदेश", "कडपा", "जक्कू चेन्ना कृष्णा रेड्डी", " "},
        {"Andhra Pradesh", "Kadapa", "Lakshmi Reddy Putha", "2", " ", "आन्ध्र प्रदेश", "कडपा", "लक्ष्मी रेड्डी पुथा", " "},
        {"Andhra Pradesh", "Kadapa", "Chadipiralla Siva Narayana Reddy", "4", " ", "आन्ध्र प्रदेश", "कडपा", "चादिपिरल्ला शिव नारायण रेड्डी", " "},
        {"Andhra Pradesh", "Kadapa", "Venu Gopal Rachineni", "4", " ", "आन्ध्र प्रदेश", "कडपा", "वेणु गोपाल रचिनीनी", " "},
        {"Andhra Pradesh", "Kadapa", "Gundlakunta Sreeramulu", "1", " ", "आन्ध्र प्रदेश", "कडपा", "गुंडलाकुंटा श्रीरामुलु", " "},
        {"Andhra Pradesh", "Kadapa", "Gujjula Eswaraiah", "2", " ", "आन्ध्र प्रदेश", "कडपा", "गुजुला ईस्वरैया", " "},
        {"Andhra Pradesh", "Kadapa", "Gona Purushottam Reddy", "2", " ", "आन्ध्र प्रदेश", "कडपा", "गोना पुरुषोत्तम रेड्डी", " "},
        {"Andhra Pradesh", "Kadapa", "Sri Rama Chandra Singareddy", "1", " ", "आन्ध्र प्रदेश", "कडपा", "श्री राम चंद्र सिंगारेड्डी", " "},
        {"Andhra Pradesh", "Kakinada", "Sathi Veera Lakshmi", "4", " ", "आन्ध्र प्रदेश", "काकीनाडा", "सती वीरा लक्ष्मी", " "},
        {"Andhra Pradesh", "Kakinada", "Ankadi Sathibabu", "4", " ", "आन्ध्र प्रदेश", "काकीनाडा", "अनादि सतिबाबू", " "},
        {"Andhra Pradesh", "Kakinada", "Mallipudi Sri Ramachandra Murthy", "1", " ", "आन्ध्र प्रदेश", "काकीनाडा", "मल्लीपुड़ी श्री रामचंद्र मूर्ति", " "},
        {"Andhra Pradesh", "Kakinada", "Buddala Geetha Devi", "4", " ", "आन्ध्र प्रदेश", "काकीनाडा", "बुद्धाला गीता देवी", " "},
        {"Andhra Pradesh", "Kakinada", "Yalla Venkata Rama Mohana Rao", "1", " ", "आन्ध्र प्रदेश", "काकीनाडा", "यल्ला वेंकट राम मोहना राव", " "},
        {"Andhra Pradesh", "Kakinada", "Medisetti Vijaya Kumar", "2", " ", "आन्ध्र प्रदेश", "काकीनाडा", "मेदिसेटि विजया कुमार", " "},
        {"Andhra Pradesh", "Kakinada", "Peddimsetti Venkateswara Rao", "2", " ", "आन्ध्र प्रदेश", "काकीनाडा", "पेद्दिस्मेट्टी वेंकटेश्वर राव", " "},
        {"Andhra Pradesh", "Kakinada", "Kakileti Ravindra", "4", " ", "आन्ध्र प्रदेश", "काकीनाडा", "काकेली रविंद्र", " "},
        {"Andhra Pradesh", "Kakinada", "Jyothula Venkateswara Rao", "4", " ", "आन्ध्र प्रदेश", "काकीनाडा", "ज्योथुला वेंकटेश्वर राव", " "},
        {"Andhra Pradesh", "Kakinada", "Vasamsetty Venakta Ramana", "4", " ", "आन्ध्र प्रदेश", "काकीनाडा", "वसामस्ति वेंकट रमणा", " "},
        {"Andhra Pradesh", "Kurnool", "G Sanjeeva Kumar", "4", " ", "आन्ध्र प्रदेश", "कुरनूल", "जी संजीव कुमार", " "},
        {"Andhra Pradesh", "Kurnool", "B. Shiva Kumar", "4", " ", "आन्ध्र प्रदेश", "कुरनूल", "बी। शिव कुमार", " "},
        {"Andhra Pradesh", "Kurnool", "Abdul Waris", "2", " ", "आन्ध्र प्रदेश", "कुरनूल", "अब्दुल वारिस", " "},
        {"Andhra Pradesh", "Kurnool", "Kotla Jaya Surya Prakash Reddy", "3", " ", "आन्ध्र प्रदेश", "कुरनूल", "कोटला जया सूर्य प्रकाश रेड्डी", " "},
        {"Andhra Pradesh", "Kurnool", "Kasula Rajasekhar", "4", " ", "आन्ध्र प्रदेश", "कुरनूल", "कसुला राजशेखर", " "},
        {"Andhra Pradesh", "Kurnool", "Devarapogu Maddilety", "2", " ", "आन्ध्र प्रदेश", "कुरनूल", "देवरपोगु मडिलिटी", " "},
        {"Andhra Pradesh", "Kurnool", "Kommireddy Prabhakar Reddy", "2", " ", "आन्ध्र प्रदेश", "कुरनूल", "कोमिरेड्डी प्रभाकर रेड्डी", " "},
        {"Andhra Pradesh", "Kurnool", "Hatcholi Thomas", "4", " ", "आन्ध्र प्रदेश", "कुरनूल", "हैचोली थॉमस", " "},
        {"Andhra Pradesh", "Kurnool", "M. Naganna", "2", " ", "आन्ध्र प्रदेश", "कुरनूल", "एम। नागन्ना", " "},
        {"Andhra Pradesh", "Kurnool", "Ahmed Ali Khan", "1", " ", "आन्ध्र प्रदेश", "कुरनूल", "अहमद अली खान", " "},
        {"Andhra Pradesh", "Kurnool", "P.V. Parthasarathi", "1", " ", "आन्ध्र प्रदेश", "कुरनूल", "पीवी पार्थसारथी", " "},
        {"Andhra Pradesh", "Machilipatnam", "Gollu Krishna", "1", " ", "आन्ध्र प्रदेश", "मछलीपट्टनम", "गोलू कृष्ण", " "},
        {"Andhra Pradesh", "Machilipatnam", "Balashowry Vallabhaneni", "2", " ", "आन्ध्र प्रदेश", "मछलीपट्टनम", "बालाशोवरी वल्लभानेनी", " "},
        {"Andhra Pradesh", "Machilipatnam", "Gudivaka Venkata Naga Basava Rao", "4", " ", "आन्ध्र प्रदेश", "मछलीपट्टनम", "गुडीवाका वेंकट नाग बासावा राव", " "},
        {"Andhra Pradesh", "Machilipatnam", "Konakalla Narayana Rao", "3", " ", "आन्ध्र प्रदेश", "मछलीपट्टनम", "कोनकल्ला नारायण राव", " "},
        {"Andhra Pradesh", "Machilipatnam", "Peram Siva Nageswara Rao", "4", " ", "आन्ध्र प्रदेश", "मछलीपट्टनम", "पेरम शिव नागेश्वर राव", " "},
        {"Andhra Pradesh", "Machilipatnam", "Gudivaka Ramanjaneyulu", "1", " ", "आन्ध्र प्रदेश", "मछलीपट्टनम", "गुडीवाका रमनंजयुलु", " "},
        {"Andhra Pradesh", "Machilipatnam", "Valluru Venkateswara Rao", "3", " ", "आन्ध्र प्रदेश", "मछलीपट्टनम", "वल्लुरु वेंकटेश्वर राव", " "},
        {"Andhra Pradesh", "Machilipatnam", "Gandhi Dhanekula", "3", " ", "आन्ध्र प्रदेश", "मछलीपट्टनम", "गांधी धनकुला", " "},
        {"Andhra Pradesh", "Machilipatnam", "Yarlagadda Rama Mohana Rao", "4", " ", "आन्ध्र प्रदेश", "मछलीपट्टनम", "यारलागड्डा राम मोहना राव", " "},
        {"Andhra Pradesh", "Nandyal", "C. Surendra Nath Reddy", "4", " ", "आन्ध्र प्रदेश", "नांदयाल", "सी। सुरेन्द्र नाथ रेड्डी", " "},
        {"Andhra Pradesh", "Nandyal", "Jestadi Sudhakar", "2", " ", "आन्ध्र प्रदेश", "नांदयाल", "जस्तेदी सुधाकर", " "},
        {"Andhra Pradesh", "Nandyal", "Ruddireddy Radhakrishna", "4", " ", "आन्ध्र प्रदेश", "नांदयाल", "रुद्धिरड्डी राधाकृष्ण", " "},
        {"Andhra Pradesh", "Nandyal", "Poluru Guruvaiah", "4", " ", "आन्ध्र प्रदेश", "नांदयाल", "पोलुरु गुरुवा", " "},
        {"Andhra Pradesh", "Nandyal", "Vangala Parameswara Reddy.", "2", " ", "आन्ध्र प्रदेश", "नांदयाल", "वंगला परमेश्वर रेड्डी।", " "},
        {"Andhra Pradesh", "Nandyal", "Bhuma Kishor Reddy", "4", " ", "आन्ध्र प्रदेश", "नांदयाल", "भूमा किशोर रेड्डी", " "},
        {"Andhra Pradesh", "Nandyal", "D. Mahammad Rafi", "4", " ", "आन्ध्र प्रदेश", "नांदयाल", "डी। महम्मद रफ़ी", " "},
        {"Andhra Pradesh", "Nandyal", "K.P. Kambagiriswamy", "2", " ", "आन्ध्र प्रदेश", "नांदयाल", "केपी कांबगीरीस्वामी", " "},
        {"Andhra Pradesh", "Nandyal", "D. P. Jamal Basha", "4", " ", "आन्ध्र प्रदेश", "नांदयाल", "डीपी जमाल बाशा", " "},
        {"Andhra Pradesh", "Nandyal", "B.C. Ramanatha Reddy", "2", " ", "आन्ध्र प्रदेश", "नांदयाल", "बीसी रमानाथ रेड्डी", " "},
        {"Andhra Pradesh", "Nandyal", "Pula. Nagamaddilety", "4", " ", "आन्ध्र प्रदेश", "नांदयाल", "पुला। Nagamaddilety", " "},
        {"Andhra Pradesh", "Nandyal", "S.P.Y. Reddy", "2", " ", "आन्ध्र प्रदेश", "नांदयाल", "एसपीवाई रेड्डी", " "},
        {"Andhra Pradesh", "Nandyal", "Adinarayana Inty", "1", " ", "आन्ध्र प्रदेश", "नांदयाल", "आदिनारायण इं", " "},
        {"Andhra Pradesh", "Nandyal", "Lakshmi Narasaiah Jangiti", "1", " ", "आन्ध्र प्रदेश", "नांदयाल", "लक्ष्मी नारसहाय जंगीति", " "},
        {"Andhra Pradesh", "Nandyal", "I.V. Pakkir Reddy", "2", " ", "आन्ध्र प्रदेश", "नांदयाल", "IV पाकीर रेड्डी", " "},
        {"Andhra Pradesh", "Nandyal", "Pocha Brahmananda Reddy", "2", " ", "आन्ध्र प्रदेश", "नांदयाल", "पोचा ब्रह्मानंद रेड्डी", " "},
        {"Andhra Pradesh", "Narasaraopet", "Reddyboina Prasanna Kumar", "4", " ", "आन्ध्र प्रदेश", "नरसरोपेट", "रेड्डीबोनी प्रसन्ना कुमार", " "},
        {"Andhra Pradesh", "Narasaraopet", "Rayapati Sambasiva Rao", "3", " ", "आन्ध्र प्रदेश", "नरसरोपेट", "रायपट्टी सांबशिव राव", " "},
        {"Andhra Pradesh", "Narasaraopet", "Durgampudi Rami Reddy", "3", " ", "आन्ध्र प्रदेश", "नरसरोपेट", "दुर्गमपुदी रामी रेड्डी", " "},
        {"Andhra Pradesh", "Narasaraopet", "Kanakam Srinivasarao", "4", " ", "आन्ध्र प्रदेश", "नरसरोपेट", "कनकम श्रीनिवासराव", " "},
        {"Andhra Pradesh", "Narasaraopet", "Surabhi Devasahayam", "4", " ", "आन्ध्र प्रदेश", "नरसरोपेट", "सुरभि देवसहायम्", " "},
        {"Andhra Pradesh", "Narasaraopet", "Pakkala Suribabu", "1", " ", "आन्ध्र प्रदेश", "नरसरोपेट", "पक्कल सुरिबू", " "},
        {"Andhra Pradesh", "Narasaraopet", "Narasimharao Parimi", "2", " ", "आन्ध्र प्रदेश", "नरसरोपेट", "नरसिंहराव परिमी", " "},
        {"Andhra Pradesh", "Narasaraopet", "Kanna Lakshmi Narayana", "1", " ", "आन्ध्र प्रदेश", "नरसरोपेट", "कन्ना लक्ष्मी नारायण", " "},
        {"Andhra Pradesh", "Narasaraopet", "Shaik Nayub Kamal", "4", " ", "आन्ध्र प्रदेश", "नरसरोपेट", "शैक नायब कमल", " "},
        {"Andhra Pradesh", "Narsapuram", "Kanumuru Raghu Rama Krishna Raju", "2", " ", "आन्ध्र प्रदेश", "नरसापुरम", "कानमुरु रघु राम कृष्ण राजू", " "},
        {"Andhra Pradesh", "Narsapuram", "Medapati Varahala Reddy", "4", " ", "आन्ध्र प्रदेश", "नरसापुरम", "मेदापति वराहला रेड्डी", " "},
        {"Andhra Pradesh", "Narsapuram", "Dasari Krishna Murthy", "4", " ", "आन्ध्र प्रदेश", "नरसापुरम", "दसारी कृष्ण मूर्ति", " "},
        {"Andhra Pradesh", "Narsapuram", "Nalli Rajesh", "2", " ", "आन्ध्र प्रदेश", "नरसापुरम", "नल्ली राजेश", " "},
        {"Andhra Pradesh", "Narsapuram", "Pydikondala Manikyala Rao", "1", " ", "आन्ध्र प्रदेश", "नरसापुरम", "पाइदिकोंडला माणिक्यला राव", " "},
        {"Andhra Pradesh", "Narsapuram", "Venkata Sivarama Raju Vetukuri", "2", " ", "आन्ध्र प्रदेश", "नरसापुरम", "वेंकट शिवराम राजू वेतुकुरी", " "},
        {"Andhra Pradesh", "Narsapuram", "Kanumuru Bapiraju", "1", " ", "आन्ध्र प्रदेश", "नरसापुरम", "कानमुरु बापिराजू", " "},
        {"Andhra Pradesh", "Narsapuram", "K.A.Paul", "2", " ", "आन्ध्र प्रदेश", "नरसापुरम", "KAPaul", " "},
        {"Andhra Pradesh", "Narsapuram", "G S Raju", "4", " ", "आन्ध्र प्रदेश", "नरसापुरम", "जीएस राजू", " "},
        {"Andhra Pradesh", "Narsapuram", "Gurugubilli Rambabu", "4", " ", "आन्ध्र प्रदेश", "नरसापुरम", "गुरुगुबिली रामबाबू", " "},
        {"Andhra Pradesh", "Nellore", "Sannapureddy Suresh Reddy", "1", " ", "आन्ध्र प्रदेश", "नेल्लोर", "सन्निपुरेड्डी सुरेश रेड्डी", " "},
        {"Andhra Pradesh", "Nellore", "Narasapuram Prasad", "4", " ", "आन्ध्र प्रदेश", "नेल्लोर", "नरसापुरम प्रसाद", " "},
        {"Andhra Pradesh", "Nellore", "Chandra Rajagopal", "2", " ", "आन्ध्र प्रदेश", "नेल्लोर", "चन्द्र राजगोपाल", " "},
        {"Andhra Pradesh", "Nellore", "Chevuru Devakumar Reddy", "1", " ", "आन्ध्र प्रदेश", "नेल्लोर", "शेवरु देवकुमार रेड्डी", " "},
        {"Andhra Pradesh", "Nellore", "Chinni Venkateswarlu", "3", " ", "आन्ध्र प्रदेश", "नेल्लोर", "चिन्नी वेंकटेश्वरलु", " "},
        {"Andhra Pradesh", "Nellore", "Meda Malla Reddy", "3", " ", "आन्ध्र प्रदेश", "नेल्लोर", "मेदा मल्ला रेड्डी", " "},
        {"Andhra Pradesh", "Nellore", "Kankanala Penchala Naidu", "4", " ", "आन्ध्र प्रदेश", "नेल्लोर", "कंकनमाला पेन्चाला नायडू", " "},
        {"Andhra Pradesh", "Nellore", "Adala Prabhakara Reddy", "3", " ", "आन्ध्र प्रदेश", "नेल्लोर", "अदला प्रभाकर रेड्डी", " "},
        {"Andhra Pradesh", "Nellore", "Shaik Mahaboob Basha (Mabu)", "2", " ", "आन्ध्र प्रदेश", "नेल्लोर", "शैक महबूब बाशा (माबु)", " "},
        {"Andhra Pradesh", "Ongole", "Konda Praveen Kumar", "4", " ", "आन्ध्र प्रदेश", "ओंगोल", "कोंडा प्रवीण कुमार", " "},
        {"Andhra Pradesh", "Ongole", "Venkatesh Vepuri", "4", " ", "आन्ध्र प्रदेश", "ओंगोल", "वेंकटेश वेपुरी", " "},
        {"Andhra Pradesh", "Ongole", "Dr Sirivella Prasad", "1", " ", "आन्ध्र प्रदेश", "ओंगोल", "डॉ। सिरिवला प्रसाद", " "},
        {"Andhra Pradesh", "Ongole", "Billa Chennaiah", "4", " ", "आन्ध्र प्रदेश", "ओंगोल", "बिल्ला चेन्नाया", " "},
        {"Andhra Pradesh", "Ongole", "Thoganti Sreenivasulu", "1", " ", "आन्ध्र प्रदेश", "ओंगोल", "थोगन्ति श्रीनिवासुलु", " "},
        {"Andhra Pradesh", "Ongole", "Magunta Sreenivasulu Reddy", "3", " ", "आन्ध्र प्रदेश", "ओंगोल", "मगुंटा श्रीनिवासुलु रेड्डी", " "},
        {"Andhra Pradesh", "Ongole", "Kavuri Venu Babu Naidu", "4", " ", "आन्ध्र प्रदेश", "ओंगोल", "कवुरी वेणु बाबू नायडू", " "},
        {"Andhra Pradesh", "Rajahmundry", "Venu Kollapu", "2", " ", "आन्ध्र प्रदेश", "राजमुंदरी", "वेणु कोल्लापु", " "},
        {"Andhra Pradesh", "Rajahmundry", "Margani Bharat Ram", "2", " ", "आन्ध्र प्रदेश", "राजमुंदरी", "मरगनी भरत राम", " "},
        {"Andhra Pradesh", "Rajahmundry", "Geddam David Nelson Babu", "2", " ", "आन्ध्र प्रदेश", "राजमुंदरी", "गेड्डम डेविड नेल्सन बाबू", " "},
        {"Andhra Pradesh", "Rajahmundry", "Bandaru Rajeswara Rao", "4", " ", "आन्ध्र प्रदेश", "राजमुंदरी", "बंडारू राजेश्वर राव", " "},
        {"Andhra Pradesh", "Rajahmundry", "Meda Srinivasa Rao", "2", " ", "आन्ध्र प्रदेश", "राजमुंदरी", "मेदा श्रीनिवास राव", " "},
        {"Andhra Pradesh", "Rajahmundry", "Kuruvella Bhanu Chandar", "4", " ", "आन्ध्र प्रदेश", "राजमुंदरी", "कुरुवेलला भानु चंदर", " "},
        {"Andhra Pradesh", "Rajahmundry", "Nalluri Vijaya Srinivasa Rao", "1", " ", "आन्ध्र प्रदेश", "राजमुंदरी", "नल्लूरी विजया श्रीनिवास राव", " "},
        {"Andhra Pradesh", "Rajahmundry", "Srinivasa Rao Sangisetti", "4", " ", "आन्ध्र प्रदेश", "राजमुंदरी", "श्रीनिवास राव संगीसेटी", " "},
        {"Andhra Pradesh", "Rajahmundry", "Paravasthu Satya Gopinath Das", "1", " ", "आन्ध्र प्रदेश", "राजमुंदरी", "परवस्तु सत्य गोपीनाथ दास", " "},
        {"Andhra Pradesh", "Rajampet", "M.Shajahan Basha", "1", " ", "आन्ध्र प्रदेश", "राजमपेट", "एम। शाहजहां बाशा", " "},
        {"Andhra Pradesh", "Rajampet", "Mukram Syed", "4", " ", "आन्ध्र प्रदेश", "राजमपेट", "मुकर्रम सैयद", " "},
        {"Andhra Pradesh", "Rajampet", "Asadi Venkatadri", "4", " ", "आन्ध्र प्रदेश", "राजमपेट", "असदी वेंकटाद्रि", " "},
        {"Andhra Pradesh", "Rajampet", "Naresh Kumar Poojala", "4", " ", "आन्ध्र प्रदेश", "राजमपेट", "नरेश कुमार पूजला", " "},
        {"Andhra Pradesh", "Rajampet", "Khader Valli Shaik", "4", " ", "आन्ध्र प्रदेश", "राजमपेट", "खदर वल्ली शेख", " "},
        {"Andhra Pradesh", "Rajampet", "P.V.Midhun Reddy", "2", " ", "आन्ध्र प्रदेश", "राजमपेट", "पीवीमधुन रेड्डी", " "},
        {"Andhra Pradesh", "Rajampet", "D.A. Sathya Prabha", "3", " ", "आन्ध्र प्रदेश", "राजमपेट", "डीए सत्य प्रभा", " "},
        {"Andhra Pradesh", "Srikakulam", "Perla Samba Murthy", "1", " ", "आन्ध्र प्रदेश", "श्रीकाकुलम", "पेरला सांबा मूर्ति", " "},
        {"Andhra Pradesh", "Srikakulam", "Namballa Krishna Mohan", "2", " ", "आन्ध्र प्रदेश", "श्रीकाकुलम", "नंबल्ला कृष्ण मोहन", " "},
        {"Andhra Pradesh", "Srikakulam", "Srinivas Duvvada", "2", " ", "आन्ध्र प्रदेश", "श्रीकाकुलम", "श्रीनिवास दुव्वादा", " "},
        {"Andhra Pradesh", "Srikakulam", "Dola Jagan Mohana Rao", "1", " ", "आन्ध्र प्रदेश", "श्रीकाकुलम", "डोला जगन मोहन राव", " "},
        {"Andhra Pradesh", "Srikakulam", "Rammohannaidu Kinjarapu", "2", " ", "आन्ध्र प्रदेश", "श्रीकाकुलम", "राममोहननिदु किंजरापु", " "},
        {"Andhra Pradesh", "Tirupati", "Karra Siva", "4", " ", "आन्ध्र प्रदेश", "तिरुपति", "कर्रा शिव", " "},
        {"Andhra Pradesh", "Tirupati", "K.S. Munirathnam", "3", " ", "आन्ध्र प्रदेश", "तिरुपति", "केएस मुनिरत्नम", " "},
        {"Andhra Pradesh", "Tirupati", "Bommi Srihari Rao", "1", " ", "आन्ध्र प्रदेश", "तिरुपति", "बोम्मी श्रीहरि राव", " "},
        {"Andhra Pradesh", "Tirupati", "Chinta Mohan", "1", " ", "आन्ध्र प्रदेश", "तिरुपति", "चिन्ता मोहन", " "},
        {"Andhra Pradesh", "Tirupati", "M. Solomon", "3", " ", "आन्ध्र प्रदेश", "तिरुपति", "एम। सोलोमन", " "},
        {"Andhra Pradesh", "Vijayawada", "Naraharisetty Narasimha Rao", "1", " ", "आन्ध्र प्रदेश", "विजयवाड़ा", "नरहरिसट्टी नरसिम्हा राव", " "},
        {"Andhra Pradesh", "Vijayawada", "Mohammad Ishaq", "4", " ", "आन्ध्र प्रदेश", "विजयवाड़ा", "मोहम्मद इशाक", " "},
        {"Andhra Pradesh", "Vijayawada", "Muttamasetty Lakshmana Siva Prasad Babu", "3", " ", "आन्ध्र प्रदेश", "विजयवाड़ा", "मुत्तमासतेति लक्ष्मणा शिव प्रसाद बाबू", " "},
        {"Andhra Pradesh", "Vijayawada", "Anil Kumar Maddineni", "2", " ", "आन्ध्र प्रदेश", "विजयवाड़ा", "अनिल कुमार मद्दीनैनी", " "},
        {"Andhra Pradesh", "Vijayawada", "Siva Prasad Padala", "4", " ", "आन्ध्र प्रदेश", "विजयवाड़ा", "शिव प्रसाद पाडला", " "},
        {"Andhra Pradesh", "Vijayawada", "Srinivas Kesineni", "4", " ", "आन्ध्र प्रदेश", "विजयवाड़ा", "श्रीनिवास केसिनेनी", " "},
        {"Andhra Pradesh", "Vijayawada", "Bolisetty Hari Babu", "2", " ", "आन्ध्र प्रदेश", "विजयवाड़ा", "बोलिस्ति हरि बाबू", " "},
        {"Andhra Pradesh", "Vijayawada", "Prasad Veera Potluri", "2", " ", "आन्ध्र प्रदेश", "विजयवाड़ा", "प्रसाद वीरा पोटुलुरी", " "},
        {"Andhra Pradesh", "Vijayawada", "Dileep Kilaru", "1", " ", "आन्ध्र प्रदेश", "विजयवाड़ा", "दिलीप किलरू", " "},
        {"Andhra Pradesh", "Vijayawada", "Gandhi Dhanekula", "3", " ", "आन्ध्र प्रदेश", "विजयवाड़ा", "गांधी धनकुला", " "},
        {"Andhra Pradesh", "Vijayawada", "Madabathula Chandra Sekhar", "4", " ", "आन्ध्र प्रदेश", "विजयवाड़ा", "मदबथुला चन्द्रशेखर", " "},
        {"Andhra Pradesh", "Vijayawada", "Lurthu Meri Daila", "4", " ", "आन्ध्र प्रदेश", "विजयवाड़ा", "लरतथु मारी डेला", " "},
        {"Andhra Pradesh", "Vijayawada", "Riyaz Dada Miya Shaik", "4", " ", "आन्ध्र प्रदेश", "विजयवाड़ा", "रियाज दादा मिया शेख", " "},
        {"Andhra Pradesh", "Visakhapatnam", "Gannu Mallayya", "3", " ", "आन्ध्र प्रदेश", "विशाखापत्तनम", "गन्नू मलैया", " "},
        {"Andhra Pradesh", "Visakhapatnam", "Kothapalli Geetha", "2", " ", "आन्ध्र प्रदेश", "विशाखापत्तनम", "कोथपल्ली गीथा", " "},
        {"Andhra Pradesh", "Visakhapatnam", "Pedada Ramanikumari", "1", " ", "आन्ध्र प्रदेश", "विशाखापत्तनम", "पेड़ा रमानीकुमारी", " "},
        {"Andhra Pradesh", "Visakhapatnam", "B. Jaya Venu Gopal", "4", " ", "आन्ध्र प्रदेश", "विशाखापत्तनम", "बी जया वेणु गोपाल", " "},
        {"Andhra Pradesh", "Visakhapatnam", "R. Udaya Gowri", "4", " ", "आन्ध्र प्रदेश", "विशाखापत्तनम", "आर। उदय गौरी", " "},
        {"Andhra Pradesh", "Visakhapatnam", "Gampala Somasundaram", "3", " ", "आन्ध्र प्रदेश", "विशाखापत्तनम", "गम्पला सोमसुंदरम", " "},
        {"Andhra Pradesh", "Visakhapatnam", "M V V Satyanarayana", "2", " ", "आन्ध्र प्रदेश", "विशाखापत्तनम", "एमवीवी सत्यनारायण", " "},
        {"Andhra Pradesh", "Visakhapatnam", "Daggubati Purandeswari", "1", " ", "आन्ध्र प्रदेश", "विशाखापत्तनम", "दग्गुबाती पुरंदेश्वरी", " "},
        {"Andhra Pradesh", "Vizianagaram", "Yella Rao Siyyadula", "4", " ", "आन्ध्र प्रदेश", "विजयनगरम", "येला राव सियादुला", " "},
        {"Andhra Pradesh", "Vizianagaram", "Adiraju Yedla", "1", " ", "आन्ध्र प्रदेश", "विजयनगरम", "आदिराजु येदला", " "},
        {"Andhra Pradesh", "Vizianagaram", "Ashok Gajapathi Raju Pusapati", "3", " ", "आन्ध्र प्रदेश", "विजयनगरम", "अशोक गजपति राजू पुष्पति", " "},
        {"Andhra Pradesh", "Vizianagaram", "Pentapati Rajesh", "4", " ", "आन्ध्र प्रदेश", "विजयनगरम", "पेंटापति राजेश", " "},
        {"Andhra Pradesh", "Vizianagaram", "Kovvuri Surya Bhavani", "4", " ", "आन्ध्र प्रदेश", "विजयनगरम", "कोव्वुरी सूर्य भवानी", " "},
        {"Andhra Pradesh", "Vizianagaram", "Lingala Chiranjeevi", "4", " ", "आन्ध्र प्रदेश", "विजयनगरम", "लिंगाला चिरंजीवी", " "},
        {"Andhra Pradesh", "Vizianagaram", "Ramu Naidu Yijurothu", "4", " ", "आन्ध्र प्रदेश", "विजयनगरम", "रामू नायडू यिजुरथु", " "},
        {"Andhra Pradesh", "Vizianagaram", "Anandsagar Pogru", "4", " ", "आन्ध्र प्रदेश", "विजयनगरम", "अनंदसागर पोगरू", " "},
        {"Andhra Pradesh", "Vizianagaram", "Sanyasi Raju Pakalapati", "1", " ", "आन्ध्र प्रदेश", "विजयनगरम", "सन्यासी राजू पकलपति", " "},
        {"Andhra Pradesh", "Vizianagaram", "Bellana Chandra Sekhar", "2", " ", "आन्ध्र प्रदेश", "विजयनगरम", "बेलना चंद्र शेखर", " "},
        {"Andhra Pradesh", "Vizianagaram", "Mukka Sreenivasa Rao", "4", " ", "आन्ध्र प्रदेश", "विजयनगरम", "मुक्का श्रीनिवास राव", " "},
};

}