/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Assam {
public static final String[][] green_bucket = {
{"Assam",  "3435", "Autonomous District", "Holiram Terang", "Autonomous State Demand Committee", "5.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5922",  "असम",  "स्वायत्त जिला", "Holiram Terang", "स्वायत्त राज्य की मांग समिति", ""}, 
{"Assam",  "6451", "Barpeta", "Santanu Mukherjee", "Bharatiya Gana Parishad", "12.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9076",  "असम",  "बारपेटा", "संतनु मुखर्जी", "भारतीय गण परिषद", ""}, 
{"Assam",  "6455", "Barpeta", "Aroon Barooa", "Purvanchal Janta Party (Secular)", "7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9070",  "असम",  "बारपेटा", "आरोन बारोआ", "पूर्वांचल जनता पार्टी (सेक्युलर)", ""}, 
{"Assam",  "6456", "Barpeta", "Pranabjyoti Das Rajbonshi", "National Peoples Party", "34.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9073",  "असम",  "बारपेटा", "प्रणबज्योति दास राजबंशी", "नेशनल पीपुल्स पार्टी", ""}, 
{"Assam",  "6460", "Barpeta", "Saniara Parbin", "Voters Party International", "50.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9075",  "असम",  "बारपेटा", "सानीरा परबीन", "वोटर पार्टी इंटरनेशनल", ""}, 
{"Assam",  "6463", "Barpeta", "Chitralekha Das", "Socialist Unity Centre of India (Communist)", "22.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7840",  "असम",  "बारपेटा", "चित्रलेखा दास", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Assam",  "6430", "Dhubri", "Alakesh Roy", "Hindusthan Nirman Dal", "25.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8229",  "असम",  "धुबरी", "अलकेश रॉय", "हिंदुस्तान निर्माण दल", ""}, 
{"Assam",  "6431", "Dhubri", "Anamika Sarkar", "Independent", "62Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8230",  "असम",  "धुबरी", "अनामिका सरकार", "निर्दलीय", ""}, 
{"Assam",  "6433", "Dhubri", "Johirul Islam Khan", "Purvanchal Janta Party (Secular)", "4.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9077",  "असम",  "धुबरी", "जोहिरुल इस्लाम खान", "पूर्वांचल जनता पार्टी (सेक्युलर)", ""}, 
{"Assam",  "6434", "Dhubri", "Shajahan Sheikh", "Voters Party International", "5.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7843",  "असम",  "धुबरी", "शाजहां शेख", "वोटर पार्टी इंटरनेशनल", ""}, 
{"Assam",  "6435", "Dhubri", "Zabed Islam", "Asom Gana Parishad", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8231",  "असम",  "धुबरी", "ज़ाबेद इस्लाम", "असोम गण परिषद", ""}, 
{"Assam",  "6438", "Dhubri", "Surat Jaman Mondal", "Socialist Unity Centre of India (Communist)", "16.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7842",  "असम",  "धुबरी", "सुरत जमन मोंडल", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Assam",  "6442", "Dhubri", "Mir Hussain Sarkar", "Independent", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9078",  "असम",  "धुबरी", "मीर हुसैन सरकार", "निर्दलीय", ""}, 
{"Assam",  "3480", "Dibrugarh", "Md. Nurul Huda Imdadul Islam Saikia", "Independent", "70.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5585",  "असम",  "डिब्रूगढ़", "मो। नूरुल हुदा इमदादुल इस्लाम सैकिया", "निर्दलीय", ""}, 
{"Assam",  "3483", "Dibrugarh", "Apurba Saikia", "Independent", "6.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5589",  "असम",  "डिब्रूगढ़", "अपूर्वा सैकिया", "निर्दलीय", ""}, 
{"Assam",  "3487", "Dibrugarh", "Dr. Titus Bhengra", "Bahujan Mukti Party", "9.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5586",  "असम",  "डिब्रूगढ़", "डॉ। टाइटस भेंगरा", "बहुजन मुक्ति पार्टी", ""}, 
{"Assam",  "6466", "Gauhati", "Rajib Kakati", "Hindusthan Nirman Dal", "67.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8236",  "असम",  "गुवाहाटी", "राजिब काकती", "हिंदुस्तान निर्माण दल", ""}, 
{"Assam",  "6467", "Gauhati", "Dr. Faruk Ahmed Bhuyan", "Independent", "92.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8232",  "असम",  "गुवाहाटी", "डॉ। फारुक अहमद भुयान", "निर्दलीय", ""}, 
{"Assam",  "6469", "Gauhati", "Upamanyu Hazarika", "Independent", "6.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8239",  "असम",  "गुवाहाटी", "उपमन्यु हजारिका", "निर्दलीय", ""}, 
{"Assam",  "6470", "Gauhati", "Rubi Neog", "National Republican Congress", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9094",  "असम",  "गुवाहाटी", "रूबी नेग", "नेशनल रिपब्लिकन कांग्रेस", ""}, 
{"Assam",  "6472", "Gauhati", "Pankaj Das", "Swarna Bharat Party", "6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7395",  "असम",  "गुवाहाटी", "पंकज दास", "स्वर्ण भारत पार्टी", ""}, 
{"Assam",  "6473", "Gauhati", "Utpal Borgohain", "Independent", "78Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9096",  "असम",  "गुवाहाटी", "उत्पल बोर्गोहिन", "निर्दलीय", ""}, 
{"Assam",  "6474", "Gauhati", "Alimuddin Ahmed", "Independent", "73.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9091",  "असम",  "गुवाहाटी", "अलीमुद्दीन अहमद", "निर्दलीय", ""}, 
{"Assam",  "6475", "Gauhati", "Partha Pratim Baruah", "Voters Party International", "67050", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8234",  "असम",  "गुवाहाटी", "पार्थ प्रतिम बरुआ", "वोटर पार्टी इंटरनेशनल", ""}, 
{"Assam",  "6476", "Gauhati", "Dr. Avijit Chakraborty", "Bharatiya Gana Parishad", "12.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7845",  "असम",  "गुवाहाटी", "डॉ। अविजीत चक्रवर्ती", "भारतीय गण परिषद", ""}, 
{"Assam",  "6479", "Gauhati", "Junmoni Devi Khaund", "Independent", "34.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8233",  "असम",  "गुवाहाटी", "जुमोनी देवी खुंद", "निर्दलीय", ""}, 
{"Assam",  "6480", "Gauhati", "Ratul Kumar Choudhury", "Samajwadi Party", "24.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8237",  "असम",  "गुवाहाटी", "रतुल कुमार चौधरी", "समाजवादी पार्टी", ""}, 
{"Assam",  "3473", "Jorhat", "Kanak Gogoi", "Communist Party of India", "23894", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4872",  "असम",  "जोरहाट", "कनक गोगोई", "भारतीय कम्युनिस्ट पार्टी", ""}, 
{"Assam",  "3475", "Jorhat", "Nandita Nag", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5583",  "असम",  "जोरहाट", "नंदिता नाग", "निर्दलीय", ""}, 
{"Assam",  "3476", "Jorhat", "Ribulaya Gogoi", "All India Trinamool Congress", "11.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5580",  "असम",  "जोरहाट", "रिबुल्या गोगोई", "अखिल भारतीय तृणमूल कांग्रेस", ""}, 
{"Assam",  "3467", "Kaliabor", "Md. Hariqul Islam Bhuyan", "Asom Jana Morcha", "38.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5573",  "असम",  "कलियाबोर", "मो। हरिकुल इस्लाम भुइयां", "अस जन जन मोर्चा", ""}, 
{"Assam",  "3468", "Kaliabor", "Abdul Aziz", "National People's Party", "35.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5575",  "असम",  "कलियाबोर", "अब्दुल अजीज", "नेशनल पीपुल्स पार्टी", ""}, 
{"Assam",  "3470", "Kaliabor", "Moni Madhab Mahanta", "Asom Gana Parishad", "27.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5576",  "असम",  "कलियाबोर", "मोनी माधब महंत", "असोम गण परिषद", ""}, 
{"Assam",  "3416", "Karimganj", "Raju Das", "Independent", "7.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5904",  "असम",  "करीमगंज", "राजू दास", "निर्दलीय", ""}, 
{"Assam",  "6444", "Kokrajhar", "Ranjoy Kr. Brahma", "Independent", "1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9068",  "असम",  "कोकराझार", "रणजॉय क्र। ब्रह्मा", "निर्दलीय", ""}, 
{"Assam",  "6446", "Kokrajhar", "Urkhao Gwra Brahma", "United Peoples Party, Liberal", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8243",  "असम",  "कोकराझार", "उरखो ग्वाला ब्रह्मा", "यूनाइटेड पीपल्स पार्टी, लिबरल", ""}, 
{"Assam",  "3439", "Kokrajhar", "Biraj Deka", "Communist Party of India (Marxist)", "15.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7848",  "असम",  "कोकराझार", "बिराज डेका", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)", ""}, 
{"Assam",  "3488", "Lakhimpur", "Hem Kanta Miri", "Socialist Unity Centre of India (Communist)", "2.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4874",  "असम",  "लखीमपुर", "हेम कांता मिरी", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Assam",  "3490", "Lakhimpur", "Arup Kalita", "Communist Party of India", "25.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5376",  "असम",  "लखीमपुर", "अरूप कलिता", "भारतीय कम्युनिस्ट पार्टी", ""}, 
{"Assam",  "3492", "Lakhimpur", "Anup Pratim Borbaruah", "Nationalist Congress Party", "5.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5592",  "असम",  "लखीमपुर", "अनूप प्रतीम बोरबरुआ", "राष्ट्रवादी कांग्रेस पार्टी", ""}, 
{"Assam",  "3494", "Lakhimpur", "Bhupen Narah", "Voters Party International", "7.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5597",  "असम",  "लखीमपुर", "भूपेन नारह", "वोटर पार्टी इंटरनेशनल", ""}, 
{"Assam",  "3440", "Mangaldoi", "Swarnalata Chaliha", "Socialist Unity Centre of India (Communist)", "32900", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5927",  "असम",  "मंगलदोई", "स्वर्णलता चालिहा", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Assam",  "3445", "Mangaldoi", "Prodeep Kumar Daimary", "Independent", "10.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5565",  "असम",  "मंगलदोई", "प्रोडीप कुमार दैमारी", "निर्दलीय", ""}, 
{"Assam",  "3446", "Mangaldoi", "Sudhendu Mohan Talukdar", "All India Trinamool Congress", "38.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5932",  "असम",  "मंगलदोई", "सुधेंदु मोहन तालुकदार", "अखिल भारतीय तृणमूल कांग्रेस", ""}, 
{"Assam",  "3447", "Mangaldoi", "Jayanta Kumar Kalita", "Independent", "41.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5928",  "असम",  "मंगलदोई", "जयंत कुमार कलिता", "निर्दलीय", ""}, 
{"Assam",  "3449", "Mangaldoi", "Kazi Nekib Ahmed", "Independent", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5931",  "असम",  "मंगलदोई", "काजी नेकिब अहमद", "निर्दलीय", ""}, 
{"Assam",  "3458", "Nawgong", "Saiful Islam Choudhury", "Asom Jana Morcha", "94.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5374",  "असम",  "नौगांव", "सैफुल इस्लाम चौधरी", "अस जन जन मोर्चा", ""}, 
{"Assam",  "3462", "Nawgong", "Zakir Hussain", "Independent", "41.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5938",  "असम",  "नौगांव", "जाकिर हुसैन", "निर्दलीय", ""}, 
{"Assam",  "3423", "Silchar", "Badrul Islam Barbhuiya", "All India Forward Bloc", "26.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5913",  "असम",  "सिलचर", "बदरुल इस्लाम बारबुइया", "ऑल इंडिया फॉरवर्ड ब्लॉक", ""}, 
{"Assam",  "3425", "Silchar", "Nazia Yasmin Mazumdar", "National People's Party", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5911",  "असम",  "सिलचर", "नाज़िया यास्मीन मजूमदार", "नेशनल पीपुल्स पार्टी", ""}, 
{"Assam",  "3431", "Silchar", "Ashitava Dutta", "Independent", "4.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5915",  "असम",  "सिलचर", "अश्वित दत्ता", "निर्दलीय", ""}, 
{"Assam",  "3454", "Tezpur", "Ram Bahadur Sunar", "National People's Party", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7957",  "असम",  "तेजपुर", "राम बहादुर सुनार", "नेशनल पीपुल्स पार्टी", ""}, 
};

public static final String[][] red_bucket = {
{ "Assam",  "3436",  "Autonomous District", "Biren Singh Engti", "ForeignFunding",  " ","असम",  "स्वायत्त जिला", "बीरेन सिंह एंगती", " "}, 
{ "Assam",  "3437",  "Autonomous District", "Horen Sing Bey", "ForeignFunding",  " ","असम",  "स्वायत्त जिला", "होरन गा बय", " "}, 
{ "Assam",  "3438",  "Autonomous District", "Lienkhochon", "NotGraduate",  " ","असम",  "स्वायत्त जिला", "Lienkhochon", " "}, 
{ "Assam",  "6452",  "Barpeta", "Kumar Deepak Das", "CriminalCases",  " ","असम",  "बारपेटा", "कुमार दीपक दास", " "}, 
{ "Assam",  "6453",  "Barpeta", "Matiar Rahman", "NotGraduate",  " ","असम",  "बारपेटा", "मतीर रहमान", " "}, 
{ "Assam",  "6454",  "Barpeta", "Bhadreswar Barman", "NotGraduate",  " ","असम",  "बारपेटा", "भद्रेश्वर बर्मन", " "}, 
{ "Assam",  "6457",  "Barpeta", "Rafiqul Islam", "CriminalCases",  " ","असम",  "बारपेटा", "रफीकुल इस्लाम", " "}, 
{ "Assam",  "6458",  "Barpeta", "Ashahak Ali Dewan", "OverAged",  " ","असम",  "बारपेटा", "अशक अली दीवान", " "}, 
{ "Assam",  "6459",  "Barpeta", "Arfan Ali", "NotGraduate",  " ","असम",  "बारपेटा", "अरफान अली", " "}, 
{ "Assam",  "6461",  "Barpeta", "Rejaul Karim", "NotGraduate",  " ","असम",  "बारपेटा", "रेजुल करीम", " "}, 
{ "Assam",  "6462",  "Barpeta", "Abdul Khaleque", "ForeignFunding",  " ","असम",  "बारपेटा", "अब्दुल खलीक", " "}, 
{ "Assam",  "6428",  "Dhubri", "Abu Taher Bepari", "ForeignFunding",  " ","असम",  "धुबरी", "अबू ताहिर बेपारी", " "}, 
{ "Assam",  "6429",  "Dhubri", "Shukur Ali", "NotGraduate",  " ","असम",  "धुबरी", "शुकुर अली", " "}, 
{ "Assam",  "6432",  "Dhubri", "Nripen Das", "NotGraduate",  " ","असम",  "धुबरी", "नृपेन दास", " "}, 
{ "Assam",  "6436",  "Dhubri", "Nurul Islam Choudhury", "OverAged",  " ","असम",  "धुबरी", "नुरुल इस्लाम चौधरी", " "}, 
{ "Assam",  "6437",  "Dhubri", "Uttam Kumar Ray", "CriminalCases",  " ","असम",  "धुबरी", "उत्तम कुमार रे", " "}, 
{ "Assam",  "6439",  "Dhubri", "Mehbubar Rahman", "NotGraduate",  " ","असम",  "धुबरी", "महबूब रहमान", " "}, 
{ "Assam",  "6440",  "Dhubri", "Badruddin Ajmal", "CriminalCases",  " ","असम",  "धुबरी", "बदरुद्दीन अजमल", " "}, 
{ "Assam",  "6441",  "Dhubri", "Rukunur Zaman", "NotGraduate",  " ","असम",  "धुबरी", "रुकुनुर ज़मान", " "}, 
{ "Assam",  "3481",  "Dibrugarh", "Rubul Buragohain", "NotGraduate",  " ","असम",  "डिब्रूगढ़", "रुबुल बुरगोहैन", " "}, 
{ "Assam",  "3482",  "Dibrugarh", "Israil Nanda", "NotGraduate",  " ","असम",  "डिब्रूगढ़", "इजरायल नंदा", " "}, 
{ "Assam",  "3484",  "Dibrugarh", "Paban Singh Ghatowar", "ForeignFunding",  " ","असम",  "डिब्रूगढ़", "पबन सिंह घाटोवार", " "}, 
{ "Assam",  "3485",  "Dibrugarh", "Bhaben Baruah", "CriminalCases",  " ","असम",  "डिब्रूगढ़", "भाबें बरुआ", " "}, 
{ "Assam",  "3486",  "Dibrugarh", "Rameswar Teli", "ForeignFunding",  " ","असम",  "डिब्रूगढ़", "रामेश्वर तेली", " "}, 
{ "Assam",  "6464",  "Gauhati", "Bobbeeta Sharma", "ForeignFunding",  " ","असम",  "गुवाहाटी", "बोबीबेता शर्मा", " "}, 
{ "Assam",  "6465",  "Gauhati", "Sri Shankha Sinha", "NotGraduate",  " ","असम",  "गुवाहाटी", "श्री शंख सिन्हा", " "}, 
{ "Assam",  "6468",  "Gauhati", "Sadek Ali", "CriminalCases",  " ","असम",  "गुवाहाटी", "सादिक अली", " "}, 
{ "Assam",  "6471",  "Gauhati", "Queen Oja", "ForeignFunding",  " ","असम",  "गुवाहाटी", "रानी ओजा", " "}, 
{ "Assam",  "6477",  "Gauhati", "Manoj Sharma", "CriminalCases",  " ","असम",  "गुवाहाटी", "मनोज शर्मा", " "}, 
{ "Assam",  "6478",  "Gauhati", "Mamoni Sarma", "NotGraduate",  " ","असम",  "गुवाहाटी", "मामोनी सरमा", " "}, 
{ "Assam",  "3472",  "Jorhat", "Kamala Raj Konwar", "NotGraduate",  " ","असम",  "जोरहाट", "कमला राज कोंवर", " "}, 
{ "Assam",  "3474",  "Jorhat", "Topon Kumar Gogoi", "ForeignFunding",  " ","असम",  "जोरहाट", "टोपन कुमार गोगोई", " "}, 
{ "Assam",  "3477",  "Jorhat", "Raj Kumar Duwara", "NotGraduate",  " ","असम",  "जोरहाट", "राज कुमार दुवारा", " "}, 
{ "Assam",  "3478",  "Jorhat", "Arbin Kumar Boruah", "NotGraduate",  " ","असम",  "जोरहाट", "अर्बिन कुमार बोरुहा", " "}, 
{ "Assam",  "3479",  "Jorhat", "Sushanta Borgohain", "ForeignFunding",  " ","असम",  "जोरहाट", "सुशांत बोर्गोहैन", " "}, 
{ "Assam",  "3465",  "Kaliabor", "Sri Bhaskar Sarmah", "NotGraduate",  " ","असम",  "कलियाबोर", "श्री भास्कर सरमाह", " "}, 
{ "Assam",  "3466",  "Kaliabor", "Sri Jiten Gogoi", "CriminalCases",  " ","असम",  "कलियाबोर", "श्री जितेन गोगोई", " "}, 
{ "Assam",  "3469",  "Kaliabor", "Shree Diganta Kumar Saikia", "CriminalCases",  " ","असम",  "कलियाबोर", "श्री दिगंत कुमार सैकिया", " "}, 
{ "Assam",  "3471",  "Kaliabor", "Gaurav Gogoi", "ForeignFunding",  " ","असम",  "कलियाबोर", "गौरव गोगोई", " "}, 
{ "Assam",  "3408",  "Karimganj", "Nikhil Ranjan Das", "NotGraduate",  " ","असम",  "करीमगंज", "निखिल रंजन दास", " "}, 
{ "Assam",  "3409",  "Karimganj", "Kripanath Mallah", "ForeignFunding",  " ","असम",  "करीमगंज", "कृपानथ मल्लाह", " "}, 
{ "Assam",  "3410",  "Karimganj", "Ajoy Kumar Sarkar", "NotGraduate",  " ","असम",  "करीमगंज", "अजॉय कुमार सरकार", " "}, 
{ "Assam",  "3411",  "Karimganj", "Probash Chandra Sarkar", "NotGraduate",  " ","असम",  "करीमगंज", "प्रोबेश चंद्र सरकार", " "}, 
{ "Assam",  "3412",  "Karimganj", "Parikshit Roy", "NotGraduate",  " ","असम",  "करीमगंज", "परीक्षित रॉय", " "}, 
{ "Assam",  "3413",  "Karimganj", "Anupam Singha", "NotGraduate",  " ","असम",  "करीमगंज", "अनुपम सिंहा", " "}, 
{ "Assam",  "3414",  "Karimganj", "Satyajit Das", "NotGraduate",  " ","असम",  "करीमगंज", "सत्यजीत दास", " "}, 
{ "Assam",  "3415",  "Karimganj", "Swarup Das", "ForeignFunding",  " ","असम",  "करीमगंज", "स्वरूप दास", " "}, 
{ "Assam",  "3417",  "Karimganj", "Rabindra Chandra Das", "NotGraduate",  " ","असम",  "करीमगंज", "रवीन्द्र चंद्र दास", " "}, 
{ "Assam",  "3418",  "Karimganj", "Radheshyam Biswas", "OverAged",  " ","असम",  "करीमगंज", "राधेश्याम विश्वास", " "}, 
{ "Assam",  "3419",  "Karimganj", "Ramnarayan Suklabaidya", "NotGraduate",  " ","असम",  "करीमगंज", "रामनारायण सुकुलबैद्य", " "}, 
{ "Assam",  "3420",  "Karimganj", "Hiralal Rabidas", "NotGraduate",  " ","असम",  "करीमगंज", "हीरालाल रविदास", " "}, 
{ "Assam",  "3421",  "Karimganj", "Chandan Das", "NotGraduate",  " ","असम",  "करीमगंज", "चंदन दास", " "}, 
{ "Assam",  "6443",  "Kokrajhar", "Sabda Ram Rabha", "ForeignFunding",  " ","असम",  "कोकराझार", "सबदा राम राभा", " "}, 
{ "Assam",  "6445",  "Kokrajhar", "Naba Kumar Sarania", "CriminalCases",  " ","असम",  "कोकराझार", "नाबा कुमार सरानिया", " "}, 
{ "Assam",  "6447",  "Kokrajhar", "Rajesh Narzary", "NotGraduate",  " ","असम",  "कोकराझार", "राजेश नारज़री", " "}, 
{ "Assam",  "6448",  "Kokrajhar", "Charan Iswary", "NotGraduate",  " ","असम",  "कोकराझार", "चरन इसवरी", " "}, 
{ "Assam",  "6449",  "Kokrajhar", "Prasanjit Kumar Das", "NotGraduate",  " ","असम",  "कोकराझार", "प्रसनजीत कुमार दास", " "}, 
{ "Assam",  "6450",  "Kokrajhar", "Pramila Rani Brahma", "OverAged",  " ","असम",  "कोकराझार", "प्रमिला रानी ब्रह्मा", " "}, 
{ "Assam",  "3489",  "Lakhimpur", "Probhu Lal Vaisnava", "NotGraduate",  " ","असम",  "लखीमपुर", "सुभु लाल वैष्णव", " "}, 
{ "Assam",  "3491",  "Lakhimpur", "Pradan Baruah", "ForeignFunding",  " ","असम",  "लखीमपुर", "प्रदन बरुआ", " "}, 
{ "Assam",  "3493",  "Lakhimpur", "Anil Borgohain", "ForeignFunding",  " ","असम",  "लखीमपुर", "अनिल बोर्गोहिन", " "}, 
{ "Assam",  "3495",  "Lakhimpur", "Ubaidur Rahman", "NotGraduate",  " ","असम",  "लखीमपुर", "उबैदुर रहमान", " "}, 
{ "Assam",  "3496",  "Lakhimpur", "Md Ambaz Uddin", "NotGraduate",  " ","असम",  "लखीमपुर", "एमडी अंदाज़ उद्दीन", " "}, 
{ "Assam",  "3497",  "Lakhimpur", "Amiya Kumar Handique", "OverAged",  " ","असम",  "लखीमपुर", "अमिय कुमार हांडिक", " "}, 
{ "Assam",  "3498",  "Lakhimpur", "Dilip Moran", "NotGraduate",  " ","असम",  "लखीमपुर", "दिलीप मोरन", " "}, 
{ "Assam",  "3441",  "Mangaldoi", "Bhubaneswar Kalita", "ForeignFunding",  " ","असम",  "मंगलदोई", "भुवनेश्वर कलिता", " "}, 
{ "Assam",  "3442",  "Mangaldoi", "Shri Dilip Saikia", "ForeignFunding",  " ","असम",  "मंगलदोई", "श्री दिलीप सैकिया", " "}, 
{ "Assam",  "3443",  "Mangaldoi", "Sri Biren Basak", "NotGraduate",  " ","असम",  "मंगलदोई", "श्री बिरेन बसाक", " "}, 
{ "Assam",  "3444",  "Mangaldoi", "Ainul Haque", "NotGraduate",  " ","असम",  "मंगलदोई", "आइनुल हक", " "}, 
{ "Assam",  "3448",  "Mangaldoi", "Mani Ram Basumatari", "NotGraduate",  " ","असम",  "मंगलदोई", "मणि राम बसुमतारी", " "}, 
{ "Assam",  "3450",  "Mangaldoi", "Gandheswar Mochahari", "NotGraduate",  " ","असम",  "मंगलदोई", "गंधेश्वर मोचाहारी", " "}, 
{ "Assam",  "3459",  "Nawgong", "Sri Rupak Sharma", "ForeignFunding",  " ","असम",  "नौगांव", "श्री रूपक शर्मा", " "}, 
{ "Assam",  "3460",  "Nawgong", "Pradyut Bordoloi", "ForeignFunding",  " ","असम",  "नौगांव", "प्रद्युत बोरदोलोई", " "}, 
{ "Assam",  "3461",  "Nawgong", "Sahadeb Das", "CriminalCases",  " ","असम",  "नौगांव", "सहदेब दास", " "}, 
{ "Assam",  "3463",  "Nawgong", "Azgor Ali", "NotGraduate",  " ","असम",  "नौगांव", "अज़गर अली", " "}, 
{ "Assam",  "3464",  "Nawgong", "Sukanta Mazumdar", "NotGraduate",  " ","असम",  "नौगांव", "सुकांत मजूमदार", " "}, 
{ "Assam",  "3422",  "Silchar", "Shyam Deo Kurmi", "OverAged",  " ","असम",  "सिलचर", "श्याम देव कुर्मी", " "}, 
{ "Assam",  "3424",  "Silchar", "Puran Lal Goala", "NotGraduate",  " ","असम",  "सिलचर", "पूरन लाल गोल", " "}, 
{ "Assam",  "3426",  "Silchar", "Rajdeep Roy", "ForeignFunding",  " ","असम",  "सिलचर", "राजदीप रॉय", " "}, 
{ "Assam",  "3427",  "Silchar", "Ashutosh Bhattacharjee", "NotGraduate",  " ","असम",  "सिलचर", "आशुतोष भट्टाचार्जी", " "}, 
{ "Assam",  "3428",  "Silchar", "Mohendra Chandra Das", "NotGraduate",  " ","असम",  "सिलचर", "मोहेंद्र चंद्र दास", " "}, 
{ "Assam",  "3429",  "Silchar", "Smt. Sushmita Dev", "ForeignFunding",  " ","असम",  "सिलचर", "श्रीमती। सुष्मिता देव", " "}, 
{ "Assam",  "3430",  "Silchar", "Nazmul Haque Laskar", "NotGraduate",  " ","असम",  "सिलचर", "नजमुल हक लस्कर", " "}, 
{ "Assam",  "3432",  "Silchar", "Hitabrata Roy", "OverAged",  " ","असम",  "सिलचर", "Hitabrata रॉय", " "}, 
{ "Assam",  "3433",  "Silchar", "Sabindra Das", "NotGraduate",  " ","असम",  "सिलचर", "सबिन्द्र दास", " "}, 
{ "Assam",  "3434",  "Silchar", "Shuvadip Datta", "NotGraduate",  " ","असम",  "सिलचर", "Shuvadip दत्ता", " "}, 
{ "Assam",  "3451",  "Tezpur", "Ziabur Rahman Khan", "CriminalCases",  " ","असम",  "तेजपुर", "ज़ियाबुर रहमान खान", " "}, 
{ "Assam",  "3452",  "Tezpur", "Bijoy Kumar Tiru", "OverAged",  " ","असम",  "तेजपुर", "बिजॉय कुमार तिरु", " "}, 
{ "Assam",  "3453",  "Tezpur", "M.G.V.K. Bhanu", "ForeignFunding",  " ","असम",  "तेजपुर", "एमजीवीके भानु", " "}, 
{ "Assam",  "3455",  "Tezpur", "Mahendra Bhuyan", "CriminalCases",  " ","असम",  "तेजपुर", "महेंद्र भुयान", " "}, 
{ "Assam",  "3456",  "Tezpur", "Mahendra Orang", "NotGraduate",  " ","असम",  "तेजपुर", "महेंद्र ओरंग", " "}, 
{ "Assam",  "3457",  "Tezpur", "Pallab Lochan Das", "ForeignFunding",  " ","असम",  "तेजपुर", "पल्लब लोचन दास", " "}, 
};

}