/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Assam {
public static final String[][] green_bucket = {
        {"Assam", "Autonomous District", "Holiram Terang", "Autonomous State Demand Committee", "5.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5922", "असम", "स्वायत्त जिला", "Holiram Terang", "स्वायत्त राज्य की मांग समिति"},
        {"Assam", "Barpeta", "Santanu Mukherjee", "Bharatiya Gana Parishad", "12.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9076", "असम", "बारपेटा", "संतनु मुखर्जी", "भारतीय गण परिषद"},
        {"Assam", "Barpeta", "Aroon Barooa", "Purvanchal Janta Party (Secular)", "7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9070", "असम", "बारपेटा", "आरोन बारोआ", "पूर्वांचल जनता पार्टी (सेक्युलर)"},
        {"Assam", "Barpeta", "Pranabjyoti Das Rajbonshi", "National Peoples Party", "34.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9073", "असम", "बारपेटा", "प्रणबज्योति दास राजबंशी", "नेशनल पीपुल्स पार्टी"},
        {"Assam", "Barpeta", "Saniara Parbin", "Voters Party International", "50.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9075", "असम", "बारपेटा", "सानीरा परबीन", "वोटर पार्टी इंटरनेशनल"},
        {"Assam", "Barpeta", "Chitralekha Das", "Socialist Unity Centre of India (Communist)", "22.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7840", "असम", "बारपेटा", "चित्रलेखा दास", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Assam", "Dhubri", "Alakesh Roy", "Hindusthan Nirman Dal", "25.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8229", "असम", "धुबरी", "अलकेश रॉय", "हिंदुस्तान निर्माण दल"},
        {"Assam", "Dhubri", "Anamika Sarkar", "Independent", "62Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8230", "असम", "धुबरी", "अनामिका सरकार", "निर्दलीय"},
        {"Assam", "Dhubri", "Johirul Islam Khan", "Purvanchal Janta Party (Secular)", "4.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9077", "असम", "धुबरी", "जोहिरुल इस्लाम खान", "पूर्वांचल जनता पार्टी (सेक्युलर)"},
        {"Assam", "Dhubri", "Shajahan Sheikh", "Voters Party International", "5.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7843", "असम", "धुबरी", "शाजहां शेख", "वोटर पार्टी इंटरनेशनल"},
        {"Assam", "Dhubri", "Zabed Islam", "Asom Gana Parishad", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8231", "असम", "धुबरी", "ज़ाबेद इस्लाम", "असोम गण परिषद"},
        {"Assam", "Dhubri", "Surat Jaman Mondal", "Socialist Unity Centre of India (Communist)", "16.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7842", "असम", "धुबरी", "सुरत जमन मोंडल", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Assam", "Dhubri", "Mir Hussain Sarkar", "Independent", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9078", "असम", "धुबरी", "मीर हुसैन सरकार", "निर्दलीय"},
        {"Assam", "Dibrugarh", "Md. Nurul Huda Imdadul Islam Saikia", "Independent", "70.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5585", "असम", "डिब्रूगढ़", "मो। नूरुल हुदा इमदादुल इस्लाम सैकिया", "निर्दलीय"},
        {"Assam", "Dibrugarh", "Apurba Saikia", "Independent", "6.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5589", "असम", "डिब्रूगढ़", "अपूर्वा सैकिया", "निर्दलीय"},
        {"Assam", "Dibrugarh", "Dr. Titus Bhengra", "Bahujan Mukti Party", "9.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5586", "असम", "डिब्रूगढ़", "डॉ। टाइटस भेंगरा", "बहुजन मुक्ति पार्टी"},
        {"Assam", "Gauhati", "Rajib Kakati", "Hindusthan Nirman Dal", "67.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8236", "असम", "गुवाहाटी", "राजिब काकती", "हिंदुस्तान निर्माण दल"},
        {"Assam", "Gauhati", "Upamanyu Hazarika", "Independent", "6.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8239", "असम", "गुवाहाटी", "उपमन्यु हजारिका", "निर्दलीय"},
        {"Assam", "Gauhati", "Rubi Neog", "National Republican Congress", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9094", "असम", "गुवाहाटी", "रूबी नेग", "नेशनल रिपब्लिकन कांग्रेस"},
        {"Assam", "Gauhati", "Pankaj Das", "Swarna Bharat Party", "6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7395", "असम", "गुवाहाटी", "पंकज दास", "स्वर्ण भारत पार्टी"},
        {"Assam", "Gauhati", "Utpal Borgohain", "Independent", "78Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9096", "असम", "गुवाहाटी", "उत्पल बोर्गोहिन", "निर्दलीय"},
        {"Assam", "Gauhati", "Alimuddin Ahmed", "Independent", "73.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9091", "असम", "गुवाहाटी", "अलीमुद्दीन अहमद", "निर्दलीय"},
        {"Assam", "Gauhati", "Partha Pratim Baruah", "Voters Party International", "67050", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8234", "असम", "गुवाहाटी", "पार्थ प्रतिम बरुआ", "वोटर पार्टी इंटरनेशनल"},
        {"Assam", "Gauhati", "Dr. Avijit Chakraborty", "Bharatiya Gana Parishad", "12.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7845", "असम", "गुवाहाटी", "डॉ। अविजीत चक्रवर्ती", "भारतीय गण परिषद"},
        {"Assam", "Gauhati", "Junmoni Devi Khaund", "Independent", "34.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8233", "असम", "गुवाहाटी", "जुमोनी देवी खुंद", "निर्दलीय"},
        {"Assam", "Gauhati", "Ratul Kumar Choudhury", "Samajwadi Party", "24.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8237", "असम", "गुवाहाटी", "रतुल कुमार चौधरी", "समाजवादी पार्टी"},
        {"Assam", "Jorhat", "Kanak Gogoi", "Communist Party of India", "23894", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4872", "असम", "जोरहाट", "कनक गोगोई", "भारतीय कम्युनिस्ट पार्टी"},
        {"Assam", "Jorhat", "Nandita Nag", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5583", "असम", "जोरहाट", "नंदिता नाग", "निर्दलीय"},
        {"Assam", "Jorhat", "Ribulaya Gogoi", "All India Trinamool Congress", "11.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5580", "असम", "जोरहाट", "रिबुल्या गोगोई", "अखिल भारतीय तृणमूल कांग्रेस"},
        {"Assam", "Kaliabor", "Md. Hariqul Islam Bhuyan", "Asom Jana Morcha", "38.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5573", "असम", "कलियाबोर", "मो। हरिकुल इस्लाम भुइयां", "अस जन जन मोर्चा"},
        {"Assam", "Kaliabor", "Abdul Aziz", "National People's Party", "35.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5575", "असम", "कलियाबोर", "अब्दुल अजीज", "नेशनल पीपुल्स पार्टी"},
        {"Assam", "Kaliabor", "Moni Madhab Mahanta", "Asom Gana Parishad", "27.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5576", "असम", "कलियाबोर", "मोनी माधब महंत", "असोम गण परिषद"},
        {"Assam", "Karimganj", "Raju Das", "Independent", "7.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5904", "असम", "करीमगंज", "राजू दास", "निर्दलीय"},
        {"Assam", "Kokrajhar", "Ranjoy Kr. Brahma", "Independent", "1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9068", "असम", "कोकराझार", "रणजॉय क्र। ब्रह्मा", "निर्दलीय"},
        {"Assam", "Kokrajhar", "Urkhao Gwra Brahma", "United Peoples Party, Liberal", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8243", "असम", "कोकराझार", "उरखो ग्वाला ब्रह्मा", "यूनाइटेड पीपल्स पार्टी, लिबरल"},
        {"Assam", "Kokrajhar", "Biraj Deka", "Communist Party of India (Marxist)", "15.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7848", "असम", "कोकराझार", "बिराज डेका", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
        {"Assam", "Lakhimpur", "Hem Kanta Miri", "Socialist Unity Centre of India (Communist)", "2.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4874", "असम", "लखीमपुर", "हेम कांता मिरी", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Assam", "Lakhimpur", "Arup Kalita", "Communist Party of India", "25.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5376", "असम", "लखीमपुर", "अरूप कलिता", "भारतीय कम्युनिस्ट पार्टी"},
        {"Assam", "Lakhimpur", "Anup Pratim Borbaruah", "Nationalist Congress Party", "5.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5592", "असम", "लखीमपुर", "अनूप प्रतीम बोरबरुआ", "राष्ट्रवादी कांग्रेस पार्टी"},
        {"Assam", "Lakhimpur", "Bhupen Narah", "Voters Party International", "7.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5597", "असम", "लखीमपुर", "भूपेन नारह", "वोटर पार्टी इंटरनेशनल"},
        {"Assam", "Mangaldoi", "Swarnalata Chaliha", "Socialist Unity Centre of India (Communist)", "32900", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5927", "असम", "मंगलदोई", "स्वर्णलता चालिहा", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Assam", "Mangaldoi", "Prodeep Kumar Daimary", "Independent", "10.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5565", "असम", "मंगलदोई", "प्रोडीप कुमार दैमारी", "निर्दलीय"},
        {"Assam", "Mangaldoi", "Sudhendu Mohan Talukdar", "All India Trinamool Congress", "38.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5932", "असम", "मंगलदोई", "सुधेंदु मोहन तालुकदार", "अखिल भारतीय तृणमूल कांग्रेस"},
        {"Assam", "Mangaldoi", "Jayanta Kumar Kalita", "Independent", "41.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5928", "असम", "मंगलदोई", "जयंत कुमार कलिता", "निर्दलीय"},
        {"Assam", "Mangaldoi", "Kazi Nekib Ahmed", "Independent", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5931", "असम", "मंगलदोई", "काजी नेकिब अहमद", "निर्दलीय"},
        {"Assam", "Nawgong", "Saiful Islam Choudhury", "Asom Jana Morcha", "94.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5374", "असम", "नौगांव", "सैफुल इस्लाम चौधरी", "अस जन जन मोर्चा"},
        {"Assam", "Nawgong", "Zakir Hussain", "Independent", "41.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5938", "असम", "नौगांव", "जाकिर हुसैन", "निर्दलीय"},
        {"Assam", "Silchar", "Badrul Islam Barbhuiya", "All India Forward Bloc", "26.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5913", "असम", "सिलचर", "बदरुल इस्लाम बारबुइया", "ऑल इंडिया फॉरवर्ड ब्लॉक"},
        {"Assam", "Silchar", "Nazia Yasmin Mazumdar", "National People's Party", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5911", "असम", "सिलचर", "नाज़िया यास्मीन मजूमदार", "नेशनल पीपुल्स पार्टी"},
        {"Assam", "Silchar", "Ashitava Dutta", "Independent", "4.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5915", "असम", "सिलचर", "अश्वित दत्ता", "निर्दलीय"},
        {"Assam", "Tezpur", "Ram Bahadur Sunar", "National People's Party", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7957", "असम", "तेजपुर", "राम बहादुर सुनार", "नेशनल पीपुल्स पार्टी"},
};

public static final String[][] red_bucket = {
        {"Assam", "Autonomous District", "Biren Singh Engti", "1", " ", "असम", "स्वायत्त जिला", "बीरेन सिंह एंगती", " "},
        {"Assam", "Autonomous District", "Horen Sing Bey", "1", " ", "असम", "स्वायत्त जिला", "होरन गा बय", " "},
        {"Assam", "Autonomous District", "Lienkhochon", "4", " ", "असम", "स्वायत्त जिला", "Lienkhochon", " "},
        {"Assam", "Barpeta", "Kumar Deepak Das", "2", " ", "असम", "बारपेटा", "कुमार दीपक दास", " "},
        {"Assam", "Barpeta", "Matiar Rahman", "4", " ", "असम", "बारपेटा", "मतीर रहमान", " "},
        {"Assam", "Barpeta", "Bhadreswar Barman", "4", " ", "असम", "बारपेटा", "भद्रेश्वर बर्मन", " "},
        {"Assam", "Barpeta", "Rafiqul Islam", "2", " ", "असम", "बारपेटा", "रफीकुल इस्लाम", " "},
        {"Assam", "Barpeta", "Ashahak Ali Dewan", "3", " ", "असम", "बारपेटा", "अशक अली दीवान", " "},
        {"Assam", "Barpeta", "Arfan Ali", "4", " ", "असम", "बारपेटा", "अरफान अली", " "},
        {"Assam", "Barpeta", "Rejaul Karim", "4", " ", "असम", "बारपेटा", "रेजुल करीम", " "},
        {"Assam", "Barpeta", "Abdul Khaleque", "1", " ", "असम", "बारपेटा", "अब्दुल खलीक", " "},
        {"Assam", "Dhubri", "Abu Taher Bepari", "1", " ", "असम", "धुबरी", "अबू ताहिर बेपारी", " "},
        {"Assam", "Dhubri", "Shukur Ali", "4", " ", "असम", "धुबरी", "शुकुर अली", " "},
        {"Assam", "Dhubri", "Nripen Das", "4", " ", "असम", "धुबरी", "नृपेन दास", " "},
        {"Assam", "Dhubri", "Nurul Islam Choudhury", "3", " ", "असम", "धुबरी", "नुरुल इस्लाम चौधरी", " "},
        {"Assam", "Dhubri", "Uttam Kumar Ray", "2", " ", "असम", "धुबरी", "उत्तम कुमार रे", " "},
        {"Assam", "Dhubri", "Mehbubar Rahman", "4", " ", "असम", "धुबरी", "महबूब रहमान", " "},
        {"Assam", "Dhubri", "Badruddin Ajmal", "2", " ", "असम", "धुबरी", "बदरुद्दीन अजमल", " "},
        {"Assam", "Dhubri", "Rukunur Zaman", "4", " ", "असम", "धुबरी", "रुकुनुर ज़मान", " "},
        {"Assam", "Dibrugarh", "Rubul Buragohain", "4", " ", "असम", "डिब्रूगढ़", "रुबुल बुरगोहैन", " "},
        {"Assam", "Dibrugarh", "Israil Nanda", "4", " ", "असम", "डिब्रूगढ़", "इजरायल नंदा", " "},
        {"Assam", "Dibrugarh", "Paban Singh Ghatowar", "1", " ", "असम", "डिब्रूगढ़", "पबन सिंह घाटोवार", " "},
        {"Assam", "Dibrugarh", "Bhaben Baruah", "2", " ", "असम", "डिब्रूगढ़", "भाबें बरुआ", " "},
        {"Assam", "Dibrugarh", "Rameswar Teli", "1", " ", "असम", "डिब्रूगढ़", "रामेश्वर तेली", " "},
        {"Assam", "Gauhati", "Bobbeeta Sharma", "1", " ", "असम", "गुवाहाटी", "बोबीबेता शर्मा", " "},
        {"Assam", "Gauhati", "Sri Shankha Sinha", "4", " ", "असम", "गुवाहाटी", "श्री शंख सिन्हा", " "},
        {"Assam", "Gauhati", "Dr. Faruk Ahmed Bhuyan", "4", " ", "असम", "गुवाहाटी", "डॉ। फारुक अहमद भुयान", " "},
        {"Assam", "Gauhati", "Sadek Ali", "2", " ", "असम", "गुवाहाटी", "सादिक अली", " "},
        {"Assam", "Gauhati", "Queen Oja", "1", " ", "असम", "गुवाहाटी", "रानी ओजा", " "},
        {"Assam", "Gauhati", "Manoj Sharma", "2", " ", "असम", "गुवाहाटी", "मनोज शर्मा", " "},
        {"Assam", "Gauhati", "Mamoni Sarma", "4", " ", "असम", "गुवाहाटी", "मामोनी सरमा", " "},
        {"Assam", "Jorhat", "Kamala Raj Konwar", "4", " ", "असम", "जोरहाट", "कमला राज कोंवर", " "},
        {"Assam", "Jorhat", "Topon Kumar Gogoi", "1", " ", "असम", "जोरहाट", "टोपन कुमार गोगोई", " "},
        {"Assam", "Jorhat", "Raj Kumar Duwara", "4", " ", "असम", "जोरहाट", "राज कुमार दुवारा", " "},
        {"Assam", "Jorhat", "Arbin Kumar Boruah", "4", " ", "असम", "जोरहाट", "अर्बिन कुमार बोरुहा", " "},
        {"Assam", "Jorhat", "Sushanta Borgohain", "1", " ", "असम", "जोरहाट", "सुशांत बोर्गोहैन", " "},
        {"Assam", "Kaliabor", "Sri Bhaskar Sarmah", "4", " ", "असम", "कलियाबोर", "श्री भास्कर सरमाह", " "},
        {"Assam", "Kaliabor", "Sri Jiten Gogoi", "2", " ", "असम", "कलियाबोर", "श्री जितेन गोगोई", " "},
        {"Assam", "Kaliabor", "Shree Diganta Kumar Saikia", "2", " ", "असम", "कलियाबोर", "श्री दिगंत कुमार सैकिया", " "},
        {"Assam", "Kaliabor", "Gaurav Gogoi", "1", " ", "असम", "कलियाबोर", "गौरव गोगोई", " "},
        {"Assam", "Karimganj", "Nikhil Ranjan Das", "4", " ", "असम", "करीमगंज", "निखिल रंजन दास", " "},
        {"Assam", "Karimganj", "Kripanath Mallah", "1", " ", "असम", "करीमगंज", "कृपानथ मल्लाह", " "},
        {"Assam", "Karimganj", "Ajoy Kumar Sarkar", "4", " ", "असम", "करीमगंज", "अजॉय कुमार सरकार", " "},
        {"Assam", "Karimganj", "Probash Chandra Sarkar", "4", " ", "असम", "करीमगंज", "प्रोबेश चंद्र सरकार", " "},
        {"Assam", "Karimganj", "Parikshit Roy", "4", " ", "असम", "करीमगंज", "परीक्षित रॉय", " "},
        {"Assam", "Karimganj", "Anupam Singha", "4", " ", "असम", "करीमगंज", "अनुपम सिंहा", " "},
        {"Assam", "Karimganj", "Satyajit Das", "4", " ", "असम", "करीमगंज", "सत्यजीत दास", " "},
        {"Assam", "Karimganj", "Swarup Das", "1", " ", "असम", "करीमगंज", "स्वरूप दास", " "},
        {"Assam", "Karimganj", "Rabindra Chandra Das", "4", " ", "असम", "करीमगंज", "रवीन्द्र चंद्र दास", " "},
        {"Assam", "Karimganj", "Radheshyam Biswas", "3", " ", "असम", "करीमगंज", "राधेश्याम विश्वास", " "},
        {"Assam", "Karimganj", "Ramnarayan Suklabaidya", "4", " ", "असम", "करीमगंज", "रामनारायण सुकुलबैद्य", " "},
        {"Assam", "Karimganj", "Hiralal Rabidas", "4", " ", "असम", "करीमगंज", "हीरालाल रविदास", " "},
        {"Assam", "Karimganj", "Chandan Das", "4", " ", "असम", "करीमगंज", "चंदन दास", " "},
        {"Assam", "Kokrajhar", "Sabda Ram Rabha", "1", " ", "असम", "कोकराझार", "सबदा राम राभा", " "},
        {"Assam", "Kokrajhar", "Naba Kumar Sarania", "2", " ", "असम", "कोकराझार", "नाबा कुमार सरानिया", " "},
        {"Assam", "Kokrajhar", "Rajesh Narzary", "4", " ", "असम", "कोकराझार", "राजेश नारज़री", " "},
        {"Assam", "Kokrajhar", "Charan Iswary", "4", " ", "असम", "कोकराझार", "चरन इसवरी", " "},
        {"Assam", "Kokrajhar", "Prasanjit Kumar Das", "4", " ", "असम", "कोकराझार", "प्रसनजीत कुमार दास", " "},
        {"Assam", "Kokrajhar", "Pramila Rani Brahma", "3", " ", "असम", "कोकराझार", "प्रमिला रानी ब्रह्मा", " "},
        {"Assam", "Lakhimpur", "Probhu Lal Vaisnava", "4", " ", "असम", "लखीमपुर", "सुभु लाल वैष्णव", " "},
        {"Assam", "Lakhimpur", "Pradan Baruah", "1", " ", "असम", "लखीमपुर", "प्रदन बरुआ", " "},
        {"Assam", "Lakhimpur", "Anil Borgohain", "1", " ", "असम", "लखीमपुर", "अनिल बोर्गोहिन", " "},
        {"Assam", "Lakhimpur", "Ubaidur Rahman", "4", " ", "असम", "लखीमपुर", "उबैदुर रहमान", " "},
        {"Assam", "Lakhimpur", "Md Ambaz Uddin", "4", " ", "असम", "लखीमपुर", "एमडी अंदाज़ उद्दीन", " "},
        {"Assam", "Lakhimpur", "Amiya Kumar Handique", "3", " ", "असम", "लखीमपुर", "अमिय कुमार हांडिक", " "},
        {"Assam", "Lakhimpur", "Dilip Moran", "4", " ", "असम", "लखीमपुर", "दिलीप मोरन", " "},
        {"Assam", "Mangaldoi", "Bhubaneswar Kalita", "1", " ", "असम", "मंगलदोई", "भुवनेश्वर कलिता", " "},
        {"Assam", "Mangaldoi", "Shri Dilip Saikia", "1", " ", "असम", "मंगलदोई", "श्री दिलीप सैकिया", " "},
        {"Assam", "Mangaldoi", "Sri Biren Basak", "4", " ", "असम", "मंगलदोई", "श्री बिरेन बसाक", " "},
        {"Assam", "Mangaldoi", "Ainul Haque", "4", " ", "असम", "मंगलदोई", "आइनुल हक", " "},
        {"Assam", "Mangaldoi", "Mani Ram Basumatari", "4", " ", "असम", "मंगलदोई", "मणि राम बसुमतारी", " "},
        {"Assam", "Mangaldoi", "Gandheswar Mochahari", "4", " ", "असम", "मंगलदोई", "गंधेश्वर मोचाहारी", " "},
        {"Assam", "Nawgong", "Sri Rupak Sharma", "1", " ", "असम", "नौगांव", "श्री रूपक शर्मा", " "},
        {"Assam", "Nawgong", "Pradyut Bordoloi", "1", " ", "असम", "नौगांव", "प्रद्युत बोरदोलोई", " "},
        {"Assam", "Nawgong", "Sahadeb Das", "2", " ", "असम", "नौगांव", "सहदेब दास", " "},
        {"Assam", "Nawgong", "Azgor Ali", "4", " ", "असम", "नौगांव", "अज़गर अली", " "},
        {"Assam", "Nawgong", "Sukanta Mazumdar", "4", " ", "असम", "नौगांव", "सुकांत मजूमदार", " "},
        {"Assam", "Silchar", "Shyam Deo Kurmi", "3", " ", "असम", "सिलचर", "श्याम देव कुर्मी", " "},
        {"Assam", "Silchar", "Puran Lal Goala", "4", " ", "असम", "सिलचर", "पूरन लाल गोल", " "},
        {"Assam", "Silchar", "Rajdeep Roy", "1", " ", "असम", "सिलचर", "राजदीप रॉय", " "},
        {"Assam", "Silchar", "Ashutosh Bhattacharjee", "4", " ", "असम", "सिलचर", "आशुतोष भट्टाचार्जी", " "},
        {"Assam", "Silchar", "Mohendra Chandra Das", "4", " ", "असम", "सिलचर", "मोहेंद्र चंद्र दास", " "},
        {"Assam", "Silchar", "Smt. Sushmita Dev", "1", " ", "असम", "सिलचर", "श्रीमती। सुष्मिता देव", " "},
        {"Assam", "Silchar", "Nazmul Haque Laskar", "4", " ", "असम", "सिलचर", "नजमुल हक लस्कर", " "},
        {"Assam", "Silchar", "Hitabrata Roy", "3", " ", "असम", "सिलचर", "Hitabrata रॉय", " "},
        {"Assam", "Silchar", "Sabindra Das", "4", " ", "असम", "सिलचर", "सबिन्द्र दास", " "},
        {"Assam", "Silchar", "Shuvadip Datta", "4", " ", "असम", "सिलचर", "Shuvadip दत्ता", " "},
        {"Assam", "Tezpur", "Ziabur Rahman Khan", "2", " ", "असम", "तेजपुर", "ज़ियाबुर रहमान खान", " "},
        {"Assam", "Tezpur", "Bijoy Kumar Tiru", "3", " ", "असम", "तेजपुर", "बिजॉय कुमार तिरु", " "},
        {"Assam", "Tezpur", "M.G.V.K. Bhanu", "1", " ", "असम", "तेजपुर", "एमजीवीके भानु", " "},
        {"Assam", "Tezpur", "Mahendra Bhuyan", "2", " ", "असम", "तेजपुर", "महेंद्र भुयान", " "},
        {"Assam", "Tezpur", "Mahendra Orang", "4", " ", "असम", "तेजपुर", "महेंद्र ओरंग", " "},
        {"Assam", "Tezpur", "Pallab Lochan Das", "1", " ", "असम", "तेजपुर", "पल्लब लोचन दास", " "},
};

}