/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Bihar {
public static final String[][] green_bucket = {
        {"Bihar", "Araria", "Md Mobinul Haque", "Independent", "5.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9512", "बिहार", "अररिया", "मोद मोबिनुल हक", "निर्दलीय"},
        {"Bihar", "Araria", "Ram Narayan Bharti", "Bahujan Samaj Party", "69.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8159", "बिहार", "अररिया", "राम नारायण भारती", "बहुजन समाज पार्टी"},
        {"Bihar", "Aurangabad", "Jaya Balu Rajkundal", "Bahujan Samaj Party", "52.3Lac", "http://myneta.info/ls2014/candidate.php?candidate_id=8514", "बिहार", "औरंगाबाद बिहा", "जया बलु राजकुमार", "बहुजन समाज पार्टी"},
        {"Bihar", "Aurangabad", "Upendra Prasad", "Hindustani Awam Morcha (Secular)", "2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5392", "बिहार", "औरंगाबाद बिहा", "उपेंद्र प्रसाद", "हिंदुस्तानी आवाम मोर्चा (सेक्युलर)"},
        {"Bihar", "Aurangabad", "Santosh Kumar Sinha", "Independent", "12.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4611", "बिहार", "औरंगाबाद बिहा", "संतोष कुमार सिन्हा", "निर्दलीय"},
        {"Bihar", "Aurangabad", "Som Prakash", "Swaraj Party (Loktantrik)", "14.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4609", "बिहार", "औरंगाबाद बिहा", "सोम प्रकाश", "स्वराज पार्टी (लोकतांत्रिक)"},
        {"Bihar", "Aurangabad", "Avinash Kumar", "Peoples Party of India (Democratic)", "37.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4612", "बिहार", "औरंगाबाद बिहा", "अविनाश कुमार", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
        {"Bihar", "Aurangabad", "Dhirendra Kumar Singh", "Independent", "83.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4613", "बिहार", "औरंगाबाद बिहा", "धीरेन्द्र कुमार सिंह", "निर्दलीय"},
        {"Bihar", "Banka", "Kailash Prasad Singh", "Pragatishil Samajwadi Party (Lohia)", "38.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6003", "बिहार", "बांका", "कैलाश प्रसाद सिंह", "प्रगति समाजवादी पार्टी (लोहिया)"},
        {"Bihar", "Banka", "Sanjiv Kumar Kunal", "Independent", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5999", "बिहार", "बांका", "संजीव कुमार कुणाल", "निर्दलीय"},
        {"Bihar", "Begusarai", "Gaurav Kumar", "Bhartiya Lokmat Rashtrwadi Party", "4.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9790", "बिहार", "बेगूसराय", "गौरव कुमार", "भारतीय लोकमत राष्ट्रवादी पार्टी"},
        {"Bihar", "Bhagalpur", "Satyendra Kumar", "Aam Aadmi Party", "3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5975", "बिहार", "भागलपुर", "सत्येंद्र कुमार", "आम आदमी पार्टी"},
        {"Bihar", "Bhagalpur", "Sunil Kumar", "Independent", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5974", "बिहार", "भागलपुर", "सुनील कुमार", "निर्दलीय"},
        {"Bihar", "Bhagalpur", "Nurullah", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5603", "बिहार", "भागलपुर", "Nurullah", "निर्दलीय"},
        {"Bihar", "Gaya", "Dayanand Rajwanshi", "Moolniwasi Samaj Party", "4.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5608", "बिहार", "गया", "दयानंद राजवंशी", "मूलनिवासी समाज पार्टी"},
        {"Bihar", "Gaya", "Prakash Chandra", "Public Mission Party", "81.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5612", "बिहार", "गया", "प्रकाश चंद्र", "सार्वजनिक मिशन पार्टी"},
        {"Bihar", "Gaya", "Umesh Rajak", "Peoples Party of India (Democratic)", "1.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4691", "बिहार", "गया", "उमेश रजक", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
        {"Bihar", "Gaya", "Dilip Kumar", "Bahujan Samaj Party", "18.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5605", "बिहार", "गया", "दिलीप कुमार", "बहुजन समाज पार्टी"},
        {"Bihar", "Gaya", "Vijay Kumar Chaudhari", "Janta Dal Rashtravadi", "45.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5606", "बिहार", "गया", "विजय कुमार चौधरी", "जनता दल राष्ट्रवादी"},
        {"Bihar", "Jamui", "Balmiki Paswan", "Hindusthan Nirman Dal", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5637", "बिहार", "जमुई", "बाल्मीकि पासवान", "हिंदुस्तान निर्माण दल"},
        {"Bihar", "Jamui", "Virendra Kumar", "Independent", "2.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5632", "बिहार", "जमुई", "वीरेन्द्र कुमार", "निर्दलीय"},
        {"Bihar", "Jamui", "Subhash Paswan", "Independent", "17.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5639", "बिहार", "जमुई", "सुभाष पासवान", "निर्दलीय"},
        {"Bihar", "Jamui", "Vishnu Priya", "Bahujan Mukti Party", "88.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5636", "बिहार", "जमुई", "विष्णु प्रिया", "बहुजन मुक्ति पार्टी"},
        {"Bihar", "Jhanjharpur", "Surendra Prasad Suman", "All India Forward Bloc", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8157", "बिहार", "झंझारपुर", "सुरेन्द्र प्रसाद सुमन", "ऑल इंडिया फॉरवर्ड ब्लॉक"},
        {"Bihar", "Jhanjharpur", "Bipin Kumar Singhwait", "Independent", "55.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9146", "बिहार", "झंझारपुर", "बिपिन कुमार सिंहवात", "निर्दलीय"},
        {"Bihar", "Jhanjharpur", "Sanjay Bhartia", "Independent", "11.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7782", "बिहार", "झंझारपुर", "संजय भरतिया", "निर्दलीय"},
        {"Bihar", "Jhanjharpur", "Ramesh Kamat", "Aam Adhikar Morcha", "16.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7783", "बिहार", "झंझारपुर", "रमेश कामत", "आम पालन मोर्चा"},
        {"Bihar", "Jhanjharpur", "Raj Kumar Singh", "Bahujan Samaj Party", "8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8158", "बिहार", "झंझारपुर", "राज कुमार सिंह", "बहुजन समाज पार्टी"},
        {"Bihar", "Khagaria", "Sangram Kumar Sada", "Independent", "3.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9521", "बिहार", "खगरिया", "संग्राम कुमार सदा", "निर्दलीय"},
        {"Bihar", "Khagaria", "Priyadarshi Dinkar", "Independent", "3.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9520", "बिहार", "खगरिया", "प्रियदर्शी दिनकर", "निर्दलीय"},
        {"Bihar", "Khagaria", "Sandip Kumar Saket", "Shiv Sena", "80.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8150", "बिहार", "खगरिया", "संदीप कुमार साकेत", "शिवसेना"},
        {"Bihar", "Khagaria", "Upendra Sahani", "Rashtriya Jansambhavna Party", "3.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8147", "बिहार", "खगरिया", "उपेंद्र सहनी", "राष्ट्रीय जनसंवाद पार्टी"},
        {"Bihar", "Khagaria", "Kundan Kumar", "Independent", "4.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9517", "बिहार", "खगरिया", "कुंदन कुमार", "निर्दलीय"},
        {"Bihar", "Khagaria", "Vinay Kumar Varun", "Janhit Kisan Party", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7619", "बिहार", "खगरिया", "विनय कुमार वरुण", "जनहित किसान पार्टी"},
        {"Bihar", "Kishanganj", "Indra Deo Paswan", "Bahujan Samaj Party", "68.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5950", "बिहार", "किशनगंज", "इंद्र देव पासवान", "बहुजन समाज पार्टी"},
        {"Bihar", "Kishanganj", "Rajesh Kumar Dubey", "Independent", "5.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5944", "बिहार", "किशनगंज", "राजेश कुमार दुबे", "निर्दलीय"},
        {"Bihar", "Madhepura", "Vinay Kumar Mishra", "Independent", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8170", "बिहार", "मधेपुरा", "विनय कुमार मिश्र", "निर्दलीय"},
        {"Bihar", "Madhepura", "Mohammad Arshad Hussain", "Independent", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7622", "बिहार", "मधेपुरा", "मोहम्मद अरशद हुसैन", "निर्दलीय"},
        {"Bihar", "Madhepura", "Anil Bharti", "Rashtravadi Janata Party", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8168", "बिहार", "मधेपुरा", "अनिल भारती", "राष्ट्रवादी जनता पार्टी"},
        {"Bihar", "Madhepura", "Suman Kumar Jha", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7624", "बिहार", "मधेपुरा", "सुमन कुमार झा", "निर्दलीय"},
        {"Bihar", "Madhepura", "Suresh Kumar Bharti", "Asli Deshi Party", "3.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9523", "बिहार", "मधेपुरा", "सुरेश कुमार भारती", "असली देसी पार्टी"},
        {"Bihar", "Madhepura", "Jaykant Yadav", "Independent", "5.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9524", "बिहार", "मधेपुरा", "जयकांत यादव", "निर्दलीय"},
        {"Bihar", "Madhepura", "Rajiv Kumar Yadav", "Baliraja Party", "5.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8169", "बिहार", "मधेपुरा", "राजीव कुमार यादव", "बलिराजा पार्टी"},
        {"Bihar", "Munger", "Rajesh Kumar Ratnakar", "Independent", "16Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10158", "बिहार", "मुंगेर", "राजेश कुमार रत्नाकर", "निर्दलीय"},
        {"Bihar", "Munger", "Arbind Kumar Sharma", "Rashtriya Hind Sena", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10168", "बिहार", "मुंगेर", "अरबिंद कुमार शर्मा", "राष्ट्रीय हिंद सेना"},
        {"Bihar", "Munger", "Pranay Kumar", "Independent", "69.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10149", "बिहार", "मुंगेर", "प्रणय कुमार", "निर्दलीय"},
        {"Bihar", "Munger", "Krishna Murari Kumar", "Jan Adhikar Party", "44.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10153", "बिहार", "मुंगेर", "कृष्ण मुरारी कुमार", "जन अधिक्कार पार्टी"},
        {"Bihar", "Munger", "Amarjit Patel", "Independent", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10163", "बिहार", "मुंगेर", "अमरजीत पटेल", "निर्दलीय"},
        {"Bihar", "Munger", "Panchanand Singh", "Jago Hindustan Party", "66500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10162", "बिहार", "मुंगेर", "पंचानंद सिंह", "जागो हिंदुस्तान पार्टी"},
        {"Bihar", "Nawada", "Mokim Uddin", "Rashtriya Ulama Council", "73.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5619", "बिहार", "नवादा", "मोकिम उद्दीन", "राष्ट्रीय उलमा परिषद"},
        {"Bihar", "Nawada", "Tulsi Dayal", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4608", "बिहार", "नवादा", "तुलसी दयाल", "निर्दलीय"},
        {"Bihar", "Nawada", "Aditya Pradhan", "Peoples Party of India (Democratic)", "34.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5622", "बिहार", "नवादा", "आदित्य प्रधान", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
        {"Bihar", "Nawada", "Rajesh Kumar", "Independent", "62.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4693", "बिहार", "नवादा", "राजेश कुमार", "निर्दलीय"},
        {"Bihar", "Purnia", "Dr. Mritunjay Kumar Jha", "Independent", "14.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5103", "बिहार", "पूर्णिया", "डॉ मृत्युंजय कुमार झा", "निर्दलीय"},
        {"Bihar", "Purnia", "Sanoj Kumar Chauhan", "Bihar Lok Nirman Dal", "27.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5964", "बिहार", "पूर्णिया", "सनोज कुमार चौहान", "बिहार लोक निर्माण दल"},
        {"Bihar", "Samastipur", "Mantesh Kumar", "Bahujan Samaj Party", "25.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10175", "बिहार", "समस्तीपुर", "मंटेश कुमार", "बहुजन समाज पार्टी"},
        {"Bihar", "Samastipur", "Ratan Bihari", "Jan Adhikar Party", "7.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10176", "बिहार", "समस्तीपुर", "रतन बिहारी", "जन अधिक्कार पार्टी"},
        {"Bihar", "Samastipur", "Pinku Paswan", "Yuva Krantikari Party", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10189", "बिहार", "समस्तीपुर", "पिंकू पासवान", "युवा क्रांतिकारी पार्टी"},
        {"Bihar", "Samastipur", "Suraj Kumar Das", "Independent", "14.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10170", "बिहार", "समस्तीपुर", "सूरज कुमार दास", "निर्दलीय"},
        {"Bihar", "Samastipur", "Vidyanand Ram", "Wazib Adhikar Party", "5.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10181", "बिहार", "समस्तीपुर", "विद्यानंद राम", "वजीब अदिकार पार्टी"},
        {"Bihar", "Supaul", "Rajesh Kumar S/O Yugeshwar Sah", "Independent", "6.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10738", "बिहार", "सुपौल", "राजेश कुमार एस / ओ युगेश्वर साह", "निर्दलीय"},
        {"Bihar", "Supaul", "Deep Narayan Mandal", "Shiv Sena", "60.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9190", "बिहार", "सुपौल", "दीप नारायण मंडल", "शिवसेना"},
        {"Bihar", "Supaul", "Sudhakar Jha", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7628", "बिहार", "सुपौल", "सुधाकर झा", "निर्दलीय"},
        {"Bihar", "Supaul", "Sandeep Kumar Singh", "Independent", "6.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9197", "बिहार", "सुपौल", "संदीप कुमार सिंह", "निर्दलीय"},
        {"Bihar", "Supaul", "Binod Kumar Sahu", "Independent", "75.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7631", "बिहार", "सुपौल", "बिनोद कुमार साहू", "निर्दलीय"},
        {"Bihar", "Supaul", "Rajesh Kumar S/O Jawahar Lal Das", "Independent", "4.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8171", "बिहार", "सुपौल", "राजेश कुमार एस / ओ जवाहर लाल दास", "निर्दलीय"},
        {"Bihar", "Ujiarpur", "Sudhir Kumar Ray", "Independent", "68.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10196", "बिहार", "उजियारपुर", "सुधीर कुमार रे", "निर्दलीय"},
        {"Bihar", "Ujiarpur", "Manoj Kumar", "Janta Raj Vikas Party", "33.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10203", "बिहार", "उजियारपुर", "मनोज कुमार", "जनता राज विकास पार्टी"},
        {"Bihar", "Ujiarpur", "Navin Kumar", "Bahujan Samaj Party", "77Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10207", "बिहार", "उजियारपुर", "नवीन कुमार", "बहुजन समाज पार्टी"},
        {"Bihar", "Ujiarpur", "Dr Ajay Singh Almust", "Rashtriya Samta Party (Secular)", "43.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10205", "बिहार", "उजियारपुर", "डॉ। अजय सिंह सर्वशक्तिमान", "राष्ट्रीय समता पार्टी (धर्मनिरपेक्ष)"},
        {"Bihar", "Ujiarpur", "A M Izharul Haque", "Sathi Aur Aapka Faisala Party", "8.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10208", "बिहार", "उजियारपुर", "एएम इज़हारुल हक़", "सती और आप फसाला पार्टी"},
        {"Bihar", "Ujiarpur", "Jay Narayan Sah", "Bajjikanchal Vikas Party", "18.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10218", "बिहार", "उजियारपुर", "जय नारायण साह", "बज्जीांचल विकास पार्टी"},
        {"Bihar", "Ujiarpur", "Kumar Gaurav", "Jai Prakash Janata Dal", "8.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10198", "बिहार", "उजियारपुर", "कुमार गौरव", "जय प्रकाश जनता दल"},
};

public static final String[][] red_bucket = {
        {"Bihar", "Araria", "Md Matin", "2", " ", "बिहार", "अररिया", "मोद मतीन", " "},
        {"Bihar", "Araria", "Sudama Singh", "2", " ", "बिहार", "अररिया", "सुदामा सिंह", " "},
        {"Bihar", "Araria", "Mukesh Singh", "4", " ", "बिहार", "अररिया", "मुकेश सिंह", " "},
        {"Bihar", "Araria", "Abdul Wahid Khan", "2", " ", "बिहार", "अररिया", "अब्दुल वाहिद खान", " "},
        {"Bihar", "Araria", "Md Minhaz Alam", "4", " ", "बिहार", "अररिया", "एमडी मिन्हाज आलम", " "},
        {"Bihar", "Araria", "Sarfaraz Alam", "2", " ", "बिहार", "अररिया", "सरफराज आलम", " "},
        {"Bihar", "Araria", "Tarachand Paswan", "2", " ", "बिहार", "अररिया", "ताराचंद पासवान", " "},
        {"Bihar", "Araria", "Ramanand Rishideo", "3", " ", "बिहार", "अररिया", "रामानंद ऋषिदेव", " "},
        {"Bihar", "Araria", "Pradeep Kumar Singh", "1", " ", "बिहार", "अररिया", "प्रदीप कुमार सिंह", " "},
        {"Bihar", "Araria", "Shaheen Praveen", "2", " ", "बिहार", "अररिया", "शाहीन प्रवीण", " "},
        {"Bihar", "Aurangabad", "Sushil Kumar Singh", "1", " ", "बिहार", "औरंगाबाद बिहा", "सुशील कुमार सिंह", " "},
        {"Bihar", "Aurangabad", "Yogendra Ram", "4", " ", "बिहार", "औरंगाबाद बिहा", "योगेन्द्र राम", " "},
        {"Bihar", "Aurangabad", "Dr Dharmendra Kumar", "2", " ", "बिहार", "औरंगाबाद बिहा", "डॉ। धर्मेंद्र कुमार", " "},
        {"Bihar", "Aurangabad", "Naresh Yadav", "2", " ", "बिहार", "औरंगाबाद बिहा", "नरेश यादव", " "},
        {"Bihar", "Aurangabad", "Subhash Kisanrao Patil", "2", " ", "बिहार", "औरंगाबाद बिहा", "सुभाष किसानराव पाटिल", " "},
        {"Bihar", "Banka", "Pramod Singh Weldone", "2", " ", "बिहार", "बांका", "प्रमोद सिंह वेल्डन", " "},
        {"Bihar", "Banka", "Putul Kumari", "2", " ", "बिहार", "बांका", "पुतुल कुमारी", " "},
        {"Bihar", "Banka", "Jai Prakash Narayan Yadav", "2", " ", "बिहार", "बांका", "जय प्रकाश नारायण यादव", " "},
        {"Bihar", "Banka", "Rajkishor Prasad", "2", " ", "बिहार", "बांका", "राजकिशोर प्रसाद", " "},
        {"Bihar", "Banka", "Amarjeet Kumar", "2", " ", "बिहार", "बांका", "अमरजीत कुमार", " "},
        {"Bihar", "Banka", "Phesal Ansari", "4", " ", "बिहार", "बांका", "फ़ेसल अंसारी", " "},
        {"Bihar", "Banka", "Md. Mukhtar Alam", "4", " ", "बिहार", "बांका", "मो। मुख्तार आलम", " "},
        {"Bihar", "Banka", "Md. Rafique Alam", "2", " ", "बिहार", "बांका", "मो। रफीक आलम", " "},
        {"Bihar", "Banka", "Manoj Kumar Sah", "4", " ", "बिहार", "बांका", "मनोज कुमार साह", " "},
        {"Bihar", "Banka", "Neelu Devi", "4", " ", "बिहार", "बांका", "नीलू देवी", " "},
        {"Bihar", "Banka", "Umakant Yadav", "3", " ", "बिहार", "बांका", "उमाकांत यादव", " "},
        {"Bihar", "Banka", "Pravin Kumar Jha", "4", " ", "बिहार", "बांका", "प्रवीण कुमार झा", " "},
        {"Bihar", "Banka", "Mp Yadav", "4", " ", "बिहार", "बांका", "Mp यादव", " "},
        {"Bihar", "Banka", "Naresh Yadav", "4", " ", "बिहार", "बांका", "नरेश यादव", " "},
        {"Bihar", "Banka", "Pawan Thakur", "4", " ", "बिहार", "बांका", "पवन ठाकुर", " "},
        {"Bihar", "Banka", "Mritiunjay Roy", "4", " ", "बिहार", "बांका", "मृत्युंजय रॉय", " "},
        {"Bihar", "Banka", "Giridhari Yadav", "2", " ", "बिहार", "बांका", "गिरधारी यादव", " "},
        {"Bihar", "Banka", "Syed Alamdar Hussain", "2", " ", "बिहार", "बांका", "सैयद आलमदार हुसैन", " "},
        {"Bihar", "Begusarai", "Dhiraj Narain", "3", " ", "बिहार", "बेगूसराय", "धीरज नारायण", " "},
        {"Bihar", "Begusarai", "Giriraj Singh", "1", " ", "बिहार", "बेगूसराय", "गिरिराज सिंह", " "},
        {"Bihar", "Begusarai", "Md. Tanweer Hassan", "2", " ", "बिहार", "बेगूसराय", "एमडी। तनवीर हसन", " "},
        {"Bihar", "Begusarai", "Kanhaiya Kumar", "2", " ", "बिहार", "बेगूसराय", "कन्हैया कुमार", " "},
        {"Bihar", "Begusarai", "Amar Kumar", "2", " ", "बिहार", "बेगूसराय", "अमर कुमार", " "},
        {"Bihar", "Begusarai", "Shambhu Kumar Singh", "2", " ", "बिहार", "बेगूसराय", "शंभू कुमार सिंह", " "},
        {"Bihar", "Begusarai", "Saurabh", "4", " ", "बिहार", "बेगूसराय", "सौरभ", " "},
        {"Bihar", "Begusarai", "Umesh Patel", "4", " ", "बिहार", "बेगूसराय", "उमेश पटेल", " "},
        {"Bihar", "Begusarai", "Maksudan Paswan", "4", " ", "बिहार", "बेगूसराय", "मकसूदन पासवान", " "},
        {"Bihar", "Bhagalpur", "Abhishek Priyadarshi", "4", " ", "बिहार", "भागलपुर", "अभिषेक प्रियदर्शी", " "},
        {"Bihar", "Bhagalpur", "Deepak Kumar", "4", " ", "बिहार", "भागलपुर", "दीपक कुमार", " "},
        {"Bihar", "Bhagalpur", "Shailesh Kumar", "4", " ", "बिहार", "भागलपुर", "शैलेश कुमार", " "},
        {"Bihar", "Bhagalpur", "Sushil Kumar Das", "3", " ", "बिहार", "भागलपुर", "सुशील कुमार दास", " "},
        {"Bihar", "Bhagalpur", "Mohammad Ashiq Ibrahimi", "2", " ", "बिहार", "भागलपुर", "मोहम्मद आशिक इब्राहिमी", " "},
        {"Bihar", "Bhagalpur", "Ajay Kumar Mandal", "4", " ", "बिहार", "भागलपुर", "अजय कुमार मंडल", " "},
        {"Bihar", "Darbhanga", "Md. Mukhtar", "2", " ", "बिहार", "दरभंगा", "मो। मुख्तार", " "},
        {"Bihar", "Darbhanga", "Abdul Ajij", "2", " ", "बिहार", "दरभंगा", "अब्दुल अजीज", " "},
        {"Bihar", "Darbhanga", "Pankaj Kumar Singh", "4", " ", "बिहार", "दरभंगा", "पंकज कुमार सिंह", " "},
        {"Bihar", "Darbhanga", "Saroj Kumar Chaudhary", "2", " ", "बिहार", "दरभंगा", "सरोज कुमार चौधरी", " "},
        {"Bihar", "Darbhanga", "Abdul Bari Siddiqui", "3", " ", "बिहार", "दरभंगा", "अब्दुल बारी सिद्दीकी", " "},
        {"Bihar", "Darbhanga", "Gopaljee Thakur", "1", " ", "बिहार", "दरभंगा", "गोपालजी ठाकुर", " "},
        {"Bihar", "Darbhanga", "Saguni Ray", "4", " ", "बिहार", "दरभंगा", "सगुनी रे", " "},
        {"Bihar", "Darbhanga", "Sanjay Paswan", "2", " ", "बिहार", "दरभंगा", "संजय पासवान", " "},
        {"Bihar", "Gaya", "Shiv Shankar", "2", " ", "बिहार", "गया", "शिव शंकर", " "},
        {"Bihar", "Gaya", "Vijay Kumar", "2", " ", "बिहार", "गया", "विजय कुमार", " "},
        {"Bihar", "Gaya", "Rakesh Chaudhari", "4", " ", "बिहार", "गया", "राकेश चौधरी", " "},
        {"Bihar", "Gaya", "Giridhar Sapera", "4", " ", "बिहार", "गया", "गिरिधर सपेरा", " "},
        {"Bihar", "Gaya", "Din Dayal Bharti", "4", " ", "बिहार", "गया", "दीन दयाल भारती", " "},
        {"Bihar", "Gaya", "Sunil Paswan", "4", " ", "बिहार", "गया", "सुनील पासवान", " "},
        {"Bihar", "Gaya", "Jitan Ram Manjhi", "2", " ", "बिहार", "गया", "जीतन राम मांझी", " "},
        {"Bihar", "Gaya", "Rajesh Kumar Paswan", "4", " ", "बिहार", "गया", "राजेश कुमार पासवान", " "},
        {"Bihar", "Jamui", "Bhudeo Choudhary", "2", " ", "बिहार", "जमुई", "भूदेव चौधरी", " "},
        {"Bihar", "Jamui", "Pankaj Kumar Das", "4", " ", "बिहार", "जमुई", "पंकज कुमार दास", " "},
        {"Bihar", "Jamui", "Ajay Kumar", "2", " ", "बिहार", "जमुई", "अजय कुमार", " "},
        {"Bihar", "Jamui", "Chirag Kumar Paswan", "2", " ", "बिहार", "जमुई", "चिराग कुमार पासवान", " "},
        {"Bihar", "Jhanjharpur", "Prabhat Prasad", "3", " ", "बिहार", "झंझारपुर", "प्रभात प्रसाद", " "},
        {"Bihar", "Jhanjharpur", "Ganga Prasad Yadav", "2", " ", "बिहार", "झंझारपुर", "गंगा प्रसाद यादव", " "},
        {"Bihar", "Jhanjharpur", "Om Prakash Poddar", "2", " ", "बिहार", "झंझारपुर", "ओम प्रकाश पोद्दार", " "},
        {"Bihar", "Jhanjharpur", "Chhedi Ram", "4", " ", "बिहार", "झंझारपुर", "छेदी राम", " "},
        {"Bihar", "Jhanjharpur", "Lakshman Prasad Yadav", "4", " ", "बिहार", "झंझारपुर", "लक्ष्मण प्रसाद यादव", " "},
        {"Bihar", "Jhanjharpur", "Devendra Prasad Yadav", "3", " ", "बिहार", "झंझारपुर", "देवेंद्र प्रसाद यादव", " "},
        {"Bihar", "Jhanjharpur", "Ratneshwar Jha", "4", " ", "बिहार", "झंझारपुर", "रत्नेश्वर झा", " "},
        {"Bihar", "Jhanjharpur", "Ramanand Thakur", "2", " ", "बिहार", "झंझारपुर", "रामानंद ठाकुर", " "},
        {"Bihar", "Jhanjharpur", "Ramprit Mandal", "2", " ", "बिहार", "झंझारपुर", "रामप्रीत मंडल", " "},
        {"Bihar", "Jhanjharpur", "Ganpati Jha", "2", " ", "बिहार", "झंझारपुर", "गणपति झा", " "},
        {"Bihar", "Jhanjharpur", "Gulab Yadav", "2", " ", "बिहार", "झंझारपुर", "गुलाब यादव", " "},
        {"Bihar", "Jhanjharpur", "Bablu Gupta", "2", " ", "बिहार", "झंझारपुर", "बबलू गुप्ता", " "},
        {"Bihar", "Katihar", "Samir Kumar Jha", "4", " ", "बिहार", "कटिहार", "समीर कुमार झा", " "},
        {"Bihar", "Katihar", "Shivnandan Mandal", "3", " ", "बिहार", "कटिहार", "शिवनंदन मंडल", " "},
        {"Bihar", "Katihar", "Muhammad Shakur", "3", " ", "बिहार", "कटिहार", "मुहम्मद शकूर", " "},
        {"Bihar", "Katihar", "Ganga Kebat", "4", " ", "बिहार", "कटिहार", "गंगा केवट", " "},
        {"Bihar", "Katihar", "Basukinath Sah", "4", " ", "बिहार", "कटिहार", "बासुकीनाथ साह", " "},
        {"Bihar", "Katihar", "Abdur Rahman", "4", " ", "बिहार", "कटिहार", "अब्दुर रहमान", " "},
        {"Bihar", "Katihar", "Dulal Chandra Goswami", "2", " ", "बिहार", "कटिहार", "दुलाल चंद्र गोस्वामी", " "},
        {"Bihar", "Katihar", "Shah Tariq Anwar", "1", " ", "बिहार", "कटिहार", "शाह तारिक अनवर", " "},
        {"Bihar", "Katihar", "Marang Hansda", "4", " ", "बिहार", "कटिहार", "मारंग हांसदा", " "},
        {"Bihar", "Khagaria", "Parmanand Singh", "2", " ", "बिहार", "खगरिया", "परमानंद सिंह", " "},
        {"Bihar", "Khagaria", "Bandan Kumar Singh", "4", " ", "बिहार", "खगरिया", "बंदन कुमार सिंह", " "},
        {"Bihar", "Khagaria", "Ramakant Choudhari", "4", " ", "बिहार", "खगरिया", "रमाकांत चौधरी", " "},
        {"Bihar", "Khagaria", "Sobha Devi", "4", " ", "बिहार", "खगरिया", "सोभा देवी", " "},
        {"Bihar", "Khagaria", "Tej Bahadur Singh", "3", " ", "बिहार", "खगरिया", "तेज बहादुर सिंह", " "},
        {"Bihar", "Khagaria", "Sunil Yadav", "4", " ", "बिहार", "खगरिया", "सुनील यादव", " "},
        {"Bihar", "Khagaria", "Choudhary Mahbub Ali Kaisar", "2", " ", "बिहार", "खगरिया", "चौधरी महबूब अली कैसर", " "},
        {"Bihar", "Khagaria", "Shiv Narayan Singh", "4", " ", "बिहार", "खगरिया", "शिव नारायण सिंह", " "},
        {"Bihar", "Khagaria", "Madhuvala Devi", "4", " ", "बिहार", "खगरिया", "मधुवाला देवी", " "},
        {"Bihar", "Khagaria", "Nagendra Singh Tyagi", "2", " ", "बिहार", "खगरिया", "नागेंद्र सिंह त्यागी", " "},
        {"Bihar", "Khagaria", "Moni Kumar", "4", " ", "बिहार", "खगरिया", "मोनी कुमार", " "},
        {"Bihar", "Khagaria", "Umesh Chandra Bharti", "2", " ", "बिहार", "खगरिया", "उमेश चंद्र भारती", " "},
        {"Bihar", "Khagaria", "Mukesh Sahani", "2", " ", "बिहार", "खगरिया", "मुकेश सहनी", " "},
        {"Bihar", "Khagaria", "Dhirendra Choudhary", "4", " ", "बिहार", "खगरिया", "धीरेन्द्र चौधरी", " "},
        {"Bihar", "Kishanganj", "Syed Mahmood Ashraf", "2", " ", "बिहार", "किशनगंज", "सैयद महमूद अशरफ", " "},
        {"Bihar", "Kishanganj", "Javed Akhter", "2", " ", "बिहार", "किशनगंज", "जावेद अख्तर", " "},
        {"Bihar", "Kishanganj", "Haserul", "4", " ", "बिहार", "किशनगंज", "Haserul", " "},
        {"Bihar", "Kishanganj", "Chhote Lal Mahto", "4", " ", "बिहार", "किशनगंज", "छोटे लाल महतो", " "},
        {"Bihar", "Kishanganj", "Shukal Murmu", "4", " ", "बिहार", "किशनगंज", "शुकल मुर्मू", " "},
        {"Bihar", "Kishanganj", "Pradeep Kumar Singh", "4", " ", "बिहार", "किशनगंज", "प्रदीप कुमार सिंह", " "},
        {"Bihar", "Kishanganj", "Asad Alam", "4", " ", "बिहार", "किशनगंज", "असद आलम", " "},
        {"Bihar", "Kishanganj", "Alimuddin Ansari", "4", " ", "बिहार", "किशनगंज", "अलीमुद्दीन अंसारी", " "},
        {"Bihar", "Kishanganj", "Rajendra Paswan", "2", " ", "बिहार", "किशनगंज", "राजेंद्र पासवान", " "},
        {"Bihar", "Kishanganj", "Akhtarul Iman", "2", " ", "बिहार", "किशनगंज", "अख्तरुल ईमान", " "},
        {"Bihar", "Kishanganj", "Dr. Mohammad Jawed", "1", " ", "बिहार", "किशनगंज", "डॉ। मोहम्मद जावेद", " "},
        {"Bihar", "Kishanganj", "Azimuddin", "3", " ", "बिहार", "किशनगंज", "Azimuddin", " "},
        {"Bihar", "Madhepura", "Sharad Yadav", "2", " ", "बिहार", "मधेपुरा", "शरद यादव", " "},
        {"Bihar", "Madhepura", "Dinesh Chandra Yadav", "2", " ", "बिहार", "मधेपुरा", "दिनेश चंद्र यादव", " "},
        {"Bihar", "Madhepura", "Manoj Kumar Manda", "4", " ", "बिहार", "मधेपुरा", "मनोज कुमार मंदा", " "},
        {"Bihar", "Madhepura", "Umashankar", "4", " ", "बिहार", "मधेपुरा", "उमाशंकर", " "},
        {"Bihar", "Madhepura", "Rajesh Ranjan", "2", " ", "बिहार", "मधेपुरा", "राजेश रंजन", " "},
        {"Bihar", "Madhepura", "Rajo Sah", "4", " ", "बिहार", "मधेपुरा", "राजो साह", " "},
        {"Bihar", "Munger", "Santosh Kumar", "4", " ", "बिहार", "मुंगेर", "संतोष कुमार", " "},
        {"Bihar", "Munger", "Ajit Kumar", "4", " ", "बिहार", "मुंगेर", "अजीत कुमार", " "},
        {"Bihar", "Munger", "Dina Saw", "4", " ", "बिहार", "मुंगेर", "दीना देखा", " "},
        {"Bihar", "Munger", "Nilam Devi", "1", " ", "बिहार", "मुंगेर", "निलम देवी", " "},
        {"Bihar", "Munger", "Mahesh Ram", "4", " ", "बिहार", "मुंगेर", "महेश राम", " "},
        {"Bihar", "Munger", "Raushan Kumar", "4", " ", "बिहार", "मुंगेर", "रौशन कुमार", " "},
        {"Bihar", "Munger", "Kumar Navneet Himanshu", "2", " ", "बिहार", "मुंगेर", "कुमार नवनीत हिमांशु", " "},
        {"Bihar", "Munger", "Vikash Kumar Arya", "2", " ", "बिहार", "मुंगेर", "विकाश कुमार आर्य", " "},
        {"Bihar", "Munger", "Sanjay Kesari", "2", " ", "बिहार", "मुंगेर", "संजय केसरी", " "},
        {"Bihar", "Munger", "Suryoday Paswan", "2", " ", "बिहार", "मुंगेर", "सूर्योदय पासवान", " "},
        {"Bihar", "Munger", "Rajiv Ranjan Singh", "2", " ", "बिहार", "मुंगेर", "राजीव रंजन सिंह", " "},
        {"Bihar", "Munger", "Sonelal Kora", "4", " ", "बिहार", "मुंगेर", "सोनेलाल कोरा", " "},
        {"Bihar", "Munger", "Uchit Kumar", "4", " ", "बिहार", "मुंगेर", "उचित कुमार", " "},
        {"Bihar", "Nawada", "Prof. K.B. Prasad", "3", " ", "बिहार", "नवादा", "केबी प्रसाद", " "},
        {"Bihar", "Nawada", "Vishnu Dev Yadav", "3", " ", "बिहार", "नवादा", "विष्णु देव यादव", " "},
        {"Bihar", "Nawada", "Naresh Prasad", "2", " ", "बिहार", "नवादा", "नरेश प्रसाद", " "},
        {"Bihar", "Nawada", "Vijay Ram", "4", " ", "बिहार", "नवादा", "विजय राम", " "},
        {"Bihar", "Nawada", "Ranganathacharya", "2", " ", "बिहार", "नवादा", "Ranganathacharya", " "},
        {"Bihar", "Nawada", "Rakesh Raushan", "2", " ", "बिहार", "नवादा", "राकेश रौशन", " "},
        {"Bihar", "Nawada", "Nivedita Singh", "2", " ", "बिहार", "नवादा", "निवेदिता सिंह", " "},
        {"Bihar", "Nawada", "Chandan Singh", "2", " ", "बिहार", "नवादा", "चंदन सिंह", " "},
        {"Bihar", "Purnia", "Shobha Soren", "4", " ", "बिहार", "पूर्णिया", "शोभा सोरेन", " "},
        {"Bihar", "Purnia", "Md Akhtar Ali", "4", " ", "बिहार", "पूर्णिया", "एमडी अख्तर अली", " "},
        {"Bihar", "Purnia", "Rajiv Kumar Singh", "4", " ", "बिहार", "पूर्णिया", "राजीव कुमार सिंह", " "},
        {"Bihar", "Purnia", "Shubhash Kumar Thakur", "4", " ", "बिहार", "पूर्णिया", "शुभाष कुमार ठाकुर", " "},
        {"Bihar", "Purnia", "Uday Singh", "1", " ", "बिहार", "पूर्णिया", "उदय सिंह", " "},
        {"Bihar", "Purnia", "Arjun Singh", "2", " ", "बिहार", "पूर्णिया", "अर्जुन सिंह", " "},
        {"Bihar", "Purnia", "Ashok Kumar Singh", "4", " ", "बिहार", "पूर्णिया", "अशोक कुमार सिंह", " "},
        {"Bihar", "Purnia", "Jitendra Urab", "2", " ", "बिहार", "पूर्णिया", "जितेन्द्र उरब", " "},
        {"Bihar", "Purnia", "Santosh Kumar", "2", " ", "बिहार", "पूर्णिया", "संतोष कुमार", " "},
        {"Bihar", "Purnia", "Anirudh Mehta", "4", " ", "बिहार", "पूर्णिया", "अनिरुद्ध मेहता", " "},
        {"Bihar", "Purnia", "Ashok Kumar Sah", "2", " ", "बिहार", "पूर्णिया", "अशोक कुमार साह", " "},
        {"Bihar", "Purnia", "Manju Murmu", "4", " ", "बिहार", "पूर्णिया", "मंजू मुर्मू", " "},
        {"Bihar", "Purnia", "Sageer Ahmad", "4", " ", "बिहार", "पूर्णिया", "सगीर अहमद", " "},
        {"Bihar", "Purnia", "Rajesh Kumar", "4", " ", "बिहार", "पूर्णिया", "राजेश कुमार", " "},
        {"Bihar", "Samastipur", "Ramchandra Paswan", "2", " ", "बिहार", "समस्तीपुर", "रामचंद्र पासवान", " "},
        {"Bihar", "Samastipur", "Dr. Ashok Kumar", "1", " ", "बिहार", "समस्तीपुर", "डॉ। अशोक कुमार", " "},
        {"Bihar", "Samastipur", "Lalo Paswan", "4", " ", "बिहार", "समस्तीपुर", "लालो पासवान", " "},
        {"Bihar", "Samastipur", "Asha Devi", "2", " ", "बिहार", "समस्तीपुर", "आशा देवी", " "},
        {"Bihar", "Samastipur", "Vijay Kumar Ram", "4", " ", "बिहार", "समस्तीपुर", "विजय कुमार राम", " "},
        {"Bihar", "Samastipur", "Raj Kumar Ram", "2", " ", "बिहार", "समस्तीपुर", "राज कुमार राम", " "},
        {"Bihar", "Supaul", "Ranjeet Ranjan", "1", " ", "बिहार", "सुपौल", "रणजीत रंजन", " "},
        {"Bihar", "Supaul", "Md. Afroj Alam", "4", " ", "बिहार", "सुपौल", "मो। अफरोज आलम", " "},
        {"Bihar", "Supaul", "Dinesh Prasad Yadav", "2", " ", "बिहार", "सुपौल", "दिनेश प्रसाद यादव", " "},
        {"Bihar", "Supaul", "Satya Narayan Mehta", "2", " ", "बिहार", "सुपौल", "सत्य नारायण मेहता", " "},
        {"Bihar", "Supaul", "Sanjay Sardar", "4", " ", "बिहार", "सुपौल", "संजय सरदार", " "},
        {"Bihar", "Supaul", "Naveen Kumar Singh", "4", " ", "बिहार", "सुपौल", "नवीन कुमार सिंह", " "},
        {"Bihar", "Supaul", "Pramod Kumar Nirala", "2", " ", "बिहार", "सुपौल", "प्रमोद कुमार निराला", " "},
        {"Bihar", "Supaul", "Kiran Devi", "4", " ", "बिहार", "सुपौल", "किरण देवी", " "},
        {"Bihar", "Supaul", "Bhim Kumar Gupta", "4", " ", "बिहार", "सुपौल", "भीम कुमार गुप्ता", " "},
        {"Bihar", "Supaul", "Dileshwar Kamait", "2", " ", "बिहार", "सुपौल", "दिलेश्वर कामायत", " "},
        {"Bihar", "Supaul", "Anand Pathak", "2", " ", "बिहार", "सुपौल", "आनंद पाठक", " "},
        {"Bihar", "Supaul", "Krishandev Mandal", "2", " ", "बिहार", "सुपौल", "कृष्णदेव मंडल", " "},
        {"Bihar", "Supaul", "Sanjeet Kumar Chaudhary", "4", " ", "बिहार", "सुपौल", "संजीत कुमार चौधरी", " "},
        {"Bihar", "Supaul", "Mohammad Abul Kalam Azad", "4", " ", "बिहार", "सुपौल", "मोहम्मद अबुल कलाम आज़ाद", " "},
        {"Bihar", "Ujiarpur", "Pranav Kumar", "4", " ", "बिहार", "उजियारपुर", "प्रणव कुमार", " "},
        {"Bihar", "Ujiarpur", "Amrendra Kumar Yadav", "2", " ", "बिहार", "उजियारपुर", "अमरेन्द्र कुमार यादव", " "},
        {"Bihar", "Ujiarpur", "Nityanand Rai", "1", " ", "बिहार", "उजियारपुर", "नित्यानंद राय", " "},
        {"Bihar", "Ujiarpur", "Lalan Kumar Roy", "4", " ", "बिहार", "उजियारपुर", "ललन कुमार रॉय", " "},
        {"Bihar", "Ujiarpur", "Ramashray Thakur", "4", " ", "बिहार", "उजियारपुर", "रामाश्रय ठाकुर", " "},
        {"Bihar", "Ujiarpur", "Upendra Kushwaha", "2", " ", "बिहार", "उजियारपुर", "उपेंद्र कुशवाहा", " "},
        {"Bihar", "Ujiarpur", "Ajay Kumar", "2", " ", "बिहार", "उजियारपुर", "अजय कुमार", " "},
        {"Bihar", "Ujiarpur", "Allamaa Shiblee Nomani Halami", "4", " ", "बिहार", "उजियारपुर", "अल्लामा शिब्ली नोमानी हलामी", " "},
        {"Bihar", "Ujiarpur", "Raj Kumar Chauhan", "4", " ", "बिहार", "उजियारपुर", "राज कुमार चौहान", " "},
        {"Bihar", "Ujiarpur", "Md. Anwar", "2", " ", "बिहार", "उजियारपुर", "अनवर अनवर", " "},
        {"Bihar", "Ujiarpur", "Mamta Kumari", "2", " ", "बिहार", "उजियारपुर", "ममता कुमारी", " "},
};

}