/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Bihar {
public static final String[][] green_bucket = {
{"Bihar",  "6521", "Araria", "Md Mobinul Haque", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9512",  "बिहार",  "अररिया", "मोद मोबिनुल हक", "निर्दलीय", ""}, 
{"Bihar",  "6524", "Araria", "Ram Narayan Bharti", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8159",  "बिहार",  "अररिया", "राम नारायण भारती", "बहुजन समाज पार्टी", ""}, 
{"Bihar",  "3568", "Aurangabad", "Jaya Balu Rajkundal", "Bahujan Samaj Party", "http://myneta.info/ls2014/candidate.php?candidate_id=8514",  "बिहार",  "औरंगाबाद बिहा", "जया बलु राजकुमार", "बहुजन समाज पार्टी", ""}, 
{"Bihar",  "3570", "Aurangabad", "Upendra Prasad", "Hindustani Awam Morcha (Secular)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5392",  "बिहार",  "औरंगाबाद बिहा", "उपेंद्र प्रसाद", "हिंदुस्तानी आवाम मोर्चा (सेक्युलर)", ""}, 
{"Bihar",  "3571", "Aurangabad", "Santosh Kumar Sinha", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4611",  "बिहार",  "औरंगाबाद बिहा", "संतोष कुमार सिन्हा", "निर्दलीय", ""}, 
{"Bihar",  "3573", "Aurangabad", "Som Prakash", "Swaraj Party (Loktantrik)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4609",  "बिहार",  "औरंगाबाद बिहा", "सोम प्रकाश", "स्वराज पार्टी (लोकतांत्रिक)", ""}, 
{"Bihar",  "3575", "Aurangabad", "Avinash Kumar", "Peoples Party of India (Democratic)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4612",  "बिहार",  "औरंगाबाद बिहा", "अविनाश कुमार", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", ""}, 
{"Bihar",  "3576", "Aurangabad", "Dhirendra Kumar Singh", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4613",  "बिहार",  "औरंगाबाद बिहा", "धीरेन्द्र कुमार सिंह", "निर्दलीय", ""}, 
{"Bihar",  "3560", "Banka", "Kailash Prasad Singh", "Pragatishil Samajwadi Party (Lohia)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6003",  "बिहार",  "बांका", "कैलाश प्रसाद सिंह", "प्रगति समाजवादी पार्टी (लोहिया)", ""}, 
{"Bihar",  "3564", "Banka", "Sanjiv Kumar Kunal", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5999",  "बिहार",  "बांका", "संजीव कुमार कुणाल", "निर्दलीय", ""}, 
{"Bihar",  "3538", "Bhagalpur", "Satyendra Kumar", "Aam Aadmi Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5975",  "बिहार",  "भागलपुर", "सत्येंद्र कुमार", "आम आदमी पार्टी", ""}, 
{"Bihar",  "3539", "Bhagalpur", "Sunil Kumar", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5974",  "बिहार",  "भागलपुर", "सुनील कुमार", "निर्दलीय", ""}, 
{"Bihar",  "3544", "Bhagalpur", "Nurullah", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5603",  "बिहार",  "भागलपुर", "Nurullah", "निर्दलीय", ""}, 
{"Bihar",  "3585", "Gaya", "Dayanand Rajwanshi", "Moolniwasi Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5608",  "बिहार",  "गया", "दयानंद राजवंशी", "मूलनिवासी समाज पार्टी", ""}, 
{"Bihar",  "3588", "Gaya", "Prakash Chandra", "Public Mission Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5612",  "बिहार",  "गया", "प्रकाश चंद्र", "सार्वजनिक मिशन पार्टी", ""}, 
{"Bihar",  "3590", "Gaya", "Umesh Rajak", "Peoples Party of India (Democratic)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4691",  "बिहार",  "गया", "उमेश रजक", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", ""}, 
{"Bihar",  "3579", "Gaya", "Dilip Kumar", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5605",  "बिहार",  "गया", "दिलीप कुमार", "बहुजन समाज पार्टी", ""}, 
{"Bihar",  "3582", "Gaya", "Vijay Kumar Chaudhari", "Janta Dal Rashtravadi", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5606",  "बिहार",  "गया", "विजय कुमार चौधरी", "जनता दल राष्ट्रवादी", ""}, 
{"Bihar",  "3604", "Jamui", "Balmiki Paswan", "Hindusthan Nirman Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5637",  "बिहार",  "जमुई", "बाल्मीकि पासवान", "हिंदुस्तान निर्माण दल", ""}, 
{"Bihar",  "3606", "Jamui", "Virendra Kumar", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5632",  "बिहार",  "जमुई", "वीरेन्द्र कुमार", "निर्दलीय", ""}, 
{"Bihar",  "3607", "Jamui", "Subhash Paswan", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5639",  "बिहार",  "जमुई", "सुभाष पासवान", "निर्दलीय", ""}, 
{"Bihar",  "3609", "Jamui", "Vishnu Priya", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5636",  "बिहार",  "जमुई", "विष्णु प्रिया", "बहुजन मुक्ति पार्टी", ""}, 
{"Bihar",  "6482", "Jhanjharpur", "Surendra Prasad Suman", "All India Forward Bloc", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8157",  "बिहार",  "झंझारपुर", "सुरेन्द्र प्रसाद सुमन", "ऑल इंडिया फॉरवर्ड ब्लॉक", ""}, 
{"Bihar",  "6489", "Jhanjharpur", "Bipin Kumar Singhwait", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9146",  "बिहार",  "झंझारपुर", "बिपिन कुमार सिंहवात", "निर्दलीय", ""}, 
{"Bihar",  "6491", "Jhanjharpur", "Sanjay Bhartia", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7782",  "बिहार",  "झंझारपुर", "संजय भरतिया", "निर्दलीय", ""}, 
{"Bihar",  "6492", "Jhanjharpur", "Ramesh Kamat", "Aam Adhikar Morcha", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7783",  "बिहार",  "झंझारपुर", "रमेश कामत", "", ""}, 
{"Bihar",  "6497", "Jhanjharpur", "Raj Kumar Singh", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8158",  "बिहार",  "झंझारपुर", "राज कुमार सिंह", "बहुजन समाज पार्टी", ""}, 
{"Bihar",  "6546", "Khagaria", "Sangram Kumar Sada", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9521",  "बिहार",  "खगरिया", "संग्राम कुमार सदा", "निर्दलीय", ""}, 
{"Bihar",  "6552", "Khagaria", "Priyadarshi Dinkar", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9520",  "बिहार",  "खगरिया", "प्रियदर्शी दिनकर", "निर्दलीय", ""}, 
{"Bihar",  "6556", "Khagaria", "Sandip Kumar Saket", "Shiv Sena", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8150",  "बिहार",  "खगरिया", "संदीप कुमार साकेत", "शिवसेना", ""}, 
{"Bihar",  "6559", "Khagaria", "Kundan Kumar", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9517",  "बिहार",  "खगरिया", "कुंदन कुमार", "निर्दलीय", ""}, 
{"Bihar",  "6562", "Khagaria", "Vinay Kumar Varun", "Janhit Kisan Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7619",  "बिहार",  "खगरिया", "विनय कुमार वरुण", "", ""}, 
{"Bihar",  "3499", "Kishanganj", "Indra Deo Paswan", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5950",  "बिहार",  "किशनगंज", "इंद्र देव पासवान", "बहुजन समाज पार्टी", ""}, 
{"Bihar",  "3504", "Kishanganj", "Rajesh Kumar Dubey", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5944",  "बिहार",  "किशनगंज", "राजेश कुमार दुबे", "निर्दलीय", ""}, 
{"Bihar",  "6531", "Madhepura", "Vinay Kumar Mishra", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8170",  "बिहार",  "मधेपुरा", "विनय कुमार मिश्र", "निर्दलीय", ""}, 
{"Bihar",  "6532", "Madhepura", "Mohammad Arshad Hussain", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7622",  "बिहार",  "मधेपुरा", "मोहम्मद अरशद हुसैन", "निर्दलीय", ""}, 
{"Bihar",  "6533", "Madhepura", "Anil Bharti", "Rashtravadi Janata Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8168",  "बिहार",  "मधेपुरा", "अनिल भारती", "", ""}, 
{"Bihar",  "6534", "Madhepura", "Suman Kumar Jha", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7624",  "बिहार",  "मधेपुरा", "सुमन कुमार झा", "निर्दलीय", ""}, 
{"Bihar",  "6536", "Madhepura", "Suresh Kumar Bharti", "Asli Deshi Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9523",  "बिहार",  "मधेपुरा", "सुरेश कुमार भारती", "", ""}, 
{"Bihar",  "6540", "Madhepura", "Jaykant Yadav", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9524",  "बिहार",  "मधेपुरा", "जयकांत यादव", "निर्दलीय", ""}, 
{"Bihar",  "6542", "Madhepura", "Rajiv Kumar Yadav", "Baliraja Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8169",  "बिहार",  "मधेपुरा", "राजीव कुमार यादव", "बलिराजा पार्टी", ""}, 
{"Bihar",  "3596", "Nawada", "Mokim Uddin", "Rashtriya Ulama Council", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5619",  "बिहार",  "नवादा", "मोकिम उद्दीन", "राष्ट्रीय उलमा परिषद", ""}, 
{"Bihar",  "3597", "Nawada", "Tulsi Dayal", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4608",  "बिहार",  "नवादा", "तुलसी दयाल", "निर्दलीय", ""}, 
{"Bihar",  "3599", "Nawada", "Aditya Pradhan", "Peoples Party of India (Democratic)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5622",  "बिहार",  "नवादा", "आदित्य प्रधान", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", ""}, 
{"Bihar",  "3601", "Nawada", "Rajesh Kumar", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4693",  "बिहार",  "नवादा", "राजेश कुमार", "निर्दलीय", ""}, 
{"Bihar",  "3532", "Purnia", "Dr. Mritunjay Kumar Jha", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5103",  "बिहार",  "पूर्णिया", "डॉ मृत्युंजय कुमार झा", "निर्दलीय", ""}, 
{"Bihar",  "3534", "Purnia", "Sanoj Kumar Chauhan", "Bihar Lok Nirman Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5964",  "बिहार",  "पूर्णिया", "सनोज कुमार चौहान", "बिहार लोक निर्माण दल", ""}, 
{"Bihar",  "6500", "Supaul", "Rajesh Kumar S/O Yugeshwar Sah", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10738",  "बिहार",  "सुपौल", "राजेश कुमार एस / ओ युगेश्वर साह", "निर्दलीय", ""}, 
{"Bihar",  "6501", "Supaul", "Deep Narayan Mandal", "Shiv Sena", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9190",  "बिहार",  "सुपौल", "दीप नारायण मंडल", "शिवसेना", ""}, 
{"Bihar",  "6504", "Supaul", "Sudhakar Jha", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7628",  "बिहार",  "सुपौल", "सुधाकर झा", "निर्दलीय", ""}, 
{"Bihar",  "6505", "Supaul", "Sandeep Kumar Singh", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9197",  "बिहार",  "सुपौल", "संदीप कुमार सिंह", "निर्दलीय", ""}, 
{"Bihar",  "6510", "Supaul", "Binod Kumar Sahu", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7631",  "बिहार",  "सुपौल", "बिनोद कुमार साहू", "निर्दलीय", ""}, 
{"Bihar",  "6512", "Supaul", "Rajesh Kumar S/O Jawahar Lal Das", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8171",  "बिहार",  "सुपौल", "राजेश कुमार एस / ओ जवाहर लाल दास", "निर्दलीय", ""}, 
};

public static final String[][] red_bucket = {
{ "Bihar",  "6518",  "Araria", "Md Matin", "CriminalCases",  " ","बिहार",  "अररिया", "मोद मतीन", " "}, 
{ "Bihar",  "6519",  "Araria", "Sudama Singh", "CriminalCases",  " ","बिहार",  "अररिया", "सुदामा सिंह", " "}, 
{ "Bihar",  "6520",  "Araria", "Mukesh Singh", "NotGraduate",  " ","बिहार",  "अररिया", "मुकेश सिंह", " "}, 
{ "Bihar",  "6522",  "Araria", "Abdul Wahid Khan", "CriminalCases",  " ","बिहार",  "अररिया", "अब्दुल वाहिद खान", " "}, 
{ "Bihar",  "6523",  "Araria", "Md Minhaz Alam", "NotGraduate",  " ","बिहार",  "अररिया", "एमडी मिन्हाज आलम", " "}, 
{ "Bihar",  "6525",  "Araria", "Sarfaraz Alam", "CriminalCases",  " ","बिहार",  "अररिया", "सरफराज आलम", " "}, 
{ "Bihar",  "6526",  "Araria", "Tarachand Paswan", "CriminalCases",  " ","बिहार",  "अररिया", "ताराचंद पासवान", " "}, 
{ "Bihar",  "6527",  "Araria", "Ramanand Rishideo", "OverAged",  " ","बिहार",  "अररिया", "रामानंद ऋषिदेव", " "}, 
{ "Bihar",  "6528",  "Araria", "Pradeep Kumar Singh", "ForeignFunding",  " ","बिहार",  "अररिया", "प्रदीप कुमार सिंह", " "}, 
{ "Bihar",  "6529",  "Araria", "Shaheen Praveen", "CriminalCases",  " ","बिहार",  "अररिया", "शाहीन प्रवीण", " "}, 
{ "Bihar",  "3567",  "Aurangabad", "Sushil Kumar Singh", "ForeignFunding",  " ","बिहार",  "औरंगाबाद बिहा", "सुशील कुमार सिंह", " "}, 
{ "Bihar",  "3569",  "Aurangabad", "Yogendra Ram", "NotGraduate",  " ","बिहार",  "औरंगाबाद बिहा", "योगेन्द्र राम", " "}, 
{ "Bihar",  "3572",  "Aurangabad", "Dr Dharmendra Kumar", "CriminalCases",  " ","बिहार",  "औरंगाबाद बिहा", "डॉ। धर्मेंद्र कुमार", " "}, 
{ "Bihar",  "3574",  "Aurangabad", "Naresh Yadav", "CriminalCases",  " ","बिहार",  "औरंगाबाद बिहा", "नरेश यादव", " "}, 
{ "Bihar",  "3577",  "Aurangabad", "Subhash Kisanrao Patil", "CriminalCases",  " ","बिहार",  "औरंगाबाद बिहा", "सुभाष किसानराव पाटिल", " "}, 
{ "Bihar",  "3547",  "Banka", "Pramod Singh Weldone", "CriminalCases",  " ","बिहार",  "बांका", "प्रमोद सिंह वेल्डन", " "}, 
{ "Bihar",  "3548",  "Banka", "Putul Kumari", "CriminalCases",  " ","बिहार",  "बांका", "पुतुल कुमारी", " "}, 
{ "Bihar",  "3549",  "Banka", "Jai Prakash Narayan Yadav", "CriminalCases",  " ","बिहार",  "बांका", "जय प्रकाश नारायण यादव", " "}, 
{ "Bihar",  "3550",  "Banka", "Rajkishor Prasad", "CriminalCases",  " ","बिहार",  "बांका", "राजकिशोर प्रसाद", " "}, 
{ "Bihar",  "3551",  "Banka", "Amarjeet Kumar", "CriminalCases",  " ","बिहार",  "बांका", "अमरजीत कुमार", " "}, 
{ "Bihar",  "3552",  "Banka", "Phesal Ansari", "NotGraduate",  " ","बिहार",  "बांका", "फ़ेसल अंसारी", " "}, 
{ "Bihar",  "3553",  "Banka", "Md. Mukhtar Alam", "NotGraduate",  " ","बिहार",  "बांका", "मो। मुख्तार आलम", " "}, 
{ "Bihar",  "3554",  "Banka", "Md. Rafique Alam", "CriminalCases",  " ","बिहार",  "बांका", "मो। रफीक आलम", " "}, 
{ "Bihar",  "3555",  "Banka", "Manoj Kumar Sah", "NotGraduate",  " ","बिहार",  "बांका", "मनोज कुमार साह", " "}, 
{ "Bihar",  "3556",  "Banka", "Neelu Devi", "NotGraduate",  " ","बिहार",  "बांका", "नीलू देवी", " "}, 
{ "Bihar",  "3557",  "Banka", "Umakant Yadav", "OverAged",  " ","बिहार",  "बांका", "उमाकांत यादव", " "}, 
{ "Bihar",  "3558",  "Banka", "Pravin Kumar Jha", "NotGraduate",  " ","बिहार",  "बांका", "प्रवीण कुमार झा", " "}, 
{ "Bihar",  "3559",  "Banka", "Mp Yadav", "NotGraduate",  " ","बिहार",  "बांका", "Mp यादव", " "}, 
{ "Bihar",  "3561",  "Banka", "Naresh Yadav", "NotGraduate",  " ","बिहार",  "बांका", "नरेश यादव", " "}, 
{ "Bihar",  "3562",  "Banka", "Pawan Thakur", "NotGraduate",  " ","बिहार",  "बांका", "पवन ठाकुर", " "}, 
{ "Bihar",  "3563",  "Banka", "Mritiunjay Roy", "NotGraduate",  " ","बिहार",  "बांका", "मृत्युंजय रॉय", " "}, 
{ "Bihar",  "3565",  "Banka", "Giridhari Yadav", "CriminalCases",  " ","बिहार",  "बांका", "गिरधारी यादव", " "}, 
{ "Bihar",  "3566",  "Banka", "Syed Alamdar Hussain", "CriminalCases",  " ","बिहार",  "बांका", "सैयद आलमदार हुसैन", " "}, 
{ "Bihar",  "3540",  "Bhagalpur", "Abhishek Priyadarshi", "NotGraduate",  " ","बिहार",  "भागलपुर", "अभिषेक प्रियदर्शी", " "}, 
{ "Bihar",  "3541",  "Bhagalpur", "Deepak Kumar", "NotGraduate",  " ","बिहार",  "भागलपुर", "दीपक कुमार", " "}, 
{ "Bihar",  "3542",  "Bhagalpur", "Shailesh Kumar", "NotGraduate",  " ","बिहार",  "भागलपुर", "शैलेश कुमार", " "}, 
{ "Bihar",  "3543",  "Bhagalpur", "Sushil Kumar Das", "OverAged",  " ","बिहार",  "भागलपुर", "सुशील कुमार दास", " "}, 
{ "Bihar",  "3545",  "Bhagalpur", "Mohammad Ashiq Ibrahimi", "CriminalCases",  " ","बिहार",  "भागलपुर", "मोहम्मद आशिक इब्राहिमी", " "}, 
{ "Bihar",  "3546",  "Bhagalpur", "Ajay Kumar Mandal", "NotGraduate",  " ","बिहार",  "भागलपुर", "अजय कुमार मंडल", " "}, 
{ "Bihar",  "3584",  "Gaya", "Shiv Shankar", "CriminalCases",  " ","बिहार",  "गया", "शिव शंकर", " "}, 
{ "Bihar",  "3586",  "Gaya", "Vijay Kumar", "CriminalCases",  " ","बिहार",  "गया", "विजय कुमार", " "}, 
{ "Bihar",  "3587",  "Gaya", "Rakesh Chaudhari", "NotGraduate",  " ","बिहार",  "गया", "राकेश चौधरी", " "}, 
{ "Bihar",  "3589",  "Gaya", "Giridhar Sapera", "NotGraduate",  " ","बिहार",  "गया", "गिरिधर सपेरा", " "}, 
{ "Bihar",  "3578",  "Gaya", "Din Dayal Bharti", "NotGraduate",  " ","बिहार",  "गया", "दीन दयाल भारती", " "}, 
{ "Bihar",  "3580",  "Gaya", "Sunil Paswan", "NotGraduate",  " ","बिहार",  "गया", "सुनील पासवान", " "}, 
{ "Bihar",  "3581",  "Gaya", "Jitan Ram Manjhi", "CriminalCases",  " ","बिहार",  "गया", "जीतन राम मांझी", " "}, 
{ "Bihar",  "3583",  "Gaya", "Rajesh Kumar Paswan", "NotGraduate",  " ","बिहार",  "गया", "राजेश कुमार पासवान", " "}, 
{ "Bihar",  "3603",  "Jamui", "Bhudeo Choudhary", "CriminalCases",  " ","बिहार",  "जमुई", "भूदेव चौधरी", " "}, 
{ "Bihar",  "3605",  "Jamui", "Pankaj Kumar Das", "NotGraduate",  " ","बिहार",  "जमुई", "पंकज कुमार दास", " "}, 
{ "Bihar",  "3608",  "Jamui", "Ajay Kumar", "CriminalCases",  " ","बिहार",  "जमुई", "अजय कुमार", " "}, 
{ "Bihar",  "3610",  "Jamui", "Chirag Kumar Paswan", "CriminalCases",  " ","बिहार",  "जमुई", "चिराग कुमार पासवान", " "}, 
{ "Bihar",  "6481",  "Jhanjharpur", "Prabhat Prasad", "OverAged",  " ","बिहार",  "झंझारपुर", "प्रभात प्रसाद", " "}, 
{ "Bihar",  "6483",  "Jhanjharpur", "Ganga Prasad Yadav", "CriminalCases",  " ","बिहार",  "झंझारपुर", "गंगा प्रसाद यादव", " "}, 
{ "Bihar",  "6484",  "Jhanjharpur", "Om Prakash Poddar", "CriminalCases",  " ","बिहार",  "झंझारपुर", "ओम प्रकाश पोद्दार", " "}, 
{ "Bihar",  "6485",  "Jhanjharpur", "Chhedi Ram", "NotGraduate",  " ","बिहार",  "झंझारपुर", "छेदी राम", " "}, 
{ "Bihar",  "6486",  "Jhanjharpur", "Lakshman Prasad Yadav", "NotGraduate",  " ","बिहार",  "झंझारपुर", "लक्ष्मण प्रसाद यादव", " "}, 
{ "Bihar",  "6487",  "Jhanjharpur", "Devendra Prasad Yadav", "OverAged",  " ","बिहार",  "झंझारपुर", "देवेंद्र प्रसाद यादव", " "}, 
{ "Bihar",  "6488",  "Jhanjharpur", "Ratneshwar Jha", "NotGraduate",  " ","बिहार",  "झंझारपुर", "रत्नेश्वर झा", " "}, 
{ "Bihar",  "6490",  "Jhanjharpur", "Ramanand Thakur", "CriminalCases",  " ","बिहार",  "झंझारपुर", "रामानंद ठाकुर", " "}, 
{ "Bihar",  "6493",  "Jhanjharpur", "Ramprit Mandal", "CriminalCases",  " ","बिहार",  "झंझारपुर", "रामप्रीत मंडल", " "}, 
{ "Bihar",  "6494",  "Jhanjharpur", "Ganpati Jha", "CriminalCases",  " ","बिहार",  "झंझारपुर", "गणपति झा", " "}, 
{ "Bihar",  "6495",  "Jhanjharpur", "Gulab Yadav", "CriminalCases",  " ","बिहार",  "झंझारपुर", "गुलाब यादव", " "}, 
{ "Bihar",  "6496",  "Jhanjharpur", "Bablu Gupta", "CriminalCases",  " ","बिहार",  "झंझारपुर", "बबलू गुप्ता", " "}, 
{ "Bihar",  "3513",  "Katihar", "Samir Kumar Jha", "NotGraduate",  " ","बिहार",  "कटिहार", "समीर कुमार झा", " "}, 
{ "Bihar",  "3514",  "Katihar", "Shivnandan Mandal", "OverAged",  " ","बिहार",  "कटिहार", "शिवनंदन मंडल", " "}, 
{ "Bihar",  "3515",  "Katihar", "Muhammad Shakur", "OverAged",  " ","बिहार",  "कटिहार", "मुहम्मद शकूर", " "}, 
{ "Bihar",  "3516",  "Katihar", "Ganga Kebat", "NotGraduate",  " ","बिहार",  "कटिहार", "गंगा केवट", " "}, 
{ "Bihar",  "3517",  "Katihar", "Basukinath Sah", "NotGraduate",  " ","बिहार",  "कटिहार", "बासुकीनाथ साह", " "}, 
{ "Bihar",  "3518",  "Katihar", "Abdur Rahman", "NotGraduate",  " ","बिहार",  "कटिहार", "अब्दुर रहमान", " "}, 
{ "Bihar",  "3519",  "Katihar", "Dulal Chandra Goswami", "CriminalCases",  " ","बिहार",  "कटिहार", "दुलाल चंद्र गोस्वामी", " "}, 
{ "Bihar",  "3520",  "Katihar", "Shah Tariq Anwar", "ForeignFunding",  " ","बिहार",  "कटिहार", "शाह तारिक अनवर", " "}, 
{ "Bihar",  "3521",  "Katihar", "Marang Hansda", "NotGraduate",  " ","बिहार",  "कटिहार", "मारंग हांसदा", " "}, 
{ "Bihar",  "6543",  "Khagaria", "Parmanand Singh", "CriminalCases",  " ","बिहार",  "खगरिया", "परमानंद सिंह", " "}, 
{ "Bihar",  "6544",  "Khagaria", "Bandan Kumar Singh", "NotGraduate",  " ","बिहार",  "खगरिया", "बंदन कुमार सिंह", " "}, 
{ "Bihar",  "6545",  "Khagaria", "Ramakant Choudhari", "NotGraduate",  " ","बिहार",  "खगरिया", "रमाकांत चौधरी", " "}, 
{ "Bihar",  "6547",  "Khagaria", "Sobha Devi", "NotGraduate",  " ","बिहार",  "खगरिया", "सोभा देवी", " "}, 
{ "Bihar",  "6548",  "Khagaria", "Tej Bahadur Singh", "OverAged",  " ","बिहार",  "खगरिया", "तेज बहादुर सिंह", " "}, 
{ "Bihar",  "6549",  "Khagaria", "Sunil Yadav", "NotGraduate",  " ","बिहार",  "खगरिया", "सुनील यादव", " "}, 
{ "Bihar",  "6550",  "Khagaria", "Choudhary Mahbub Ali Kaisar", "CriminalCases",  " ","बिहार",  "खगरिया", "चौधरी महबूब अली कैसर", " "}, 
{ "Bihar",  "6551",  "Khagaria", "Shiv Narayan Singh", "NotGraduate",  " ","बिहार",  "खगरिया", "शिव नारायण सिंह", " "}, 
{ "Bihar",  "6553",  "Khagaria", "Madhuvala Devi", "NotGraduate",  " ","बिहार",  "खगरिया", "मधुवाला देवी", " "}, 
{ "Bihar",  "6554",  "Khagaria", "Nagendra Singh Tyagi", "CriminalCases",  " ","बिहार",  "खगरिया", "नागेंद्र सिंह त्यागी", " "}, 
{ "Bihar",  "6555",  "Khagaria", "Moni Kumar", "NotGraduate",  " ","बिहार",  "खगरिया", "मोनी कुमार", " "}, 
{ "Bihar",  "6557",  "Khagaria", "Umesh Chandra Bharti", "CriminalCases",  " ","बिहार",  "खगरिया", "उमेश चंद्र भारती", " "}, 
{ "Bihar",  "6558",  "Khagaria", "Upendra Sahani", "NotGraduate",  " ","बिहार",  "खगरिया", "उपेंद्र सहनी", " "}, 
{ "Bihar",  "6560",  "Khagaria", "Mukesh Sahani", "CriminalCases",  " ","बिहार",  "खगरिया", "मुकेश सहनी", " "}, 
{ "Bihar",  "6561",  "Khagaria", "Dhirendra Choudhary", "NotGraduate",  " ","बिहार",  "खगरिया", "धीरेन्द्र चौधरी", " "}, 
{ "Bihar",  "3500",  "Kishanganj", "Syed Mahmood Ashraf", "CriminalCases",  " ","बिहार",  "किशनगंज", "सैयद महमूद अशरफ", " "}, 
{ "Bihar",  "3501",  "Kishanganj", "Javed Akhter", "CriminalCases",  " ","बिहार",  "किशनगंज", "जावेद अख्तर", " "}, 
{ "Bihar",  "3502",  "Kishanganj", "Haserul", "NotGraduate",  " ","बिहार",  "किशनगंज", "Haserul", " "}, 
{ "Bihar",  "3503",  "Kishanganj", "Chhote Lal Mahto", "NotGraduate",  " ","बिहार",  "किशनगंज", "छोटे लाल महतो", " "}, 
{ "Bihar",  "3505",  "Kishanganj", "Shukal Murmu", "NotGraduate",  " ","बिहार",  "किशनगंज", "शुकल मुर्मू", " "}, 
{ "Bihar",  "3506",  "Kishanganj", "Pradeep Kumar Singh", "NotGraduate",  " ","बिहार",  "किशनगंज", "प्रदीप कुमार सिंह", " "}, 
{ "Bihar",  "3507",  "Kishanganj", "Asad Alam", "NotGraduate",  " ","बिहार",  "किशनगंज", "असद आलम", " "}, 
{ "Bihar",  "3508",  "Kishanganj", "Alimuddin Ansari", "NotGraduate",  " ","बिहार",  "किशनगंज", "अलीमुद्दीन अंसारी", " "}, 
{ "Bihar",  "3509",  "Kishanganj", "Rajendra Paswan", "CriminalCases",  " ","बिहार",  "किशनगंज", "राजेंद्र पासवान", " "}, 
{ "Bihar",  "3510",  "Kishanganj", "Akhtarul Iman", "CriminalCases",  " ","बिहार",  "किशनगंज", "अख्तरुल ईमान", " "}, 
{ "Bihar",  "3511",  "Kishanganj", "Dr. Mohammad Jawed", "ForeignFunding",  " ","बिहार",  "किशनगंज", "डॉ। मोहम्मद जावेद", " "}, 
{ "Bihar",  "3512",  "Kishanganj", "Azimuddin", "OverAged",  " ","बिहार",  "किशनगंज", "Azimuddin", " "}, 
{ "Bihar",  "6530",  "Madhepura", "Sharad Yadav", "CriminalCases",  " ","बिहार",  "मधेपुरा", "शरद यादव", " "}, 
{ "Bihar",  "6535",  "Madhepura", "Dinesh Chandra Yadav", "CriminalCases",  " ","बिहार",  "मधेपुरा", "दिनेश चंद्र यादव", " "}, 
{ "Bihar",  "6537",  "Madhepura", "Manoj Kumar Manda", "NotGraduate",  " ","बिहार",  "मधेपुरा", "मनोज कुमार मंदा", " "}, 
{ "Bihar",  "6538",  "Madhepura", "Umashankar", "NotGraduate",  " ","बिहार",  "मधेपुरा", "उमाशंकर", " "}, 
{ "Bihar",  "6539",  "Madhepura", "Rajesh Ranjan", "CriminalCases",  " ","बिहार",  "मधेपुरा", "राजेश रंजन", " "}, 
{ "Bihar",  "6541",  "Madhepura", "Rajo Sah", "NotGraduate",  " ","बिहार",  "मधेपुरा", "राजो साह", " "}, 
{ "Bihar",  "3591",  "Nawada", "Prof. K.B. Prasad", "OverAged",  " ","बिहार",  "नवादा", "केबी प्रसाद", " "}, 
{ "Bihar",  "3592",  "Nawada", "Vishnu Dev Yadav", "OverAged",  " ","बिहार",  "नवादा", "विष्णु देव यादव", " "}, 
{ "Bihar",  "3593",  "Nawada", "Naresh Prasad", "CriminalCases",  " ","बिहार",  "नवादा", "नरेश प्रसाद", " "}, 
{ "Bihar",  "3594",  "Nawada", "Vijay Ram", "NotGraduate",  " ","बिहार",  "नवादा", "विजय राम", " "}, 
{ "Bihar",  "3595",  "Nawada", "Ranganathacharya", "CriminalCases",  " ","बिहार",  "नवादा", "Ranganathacharya", " "}, 
{ "Bihar",  "3598",  "Nawada", "Rakesh Raushan", "CriminalCases",  " ","बिहार",  "नवादा", "राकेश रौशन", " "}, 
{ "Bihar",  "3600",  "Nawada", "Nivedita Singh", "CriminalCases",  " ","बिहार",  "नवादा", "निवेदिता सिंह", " "}, 
{ "Bihar",  "3602",  "Nawada", "Chandan Singh", "CriminalCases",  " ","बिहार",  "नवादा", "चंदन सिंह", " "}, 
{ "Bihar",  "3522",  "Purnia", "Shobha Soren", "NotGraduate",  " ","बिहार",  "पूर्णिया", "शोभा सोरेन", " "}, 
{ "Bihar",  "3523",  "Purnia", "Md Akhtar Ali", "NotGraduate",  " ","बिहार",  "पूर्णिया", "एमडी अख्तर अली", " "}, 
{ "Bihar",  "3524",  "Purnia", "Rajiv Kumar Singh", "NotGraduate",  " ","बिहार",  "पूर्णिया", "राजीव कुमार सिंह", " "}, 
{ "Bihar",  "3525",  "Purnia", "Shubhash Kumar Thakur", "NotGraduate",  " ","बिहार",  "पूर्णिया", "शुभाष कुमार ठाकुर", " "}, 
{ "Bihar",  "3526",  "Purnia", "Uday Singh", "ForeignFunding",  " ","बिहार",  "पूर्णिया", "उदय सिंह", " "}, 
{ "Bihar",  "3527",  "Purnia", "Arjun Singh", "CriminalCases",  " ","बिहार",  "पूर्णिया", "अर्जुन सिंह", " "}, 
{ "Bihar",  "3528",  "Purnia", "Ashok Kumar Singh", "NotGraduate",  " ","बिहार",  "पूर्णिया", "अशोक कुमार सिंह", " "}, 
{ "Bihar",  "3529",  "Purnia", "Jitendra Urab", "CriminalCases",  " ","बिहार",  "पूर्णिया", "जितेन्द्र उरब", " "}, 
{ "Bihar",  "3530",  "Purnia", "Santosh Kumar", "CriminalCases",  " ","बिहार",  "पूर्णिया", "संतोष कुमार", " "}, 
{ "Bihar",  "3531",  "Purnia", "Anirudh Mehta", "NotGraduate",  " ","बिहार",  "पूर्णिया", "अनिरुद्ध मेहता", " "}, 
{ "Bihar",  "3533",  "Purnia", "Ashok Kumar Sah", "CriminalCases",  " ","बिहार",  "पूर्णिया", "अशोक कुमार साह", " "}, 
{ "Bihar",  "3535",  "Purnia", "Manju Murmu", "NotGraduate",  " ","बिहार",  "पूर्णिया", "मंजू मुर्मू", " "}, 
{ "Bihar",  "3536",  "Purnia", "Sageer Ahmad", "NotGraduate",  " ","बिहार",  "पूर्णिया", "सगीर अहमद", " "}, 
{ "Bihar",  "3537",  "Purnia", "Rajesh Kumar", "NotGraduate",  " ","बिहार",  "पूर्णिया", "राजेश कुमार", " "}, 
{ "Bihar",  "6498",  "Supaul", "Ranjeet Ranjan", "ForeignFunding",  " ","बिहार",  "सुपौल", "रणजीत रंजन", " "}, 
{ "Bihar",  "6499",  "Supaul", "Md. Afroj Alam", "NotGraduate",  " ","बिहार",  "सुपौल", "मो। अफरोज आलम", " "}, 
{ "Bihar",  "6502",  "Supaul", "Dinesh Prasad Yadav", "CriminalCases",  " ","बिहार",  "सुपौल", "दिनेश प्रसाद यादव", " "}, 
{ "Bihar",  "6503",  "Supaul", "Satya Narayan Mehta", "CriminalCases",  " ","बिहार",  "सुपौल", "सत्य नारायण मेहता", " "}, 
{ "Bihar",  "6506",  "Supaul", "Sanjay Sardar", "NotGraduate",  " ","बिहार",  "सुपौल", "संजय सरदार", " "}, 
{ "Bihar",  "6507",  "Supaul", "Naveen Kumar Singh", "NotGraduate",  " ","बिहार",  "सुपौल", "नवीन कुमार सिंह", " "}, 
{ "Bihar",  "6508",  "Supaul", "Pramod Kumar Nirala", "CriminalCases",  " ","बिहार",  "सुपौल", "प्रमोद कुमार निराला", " "}, 
{ "Bihar",  "6509",  "Supaul", "Kiran Devi", "NotGraduate",  " ","बिहार",  "सुपौल", "किरण देवी", " "}, 
{ "Bihar",  "6511",  "Supaul", "Bhim Kumar Gupta", "NotGraduate",  " ","बिहार",  "सुपौल", "भीम कुमार गुप्ता", " "}, 
{ "Bihar",  "6513",  "Supaul", "Dileshwar Kamait", "CriminalCases",  " ","बिहार",  "सुपौल", "दिलेश्वर कामायत", " "}, 
{ "Bihar",  "6514",  "Supaul", "Anand Pathak", "CriminalCases",  " ","बिहार",  "सुपौल", "आनंद पाठक", " "}, 
{ "Bihar",  "6515",  "Supaul", "Krishandev Mandal", "CriminalCases",  " ","बिहार",  "सुपौल", "कृष्णदेव मंडल", " "}, 
{ "Bihar",  "6516",  "Supaul", "Sanjeet Kumar Chaudhary", "NotGraduate",  " ","बिहार",  "सुपौल", "संजीत कुमार चौधरी", " "}, 
{ "Bihar",  "6517",  "Supaul", "Mohammad Abul Kalam Azad", "NotGraduate",  " ","बिहार",  "सुपौल", "मोहम्मद अबुल कलाम आज़ाद", " "}, 
};

}