/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Bihar {
public static final String[][] green_bucket = {
        {"Bihar", "Araria", "Md Mobinul Haque", "Independent", "5.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9512", "बिहार", "अररिया", "मोद मोबिनुल हक", "निर्दलीय"},
        {"Bihar", "Araria", "Ram Narayan Bharti", "Bahujan Samaj Party", "69.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8159", "बिहार", "अररिया", "राम नारायण भारती", "बहुजन समाज पार्टी"},
        {"Bihar", "Arrah", "Bharat Bhushan Pandey", "Akhil Bharatiya Jan Sangh", "22.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13064", "बिहार", "आरा", "भारत भूषण पांडे", "अखिल भारतीय जनसंघ"},
        {"Bihar", "Arrah", "Ram Raj Singh", "Independent", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13644", "बिहार", "आरा", "राम राज सिंह", "निर्दलीय"},
        {"Bihar", "Arrah", "Manoj Yadav", "Bahujan Samaj Party", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13061", "बिहार", "आरा", "मनोज यादव", "बहुजन समाज पार्टी"},
        {"Bihar", "Arrah", "Lakshaman Kumar Ojha", "Independent", "3.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13645", "बिहार", "आरा", "लक्ष्मण कुमार ओझा", "निर्दलीय"},
        {"Bihar", "Arrah", "Dr. Kumar Sheelbhadra", "Independent", "52.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13646", "बिहार", "आरा", "डॉ। कुमार शीलभद्र", "निर्दलीय"},
        {"Bihar", "Aurangabad", "Jaya Balu Rajkundal", "Bahujan Samaj Party", "52.3Lac", "http://myneta.info/ls2014/candidate.php?candidate_id=8514", "बिहार", "औरंगाबाद बिहा", "जया बलु राजकुमार", "बहुजन समाज पार्टी"},
        {"Bihar", "Aurangabad", "Upendra Prasad", "Hindustani Awam Morcha (Secular)", "2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5392", "बिहार", "औरंगाबाद बिहा", "उपेंद्र प्रसाद", "हिंदुस्तानी आवाम मोर्चा (सेक्युलर)"},
        {"Bihar", "Aurangabad", "Santosh Kumar Sinha", "Independent", "12.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4611", "बिहार", "औरंगाबाद बिहा", "संतोष कुमार सिन्हा", "निर्दलीय"},
        {"Bihar", "Aurangabad", "Som Prakash", "Swaraj Party (Loktantrik)", "14.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4609", "बिहार", "औरंगाबाद बिहा", "सोम प्रकाश", "स्वराज पार्टी (लोकतांत्रिक)"},
        {"Bihar", "Aurangabad", "Avinash Kumar", "Peoples Party of India (Democratic)", "37.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4612", "बिहार", "औरंगाबाद बिहा", "अविनाश कुमार", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
        {"Bihar", "Aurangabad", "Dhirendra Kumar Singh", "Independent", "83.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4613", "बिहार", "औरंगाबाद बिहा", "धीरेन्द्र कुमार सिंह", "निर्दलीय"},
        {"Bihar", "Banka", "Kailash Prasad Singh", "Pragatishil Samajwadi Party (Lohia)", "38.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6003", "बिहार", "बांका", "कैलाश प्रसाद सिंह", "प्रगति समाजवादी पार्टी (लोहिया)"},
        {"Bihar", "Banka", "Sanjiv Kumar Kunal", "Independent", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5999", "बिहार", "बांका", "संजीव कुमार कुणाल", "निर्दलीय"},
        {"Bihar", "Begusarai", "Gaurav Kumar", "Bhartiya Lokmat Rashtrwadi Party", "4.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9790", "बिहार", "बेगूसराय", "गौरव कुमार", "भारतीय लोकमत राष्ट्रवादी पार्टी"},
        {"Bihar", "Bhagalpur", "Satyendra Kumar", "Aam Aadmi Party", "3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5975", "बिहार", "भागलपुर", "सत्येंद्र कुमार", "आम आदमी पार्टी"},
        {"Bihar", "Bhagalpur", "Sunil Kumar", "Independent", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5974", "बिहार", "भागलपुर", "सुनील कुमार", "निर्दलीय"},
        {"Bihar", "Bhagalpur", "Nurullah", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5603", "बिहार", "भागलपुर", "Nurullah", "निर्दलीय"},
        {"Bihar", "Buxar", "Uday Narayan Rai", "Suheldev Bhartiya Samaj Party", "7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13073", "बिहार", "बक्सर", "उदय नारायण राय", "सुहेलदेव भारतीय समाज पार्टी"},
        {"Bihar", "Buxar", "Arvind Kumar Pandey", "Independent", "15.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13853", "बिहार", "बक्सर", "अरविंद कुमार पांडे", "निर्दलीय"},
        {"Bihar", "Buxar", "Binod Kumar Bikrant", "Peoples Party of India (Democratic)", "4.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13069", "बिहार", "बक्सर", "बिनोद कुमार बिक्रांत", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
        {"Bihar", "Buxar", "Ravi Raj", "Pragatishil Samajwadi Party (Lohia)", "69.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13070", "बिहार", "बक्सर", "रवि राज", "प्रगति समाजवादी पार्टी (लोहिया)"},
        {"Bihar", "Gaya", "Dayanand Rajwanshi", "Moolniwasi Samaj Party", "4.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5608", "बिहार", "गया", "दयानंद राजवंशी", "मूलनिवासी समाज पार्टी"},
        {"Bihar", "Gaya", "Prakash Chandra", "Public Mission Party", "81.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5612", "बिहार", "गया", "प्रकाश चंद्र", "सार्वजनिक मिशन पार्टी"},
        {"Bihar", "Gaya", "Umesh Rajak", "Peoples Party of India (Democratic)", "1.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4691", "बिहार", "गया", "उमेश रजक", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
        {"Bihar", "Gaya", "Dilip Kumar", "Bahujan Samaj Party", "18.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5605", "बिहार", "गया", "दिलीप कुमार", "बहुजन समाज पार्टी"},
        {"Bihar", "Gaya", "Vijay Kumar Chaudhari", "Janta Dal Rashtravadi", "45.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5606", "बिहार", "गया", "विजय कुमार चौधरी", "जनता दल राष्ट्रवादी"},
        {"Bihar", "Gopalganj", "Dilip Kumar Manjhi", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12497", "बिहार", "गोपालगंज", "दिलीप कुमार मांझी", "निर्दलीय"},
        {"Bihar", "Gopalganj", "Dr. Alok Kumar Suman", "Janata Dal (United)", "3.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12076", "बिहार", "गोपालगंज", "डॉ। आलोक कुमार सुमन", "जनता दल (यूनाइटेड)"},
        {"Bihar", "Gopalganj", "Kunal Kishore Vivek", "Bahujan Samaj Party", "2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12498", "बिहार", "गोपालगंज", "कुणाल किशोर विवेक", "बहुजन समाज पार्टी"},
        {"Bihar", "Gopalganj", "Suraj Kumar", "Independent", "14.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12074", "बिहार", "गोपालगंज", "सूरज कुमार", "निर्दलीय"},
        {"Bihar", "Gopalganj", "Dinanath Manjhi", "Independent", "69.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12493", "बिहार", "गोपालगंज", "दीनानाथ मांझी", "निर्दलीय"},
        {"Bihar", "Gopalganj", "Uma Shankar Kharwar", "Independent", "3.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12492", "बिहार", "गोपालगंज", "उमा शंकर खरवार", "निर्दलीय"},
        {"Bihar", "Gopalganj", "Ram Kumar Manjhi", "Independent", "28.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12496", "बिहार", "गोपालगंज", "राम कुमार मांझी", "निर्दलीय"},
        {"Bihar", "Hajipur", "Shiwani Kant", "Independent", "45.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11639", "बिहार", "हाजीपुर", "शिवानी कांत", "निर्दलीय"},
        {"Bihar", "Hajipur", "Kumari Aashiki", "Sathi Aur Aapka Faisala Party", "31.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11634", "बिहार", "हाजीपुर", "कुमारी आशिकी", "सती और आप फसाला पार्टी"},
        {"Bihar", "Jahanabad", "Chandra Prakash", "Independent", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13637", "बिहार", "जहानाबाद", "चंद्र प्रकाश", "निर्दलीय"},
        {"Bihar", "Jahanabad", "Avinash Kumar", "Bharatiya Bahujan Congress", "10Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13639", "बिहार", "जहानाबाद", "अविनाश कुमार", "भारतीय बहुजन कांग्रेस"},
        {"Bihar", "Jahanabad", "Sunil Kumar", "Peoples Party of India (Democratic)", "25.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13083", "बिहार", "जहानाबाद", "सुनील कुमार", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
        {"Bihar", "Jahanabad", "Uma Shankar Verma", "Socialist Unity Centre of India (Communist)", "40.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13082", "बिहार", "जहानाबाद", "उमा शंकर वर्मा", "भारतीय समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Bihar", "Jahanabad", "Mira Kumari Yadav", "Shoshit Samaj Dal", "61482", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13641", "बिहार", "जहानाबाद", "मीरा कुमारी यादव", "शोषित समाज दल"},
        {"Bihar", "Jamui", "Balmiki Paswan", "Hindusthan Nirman Dal", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5637", "बिहार", "जमुई", "बाल्मीकि पासवान", "हिंदुस्तान निर्माण दल"},
        {"Bihar", "Jamui", "Virendra Kumar", "Independent", "2.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5632", "बिहार", "जमुई", "वीरेन्द्र कुमार", "निर्दलीय"},
        {"Bihar", "Jamui", "Subhash Paswan", "Independent", "17.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5639", "बिहार", "जमुई", "सुभाष पासवान", "निर्दलीय"},
        {"Bihar", "Jamui", "Vishnu Priya", "Bahujan Mukti Party", "88.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5636", "बिहार", "जमुई", "विष्णु प्रिया", "बहुजन मुक्ति पार्टी"},
        {"Bihar", "Jhanjharpur", "Surendra Prasad Suman", "All India Forward Bloc", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8157", "बिहार", "झंझारपुर", "सुरेन्द्र प्रसाद सुमन", "ऑल इंडिया फॉरवर्ड ब्लॉक"},
        {"Bihar", "Jhanjharpur", "Bipin Kumar Singhwait", "Independent", "55.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9146", "बिहार", "झंझारपुर", "बिपिन कुमार सिंहवात", "निर्दलीय"},
        {"Bihar", "Jhanjharpur", "Sanjay Bhartia", "Independent", "11.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7782", "बिहार", "झंझारपुर", "संजय भरतिया", "निर्दलीय"},
        {"Bihar", "Jhanjharpur", "Ramesh Kamat", "Aam Adhikar Morcha", "16.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7783", "बिहार", "झंझारपुर", "रमेश कामत", "आम पालन मोर्चा"},
        {"Bihar", "Jhanjharpur", "Raj Kumar Singh", "Bahujan Samaj Party", "8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8158", "बिहार", "झंझारपुर", "राज कुमार सिंह", "बहुजन समाज पार्टी"},
        {"Bihar", "Karakat", "Prithvi Nath Prasad", "Asli Deshi Party", "65Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13861", "बिहार", "काराकाट", "पृथ्वी नाथ प्रसाद", "असली देसी पार्टी"},
        {"Bihar", "Karakat", "Ghanshyam Tiwari", "Samajwadi Party", "67.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13862", "बिहार", "काराकाट", "घनश्याम तिवारी", "समाजवादी पार्टी"},
        {"Bihar", "Karakat", "Arif Isain Husain", "Janta Dal Rashtravadi", "2.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13857", "बिहार", "काराकाट", "आरिफ इसैन हुसैन", "जनता दल राष्ट्रवादी"},
        {"Bihar", "Karakat", "Punam Devi", "Independent", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13858", "बिहार", "काराकाट", "पुनम देवी", "निर्दलीय"},
        {"Bihar", "Karakat", "Prakash Chandra Goyal", "Peoples Party of India (Democratic)", "10.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13860", "बिहार", "काराकाट", "प्रकाश चंद्र गोयल", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
        {"Bihar", "Karakat", "Kumar Saurabh", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13864", "बिहार", "काराकाट", "कुमार सौरभ", "निर्दलीय"},
        {"Bihar", "Karakat", "Dharmendra Singh", "Independent", "3.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13856", "बिहार", "काराकाट", "धर्मेंद्र सिंह", "निर्दलीय"},
        {"Bihar", "Karakat", "Mohammad Atahar Hussain", "Ambedkar National Congress", "6.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12771", "बिहार", "काराकाट", "मोहम्मद अतहर हुसैन", "अंबेडकर राष्ट्रीय कांग्रेस"},
        {"Bihar", "Karakat", "Nand Kishor Yadav", "Swaraj Party (Loktantrik)", "2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13658", "बिहार", "काराकाट", "नंद किशोर यादव", "स्वराज पार्टी (लोकतांत्रिक)"},
        {"Bihar", "Khagaria", "Sangram Kumar Sada", "Independent", "3.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9521", "बिहार", "खगरिया", "संग्राम कुमार सदा", "निर्दलीय"},
        {"Bihar", "Khagaria", "Priyadarshi Dinkar", "Independent", "3.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9520", "बिहार", "खगरिया", "प्रियदर्शी दिनकर", "निर्दलीय"},
        {"Bihar", "Khagaria", "Sandip Kumar Saket", "Shiv Sena", "80.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8150", "बिहार", "खगरिया", "संदीप कुमार साकेत", "शिवसेना"},
        {"Bihar", "Khagaria", "Upendra Sahani", "Rashtriya Jansambhavna Party", "3.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8147", "बिहार", "खगरिया", "उपेंद्र सहनी", "राष्ट्रीय जनसंवाद पार्टी"},
        {"Bihar", "Khagaria", "Kundan Kumar", "Independent", "4.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9517", "बिहार", "खगरिया", "कुंदन कुमार", "निर्दलीय"},
        {"Bihar", "Khagaria", "Vinay Kumar Varun", "Janhit Kisan Party", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7619", "बिहार", "खगरिया", "विनय कुमार वरुण", "जनहित किसान पार्टी"},
        {"Bihar", "Kishanganj", "Indra Deo Paswan", "Bahujan Samaj Party", "68.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5950", "बिहार", "किशनगंज", "इंद्र देव पासवान", "बहुजन समाज पार्टी"},
        {"Bihar", "Kishanganj", "Rajesh Kumar Dubey", "Independent", "5.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5944", "बिहार", "किशनगंज", "राजेश कुमार दुबे", "निर्दलीय"},
        {"Bihar", "Madhepura", "Vinay Kumar Mishra", "Independent", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8170", "बिहार", "मधेपुरा", "विनय कुमार मिश्र", "निर्दलीय"},
        {"Bihar", "Madhepura", "Mohammad Arshad Hussain", "Independent", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7622", "बिहार", "मधेपुरा", "मोहम्मद अरशद हुसैन", "निर्दलीय"},
        {"Bihar", "Madhepura", "Anil Bharti", "Rashtravadi Janata Party", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8168", "बिहार", "मधेपुरा", "अनिल भारती", "राष्ट्रवादी जनता पार्टी"},
        {"Bihar", "Madhepura", "Suman Kumar Jha", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7624", "बिहार", "मधेपुरा", "सुमन कुमार झा", "निर्दलीय"},
        {"Bihar", "Madhepura", "Suresh Kumar Bharti", "Asli Deshi Party", "3.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9523", "बिहार", "मधेपुरा", "सुरेश कुमार भारती", "असली देसी पार्टी"},
        {"Bihar", "Madhepura", "Jaykant Yadav", "Independent", "5.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9524", "बिहार", "मधेपुरा", "जयकांत यादव", "निर्दलीय"},
        {"Bihar", "Madhepura", "Rajiv Kumar Yadav", "Baliraja Party", "5.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8169", "बिहार", "मधेपुरा", "राजीव कुमार यादव", "बलिराजा पार्टी"},
        {"Bihar", "Madhubani", "Abubakar Rahmani", "Independent", "7.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12576", "बिहार", "मधुबनी", "अबूबकर रहमानी", "निर्दलीय"},
        {"Bihar", "Madhubani", "Ranjit Kumar", "Bahujan Mukti Party", "4.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11086", "बिहार", "मधुबनी", "रंजीत कुमार", "बहुजन मुक्ति पार्टी"},
        {"Bihar", "Madhubani", "Anand Kumar Jha", "Akhil Bhartiya Mithila Party", "1.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12572", "बिहार", "मधुबनी", "आनंद कुमार झा", "अखिल भारतीय मिथिला पार्टी"},
        {"Bihar", "Maharajganj", "M.K.Singh Rathour", "Independent", "3.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12080", "बिहार", "महाराजगंज", "एमकेसिंह राठौर", "निर्दलीय"},
        {"Bihar", "Maharajganj", "Menaka Raman", "Independent", "78.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12500", "बिहार", "महाराजगंज", "मेनका रमन", "निर्दलीय"},
        {"Bihar", "Maharajganj", "Rajendra Kumar", "Independent", "18.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12086", "बिहार", "महाराजगंज", "राजेंद्र कुमार", "निर्दलीय"},
        {"Bihar", "Munger", "Rajesh Kumar Ratnakar", "Independent", "16Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10158", "बिहार", "मुंगेर", "राजेश कुमार रत्नाकर", "निर्दलीय"},
        {"Bihar", "Munger", "Arbind Kumar Sharma", "Rashtriya Hind Sena", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10168", "बिहार", "मुंगेर", "अरबिंद कुमार शर्मा", "राष्ट्रीय हिंद सेना"},
        {"Bihar", "Munger", "Pranay Kumar", "Independent", "69.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10149", "बिहार", "मुंगेर", "प्रणय कुमार", "निर्दलीय"},
        {"Bihar", "Munger", "Krishna Murari Kumar", "Jan Adhikar Party", "44.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10153", "बिहार", "मुंगेर", "कृष्ण मुरारी कुमार", "जन अधिक्कार पार्टी"},
        {"Bihar", "Munger", "Amarjit Patel", "Independent", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10163", "बिहार", "मुंगेर", "अमरजीत पटेल", "निर्दलीय"},
        {"Bihar", "Munger", "Panchanand Singh", "Jago Hindustan Party", "66500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10162", "बिहार", "मुंगेर", "पंचानंद सिंह", "जागो हिंदुस्तान पार्टी"},
        {"Bihar", "Muzaffarpur", "Nandan Kumar", "Janata Party", "5809", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12578", "बिहार", "मुजफ्फरपुर", "नंदन कुमार", "जनता पार्टी"},
        {"Bihar", "Muzaffarpur", "Sudhir Kumar Jha", "Yuva Krantikari Party", "86.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11093", "बिहार", "मुजफ्फरपुर", "सुधीर कुमार झा", "युवा क्रांतिकारी पार्टी"},
        {"Bihar", "Muzaffarpur", "Anirudh Singh", "All India Forward Bloc", "12.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11335", "बिहार", "मुजफ्फरपुर", "अनिरुद्ध सिंह", "ऑल इंडिया फॉरवर्ड ब्लॉक"},
        {"Bihar", "Muzaffarpur", "Ajitansh Gaur", "Independent", "95536", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11087", "बिहार", "मुजफ्फरपुर", "अजितेश गौड़", "निर्दलीय"},
        {"Bihar", "Muzaffarpur", "Renu Khari", "Jan Adhikar Party", "62.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12579", "बिहार", "मुजफ्फरपुर", "रेणु खारी", "जन आढ़ती पार्टी"},
        {"Bihar", "Muzaffarpur", "Mukesh Kumar", "Independent", "1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11333", "बिहार", "मुजफ्फरपुर", "मुकेश कुमार", "निर्दलीय"},
        {"Bihar", "Muzaffarpur", "Pradeep Kumar Singh", "Shiv Sena", "59.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11649", "बिहार", "मुजफ्फरपुर", "प्रदीप कुमार सिंह", "शिवसेना"},
        {"Bihar", "Muzaffarpur", "Suresh Kumar", "Independent", "41.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11655", "बिहार", "मुजफ्फरपुर", "सुरेश कुमार", "निर्दलीय"},
        {"Bihar", "Muzaffarpur", "Raj Bhushan Chaudhry", "Vikassheel Insaan Party", "7.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11331", "बिहार", "मुजफ्फरपुर", "राज भूषण चौधरी", "विकासशील इन्सान पार्टी"},
        {"Bihar", "Nalanda", "Ramchandra Singh", "Independent", "88.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14164", "बिहार", "नालंदा", "रामचंद्र सिंह", "निर्दलीय"},
        {"Bihar", "Nalanda", "Rajeev Ranjan Kumar", "Jan Adhikar Party", "81.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14147", "बिहार", "नालंदा", "राजीव रंजन कुमार", "जन आढ़ती पार्टी"},
        {"Bihar", "Nalanda", "Brahamdev Prasad", "Shoshit Samaj Dal", "32.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14146", "बिहार", "नालंदा", "ब्रह्मदेव प्रसाद", "शोषित समाज दल"},
        {"Bihar", "Nalanda", "Sanjeet Kumar", "Jantantrik Vikas Party", "2.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14152", "बिहार", "नालंदा", "संजीत कुमार", "जनतांत्रिक पार्टी"},
        {"Bihar", "Nalanda", "Sunil Ravidas", "Republican Party of India", "2.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14153", "बिहार", "नालंदा", "सुनील रविदास", "रिपब्लिकन पार्टी ऑफ इंडिया"},
        {"Bihar", "Nalanda", "Rakesh Paswan", "Independent", "5.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14163", "बिहार", "नालंदा", "राकेश पासवान", "निर्दलीय"},
        {"Bihar", "Nalanda", "Anil Kumar", "Bharatiya Jan Kranti Dal (Democratic)", "2.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14140", "बिहार", "नालंदा", "अनिल कुमार", "भारतीय जन क्रांति दल (लोकतांत्रिक)"},
        {"Bihar", "Nawada", "Mokim Uddin", "Rashtriya Ulama Council", "73.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5619", "बिहार", "नवादा", "मोकिम उद्दीन", "राष्ट्रीय उलमा परिषद"},
        {"Bihar", "Nawada", "Tulsi Dayal", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4608", "बिहार", "नवादा", "तुलसी दयाल", "निर्दलीय"},
        {"Bihar", "Nawada", "Aditya Pradhan", "Peoples Party of India (Democratic)", "34.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5622", "बिहार", "नवादा", "आदित्य प्रधान", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
        {"Bihar", "Nawada", "Rajesh Kumar", "Independent", "62.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4693", "बिहार", "नवादा", "राजेश कुमार", "निर्दलीय"},
        {"Bihar", "Paschim Champaran", "Ajay Kumar Sinha", "Independent", "38.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12788", "बिहार", "पश्चिम चंपारण", "अजय कुमार सिन्हा", "निर्दलीय"},
        {"Bihar", "Paschim Champaran", "Bipin Nath Tiwari", "Loktantrik Jan Swaraj Party", "36.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12504", "बिहार", "पश्चिम चंपारण", "बिपिन नाथ तिवारी", "लोकतान्त्रिक जन स्वराज पार्टी"},
        {"Bihar", "Pataliputra", "Ram Niranjan Roy", "Rashtrawadi Chetna Party", "35.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14186", "बिहार", "पाटलिपुत्र", "राम निरंजन रॉय", "राष्ट्रवादी चेतना पार्टी"},
        {"Bihar", "Pataliputra", "Wakil Ahmad", "Janata Party", "65.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14189", "बिहार", "पाटलिपुत्र", "वक़ील अहमद", "जनता पार्टी"},
        {"Bihar", "Pataliputra", "Md. Kalimullah", "Bahujan Samaj Party", "48Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13059", "बिहार", "पाटलिपुत्र", "मो। कलीमुल्लाह", "बहुजन समाज पार्टी"},
        {"Bihar", "Pataliputra", "Brajeshwar Prasad Singh", "Independent", "2.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14194", "बिहार", "पाटलिपुत्र", "ब्रजेश्वर प्रसाद सिंह", "निर्दलीय"},
        {"Bihar", "Pataliputra", "Ramesh Kumar Sharma", "Independent", "1107.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14196", "बिहार", "पाटलिपुत्र", "रमेश कुमार शर्मा", "निर्दलीय"},
        {"Bihar", "Pataliputra", "Indu Devi Mishra", "Bharatiya Jan Kranti Dal (Democratic)", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14180", "बिहार", "पाटलिपुत्र", "इंदु देवी मिश्रा", "भारतीय जन क्रांति दल (लोकतांत्रिक)"},
        {"Bihar", "Pataliputra", "Satish Kumar", "Bharatiya Momin Front", "51500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13058", "बिहार", "पाटलिपुत्र", "सतीश कुमार", "भारतीय मोमिन मोर्चा"},
        {"Bihar", "Pataliputra", "Durgesh Nandan Singh Alias Durgesh Yadav", "Rashtriya Janvikas Party (Democratic)", "41.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14182", "बिहार", "पाटलिपुत्र", "दुर्गेश नंदन सिंह उर्फ दुर्गेश यादव", "राष्ट्रीय जनता पार्टी (लोकतांत्रिक)"},
        {"Bihar", "Patna Sahib", "Mahboob Alam Ansari", "Bharatiya Momin Front", "20.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13053", "बिहार", "पटना साहिब", "महबूब आलम अंसारी", "भारतीय मोमिन मोर्चा"},
        {"Bihar", "Patna Sahib", "Vishnu Dev", "Independent", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14179", "बिहार", "पटना साहिब", "विष्णु देव", "निर्दलीय"},
        {"Bihar", "Patna Sahib", "Prabhash Chandra Sharma", "Vanchit Samaj Party", "49.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13051", "बिहार", "पटना साहिब", "प्रभाष चंद्र शर्मा", "वंचित समाज पार्टी"},
        {"Bihar", "Patna Sahib", "Anamika Kumari", "Socialist Unity Centre of India (Communist)", "24070", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13049", "बिहार", "पटना साहिब", "अनामिका कुमारी", "भारतीय समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Bihar", "Patna Sahib", "Nimesh Shukla", "Independent", "14.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14177", "बिहार", "पटना साहिब", "निमेष शुक्ला", "निर्दलीय"},
        {"Bihar", "Patna Sahib", "Kumar Raunak", "Independent", "76.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14175", "बिहार", "पटना साहिब", "कुमार रौनक", "निर्दलीय"},
        {"Bihar", "Patna Sahib", "Rajesh Kumar", "Janata Party", "3.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14170", "बिहार", "पटना साहिब", "राजेश कुमार", "जनता पार्टी"},
        {"Bihar", "Patna Sahib", "Arvind Kumar", "Independent", "4.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14173", "बिहार", "पटना साहिब", "अरविंद कुमार", "निर्दलीय"},
        {"Bihar", "Patna Sahib", "Sumit Ranjan Sinha", "Shiv Sena", "86000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13052", "बिहार", "पटना साहिब", "सुमित रंजन सिन्हा", "शिवसेना"},
        {"Bihar", "Purnia", "Dr. Mritunjay Kumar Jha", "Independent", "14.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5103", "बिहार", "पूर्णिया", "डॉ मृत्युंजय कुमार झा", "निर्दलीय"},
        {"Bihar", "Purnia", "Sanoj Kumar Chauhan", "Bihar Lok Nirman Dal", "27.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5964", "बिहार", "पूर्णिया", "सनोज कुमार चौहान", "बिहार लोक निर्माण दल"},
        {"Bihar", "Purvi Champaran", "Rajiv Ranjan", "Janta Dal Rashtravadi", "4.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12817", "बिहार", "पूर्वी चंपारण", "राजीव रंजन", "जनता दल राष्ट्रवादी"},
        {"Bihar", "Purvi Champaran", "Mohammad Ajmer Alam", "Independent", "24.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12827", "बिहार", "पूर्वी चंपारण", "मोहम्मद अजमेर आलम", "निर्दलीय"},
        {"Bihar", "Purvi Champaran", "Shakti Kumar", "Independent", "71.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12822", "बिहार", "पूर्वी चंपारण", "शक्ति कुमार", "निर्दलीय"},
        {"Bihar", "Samastipur", "Mantesh Kumar", "Bahujan Samaj Party", "25.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10175", "बिहार", "समस्तीपुर", "मंटेश कुमार", "बहुजन समाज पार्टी"},
        {"Bihar", "Samastipur", "Ratan Bihari", "Jan Adhikar Party", "7.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10176", "बिहार", "समस्तीपुर", "रतन बिहारी", "जन अधिक्कार पार्टी"},
        {"Bihar", "Samastipur", "Pinku Paswan", "Yuva Krantikari Party", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10189", "बिहार", "समस्तीपुर", "पिंकू पासवान", "युवा क्रांतिकारी पार्टी"},
        {"Bihar", "Samastipur", "Suraj Kumar Das", "Independent", "14.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10170", "बिहार", "समस्तीपुर", "सूरज कुमार दास", "निर्दलीय"},
        {"Bihar", "Samastipur", "Vidyanand Ram", "Wazib Adhikar Party", "5.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10181", "बिहार", "समस्तीपुर", "विद्यानंद राम", "वजीब अदिकार पार्टी"},
        {"Bihar", "Saran", "Shiv Brat Singh", "Independent", "77Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12072", "बिहार", "सरन", "शिव बरात सिंह", "निर्दलीय"},
        {"Bihar", "Saran", "Prabhat Kumar", "Independent", "20.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11656", "बिहार", "सरन", "प्रभात कुमार", "निर्दलीय"},
        {"Bihar", "Saran", "Bhisham Kumar Ray", "Purvanchal Mahapanchayat", "33.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12065", "बिहार", "सरन", "भीष्म कुमार रे", "पूर्वांचल महापंचायत"},
        {"Bihar", "Sasaram", "Manoj Kumar", "Bahujan Samaj Party", "88.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13080", "बिहार", "सासाराम", "मनोज कुमार", "बहुजन समाज पार्टी"},
        {"Bihar", "Sheohar", "Upendra Sahani", "Rashtriya Jansambhavna Party", "3.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12097", "बिहार", "शिवहर", "उपेंद्र सहनी", "राष्ट्रीय जनसंवाद पार्टी"},
        {"Bihar", "Sheohar", "Anil Kumar", "Jan Adhikar Party", "49.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12868", "बिहार", "शिवहर", "अनिल कुमार", "जन आढ़ती पार्टी"},
        {"Bihar", "Sheohar", "Anand Kumar Maurya", "Bahujan Azad Party", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13519", "बिहार", "शिवहर", "आनंद कुमार मौर्य", "बहुजन आजाद पार्टी"},
        {"Bihar", "Sheohar", "Devendra Prasad Singh", "All India Forward Bloc", "3.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12107", "बिहार", "शिवहर", "देवेंद्र प्रसाद सिंह", "ऑल इंडिया फॉरवर्ड ब्लॉक"},
        {"Bihar", "Sitamarhi", "Junaid Khan", "Independent", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11659", "बिहार", "सीतामढ़ी", "जुनैद खान", "निर्दलीय"},
        {"Bihar", "Sitamarhi", "Ravindra Kumar Chandra Urf Dr. Raja Babu", "Bhartiya Mitra Party", "5200", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12691", "बिहार", "सीतामढ़ी", "रवींद्र कुमार चंद्र उर्फ़ डॉ। राजा बाबू", "भारतीय मित्र पार्टी"},
        {"Bihar", "Sitamarhi", "Raj Kishore Prasad", "Proutist Bloc, India", "22.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11343", "बिहार", "सीतामढ़ी", "राज किशोर प्रसाद", "प्राउटिस्ट ब्लाक, भारत"},
        {"Bihar", "Sitamarhi", "Chandrika Prasad", "Independent", "7.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11345", "बिहार", "सीतामढ़ी", "चंद्रिका प्रसाद", "निर्दलीय"},
        {"Bihar", "Sitamarhi", "Braj Kishor Jha", "All India Forward Bloc", "3.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11661", "बिहार", "सीतामढ़ी", "ब्रज किशोर झा", "ऑल इंडिया फॉरवर्ड ब्लॉक"},
        {"Bihar", "Sitamarhi", "Nand Kishore Gupta", "Independent", "7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11660", "बिहार", "सीतामढ़ी", "नंद किशोर गुप्ता", "निर्दलीय"},
        {"Bihar", "Sitamarhi", "Surendra Kumar", "Bajjikanchal Vikas Party", "10.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12692", "बिहार", "सीतामढ़ी", "सुरेंद्र कुमार", "बज्जीांचल विकास पार्टी"},
        {"Bihar", "Sitamarhi", "Mahesh Nandan Singh", "Independent", "22.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11347", "बिहार", "सीतामढ़ी", "महेश नंदन सिंह", "निर्दलीय"},
        {"Bihar", "Siwan", "Satyendra Kushwaha", "Independent", "18.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12796", "बिहार", "सिवान", "सत्येंद्र कुशवाहा", "निर्दलीय"},
        {"Bihar", "Siwan", "Abhishek Kumar", "Independent", "50.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12112", "बिहार", "सिवान", "अभिषेक कुमार", "निर्दलीय"},
        {"Bihar", "Siwan", "Vijay Bahadur Singh", "Rashtriya Sahyog Party", "56.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12110", "बिहार", "सिवान", "विजय बहादुर सिंह", "राष्ट्रीय सहयोग पार्टी"},
        {"Bihar", "Siwan", "Deva Kant Mishra Alias Munna Bhaiya", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12805", "बिहार", "सिवान", "देव कांत मिश्र अलियास मुन्ना भैया", "निर्दलीय"},
        {"Bihar", "Siwan", "Sudhir Kumar Singh", "Shiv Sena", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12109", "बिहार", "सिवान", "सुधीर कुमार सिंह", "शिवसेना"},
        {"Bihar", "Siwan", "Shabana", "Jai Prakash Janata Dal", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12810", "बिहार", "सिवान", "शबाना", "जय प्रकाश जनता दल"},
        {"Bihar", "Supaul", "Rajesh Kumar S/O Yugeshwar Sah", "Independent", "6.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10738", "बिहार", "सुपौल", "राजेश कुमार एस / ओ युगेश्वर साह", "निर्दलीय"},
        {"Bihar", "Supaul", "Deep Narayan Mandal", "Shiv Sena", "60.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9190", "बिहार", "सुपौल", "दीप नारायण मंडल", "शिवसेना"},
        {"Bihar", "Supaul", "Sudhakar Jha", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7628", "बिहार", "सुपौल", "सुधाकर झा", "निर्दलीय"},
        {"Bihar", "Supaul", "Sandeep Kumar Singh", "Independent", "6.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9197", "बिहार", "सुपौल", "संदीप कुमार सिंह", "निर्दलीय"},
        {"Bihar", "Supaul", "Binod Kumar Sahu", "Independent", "75.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7631", "बिहार", "सुपौल", "बिनोद कुमार साहू", "निर्दलीय"},
        {"Bihar", "Supaul", "Rajesh Kumar S/O Jawahar Lal Das", "Independent", "4.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8171", "बिहार", "सुपौल", "राजेश कुमार एस / ओ जवाहर लाल दास", "निर्दलीय"},
        {"Bihar", "Ujiarpur", "Sudhir Kumar Ray", "Independent", "68.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10196", "बिहार", "उजियारपुर", "सुधीर कुमार रे", "निर्दलीय"},
        {"Bihar", "Ujiarpur", "Manoj Kumar", "Janta Raj Vikas Party", "33.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10203", "बिहार", "उजियारपुर", "मनोज कुमार", "जनता राज विकास पार्टी"},
        {"Bihar", "Ujiarpur", "Navin Kumar", "Bahujan Samaj Party", "77Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10207", "बिहार", "उजियारपुर", "नवीन कुमार", "बहुजन समाज पार्टी"},
        {"Bihar", "Ujiarpur", "Dr Ajay Singh Almust", "Rashtriya Samta Party (Secular)", "43.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10205", "बिहार", "उजियारपुर", "डॉ। अजय सिंह सर्वशक्तिमान", "राष्ट्रीय समता पार्टी (धर्मनिरपेक्ष)"},
        {"Bihar", "Ujiarpur", "A M Izharul Haque", "Sathi Aur Aapka Faisala Party", "8.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10208", "बिहार", "उजियारपुर", "एएम इज़हारुल हक़", "सती और आप फसाला पार्टी"},
        {"Bihar", "Ujiarpur", "Jay Narayan Sah", "Bajjikanchal Vikas Party", "18.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10218", "बिहार", "उजियारपुर", "जय नारायण साह", "बज्जीांचल विकास पार्टी"},
        {"Bihar", "Ujiarpur", "Kumar Gaurav", "Jai Prakash Janata Dal", "8.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10198", "बिहार", "उजियारपुर", "कुमार गौरव", "जय प्रकाश जनता दल"},
        {"Bihar", "Vaishali", "Abhay Kumar Sharma", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12850", "बिहार", "वैशाली", "अभय कुमार शर्मा", "निर्दलीय"},
        {"Bihar", "Vaishali", "Rameshwar Sah", "Rashtriya Pragati Party", "3.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12852", "बिहार", "वैशाली", "रामेश्वर साह", "राष्ट्रीय प्रगति पार्टी"},
        {"Bihar", "Vaishali", "Lalji Kuamr Rakesh", "Independent", "34Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12861", "बिहार", "वैशाली", "लालजी कुम्र राकेश", "निर्दलीय"},
        {"Bihar", "Vaishali", "Ismohamad Alias Md. Munna", "Independent", "16Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12122", "बिहार", "वैशाली", "इस्मोअद अलियास मुद मुन्ना", "निर्दलीय"},
        {"Bihar", "Vaishali", "Balak Nath Sahni", "Rashtriya mahan Gantantra Party", "6.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12862", "बिहार", "वैशाली", "बालक नाथ साहनी", "राष्ट्रीय महामंत्र पार्टी"},
        {"Bihar", "Vaishali", "Arvind Kumar Singh", "Independent", "89.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12855", "बिहार", "वैशाली", "अरविंद कुमार सिंह", "निर्दलीय"},
        {"Bihar", "Vaishali", "Sudha Rani", "Independent", "2.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12858", "बिहार", "वैशाली", "सुधा रानी", "निर्दलीय"},
        {"Bihar", "Valmiki Nagar", "Munna Singh", "Independent", "2.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12837", "बिहार", "वाल्मीकि नगर", "मुन्ना सिंह", "निर्दलीय"},
};

public static final String[][] red_bucket = {
        {"Bihar", "Araria", "Md Matin", "2", " ", "बिहार", "अररिया", "मोद मतीन", " "},
        {"Bihar", "Araria", "Sudama Singh", "2", " ", "बिहार", "अररिया", "सुदामा सिंह", " "},
        {"Bihar", "Araria", "Mukesh Singh", "4", " ", "बिहार", "अररिया", "मुकेश सिंह", " "},
        {"Bihar", "Araria", "Abdul Wahid Khan", "2", " ", "बिहार", "अररिया", "अब्दुल वाहिद खान", " "},
        {"Bihar", "Araria", "Md Minhaz Alam", "4", " ", "बिहार", "अररिया", "एमडी मिन्हाज आलम", " "},
        {"Bihar", "Araria", "Sarfaraz Alam", "2", " ", "बिहार", "अररिया", "सरफराज आलम", " "},
        {"Bihar", "Araria", "Tarachand Paswan", "2", " ", "बिहार", "अररिया", "ताराचंद पासवान", " "},
        {"Bihar", "Araria", "Ramanand Rishideo", "3", " ", "बिहार", "अररिया", "रामानंद ऋषिदेव", " "},
        {"Bihar", "Araria", "Pradeep Kumar Singh", "1", " ", "बिहार", "अररिया", "प्रदीप कुमार सिंह", " "},
        {"Bihar", "Araria", "Shaheen Praveen", "2", " ", "बिहार", "अररिया", "शाहीन प्रवीण", " "},
        {"Bihar", "Arrah", "Raju Yadav", "2", " ", "बिहार", "आरा", "राजू यादव", " "},
        {"Bihar", "Arrah", "R. K. Singh", "1", " ", "बिहार", "आरा", "आरके सिंह", " "},
        {"Bihar", "Arrah", "Anil Kumar Singh", "3", " ", "बिहार", "आरा", "अनिल कुमार सिंह", " "},
        {"Bihar", "Arrah", "Krishna Paswan", "2", " ", "बिहार", "आरा", "कृष्णा पासवान", " "},
        {"Bihar", "Arrah", "Shiv Das Singh", "3", " ", "बिहार", "आरा", "शिव दास सिंह", " "},
        {"Bihar", "Arrah", "Raj Giri Bhagat", "3", " ", "बिहार", "आरा", "राज गिरी भगत", " "},
        {"Bihar", "Aurangabad", "Sushil Kumar Singh", "1", " ", "बिहार", "औरंगाबाद बिहा", "सुशील कुमार सिंह", " "},
        {"Bihar", "Aurangabad", "Yogendra Ram", "4", " ", "बिहार", "औरंगाबाद बिहा", "योगेन्द्र राम", " "},
        {"Bihar", "Aurangabad", "Dr Dharmendra Kumar", "2", " ", "बिहार", "औरंगाबाद बिहा", "डॉ। धर्मेंद्र कुमार", " "},
        {"Bihar", "Aurangabad", "Naresh Yadav", "2", " ", "बिहार", "औरंगाबाद बिहा", "नरेश यादव", " "},
        {"Bihar", "Aurangabad", "Subhash Kisanrao Patil", "2", " ", "बिहार", "औरंगाबाद बिहा", "सुभाष किसानराव पाटिल", " "},
        {"Bihar", "Banka", "Pramod Singh Weldone", "2", " ", "बिहार", "बांका", "प्रमोद सिंह वेल्डन", " "},
        {"Bihar", "Banka", "Putul Kumari", "2", " ", "बिहार", "बांका", "पुतुल कुमारी", " "},
        {"Bihar", "Banka", "Jai Prakash Narayan Yadav", "2", " ", "बिहार", "बांका", "जय प्रकाश नारायण यादव", " "},
        {"Bihar", "Banka", "Rajkishor Prasad", "2", " ", "बिहार", "बांका", "राजकिशोर प्रसाद", " "},
        {"Bihar", "Banka", "Amarjeet Kumar", "2", " ", "बिहार", "बांका", "अमरजीत कुमार", " "},
        {"Bihar", "Banka", "Phesal Ansari", "4", " ", "बिहार", "बांका", "फ़ेसल अंसारी", " "},
        {"Bihar", "Banka", "Md. Mukhtar Alam", "4", " ", "बिहार", "बांका", "मो। मुख्तार आलम", " "},
        {"Bihar", "Banka", "Md. Rafique Alam", "2", " ", "बिहार", "बांका", "मो। रफीक आलम", " "},
        {"Bihar", "Banka", "Manoj Kumar Sah", "4", " ", "बिहार", "बांका", "मनोज कुमार साह", " "},
        {"Bihar", "Banka", "Neelu Devi", "4", " ", "बिहार", "बांका", "नीलू देवी", " "},
        {"Bihar", "Banka", "Umakant Yadav", "3", " ", "बिहार", "बांका", "उमाकांत यादव", " "},
        {"Bihar", "Banka", "Pravin Kumar Jha", "4", " ", "बिहार", "बांका", "प्रवीण कुमार झा", " "},
        {"Bihar", "Banka", "Mp Yadav", "4", " ", "बिहार", "बांका", "Mp यादव", " "},
        {"Bihar", "Banka", "Naresh Yadav", "4", " ", "बिहार", "बांका", "नरेश यादव", " "},
        {"Bihar", "Banka", "Pawan Thakur", "4", " ", "बिहार", "बांका", "पवन ठाकुर", " "},
        {"Bihar", "Banka", "Mritiunjay Roy", "4", " ", "बिहार", "बांका", "मृत्युंजय रॉय", " "},
        {"Bihar", "Banka", "Giridhari Yadav", "2", " ", "बिहार", "बांका", "गिरधारी यादव", " "},
        {"Bihar", "Banka", "Syed Alamdar Hussain", "2", " ", "बिहार", "बांका", "सैयद आलमदार हुसैन", " "},
        {"Bihar", "Begusarai", "Dhiraj Narain", "3", " ", "बिहार", "बेगूसराय", "धीरज नारायण", " "},
        {"Bihar", "Begusarai", "Giriraj Singh", "1", " ", "बिहार", "बेगूसराय", "गिरिराज सिंह", " "},
        {"Bihar", "Begusarai", "Md. Tanweer Hassan", "2", " ", "बिहार", "बेगूसराय", "एमडी। तनवीर हसन", " "},
        {"Bihar", "Begusarai", "Kanhaiya Kumar", "2", " ", "बिहार", "बेगूसराय", "कन्हैया कुमार", " "},
        {"Bihar", "Begusarai", "Amar Kumar", "2", " ", "बिहार", "बेगूसराय", "अमर कुमार", " "},
        {"Bihar", "Begusarai", "Shambhu Kumar Singh", "2", " ", "बिहार", "बेगूसराय", "शंभू कुमार सिंह", " "},
        {"Bihar", "Begusarai", "Saurabh", "4", " ", "बिहार", "बेगूसराय", "सौरभ", " "},
        {"Bihar", "Begusarai", "Umesh Patel", "4", " ", "बिहार", "बेगूसराय", "उमेश पटेल", " "},
        {"Bihar", "Begusarai", "Maksudan Paswan", "4", " ", "बिहार", "बेगूसराय", "मकसूदन पासवान", " "},
        {"Bihar", "Bhagalpur", "Abhishek Priyadarshi", "4", " ", "बिहार", "भागलपुर", "अभिषेक प्रियदर्शी", " "},
        {"Bihar", "Bhagalpur", "Deepak Kumar", "4", " ", "बिहार", "भागलपुर", "दीपक कुमार", " "},
        {"Bihar", "Bhagalpur", "Shailesh Kumar", "4", " ", "बिहार", "भागलपुर", "शैलेश कुमार", " "},
        {"Bihar", "Bhagalpur", "Sushil Kumar Das", "3", " ", "बिहार", "भागलपुर", "सुशील कुमार दास", " "},
        {"Bihar", "Bhagalpur", "Mohammad Ashiq Ibrahimi", "2", " ", "बिहार", "भागलपुर", "मोहम्मद आशिक इब्राहिमी", " "},
        {"Bihar", "Bhagalpur", "Ajay Kumar Mandal", "4", " ", "बिहार", "भागलपुर", "अजय कुमार मंडल", " "},
        {"Bihar", "Buxar", "Ashwini Kumar Choubey", "1", " ", "बिहार", "बक्सर", "अश्विनी कुमार चौबे", " "},
        {"Bihar", "Buxar", "Ranjit Singh", "2", " ", "बिहार", "बक्सर", "रणजीत सिंह", " "},
        {"Bihar", "Buxar", "Jay Prakash Ram", "4", " ", "बिहार", "बक्सर", "जय प्रकाश राम", " "},
        {"Bihar", "Buxar", "Rakesh Kumar Rai", "4", " ", "बिहार", "बक्सर", "राकेश कुमार राय", " "},
        {"Bihar", "Buxar", "Anil Kumar Rai", "2", " ", "बिहार", "बक्सर", "अनिल कुमार राय", " "},
        {"Bihar", "Buxar", "Santosh Kumar Yadav", "2", " ", "बिहार", "बक्सर", "संतोष कुमार यादव", " "},
        {"Bihar", "Buxar", "Sushil Kumar Singh", "2", " ", "बिहार", "बक्सर", "सुशील कुमार सिंह", " "},
        {"Bihar", "Buxar", "Dhanjit Singh", "2", " ", "बिहार", "बक्सर", "धनजीत सिंह", " "},
        {"Bihar", "Buxar", "Jagadanand Singh", "2", " ", "बिहार", "बक्सर", "जगदानंद सिंह", " "},
        {"Bihar", "Buxar", "Anil Kumar", "2", " ", "बिहार", "बक्सर", "अनिल कुमार", " "},
        {"Bihar", "Darbhanga", "Md. Mukhtar", "2", " ", "बिहार", "दरभंगा", "मो। मुख्तार", " "},
        {"Bihar", "Darbhanga", "Abdul Ajij", "2", " ", "बिहार", "दरभंगा", "अब्दुल अजीज", " "},
        {"Bihar", "Darbhanga", "Pankaj Kumar Singh", "4", " ", "बिहार", "दरभंगा", "पंकज कुमार सिंह", " "},
        {"Bihar", "Darbhanga", "Saroj Kumar Chaudhary", "2", " ", "बिहार", "दरभंगा", "सरोज कुमार चौधरी", " "},
        {"Bihar", "Darbhanga", "Abdul Bari Siddiqui", "3", " ", "बिहार", "दरभंगा", "अब्दुल बारी सिद्दीकी", " "},
        {"Bihar", "Darbhanga", "Gopaljee Thakur", "1", " ", "बिहार", "दरभंगा", "गोपालजी ठाकुर", " "},
        {"Bihar", "Darbhanga", "Saguni Ray", "4", " ", "बिहार", "दरभंगा", "सगुनी रे", " "},
        {"Bihar", "Darbhanga", "Sanjay Paswan", "2", " ", "बिहार", "दरभंगा", "संजय पासवान", " "},
        {"Bihar", "Gaya", "Shiv Shankar", "2", " ", "बिहार", "गया", "शिव शंकर", " "},
        {"Bihar", "Gaya", "Vijay Kumar", "2", " ", "बिहार", "गया", "विजय कुमार", " "},
        {"Bihar", "Gaya", "Rakesh Chaudhari", "4", " ", "बिहार", "गया", "राकेश चौधरी", " "},
        {"Bihar", "Gaya", "Giridhar Sapera", "4", " ", "बिहार", "गया", "गिरिधर सपेरा", " "},
        {"Bihar", "Gaya", "Din Dayal Bharti", "4", " ", "बिहार", "गया", "दीन दयाल भारती", " "},
        {"Bihar", "Gaya", "Sunil Paswan", "4", " ", "बिहार", "गया", "सुनील पासवान", " "},
        {"Bihar", "Gaya", "Jitan Ram Manjhi", "2", " ", "बिहार", "गया", "जीतन राम मांझी", " "},
        {"Bihar", "Gaya", "Rajesh Kumar Paswan", "4", " ", "बिहार", "गया", "राजेश कुमार पासवान", " "},
        {"Bihar", "Gopalganj", "Om Prakash Manjhi", "2", " ", "बिहार", "गोपालगंज", "ओम प्रकाश मांझी", " "},
        {"Bihar", "Gopalganj", "Gaya Ram", "3", " ", "बिहार", "गोपालगंज", "गया राम", " "},
        {"Bihar", "Gopalganj", "Surendra Ram S/O Ganesh Ram", "2", " ", "बिहार", "गोपालगंज", "सुरेंद्र राम एस / ओ गणेश राम", " "},
        {"Bihar", "Gopalganj", "Ajay Paswan", "2", " ", "बिहार", "गोपालगंज", "अजय पासवान", " "},
        {"Bihar", "Gopalganj", "Surendra Ram S/O Late Chandradev Ram", "2", " ", "बिहार", "गोपालगंज", "सुरेंद्र राम एस / ओ स्वर्गीय चंद्रदेव राम", " "},
        {"Bihar", "Hajipur", "Dasai Chaudhary", "3", " ", "बिहार", "हाजीपुर", "दसई चौधरी", " "},
        {"Bihar", "Hajipur", "Jibas Paswan", "2", " ", "बिहार", "हाजीपुर", "जिबास पासवान", " "},
        {"Bihar", "Hajipur", "Umesh Das", "4", " ", "बिहार", "हाजीपुर", "उमेश दास", " "},
        {"Bihar", "Hajipur", "Pashupati Kumar Paras", "2", " ", "बिहार", "हाजीपुर", "पशुपति कुमार पारस", " "},
        {"Bihar", "Hajipur", "Balendra Das", "2", " ", "बिहार", "हाजीपुर", "बालेन्द्र दास", " "},
        {"Bihar", "Hajipur", "Rajgir Paswan", "4", " ", "बिहार", "हाजीपुर", "राजगीर पासवान", " "},
        {"Bihar", "Hajipur", "Shivchandra Ram", "2", " ", "बिहार", "हाजीपुर", "शिवचंद्र राम", " "},
        {"Bihar", "Hajipur", "Arvind Paswan", "4", " ", "बिहार", "हाजीपुर", "अरविंद पासवान", " "},
        {"Bihar", "Hajipur", "Raj Kumar Paswan", "4", " ", "बिहार", "हाजीपुर", "राज कुमार पासवान", " "},
        {"Bihar", "Jahanabad", "Rajendra Paswan", "3", " ", "बिहार", "जहानाबाद", "राजेंद्र पासवान", " "},
        {"Bihar", "Jahanabad", "Surendra Prasad Yadav", "2", " ", "बिहार", "जहानाबाद", "सुरेंद्र प्रसाद यादव", " "},
        {"Bihar", "Jahanabad", "Ramjee Kewat", "4", " ", "बिहार", "जहानाबाद", "रामजी केवट", " "},
        {"Bihar", "Jahanabad", "Arun Kumar", "2", " ", "बिहार", "जहानाबाद", "अरुण कुमार", " "},
        {"Bihar", "Jahanabad", "Nityanand Singh", "2", " ", "बिहार", "जहानाबाद", "नित्यानंद सिंह", " "},
        {"Bihar", "Jahanabad", "Chandeshwar Prasad", "2", " ", "बिहार", "जहानाबाद", "चंदेश्वर प्रसाद", " "},
        {"Bihar", "Jahanabad", "Arbind Kumar", "2", " ", "बिहार", "जहानाबाद", "अरबिंद कुमार", " "},
        {"Bihar", "Jahanabad", "Kunti Devi", "2", " ", "बिहार", "जहानाबाद", "कुंती देवी", " "},
        {"Bihar", "Jamui", "Bhudeo Choudhary", "2", " ", "बिहार", "जमुई", "भूदेव चौधरी", " "},
        {"Bihar", "Jamui", "Pankaj Kumar Das", "4", " ", "बिहार", "जमुई", "पंकज कुमार दास", " "},
        {"Bihar", "Jamui", "Ajay Kumar", "2", " ", "बिहार", "जमुई", "अजय कुमार", " "},
        {"Bihar", "Jamui", "Chirag Kumar Paswan", "2", " ", "बिहार", "जमुई", "चिराग कुमार पासवान", " "},
        {"Bihar", "Jhanjharpur", "Prabhat Prasad", "3", " ", "बिहार", "झंझारपुर", "प्रभात प्रसाद", " "},
        {"Bihar", "Jhanjharpur", "Ganga Prasad Yadav", "2", " ", "बिहार", "झंझारपुर", "गंगा प्रसाद यादव", " "},
        {"Bihar", "Jhanjharpur", "Om Prakash Poddar", "2", " ", "बिहार", "झंझारपुर", "ओम प्रकाश पोद्दार", " "},
        {"Bihar", "Jhanjharpur", "Chhedi Ram", "4", " ", "बिहार", "झंझारपुर", "छेदी राम", " "},
        {"Bihar", "Jhanjharpur", "Lakshman Prasad Yadav", "4", " ", "बिहार", "झंझारपुर", "लक्ष्मण प्रसाद यादव", " "},
        {"Bihar", "Jhanjharpur", "Devendra Prasad Yadav", "3", " ", "बिहार", "झंझारपुर", "देवेंद्र प्रसाद यादव", " "},
        {"Bihar", "Jhanjharpur", "Ratneshwar Jha", "4", " ", "बिहार", "झंझारपुर", "रत्नेश्वर झा", " "},
        {"Bihar", "Jhanjharpur", "Ramanand Thakur", "2", " ", "बिहार", "झंझारपुर", "रामानंद ठाकुर", " "},
        {"Bihar", "Jhanjharpur", "Ramprit Mandal", "2", " ", "बिहार", "झंझारपुर", "रामप्रीत मंडल", " "},
        {"Bihar", "Jhanjharpur", "Ganpati Jha", "2", " ", "बिहार", "झंझारपुर", "गणपति झा", " "},
        {"Bihar", "Jhanjharpur", "Gulab Yadav", "2", " ", "बिहार", "झंझारपुर", "गुलाब यादव", " "},
        {"Bihar", "Jhanjharpur", "Bablu Gupta", "2", " ", "बिहार", "झंझारपुर", "बबलू गुप्ता", " "},
        {"Bihar", "Karakat", "Pradeep Chouhan", "2", " ", "बिहार", "काराकाट", "प्रदीप चौहान", " "},
        {"Bihar", "Karakat", "Gorakh Ram", "2", " ", "बिहार", "काराकाट", "गोरख राम", " "},
        {"Bihar", "Karakat", "Abhiram Priyadarshi", "4", " ", "बिहार", "काराकाट", "अभिराम प्रियदर्शी", " "},
        {"Bihar", "Karakat", "Usha Sharan", "2", " ", "बिहार", "काराकाट", "उषा शरण", " "},
        {"Bihar", "Karakat", "Upendra Kushwaha", "2", " ", "बिहार", "काराकाट", "उपेंद्र कुशवाहा", " "},
        {"Bihar", "Karakat", "Ramji Singh Kanta", "4", " ", "बिहार", "काराकाट", "रामजी सिंह कांता", " "},
        {"Bihar", "Karakat", "Mamta Pandey", "4", " ", "बिहार", "काराकाट", "ममता पांडे", " "},
        {"Bihar", "Karakat", "Raj Narayan Tiwari", "4", " ", "बिहार", "काराकाट", "राज नारायण तिवारी", " "},
        {"Bihar", "Karakat", "Manoj Singh Kushvaha", "2", " ", "बिहार", "काराकाट", "मनोज सिंह कुशवाह", " "},
        {"Bihar", "Karakat", "Jyoti Rashmi", "2", " ", "बिहार", "काराकाट", "ज्योति रश्मि", " "},
        {"Bihar", "Karakat", "Mahabali Singh", "2", " ", "बिहार", "काराकाट", "महाबली सिंह", " "},
        {"Bihar", "Karakat", "Neelam Kumari", "2", " ", "बिहार", "काराकाट", "नीलम कुमारी", " "},
        {"Bihar", "Karakat", "Basudeo Hazarika", "4", " ", "बिहार", "काराकाट", "बासुदेव हजारिका", " "},
        {"Bihar", "Karakat", "Ram Ayodhya Singh", "4", " ", "बिहार", "काराकाट", "राम अयोध्या सिंह", " "},
        {"Bihar", "Karakat", "Shashikant Singh", "4", " ", "बिहार", "काराकाट", "शशिकांत सिंह", " "},
        {"Bihar", "Karakat", "Rameshwar Singh", "3", " ", "बिहार", "काराकाट", "रामेश्वर सिंह", " "},
        {"Bihar", "Karakat", "Kamlesh Ram (Prasad)", "4", " ", "बिहार", "काराकाट", "कमलेश राम (प्रसाद)", " "},
        {"Bihar", "Karakat", "Raja Ram Singh", "2", " ", "बिहार", "काराकाट", "राजा राम सिंह", " "},
        {"Bihar", "Katihar", "Samir Kumar Jha", "4", " ", "बिहार", "कटिहार", "समीर कुमार झा", " "},
        {"Bihar", "Katihar", "Shivnandan Mandal", "3", " ", "बिहार", "कटिहार", "शिवनंदन मंडल", " "},
        {"Bihar", "Katihar", "Muhammad Shakur", "3", " ", "बिहार", "कटिहार", "मुहम्मद शकूर", " "},
        {"Bihar", "Katihar", "Ganga Kebat", "4", " ", "बिहार", "कटिहार", "गंगा केवट", " "},
        {"Bihar", "Katihar", "Basukinath Sah", "4", " ", "बिहार", "कटिहार", "बासुकीनाथ साह", " "},
        {"Bihar", "Katihar", "Abdur Rahman", "4", " ", "बिहार", "कटिहार", "अब्दुर रहमान", " "},
        {"Bihar", "Katihar", "Dulal Chandra Goswami", "2", " ", "बिहार", "कटिहार", "दुलाल चंद्र गोस्वामी", " "},
        {"Bihar", "Katihar", "Shah Tariq Anwar", "1", " ", "बिहार", "कटिहार", "शाह तारिक अनवर", " "},
        {"Bihar", "Katihar", "Marang Hansda", "4", " ", "बिहार", "कटिहार", "मारंग हांसदा", " "},
        {"Bihar", "Khagaria", "Parmanand Singh", "2", " ", "बिहार", "खगरिया", "परमानंद सिंह", " "},
        {"Bihar", "Khagaria", "Bandan Kumar Singh", "4", " ", "बिहार", "खगरिया", "बंदन कुमार सिंह", " "},
        {"Bihar", "Khagaria", "Ramakant Choudhari", "4", " ", "बिहार", "खगरिया", "रमाकांत चौधरी", " "},
        {"Bihar", "Khagaria", "Sobha Devi", "4", " ", "बिहार", "खगरिया", "सोभा देवी", " "},
        {"Bihar", "Khagaria", "Tej Bahadur Singh", "3", " ", "बिहार", "खगरिया", "तेज बहादुर सिंह", " "},
        {"Bihar", "Khagaria", "Sunil Yadav", "4", " ", "बिहार", "खगरिया", "सुनील यादव", " "},
        {"Bihar", "Khagaria", "Choudhary Mahbub Ali Kaisar", "2", " ", "बिहार", "खगरिया", "चौधरी महबूब अली कैसर", " "},
        {"Bihar", "Khagaria", "Shiv Narayan Singh", "4", " ", "बिहार", "खगरिया", "शिव नारायण सिंह", " "},
        {"Bihar", "Khagaria", "Madhuvala Devi", "4", " ", "बिहार", "खगरिया", "मधुवाला देवी", " "},
        {"Bihar", "Khagaria", "Nagendra Singh Tyagi", "2", " ", "बिहार", "खगरिया", "नागेंद्र सिंह त्यागी", " "},
        {"Bihar", "Khagaria", "Moni Kumar", "4", " ", "बिहार", "खगरिया", "मोनी कुमार", " "},
        {"Bihar", "Khagaria", "Umesh Chandra Bharti", "2", " ", "बिहार", "खगरिया", "उमेश चंद्र भारती", " "},
        {"Bihar", "Khagaria", "Mukesh Sahani", "2", " ", "बिहार", "खगरिया", "मुकेश सहनी", " "},
        {"Bihar", "Khagaria", "Dhirendra Choudhary", "4", " ", "बिहार", "खगरिया", "धीरेन्द्र चौधरी", " "},
        {"Bihar", "Kishanganj", "Syed Mahmood Ashraf", "2", " ", "बिहार", "किशनगंज", "सैयद महमूद अशरफ", " "},
        {"Bihar", "Kishanganj", "Javed Akhter", "2", " ", "बिहार", "किशनगंज", "जावेद अख्तर", " "},
        {"Bihar", "Kishanganj", "Haserul", "4", " ", "बिहार", "किशनगंज", "Haserul", " "},
        {"Bihar", "Kishanganj", "Chhote Lal Mahto", "4", " ", "बिहार", "किशनगंज", "छोटे लाल महतो", " "},
        {"Bihar", "Kishanganj", "Shukal Murmu", "4", " ", "बिहार", "किशनगंज", "शुकल मुर्मू", " "},
        {"Bihar", "Kishanganj", "Pradeep Kumar Singh", "4", " ", "बिहार", "किशनगंज", "प्रदीप कुमार सिंह", " "},
        {"Bihar", "Kishanganj", "Asad Alam", "4", " ", "बिहार", "किशनगंज", "असद आलम", " "},
        {"Bihar", "Kishanganj", "Alimuddin Ansari", "4", " ", "बिहार", "किशनगंज", "अलीमुद्दीन अंसारी", " "},
        {"Bihar", "Kishanganj", "Rajendra Paswan", "2", " ", "बिहार", "किशनगंज", "राजेंद्र पासवान", " "},
        {"Bihar", "Kishanganj", "Akhtarul Iman", "2", " ", "बिहार", "किशनगंज", "अख्तरुल ईमान", " "},
        {"Bihar", "Kishanganj", "Dr. Mohammad Jawed", "1", " ", "बिहार", "किशनगंज", "डॉ। मोहम्मद जावेद", " "},
        {"Bihar", "Kishanganj", "Azimuddin", "3", " ", "बिहार", "किशनगंज", "Azimuddin", " "},
        {"Bihar", "Madhepura", "Sharad Yadav", "2", " ", "बिहार", "मधेपुरा", "शरद यादव", " "},
        {"Bihar", "Madhepura", "Dinesh Chandra Yadav", "2", " ", "बिहार", "मधेपुरा", "दिनेश चंद्र यादव", " "},
        {"Bihar", "Madhepura", "Manoj Kumar Manda", "4", " ", "बिहार", "मधेपुरा", "मनोज कुमार मंदा", " "},
        {"Bihar", "Madhepura", "Umashankar", "4", " ", "बिहार", "मधेपुरा", "उमाशंकर", " "},
        {"Bihar", "Madhepura", "Rajesh Ranjan", "2", " ", "बिहार", "मधेपुरा", "राजेश रंजन", " "},
        {"Bihar", "Madhepura", "Rajo Sah", "4", " ", "बिहार", "मधेपुरा", "राजो साह", " "},
        {"Bihar", "Madhubani", "Vidya Sagar Mandal", "2", " ", "बिहार", "मधुबनी", "विद्या सागर मंडल", " "},
        {"Bihar", "Madhubani", "Ashok Kumar Yadav", "1", " ", "बिहार", "मधुबनी", "अशोक कुमार यादव", " "},
        {"Bihar", "Madhubani", "Md. Khalique Ansari", "4", " ", "बिहार", "मधुबनी", "मो। खालिक अंसारी", " "},
        {"Bihar", "Madhubani", "Dr. Shakeel Ahmad", "1", " ", "बिहार", "मधुबनी", "डॉ। शकील अहमद", " "},
        {"Bihar", "Madhubani", "Dhaneshwar Mahto", "2", " ", "बिहार", "मधुबनी", "धनेश्वर महतो", " "},
        {"Bihar", "Madhubani", "Hema Jha", "4", " ", "बिहार", "मधुबनी", "हेमा झा", " "},
        {"Bihar", "Madhubani", "Satish Chandra Jha", "2", " ", "बिहार", "मधुबनी", "सतीश चंद्र झा", " "},
        {"Bihar", "Madhubani", "Ram Swarup Bharti", "4", " ", "बिहार", "मधुबनी", "राम स्वरूप भारती", " "},
        {"Bihar", "Madhubani", "Subhash Chandra Jha", "2", " ", "बिहार", "मधुबनी", "सुभाष चंद्र झा", " "},
        {"Bihar", "Madhubani", "Abhijit Kumar Singh", "2", " ", "बिहार", "मधुबनी", "अभिजीत कुमार सिंह", " "},
        {"Bihar", "Madhubani", "Anil Kumar Sah", "2", " ", "बिहार", "मधुबनी", "अनिल कुमार साह", " "},
        {"Bihar", "Madhubani", "Raju Kumar Raj", "4", " ", "बिहार", "मधुबनी", "राजू कुमार राज", " "},
        {"Bihar", "Madhubani", "Rekha Ranjan Yadav", "4", " ", "बिहार", "मधुबनी", "रेखा रंजन यादव", " "},
        {"Bihar", "Maharajganj", "Ali Azhar Ansari", "4", " ", "बिहार", "महाराजगंज", "अली अजहर अंसारी", " "},
        {"Bihar", "Maharajganj", "Aravind Kumar Sharma", "4", " ", "बिहार", "महाराजगंज", "अरविंद कुमार शर्मा", " "},
        {"Bihar", "Maharajganj", "Randhir Kumar Singh", "2", " ", "बिहार", "महाराजगंज", "रणधीर कुमार सिंह", " "},
        {"Bihar", "Maharajganj", "Dr. Gopal Prasad", "2", " ", "बिहार", "महाराजगंज", "डॉ। गोपाल प्रसाद", " "},
        {"Bihar", "Maharajganj", "Anirudh Prasad", "2", " ", "बिहार", "महाराजगंज", "अनिरुद्ध प्रसाद", " "},
        {"Bihar", "Maharajganj", "Shree Bhagwan Singh", "2", " ", "बिहार", "महाराजगंज", "श्री भगवान सिंह", " "},
        {"Bihar", "Maharajganj", "Subhash Singh", "4", " ", "बिहार", "महाराजगंज", "सुभाष सिंह", " "},
        {"Bihar", "Maharajganj", "Janardan Singh Sigriwal", "1", " ", "बिहार", "महाराजगंज", "जनार्दन सिंह सिग्रीवाल", " "},
        {"Bihar", "Munger", "Santosh Kumar", "4", " ", "बिहार", "मुंगेर", "संतोष कुमार", " "},
        {"Bihar", "Munger", "Ajit Kumar", "4", " ", "बिहार", "मुंगेर", "अजीत कुमार", " "},
        {"Bihar", "Munger", "Dina Saw", "4", " ", "बिहार", "मुंगेर", "दीना देखा", " "},
        {"Bihar", "Munger", "Nilam Devi", "1", " ", "बिहार", "मुंगेर", "निलम देवी", " "},
        {"Bihar", "Munger", "Mahesh Ram", "4", " ", "बिहार", "मुंगेर", "महेश राम", " "},
        {"Bihar", "Munger", "Raushan Kumar", "4", " ", "बिहार", "मुंगेर", "रौशन कुमार", " "},
        {"Bihar", "Munger", "Kumar Navneet Himanshu", "2", " ", "बिहार", "मुंगेर", "कुमार नवनीत हिमांशु", " "},
        {"Bihar", "Munger", "Vikash Kumar Arya", "2", " ", "बिहार", "मुंगेर", "विकाश कुमार आर्य", " "},
        {"Bihar", "Munger", "Sanjay Kesari", "2", " ", "बिहार", "मुंगेर", "संजय केसरी", " "},
        {"Bihar", "Munger", "Suryoday Paswan", "2", " ", "बिहार", "मुंगेर", "सूर्योदय पासवान", " "},
        {"Bihar", "Munger", "Rajiv Ranjan Singh", "2", " ", "बिहार", "मुंगेर", "राजीव रंजन सिंह", " "},
        {"Bihar", "Munger", "Sonelal Kora", "4", " ", "बिहार", "मुंगेर", "सोनेलाल कोरा", " "},
        {"Bihar", "Munger", "Uchit Kumar", "4", " ", "बिहार", "मुंगेर", "उचित कुमार", " "},
        {"Bihar", "Muzaffarpur", "Swarnlata Devi", "4", " ", "बिहार", "मुजफ्फरपुर", "स्वर्णलता देवी", " "},
        {"Bihar", "Muzaffarpur", "Jauhar Azad", "4", " ", "बिहार", "मुजफ्फरपुर", "जौहर आज़ाद", " "},
        {"Bihar", "Muzaffarpur", "Nageshwar Prasad Singh", "4", " ", "बिहार", "मुजफ्फरपुर", "नागेश्वर प्रसाद सिंह", " "},
        {"Bihar", "Muzaffarpur", "Ajay Nishad", "1", " ", "बिहार", "मुजफ्फरपुर", "अजय निषाद", " "},
        {"Bihar", "Muzaffarpur", "Mohamad Idris", "4", " ", "बिहार", "मुजफ्फरपुर", "मोहम्मद इदरीस", " "},
        {"Bihar", "Muzaffarpur", "Pankaj Kumar", "4", " ", "बिहार", "मुजफ्फरपुर", "पंकज कुमार", " "},
        {"Bihar", "Muzaffarpur", "Shiv Shakti Monu", "4", " ", "बिहार", "मुजफ्फरपुर", "शिव शक्ति मोनू", " "},
        {"Bihar", "Muzaffarpur", "Shiva Bihari Singhania", "4", " ", "बिहार", "मुजफ्फरपुर", "शिव बिहारी सिंघानिया", " "},
        {"Bihar", "Muzaffarpur", "Surendra Ray", "4", " ", "बिहार", "मुजफ्फरपुर", "सुरेंद्र रे", " "},
        {"Bihar", "Muzaffarpur", "Dharmendra Paswan", "4", " ", "बिहार", "मुजफ्फरपुर", "धर्मेंद्र पासवान", " "},
        {"Bihar", "Muzaffarpur", "Devendra Rakesh", "3", " ", "बिहार", "मुजफ्फरपुर", "देवेंद्र राकेश", " "},
        {"Bihar", "Muzaffarpur", "Sukhdeo Prasad", "3", " ", "बिहार", "मुजफ्फरपुर", "सुखदेव प्रसाद", " "},
        {"Bihar", "Muzaffarpur", "Ritesh Prasad", "4", " ", "बिहार", "मुजफ्फरपुर", "रितेश प्रसाद", " "},
        {"Bihar", "Nalanda", "Kumar Hari Charan Singh Yadav", "4", " ", "बिहार", "नालंदा", "कुमार हरि चरण सिंह यादव", " "},
        {"Bihar", "Nalanda", "Punit Kumar", "2", " ", "बिहार", "नालंदा", "पुनीत कुमार", " "},
        {"Bihar", "Nalanda", "Shailendra Chaudhari", "4", " ", "बिहार", "नालंदा", "शैलेंद्र चौधरी", " "},
        {"Bihar", "Nalanda", "Mohammad Surkhab Alam", "4", " ", "बिहार", "नालंदा", "मोहम्मद सुरखाब आलम", " "},
        {"Bihar", "Nalanda", "Nita Devi", "4", " ", "बिहार", "नालंदा", "नीता देवी", " "},
        {"Bihar", "Nalanda", "Shashi Kumar", "2", " ", "बिहार", "नालंदा", "शशि कुमार", " "},
        {"Bihar", "Nalanda", "Surendra Singh", "4", " ", "बिहार", "नालंदा", "सुरेंद्र सिंह", " "},
        {"Bihar", "Nalanda", "Sampati Kumar", "4", " ", "बिहार", "नालंदा", "संपत कुमार", " "},
        {"Bihar", "Nalanda", "Ramchandra Prasad", "2", " ", "बिहार", "नालंदा", "रामचंद्र प्रसाद", " "},
        {"Bihar", "Nalanda", "Ramvilaf Paswan", "4", " ", "बिहार", "नालंदा", "रामविलाफ पासवान", " "},
        {"Bihar", "Nalanda", "Ashok Kumar", "2", " ", "बिहार", "नालंदा", "अशोक कुमार", " "},
        {"Bihar", "Nalanda", "Sudhir Kumar", "4", " ", "बिहार", "नालंदा", "सुधीर कुमार", " "},
        {"Bihar", "Nalanda", "Ram Charitra Prasad Singh", "2", " ", "बिहार", "नालंदा", "राम चरित्र प्रसाद सिंह", " "},
        {"Bihar", "Nalanda", "Usha Devi", "4", " ", "बिहार", "नालंदा", "उषा देवी", " "},
        {"Bihar", "Nalanda", "Sohavan Paswan", "4", " ", "बिहार", "नालंदा", "सोहन पासवान", " "},
        {"Bihar", "Nalanda", "Mohan Bind", "2", " ", "बिहार", "नालंदा", "मोहन बिंद", " "},
        {"Bihar", "Nalanda", "Rajnish Kumar Paswan", "4", " ", "बिहार", "नालंदा", "रजनीश कुमार पासवान", " "},
        {"Bihar", "Nalanda", "Pawan Kumar Pandey", "4", " ", "बिहार", "नालंदा", "पवन कुमार पांडे", " "},
        {"Bihar", "Nalanda", "Kaushlendra Kumar", "4", " ", "बिहार", "नालंदा", "कौशलेंद्र कुमार", " "},
        {"Bihar", "Nalanda", "Ashok Kumar Azad", "4", " ", "बिहार", "नालंदा", "अशोक कुमार आजाद", " "},
        {"Bihar", "Nalanda", "Dilip Rawat", "4", " ", "बिहार", "नालंदा", "दिलीप रावत", " "},
        {"Bihar", "Nalanda", "Dinanath Pandey", "3", " ", "बिहार", "नालंदा", "दीनानाथ पांडे", " "},
        {"Bihar", "Nalanda", "Rekha Kumari", "4", " ", "बिहार", "नालंदा", "रेखा कुमारी", " "},
        {"Bihar", "Nalanda", "Shankar Pandey", "4", " ", "बिहार", "नालंदा", "शंकर पांडे", " "},
        {"Bihar", "Nalanda", "Chiranjib Kumar", "4", " ", "बिहार", "नालंदा", "चिरंजीब कुमार", " "},
        {"Bihar", "Nalanda", "Purushotam Sharma", "4", " ", "बिहार", "नालंदा", "पुरुषोत्तम शर्मा", " "},
        {"Bihar", "Nalanda", "Mintu Kumar", "4", " ", "बिहार", "नालंदा", "मिंटू कुमार", " "},
        {"Bihar", "Nawada", "Prof. K.B. Prasad", "3", " ", "बिहार", "नवादा", "केबी प्रसाद", " "},
        {"Bihar", "Nawada", "Vishnu Dev Yadav", "3", " ", "बिहार", "नवादा", "विष्णु देव यादव", " "},
        {"Bihar", "Nawada", "Naresh Prasad", "2", " ", "बिहार", "नवादा", "नरेश प्रसाद", " "},
        {"Bihar", "Nawada", "Vijay Ram", "4", " ", "बिहार", "नवादा", "विजय राम", " "},
        {"Bihar", "Nawada", "Ranganathacharya", "2", " ", "बिहार", "नवादा", "Ranganathacharya", " "},
        {"Bihar", "Nawada", "Rakesh Raushan", "2", " ", "बिहार", "नवादा", "राकेश रौशन", " "},
        {"Bihar", "Nawada", "Nivedita Singh", "2", " ", "बिहार", "नवादा", "निवेदिता सिंह", " "},
        {"Bihar", "Nawada", "Chandan Singh", "2", " ", "बिहार", "नवादा", "चंदन सिंह", " "},
        {"Bihar", "Nawada", "Vibha Devi", "4", " ", "बिहार", "नवादा", "विभा देवी", " "},
        {"Bihar", "Paschim Champaran", "Vikash Kumar Prasad", "4", " ", "बिहार", "पश्चिम चंपारण", "विकाश कुमार प्रसाद", " "},
        {"Bihar", "Paschim Champaran", "Brijesh Kumar Kushwaha", "2", " ", "बिहार", "पश्चिम चंपारण", "बृजेश कुमार कुशवाहा", " "},
        {"Bihar", "Paschim Champaran", "Nafish Ahmad", "4", " ", "बिहार", "पश्चिम चंपारण", "नफीश अहमद", " "},
        {"Bihar", "Paschim Champaran", "Sanjay Kumar Patel", "2", " ", "बिहार", "पश्चिम चंपारण", "संजय कुमार पटेल", " "},
        {"Bihar", "Paschim Champaran", "Ratan Kumar Sarkar", "3", " ", "बिहार", "पश्चिम चंपारण", "रतन कुमार सरकार", " "},
        {"Bihar", "Paschim Champaran", "Rakesh Kumar", "2", " ", "बिहार", "पश्चिम चंपारण", "राकेश कुमार", " "},
        {"Bihar", "Paschim Champaran", "Dr. Sanjay Jaiswal", "1", " ", "बिहार", "पश्चिम चंपारण", "डॉ। संजय जायसवाल", " "},
        {"Bihar", "Pataliputra", "Lalita Ray", "4", " ", "बिहार", "पाटलिपुत्र", "ललिता रे", " "},
        {"Bihar", "Pataliputra", "Vinod Das", "4", " ", "बिहार", "पाटलिपुत्र", "विनोद दास", " "},
        {"Bihar", "Pataliputra", "Pupul Kumar Sharma", "4", " ", "बिहार", "पाटलिपुत्र", "पुपुल कुमार शर्मा", " "},
        {"Bihar", "Pataliputra", "Sohan Ray", "3", " ", "बिहार", "पाटलिपुत्र", "सोहन रे", " "},
        {"Bihar", "Pataliputra", "Ram Kripal Yadav", "1", " ", "बिहार", "पाटलिपुत्र", "राम कृपाल यादव", " "},
        {"Bihar", "Pataliputra", "Jitendra Bind", "4", " ", "बिहार", "पाटलिपुत्र", "जितेंद्र बिंद", " "},
        {"Bihar", "Pataliputra", "Mantu Kumar", "4", " ", "बिहार", "पाटलिपुत्र", "मंटू कुमार", " "},
        {"Bihar", "Pataliputra", "Suresh Paswan", "4", " ", "बिहार", "पाटलिपुत्र", "सुरेश पासवान", " "},
        {"Bihar", "Pataliputra", "Shiv Kumar Singh", "2", " ", "बिहार", "पाटलिपुत्र", "शिव कुमार सिंह", " "},
        {"Bihar", "Pataliputra", "Md. Taufique Ahmad", "4", " ", "बिहार", "पाटलिपुत्र", "मो। तौफीक अहमद", " "},
        {"Bihar", "Pataliputra", "Bindu Devi", "4", " ", "बिहार", "पाटलिपुत्र", "बिन्दु देवी", " "},
        {"Bihar", "Pataliputra", "Ram Narayan Manjhi", "4", " ", "बिहार", "पाटलिपुत्र", "राम नारायण मांझी", " "},
        {"Bihar", "Pataliputra", "Ram Pravesh Rajak", "3", " ", "बिहार", "पाटलिपुत्र", "रामप्रवेश रजक", " "},
        {"Bihar", "Pataliputra", "Shailesh Kumar", "4", " ", "बिहार", "पाटलिपुत्र", "शैलेश कुमार", " "},
        {"Bihar", "Pataliputra", "Misha Bharti", "2", " ", "बिहार", "पाटलिपुत्र", "मिशा भारती", " "},
        {"Bihar", "Patna Sahib", "Akhilesh Kumar", "4", " ", "बिहार", "पटना साहिब", "अखिलेश कुमार", " "},
        {"Bihar", "Patna Sahib", "Basant Singh", "4", " ", "बिहार", "पटना साहिब", "बसंत सिंह", " "},
        {"Bihar", "Patna Sahib", "Rita Devi", "4", " ", "बिहार", "पटना साहिब", "रीता देवी", " "},
        {"Bihar", "Patna Sahib", "Javed", "4", " ", "बिहार", "पटना साहिब", "जावेद", " "},
        {"Bihar", "Patna Sahib", "Amit Kumar Gupta", "4", " ", "बिहार", "पटना साहिब", "अमित कुमार गुप्ता", " "},
        {"Bihar", "Patna Sahib", "Ravi Shankar Prasad", "1", " ", "बिहार", "पटना साहिब", "रविशंकर प्रसाद", " "},
        {"Bihar", "Patna Sahib", "Shatrughan Sinha", "1", " ", "बिहार", "पटना साहिब", "शत्रुघ्न सिन्हा", " "},
        {"Bihar", "Patna Sahib", "Rani Devi", "4", " ", "बिहार", "पटना साहिब", "रानी देवी", " "},
        {"Bihar", "Patna Sahib", "Ashok Kumar Gupta", "3", " ", "बिहार", "पटना साहिब", "अशोक कुमार गुप्ता", " "},
        {"Bihar", "Purnia", "Shobha Soren", "4", " ", "बिहार", "पूर्णिया", "शोभा सोरेन", " "},
        {"Bihar", "Purnia", "Md Akhtar Ali", "4", " ", "बिहार", "पूर्णिया", "एमडी अख्तर अली", " "},
        {"Bihar", "Purnia", "Rajiv Kumar Singh", "4", " ", "बिहार", "पूर्णिया", "राजीव कुमार सिंह", " "},
        {"Bihar", "Purnia", "Shubhash Kumar Thakur", "4", " ", "बिहार", "पूर्णिया", "शुभाष कुमार ठाकुर", " "},
        {"Bihar", "Purnia", "Uday Singh", "1", " ", "बिहार", "पूर्णिया", "उदय सिंह", " "},
        {"Bihar", "Purnia", "Arjun Singh", "2", " ", "बिहार", "पूर्णिया", "अर्जुन सिंह", " "},
        {"Bihar", "Purnia", "Ashok Kumar Singh", "4", " ", "बिहार", "पूर्णिया", "अशोक कुमार सिंह", " "},
        {"Bihar", "Purnia", "Jitendra Urab", "2", " ", "बिहार", "पूर्णिया", "जितेन्द्र उरब", " "},
        {"Bihar", "Purnia", "Santosh Kumar", "2", " ", "बिहार", "पूर्णिया", "संतोष कुमार", " "},
        {"Bihar", "Purnia", "Anirudh Mehta", "4", " ", "बिहार", "पूर्णिया", "अनिरुद्ध मेहता", " "},
        {"Bihar", "Purnia", "Ashok Kumar Sah", "2", " ", "बिहार", "पूर्णिया", "अशोक कुमार साह", " "},
        {"Bihar", "Purnia", "Manju Murmu", "4", " ", "बिहार", "पूर्णिया", "मंजू मुर्मू", " "},
        {"Bihar", "Purnia", "Sageer Ahmad", "4", " ", "बिहार", "पूर्णिया", "सगीर अहमद", " "},
        {"Bihar", "Purnia", "Rajesh Kumar", "4", " ", "बिहार", "पूर्णिया", "राजेश कुमार", " "},
        {"Bihar", "Purvi Champaran", "Shatrughna Tiwary", "2", " ", "बिहार", "पूर्वी चंपारण", "शत्रुघ्न तिवारी", " "},
        {"Bihar", "Purvi Champaran", "Shekh Seraj", "2", " ", "बिहार", "पूर्वी चंपारण", "शेख सेराज", " "},
        {"Bihar", "Purvi Champaran", "Radha Mohan Singh", "1", " ", "बिहार", "पूर्वी चंपारण", "राधा मोहन सिंह", " "},
        {"Bihar", "Purvi Champaran", "Randhir Kumar Tiwari", "4", " ", "बिहार", "पूर्वी चंपारण", "रणधीर कुमार तिवारी", " "},
        {"Bihar", "Purvi Champaran", "Parasnath Ram", "2", " ", "बिहार", "पूर्वी चंपारण", "पारसनाथ राम", " "},
        {"Bihar", "Purvi Champaran", "Sachin Paswan", "2", " ", "बिहार", "पूर्वी चंपारण", "सचिन पासवान", " "},
        {"Bihar", "Purvi Champaran", "Devendra Singh", "2", " ", "बिहार", "पूर्वी चंपारण", "देवेंद्र सिंह", " "},
        {"Bihar", "Purvi Champaran", "Ramchandra Sah", "3", " ", "बिहार", "पूर्वी चंपारण", "रामचंद्र साह", " "},
        {"Bihar", "Purvi Champaran", "Vinay Kumar Srivastava", "4", " ", "बिहार", "पूर्वी चंपारण", "विनय कुमार श्रीवास्तव", " "},
        {"Bihar", "Purvi Champaran", "Pradip Singh", "2", " ", "बिहार", "पूर्वी चंपारण", "प्रदीप सिंह", " "},
        {"Bihar", "Purvi Champaran", "Manoj Tiwari", "4", " ", "बिहार", "पूर्वी चंपारण", "मनोज तिवारी", " "},
        {"Bihar", "Purvi Champaran", "Dinesh Sahani", "4", " ", "बिहार", "पूर्वी चंपारण", "दिनेश सहानी", " "},
        {"Bihar", "Purvi Champaran", "Satyam Yadav", "2", " ", "बिहार", "पूर्वी चंपारण", "सत्यम यादव", " "},
        {"Bihar", "Purvi Champaran", "Aniket Ranjan", "2", " ", "बिहार", "पूर्वी चंपारण", "अनिकेत रंजन", " "},
        {"Bihar", "Purvi Champaran", "Parasnath Pandey", "2", " ", "बिहार", "पूर्वी चंपारण", "पारसनाथ पांडे", " "},
        {"Bihar", "Purvi Champaran", "Muneshwar Tiwary", "4", " ", "बिहार", "पूर्वी चंपारण", "मुनेश्वर तिवारी", " "},
        {"Bihar", "Purvi Champaran", "Aakash Kumar", "4", " ", "बिहार", "पूर्वी चंपारण", "आकाश कुमार", " "},
        {"Bihar", "Purvi Champaran", "Shobha Devi", "4", " ", "बिहार", "पूर्वी चंपारण", "शोभा देवी", " "},
        {"Bihar", "Purvi Champaran", "Prabhakar Jayaswal", "2", " ", "बिहार", "पूर्वी चंपारण", "प्रभाकर जयसवाल", " "},
        {"Bihar", "Samastipur", "Ramchandra Paswan", "2", " ", "बिहार", "समस्तीपुर", "रामचंद्र पासवान", " "},
        {"Bihar", "Samastipur", "Dr. Ashok Kumar", "1", " ", "बिहार", "समस्तीपुर", "डॉ। अशोक कुमार", " "},
        {"Bihar", "Samastipur", "Lalo Paswan", "4", " ", "बिहार", "समस्तीपुर", "लालो पासवान", " "},
        {"Bihar", "Samastipur", "Asha Devi", "2", " ", "बिहार", "समस्तीपुर", "आशा देवी", " "},
        {"Bihar", "Samastipur", "Vijay Kumar Ram", "4", " ", "बिहार", "समस्तीपुर", "विजय कुमार राम", " "},
        {"Bihar", "Samastipur", "Raj Kumar Ram", "2", " ", "बिहार", "समस्तीपुर", "राज कुमार राम", " "},
        {"Bihar", "Saran", "Ishteyaque Ahmad", "4", " ", "बिहार", "सरन", "इश्तियाक अहमद", " "},
        {"Bihar", "Saran", "Rajiv Pratap Rudy", "1", " ", "बिहार", "सरन", "राजीव प्रताप रूडी", " "},
        {"Bihar", "Saran", "Sheojee Ram", "2", " ", "बिहार", "सरन", "शोजी राम", " "},
        {"Bihar", "Saran", "Juned Khan", "4", " ", "बिहार", "सरन", "जुनैद खान", " "},
        {"Bihar", "Saran", "Dharamveer Kumar", "4", " ", "बिहार", "सरन", "धरमवीर कुमार", " "},
        {"Bihar", "Saran", "Raj Kumar Ray", "4", " ", "बिहार", "सरन", "राज कुमार रे", " "},
        {"Bihar", "Saran", "Raj Kishor Prasad", "4", " ", "बिहार", "सरन", "राज किशोर प्रसाद", " "},
        {"Bihar", "Saran", "Lalu Prasad Yadav", "4", " ", "बिहार", "सरन", "लालू प्रसाद यादव", " "},
        {"Bihar", "Saran", "Chandrika Roy", "2", " ", "बिहार", "सरन", "चंद्रिका राय", " "},
        {"Bihar", "Sasaram", "Rajanikant Choudhary", "3", " ", "बिहार", "सासाराम", "रजनीकांत चौधरी", " "},
        {"Bihar", "Sasaram", "Raghuni Ram Shastri", "3", " ", "बिहार", "सासाराम", "रघुनी राम शास्त्री", " "},
        {"Bihar", "Sasaram", "Ashok Baitha", "2", " ", "बिहार", "सासाराम", "अशोक बैठा", " "},
        {"Bihar", "Sasaram", "Ashok Kumar Paswan", "4", " ", "बिहार", "सासाराम", "अशोक कुमार पासवान", " "},
        {"Bihar", "Sasaram", "Nirmala Devi", "4", " ", "बिहार", "सासाराम", "निर्मला देवी", " "},
        {"Bihar", "Sasaram", "Satya Narayan Ram", "3", " ", "बिहार", "सासाराम", "सत्य नारायण राम", " "},
        {"Bihar", "Sasaram", "Dharmraj Paswan", "4", " ", "बिहार", "सासाराम", "धर्मराज पासवान", " "},
        {"Bihar", "Sasaram", "Ramekbal Ram", "4", " ", "बिहार", "सासाराम", "रामकबल राम", " "},
        {"Bihar", "Sasaram", "Satya Narayan Paswan", "4", " ", "बिहार", "सासाराम", "सत्य नारायण पासवान", " "},
        {"Bihar", "Sasaram", "Vidya Jyoti", "4", " ", "बिहार", "सासाराम", "विद्या ज्योति", " "},
        {"Bihar", "Sasaram", "Meira Kumar", "1", " ", "बिहार", "सासाराम", "मीरा कुमार", " "},
        {"Bihar", "Sheohar", "Prabhu Narayan", "2", " ", "बिहार", "शिवहर", "प्रभु नारायण", " "},
        {"Bihar", "Sheohar", "Nabi Hussain", "4", " ", "बिहार", "शिवहर", "नबी हुसैन", " "},
        {"Bihar", "Sheohar", "Mukesh Kumar Jha", "2", " ", "बिहार", "शिवहर", "मुकेश कुमार झा", " "},
        {"Bihar", "Sheohar", "Ram Dayal Prasad", "3", " ", "बिहार", "शिवहर", "राम दयाल प्रसाद", " "},
        {"Bihar", "Sheohar", "Kedar Nath Prasad", "2", " ", "बिहार", "शिवहर", "केदार नाथ प्रसाद", " "},
        {"Bihar", "Sheohar", "Anil Kumar Tiwari", "4", " ", "बिहार", "शिवहर", "अनिल कुमार तिवारी", " "},
        {"Bihar", "Sheohar", "Vijay Nandan Paswan", "4", " ", "बिहार", "शिवहर", "विजय नंदन पासवान", " "},
        {"Bihar", "Sheohar", "Jagdish Prasad", "4", " ", "बिहार", "शिवहर", "जगदीश प्रसाद", " "},
        {"Bihar", "Sheohar", "Shamim Alam", "4", " ", "बिहार", "शिवहर", "शमीम आलम", " "},
        {"Bihar", "Sheohar", "Shyam Kumar", "2", " ", "बिहार", "शिवहर", "श्याम कुमार", " "},
        {"Bihar", "Sheohar", "Syed Faisal Ali", "2", " ", "बिहार", "शिवहर", "सैयद फैसल अली", " "},
        {"Bihar", "Sheohar", "Raj Kumar Prasad", "4", " ", "बिहार", "शिवहर", "राज कुमार प्रसाद", " "},
        {"Bihar", "Sheohar", "Rama Devi", "1", " ", "बिहार", "शिवहर", "रमा देवी", " "},
        {"Bihar", "Sheohar", "Abul Kalam Khan", "4", " ", "बिहार", "शिवहर", "अबुल कलाम खान", " "},
        {"Bihar", "Sitamarhi", "Vinod Sah", "4", " ", "बिहार", "सीतामढ़ी", "विनोद साह", " "},
        {"Bihar", "Sitamarhi", "Dharmendra Kumar", "4", " ", "बिहार", "सीतामढ़ी", "धर्मेंद्र कुमार", " "},
        {"Bihar", "Sitamarhi", "Lalbabu Paswan", "4", " ", "बिहार", "सीतामढ़ी", "लालबाबू पासवान", " "},
        {"Bihar", "Sitamarhi", "Amit Chaudhary", "2", " ", "बिहार", "सीतामढ़ी", "अमित चौधरी", " "},
        {"Bihar", "Sitamarhi", "Thakur Chandan Kumar Singh", "2", " ", "बिहार", "सीतामढ़ी", "ठाकुर चंदन कुमार सिंह", " "},
        {"Bihar", "Sitamarhi", "Ramesh Kumar Mishra", "4", " ", "बिहार", "सीतामढ़ी", "रमेश कुमार मिश्रा", " "},
        {"Bihar", "Sitamarhi", "Mohan Sah", "2", " ", "बिहार", "सीतामढ़ी", "मोहन साह", " "},
        {"Bihar", "Sitamarhi", "Jasem Ahamad", "4", " ", "बिहार", "सीतामढ़ी", "जसम अहमद", " "},
        {"Bihar", "Sitamarhi", "Raghunath Kumar", "2", " ", "बिहार", "सीतामढ़ी", "रघुनाथ कुमार", " "},
        {"Bihar", "Sitamarhi", "Sunil Kumar", "2", " ", "बिहार", "सीतामढ़ी", "सुनील कुमार", " "},
        {"Bihar", "Sitamarhi", "Shashi Kumar Singh", "3", " ", "बिहार", "सीतामढ़ी", "शशि कुमार सिंह", " "},
        {"Bihar", "Sitamarhi", "Arjun Ray", "2", " ", "बिहार", "सीतामढ़ी", "अर्जुन रे", " "},
        {"Bihar", "Siwan", "Parmanand Gond", "4", " ", "बिहार", "सिवान", "परमानंद गोंड", " "},
        {"Bihar", "Siwan", "Amarjit Prasad", "4", " ", "बिहार", "सिवान", "अमरजीत प्रसाद", " "},
        {"Bihar", "Siwan", "Amarnath Yadav", "2", " ", "बिहार", "सिवान", "अमरनाथ यादव", " "},
        {"Bihar", "Siwan", "Kavita Singh", "2", " ", "बिहार", "सिवान", "कविता सिंह", " "},
        {"Bihar", "Siwan", "Narad Pandit", "4", " ", "बिहार", "सिवान", "नारद पंडित", " "},
        {"Bihar", "Siwan", "Hena Shahab", "2", " ", "बिहार", "सिवान", "हेना शहाब", " "},
        {"Bihar", "Siwan", "Sanjay Prajapati", "2", " ", "बिहार", "सिवान", "संजय प्रजापति", " "},
        {"Bihar", "Siwan", "Upendra Kumar Giri", "2", " ", "बिहार", "सिवान", "उपेंद्र कुमार गिरि", " "},
        {"Bihar", "Siwan", "Anil Kumar Verma", "4", " ", "बिहार", "सिवान", "अनिल कुमार वर्मा", " "},
        {"Bihar", "Siwan", "Madhuri Pandey", "4", " ", "बिहार", "सिवान", "माधुरी पांडे", " "},
        {"Bihar", "Siwan", "Jai Prakash Prasad", "4", " ", "बिहार", "सिवान", "जय प्रकाश प्रसाद", " "},
        {"Bihar", "Siwan", "Rohit Kumar Yadav", "4", " ", "बिहार", "सिवान", "रोहित कुमार यादव", " "},
        {"Bihar", "Siwan", "Balmiki Prasad", "2", " ", "बिहार", "सिवान", "बाल्मीकि प्रसाद", " "},
        {"Bihar", "Supaul", "Ranjeet Ranjan", "1", " ", "बिहार", "सुपौल", "रणजीत रंजन", " "},
        {"Bihar", "Supaul", "Md. Afroj Alam", "4", " ", "बिहार", "सुपौल", "मो। अफरोज आलम", " "},
        {"Bihar", "Supaul", "Dinesh Prasad Yadav", "2", " ", "बिहार", "सुपौल", "दिनेश प्रसाद यादव", " "},
        {"Bihar", "Supaul", "Satya Narayan Mehta", "2", " ", "बिहार", "सुपौल", "सत्य नारायण मेहता", " "},
        {"Bihar", "Supaul", "Sanjay Sardar", "4", " ", "बिहार", "सुपौल", "संजय सरदार", " "},
        {"Bihar", "Supaul", "Naveen Kumar Singh", "4", " ", "बिहार", "सुपौल", "नवीन कुमार सिंह", " "},
        {"Bihar", "Supaul", "Pramod Kumar Nirala", "2", " ", "बिहार", "सुपौल", "प्रमोद कुमार निराला", " "},
        {"Bihar", "Supaul", "Kiran Devi", "4", " ", "बिहार", "सुपौल", "किरण देवी", " "},
        {"Bihar", "Supaul", "Bhim Kumar Gupta", "4", " ", "बिहार", "सुपौल", "भीम कुमार गुप्ता", " "},
        {"Bihar", "Supaul", "Dileshwar Kamait", "2", " ", "बिहार", "सुपौल", "दिलेश्वर कामायत", " "},
        {"Bihar", "Supaul", "Anand Pathak", "2", " ", "बिहार", "सुपौल", "आनंद पाठक", " "},
        {"Bihar", "Supaul", "Krishandev Mandal", "2", " ", "बिहार", "सुपौल", "कृष्णदेव मंडल", " "},
        {"Bihar", "Supaul", "Sanjeet Kumar Chaudhary", "4", " ", "बिहार", "सुपौल", "संजीत कुमार चौधरी", " "},
        {"Bihar", "Supaul", "Mohammad Abul Kalam Azad", "4", " ", "बिहार", "सुपौल", "मोहम्मद अबुल कलाम आज़ाद", " "},
        {"Bihar", "Ujiarpur", "Pranav Kumar", "4", " ", "बिहार", "उजियारपुर", "प्रणव कुमार", " "},
        {"Bihar", "Ujiarpur", "Amrendra Kumar Yadav", "2", " ", "बिहार", "उजियारपुर", "अमरेन्द्र कुमार यादव", " "},
        {"Bihar", "Ujiarpur", "Nityanand Rai", "1", " ", "बिहार", "उजियारपुर", "नित्यानंद राय", " "},
        {"Bihar", "Ujiarpur", "Lalan Kumar Roy", "4", " ", "बिहार", "उजियारपुर", "ललन कुमार रॉय", " "},
        {"Bihar", "Ujiarpur", "Ramashray Thakur", "4", " ", "बिहार", "उजियारपुर", "रामाश्रय ठाकुर", " "},
        {"Bihar", "Ujiarpur", "Upendra Kushwaha", "2", " ", "बिहार", "उजियारपुर", "उपेंद्र कुशवाहा", " "},
        {"Bihar", "Ujiarpur", "Ajay Kumar", "2", " ", "बिहार", "उजियारपुर", "अजय कुमार", " "},
        {"Bihar", "Ujiarpur", "Allamaa Shiblee Nomani Halami", "4", " ", "बिहार", "उजियारपुर", "अल्लामा शिब्ली नोमानी हलामी", " "},
        {"Bihar", "Ujiarpur", "Raj Kumar Chauhan", "4", " ", "बिहार", "उजियारपुर", "राज कुमार चौहान", " "},
        {"Bihar", "Ujiarpur", "Md. Anwar", "2", " ", "बिहार", "उजियारपुर", "अनवर अनवर", " "},
        {"Bihar", "Ujiarpur", "Mamta Kumari", "2", " ", "बिहार", "उजियारपुर", "ममता कुमारी", " "},
        {"Bihar", "Vaishali", "Beena Devi W/O Ajit Kumar Ray", "4", " ", "बिहार", "वैशाली", "बीना देवी डब्ल्यू / ओ अजीत कुमार रे", " "},
        {"Bihar", "Vaishali", "Abha Rai", "4", " ", "बिहार", "वैशाली", "आभा राय", " "},
        {"Bihar", "Vaishali", "Satish Kumar Mishra", "4", " ", "बिहार", "वैशाली", "सतीश कुमार मिश्रा", " "},
        {"Bihar", "Vaishali", "Pankaj Kumar", "2", " ", "बिहार", "वैशाली", "पंकज कुमार", " "},
        {"Bihar", "Vaishali", "Raghuvansh Prasad Singh", "2", " ", "बिहार", "वैशाली", "रघुवंश प्रसाद सिंह", " "},
        {"Bihar", "Vaishali", "Veena Devi", "2", " ", "बिहार", "वैशाली", "वीणा देवी", " "},
        {"Bihar", "Vaishali", "Shankar Mahto", "2", " ", "बिहार", "वैशाली", "शंकर महतो", " "},
        {"Bihar", "Vaishali", "Reshami Devi", "4", " ", "बिहार", "वैशाली", "रेशम देवी", " "},
        {"Bihar", "Vaishali", "Vidya Bhushan", "4", " ", "बिहार", "वैशाली", "विद्या भूषण", " "},
        {"Bihar", "Vaishali", "Amit Vikram", "4", " ", "बिहार", "वैशाली", "अमित विक्रम", " "},
        {"Bihar", "Vaishali", "Dhanvanti Devi", "4", " ", "बिहार", "वैशाली", "धनवंती देवी", " "},
        {"Bihar", "Vaishali", "Naresh Ram", "4", " ", "बिहार", "वैशाली", "नरेश राम", " "},
        {"Bihar", "Vaishali", "Suresh Kumar Gupta", "4", " ", "बिहार", "वैशाली", "सुरेश कुमार गुप्ता", " "},
        {"Bihar", "Vaishali", "Rinku Devi1", "4", " ", "बिहार", "वैशाली", "रिंकू देवी १", " "},
        {"Bihar", "Valmiki Nagar", "Baidyanath Prasad Mahto", "2", " ", "बिहार", "वाल्मीकि नगर", "बैद्यनाथ प्रसाद महतो", " "},
        {"Bihar", "Valmiki Nagar", "Bhola Ray", "4", " ", "बिहार", "वाल्मीकि नगर", "भोला रे", " "},
        {"Bihar", "Valmiki Nagar", "Sushma Devi", "2", " ", "बिहार", "वाल्मीकि नगर", "सुषमा देवी", " "},
        {"Bihar", "Valmiki Nagar", "Ramesh Prasad", "4", " ", "बिहार", "वाल्मीकि नगर", "रमेश प्रसाद", " "},
        {"Bihar", "Valmiki Nagar", "Durgesh Singh Chauhan", "4", " ", "बिहार", "वाल्मीकि नगर", "दुर्गेश सिंह चौहान", " "},
        {"Bihar", "Valmiki Nagar", "Shashwat Kedar", "1", " ", "बिहार", "वाल्मीकि नगर", "शशवत केदार", " "},
        {"Bihar", "Valmiki Nagar", "Shiv Kumar Chaudhary", "4", " ", "बिहार", "वाल्मीकि नगर", "शिव कुमार चौधरी", " "},
        {"Bihar", "Valmiki Nagar", "Rajesh Kushwaha", "4", " ", "बिहार", "वाल्मीकि नगर", "राजेश कुशवाहा", " "},
        {"Bihar", "Valmiki Nagar", "Suresh Sah", "4", " ", "बिहार", "वाल्मीकि नगर", "सुरेश साह", " "},
        {"Bihar", "Valmiki Nagar", "Deepak Yadav", "2", " ", "बिहार", "वाल्मीकि नगर", "दीपक यादव", " "},
        {"Bihar", "Valmiki Nagar", "Manoj Kumar", "4", " ", "बिहार", "वाल्मीकि नगर", "मनोज कुमार", " "},
        {"Bihar", "Valmiki Nagar", "Rakesh Kewat", "4", " ", "बिहार", "वाल्मीकि नगर", "राकेश केवट", " "},
};

}