/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Chhattisgarh {
public static final String[][] green_bucket = {
        {"Chhattisgarh", "Bastar", "Ramu Ram Mourya", "Communist Party of India", "10.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7196", "छत्तीसगढ़", "बस्तर", "रामू राम मौर्य", "भारतीय कम्युनिस्ट पार्टी"},
        {"Chhattisgarh", "Bastar", "Paneesh Prasad Nag", "Ambedkarite Party of India", "34.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7197", "छत्तीसगढ़", "बस्तर", "पनेश प्रसाद नाग", "भारत की अम्बेडकरवादी पार्टी"},
        {"Chhattisgarh", "Bilaspur", "Nand Kishore Raj", "Gondvana Gantantra Party", "38.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9472", "छत्तीसगढ़", "बिलासपुर", "नंद किशोर राज", "गोंडवाना गणतंत्र पार्टी"},
        {"Chhattisgarh", "Bilaspur", "Urmila Tiwari", "Independent", "2.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9471", "छत्तीसगढ़", "बिलासपुर", "उर्मिला तिवारी", "निर्दलीय"},
        {"Chhattisgarh", "Bilaspur", "Salik Ram Jogivansh", "Independent", "10.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7464", "छत्तीसगढ़", "बिलासपुर", "सालिक राम जोगीवंश", "निर्दलीय"},
        {"Chhattisgarh", "Bilaspur", "Ramfal Mandrey", "Ambedkarite Party of India", "24Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7463", "छत्तीसगढ़", "बिलासपुर", "रामफल मंड्रे", "भारत की अम्बेडकरवादी पार्टी"},
        {"Chhattisgarh", "Bilaspur", "Indrasen Mogre", "Independent", "1.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9464", "छत्तीसगढ़", "बिलासपुर", "इंद्रसेन मोगरे", "निर्दलीय"},
        {"Chhattisgarh", "Bilaspur", "Sandeep Singh Porte", "Adhikar Vikas Party", "27.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8222", "छत्तीसगढ़", "बिलासपुर", "संदीप सिंह पोर्ते", "अधिक्कार विकास पार्टी"},
        {"Chhattisgarh", "Bilaspur", "Harish Kumar Mandwa", "Independent", "2.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9473", "छत्तीसगढ़", "बिलासपुर", "हरीश कुमार मंडवा", "निर्दलीय"},
        {"Chhattisgarh", "Bilaspur", "Yaman Banjare", "Bhartiya Kisan Party", "2.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9463", "छत्तीसगढ़", "बिलासपुर", "यमन बंजारे", "भारतीय किसान पार्टी"},
        {"Chhattisgarh", "Bilaspur", "Siddhram Lahare", "Rashtriya Jansabha Party", "12.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9468", "छत्तीसगढ़", "बिलासपुर", "सिद्धराम लहरे", "राष्ट्रीय जनसंवाद पार्टी"},
        {"Chhattisgarh", "Bilaspur", "Avishek Ekka", "Independent", "4.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8221", "छत्तीसगढ़", "बिलासपुर", "अविषेक एक्का", "निर्दलीय"},
        {"Chhattisgarh", "Bilaspur", "Baldau Prasad Sahu", "Independent", "12Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9465", "छत्तीसगढ़", "बिलासपुर", "बलदाऊ प्रसाद साहू", "निर्दलीय"},
        {"Chhattisgarh", "Durg", "Praveen Tiwari", "Independent", "6.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11143", "छत्तीसगढ़", "दुर्ग", "प्रवीण तिवारी", "निर्दलीय"},
        {"Chhattisgarh", "Durg", "Rajesh Kumar Dubey", "Bhartiya Shakti Chetna Party", "93.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8217", "छत्तीसगढ़", "दुर्ग", "राजेश कुमार दुबे", "भारतीय शक्ति चेतना पार्टी"},
        {"Chhattisgarh", "Durg", "Farid Mohammad Quraishi", "Gondvana Gantantra Party", "2.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11141", "छत्तीसगढ़", "दुर्ग", "फरीद मोहम्मद कुरैशी", "गोंडवाना गणतंत्र पार्टी"},
        {"Chhattisgarh", "Durg", "Geetanjali Singh", "Bahujan Samaj Party", "54.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7472", "छत्तीसगढ़", "दुर्ग", "गीतांजलि सिंह", "बहुजन समाज पार्टी"},
        {"Chhattisgarh", "Durg", "Aatma Ram Sahu", "Socialist Unity Centre of India (Communist)", "48000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7470", "छत्तीसगढ़", "दुर्ग", "आतम राम साहू", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Chhattisgarh", "Durg", "Tressa David", "India Praja Bandhu Party", "4.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8213", "छत्तीसगढ़", "दुर्ग", "त्रेसा डेविड", "भारत प्रजा बंधु पार्टी"},
        {"Chhattisgarh", "Durg", "Sunil Kumar Markandey", "Independent", "3.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11146", "छत्तीसगढ़", "दुर्ग", "सुनील कुमार मार्कंडेय", "निर्दलीय"},
        {"Chhattisgarh", "Durg", "Sevakram Banjare", "Rashtriya Jansabha Party", "2.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11142", "छत्तीसगढ़", "दुर्ग", "सेवकराम बंजारे", "राष्ट्रीय जनसंवाद पार्टी"},
        {"Chhattisgarh", "Janjgir Champa", "Dauram Satnami", "Bahujan Samaj Party", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7475", "छत्तीसगढ़", "जांजगीर", "डौरम सतनामी", "बहुजन समाज पार्टी"},
        {"Chhattisgarh", "Janjgir Champa", "Seema Ajay", "Ambedkarite Party of India", "10Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7800", "छत्तीसगढ़", "जांजगीर", "सीमा अजय", "भारत की अम्बेडकरवादी पार्टी"},
        {"Chhattisgarh", "Janjgir Champa", "Shanti Kumar Ratre", "Gondvana Gantantra Party", "44.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7799", "छत्तीसगढ़", "जांजगीर", "शांति कुमार रात्रे", "गोंडवाना गणतंत्र पार्टी"},
        {"Chhattisgarh", "Janjgir Champa", "Naresh Kumar Dahriya", "Rashtriya Gondvana Party", "6.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9475", "छत्तीसगढ़", "जांजगीर", "नरेश कुमार डहरिया", "राष्ट्रीय गोंडवाना पार्टी"},
        {"Chhattisgarh", "Janjgir Champa", "Aashish Ratre", "Peoples Party of India (Democratic)", "72.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7478", "छत्तीसगढ़", "जांजगीर", "आशीष रात्रे", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
        {"Chhattisgarh", "Janjgir Champa", "Asharam Ratnakar", "Independent", "10.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11350", "छत्तीसगढ़", "जांजगीर", "आशाराम रत्नाकर", "निर्दलीय"},
        {"Chhattisgarh", "Kanker", "Durgaprasad Thakur", "Ambedkarite Party of India", "21.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7169", "छत्तीसगढ़", "कांकेर", "दुर्गाप्रसाद ठाकुर", "भारत की अम्बेडकरवादी पार्टी"},
        {"Chhattisgarh", "Kanker", "Umashankar Bhandari", "Shiv Sena", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7175", "छत्तीसगढ़", "कांकेर", "उमाशंकर भंडारी", "शिवसेना"},
        {"Chhattisgarh", "Kanker", "Mathan Singh Markam", "Bhartiya Shakti Chetna Party", "9.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7172", "छत्तीसगढ़", "कांकेर", "मथन सिंह मरकाम", "भारतीय शक्ति चेतना पार्टी"},
        {"Chhattisgarh", "Korba", "Deepak Kumar Sahu", "Independent", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8208", "छत्तीसगढ़", "कोरबा", "दीपक कुमार साहू", "निर्दलीय"},
        {"Chhattisgarh", "Korba", "Chandra Bhushan Kanwar", "Ambedkarite Party of India", "35600", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7480", "छत्तीसगढ़", "कोरबा", "चंद्र भूषण कंवर", "भारत की अम्बेडकरवादी पार्टी"},
        {"Chhattisgarh", "Korba", "Lilambar Singh", "Bhartiya Tribal Party", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8206", "छत्तीसगढ़", "कोरबा", "लीलम्बर सिंह", "भारतीय ट्राइबल पार्टी"},
        {"Chhattisgarh", "Korba", "Tuleshwar Markam", "Gondvana Gantantra Party", "27.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8207", "छत्तीसगढ़", "कोरबा", "तुलेश्वर मरकाम", "गोंडवाना गणतंत्र पार्टी"},
        {"Chhattisgarh", "Mahasamund", "Champalal Patel", "Independent", "20.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5418", "छत्तीसगढ़", "महासमुंद", "चंपालाल पटेल", "निर्दलीय"},
        {"Chhattisgarh", "Raigarh", "Kripashankar Bhagat", "Bhartiya Tribal Party", "74Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8205", "छत्तीसगढ़", "रायगढ़", "कृपाशंकर भगत", "भारतीय ट्राइबल पार्टी"},
        {"Chhattisgarh", "Raigarh", "Innocent Kujur", "Bahujan Samaj Party", "77Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7498", "छत्तीसगढ़", "रायगढ़", "मासूम कुजूर", "बहुजन समाज पार्टी"},
        {"Chhattisgarh", "Raigarh", "Naval Kishor Rathiya", "Independent", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9485", "छत्तीसगढ़", "रायगढ़", "नवल किशोर राठिया", "निर्दलीय"},
        {"Chhattisgarh", "Raipur", "Shailendra Kumar Banjare", "Shakti Sena (Bharat Desh)", "61Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7817", "छत्तीसगढ़", "रायपुर", "शैलेंद्र कुमार बंजारे", "शक्ति सेना (भारत देश)"},
        {"Chhattisgarh", "Raipur", "Santosh Sahu", "Independent", "10.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9493", "छत्तीसगढ़", "रायपुर", "संतोष साहू", "निर्दलीय"},
        {"Chhattisgarh", "Raipur", "Ajay Chakole", "Gondvana Gantantra Party", "3.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8202", "छत्तीसगढ़", "रायपुर", "अजय चकोले", "गोंडवाना गणतंत्र पार्टी"},
        {"Chhattisgarh", "Raipur", "Devendra Kumar Patil", "Socialist Unity Centre of India (Communist)", "24000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7500", "छत्तीसगढ़", "रायपुर", "देवेंद्र कुमार पाटिल", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Chhattisgarh", "Raipur", "Dr. Yogita Bajpai", "Sarvodaya Bharat Party", "40.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8197", "छत्तीसगढ़", "रायपुर", "डॉ। योगिता बाजपेयी", "सर्वोदय भारत पार्टी"},
        {"Chhattisgarh", "Raipur", "Pritesh Pandey", "Independent", "3.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7820", "छत्तीसगढ़", "रायपुर", "प्रीतेश पांडे", "निर्दलीय"},
        {"Chhattisgarh", "Rajnandgaon", "Ravita Lakra (Dhruv)", "Bahujan Samaj Party", "38.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7153", "छत्तीसगढ़", "राजनंदगांव", "रविता लकड़ा (ध्रुव)", "बहुजन समाज पार्टी"},
        {"Chhattisgarh", "Rajnandgaon", "Mahendra Kumar Sahu", "Forward Democratic Labour Party", "17.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5538", "छत्तीसगढ़", "राजनंदगांव", "महेंद्र कुमार साहू", "फॉरवर्ड डेमोक्रेटिक लेबर पार्टी"},
        {"Chhattisgarh", "Rajnandgaon", "Baidya Shekhu Ram Verma", "Ambedkarite Party of India", "64.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5112", "छत्तीसगढ़", "राजनंदगांव", "बैद्य शेखू राम वर्मा", "भारत की अम्बेडकरवादी पार्टी"},
        {"Chhattisgarh", "Surguja", "Asha Devi Poya", "Gondvana Gantantra Party", "27.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7824", "छत्तीसगढ़", "सरगुजा", "आशा देवी पोया", "गोंडवाना गणतंत्र पार्टी"},
        {"Chhattisgarh", "Surguja", "Pawan Kumar Nag", "Bahujan Mukti Party", "80000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9499", "छत्तीसगढ़", "सरगुजा", "पवन कुमार नाग", "बहुजन मुक्ति पार्टी"},
        {"Chhattisgarh", "Surguja", "Maya Prajapati", "Bahujan Samaj Party", "78.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7509", "छत्तीसगढ़", "सरगुजा", "माया प्रजापति", "बहुजन समाज पार्टी"},
        {"Chhattisgarh", "Surguja", "Chandradeep Singh Korcho", "Rashtriya Jansabha Party", "1.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9498", "छत्तीसगढ़", "सरगुजा", "चंद्रदीप सिंह कोरचो", "राष्ट्रीय जनसंवाद पार्टी"},
};

public static final String[][] red_bucket = {
        {"Chhattisgarh", "Bastar", "Suresh Kawasi", "4", " ", "छत्तीसगढ़", "बस्तर", "सुरेश कावासी", " "},
        {"Chhattisgarh", "Bastar", "Deepak Kumar Baij", "1", " ", "छत्तीसगढ़", "बस्तर", "दीपक कुमार बैज", " "},
        {"Chhattisgarh", "Bastar", "Aaytu Ram Mandavi", "4", " ", "छत्तीसगढ़", "बस्तर", "आयतू राम मंडावी", " "},
        {"Chhattisgarh", "Bastar", "Baidu Ram Kashyap", "1", " ", "छत्तीसगढ़", "बस्तर", "Baidu राम कश्यप", " "},
        {"Chhattisgarh", "Bilaspur", "Arun Sao", "1", " ", "छत्तीसगढ़", "बिलासपुर", "अरुण साओ", " "},
        {"Chhattisgarh", "Bilaspur", "Raju Khatik", "4", " ", "छत्तीसगढ़", "बिलासपुर", "राजू खटीक", " "},
        {"Chhattisgarh", "Bilaspur", "Atal Shrivastav", "1", " ", "छत्तीसगढ़", "बिलासपुर", "अटल श्रीवास्तव", " "},
        {"Chhattisgarh", "Bilaspur", "Pooran Lal Chhabariya", "2", " ", "छत्तीसगढ़", "बिलासपुर", "पूरन लाल छाबड़िया", " "},
        {"Chhattisgarh", "Bilaspur", "Arun Kumar Sahu", "4", " ", "छत्तीसगढ़", "बिलासपुर", "अरुण कुमार साहू", " "},
        {"Chhattisgarh", "Bilaspur", "Uttam Das Gurugosai", "4", " ", "छत्तीसगढ़", "बिलासपुर", "उत्तम दास गुरुगोसाई", " "},
        {"Chhattisgarh", "Bilaspur", "Vidya Sahu", "4", " ", "छत्तीसगढ़", "बिलासपुर", "विद्या साहू", " "},
        {"Chhattisgarh", "Bilaspur", "Sandeep Tiwari", "2", " ", "छत्तीसगढ़", "बिलासपुर", "संदीप तिवारी", " "},
        {"Chhattisgarh", "Bilaspur", "Santosh Kumar Kaushal", "4", " ", "छत्तीसगढ़", "बिलासपुर", "संतोष कुमार कौशल", " "},
        {"Chhattisgarh", "Bilaspur", "Dujram Sahu", "4", " ", "छत्तीसगढ़", "बिलासपुर", "दुजराम साहू", " "},
        {"Chhattisgarh", "Bilaspur", "Ramkumar Ghatlahare", "4", " ", "छत्तीसगढ़", "बिलासपुर", "रामकुमार घाटलारे", " "},
        {"Chhattisgarh", "Bilaspur", "Hairschandra Teli (Sahu)", "4", " ", "छत्तीसगढ़", "बिलासपुर", "मेलेशचंद्र तेली (साहू)", " "},
        {"Chhattisgarh", "Bilaspur", "Shambhu Sharma", "3", " ", "छत्तीसगढ़", "बिलासपुर", "शंभू शर्मा", " "},
        {"Chhattisgarh", "Bilaspur", "Hori Lal Anant", "4", " ", "छत्तीसगढ़", "बिलासपुर", "होरी लाल अनंत", " "},
        {"Chhattisgarh", "Durg", "Anoop Kumar Pandey", "4", " ", "छत्तीसगढ़", "दुर्ग", "अनूप कुमार पांडे", " "},
        {"Chhattisgarh", "Durg", "Vijay Baghel", "1", " ", "छत्तीसगढ़", "दुर्ग", "विजय बघेल", " "},
        {"Chhattisgarh", "Durg", "Anurag Singh", "4", " ", "छत्तीसगढ़", "दुर्ग", "अनुराग सिंह", " "},
        {"Chhattisgarh", "Durg", "Pokhraj Meshram", "4", " ", "छत्तीसगढ़", "दुर्ग", "पोखराज मेश्राम", " "},
        {"Chhattisgarh", "Durg", "Pitambar Lal Nishad", "4", " ", "छत्तीसगढ़", "दुर्ग", "पीताम्बर लाल निषाद", " "},
        {"Chhattisgarh", "Durg", "Guru Dada Lokesh", "3", " ", "छत्तीसगढ़", "दुर्ग", "गुरु दादा लोकेश", " "},
        {"Chhattisgarh", "Durg", "Manoj Gaykwad Chhattisgarhiya", "4", " ", "छत्तीसगढ़", "दुर्ग", "मनोज गायकवाड़ छत्तीसगढ़ी", " "},
        {"Chhattisgarh", "Durg", "Pratima Chandrakar", "1", " ", "छत्तीसगढ़", "दुर्ग", "प्रतिमा चंद्राकर", " "},
        {"Chhattisgarh", "Durg", "Malik Ram Thakur", "4", " ", "छत्तीसगढ़", "दुर्ग", "मलिक राम ठाकुर", " "},
        {"Chhattisgarh", "Durg", "Kamlesh Kumar Nagarchi", "4", " ", "छत्तीसगढ़", "दुर्ग", "कमलेश कुमार नागरची", " "},
        {"Chhattisgarh", "Durg", "Raj Kumar Gupta", "3", " ", "छत्तीसगढ़", "दुर्ग", "राज कुमार गुप्ता", " "},
        {"Chhattisgarh", "Durg", "Arun Kumar Joshi", "4", " ", "छत्तीसगढ़", "दुर्ग", "अरुण कुमार जोशी", " "},
        {"Chhattisgarh", "Durg", "Hidar Bhati", "4", " ", "छत्तीसगढ़", "दुर्ग", "हिदर भाटी", " "},
        {"Chhattisgarh", "Janjgir Champa", "Ravindra Shekhar Bharadwaj", "1", " ", "छत्तीसगढ़", "जांजगीर", "रवींद्र शेखर भारद्वाज", " "},
        {"Chhattisgarh", "Janjgir Champa", "Vranda Chouhan", "4", " ", "छत्तीसगढ़", "जांजगीर", "वृंदा चौहान", " "},
        {"Chhattisgarh", "Janjgir Champa", "Bhojram Banjare", "2", " ", "छत्तीसगढ़", "जांजगीर", "भोजराम बंजारे", " "},
        {"Chhattisgarh", "Janjgir Champa", "Nitesh Kumar Ratre", "4", " ", "छत्तीसगढ़", "जांजगीर", "नितेश कुमार रत्रे", " "},
        {"Chhattisgarh", "Janjgir Champa", "Uday Das Ratre", "4", " ", "छत्तीसगढ़", "जांजगीर", "उदय दास रत्रे", " "},
        {"Chhattisgarh", "Janjgir Champa", "Sitabai Chouhan", "4", " ", "छत्तीसगढ़", "जांजगीर", "सीताबाई चौहान", " "},
        {"Chhattisgarh", "Janjgir Champa", "Naresh Bai Jangde", "4", " ", "छत्तीसगढ़", "जांजगीर", "नरेश बाई जांगड़े", " "},
        {"Chhattisgarh", "Janjgir Champa", "Lakhan Ram Chouhan", "3", " ", "छत्तीसगढ़", "जांजगीर", "लखन राम चौहान", " "},
        {"Chhattisgarh", "Janjgir Champa", "Guharam Ajgalle", "1", " ", "छत्तीसगढ़", "जांजगीर", "गुहाराम अजगले", " "},
        {"Chhattisgarh", "Kanker", "Sube Singh Dhurva", "4", " ", "छत्तीसगढ़", "कांकेर", "सूबे सिंह धुर्वा", " "},
        {"Chhattisgarh", "Kanker", "Mohan Mandavi", "1", " ", "छत्तीसगढ़", "कांकेर", "मोहन मंडावी", " "},
        {"Chhattisgarh", "Kanker", "Narend Nag", "4", " ", "छत्तीसगढ़", "कांकेर", "नरेंद्र नाग", " "},
        {"Chhattisgarh", "Kanker", "Biresh Thakur", "1", " ", "छत्तीसगढ़", "कांकेर", "बिरेश ठाकुर", " "},
        {"Chhattisgarh", "Kanker", "Harisingh Sidar", "3", " ", "छत्तीसगढ़", "कांकेर", "हरिसिंह सिदार", " "},
        {"Chhattisgarh", "Kanker", "Ghanshyam Jurri", "4", " ", "छत्तीसगढ़", "कांकेर", "घनश्याम जुरी", " "},
        {"Chhattisgarh", "Korba", "Jyotsna Mahant", "1", " ", "छत्तीसगढ़", "कोरबा", "ज्योत्सना महंत", " "},
        {"Chhattisgarh", "Korba", "Raj Kumar Yadav", "3", " ", "छत्तीसगढ़", "कोरबा", "राज कुमार यादव", " "},
        {"Chhattisgarh", "Korba", "Pramod Kumar Sharma", "4", " ", "छत्तीसगढ़", "कोरबा", "प्रमोद कुमार शर्मा", " "},
        {"Chhattisgarh", "Korba", "Rajesh Pandey", "2", " ", "छत्तीसगढ़", "कोरबा", "राजेश पांडे", " "},
        {"Chhattisgarh", "Korba", "Jyoti Nand Dubey", "1", " ", "छत्तीसगढ़", "कोरबा", "ज्योति नंद दुबे", " "},
        {"Chhattisgarh", "Korba", "Parmit Singh", "2", " ", "छत्तीसगढ़", "कोरबा", "परमीत सिंह", " "},
        {"Chhattisgarh", "Korba", "Suman Lal Khande", "4", " ", "छत्तीसगढ़", "कोरबा", "सुमन लाल खांडे", " "},
        {"Chhattisgarh", "Korba", "Ramdayal Uraon", "4", " ", "छत्तीसगढ़", "कोरबा", "रामदयाल उरांव", " "},
        {"Chhattisgarh", "Korba", "Lakhan Lal Dewangan", "4", " ", "छत्तीसगढ़", "कोरबा", "लखन लाल देवांगन", " "},
        {"Chhattisgarh", "Mahasamund", "Rohit Kumar Kosre", "4", " ", "छत्तीसगढ़", "महासमुंद", "रोहित कुमार कोसरे", " "},
        {"Chhattisgarh", "Mahasamund", "Santosh Banjare", "4", " ", "छत्तीसगढ़", "महासमुंद", "संतोष बंजारे", " "},
        {"Chhattisgarh", "Mahasamund", "Ashok Soni", "4", " ", "छत्तीसगढ़", "महासमुंद", "अशोक सोनी", " "},
        {"Chhattisgarh", "Mahasamund", "Khilawan Singh Dhruw", "4", " ", "छत्तीसगढ़", "महासमुंद", "खिलवान सिंह ध्रुव", " "},
        {"Chhattisgarh", "Mahasamund", "Devendar Singh Thakur (Rajput)", "2", " ", "छत्तीसगढ़", "महासमुंद", "देवेन्द्र सिंह ठाकुर (राजपूत)", " "},
        {"Chhattisgarh", "Mahasamund", "Dhanendra Sahu", "1", " ", "छत्तीसगढ़", "महासमुंद", "धनेंद्र साहू", " "},
        {"Chhattisgarh", "Mahasamund", "Dhansing Kosariya", "2", " ", "छत्तीसगढ़", "महासमुंद", "धनसार कोसरिया", " "},
        {"Chhattisgarh", "Mahasamund", "Jagmohan Bhagwat Kosariya", "3", " ", "छत्तीसगढ़", "महासमुंद", "जगमोहन भागवत कोश्यारी", " "},
        {"Chhattisgarh", "Mahasamund", "Tarun Kumar Dadsena", "2", " ", "छत्तीसगढ़", "महासमुंद", "तरुण कुमार डडसेना", " "},
        {"Chhattisgarh", "Mahasamund", "Bhojlal Netam", "3", " ", "छत्तीसगढ़", "महासमुंद", "भोजलाल नेताम", " "},
        {"Chhattisgarh", "Mahasamund", "Chunni Lal Sahu", "1", " ", "छत्तीसगढ़", "महासमुंद", "चुन्नी लाल साहू", " "},
        {"Chhattisgarh", "Mahasamund", "Dr. Virendra Choudhary", "4", " ", "छत्तीसगढ़", "महासमुंद", "डॉ। वीरेंद्र चौधरी", " "},
        {"Chhattisgarh", "Raigarh", "Gomati", "1", " ", "छत्तीसगढ़", "रायगढ़", "गोमती", " "},
        {"Chhattisgarh", "Raigarh", "Amrit Tirkey", "4", " ", "छत्तीसगढ़", "रायगढ़", "अमृत तिर्की", " "},
        {"Chhattisgarh", "Raigarh", "Tejram Sidar", "4", " ", "छत्तीसगढ़", "रायगढ़", "तेजराम सिदार", " "},
        {"Chhattisgarh", "Raigarh", "Praksh Kumar Uraon", "4", " ", "छत्तीसगढ़", "रायगढ़", "प्रक्ष कुमार उरांव", " "},
        {"Chhattisgarh", "Raigarh", "Jai Singh Sidar", "4", " ", "छत्तीसगढ़", "रायगढ़", "जय सिंह सिदार", " "},
        {"Chhattisgarh", "Raigarh", "Vijay Lakara", "4", " ", "छत्तीसगढ़", "रायगढ़", "विजय लकड़ा", " "},
        {"Chhattisgarh", "Raigarh", "Ravishankar Sidar", "4", " ", "छत्तीसगढ़", "रायगढ़", "रविशंकर सिदार", " "},
        {"Chhattisgarh", "Raigarh", "Jyoti Bhagat", "4", " ", "छत्तीसगढ़", "रायगढ़", "ज्योति भगत", " "},
        {"Chhattisgarh", "Raigarh", "Tarika Tarangini Uraon", "2", " ", "छत्तीसगढ़", "रायगढ़", "तारिका तरंगिणी उरांव", " "},
        {"Chhattisgarh", "Raigarh", "Laljeet Singh Rathiya", "1", " ", "छत्तीसगढ़", "रायगढ़", "लालजीत सिंह राठिया", " "},
        {"Chhattisgarh", "Raigarh", "Vir Kumar Tigga", "4", " ", "छत्तीसगढ़", "रायगढ़", "वीर कुमार तिग्गा", " "},
        {"Chhattisgarh", "Raipur", "Manish Shrivastav", "4", " ", "छत्तीसगढ़", "रायपुर", "मनीष श्रीवास्तव", " "},
        {"Chhattisgarh", "Raipur", "Chhabi Lal Kanwar", "4", " ", "छत्तीसगढ़", "रायपुर", "छबि लाल कंवर", " "},
        {"Chhattisgarh", "Raipur", "Devki Dubey", "4", " ", "छत्तीसगढ़", "रायपुर", "देवकी दुबे", " "},
        {"Chhattisgarh", "Raipur", "Pramod Dubey", "1", " ", "छत्तीसगढ़", "रायपुर", "प्रमोद दुबे", " "},
        {"Chhattisgarh", "Raipur", "Ramdyal Dahariya", "4", " ", "छत्तीसगढ़", "रायपुर", "रामदयाल डहरिया", " "},
        {"Chhattisgarh", "Raipur", "Navin Gupta", "4", " ", "छत्तीसगढ़", "रायपुर", "नवीन गुप्ता", " "},
        {"Chhattisgarh", "Raipur", "Sanju Kumar Yadav", "4", " ", "छत्तीसगढ़", "रायपुर", "संजू कुमार यादव", " "},
        {"Chhattisgarh", "Raipur", "Vijay Kumar Kurre", "4", " ", "छत्तीसगढ़", "रायपुर", "विजय कुमार कुर्रे", " "},
        {"Chhattisgarh", "Raipur", "Pravin Jain", "4", " ", "छत्तीसगढ़", "रायपुर", "प्रवीण जैन", " "},
        {"Chhattisgarh", "Raipur", "Ramkrishna Verma", "4", " ", "छत्तीसगढ़", "रायपुर", "रामकृष्ण वर्मा", " "},
        {"Chhattisgarh", "Raipur", "Santosh Kumar Yadu", "4", " ", "छत्तीसगढ़", "रायपुर", "संतोष कुमार यदु", " "},
        {"Chhattisgarh", "Raipur", "Rupesh Sahu", "4", " ", "छत्तीसगढ़", "रायपुर", "रूपेश साहू", " "},
        {"Chhattisgarh", "Raipur", "Tameshwar Sahu", "4", " ", "छत्तीसगढ़", "रायपुर", "तमेश्वर साहू", " "},
        {"Chhattisgarh", "Raipur", "Ikram Saifi", "4", " ", "छत्तीसगढ़", "रायपुर", "इकराम सैफी", " "},
        {"Chhattisgarh", "Raipur", "Shankar Lal Vardani", "4", " ", "छत्तीसगढ़", "रायपुर", "शंकर लाल वरदानी", " "},
        {"Chhattisgarh", "Raipur", "Khilesh Kumar Sahu", "4", " ", "छत्तीसगढ़", "रायपुर", "खिलेश कुमार साहू", " "},
        {"Chhattisgarh", "Raipur", "Tarjan Jangde", "4", " ", "छत्तीसगढ़", "रायपुर", "टारजन जांगड़े", " "},
        {"Chhattisgarh", "Raipur", "Sunil Kumar Soni", "1", " ", "छत्तीसगढ़", "रायपुर", "सुनील कुमार सोनी", " "},
        {"Chhattisgarh", "Raipur", "Banmali Chhura", "4", " ", "छत्तीसगढ़", "रायपुर", "बनमाली छुरा", " "},
        {"Chhattisgarh", "Rajnandgaon", "Kamini Sahu", "4", " ", "छत्तीसगढ़", "राजनंदगांव", "कामिनी साहू", " "},
        {"Chhattisgarh", "Rajnandgaon", "Sudesh Tikam", "2", " ", "छत्तीसगढ़", "राजनंदगांव", "सुदेश टीकम", " "},
        {"Chhattisgarh", "Rajnandgaon", "Bhola Ram Sahu", "1", " ", "छत्तीसगढ़", "राजनंदगांव", "भोला राम साहू", " "},
        {"Chhattisgarh", "Rajnandgaon", "Vishwanath Singh Porte", "4", " ", "छत्तीसगढ़", "राजनंदगांव", "विश्वनाथ सिंह पोर्ते", " "},
        {"Chhattisgarh", "Rajnandgaon", "Ramkhilawan Dahariya", "4", " ", "छत्तीसगढ़", "राजनंदगांव", "रामखिलावन डहरिया", " "},
        {"Chhattisgarh", "Rajnandgaon", "Kranti Gupta", "4", " ", "छत्तीसगढ़", "राजनंदगांव", "क्रांति गुप्ता", " "},
        {"Chhattisgarh", "Rajnandgaon", "Ajay Pali", "4", " ", "छत्तीसगढ़", "राजनंदगांव", "अजय पाली", " "},
        {"Chhattisgarh", "Rajnandgaon", "Pratima Santosh Washnik", "4", " ", "छत्तीसगढ़", "राजनंदगांव", "प्रतिमा संतोष वाशनिक", " "},
        {"Chhattisgarh", "Rajnandgaon", "Dr. Gojupal", "2", " ", "छत्तीसगढ़", "राजनंदगांव", "डॉ। गूजुपाल", " "},
        {"Chhattisgarh", "Rajnandgaon", "Sachchidanand Kaushik", "4", " ", "छत्तीसगढ़", "राजनंदगांव", "सच्चिदानंद कौशिक", " "},
        {"Chhattisgarh", "Rajnandgaon", "Santosh Pandey", "1", " ", "छत्तीसगढ़", "राजनंदगांव", "संतोष पांडे", " "},
        {"Chhattisgarh", "Surguja", "Khel Sai Singh", "1", " ", "छत्तीसगढ़", "सरगुजा", "खेल साई सिंह", " "},
        {"Chhattisgarh", "Surguja", "Ramnath Cherwa", "4", " ", "छत्तीसगढ़", "सरगुजा", "रामनाथ चेरवा", " "},
        {"Chhattisgarh", "Surguja", "Mohan Singh Tekam", "4", " ", "छत्तीसगढ़", "सरगुजा", "मोहन सिंह टेकाम", " "},
        {"Chhattisgarh", "Surguja", "Palsay Uranv", "4", " ", "छत्तीसगढ़", "सरगुजा", "पलसे उरणव", " "},
        {"Chhattisgarh", "Surguja", "Renuka Singh Saruta", "1", " ", "छत्तीसगढ़", "सरगुजा", "रेणुका सिंह सरुता", " "},
        {"Chhattisgarh", "Surguja", "Guman Singh Poya", "4", " ", "छत्तीसगढ़", "सरगुजा", "गुमान सिंह पोया", " "},
};

}