/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Chhattisgarh {
public static final String[][] green_bucket = {
{"Chhattisgarh",  "3638", "Bastar", "Ramu Ram Mourya", "Communist Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7196",  "छत्तीसगढ़",  "बस्तर", "रामू राम मौर्य", "भारतीय कम्युनिस्ट पार्टी", ""}, 
{"Chhattisgarh",  "3641", "Bastar", "Paneesh Prasad Nag", "Ambedkarite Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7197",  "छत्तीसगढ़",  "बस्तर", "पनेश प्रसाद नाग", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Chhattisgarh",  "6605", "Bilaspur", "Nand Kishore Raj", "Gondvana Gantantra Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9472",  "छत्तीसगढ़",  "बिलासपुर", "नंद किशोर राज", "गोंडवाना गणतंत्र पार्टी", ""}, 
{"Chhattisgarh",  "6606", "Bilaspur", "Urmila Tiwari", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9471",  "छत्तीसगढ़",  "बिलासपुर", "उर्मिला तिवारी", "निर्दलीय", ""}, 
{"Chhattisgarh",  "6607", "Bilaspur", "Salik Ram Jogivansh", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7464",  "छत्तीसगढ़",  "बिलासपुर", "सालिक राम जोगीवंश", "निर्दलीय", ""}, 
{"Chhattisgarh",  "6610", "Bilaspur", "Ramfal Mandrey", "Ambedkarite Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7463",  "छत्तीसगढ़",  "बिलासपुर", "रामफल मंड्रे", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Chhattisgarh",  "6611", "Bilaspur", "Indrasen Mogre", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9464",  "छत्तीसगढ़",  "बिलासपुर", "इंद्रसेन मोगरे", "निर्दलीय", ""}, 
{"Chhattisgarh",  "6613", "Bilaspur", "Sandeep Singh Porte", "Adhikar Vikas Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8222",  "छत्तीसगढ़",  "बिलासपुर", "संदीप सिंह पोर्ते", "", ""}, 
{"Chhattisgarh",  "6615", "Bilaspur", "Harish Kumar Mandwa", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9473",  "छत्तीसगढ़",  "बिलासपुर", "हरीश कुमार मंडवा", "निर्दलीय", ""}, 
{"Chhattisgarh",  "6616", "Bilaspur", "Yaman Banjare", "Bhartiya Kisan Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9463",  "छत्तीसगढ़",  "बिलासपुर", "यमन बंजारे", "भारतीय किसान पार्टी", ""}, 
{"Chhattisgarh",  "6617", "Bilaspur", "Siddhram Lahare", "Rashtriya Jansabha Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9468",  "छत्तीसगढ़",  "बिलासपुर", "सिद्धराम लहरे", "राष्ट्रीय जनसंवाद पार्टी", ""}, 
{"Chhattisgarh",  "6619", "Bilaspur", "Avishek Ekka", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8221",  "छत्तीसगढ़",  "बिलासपुर", "अविषेक एक्का", "निर्दलीय", ""}, 
{"Chhattisgarh",  "6623", "Bilaspur", "Baldau Prasad Sahu", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9465",  "छत्तीसगढ़",  "बिलासपुर", "बलदाऊ प्रसाद साहू", "निर्दलीय", ""}, 
{"Chhattisgarh",  "6625", "Durg", "Praveen Tiwari", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11143",  "छत्तीसगढ़",  "दुर्ग", "प्रवीण तिवारी", "निर्दलीय", ""}, 
{"Chhattisgarh",  "6626", "Durg", "Rajesh Kumar Dubey", "Bhartiya Shakti Chetna Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8217",  "छत्तीसगढ़",  "दुर्ग", "राजेश कुमार दुबे", "भारतीय शक्ति चेतना पार्टी", ""}, 
{"Chhattisgarh",  "6627", "Durg", "Farid Mohammad Quraishi", "Gondvana Gantantra Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11141",  "छत्तीसगढ़",  "दुर्ग", "फरीद मोहम्मद कुरैशी", "गोंडवाना गणतंत्र पार्टी", ""}, 
{"Chhattisgarh",  "6628", "Durg", "Geetanjali Singh", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7472",  "छत्तीसगढ़",  "दुर्ग", "गीतांजलि सिंह", "बहुजन समाज पार्टी", ""}, 
{"Chhattisgarh",  "6632", "Durg", "Aatma Ram Sahu", "Socialist Unity Centre of India (Communist)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7470",  "छत्तीसगढ़",  "दुर्ग", "आतम राम साहू", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Chhattisgarh",  "6634", "Durg", "Tressa David", "India Praja Bandhu Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8213",  "छत्तीसगढ़",  "दुर्ग", "त्रेसा डेविड", "भारत प्रजा बंधु पार्टी", ""}, 
{"Chhattisgarh",  "6642", "Durg", "Sunil Kumar Markandey", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11146",  "छत्तीसगढ़",  "दुर्ग", "सुनील कुमार मार्कंडेय", "निर्दलीय", ""}, 
{"Chhattisgarh",  "6644", "Durg", "Sevakram Banjare", "Rashtriya Jansabha Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11142",  "छत्तीसगढ़",  "दुर्ग", "सेवकराम बंजारे", "राष्ट्रीय जनसंवाद पार्टी", ""}, 
{"Chhattisgarh",  "7888", "Janjgir Champa", "Dauram Satnami", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7475",  "छत्तीसगढ़",  "जांजगीर", "डौरम सतनामी", "बहुजन समाज पार्टी", ""}, 
{"Chhattisgarh",  "7892", "Janjgir Champa", "Seema Ajay", "Ambedkarite Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7800",  "छत्तीसगढ़",  "जांजगीर", "सीमा अजय", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Chhattisgarh",  "7893", "Janjgir Champa", "Shanti Kumar Ratre", "Gondvana Gantantra Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7799",  "छत्तीसगढ़",  "जांजगीर", "शांति कुमार रात्रे", "गोंडवाना गणतंत्र पार्टी", ""}, 
{"Chhattisgarh",  "7895", "Janjgir Champa", "Naresh Kumar Dahriya", "Rashtriya Gondvana Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9475",  "छत्तीसगढ़",  "जांजगीर", "नरेश कुमार डहरिया", "", ""}, 
{"Chhattisgarh",  "7899", "Janjgir Champa", "Aashish Ratre", "Peoples Party of India (Democratic)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7478",  "छत्तीसगढ़",  "जांजगीर", "आशीष रात्रे", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", ""}, 
{"Chhattisgarh",  "7901", "Janjgir Champa", "Asharam Ratnakar", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11350",  "छत्तीसगढ़",  "जांजगीर", "आशाराम रत्नाकर", "निर्दलीय", ""}, 
{"Chhattisgarh",  "3648", "Kanker", "Durgaprasad Thakur", "Ambedkarite Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7169",  "छत्तीसगढ़",  "कांकेर", "दुर्गाप्रसाद ठाकुर", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Chhattisgarh",  "3649", "Kanker", "Umashankar Bhandari", "Shiv Sena", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7175",  "छत्तीसगढ़",  "कांकेर", "उमाशंकर भंडारी", "शिवसेना", ""}, 
{"Chhattisgarh",  "3652", "Kanker", "Mathan Singh Markam", "Bhartiya Shakti Chetna Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7172",  "छत्तीसगढ़",  "कांकेर", "मथन सिंह मरकाम", "भारतीय शक्ति चेतना पार्टी", ""}, 
{"Chhattisgarh",  "6590", "Korba", "Deepak Kumar Sahu", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8208",  "छत्तीसगढ़",  "कोरबा", "दीपक कुमार साहू", "निर्दलीय", ""}, 
{"Chhattisgarh",  "6593", "Korba", "Chandra Bhushan Kanwar", "Ambedkarite Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7480",  "छत्तीसगढ़",  "कोरबा", "चंद्र भूषण कंवर", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Chhattisgarh",  "6596", "Korba", "Lilambar Singh", "Bhartiya Tribal Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8206",  "छत्तीसगढ़",  "कोरबा", "लीलम्बर सिंह", "", ""}, 
{"Chhattisgarh",  "6599", "Korba", "Tuleshwar Markam", "Gondvana Gantantra Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8207",  "छत्तीसगढ़",  "कोरबा", "तुलेश्वर मरकाम", "गोंडवाना गणतंत्र पार्टी", ""}, 
{"Chhattisgarh",  "3629", "Mahasamund", "Champalal Patel", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5418",  "छत्तीसगढ़",  "महासमुंद", "चंपालाल पटेल", "निर्दलीय", ""}, 
{"Chhattisgarh",  "6575", "Raigarh", "Kripashankar Bhagat", "Bhartiya Tribal Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8205",  "छत्तीसगढ़",  "रायगढ़", "कृपाशंकर भगत", "", ""}, 
{"Chhattisgarh",  "6583", "Raigarh", "Innocent Kujur", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7498",  "छत्तीसगढ़",  "रायगढ़", "मासूम कुजूर", "बहुजन समाज पार्टी", ""}, 
{"Chhattisgarh",  "6586", "Raigarh", "Naval Kishor Rathiya", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9485",  "छत्तीसगढ़",  "रायगढ़", "नवल किशोर राठिया", "निर्दलीय", ""}, 
{"Chhattisgarh",  "6657", "Raipur", "Shailendra Kumar Banjare", "Shakti Sena (Bharat Desh)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7817",  "छत्तीसगढ़",  "रायपुर", "शैलेंद्र कुमार बंजारे", "", ""}, 
{"Chhattisgarh",  "6660", "Raipur", "Santosh Sahu", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9493",  "छत्तीसगढ़",  "रायपुर", "संतोष साहू", "निर्दलीय", ""}, 
{"Chhattisgarh",  "6669", "Raipur", "Ajay Chakole", "Gondvana Gantantra Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8202",  "छत्तीसगढ़",  "रायपुर", "अजय चकोले", "गोंडवाना गणतंत्र पार्टी", ""}, 
{"Chhattisgarh",  "6670", "Raipur", "Devendra Kumar Patil", "Socialist Unity Centre of India (Communist)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7500",  "छत्तीसगढ़",  "रायपुर", "देवेंद्र कुमार पाटिल", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Chhattisgarh",  "6651", "Raipur", "Dr. Yogita Bajpai", "Sarvodaya Bharat Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8197",  "छत्तीसगढ़",  "रायपुर", "डॉ। योगिता बाजपेयी", "सर्वोदय भारत पार्टी", ""}, 
{"Chhattisgarh",  "6653", "Raipur", "Pritesh Pandey", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7820",  "छत्तीसगढ़",  "रायपुर", "प्रीतेश पांडे", "निर्दलीय", ""}, 
{"Chhattisgarh",  "3614", "Rajnandgaon", "Ravita Lakra (Dhruv)", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7153",  "छत्तीसगढ़",  "राजनंदगांव", "रविता लकड़ा (ध्रुव)", "बहुजन समाज पार्टी", ""}, 
{"Chhattisgarh",  "3623", "Rajnandgaon", "Mahendra Kumar Sahu", "Forward Democratic Labour Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5538",  "छत्तीसगढ़",  "राजनंदगांव", "महेंद्र कुमार साहू", "फॉरवर्ड डेमोक्रेटिक लेबर पार्टी", ""}, 
{"Chhattisgarh",  "3624", "Rajnandgaon", "Baidya Shekhu Ram Verma", "Ambedkarite Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5112",  "छत्तीसगढ़",  "राजनंदगांव", "बैद्य शेखू राम वर्मा", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Chhattisgarh",  "6565", "Surguja", "Asha Devi Poya", "Gondvana Gantantra Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7824",  "छत्तीसगढ़",  "सरगुजा", "आशा देवी पोया", "गोंडवाना गणतंत्र पार्टी", ""}, 
{"Chhattisgarh",  "6567", "Surguja", "Pawan Kumar Nag", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9499",  "छत्तीसगढ़",  "सरगुजा", "पवन कुमार नाग", "बहुजन मुक्ति पार्टी", ""}, 
{"Chhattisgarh",  "6569", "Surguja", "Maya Prajapati", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7509",  "छत्तीसगढ़",  "सरगुजा", "माया प्रजापति", "बहुजन समाज पार्टी", ""}, 
{"Chhattisgarh",  "6570", "Surguja", "Chandradeep Singh Korcho", "Rashtriya Jansabha Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9498",  "छत्तीसगढ़",  "सरगुजा", "चंद्रदीप सिंह कोरचो", "राष्ट्रीय जनसंवाद पार्टी", ""}, 
};

public static final String[][] red_bucket = {
{ "Chhattisgarh",  "3639",  "Bastar", "Suresh Kawasi", "NotGraduate",  " ","छत्तीसगढ़",  "बस्तर", "सुरेश कावासी", " "}, 
{ "Chhattisgarh",  "3640",  "Bastar", "Deepak Kumar Baij", "ForeignFunding",  " ","छत्तीसगढ़",  "बस्तर", "दीपक कुमार बैज", " "}, 
{ "Chhattisgarh",  "3642",  "Bastar", "Aaytu Ram Mandavi", "NotGraduate",  " ","छत्तीसगढ़",  "बस्तर", "आयतू राम मंडावी", " "}, 
{ "Chhattisgarh",  "3643",  "Bastar", "Baidu Ram Kashyap", "ForeignFunding",  " ","छत्तीसगढ़",  "बस्तर", "Baidu राम कश्यप", " "}, 
{ "Chhattisgarh",  "6600",  "Bilaspur", "Arun Sao", "ForeignFunding",  " ","छत्तीसगढ़",  "बिलासपुर", "अरुण साओ", " "}, 
{ "Chhattisgarh",  "6601",  "Bilaspur", "Raju Khatik", "NotGraduate",  " ","छत्तीसगढ़",  "बिलासपुर", "राजू खटीक", " "}, 
{ "Chhattisgarh",  "6602",  "Bilaspur", "Atal Shrivastav", "ForeignFunding",  " ","छत्तीसगढ़",  "बिलासपुर", "अटल श्रीवास्तव", " "}, 
{ "Chhattisgarh",  "6603",  "Bilaspur", "Pooran Lal Chhabariya", "CriminalCases",  " ","छत्तीसगढ़",  "बिलासपुर", "पूरन लाल छाबड़िया", " "}, 
{ "Chhattisgarh",  "6604",  "Bilaspur", "Arun Kumar Sahu", "NotGraduate",  " ","छत्तीसगढ़",  "बिलासपुर", "अरुण कुमार साहू", " "}, 
{ "Chhattisgarh",  "6608",  "Bilaspur", "Uttam Das Gurugosai", "NotGraduate",  " ","छत्तीसगढ़",  "बिलासपुर", "उत्तम दास गुरुगोसाई", " "}, 
{ "Chhattisgarh",  "6609",  "Bilaspur", "Vidya Sahu", "NotGraduate",  " ","छत्तीसगढ़",  "बिलासपुर", "विद्या साहू", " "}, 
{ "Chhattisgarh",  "6612",  "Bilaspur", "Sandeep Tiwari", "CriminalCases",  " ","छत्तीसगढ़",  "बिलासपुर", "संदीप तिवारी", " "}, 
{ "Chhattisgarh",  "6614",  "Bilaspur", "Santosh Kumar Kaushal", "NotGraduate",  " ","छत्तीसगढ़",  "बिलासपुर", "संतोष कुमार कौशल", " "}, 
{ "Chhattisgarh",  "6618",  "Bilaspur", "Dujram Sahu", "NotGraduate",  " ","छत्तीसगढ़",  "बिलासपुर", "दुजराम साहू", " "}, 
{ "Chhattisgarh",  "6620",  "Bilaspur", "Ramkumar Ghatlahare", "NotGraduate",  " ","छत्तीसगढ़",  "बिलासपुर", "रामकुमार घाटलारे", " "}, 
{ "Chhattisgarh",  "6621",  "Bilaspur", "Hairschandra Teli (Sahu)", "NotGraduate",  " ","छत्तीसगढ़",  "बिलासपुर", "मेलेशचंद्र तेली (साहू)", " "}, 
{ "Chhattisgarh",  "6622",  "Bilaspur", "Shambhu Sharma", "OverAged",  " ","छत्तीसगढ़",  "बिलासपुर", "शंभू शर्मा", " "}, 
{ "Chhattisgarh",  "6624",  "Bilaspur", "Hori Lal Anant", "NotGraduate",  " ","छत्तीसगढ़",  "बिलासपुर", "होरी लाल अनंत", " "}, 
{ "Chhattisgarh",  "6629",  "Durg", "Anoop Kumar Pandey", "NotGraduate",  " ","छत्तीसगढ़",  "दुर्ग", "अनूप कुमार पांडे", " "}, 
{ "Chhattisgarh",  "6630",  "Durg", "Vijay Baghel", "ForeignFunding",  " ","छत्तीसगढ़",  "दुर्ग", "विजय बघेल", " "}, 
{ "Chhattisgarh",  "6631",  "Durg", "Anurag Singh", "NotGraduate",  " ","छत्तीसगढ़",  "दुर्ग", "अनुराग सिंह", " "}, 
{ "Chhattisgarh",  "6633",  "Durg", "Pokhraj Meshram", "NotGraduate",  " ","छत्तीसगढ़",  "दुर्ग", "पोखराज मेश्राम", " "}, 
{ "Chhattisgarh",  "6635",  "Durg", "Pitambar Lal Nishad", "NotGraduate",  " ","छत्तीसगढ़",  "दुर्ग", "पीताम्बर लाल निषाद", " "}, 
{ "Chhattisgarh",  "6636",  "Durg", "Guru Dada Lokesh", "OverAged",  " ","छत्तीसगढ़",  "दुर्ग", "गुरु दादा लोकेश", " "}, 
{ "Chhattisgarh",  "6637",  "Durg", "Manoj Gaykwad Chhattisgarhiya", "NotGraduate",  " ","छत्तीसगढ़",  "दुर्ग", "मनोज गायकवाड़ छत्तीसगढ़ी", " "}, 
{ "Chhattisgarh",  "6638",  "Durg", "Pratima Chandrakar", "ForeignFunding",  " ","छत्तीसगढ़",  "दुर्ग", "प्रतिमा चंद्राकर", " "}, 
{ "Chhattisgarh",  "6639",  "Durg", "Malik Ram Thakur", "NotGraduate",  " ","छत्तीसगढ़",  "दुर्ग", "मलिक राम ठाकुर", " "}, 
{ "Chhattisgarh",  "6640",  "Durg", "Kamlesh Kumar Nagarchi", "NotGraduate",  " ","छत्तीसगढ़",  "दुर्ग", "कमलेश कुमार नागरची", " "}, 
{ "Chhattisgarh",  "6641",  "Durg", "Raj Kumar Gupta", "OverAged",  " ","छत्तीसगढ़",  "दुर्ग", "राज कुमार गुप्ता", " "}, 
{ "Chhattisgarh",  "6643",  "Durg", "Arun Kumar Joshi", "NotGraduate",  " ","छत्तीसगढ़",  "दुर्ग", "अरुण कुमार जोशी", " "}, 
{ "Chhattisgarh",  "6645",  "Durg", "Hidar Bhati", "NotGraduate",  " ","छत्तीसगढ़",  "दुर्ग", "हिदर भाटी", " "}, 
{ "Chhattisgarh",  "7887",  "Janjgir Champa", "Ravindra Shekhar Bharadwaj", "ForeignFunding",  " ","छत्तीसगढ़",  "जांजगीर", "रवींद्र शेखर भारद्वाज", " "}, 
{ "Chhattisgarh",  "7889",  "Janjgir Champa", "Vranda Chouhan", "NotGraduate",  " ","छत्तीसगढ़",  "जांजगीर", "वृंदा चौहान", " "}, 
{ "Chhattisgarh",  "7890",  "Janjgir Champa", "Bhojram Banjare", "CriminalCases",  " ","छत्तीसगढ़",  "जांजगीर", "भोजराम बंजारे", " "}, 
{ "Chhattisgarh",  "7891",  "Janjgir Champa", "Nitesh Kumar Ratre", "NotGraduate",  " ","छत्तीसगढ़",  "जांजगीर", "नितेश कुमार रत्रे", " "}, 
{ "Chhattisgarh",  "7894",  "Janjgir Champa", "Uday Das Ratre", "NotGraduate",  " ","छत्तीसगढ़",  "जांजगीर", "उदय दास रत्रे", " "}, 
{ "Chhattisgarh",  "7896",  "Janjgir Champa", "Sitabai Chouhan", "NotGraduate",  " ","छत्तीसगढ़",  "जांजगीर", "सीताबाई चौहान", " "}, 
{ "Chhattisgarh",  "7897",  "Janjgir Champa", "Naresh Bai Jangde", "NotGraduate",  " ","छत्तीसगढ़",  "जांजगीर", "नरेश बाई जांगड़े", " "}, 
{ "Chhattisgarh",  "7898",  "Janjgir Champa", "Lakhan Ram Chouhan", "OverAged",  " ","छत्तीसगढ़",  "जांजगीर", "लखन राम चौहान", " "}, 
{ "Chhattisgarh",  "7900",  "Janjgir Champa", "Guharam Ajgalle", "ForeignFunding",  " ","छत्तीसगढ़",  "जांजगीर", "गुहाराम अजगले", " "}, 
{ "Chhattisgarh",  "3644",  "Kanker", "Sube Singh Dhurva", "NotGraduate",  " ","छत्तीसगढ़",  "कांकेर", "सूबे सिंह धुर्वा", " "}, 
{ "Chhattisgarh",  "3645",  "Kanker", "Mohan Mandavi", "ForeignFunding",  " ","छत्तीसगढ़",  "कांकेर", "मोहन मंडावी", " "}, 
{ "Chhattisgarh",  "3646",  "Kanker", "Narend Nag", "NotGraduate",  " ","छत्तीसगढ़",  "कांकेर", "नरेंद्र नाग", " "}, 
{ "Chhattisgarh",  "3647",  "Kanker", "Biresh Thakur", "ForeignFunding",  " ","छत्तीसगढ़",  "कांकेर", "बिरेश ठाकुर", " "}, 
{ "Chhattisgarh",  "3650",  "Kanker", "Harisingh Sidar", "OverAged",  " ","छत्तीसगढ़",  "कांकेर", "हरिसिंह सिदार", " "}, 
{ "Chhattisgarh",  "3651",  "Kanker", "Ghanshyam Jurri", "NotGraduate",  " ","छत्तीसगढ़",  "कांकेर", "घनश्याम जुरी", " "}, 
{ "Chhattisgarh",  "6587",  "Korba", "Jyotsna Mahant", "ForeignFunding",  " ","छत्तीसगढ़",  "कोरबा", "ज्योत्सना महंत", " "}, 
{ "Chhattisgarh",  "6588",  "Korba", "Raj Kumar Yadav", "OverAged",  " ","छत्तीसगढ़",  "कोरबा", "राज कुमार यादव", " "}, 
{ "Chhattisgarh",  "6589",  "Korba", "Pramod Kumar Sharma", "NotGraduate",  " ","छत्तीसगढ़",  "कोरबा", "प्रमोद कुमार शर्मा", " "}, 
{ "Chhattisgarh",  "6591",  "Korba", "Rajesh Pandey", "CriminalCases",  " ","छत्तीसगढ़",  "कोरबा", "राजेश पांडे", " "}, 
{ "Chhattisgarh",  "6592",  "Korba", "Jyoti Nand Dubey", "ForeignFunding",  " ","छत्तीसगढ़",  "कोरबा", "ज्योति नंद दुबे", " "}, 
{ "Chhattisgarh",  "6594",  "Korba", "Parmit Singh", "CriminalCases",  " ","छत्तीसगढ़",  "कोरबा", "परमीत सिंह", " "}, 
{ "Chhattisgarh",  "6595",  "Korba", "Suman Lal Khande", "NotGraduate",  " ","छत्तीसगढ़",  "कोरबा", "सुमन लाल खांडे", " "}, 
{ "Chhattisgarh",  "6597",  "Korba", "Ramdayal Uraon", "NotGraduate",  " ","छत्तीसगढ़",  "कोरबा", "रामदयाल उरांव", " "}, 
{ "Chhattisgarh",  "6598",  "Korba", "Lakhan Lal Dewangan", "NotGraduate",  " ","छत्तीसगढ़",  "कोरबा", "लखन लाल देवांगन", " "}, 
{ "Chhattisgarh",  "3625",  "Mahasamund", "Rohit Kumar Kosre", "NotGraduate",  " ","छत्तीसगढ़",  "महासमुंद", "रोहित कुमार कोसरे", " "}, 
{ "Chhattisgarh",  "3626",  "Mahasamund", "Santosh Banjare", "NotGraduate",  " ","छत्तीसगढ़",  "महासमुंद", "संतोष बंजारे", " "}, 
{ "Chhattisgarh",  "3627",  "Mahasamund", "Ashok Soni", "NotGraduate",  " ","छत्तीसगढ़",  "महासमुंद", "अशोक सोनी", " "}, 
{ "Chhattisgarh",  "3628",  "Mahasamund", "Khilawan Singh Dhruw", "NotGraduate",  " ","छत्तीसगढ़",  "महासमुंद", "खिलवान सिंह ध्रुव", " "}, 
{ "Chhattisgarh",  "3630",  "Mahasamund", "Devendar Singh Thakur (Rajput)", "CriminalCases",  " ","छत्तीसगढ़",  "महासमुंद", "देवेन्द्र सिंह ठाकुर (राजपूत)", " "}, 
{ "Chhattisgarh",  "3631",  "Mahasamund", "Dhanendra Sahu", "ForeignFunding",  " ","छत्तीसगढ़",  "महासमुंद", "धनेंद्र साहू", " "}, 
{ "Chhattisgarh",  "3632",  "Mahasamund", "Dhansing Kosariya", "CriminalCases",  " ","छत्तीसगढ़",  "महासमुंद", "धनसार कोसरिया", " "}, 
{ "Chhattisgarh",  "3633",  "Mahasamund", "Jagmohan Bhagwat Kosariya", "OverAged",  " ","छत्तीसगढ़",  "महासमुंद", "जगमोहन भागवत कोश्यारी", " "}, 
{ "Chhattisgarh",  "3634",  "Mahasamund", "Tarun Kumar Dadsena", "CriminalCases",  " ","छत्तीसगढ़",  "महासमुंद", "तरुण कुमार डडसेना", " "}, 
{ "Chhattisgarh",  "3635",  "Mahasamund", "Bhojlal Netam", "OverAged",  " ","छत्तीसगढ़",  "महासमुंद", "भोजलाल नेताम", " "}, 
{ "Chhattisgarh",  "3636",  "Mahasamund", "Chunni Lal Sahu", "ForeignFunding",  " ","छत्तीसगढ़",  "महासमुंद", "चुन्नी लाल साहू", " "}, 
{ "Chhattisgarh",  "3637",  "Mahasamund", "Dr. Virendra Choudhary", "NotGraduate",  " ","छत्तीसगढ़",  "महासमुंद", "डॉ। वीरेंद्र चौधरी", " "}, 
{ "Chhattisgarh",  "6573",  "Raigarh", "Gomati", "ForeignFunding",  " ","छत्तीसगढ़",  "रायगढ़", "गोमती", " "}, 
{ "Chhattisgarh",  "6574",  "Raigarh", "Amrit Tirkey", "NotGraduate",  " ","छत्तीसगढ़",  "रायगढ़", "अमृत तिर्की", " "}, 
{ "Chhattisgarh",  "6576",  "Raigarh", "Tejram Sidar", "NotGraduate",  " ","छत्तीसगढ़",  "रायगढ़", "तेजराम सिदार", " "}, 
{ "Chhattisgarh",  "6577",  "Raigarh", "Praksh Kumar Uraon", "NotGraduate",  " ","छत्तीसगढ़",  "रायगढ़", "प्रक्ष कुमार उरांव", " "}, 
{ "Chhattisgarh",  "6578",  "Raigarh", "Jai Singh Sidar", "NotGraduate",  " ","छत्तीसगढ़",  "रायगढ़", "जय सिंह सिदार", " "}, 
{ "Chhattisgarh",  "6579",  "Raigarh", "Vijay Lakara", "NotGraduate",  " ","छत्तीसगढ़",  "रायगढ़", "विजय लकड़ा", " "}, 
{ "Chhattisgarh",  "6580",  "Raigarh", "Ravishankar Sidar", "NotGraduate",  " ","छत्तीसगढ़",  "रायगढ़", "रविशंकर सिदार", " "}, 
{ "Chhattisgarh",  "6581",  "Raigarh", "Jyoti Bhagat", "NotGraduate",  " ","छत्तीसगढ़",  "रायगढ़", "ज्योति भगत", " "}, 
{ "Chhattisgarh",  "6582",  "Raigarh", "Tarika Tarangini Uraon", "CriminalCases",  " ","छत्तीसगढ़",  "रायगढ़", "तारिका तरंगिणी उरांव", " "}, 
{ "Chhattisgarh",  "6584",  "Raigarh", "Laljeet Singh Rathiya", "ForeignFunding",  " ","छत्तीसगढ़",  "रायगढ़", "लालजीत सिंह राठिया", " "}, 
{ "Chhattisgarh",  "6585",  "Raigarh", "Vir Kumar Tigga", "NotGraduate",  " ","छत्तीसगढ़",  "रायगढ़", "वीर कुमार तिग्गा", " "}, 
{ "Chhattisgarh",  "6656",  "Raipur", "Manish Shrivastav", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "मनीष श्रीवास्तव", " "}, 
{ "Chhattisgarh",  "6658",  "Raipur", "Chhabi Lal Kanwar", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "छबि लाल कंवर", " "}, 
{ "Chhattisgarh",  "6659",  "Raipur", "Devki Dubey", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "देवकी दुबे", " "}, 
{ "Chhattisgarh",  "6661",  "Raipur", "Pramod Dubey", "ForeignFunding",  " ","छत्तीसगढ़",  "रायपुर", "प्रमोद दुबे", " "}, 
{ "Chhattisgarh",  "6662",  "Raipur", "Ramdyal Dahariya", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "रामदयाल डहरिया", " "}, 
{ "Chhattisgarh",  "6663",  "Raipur", "Navin Gupta", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "नवीन गुप्ता", " "}, 
{ "Chhattisgarh",  "6664",  "Raipur", "Sanju Kumar Yadav", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "संजू कुमार यादव", " "}, 
{ "Chhattisgarh",  "6665",  "Raipur", "Vijay Kumar Kurre", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "विजय कुमार कुर्रे", " "}, 
{ "Chhattisgarh",  "6666",  "Raipur", "Pravin Jain", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "प्रवीण जैन", " "}, 
{ "Chhattisgarh",  "6667",  "Raipur", "Ramkrishna Verma", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "रामकृष्ण वर्मा", " "}, 
{ "Chhattisgarh",  "6668",  "Raipur", "Santosh Kumar Yadu", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "संतोष कुमार यदु", " "}, 
{ "Chhattisgarh",  "6646",  "Raipur", "Rupesh Sahu", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "रूपेश साहू", " "}, 
{ "Chhattisgarh",  "6647",  "Raipur", "Tameshwar Sahu", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "तमेश्वर साहू", " "}, 
{ "Chhattisgarh",  "6648",  "Raipur", "Ikram Saifi", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "इकराम सैफी", " "}, 
{ "Chhattisgarh",  "6649",  "Raipur", "Shankar Lal Vardani", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "शंकर लाल वरदानी", " "}, 
{ "Chhattisgarh",  "6650",  "Raipur", "Khilesh Kumar Sahu", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "खिलेश कुमार साहू", " "}, 
{ "Chhattisgarh",  "6652",  "Raipur", "Tarjan Jangde", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "टारजन जांगड़े", " "}, 
{ "Chhattisgarh",  "6654",  "Raipur", "Sunil Kumar Soni", "ForeignFunding",  " ","छत्तीसगढ़",  "रायपुर", "सुनील कुमार सोनी", " "}, 
{ "Chhattisgarh",  "6655",  "Raipur", "Banmali Chhura", "NotGraduate",  " ","छत्तीसगढ़",  "रायपुर", "बनमाली छुरा", " "}, 
{ "Chhattisgarh",  "3611",  "Rajnandgaon", "Kamini Sahu", "NotGraduate",  " ","छत्तीसगढ़",  "राजनंदगांव", "कामिनी साहू", " "}, 
{ "Chhattisgarh",  "3612",  "Rajnandgaon", "Sudesh Tikam", "CriminalCases",  " ","छत्तीसगढ़",  "राजनंदगांव", "सुदेश टीकम", " "}, 
{ "Chhattisgarh",  "3613",  "Rajnandgaon", "Bhola Ram Sahu", "ForeignFunding",  " ","छत्तीसगढ़",  "राजनंदगांव", "भोला राम साहू", " "}, 
{ "Chhattisgarh",  "3615",  "Rajnandgaon", "Vishwanath Singh Porte", "NotGraduate",  " ","छत्तीसगढ़",  "राजनंदगांव", "विश्वनाथ सिंह पोर्ते", " "}, 
{ "Chhattisgarh",  "3616",  "Rajnandgaon", "Ramkhilawan Dahariya", "NotGraduate",  " ","छत्तीसगढ़",  "राजनंदगांव", "रामखिलावन डहरिया", " "}, 
{ "Chhattisgarh",  "3617",  "Rajnandgaon", "Kranti Gupta", "NotGraduate",  " ","छत्तीसगढ़",  "राजनंदगांव", "क्रांति गुप्ता", " "}, 
{ "Chhattisgarh",  "3618",  "Rajnandgaon", "Ajay Pali", "NotGraduate",  " ","छत्तीसगढ़",  "राजनंदगांव", "अजय पाली", " "}, 
{ "Chhattisgarh",  "3619",  "Rajnandgaon", "Pratima Santosh Washnik", "NotGraduate",  " ","छत्तीसगढ़",  "राजनंदगांव", "प्रतिमा संतोष वाशनिक", " "}, 
{ "Chhattisgarh",  "3620",  "Rajnandgaon", "Dr. Gojupal", "CriminalCases",  " ","छत्तीसगढ़",  "राजनंदगांव", "डॉ। गूजुपाल", " "}, 
{ "Chhattisgarh",  "3621",  "Rajnandgaon", "Sachchidanand Kaushik", "NotGraduate",  " ","छत्तीसगढ़",  "राजनंदगांव", "सच्चिदानंद कौशिक", " "}, 
{ "Chhattisgarh",  "3622",  "Rajnandgaon", "Santosh Pandey", "ForeignFunding",  " ","छत्तीसगढ़",  "राजनंदगांव", "संतोष पांडे", " "}, 
{ "Chhattisgarh",  "6563",  "Surguja", "Khel Sai Singh", "ForeignFunding",  " ","छत्तीसगढ़",  "सरगुजा", "खेल साई सिंह", " "}, 
{ "Chhattisgarh",  "6564",  "Surguja", "Ramnath Cherwa", "NotGraduate",  " ","छत्तीसगढ़",  "सरगुजा", "रामनाथ चेरवा", " "}, 
{ "Chhattisgarh",  "6566",  "Surguja", "Mohan Singh Tekam", "NotGraduate",  " ","छत्तीसगढ़",  "सरगुजा", "मोहन सिंह टेकाम", " "}, 
{ "Chhattisgarh",  "6568",  "Surguja", "Palsay Uranv", "NotGraduate",  " ","छत्तीसगढ़",  "सरगुजा", "पलसे उरणव", " "}, 
{ "Chhattisgarh",  "6571",  "Surguja", "Renuka Singh Saruta", "ForeignFunding",  " ","छत्तीसगढ़",  "सरगुजा", "रेणुका सिंह सरुता", " "}, 
{ "Chhattisgarh",  "6572",  "Surguja", "Guman Singh Poya", "NotGraduate",  " ","छत्तीसगढ़",  "सरगुजा", "गुमान सिंह पोया", " "}, 
};

}