/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Gujarat {
public static final String[][] green_bucket = {
        {"Gujarat", "Ahmedabad East", "Minaxiben Rakeshkumar Solanki", "Independent", "69.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9377", "गुजरात", "अहमदाबाद पूर्व", "मिनाक्सीबेन राकेशकुमार सोलंकी", "निर्दलीय"},
        {"Gujarat", "Ahmedabad East", "Chauhan Narendra Sinh Makhatul Sinh", "Yuva Jan Jagriti Party", "53.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9385", "गुजरात", "अहमदाबाद पूर्व", "चौहान नरेंद्र सिंह माखतुल सिंह", "युवा जन जागृति पार्टी"},
        {"Gujarat", "Ahmedabad East", "Mundra Anilkumar", "Lok Gathbandhan Party", "18.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9374", "गुजरात", "अहमदाबाद पूर्व", "मुंद्रा अनिलकुमार", "लोक गठबंधन पार्टी"},
        {"Gujarat", "Ahmedabad East", "Dr. Hiteshkumar Mahendrabhai", "Nirbhay Bharteey Party", "54.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9383", "गुजरात", "अहमदाबाद पूर्व", "डॉ। हितेशकुमार महेंद्रभाई", "निर्भय भारती पार्टी"},
        {"Gujarat", "Ahmedabad East", "Pareshkumar Nanubhai Mulani", "Independent", "21Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9373", "गुजरात", "अहमदाबाद पूर्व", "परेशकुमार नानूभाई मुलानी", "निर्दलीय"},
        {"Gujarat", "Ahmedabad East", "Sharma Brijeshkumar Ujagarlal", "Independent", "26800", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10034", "गुजरात", "अहमदाबाद पूर्व", "शर्मा बृजेशकुमार उजागरलाल", "निर्दलीय"},
        {"Gujarat", "Ahmedabad East", "Atulbhai Nanubhai Kathiriya", "Independent", "29Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9381", "गुजरात", "अहमदाबाद पूर्व", "अतुलभाई नानूभाई कथिरिया", "निर्दलीय"},
        {"Gujarat", "Ahmedabad East", "Bhatt Sunilkumar Narendrabhai", "Right to Recall Party", "25.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9376", "गुजरात", "अहमदाबाद पूर्व", "भट्ट सुनीलकुमार नरेंद्रभाई", "राइट टू रिकॉल पार्टी"},
        {"Gujarat", "Ahmedabad West", "Solanki Chiragbhai Somabhai", "Jan Satya Path Party", "4.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9393", "गुजरात", "अहमदाबाद पश्चिम", "सोलंकी चिरागभाई सोमाभाई", "जन सत्य पथ पार्टी"},
        {"Gujarat", "Ahmedabad West", "Jadav Ulpesh Jyantilal", "Peoples Party of India (Democratic)", "36.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9395", "गुजरात", "अहमदाबाद पश्चिम", "जादव उल्पेश जयंतीलाल", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
        {"Gujarat", "Ahmedabad West", "Chauhan Harishbhai Jethabhai", "Rashtriya Power Party", "32.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9390", "गुजरात", "अहमदाबाद पश्चिम", "चौहान हरीशभाई जेठाभाई", "राष्ट्रीय पावर पार्टी"},
        {"Gujarat", "Ahmedabad West", "Malhotra Pankajkumar Dayabhai (Doctor Saheb)", "Independent", "4000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10037", "गुजरात", "अहमदाबाद पश्चिम", "मल्होत्रा पंकजकुमार दयाभाई (डॉक्टर साहब)", "निर्दलीय"},
        {"Gujarat", "Anand", "Chavda Kaushikkumar", "Independent", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8976", "गुजरात", "आनंद", "चावड़ा कौशिककुमार", "निर्दलीय"},
        {"Gujarat", "Anand", "Bhatt Sunilkumar Narendrabhai", "Right to Recall Party", "25.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8979", "गुजरात", "आनंद", "भट्ट सुनीलकुमार नरेंद्रभाई", "राइट टू रिकॉल पार्टी"},
        {"Gujarat", "Banaskantha", "Madhu Nirupaben", "Independent", "3.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9294", "गुजरात", "बनासकांठा", "मधु निरुपाबेन", "निर्दलीय"},
        {"Gujarat", "Banaskantha", "Purohit Shyamaben Naranbhai", "Independent", "25.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9282", "गुजरात", "बनासकांठा", "पुरोहित श्यामबेन नारनभाई", "निर्दलीय"},
        {"Gujarat", "Bardoli", "Pragneshbhai Ratilal Chaudhari", "Independent", "54.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10352", "गुजरात", "बारडोली", "प्रज्ञेशभाई रतिलाल चौधरी", "निर्दलीय"},
        {"Gujarat", "Bardoli", "Dineshbhai Gulabbhai Chaudhari", "Bahujan Samaj Party", "95000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8004", "गुजरात", "बारडोली", "दिनेशभाई गुलाबभाई चौधरी", "बहुजन समाज पार्टी"},
        {"Gujarat", "Bardoli", "Sureshbhai Motiyabhai Chaudhari", "Independent", "56.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10354", "गुजरात", "बारडोली", "सुरेशभाई मोटियाभाई चौधरी", "निर्दलीय"},
        {"Gujarat", "Bharuch", "Jitendra Parmar", "Independent", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9009", "गुजरात", "भरूच", "जितेंद्र परमार", "निर्दलीय"},
        {"Gujarat", "Bhavnagar", "Vijaykumar Ramabhai Makadiya", "Bahujan Samaj Party", "50000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8503", "गुजरात", "भावनगर", "विजयकुमार रामभाई मकाडिय़ा", "बहुजन समाज पार्टी"},
        {"Gujarat", "Bhavnagar", "Champaben Zaverbhai Chauhan", "Independent", "37.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9448", "गुजरात", "भावनगर", "चम्पाबेन झवेरभाई चौहान", "निर्दलीय"},
        {"Gujarat", "Chhota Udaipur", "Umesh Jangubhai Rathawa", "Independent", "1.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9002", "गुजरात", "छोटा उदयपुर", "उमेश जंगुभाई राठवा", "निर्दलीय"},
        {"Gujarat", "Chhota Udaipur", "Vasava Rajesh Somabhai", "Bhartiya Tribal Party", "10.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9004", "गुजरात", "छोटा उदयपुर", "वसावा राजेश सोमभाई", "भारतीय ट्राइबल पार्टी"},
        {"Gujarat", "Dahod", "Devadha Samsubhai Khatarabhai", "Independent", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8996", "गुजरात", "दाहोद", "देवदास संमुभाई खातरभाई", "निर्दलीय"},
        {"Gujarat", "Gandhinagar", "Rathod Bhogilal Jenabhai", "Bahujan Mukti Party", "6.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9360", "गुजरात", "गांधीनगर", "राठौड़ भोगीलाल जेनाभाई", "बहुजन मुक्ति पार्टी"},
        {"Gujarat", "Gandhinagar", "Jayendra Karshanbhai Rathod", "Bahujan Samaj Party", "8.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8481", "गुजरात", "गांधीनगर", "जयेन्द्र दर्शनभाई राठौड़", "बहुजन समाज पार्टी"},
        {"Gujarat", "Gandhinagar", "Rahul Chimanbhai Mehta", "Right to Recall Party", "5.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9349", "गुजरात", "गांधीनगर", "राहुल चिमनभाई मेहता", "राइट टू रिकॉल पार्टी"},
        {"Gujarat", "Jamnagar", "Jahid Aavad Jami", "Independent", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10059", "गुजरात", "जामनगर", "जाहिद आवद जामी", "निर्दलीय"},
        {"Gujarat", "Jamnagar", "Vaghela Sunil Jethalal", "Bahujan Samaj Party", "1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8020", "गुजरात", "जामनगर", "वाघेला सुनील जेठालाल", "बहुजन समाज पार्टी"},
        {"Gujarat", "Jamnagar", "Baxi Mrudul Ashwinkumar", "Independent", "1.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10063", "गुजरात", "जामनगर", "बक्सी मृदुल अश्विनकुमार", "निर्दलीय"},
        {"Gujarat", "Junagadh", "Dharmendra Vajubhai Makwana", "Independent", "3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9307", "गुजरात", "जूनागढ़", "धर्मेंद्र वजुभाई मकवाना", "निर्दलीय"},
        {"Gujarat", "Junagadh", "Haresh Manubhai Sardhara", "Independent", "7.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9305", "गुजरात", "जूनागढ़", "हरेश मनुभाई सरधरा", "निर्दलीय"},
        {"Gujarat", "Junagadh", "Vala Jaypalsinh Hajabhai", "Independent", "3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9303", "गुजरात", "जूनागढ़", "वला जयपालसिंह हजभाई", "निर्दलीय"},
        {"Gujarat", "Mahesana", "Chaudhari Sendhabhai Abherajbhai", "Bahujan Mukti Party", "84.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9321", "गुजरात", "महेसाणा", "चौधरी सेंधाभाई अभिराजभाई", "बहुजन मुक्ति पार्टी"},
        {"Gujarat", "Mahesana", "Barot Kuldipkumar Bharatkumar", "Yuva Jan Jagriti Party", "14.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9328", "गुजरात", "महेसाणा", "बरोट कुलदीपकुमार भरतकुमार", "युवा जन जागृति पार्टी"},
        {"Gujarat", "Navsari", "Jain Rajendrakumar Anilkumar", "Independent", "5.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9033", "गुजरात", "नवसारी", "जैन राजेंद्रकुमार अनिलकुमार", "निर्दलीय"},
        {"Gujarat", "Navsari", "Singh Vineeta", "Bahujan Samaj Party", "58.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8578", "गुजरात", "नवसारी", "सिंह विनीता", "बहुजन समाज पार्टी"},
        {"Gujarat", "Navsari", "Khadadiya Kanubhai Tapubhai", "Socialist Unity Centre of India (Communist)", "75.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9022", "गुजरात", "नवसारी", "खड़दिया कनुभाई तपुभाई", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Gujarat", "Navsari", "Khan Heenabegam", "Independent", "51.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9026", "गुजरात", "नवसारी", "खान हेनाबेगम", "निर्दलीय"},
        {"Gujarat", "Navsari", "Patel Navinkumar", "Independent", "7.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9029", "गुजरात", "नवसारी", "पटेल नवीनकुमार", "निर्दलीय"},
        {"Gujarat", "Navsari", "Mishra Jitendrabhai Premnath", "Sanyukt Vikas Party", "11.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9030", "गुजरात", "नवसारी", "मिश्रा जितेन्द्रभाई प्रेमनाथ", "संयुक्ता विकास पार्टी"},
        {"Gujarat", "Panchmahal", "Rathod Vijaysinh", "Hindusthan Nirman Dal", "18.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8992", "गुजरात", "पंचमहल", "राठौड़ विजयसिंह", "हिंदुस्तान निर्माण दल"},
        {"Gujarat", "Patan", "Parmar Surajkumar Mahendrakumar", "Bahujan Samaj Party", "9.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8011", "गुजरात", "पाटन", "परमार सूरजकुमार महेंद्रकुमार", "बहुजन समाज पार्टी"},
        {"Gujarat", "Patan", "Chaudhari Kirtibhai Jesangbhai", "Nationalist Congress Party", "37.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9312", "गुजरात", "पाटन", "चौधरी कीर्तिभाई जेसंगभाई", "राष्ट्रवादी कांग्रेस पार्टी"},
        {"Gujarat", "Porbandar", "Bhanubhai Odedra", "Independent", "21.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9411", "गुजरात", "पोरबंदर", "भानुभाई ओडेदरा", "निर्दलीय"},
        {"Gujarat", "Porbandar", "Vakil Vinzuda Ranjitbhai", "Bahujan Maha Party", "14.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9412", "गुजरात", "पोरबंदर", "वकिल विनज़ुदा रंजीतभाई", "बहुजन महा पार्टी"},
        {"Gujarat", "Porbandar", "Sondarva Ashok", "Independent", "24.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9414", "गुजरात", "पोरबंदर", "सोंदरवा अशोक", "निर्दलीय"},
        {"Gujarat", "Porbandar", "Alpesh Vadoliya", "Independent", "75124", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9419", "गुजरात", "पोरबंदर", "अल्पेश वडोलिया", "निर्दलीय"},
        {"Gujarat", "Rajkot", "Chitroda Nathalal", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9404", "गुजरात", "राजकोट", "चितरोदा नथमल", "निर्दलीय"},
        {"Gujarat", "Sabarkantha", "Kalabhai Bababhai Parmar", "Independent", "5.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9340", "गुजरात", "साबरकांठा", "कालाभाई बाबाभाई परमार", "निर्दलीय"},
        {"Gujarat", "Sabarkantha", "Vinodbhai Mesariya", "Bahujan Samaj Party", "44.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8015", "गुजरात", "साबरकांठा", "विनोदभाई मेसरिया", "बहुजन समाज पार्टी"},
        {"Gujarat", "Sabarkantha", "Patel Jayntibhai Shamjibhai", "Hindusthan Nirman Dal", "39.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9339", "गुजरात", "साबरकांठा", "पटेल जयंतीभाई शामजीभाई", "हिंदुस्तान निर्माण दल"},
        {"Gujarat", "Sabarkantha", "Kharadi Dharmendrasingh Samsubhai", "Bhartiya Tribal Party", "27Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9346", "गुजरात", "साबरकांठा", "खराडी धर्मेन्द्रसिंह समसुभाई", "भारतीय ट्राइबल पार्टी"},
        {"Gujarat", "Sabarkantha", "Patel Kiritkumar Babarbhai", "Independent", "41.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9954", "गुजरात", "साबरकांठा", "पटेल किरीटकुमार बाबरभाई", "निर्दलीय"},
        {"Gujarat", "Surat", "Rita Captain", "Pyramid Party of India", "1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8802", "गुजरात", "सूरत", "रीता कैप्टन", "पिरामिड पार्टी ऑफ इंडिया"},
        {"Gujarat", "Surat", "Shenmare Vijaybhai Namdeo", "Communist Party of India", "98.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8005", "गुजरात", "सूरत", "शेनमारे विजयभाई नामदेव", "भारतीय कम्युनिस्ट पार्टी"},
        {"Gujarat", "Surat", "Jogiya Amisha Vikrambhai", "Sanyukt Vikas Party", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8805", "गुजरात", "सूरत", "जोगिया अमीषा विक्रमभाई", "संयुक्ता विकास पार्टी"},
        {"Gujarat", "Surat", "Natvarbhai Dahyabhai Mahyavanshi", "Independent", "10.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8800", "गुजरात", "सूरत", "नटवरभाई भयभाई महावंशी", "निर्दलीय"},
        {"Gujarat", "Surendranagar", "Bhavanbhai Devjibhai Vora", "Independent", "8.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10047", "गुजरात", "सुरेंद्रनगर", "भवानभाई देवजीभाई वोरा", "निर्दलीय"},
        {"Gujarat", "Surendranagar", "Rathod Anandbhai Pachanbhai", "Independent", "3.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8796", "गुजरात", "सुरेंद्रनगर", "राठौड़ आनंदभाई पचनभाई", "निर्दलीय"},
        {"Gujarat", "Surendranagar", "Solanki Shaileshbhai Nagarbhai", "Bahujan Samaj Party", "45.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8492", "गुजरात", "सुरेंद्रनगर", "सोलंकी शैलेशभाई नागरभाई", "बहुजन समाज पार्टी"},
        {"Gujarat", "Vadodara", "Dr. Rahul Vasudevbhai Vyas", "Independent", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8784", "गुजरात", "वडोदरा", "डॉ। राहुल वासुदेवभाई व्यास", "निर्दलीय"},
        {"Gujarat", "Vadodara", "Sindhi Mahebubkhan Yusufkhan", "Independent", "26.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8785", "गुजरात", "वडोदरा", "सिंधी महबूबखान युसुफखान", "निर्दलीय"},
        {"Gujarat", "Vadodara", "Rohit Madhusudan Mohanbhai", "Bahujan Samaj Party", "90.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8001", "गुजरात", "वडोदरा", "रोहित मधुसूदन मोहनभाई", "बहुजन समाज पार्टी"},
        {"Gujarat", "Vadodara", "Tapanbhai Dasgupta", "Socialist Unity Centre of India (Communist)", "11.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8781", "गुजरात", "वडोदरा", "तपनभाई दासगुप्ता", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Gujarat", "Vadodara", "Nimesh Patel (Kamrol)", "Independent", "26.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10345", "गुजरात", "वडोदरा", "निमेश पटेल (कमरोल)", "निर्दलीय"},
        {"Gujarat", "Vadodara", "Santosh S. Solanki", "Bhartiya Manavadhikaar Federal Party", "8.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10344", "गुजरात", "वडोदरा", "संतोष एस। सोलंकी", "भारतीय मानववादी फेडरल पार्टी"},
        {"Gujarat", "Valsad", "Ganvit Jayendrabhai Laxmanbhai", "Independent", "25000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8775", "गुजरात", "वलसाड", "गनवित जयेन्द्रभाई लक्ष्मणभाई", "निर्दलीय"},
        {"Gujarat", "Valsad", "Gaurangbhai Rameshbhai Patel", "Independent", "7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8778", "गुजरात", "वलसाड", "गौरांगभाई रमेशभाई पटेल", "निर्दलीय"},
};

public static final String[][] red_bucket = {
        {"Gujarat", "Ahmedabad East", "Virat Pradip Shah", "4", " ", "गुजरात", "अहमदाबाद पूर्व", "विराट प्रदीप शाह", " "},
        {"Gujarat", "Ahmedabad East", "Kadri Mohammad Sabir", "4", " ", "गुजरात", "अहमदाबाद पूर्व", "कादरी मोहम्मद साबिर", " "},
        {"Gujarat", "Ahmedabad East", "Mishra Arjun Ramshankar", "4", " ", "गुजरात", "अहमदाबाद पूर्व", "मिश्रा अर्जुन रामशंकर", " "},
        {"Gujarat", "Ahmedabad East", "Samirbhai Rajeshbhai Upadhyay", "4", " ", "गुजरात", "अहमदाबाद पूर्व", "समीरभाई राजेशभाई उपाध्याय", " "},
        {"Gujarat", "Ahmedabad East", "Geetaben Patel", "1", " ", "गुजरात", "अहमदाबाद पूर्व", "गीताबेन पटेल", " "},
        {"Gujarat", "Ahmedabad East", "Patel Hasmukhbhai Somabhai", "1", " ", "गुजरात", "अहमदाबाद पूर्व", "पटेल हसमुखभाई सोमाभाई", " "},
        {"Gujarat", "Ahmedabad East", "Bharvad Saileshkumar Kalidas", "2", " ", "गुजरात", "अहमदाबाद पूर्व", "भारवद शैलेषकुमार कालिदास", " "},
        {"Gujarat", "Ahmedabad East", "Chauhan Kiritbhai", "4", " ", "गुजरात", "अहमदाबाद पूर्व", "चौहान किरीटभाई", " "},
        {"Gujarat", "Ahmedabad East", "Mishra Rajkumar Malekchand", "4", " ", "गुजरात", "अहमदाबाद पूर्व", "मिश्रा राजकुमार मालेकचंद", " "},
        {"Gujarat", "Ahmedabad East", "Rajesh Maurya", "4", " ", "गुजरात", "अहमदाबाद पूर्व", "राजेश मौर्य", " "},
        {"Gujarat", "Ahmedabad East", "Vekariya Rushi Bharatbhai (Patel)", "4", " ", "गुजरात", "अहमदाबाद पूर्व", "वेकारिया रूशी भरतभाई (पटेल)", " "},
        {"Gujarat", "Ahmedabad East", "Thakur Jitendrasinh Surendrasinh", "4", " ", "गुजरात", "अहमदाबाद पूर्व", "ठाकुर जितेन्द्रसिंह सुरेन्द्रसिंह", " "},
        {"Gujarat", "Ahmedabad East", "Devda Dasharath Misarilal", "2", " ", "गुजरात", "अहमदाबाद पूर्व", "देवदा दशरथ मिसरीलाल", " "},
        {"Gujarat", "Ahmedabad East", "Shekh Salmabanu Mohamad Salim", "4", " ", "गुजरात", "अहमदाबाद पूर्व", "शेख सालमबनु मोहमद सलीम", " "},
        {"Gujarat", "Ahmedabad East", "Mahesh Prabhudas Ahuja", "2", " ", "गुजरात", "अहमदाबाद पूर्व", "महेश प्रभुदास आहूजा", " "},
        {"Gujarat", "Ahmedabad East", "Jayswal Nareshkumar Babulal", "4", " ", "गुजरात", "अहमदाबाद पूर्व", "जयसवाल नरेशकुमार बाबूलाल", " "},
        {"Gujarat", "Ahmedabad East", "Manoj Premchand Gupta", "4", " ", "गुजरात", "अहमदाबाद पूर्व", "मनोज प्रेमचंद गुप्ता", " "},
        {"Gujarat", "Ahmedabad East", "Vaghela Ganeshbhai Narsinhbhai", "4", " ", "गुजरात", "अहमदाबाद पूर्व", "वाघेला गणेशभाई नरसिंहभाई", " "},
        {"Gujarat", "Ahmedabad West", "Dipika Jitendrakumar Sutaria", "4", " ", "गुजरात", "अहमदाबाद पश्चिम", "दीपिका जितेंद्रकुमार सुतारिया", " "},
        {"Gujarat", "Ahmedabad West", "Dr. Solanki Kiritbhai", "1", " ", "गुजरात", "अहमदाबाद पश्चिम", "डॉ। सोलंकी किरीटभाई", " "},
        {"Gujarat", "Ahmedabad West", "Raju Parmar", "1", " ", "गुजरात", "अहमदाबाद पश्चिम", "राजू परमार", " "},
        {"Gujarat", "Ahmedabad West", "Mahedia Mahendrabhai Parsottamdas", "2", " ", "गुजरात", "अहमदाबाद पश्चिम", "महेदिया महेन्द्रभाई परसोत्तमदास", " "},
        {"Gujarat", "Ahmedabad West", "Tribhovandas Karsandas Vaghela", "3", " ", "गुजरात", "अहमदाबाद पश्चिम", "त्रिभुवनदास करसंडस वाघेला", " "},
        {"Gujarat", "Ahmedabad West", "Bhitora Bhavesh Chimanbhai", "4", " ", "गुजरात", "अहमदाबाद पश्चिम", "भिटोरा भावेश चिमनभाई", " "},
        {"Gujarat", "Ahmedabad West", "Vedubhai Sirasat Kautikbhai", "4", " ", "गुजरात", "अहमदाबाद पश्चिम", "वेदुभाई सिरसाट कौतिकभाई", " "},
        {"Gujarat", "Ahmedabad West", "Harshadkumar Laxmanbhai Solanki", "4", " ", "गुजरात", "अहमदाबाद पश्चिम", "हर्षदकुमार लक्ष्मणभाई सोलंकी", " "},
        {"Gujarat", "Ahmedabad West", "Vaghela Ashwinbhai Amrutbhai", "4", " ", "गुजरात", "अहमदाबाद पश्चिम", "वाघेला अश्विनभाई अमृतभाई", " "},
        {"Gujarat", "Amreli", "Bagda Himmatbhai Danjibhai", "2", " ", "गुजरात", "अमरेली", "बागदा हिम्मतबाई दंजीभाई", " "},
        {"Gujarat", "Amreli", "Dayala Subhashbhai Parbatbhai", "4", " ", "गुजरात", "अमरेली", "दयाला सुभाषभाई परबतभाई", " "},
        {"Gujarat", "Amreli", "Gosai Rasikpragat Samjupragat", "4", " ", "गुजरात", "अमरेली", "गोसाई रसिकप्रगट समुझपतगट", " "},
        {"Gujarat", "Amreli", "Sukhdiya Nathabhai", "2", " ", "गुजरात", "अमरेली", "सुखिया नतभाई", " "},
        {"Gujarat", "Amreli", "Kachhadiya Naranbhai Bhikhabhai", "1", " ", "गुजरात", "अमरेली", "कछदिया नारनभाई भीखाभाई", " "},
        {"Gujarat", "Amreli", "Paresh Dhanani", "1", " ", "गुजरात", "अमरेली", "परेश धनानी", " "},
        {"Gujarat", "Amreli", "Valodara Vrajlal Jivabhai", "3", " ", "गुजरात", "अमरेली", "वलोदरा व्रजलाल जीवाभाई", " "},
        {"Gujarat", "Amreli", "Dhapa Dharamshibhai Ramjibhai", "2", " ", "गुजरात", "अमरेली", "धापा धर्मशीभाई रामजीभाई", " "},
        {"Gujarat", "Amreli", "Chauhan Ravjibhai Mulabhai", "4", " ", "गुजरात", "अमरेली", "चौहान रविजीभाई मूलभाई", " "},
        {"Gujarat", "Amreli", "Chauhan Dayabhai Bhagvanbhai", "4", " ", "गुजरात", "अमरेली", "चौहान दयाभाई भगवानभाई", " "},
        {"Gujarat", "Amreli", "Jerambhai Raghavbhai Parmar", "2", " ", "गुजरात", "अमरेली", "जरामभाई राघवभाई परमार", " "},
        {"Gujarat", "Amreli", "Nanalal Kalidas Maheta", "4", " ", "गुजरात", "अमरेली", "नानालाल कालिदास महेता", " "},
        {"Gujarat", "Anand", "Keyur Pravinbhai Patel", "4", " ", "गुजरात", "आनंद", "केयूर प्रवीणभाई पटेल", " "},
        {"Gujarat", "Anand", "Vankar Rameshbhai Valjibhai", "4", " ", "गुजरात", "आनंद", "वानकर रमेशभाई वलजीभाई", " "},
        {"Gujarat", "Anand", "Miteshbhai Patel", "1", " ", "गुजरात", "आनंद", "मितेशभाई पटेल", " "},
        {"Gujarat", "Anand", "Bharatbhai Chhotabhai Solanki", "4", " ", "गुजरात", "आनंद", "भरतभाई छोटभाई सोलंकी", " "},
        {"Gujarat", "Anand", "Hitendrasinh Parmar", "4", " ", "गुजरात", "आनंद", "हितेन्द्रसिंह परमार", " "},
        {"Gujarat", "Anand", "Bharatbhai Madhavsinh Solanki", "1", " ", "गुजरात", "आनंद", "भरतभाई माधवसिंह सोलंकी", " "},
        {"Gujarat", "Anand", "Santolkumar Patel", "4", " ", "गुजरात", "आनंद", "संतोलकुमार पटेल", " "},
        {"Gujarat", "Anand", "Bhatt Ashishkumar Manojkumar", "4", " ", "गुजरात", "आनंद", "भट्ट आशीषकुमार मनोजकुमार", " "},
        {"Gujarat", "Banaskantha", "Tejabhai Nethibhai Rabari", "2", " ", "गुजरात", "बनासकांठा", "तेजभाई नेतिभाई रबारी", " "},
        {"Gujarat", "Banaskantha", "Charmta Bharatkumar Khemabhai", "2", " ", "गुजरात", "बनासकांठा", "चारित्र भरतकुमार खेमाभाई", " "},
        {"Gujarat", "Banaskantha", "Desai Ishvarbhai", "4", " ", "गुजरात", "बनासकांठा", "देसाई ईश्वरभाई", " "},
        {"Gujarat", "Banaskantha", "Jagdishji Parthiji Dharani", "4", " ", "गुजरात", "बनासकांठा", "जगदीशजी पार्थिजी धरनी", " "},
        {"Gujarat", "Banaskantha", "Thakor Melaji Madarsinh", "4", " ", "गुजरात", "बनासकांठा", "ठाकोर मेलाजी मदरसिंह", " "},
        {"Gujarat", "Banaskantha", "Parmar Chhaganchandraraj Dhanabhai", "4", " ", "गुजरात", "बनासकांठा", "परमार छगनचंद्रराज धनभाई", " "},
        {"Gujarat", "Banaskantha", "Thakor Swarupji Sardarji", "4", " ", "गुजरात", "बनासकांठा", "ठाकोर स्वरूपजी सरदारजी", " "},
        {"Gujarat", "Banaskantha", "Parthibhai Galbabhai Bhatol", "1", " ", "गुजरात", "बनासकांठा", "पार्थीभाई गलबाभाई भटोल", " "},
        {"Gujarat", "Banaskantha", "Padhiyar Bharatkumar Ishvarlal", "4", " ", "गुजरात", "बनासकांठा", "पधियार भरतकुमार ईश्वरलाल", " "},
        {"Gujarat", "Banaskantha", "Parbatbhai Patel", "1", " ", "गुजरात", "बनासकांठा", "परबतभाई पटेल", " "},
        {"Gujarat", "Banaskantha", "Parsani Ibrahimbhai Pirabhai", "4", " ", "गुजरात", "बनासकांठा", "परसानी इब्राहिमभाई पिराबाई", " "},
        {"Gujarat", "Banaskantha", "Dr. Chandraben", "2", " ", "गुजरात", "बनासकांठा", "डॉ। चंद्रबेन", " "},
        {"Gujarat", "Bardoli", "Arvindbhai Bhanabhai Rathod", "4", " ", "गुजरात", "बारडोली", "अरविंदभाई भानभाई राठौड़", " "},
        {"Gujarat", "Bardoli", "Chaudhari Tusharbhai Amarsinhbhai", "1", " ", "गुजरात", "बारडोली", "चौधरी तुषारभाई अमरसिंहभाई", " "},
        {"Gujarat", "Bardoli", "Vasava Uttambhai Somabhai", "2", " ", "गुजरात", "बारडोली", "वसावा उत्तमभाई सोमाभाई", " "},
        {"Gujarat", "Bardoli", "Gamit Mohanbhai Babubhai", "3", " ", "गुजरात", "बारडोली", "गामित मोहनभाई बाबूभाई", " "},
        {"Gujarat", "Bardoli", "Gamit Kaushikbhai Virendrabhai", "4", " ", "गुजरात", "बारडोली", "गामित कौशिकभाई वीरेंद्रभाई", " "},
        {"Gujarat", "Bardoli", "Gamit Sureshbhai Babubhai", "4", " ", "गुजरात", "बारडोली", "गामित सुरेशभाई बाबूभाई", " "},
        {"Gujarat", "Bardoli", "Parbhubhai Nagarbhai Vasava", "1", " ", "गुजरात", "बारडोली", "परभुभाई नगरभाई वसावा", " "},
        {"Gujarat", "Bardoli", "Umedbhai Bhimsingbhai Gamit", "4", " ", "गुजरात", "बारडोली", "उम्मेदभाई भीमसिंगभाई गामित", " "},
        {"Gujarat", "Bardoli", "Vasava Fatesingbhai Vahriyabhai", "4", " ", "गुजरात", "बारडोली", "वसावा फ़तेसिंघभाई वहरियाभाई", " "},
        {"Gujarat", "Bharuch", "Vashi Narendrasinh", "4", " ", "गुजरात", "भरूच", "वाशी नरेंद्रसिंह", " "},
        {"Gujarat", "Bharuch", "Patel Imran", "4", " ", "गुजरात", "भरूच", "पटेल इमरान", " "},
        {"Gujarat", "Bharuch", "Parmar Ashokchandra", "4", " ", "गुजरात", "भरूच", "परमार अशोकचंद्र", " "},
        {"Gujarat", "Bharuch", "Sukhdev Vasava", "4", " ", "गुजरात", "भरूच", "सुखदेव वसावा", " "},
        {"Gujarat", "Bharuch", "Sabbirbhai Patel", "4", " ", "गुजरात", "भरूच", "सब्बीरभाई पटेल", " "},
        {"Gujarat", "Bharuch", "Rajeshbhai Solanki", "4", " ", "गुजरात", "भरूच", "राजेशभाई सोलंकी", " "},
        {"Gujarat", "Bharuch", "Vasava Navinbhai", "4", " ", "गुजरात", "भरूच", "वसावा नवीनभाई", " "},
        {"Gujarat", "Bharuch", "Pathan Salimkhan", "4", " ", "गुजरात", "भरूच", "पठान सलीमखान", " "},
        {"Gujarat", "Bharuch", "Mukhtiyar Shaikh", "4", " ", "गुजरात", "भरूच", "मुख्तियार शेख", " "},
        {"Gujarat", "Bharuch", "Chhotubhai Vasava", "2", " ", "गुजरात", "भरूच", "छोटूभाई वसावा", " "},
        {"Gujarat", "Bharuch", "Rafikbhai Sapa", "2", " ", "गुजरात", "भरूच", "रफीकभाई सपा", " "},
        {"Gujarat", "Bharuch", "Sherkhan Pathan", "1", " ", "गुजरात", "भरूच", "शेरखान पठान", " "},
        {"Gujarat", "Bharuch", "Vasava Rajeshbhai", "4", " ", "गुजरात", "भरूच", "वसावा राजेशभाई", " "},
        {"Gujarat", "Bharuch", "Mansukhbhai Vasava", "1", " ", "गुजरात", "भरूच", "मनसुखभाई वसावा", " "},
        {"Gujarat", "Bharuch", "Vikramsinh Gohil", "4", " ", "गुजरात", "भरूच", "विक्रमसिंह गोहिल", " "},
        {"Gujarat", "Bharuch", "Sindha Kiritsinh", "4", " ", "गुजरात", "भरूच", "सिंध किरिटसिंह", " "},
        {"Gujarat", "Bhavnagar", "Chauhan Ajaykumar Ramratansinh", "2", " ", "गुजरात", "भावनगर", "चौहान अजयकुमार रामरतनसिंह", " "},
        {"Gujarat", "Bhavnagar", "Zala Ramdevsinh Bharatsinh", "4", " ", "गुजरात", "भावनगर", "ज़ला रामदेवसिंह भरतसिंह", " "},
        {"Gujarat", "Bhavnagar", "Hareshbhai Babubhai Vegad", "2", " ", "गुजरात", "भावनगर", "हरेशभाई बाबूभाई वेगड़", " "},
        {"Gujarat", "Bhavnagar", "Dhapa Dharamshibhai Ramjibhai", "2", " ", "गुजरात", "भावनगर", "धापा धर्मशीभाई रामजीभाई", " "},
        {"Gujarat", "Bhavnagar", "Sondarva Bharatbhai Kanjibhai", "4", " ", "गुजरात", "भावनगर", "सोंदरवा भरतभाई कंजीभाई", " "},
        {"Gujarat", "Bhavnagar", "Manharbhai Nagjibhai Patel", "1", " ", "गुजरात", "भावनगर", "मनहरभाई नागजीभाई पटेल", " "},
        {"Gujarat", "Bhavnagar", "Dr.Bharatiben Dhirubhai Shiyal", "1", " ", "गुजरात", "भावनगर", "डॉ.भारतीबेन धीरूभाई शियाल", " "},
        {"Gujarat", "Bhavnagar", "Sitapara Sagarbhai Bhurabhai", "4", " ", "गुजरात", "भावनगर", "सीतापारा सागरभाई भुरभाई", " "},
        {"Gujarat", "Chhota Udaipur", "Pravinbhai Dhursingbhai Rathava", "4", " ", "गुजरात", "छोटा उदयपुर", "प्रवीणभाई ढेसिंगभाई राठवा", " "},
        {"Gujarat", "Chhota Udaipur", "Rathva Gitaben Vajesingbhai", "1", " ", "गुजरात", "छोटा उदयपुर", "रथ्वा गीताबेन वजेसिंगभाई", " "},
        {"Gujarat", "Chhota Udaipur", "Rathava Ranjitsinh Mohansinh", "1", " ", "गुजरात", "छोटा उदयपुर", "रथवा रंजीतसिंह मोहनसिंह", " "},
        {"Gujarat", "Chhota Udaipur", "Rathava Furkanbhai Baljibhai", "4", " ", "गुजरात", "छोटा उदयपुर", "रथवा फुरकानभाई बलजीभाई", " "},
        {"Gujarat", "Chhota Udaipur", "Rathva Maganbhai Chathiyabhai", "4", " ", "गुजरात", "छोटा उदयपुर", "रथवा मगनभाई चठियाभाई", " "},
        {"Gujarat", "Chhota Udaipur", "Rathva Bhavsingbhai Namarsingbhai", "2", " ", "गुजरात", "छोटा उदयपुर", "रथवा भवसिंघभय नमरसिंघै", " "},
        {"Gujarat", "Dahod", "Kalara Ramsingbhai Nanjibhai", "4", " ", "गुजरात", "दाहोद", "कलरा रामसिंगभाई नंजिभाई", " "},
        {"Gujarat", "Dahod", "Bhabhor Dhulabhai Ditabhai", "4", " ", "गुजरात", "दाहोद", "भभोर धूलभाई दिताभाई", " "},
        {"Gujarat", "Dahod", "Damor Manabhai Bhavsing", "4", " ", "गुजरात", "दाहोद", "डामोर मनभाई भावसिंह", " "},
        {"Gujarat", "Dahod", "Katara Babubhai Khimabhai", "1", " ", "गुजरात", "दाहोद", "कटारा बाबूभाई खिमभाई", " "},
        {"Gujarat", "Dahod", "Jasvantsinh Sumanbhai Bhabhor", "1", " ", "गुजरात", "दाहोद", "जसवंतसिंह सुमनभाई भाभोर", " "},
        {"Gujarat", "Dahod", "Jagdishbhai Manilal Meda", "4", " ", "गुजरात", "दाहोद", "जगदीशभाई मणिलाल मेधा", " "},
        {"Gujarat", "Gandhinagar", "Naranbhai Tulsidas Sengal", "4", " ", "गुजरात", "गांधीनगर", "नारनभाई तुलसीदास सेंगल", " "},
        {"Gujarat", "Gandhinagar", "Makwana Anilkumar Somabhai", "4", " ", "गुजरात", "गांधीनगर", "मकवाना अनिलकुमार सोमभाई", " "},
        {"Gujarat", "Gandhinagar", "Mahendrabhai Somabhai Patni", "4", " ", "गुजरात", "गांधीनगर", "महेंद्रभाई सोमाभाई पाटनी", " "},
        {"Gujarat", "Gandhinagar", "Amit Shah", "1", " ", "गुजरात", "गांधीनगर", "अमित शाह", " "},
        {"Gujarat", "Gandhinagar", "Narendrabhai Revashanker Trivedi", "3", " ", "गुजरात", "गांधीनगर", "नरेंद्रभाई रेवाशंकर त्रिवेदी", " "},
        {"Gujarat", "Gandhinagar", "Chandrapal Hasmukh Bavjibhai", "4", " ", "गुजरात", "गांधीनगर", "चंद्रपाल हसमुख बावजीभाई", " "},
        {"Gujarat", "Gandhinagar", "Shekh Shahinbanu Molana Mustak", "4", " ", "गुजरात", "गांधीनगर", "शेख शाहीननु मोलाना मुस्तक", " "},
        {"Gujarat", "Gandhinagar", "Chavda Chatursinh Javanji", "1", " ", "गुजरात", "गांधीनगर", "चावड़ा चतुरसिंह जवानीजी", " "},
        {"Gujarat", "Gandhinagar", "Patel Amarish Jasvantlal", "3", " ", "गुजरात", "गांधीनगर", "पटेल अमरिश जसवंतलाल", " "},
        {"Gujarat", "Gandhinagar", "Vora Alimahmad Rajabhai", "3", " ", "गुजरात", "गांधीनगर", "वोरा अलीमहद राजभाई", " "},
        {"Gujarat", "Gandhinagar", "Makwana Prakashbhai Bahecharji", "2", " ", "गुजरात", "गांधीनगर", "मकवाना प्रकाशभाई बहेचरजी", " "},
        {"Gujarat", "Gandhinagar", "Rathod Valjibhai Becharbhai", "2", " ", "गुजरात", "गांधीनगर", "राठौड़ वलजीभाई बेचारभाई", " "},
        {"Gujarat", "Gandhinagar", "Khodabhai Lalajibhai Desai", "2", " ", "गुजरात", "गांधीनगर", "खोदाभाई लालजीभाई देसाई", " "},
        {"Gujarat", "Gandhinagar", "Pathan Firozkhan", "4", " ", "गुजरात", "गांधीनगर", "पठान फिरोजखान", " "},
        {"Gujarat", "Jamnagar", "Aamin Mamadbhai Safiya", "4", " ", "गुजरात", "जामनगर", "आमीन ममदभाई सफिया", " "},
        {"Gujarat", "Jamnagar", "Amandbhai", "3", " ", "गुजरात", "जामनगर", "Amandbhai", " "},
        {"Gujarat", "Jamnagar", "Chavada Ashok", "4", " ", "गुजरात", "जामनगर", "चावड़ा अशोक", " "},
        {"Gujarat", "Jamnagar", "Chauhan Dhiraj Kantilal", "2", " ", "गुजरात", "जामनगर", "चौहान धीरज कांतिलाल", " "},
        {"Gujarat", "Jamnagar", "Sumbhania Aamin", "4", " ", "गुजरात", "जामनगर", "सुंभानिया आमीन", " "},
        {"Gujarat", "Jamnagar", "Donga Jayantilal Arjanbhai", "4", " ", "गुजरात", "जामनगर", "डोंगा जयंतीलाल अर्जनभाई", " "},
        {"Gujarat", "Jamnagar", "Vallabhbhai Chanabhai Sojitra", "4", " ", "गुजरात", "जामनगर", "वल्लभभाई चनाभाई सोजित्रा", " "},
        {"Gujarat", "Jamnagar", "Kandoriya Mulubhai Ranmalbhai", "1", " ", "गुजरात", "जामनगर", "कंदोरिया मुलुभाई रणमलभाई", " "},
        {"Gujarat", "Jamnagar", "Jadeja Bhavnaba", "4", " ", "गुजरात", "जामनगर", "जडेजा भावनबा", " "},
        {"Gujarat", "Jamnagar", "Makrani Ajazahmed", "4", " ", "गुजरात", "जामनगर", "मकरानी अजाजहम्मद", " "},
        {"Gujarat", "Jamnagar", "Bharat Ramjibhai Dagara", "4", " ", "गुजरात", "जामनगर", "भरत रामजीभाई डगरा", " "},
        {"Gujarat", "Jamnagar", "Chavada Shamjibhai", "4", " ", "गुजरात", "जामनगर", "चावड़ा शामजीभाई", " "},
        {"Gujarat", "Jamnagar", "Sapariya Vijaykumar Mansukhbhai", "4", " ", "गुजरात", "जामनगर", "सपरिया विजयकुमार मनसुखभाई", " "},
        {"Gujarat", "Jamnagar", "Alimamad Palani", "4", " ", "गुजरात", "जामनगर", "अलीमद पलानी", " "},
        {"Gujarat", "Jamnagar", "Popatputra Rafik Abubakar", "4", " ", "गुजरात", "जामनगर", "पोपटपुत्र रफिक अबूबकर", " "},
        {"Gujarat", "Jamnagar", "Bharkhani Karabhai Jivabhai", "4", " ", "गुजरात", "जामनगर", "भरखनी करभाई जीवाभाई", " "},
        {"Gujarat", "Jamnagar", "Dalvadi Nakum Rasik Lalji", "4", " ", "गुजरात", "जामनगर", "दलवडी नाकुम रसिक लालजी", " "},
        {"Gujarat", "Jamnagar", "Poonamben Hematbhai Maadam", "1", " ", "गुजरात", "जामनगर", "पूनमबेन हेमतभाई मादम", " "},
        {"Gujarat", "Jamnagar", "Rabari Karshanbhai Jeshabhai", "4", " ", "गुजरात", "जामनगर", "रबारी कर्षभाई जेसभाई", " "},
        {"Gujarat", "Jamnagar", "Bathvar Nanji Amarshi", "4", " ", "गुजरात", "जामनगर", "बथवार नानजी अमरशी", " "},
        {"Gujarat", "Jamnagar", "Sahdevsinh Chudasama", "2", " ", "गुजरात", "जामनगर", "सहदेवसिंह चुडासमा", " "},
        {"Gujarat", "Jamnagar", "Nakum Narmadaben Khodalal", "4", " ", "गुजरात", "जामनगर", "नाकुम नर्मदाबेन खोडलाल", " "},
        {"Gujarat", "Jamnagar", "Bhanderi Amarshibhai Chhaganbhai", "4", " ", "गुजरात", "जामनगर", "भंडारी अमरसिभाई छगनभाई", " "},
        {"Gujarat", "Jamnagar", "Sama Yusuf", "2", " ", "गुजरात", "जामनगर", "साम युसूफ", " "},
        {"Gujarat", "Jamnagar", "Kachchhi Daudbhai Nathabhai", "4", " ", "गुजरात", "जामनगर", "कच्छी दाउदभाई नतभाई", " "},
        {"Gujarat", "Junagadh", "Vansh Punjabhai Bhimabhai", "1", " ", "गुजरात", "जूनागढ़", "वंश पंजाबी भीमभाई", " "},
        {"Gujarat", "Junagadh", "Chudasama Rajeshbhai Naranbhai", "1", " ", "गुजरात", "जूनागढ़", "चुडासमा राजेशभाई नारनभाई", " "},
        {"Gujarat", "Junagadh", "Panchabhai Bhayabhai Damaniya", "4", " ", "गुजरात", "जूनागढ़", "पंचभाई भयभाई दमानिया", " "},
        {"Gujarat", "Junagadh", "Deven Govindbhai Vanvi", "4", " ", "गुजरात", "जूनागढ़", "देवेन गोविंदभाई वनवी", " "},
        {"Gujarat", "Junagadh", "Rathod Nathabhai Vasharambhai", "3", " ", "गुजरात", "जूनागढ़", "राठौड़ नाथाभाई वाशरामभाई", " "},
        {"Gujarat", "Junagadh", "Zala Mukeshbhai Bharmalbhai", "2", " ", "गुजरात", "जूनागढ़", "ज़ला मुकेशभाई भारमलभाई", " "},
        {"Gujarat", "Junagadh", "Bhut Ashokbhai Bhimjibhai", "3", " ", "गुजरात", "जूनागढ़", "भुत अशोकभाई भीमजीभाई", " "},
        {"Gujarat", "Junagadh", "Pradipbhai Mavjibhai Tank", "4", " ", "गुजरात", "जूनागढ़", "प्रदीपभाई मावजीभाई टैंक", " "},
        {"Gujarat", "Junagadh", "Karia Dhirenbhai Amrutlal", "2", " ", "गुजरात", "जूनागढ़", "करिया धीरेनभाई अमृतलाल", " "},
        {"Gujarat", "Kachchh", "Chavda Pravinbhai Chanabhai", "4", " ", "गुजरात", "कच्छ", "चावड़ा प्रवीणभाई चनाभाई", " "},
        {"Gujarat", "Kachchh", "Dhirubhai Babulal Shrimali", "4", " ", "गुजरात", "कच्छ", "धीरूभाई बाबूलाल श्रीमाली", " "},
        {"Gujarat", "Kachchh", "Maheshwari Devjibhai Vachhiyabhai", "2", " ", "गुजरात", "कच्छ", "महेश्वरी देवजीभाई वाछियाभाई", " "},
        {"Gujarat", "Kachchh", "Naresh Naranbhai Maheshwari", "1", " ", "गुजरात", "कच्छ", "नरेश नरनभाई माहेश्वरी", " "},
        {"Gujarat", "Kachchh", "Maru Manisha Bharat", "4", " ", "गुजरात", "कच्छ", "मारु मनीषा भरत", " "},
        {"Gujarat", "Kachchh", "Meghval Bhimjibhai Bhikhabhai", "4", " ", "गुजरात", "कच्छ", "मेघवाल भीमजीभाई भीखाभाई", " "},
        {"Gujarat", "Kachchh", "Chavda Vinod Lakhamshi", "1", " ", "गुजरात", "कच्छ", "चावड़ा विनोद लखमशी", " "},
        {"Gujarat", "Kachchh", "Sondarva Baluben Maheshbhai", "4", " ", "गुजरात", "कच्छ", "सोंदरवा बलुबेन महेशभाई", " "},
        {"Gujarat", "Kachchh", "Lakhubhai Vaghela", "4", " ", "गुजरात", "कच्छ", "लखुभाई वाघेला", " "},
        {"Gujarat", "Kachchh", "Babulal Amarshi Vaghela", "4", " ", "गुजरात", "कच्छ", "बाबूलाल अमरशी वाघेला", " "},
        {"Gujarat", "Kheda", "Chauhan Devusinh", "1", " ", "गुजरात", "खेड़ा", "चौहान देवूसिंह", " "},
        {"Gujarat", "Kheda", "Pathan Imtiyazkhan", "4", " ", "गुजरात", "खेड़ा", "पठान इम्तियाजखान", " "},
        {"Gujarat", "Kheda", "Bhailalbhai Pandav", "4", " ", "गुजरात", "खेड़ा", "भिलालभाई पांडव", " "},
        {"Gujarat", "Kheda", "Bimalbhai Shah", "1", " ", "गुजरात", "खेड़ा", "बिमलभाई शाह", " "},
        {"Gujarat", "Kheda", "Patel Kamleshkumar", "4", " ", "गुजरात", "खेड़ा", "पटेल कमलेशकुमार", " "},
        {"Gujarat", "Kheda", "Pathan Aayashabanu", "4", " ", "गुजरात", "खेड़ा", "पठान आयशाबनु", " "},
        {"Gujarat", "Kheda", "Chauhan Parsottambhai", "4", " ", "गुजरात", "खेड़ा", "चौहान परसोत्तमभाई", " "},
        {"Gujarat", "Mahesana", "Thakor Mayurkumar Rupsangji", "4", " ", "गुजरात", "महेसाणा", "ठाकोर मयूरकुमार रूपसंगजी", " "},
        {"Gujarat", "Mahesana", "Patel Anitaben Ramabhai", "4", " ", "गुजरात", "महेसाणा", "पटेल अनिताबेन रामभाई", " "},
        {"Gujarat", "Mahesana", "Chauhan Prahladbhai", "3", " ", "गुजरात", "महेसाणा", "चौहान प्रह्लादभाई", " "},
        {"Gujarat", "Mahesana", "Prajapati Kanubhai Amatharam", "4", " ", "गुजरात", "महेसाणा", "प्रजापति कनुभाई अमथाराम", " "},
        {"Gujarat", "Mahesana", "Thakor Jayantiji Chunthaji", "4", " ", "गुजरात", "महेसाणा", "ठाकोर जयन्तीजी चूँथजी", " "},
        {"Gujarat", "Mahesana", "Patel Ambalal Talashibhai", "3", " ", "गुजरात", "महेसाणा", "पटेल अंबालाल तलाशीभाई", " "},
        {"Gujarat", "Mahesana", "Rathod Gulabsinh Dursinh", "4", " ", "गुजरात", "महेसाणा", "राठौड़ गुलाबसिंह दुरसिंह", " "},
        {"Gujarat", "Mahesana", "Shardaben Anilbhai Patel", "1", " ", "गुजरात", "महेसाणा", "शारदाबेन अनिलभाई पटेल", " "},
        {"Gujarat", "Mahesana", "A. J. Patel", "1", " ", "गुजरात", "महेसाणा", "एजे पटेल", " "},
        {"Gujarat", "Mahesana", "Thakor Bipinkumar Shankarji", "4", " ", "गुजरात", "महेसाणा", "ठाकोर बिपिनकुमार शंकरजी", " "},
        {"Gujarat", "Navsari", "Chauhan Nileshkumar Khushalbhai", "2", " ", "गुजरात", "नवसारी", "चौहान निलेशकुमार खुशालभाई", " "},
        {"Gujarat", "Navsari", "Ramjan Bhilubhai Mansuri", "4", " ", "गुजरात", "नवसारी", "रमजान भिलुभाई मंसूरी", " "},
        {"Gujarat", "Navsari", "Prakash Amarnath Shukla", "4", " ", "गुजरात", "नवसारी", "प्रकाश अमरनाथ शुक्ल", " "},
        {"Gujarat", "Navsari", "Saiyad Mehmud Ahmad", "4", " ", "गुजरात", "नवसारी", "सय्यद महमूद अहमद", " "},
        {"Gujarat", "Navsari", "Sohilkhaa Hashimkhaa Pathan", "4", " ", "गुजरात", "नवसारी", "सोहिलखा हाशिमखां पठान", " "},
        {"Gujarat", "Navsari", "Jawadkhan Sujatkhan Pathan", "4", " ", "गुजरात", "नवसारी", "जवदखन सुजातन पठान", " "},
        {"Gujarat", "Navsari", "Patel Dharmeshbhai", "1", " ", "गुजरात", "नवसारी", "पटेल धर्मेशभाई", " "},
        {"Gujarat", "Navsari", "Shaikh Javeed Ahemad", "2", " ", "गुजरात", "नवसारी", "शेख जावेद अहमद", " "},
        {"Gujarat", "Navsari", "Amrutham Narsaiya", "4", " ", "गुजरात", "नवसारी", "अमृतम नरसैया", " "},
        {"Gujarat", "Navsari", "Chandansinh", "4", " ", "गुजरात", "नवसारी", "Chandansinh", " "},
        {"Gujarat", "Navsari", "Hiramaniben", "4", " ", "गुजरात", "नवसारी", "Hiramaniben", " "},
        {"Gujarat", "Navsari", "Shekh Hamid Ramjan", "2", " ", "गुजरात", "नवसारी", "शेख हामिद रमजान", " "},
        {"Gujarat", "Navsari", "Sachin Kinra", "4", " ", "गुजरात", "नवसारी", "सचिन किनरा", " "},
        {"Gujarat", "Navsari", "Pasvan Virendra", "4", " ", "गुजरात", "नवसारी", "पासवान वीरेंद्र", " "},
        {"Gujarat", "Navsari", "Govindbhai Laxmanbhai Rathod", "4", " ", "गुजरात", "नवसारी", "गोविंदभाई लक्ष्मणभाई राठौड़", " "},
        {"Gujarat", "Navsari", "Anishbhai Gaffarbhai Bhimani", "4", " ", "गुजरात", "नवसारी", "अनिशभाई गफ्फारभाई भीमनी", " "},
        {"Gujarat", "Navsari", "Patil Chandrakant", "1", " ", "गुजरात", "नवसारी", "पाटिल चंद्रकांत", " "},
        {"Gujarat", "Navsari", "Shaikh Saeed Inayat", "4", " ", "गुजरात", "नवसारी", "शेख सईद इनायत", " "},
        {"Gujarat", "Navsari", "Sharma Rajmal Mohanlal", "4", " ", "गुजरात", "नवसारी", "शर्मा राजमल मोहनलाल", " "},
        {"Gujarat", "Panchmahal", "Patel Virendrakumar", "2", " ", "गुजरात", "पंचमहल", "पटेल वीरेंद्रकुमार", " "},
        {"Gujarat", "Panchmahal", "Vechatbhai Khant", "1", " ", "गुजरात", "पंचमहल", "वीचभाई खांट", " "},
        {"Gujarat", "Panchmahal", "Lalabhai Gadhavi", "2", " ", "गुजरात", "पंचमहल", "लालभाई गढ़वी", " "},
        {"Gujarat", "Panchmahal", "Ratansinh Rathod", "1", " ", "गुजरात", "पंचमहल", "रतनसिंह राठौड़", " "},
        {"Gujarat", "Panchmahal", "Shaikh Kalim", "4", " ", "गुजरात", "पंचमहल", "शेख कलीम", " "},
        {"Gujarat", "Patan", "Bhoraniya Soyabbhai Hasambhai", "2", " ", "गुजरात", "पाटन", "भोरान्य सोयाभाई हसाम्भाई", " "},
        {"Gujarat", "Patan", "Prajapati Jayantibhai Devabhai", "4", " ", "गुजरात", "पाटन", "प्रजापति जयंतीभाई देवभाई", " "},
        {"Gujarat", "Patan", "Umedbhai Haribhai Nai", "4", " ", "गुजरात", "पाटन", "उम्मेदभाई हरिभाई नाई", " "},
        {"Gujarat", "Patan", "Makwana Vaghabhai Maganbhai", "4", " ", "गुजरात", "पाटन", "मकवाना वगभाई मगनभाई", " "},
        {"Gujarat", "Patan", "Abdulkudus Abdulmajid Molapiya", "4", " ", "गुजरात", "पाटन", "अब्दुलकुद्दुस अब्दुलमाजिद मोलापिया", " "},
        {"Gujarat", "Patan", "Pandya Pravinkumar Tulsidas", "4", " ", "गुजरात", "पाटन", "पंड्या प्रवीणकुमार तुलसीदास", " "},
        {"Gujarat", "Patan", "Chaudhari Shaileshkumar Kanjibhai", "4", " ", "गुजरात", "पाटन", "चौधरी शैलेशकुमार कांजीभाई", " "},
        {"Gujarat", "Patan", "Thakor Jagdishbhai", "1", " ", "गुजरात", "पाटन", "ठाकोर जगदीशभाई", " "},
        {"Gujarat", "Patan", "Dabhi Bharatsinhji Shankarji", "1", " ", "गुजरात", "पाटन", "डाभी भरतसिंहजी शंकरजी", " "},
        {"Gujarat", "Patan", "Rathod Govindbhai Bhikhabhai", "4", " ", "गुजरात", "पाटन", "राठौड़ गोविंदभाई भीखाभाई", " "},
        {"Gujarat", "Porbandar", "Rabari Dasabhai Karabhai", "2", " ", "गुजरात", "पोरबंदर", "रबारी दसभाई करभाई", " "},
        {"Gujarat", "Porbandar", "Bhargav Joshi", "4", " ", "गुजरात", "पोरबंदर", "भार्गव जोशी", " "},
        {"Gujarat", "Porbandar", "Rameshbhai Dhaduk", "1", " ", "गुजरात", "पोरबंदर", "रमेशभाई धाडुक", " "},
        {"Gujarat", "Porbandar", "Riyaz Suriya", "2", " ", "गुजरात", "पोरबंदर", "रियाज सूरिया", " "},
        {"Gujarat", "Porbandar", "Rank Jigneshbhai", "4", " ", "गुजरात", "पोरबंदर", "रैंक जिग्नेशभाई", " "},
        {"Gujarat", "Porbandar", "Rathod Dayabhai", "4", " ", "गुजरात", "पोरबंदर", "राठौड़ दयाभाई", " "},
        {"Gujarat", "Porbandar", "Kadavala Samatbha", "4", " ", "गुजरात", "पोरबंदर", "कदवला समताभा", " "},
        {"Gujarat", "Porbandar", "Reshma Patel", "4", " ", "गुजरात", "पोरबंदर", "रेशमा पटेल", " "},
        {"Gujarat", "Porbandar", "Ramani Vimalbhai", "4", " ", "गुजरात", "पोरबंदर", "रमणी विमलभाई", " "},
        {"Gujarat", "Porbandar", "Lalit Vasoya", "1", " ", "गुजरात", "पोरबंदर", "ललित वसोया", " "},
        {"Gujarat", "Porbandar", "Aantroliya Karabhai", "4", " ", "गुजरात", "पोरबंदर", "आंत्रोलिया करभाई", " "},
        {"Gujarat", "Porbandar", "Unadkat Prakashbha", "4", " ", "गुजरात", "पोरबंदर", "उनादकट प्रकाशभा", " "},
        {"Gujarat", "Porbandar", "Kirtikumar Marvaniya", "4", " ", "गुजरात", "पोरबंदर", "कीर्तिकुमार मारवानिया", " "},
        {"Gujarat", "Rajkot", "Chauhan Manojbhai", "4", " ", "गुजरात", "राजकोट", "चौहान मनोजभाई", " "},
        {"Gujarat", "Rajkot", "Dengada Pravinbhai", "2", " ", "गुजरात", "राजकोट", "डेंगडा प्रवीणभाई", " "},
        {"Gujarat", "Rajkot", "Amardas Desani", "2", " ", "गुजरात", "राजकोट", "अमरदास देसानी", " "},
        {"Gujarat", "Rajkot", "Jaspalsinh Tomar", "4", " ", "गुजरात", "राजकोट", "जसपालसिंह तोमर", " "},
        {"Gujarat", "Rajkot", "Parmar Vijay", "2", " ", "गुजरात", "राजकोट", "परमार विजय", " "},
        {"Gujarat", "Rajkot", "Rakeshbhai", "4", " ", "गुजरात", "राजकोट", "Rakeshbhai", " "},
        {"Gujarat", "Rajkot", "J. B. Chauhan", "4", " ", "गुजरात", "राजकोट", "जेबी चौहान", " "},
        {"Gujarat", "Rajkot", "Kundaria Mohanbhai", "1", " ", "गुजरात", "राजकोट", "कुंदरिया मोहनभाई", " "},
        {"Gujarat", "Rajkot", "Kagathara Lalitbhai", "1", " ", "गुजरात", "राजकोट", "कगथरा ललिताभाई", " "},
        {"Gujarat", "Sabarkantha", "Jadeja Indravijaysinh", "4", " ", "गुजरात", "साबरकांठा", "जडेजा इंद्रविजयसिंह", " "},
        {"Gujarat", "Sabarkantha", "Luhar Hafizhusen", "4", " ", "गुजरात", "साबरकांठा", "लुहार हफीज़ुसेन", " "},
        {"Gujarat", "Sabarkantha", "Mayursinh Vanrajsinh Zala", "4", " ", "गुजरात", "साबरकांठा", "मयूरसिंह वनराजसिंह जाला", " "},
        {"Gujarat", "Sabarkantha", "Pathan Aiyubkhan Ajabakhan", "4", " ", "गुजरात", "साबरकांठा", "पठान अयूबखान अजबखान", " "},
        {"Gujarat", "Sabarkantha", "Laxmishankar Madhusudan Joshi", "3", " ", "गुजरात", "साबरकांठा", "लक्ष्मीशंकर मधुसूदन जोशी", " "},
        {"Gujarat", "Sabarkantha", "Lata Babubhai Nathaji", "4", " ", "गुजरात", "साबरकांठा", "लता बाबूभाई नाथजी", " "},
        {"Gujarat", "Sabarkantha", "Sanghani Mustakbhai Jamalbhai", "2", " ", "गुजरात", "साबरकांठा", "संघानी मुस्तकभाई जमालभाई", " "},
        {"Gujarat", "Sabarkantha", "Solanki Maganbhai Lakhabhai", "2", " ", "गुजरात", "साबरकांठा", "सोलंकी मगनभाई लखभाई", " "},
        {"Gujarat", "Sabarkantha", "Raval Rajubhai Punjabhai", "4", " ", "गुजरात", "साबरकांठा", "रावल राजुभाई पंजाबी", " "},
        {"Gujarat", "Sabarkantha", "Thakor Rajendrasinh", "1", " ", "गुजरात", "साबरकांठा", "ठाकोर राजेंद्रसिंह", " "},
        {"Gujarat", "Sabarkantha", "Patel Keshavlal Gangarambhai", "4", " ", "गुजरात", "साबरकांठा", "पटेल केशवलाल गंगारामभाई", " "},
        {"Gujarat", "Sabarkantha", "Zala Dalpatsinh Motisinh", "4", " ", "गुजरात", "साबरकांठा", "ज़ला दलपतसिंह मोतीसिंह", " "},
        {"Gujarat", "Sabarkantha", "Nareshkumar Rameshbhai Patel", "4", " ", "गुजरात", "साबरकांठा", "नरेशकुमार रमेशभाई पटेल", " "},
        {"Gujarat", "Sabarkantha", "Rathod Dipsinh Shankarsinh", "1", " ", "गुजरात", "साबरकांठा", "राठौड़ दिपसिंह शंकरसिंह", " "},
        {"Gujarat", "Sabarkantha", "Vikrambhai Bahecharbhai Makwana", "4", " ", "गुजरात", "साबरकांठा", "विक्रमभाई बहेचरभाई मकवाना", " "},
        {"Gujarat", "Surat", "Gautamraj G. Hindustani", "4", " ", "गुजरात", "सूरत", "गौतमराज जी। हिंदुस्तानी", " "},
        {"Gujarat", "Surat", "Tulasibhai Laxmanbhai Dakhara", "4", " ", "गुजरात", "सूरत", "तुलसीभाई लक्ष्मणभाई डखारा", " "},
        {"Gujarat", "Surat", "Dineshbhai Chaturbhai Jikadara", "4", " ", "गुजरात", "सूरत", "दिनेशभाई चतुर्भाई जिकदारा", " "},
        {"Gujarat", "Surat", "Baraiya Rameshbhai Parsottambhai", "4", " ", "गुजरात", "सूरत", "बरैया रमेशभाई परसोत्तमभाई", " "},
        {"Gujarat", "Surat", "Surwade Santosh Avdhut", "4", " ", "गुजरात", "सूरत", "सुरवडे संतोष अवधूत", " "},
        {"Gujarat", "Surat", "Dipakbhai Ramnikbhai Gangani", "4", " ", "गुजरात", "सूरत", "दिपकभाई रमणिकभाई गंगानी", " "},
        {"Gujarat", "Surat", "Jardosh Darshnaben Vikrambhai", "1", " ", "गुजरात", "सूरत", "जरदोष दर्शनाबेन विक्रमभाई", " "},
        {"Gujarat", "Surat", "Dhameliya Piyushkumar Vallabhabhai", "4", " ", "गुजरात", "सूरत", "धमालिया पीयूषकुमार वल्लभभाई", " "},
        {"Gujarat", "Surat", "Ashok Vallabhbhai Pate", "1", " ", "गुजरात", "सूरत", "अशोक वल्लभभाई पाटे", " "},
        {"Gujarat", "Surendranagar", "Mahendrabhai Munjpara", "1", " ", "गुजरात", "सुरेंद्रनगर", "महेंद्रभाई मुंजपारा", " "},
        {"Gujarat", "Surendranagar", "Hanifbhai Kayabhai Katiya", "4", " ", "गुजरात", "सुरेंद्रनगर", "हनीफ़भाई कयाभाई कटिया", " "},
        {"Gujarat", "Surendranagar", "Bhupatbhai Laljibhai Solanki", "2", " ", "गुजरात", "सुरेंद्रनगर", "भूपतभाई लालजीभाई सोलंकी", " "},
        {"Gujarat", "Surendranagar", "Sardarkhan Malek", "4", " ", "गुजरात", "सुरेंद्रनगर", "सरदारखान मालेक", " "},
        {"Gujarat", "Surendranagar", "Goltar Bhagvanbhai Maiyabhai", "2", " ", "गुजरात", "सुरेंद्रनगर", "गोलतर भगवानभाई मैयाभाई", " "},
        {"Gujarat", "Surendranagar", "Oghadbhai Mer", "4", " ", "गुजरात", "सुरेंद्रनगर", "औघड़भाई मेर", " "},
        {"Gujarat", "Surendranagar", "Bhanjibhai Shekhava", "4", " ", "गुजरात", "सुरेंद्रनगर", "भनजीभाई शेखवा", " "},
        {"Gujarat", "Surendranagar", "Bhathaniya Faridbhai Amijibhai", "4", " ", "गुजरात", "सुरेंद्रनगर", "भथानिया फरीदभाई अमीजीभाई", " "},
        {"Gujarat", "Surendranagar", "Thakor Jaguji Kuvarji", "4", " ", "गुजरात", "सुरेंद्रनगर", "ठाकोर जगुजी कुवरजी", " "},
        {"Gujarat", "Surendranagar", "Kolipatel Somabhai", "1", " ", "गुजरात", "सुरेंद्रनगर", "कोलीपटेल सोमाभाई", " "},
        {"Gujarat", "Surendranagar", "Karimbhai Adambhai Urfe Bababhai", "3", " ", "गुजरात", "सुरेंद्रनगर", "करमभाई अधमभाई उर्फ़ बाबाभाई", " "},
        {"Gujarat", "Surendranagar", "Vaghela Dahyabhai Khengarbhai", "4", " ", "गुजरात", "सुरेंद्रनगर", "वाघेला भयभाई खंगारभाई", " "},
        {"Gujarat", "Surendranagar", "Makwana Dalpatbhai Lagharbhai", "3", " ", "गुजरात", "सुरेंद्रनगर", "मकवाना दलपतभाई लगरभाई", " "},
        {"Gujarat", "Surendranagar", "Makvana Kamabhai", "3", " ", "गुजरात", "सुरेंद्रनगर", "मकवाना कामाभाई", " "},
        {"Gujarat", "Surendranagar", "Daniya Anirudhbhai Gandabhai", "4", " ", "गुजरात", "सुरेंद्रनगर", "दानिया अनिरुद्धभाई गंडभाई", " "},
        {"Gujarat", "Surendranagar", "Dekavadiya Darjibhai Maganbhai", "4", " ", "गुजरात", "सुरेंद्रनगर", "देवकादिया दर्जीभाई मगनभाई", " "},
        {"Gujarat", "Surendranagar", "Rathod Ashokbhai Vithathalbhai", "4", " ", "गुजरात", "सुरेंद्रनगर", "राठौड़ अशोकभाई विठ्ठलभाई", " "},
        {"Gujarat", "Surendranagar", "Salimbhai Shahbudinbhai Pathan", "4", " ", "गुजरात", "सुरेंद्रनगर", "सलीमभाई शाहबुद्दीनभाई पठान", " "},
        {"Gujarat", "Surendranagar", "Patel Baldevbhai", "3", " ", "गुजरात", "सुरेंद्रनगर", "पटेल बलदेवभाई", " "},
        {"Gujarat", "Surendranagar", "Vaghela Prakashbhai Bachubhai", "4", " ", "गुजरात", "सुरेंद्रनगर", "वाघेला प्रकाशभाई बच्चुभाई", " "},
        {"Gujarat", "Surendranagar", "Koli Rameshbhai Virsangbhai Vaghela", "4", " ", "गुजरात", "सुरेंद्रनगर", "कोली रमेशभाई विरसांगभाई वाघेला", " "},
        {"Gujarat", "Surendranagar", "Dost Mer", "4", " ", "गुजरात", "सुरेंद्रनगर", "दोस्त मेर", " "},
        {"Gujarat", "Surendranagar", "Parmar Ghoghjibhai Kanjibhai", "4", " ", "गुजरात", "सुरेंद्रनगर", "परमार घोघजीभाई कंजीभाई", " "},
        {"Gujarat", "Surendranagar", "Koli Patel Laljibhai Chaturbhai", "2", " ", "गुजरात", "सुरेंद्रनगर", "कोली पटेल लालजीभाई चतुर्भाई", " "},
        {"Gujarat", "Surendranagar", "Sapra Vipul R.", "4", " ", "गुजरात", "सुरेंद्रनगर", "सपरा विपुल आर।", " "},
        {"Gujarat", "Surendranagar", "Jargela Hasanbhai Abdulbhai", "4", " ", "गुजरात", "सुरेंद्रनगर", "जरगेला हसनभाई अब्दुलभाई", " "},
        {"Gujarat", "Surendranagar", "Kalubhai Malubhai Vadaliya", "3", " ", "गुजरात", "सुरेंद्रनगर", "कालुभाई मलुभाई वडालिया", " "},
        {"Gujarat", "Surendranagar", "Naresh Makwana", "4", " ", "गुजरात", "सुरेंद्रनगर", "नरेश मकवाना", " "},
        {"Gujarat", "Vadodara", "Prashant Patel", "1", " ", "गुजरात", "वडोदरा", "प्रशांत पटेल", " "},
        {"Gujarat", "Vadodara", "Shri Patel Kalidas Motibhai", "3", " ", "गुजरात", "वडोदरा", "श्री पटेल कालिदास मोतीभाई", " "},
        {"Gujarat", "Vadodara", "Ranjanben Bhatt", "1", " ", "गुजरात", "वडोदरा", "रंजनबेन भट्ट", " "},
        {"Gujarat", "Vadodara", "Mohsimmiya(Saiyad Mohsin Bapu)", "4", " ", "गुजरात", "वडोदरा", "मोहसिमिया (सय्यद मोहसिन बापू)", " "},
        {"Gujarat", "Vadodara", "Gohil Rinku", "4", " ", "गुजरात", "वडोदरा", "गोहिल रिंकू", " "},
        {"Gujarat", "Vadodara", "Yasinali Polra", "4", " ", "गुजरात", "वडोदरा", "यासिनाली पोला", " "},
        {"Gujarat", "Vadodara", "Jat Subhas Singh Brijlal", "2", " ", "गुजरात", "वडोदरा", "जाट सुभाष सिंह बृजलाल", " "},
        {"Gujarat", "Valsad", "Dr.K.C.Patel", "1", " ", "गुजरात", "वलसाड", "Dr.KCPatel", " "},
        {"Gujarat", "Valsad", "Chaudhari Jitubhai Harjibhai", "1", " ", "गुजरात", "वलसाड", "चौधरी जीतूभाई हरजीभाई", " "},
        {"Gujarat", "Valsad", "Patel Nareshbhai Babubhai", "4", " ", "गुजरात", "वलसाड", "पटेल नरेशभाई बाबूभाई", " "},
        {"Gujarat", "Valsad", "Patel Umeshbhai Maganbhai", "4", " ", "गुजरात", "वलसाड", "पटेल उमेशभाई मगनभाई", " "},
        {"Gujarat", "Valsad", "Babubhai Talaviya", "3", " ", "गुजरात", "वलसाड", "बाबूभाई तलाविया", " "},
        {"Gujarat", "Valsad", "Kishorbhai Ramanbhai Patel", "4", " ", "गुजरात", "वलसाड", "किशोरभाई रमनभाई पटेल", " "},
        {"Gujarat", "Valsad", "Patel Pankajbhai Lallubhai", "4", " ", "गुजरात", "वलसाड", "पटेल पंकजभाई लल्लूभाई", " "},
};

}