/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Gujarat {
public static final String[][] green_bucket = {
{"Gujarat",  "6760", "Ahmedabad East", "Minaxiben Rakeshkumar Solanki", "Independent", "69.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9377",  "गुजरात",  "अहमदाबाद पूर्व", "मिनाक्सीबेन राकेशकुमार सोलंकी", "निर्दलीय", ""}, 
{"Gujarat",  "6761", "Ahmedabad East", "Chauhan Narendra Sinh Makhatul Sinh", "Yuva Jan Jagriti Party", "53.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9385",  "गुजरात",  "अहमदाबाद पूर्व", "चौहान नरेंद्र सिंह माखतुल सिंह", "युवा जन जागृति पार्टी", ""}, 
{"Gujarat",  "6764", "Ahmedabad East", "Mundra Anilkumar", "Lok Gathbandhan Party", "18.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9374",  "गुजरात",  "अहमदाबाद पूर्व", "मुंद्रा अनिलकुमार", "लोक गठबंधन पार्टी", ""}, 
{"Gujarat",  "6766", "Ahmedabad East", "Dr. Hiteshkumar Mahendrabhai", "Nirbhay Bharteey Party", "54.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9383",  "गुजरात",  "अहमदाबाद पूर्व", "डॉ। हितेशकुमार महेंद्रभाई", "निर्भय भारती पार्टी", ""}, 
{"Gujarat",  "6770", "Ahmedabad East", "Pareshkumar Nanubhai Mulani", "Independent", "21Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9373",  "गुजरात",  "अहमदाबाद पूर्व", "परेशकुमार नानूभाई मुलानी", "निर्दलीय", ""}, 
{"Gujarat",  "6777", "Ahmedabad East", "Sharma Brijeshkumar Ujagarlal", "Independent", "26800", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10034",  "गुजरात",  "अहमदाबाद पूर्व", "शर्मा बृजेशकुमार उजागरलाल", "निर्दलीय", ""}, 
{"Gujarat",  "6778", "Ahmedabad East", "Atulbhai Nanubhai Kathiriya", "Independent", "29Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9381",  "गुजरात",  "अहमदाबाद पूर्व", "अतुलभाई नानूभाई कथिरिया", "निर्दलीय", ""}, 
{"Gujarat",  "6783", "Ahmedabad East", "Bhatt Sunilkumar Narendrabhai", "Right to Recall Party", "25.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9376",  "गुजरात",  "अहमदाबाद पूर्व", "भट्ट सुनीलकुमार नरेंद्रभाई", "राइट टू रिकॉल पार्टी", ""}, 
{"Gujarat",  "6792", "Ahmedabad West", "Solanki Chiragbhai Somabhai", "Jan Satya Path Party", "4.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9393",  "गुजरात",  "अहमदाबाद पश्चिम", "सोलंकी चिरागभाई सोमाभाई", "जन सत्य पथ पार्टी", ""}, 
{"Gujarat",  "6795", "Ahmedabad West", "Jadav Ulpesh Jyantilal", "Peoples Party of India (Democratic)", "36.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9395",  "गुजरात",  "अहमदाबाद पश्चिम", "जादव उल्पेश जयंतीलाल", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", ""}, 
{"Gujarat",  "6796", "Ahmedabad West", "Chauhan Harishbhai Jethabhai", "Rashtriya Power Party", "32.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9390",  "गुजरात",  "अहमदाबाद पश्चिम", "चौहान हरीशभाई जेठाभाई", "राष्ट्रीय पावर पार्टी", ""}, 
{"Gujarat",  "6797", "Ahmedabad West", "Malhotra Pankajkumar Dayabhai (Doctor Saheb)", "Independent", "4000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10037",  "गुजरात",  "अहमदाबाद पश्चिम", "मल्होत्रा पंकजकुमार दयाभाई (डॉक्टर साहब)", "निर्दलीय", ""}, 
{"Gujarat",  "6919", "Anand", "Chavda Kaushikkumar", "Independent", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8976",  "गुजरात",  "आनंद", "चावड़ा कौशिककुमार", "निर्दलीय", ""}, 
{"Gujarat",  "6925", "Anand", "Bhatt Sunilkumar Narendrabhai", "Right to Recall Party", "25.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8979",  "गुजरात",  "आनंद", "भट्ट सुनीलकुमार नरेंद्रभाई", "राइट टू रिकॉल पार्टी", ""}, 
{"Gujarat",  "6685", "Banaskantha", "Madhu Nirupaben", "Independent", "3.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9294",  "गुजरात",  "बनासकांठा", "मधु निरुपाबेन", "निर्दलीय", ""}, 
{"Gujarat",  "6687", "Banaskantha", "Purohit Shyamaben Naranbhai", "Independent", "25.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9282",  "गुजरात",  "बनासकांठा", "पुरोहित श्यामबेन नारनभाई", "निर्दलीय", ""}, 
{"Gujarat",  "6993", "Bardoli", "Pragneshbhai Ratilal Chaudhari", "Independent", "54.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10352",  "गुजरात",  "बारडोली", "प्रज्ञेशभाई रतिलाल चौधरी", "निर्दलीय", ""}, 
{"Gujarat",  "6995", "Bardoli", "Dineshbhai Gulabbhai Chaudhari", "Bahujan Samaj Party", "95000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8004",  "गुजरात",  "बारडोली", "दिनेशभाई गुलाबभाई चौधरी", "बहुजन समाज पार्टी", ""}, 
{"Gujarat",  "6996", "Bardoli", "Sureshbhai Motiyabhai Chaudhari", "Independent", "56.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10354",  "गुजरात",  "बारडोली", "सुरेशभाई मोटियाभाई चौधरी", "निर्दलीय", ""}, 
{"Gujarat",  "6982", "Bharuch", "Jitendra Parmar", "Independent", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9009",  "गुजरात",  "भरूच", "जितेंद्र परमार", "निर्दलीय", ""}, 
{"Gujarat",  "6912", "Bhavnagar", "Vijaykumar Ramabhai Makadiya", "Bahujan Samaj Party", "50000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8503",  "गुजरात",  "भावनगर", "विजयकुमार रामभाई मकाडिय़ा", "बहुजन समाज पार्टी", ""}, 
{"Gujarat",  "6913", "Bhavnagar", "Champaben Zaverbhai Chauhan", "Independent", "37.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9448",  "गुजरात",  "भावनगर", "चम्पाबेन झवेरभाई चौहान", "निर्दलीय", ""}, 
{"Gujarat",  "6961", "Chhota Udaipur", "Umesh Jangubhai Rathawa", "Independent", "1.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9002",  "गुजरात",  "छोटा उदयपुर", "उमेश जंगुभाई राठवा", "निर्दलीय", ""}, 
{"Gujarat",  "6967", "Chhota Udaipur", "Vasava Rajesh Somabhai", "Bhartiya Tribal Party", "10.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9004",  "गुजरात",  "छोटा उदयपुर", "वसावा राजेश सोमभाई", "भारतीय ट्राइबल पार्टी", ""}, 
{"Gujarat",  "6943", "Dahod", "Devadha Samsubhai Khatarabhai", "Independent", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8996",  "गुजरात",  "दाहोद", "देवदास संमुभाई खातरभाई", "निर्दलीय", ""}, 
{"Gujarat",  "6754", "Gandhinagar", "Jayendra Karshanbhai Rathod", "Bahujan Samaj Party", "8.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8481",  "गुजरात",  "गांधीनगर", "जयेन्द्र दर्शनभाई राठौड़", "बहुजन समाज पार्टी", ""}, 
{"Gujarat",  "6755", "Gandhinagar", "Rahul Chimanbhai Mehta", "Right to Recall Party", "5.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9349",  "गुजरात",  "गांधीनगर", "राहुल चिमनभाई मेहता", "राइट टू रिकॉल पार्टी", ""}, 
{"Gujarat",  "6860", "Jamnagar", "Jahid Aavad Jami", "Independent", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10059",  "गुजरात",  "जामनगर", "जाहिद आवद जामी", "निर्दलीय", ""}, 
{"Gujarat",  "6867", "Jamnagar", "Vaghela Sunil Jethalal", "Bahujan Samaj Party", "1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8020",  "गुजरात",  "जामनगर", "वाघेला सुनील जेठालाल", "बहुजन समाज पार्टी", ""}, 
{"Gujarat",  "6878", "Jamnagar", "Baxi Mrudul Ashwinkumar", "Independent", "1.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10063",  "गुजरात",  "जामनगर", "बक्सी मृदुल अश्विनकुमार", "निर्दलीय", ""}, 
{"Gujarat",  "6884", "Junagadh", "Dharmendra Vajubhai Makwana", "Independent", "3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9307",  "गुजरात",  "जूनागढ़", "धर्मेंद्र वजुभाई मकवाना", "निर्दलीय", ""}, 
{"Gujarat",  "6887", "Junagadh", "Haresh Manubhai Sardhara", "Independent", "7.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9305",  "गुजरात",  "जूनागढ़", "हरेश मनुभाई सरधरा", "निर्दलीय", ""}, 
{"Gujarat",  "6892", "Junagadh", "Vala Jaypalsinh Hajabhai", "Independent", "3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9303",  "गुजरात",  "जूनागढ़", "वला जयपालसिंह हजभाई", "निर्दलीय", ""}, 
{"Gujarat",  "6717", "Mahesana", "Chaudhari Sendhabhai Abherajbhai", "Bahujan Mukti Party", "84.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9321",  "गुजरात",  "महेसाणा", "चौधरी सेंधाभाई अभिराजभाई", "बहुजन मुक्ति पार्टी", ""}, 
{"Gujarat",  "6719", "Mahesana", "Barot Kuldipkumar Bharatkumar", "Yuva Jan Jagriti Party", "14.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9328",  "गुजरात",  "महेसाणा", "बरोट कुलदीपकुमार भरतकुमार", "युवा जन जागृति पार्टी", ""}, 
{"Gujarat",  "7015", "Navsari", "Jain Rajendrakumar Anilkumar", "Independent", "5.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9033",  "गुजरात",  "नवसारी", "जैन राजेंद्रकुमार अनिलकुमार", "निर्दलीय", ""}, 
{"Gujarat",  "7022", "Navsari", "Singh Vineeta", "Bahujan Samaj Party", "58.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8578",  "गुजरात",  "नवसारी", "सिंह विनीता", "बहुजन समाज पार्टी", ""}, 
{"Gujarat",  "7026", "Navsari", "Khadadiya Kanubhai Tapubhai", "Socialist Unity Centre of India (Communist)", "75.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9022",  "गुजरात",  "नवसारी", "खड़दिया कनुभाई तपुभाई", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Gujarat",  "7027", "Navsari", "Khan Heenabegam", "Independent", "51.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9026",  "गुजरात",  "नवसारी", "खान हेनाबेगम", "निर्दलीय", ""}, 
{"Gujarat",  "7030", "Navsari", "Patel Navinkumar", "Independent", "7.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9029",  "गुजरात",  "नवसारी", "पटेल नवीनकुमार", "निर्दलीय", ""}, 
{"Gujarat",  "7033", "Navsari", "Mishra Jitendrabhai Premnath", "Sanyukt Vikas Party", "11.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9030",  "गुजरात",  "नवसारी", "मिश्रा जितेन्द्रभाई प्रेमनाथ", "संयुक्ता विकास पार्टी", ""}, 
{"Gujarat",  "6936", "Panchmahal", "Rathod Vijaysinh", "Hindusthan Nirman Dal", "18.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8992",  "गुजरात",  "पंचमहल", "राठौड़ विजयसिंह", "हिंदुस्तान निर्माण दल", ""}, 
{"Gujarat",  "6703", "Patan", "Parmar Surajkumar Mahendrakumar", "Bahujan Samaj Party", "9.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8011",  "गुजरात",  "पाटन", "परमार सूरजकुमार महेंद्रकुमार", "बहुजन समाज पार्टी", ""}, 
{"Gujarat",  "6710", "Patan", "Chaudhari Kirtibhai Jesangbhai", "Nationalist Congress Party", "37.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9312",  "गुजरात",  "पाटन", "चौधरी कीर्तिभाई जेसंगभाई", "राष्ट्रवादी कांग्रेस पार्टी", ""}, 
{"Gujarat",  "6842", "Porbandar", "Bhanubhai Odedra", "Independent", "21.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9411",  "गुजरात",  "पोरबंदर", "भानुभाई ओडेदरा", "निर्दलीय", ""}, 
{"Gujarat",  "6844", "Porbandar", "Vakil Vinzuda Ranjitbhai", "Bahujan Maha Party", "14.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9412",  "गुजरात",  "पोरबंदर", "वकिल विनज़ुदा रंजीतभाई", "बहुजन महा पार्टी", ""}, 
{"Gujarat",  "6849", "Porbandar", "Sondarva Ashok", "Independent", "24.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9414",  "गुजरात",  "पोरबंदर", "सोंदरवा अशोक", "निर्दलीय", ""}, 
{"Gujarat",  "6855", "Porbandar", "Alpesh Vadoliya", "Independent", "75124", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9419",  "गुजरात",  "पोरबंदर", "अल्पेश वडोलिया", "निर्दलीय", ""}, 
{"Gujarat",  "6838", "Rajkot", "Chitroda Nathalal", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9404",  "गुजरात",  "राजकोट", "चितरोदा नथमल", "निर्दलीय", ""}, 
{"Gujarat",  "6726", "Sabarkantha", "Kalabhai Bababhai Parmar", "Independent", "5.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9340",  "गुजरात",  "साबरकांठा", "कालाभाई बाबाभाई परमार", "निर्दलीय", ""}, 
{"Gujarat",  "6727", "Sabarkantha", "Vinodbhai Mesariya", "Bahujan Samaj Party", "44.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8015",  "गुजरात",  "साबरकांठा", "विनोदभाई मेसरिया", "बहुजन समाज पार्टी", ""}, 
{"Gujarat",  "6728", "Sabarkantha", "Patel Jayntibhai Shamjibhai", "Hindusthan Nirman Dal", "39.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9339",  "गुजरात",  "साबरकांठा", "पटेल जयंतीभाई शामजीभाई", "हिंदुस्तान निर्माण दल", ""}, 
{"Gujarat",  "6730", "Sabarkantha", "Kharadi Dharmendrasingh Samsubhai", "Bhartiya Tribal Party", "27Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9346",  "गुजरात",  "साबरकांठा", "खराडी धर्मेन्द्रसिंह समसुभाई", "भारतीय ट्राइबल पार्टी", ""}, 
{"Gujarat",  "6740", "Sabarkantha", "Patel Kiritkumar Babarbhai", "Independent", "41.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9954",  "गुजरात",  "साबरकांठा", "पटेल किरीटकुमार बाबरभाई", "निर्दलीय", ""}, 
{"Gujarat",  "6999", "Surat", "Rita Captain", "Pyramid Party of India", "1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8802",  "गुजरात",  "सूरत", "रीता कैप्टन", "पिरामिड पार्टी ऑफ इंडिया", ""}, 
{"Gujarat",  "7000", "Surat", "Shenmare Vijaybhai Namdeo", "Communist Party of India", "98.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8005",  "गुजरात",  "सूरत", "शेनमारे विजयभाई नामदेव", "भारतीय कम्युनिस्ट पार्टी", ""}, 
{"Gujarat",  "7003", "Surat", "Jogiya Amisha Vikrambhai", "Sanyukt Vikas Party", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8805",  "गुजरात",  "सूरत", "जोगिया अमीषा विक्रमभाई", "संयुक्ता विकास पार्टी", ""}, 
{"Gujarat",  "7008", "Surat", "Natvarbhai Dahyabhai Mahyavanshi", "Independent", "10.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8800",  "गुजरात",  "सूरत", "नटवरभाई भयभाई महावंशी", "निर्दलीय", ""}, 
{"Gujarat",  "6815", "Surendranagar", "Bhavanbhai Devjibhai Vora", "Independent", "8.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10047",  "गुजरात",  "सुरेंद्रनगर", "भवानभाई देवजीभाई वोरा", "निर्दलीय", ""}, 
{"Gujarat",  "6819", "Surendranagar", "Rathod Anandbhai Pachanbhai", "Independent", "3.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8796",  "गुजरात",  "सुरेंद्रनगर", "राठौड़ आनंदभाई पचनभाई", "निर्दलीय", ""}, 
{"Gujarat",  "6827", "Surendranagar", "Solanki Shaileshbhai Nagarbhai", "Bahujan Samaj Party", "45.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8492",  "गुजरात",  "सुरेंद्रनगर", "सोलंकी शैलेशभाई नागरभाई", "बहुजन समाज पार्टी", ""}, 
{"Gujarat",  "6949", "Vadodara", "Dr. Rahul Vasudevbhai Vyas", "Independent", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8784",  "गुजरात",  "वडोदरा", "डॉ। राहुल वासुदेवभाई व्यास", "निर्दलीय", ""}, 
{"Gujarat",  "6952", "Vadodara", "Sindhi Mahebubkhan Yusufkhan", "Independent", "26.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8785",  "गुजरात",  "वडोदरा", "सिंधी महबूबखान युसुफखान", "निर्दलीय", ""}, 
{"Gujarat",  "6953", "Vadodara", "Rohit Madhusudan Mohanbhai", "Bahujan Samaj Party", "90.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8001",  "गुजरात",  "वडोदरा", "रोहित मधुसूदन मोहनभाई", "बहुजन समाज पार्टी", ""}, 
{"Gujarat",  "6958", "Vadodara", "Tapanbhai Dasgupta", "Socialist Unity Centre of India (Communist)", "11.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8781",  "गुजरात",  "वडोदरा", "तपनभाई दासगुप्ता", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Gujarat",  "6959", "Vadodara", "Nimesh Patel (Kamrol)", "Independent", "26.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10345",  "गुजरात",  "वडोदरा", "निमेश पटेल (कमरोल)", "निर्दलीय", ""}, 
{"Gujarat",  "6960", "Vadodara", "Santosh S. Solanki", "Bhartiya Manavadhikaar Federal Party", "8.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10344",  "गुजरात",  "वडोदरा", "संतोष एस। सोलंकी", "भारतीय मानववादी फेडरल पार्टी", ""}, 
{"Gujarat",  "7038", "Valsad", "Ganvit Jayendrabhai Laxmanbhai", "Independent", "25000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8775",  "गुजरात",  "वलसाड", "गनवित जयेन्द्रभाई लक्ष्मणभाई", "निर्दलीय", ""}, 
{"Gujarat",  "7044", "Valsad", "Gaurangbhai Rameshbhai Patel", "Independent", "7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8778",  "गुजरात",  "वलसाड", "गौरांगभाई रमेशभाई पटेल", "निर्दलीय", ""}, 
};

public static final String[][] red_bucket = {
{ "Gujarat",  "6759",  "Ahmedabad East", "Virat Pradip Shah", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पूर्व", "विराट प्रदीप शाह", " "}, 
{ "Gujarat",  "6762",  "Ahmedabad East", "Kadri Mohammad Sabir", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पूर्व", "कादरी मोहम्मद साबिर", " "}, 
{ "Gujarat",  "6763",  "Ahmedabad East", "Mishra Arjun Ramshankar", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पूर्व", "मिश्रा अर्जुन रामशंकर", " "}, 
{ "Gujarat",  "6765",  "Ahmedabad East", "Samirbhai Rajeshbhai Upadhyay", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पूर्व", "समीरभाई राजेशभाई उपाध्याय", " "}, 
{ "Gujarat",  "6767",  "Ahmedabad East", "Geetaben Patel", "ForeignFunding",  " ","गुजरात",  "अहमदाबाद पूर्व", "गीताबेन पटेल", " "}, 
{ "Gujarat",  "6768",  "Ahmedabad East", "Patel Hasmukhbhai Somabhai", "ForeignFunding",  " ","गुजरात",  "अहमदाबाद पूर्व", "पटेल हसमुखभाई सोमाभाई", " "}, 
{ "Gujarat",  "6769",  "Ahmedabad East", "Bharvad Saileshkumar Kalidas", "CriminalCases",  " ","गुजरात",  "अहमदाबाद पूर्व", "भारवद शैलेषकुमार कालिदास", " "}, 
{ "Gujarat",  "6771",  "Ahmedabad East", "Chauhan Kiritbhai", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पूर्व", "चौहान किरीटभाई", " "}, 
{ "Gujarat",  "6772",  "Ahmedabad East", "Mishra Rajkumar Malekchand", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पूर्व", "मिश्रा राजकुमार मालेकचंद", " "}, 
{ "Gujarat",  "6773",  "Ahmedabad East", "Rajesh Maurya", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पूर्व", "राजेश मौर्य", " "}, 
{ "Gujarat",  "6774",  "Ahmedabad East", "Vekariya Rushi Bharatbhai (Patel)", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पूर्व", "वेकारिया रूशी भरतभाई (पटेल)", " "}, 
{ "Gujarat",  "6775",  "Ahmedabad East", "Thakur Jitendrasinh Surendrasinh", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पूर्व", "ठाकुर जितेन्द्रसिंह सुरेन्द्रसिंह", " "}, 
{ "Gujarat",  "6776",  "Ahmedabad East", "Devda Dasharath Misarilal", "CriminalCases",  " ","गुजरात",  "अहमदाबाद पूर्व", "देवदा दशरथ मिसरीलाल", " "}, 
{ "Gujarat",  "6779",  "Ahmedabad East", "Shekh Salmabanu Mohamad Salim", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पूर्व", "शेख सालमबनु मोहमद सलीम", " "}, 
{ "Gujarat",  "6780",  "Ahmedabad East", "Mahesh Prabhudas Ahuja", "CriminalCases",  " ","गुजरात",  "अहमदाबाद पूर्व", "महेश प्रभुदास आहूजा", " "}, 
{ "Gujarat",  "6781",  "Ahmedabad East", "Jayswal Nareshkumar Babulal", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पूर्व", "जयसवाल नरेशकुमार बाबूलाल", " "}, 
{ "Gujarat",  "6782",  "Ahmedabad East", "Manoj Premchand Gupta", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पूर्व", "मनोज प्रेमचंद गुप्ता", " "}, 
{ "Gujarat",  "6784",  "Ahmedabad East", "Vaghela Ganeshbhai Narsinhbhai", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पूर्व", "वाघेला गणेशभाई नरसिंहभाई", " "}, 
{ "Gujarat",  "6785",  "Ahmedabad West", "Dipika Jitendrakumar Sutaria", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पश्चिम", "दीपिका जितेंद्रकुमार सुतारिया", " "}, 
{ "Gujarat",  "6786",  "Ahmedabad West", "Dr. Solanki Kiritbhai", "ForeignFunding",  " ","गुजरात",  "अहमदाबाद पश्चिम", "डॉ। सोलंकी किरीटभाई", " "}, 
{ "Gujarat",  "6787",  "Ahmedabad West", "Raju Parmar", "ForeignFunding",  " ","गुजरात",  "अहमदाबाद पश्चिम", "राजू परमार", " "}, 
{ "Gujarat",  "6788",  "Ahmedabad West", "Mahedia Mahendrabhai Parsottamdas", "CriminalCases",  " ","गुजरात",  "अहमदाबाद पश्चिम", "महेदिया महेन्द्रभाई परसोत्तमदास", " "}, 
{ "Gujarat",  "6789",  "Ahmedabad West", "Tribhovandas Karsandas Vaghela", "OverAged",  " ","गुजरात",  "अहमदाबाद पश्चिम", "त्रिभुवनदास करसंडस वाघेला", " "}, 
{ "Gujarat",  "6790",  "Ahmedabad West", "Bhitora Bhavesh Chimanbhai", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पश्चिम", "भिटोरा भावेश चिमनभाई", " "}, 
{ "Gujarat",  "6791",  "Ahmedabad West", "Vedubhai Sirasat Kautikbhai", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पश्चिम", "वेदुभाई सिरसाट कौतिकभाई", " "}, 
{ "Gujarat",  "6793",  "Ahmedabad West", "Harshadkumar Laxmanbhai Solanki", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पश्चिम", "हर्षदकुमार लक्ष्मणभाई सोलंकी", " "}, 
{ "Gujarat",  "6794",  "Ahmedabad West", "Vaghela Ashwinbhai Amrutbhai", "NotGraduate",  " ","गुजरात",  "अहमदाबाद पश्चिम", "वाघेला अश्विनभाई अमृतभाई", " "}, 
{ "Gujarat",  "6896",  "Amreli", "Bagda Himmatbhai Danjibhai", "CriminalCases",  " ","गुजरात",  "अमरेली", "बागदा हिम्मतबाई दंजीभाई", " "}, 
{ "Gujarat",  "6897",  "Amreli", "Dayala Subhashbhai Parbatbhai", "NotGraduate",  " ","गुजरात",  "अमरेली", "दयाला सुभाषभाई परबतभाई", " "}, 
{ "Gujarat",  "6898",  "Amreli", "Gosai Rasikpragat Samjupragat", "NotGraduate",  " ","गुजरात",  "अमरेली", "गोसाई रसिकप्रगट समुझपतगट", " "}, 
{ "Gujarat",  "6899",  "Amreli", "Sukhdiya Nathabhai", "CriminalCases",  " ","गुजरात",  "अमरेली", "सुखिया नतभाई", " "}, 
{ "Gujarat",  "6900",  "Amreli", "Kachhadiya Naranbhai Bhikhabhai", "ForeignFunding",  " ","गुजरात",  "अमरेली", "कछदिया नारनभाई भीखाभाई", " "}, 
{ "Gujarat",  "6901",  "Amreli", "Paresh Dhanani", "ForeignFunding",  " ","गुजरात",  "अमरेली", "परेश धनानी", " "}, 
{ "Gujarat",  "6902",  "Amreli", "Valodara Vrajlal Jivabhai", "OverAged",  " ","गुजरात",  "अमरेली", "वलोदरा व्रजलाल जीवाभाई", " "}, 
{ "Gujarat",  "6903",  "Amreli", "Dhapa Dharamshibhai Ramjibhai", "CriminalCases",  " ","गुजरात",  "अमरेली", "धापा धर्मशीभाई रामजीभाई", " "}, 
{ "Gujarat",  "6904",  "Amreli", "Chauhan Ravjibhai Mulabhai", "NotGraduate",  " ","गुजरात",  "अमरेली", "चौहान रविजीभाई मूलभाई", " "}, 
{ "Gujarat",  "6905",  "Amreli", "Chauhan Dayabhai Bhagvanbhai", "NotGraduate",  " ","गुजरात",  "अमरेली", "चौहान दयाभाई भगवानभाई", " "}, 
{ "Gujarat",  "6906",  "Amreli", "Jerambhai Raghavbhai Parmar", "CriminalCases",  " ","गुजरात",  "अमरेली", "जरामभाई राघवभाई परमार", " "}, 
{ "Gujarat",  "6907",  "Amreli", "Nanalal Kalidas Maheta", "NotGraduate",  " ","गुजरात",  "अमरेली", "नानालाल कालिदास महेता", " "}, 
{ "Gujarat",  "6918",  "Anand", "Keyur Pravinbhai Patel", "NotGraduate",  " ","गुजरात",  "आनंद", "केयूर प्रवीणभाई पटेल", " "}, 
{ "Gujarat",  "6920",  "Anand", "Vankar Rameshbhai Valjibhai", "NotGraduate",  " ","गुजरात",  "आनंद", "वानकर रमेशभाई वलजीभाई", " "}, 
{ "Gujarat",  "6921",  "Anand", "Miteshbhai Patel", "ForeignFunding",  " ","गुजरात",  "आनंद", "मितेशभाई पटेल", " "}, 
{ "Gujarat",  "6922",  "Anand", "Bharatbhai Chhotabhai Solanki", "NotGraduate",  " ","गुजरात",  "आनंद", "भरतभाई छोटभाई सोलंकी", " "}, 
{ "Gujarat",  "6923",  "Anand", "Hitendrasinh Parmar", "NotGraduate",  " ","गुजरात",  "आनंद", "हितेन्द्रसिंह परमार", " "}, 
{ "Gujarat",  "6924",  "Anand", "Bharatbhai Madhavsinh Solanki", "ForeignFunding",  " ","गुजरात",  "आनंद", "भरतभाई माधवसिंह सोलंकी", " "}, 
{ "Gujarat",  "6926",  "Anand", "Santolkumar Patel", "NotGraduate",  " ","गुजरात",  "आनंद", "संतोलकुमार पटेल", " "}, 
{ "Gujarat",  "6927",  "Anand", "Bhatt Ashishkumar Manojkumar", "NotGraduate",  " ","गुजरात",  "आनंद", "भट्ट आशीषकुमार मनोजकुमार", " "}, 
{ "Gujarat",  "6686",  "Banaskantha", "Tejabhai Nethibhai Rabari", "CriminalCases",  " ","गुजरात",  "बनासकांठा", "तेजभाई नेतिभाई रबारी", " "}, 
{ "Gujarat",  "6688",  "Banaskantha", "Charmta Bharatkumar Khemabhai", "CriminalCases",  " ","गुजरात",  "बनासकांठा", "चारित्र भरतकुमार खेमाभाई", " "}, 
{ "Gujarat",  "6689",  "Banaskantha", "Desai Ishvarbhai", "NotGraduate",  " ","गुजरात",  "बनासकांठा", "देसाई ईश्वरभाई", " "}, 
{ "Gujarat",  "6690",  "Banaskantha", "Jagdishji Parthiji Dharani", "NotGraduate",  " ","गुजरात",  "बनासकांठा", "जगदीशजी पार्थिजी धरनी", " "}, 
{ "Gujarat",  "6691",  "Banaskantha", "Thakor Melaji Madarsinh", "NotGraduate",  " ","गुजरात",  "बनासकांठा", "ठाकोर मेलाजी मदरसिंह", " "}, 
{ "Gujarat",  "6692",  "Banaskantha", "Parmar Chhaganchandraraj Dhanabhai", "NotGraduate",  " ","गुजरात",  "बनासकांठा", "परमार छगनचंद्रराज धनभाई", " "}, 
{ "Gujarat",  "6693",  "Banaskantha", "Thakor Swarupji Sardarji", "NotGraduate",  " ","गुजरात",  "बनासकांठा", "ठाकोर स्वरूपजी सरदारजी", " "}, 
{ "Gujarat",  "6694",  "Banaskantha", "Parthibhai Galbabhai Bhatol", "ForeignFunding",  " ","गुजरात",  "बनासकांठा", "पार्थीभाई गलबाभाई भटोल", " "}, 
{ "Gujarat",  "6695",  "Banaskantha", "Padhiyar Bharatkumar Ishvarlal", "NotGraduate",  " ","गुजरात",  "बनासकांठा", "पधियार भरतकुमार ईश्वरलाल", " "}, 
{ "Gujarat",  "6696",  "Banaskantha", "Parbatbhai Patel", "ForeignFunding",  " ","गुजरात",  "बनासकांठा", "परबतभाई पटेल", " "}, 
{ "Gujarat",  "6697",  "Banaskantha", "Parsani Ibrahimbhai Pirabhai", "NotGraduate",  " ","गुजरात",  "बनासकांठा", "परसानी इब्राहिमभाई पिराबाई", " "}, 
{ "Gujarat",  "6698",  "Banaskantha", "Dr. Chandraben", "CriminalCases",  " ","गुजरात",  "बनासकांठा", "डॉ। चंद्रबेन", " "}, 
{ "Gujarat",  "6986",  "Bardoli", "Arvindbhai Bhanabhai Rathod", "NotGraduate",  " ","गुजरात",  "बारडोली", "अरविंदभाई भानभाई राठौड़", " "}, 
{ "Gujarat",  "6987",  "Bardoli", "Chaudhari Tusharbhai Amarsinhbhai", "ForeignFunding",  " ","गुजरात",  "बारडोली", "चौधरी तुषारभाई अमरसिंहभाई", " "}, 
{ "Gujarat",  "6988",  "Bardoli", "Vasava Uttambhai Somabhai", "CriminalCases",  " ","गुजरात",  "बारडोली", "वसावा उत्तमभाई सोमाभाई", " "}, 
{ "Gujarat",  "6989",  "Bardoli", "Gamit Mohanbhai Babubhai", "OverAged",  " ","गुजरात",  "बारडोली", "गामित मोहनभाई बाबूभाई", " "}, 
{ "Gujarat",  "6990",  "Bardoli", "Gamit Kaushikbhai Virendrabhai", "NotGraduate",  " ","गुजरात",  "बारडोली", "गामित कौशिकभाई वीरेंद्रभाई", " "}, 
{ "Gujarat",  "6991",  "Bardoli", "Gamit Sureshbhai Babubhai", "NotGraduate",  " ","गुजरात",  "बारडोली", "गामित सुरेशभाई बाबूभाई", " "}, 
{ "Gujarat",  "6992",  "Bardoli", "Parbhubhai Nagarbhai Vasava", "ForeignFunding",  " ","गुजरात",  "बारडोली", "परभुभाई नगरभाई वसावा", " "}, 
{ "Gujarat",  "6994",  "Bardoli", "Umedbhai Bhimsingbhai Gamit", "NotGraduate",  " ","गुजरात",  "बारडोली", "उम्मेदभाई भीमसिंगभाई गामित", " "}, 
{ "Gujarat",  "6997",  "Bardoli", "Vasava Fatesingbhai Vahriyabhai", "NotGraduate",  " ","गुजरात",  "बारडोली", "वसावा फ़तेसिंघभाई वहरियाभाई", " "}, 
{ "Gujarat",  "6969",  "Bharuch", "Vashi Narendrasinh", "NotGraduate",  " ","गुजरात",  "भरूच", "वाशी नरेंद्रसिंह", " "}, 
{ "Gujarat",  "6970",  "Bharuch", "Patel Imran", "NotGraduate",  " ","गुजरात",  "भरूच", "पटेल इमरान", " "}, 
{ "Gujarat",  "6971",  "Bharuch", "Parmar Ashokchandra", "NotGraduate",  " ","गुजरात",  "भरूच", "परमार अशोकचंद्र", " "}, 
{ "Gujarat",  "6972",  "Bharuch", "Sukhdev Vasava", "NotGraduate",  " ","गुजरात",  "भरूच", "सुखदेव वसावा", " "}, 
{ "Gujarat",  "6973",  "Bharuch", "Sabbirbhai Patel", "NotGraduate",  " ","गुजरात",  "भरूच", "सब्बीरभाई पटेल", " "}, 
{ "Gujarat",  "6974",  "Bharuch", "Rajeshbhai Solanki", "NotGraduate",  " ","गुजरात",  "भरूच", "राजेशभाई सोलंकी", " "}, 
{ "Gujarat",  "6975",  "Bharuch", "Vasava Navinbhai", "NotGraduate",  " ","गुजरात",  "भरूच", "वसावा नवीनभाई", " "}, 
{ "Gujarat",  "6976",  "Bharuch", "Pathan Salimkhan", "NotGraduate",  " ","गुजरात",  "भरूच", "पठान सलीमखान", " "}, 
{ "Gujarat",  "6977",  "Bharuch", "Mukhtiyar Shaikh", "NotGraduate",  " ","गुजरात",  "भरूच", "मुख्तियार शेख", " "}, 
{ "Gujarat",  "6978",  "Bharuch", "Chhotubhai Vasava", "CriminalCases",  " ","गुजरात",  "भरूच", "छोटूभाई वसावा", " "}, 
{ "Gujarat",  "6979",  "Bharuch", "Rafikbhai Sapa", "CriminalCases",  " ","गुजरात",  "भरूच", "रफीकभाई सपा", " "}, 
{ "Gujarat",  "6980",  "Bharuch", "Sherkhan Pathan", "ForeignFunding",  " ","गुजरात",  "भरूच", "शेरखान पठान", " "}, 
{ "Gujarat",  "6981",  "Bharuch", "Vasava Rajeshbhai", "NotGraduate",  " ","गुजरात",  "भरूच", "वसावा राजेशभाई", " "}, 
{ "Gujarat",  "6983",  "Bharuch", "Mansukhbhai Vasava", "ForeignFunding",  " ","गुजरात",  "भरूच", "मनसुखभाई वसावा", " "}, 
{ "Gujarat",  "6984",  "Bharuch", "Vikramsinh Gohil", "NotGraduate",  " ","गुजरात",  "भरूच", "विक्रमसिंह गोहिल", " "}, 
{ "Gujarat",  "6985",  "Bharuch", "Sindha Kiritsinh", "NotGraduate",  " ","गुजरात",  "भरूच", "सिंध किरिटसिंह", " "}, 
{ "Gujarat",  "6914",  "Bhavnagar", "Chauhan Ajaykumar Ramratansinh", "CriminalCases",  " ","गुजरात",  "भावनगर", "चौहान अजयकुमार रामरतनसिंह", " "}, 
{ "Gujarat",  "6915",  "Bhavnagar", "Zala Ramdevsinh Bharatsinh", "NotGraduate",  " ","गुजरात",  "भावनगर", "ज़ला रामदेवसिंह भरतसिंह", " "}, 
{ "Gujarat",  "6916",  "Bhavnagar", "Hareshbhai Babubhai Vegad", "CriminalCases",  " ","गुजरात",  "भावनगर", "हरेशभाई बाबूभाई वेगड़", " "}, 
{ "Gujarat",  "6917",  "Bhavnagar", "Dhapa Dharamshibhai Ramjibhai", "CriminalCases",  " ","गुजरात",  "भावनगर", "धापा धर्मशीभाई रामजीभाई", " "}, 
{ "Gujarat",  "6908",  "Bhavnagar", "Sondarva Bharatbhai Kanjibhai", "NotGraduate",  " ","गुजरात",  "भावनगर", "सोंदरवा भरतभाई कंजीभाई", " "}, 
{ "Gujarat",  "6909",  "Bhavnagar", "Manharbhai Nagjibhai Patel", "ForeignFunding",  " ","गुजरात",  "भावनगर", "मनहरभाई नागजीभाई पटेल", " "}, 
{ "Gujarat",  "6910",  "Bhavnagar", "Dr.Bharatiben Dhirubhai Shiyal", "ForeignFunding",  " ","गुजरात",  "भावनगर", "डॉ.भारतीबेन धीरूभाई शियाल", " "}, 
{ "Gujarat",  "6911",  "Bhavnagar", "Sitapara Sagarbhai Bhurabhai", "NotGraduate",  " ","गुजरात",  "भावनगर", "सीतापारा सागरभाई भुरभाई", " "}, 
{ "Gujarat",  "6962",  "Chhota Udaipur", "Pravinbhai Dhursingbhai Rathava", "NotGraduate",  " ","गुजरात",  "छोटा उदयपुर", "प्रवीणभाई ढेसिंगभाई राठवा", " "}, 
{ "Gujarat",  "6963",  "Chhota Udaipur", "Rathva Gitaben Vajesingbhai", "ForeignFunding",  " ","गुजरात",  "छोटा उदयपुर", "रथ्वा गीताबेन वजेसिंगभाई", " "}, 
{ "Gujarat",  "6964",  "Chhota Udaipur", "Rathava Ranjitsinh Mohansinh", "ForeignFunding",  " ","गुजरात",  "छोटा उदयपुर", "रथवा रंजीतसिंह मोहनसिंह", " "}, 
{ "Gujarat",  "6965",  "Chhota Udaipur", "Rathava Furkanbhai Baljibhai", "NotGraduate",  " ","गुजरात",  "छोटा उदयपुर", "रथवा फुरकानभाई बलजीभाई", " "}, 
{ "Gujarat",  "6966",  "Chhota Udaipur", "Rathva Maganbhai Chathiyabhai", "NotGraduate",  " ","गुजरात",  "छोटा उदयपुर", "रथवा मगनभाई चठियाभाई", " "}, 
{ "Gujarat",  "6968",  "Chhota Udaipur", "Rathva Bhavsingbhai Namarsingbhai", "CriminalCases",  " ","गुजरात",  "छोटा उदयपुर", "रथवा भवसिंघभय नमरसिंघै", " "}, 
{ "Gujarat",  "6941",  "Dahod", "Kalara Ramsingbhai Nanjibhai", "NotGraduate",  " ","गुजरात",  "दाहोद", "कलरा रामसिंगभाई नंजिभाई", " "}, 
{ "Gujarat",  "6942",  "Dahod", "Bhabhor Dhulabhai Ditabhai", "NotGraduate",  " ","गुजरात",  "दाहोद", "भभोर धूलभाई दिताभाई", " "}, 
{ "Gujarat",  "6944",  "Dahod", "Damor Manabhai Bhavsing", "NotGraduate",  " ","गुजरात",  "दाहोद", "डामोर मनभाई भावसिंह", " "}, 
{ "Gujarat",  "6945",  "Dahod", "Katara Babubhai Khimabhai", "ForeignFunding",  " ","गुजरात",  "दाहोद", "कटारा बाबूभाई खिमभाई", " "}, 
{ "Gujarat",  "6946",  "Dahod", "Jasvantsinh Sumanbhai Bhabhor", "ForeignFunding",  " ","गुजरात",  "दाहोद", "जसवंतसिंह सुमनभाई भाभोर", " "}, 
{ "Gujarat",  "6947",  "Dahod", "Jagdishbhai Manilal Meda", "NotGraduate",  " ","गुजरात",  "दाहोद", "जगदीशभाई मणिलाल मेधा", " "}, 
{ "Gujarat",  "6743",  "Gandhinagar", "Naranbhai Tulsidas Sengal", "NotGraduate",  " ","गुजरात",  "गांधीनगर", "नारनभाई तुलसीदास सेंगल", " "}, 
{ "Gujarat",  "6744",  "Gandhinagar", "Makwana Anilkumar Somabhai", "NotGraduate",  " ","गुजरात",  "गांधीनगर", "मकवाना अनिलकुमार सोमभाई", " "}, 
{ "Gujarat",  "6745",  "Gandhinagar", "Mahendrabhai Somabhai Patni", "NotGraduate",  " ","गुजरात",  "गांधीनगर", "महेंद्रभाई सोमाभाई पाटनी", " "}, 
{ "Gujarat",  "6746",  "Gandhinagar", "Amit Shah", "ForeignFunding",  " ","गुजरात",  "गांधीनगर", "अमित शाह", " "}, 
{ "Gujarat",  "6747",  "Gandhinagar", "Narendrabhai Revashanker Trivedi", "OverAged",  " ","गुजरात",  "गांधीनगर", "नरेंद्रभाई रेवाशंकर त्रिवेदी", " "}, 
{ "Gujarat",  "6748",  "Gandhinagar", "Chandrapal Hasmukh Bavjibhai", "NotGraduate",  " ","गुजरात",  "गांधीनगर", "चंद्रपाल हसमुख बावजीभाई", " "}, 
{ "Gujarat",  "6749",  "Gandhinagar", "Shekh Shahinbanu Molana Mustak", "NotGraduate",  " ","गुजरात",  "गांधीनगर", "शेख शाहीननु मोलाना मुस्तक", " "}, 
{ "Gujarat",  "6750",  "Gandhinagar", "Chavda Chatursinh Javanji", "ForeignFunding",  " ","गुजरात",  "गांधीनगर", "चावड़ा चतुरसिंह जवानीजी", " "}, 
{ "Gujarat",  "6751",  "Gandhinagar", "Patel Amarish Jasvantlal", "OverAged",  " ","गुजरात",  "गांधीनगर", "पटेल अमरिश जसवंतलाल", " "}, 
{ "Gujarat",  "6752",  "Gandhinagar", "Vora Alimahmad Rajabhai", "OverAged",  " ","गुजरात",  "गांधीनगर", "वोरा अलीमहद राजभाई", " "}, 
{ "Gujarat",  "6753",  "Gandhinagar", "Makwana Prakashbhai Bahecharji", "CriminalCases",  " ","गुजरात",  "गांधीनगर", "मकवाना प्रकाशभाई बहेचरजी", " "}, 
{ "Gujarat",  "6756",  "Gandhinagar", "Rathod Valjibhai Becharbhai", "CriminalCases",  " ","गुजरात",  "गांधीनगर", "राठौड़ वलजीभाई बेचारभाई", " "}, 
{ "Gujarat",  "6757",  "Gandhinagar", "Khodabhai Lalajibhai Desai", "CriminalCases",  " ","गुजरात",  "गांधीनगर", "खोदाभाई लालजीभाई देसाई", " "}, 
{ "Gujarat",  "6758",  "Gandhinagar", "Pathan Firozkhan", "NotGraduate",  " ","गुजरात",  "गांधीनगर", "पठान फिरोजखान", " "}, 
{ "Gujarat",  "6856",  "Jamnagar", "Aamin Mamadbhai Safiya", "NotGraduate",  " ","गुजरात",  "जामनगर", "आमीन ममदभाई सफिया", " "}, 
{ "Gujarat",  "6857",  "Jamnagar", "Amandbhai", "OverAged",  " ","गुजरात",  "जामनगर", "Amandbhai", " "}, 
{ "Gujarat",  "6858",  "Jamnagar", "Chavada Ashok", "NotGraduate",  " ","गुजरात",  "जामनगर", "चावड़ा अशोक", " "}, 
{ "Gujarat",  "6859",  "Jamnagar", "Chauhan Dhiraj Kantilal", "CriminalCases",  " ","गुजरात",  "जामनगर", "चौहान धीरज कांतिलाल", " "}, 
{ "Gujarat",  "6861",  "Jamnagar", "Sumbhania Aamin", "NotGraduate",  " ","गुजरात",  "जामनगर", "सुंभानिया आमीन", " "}, 
{ "Gujarat",  "6862",  "Jamnagar", "Donga Jayantilal Arjanbhai", "NotGraduate",  " ","गुजरात",  "जामनगर", "डोंगा जयंतीलाल अर्जनभाई", " "}, 
{ "Gujarat",  "6863",  "Jamnagar", "Vallabhbhai Chanabhai Sojitra", "NotGraduate",  " ","गुजरात",  "जामनगर", "वल्लभभाई चनाभाई सोजित्रा", " "}, 
{ "Gujarat",  "6864",  "Jamnagar", "Kandoriya Mulubhai Ranmalbhai", "ForeignFunding",  " ","गुजरात",  "जामनगर", "कंदोरिया मुलुभाई रणमलभाई", " "}, 
{ "Gujarat",  "6865",  "Jamnagar", "Jadeja Bhavnaba", "NotGraduate",  " ","गुजरात",  "जामनगर", "जडेजा भावनबा", " "}, 
{ "Gujarat",  "6866",  "Jamnagar", "Makrani Ajazahmed", "NotGraduate",  " ","गुजरात",  "जामनगर", "मकरानी अजाजहम्मद", " "}, 
{ "Gujarat",  "6868",  "Jamnagar", "Bharat Ramjibhai Dagara", "NotGraduate",  " ","गुजरात",  "जामनगर", "भरत रामजीभाई डगरा", " "}, 
{ "Gujarat",  "6869",  "Jamnagar", "Chavada Shamjibhai", "NotGraduate",  " ","गुजरात",  "जामनगर", "चावड़ा शामजीभाई", " "}, 
{ "Gujarat",  "6870",  "Jamnagar", "Sapariya Vijaykumar Mansukhbhai", "NotGraduate",  " ","गुजरात",  "जामनगर", "सपरिया विजयकुमार मनसुखभाई", " "}, 
{ "Gujarat",  "6871",  "Jamnagar", "Alimamad Palani", "NotGraduate",  " ","गुजरात",  "जामनगर", "अलीमद पलानी", " "}, 
{ "Gujarat",  "6872",  "Jamnagar", "Popatputra Rafik Abubakar", "NotGraduate",  " ","गुजरात",  "जामनगर", "पोपटपुत्र रफिक अबूबकर", " "}, 
{ "Gujarat",  "6873",  "Jamnagar", "Bharkhani Karabhai Jivabhai", "NotGraduate",  " ","गुजरात",  "जामनगर", "भरखनी करभाई जीवाभाई", " "}, 
{ "Gujarat",  "6874",  "Jamnagar", "Dalvadi Nakum Rasik Lalji", "NotGraduate",  " ","गुजरात",  "जामनगर", "दलवडी नाकुम रसिक लालजी", " "}, 
{ "Gujarat",  "6875",  "Jamnagar", "Poonamben Hematbhai Maadam", "ForeignFunding",  " ","गुजरात",  "जामनगर", "पूनमबेन हेमतभाई मादम", " "}, 
{ "Gujarat",  "6876",  "Jamnagar", "Rabari Karshanbhai Jeshabhai", "NotGraduate",  " ","गुजरात",  "जामनगर", "रबारी कर्षभाई जेसभाई", " "}, 
{ "Gujarat",  "6877",  "Jamnagar", "Bathvar Nanji Amarshi", "NotGraduate",  " ","गुजरात",  "जामनगर", "बथवार नानजी अमरशी", " "}, 
{ "Gujarat",  "6879",  "Jamnagar", "Sahdevsinh Chudasama", "CriminalCases",  " ","गुजरात",  "जामनगर", "सहदेवसिंह चुडासमा", " "}, 
{ "Gujarat",  "6880",  "Jamnagar", "Nakum Narmadaben Khodalal", "NotGraduate",  " ","गुजरात",  "जामनगर", "नाकुम नर्मदाबेन खोडलाल", " "}, 
{ "Gujarat",  "6881",  "Jamnagar", "Bhanderi Amarshibhai Chhaganbhai", "NotGraduate",  " ","गुजरात",  "जामनगर", "भंडारी अमरसिभाई छगनभाई", " "}, 
{ "Gujarat",  "6882",  "Jamnagar", "Sama Yusuf", "CriminalCases",  " ","गुजरात",  "जामनगर", "साम युसूफ", " "}, 
{ "Gujarat",  "6883",  "Jamnagar", "Kachchhi Daudbhai Nathabhai", "NotGraduate",  " ","गुजरात",  "जामनगर", "कच्छी दाउदभाई नतभाई", " "}, 
{ "Gujarat",  "6885",  "Junagadh", "Vansh Punjabhai Bhimabhai", "ForeignFunding",  " ","गुजरात",  "जूनागढ़", "वंश पंजाबी भीमभाई", " "}, 
{ "Gujarat",  "6886",  "Junagadh", "Chudasama Rajeshbhai Naranbhai", "ForeignFunding",  " ","गुजरात",  "जूनागढ़", "चुडासमा राजेशभाई नारनभाई", " "}, 
{ "Gujarat",  "6888",  "Junagadh", "Panchabhai Bhayabhai Damaniya", "NotGraduate",  " ","गुजरात",  "जूनागढ़", "पंचभाई भयभाई दमानिया", " "}, 
{ "Gujarat",  "6889",  "Junagadh", "Deven Govindbhai Vanvi", "NotGraduate",  " ","गुजरात",  "जूनागढ़", "देवेन गोविंदभाई वनवी", " "}, 
{ "Gujarat",  "6890",  "Junagadh", "Rathod Nathabhai Vasharambhai", "OverAged",  " ","गुजरात",  "जूनागढ़", "राठौड़ नाथाभाई वाशरामभाई", " "}, 
{ "Gujarat",  "6891",  "Junagadh", "Zala Mukeshbhai Bharmalbhai", "CriminalCases",  " ","गुजरात",  "जूनागढ़", "ज़ला मुकेशभाई भारमलभाई", " "}, 
{ "Gujarat",  "6893",  "Junagadh", "Bhut Ashokbhai Bhimjibhai", "OverAged",  " ","गुजरात",  "जूनागढ़", "भुत अशोकभाई भीमजीभाई", " "}, 
{ "Gujarat",  "6894",  "Junagadh", "Pradipbhai Mavjibhai Tank", "NotGraduate",  " ","गुजरात",  "जूनागढ़", "प्रदीपभाई मावजीभाई टैंक", " "}, 
{ "Gujarat",  "6895",  "Junagadh", "Karia Dhirenbhai Amrutlal", "CriminalCases",  " ","गुजरात",  "जूनागढ़", "करिया धीरेनभाई अमृतलाल", " "}, 
{ "Gujarat",  "6675",  "Kachchh", "Chavda Pravinbhai Chanabhai", "NotGraduate",  " ","गुजरात",  "कच्छ", "चावड़ा प्रवीणभाई चनाभाई", " "}, 
{ "Gujarat",  "6676",  "Kachchh", "Dhirubhai Babulal Shrimali", "NotGraduate",  " ","गुजरात",  "कच्छ", "धीरूभाई बाबूलाल श्रीमाली", " "}, 
{ "Gujarat",  "6677",  "Kachchh", "Maheshwari Devjibhai Vachhiyabhai", "CriminalCases",  " ","गुजरात",  "कच्छ", "महेश्वरी देवजीभाई वाछियाभाई", " "}, 
{ "Gujarat",  "6678",  "Kachchh", "Naresh Naranbhai Maheshwari", "ForeignFunding",  " ","गुजरात",  "कच्छ", "नरेश नरनभाई माहेश्वरी", " "}, 
{ "Gujarat",  "6679",  "Kachchh", "Maru Manisha Bharat", "NotGraduate",  " ","गुजरात",  "कच्छ", "मारु मनीषा भरत", " "}, 
{ "Gujarat",  "6680",  "Kachchh", "Meghval Bhimjibhai Bhikhabhai", "NotGraduate",  " ","गुजरात",  "कच्छ", "मेघवाल भीमजीभाई भीखाभाई", " "}, 
{ "Gujarat",  "6681",  "Kachchh", "Chavda Vinod Lakhamshi", "ForeignFunding",  " ","गुजरात",  "कच्छ", "चावड़ा विनोद लखमशी", " "}, 
{ "Gujarat",  "6682",  "Kachchh", "Sondarva Baluben Maheshbhai", "NotGraduate",  " ","गुजरात",  "कच्छ", "सोंदरवा बलुबेन महेशभाई", " "}, 
{ "Gujarat",  "6683",  "Kachchh", "Lakhubhai Vaghela", "NotGraduate",  " ","गुजरात",  "कच्छ", "लखुभाई वाघेला", " "}, 
{ "Gujarat",  "6684",  "Kachchh", "Babulal Amarshi Vaghela", "NotGraduate",  " ","गुजरात",  "कच्छ", "बाबूलाल अमरशी वाघेला", " "}, 
{ "Gujarat",  "6928",  "Kheda", "Chauhan Devusinh", "ForeignFunding",  " ","गुजरात",  "खेड़ा", "चौहान देवूसिंह", " "}, 
{ "Gujarat",  "6929",  "Kheda", "Pathan Imtiyazkhan", "NotGraduate",  " ","गुजरात",  "खेड़ा", "पठान इम्तियाजखान", " "}, 
{ "Gujarat",  "6930",  "Kheda", "Bhailalbhai Pandav", "NotGraduate",  " ","गुजरात",  "खेड़ा", "भिलालभाई पांडव", " "}, 
{ "Gujarat",  "6931",  "Kheda", "Bimalbhai Shah", "ForeignFunding",  " ","गुजरात",  "खेड़ा", "बिमलभाई शाह", " "}, 
{ "Gujarat",  "6932",  "Kheda", "Patel Kamleshkumar", "NotGraduate",  " ","गुजरात",  "खेड़ा", "पटेल कमलेशकुमार", " "}, 
{ "Gujarat",  "6933",  "Kheda", "Pathan Aayashabanu", "NotGraduate",  " ","गुजरात",  "खेड़ा", "पठान आयशाबनु", " "}, 
{ "Gujarat",  "6934",  "Kheda", "Chauhan Parsottambhai", "NotGraduate",  " ","गुजरात",  "खेड़ा", "चौहान परसोत्तमभाई", " "}, 
{ "Gujarat",  "6711",  "Mahesana", "Thakor Mayurkumar Rupsangji", "NotGraduate",  " ","गुजरात",  "महेसाणा", "ठाकोर मयूरकुमार रूपसंगजी", " "}, 
{ "Gujarat",  "6712",  "Mahesana", "Patel Anitaben Ramabhai", "NotGraduate",  " ","गुजरात",  "महेसाणा", "पटेल अनिताबेन रामभाई", " "}, 
{ "Gujarat",  "6713",  "Mahesana", "Chauhan Prahladbhai", "OverAged",  " ","गुजरात",  "महेसाणा", "चौहान प्रह्लादभाई", " "}, 
{ "Gujarat",  "6714",  "Mahesana", "Prajapati Kanubhai Amatharam", "NotGraduate",  " ","गुजरात",  "महेसाणा", "प्रजापति कनुभाई अमथाराम", " "}, 
{ "Gujarat",  "6715",  "Mahesana", "Thakor Jayantiji Chunthaji", "NotGraduate",  " ","गुजरात",  "महेसाणा", "ठाकोर जयन्तीजी चूँथजी", " "}, 
{ "Gujarat",  "6716",  "Mahesana", "Patel Ambalal Talashibhai", "OverAged",  " ","गुजरात",  "महेसाणा", "पटेल अंबालाल तलाशीभाई", " "}, 
{ "Gujarat",  "6718",  "Mahesana", "Rathod Gulabsinh Dursinh", "NotGraduate",  " ","गुजरात",  "महेसाणा", "राठौड़ गुलाबसिंह दुरसिंह", " "}, 
{ "Gujarat",  "6720",  "Mahesana", "Shardaben Anilbhai Patel", "ForeignFunding",  " ","गुजरात",  "महेसाणा", "शारदाबेन अनिलभाई पटेल", " "}, 
{ "Gujarat",  "6721",  "Mahesana", "A. J. Patel", "ForeignFunding",  " ","गुजरात",  "महेसाणा", "एजे पटेल", " "}, 
{ "Gujarat",  "6722",  "Mahesana", "Thakor Bipinkumar Shankarji", "NotGraduate",  " ","गुजरात",  "महेसाणा", "ठाकोर बिपिनकुमार शंकरजी", " "}, 
{ "Gujarat",  "7011",  "Navsari", "Chauhan Nileshkumar Khushalbhai", "CriminalCases",  " ","गुजरात",  "नवसारी", "चौहान निलेशकुमार खुशालभाई", " "}, 
{ "Gujarat",  "7012",  "Navsari", "Ramjan Bhilubhai Mansuri", "NotGraduate",  " ","गुजरात",  "नवसारी", "रमजान भिलुभाई मंसूरी", " "}, 
{ "Gujarat",  "7013",  "Navsari", "Prakash Amarnath Shukla", "NotGraduate",  " ","गुजरात",  "नवसारी", "प्रकाश अमरनाथ शुक्ल", " "}, 
{ "Gujarat",  "7014",  "Navsari", "Saiyad Mehmud Ahmad", "NotGraduate",  " ","गुजरात",  "नवसारी", "सय्यद महमूद अहमद", " "}, 
{ "Gujarat",  "7016",  "Navsari", "Sohilkhaa Hashimkhaa Pathan", "NotGraduate",  " ","गुजरात",  "नवसारी", "सोहिलखा हाशिमखां पठान", " "}, 
{ "Gujarat",  "7017",  "Navsari", "Jawadkhan Sujatkhan Pathan", "NotGraduate",  " ","गुजरात",  "नवसारी", "जवदखन सुजातन पठान", " "}, 
{ "Gujarat",  "7018",  "Navsari", "Patel Dharmeshbhai", "ForeignFunding",  " ","गुजरात",  "नवसारी", "पटेल धर्मेशभाई", " "}, 
{ "Gujarat",  "7019",  "Navsari", "Shaikh Javeed Ahemad", "CriminalCases",  " ","गुजरात",  "नवसारी", "शेख जावेद अहमद", " "}, 
{ "Gujarat",  "7020",  "Navsari", "Amrutham Narsaiya", "NotGraduate",  " ","गुजरात",  "नवसारी", "अमृतम नरसैया", " "}, 
{ "Gujarat",  "7021",  "Navsari", "Chandansinh", "NotGraduate",  " ","गुजरात",  "नवसारी", "Chandansinh", " "}, 
{ "Gujarat",  "7023",  "Navsari", "Hiramaniben", "NotGraduate",  " ","गुजरात",  "नवसारी", "Hiramaniben", " "}, 
{ "Gujarat",  "7024",  "Navsari", "Shekh Hamid Ramjan", "CriminalCases",  " ","गुजरात",  "नवसारी", "शेख हामिद रमजान", " "}, 
{ "Gujarat",  "7025",  "Navsari", "Sachin Kinra", "NotGraduate",  " ","गुजरात",  "नवसारी", "सचिन किनरा", " "}, 
{ "Gujarat",  "7028",  "Navsari", "Pasvan Virendra", "NotGraduate",  " ","गुजरात",  "नवसारी", "पासवान वीरेंद्र", " "}, 
{ "Gujarat",  "7029",  "Navsari", "Govindbhai Laxmanbhai Rathod", "NotGraduate",  " ","गुजरात",  "नवसारी", "गोविंदभाई लक्ष्मणभाई राठौड़", " "}, 
{ "Gujarat",  "7031",  "Navsari", "Anishbhai Gaffarbhai Bhimani", "NotGraduate",  " ","गुजरात",  "नवसारी", "अनिशभाई गफ्फारभाई भीमनी", " "}, 
{ "Gujarat",  "7032",  "Navsari", "Patil Chandrakant", "ForeignFunding",  " ","गुजरात",  "नवसारी", "पाटिल चंद्रकांत", " "}, 
{ "Gujarat",  "7034",  "Navsari", "Shaikh Saeed Inayat", "NotGraduate",  " ","गुजरात",  "नवसारी", "शेख सईद इनायत", " "}, 
{ "Gujarat",  "7035",  "Navsari", "Sharma Rajmal Mohanlal", "NotGraduate",  " ","गुजरात",  "नवसारी", "शर्मा राजमल मोहनलाल", " "}, 
{ "Gujarat",  "6935",  "Panchmahal", "Patel Virendrakumar", "CriminalCases",  " ","गुजरात",  "पंचमहल", "पटेल वीरेंद्रकुमार", " "}, 
{ "Gujarat",  "6937",  "Panchmahal", "Vechatbhai Khant", "ForeignFunding",  " ","गुजरात",  "पंचमहल", "वीचभाई खांट", " "}, 
{ "Gujarat",  "6938",  "Panchmahal", "Lalabhai Gadhavi", "CriminalCases",  " ","गुजरात",  "पंचमहल", "लालभाई गढ़वी", " "}, 
{ "Gujarat",  "6939",  "Panchmahal", "Ratansinh Rathod", "ForeignFunding",  " ","गुजरात",  "पंचमहल", "रतनसिंह राठौड़", " "}, 
{ "Gujarat",  "6940",  "Panchmahal", "Shaikh Kalim", "NotGraduate",  " ","गुजरात",  "पंचमहल", "शेख कलीम", " "}, 
{ "Gujarat",  "6699",  "Patan", "Bhoraniya Soyabbhai Hasambhai", "CriminalCases",  " ","गुजरात",  "पाटन", "भोरान्य सोयाभाई हसाम्भाई", " "}, 
{ "Gujarat",  "6700",  "Patan", "Prajapati Jayantibhai Devabhai", "NotGraduate",  " ","गुजरात",  "पाटन", "प्रजापति जयंतीभाई देवभाई", " "}, 
{ "Gujarat",  "6701",  "Patan", "Umedbhai Haribhai Nai", "NotGraduate",  " ","गुजरात",  "पाटन", "उम्मेदभाई हरिभाई नाई", " "}, 
{ "Gujarat",  "6702",  "Patan", "Makwana Vaghabhai Maganbhai", "NotGraduate",  " ","गुजरात",  "पाटन", "मकवाना वगभाई मगनभाई", " "}, 
{ "Gujarat",  "6704",  "Patan", "Abdulkudus Abdulmajid Molapiya", "NotGraduate",  " ","गुजरात",  "पाटन", "अब्दुलकुद्दुस अब्दुलमाजिद मोलापिया", " "}, 
{ "Gujarat",  "6705",  "Patan", "Pandya Pravinkumar Tulsidas", "NotGraduate",  " ","गुजरात",  "पाटन", "पंड्या प्रवीणकुमार तुलसीदास", " "}, 
{ "Gujarat",  "6706",  "Patan", "Chaudhari Shaileshkumar Kanjibhai", "NotGraduate",  " ","गुजरात",  "पाटन", "चौधरी शैलेशकुमार कांजीभाई", " "}, 
{ "Gujarat",  "6707",  "Patan", "Thakor Jagdishbhai", "ForeignFunding",  " ","गुजरात",  "पाटन", "ठाकोर जगदीशभाई", " "}, 
{ "Gujarat",  "6708",  "Patan", "Dabhi Bharatsinhji Shankarji", "ForeignFunding",  " ","गुजरात",  "पाटन", "डाभी भरतसिंहजी शंकरजी", " "}, 
{ "Gujarat",  "6709",  "Patan", "Rathod Govindbhai Bhikhabhai", "NotGraduate",  " ","गुजरात",  "पाटन", "राठौड़ गोविंदभाई भीखाभाई", " "}, 
{ "Gujarat",  "6839",  "Porbandar", "Rabari Dasabhai Karabhai", "CriminalCases",  " ","गुजरात",  "पोरबंदर", "रबारी दसभाई करभाई", " "}, 
{ "Gujarat",  "6840",  "Porbandar", "Bhargav Joshi", "NotGraduate",  " ","गुजरात",  "पोरबंदर", "भार्गव जोशी", " "}, 
{ "Gujarat",  "6841",  "Porbandar", "Rameshbhai Dhaduk", "ForeignFunding",  " ","गुजरात",  "पोरबंदर", "रमेशभाई धाडुक", " "}, 
{ "Gujarat",  "6843",  "Porbandar", "Riyaz Suriya", "CriminalCases",  " ","गुजरात",  "पोरबंदर", "रियाज सूरिया", " "}, 
{ "Gujarat",  "6845",  "Porbandar", "Rank Jigneshbhai", "NotGraduate",  " ","गुजरात",  "पोरबंदर", "रैंक जिग्नेशभाई", " "}, 
{ "Gujarat",  "6846",  "Porbandar", "Rathod Dayabhai", "NotGraduate",  " ","गुजरात",  "पोरबंदर", "राठौड़ दयाभाई", " "}, 
{ "Gujarat",  "6847",  "Porbandar", "Kadavala Samatbha", "NotGraduate",  " ","गुजरात",  "पोरबंदर", "कदवला समताभा", " "}, 
{ "Gujarat",  "6848",  "Porbandar", "Reshma Patel", "NotGraduate",  " ","गुजरात",  "पोरबंदर", "रेशमा पटेल", " "}, 
{ "Gujarat",  "6850",  "Porbandar", "Ramani Vimalbhai", "NotGraduate",  " ","गुजरात",  "पोरबंदर", "रमणी विमलभाई", " "}, 
{ "Gujarat",  "6851",  "Porbandar", "Lalit Vasoya", "ForeignFunding",  " ","गुजरात",  "पोरबंदर", "ललित वसोया", " "}, 
{ "Gujarat",  "6852",  "Porbandar", "Aantroliya Karabhai", "NotGraduate",  " ","गुजरात",  "पोरबंदर", "आंत्रोलिया करभाई", " "}, 
{ "Gujarat",  "6853",  "Porbandar", "Unadkat Prakashbha", "NotGraduate",  " ","गुजरात",  "पोरबंदर", "उनादकट प्रकाशभा", " "}, 
{ "Gujarat",  "6854",  "Porbandar", "Kirtikumar Marvaniya", "NotGraduate",  " ","गुजरात",  "पोरबंदर", "कीर्तिकुमार मारवानिया", " "}, 
{ "Gujarat",  "6829",  "Rajkot", "Chauhan Manojbhai", "NotGraduate",  " ","गुजरात",  "राजकोट", "चौहान मनोजभाई", " "}, 
{ "Gujarat",  "6830",  "Rajkot", "Dengada Pravinbhai", "CriminalCases",  " ","गुजरात",  "राजकोट", "डेंगडा प्रवीणभाई", " "}, 
{ "Gujarat",  "6831",  "Rajkot", "Amardas Desani", "CriminalCases",  " ","गुजरात",  "राजकोट", "अमरदास देसानी", " "}, 
{ "Gujarat",  "6832",  "Rajkot", "Jaspalsinh Tomar", "NotGraduate",  " ","गुजरात",  "राजकोट", "जसपालसिंह तोमर", " "}, 
{ "Gujarat",  "6833",  "Rajkot", "Parmar Vijay", "CriminalCases",  " ","गुजरात",  "राजकोट", "परमार विजय", " "}, 
{ "Gujarat",  "6834",  "Rajkot", "Rakeshbhai", "NotGraduate",  " ","गुजरात",  "राजकोट", "Rakeshbhai", " "}, 
{ "Gujarat",  "6835",  "Rajkot", "J. B. Chauhan", "NotGraduate",  " ","गुजरात",  "राजकोट", "जेबी चौहान", " "}, 
{ "Gujarat",  "6836",  "Rajkot", "Kundaria Mohanbhai", "ForeignFunding",  " ","गुजरात",  "राजकोट", "कुंदरिया मोहनभाई", " "}, 
{ "Gujarat",  "6837",  "Rajkot", "Kagathara Lalitbhai", "ForeignFunding",  " ","गुजरात",  "राजकोट", "कगथरा ललिताभाई", " "}, 
{ "Gujarat",  "6723",  "Sabarkantha", "Jadeja Indravijaysinh", "NotGraduate",  " ","गुजरात",  "साबरकांठा", "जडेजा इंद्रविजयसिंह", " "}, 
{ "Gujarat",  "6724",  "Sabarkantha", "Luhar Hafizhusen", "NotGraduate",  " ","गुजरात",  "साबरकांठा", "लुहार हफीज़ुसेन", " "}, 
{ "Gujarat",  "6725",  "Sabarkantha", "Mayursinh Vanrajsinh Zala", "NotGraduate",  " ","गुजरात",  "साबरकांठा", "मयूरसिंह वनराजसिंह जाला", " "}, 
{ "Gujarat",  "6729",  "Sabarkantha", "Pathan Aiyubkhan Ajabakhan", "NotGraduate",  " ","गुजरात",  "साबरकांठा", "पठान अयूबखान अजबखान", " "}, 
{ "Gujarat",  "6731",  "Sabarkantha", "Laxmishankar Madhusudan Joshi", "OverAged",  " ","गुजरात",  "साबरकांठा", "लक्ष्मीशंकर मधुसूदन जोशी", " "}, 
{ "Gujarat",  "6732",  "Sabarkantha", "Lata Babubhai Nathaji", "NotGraduate",  " ","गुजरात",  "साबरकांठा", "लता बाबूभाई नाथजी", " "}, 
{ "Gujarat",  "6733",  "Sabarkantha", "Sanghani Mustakbhai Jamalbhai", "CriminalCases",  " ","गुजरात",  "साबरकांठा", "संघानी मुस्तकभाई जमालभाई", " "}, 
{ "Gujarat",  "6734",  "Sabarkantha", "Solanki Maganbhai Lakhabhai", "CriminalCases",  " ","गुजरात",  "साबरकांठा", "सोलंकी मगनभाई लखभाई", " "}, 
{ "Gujarat",  "6735",  "Sabarkantha", "Raval Rajubhai Punjabhai", "NotGraduate",  " ","गुजरात",  "साबरकांठा", "रावल राजुभाई पंजाबी", " "}, 
{ "Gujarat",  "6736",  "Sabarkantha", "Thakor Rajendrasinh", "ForeignFunding",  " ","गुजरात",  "साबरकांठा", "ठाकोर राजेंद्रसिंह", " "}, 
{ "Gujarat",  "6737",  "Sabarkantha", "Patel Keshavlal Gangarambhai", "NotGraduate",  " ","गुजरात",  "साबरकांठा", "पटेल केशवलाल गंगारामभाई", " "}, 
{ "Gujarat",  "6738",  "Sabarkantha", "Zala Dalpatsinh Motisinh", "NotGraduate",  " ","गुजरात",  "साबरकांठा", "ज़ला दलपतसिंह मोतीसिंह", " "}, 
{ "Gujarat",  "6739",  "Sabarkantha", "Nareshkumar Rameshbhai Patel", "NotGraduate",  " ","गुजरात",  "साबरकांठा", "नरेशकुमार रमेशभाई पटेल", " "}, 
{ "Gujarat",  "6741",  "Sabarkantha", "Rathod Dipsinh Shankarsinh", "ForeignFunding",  " ","गुजरात",  "साबरकांठा", "राठौड़ दिपसिंह शंकरसिंह", " "}, 
{ "Gujarat",  "6742",  "Sabarkantha", "Vikrambhai Bahecharbhai Makwana", "NotGraduate",  " ","गुजरात",  "साबरकांठा", "विक्रमभाई बहेचरभाई मकवाना", " "}, 
{ "Gujarat",  "6998",  "Surat", "Gautamraj G. Hindustani", "NotGraduate",  " ","गुजरात",  "सूरत", "गौतमराज जी। हिंदुस्तानी", " "}, 
{ "Gujarat",  "7001",  "Surat", "Tulasibhai Laxmanbhai Dakhara", "NotGraduate",  " ","गुजरात",  "सूरत", "तुलसीभाई लक्ष्मणभाई डखारा", " "}, 
{ "Gujarat",  "7002",  "Surat", "Dineshbhai Chaturbhai Jikadara", "NotGraduate",  " ","गुजरात",  "सूरत", "दिनेशभाई चतुर्भाई जिकदारा", " "}, 
{ "Gujarat",  "7004",  "Surat", "Baraiya Rameshbhai Parsottambhai", "NotGraduate",  " ","गुजरात",  "सूरत", "बरैया रमेशभाई परसोत्तमभाई", " "}, 
{ "Gujarat",  "7005",  "Surat", "Surwade Santosh Avdhut", "NotGraduate",  " ","गुजरात",  "सूरत", "सुरवडे संतोष अवधूत", " "}, 
{ "Gujarat",  "7006",  "Surat", "Dipakbhai Ramnikbhai Gangani", "NotGraduate",  " ","गुजरात",  "सूरत", "दिपकभाई रमणिकभाई गंगानी", " "}, 
{ "Gujarat",  "7007",  "Surat", "Jardosh Darshnaben Vikrambhai", "ForeignFunding",  " ","गुजरात",  "सूरत", "जरदोष दर्शनाबेन विक्रमभाई", " "}, 
{ "Gujarat",  "7009",  "Surat", "Dhameliya Piyushkumar Vallabhabhai", "NotGraduate",  " ","गुजरात",  "सूरत", "धमालिया पीयूषकुमार वल्लभभाई", " "}, 
{ "Gujarat",  "7010",  "Surat", "Ashok Vallabhbhai Pate", "ForeignFunding",  " ","गुजरात",  "सूरत", "अशोक वल्लभभाई पाटे", " "}, 
{ "Gujarat",  "6798",  "Surendranagar", "Mahendrabhai Munjpara", "ForeignFunding",  " ","गुजरात",  "सुरेंद्रनगर", "महेंद्रभाई मुंजपारा", " "}, 
{ "Gujarat",  "6799",  "Surendranagar", "Hanifbhai Kayabhai Katiya", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "हनीफ़भाई कयाभाई कटिया", " "}, 
{ "Gujarat",  "6800",  "Surendranagar", "Bhupatbhai Laljibhai Solanki", "CriminalCases",  " ","गुजरात",  "सुरेंद्रनगर", "भूपतभाई लालजीभाई सोलंकी", " "}, 
{ "Gujarat",  "6801",  "Surendranagar", "Sardarkhan Malek", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "सरदारखान मालेक", " "}, 
{ "Gujarat",  "6802",  "Surendranagar", "Goltar Bhagvanbhai Maiyabhai", "CriminalCases",  " ","गुजरात",  "सुरेंद्रनगर", "गोलतर भगवानभाई मैयाभाई", " "}, 
{ "Gujarat",  "6803",  "Surendranagar", "Oghadbhai Mer", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "औघड़भाई मेर", " "}, 
{ "Gujarat",  "6804",  "Surendranagar", "Bhanjibhai Shekhava", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "भनजीभाई शेखवा", " "}, 
{ "Gujarat",  "6805",  "Surendranagar", "Bhathaniya Faridbhai Amijibhai", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "भथानिया फरीदभाई अमीजीभाई", " "}, 
{ "Gujarat",  "6806",  "Surendranagar", "Thakor Jaguji Kuvarji", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "ठाकोर जगुजी कुवरजी", " "}, 
{ "Gujarat",  "6807",  "Surendranagar", "Kolipatel Somabhai", "ForeignFunding",  " ","गुजरात",  "सुरेंद्रनगर", "कोलीपटेल सोमाभाई", " "}, 
{ "Gujarat",  "6808",  "Surendranagar", "Karimbhai Adambhai Urfe Bababhai", "OverAged",  " ","गुजरात",  "सुरेंद्रनगर", "करमभाई अधमभाई उर्फ़ बाबाभाई", " "}, 
{ "Gujarat",  "6809",  "Surendranagar", "Vaghela Dahyabhai Khengarbhai", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "वाघेला भयभाई खंगारभाई", " "}, 
{ "Gujarat",  "6810",  "Surendranagar", "Makwana Dalpatbhai Lagharbhai", "OverAged",  " ","गुजरात",  "सुरेंद्रनगर", "मकवाना दलपतभाई लगरभाई", " "}, 
{ "Gujarat",  "6811",  "Surendranagar", "Makvana Kamabhai", "OverAged",  " ","गुजरात",  "सुरेंद्रनगर", "मकवाना कामाभाई", " "}, 
{ "Gujarat",  "6812",  "Surendranagar", "Daniya Anirudhbhai Gandabhai", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "दानिया अनिरुद्धभाई गंडभाई", " "}, 
{ "Gujarat",  "6813",  "Surendranagar", "Dekavadiya Darjibhai Maganbhai", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "देवकादिया दर्जीभाई मगनभाई", " "}, 
{ "Gujarat",  "6814",  "Surendranagar", "Rathod Ashokbhai Vithathalbhai", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "राठौड़ अशोकभाई विठ्ठलभाई", " "}, 
{ "Gujarat",  "6816",  "Surendranagar", "Salimbhai Shahbudinbhai Pathan", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "सलीमभाई शाहबुद्दीनभाई पठान", " "}, 
{ "Gujarat",  "6817",  "Surendranagar", "Patel Baldevbhai", "OverAged",  " ","गुजरात",  "सुरेंद्रनगर", "पटेल बलदेवभाई", " "}, 
{ "Gujarat",  "6818",  "Surendranagar", "Vaghela Prakashbhai Bachubhai", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "वाघेला प्रकाशभाई बच्चुभाई", " "}, 
{ "Gujarat",  "6820",  "Surendranagar", "Koli Rameshbhai Virsangbhai Vaghela", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "कोली रमेशभाई विरसांगभाई वाघेला", " "}, 
{ "Gujarat",  "6821",  "Surendranagar", "Dost Mer", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "दोस्त मेर", " "}, 
{ "Gujarat",  "6822",  "Surendranagar", "Parmar Ghoghjibhai Kanjibhai", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "परमार घोघजीभाई कंजीभाई", " "}, 
{ "Gujarat",  "6823",  "Surendranagar", "Koli Patel Laljibhai Chaturbhai", "CriminalCases",  " ","गुजरात",  "सुरेंद्रनगर", "कोली पटेल लालजीभाई चतुर्भाई", " "}, 
{ "Gujarat",  "6824",  "Surendranagar", "Sapra Vipul R.", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "सपरा विपुल आर।", " "}, 
{ "Gujarat",  "6825",  "Surendranagar", "Jargela Hasanbhai Abdulbhai", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "जरगेला हसनभाई अब्दुलभाई", " "}, 
{ "Gujarat",  "6826",  "Surendranagar", "Kalubhai Malubhai Vadaliya", "OverAged",  " ","गुजरात",  "सुरेंद्रनगर", "कालुभाई मलुभाई वडालिया", " "}, 
{ "Gujarat",  "6828",  "Surendranagar", "Naresh Makwana", "NotGraduate",  " ","गुजरात",  "सुरेंद्रनगर", "नरेश मकवाना", " "}, 
{ "Gujarat",  "6948",  "Vadodara", "Prashant Patel", "ForeignFunding",  " ","गुजरात",  "वडोदरा", "प्रशांत पटेल", " "}, 
{ "Gujarat",  "6950",  "Vadodara", "Shri Patel Kalidas Motibhai", "OverAged",  " ","गुजरात",  "वडोदरा", "श्री पटेल कालिदास मोतीभाई", " "}, 
{ "Gujarat",  "6951",  "Vadodara", "Ranjanben Bhatt", "ForeignFunding",  " ","गुजरात",  "वडोदरा", "रंजनबेन भट्ट", " "}, 
{ "Gujarat",  "6954",  "Vadodara", "Mohsimmiya(Saiyad Mohsin Bapu)", "NotGraduate",  " ","गुजरात",  "वडोदरा", "मोहसिमिया (सय्यद मोहसिन बापू)", " "}, 
{ "Gujarat",  "6955",  "Vadodara", "Gohil Rinku", "NotGraduate",  " ","गुजरात",  "वडोदरा", "गोहिल रिंकू", " "}, 
{ "Gujarat",  "6956",  "Vadodara", "Yasinali Polra", "NotGraduate",  " ","गुजरात",  "वडोदरा", "यासिनाली पोला", " "}, 
{ "Gujarat",  "6957",  "Vadodara", "Jat Subhas Singh Brijlal", "CriminalCases",  " ","गुजरात",  "वडोदरा", "जाट सुभाष सिंह बृजलाल", " "}, 
{ "Gujarat",  "7036",  "Valsad", "Dr.K.C.Patel", "ForeignFunding",  " ","गुजरात",  "वलसाड", "Dr.KCPatel", " "}, 
{ "Gujarat",  "7037",  "Valsad", "Chaudhari Jitubhai Harjibhai", "ForeignFunding",  " ","गुजरात",  "वलसाड", "चौधरी जीतूभाई हरजीभाई", " "}, 
{ "Gujarat",  "7039",  "Valsad", "Patel Nareshbhai Babubhai", "NotGraduate",  " ","गुजरात",  "वलसाड", "पटेल नरेशभाई बाबूभाई", " "}, 
{ "Gujarat",  "7040",  "Valsad", "Patel Umeshbhai Maganbhai", "NotGraduate",  " ","गुजरात",  "वलसाड", "पटेल उमेशभाई मगनभाई", " "}, 
{ "Gujarat",  "7041",  "Valsad", "Babubhai Talaviya", "OverAged",  " ","गुजरात",  "वलसाड", "बाबूभाई तलाविया", " "}, 
{ "Gujarat",  "7042",  "Valsad", "Kishorbhai Ramanbhai Patel", "NotGraduate",  " ","गुजरात",  "वलसाड", "किशोरभाई रमनभाई पटेल", " "}, 
{ "Gujarat",  "7043",  "Valsad", "Patel Pankajbhai Lallubhai", "NotGraduate",  " ","गुजरात",  "वलसाड", "पटेल पंकजभाई लल्लूभाई", " "}, 
};

}