/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Haryana {
    public static final String[][] green_bucket = {
            {"Haryana", "Ambala", "Arun Kumar", "Communist Party of India", "17Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12133", "हरियाणा", "अंबाला", "अरुण कुमार", "भारतीय कम्युनिस्ट पार्टी"},
            {"Haryana", "Ambala", "Prithvi Raj", "Aam Aadmi Party", "3.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12976", "हरियाणा", "अंबाला", "पृथ्वी राज", "आम आदमी पार्टी"},
            {"Haryana", "Ambala", "Anil Kumar", "Republican Party of India (Athawale)", "16.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12134", "हरियाणा", "अंबाला", "अनिल कुमार", "भारतीय रिपब्लिकन पार्टी (अठावले)"},
            {"Haryana", "Ambala", "Suraj Bhan", "Independent", "73.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12991", "हरियाणा", "अंबाला", "सूरज भान", "निर्दलीय"},
            {"Haryana", "Ambala", "Varun Kumar Jaglan", "Peoples Party of India (Democratic)", "4.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12978", "हरियाणा", "अंबाला", "वरुण कुमार जगलान", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
            {"Haryana", "Ambala", "Suraj Bhan Narwal", "Pragatishil Samajwadi Party (Lohia)", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12981", "हरियाणा", "अंबाला", "सूरजभान नरवाल", "प्रगति समाजवादी पार्टी (लोहिया)"},
            {"Haryana", "Ambala", "Beta Mam Chand Rattuwala", "Independent", "28.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12989", "हरियाणा", "अंबाला", "बेटा मम चंद रत्तुवाला", "निर्दलीय"},
            {"Haryana", "Bhiwani Mahendragarh", "Sudhir Kumar", "Independent", "77.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13200", "हरियाणा", "भिवानी-महेंद्रगढ़", "सुधीर कुमार", "निर्दलीय"},
            {"Haryana", "Bhiwani Mahendragarh", "Dharambir Singh S/0 Fateh Singh", "Independent", "46.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13194", "हरियाणा", "भिवानी-महेंद्रगढ़", "धर्मबीर सिंह एस / 0 फतेह सिंह", "निर्दलीय"},
            {"Haryana", "Bhiwani Mahendragarh", "Satya Pal", "Independent", "2.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13199", "हरियाणा", "भिवानी-महेंद्रगढ़", "सत्य पाल", "निर्दलीय"},
            {"Haryana", "Bhiwani Mahendragarh", "Rajnish Kumar", "Independent", "77.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13195", "हरियाणा", "भिवानी-महेंद्रगढ़", "रजनीश कुमार", "निर्दलीय"},
            {"Haryana", "Bhiwani Mahendragarh", "Om Parkash", "Socialist Unity Centre of India (Communist)", "4.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12142", "हरियाणा", "भिवानी-महेंद्रगढ़", "ओम प्रकाश", "भारतीय समाजवादी एकता केंद्र (कम्युनिस्ट)"},
            {"Haryana", "Bhiwani Mahendragarh", "Vinod Kumar", "Independent", "6.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13198", "हरियाणा", "भिवानी-महेंद्रगढ़", "विनोद कुमार", "निर्दलीय"},
            {"Haryana", "Bhiwani Mahendragarh", "Lalit", "Independent", "20.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13197", "हरियाणा", "भिवानी-महेंद्रगढ़", "ललित", "निर्दलीय"},
            {"Haryana", "Bhiwani Mahendragarh", "Swati Yadav", "Jannayak Janta Party", "9.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13193", "हरियाणा", "भिवानी-महेंद्रगढ़", "स्वाति यादव", "जननायक जनता पार्टी"},
            {"Haryana", "Bhiwani Mahendragarh", "Ramesh Rao Pilot", "Loktanter Suraksha Party", "9.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13189", "हरियाणा", "भिवानी-महेंद्रगढ़", "रमेश राव पायलट", "लोकतन्त्र सुरक्षा पार्टी"},
            {"Haryana", "Bhiwani Mahendragarh", "Mohd. Irfan", "Bharat Prabhat Party", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12143", "हरियाणा", "भिवानी-महेंद्रगढ़", "मोहम्मद। इरफान", "भारत प्रभात पार्टी"},
            {"Haryana", "Faridabad", "Vijender Kumar Kasana", "Bhartiya Kisan Party", "2.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12153", "हरियाणा", "फरीदाबाद", "विजेंद्र कुमार कसाना", "भारतीय किसान पार्टी"},
            {"Haryana", "Faridabad", "K P Singh", "Independent", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13297", "हरियाणा", "फरीदाबाद", "केपी सिंह", "निर्दलीय"},
            {"Haryana", "Faridabad", "Pradeep Kumar", "Tola Party", "78Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13304", "हरियाणा", "फरीदाबाद", "प्रदीप कुमार", "टोला पार्टी"},
            {"Haryana", "Faridabad", "Manoj", "Independent", "2.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12151", "हरियाणा", "फरीदाबाद", "मनोज", "निर्दलीय"},
            {"Haryana", "Faridabad", "Hari Shankar Rajvans", "Adim Bhartiya Dal", "11.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12147", "हरियाणा", "फरीदाबाद", "हरि शंकर राजवंश", "आदिम भारतीय दल"},
            {"Haryana", "Faridabad", "Shyamvir", "Rashtriya Lokswaraj Party", "73.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13302", "हरियाणा", "फरीदाबाद", "Shyamvir", "राष्ट्रीय लोकसुराज पार्टी"},
            {"Haryana", "Faridabad", "Hari Chand", "Peoples Party of India (Democratic)", "45.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13301", "हरियाणा", "फरीदाबाद", "हरि चंद", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
            {"Haryana", "Faridabad", "Tika Ram", "Independent", "4.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13298", "हरियाणा", "फरीदाबाद", "टीका राम", "निर्दलीय"},
            {"Haryana", "Faridabad", "Amit Singh Patel", "Independent", "8.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13294", "हरियाणा", "फरीदाबाद", "अमित सिंह पटेल", "निर्दलीय"},
            {"Haryana", "Faridabad", "C A Shukla", "Independent", "13.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13296", "हरियाणा", "फरीदाबाद", "सीए शुक्ला", "निर्दलीय"},
            {"Haryana", "Gurgaon", "Advocate Parveen Yadav Wazirabad", "Akhil Bharatiya Jan Sangh", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13033", "हरियाणा", "गुडगाँव", "अधिवक्ता परवीन यादव वजीराबाद", "अखिल भारतीय जनसंघ"},
            {"Haryana", "Gurgaon", "Virender Singh", "Independent", "3.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12161", "हरियाणा", "गुडगाँव", "वीरेंद्र सिंह", "निर्दलीय"},
            {"Haryana", "Gurgaon", "Col. Dharam Pal Singh Raghava", "Rashtra Nirman Party", "2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13041", "हरियाणा", "गुडगाँव", "कर्नल धर्मपाल सिंह राघव", "राष्ट्र निर्माण पार्टी"},
            {"Haryana", "Gurgaon", "Jawahar Singh Pahal", "Bhartiya Shakti Chetna Party", "3.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13035", "हरियाणा", "गुडगाँव", "जवाहर सिंह पहल", "भारतीय शक्ति चेतना पार्टी"},
            {"Haryana", "Gurgaon", "Ramesh Kumar", "Rashtriya Sahara Party", "1.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13042", "हरियाणा", "गुडगाँव", "रमेश कुमार", "राष्ट्रीय सहारा पार्टी"},
            {"Haryana", "Gurgaon", "Dr. Mehmood Khan", "Jannayak Janta Party", "24.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13039", "हरियाणा", "गुडगाँव", "डॉ। महमूद खान", "जननायक जनता पार्टी"},
            {"Haryana", "Gurgaon", "Pawan Nehra", "Independent", "11.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13528", "हरियाणा", "गुडगाँव", "पवन नेहरा", "निर्दलीय"},
            {"Haryana", "Gurgaon", "Virender Rana", "INLD", "102.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13038", "हरियाणा", "गुडगाँव", "वीरेंद्र राणा", "इनेलो"},
            {"Haryana", "Gurgaon", "Rais Ahmad", "Bahujan Samaj Party", "45.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12163", "हरियाणा", "गुडगाँव", "रईस अहमद", "बहुजन समाज पार्टी"},
            {"Haryana", "Hisar", "Atam Parkash", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12166", "हरियाणा", "हिसार", "आतम प्रकाशम", "निर्दलीय"},
            {"Haryana", "Hisar", "Shashi Bharat Bhushan", "Pragatishil Samajwadi Party (Lohia)", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13247", "हरियाणा", "हिसार", "शशि भारत भूषण", "प्रगति समाजवादी पार्टी (लोहिया)"},
            {"Haryana", "Hisar", "Dara Singh", "Bhartiya Janraj Party", "1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13245", "हरियाणा", "हिसार", "दारा सिंह", "भारतीय जनराज पार्टी"},
            {"Haryana", "Hisar", "Sukhbir Singh", "Communist Party of India (Marxist)", "14.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12165", "हरियाणा", "हिसार", "सुखबीर सिंह", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
            {"Haryana", "Hisar", "Vikas Godara", "Rashtriya Lokswaraj Party", "3.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13246", "हरियाणा", "हिसार", "विकास गोदारा", "राष्ट्रीय लोकसुराज पार्टी"},
            {"Haryana", "Hisar", "Sudhir Godara", "Independent", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13252", "हरियाणा", "हिसार", "सुधीर गोदारा", "निर्दलीय"},
            {"Haryana", "Hisar", "Bajrang Vats", "Independent", "31.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13254", "हरियाणा", "हिसार", "बजरंग वत्स", "निर्दलीय"},
            {"Haryana", "Hisar", "Sandeep", "Bharat Prabhat Party", "23.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12172", "हरियाणा", "हिसार", "संदीप", "भारत प्रभात पार्टी"},
            {"Haryana", "Hisar", "Dushyant Chautala", "Jannayak Janta Party", "76.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12171", "हरियाणा", "हिसार", "दुष्यंत चौटाला", "जननायक जनता पार्टी"},
            {"Haryana", "Hisar", "Pawan Kumar", "Rashtriya Bhagidari Samaj Party", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12168", "हरियाणा", "हिसार", "पवन कुमार", "राष्ट्रीय भगवान समाज पार्टी"},
            {"Haryana", "Karnal", "Naresh Kumar", "Pragatishil Samajwadi Party (Lohia)", "2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12507", "हरियाणा", "करनाल", "नरेश कुमार", "प्रगति समाजवादी पार्टी (लोहिया)"},
            {"Haryana", "Karnal", "Krishan Kumar Aggarwal", "Aam Aadmi Party", "4.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12506", "हरियाणा", "करनाल", "कृष्ण कुमार अग्रवाल", "आम आदमी पार्टी"},
            {"Haryana", "Karnal", "Parmod Kumar Sharma", "Independent", "95.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12510", "हरियाणा", "करनाल", "प्रमोद कुमार शर्मा", "निर्दलीय"},
            {"Haryana", "Kurukshetra", "Raj Kumari", "Bharat Prabhat Party", "22000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13279", "हरियाणा", "कुरुक्षेत्र", "राज कुमारी", "भारत प्रभात पार्टी"},
            {"Haryana", "Kurukshetra", "Roshan Lal Muwal", "Independent", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13286", "हरियाणा", "कुरुक्षेत्र", "रोशन लाल मुवाल", "निर्दलीय"},
            {"Haryana", "Kurukshetra", "Vikram Singh", "Bhartiya Shakti Chetna Party", "25378", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12186", "हरियाणा", "कुरुक्षेत्र", "विक्रम सिंह", "भारतीय शक्ति चेतना पार्टी"},
            {"Haryana", "Kurukshetra", "Ashwini Sharma Hrittwal", "Independent", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12181", "हरियाणा", "कुरुक्षेत्र", "अश्विनी शर्मा ह्रितवाल", "निर्दलीय"},
            {"Haryana", "Kurukshetra", "Subhash", "Pragatishil Samajwadi Party (Lohia)", "9.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13281", "हरियाणा", "कुरुक्षेत्र", "सुभाष", "प्रगति समाजवादी पार्टी (लोहिया)"},
            {"Haryana", "Kurukshetra", "Jai Bhagwan", "Jannayak Janta Party", "13.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13276", "हरियाणा", "कुरुक्षेत्र", "जय भगवान", "जननायक जनता पार्टी"},
            {"Haryana", "Kurukshetra", "Shashi", "Bahujan Samaj Party", "5.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13275", "हरियाणा", "कुरुक्षेत्र", "शशि", "बहुजन समाज पार्टी"},
            {"Haryana", "Kurukshetra", "Kanwaljit Singh", "Independent", "5.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12178", "हरियाणा", "कुरुक्षेत्र", "कंवलजीत सिंह", "निर्दलीय"},
            {"Haryana", "Kurukshetra", "Sachin Gaba", "Independent", "41.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12182", "हरियाणा", "कुरुक्षेत्र", "सचिन गाबा", "निर्दलीय"},
            {"Haryana", "Kurukshetra", "Satish Kumar Singal", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13288", "हरियाणा", "कुरुक्षेत्र", "सतीश कुमार सिंघल", "निर्दलीय"},
            {"Haryana", "Rohtak", "Satyavir Singh", "Independent", "36.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13213", "हरियाणा", "रोहतक", "सत्यवीर सिंह", "निर्दलीय"},
            {"Haryana", "Rohtak", "Rajbir", "Aapki Apni Party (Peoples)", "37.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13206", "हरियाणा", "रोहतक", "राजबीर", "अपना दल (पीपल्स)"},
            {"Haryana", "Rohtak", "Vinay", "Independent", "99.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13212", "हरियाणा", "रोहतक", "विनय", "निर्दलीय"},
            {"Haryana", "Rohtak", "Parveen Kumar", "Independent", "8.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13209", "हरियाणा", "रोहतक", "परवीन कुमार", "निर्दलीय"},
            {"Haryana", "Sirsa", "Brij Pal Balmiki", "Bahujan Mukti Party", "56.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13262", "हरियाणा", "सिरसा", "बृज पाल बाल्मीकि", "बहुजन मुक्ति पार्टी"},
            {"Haryana", "Sirsa", "Dr. Rajesh Mehandia", "Peoples Party of India (Democratic)", "31.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12194", "हरियाणा", "सिरसा", "डॉ। राजेश मेहंदिया", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
            {"Haryana", "Sirsa", "Janak Raj Atwal", "Bahujan Samaj Party", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12193", "हरियाणा", "सिरसा", "जनक राज अटवाल", "बहुजन समाज पार्टी"},
            {"Haryana", "Sirsa", "Deepak", "Independent", "4.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13268", "हरियाणा", "सिरसा", "दीपक", "निर्दलीय"},
            {"Haryana", "Sirsa", "Dalip Luna", "Independent", "3.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13267", "हरियाणा", "सिरसा", "दलीप लुन", "निर्दलीय"},
            {"Haryana", "Sonipat", "Dr. Jagbir Singh", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13225", "हरियाणा", "सोनीपत", "डॉ। जगबीर सिंह", "निर्दलीय"},
            {"Haryana", "Sonipat", "Sant Dharamveer Chotiwala", "Bahujan Maha Party", "4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13217", "हरियाणा", "सोनीपत", "संत धरमवीर छोटेवाला", "बहुजन महा पार्टी"},
            {"Haryana", "Sonipat", "Raj Bala Saini", "Loktanter Suraksha Party", "3.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12200", "हरियाणा", "सोनीपत", "राज बाला सैनी", "लोकतन्त्र सुरक्षा पार्टी"},
            {"Haryana", "Sonipat", "Shiyanand Tyagi", "Independent", "8.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13233", "हरियाणा", "सोनीपत", "शियानंद त्यागी", "निर्दलीय"},
            {"Haryana", "Sonipat", "Satinder Rathi", "Independent", "2.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13234", "हरियाणा", "सोनीपत", "सतिंदर राठी", "निर्दलीय"},
            {"Haryana", "Sonipat", "Rajesh Sharma", "Pragatishil Samajwadi Party (Lohia)", "70.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13221", "हरियाणा", "सोनीपत", "राजेश शर्मा", "प्रगति समाजवादी पार्टी (लोहिया)"},
            {"Haryana", "Sonipat", "Anil Kumar", "Independent", "5.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13219", "हरियाणा", "सोनीपत", "अनिल कुमार", "निर्दलीय"},
            {"Haryana", "Sonipat", "Ashwani", "Independent", "1700", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12198", "हरियाणा", "सोनीपत", "अश्विनी", "निर्दलीय"},
            {"Haryana", "Sonipat", "Bijender", "Independent", "3.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13229", "हरियाणा", "सोनीपत", "बिजेन्द्र", "निर्दलीय"},
            {"Haryana", "Sonipat", "Ravinder Kumar", "Independent", "3.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13232", "हरियाणा", "सोनीपत", "रविन्द्र कुमार", "निर्दलीय"},
            {"Haryana", "Sonipat", "Sudhir Kumar", "Bharat Prabhat Party", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13223", "हरियाणा", "सोनीपत", "सुधीर कुमार", "भारत प्रभात पार्टी"},
            {"Haryana", "Sonipat", "Satish Raj", "Independent", "5.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12199", "हरियाणा", "सोनीपत", "सतीश राज", "निर्दलीय"},
            {"Haryana", "Sonipat", "Kusum Parashar", "Mahila & Yuva Shakti Party", "51.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13215", "हरियाणा", "सोनीपत", "कुसुम पाराशर", "महिला और युवा शक्ति पार्टी"},
    };

    public static final String[][] red_bucket = {
            {"Haryana", "Ambala", "Ram Pal", "2", " ", "हरियाणा", "अंबाला", "राम पाल", " "},
            {"Haryana", "Ambala", "Rattan Lal Kataria", "1", " ", "हरियाणा", "अंबाला", "रतन लाल कटारिया", " "},
            {"Haryana", "Ambala", "Ranjeet Singh", "2", " ", "हरियाणा", "अंबाला", "रणजीत सिंह", " "},
            {"Haryana", "Ambala", "Suraj Kumar", "4", " ", "हरियाणा", "अंबाला", "सूरज कुमार", " "},
            {"Haryana", "Ambala", "Rattan Lal", "3", " ", "हरियाणा", "अंबाला", "रतन लाल", " "},
            {"Haryana", "Ambala", "Naresh Kumar", "4", " ", "हरियाणा", "अंबाला", "नरेश कुमार", " "},
            {"Haryana", "Ambala", "Jatinder Singh", "4", " ", "हरियाणा", "अंबाला", "जतिंदर सिंह", " "},
            {"Haryana", "Ambala", "Sandeep Singh", "4", " ", "हरियाणा", "अंबाला", "संदीप सिंह ने गु", " "},
            {"Haryana", "Ambala", "Selja", "1", " ", "हरियाणा", "अंबाला", "शैलजा", " "},
            {"Haryana", "Ambala", "Rajender Kumar Bhatli", "4", " ", "हरियाणा", "अंबाला", "राजेंद्र कुमार भटली", " "},
            {"Haryana", "Ambala", "Puran Chand", "4", " ", "हरियाणा", "अंबाला", "पूरन चंद", " "},
            {"Haryana", "Bhiwani Mahendragarh", "Kundan Kumar", "4", " ", "हरियाणा", "भिवानी-महेंद्रगढ़", "कुंदन कुमार", " "},
            {"Haryana", "Bhiwani Mahendragarh", "Suresh Chand", "3", " ", "हरियाणा", "भिवानी-महेंद्रगढ़", "सुरेश चंद", " "},
            {"Haryana", "Bhiwani Mahendragarh", "Dharambir Singh", "1", " ", "हरियाणा", "भिवानी-महेंद्रगढ़", "धर्मबीर सिंह", " "},
            {"Haryana", "Bhiwani Mahendragarh", "Happy Singh", "4", " ", "हरियाणा", "भिवानी-महेंद्रगढ़", "हैप्पी सिंह", " "},
            {"Haryana", "Bhiwani Mahendragarh", "Salesh Kumar", "2", " ", "हरियाणा", "भिवानी-महेंद्रगढ़", "सलेश कुमार", " "},
            {"Haryana", "Bhiwani Mahendragarh", "Ram Kishan", "4", " ", "हरियाणा", "भिवानी-महेंद्रगढ़", "राम किशन", " "},
            {"Haryana", "Bhiwani Mahendragarh", "Shruti Choudhry", "1", " ", "हरियाणा", "भिवानी-महेंद्रगढ़", "श्रुति चौधरी", " "},
            {"Haryana", "Bhiwani Mahendragarh", "Satbir", "4", " ", "हरियाणा", "भिवानी-महेंद्रगढ़", "सतबीर", " "},
            {"Haryana", "Bhiwani Mahendragarh", "Balwan Singh", "2", " ", "हरियाणा", "भिवानी-महेंद्रगढ़", "बलवान सिंह", " "},
            {"Haryana", "Bhiwani Mahendragarh", "Jagat Singh", "3", " ", "हरियाणा", "भिवानी-महेंद्रगढ़", "जगत सिंह", " "},
            {"Haryana", "Bhiwani Mahendragarh", "Bhai Surender Dhanak", "4", " ", "हरियाणा", "भिवानी-महेंद्रगढ़", "भाई सुरेंदर धनक", " "},
            {"Haryana", "Faridabad", "Sanjay Maurya", "4", " ", "हरियाणा", "फरीदाबाद", "संजय मौर्य", " "},
            {"Haryana", "Faridabad", "Daya Chand", "3", " ", "हरियाणा", "फरीदाबाद", "दया चंद", " "},
            {"Haryana", "Faridabad", "Mahender Singh Chauhan", "3", " ", "हरियाणा", "फरीदाबाद", "महेन्द्र सिंह चौहान", " "},
            {"Haryana", "Faridabad", "Navin Jaihind", "2", " ", "हरियाणा", "फरीदाबाद", "नवीन जयहिंद", " "},
            {"Haryana", "Faridabad", "Ram Kishan Gola", "4", " ", "हरियाणा", "फरीदाबाद", "राम किशन गोला", " "},
            {"Haryana", "Faridabad", "Deepak Gaur", "2", " ", "हरियाणा", "फरीदाबाद", "दीपक गौर", " "},
            {"Haryana", "Faridabad", "Mandhir Maan", "4", " ", "हरियाणा", "फरीदाबाद", "मंधीर मान", " "},
            {"Haryana", "Faridabad", "Balwant Kataria", "2", " ", "हरियाणा", "फरीदाबाद", "बलवंत कटारिया", " "},
            {"Haryana", "Faridabad", "Ruby", "4", " ", "हरियाणा", "फरीदाबाद", "माणिक", " "},
            {"Haryana", "Faridabad", "Rakesh Kumar", "4", " ", "हरियाणा", "फरीदाबाद", "राकेश कुमार", " "},
            {"Haryana", "Faridabad", "Krishan Pal", "1", " ", "हरियाणा", "फरीदाबाद", "कृष्णपाल", " "},
            {"Haryana", "Faridabad", "Sahiram Rawat", "2", " ", "हरियाणा", "फरीदाबाद", "साहिरम रावत", " "},
            {"Haryana", "Faridabad", "Mahesh Pratap Sharma", "4", " ", "हरियाणा", "फरीदाबाद", "महेश प्रताप शर्मा", " "},
            {"Haryana", "Faridabad", "Avtar Singh Bhadana", "1", " ", "हरियाणा", "फरीदाबाद", "अवतार सिंह भड़ाना", " "},
            {"Haryana", "Faridabad", "Mukesh Kumar Singh", "4", " ", "हरियाणा", "फरीदाबाद", "मुकेश कुमार सिंह", " "},
            {"Haryana", "Faridabad", "Baudhycharya Khajan Isngh Gautam", "4", " ", "हरियाणा", "फरीदाबाद", "बौधिचार्य खजन इस्घ गौतम", " "},
            {"Haryana", "Faridabad", "Lekha Ram Dabang", "4", " ", "हरियाणा", "फरीदाबाद", "लखे राम दबंग", " "},
            {"Haryana", "Gurgaon", "Vinod Kumar", "4", " ", "हरियाणा", "गुडगाँव", "विनोद कुमार", " "},
            {"Haryana", "Gurgaon", "Mahabir Mehra Chhilarki", "4", " ", "हरियाणा", "गुडगाँव", "महाबीर मेहरा छिलारकी", " "},
            {"Haryana", "Gurgaon", "Rao Inderjeet", "4", " ", "हरियाणा", "गुडगाँव", "राव इंद्रजीत", " "},
            {"Haryana", "Gurgaon", "Rao Inderjit Singh", "1", " ", "हरियाणा", "गुडगाँव", "राव इंद्रजीत सिंह", " "},
            {"Haryana", "Gurgaon", "Chowkidar Anjan Deveshwar", "4", " ", "हरियाणा", "गुडगाँव", "चौकीदार अंजन देवेश्वर", " "},
            {"Haryana", "Gurgaon", "Sharvan Kumar", "4", " ", "हरियाणा", "गुडगाँव", "शरवन कुमार", " "},
            {"Haryana", "Gurgaon", "Ramesh Chand", "3", " ", "हरियाणा", "गुडगाँव", "रमेश चंद", " "},
            {"Haryana", "Gurgaon", "Fauji Jai Kawar Tyagi Dixshit", "4", " ", "हरियाणा", "गुडगाँव", "फौजी जय कवार त्यागी दीक्षित", " "},
            {"Haryana", "Gurgaon", "Pawan Kumar", "4", " ", "हरियाणा", "गुडगाँव", "पवन कुमार", " "},
            {"Haryana", "Gurgaon", "Dr. Abdul Latif (Miya Ji)", "4", " ", "हरियाणा", "गुडगाँव", "डॉ। अब्दुल लतीफ़ (मिया जी)", " "},
            {"Haryana", "Gurgaon", "Kusheshwar Bhagat", "4", " ", "हरियाणा", "गुडगाँव", "कुशेश्वर भगत", " "},
            {"Haryana", "Gurgaon", "Hans Kumar", "4", " ", "हरियाणा", "गुडगाँव", "हंस कुमार", " "},
            {"Haryana", "Gurgaon", "Sudesh Kumar", "4", " ", "हरियाणा", "गुडगाँव", "सुदेश कुमार", " "},
            {"Haryana", "Gurgaon", "Azad Singh Nangalia", "4", " ", "हरियाणा", "गुडगाँव", "आजाद सिंह नांगलिया", " "},
            {"Haryana", "Gurgaon", "Capt. Ajay Singh", "1", " ", "हरियाणा", "गुडगाँव", "कैप्टन अजय सिंह", " "},
            {"Haryana", "Hisar", "Bhavya Bishnoi", "1", " ", "हरियाणा", "हिसार", "भाव बिश्नोई", " "},
            {"Haryana", "Hisar", "Shamsher Singh", "4", " ", "हरियाणा", "हिसार", "शमशेर सिंह", " "},
            {"Haryana", "Hisar", "Bijender", "4", " ", "हरियाणा", "हिसार", "बिजेन्द्र", " "},
            {"Haryana", "Hisar", "Surinder Sharma", "4", " ", "हरियाणा", "हिसार", "सुरिंदर शर्मा", " "},
            {"Haryana", "Hisar", "Suresh Koth", "2", " ", "हरियाणा", "हिसार", "सुरेश कोठ", " "},
            {"Haryana", "Hisar", "Anoop Mehta", "4", " ", "हरियाणा", "हिसार", "अनूप मेहता", " "},
            {"Haryana", "Hisar", "Kuldeep Bhukkal", "4", " ", "हरियाणा", "हिसार", "कुलदीप भुक्कल", " "},
            {"Haryana", "Hisar", "Deepak", "2", " ", "हरियाणा", "हिसार", "दीपक", " "},
            {"Haryana", "Hisar", "Mange Ram Verma", "4", " ", "हरियाणा", "हिसार", "मांगे राम वर्मा", " "},
            {"Haryana", "Hisar", "Saleem Din", "4", " ", "हरियाणा", "हिसार", "सलीम दीन", " "},
            {"Haryana", "Hisar", "Sumit Kumar", "4", " ", "हरियाणा", "हिसार", "सुमित कुमार", " "},
            {"Haryana", "Hisar", "Pardeep Kumar", "4", " ", "हरियाणा", "हिसार", "प्रदीप कुमार", " "},
            {"Haryana", "Hisar", "Jai Bhagwan", "4", " ", "हरियाणा", "हिसार", "जय भगवान", " "},
            {"Haryana", "Hisar", "Pyarelal Chohan Advocate", "3", " ", "हरियाणा", "हिसार", "प्यारेलाल चैहान एडवोकेट", " "},
            {"Haryana", "Hisar", "Kaka Sahil Thakral", "4", " ", "हरियाणा", "हिसार", "काका साहिल ठकराल", " "},
            {"Haryana", "Hisar", "Brijendra Singh", "1", " ", "हरियाणा", "हिसार", "बृजेन्द्र सिंह", " "},
            {"Haryana", "Karnal", "Jagdish", "3", " ", "हरियाणा", "करनाल", "जगदीश", " "},
            {"Haryana", "Karnal", "Ishwar Chand Salwan", "3", " ", "हरियाणा", "करनाल", "ईश्वर चंद सलवान", " "},
            {"Haryana", "Karnal", "Ankur", "4", " ", "हरियाणा", "करनाल", "अंकुर", " "},
            {"Haryana", "Karnal", "Kitab Singh", "4", " ", "हरियाणा", "करनाल", "किताब सिंह", " "},
            {"Haryana", "Karnal", "Tilak Raj", "2", " ", "हरियाणा", "करनाल", "तिलक राज", " "},
            {"Haryana", "Karnal", "Dinesh Sharma", "2", " ", "हरियाणा", "करनाल", "दिनेश शर्मा", " "},
            {"Haryana", "Karnal", "Pankaj", "4", " ", "हरियाणा", "करनाल", "पंकज", " "},
            {"Haryana", "Karnal", "Dharmvir Padha", "4", " ", "हरियाणा", "करनाल", "धर्मवीर पाधा", " "},
            {"Haryana", "Karnal", "Ishwar Singh", "4", " ", "हरियाणा", "करनाल", "ईश्वर सिंह", " "},
            {"Haryana", "Karnal", "Anil Kumar", "4", " ", "हरियाणा", "करनाल", "अनिल कुमार", " "},
            {"Haryana", "Karnal", "Vicky Chinalya", "4", " ", "हरियाणा", "करनाल", "विक्की चिन्यालीस", " "},
            {"Haryana", "Karnal", "Kuldip Sharma", "1", " ", "हरियाणा", "करनाल", "कुलदीप शर्मा", " "},
            {"Haryana", "Karnal", "Sanjay Bhatia", "1", " ", "हरियाणा", "करनाल", "संजय भाटिया", " "},
            {"Haryana", "Kurukshetra", "Jyoti", "4", " ", "हरियाणा", "कुरुक्षेत्र", "ज्योति", " "},
            {"Haryana", "Kurukshetra", "Nitin", "2", " ", "हरियाणा", "कुरुक्षेत्र", "नितिन", " "},
            {"Haryana", "Kurukshetra", "Sandeep Kumar Kaushik", "4", " ", "हरियाणा", "कुरुक्षेत्र", "संदीप कुमार कौशिक", " "},
            {"Haryana", "Kurukshetra", "Jai Parkash Sharma", "4", " ", "हरियाणा", "कुरुक्षेत्र", "जय प्रकाश शर्मा", " "},
            {"Haryana", "Kurukshetra", "Anil", "4", " ", "हरियाणा", "कुरुक्षेत्र", "नील का पौधा", " "},
            {"Haryana", "Kurukshetra", "Rameshwar Dass", "4", " ", "हरियाणा", "कुरुक्षेत्र", "रामेश्वर दास", " "},
            {"Haryana", "Kurukshetra", "Nayab Singh", "1", " ", "हरियाणा", "कुरुक्षेत्र", "नायब सिंह", " "},
            {"Haryana", "Kurukshetra", "Sandeep Singh", "2", " ", "हरियाणा", "कुरुक्षेत्र", "संदीप सिंह ने गु", " "},
            {"Haryana", "Kurukshetra", "Arjun Singh Chautala", "4", " ", "हरियाणा", "कुरुक्षेत्र", "अर्जुन सिंह चौटाला", " "},
            {"Haryana", "Kurukshetra", "Ram Narayan", "4", " ", "हरियाणा", "कुरुक्षेत्र", "राम नारायण", " "},
            {"Haryana", "Kurukshetra", "Balveer Singh", "3", " ", "हरियाणा", "कुरुक्षेत्र", "बलवीर सिंह", " "},
            {"Haryana", "Kurukshetra", "Nirmal Singh", "1", " ", "हरियाणा", "कुरुक्षेत्र", "निर्मल सिंह", " "},
            {"Haryana", "Kurukshetra", "Sumer Chand", "4", " ", "हरियाणा", "कुरुक्षेत्र", "सुमेर चंद", " "},
            {"Haryana", "Kurukshetra", "Ramesh Chander Khatkar", "2", " ", "हरियाणा", "कुरुक्षेत्र", "रमेश चंदर खटकर", " "},
            {"Haryana", "Rohtak", "Krishan", "4", " ", "हरियाणा", "रोहतक", "कृष्ण", " "},
            {"Haryana", "Rohtak", "Arvind Kumar Sharma", "1", " ", "हरियाणा", "रोहतक", "अरविंद कुमार शर्मा", " "},
            {"Haryana", "Rohtak", "Pradeep Kumar Deswal", "2", " ", "हरियाणा", "रोहतक", "प्रदीप कुमार देशवाल", " "},
            {"Haryana", "Rohtak", "Dharamvir", "4", " ", "हरियाणा", "रोहतक", "धर्मवीर", " "},
            {"Haryana", "Rohtak", "Rambir", "4", " ", "हरियाणा", "रोहतक", "Rambir", " "},
            {"Haryana", "Rohtak", "Ram Kishan Sain", "4", " ", "हरियाणा", "रोहतक", "राम किशन सेन", " "},
            {"Haryana", "Rohtak", "Ashok Kumar", "4", " ", "हरियाणा", "रोहतक", "अशोक कुमार", " "},
            {"Haryana", "Rohtak", "Deepender Singh", "1", " ", "हरियाणा", "रोहतक", "दीपेन्द्र सिंह", " "},
            {"Haryana", "Rohtak", "Sukhbir", "4", " ", "हरियाणा", "रोहतक", "सुखबीर", " "},
            {"Haryana", "Rohtak", "Manju Devi", "4", " ", "हरियाणा", "रोहतक", "मंजू देवी", " "},
            {"Haryana", "Rohtak", "Kishan Lal", "4", " ", "हरियाणा", "रोहतक", "किशन लाल", " "},
            {"Haryana", "Rohtak", "Imran", "4", " ", "हरियाणा", "रोहतक", "इमरान", " "},
            {"Haryana", "Rohtak", "Jai Karan", "3", " ", "हरियाणा", "रोहतक", "जय करण", " "},
            {"Haryana", "Rohtak", "Inderjeet", "2", " ", "हरियाणा", "रोहतक", "इंद्रजीत", " "},
            {"Haryana", "Sirsa", "Surender Kumar", "4", " ", "हरियाणा", "सिरसा", "सुरेंद्र कुमार", " "},
            {"Haryana", "Sirsa", "Jaswant", "4", " ", "हरियाणा", "सिरसा", "जसवंत", " "},
            {"Haryana", "Sirsa", "Ankur Gill", "4", " ", "हरियाणा", "सिरसा", "अंकुर गिल", " "},
            {"Haryana", "Sirsa", "Surajmal Athwal", "4", " ", "हरियाणा", "सिरसा", "सूरजमल अठवाल", " "},
            {"Haryana", "Sirsa", "Nirmal Singh", "4", " ", "हरियाणा", "सिरसा", "निर्मल सिंह", " "},
            {"Haryana", "Sirsa", "Rajender Sirsa", "4", " ", "हरियाणा", "सिरसा", "राजेंदर सिरसा", " "},
            {"Haryana", "Sirsa", "Kashmir Chand Oad", "3", " ", "हरियाणा", "सिरसा", "कश्मीर चंद ओड", " "},
            {"Haryana", "Sirsa", "Sunita Duggal", "1", " ", "हरियाणा", "सिरसा", "सुनीता दुग्गल", " "},
            {"Haryana", "Sirsa", "Ashok Tanwar", "1", " ", "हरियाणा", "सिरसा", "अशोक तंवर", " "},
            {"Haryana", "Sirsa", "Angrej Singh Alahi", "4", " ", "हरियाणा", "सिरसा", "अंगरेज सिंह अलाही", " "},
            {"Haryana", "Sirsa", "Rajesh Chaubara", "4", " ", "हरियाणा", "सिरसा", "राजेश चौबारा", " "},
            {"Haryana", "Sirsa", "Virender Singh", "4", " ", "हरियाणा", "सिरसा", "वीरेंद्र सिंह", " "},
            {"Haryana", "Sirsa", "Hira Singh Hanspur", "4", " ", "हरियाणा", "सिरसा", "हीरा सिंह हंसपुर", " "},
            {"Haryana", "Sirsa", "Charanjeet Singh Rori", "4", " ", "हरियाणा", "सिरसा", "चरणजीत सिंह रोरी", " "},
            {"Haryana", "Sirsa", "Vinod Kumar Sirkiband (Gihara)", "4", " ", "हरियाणा", "सिरसा", "विनोद कुमार सिरकिबंद (गिहारा)", " "},
            {"Haryana", "Sonipat", "Surender Kumar Chhikara", "4", " ", "हरियाणा", "सोनीपत", "सुरेंद्र कुमार छिकारा", " "},
            {"Haryana", "Sonipat", "Manish", "4", " ", "हरियाणा", "सोनीपत", "मनीष", " "},
            {"Haryana", "Sonipat", "Ramdiya", "3", " ", "हरियाणा", "सोनीपत", "Ramdiya", " "},
            {"Haryana", "Sonipat", "Karan Singh", "4", " ", "हरियाणा", "सोनीपत", "कारन सिंह", " "},
            {"Haryana", "Sonipat", "Mahavir", "4", " ", "हरियाणा", "सोनीपत", "महावीर", " "},
            {"Haryana", "Sonipat", "Sukhmandar Singh Kharb", "4", " ", "हरियाणा", "सोनीपत", "सुखमंदर सिंह खरब", " "},
            {"Haryana", "Sonipat", "Pardeep Chahal", "4", " ", "हरियाणा", "सोनीपत", "परदीप चहल", " "},
            {"Haryana", "Sonipat", "Jai Prakash", "4", " ", "हरियाणा", "सोनीपत", "जय प्रकाश", " "},
            {"Haryana", "Sonipat", "Master Ramesh Khatri Lambardar", "2", " ", "हरियाणा", "सोनीपत", "मास्टर रमेश खत्री लम्बरदार", " "},
            {"Haryana", "Sonipat", "Ramesh Chander Kaushik", "1", " ", "हरियाणा", "सोनीपत", "रमेश चंदर कौशिक", " "},
            {"Haryana", "Sonipat", "Bijender Kumar", "4", " ", "हरियाणा", "सोनीपत", "बिजेन्द्र कुमार", " "},
            {"Haryana", "Sonipat", "Bhupinder Singh Hooda", "1", " ", "हरियाणा", "सोनीपत", "भूपिंदर सिंह हुड्डा", " "},
            {"Haryana", "Sonipat", "Comrade Balbeer Singh", "4", " ", "हरियाणा", "सोनीपत", "कामरेड बलबीर सिंह", " "},
            {"Haryana", "Sonipat", "Mohan", "2", " ", "हरियाणा", "सोनीपत", "मोहन", " "},
            {"Haryana", "Sonipat", "Dharambir", "4", " ", "हरियाणा", "सोनीपत", "धरमबिर", " "},
            {"Haryana", "Sonipat", "Digvijay Singh Chautala", "2", " ", "हरियाणा", "सोनीपत", "दिग्विजय सिंह चौटाला", " "},
    };

}