/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Jammu_and_Kashmir {
public static final String[][] green_bucket = {
{"Jammu & Kashmir",  "6366", "Baramulla", "Syed Najeeb Shah Naqvi", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5643",  "जम्मू और कश्मीर",  "बारामूला", "सैयद नजीब शाह नकवी", "निर्दलीय", ""}, 
{"Jammu & Kashmir",  "6368", "Baramulla", "Abdul Qayoom Wani", "Jammu & Kashmir Peoples Democratic Party", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4876",  "जम्मू और कश्मीर",  "बारामूला", "अब्दुल कयूम वानी", "जम्मू और कश्मीर पीपुल्स डेमोक्रेटिक पार्टी", ""}, 
{"Jammu & Kashmir",  "6400", "Jammu", "Anil Singh", "Independent", "10000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6048",  "जम्मू और कश्मीर",  "जम्मू", "अनिल सिंह", "निर्दलीय", ""}, 
{"Jammu & Kashmir",  "6404", "Jammu", "Lal Singh", "Dogra Swabhiman Sangathan Party", "2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6030",  "जम्मू और कश्मीर",  "जम्मू", "लाल सिंह", "डोगरा स्वाभिमान संगठन पार्टी", ""}, 
{"Jammu & Kashmir",  "6405", "Jammu", "Manish Sahni", "Shiv Sena", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6055",  "जम्मू और कश्मीर",  "जम्मू", "मनीष साहनी", "शिवसेना", ""}, 
{"Jammu & Kashmir",  "6407", "Jammu", "Syed Aqib Hussain", "Independent Peoples Party", "37.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4710",  "जम्मू और कश्मीर",  "जम्मू", "सैयद अकीब हुसैन", "स्वतंत्र पीपुल्स पार्टी", ""}, 
{"Jammu & Kashmir",  "6412", "Jammu", "Sushil Kumar", "Hindusthan Nirman Dal", "1.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5661",  "जम्मू और कश्मीर",  "जम्मू", "सुशील कुमार", "हिंदुस्तान निर्माण दल", ""}, 
{"Jammu & Kashmir",  "6416", "Jammu", "Ajay Kumar", "Independent", "17.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6029",  "जम्मू और कश्मीर",  "जम्मू", "अजय कुमार", "निर्दलीय", ""}, 
{"Jammu & Kashmir",  "6419", "Jammu", "Mohd Younis", "Jammu & Kashmir Pir Panjal Awami Party", "9.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5656",  "जम्मू और कश्मीर",  "जम्मू", "मोहम्मद यूनिस", "जम्मू और कश्मीर पीर पंजाल अवामी पार्टी", ""}, 
{"Jammu & Kashmir",  "6398", "Jammu", "Sakander Ahmad Nourani", "Independent", "4.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6054",  "जम्मू और कश्मीर",  "जम्मू", "सकंदर अहमद नूरानी", "निर्दलीय", ""}, 
{"Jammu & Kashmir",  "6379", "Srinagar", "Irfan Raza Ansari", "Jammu & Kashmir People Conference", "66.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6006",  "जम्मू और कश्मीर",  "श्रीनगर", "इरफान रजा अंसारी", "जम्मू और कश्मीर लोग सम्मेलन", ""}, 
{"Jammu & Kashmir",  "6382", "Srinagar", "Bilal Sultan", "Independent", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6011",  "जम्मू और कश्मीर",  "श्रीनगर", "बिलाल सुल्तान", "निर्दलीय", ""}, 
{"Jammu & Kashmir",  "6385", "Udhampur", "Lal Singh", "Dogra Swabhiman Sangathan Party", "2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6019",  "जम्मू और कश्मीर",  "उधमपुर", "लाल सिंह", "डोगरा स्वाभिमान संगठन पार्टी", ""}, 
{"Jammu & Kashmir",  "6387", "Udhampur", "Rakesh Mudgal", "Independent", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6025",  "जम्मू और कश्मीर",  "उधमपुर", "राकेश मुद्गल", "निर्दलीय", ""}, 
{"Jammu & Kashmir",  "6388", "Udhampur", "Meenakshi", "Shiv Sena", "21.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6024",  "जम्मू और कश्मीर",  "उधमपुर", "मीनाक्षी", "शिवसेना", ""}, 
{"Jammu & Kashmir",  "6393", "Udhampur", "Tilak Raj Bhagat", "Bahujan Samaj Party", "2.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5396",  "जम्मू और कश्मीर",  "उधमपुर", "तिलक राज भगत", "बहुजन समाज पार्टी", ""}, 
{"Jammu & Kashmir",  "6395", "Udhampur", "Shaber Ahmed", "Independent", "79200", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6023",  "जम्मू और कश्मीर",  "उधमपुर", "शबर अहमद", "निर्दलीय", ""}, 
};

public static final String[][] red_bucket = {
{ "Jammu & Kashmir",  "6364",  "Baramulla", "Mohd Maqbool War", "ForeignFunding",  " ","जम्मू और कश्मीर",  "बारामूला", "मोहम्मद मकबूल वार", " "}, 
{ "Jammu & Kashmir",  "6365",  "Baramulla", "Haji Farooq Ahmad Mir", "ForeignFunding",  " ","जम्मू और कश्मीर",  "बारामूला", "हाजी फारूक अहमद मीर", " "}, 
{ "Jammu & Kashmir",  "6367",  "Baramulla", "Engineer Rashid", "NotGraduate",  " ","जम्मू और कश्मीर",  "बारामूला", "इंजीनियर रशीद", " "}, 
{ "Jammu & Kashmir",  "6369",  "Baramulla", "Jahangir Khan", "NotGraduate",  " ","जम्मू और कश्मीर",  "बारामूला", "जहाँगीर खान", " "}, 
{ "Jammu & Kashmir",  "6370",  "Baramulla", "Javid Ahmad Qureshi", "NotGraduate",  " ","जम्मू और कश्मीर",  "बारामूला", "जावीद अहमद कुरैशी", " "}, 
{ "Jammu & Kashmir",  "6371",  "Baramulla", "Mohammad Akbar Lone", "OverAged",  " ","जम्मू और कश्मीर",  "बारामूला", "मोहम्मद अकबर लोन", " "}, 
{ "Jammu & Kashmir",  "6372",  "Baramulla", "Raja Aijaz Ali", "OverAged",  " ","जम्मू और कश्मीर",  "बारामूला", "राजा ऐजाज अली", " "}, 
{ "Jammu & Kashmir",  "6401",  "Jammu", "Rajiv Chuni", "NotGraduate",  " ","जम्मू और कश्मीर",  "जम्मू", "राजीव चुन्नी", " "}, 
{ "Jammu & Kashmir",  "6402",  "Jammu", "Prof. Bhim Singh", "OverAged",  " ","जम्मू और कश्मीर",  "जम्मू", "भीम सिंह को प्रो", " "}, 
{ "Jammu & Kashmir",  "6403",  "Jammu", "Jugal Kishore", "ForeignFunding",  " ","जम्मू और कश्मीर",  "जम्मू", "जुगल किशोर", " "}, 
{ "Jammu & Kashmir",  "6406",  "Jammu", "Gursagar Singh", "NotGraduate",  " ","जम्मू और कश्मीर",  "जम्मू", "गुरसागर सिंह", " "}, 
{ "Jammu & Kashmir",  "6408",  "Jammu", "Syed Zeshan Haider", "NotGraduate",  " ","जम्मू और कश्मीर",  "जम्मू", "सैयद जीशान हैदर", " "}, 
{ "Jammu & Kashmir",  "6409",  "Jammu", "Balwan Singh", "NotGraduate",  " ","जम्मू और कश्मीर",  "जम्मू", "बलवान सिंह", " "}, 
{ "Jammu & Kashmir",  "6410",  "Jammu", "Badri Nath", "NotGraduate",  " ","जम्मू और कश्मीर",  "जम्मू", "बद्री नाथ", " "}, 
{ "Jammu & Kashmir",  "6411",  "Jammu", "Er. Ghulam Mustafa Chowdhary", "NotGraduate",  " ","जम्मू और कश्मीर",  "जम्मू", "एर। गुलाम मुस्तफा चौधरी", " "}, 
{ "Jammu & Kashmir",  "6413",  "Jammu", "Tarseem Lal Khullar", "NotGraduate",  " ","जम्मू और कश्मीर",  "जम्मू", "तरसेम लाल खुल्लर", " "}, 
{ "Jammu & Kashmir",  "6414",  "Jammu", "Javaid Ahmed", "NotGraduate",  " ","जम्मू और कश्मीर",  "जम्मू", "जावेद अहमद", " "}, 
{ "Jammu & Kashmir",  "6415",  "Jammu", "Satish Poonchi", "OverAged",  " ","जम्मू और कश्मीर",  "जम्मू", "सतीश पुंछी", " "}, 
{ "Jammu & Kashmir",  "6417",  "Jammu", "Perseen Singh", "NotGraduate",  " ","जम्मू और कश्मीर",  "जम्मू", "परसेन सिंह", " "}, 
{ "Jammu & Kashmir",  "6418",  "Jammu", "Shazad Shabnam", "CriminalCases",  " ","जम्मू और कश्मीर",  "जम्मू", "शाज़ाद शबनम", " "}, 
{ "Jammu & Kashmir",  "6420",  "Jammu", "Raman Bhalla", "ForeignFunding",  " ","जम्मू और कश्मीर",  "जम्मू", "रमन भल्ला", " "}, 
{ "Jammu & Kashmir",  "6397",  "Jammu", "Bahadur", "NotGraduate",  " ","जम्मू और कश्मीर",  "जम्मू", "बहादुर", " "}, 
{ "Jammu & Kashmir",  "6399",  "Jammu", "Subash Chander", "NotGraduate",  " ","जम्मू और कश्मीर",  "जम्मू", "सुबाष चंदर", " "}, 
{ "Jammu & Kashmir",  "6373",  "Srinagar", "Abdul Khaliq Bhat", "NotGraduate",  " ","जम्मू और कश्मीर",  "श्रीनगर", "अब्दुल खालिक भट", " "}, 
{ "Jammu & Kashmir",  "6374",  "Srinagar", "Aga Syed Mohsin", "NotGraduate",  " ","जम्मू और कश्मीर",  "श्रीनगर", "आगा सैयद मोहसिन", " "}, 
{ "Jammu & Kashmir",  "6375",  "Srinagar", "Farooq Abdullah", "CriminalCases",  " ","जम्मू और कश्मीर",  "श्रीनगर", "फारूक अब्दुल्ला", " "}, 
{ "Jammu & Kashmir",  "6376",  "Srinagar", "Sheikh Khalid Jehangir", "ForeignFunding",  " ","जम्मू और कश्मीर",  "श्रीनगर", "शेख खालिद जहाँगीर", " "}, 
{ "Jammu & Kashmir",  "6377",  "Srinagar", "Abdul Rashid Banday", "OverAged",  " ","जम्मू और कश्मीर",  "श्रीनगर", "अब्दुल रशीद बंदे", " "}, 
{ "Jammu & Kashmir",  "6378",  "Srinagar", "Showkat Hussain Khan", "NotGraduate",  " ","जम्मू और कश्मीर",  "श्रीनगर", "शोकात हुसैन खान", " "}, 
{ "Jammu & Kashmir",  "6380",  "Srinagar", "Sajjad Ahmad Dar", "NotGraduate",  " ","जम्मू और कश्मीर",  "श्रीनगर", "सज्जाद अहमद डार", " "}, 
{ "Jammu & Kashmir",  "6381",  "Srinagar", "Abdual Rashid Ganie", "NotGraduate",  " ","जम्मू और कश्मीर",  "श्रीनगर", "अब्दु रशीद गनी", " "}, 
{ "Jammu & Kashmir",  "6383",  "Srinagar", "Nazir Ahmad Lone", "NotGraduate",  " ","जम्मू और कश्मीर",  "श्रीनगर", "नजीर अहमद लोन", " "}, 
{ "Jammu & Kashmir",  "6384",  "Srinagar", "Nazir Ahmad Sofi", "NotGraduate",  " ","जम्मू और कश्मीर",  "श्रीनगर", "नजीर अहमद सोफी", " "}, 
{ "Jammu & Kashmir",  "6386",  "Udhampur", "Bansi Lal", "NotGraduate",  " ","जम्मू और कश्मीर",  "उधमपुर", "बंसी लाल", " "}, 
{ "Jammu & Kashmir",  "6389",  "Udhampur", "Harsh Dev Singh", "CriminalCases",  " ","जम्मू और कश्मीर",  "उधमपुर", "हर्ष देव सिंह", " "}, 
{ "Jammu & Kashmir",  "6390",  "Udhampur", "Vikramaditya Singh", "ForeignFunding",  " ","जम्मू और कश्मीर",  "उधमपुर", "विक्रमादित्य सिंह", " "}, 
{ "Jammu & Kashmir",  "6391",  "Udhampur", "Dr. Jitendra Singh", "ForeignFunding",  " ","जम्मू और कश्मीर",  "उधमपुर", "डॉ। जितेंद्र सिंह", " "}, 
{ "Jammu & Kashmir",  "6392",  "Udhampur", "Mohd Ayub", "CriminalCases",  " ","जम्मू और कश्मीर",  "उधमपुर", "मोहम्मद अयूब", " "}, 
{ "Jammu & Kashmir",  "6394",  "Udhampur", "Garib Singh", "NotGraduate",  " ","जम्मू और कश्मीर",  "उधमपुर", "गरीब सिंह", " "}, 
{ "Jammu & Kashmir",  "6396",  "Udhampur", "Firdous Ahmed Bawani", "NotGraduate",  " ","जम्मू और कश्मीर",  "उधमपुर", "फिरदौस अहमद बवानी", " "}, 
};

}