/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Jammu_and_Kashmir {
public static final String[][] green_bucket = {
        {"Jammu & Kashmir", "Baramulla", "Syed Najeeb Shah Naqvi", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5643", "जम्मू और कश्मीर", "बारामूला", "सैयद नजीब शाह नकवी", "निर्दलीय"},
        {"Jammu & Kashmir", "Baramulla", "Abdul Qayoom Wani", "Jammu & Kashmir Peoples Democratic Party", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4876", "जम्मू और कश्मीर", "बारामूला", "अब्दुल कयूम वानी", "जम्मू और कश्मीर पीपुल्स डेमोक्रेटिक पार्टी"},
        {"Jammu & Kashmir", "Jammu", "Anil Singh", "Independent", "10000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6048", "जम्मू और कश्मीर", "जम्मू", "अनिल सिंह", "निर्दलीय"},
        {"Jammu & Kashmir", "Jammu", "Lal Singh", "Dogra Swabhiman Sangathan Party", "2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6030", "जम्मू और कश्मीर", "जम्मू", "लाल सिंह", "डोगरा स्वाभिमान संगठन पार्टी"},
        {"Jammu & Kashmir", "Jammu", "Manish Sahni", "Shiv Sena", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6055", "जम्मू और कश्मीर", "जम्मू", "मनीष साहनी", "शिवसेना"},
        {"Jammu & Kashmir", "Jammu", "Syed Aqib Hussain", "Independent Peoples Party", "37.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4710", "जम्मू और कश्मीर", "जम्मू", "सैयद अकीब हुसैन", "स्वतंत्र पीपुल्स पार्टी"},
        {"Jammu & Kashmir", "Jammu", "Sushil Kumar", "Hindusthan Nirman Dal", "1.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5661", "जम्मू और कश्मीर", "जम्मू", "सुशील कुमार", "हिंदुस्तान निर्माण दल"},
        {"Jammu & Kashmir", "Jammu", "Ajay Kumar", "Independent", "17.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6029", "जम्मू और कश्मीर", "जम्मू", "अजय कुमार", "निर्दलीय"},
        {"Jammu & Kashmir", "Jammu", "Mohd Younis", "Jammu & Kashmir Pir Panjal Awami Party", "9.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5656", "जम्मू और कश्मीर", "जम्मू", "मोहम्मद यूनिस", "जम्मू और कश्मीर पीर पंजाल अवामी पार्टी"},
        {"Jammu & Kashmir", "Jammu", "Sakander Ahmad Nourani", "Independent", "4.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6054", "जम्मू और कश्मीर", "जम्मू", "सकंदर अहमद नूरानी", "निर्दलीय"},
        {"Jammu & Kashmir", "Srinagar", "Irfan Raza Ansari", "Jammu & Kashmir People Conference", "66.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6006", "जम्मू और कश्मीर", "श्रीनगर", "इरफान रजा अंसारी", "जम्मू और कश्मीर लोग सम्मेलन"},
        {"Jammu & Kashmir", "Srinagar", "Bilal Sultan", "Independent", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6011", "जम्मू और कश्मीर", "श्रीनगर", "बिलाल सुल्तान", "निर्दलीय"},
        {"Jammu & Kashmir", "Udhampur", "Lal Singh", "Dogra Swabhiman Sangathan Party", "2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6019", "जम्मू और कश्मीर", "उधमपुर", "लाल सिंह", "डोगरा स्वाभिमान संगठन पार्टी"},
        {"Jammu & Kashmir", "Udhampur", "Rakesh Mudgal", "Independent", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6025", "जम्मू और कश्मीर", "उधमपुर", "राकेश मुद्गल", "निर्दलीय"},
        {"Jammu & Kashmir", "Udhampur", "Meenakshi", "Shiv Sena", "21.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6024", "जम्मू और कश्मीर", "उधमपुर", "मीनाक्षी", "शिवसेना"},
        {"Jammu & Kashmir", "Udhampur", "Tilak Raj Bhagat", "Bahujan Samaj Party", "2.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5396", "जम्मू और कश्मीर", "उधमपुर", "तिलक राज भगत", "बहुजन समाज पार्टी"},
        {"Jammu & Kashmir", "Udhampur", "Shaber Ahmed", "Independent", "79200", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6023", "जम्मू और कश्मीर", "उधमपुर", "शबर अहमद", "निर्दलीय"},
};

public static final String[][] red_bucket = {
        {"Jammu & Kashmir", "Baramulla", "Mohd Maqbool War", "1", " ", "जम्मू और कश्मीर", "बारामूला", "मोहम्मद मकबूल वार", " "},
        {"Jammu & Kashmir", "Baramulla", "Haji Farooq Ahmad Mir", "1", " ", "जम्मू और कश्मीर", "बारामूला", "हाजी फारूक अहमद मीर", " "},
        {"Jammu & Kashmir", "Baramulla", "Engineer Rashid", "4", " ", "जम्मू और कश्मीर", "बारामूला", "इंजीनियर रशीद", " "},
        {"Jammu & Kashmir", "Baramulla", "Jahangir Khan", "4", " ", "जम्मू और कश्मीर", "बारामूला", "जहाँगीर खान", " "},
        {"Jammu & Kashmir", "Baramulla", "Javid Ahmad Qureshi", "4", " ", "जम्मू और कश्मीर", "बारामूला", "जावीद अहमद कुरैशी", " "},
        {"Jammu & Kashmir", "Baramulla", "Mohammad Akbar Lone", "3", " ", "जम्मू और कश्मीर", "बारामूला", "मोहम्मद अकबर लोन", " "},
        {"Jammu & Kashmir", "Baramulla", "Raja Aijaz Ali", "3", " ", "जम्मू और कश्मीर", "बारामूला", "राजा ऐजाज अली", " "},
        {"Jammu & Kashmir", "Jammu", "Rajiv Chuni", "4", " ", "जम्मू और कश्मीर", "जम्मू", "राजीव चुन्नी", " "},
        {"Jammu & Kashmir", "Jammu", "Prof. Bhim Singh", "3", " ", "जम्मू और कश्मीर", "जम्मू", "भीम सिंह को प्रो", " "},
        {"Jammu & Kashmir", "Jammu", "Jugal Kishore", "1", " ", "जम्मू और कश्मीर", "जम्मू", "जुगल किशोर", " "},
        {"Jammu & Kashmir", "Jammu", "Gursagar Singh", "4", " ", "जम्मू और कश्मीर", "जम्मू", "गुरसागर सिंह", " "},
        {"Jammu & Kashmir", "Jammu", "Syed Zeshan Haider", "4", " ", "जम्मू और कश्मीर", "जम्मू", "सैयद जीशान हैदर", " "},
        {"Jammu & Kashmir", "Jammu", "Balwan Singh", "4", " ", "जम्मू और कश्मीर", "जम्मू", "बलवान सिंह", " "},
        {"Jammu & Kashmir", "Jammu", "Badri Nath", "4", " ", "जम्मू और कश्मीर", "जम्मू", "बद्री नाथ", " "},
        {"Jammu & Kashmir", "Jammu", "Er. Ghulam Mustafa Chowdhary", "4", " ", "जम्मू और कश्मीर", "जम्मू", "एर। गुलाम मुस्तफा चौधरी", " "},
        {"Jammu & Kashmir", "Jammu", "Tarseem Lal Khullar", "4", " ", "जम्मू और कश्मीर", "जम्मू", "तरसेम लाल खुल्लर", " "},
        {"Jammu & Kashmir", "Jammu", "Javaid Ahmed", "4", " ", "जम्मू और कश्मीर", "जम्मू", "जावेद अहमद", " "},
        {"Jammu & Kashmir", "Jammu", "Satish Poonchi", "3", " ", "जम्मू और कश्मीर", "जम्मू", "सतीश पुंछी", " "},
        {"Jammu & Kashmir", "Jammu", "Perseen Singh", "4", " ", "जम्मू और कश्मीर", "जम्मू", "परसेन सिंह", " "},
        {"Jammu & Kashmir", "Jammu", "Shazad Shabnam", "2", " ", "जम्मू और कश्मीर", "जम्मू", "शाज़ाद शबनम", " "},
        {"Jammu & Kashmir", "Jammu", "Raman Bhalla", "1", " ", "जम्मू और कश्मीर", "जम्मू", "रमन भल्ला", " "},
        {"Jammu & Kashmir", "Jammu", "Bahadur", "4", " ", "जम्मू और कश्मीर", "जम्मू", "बहादुर", " "},
        {"Jammu & Kashmir", "Jammu", "Subash Chander", "4", " ", "जम्मू और कश्मीर", "जम्मू", "सुबाष चंदर", " "},
        {"Jammu & Kashmir", "Srinagar", "Abdul Khaliq Bhat", "4", " ", "जम्मू और कश्मीर", "श्रीनगर", "अब्दुल खालिक भट", " "},
        {"Jammu & Kashmir", "Srinagar", "Aga Syed Mohsin", "4", " ", "जम्मू और कश्मीर", "श्रीनगर", "आगा सैयद मोहसिन", " "},
        {"Jammu & Kashmir", "Srinagar", "Farooq Abdullah", "2", " ", "जम्मू और कश्मीर", "श्रीनगर", "फारूक अब्दुल्ला", " "},
        {"Jammu & Kashmir", "Srinagar", "Sheikh Khalid Jehangir", "1", " ", "जम्मू और कश्मीर", "श्रीनगर", "शेख खालिद जहाँगीर", " "},
        {"Jammu & Kashmir", "Srinagar", "Abdul Rashid Banday", "3", " ", "जम्मू और कश्मीर", "श्रीनगर", "अब्दुल रशीद बंदे", " "},
        {"Jammu & Kashmir", "Srinagar", "Showkat Hussain Khan", "4", " ", "जम्मू और कश्मीर", "श्रीनगर", "शोकात हुसैन खान", " "},
        {"Jammu & Kashmir", "Srinagar", "Sajjad Ahmad Dar", "4", " ", "जम्मू और कश्मीर", "श्रीनगर", "सज्जाद अहमद डार", " "},
        {"Jammu & Kashmir", "Srinagar", "Abdual Rashid Ganie", "4", " ", "जम्मू और कश्मीर", "श्रीनगर", "अब्दु रशीद गनी", " "},
        {"Jammu & Kashmir", "Srinagar", "Nazir Ahmad Lone", "4", " ", "जम्मू और कश्मीर", "श्रीनगर", "नजीर अहमद लोन", " "},
        {"Jammu & Kashmir", "Srinagar", "Nazir Ahmad Sofi", "4", " ", "जम्मू और कश्मीर", "श्रीनगर", "नजीर अहमद सोफी", " "},
        {"Jammu & Kashmir", "Udhampur", "Bansi Lal", "4", " ", "जम्मू और कश्मीर", "उधमपुर", "बंसी लाल", " "},
        {"Jammu & Kashmir", "Udhampur", "Harsh Dev Singh", "2", " ", "जम्मू और कश्मीर", "उधमपुर", "हर्ष देव सिंह", " "},
        {"Jammu & Kashmir", "Udhampur", "Vikramaditya Singh", "1", " ", "जम्मू और कश्मीर", "उधमपुर", "विक्रमादित्य सिंह", " "},
        {"Jammu & Kashmir", "Udhampur", "Dr. Jitendra Singh", "1", " ", "जम्मू और कश्मीर", "उधमपुर", "डॉ। जितेंद्र सिंह", " "},
        {"Jammu & Kashmir", "Udhampur", "Mohd Ayub", "2", " ", "जम्मू और कश्मीर", "उधमपुर", "मोहम्मद अयूब", " "},
        {"Jammu & Kashmir", "Udhampur", "Garib Singh", "4", " ", "जम्मू और कश्मीर", "उधमपुर", "गरीब सिंह", " "},
        {"Jammu & Kashmir", "Udhampur", "Firdous Ahmed Bawani", "4", " ", "जम्मू और कश्मीर", "उधमपुर", "फिरदौस अहमद बवानी", " "},
};

}