/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Jammu_and_Kashmir {
public static final String[][] green_bucket = {
{"Jammu & Kashmir",  "6366", "Baramulla", "Syed Najeeb Shah Naqvi", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5643",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6368", "Baramulla", "Abdul Qayoom Wani", "Jammu & Kashmir Peoples Democratic Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4876",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6400", "Jammu", "Anil Singh", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6048",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6404", "Jammu", "Lal Singh", "Dogra Swabhiman Sangathan Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6030",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6405", "Jammu", "Manish Sahni", "SHS", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6055",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6407", "Jammu", "Syed Aqib Hussain", "Independent Peoples Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4710",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6412", "Jammu", "Sushil Kumar", "Hindusthan Nirman Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5661",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6416", "Jammu", "Ajay Kumar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6029",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6419", "Jammu", "Mohd Younis", "Jammu & Kashmir Pir Panjal Awami Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5656",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6398", "Jammu", "Sakander Ahmad Nourani", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6054",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6379", "Srinagar", "Irfan Raza Ansari", "Jammu & Kashmir People Conference", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6006",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6382", "Srinagar", "Bilal Sultan", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6011",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6385", "Udhampur", "Lal Singh", "Dogra Swabhiman Sangathan Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6019",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6387", "Udhampur", "Rakesh Mudgal", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6025",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6388", "Udhampur", "Meenakshi", "SHS", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6024",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6393", "Udhampur", "Tilak Raj Bhagat", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5396",  "",  "", "", "", ""}, 
{"Jammu & Kashmir",  "6395", "Udhampur", "Shaber Ahmed", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6023",  "",  "", "", "", ""}, 
};

public static final String[][] red_bucket = {
{ "Jammu & Kashmir",  "6364",  "Baramulla", "Mohd Maqbool War", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6365",  "Baramulla", "Haji Farooq Ahmad Mir", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6367",  "Baramulla", "Engineer Rashid", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6369",  "Baramulla", "Jahangir Khan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6370",  "Baramulla", "Javid Ahmad Qureshi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6371",  "Baramulla", "Mohammad Akbar Lone", "OverAged",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6372",  "Baramulla", "Raja Aijaz Ali", "OverAged",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6401",  "Jammu", "Rajiv Chuni", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6402",  "Jammu", "Prof. Bhim Singh", "OverAged",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6403",  "Jammu", "Jugal Kishore", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6406",  "Jammu", "Gursagar Singh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6408",  "Jammu", "Syed Zeshan Haider", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6409",  "Jammu", "Balwan Singh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6410",  "Jammu", "Badri Nath", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6411",  "Jammu", "Er. Ghulam Mustafa Chowdhary", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6413",  "Jammu", "Tarseem Lal Khullar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6414",  "Jammu", "Javaid Ahmed", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6415",  "Jammu", "Satish Poonchi", "OverAged",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6417",  "Jammu", "Perseen Singh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6418",  "Jammu", "Shazad Shabnam", "CriminalCases",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6420",  "Jammu", "Raman Bhalla", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6397",  "Jammu", "Bahadur", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6399",  "Jammu", "Subash Chander", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6373",  "Srinagar", "Abdul Khaliq Bhat", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6374",  "Srinagar", "Aga Syed Mohsin", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6375",  "Srinagar", "Farooq Abdullah", "CriminalCases",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6376",  "Srinagar", "Sheikh Khalid Jehangir", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6377",  "Srinagar", "Abdul Rashid Banday", "OverAged",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6378",  "Srinagar", "Showkat Hussain Khan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6380",  "Srinagar", "Sajjad Ahmad Dar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6381",  "Srinagar", "Abdual Rashid Ganie", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6383",  "Srinagar", "Nazir Ahmad Lone", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6384",  "Srinagar", "Nazir Ahmad Sofi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6386",  "Udhampur", "Bansi Lal", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6389",  "Udhampur", "Harsh Dev Singh", "CriminalCases",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6390",  "Udhampur", "Vikramaditya Singh", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6391",  "Udhampur", "Dr. Jitendra Singh", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6392",  "Udhampur", "Mohd Ayub", "CriminalCases",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6394",  "Udhampur", "Garib Singh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Jammu & Kashmir",  "6396",  "Udhampur", "Firdous Ahmed Bawani", "NotGraduate",  " ","",  "", "", " "}, 
};

}