/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Jharkhand {
    public static final String[][] green_bucket = {
            {"Jharkhand", "Chatra", "Pramod Toppo", "Independent", "1.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10242", "झारखण्ड", "चतरा", "प्रमोद टोप्पो", "निर्दलीय"},
            {"Jharkhand", "Chatra", "Ramanand Das", "Bhartiya Sarvodaya Party", "43.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10244", "झारखण्ड", "चतरा", "रामानंद दास", "भारतीय सर्वोदय पार्टी"},
            {"Jharkhand", "Chatra", "Manoj Kumar Pandey", "Independent", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10234", "झारखण्ड", "चतरा", "मनोज कुमार पांडे", "निर्दलीय"},
            {"Jharkhand", "Chatra", "Nandlal Prasad", "Independent", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10238", "झारखण्ड", "चतरा", "नंदलाल प्रसाद", "निर्दलीय"},
            {"Jharkhand", "Chatra", "Yogendra Yadav", "Independent", "19.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10251", "झारखण्ड", "चतरा", "योगेंद्र यादव", "निर्दलीय"},
            {"Jharkhand", "Chatra", "Rameshi Ram", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10245", "झारखण्ड", "चतरा", "रमेशी राम", "निर्दलीय"},
            {"Jharkhand", "Hazaribagh", "Jagat Kumar Soni", "Bhartiya Azad Sena", "27.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11955", "", "", "जगत कुमार सोनी", "भारतीय आजाद सेना"},
            {"Jharkhand", "Hazaribagh", "Rameshwar Ram Kushwaha", "All India Forward Bloc", "8.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11353", "", "", "रामेश्वर राम कुशवाहा", "ऑल इंडिया फॉरवर्ड ब्लॉक"},
            {"Jharkhand", "Hazaribagh", "Vinod Kumar", "Bahujan Samaj Party", "2.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11354", "", "", "विनोद कुमार", "बहुजन समाज पार्टी"},
            {"Jharkhand", "Hazaribagh", "Tekochand Mahto", "Independent", "26.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11959", "", "", "टेकचंद महतो", "निर्दलीय"},
            {"Jharkhand", "Hazaribagh", "Rajesh Ranjan", "Socialist Unity Centre of India (Communist)", "15.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11167", "", "", "राजेश रंजन", "भारतीय समाजवादी एकता केंद्र (कम्युनिस्ट)"},
            {"Jharkhand", "Hazaribagh", "Krishna Kumar Singh", "Bharat Prabhat Party", "27Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11956", "", "", "कृष्ण कुमार सिंह", "भारत प्रभात पार्टी"},
            {"Jharkhand", "Khunti", "Niyaran Herenj", "Independent", "19.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11968", "", "", "नियरन हेरेंज", "निर्दलीय"},
            {"Jharkhand", "Khunti", "Ajay Topno", "Jharkhand Party", "81.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11359", "", "", "अजय टोपनो", "झारखंड पार्टी"},
            {"Jharkhand", "Khunti", "Indumati Mundu", "Bahujan Samaj Party", "13.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11170", "", "", "इंदुमती मुंडु", "बहुजन समाज पार्टी"},
            {"Jharkhand", "Khunti", "Sibil Kandulna", "Rashtriya Sangail Party", "46.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11360", "", "", "सिबिल कंडुलना", "राष्ट्रीय संगठन पार्टी"},
            {"Jharkhand", "Khunti", "Abinashi Mundu", "Hum Bhartiya Party", "11.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11964", "", "", "अबिनाशी मुंडू", "हम भारतीय पार्टी"},
            {"Jharkhand", "Khunti", "Meenakshi Munda", "Independent", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11967", "", "", "मीनाक्षी मुंडा", "निर्दलीय"},
            {"Jharkhand", "Kodarma", "Tuklal Nayak", "Hindusthan Nirman Dal", "25Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11370", "", "", "तुकलाल नायक", "हिंदुस्तान निर्माण दल"},
            {"Jharkhand", "Kodarma", "Rameshwar Pd Yadav", "Independent", "13.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11672", "", "", "रामेश्वर पीडी यादव", "निर्दलीय"},
            {"Jharkhand", "Kodarma", "Kanchan Kumari", "All India Trinamool Congress", "52.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11671", "", "", "कंचन कुमारी", "अखिल भारतीय तृणमूल कांग्रेस"},
            {"Jharkhand", "Kodarma", "Avadhesh Kumar Singh", "Vishva SHakti Party", "19Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11365", "", "", "अवधेश कुमार सिंह", "विश्वाशक्ति पार्टी"},
            {"Jharkhand", "Lohardaga", "Aalone Baxla", "Independent", "27.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10252", "झारखण्ड", "लोहरदगा", "अलोन बक्सला", "निर्दलीय"},
            {"Jharkhand", "Lohardaga", "Ajit Kumar Bhagat", "Independent", "25.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10253", "झारखण्ड", "लोहरदगा", "अजीत कुमार भगत", "निर्दलीय"},
            {"Jharkhand", "Lohardaga", "Ambar Saurav Kunal", "Independent", "20Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10254", "झारखण्ड", "लोहरदगा", "अंबर सौरव कुणाल", "निर्दलीय"},
            {"Jharkhand", "Lohardaga", "Anand Paul Tirkey", "Independent", "26.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10255", "झारखण्ड", "लोहरदगा", "आनंद पॉल तिर्की", "निर्दलीय"},
            {"Jharkhand", "Palamu", "Prayag Ram", "Proutist Sarva Samaj", "2.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10294", "झारखण्ड", "पलामू", "प्रयाग राम", "प्राउटिस्ट सर्व समाज"},
            {"Jharkhand", "Ranchi", "Alok Kumar", "Rashtriya Jansangharsh Swaraj Party", "70000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11676", "", "", "आलोक कुमार", "राष्ट्रीय जनसंघर्ष स्वराज पार्टी"},
            {"Jharkhand", "Ranchi", "Bidyadhar Prasad", "Bahujan Samaj Party", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11382", "", "", "बिद्याधर प्रसाद", "बहुजन समाज पार्टी"},
            {"Jharkhand", "Ranchi", "Sunita Munda", "Ambedkarite Party of India", "2.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11985", "", "", "सुनीता मुंडा", "भारत की अम्बेडकरवादी पार्टी"},
            {"Jharkhand", "Ranchi", "Vikas Chandra Sharma", "Communist Party of India (Marxist–Leninist) Red Star", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11679", "", "", "विकास चंद्र शर्मा", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) रेड स्टार"},
            {"Jharkhand", "Ranchi", "Anjani Pandey", "Independent", "30000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11680", "", "", "अंजनी पांडे", "निर्दलीय"},
            {"Jharkhand", "Ranchi", "Ranjit Mahto", "Peoples Party of India (Democratic)", "16.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11379", "", "", "रंजीत महतो", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
            {"Jharkhand", "Ranchi", "Ramjit Mahto", "Proutist Sarva Samaj", "30Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11375", "", "", "रामजीत महतो", "प्राउटिस्ट सर्व समाज"},
            {"Jharkhand", "Ranchi", "Satish Singh", "Independent", "62.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11372", "", "", "सतीश सिंह", "निर्दलीय"},
    };

    public static final String[][] red_bucket = {
            {"Jharkhand", "Chatra", "Manoj Kumar Yadav", "1", " ", "झारखण्ड", "चतरा", "मनोज कुमार यादव", " "},
            {"Jharkhand", "Chatra", "Sunil Kumar Singh", "1", " ", "झारखण्ड", "चतरा", "सुनील कुमार सिंह", " "},
            {"Jharkhand", "Chatra", "Pankaj Ranjan", "4", " ", "झारखण्ड", "चतरा", "पंकज रंजन", " "},
            {"Jharkhand", "Chatra", "Rajendra Sahu", "4", " ", "झारखण्ड", "चतरा", "राजेंद्र साहू", " "},
            {"Jharkhand", "Chatra", "Sagar Ram", "4", " ", "झारखण्ड", "चतरा", "सागर राम", " "},
            {"Jharkhand", "Chatra", "Jaidullah Ansari", "3", " ", "झारखण्ड", "चतरा", "जयदुल्ला अंसारी", " "},
            {"Jharkhand", "Chatra", "Bagendra Ram", "4", " ", "झारखण्ड", "चतरा", "बगेन्द्र राम", " "},
            {"Jharkhand", "Chatra", "Ashutosh Kumar", "4", " ", "झारखण्ड", "चतरा", "आशुतोष कुमार", " "},
            {"Jharkhand", "Chatra", "Arjun Kumar", "2", " ", "झारखण्ड", "चतरा", "अर्जुन कुमार", " "},
            {"Jharkhand", "Chatra", "Abdul Rajak Ansari", "2", " ", "झारखण्ड", "चतरा", "अब्दुल रजक अंसारी", " "},
            {"Jharkhand", "Chatra", "Ayub Kha", "4", " ", "झारखण्ड", "चतरा", "अयूब खा", " "},
            {"Jharkhand", "Chatra", "Duleshwar Saw", "4", " ", "झारखण्ड", "चतरा", "दुलेश्वर साव", " "},
            {"Jharkhand", "Chatra", "Nageshwar Ganjhu", "4", " ", "झारखण्ड", "चतरा", "नागेश्वर गंझू", " "},
            {"Jharkhand", "Chatra", "Shaukat Ali", "4", " ", "झारखण्ड", "चतरा", "शौकत अली", " "},
            {"Jharkhand", "Chatra", "Bhagalpuri Yadav", "4", " ", "झारखण्ड", "चतरा", "भागलपुरी यादव", " "},
            {"Jharkhand", "Chatra", "Dhananjay Kumar", "4", " ", "झारखण्ड", "चतरा", "धनंजय कुमार", " "},
            {"Jharkhand", "Chatra", "Arun Kumar Yadav", "2", " ", "झारखण्ड", "चतरा", "अरुण कुमार यादव", " "},
            {"Jharkhand", "Chatra", "Subhash Prasad Yadav", "2", " ", "झारखण्ड", "चतरा", "सुभाष प्रसाद यादव", " "},
            {"Jharkhand", "Chatra", "Nand Lal Prasad Keshari", "4", " ", "झारखण्ड", "चतरा", "नंद लाल प्रसाद केशरी", " "},
            {"Jharkhand", "Hazaribagh", "Ramavtar Mahto", "4", " ", "", "", "रामावतार महतो", " "},
            {"Jharkhand", "Hazaribagh", "Bhubaneshwar Prasad Mehta", "2", " ", "", "", "भुवनेश्वर प्रसाद मेहता", " "},
            {"Jharkhand", "Hazaribagh", "Gopal Prasad Sahu", "1", " ", "", "", "गोपाल प्रसाद साहू", " "},
            {"Jharkhand", "Hazaribagh", "Rajni Devi", "4", " ", "", "", "रजनी देवी", " "},
            {"Jharkhand", "Hazaribagh", "Gautam Kumar", "2", " ", "", "", "गौतम कुमार", " "},
            {"Jharkhand", "Hazaribagh", "Jayant Sinha", "1", " ", "", "", "जयंत सिन्हा", " "},
            {"Jharkhand", "Hazaribagh", "Md Mubarak", "4", " ", "", "", "मोद मुबारक", " "},
            {"Jharkhand", "Hazaribagh", "Md. Moin Uddin Ahmad", "2", " ", "", "", "मो। मोइन उद्दीन अहमद", " "},
            {"Jharkhand", "Hazaribagh", "Misbahul Islam", "2", " ", "", "", "मिस्बाहुल इस्लाम", " "},
            {"Jharkhand", "Hazaribagh", "Bhawesh Kumar Mishra", "2", " ", "", "", "भवेश कुमार मिश्रा", " "},
            {"Jharkhand", "Khunti", "Arjun Munda", "1", " ", "", "", "अर्जुन मुंडा", " "},
            {"Jharkhand", "Khunti", "Kali Charan Munda", "1", " ", "", "", "काली चरण मुंडा", " "},
            {"Jharkhand", "Khunti", "Sukhram Herenj", "3", " ", "", "", "सुखराम हेरेंज", " "},
            {"Jharkhand", "Khunti", "Munna Baraik", "4", " ", "", "", "मुन्ना बारिक", " "},
            {"Jharkhand", "Khunti", "Neel Justin Beck", "2", " ", "", "", "नील जस्टिन बेक", " "},
            {"Jharkhand", "Kodarma", "Babu Lal Marandi", "2", " ", "", "", "बाबू लाल मरांडी", " "},
            {"Jharkhand", "Kodarma", "Ajay Krishna", "2", " ", "", "", "अजय कृष्ण", " "},
            {"Jharkhand", "Kodarma", "Dayanand Kumar", "4", " ", "", "", "दयानंद कुमार", " "},
            {"Jharkhand", "Kodarma", "Pradip Turi", "4", " ", "", "", "प्रदीप तुरी", " "},
            {"Jharkhand", "Kodarma", "Shivnath Saw", "4", " ", "", "", "शिवनाथ ने देखा", " "},
            {"Jharkhand", "Kodarma", "Raj Kumar Yadav", "2", " ", "", "", "राज कुमार यादव", " "},
            {"Jharkhand", "Kodarma", "Bayas Kumar", "2", " ", "", "", "ब्यास कुमार", " "},
            {"Jharkhand", "Kodarma", "Sarfaraj Ahmad", "2", " ", "", "", "सरफराज अहमद", " "},
            {"Jharkhand", "Kodarma", "Md Mahboob Alam", "4", " ", "", "", "एमडी महबूब आलम", " "},
            {"Jharkhand", "Kodarma", "Annapurna Devi", "1", " ", "", "", "अन्नपूर्णा देवी", " "},
            {"Jharkhand", "Lohardaga", "Saniya Oraon", "2", " ", "झारखण्ड", "लोहरदगा", "सानीया उरांव", " "},
            {"Jharkhand", "Lohardaga", "Sukhdeo Bhagat", "1", " ", "झारखण्ड", "लोहरदगा", "सुखदेव भगत", " "},
            {"Jharkhand", "Lohardaga", "Sharvan Kumar Panna", "4", " ", "झारखण्ड", "लोहरदगा", "शरवन कुमार पन्ना", " "},
            {"Jharkhand", "Lohardaga", "Dinesh Oraon", "4", " ", "झारखण्ड", "लोहरदगा", "दिनेश उरांव", " "},
            {"Jharkhand", "Lohardaga", "Deo Kumar Dhan", "2", " ", "झारखण्ड", "लोहरदगा", "देव कुमार धन", " "},
            {"Jharkhand", "Lohardaga", "Ekus Dhan", "3", " ", "झारखण्ड", "लोहरदगा", "एकस धन", " "},
            {"Jharkhand", "Lohardaga", "Sudarshan Bhagat", "1", " ", "झारखण्ड", "लोहरदगा", "सुदर्शन भगत", " "},
            {"Jharkhand", "Lohardaga", "Sanjay Oraon", "4", " ", "झारखण्ड", "लोहरदगा", "संजय उरांव", " "},
            {"Jharkhand", "Lohardaga", "Raghunath Mahli", "4", " ", "झारखण्ड", "लोहरदगा", "रघुनाथ महली", " "},
            {"Jharkhand", "Lohardaga", "Kalindar Oraon", "4", " ", "झारखण्ड", "लोहरदगा", "कलिंदर उरांव", " "},
            {"Jharkhand", "Palamu", "Ghuran Ram", "2", " ", "झारखण्ड", "पलामू", "घुरन राम", " "},
            {"Jharkhand", "Palamu", "Uday Kumar Paswan", "4", " ", "झारखण्ड", "पलामू", "उदय कुमार पासवान", " "},
            {"Jharkhand", "Palamu", "Satyendra Kumar Paswan", "4", " ", "झारखण्ड", "पलामू", "सत्येंद्र कुमार पासवान", " "},
            {"Jharkhand", "Palamu", "Shravan Kumar Ravi", "4", " ", "झारखण्ड", "पलामू", "श्रवण कुमार रवि", " "},
            {"Jharkhand", "Palamu", "Anjana Bhuiyan", "4", " ", "झारखण्ड", "पलामू", "अंजना भुइयां", " "},
            {"Jharkhand", "Palamu", "Madan Ram", "4", " ", "झारखण्ड", "पलामू", "मदन राम", " "},
            {"Jharkhand", "Palamu", "Baban Bhuiya", "4", " ", "झारखण्ड", "पलामू", "बबन भुइया", " "},
            {"Jharkhand", "Palamu", "Sushma Mehta", "2", " ", "झारखण्ड", "पलामू", "सुषमा मेहता", " "},
            {"Jharkhand", "Palamu", "Vijay Ram", "4", " ", "झारखण्ड", "पलामू", "विजय राम", " "},
            {"Jharkhand", "Palamu", "Dinesh Ram", "2", " ", "झारखण्ड", "पलामू", "दिनेश राम", " "},
            {"Jharkhand", "Palamu", "Balkesh Prasad Paswan", "4", " ", "झारखण्ड", "पलामू", "बालकेश प्रसाद पासवान", " "},
            {"Jharkhand", "Palamu", "Amindra Paswan", "4", " ", "झारखण्ड", "पलामू", "अमिंद्र पासवान", " "},
            {"Jharkhand", "Palamu", "Jorawar Ram", "2", " ", "झारखण्ड", "पलामू", "जोरावर राम", " "},
            {"Jharkhand", "Palamu", "Umesh Kumar Paswan", "4", " ", "झारखण्ड", "पलामू", "उमेश कुमार पासवान", " "},
            {"Jharkhand", "Palamu", "Vishnu Dayal Ram", "1", " ", "झारखण्ड", "पलामू", "विष्णु दयाल राम", " "},
            {"Jharkhand", "Palamu", "Ramji Paswan", "2", " ", "झारखण्ड", "पलामू", "रामजी पासवान", " "},
            {"Jharkhand", "Palamu", "Shyam Narayan Bhuiya", "2", " ", "झारखण्ड", "पलामू", "श्याम नारायण भुईया", " "},
            {"Jharkhand", "Palamu", "Vijay Kumar", "4", " ", "झारखण्ड", "पलामू", "विजय कुमार", " "},
            {"Jharkhand", "Ranchi", "Jitendra Thakur", "4", " ", "", "", "जितेंद्र ठाकुर", " "},
            {"Jharkhand", "Ranchi", "Sidheshwar Singh", "3", " ", "", "", "सिद्धेश्वर सिंह", " "},
            {"Jharkhand", "Ranchi", "Amar Kumar Mahto", "4", " ", "", "", "अमर कुमार महतो", " "},
            {"Jharkhand", "Ranchi", "Parmeshwar Mahto", "4", " ", "", "", "परमेस्वर महतो", " "},
            {"Jharkhand", "Ranchi", "Rajesh Kumar", "4", " ", "", "", "राजेश कुमार", " "},
            {"Jharkhand", "Ranchi", "Rajesh Thapa", "4", " ", "", "", "राजेश थापा", " "},
            {"Jharkhand", "Ranchi", "Sanjay Seth", "1", " ", "", "", "संजय सेठ", " "},
            {"Jharkhand", "Ranchi", "Subodh Kant Sahay", "1", " ", "", "", "सुबोधकांत सहाय", " "},
            {"Jharkhand", "Ranchi", "Raju Mahto", "2", " ", "", "", "राजू महतो", " "},
            {"Jharkhand", "Ranchi", "Jay Prakash Prasad", "4", " ", "", "", "जय प्रकाश प्रसाद", " "},
            {"Jharkhand", "Ranchi", "Ram Tahal. Choudhary", "3", " ", "", "", "राम टहल। चौधरी", " "},
            {"Jharkhand", "Ranchi", "Nand Kishor Yadav", "4", " ", "", "", "नंद किशोर यादव", " "},
    };

}