/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Jharkhand {
    public static final String[][] green_bucket = {
            {"Jharkhand", "Chatra", "Pramod Toppo", "Independent", "1.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10242", "झारखण्ड", "चतरा", "प्रमोद टोप्पो", "निर्दलीय"},
            {"Jharkhand", "Chatra", "Ramanand Das", "Bhartiya Sarvodaya Party", "43.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10244", "झारखण्ड", "चतरा", "रामानंद दास", "भारतीय सर्वोदय पार्टी"},
            {"Jharkhand", "Chatra", "Manoj Kumar Pandey", "Independent", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10234", "झारखण्ड", "चतरा", "मनोज कुमार पांडे", "निर्दलीय"},
            {"Jharkhand", "Chatra", "Nandlal Prasad", "Independent", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10238", "झारखण्ड", "चतरा", "नंदलाल प्रसाद", "निर्दलीय"},
            {"Jharkhand", "Chatra", "Yogendra Yadav", "Independent", "19.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10251", "झारखण्ड", "चतरा", "योगेंद्र यादव", "निर्दलीय"},
            {"Jharkhand", "Chatra", "Rameshi Ram", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10245", "झारखण्ड", "चतरा", "रमेशी राम", "निर्दलीय"},
            {"Jharkhand", "Dhanbad", "Sudhir Kumar Mahato", "Bahujan Mukti Party", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13518", "झारखण्ड", "धनबाद", "सुधीर कुमार महतो", "बहुजन मुक्ति पार्टी"},
            {"Jharkhand", "Dhanbad", "Varun Kumar", "Independent", "92800", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12899", "झारखण्ड", "धनबाद", "वरुण कुमार", "निर्दलीय"},
            {"Jharkhand", "Dhanbad", "Meghnath Rawani", "Bahujan Samaj Party", "36.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12901", "झारखण्ड", "धनबाद", "मेघनाथ रावणी", "बहुजन समाज पार्टी"},
            {"Jharkhand", "Dhanbad", "Rajesh Kumar Singh", "Independent", "2.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12894", "झारखण्ड", "धनबाद", "राजेश कुमार सिंह", "निर्दलीय"},
            {"Jharkhand", "Dumka", "Baghrai Soren", "Independent", "6.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13000", "झारखण्ड", "दुमका", "बाघराय सोरेन", "निर्दलीय"},
            {"Jharkhand", "Dumka", "Dr. Shrilal Kisku", "Independent", "30.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13951", "झारखण्ड", "दुमका", "डॉ। श्रीलाल किस्कू", "निर्दलीय"},
            {"Jharkhand", "Dumka", "Rajesh Besra", "Independent", "1.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13950", "झारखण्ड", "दुमका", "राजेश बेसरा", "निर्दलीय"},
            {"Jharkhand", "Giridih", "Rajendra Dasaundhi", "Independent", "6.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12213", "झारखण्ड", "गिरिडीह", "राजेन्द्र दसौंधी", "निर्दलीय"},
            {"Jharkhand", "Giridih", "Shibu Singh", "Bhartiya Manavadhikaar Federal Party", "17Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12889", "झारखण्ड", "गिरिडीह", "शिबू सिंह", "भारतीय मानववादी फेडरल पार्टी"},
            {"Jharkhand", "Giridih", "Sunita Tudu", "Independent", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12888", "झारखण्ड", "गिरिडीह", "सुनीता टुडू", "निर्दलीय"},
            {"Jharkhand", "Giridih", "Chandra Deo Prasad", "Aihra National Party", "21Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12884", "झारखण्ड", "गिरिडीह", "चंद्र देव प्रसाद", "ऐहरा नेशनल पार्टी"},
            {"Jharkhand", "Giridih", "Simmi Suman", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12215", "झारखण्ड", "गिरिडीह", "सिम्मी सुमन", "निर्दलीय"},
            {"Jharkhand", "Godda", "Mahesh Kumar Suman", "Independent", "2.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14093", "झारखण्ड", "गोड्डा", "महेश कुमार सुमन", "निर्दलीय"},
            {"Jharkhand", "Godda", "Anup Kumar Sinha", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14090", "झारखण्ड", "गोड्डा", "अनूप कुमार सिन्हा", "निर्दलीय"},
            {"Jharkhand", "Godda", "Noor Hassan", "Rashtriya Samta Party (Secular)", "20.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14087", "झारखण्ड", "गोड्डा", "नूर हसन", "राष्ट्रीय समता पार्टी (धर्मनिरपेक्ष)"},
            {"Jharkhand", "Godda", "Asha Makede", "Pichhara Samaj Party United", "10000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14086", "झारखण्ड", "गोड्डा", "आशा मक्केड", "पिच्छारा समाज पार्टी यूनाइटेड"},
            {"Jharkhand", "Godda", "Zaffar Obaid", "Bahujan Samaj Party", "8.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12997", "झारखण्ड", "गोड्डा", "जफर ओबैद", "बहुजन समाज पार्टी"},
            {"Jharkhand", "Hazaribagh", "Jagat Kumar Soni", "Bhartiya Azad Sena", "27.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11955", "झारखण्ड", "हजारीबाग", "जगत कुमार सोनी", "भारतीय आजाद सेना"},
            {"Jharkhand", "Hazaribagh", "Rameshwar Ram Kushwaha", "All India Forward Bloc", "8.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11353", "झारखण्ड", "हजारीबाग", "रामेश्वर राम कुशवाहा", "ऑल इंडिया फॉरवर्ड ब्लॉक"},
            {"Jharkhand", "Hazaribagh", "Vinod Kumar", "Bahujan Samaj Party", "2.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11354", "झारखण्ड", "हजारीबाग", "विनोद कुमार", "बहुजन समाज पार्टी"},
            {"Jharkhand", "Hazaribagh", "Tekochand Mahto", "Independent", "26.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11959", "झारखण्ड", "हजारीबाग", "टेकचंद महतो", "निर्दलीय"},
            {"Jharkhand", "Hazaribagh", "Rajesh Ranjan", "Socialist Unity Centre of India (Communist)", "15.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11167", "झारखण्ड", "हजारीबाग", "राजेश रंजन", "भारतीय समाजवादी एकता केंद्र (कम्युनिस्ट)"},
            {"Jharkhand", "Hazaribagh", "Krishna Kumar Singh", "Bharat Prabhat Party", "27Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11956", "झारखण्ड", "हजारीबाग", "कृष्ण कुमार सिंह", "भारत प्रभात पार्टी"},
            {"Jharkhand", "Jamshedpur", "Sarita Anand", "Independent", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13351", "झारखण्ड", "जमशेदपुर", "सरिता आनंद", "निर्दलीय"},
            {"Jharkhand", "Jamshedpur", "Anjana Mahata", "All India Trinamool Congress", "80.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12217", "झारखण्ड", "जमशेदपुर", "अंजना महत", "अखिल भारतीय तृणमूल कांग्रेस"},
            {"Jharkhand", "Jamshedpur", "Subrat Kumar Pradhan", "Ambedkarite Party of India", "3.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12905", "झारखण्ड", "जमशेदपुर", "सुब्रत कुमार प्रधान", "भारत की अम्बेडकरवादी पार्टी"},
            {"Jharkhand", "Jamshedpur", "Asit Kumar Singh", "Independent", "24.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13346", "झारखण्ड", "जमशेदपुर", "असित कुमार सिंह", "निर्दलीय"},
            {"Jharkhand", "Jamshedpur", "Chandra Shekhar Mahato", "Peoples Party of India (Democratic)", "32.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12912", "झारखण्ड", "जमशेदपुर", "चंद्र शेखर महतो", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
            {"Jharkhand", "Jamshedpur", "Rakesh Kumar", "Independent", "74Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13349", "झारखण्ड", "जमशेदपुर", "राकेश कुमार", "निर्दलीय"},
            {"Jharkhand", "Jamshedpur", "Panmani Singh", "Socialist Unity Centre of India (Communist)", "42.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12913", "झारखण्ड", "जमशेदपुर", "पानमणि सिंह", "भारतीय समाजवादी एकता केंद्र (कम्युनिस्ट)"},
            {"Jharkhand", "Jamshedpur", "Shailesh Kumar Singh", "Independent", "3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13350", "झारखण्ड", "जमशेदपुर", "शैलेश कुमार सिंह", "निर्दलीय"},
            {"Jharkhand", "Jamshedpur", "Ranjit Kumar Singh", "Jharkhand Party", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12910", "झारखण्ड", "जमशेदपुर", "रंजीत कुमार सिंह", "झारखंड पार्टी"},
            {"Jharkhand", "Jamshedpur", "Mahesh Kumar", "Right to Recall Party", "10.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12218", "झारखण्ड", "जमशेदपुर", "महेश कुमार", "राइट टू रिकॉल पार्टी"},
            {"Jharkhand", "Khunti", "Niyaran Herenj", "Independent", "19.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11968", "झारखण्ड", "खूंटी", "नियरन हेरेंज", "निर्दलीय"},
            {"Jharkhand", "Khunti", "Ajay Topno", "Jharkhand Party", "81.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11359", "झारखण्ड", "खूंटी", "अजय टोपनो", "झारखंड पार्टी"},
            {"Jharkhand", "Khunti", "Indumati Mundu", "Bahujan Samaj Party", "13.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11170", "झारखण्ड", "खूंटी", "इंदुमती मुंडु", "बहुजन समाज पार्टी"},
            {"Jharkhand", "Khunti", "Sibil Kandulna", "Rashtriya Sangail Party", "46.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11360", "झारखण्ड", "खूंटी", "सिबिल कंडुलना", "राष्ट्रीय संगठन पार्टी"},
            {"Jharkhand", "Khunti", "Abinashi Mundu", "Hum Bhartiya Party", "11.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11964", "झारखण्ड", "खूंटी", "अबिनाशी मुंडू", "हम भारतीय पार्टी"},
            {"Jharkhand", "Khunti", "Meenakshi Munda", "Independent", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11967", "झारखण्ड", "खूंटी", "मीनाक्षी मुंडा", "निर्दलीय"},
            {"Jharkhand", "Kodarma", "Tuklal Nayak", "Hindusthan Nirman Dal", "25Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11370", "झारखण्ड", "कोडरमा", "तुकलाल नायक", "हिंदुस्तान निर्माण दल"},
            {"Jharkhand", "Kodarma", "Rameshwar Pd Yadav", "Independent", "13.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11672", "झारखण्ड", "कोडरमा", "रामेश्वर पीडी यादव", "निर्दलीय"},
            {"Jharkhand", "Kodarma", "Kanchan Kumari", "All India Trinamool Congress", "52.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11671", "झारखण्ड", "कोडरमा", "कंचन कुमारी", "अखिल भारतीय तृणमूल कांग्रेस"},
            {"Jharkhand", "Kodarma", "Avadhesh Kumar Singh", "Vishva SHakti Party", "19Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11365", "झारखण्ड", "कोडरमा", "अवधेश कुमार सिंह", "विश्वाशक्ति पार्टी"},
            {"Jharkhand", "Lohardaga", "Aalone Baxla", "Independent", "27.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10252", "झारखण्ड", "लोहरदगा", "अलोन बक्सला", "निर्दलीय"},
            {"Jharkhand", "Lohardaga", "Ajit Kumar Bhagat", "Independent", "25.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10253", "झारखण्ड", "लोहरदगा", "अजीत कुमार भगत", "निर्दलीय"},
            {"Jharkhand", "Lohardaga", "Ambar Saurav Kunal", "Independent", "20Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10254", "झारखण्ड", "लोहरदगा", "अंबर सौरव कुणाल", "निर्दलीय"},
            {"Jharkhand", "Lohardaga", "Anand Paul Tirkey", "Independent", "26.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10255", "झारखण्ड", "लोहरदगा", "आनंद पॉल तिर्की", "निर्दलीय"},
            {"Jharkhand", "Palamu", "Prayag Ram", "Proutist Sarva Samaj", "2.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10294", "झारखण्ड", "पलामू", "प्रयाग राम", "प्राउटिस्ट सर्व समाज"},
            {"Jharkhand", "Rajmahal", "Neeraj Hembrom", "All India Forward Bloc", "2.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12996", "झारखण्ड", "राजमहल", "नीरज हेम्ब्रोम", "ऑल इंडिया फॉरवर्ड ब्लॉक"},
            {"Jharkhand", "Rajmahal", "Gopin Soren", "Communist Party of India (Marxist)", "24Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12992", "झारखण्ड", "राजमहल", "गोपी सोरेन", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
            {"Jharkhand", "Rajmahal", "Barnad Hembrom", "Independent", "32.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14102", "झारखण्ड", "राजमहल", "बरनाद हम्ब्रोम", "निर्दलीय"},
            {"Jharkhand", "Rajmahal", "Monika Kisku", "All India Trinamool Congress", "49.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=14099", "झारखण्ड", "राजमहल", "मोनिका किस्कू", "अखिल भारतीय तृणमूल कांग्रेस"},
            {"Jharkhand", "Ranchi", "Alok Kumar", "Rashtriya Jansangharsh Swaraj Party", "70000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11676", "झारखण्ड", "रांची", "आलोक कुमार", "राष्ट्रीय जनसंघर्ष स्वराज पार्टी"},
            {"Jharkhand", "Ranchi", "Bidyadhar Prasad", "Bahujan Samaj Party", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11382", "झारखण्ड", "रांची", "बिद्याधर प्रसाद", "बहुजन समाज पार्टी"},
            {"Jharkhand", "Ranchi", "Sunita Munda", "Ambedkarite Party of India", "2.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11985", "झारखण्ड", "रांची", "सुनीता मुंडा", "भारत की अम्बेडकरवादी पार्टी"},
            {"Jharkhand", "Ranchi", "Vikas Chandra Sharma", "Communist Party of India (Marxist–Leninist) Red Star", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11679", "झारखण्ड", "रांची", "विकास चंद्र शर्मा", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) रेड स्टार"},
            {"Jharkhand", "Ranchi", "Anjani Pandey", "Independent", "30000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11680", "झारखण्ड", "रांची", "अंजनी पांडे", "निर्दलीय"},
            {"Jharkhand", "Ranchi", "Ranjit Mahto", "Peoples Party of India (Democratic)", "16.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11379", "झारखण्ड", "रांची", "रंजीत महतो", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
            {"Jharkhand", "Ranchi", "Ramjit Mahto", "Proutist Sarva Samaj", "30Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11375", "झारखण्ड", "रांची", "रामजीत महतो", "प्राउटिस्ट सर्व समाज"},
            {"Jharkhand", "Ranchi", "Satish Singh", "Independent", "62.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11372", "झारखण्ड", "रांची", "सतीश सिंह", "निर्दलीय"},
            {"Jharkhand", "Singhbhum", "Anil Soren", "Independent", "20.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12879", "झारखण्ड", "सिंहभूम", "अनिल सोरेन", "निर्दलीय"},
            {"Jharkhand", "Singhbhum", "Krishna Mardi", "Jharkhand Mukti Morcha (Ulgulan)", "19.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12880", "झारखण्ड", "सिंहभूम", "कृष्णा मार्डी", "झारखंड मुक्ति मोर्चा (उलगुलान)"},
            {"Jharkhand", "Singhbhum", "Pushpa Sinku", "Independent", "1.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12878", "झारखण्ड", "सिंहभूम", "पुष्पा सिंकु", "निर्दलीय"},
            {"Jharkhand", "Singhbhum", "Chandra Mohan Hembrom", "Socialist Unity Centre of India (Communist)", "94310", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12224", "झारखण्ड", "सिंहभूम", "चन्द्र मोहन हम्ब्रोम", "भारतीय समाजवादी एकता केंद्र (कम्युनिस्ट)"},
            {"Jharkhand", "Singhbhum", "Pratap Singh Banara", "Ambedkarite Party of India", "52985", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12223", "झारखण्ड", "सिंहभूम", "प्रताप सिंह बानरा", "भारत की अम्बेडकरवादी पार्टी"},
    };

    public static final String[][] red_bucket = {
            {"Jharkhand", "Chatra", "Manoj Kumar Yadav", "1", " ", "झारखण्ड", "चतरा", "मनोज कुमार यादव", " "},
            {"Jharkhand", "Chatra", "Sunil Kumar Singh", "1", " ", "झारखण्ड", "चतरा", "सुनील कुमार सिंह", " "},
            {"Jharkhand", "Chatra", "Pankaj Ranjan", "4", " ", "झारखण्ड", "चतरा", "पंकज रंजन", " "},
            {"Jharkhand", "Chatra", "Rajendra Sahu", "4", " ", "झारखण्ड", "चतरा", "राजेंद्र साहू", " "},
            {"Jharkhand", "Chatra", "Sagar Ram", "4", " ", "झारखण्ड", "चतरा", "सागर राम", " "},
            {"Jharkhand", "Chatra", "Jaidullah Ansari", "3", " ", "झारखण्ड", "चतरा", "जयदुल्ला अंसारी", " "},
            {"Jharkhand", "Chatra", "Bagendra Ram", "4", " ", "झारखण्ड", "चतरा", "बगेन्द्र राम", " "},
            {"Jharkhand", "Chatra", "Ashutosh Kumar", "4", " ", "झारखण्ड", "चतरा", "आशुतोष कुमार", " "},
            {"Jharkhand", "Chatra", "Arjun Kumar", "2", " ", "झारखण्ड", "चतरा", "अर्जुन कुमार", " "},
            {"Jharkhand", "Chatra", "Abdul Rajak Ansari", "2", " ", "झारखण्ड", "चतरा", "अब्दुल रजक अंसारी", " "},
            {"Jharkhand", "Chatra", "Ayub Kha", "4", " ", "झारखण्ड", "चतरा", "अयूब खा", " "},
            {"Jharkhand", "Chatra", "Duleshwar Saw", "4", " ", "झारखण्ड", "चतरा", "दुलेश्वर साव", " "},
            {"Jharkhand", "Chatra", "Nageshwar Ganjhu", "4", " ", "झारखण्ड", "चतरा", "नागेश्वर गंझू", " "},
            {"Jharkhand", "Chatra", "Shaukat Ali", "4", " ", "झारखण्ड", "चतरा", "शौकत अली", " "},
            {"Jharkhand", "Chatra", "Bhagalpuri Yadav", "4", " ", "झारखण्ड", "चतरा", "भागलपुरी यादव", " "},
            {"Jharkhand", "Chatra", "Dhananjay Kumar", "4", " ", "झारखण्ड", "चतरा", "धनंजय कुमार", " "},
            {"Jharkhand", "Chatra", "Arun Kumar Yadav", "2", " ", "झारखण्ड", "चतरा", "अरुण कुमार यादव", " "},
            {"Jharkhand", "Chatra", "Subhash Prasad Yadav", "2", " ", "झारखण्ड", "चतरा", "सुभाष प्रसाद यादव", " "},
            {"Jharkhand", "Chatra", "Nand Lal Prasad Keshari", "4", " ", "झारखण्ड", "चतरा", "नंद लाल प्रसाद केशरी", " "},
            {"Jharkhand", "Dhanbad", "K.C.Singh Raj", "3", " ", "झारखण्ड", "धनबाद", "केसीसिंह राज", " "},
            {"Jharkhand", "Dhanbad", "Meraj Khan", "2", " ", "झारखण्ड", "धनबाद", "मेराज खान", " "},
            {"Jharkhand", "Dhanbad", "Deepak Kumar Das", "4", " ", "झारखण्ड", "धनबाद", "दीपक कुमार दास", " "},
            {"Jharkhand", "Dhanbad", "Sanjay Paswan", "4", " ", "झारखण्ड", "धनबाद", "संजय पासवान", " "},
            {"Jharkhand", "Dhanbad", "Lakshmi Devi", "4", " ", "झारखण्ड", "धनबाद", "लक्ष्मी देवी", " "},
            {"Jharkhand", "Dhanbad", "Pashupati Nath Singh", "1", " ", "झारखण्ड", "धनबाद", "पशुपति नाथ सिंह", " "},
            {"Jharkhand", "Dhanbad", "Umesh Paswan", "4", " ", "झारखण्ड", "धनबाद", "उमेश पासवान", " "},
            {"Jharkhand", "Dhanbad", "Mihir Chandra Mahato", "4", " ", "झारखण्ड", "धनबाद", "मिहिर चंद्र महतो", " "},
            {"Jharkhand", "Dhanbad", "Mantosh Kumar Mandal", "3", " ", "झारखण्ड", "धनबाद", "मंतोष कुमार मंडल", " "},
            {"Jharkhand", "Dhanbad", "Kirti Azad", "1", " ", "झारखण्ड", "धनबाद", "कीर्ति आज़ाद", " "},
            {"Jharkhand", "Dhanbad", "Bamapada Bauri", "2", " ", "झारखण्ड", "धनबाद", "बमपद बौरी", " "},
            {"Jharkhand", "Dhanbad", "Madhvi Singh", "4", " ", "झारखण्ड", "धनबाद", "माधवी सिंह", " "},
            {"Jharkhand", "Dhanbad", "Siddharth Gautam", "2", " ", "झारखण्ड", "धनबाद", "सिद्धार्थ गौतम", " "},
            {"Jharkhand", "Dhanbad", "Prem Prakash Paswan", "4", " ", "झारखण्ड", "धनबाद", "प्रेम प्रकाश पासवान", " "},
            {"Jharkhand", "Dhanbad", "Ram Lal Mahto", "3", " ", "झारखण्ड", "धनबाद", "राम लाल महतो", " "},
            {"Jharkhand", "Dhanbad", "Heera Lal Shankhvar", "3", " ", "झारखण्ड", "धनबाद", "हीरा लाल शंखवार", " "},
            {"Jharkhand", "Dumka", "Satish Soren", "3", " ", "झारखण्ड", "दुमका", "सतीश सोरेन", " "},
            {"Jharkhand", "Dumka", "Shibu Soren", "3", " ", "झारखण्ड", "दुमका", "शिबू सोरेन", " "},
            {"Jharkhand", "Dumka", "Raska Soren", "3", " ", "झारखण्ड", "दुमका", "रस्का सोरेन", " "},
            {"Jharkhand", "Dumka", "Stephan Besra", "4", " ", "झारखण्ड", "दुमका", "स्टीफन बेसरा", " "},
            {"Jharkhand", "Dumka", "Samuel Tudu", "4", " ", "झारखण्ड", "दुमका", "सैमुअल टुडू", " "},
            {"Jharkhand", "Dumka", "Ramesh Tudu", "4", " ", "झारखण्ड", "दुमका", "रमेश टुडू", " "},
            {"Jharkhand", "Dumka", "Senapati Murmu", "4", " ", "झारखण्ड", "दुमका", "सेनापति मुर्मू", " "},
            {"Jharkhand", "Dumka", "Sunil Soren", "1", " ", "झारखण्ड", "दुमका", "सुनील सोरेन", " "},
            {"Jharkhand", "Dumka", "Mohril Murmu", "3", " ", "झारखण्ड", "दुमका", "मोहिल मुर्मू", " "},
            {"Jharkhand", "Dumka", "Probina Murmu", "4", " ", "झारखण्ड", "दुमका", "प्रोबिना मुर्मू", " "},
            {"Jharkhand", "Dumka", "Thakuroon Soren", "2", " ", "झारखण्ड", "दुमका", "ठाकुरों सोरेन", " "},
            {"Jharkhand", "Dumka", "Arjun Pujhar", "4", " ", "झारखण्ड", "दुमका", "अर्जुन पुजहर", " "},
            {"Jharkhand", "Giridih", "Madhu Sudan", "4", " ", "झारखण्ड", "गिरिडीह", "मधु सूदन", " "},
            {"Jharkhand", "Giridih", "Chandra Prakash Choudhary", "2", " ", "झारखण्ड", "गिरिडीह", "चंद्र प्रकाश चौधरी", " "},
            {"Jharkhand", "Giridih", "Jagarnath Mahto", "2", " ", "झारखण्ड", "गिरिडीह", "जगरनाथ महतो", " "},
            {"Jharkhand", "Giridih", "Rasul Baksh", "2", " ", "झारखण्ड", "गिरिडीह", "रसूल बख्श", " "},
            {"Jharkhand", "Giridih", "Sanjeev Kumar Mahato", "4", " ", "झारखण्ड", "गिरिडीह", "संजीव कुमार महतो", " "},
            {"Jharkhand", "Giridih", "Ahmad Ansari", "4", " ", "झारखण्ड", "गिरिडीह", "अहमद अंसारी", " "},
            {"Jharkhand", "Giridih", "Dwaraka Prasad Lala", "2", " ", "झारखण्ड", "गिरिडीह", "द्वारका प्रसाद लाला", " "},
            {"Jharkhand", "Giridih", "Amit Jani", "2", " ", "झारखण्ड", "गिरिडीह", "अमित जानी", " "},
            {"Jharkhand", "Giridih", "Jogeshwar Thakur", "2", " ", "झारखण्ड", "गिरिडीह", "जोगेश्वर ठाकुर", " "},
            {"Jharkhand", "Giridih", "Sohrab Shah", "4", " ", "झारखण्ड", "गिरिडीह", "सोहराब शाह", " "},
            {"Jharkhand", "Godda", "Birendra Kumar", "2", " ", "झारखण्ड", "गोड्डा", "बीरेंद्र कुमार", " "},
            {"Jharkhand", "Godda", "Nishikant Dubey", "1", " ", "झारखण्ड", "गोड्डा", "निशिकांत दुबे", " "},
            {"Jharkhand", "Godda", "K. Rangaiah", "3", " ", "झारखण्ड", "गोड्डा", "के। रंगैया", " "},
            {"Jharkhand", "Godda", "Madhusudan Ray", "4", " ", "झारखण्ड", "गोड्डा", "मधुसूदन रे", " "},
            {"Jharkhand", "Godda", "Jitendra Kumar Barnwal", "4", " ", "झारखण्ड", "गोड्डा", "जितेंद्र कुमार बर्णवाल", " "},
            {"Jharkhand", "Godda", "Murari Kapri", "4", " ", "झारखण्ड", "गोड्डा", "मुरारी कापरी", " "},
            {"Jharkhand", "Godda", "Pradeep Yadav", "2", " ", "झारखण्ड", "गोड्डा", "प्रदीप यादव", " "},
            {"Jharkhand", "Hazaribagh", "Ramavtar Mahto", "4", " ", "झारखण्ड", "हजारीबाग", "रामावतार महतो", " "},
            {"Jharkhand", "Hazaribagh", "Bhubaneshwar Prasad Mehta", "2", " ", "झारखण्ड", "हजारीबाग", "भुवनेश्वर प्रसाद मेहता", " "},
            {"Jharkhand", "Hazaribagh", "Gopal Prasad Sahu", "1", " ", "झारखण्ड", "हजारीबाग", "गोपाल प्रसाद साहू", " "},
            {"Jharkhand", "Hazaribagh", "Rajni Devi", "4", " ", "झारखण्ड", "हजारीबाग", "रजनी देवी", " "},
            {"Jharkhand", "Hazaribagh", "Gautam Kumar", "2", " ", "झारखण्ड", "हजारीबाग", "गौतम कुमार", " "},
            {"Jharkhand", "Hazaribagh", "Jayant Sinha", "1", " ", "झारखण्ड", "हजारीबाग", "जयंत सिन्हा", " "},
            {"Jharkhand", "Hazaribagh", "Md Mubarak", "4", " ", "झारखण्ड", "हजारीबाग", "मोद मुबारक", " "},
            {"Jharkhand", "Hazaribagh", "Md. Moin Uddin Ahmad", "2", " ", "झारखण्ड", "हजारीबाग", "मो। मोइन उद्दीन अहमद", " "},
            {"Jharkhand", "Hazaribagh", "Misbahul Islam", "2", " ", "झारखण्ड", "हजारीबाग", "मिस्बाहुल इस्लाम", " "},
            {"Jharkhand", "Hazaribagh", "Bhawesh Kumar Mishra", "2", " ", "झारखण्ड", "हजारीबाग", "भवेश कुमार मिश्रा", " "},
            {"Jharkhand", "Jamshedpur", "Mubin Khan", "4", " ", "झारखण्ड", "जमशेदपुर", "मुबीन खान", " "},
            {"Jharkhand", "Jamshedpur", "Ashraf Hussain", "4", " ", "झारखण्ड", "जमशेदपुर", "अशरफ हुसैन", " "},
            {"Jharkhand", "Jamshedpur", "Sabita Kaibarto", "4", " ", "झारखण्ड", "जमशेदपुर", "सबिता काइबर्तो", " "},
            {"Jharkhand", "Jamshedpur", "Qamar Raza Khan", "4", " ", "झारखण्ड", "जमशेदपुर", "क़मर रज़ा ख़ान", " "},
            {"Jharkhand", "Jamshedpur", "Shekh Akhir Uddin", "2", " ", "झारखण्ड", "जमशेदपुर", "शेख अखिर उद्दीन", " "},
            {"Jharkhand", "Jamshedpur", "Bidyut Baran Mahato", "1", " ", "झारखण्ड", "जमशेदपुर", "बिद्युत बरन महतो", " "},
            {"Jharkhand", "Jamshedpur", "Dinesh Mahato", "2", " ", "झारखण्ड", "जमशेदपुर", "दिनेश महतो", " "},
            {"Jharkhand", "Jamshedpur", "Asjadullah Imran", "2", " ", "झारखण्ड", "जमशेदपुर", "असजदुल्लाह इमरान", " "},
            {"Jharkhand", "Jamshedpur", "Champai Soren", "2", " ", "झारखण्ड", "जमशेदपुर", "चंपई सोरेन", " "},
            {"Jharkhand", "Jamshedpur", "Deepak Kumar Giri", "4", " ", "झारखण्ड", "जमशेदपुर", "दीपक कुमार गिरि", " "},
            {"Jharkhand", "Jamshedpur", "Malay Kumar Mahato", "4", " ", "झारखण्ड", "जमशेदपुर", "मलय कुमार महतो", " "},
            {"Jharkhand", "Jamshedpur", "Angad Mahato", "4", " ", "झारखण्ड", "जमशेदपुर", "अंगद महतो", " "},
            {"Jharkhand", "Jamshedpur", "Surya Singh Besra", "2", " ", "झारखण्ड", "जमशेदपुर", "सूर्य सिंह बेसरा", " "},
            {"Jharkhand", "Khunti", "Arjun Munda", "1", " ", "झारखण्ड", "खूंटी", "अर्जुन मुंडा", " "},
            {"Jharkhand", "Khunti", "Kali Charan Munda", "1", " ", "झारखण्ड", "खूंटी", "काली चरण मुंडा", " "},
            {"Jharkhand", "Khunti", "Sukhram Herenj", "3", " ", "झारखण्ड", "खूंटी", "सुखराम हेरेंज", " "},
            {"Jharkhand", "Khunti", "Munna Baraik", "4", " ", "झारखण्ड", "खूंटी", "मुन्ना बारिक", " "},
            {"Jharkhand", "Khunti", "Neel Justin Beck", "2", " ", "झारखण्ड", "खूंटी", "नील जस्टिन बेक", " "},
            {"Jharkhand", "Kodarma", "Babu Lal Marandi", "2", " ", "झारखण्ड", "कोडरमा", "बाबू लाल मरांडी", " "},
            {"Jharkhand", "Kodarma", "Ajay Krishna", "2", " ", "झारखण्ड", "कोडरमा", "अजय कृष्ण", " "},
            {"Jharkhand", "Kodarma", "Dayanand Kumar", "4", " ", "झारखण्ड", "कोडरमा", "दयानंद कुमार", " "},
            {"Jharkhand", "Kodarma", "Pradip Turi", "4", " ", "झारखण्ड", "कोडरमा", "प्रदीप तुरी", " "},
            {"Jharkhand", "Kodarma", "Shivnath Saw", "4", " ", "झारखण्ड", "कोडरमा", "शिवनाथ ने देखा", " "},
            {"Jharkhand", "Kodarma", "Raj Kumar Yadav", "2", " ", "झारखण्ड", "कोडरमा", "राज कुमार यादव", " "},
            {"Jharkhand", "Kodarma", "Bayas Kumar", "2", " ", "झारखण्ड", "कोडरमा", "ब्यास कुमार", " "},
            {"Jharkhand", "Kodarma", "Sarfaraj Ahmad", "2", " ", "झारखण्ड", "कोडरमा", "सरफराज अहमद", " "},
            {"Jharkhand", "Kodarma", "Md Mahboob Alam", "4", " ", "झारखण्ड", "कोडरमा", "एमडी महबूब आलम", " "},
            {"Jharkhand", "Kodarma", "Annapurna Devi", "1", " ", "झारखण्ड", "कोडरमा", "अन्नपूर्णा देवी", " "},
            {"Jharkhand", "Lohardaga", "Saniya Oraon", "2", " ", "झारखण्ड", "लोहरदगा", "सानीया उरांव", " "},
            {"Jharkhand", "Lohardaga", "Sukhdeo Bhagat", "1", " ", "झारखण्ड", "लोहरदगा", "सुखदेव भगत", " "},
            {"Jharkhand", "Lohardaga", "Sharvan Kumar Panna", "4", " ", "झारखण्ड", "लोहरदगा", "शरवन कुमार पन्ना", " "},
            {"Jharkhand", "Lohardaga", "Dinesh Oraon", "4", " ", "झारखण्ड", "लोहरदगा", "दिनेश उरांव", " "},
            {"Jharkhand", "Lohardaga", "Deo Kumar Dhan", "2", " ", "झारखण्ड", "लोहरदगा", "देव कुमार धन", " "},
            {"Jharkhand", "Lohardaga", "Ekus Dhan", "3", " ", "झारखण्ड", "लोहरदगा", "एकस धन", " "},
            {"Jharkhand", "Lohardaga", "Sudarshan Bhagat", "1", " ", "झारखण्ड", "लोहरदगा", "सुदर्शन भगत", " "},
            {"Jharkhand", "Lohardaga", "Sanjay Oraon", "4", " ", "झारखण्ड", "लोहरदगा", "संजय उरांव", " "},
            {"Jharkhand", "Lohardaga", "Raghunath Mahli", "4", " ", "झारखण्ड", "लोहरदगा", "रघुनाथ महली", " "},
            {"Jharkhand", "Lohardaga", "Kalindar Oraon", "4", " ", "झारखण्ड", "लोहरदगा", "कलिंदर उरांव", " "},
            {"Jharkhand", "Palamu", "Ghuran Ram", "2", " ", "झारखण्ड", "पलामू", "घुरन राम", " "},
            {"Jharkhand", "Palamu", "Uday Kumar Paswan", "4", " ", "झारखण्ड", "पलामू", "उदय कुमार पासवान", " "},
            {"Jharkhand", "Palamu", "Satyendra Kumar Paswan", "4", " ", "झारखण्ड", "पलामू", "सत्येंद्र कुमार पासवान", " "},
            {"Jharkhand", "Palamu", "Shravan Kumar Ravi", "4", " ", "झारखण्ड", "पलामू", "श्रवण कुमार रवि", " "},
            {"Jharkhand", "Palamu", "Anjana Bhuiyan", "4", " ", "झारखण्ड", "पलामू", "अंजना भुइयां", " "},
            {"Jharkhand", "Palamu", "Madan Ram", "4", " ", "झारखण्ड", "पलामू", "मदन राम", " "},
            {"Jharkhand", "Palamu", "Baban Bhuiya", "4", " ", "झारखण्ड", "पलामू", "बबन भुइया", " "},
            {"Jharkhand", "Palamu", "Sushma Mehta", "2", " ", "झारखण्ड", "पलामू", "सुषमा मेहता", " "},
            {"Jharkhand", "Palamu", "Vijay Ram", "4", " ", "झारखण्ड", "पलामू", "विजय राम", " "},
            {"Jharkhand", "Palamu", "Dinesh Ram", "2", " ", "झारखण्ड", "पलामू", "दिनेश राम", " "},
            {"Jharkhand", "Palamu", "Balkesh Prasad Paswan", "4", " ", "झारखण्ड", "पलामू", "बालकेश प्रसाद पासवान", " "},
            {"Jharkhand", "Palamu", "Amindra Paswan", "4", " ", "झारखण्ड", "पलामू", "अमिंद्र पासवान", " "},
            {"Jharkhand", "Palamu", "Jorawar Ram", "2", " ", "झारखण्ड", "पलामू", "जोरावर राम", " "},
            {"Jharkhand", "Palamu", "Umesh Kumar Paswan", "4", " ", "झारखण्ड", "पलामू", "उमेश कुमार पासवान", " "},
            {"Jharkhand", "Palamu", "Vishnu Dayal Ram", "1", " ", "झारखण्ड", "पलामू", "विष्णु दयाल राम", " "},
            {"Jharkhand", "Palamu", "Ramji Paswan", "2", " ", "झारखण्ड", "पलामू", "रामजी पासवान", " "},
            {"Jharkhand", "Palamu", "Shyam Narayan Bhuiya", "2", " ", "झारखण्ड", "पलामू", "श्याम नारायण भुईया", " "},
            {"Jharkhand", "Palamu", "Vijay Kumar", "4", " ", "झारखण्ड", "पलामू", "विजय कुमार", " "},
            {"Jharkhand", "Rajmahal", "Mandal Hansda", "3", " ", "झारखण्ड", "राजमहल", "मंडल हांसदा", " "},
            {"Jharkhand", "Rajmahal", "Christopher Murmu", "4", " ", "झारखण्ड", "राजमहल", "क्रिस्टोफर मुर्मू", " "},
            {"Jharkhand", "Rajmahal", "Hemlal Murmu", "1", " ", "झारखण्ड", "राजमहल", "हेमलाल मुर्मू", " "},
            {"Jharkhand", "Rajmahal", "Mahashay Tudu", "4", " ", "झारखण्ड", "राजमहल", "महाशाय टुडू", " "},
            {"Jharkhand", "Rajmahal", "Mangal Marandi", "4", " ", "झारखण्ड", "राजमहल", "मंगल मरांडी", " "},
            {"Jharkhand", "Rajmahal", "Baidhnath Pahadiya", "4", " ", "झारखण्ड", "राजमहल", "बैद्यनाथ पहाड़िया", " "},
            {"Jharkhand", "Rajmahal", "Mary Nisha Hansdak", "4", " ", "झारखण्ड", "राजमहल", "मेरी निशा हंसदक", " "},
            {"Jharkhand", "Rajmahal", "Mahesh Pahadiya", "4", " ", "झारखण्ड", "राजमहल", "महेश पहाड़िया", " "},
            {"Jharkhand", "Rajmahal", "Vijay Kumar Hansdak", "4", " ", "झारखण्ड", "राजमहल", "विजय कुमार हंसदक", " "},
            {"Jharkhand", "Rajmahal", "Mahendra Hansda", "2", " ", "झारखण्ड", "राजमहल", "महेंद्र हांसदा", " "},
            {"Jharkhand", "Ranchi", "Jitendra Thakur", "4", " ", "झारखण्ड", "रांची", "जितेंद्र ठाकुर", " "},
            {"Jharkhand", "Ranchi", "Sidheshwar Singh", "3", " ", "झारखण्ड", "रांची", "सिद्धेश्वर सिंह", " "},
            {"Jharkhand", "Ranchi", "Amar Kumar Mahto", "4", " ", "झारखण्ड", "रांची", "अमर कुमार महतो", " "},
            {"Jharkhand", "Ranchi", "Parmeshwar Mahto", "4", " ", "झारखण्ड", "रांची", "परमेस्वर महतो", " "},
            {"Jharkhand", "Ranchi", "Rajesh Kumar", "4", " ", "झारखण्ड", "रांची", "राजेश कुमार", " "},
            {"Jharkhand", "Ranchi", "Rajesh Thapa", "4", " ", "झारखण्ड", "रांची", "राजेश थापा", " "},
            {"Jharkhand", "Ranchi", "Sanjay Seth", "1", " ", "झारखण्ड", "रांची", "संजय सेठ", " "},
            {"Jharkhand", "Ranchi", "Subodh Kant Sahay", "1", " ", "झारखण्ड", "रांची", "सुबोधकांत सहाय", " "},
            {"Jharkhand", "Ranchi", "Raju Mahto", "2", " ", "झारखण्ड", "रांची", "राजू महतो", " "},
            {"Jharkhand", "Ranchi", "Jay Prakash Prasad", "4", " ", "झारखण्ड", "रांची", "जय प्रकाश प्रसाद", " "},
            {"Jharkhand", "Ranchi", "Ram Tahal. Choudhary", "3", " ", "झारखण्ड", "रांची", "राम टहल। चौधरी", " "},
            {"Jharkhand", "Ranchi", "Nand Kishor Yadav", "4", " ", "झारखण्ड", "रांची", "नंद किशोर यादव", " "},
            {"Jharkhand", "Singhbhum", "Pardeshi Lal Munda", "2", " ", "झारखण्ड", "सिंहभूम", "परदेशी लाल मुंडा", " "},
            {"Jharkhand", "Singhbhum", "Hari Orawn", "2", " ", "झारखण्ड", "सिंहभूम", "हरि ओरवण", " "},
            {"Jharkhand", "Singhbhum", "Laxman Giluwa", "1", " ", "झारखण्ड", "सिंहभूम", "लक्ष्मण गिलुवा", " "},
            {"Jharkhand", "Singhbhum", "Geeta Kora", "1", " ", "झारखण्ड", "सिंहभूम", "गीता कोरा", " "},
    };

}