/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Jharkhand {
    public static final String[][] green_bucket = {
            {"Jharkhand", "Chatra", "Pramod Toppo", "Independent", "1.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10242", "झारखण्ड", "चतरा", "प्रमोद टोप्पो", "निर्दलीय"},
            {"Jharkhand", "Chatra", "Ramanand Das", "Bhartiya Sarvodaya Party", "43.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10244", "झारखण्ड", "चतरा", "रामानंद दास", "भारतीय सर्वोदय पार्टी"},
            {"Jharkhand", "Chatra", "Manoj Kumar Pandey", "Independent", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10234", "झारखण्ड", "चतरा", "मनोज कुमार पांडे", "निर्दलीय"},
            {"Jharkhand", "Chatra", "Nandlal Prasad", "Independent", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10238", "झारखण्ड", "चतरा", "नंदलाल प्रसाद", "निर्दलीय"},
            {"Jharkhand", "Chatra", "Yogendra Yadav", "Independent", "19.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10251", "झारखण्ड", "चतरा", "योगेंद्र यादव", "निर्दलीय"},
            {"Jharkhand", "Chatra", "Rameshi Ram", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10245", "झारखण्ड", "चतरा", "रमेशी राम", "निर्दलीय"},
            {"Jharkhand", "Lohardaga", "Aalone Baxla", "Independent", "27.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10252", "झारखण्ड", "लोहरदगा", "अलोन बक्सला", "निर्दलीय"},
            {"Jharkhand", "Lohardaga", "Ajit Kumar Bhagat", "Independent", "25.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10253", "झारखण्ड", "लोहरदगा", "अजीत कुमार भगत", "निर्दलीय"},
            {"Jharkhand", "Lohardaga", "Ambar Saurav Kunal", "Independent", "20Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10254", "झारखण्ड", "लोहरदगा", "अंबर सौरव कुणाल", "निर्दलीय"},
            {"Jharkhand", "Lohardaga", "Anand Paul Tirkey", "Independent", "26.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10255", "झारखण्ड", "लोहरदगा", "आनंद पॉल तिर्की", "निर्दलीय"},
            {"Jharkhand", "Palamu", "Prayag Ram", "Proutist Sarva Samaj", "2.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10294", "झारखण्ड", "पलामू", "प्रयाग राम", "प्राउटिस्ट सर्व समाज"},
    };

    public static final String[][] red_bucket = {
            {"Jharkhand", "Chatra", "Manoj Kumar Yadav", "1", " ", "झारखण्ड", "चतरा", "मनोज कुमार यादव", " "},
            {"Jharkhand", "Chatra", "Sunil Kumar Singh", "1", " ", "झारखण्ड", "चतरा", "सुनील कुमार सिंह", " "},
            {"Jharkhand", "Chatra", "Pankaj Ranjan", "4", " ", "झारखण्ड", "चतरा", "पंकज रंजन", " "},
            {"Jharkhand", "Chatra", "Rajendra Sahu", "4", " ", "झारखण्ड", "चतरा", "राजेंद्र साहू", " "},
            {"Jharkhand", "Chatra", "Sagar Ram", "4", " ", "झारखण्ड", "चतरा", "सागर राम", " "},
            {"Jharkhand", "Chatra", "Jaidullah Ansari", "3", " ", "झारखण्ड", "चतरा", "जयदुल्ला अंसारी", " "},
            {"Jharkhand", "Chatra", "Bagendra Ram", "4", " ", "झारखण्ड", "चतरा", "बगेन्द्र राम", " "},
            {"Jharkhand", "Chatra", "Ashutosh Kumar", "4", " ", "झारखण्ड", "चतरा", "आशुतोष कुमार", " "},
            {"Jharkhand", "Chatra", "Arjun Kumar", "2", " ", "झारखण्ड", "चतरा", "अर्जुन कुमार", " "},
            {"Jharkhand", "Chatra", "Abdul Rajak Ansari", "2", " ", "झारखण्ड", "चतरा", "अब्दुल रजक अंसारी", " "},
            {"Jharkhand", "Chatra", "Ayub Kha", "4", " ", "झारखण्ड", "चतरा", "अयूब खा", " "},
            {"Jharkhand", "Chatra", "Duleshwar Saw", "4", " ", "झारखण्ड", "चतरा", "दुलेश्वर साव", " "},
            {"Jharkhand", "Chatra", "Nageshwar Ganjhu", "4", " ", "झारखण्ड", "चतरा", "नागेश्वर गंझू", " "},
            {"Jharkhand", "Chatra", "Shaukat Ali", "4", " ", "झारखण्ड", "चतरा", "शौकत अली", " "},
            {"Jharkhand", "Chatra", "Bhagalpuri Yadav", "4", " ", "झारखण्ड", "चतरा", "भागलपुरी यादव", " "},
            {"Jharkhand", "Chatra", "Dhananjay Kumar", "4", " ", "झारखण्ड", "चतरा", "धनंजय कुमार", " "},
            {"Jharkhand", "Chatra", "Arun Kumar Yadav", "2", " ", "झारखण्ड", "चतरा", "अरुण कुमार यादव", " "},
            {"Jharkhand", "Chatra", "Subhash Prasad Yadav", "2", " ", "झारखण्ड", "चतरा", "सुभाष प्रसाद यादव", " "},
            {"Jharkhand", "Chatra", "Nand Lal Prasad Keshari", "4", " ", "झारखण्ड", "चतरा", "नंद लाल प्रसाद केशरी", " "},
            {"Jharkhand", "Lohardaga", "Saniya Oraon", "2", " ", "झारखण्ड", "लोहरदगा", "सानीया उरांव", " "},
            {"Jharkhand", "Lohardaga", "Sukhdeo Bhagat", "1", " ", "झारखण्ड", "लोहरदगा", "सुखदेव भगत", " "},
            {"Jharkhand", "Lohardaga", "Sharvan Kumar Panna", "4", " ", "झारखण्ड", "लोहरदगा", "शरवन कुमार पन्ना", " "},
            {"Jharkhand", "Lohardaga", "Dinesh Oraon", "4", " ", "झारखण्ड", "लोहरदगा", "दिनेश उरांव", " "},
            {"Jharkhand", "Lohardaga", "Deo Kumar Dhan", "2", " ", "झारखण्ड", "लोहरदगा", "देव कुमार धन", " "},
            {"Jharkhand", "Lohardaga", "Ekus Dhan", "3", " ", "झारखण्ड", "लोहरदगा", "एकस धन", " "},
            {"Jharkhand", "Lohardaga", "Sudarshan Bhagat", "1", " ", "झारखण्ड", "लोहरदगा", "सुदर्शन भगत", " "},
            {"Jharkhand", "Lohardaga", "Sanjay Oraon", "4", " ", "झारखण्ड", "लोहरदगा", "संजय उरांव", " "},
            {"Jharkhand", "Lohardaga", "Raghunath Mahli", "4", " ", "झारखण्ड", "लोहरदगा", "रघुनाथ महली", " "},
            {"Jharkhand", "Lohardaga", "Kalindar Oraon", "4", " ", "झारखण्ड", "लोहरदगा", "कलिंदर उरांव", " "},
            {"Jharkhand", "Palamu", "Ghuran Ram", "2", " ", "झारखण्ड", "पलामू", "घुरन राम", " "},
            {"Jharkhand", "Palamu", "Uday Kumar Paswan", "4", " ", "झारखण्ड", "पलामू", "उदय कुमार पासवान", " "},
            {"Jharkhand", "Palamu", "Satyendra Kumar Paswan", "4", " ", "झारखण्ड", "पलामू", "सत्येंद्र कुमार पासवान", " "},
            {"Jharkhand", "Palamu", "Shravan Kumar Ravi", "4", " ", "झारखण्ड", "पलामू", "श्रवण कुमार रवि", " "},
            {"Jharkhand", "Palamu", "Anjana Bhuiyan", "4", " ", "झारखण्ड", "पलामू", "अंजना भुइयां", " "},
            {"Jharkhand", "Palamu", "Madan Ram", "4", " ", "झारखण्ड", "पलामू", "मदन राम", " "},
            {"Jharkhand", "Palamu", "Baban Bhuiya", "4", " ", "झारखण्ड", "पलामू", "बबन भुइया", " "},
            {"Jharkhand", "Palamu", "Sushma Mehta", "2", " ", "झारखण्ड", "पलामू", "सुषमा मेहता", " "},
            {"Jharkhand", "Palamu", "Vijay Ram", "4", " ", "झारखण्ड", "पलामू", "विजय राम", " "},
            {"Jharkhand", "Palamu", "Dinesh Ram", "2", " ", "झारखण्ड", "पलामू", "दिनेश राम", " "},
            {"Jharkhand", "Palamu", "Balkesh Prasad Paswan", "4", " ", "झारखण्ड", "पलामू", "बालकेश प्रसाद पासवान", " "},
            {"Jharkhand", "Palamu", "Amindra Paswan", "4", " ", "झारखण्ड", "पलामू", "अमिंद्र पासवान", " "},
            {"Jharkhand", "Palamu", "Jorawar Ram", "2", " ", "झारखण्ड", "पलामू", "जोरावर राम", " "},
            {"Jharkhand", "Palamu", "Umesh Kumar Paswan", "4", " ", "झारखण्ड", "पलामू", "उमेश कुमार पासवान", " "},
            {"Jharkhand", "Palamu", "Vishnu Dayal Ram", "1", " ", "झारखण्ड", "पलामू", "विष्णु दयाल राम", " "},
            {"Jharkhand", "Palamu", "Ramji Paswan", "2", " ", "झारखण्ड", "पलामू", "रामजी पासवान", " "},
            {"Jharkhand", "Palamu", "Shyam Narayan Bhuiya", "2", " ", "झारखण्ड", "पलामू", "श्याम नारायण भुईया", " "},
            {"Jharkhand", "Palamu", "Vijay Kumar", "4", " ", "झारखण्ड", "पलामू", "विजय कुमार", " "},
    };

}