/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Karnataka {
public static final String[][] green_bucket = {
        {"Karnataka", "Bagalkot", "Mahmad Husen Mujawar", "Bahujan Samaj Party", "50000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10491", "कर्नाटक", "बागलकोट", "महमद हुसैन मुजावर", "बहुजन समाज पार्टी"},
        {"Karnataka", "Bagalkot", "Jamindar Maruti", "Karnataka Jantha Paksha", "25Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10493", "कर्नाटक", "बागलकोट", "जमींदार मारुति", "कर्नाटक जंथा पक्ष"},
        {"Karnataka", "Bagalkot", "Ramanagoud S Balawad", "Hindustan Janta Party", "2.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7026", "कर्नाटक", "बागलकोट", "रमनगौड एस बालावाद", "हिंदुस्तान जनता पार्टी"},
        {"Karnataka", "Bagalkot", "Shivarajkumar Ajjappa Talawar", "Independent", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10498", "कर्नाटक", "बागलकोट", "शिवराजकुमार अजप्पा तलावर", "निर्दलीय"},
        {"Karnataka", "Bagalkot", "Pendari Buddesab Makabulsab", "Independent", "5.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10496", "कर्नाटक", "बागलकोट", "पेंडारी बुदेसब मकबुलसब", "निर्दलीय"},
        {"Karnataka", "Bangalore Central", "Srinivasan R", "Indian Christian Front", "7.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7382", "कर्नाटक", "बैंगलोर सेंट्रल", "श्रीनिवासन आर", "भारतीय ईसाई मोर्चा"},
        {"Karnataka", "Bangalore Central", "Kempurajan", "Republican Sena", "41000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7380", "कर्नाटक", "बैंगलोर सेंट्रल", "Kempurajan", "रिपब्लिकन सेना"},
        {"Karnataka", "Bangalore Central", "Francis Binny Jose", "Independent", "6.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7374", "कर्नाटक", "बैंगलोर सेंट्रल", "फ्रांसिस बिन्नी जोस", "निर्दलीय"},
        {"Karnataka", "Bangalore Central", "Pradeep Mendonca", "Independent", "58.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7291", "कर्नाटक", "बैंगलोर सेंट्रल", "प्रदीप मेंडोंका", "निर्दलीय"},
        {"Karnataka", "Bangalore Central", "M.K. Pasha", "Bahujan Samaj Party", "31000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7287", "कर्नाटक", "बैंगलोर सेंट्रल", "एमके पाशा", "बहुजन समाज पार्टी"},
        {"Karnataka", "Bangalore Central", "Syed Asif Bukhari", "Independent", "3.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7292", "कर्नाटक", "बैंगलोर सेंट्रल", "सैयद आसिफ बुखारी", "निर्दलीय"},
        {"Karnataka", "Bangalore Central", "Raparti Anil Kumar", "Independent", "12.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7372", "कर्नाटक", "बैंगलोर सेंट्रल", "राप्ती अनिल कुमार", "निर्दलीय"},
        {"Karnataka", "Bangalore Central", "Mellegatti Shridevi", "Uttama Prajaakeeya Party", "16.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7286", "कर्नाटक", "बैंगलोर सेंट्रल", "मेलिगेट्टी श्रीदेवी", "उत्तम प्रजाकेय पार्टी"},
        {"Karnataka", "Bangalore Central", "Hunsur K. Chandrashekar", "Democratic Prajakranthi Party Secularist", "63.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7381", "कर्नाटक", "बैंगलोर सेंट्रल", "हुंसुर के। चंद्रशेखर", "डेमोक्रेटिक प्रजाक्रांति पार्टी सेकुलरवादी"},
        {"Karnataka", "Bangalore Central", "Jenifar J. Russell", "Independent", "51.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7305", "कर्नाटक", "बैंगलोर सेंट्रल", "जेनिफर जे। रसेल", "निर्दलीय"},
        {"Karnataka", "Bangalore Central", "S. Mohan Kumar", "Independent", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7294", "कर्नाटक", "बैंगलोर सेंट्रल", "एस। मोहन कुमार", "निर्दलीय"},
        {"Karnataka", "Bangalore North", "Vinay Kumar V.Nayak", "Independent", "1.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7349", "कर्नाटक", "बैंगलोर उत्तर", "विनय कुमार वी। नायक", "निर्दलीय"},
        {"Karnataka", "Bangalore North", "Syed Hydri Babloo", "Bahujan Samaj Party", "2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7344", "कर्नाटक", "बैंगलोर उत्तर", "सैयद हैदरी बबलू", "बहुजन समाज पार्टी"},
        {"Karnataka", "Bangalore North", "Umesh Babu Pillegowda", "Independent", "8.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7340", "कर्नाटक", "बैंगलोर उत्तर", "उमेश बाबू पिल्लगौड़ा", "निर्दलीय"},
        {"Karnataka", "Bangalore North", "Prasanna Kumar Iyengar", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7351", "कर्नाटक", "बैंगलोर उत्तर", "प्रसन्ना कुमार अयंगर", "निर्दलीय"},
        {"Karnataka", "Bangalore North", "Parameshwar Gowda", "Independent", "3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7354", "कर्नाटक", "बैंगलोर उत्तर", "परमेश्वर गौड़ा", "निर्दलीय"},
        {"Karnataka", "Bangalore North", "Dr. Meer Layaq Hussain", "Independent", "20000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7342", "कर्नाटक", "बैंगलोर उत्तर", "डॉ। मीर लयाक हुसैन", "निर्दलीय"},
        {"Karnataka", "Bangalore North", "Shiva Manjesh K.S.", "Independent", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7337", "कर्नाटक", "बैंगलोर उत्तर", "शिव मंजेश के.एस.", "निर्दलीय"},
        {"Karnataka", "Bangalore North", "Sumatha K.S.", "Independent", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7366", "कर्नाटक", "बैंगलोर उत्तर", "सुमाथा के.एस.", "निर्दलीय"},
        {"Karnataka", "Bangalore North", "Tulasappa K Dasar", "Independent", "30.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7347", "कर्नाटक", "बैंगलोर उत्तर", "तुलसप्पा के दसर", "निर्दलीय"},
        {"Karnataka", "Bangalore North", "Krishna Murthy V .", "Right to Recall Party", "61.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7360", "कर्नाटक", "बैंगलोर उत्तर", "कृष्ण मूर्ति वी।", "राइट टू रिकॉल पार्टी"},
        {"Karnataka", "Bangalore North", "Abdul Karim Hashimpeer Desai", "Independent", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7346", "कर्नाटक", "बैंगलोर उत्तर", "अब्दुल करीम हाशिमपीर देसाई", "निर्दलीय"},
        {"Karnataka", "Bangalore Rural", "Dr Chinnappa Y Chikkahagade", "Bahujan Samaj Party", "88.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7322", "कर्नाटक", "बैंगलोर ग्रामीण", "डॉ। चिन्नाप्पा वाई चिक्काहागड़े", "बहुजन समाज पार्टी"},
        {"Karnataka", "Bangalore Rural", "Dr. M Venkataswamy", "Republican Party of India (Athawale)", "6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7325", "कर्नाटक", "बैंगलोर ग्रामीण", "डॉ। एम वेंकटस्वामी", "भारतीय रिपब्लिकन पार्टी (अठावले)"},
        {"Karnataka", "Bangalore Rural", "Rama T C", "Socialist Unity Centre of India (Communist)", "3.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5159", "कर्नाटक", "बैंगलोर ग्रामीण", "रमा टीसी", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Karnataka", "Bangalore Rural", "Raghu Janagere", "Independent", "68.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7318", "कर्नाटक", "बैंगलोर ग्रामीण", "रघु जनगेरे", "निर्दलीय"},
        {"Karnataka", "Bangalore South", "Manohar Iyer", "Independent", "12Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7689", "कर्नाटक", "बैंगलोर दक्षिण", "मनोहर अय्यर", "निर्दलीय"},
        {"Karnataka", "Bangalore South", "Dr. Banuprakash A.S", "Pyramid Party of India", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5164", "कर्नाटक", "बैंगलोर दक्षिण", "डॉ। बानूप्रकाश ए.एस.", "पिरामिड पार्टी ऑफ इंडिया"},
        {"Karnataka", "Bangalore South", "B.Sreenivasulu", "Independent", "20.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7695", "कर्नाटक", "बैंगलोर दक्षिण", "B.Sreenivasulu", "निर्दलीय"},
        {"Karnataka", "Bangalore South", "A.Raju", "Bahujan Samaj Party", "5.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7682", "कर्नाटक", "बैंगलोर दक्षिण", "A.Raju", "बहुजन समाज पार्टी"},
        {"Karnataka", "Bangalore South", "Ravikumara.T", "Pragatishil Samajwadi Party (Lohia)", "13.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7677", "कर्नाटक", "बैंगलोर दक्षिण", "Ravikumara.T", "प्रगति समाजवादी पार्टी (लोहिया)"},
        {"Karnataka", "Bangalore South", "Ambrose D Mello", "Independent", "70000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5161", "कर्नाटक", "बैंगलोर दक्षिण", "एम्ब्रोस डी मेलो", "निर्दलीय"},
        {"Karnataka", "Bangalore South", "Chetan Chaman", "Independent", "14.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7705", "कर्नाटक", "बैंगलोर दक्षिण", "चेतन चमन", "निर्दलीय"},
        {"Karnataka", "Bangalore South", "K.C.Nagabhushana Reddy", "Independent", "16Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5166", "कर्नाटक", "बैंगलोर दक्षिण", "केसी नागभूषण रेड्डी", "निर्दलीय"},
        {"Karnataka", "Bangalore South", "Prashantha.C", "Independent", "1.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7681", "कर्नाटक", "बैंगलोर दक्षिण", "Prashantha.C", "निर्दलीय"},
        {"Karnataka", "Belgaum", "Uday Naik", "Independent", "4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10479", "कर्नाटक", "बेलगाम", "उदय नाइक", "निर्दलीय"},
        {"Karnataka", "Belgaum", "Shankar Chogule", "Independent", "35.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10587", "कर्नाटक", "बेलगाम", "शंकर चौगुले", "निर्दलीय"},
        {"Karnataka", "Belgaum", "Suresh Basappa Maralingannavar", "Independent", "15.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10591", "कर्नाटक", "बेलगाम", "सुरेश बसप्पा मरलिंगनवर", "निर्दलीय"},
        {"Karnataka", "Belgaum", "Sandeep Vasant Lad", "Independent", "2.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10585", "कर्नाटक", "बेलगाम", "संदीप वसंत लाड", "निर्दलीय"},
        {"Karnataka", "Belgaum", "Badaroddin Mohammadyusuf Kamdod", "Bahujan Samaj Party", "1.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10490", "कर्नाटक", "बेलगाम", "बद्रोद्दीन मोहम्मदिसुफ़ कामदोद", "बहुजन समाज पार्टी"},
        {"Karnataka", "Belgaum", "Manjunath Rajappanavar", "Uttama Prajaakeeya Party", "22.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7024", "कर्नाटक", "बेलगाम", "मंजूनाथ राजप्पनवर", "उत्तम प्रजाकेय पार्टी"},
        {"Karnataka", "Belgaum", "Vijay Laxman Patil", "Independent", "67.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9121", "कर्नाटक", "बेलगाम", "विजय लक्ष्मण पाटिल", "निर्दलीय"},
        {"Karnataka", "Belgaum", "Vijay Krishna Madar", "Independent", "3.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10488", "कर्नाटक", "बेलगाम", "विजय कृष्ण मदार", "निर्दलीय"},
        {"Karnataka", "Belgaum", "Chetak Kumar Yallappa Kamble", "Independent", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10476", "कर्नाटक", "बेलगाम", "चेतक कुमार यलप्पा कांबले", "निर्दलीय"},
        {"Karnataka", "Belgaum", "Niteen Dhondiba Anandache", "Independent", "5.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10577", "कर्नाटक", "बेलगाम", "नितेन धोंडिबा आनंदके", "निर्दलीय"},
        {"Karnataka", "Belgaum", "Suresh Khemanna Rajukar", "Independent", "4.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10592", "कर्नाटक", "बेलगाम", "सुरेश खेमना राजुकर", "निर्दलीय"},
        {"Karnataka", "Belgaum", "Sunil Guddakayu", "Independent", "74.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10590", "कर्नाटक", "बेलगाम", "सुनील गुड्डाकायु", "निर्दलीय"},
        {"Karnataka", "Belgaum", "Uday Ramappa Kundargi", "Independent", "3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10470", "कर्नाटक", "बेलगाम", "उदय रामप्पा कुंदरगी", "निर्दलीय"},
        {"Karnataka", "Belgaum", "Anand Ramesh Patil", "Independent", "8.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10489", "कर्नाटक", "बेलगाम", "आनंद रमेश पाटिल", "निर्दलीय"},
        {"Karnataka", "Bellary", "Nayakara Ramappa", "Indian Labour Party (Ambedkar Phule)", "9.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10450", "कर्नाटक", "बेल्लारी", "नायकरा रामप्पा", "भारतीय मजदूर पार्टी (अम्बेडकर फुले)"},
        {"Karnataka", "Bellary", "Naveen Kumar. S", "Bharat Prabhat Party", "8.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10449", "कर्नाटक", "बेल्लारी", "नवीन कुमार। एस", "भारत प्रभात पार्टी"},
        {"Karnataka", "Bidar", "Rajkumar", "Purvanchal Janta Party (Secular)", "11.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10461", "कर्नाटक", "बीदर", "राजकुमार", "पूर्वांचल जनता पार्टी (सेक्युलर)"},
        {"Karnataka", "Bidar", "Maulappa", "Independent", "28.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7261", "कर्नाटक", "बीदर", "Maulappa", "निर्दलीय"},
        {"Karnataka", "Bidar", "Shaik Abdul Gaffar", "Independent", "3.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10468", "कर्नाटक", "बीदर", "शैक अब्दुल गफ्फार", "निर्दलीय"},
        {"Karnataka", "Bidar", "Ambresh Kencha", "Uttama Prajaakeeya Party", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7038", "कर्नाटक", "बीदर", "अंबरीश केंचा", "उत्तम प्रजाकेय पार्टी"},
        {"Karnataka", "Bidar", "Saibanna", "Independent", "7.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7260", "कर्नाटक", "बीदर", "Saibanna", "निर्दलीय"},
        {"Karnataka", "Bidar", "Maulasab", "Independent", "15.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10464", "कर्नाटक", "बीदर", "Maulasab", "निर्दलीय"},
        {"Karnataka", "Bidar", "Ravi", "Independent", "83.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7256", "कर्नाटक", "बीदर", "रवि", "निर्दलीय"},
        {"Karnataka", "Bijapur", "Dhareppa Mahadev Ardhavar", "Independent", "32.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10443", "कर्नाटक", "बीजापुर", "ध्रप्पा महादेव अर्धवर", "निर्दलीय"},
        {"Karnataka", "Bijapur", "Dr. Sunita Devanand Chavan", "Janata Dal (Secular)", "4.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10439", "कर्नाटक", "बीजापुर", "डॉ। सुनीता देवानंद चव्हाण", "जनता दल (सेक्युलर)"},
        {"Karnataka", "Bijapur", "Shrivenkateshwar Maha Swamiji", "Hindustan Janta Party", "9", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7029", "कर्नाटक", "बीजापुर", "श्रीवेंकटेश्वर महा स्वामीजी", "हिंदुस्तान जनता पार्टी"},
        {"Karnataka", "Bijapur", "Rudrappa Deyappa Chalawadi", "Bharipa Bahujan Mahasangh", "41.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10441", "कर्नाटक", "बीजापुर", "रुद्रप्पा दयप्पा चलवाडी", "भारिप बहुजन महासंघ"},
        {"Karnataka", "Chamarajanagar", "Hanur Nagaraju", "Uttama Prajaakeeya Party", "5.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7308", "कर्नाटक", "चामराजनगर", "हनूर नागराजू", "उत्तम प्रजाकेय पार्टी"},
        {"Karnataka", "Chamarajanagar", "Dr Shivakumara", "Bahujan Samaj Party", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7311", "कर्नाटक", "चामराजनगर", "डॉ। शिवकुमार", "बहुजन समाज पार्टी"},
        {"Karnataka", "Chamarajanagar", "Prasanna Kumar B", "Karnataka Praja Party (RaithaParva)", "15.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7317", "कर्नाटक", "चामराजनगर", "प्रसन्न कुमार बी", "कर्नाटक प्रजा पार्टी (रायपर्व)"},
        {"Karnataka", "Chikkballapur", "Nagendra Rao Shinde", "Karnataka Jantha Paksha", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7672", "कर्नाटक", "चिकबल्लपुर", "नागेंद्र राव शिंदे", "कर्नाटक जंथा पक्ष"},
        {"Karnataka", "Chikkballapur", "Abdulkarim Desai", "Independent", "86Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7673", "कर्नाटक", "चिकबल्लपुर", "अब्दुलकरिम देसाई", "निर्दलीय"},
        {"Karnataka", "Chikkodi", "Mohan Gurappa Motannavar", "Independent", "13.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10427", "कर्नाटक", "चिक्कोडी", "मोहन गुरप्पा मोटन्नवर", "निर्दलीय"},
        {"Karnataka", "Chikkodi", "Praveenkumar Baligatti", "Uttama Prajaakeeya Party", "32000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7021", "कर्नाटक", "चिक्कोडी", "प्रवीणकुमार बालीगट्टी", "उत्तम प्रजाकेय पार्टी"},
        {"Karnataka", "Chitradurga", "Niranjana A D Cheelangi", "Ambedkar Samaj Party", "4.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7101", "कर्नाटक", "चित्रदुर्ग", "निरंजना ई। चेलांगी", "अंबेडकर समाज पार्टी"},
        {"Karnataka", "Chitradurga", "D Pennappa Turuvanur", "Independent", "5.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7881", "कर्नाटक", "चित्रदुर्ग", "डी पेनप्पा तुरुवनुर", "निर्दलीय"},
        {"Karnataka", "Chitradurga", "Ramesha V", "Independent", "24.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7880", "कर्नाटक", "चित्रदुर्ग", "रमेश वी", "निर्दलीय"},
        {"Karnataka", "Chitradurga", "V S Bhutharaja", "Independent", "7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7878", "कर्नाटक", "चित्रदुर्ग", "वीएस भूथराजा", "निर्दलीय"},
        {"Karnataka", "Chitradurga", "Lokesha M K", "Independent", "3.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7882", "कर्नाटक", "चित्रदुर्ग", "लोकेश एमके", "निर्दलीय"},
        {"Karnataka", "Chitradurga", "S Meetyanaik", "Pragatishil Samajwadi Party (Lohia)", "24.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7096", "कर्नाटक", "चित्रदुर्ग", "एस मलयानिक", "प्रगति समाजवादी पार्टी (लोहिया)"},
        {"Karnataka", "Chitradurga", "Arunachalam Y", "Pyramid Party of India", "16Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5128", "कर्नाटक", "चित्रदुर्ग", "अरुणाचलम वाई", "पिरामिड पार्टी ऑफ इंडिया"},
        {"Karnataka", "Dakshina Kannada", "Venkatesh Bende", "Independent", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7918", "कर्नाटक", "दक्षिण कन्नड़", "वेंकटेश बेंद", "निर्दलीय"},
        {"Karnataka", "Davanagere", "Subhan Khan", "Independent", "10.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7272", "कर्नाटक", "दावनगेरे", "सुभान खान", "निर्दलीय"},
        {"Karnataka", "Davanagere", "Mohamed Hayath", "Independent", "3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10423", "कर्नाटक", "दावनगेरे", "मोहम्मद हयात", "निर्दलीय"},
        {"Karnataka", "Davanagere", "Madhu T G", "Socialist Unity Centre of India (Communist)", "32.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7053", "कर्नाटक", "दावनगेरे", "मधु टीजी", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Karnataka", "Davanagere", "Shashikumar R N", "Independent", "21.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10426", "कर्नाटक", "दावनगेरे", "शशिकुमार आर.एन.", "निर्दलीय"},
        {"Karnataka", "Davanagere", "V Manjunathachar", "Independent", "6.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7052", "कर्नाटक", "दावनगेरे", "वी मंजूनाथचर", "निर्दलीय"},
        {"Karnataka", "Dharwad", "Gangadhar Badiger", "Socialist Unity Centre of India (Communist)", "95105", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7044", "कर्नाटक", "धारवाड़", "गंगाधर बडिगर", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Karnataka", "Dharwad", "Santosh Nandur", "Uttama Prajaakeeya Party", "22.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7046", "कर्नाटक", "धारवाड़", "संतोष नंदूर", "उत्तम प्रजाकेय पार्टी"},
        {"Karnataka", "Dharwad", "Raju Harishchandra Kamble", "Azad Mazdoor Kissan Party", "79835", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10411", "कर्नाटक", "धारवाड़", "राजू हरिश्चंद्र कांबले", "आजाद मजदूर किसन पार्टी"},
        {"Karnataka", "Dharwad", "B. G. Sangannavar", "Independent", "22.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10414", "कर्नाटक", "धारवाड़", "बीजी सांगनावार", "निर्दलीय"},
        {"Karnataka", "Dharwad", "Makhtum Khan Hasanalikhan Sirdesai", "Independent", "6.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10415", "कर्नाटक", "धारवाड़", "मखमत खान हसनलीखान सिरदेसाई", "निर्दलीय"},
        {"Karnataka", "Gulbarga", "Mahesh Lambani", "Uttama Prajaakeeya Party", "38000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7032", "कर्नाटक", "गुलबर्गा", "महेश लाम्बानी", "उत्तम प्रजाकेय पार्टी"},
        {"Karnataka", "Gulbarga", "D. K. Konkate Keroor", "Rashtriya Samaj Paksha", "11.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7252", "कर्नाटक", "गुलबर्गा", "डीके कोंकते करूर", "राष्ट्रीय समाज पक्ष"},
        {"Karnataka", "Gulbarga", "Dr. M. P. Darakeshwaraiah", "Independent", "31.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10405", "कर्नाटक", "गुलबर्गा", "डॉ। एमपी दरकेश्वरैया", "निर्दलीय"},
        {"Karnataka", "Hassan", "Prajwal R", "Janata Dal (Secular)", "9.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4959", "कर्नाटक", "हसन", "प्रज्वल आर", "जनता दल (सेक्युलर)"},
        {"Karnataka", "Haveri", "Shylesh Nazare Ashok", "Indian Labour Party (Ambedkar Phule)", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10395", "कर्नाटक", "हावेरी", "शैलेश नज़रे अशोक", "भारतीय मजदूर पार्टी (अम्बेडकर फुले)"},
        {"Karnataka", "Haveri", "Ayubakhan A Pathan", "Bahujan Samaj Party", "65.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10392", "कर्नाटक", "हावेरी", "अयूबखान ए पठान", "बहुजन समाज पार्टी"},
        {"Karnataka", "Kolar", "Ramanji. R", "Uttama Prajaakeeya Party", "86500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7280", "कर्नाटक", "कोलार", "Ramanji। आर", "उत्तम प्रजाकेय पार्टी"},
        {"Karnataka", "Kolar", "Dr. Ramesh Babu. V.M.", "Independent", "14.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8870", "कर्नाटक", "कोलार", "डॉ। रमेश बाबू वीएम", "निर्दलीय"},
        {"Karnataka", "Kolar", "Raj Kumaresan. L", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8871", "कर्नाटक", "कोलार", "राज कुमारसन। एल", "निर्दलीय"},
        {"Karnataka", "Kolar", "Jayaprasad M.G", "Bahujan Samaj Party", "4.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7296", "कर्नाटक", "कोलार", "जयप्रसाद एम.जी.", "बहुजन समाज पार्टी"},
        {"Karnataka", "Kolar", "G. Chikkanarayana", "Republican Sena", "9.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7297", "कर्नाटक", "कोलार", "जी। चिकनकारायण", "रिपब्लिकन सेना"},
        {"Karnataka", "Kolar", "N.C. Subbarayappa", "Independent", "6.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7281", "कर्नाटक", "कोलार", "NC सुब्बारायप्पा", "निर्दलीय"},
        {"Karnataka", "Koppal", "Satishreddy", "Independent", "82000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10390", "कर्नाटक", "कोप्पल", "Satishreddy", "निर्दलीय"},
        {"Karnataka", "Koppal", "Suresh.H", "Independent", "1.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10391", "कर्नाटक", "कोप्पल", "Suresh.H", "निर्दलीय"},
        {"Karnataka", "Koppal", "Pa.Ya. Ganesh", "Independent", "19Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10386", "कर्नाटक", "कोप्पल", "पाया। गणेश", "निर्दलीय"},
        {"Karnataka", "Koppal", "Hemaraj Veerapur", "Communist Party of India (Marxist–Leninist) Red Star", "50000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10385", "कर्नाटक", "कोप्पल", "हेमराज वीरपुर", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) रेड स्टार"},
        {"Karnataka", "Mandya", "Santhosh Mandya Gowda", "Engineers Party", "7.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7756", "कर्नाटक", "मंड्या", "संतोष मंड्या गौड़ा", "इंजीनियर्स पार्टी"},
        {"Karnataka", "Mandya", "Lingegowda S H", "Independent", "80.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7746", "कर्नाटक", "मंड्या", "लिंगेगौड़ा एस.एच.", "निर्दलीय"},
        {"Karnataka", "Mandya", "Nanjundaswamy", "Bahujan Samaj Party", "85Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7757", "कर्नाटक", "मंड्या", "Nanjundaswamy", "बहुजन समाज पार्टी"},
        {"Karnataka", "Mandya", "Arvind Premanand", "Independent", "81Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7755", "कर्नाटक", "मंड्या", "अरविंद प्रेमानंद", "निर्दलीय"},
        {"Karnataka", "Mandya", "Sumalatha W/O Darshan K.", "Independent", "28.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8673", "कर्नाटक", "मंड्या", "सुमलता डब्ल्यू / ओ दर्शन के।", "निर्दलीय"},
        {"Karnataka", "Mandya", "Nikhil Kumaraswamy", "Janata Dal (Secular)", "74Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7749", "कर्नाटक", "मंड्या", "निखिल कुमारस्वामी", "जनता दल (सेक्युलर)"},
        {"Karnataka", "Mandya", "T.K. Dasar", "Independent", "30.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7759", "कर्नाटक", "मंड्या", "टीके दसर", "निर्दलीय"},
        {"Karnataka", "Mandya", "Premakumara .V.V", "Independent", "1.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7744", "कर्नाटक", "मंड्या", "प्रेमकुमार .VV", "निर्दलीय"},
        {"Karnataka", "Mysore", "K.S.Somasunder", "Independent", "6.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7718", "कर्नाटक", "मैसूर", "KSSomasunder", "निर्दलीय"},
        {"Karnataka", "Mysore", "Alishan. S", "Independent", "2.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7739", "कर्नाटक", "मैसूर", "Alishan। एस", "निर्दलीय"},
        {"Karnataka", "Mysore", "Alagudu Lingaraju", "Independent", "11.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7713", "कर्नाटक", "मैसूर", "अलागुडु लिंगराजु", "निर्दलीय"},
        {"Karnataka", "Mysore", "Sandhya P S", "Socialist Unity Centre of India (Communist)", "24.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5143", "कर्नाटक", "मैसूर", "संध्या पीएस", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Karnataka", "Mysore", "M J Suresh Gowda", "Independent", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5148", "कर्नाटक", "मैसूर", "एमजे सुरेश गौड़ा", "निर्दलीय"},
        {"Karnataka", "Raichur", "Niranjan Nayak", "Uttama Prajaakeeya Party", "13000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10379", "कर्नाटक", "रायचूर", "निरंजन नायक", "उत्तम प्रजाकेय पार्टी"},
        {"Karnataka", "Raichur", "B. Venkana Gouda Nayaka", "Bahujan Samaj Party", "17.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10378", "कर्नाटक", "रायचूर", "बी। वेंकणा गौड़ा नायक", "बहुजन समाज पार्टी"},
        {"Karnataka", "Shimoga", "K.C.Vinay Rajavath", "Independent", "18.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10377", "कर्नाटक", "शिमोगा", "केसीविनय राजावत", "निर्दलीय"},
        {"Karnataka", "Shimoga", "Shekara Naik", "Independent", "4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7054", "कर्नाटक", "शिमोगा", "शेखर नाइक", "निर्दलीय"},
        {"Karnataka", "Tumkur", "Kapanigowda", "Independent", "13.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5133", "कर्नाटक", "तुमकुर", "Kapanigowda", "निर्दलीय"},
        {"Karnataka", "Tumkur", "Chaya Rajashankar", "Uttama Prajaakeeya Party", "3.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5131", "कर्नाटक", "तुमकुर", "चाया राजशंकर", "उत्तम प्रजाकेय पार्टी"},
        {"Karnataka", "Tumkur", "Siddaramegowda T. B.", "Independent", "63Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7828", "कर्नाटक", "तुमकुर", "सिद्धारमेगौड़ा टी.बी.", "निर्दलीय"},
        {"Karnataka", "Tumkur", "K. C. Hanumantharaya", "Bahujan Samaj Party", "3.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7812", "कर्नाटक", "तुमकुर", "केसी हनुमंतराय", "बहुजन समाज पार्टी"},
        {"Karnataka", "Tumkur", "K V Srinivas Kalkere", "Independent", "3.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5135", "कर्नाटक", "तुमकुर", "केवी श्रीनिवास कालकेरे", "निर्दलीय"},
        {"Karnataka", "Tumkur", "Mahalakshmi C. P.", "Ambedkar Samaj Party", "20000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7827", "कर्नाटक", "तुमकुर", "महालक्ष्मी सी.पी.", "अंबेडकर समाज पार्टी"},
        {"Karnataka", "Tumkur", "Prakash. R. A. Jain", "Independent", "4.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7813", "कर्नाटक", "तुमकुर", "प्रकाश। रा जैन", "निर्दलीय"},
        {"Karnataka", "Uttara Kannada", "Sunil Pawar", "Uttama Prajaakeeya Party", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7270", "कर्नाटक", "उत्तर कन्नड़", "सुनील पवार", "उत्तम प्रजाकेय पार्टी"},
        {"Karnataka", "Uttara Kannada", "Balakrishna Arjun Patil", "Independent", "22Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7047", "कर्नाटक", "उत्तर कन्नड़", "बालकृष्ण अर्जुन पाटिल", "निर्दलीय"},
        {"Karnataka", "Uttara Kannada", "Kundabai Ganapati Parulekar", "Independent", "91.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10370", "कर्नाटक", "उत्तर कन्नड़", "कुंदाबाई गणपति पारुलेकर", "निर्दलीय"},
        {"Karnataka", "Uttara Kannada", "Manjunath Sadashiv", "Bharat Bhoomi Party", "8.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10369", "कर्नाटक", "उत्तर कन्नड़", "मंजूनाथ सदाशिव", "भारतभूमि पार्टी"},
        {"Karnataka", "Uttara Kannada", "Sudhakar Kira Jogalekar", "Bahujan Samaj Party", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10366", "कर्नाटक", "उत्तर कन्नड़", "सुधाकर किर जोगलेकर", "बहुजन समाज पार्टी"},
};

public static final String[][] red_bucket = {
        {"Karnataka", "Bagalkot", "Basanagouda Ramanagouda Meti", "4", " ", "कर्नाटक", "बागलकोट", "बसनगौड़ा रामानुगौदा मेटी", " "},
        {"Karnataka", "Bagalkot", "M Shashikumar Hlepadi", "4", " ", "कर्नाटक", "बागलकोट", "एम शशिकुमार हेलेपाडी", " "},
        {"Karnataka", "Bagalkot", "Gaddigoudar Parvatagouda Chandanagouda", "1", " ", "कर्नाटक", "बागलकोट", "गद्दीगौदर पार्वतगौड़ा चंदनगौड़ा", " "},
        {"Karnataka", "Bagalkot", "Veena Kashappanavar", "1", " ", "कर्नाटक", "बागलकोट", "वीणा कशप्पनवर", " "},
        {"Karnataka", "Bagalkot", "Adagal Rajendra", "4", " ", "कर्नाटक", "बागलकोट", "आदगल राजेंद्र", " "},
        {"Karnataka", "Bagalkot", "Muttu S Surakod", "4", " ", "कर्नाटक", "बागलकोट", "मुट्टु एस सुरकोड", " "},
        {"Karnataka", "Bagalkot", "Muttappa Mudakappa Hirekumbi", "4", " ", "कर्नाटक", "बागलकोट", "मुत्तप्पा मुदप्पप्पा हिरेकुम्बी", " "},
        {"Karnataka", "Bagalkot", "Parashuram Laxman Neelnaik", "2", " ", "कर्नाटक", "बागलकोट", "परशुराम लक्ष्मण नीलाणिक", " "},
        {"Karnataka", "Bagalkot", "Ravi Shivappa Padasalagi", "2", " ", "कर्नाटक", "बागलकोट", "रवि शिवप्पा पदासलगी", " "},
        {"Karnataka", "Bangalore Central", "Dr. Philip Mariyan", "4", " ", "कर्नाटक", "बैंगलोर सेंट्रल", "डॉ। फिलिप मारियान", " "},
        {"Karnataka", "Bangalore Central", "C. B. K. Rama", "4", " ", "कर्नाटक", "बैंगलोर सेंट्रल", "सीबीके राम", " "},
        {"Karnataka", "Bangalore Central", "S. Pandurangan", "3", " ", "कर्नाटक", "बैंगलोर सेंट्रल", "एस। पांडुरंगन", " "},
        {"Karnataka", "Bangalore Central", "Nawaz Dilber", "4", " ", "कर्नाटक", "बैंगलोर सेंट्रल", "नवाज दिलबर", " "},
        {"Karnataka", "Bangalore Central", "Arun Prasad A", "4", " ", "कर्नाटक", "बैंगलोर सेंट्रल", "अरुण प्रसाद ए", " "},
        {"Karnataka", "Bangalore Central", "B. Krishna Prasad", "4", " ", "कर्नाटक", "बैंगलोर सेंट्रल", "बी। कृष्ण प्रसाद", " "},
        {"Karnataka", "Bangalore Central", "Prakash Raj", "2", " ", "कर्नाटक", "बैंगलोर सेंट्रल", "प्रकाश राज", " "},
        {"Karnataka", "Bangalore Central", "P. C. Mohan", "1", " ", "कर्नाटक", "बैंगलोर सेंट्रल", "पीसी मोहन", " "},
        {"Karnataka", "Bangalore Central", "Rizwan Arshad", "1", " ", "कर्नाटक", "बैंगलोर सेंट्रल", "रिजवान अरशद", " "},
        {"Karnataka", "Bangalore Central", "C.J. Aditya", "4", " ", "कर्नाटक", "बैंगलोर सेंट्रल", "सीजे आदित्य", " "},
        {"Karnataka", "Bangalore Central", "A. Christhuraj", "4", " ", "कर्नाटक", "बैंगलोर सेंट्रल", "ए। क्रिसथुराज", " "},
        {"Karnataka", "Bangalore North", "Santhosh M.", "2", " ", "कर्नाटक", "बैंगलोर उत्तर", "संतोष एम।", " "},
        {"Karnataka", "Bangalore North", "C. Ravi Kumar", "4", " ", "कर्नाटक", "बैंगलोर उत्तर", "सी। रवि कुमार", " "},
        {"Karnataka", "Bangalore North", "K.N. Jagadesh Kumar", "2", " ", "कर्नाटक", "बैंगलोर उत्तर", "केएन जगदेश कुमार", " "},
        {"Karnataka", "Bangalore North", "N. Narayana Swamy Navakoti", "4", " ", "कर्नाटक", "बैंगलोर उत्तर", "एन। नारायण स्वामी नवकोटि", " "},
        {"Karnataka", "Bangalore North", "Amirtha Jai Kumar Essac Yesaiah", "4", " ", "कर्नाटक", "बैंगलोर उत्तर", "अमिरथा जय कुमार एस्सेक यसैया", " "},
        {"Karnataka", "Bangalore North", "Abdul Basheer", "3", " ", "कर्नाटक", "बैंगलोर उत्तर", "अब्दुल बशीर", " "},
        {"Karnataka", "Bangalore North", "Abdul Azeez", "4", " ", "कर्नाटक", "बैंगलोर उत्तर", "अब्दुल अज़ीज़", " "},
        {"Karnataka", "Bangalore North", "Kumar L.", "4", " ", "कर्नाटक", "बैंगलोर उत्तर", "कुमार एल।", " "},
        {"Karnataka", "Bangalore North", "Venkatesa Setty", "3", " ", "कर्नाटक", "बैंगलोर उत्तर", "वेंकटेश सेट्टी", " "},
        {"Karnataka", "Bangalore North", "Krishna Byregowda", "1", " ", "कर्नाटक", "बैंगलोर उत्तर", "कृष्ण बृजगौड़ा", " "},
        {"Karnataka", "Bangalore North", "D.V. Sadananda Gowda", "1", " ", "कर्नाटक", "बैंगलोर उत्तर", "डीवी सदानंद गौड़ा", " "},
        {"Karnataka", "Bangalore North", "Venu M.", "4", " ", "कर्नाटक", "बैंगलोर उत्तर", "वेणु एम।", " "},
        {"Karnataka", "Bangalore North", "V. Venkataraju", "4", " ", "कर्नाटक", "बैंगलोर उत्तर", "वी। वेंकटराजू", " "},
        {"Karnataka", "Bangalore North", "Krishnaiah", "2", " ", "कर्नाटक", "बैंगलोर उत्तर", "कृष्णैया", " "},
        {"Karnataka", "Bangalore North", "L. Nagaraj", "4", " ", "कर्नाटक", "बैंगलोर उत्तर", "एल। नागराज", " "},
        {"Karnataka", "Bangalore North", "Thimmaraj Gowda (Shenganadu)", "4", " ", "कर्नाटक", "बैंगलोर उत्तर", "थिमाराज गौड़ा (शेंगनाडु)", " "},
        {"Karnataka", "Bangalore North", "Ahmed Khan", "4", " ", "कर्नाटक", "बैंगलोर उत्तर", "अहमद खान", " "},
        {"Karnataka", "Bangalore North", "Sun Star D.Jairam", "3", " ", "कर्नाटक", "बैंगलोर उत्तर", "सन स्टार डी। जयराम", " "},
        {"Karnataka", "Bangalore North", "N.Hanume Gowda", "2", " ", "कर्नाटक", "बैंगलोर उत्तर", "एन हनुम गौड़ा", " "},
        {"Karnataka", "Bangalore Rural", "Ashwathnarayangowda", "1", " ", "कर्नाटक", "बैंगलोर ग्रामीण", "Ashwathnarayangowda", " "},
        {"Karnataka", "Bangalore Rural", "M.C. Devaraju", "4", " ", "कर्नाटक", "बैंगलोर ग्रामीण", "एमसी देवराजु", " "},
        {"Karnataka", "Bangalore Rural", "Venkateshappa", "4", " ", "कर्नाटक", "बैंगलोर ग्रामीण", "Venkateshappa", " "},
        {"Karnataka", "Bangalore Rural", "N. Krishnappa", "3", " ", "कर्नाटक", "बैंगलोर ग्रामीण", "एन। कृष्णप्पा", " "},
        {"Karnataka", "Bangalore Rural", "D.K. Suresh", "1", " ", "कर्नाटक", "बैंगलोर ग्रामीण", "डीके सुरेश", " "},
        {"Karnataka", "Bangalore Rural", "J T Prakash", "4", " ", "कर्नाटक", "बैंगलोर ग्रामीण", "जेटी प्रकाश", " "},
        {"Karnataka", "Bangalore Rural", "H.T. Chikkaraju", "4", " ", "कर्नाटक", "बैंगलोर ग्रामीण", "एचटी चिककारजू", " "},
        {"Karnataka", "Bangalore Rural", "D M Madegowda", "4", " ", "कर्नाटक", "बैंगलोर ग्रामीण", "डीएम मडगौड़ा", " "},
        {"Karnataka", "Bangalore Rural", "B. Gopal", "4", " ", "कर्नाटक", "बैंगलोर ग्रामीण", "बी। गोपाल", " "},
        {"Karnataka", "Bangalore Rural", "Manjunatha M", "4", " ", "कर्नाटक", "बैंगलोर ग्रामीण", "मंजुनाथ एम", " "},
        {"Karnataka", "Bangalore Rural", "Eswara", "3", " ", "कर्नाटक", "बैंगलोर ग्रामीण", "Eswara", " "},
        {"Karnataka", "Bangalore South", "Brahmanand.N", "4", " ", "कर्नाटक", "बैंगलोर दक्षिण", "Brahmanand.N", " "},
        {"Karnataka", "Bangalore South", "Tejasvi Surya", "1", " ", "कर्नाटक", "बैंगलोर दक्षिण", "तेजस्वी सूर्या", " "},
        {"Karnataka", "Bangalore South", "Bhagya.S", "4", " ", "कर्नाटक", "बैंगलोर दक्षिण", "Bhagya.S", " "},
        {"Karnataka", "Bangalore South", "Dr.John Basco Philips", "4", " ", "कर्नाटक", "बैंगलोर दक्षिण", "डॉ। जॉन बास्को फिलिप्स", " "},
        {"Karnataka", "Bangalore South", "G Venkatesh Bhovi", "4", " ", "कर्नाटक", "बैंगलोर दक्षिण", "जी वेंकटेश भोई", " "},
        {"Karnataka", "Bangalore South", "Vatal Nagaraj", "3", " ", "कर्नाटक", "बैंगलोर दक्षिण", "वटाल नागराज", " "},
        {"Karnataka", "Bangalore South", "Thyagaraj", "4", " ", "कर्नाटक", "बैंगलोर दक्षिण", "Thyagaraj", " "},
        {"Karnataka", "Bangalore South", "Syed Sadiq Pasha", "4", " ", "कर्नाटक", "बैंगलोर दक्षिण", "सैयद सादिक पाशा", " "},
        {"Karnataka", "Bangalore South", "Yogeesh Nagaraj", "4", " ", "कर्नाटक", "बैंगलोर दक्षिण", "योगेश नागराज", " "},
        {"Karnataka", "Bangalore South", "B.Chikka Nagesha", "4", " ", "कर्नाटक", "बैंगलोर दक्षिण", "बी चिखा नागेश", " "},
        {"Karnataka", "Bangalore South", "Kollur Manjunatha Naik", "2", " ", "कर्नाटक", "बैंगलोर दक्षिण", "कोल्लूर मंजुनाथ नाइक", " "},
        {"Karnataka", "Bangalore South", "Madesh.V", "4", " ", "कर्नाटक", "बैंगलोर दक्षिण", "Madesh.V", " "},
        {"Karnataka", "Bangalore South", "Santhosh Min B", "4", " ", "कर्नाटक", "बैंगलोर दक्षिण", "संतोष मिन बी", " "},
        {"Karnataka", "Bangalore South", "B.K.Hariprasad", "1", " ", "कर्नाटक", "बैंगलोर दक्षिण", "BKHariprasad", " "},
        {"Karnataka", "Belgaum", "Shrikant Balkrishna Kadam", "4", " ", "कर्नाटक", "बेलगाम", "श्रीकांत बालकृष्ण कदम", " "},
        {"Karnataka", "Belgaum", "Nanda Maruti Kodachwadkar", "4", " ", "कर्नाटक", "बेलगाम", "नंदा मारुति कोड़वाडकर", " "},
        {"Karnataka", "Belgaum", "Buland Deepak Dalavi", "4", " ", "कर्नाटक", "बेलगाम", "बुलंद दीपक दलवी", " "},
        {"Karnataka", "Belgaum", "Pandurang Mallappa Pattan", "4", " ", "कर्नाटक", "बेलगाम", "पांडुरंग मल्लप्पा पट्टन", " "},
        {"Karnataka", "Belgaum", "Raju Changappa Divatage", "4", " ", "कर्नाटक", "बेलगाम", "राजू चंगप्पा दिवागत", " "},
        {"Karnataka", "Belgaum", "Vinayak Gopal Gunjatkar", "4", " ", "कर्नाटक", "बेलगाम", "विनायक गोपाल गुंजतकर", " "},
        {"Karnataka", "Belgaum", "Lakshmanarav Melage", "3", " ", "कर्नाटक", "बेलगाम", "लक्ष्मणाराव मेलागे", " "},
        {"Karnataka", "Belgaum", "Sanjay Kamble", "4", " ", "कर्नाटक", "बेलगाम", "संजय कांबले", " "},
        {"Karnataka", "Belgaum", "Angadi Suresh", "1", " ", "कर्नाटक", "बेलगाम", "अंगदी सुरेश", " "},
        {"Karnataka", "Belgaum", "Maruti Siddappa Chougule", "4", " ", "कर्नाटक", "बेलगाम", "मारुति सिद्धप्पा चौगुले", " "},
        {"Karnataka", "Belgaum", "Ganesh Daddikar", "2", " ", "कर्नाटक", "बेलगाम", "गणेश दद्दिकर", " "},
        {"Karnataka", "Belgaum", "Prakash Balappa Nesarkar", "4", " ", "कर्नाटक", "बेलगाम", "प्रकाश बालप्पा नेसारकर", " "},
        {"Karnataka", "Belgaum", "Mahadev Maruti Manganakar", "4", " ", "कर्नाटक", "बेलगाम", "महादेव मारुति मंगणकर", " "},
        {"Karnataka", "Belgaum", "Kavita Deepak Kole", "4", " ", "कर्नाटक", "बेलगाम", "कविता दीपक कोइल", " "},
        {"Karnataka", "Belgaum", "Prabhakar Bhujang Patil", "4", " ", "कर्नाटक", "बेलगाम", "प्रभाकर भुजंग पाटिल", " "},
        {"Karnataka", "Belgaum", "Dilshaad Sikandar Tahashildar", "4", " ", "कर्नाटक", "बेलगाम", "दिलशाद सिकंदर तहसीलदार", " "},
        {"Karnataka", "Belgaum", "Ranjit Kallappa Patil", "2", " ", "कर्नाटक", "बेलगाम", "रंजीत कल्लप्पा पाटिल", " "},
        {"Karnataka", "Belgaum", "Dhananjay Rajaram Patil", "4", " ", "कर्नाटक", "बेलगाम", "धनंजय राजाराम पाटिल", " "},
        {"Karnataka", "Belgaum", "Gajanan Amrut Thokanekar", "4", " ", "कर्नाटक", "बेलगाम", "गजानन अमृत ठोकनेकर", " "},
        {"Karnataka", "Belgaum", "Shankar Pandappa Rathod", "4", " ", "कर्नाटक", "बेलगाम", "शंकर पंडप्पा राठौड़", " "},
        {"Karnataka", "Belgaum", "Nagesh Subhash Bobate", "4", " ", "कर्नाटक", "बेलगाम", "नागेश सुभाष बोबते", " "},
        {"Karnataka", "Belgaum", "Shubham Vikrant Shelke", "4", " ", "कर्नाटक", "बेलगाम", "शुभम विक्रांत शेलके", " "},
        {"Karnataka", "Belgaum", "Ashutosh Shashikant Kamble", "4", " ", "कर्नाटक", "बेलगाम", "आशुतोष शशिकांत कांबले", " "},
        {"Karnataka", "Belgaum", "Pranam Prakash Patil", "4", " ", "कर्नाटक", "बेलगाम", "प्रणाम प्रकाश पाटिल", " "},
        {"Karnataka", "Belgaum", "Ramchandra Dattoba Patil", "4", " ", "कर्नाटक", "बेलगाम", "रामचंद्र दत्तोबा पाटिल", " "},
        {"Karnataka", "Belgaum", "Vinayak Balakrishna More", "4", " ", "कर्नाटक", "बेलगाम", "विनायक बालकृष्ण मोरे", " "},
        {"Karnataka", "Belgaum", "Megharaj Shivagoudappa Khanagoudar", "4", " ", "कर्नाटक", "बेलगाम", "मेघराज शिवगौडप्पा खानगौदर", " "},
        {"Karnataka", "Belgaum", "Sachin Manohar Nikam", "4", " ", "कर्नाटक", "बेलगाम", "सचिन मनोहर निकम", " "},
        {"Karnataka", "Belgaum", "Krishnakant Kamanna Birje", "3", " ", "कर्नाटक", "बेलगाम", "कृष्णकांत कामना बिरजे", " "},
        {"Karnataka", "Belgaum", "Ramchandra Krishna Gaonkar", "4", " ", "कर्नाटक", "बेलगाम", "रामचंद्र कृष्ण गोदकर", " "},
        {"Karnataka", "Belgaum", "Shivaraj Narayan Patil", "4", " ", "कर्नाटक", "बेलगाम", "शिवराज नारायण पाटिल", " "},
        {"Karnataka", "Belgaum", "Rajendra Yallappa Patil", "4", " ", "कर्नाटक", "बेलगाम", "राजेंद्र यलप्पा पाटिल", " "},
        {"Karnataka", "Belgaum", "Dr.Virupakshappa Sadhunavar", "1", " ", "कर्नाटक", "बेलगाम", "डॉ.विरूपक्षपा साधुनावर", " "},
        {"Karnataka", "Belgaum", "Kallappa Krishnappa Kowadkar", "4", " ", "कर्नाटक", "बेलगाम", "कल्लप्पा कृष्णप्पा कोवाडकर", " "},
        {"Karnataka", "Belgaum", "Onkarsingh C Bhatia", "4", " ", "कर्नाटक", "बेलगाम", "ओंकारसिंह सी भाटिया", " "},
        {"Karnataka", "Belgaum", "Sunil Vittal Dasar", "4", " ", "कर्नाटक", "बेलगाम", "सुनील विट्ठल दासर", " "},
        {"Karnataka", "Belgaum", "Sachin Shantaram Kelavekar", "4", " ", "कर्नाटक", "बेलगाम", "सचिन शांताराम केलवेकर", " "},
        {"Karnataka", "Belgaum", "Anil Baban Hegade", "4", " ", "कर्नाटक", "बेलगाम", "अनिल बबन हेगड़े", " "},
        {"Karnataka", "Belgaum", "Gopal Balavantrao Desai", "4", " ", "कर्नाटक", "बेलगाम", "गोपाल बलवंतराव देसाई", " "},
        {"Karnataka", "Belgaum", "Vishwanath Buwaji", "4", " ", "कर्नाटक", "बेलगाम", "विश्वनाथ बुवाजी", " "},
        {"Karnataka", "Belgaum", "Laxman Bhimarao Dalavi", "4", " ", "कर्नाटक", "बेलगाम", "लक्ष्मण भीमराव दलवी", " "},
        {"Karnataka", "Belgaum", "Neelkanth Mahadev Patil", "4", " ", "कर्नाटक", "बेलगाम", "नीलकंठ महादेव पाटिल", " "},
        {"Karnataka", "Bellary", "A. Devadas", "4", " ", "कर्नाटक", "बेल्लारी", "ए देवदास", " "},
        {"Karnataka", "Bellary", "V. S. Ugrappa", "1", " ", "कर्नाटक", "बेल्लारी", "वीएस उग्रप्पा", " "},
        {"Karnataka", "Bellary", "K. Gulappa", "3", " ", "कर्नाटक", "बेल्लारी", "के। गुलप्पा", " "},
        {"Karnataka", "Bellary", "B. Eshwarappa", "2", " ", "कर्नाटक", "बेल्लारी", "बी ईश्वरप्पा", " "},
        {"Karnataka", "Bellary", "Yeruru Pampapathi", "4", " ", "कर्नाटक", "बेल्लारी", "येरु पमपपति", " "},
        {"Karnataka", "Bellary", "Y. Devendrappa", "1", " ", "कर्नाटक", "बेल्लारी", "वाई। देवेंद्रप्पा", " "},
        {"Karnataka", "Bellary", "T. Veeresh", "4", " ", "कर्नाटक", "बेल्लारी", "टी। वीरेश", " "},
        {"Karnataka", "Bellary", "P. D. Ramanayaka", "4", " ", "कर्नाटक", "बेल्लारी", "पीडी रामनायका", " "},
        {"Karnataka", "Bellary", "B. Raghu", "4", " ", "कर्नाटक", "बेल्लारी", "बी रघु ने", " "},
        {"Karnataka", "Bidar", "Bhagwanth Khuba", "1", " ", "कर्नाटक", "बीदर", "भगवंत खुबा", " "},
        {"Karnataka", "Bidar", "Mohammed Abdul Wakeel", "4", " ", "कर्नाटक", "बीदर", "मोहम्मद अब्दुल वेकेल", " "},
        {"Karnataka", "Bidar", "Mohammed Yousuf", "4", " ", "कर्नाटक", "बीदर", "मोहम्मद यूसुफ", " "},
        {"Karnataka", "Bidar", "Abdus Sattar Mujahed", "2", " ", "कर्नाटक", "बीदर", "अब्दुस सत्तार मुजाहिद", " "},
        {"Karnataka", "Bidar", "Sharad", "4", " ", "कर्नाटक", "बीदर", "शरद", " "},
        {"Karnataka", "Bidar", "Eshwar", "1", " ", "कर्नाटक", "बीदर", "ईश्वर", " "},
        {"Karnataka", "Bidar", "Sugriv Bharat Kachave", "4", " ", "कर्नाटक", "बीदर", "सुग्रीव भारत कछवे", " "},
        {"Karnataka", "Bidar", "Md Merajuddin", "4", " ", "कर्नाटक", "बीदर", "एमडी मरजुद्दीन", " "},
        {"Karnataka", "Bidar", "S.H Bukhari", "3", " ", "कर्नाटक", "बीदर", "एसएच बुखारी", " "},
        {"Karnataka", "Bidar", "Shrimanth Yevate Patil", "3", " ", "कर्नाटक", "बीदर", "श्रीमंत येवते पाटिल", " "},
        {"Karnataka", "Bidar", "Rajambi", "4", " ", "कर्नाटक", "बीदर", "Rajambi", " "},
        {"Karnataka", "Bidar", "Shivaraj", "3", " ", "कर्नाटक", "बीदर", "शिवराज", " "},
        {"Karnataka", "Bidar", "Dayanand", "4", " ", "कर्नाटक", "बीदर", "दयानंद", " "},
        {"Karnataka", "Bidar", "Moulvi Zameruddin", "3", " ", "कर्नाटक", "बीदर", "मौलवी ज़मीरुद्दीन", " "},
        {"Karnataka", "Bidar", "Santosh", "4", " ", "कर्नाटक", "बीदर", "संतोष", " "},
        {"Karnataka", "Bijapur", "Pujari Shrinath Sangappa", "2", " ", "कर्नाटक", "बीजापुर", "पुजारी श्रीनाथ संगप्पा", " "},
        {"Karnataka", "Bijapur", "Ramappa Harijan", "2", " ", "कर्नाटक", "बीजापुर", "रामप्पा हरिजन", " "},
        {"Karnataka", "Bijapur", "Jigajinagi Ramesh Chandappa", "1", " ", "कर्नाटक", "बीजापुर", "जिगजिनागी रमेश चंदप्पा", " "},
        {"Karnataka", "Bijapur", "Yamanappa Vittal Gunadal", "2", " ", "कर्नाटक", "बीजापुर", "यमनप्पा विट्टल गुनदाल", " "},
        {"Karnataka", "Bijapur", "Dondiba Ramu Rathod", "4", " ", "कर्नाटक", "बीजापुर", "डोंडिबा रामू राठौड़", " "},
        {"Karnataka", "Bijapur", "Balaji Dyamanna Waddar", "2", " ", "कर्नाटक", "बीजापुर", "बालाजी दायमन्ना वद्दार", " "},
        {"Karnataka", "Bijapur", "Gurubasava. P . Rabakavi", "4", " ", "कर्नाटक", "बीजापुर", "Gurubasava। पी। Rabakavi", " "},
        {"Karnataka", "Bijapur", "Dadasab Siddappa Bagayat", "4", " ", "कर्नाटक", "बीजापुर", "दादासाब सिद्दप्पा बागायत", " "},
        {"Karnataka", "Chamarajanagar", "Subbaiah", "4", " ", "कर्नाटक", "चामराजनगर", "सुब्बैया", " "},
        {"Karnataka", "Chamarajanagar", "G.D. Rajagopal", "4", " ", "कर्नाटक", "चामराजनगर", "जीडी राजगोपाल", " "},
        {"Karnataka", "Chamarajanagar", "R Dhruvanarayana", "1", " ", "कर्नाटक", "चामराजनगर", "आर ध्रुवनारायण", " "},
        {"Karnataka", "Chamarajanagar", "N Ambarish", "4", " ", "कर्नाटक", "चामराजनगर", "एन अंबरीश", " "},
        {"Karnataka", "Chamarajanagar", "V Srinivas Prasad", "1", " ", "कर्नाटक", "चामराजनगर", "वी श्रीनिवास प्रसाद", " "},
        {"Karnataka", "Chamarajanagar", "Anand Jivan Ram", "4", " ", "कर्नाटक", "चामराजनगर", "आनंद जीवन राम", " "},
        {"Karnataka", "Chamarajanagar", "M Pradeep Kumar", "4", " ", "कर्नाटक", "चामराजनगर", "एम प्रदीप कुमार", " "},
        {"Karnataka", "Chikkballapur", "Nalina.K.S", "4", " ", "कर्नाटक", "चिकबल्लपुर", "Nalina.KS", " "},
        {"Karnataka", "Chikkballapur", "Muniraju.G", "4", " ", "कर्नाटक", "चिकबल्लपुर", "Muniraju.G", " "},
        {"Karnataka", "Chikkballapur", "L. Nagaraj", "4", " ", "कर्नाटक", "चिकबल्लपुर", "एल। नागराज", " "},
        {"Karnataka", "Chikkballapur", "M.Veerappa Moily", "1", " ", "कर्नाटक", "चिकबल्लपुर", "एम. वीरप्पा मोइली", " "},
        {"Karnataka", "Chikkballapur", "Dr. C.S.Dwarakanath", "3", " ", "कर्नाटक", "चिकबल्लपुर", "डॉ। CSDwarakanath", " "},
        {"Karnataka", "Chikkballapur", "Phaniraj.S.V", "4", " ", "कर्नाटक", "चिकबल्लपुर", "Phaniraj.SV", " "},
        {"Karnataka", "Chikkballapur", "Nasrulla", "4", " ", "कर्नाटक", "चिकबल्लपुर", "Nasrulla", " "},
        {"Karnataka", "Chikkballapur", "D.Palya Khadar Subhan Khan", "4", " ", "कर्नाटक", "चिकबल्लपुर", "डी.पल्या खादर सुभान खान", " "},
        {"Karnataka", "Chikkballapur", "S.Varalakshmi", "2", " ", "कर्नाटक", "चिकबल्लपुर", "S.Varalakshmi", " "},
        {"Karnataka", "Chikkballapur", "S.R.Nageshareddy", "4", " ", "कर्नाटक", "चिकबल्लपुर", "SRNageshareddy", " "},
        {"Karnataka", "Chikkballapur", "Nazir Ahmed", "4", " ", "कर्नाटक", "चिकबल्लपुर", "नजीर अहमद", " "},
        {"Karnataka", "Chikkballapur", "Alanguru Kanakalakshmi", "4", " ", "कर्नाटक", "चिकबल्लपुर", "अलंगुरु कनकलक्ष्मी", " "},
        {"Karnataka", "Chikkballapur", "B.N.Bache Gowda", "1", " ", "कर्नाटक", "चिकबल्लपुर", "BNBache गौड़ा", " "},
        {"Karnataka", "Chikkodi", "Shrinik Annasaheb Jangate", "4", " ", "कर्नाटक", "चिक्कोडी", "श्रीनिक अन्नसाहेब जंगटे", " "},
        {"Karnataka", "Chikkodi", "Machchendra Davalu Kadapure", "4", " ", "कर्नाटक", "चिक्कोडी", "मचकेन्द्र दावालु कदपुरे", " "},
        {"Karnataka", "Chikkodi", "Jitendra Subhash Nerle", "4", " ", "कर्नाटक", "चिक्कोडी", "जितेंद्र सुभाष नेरले", " "},
        {"Karnataka", "Chikkodi", "Appasaheb Shripati Kurane", "4", " ", "कर्नाटक", "चिक्कोडी", "अप्पासाहेब श्रीपति कुराने", " "},
        {"Karnataka", "Chikkodi", "Magdum Ismailmagdum", "4", " ", "कर्नाटक", "चिक्कोडी", "मागदुम इस्माइलमगदुम", " "},
        {"Karnataka", "Chikkodi", "Prakash Babanna Hukkeri", "1", " ", "कर्नाटक", "चिक्कोडी", "प्रकाश बबना हुक्केरी", " "},
        {"Karnataka", "Chikkodi", "Vishwnath Kalloli Wajantri", "4", " ", "कर्नाटक", "चिक्कोडी", "विश्वनाथ कल्लोली वजंत्री", " "},
        {"Karnataka", "Chikkodi", "Annasaheb Shankar Jolle", "1", " ", "कर्नाटक", "चिक्कोडी", "अन्नासाहेब शंकर जोले", " "},
        {"Karnataka", "Chikkodi", "Kallappa Adiveppa Gudasi", "4", " ", "कर्नाटक", "चिक्कोडी", "कल्लप्पा आदिवप्पा गुडासी", " "},
        {"Karnataka", "Chitradurga", "L Venugopal", "4", " ", "कर्नाटक", "चित्रदुर्ग", "एल वेणुगोपाल", " "},
        {"Karnataka", "Chitradurga", "R Hanumanthappa", "3", " ", "कर्नाटक", "चित्रदुर्ग", "आर हनुमनथप्पा", " "},
        {"Karnataka", "Chitradurga", "A Narayanaswamy", "1", " ", "कर्नाटक", "चित्रदुर्ग", "एक नारायणस्वामी", " "},
        {"Karnataka", "Chitradurga", "Ganesh", "4", " ", "कर्नाटक", "चित्रदुर्ग", "गणेश", " "},
        {"Karnataka", "Chitradurga", "Kumar Y", "2", " ", "कर्नाटक", "चित्रदुर्ग", "कुमार वाई", " "},
        {"Karnataka", "Chitradurga", "B N Chandrappa", "1", " ", "कर्नाटक", "चित्रदुर्ग", "बीएन चंद्रप्पा", " "},
        {"Karnataka", "Chitradurga", "C H Narayanaswamy", "4", " ", "कर्नाटक", "चित्रदुर्ग", "सीएच नारायणस्वामी", " "},
        {"Karnataka", "Chitradurga", "L Rangappa", "2", " ", "कर्नाटक", "चित्रदुर्ग", "एल रंगप्पा", " "},
        {"Karnataka", "Chitradurga", "Thippeswamy T", "4", " ", "कर्नाटक", "चित्रदुर्ग", "थिप्पेस्वामी टी", " "},
        {"Karnataka", "Chitradurga", "Devendrappa", "4", " ", "कर्नाटक", "चित्रदुर्ग", "Devendrappa", " "},
        {"Karnataka", "Chitradurga", "Mahanthesh C U", "2", " ", "कर्नाटक", "चित्रदुर्ग", "महंतेश सीयू", " "},
        {"Karnataka", "Dakshina Kannada", "Mohammad Khalid", "4", " ", "कर्नाटक", "दक्षिण कन्नड़", "मोहम्मद खालिद", " "},
        {"Karnataka", "Dakshina Kannada", "Mohammed Eliyas", "2", " ", "कर्नाटक", "दक्षिण कन्नड़", "मोहम्मद इलियास", " "},
        {"Karnataka", "Dakshina Kannada", "H. Suresh Poojary", "4", " ", "कर्नाटक", "दक्षिण कन्नड़", "एच। सुरेश पूजारी", " "},
        {"Karnataka", "Dakshina Kannada", "Abdul Hameed", "4", " ", "कर्नाटक", "दक्षिण कन्नड़", "अब्दुल हमीद", " "},
        {"Karnataka", "Dakshina Kannada", "Nalin Kumar Kateel", "1", " ", "कर्नाटक", "दक्षिण कन्नड़", "नलिन कुमार काटेल", " "},
        {"Karnataka", "Dakshina Kannada", "Alexander", "2", " ", "कर्नाटक", "दक्षिण कन्नड़", "सिकंदर", " "},
        {"Karnataka", "Dakshina Kannada", "Mithun M Rai", "1", " ", "कर्नाटक", "दक्षिण कन्नड़", "मिथुन एम राय", " "},
        {"Karnataka", "Dakshina Kannada", "Supreeth Kumar Poojary", "4", " ", "कर्नाटक", "दक्षिण कन्नड़", "सुप्रीत कुमार पूजा", " "},
        {"Karnataka", "Dakshina Kannada", "S. Sathish Saliyan", "4", " ", "कर्नाटक", "दक्षिण कन्नड़", "एस। सतीश सलियान", " "},
        {"Karnataka", "Dakshina Kannada", "Vijay Shreenivas C", "4", " ", "कर्नाटक", "दक्षिण कन्नड़", "विजय श्रीनिवास सी", " "},
        {"Karnataka", "Dakshina Kannada", "Deepak Rajesh Coelho", "4", " ", "कर्नाटक", "दक्षिण कन्नड़", "दीपक राजेश कोल्हो", " "},
        {"Karnataka", "Dakshina Kannada", "Maxim Pinto", "4", " ", "कर्नाटक", "दक्षिण कन्नड़", "मैक्सिम पिंटो", " "},
        {"Karnataka", "Davanagere", "Ganesha B A", "4", " ", "कर्नाटक", "दावनगेरे", "गणेश बीए", " "},
        {"Karnataka", "Davanagere", "M B Veerabhadrappa", "4", " ", "कर्नाटक", "दावनगेरे", "एमबी वीरभद्रप्पा", " "},
        {"Karnataka", "Davanagere", "G M Siddeshwar", "1", " ", "कर्नाटक", "दावनगेरे", "जीएम सिद्धेश्वर", " "},
        {"Karnataka", "Davanagere", "Mohammed Aleemulla", "4", " ", "कर्नाटक", "दावनगेरे", "मोहम्मद अलीमुल्ला", " "},
        {"Karnataka", "Davanagere", "H B Manjappa", "1", " ", "कर्नाटक", "दावनगेरे", "एचबी मंजप्पा", " "},
        {"Karnataka", "Davanagere", "Siddappa B H", "2", " ", "कर्नाटक", "दावनगेरे", "सिद्दप्पा बी.एच.", " "},
        {"Karnataka", "Davanagere", "V Iqbal Ahamed", "4", " ", "कर्नाटक", "दावनगेरे", "वी इकबाल अहमद", " "},
        {"Karnataka", "Davanagere", "Manjunatha Marikoppa", "4", " ", "कर्नाटक", "दावनगेरे", "मंजूनाथ मारिकोप्पा", " "},
        {"Karnataka", "Davanagere", "Ravindra Navale", "3", " ", "कर्नाटक", "दावनगेरे", "रवींद्र नवले", " "},
        {"Karnataka", "Davanagere", "Dr Sridhara Udupa", "3", " ", "कर्नाटक", "दावनगेरे", "डॉ। श्रीधरा उडुपा", " "},
        {"Karnataka", "Davanagere", "Abdul Nazeer Sab", "4", " ", "कर्नाटक", "दावनगेरे", "अब्दुल नज़ीर सब", " "},
        {"Karnataka", "Davanagere", "Harish Halli", "4", " ", "कर्नाटक", "दावनगेरे", "हरीश होली", " "},
        {"Karnataka", "Davanagere", "Syed Zabiulla K", "4", " ", "कर्नाटक", "दावनगेरे", "सैयद जबीउल्ला के", " "},
        {"Karnataka", "Davanagere", "C M Manjunatha Swami", "4", " ", "कर्नाटक", "दावनगेरे", "सीएम मंजूनाथ स्वामी", " "},
        {"Karnataka", "Davanagere", "A T Dadakhalandar", "4", " ", "कर्नाटक", "दावनगेरे", "एटी दादाखेलदार", " "},
        {"Karnataka", "Davanagere", "S K Afzalkhan", "4", " ", "कर्नाटक", "दावनगेरे", "एसके अफजलखान", " "},
        {"Karnataka", "Davanagere", "H Eshwarappa", "3", " ", "कर्नाटक", "दावनगेरे", "एच ईश्वरप्पा", " "},
        {"Karnataka", "Davanagere", "Barkath Ali", "4", " ", "कर्नाटक", "दावनगेरे", "बरकत अली", " "},
        {"Karnataka", "Davanagere", "B V Tippeswamy Goshale", "4", " ", "कर्नाटक", "दावनगेरे", "बीवी तिप्पेस्वामी गोशले", " "},
        {"Karnataka", "Dharwad", "Udayakumar Ayyappa Ambiger", "4", " ", "कर्नाटक", "धारवाड़", "उदयकुमार अयप्पा अंबिगर", " "},
        {"Karnataka", "Dharwad", "Mallikarjunagouda Giriyappagouda Balanagoudra", "4", " ", "कर्नाटक", "धारवाड़", "मल्लिकार्जुनगौड़ा गिरियप्पगौड़ा बालनगौड़ा", " "},
        {"Karnataka", "Dharwad", "Hashinabanu Tapalvale", "4", " ", "कर्नाटक", "धारवाड़", "हशिनाबनु तपवेल", " "},
        {"Karnataka", "Dharwad", "Irappa Madar", "4", " ", "कर्नाटक", "धारवाड़", "इरापा मदार", " "},
        {"Karnataka", "Dharwad", "Vinay Kulkarni", "1", " ", "कर्नाटक", "धारवाड़", "विनय कुलकर्णी", " "},
        {"Karnataka", "Dharwad", "Maradagi Veerappa Gurushantappa", "4", " ", "कर्नाटक", "धारवाड़", "मरदगी वीरप्पा गुरुशांतप्पा", " "},
        {"Karnataka", "Dharwad", "Vinod D Ghodke", "4", " ", "कर्नाटक", "धारवाड़", "विनोद डी घोडके", " "},
        {"Karnataka", "Dharwad", "Somashekhar Peeraji Yadav", "4", " ", "कर्नाटक", "धारवाड़", "सोमशेखर पीरजी यादव", " "},
        {"Karnataka", "Dharwad", "Raju Anantsa Naikwadi", "2", " ", "कर्नाटक", "धारवाड़", "राजू अनंता नाइकवाडी", " "},
        {"Karnataka", "Dharwad", "Revanshiddappa Basavaraj Talawar", "4", " ", "कर्नाटक", "धारवाड़", "रेवंशीदप्पा बसवराज तलवार", " "},
        {"Karnataka", "Dharwad", "Pralhad Joshi", "1", " ", "कर्नाटक", "धारवाड़", "प्रल्हाद जोशी", " "},
        {"Karnataka", "Dharwad", "Vadiraj Mannari Madhusudhan", "2", " ", "कर्नाटक", "धारवाड़", "वदिराज मन्नारी मधुसूदन", " "},
        {"Karnataka", "Dharwad", "Shakeel Ahmad Abdulsattar Dodwad", "4", " ", "कर्नाटक", "धारवाड़", "शकील अहमद अब्दुलात्सर डोडवाड", " "},
        {"Karnataka", "Dharwad", "Dundasi Abdulrahiman Mahammad Hanif", "2", " ", "कर्नाटक", "धारवाड़", "दुन्दसी अब्दुलरहिमन मोहम्मद हनीफ", " "},
        {"Karnataka", "Gulbarga", "Rajkumar", "4", " ", "कर्नाटक", "गुलबर्गा", "राजकुमार", " "},
        {"Karnataka", "Gulbarga", "G. Timmaraju", "4", " ", "कर्नाटक", "गुलबर्गा", "जी। तिमाराजू", " "},
        {"Karnataka", "Gulbarga", "Dr. Umesh G Jadhav", "1", " ", "कर्नाटक", "गुलबर्गा", "डॉ। उमेश जी जाधव", " "},
        {"Karnataka", "Gulbarga", "Mallikarjun Kharge", "1", " ", "कर्नाटक", "गुलबर्गा", "मल्लिकार्जुन खड़गे", " "},
        {"Karnataka", "Gulbarga", "Shankar Jadhav", "4", " ", "कर्नाटक", "गुलबर्गा", "शंकर जाधव", " "},
        {"Karnataka", "Gulbarga", "Vijay Jadhav", "4", " ", "कर्नाटक", "गुलबर्गा", "विजय जाधव", " "},
        {"Karnataka", "Gulbarga", "Ramesh Bheemsingh Chavan", "2", " ", "कर्नाटक", "गुलबर्गा", "रमेश भीमसिंह चव्हाण", " "},
        {"Karnataka", "Gulbarga", "S. M. Sharma", "2", " ", "कर्नाटक", "गुलबर्गा", "एसएम शर्मा", " "},
        {"Karnataka", "Gulbarga", "K. B. Vasu", "2", " ", "कर्नाटक", "गुलबर्गा", "केबी वासु", " "},
        {"Karnataka", "Hassan", "Vinodraj K H", "4", " ", "कर्नाटक", "हसन", "विनोदराज के", " "},
        {"Karnataka", "Hassan", "H M Chandregowda", "3", " ", "कर्नाटक", "हसन", "एचएम चंद्रागौड़ा", " "},
        {"Karnataka", "Hassan", "M. Mahesh (Al: Lokesh)", "4", " ", "कर्नाटक", "हसन", "एम। महेश (अल: लोकेश)", " "},
        {"Karnataka", "Hassan", "Manju A", "1", " ", "कर्नाटक", "हसन", "मंजू ए", " "},
        {"Karnataka", "Hassan", "R G Sathisha", "4", " ", "कर्नाटक", "हसन", "आरजी सतीशा", " "},
        {"Karnataka", "Haveri", "Ishwar Patil", "4", " ", "कर्नाटक", "हावेरी", "ईश्वर पाटिल", " "},
        {"Karnataka", "Haveri", "Veerabhadrappa Veerappa Kabbinada", "3", " ", "कर्नाटक", "हावेरी", "वीरभद्रप्पा वीरप्पा कबिनदा", " "},
        {"Karnataka", "Haveri", "Basavaraj. S. Desai", "4", " ", "कर्नाटक", "हावेरी", "बासवराज। एस। देसाई", " "},
        {"Karnataka", "Haveri", "Bommoji Ramappa Siddappa", "3", " ", "कर्नाटक", "हावेरी", "बोम्मोजी रामप्पा सिद्धप्पा", " "},
        {"Karnataka", "Haveri", "Udasi. S.C.", "1", " ", "कर्नाटक", "हावेरी", "उदासी। अनुसूचित जाति", " "},
        {"Karnataka", "Haveri", "D.R. Patil", "1", " ", "कर्नाटक", "हावेरी", "डीआर पाटिल", " "},
        {"Karnataka", "Haveri", "Hanumanthappa D Kabbar", "4", " ", "कर्नाटक", "हावेरी", "हनुमनथप्पा डी कबर", " "},
        {"Karnataka", "Haveri", "Siddappa Kallappa Poojar", "4", " ", "कर्नाटक", "हावेरी", "सिदप्पा कल्लप्पा पुजार", " "},
        {"Karnataka", "Kolar", "K.H. Muniyappa", "1", " ", "कर्नाटक", "कोलार", "केएच मुनियप्पा", " "},
        {"Karnataka", "Kolar", "S. Muniswamy", "1", " ", "कर्नाटक", "कोलार", "एस। मुनीस्वामी", " "},
        {"Karnataka", "Kolar", "Medihala Chalavadi M Chandrashekar", "4", " ", "कर्नाटक", "कोलार", "मेदिहाला चलवदी एम चंद्रशेखर", " "},
        {"Karnataka", "Kolar", "C. Shankarappa", "4", " ", "कर्नाटक", "कोलार", "सी। शंकरप्पा", " "},
        {"Karnataka", "Kolar", "Sarvesh N.M.", "4", " ", "कर्नाटक", "कोलार", "सर्वेश एन.एम.", " "},
        {"Karnataka", "Kolar", "Ashok Chakravarthi M.B", "4", " ", "कर्नाटक", "कोलार", "अशोक चक्रवर्ती एमबी", " "},
        {"Karnataka", "Kolar", "Dhanamatnalli Venkateshappa", "4", " ", "कर्नाटक", "कोलार", "धनात्मनल्ली वेंकटेशप्पा", " "},
        {"Karnataka", "Kolar", "Munirajappa. P", "4", " ", "कर्नाटक", "कोलार", "Munirajappa। पी", " "},
        {"Karnataka", "Koppal", "Mallikarjun Hadapad", "4", " ", "कर्नाटक", "कोप्पल", "मल्लिकार्जुन हड़पड़", " "},
        {"Karnataka", "Koppal", "Bandimath Sharanayya", "4", " ", "कर्नाटक", "कोप्पल", "बांदीमठ शरणाय", " "},
        {"Karnataka", "Koppal", "Comrade B.Basavalingappa", "4", " ", "कर्नाटक", "कोप्पल", "कॉमरेड बी.बासावलिंगप्पा", " "},
        {"Karnataka", "Koppal", "Nagaraj Kalal", "4", " ", "कर्नाटक", "कोप्पल", "नागराज कलाल", " "},
        {"Karnataka", "Koppal", "Karadi Sanganna Amarappa", "1", " ", "कर्नाटक", "कोप्पल", "करदी संगना अमरप्पा", " "},
        {"Karnataka", "Koppal", "Suresh Gouda Mundinamane", "4", " ", "कर्नाटक", "कोप्पल", "सुरेश गौड़ा मुंडिनामने", " "},
        {"Karnataka", "Koppal", "Annojirao.G", "4", " ", "कर्नाटक", "कोप्पल", "Annojirao.G", " "},
        {"Karnataka", "Koppal", "K.Rajashekar Basavaraj Hitnal", "1", " ", "कर्नाटक", "कोप्पल", "के राजशेखर बसवराज हिटलल", " "},
        {"Karnataka", "Koppal", "Shivaputrappa. Gumagera", "4", " ", "कर्नाटक", "कोप्पल", "Shivaputrappa। Gumagera", " "},
        {"Karnataka", "Mandya", "M.L. Shashikumar", "4", " ", "कर्नाटक", "मंड्या", "एमएल शशिकुमार", " "},
        {"Karnataka", "Mandya", "H.Narayana", "4", " ", "कर्नाटक", "मंड्या", "H.Narayana", " "},
        {"Karnataka", "Mandya", "C. Lingegowda", "3", " ", "कर्नाटक", "मंड्या", "सी। लिंगेगौड़ा", " "},
        {"Karnataka", "Mandya", "G. Manjunath", "4", " ", "कर्नाटक", "मंड्या", "जी। मंजूनाथ", " "},
        {"Karnataka", "Mandya", "D C Jayashankara", "4", " ", "कर्नाटक", "मंड्या", "डीसी जयशंकर", " "},
        {"Karnataka", "Mandya", "Gurulingaiah", "4", " ", "कर्नाटक", "मंड्या", "Gurulingaiah", " "},
        {"Karnataka", "Mandya", "Sumalatha Ambareesh", "4", " ", "कर्नाटक", "मंड्या", "सुमलाथा अंबरीश", " "},
        {"Karnataka", "Mandya", "Satheesh Kumar .T.N", "4", " ", "कर्नाटक", "मंड्या", "सतीश कुमार .TN", " "},
        {"Karnataka", "Mandya", "Manjunath B", "2", " ", "कर्नाटक", "मंड्या", "मंजूनाथ बी", " "},
        {"Karnataka", "Mandya", "Kowdle Channappa", "3", " ", "कर्नाटक", "मंड्या", "कोवल चन्नप्पा", " "},
        {"Karnataka", "Mandya", "C.P. Divakar", "2", " ", "कर्नाटक", "मंड्या", "सीपी दिवाकर", " "},
        {"Karnataka", "Mandya", "M. Sumalatha", "4", " ", "कर्नाटक", "मंड्या", "एम। सुमलथा", " "},
        {"Karnataka", "Mandya", "Sumalatha", "4", " ", "कर्नाटक", "मंड्या", "सुमालाथा", " "},
        {"Karnataka", "Mysore", "C.H.Vijayashankar", "1", " ", "कर्नाटक", "मैसूर", "CHVijayashankar", " "},
        {"Karnataka", "Mysore", "Anand Kumar. M", "4", " ", "कर्नाटक", "मैसूर", "आनंद कुमार। एम", " "},
        {"Karnataka", "Mysore", "Asharani V", "4", " ", "कर्नाटक", "मैसूर", "आशारानी वी", " "},
        {"Karnataka", "Mysore", "R. Mahesha", "4", " ", "कर्नाटक", "मैसूर", "आर। महेशा", " "},
        {"Karnataka", "Mysore", "Kaveriamma.N.K.", "4", " ", "कर्नाटक", "मैसूर", "Kaveriamma.NK", " "},
        {"Karnataka", "Mysore", "Lokesh Kumar.G.", "2", " ", "कर्नाटक", "मैसूर", "लोकेश कुमार.जी.", " "},
        {"Karnataka", "Mysore", "Dr. B. Chandra (Chandregowda)", "2", " ", "कर्नाटक", "मैसूर", "डॉ। बी। चंद्रा (चंद्रगौड़ा)", " "},
        {"Karnataka", "Mysore", "Prathap Simha", "1", " ", "कर्नाटक", "मैसूर", "प्रताप सिम्हा", " "},
        {"Karnataka", "Mysore", "Ayub Khan", "2", " ", "कर्नाटक", "मैसूर", "अयूब खान", " "},
        {"Karnataka", "Mysore", "Raju S/O Late Chaluvashetty", "3", " ", "कर्नाटक", "मैसूर", "राजू एस / ओ स्वर्गीय चुल्लूवासटी", " "},
        {"Karnataka", "Mysore", "Venkatesha D Nayaka", "4", " ", "कर्नाटक", "मैसूर", "वेंकटेश डी नायक", " "},
        {"Karnataka", "Mysore", "Ravi", "4", " ", "कर्नाटक", "मैसूर", "रवि", " "},
        {"Karnataka", "Mysore", "Ningappa B D", "4", " ", "कर्नाटक", "मैसूर", "निंगप्पा बी.डी.", " "},
        {"Karnataka", "Mysore", "N. Nagesh", "4", " ", "कर्नाटक", "मैसूर", "एन। नागेश", " "},
        {"Karnataka", "Mysore", "G.M. Mahadeva", "2", " ", "कर्नाटक", "मैसूर", "जीएम महादेवा", " "},
        {"Karnataka", "Mysore", "P.K. Biddappa", "4", " ", "कर्नाटक", "मैसूर", "पीके बिद्दप्पा", " "},
        {"Karnataka", "Mysore", "Srinivasaiah", "3", " ", "कर्नाटक", "मैसूर", "Srinivasaiah", " "},
        {"Karnataka", "Raichur", "K. Somashekhar Yadagiri", "4", " ", "कर्नाटक", "रायचूर", "के। सोमशेखर यादगिरी", " "},
        {"Karnataka", "Raichur", "B. V Naik", "1", " ", "कर्नाटक", "रायचूर", "बी। वी। नाइक", " "},
        {"Karnataka", "Raichur", "Raja Amareshwara Naik", "1", " ", "कर्नाटक", "रायचूर", "राजा अमरेश्वर नाइक", " "},
        {"Karnataka", "Shimoga", "Krishna K", "2", " ", "कर्नाटक", "शिमोगा", "कृष्ण के", " "},
        {"Karnataka", "Shimoga", "N.T.Vijayakumar", "4", " ", "कर्नाटक", "शिमोगा", "NTVijayakumar", " "},
        {"Karnataka", "Shimoga", "Mohammed Yusuf Khan", "4", " ", "कर्नाटक", "शिमोगा", "मोहम्मद यूसुफ खान", " "},
        {"Karnataka", "Shimoga", "S.Umesha Varma", "4", " ", "कर्नाटक", "शिमोगा", "एस.उमेश वर्मा", " "},
        {"Karnataka", "Shimoga", "S.Madhubangarappa", "2", " ", "कर्नाटक", "शिमोगा", "S.Madhubangarappa", " "},
        {"Karnataka", "Shimoga", "Shashikumar S.Gowda", "4", " ", "कर्नाटक", "शिमोगा", "शशिकुमार एस। गौड़ा", " "},
        {"Karnataka", "Shimoga", "B.Y.Raghavendra", "1", " ", "कर्नाटक", "शिमोगा", "BYRaghavendra", " "},
        {"Karnataka", "Shimoga", "Guddappa", "2", " ", "कर्नाटक", "शिमोगा", "Guddappa", " "},
        {"Karnataka", "Shimoga", "Venkatesh R", "4", " ", "कर्नाटक", "शिमोगा", "वेंकटेश आर", " "},
        {"Karnataka", "Shimoga", "S.Umeshappa", "4", " ", "कर्नाटक", "शिमोगा", "S.Umeshappa", " "},
        {"Karnataka", "Tumkur", "T. N. Kumara Swamy", "4", " ", "कर्नाटक", "तुमकुर", "टीएन कुमारा स्वामी", " "},
        {"Karnataka", "Tumkur", "H. D. Devegowda", "3", " ", "कर्नाटक", "तुमकुर", "एचडी देवेगौड़ा", " "},
        {"Karnataka", "Tumkur", "B. S. Mallikarjunaiah", "2", " ", "कर्नाटक", "तुमकुर", "बीएस मल्लिकार्जुनैया", " "},
        {"Karnataka", "Tumkur", "J. K. Sami", "2", " ", "कर्नाटक", "तुमकुर", "जेके सामी", " "},
        {"Karnataka", "Tumkur", "G S Basavaraj", "1", " ", "कर्नाटक", "तुमकुर", "जीएस बसवराज", " "},
        {"Karnataka", "Tumkur", "D Sharadhishayana", "3", " ", "कर्नाटक", "तुमकुर", "D शारदीयशायण", " "},
        {"Karnataka", "Tumkur", "G Nagendra", "4", " ", "कर्नाटक", "तुमकुर", "जी नागेंद्र", " "},
        {"Karnataka", "Udupi Chikmagalur", "Maggalamakki Ganesh", "4", " ", "कर्नाटक", "उडुपी चिकमगलूर", "मग्गलकमकी गणेश", " "},
        {"Karnataka", "Udupi Chikmagalur", "Shekar Havanje", "2", " ", "कर्नाटक", "उडुपी चिकमगलूर", "शेखर हवनजी", " "},
        {"Karnataka", "Udupi Chikmagalur", "Shobha Karandlaje", "1", " ", "कर्नाटक", "उडुपी चिकमगलूर", "शोभा करंदलाजे", " "},
        {"Karnataka", "Udupi Chikmagalur", "Amrith Shenoy P", "2", " ", "कर्नाटक", "उडुपी चिकमगलूर", "अमृत शेनॉय पी", " "},
        {"Karnataka", "Udupi Chikmagalur", "Suresh Kunder", "4", " ", "कर्नाटक", "उडुपी चिकमगलूर", "सुरेश कुंदर", " "},
        {"Karnataka", "Udupi Chikmagalur", "Abdul Rahman", "4", " ", "कर्नाटक", "उडुपी चिकमगलूर", "अब्दुल रहमान", " "},
        {"Karnataka", "Udupi Chikmagalur", "Pramod Madhwaraj", "2", " ", "कर्नाटक", "उडुपी चिकमगलूर", "प्रमोद माधवराज", " "},
        {"Karnataka", "Udupi Chikmagalur", "P. Goutham Prabhu", "4", " ", "कर्नाटक", "उडुपी चिकमगलूर", "पी। गौतम प्रभु", " "},
        {"Karnataka", "Udupi Chikmagalur", "M.K Dayananda", "3", " ", "कर्नाटक", "उडुपी चिकमगलूर", "एमके दयानंद", " "},
        {"Karnataka", "Udupi Chikmagalur", "K.C. Prakash", "4", " ", "कर्नाटक", "उडुपी चिकमगलूर", "केसी प्रकाश", " "},
        {"Karnataka", "Udupi Chikmagalur", "P. Parameshwara", "2", " ", "कर्नाटक", "उडुपी चिकमगलूर", "पी। परमेस्वर", " "},
        {"Karnataka", "Udupi Chikmagalur", "Comrade Vijaykumar", "4", " ", "कर्नाटक", "उडुपी चिकमगलूर", "कामरेड विजयकुमार", " "},
        {"Karnataka", "Uttara Kannada", "Anand Asnotikar", "2", " ", "कर्नाटक", "उत्तर कन्नड़", "आनंद आसनटीकर", " "},
        {"Karnataka", "Uttara Kannada", "Nagaraj Anant Shirali", "4", " ", "कर्नाटक", "उत्तर कन्नड़", "नागराज अनंत शिराली", " "},
        {"Karnataka", "Uttara Kannada", "Mohammed Zabrood Khateeb", "2", " ", "कर्नाटक", "उत्तर कन्नड़", "मोहम्मद ज़बरूद खतीब", " "},
        {"Karnataka", "Uttara Kannada", "Nagraj Shridhar Shet", "4", " ", "कर्नाटक", "उत्तर कन्नड़", "नागराज श्रीधर शेट", " "},
        {"Karnataka", "Uttara Kannada", "Nagaraj Naik", "2", " ", "कर्नाटक", "उत्तर कन्नड़", "नागराज नाइक", " "},
        {"Karnataka", "Uttara Kannada", "Anita Ashok Shet", "4", " ", "कर्नाटक", "उत्तर कन्नड़", "अनीता अशोक शेट", " "},
        {"Karnataka", "Uttara Kannada", "Chidanand Harijan", "4", " ", "कर्नाटक", "उत्तर कन्नड़", "चिदानंद हरिजन", " "},
        {"Karnataka", "Uttara Kannada", "Anantkumar Hegde", "1", " ", "कर्नाटक", "उत्तर कन्नड़", "अनंतकुमार हेगड़े", " "},
};

}