/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Karnataka {
public static final String[][] green_bucket = {
{"Karnataka",  "3917", "Bangalore Central", "Srinivasan R", "Indian Christian Front", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7382",  "",  "", "", "", ""}, 
{"Karnataka",  "3918", "Bangalore Central", "Kempurajan", "Republican Sena", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7380",  "",  "", "", "", ""}, 
{"Karnataka",  "3920", "Bangalore Central", "Francis Binny Jose", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7374",  "",  "", "", "", ""}, 
{"Karnataka",  "3924", "Bangalore Central", "Pradeep Mendonca", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7291",  "",  "", "", "", ""}, 
{"Karnataka",  "3928", "Bangalore Central", "M.K. Pasha", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7287",  "",  "", "", "", ""}, 
{"Karnataka",  "3929", "Bangalore Central", "Syed Asif Bukhari", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7292",  "",  "", "", "", ""}, 
{"Karnataka",  "3931", "Bangalore Central", "Raparti Anil Kumar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7372",  "",  "", "", "", ""}, 
{"Karnataka",  "3932", "Bangalore Central", "Mellegatti Shridevi", "Uttama Prajaakeeya Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7286",  "",  "", "", "", ""}, 
{"Karnataka",  "3935", "Bangalore Central", "Hunsur K. Chandrashekar", "Democratic Prajakranthi Party Secularist", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7381",  "",  "", "", "", ""}, 
{"Karnataka",  "3936", "Bangalore Central", "Jenifar J. Russell", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7305",  "",  "", "", "", ""}, 
{"Karnataka",  "3937", "Bangalore Central", "S. Mohan Kumar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7294",  "",  "", "", "", ""}, 
{"Karnataka",  "3888", "Bangalore North", "Vinay Kumar V.Nayak", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7349",  "",  "", "", "", ""}, 
{"Karnataka",  "3891", "Bangalore North", "Syed Hydri Babloo", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7344",  "",  "", "", "", ""}, 
{"Karnataka",  "3892", "Bangalore North", "Umesh Babu Pillegowda", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7340",  "",  "", "", "", ""}, 
{"Karnataka",  "3893", "Bangalore North", "Prasanna Kumar Iyengar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7351",  "",  "", "", "", ""}, 
{"Karnataka",  "3895", "Bangalore North", "Parameshwar Gowda", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7354",  "",  "", "", "", ""}, 
{"Karnataka",  "3900", "Bangalore North", "Dr. Meer Layaq Hussain", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7342",  "",  "", "", "", ""}, 
{"Karnataka",  "3903", "Bangalore North", "Shiva Manjesh K.S.", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7337",  "",  "", "", "", ""}, 
{"Karnataka",  "3905", "Bangalore North", "Sumatha K.S.", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7366",  "",  "", "", "", ""}, 
{"Karnataka",  "3907", "Bangalore North", "Tulasappa K Dasar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7347",  "",  "", "", "", ""}, 
{"Karnataka",  "3911", "Bangalore North", "Krishna Murthy V .", "Right to Recall Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7360",  "",  "", "", "", ""}, 
{"Karnataka",  "3915", "Bangalore North", "Abdul Karim Hashimpeer Desai", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7346",  "",  "", "", "", ""}, 
{"Karnataka",  "3873", "Bangalore Rural", "Dr Chinnappa Y Chikkahagade", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7322",  "",  "", "", "", ""}, 
{"Karnataka",  "3874", "Bangalore Rural", "Dr. M Venkataswamy", "RPI(A)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7325",  "",  "", "", "", ""}, 
{"Karnataka",  "3877", "Bangalore Rural", "Rama T C", "SUCI(C)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5159",  "",  "", "", "", ""}, 
{"Karnataka",  "3879", "Bangalore Rural", "Raghu Janagere", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7318",  "",  "", "", "", ""}, 
{"Karnataka",  "3941", "Bangalore South", "Manohar Iyer", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7689",  "",  "", "", "", ""}, 
{"Karnataka",  "3942", "Bangalore South", "Dr. Banuprakash A.S", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5164",  "",  "", "", "", ""}, 
{"Karnataka",  "3943", "Bangalore South", "B.Sreenivasulu", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7695",  "",  "", "", "", ""}, 
{"Karnataka",  "3948", "Bangalore South", "A.Raju", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7682",  "",  "", "", "", ""}, 
{"Karnataka",  "3949", "Bangalore South", "Ravikumara.T", "Pragatishil Samajwadi Party (Lohia)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7677",  "",  "", "", "", ""}, 
{"Karnataka",  "3950", "Bangalore South", "Ambrose D Mello", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5161",  "",  "", "", "", ""}, 
{"Karnataka",  "3956", "Bangalore South", "Chetan Chaman", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7705",  "",  "", "", "", ""}, 
{"Karnataka",  "3957", "Bangalore South", "K.C.Nagabhushana Reddy", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5166",  "",  "", "", "", ""}, 
{"Karnataka",  "3960", "Bangalore South", "Prashantha.C", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7681",  "",  "", "", "", ""},
        {"Karnataka", "3736", "Belgaum", "Sandeep Vasant Lad", "IND", "http://myneta.info/ls2014/candidate.php?candidate_id=10585", "", "", "", "", ""},
        {"Karnataka", "3746", "Belgaum", "Niteen Dhondiba Anandache", "IND", "http://myneta.info/ls2014/candidate.php?candidate_id=10577", "", "", "", "", ""},
        {"Karnataka", "3752", "Belgaum", "Anand Ramesh Patil", "IND", "http://myneta.info/ls2014/candidate.php?candidate_id=10489", "", "", "", "", ""},
        {"Karnataka", "3861", "Chamarajanagar", "Hanur Nagaraju", "Uttama Prajaakeeya Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7308", "", "", "", "", ""},
{"Karnataka",  "3867", "Chamarajanagar", "Dr Shivakumara", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7311",  "",  "", "", "", ""}, 
{"Karnataka",  "3869", "Chamarajanagar", "Prasanna Kumar B", "Karnataka Praja Party (RaithaParva)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7317",  "",  "", "", "", ""}, 
{"Karnataka",  "3965", "Chikkballapur", "Nagendra Rao Shinde", "Karnataka Jantha Paksha", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7672",  "",  "", "", "", ""}, 
{"Karnataka",  "3967", "Chikkballapur", "Abdulkarim Desai", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7673",  "",  "", "", "", ""}, 
{"Karnataka",  "3788", "Chitradurga", "Niranjana A D Cheelangi", "Ambedkar Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7101",  "",  "", "", "", ""}, 
{"Karnataka",  "3794", "Chitradurga", "D Pennappa Turuvanur", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7881",  "",  "", "", "", ""}, 
{"Karnataka",  "3795", "Chitradurga", "Ramesha V", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7880",  "",  "", "", "", ""}, 
{"Karnataka",  "3797", "Chitradurga", "V S Bhutharaja", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7878",  "",  "", "", "", ""}, 
{"Karnataka",  "3799", "Chitradurga", "Lokesha M K", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7882",  "",  "", "", "", ""}, 
{"Karnataka",  "3801", "Chitradurga", "S Meetyanaik", "Pragatishil Samajwadi Party (Lohia)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7096",  "",  "", "", "", ""}, 
{"Karnataka",  "3803", "Chitradurga", "Arunachalam Y", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5128",  "",  "", "", "", ""}, 
{"Karnataka",  "3779", "Dakshina Kannada", "Venkatesh Bende", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7918",  "",  "", "", "", ""}, 
{"Karnataka",  "3769", "Hassan", "Prajwal R", "JD(S)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4959",  "",  "", "", "", ""}, 
{"Karnataka",  "3978", "Kolar", "Ramanji. R", "Uttama Prajaakeeya Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7280",  "",  "", "", "", ""}, 
{"Karnataka",  "3979", "Kolar", "Dr. Ramesh Babu. V.M.", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8870",  "",  "", "", "", ""}, 
{"Karnataka",  "3980", "Kolar", "Raj Kumaresan. L", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8871",  "",  "", "", "", ""}, 
{"Karnataka",  "3981", "Kolar", "Jayaprasad M.G", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7296",  "",  "", "", "", ""}, 
{"Karnataka",  "3985", "Kolar", "G. Chikkanarayana", "Republican Sena", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7297",  "",  "", "", "", ""}, 
{"Karnataka",  "3986", "Kolar", "N.C. Subbarayappa", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7281",  "",  "", "", "", ""}, 
{"Karnataka",  "3818", "Mandya", "Santhosh Mandya Gowda", "Engineers Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7756",  "",  "", "", "", ""}, 
{"Karnataka",  "3819", "Mandya", "Lingegowda S H", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7746",  "",  "", "", "", ""}, 
{"Karnataka",  "3822", "Mandya", "Nanjundaswamy", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7757",  "",  "", "", "", ""}, 
{"Karnataka",  "3826", "Mandya", "Arvind Premanand", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7755",  "",  "", "", "", ""}, 
{"Karnataka",  "3830", "Mandya", "Sumalatha W/O Darshan K.", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8673",  "",  "", "", "", ""}, 
{"Karnataka",  "3834", "Mandya", "Nikhil Kumaraswamy", "JD(S)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7749",  "",  "", "", "", ""}, 
{"Karnataka",  "3835", "Mandya", "T.K. Dasar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7759",  "",  "", "", "", ""}, 
{"Karnataka",  "3836", "Mandya", "Premakumara .V.V", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7744",  "",  "", "", "", ""}, 
{"Karnataka",  "3840", "Mysore", "K.S.Somasunder", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7718",  "",  "", "", "", ""}, 
{"Karnataka",  "3841", "Mysore", "Alishan. S", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7739",  "",  "", "", "", ""}, 
{"Karnataka",  "3842", "Mysore", "Alagudu Lingaraju", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7713",  "",  "", "", "", ""}, 
{"Karnataka",  "3852", "Mysore", "Sandhya P S", "SUCI(C)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5143",  "",  "", "", "", ""}, 
{"Karnataka",  "3858", "Mysore", "M J Suresh Gowda", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5148",  "",  "", "", "", ""}, 
{"Karnataka",  "3804", "Tumkur", "Kapanigowda", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5133",  "",  "", "", "", ""}, 
{"Karnataka",  "3805", "Tumkur", "Chaya Rajashankar", "Uttama Prajaakeeya Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5131",  "",  "", "", "", ""}, 
{"Karnataka",  "3809", "Tumkur", "Siddaramegowda T. B.", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7828",  "",  "", "", "", ""}, 
{"Karnataka",  "3811", "Tumkur", "K. C. Hanumantharaya", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7812",  "",  "", "", "", ""}, 
{"Karnataka",  "3812", "Tumkur", "K V Srinivas Kalkere", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5135",  "",  "", "", "", ""}, 
{"Karnataka",  "3813", "Tumkur", "Mahalakshmi C. P.", "Ambedkar Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7827",  "",  "", "", "", ""}, 
{"Karnataka",  "3816", "Tumkur", "Prakash. R. A. Jain", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7813",  "",  "", "", "", ""}, 
};

public static final String[][] red_bucket = {
        {"Karnataka", "3754", "Bagalkot", "M Shashikumar Hlepadi", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3916", "Bangalore Central", "Dr. Philip Mariyan", "NotGraduate", " ", "", "", "", " "},
{ "Karnataka",  "3919",  "Bangalore Central", "C. B. K. Rama", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3921",  "Bangalore Central", "S. Pandurangan", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3922",  "Bangalore Central", "Nawaz Dilber", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3923",  "Bangalore Central", "Arun Prasad A", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3925",  "Bangalore Central", "B. Krishna Prasad", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3926",  "Bangalore Central", "Prakash Raj", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3927",  "Bangalore Central", "P. C. Mohan", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3930",  "Bangalore Central", "Rizwan Arshad", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3933",  "Bangalore Central", "C.J. Aditya", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3934",  "Bangalore Central", "A. Christhuraj", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3886",  "Bangalore North", "Santhosh M.", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3887",  "Bangalore North", "C. Ravi Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3889",  "Bangalore North", "K.N. Jagadesh Kumar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3890",  "Bangalore North", "N. Narayana Swamy Navakoti", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3894",  "Bangalore North", "Amirtha Jai Kumar Essac Yesaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3896",  "Bangalore North", "Abdul Basheer", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3897",  "Bangalore North", "Abdul Azeez", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3898",  "Bangalore North", "Kumar L.", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3899",  "Bangalore North", "Venkatesa Setty", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3901",  "Bangalore North", "Krishna Byregowda", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3902",  "Bangalore North", "D.V. Sadananda Gowda", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3904",  "Bangalore North", "Venu M.", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3906",  "Bangalore North", "V. Venkataraju", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3908",  "Bangalore North", "Krishnaiah", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3909",  "Bangalore North", "L. Nagaraj", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3910",  "Bangalore North", "Thimmaraj Gowda (Shenganadu)", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3912",  "Bangalore North", "Ahmed Khan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3913",  "Bangalore North", "Sun Star D.Jairam", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3914",  "Bangalore North", "N.Hanume Gowda", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3871",  "Bangalore Rural", "Ashwathnarayangowda", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3872",  "Bangalore Rural", "M.C. Devaraju", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3875",  "Bangalore Rural", "Venkateshappa", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3876",  "Bangalore Rural", "N. Krishnappa", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3878",  "Bangalore Rural", "D.K. Suresh", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3880",  "Bangalore Rural", "J T Prakash", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3881",  "Bangalore Rural", "H.T. Chikkaraju", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3882",  "Bangalore Rural", "D M Madegowda", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3883",  "Bangalore Rural", "B. Gopal", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3884",  "Bangalore Rural", "Manjunatha M", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3885",  "Bangalore Rural", "Eswara", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3938",  "Bangalore South", "Brahmanand.N", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3939",  "Bangalore South", "Tejasvi Surya", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3940",  "Bangalore South", "Bhagya.S", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3944",  "Bangalore South", "Dr.John Basco Philips", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3945",  "Bangalore South", "G Venkatesh Bhovi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3946",  "Bangalore South", "Vatal Nagaraj", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3947",  "Bangalore South", "Thyagaraj", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3951",  "Bangalore South", "Syed Sadiq Pasha", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3952",  "Bangalore South", "Yogeesh Nagaraj", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3953",  "Bangalore South", "B.Chikka Nagesha", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3954",  "Bangalore South", "Kollur Manjunatha Naik", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3955",  "Bangalore South", "Madesh.V", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3958",  "Bangalore South", "Santhosh Min B", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3959",  "Bangalore South", "B.K.Hariprasad", "ForeignFunding",  " ","",  "", "", " "},
        {"Karnataka", "3723", "Belgaum", "Shrikant Balkrishna Kadam", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3724", "Belgaum", "Nanda Maruti Kodachwadkar", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3725", "Belgaum", "Buland Deepak Dalavi", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3726", "Belgaum", "Pandurang Mallappa Pattan", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3727", "Belgaum", "Raju Changappa Divatage", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3728", "Belgaum", "Lakshmanarav Melage", "OverAged", " ", "", "", "", " "},
        {"Karnataka", "3729", "Belgaum", "Sanjay Kamble", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3730", "Belgaum", "Maruti Siddappa Chougule", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3731", "Belgaum", "Prakash Balappa Nesarkar", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3732", "Belgaum", "Kavita Deepak Kole", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3733", "Belgaum", "Prabhakar Bhujang Patil", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3734", "Belgaum", "Ranjit Kallappa Patil", "CriminalCases", " ", "", "", "", " "},
        {"Karnataka", "3735", "Belgaum", "Dhananjay Rajaram Patil", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3737", "Belgaum", "Nagesh Subhash Bobate", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3738", "Belgaum", "Ashutosh Shashikant Kamble", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3739", "Belgaum", "Pranam Prakash Patil", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3740", "Belgaum", "Ramchandra Dattoba Patil", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3741", "Belgaum", "Megharaj Shivagoudappa Khanagoudar", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3742", "Belgaum", "Sachin Manohar Nikam", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3743", "Belgaum", "Krishnakant Kamanna Birje", "OverAged", " ", "", "", "", " "},
        {"Karnataka", "3744", "Belgaum", "Ramchandra Krishna Gaonkar", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3745", "Belgaum", "Rajendra Yallappa Patil", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3747", "Belgaum", "Kallappa Krishnappa Kowadkar", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3748", "Belgaum", "Onkarsingh C Bhatia", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3749", "Belgaum", "Sachin Shantaram Kelavekar", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3750", "Belgaum", "Gopal Balavantrao Desai", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3751", "Belgaum", "Laxman Bhimarao Dalavi", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3753", "Belgaum", "Neelkanth Mahadev Patil", "NotGraduate", " ", "", "", "", " "},
        {"Karnataka", "3862", "Chamarajanagar", "Subbaiah", "NotGraduate", " ", "", "", "", " "},
{ "Karnataka",  "3863",  "Chamarajanagar", "G.D. Rajagopal", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3864",  "Chamarajanagar", "R Dhruvanarayana", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3865",  "Chamarajanagar", "N Ambarish", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3866",  "Chamarajanagar", "V Srinivas Prasad", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3868",  "Chamarajanagar", "Anand Jivan Ram", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3870",  "Chamarajanagar", "M Pradeep Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3961",  "Chikkballapur", "Nalina.K.S", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3962",  "Chikkballapur", "Muniraju.G", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3963",  "Chikkballapur", "L. Nagaraj", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3964",  "Chikkballapur", "M.Veerappa Moily", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3966",  "Chikkballapur", "Dr. C.S.Dwarakanath", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3968",  "Chikkballapur", "Phaniraj.S.V", "NotGraduate",  " ","",  "", "", " "},
        {"Karnataka", "3969", "Chikkballapur", "Nasrulla", "NotGraduate", " ", "", "", "", " "},
{ "Karnataka",  "3970",  "Chikkballapur", "D.Palya Khadar Subhan Khan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3971",  "Chikkballapur", "S.Varalakshmi", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3972",  "Chikkballapur", "S.R.Nageshareddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3973",  "Chikkballapur", "Nazir Ahmed", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3974",  "Chikkballapur", "Alanguru Kanakalakshmi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3975",  "Chikkballapur", "B.N.Bache Gowda", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3722",  "Chikkodi", "Appasaheb Shripati Kurane", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3786",  "Chitradurga", "L Venugopal", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3787",  "Chitradurga", "R Hanumanthappa", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3789",  "Chitradurga", "A Narayanaswamy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3790",  "Chitradurga", "Ganesh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3791",  "Chitradurga", "Kumar Y", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3792",  "Chitradurga", "B N Chandrappa", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3793",  "Chitradurga", "C H Narayanaswamy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3796",  "Chitradurga", "L Rangappa", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3798",  "Chitradurga", "Thippeswamy T", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3800",  "Chitradurga", "Devendrappa", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3802",  "Chitradurga", "Mahanthesh C U", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3773",  "Dakshina Kannada", "Mohammad Khalid", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3774",  "Dakshina Kannada", "Mohammed Eliyas", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3775",  "Dakshina Kannada", "H. Suresh Poojary", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3776",  "Dakshina Kannada", "Abdul Hameed", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3777",  "Dakshina Kannada", "Nalin Kumar Kateel", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3778",  "Dakshina Kannada", "Alexander", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3780",  "Dakshina Kannada", "Mithun M Rai", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3781",  "Dakshina Kannada", "Supreeth Kumar Poojary", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3782",  "Dakshina Kannada", "S. Sathish Saliyan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3783",  "Dakshina Kannada", "Vijay Shreenivas C", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3784",  "Dakshina Kannada", "Deepak Rajesh Coelho", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3785",  "Dakshina Kannada", "Maxim Pinto", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3767",  "Hassan", "Vinodraj K H", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3768",  "Hassan", "H M Chandregowda", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3770",  "Hassan", "M. Mahesh (Al: Lokesh)", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3771",  "Hassan", "Manju A", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3772",  "Hassan", "R G Sathisha", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3976",  "Kolar", "K.H. Muniyappa", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3977",  "Kolar", "S. Muniswamy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3982",  "Kolar", "Medihala Chalavadi M Chandrashekar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3983",  "Kolar", "C. Shankarappa", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3984",  "Kolar", "Sarvesh N.M.", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3987",  "Kolar", "Ashok Chakravarthi M.B", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3988",  "Kolar", "Dhanamatnalli Venkateshappa", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3989",  "Kolar", "Munirajappa. P", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3820",  "Mandya", "M.L. Shashikumar", "NotGraduate",  " ","",  "", "", " "},
        {"Karnataka", "3821", "Mandya", "H.Narayana", "NotGraduate", " ", "", "", "", " "},
{ "Karnataka",  "3823",  "Mandya", "C. Lingegowda", "OverAged",  " ","",  "", "", " "},
        {"Karnataka", "3824", "Mandya", "G. Manjunath", "NotGraduate", " ", "", "", "", " "},
{ "Karnataka",  "3825",  "Mandya", "D C Jayashankara", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3827",  "Mandya", "Gurulingaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3828",  "Mandya", "Sumalatha Ambareesh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3829",  "Mandya", "Satheesh Kumar .T.N", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3831",  "Mandya", "Manjunath B", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3832",  "Mandya", "Kowdle Channappa", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3833",  "Mandya", "C.P. Divakar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3837",  "Mandya", "M. Sumalatha", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3838",  "Mandya", "Sumalatha", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3843",  "Mysore", "C.H.Vijayashankar", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3844",  "Mysore", "Anand Kumar. M", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3845",  "Mysore", "Asharani V", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3846",  "Mysore", "R. Mahesha", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3847",  "Mysore", "Kaveriamma.N.K.", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3848",  "Mysore", "Lokesh Kumar.G.", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3849",  "Mysore", "Dr. B. Chandra (Chandregowda)", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3850",  "Mysore", "Prathap Simha", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3851",  "Mysore", "Ayub Khan", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3853",  "Mysore", "Raju S/O Late Chaluvashetty", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3854",  "Mysore", "Venkatesha D Nayaka", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3855",  "Mysore", "Ravi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3856",  "Mysore", "Ningappa B D", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3857",  "Mysore", "N. Nagesh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3859",  "Mysore", "G.M. Mahadeva", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3860",  "Mysore", "P.K. Biddappa", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3839",  "Mysore", "Srinivasaiah", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3806",  "Tumkur", "T. N. Kumara Swamy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3807",  "Tumkur", "H. D. Devegowda", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3808",  "Tumkur", "B. S. Mallikarjunaiah", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3810",  "Tumkur", "J. K. Sami", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3814",  "Tumkur", "G S Basavaraj", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3815",  "Tumkur", "D Sharadhishayana", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3817",  "Tumkur", "G Nagendra", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3755",  "Udupi Chikmagalur", "Maggalamakki Ganesh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3756",  "Udupi Chikmagalur", "Shekar Havanje", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3757",  "Udupi Chikmagalur", "Shobha Karandlaje", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Karnataka",  "3758",  "Udupi Chikmagalur", "Amrith Shenoy P", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3759",  "Udupi Chikmagalur", "Suresh Kunder", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3760",  "Udupi Chikmagalur", "Abdul Rahman", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3761",  "Udupi Chikmagalur", "Pramod Madhwaraj", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3762",  "Udupi Chikmagalur", "P. Goutham Prabhu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3763",  "Udupi Chikmagalur", "M.K Dayananda", "OverAged",  " ","",  "", "", " "}, 
{ "Karnataka",  "3764",  "Udupi Chikmagalur", "K.C. Prakash", "NotGraduate",  " ","",  "", "", " "}, 
{ "Karnataka",  "3765",  "Udupi Chikmagalur", "P. Parameshwara", "CriminalCases",  " ","",  "", "", " "}, 
{ "Karnataka",  "3766",  "Udupi Chikmagalur", "Comrade Vijaykumar", "NotGraduate",  " ","",  "", "", " "}, 
};

}