/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Karnataka {
public static final String[][] green_bucket = {
{"Karnataka",  "7080", "Bagalkot", "Mahmad Husen Mujawar", "Bahujan Samaj Party", "50000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10491",  "कर्नाटक",  "बागलकोट", "महमद हुसैन मुजावर", "बहुजन समाज पार्टी", ""}, 
{"Karnataka",  "7083", "Bagalkot", "Jamindar Maruti", "Karnataka Jantha Paksha", "25Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10493",  "कर्नाटक",  "बागलकोट", "जमींदार मारुति", "कर्नाटक जंथा पक्ष", ""}, 
{"Karnataka",  "7087", "Bagalkot", "Ramanagoud S Balawad", "Hindustan Janta Party", "2.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7026",  "कर्नाटक",  "बागलकोट", "रमनगौड एस बालावाद", "हिंदुस्तान जनता पार्टी", ""}, 
{"Karnataka",  "7090", "Bagalkot", "Shivarajkumar Ajjappa Talawar", "Independent", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10498",  "कर्नाटक",  "बागलकोट", "शिवराजकुमार अजप्पा तलावर", "निर्दलीय", ""}, 
{"Karnataka",  "7092", "Bagalkot", "Pendari Buddesab Makabulsab", "Independent", "5.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10496",  "कर्नाटक",  "बागलकोट", "पेंडारी बुदेसब मकबुलसब", "निर्दलीय", ""}, 
{"Karnataka",  "3917", "Bangalore Central", "Srinivasan R", "Indian Christian Front", "7.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7382",  "कर्नाटक",  "बैंगलोर सेंट्रल", "श्रीनिवासन आर", "भारतीय ईसाई मोर्चा", ""}, 
{"Karnataka",  "3918", "Bangalore Central", "Kempurajan", "Republican Sena", "41000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7380",  "कर्नाटक",  "बैंगलोर सेंट्रल", "Kempurajan", "रिपब्लिकन सेना", ""}, 
{"Karnataka",  "3920", "Bangalore Central", "Francis Binny Jose", "Independent", "6.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7374",  "कर्नाटक",  "बैंगलोर सेंट्रल", "फ्रांसिस बिन्नी जोस", "निर्दलीय", ""}, 
{"Karnataka",  "3924", "Bangalore Central", "Pradeep Mendonca", "Independent", "58.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7291",  "कर्नाटक",  "बैंगलोर सेंट्रल", "प्रदीप मेंडोंका", "निर्दलीय", ""}, 
{"Karnataka",  "3928", "Bangalore Central", "M.K. Pasha", "Bahujan Samaj Party", "31000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7287",  "कर्नाटक",  "बैंगलोर सेंट्रल", "एमके पाशा", "बहुजन समाज पार्टी", ""}, 
{"Karnataka",  "3929", "Bangalore Central", "Syed Asif Bukhari", "Independent", "3.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7292",  "कर्नाटक",  "बैंगलोर सेंट्रल", "सैयद आसिफ बुखारी", "निर्दलीय", ""}, 
{"Karnataka",  "3931", "Bangalore Central", "Raparti Anil Kumar", "Independent", "12.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7372",  "कर्नाटक",  "बैंगलोर सेंट्रल", "राप्ती अनिल कुमार", "निर्दलीय", ""}, 
{"Karnataka",  "3932", "Bangalore Central", "Mellegatti Shridevi", "Uttama Prajaakeeya Party", "16.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7286",  "कर्नाटक",  "बैंगलोर सेंट्रल", "मेलिगेट्टी श्रीदेवी", "उत्तम प्रजाकेय पार्टी", ""}, 
{"Karnataka",  "3935", "Bangalore Central", "Hunsur K. Chandrashekar", "Democratic Prajakranthi Party Secularist", "63.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7381",  "कर्नाटक",  "बैंगलोर सेंट्रल", "हुंसुर के। चंद्रशेखर", "डेमोक्रेटिक प्रजाक्रांति पार्टी सेकुलरवादी", ""}, 
{"Karnataka",  "3936", "Bangalore Central", "Jenifar J. Russell", "Independent", "51.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7305",  "कर्नाटक",  "बैंगलोर सेंट्रल", "जेनिफर जे। रसेल", "निर्दलीय", ""}, 
{"Karnataka",  "3937", "Bangalore Central", "S. Mohan Kumar", "Independent", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7294",  "कर्नाटक",  "बैंगलोर सेंट्रल", "एस। मोहन कुमार", "निर्दलीय", ""}, 
{"Karnataka",  "3888", "Bangalore North", "Vinay Kumar V.Nayak", "Independent", "1.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7349",  "कर्नाटक",  "बैंगलोर उत्तर", "विनय कुमार वी। नायक", "निर्दलीय", ""}, 
{"Karnataka",  "3891", "Bangalore North", "Syed Hydri Babloo", "Bahujan Samaj Party", "2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7344",  "कर्नाटक",  "बैंगलोर उत्तर", "सैयद हैदरी बबलू", "बहुजन समाज पार्टी", ""}, 
{"Karnataka",  "3892", "Bangalore North", "Umesh Babu Pillegowda", "Independent", "8.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7340",  "कर्नाटक",  "बैंगलोर उत्तर", "उमेश बाबू पिल्लगौड़ा", "निर्दलीय", ""}, 
{"Karnataka",  "3893", "Bangalore North", "Prasanna Kumar Iyengar", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7351",  "कर्नाटक",  "बैंगलोर उत्तर", "प्रसन्ना कुमार अयंगर", "निर्दलीय", ""}, 
{"Karnataka",  "3895", "Bangalore North", "Parameshwar Gowda", "Independent", "3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7354",  "कर्नाटक",  "बैंगलोर उत्तर", "परमेश्वर गौड़ा", "निर्दलीय", ""}, 
{"Karnataka",  "3900", "Bangalore North", "Dr. Meer Layaq Hussain", "Independent", "20000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7342",  "कर्नाटक",  "बैंगलोर उत्तर", "डॉ। मीर लयाक हुसैन", "निर्दलीय", ""}, 
{"Karnataka",  "3903", "Bangalore North", "Shiva Manjesh K.S.", "Independent", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7337",  "कर्नाटक",  "बैंगलोर उत्तर", "शिव मंजेश के.एस.", "निर्दलीय", ""}, 
{"Karnataka",  "3905", "Bangalore North", "Sumatha K.S.", "Independent", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7366",  "कर्नाटक",  "बैंगलोर उत्तर", "सुमाथा के.एस.", "निर्दलीय", ""}, 
{"Karnataka",  "3907", "Bangalore North", "Tulasappa K Dasar", "Independent", "30.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7347",  "कर्नाटक",  "बैंगलोर उत्तर", "तुलसप्पा के दसर", "निर्दलीय", ""}, 
{"Karnataka",  "3911", "Bangalore North", "Krishna Murthy V .", "Right to Recall Party", "61.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7360",  "कर्नाटक",  "बैंगलोर उत्तर", "कृष्ण मूर्ति वी।", "राइट टू रिकॉल पार्टी", ""}, 
{"Karnataka",  "3915", "Bangalore North", "Abdul Karim Hashimpeer Desai", "Independent", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7346",  "कर्नाटक",  "बैंगलोर उत्तर", "अब्दुल करीम हाशिमपीर देसाई", "निर्दलीय", ""}, 
{"Karnataka",  "3873", "Bangalore Rural", "Dr Chinnappa Y Chikkahagade", "Bahujan Samaj Party", "88.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7322",  "कर्नाटक",  "बैंगलोर ग्रामीण", "डॉ। चिन्नाप्पा वाई चिक्काहागड़े", "बहुजन समाज पार्टी", ""}, 
{"Karnataka",  "3874", "Bangalore Rural", "Dr. M Venkataswamy", "Republican Party of India (Athawale)", "6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7325",  "कर्नाटक",  "बैंगलोर ग्रामीण", "डॉ। एम वेंकटस्वामी", "भारतीय रिपब्लिकन पार्टी (अठावले)", ""}, 
{"Karnataka",  "3877", "Bangalore Rural", "Rama T C", "Socialist Unity Centre of India (Communist)", "3.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5159",  "कर्नाटक",  "बैंगलोर ग्रामीण", "रमा टीसी", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Karnataka",  "3879", "Bangalore Rural", "Raghu Janagere", "Independent", "68.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7318",  "कर्नाटक",  "बैंगलोर ग्रामीण", "रघु जनगेरे", "निर्दलीय", ""}, 
{"Karnataka",  "3941", "Bangalore South", "Manohar Iyer", "Independent", "12Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7689",  "कर्नाटक",  "बैंगलोर दक्षिण", "मनोहर अय्यर", "निर्दलीय", ""}, 
{"Karnataka",  "3942", "Bangalore South", "Dr. Banuprakash A.S", "Pyramid Party of India", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5164",  "कर्नाटक",  "बैंगलोर दक्षिण", "डॉ। बानूप्रकाश ए.एस.", "पिरामिड पार्टी ऑफ इंडिया", ""}, 
{"Karnataka",  "3943", "Bangalore South", "B.Sreenivasulu", "Independent", "20.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7695",  "कर्नाटक",  "बैंगलोर दक्षिण", "B.Sreenivasulu", "निर्दलीय", ""}, 
{"Karnataka",  "3948", "Bangalore South", "A.Raju", "Bahujan Samaj Party", "5.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7682",  "कर्नाटक",  "बैंगलोर दक्षिण", "A.Raju", "बहुजन समाज पार्टी", ""}, 
{"Karnataka",  "3949", "Bangalore South", "Ravikumara.T", "Pragatishil Samajwadi Party (Lohia)", "13.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7677",  "कर्नाटक",  "बैंगलोर दक्षिण", "Ravikumara.T", "प्रगति समाजवादी पार्टी (लोहिया)", ""}, 
{"Karnataka",  "3950", "Bangalore South", "Ambrose D Mello", "Independent", "70000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5161",  "कर्नाटक",  "बैंगलोर दक्षिण", "एम्ब्रोस डी मेलो", "निर्दलीय", ""}, 
{"Karnataka",  "3956", "Bangalore South", "Chetan Chaman", "Independent", "14.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7705",  "कर्नाटक",  "बैंगलोर दक्षिण", "चेतन चमन", "निर्दलीय", ""}, 
{"Karnataka",  "3957", "Bangalore South", "K.C.Nagabhushana Reddy", "Independent", "16Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5166",  "कर्नाटक",  "बैंगलोर दक्षिण", "केसी नागभूषण रेड्डी", "निर्दलीय", ""}, 
{"Karnataka",  "3960", "Bangalore South", "Prashantha.C", "Independent", "1.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7681",  "कर्नाटक",  "बैंगलोर दक्षिण", "Prashantha.C", "निर्दलीय", ""}, 
{"Karnataka",  "7056", "Belgaum", "Uday Naik", "Independent", "4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10479",  "कर्नाटक",  "बेलगाम", "उदय नाइक", "निर्दलीय", ""}, 
{"Karnataka",  "7060", "Belgaum", "Shankar Chogule", "Independent", "35.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10587",  "कर्नाटक",  "बेलगाम", "शंकर चौगुले", "निर्दलीय", ""}, 
{"Karnataka",  "7062", "Belgaum", "Suresh Basappa Maralingannavar", "Independent", "15.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10591",  "कर्नाटक",  "बेलगाम", "सुरेश बसप्पा मरलिंगनवर", "निर्दलीय", ""}, 
{"Karnataka",  "3736", "Belgaum", "Sandeep Vasant Lad", "Independent", "2.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10585",  "कर्नाटक",  "बेलगाम", "संदीप वसंत लाड", "निर्दलीय", ""}, 
{"Karnataka",  "7066", "Belgaum", "Badaroddin Mohammadyusuf Kamdod", "Bahujan Samaj Party", "1.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10490",  "कर्नाटक",  "बेलगाम", "बद्रोद्दीन मोहम्मदिसुफ़ कामदोद", "बहुजन समाज पार्टी", ""}, 
{"Karnataka",  "7067", "Belgaum", "Manjunath Rajappanavar", "Uttama Prajaakeeya Party", "22.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7024",  "कर्नाटक",  "बेलगाम", "मंजूनाथ राजप्पनवर", "उत्तम प्रजाकेय पार्टी", ""}, 
{"Karnataka",  "7069", "Belgaum", "Vijay Laxman Patil", "Independent", "67.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9121",  "कर्नाटक",  "बेलगाम", "विजय लक्ष्मण पाटिल", "निर्दलीय", ""}, 
{"Karnataka",  "7070", "Belgaum", "Vijay Krishna Madar", "Independent", "3.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10488",  "कर्नाटक",  "बेलगाम", "विजय कृष्ण मदार", "निर्दलीय", ""}, 
{"Karnataka",  "7071", "Belgaum", "Chetak Kumar Yallappa Kamble", "Independent", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10476",  "कर्नाटक",  "बेलगाम", "चेतक कुमार यलप्पा कांबले", "निर्दलीय", ""}, 
{"Karnataka",  "3746", "Belgaum", "Niteen Dhondiba Anandache", "Independent", "5.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10577",  "कर्नाटक",  "बेलगाम", "नितेन धोंडिबा आनंदके", "निर्दलीय", ""}, 
{"Karnataka",  "7074", "Belgaum", "Suresh Khemanna Rajukar", "Independent", "4.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10592",  "कर्नाटक",  "बेलगाम", "सुरेश खेमना राजुकर", "निर्दलीय", ""}, 
{"Karnataka",  "7075", "Belgaum", "Sunil Guddakayu", "Independent", "74.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10590",  "कर्नाटक",  "बेलगाम", "सुनील गुड्डाकायु", "निर्दलीय", ""}, 
{"Karnataka",  "7079", "Belgaum", "Uday Ramappa Kundargi", "Independent", "3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10470",  "कर्नाटक",  "बेलगाम", "उदय रामप्पा कुंदरगी", "निर्दलीय", ""}, 
{"Karnataka",  "3752", "Belgaum", "Anand Ramesh Patil", "Independent", "8.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10489",  "कर्नाटक",  "बेलगाम", "आनंद रमेश पाटिल", "निर्दलीय", ""}, 
{"Karnataka",  "7157", "Bellary", "Nayakara Ramappa", "Indian Labour Party (Ambedkar Phule)", "9.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10450",  "कर्नाटक",  "बेल्लारी", "नायकरा रामप्पा", "भारतीय मजदूर पार्टी (अम्बेडकर फुले)", ""}, 
{"Karnataka",  "7159", "Bellary", "Naveen Kumar. S", "Bharat Prabhat Party", "8.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10449",  "कर्नाटक",  "बेल्लारी", "नवीन कुमार। एस", "भारत प्रभात पार्टी", ""}, 
{"Karnataka",  "7129", "Bidar", "Rajkumar", "Purvanchal Janta Party (Secular)", "11.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10461",  "कर्नाटक",  "बीदर", "राजकुमार", "पूर्वांचल जनता पार्टी (सेक्युलर)", ""}, 
{"Karnataka",  "7130", "Bidar", "Maulappa", "Independent", "28.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7261",  "कर्नाटक",  "बीदर", "Maulappa", "निर्दलीय", ""}, 
{"Karnataka",  "7132", "Bidar", "Shaik Abdul Gaffar", "Independent", "3.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10468",  "कर्नाटक",  "बीदर", "शैक अब्दुल गफ्फार", "निर्दलीय", ""}, 
{"Karnataka",  "7133", "Bidar", "Ambresh Kencha", "Uttama Prajaakeeya Party", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7038",  "कर्नाटक",  "बीदर", "अंबरीश केंचा", "उत्तम प्रजाकेय पार्टी", ""}, 
{"Karnataka",  "7139", "Bidar", "Saibanna", "Independent", "7.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7260",  "कर्नाटक",  "बीदर", "Saibanna", "निर्दलीय", ""}, 
{"Karnataka",  "7140", "Bidar", "Maulasab", "Independent", "15.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10464",  "कर्नाटक",  "बीदर", "Maulasab", "निर्दलीय", ""}, 
{"Karnataka",  "7141", "Bidar", "Ravi", "Independent", "83.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7256",  "कर्नाटक",  "बीदर", "रवि", "निर्दलीय", ""}, 
{"Karnataka",  "7096", "Bijapur", "Dhareppa Mahadev Ardhavar", "Independent", "32.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10443",  "कर्नाटक",  "बीजापुर", "ध्रप्पा महादेव अर्धवर", "निर्दलीय", ""}, 
{"Karnataka",  "7098", "Bijapur", "Dr. Sunita Devanand Chavan", "Janata Dal (Secular)", "4.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10439",  "कर्नाटक",  "बीजापुर", "डॉ। सुनीता देवानंद चव्हाण", "जनता दल (सेक्युलर)", ""}, 
{"Karnataka",  "7099", "Bijapur", "Shrivenkateshwar Maha Swamiji", "Hindustan Janta Party", "9", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7029",  "कर्नाटक",  "बीजापुर", "श्रीवेंकटेश्वर महा स्वामीजी", "हिंदुस्तान जनता पार्टी", ""}, 
{"Karnataka",  "7102", "Bijapur", "Rudrappa Deyappa Chalawadi", "Bharipa Bahujan Mahasangh", "41.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10441",  "कर्नाटक",  "बीजापुर", "रुद्रप्पा दयप्पा चलवाडी", "भारिप बहुजन महासंघ", ""}, 
{"Karnataka",  "3861", "Chamarajanagar", "Hanur Nagaraju", "Uttama Prajaakeeya Party", "5.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7308",  "कर्नाटक",  "चामराजनगर", "हनूर नागराजू", "उत्तम प्रजाकेय पार्टी", ""}, 
{"Karnataka",  "3867", "Chamarajanagar", "Dr Shivakumara", "Bahujan Samaj Party", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7311",  "कर्नाटक",  "चामराजनगर", "डॉ। शिवकुमार", "बहुजन समाज पार्टी", ""}, 
{"Karnataka",  "3869", "Chamarajanagar", "Prasanna Kumar B", "Karnataka Praja Party (RaithaParva)", "15.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7317",  "कर्नाटक",  "चामराजनगर", "प्रसन्न कुमार बी", "कर्नाटक प्रजा पार्टी (रायपर्व)", ""}, 
{"Karnataka",  "3965", "Chikkballapur", "Nagendra Rao Shinde", "Karnataka Jantha Paksha", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7672",  "कर्नाटक",  "चिकबल्लपुर", "नागेंद्र राव शिंदे", "कर्नाटक जंथा पक्ष", ""}, 
{"Karnataka",  "3967", "Chikkballapur", "Abdulkarim Desai", "Independent", "86Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7673",  "कर्नाटक",  "चिकबल्लपुर", "अब्दुलकरिम देसाई", "निर्दलीय", ""}, 
{"Karnataka",  "7046", "Chikkodi", "Mohan Gurappa Motannavar", "Independent", "13.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10427",  "कर्नाटक",  "चिक्कोडी", "मोहन गुरप्पा मोटन्नवर", "निर्दलीय", ""}, 
{"Karnataka",  "7047", "Chikkodi", "Praveenkumar Baligatti", "Uttama Prajaakeeya Party", "32000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7021",  "कर्नाटक",  "चिक्कोडी", "प्रवीणकुमार बालीगट्टी", "उत्तम प्रजाकेय पार्टी", ""}, 
{"Karnataka",  "3788", "Chitradurga", "Niranjana A D Cheelangi", "Ambedkar Samaj Party", "4.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7101",  "कर्नाटक",  "चित्रदुर्ग", "निरंजना ई। चेलांगी", "अंबेडकर समाज पार्टी", ""}, 
{"Karnataka",  "3794", "Chitradurga", "D Pennappa Turuvanur", "Independent", "5.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7881",  "कर्नाटक",  "चित्रदुर्ग", "डी पेनप्पा तुरुवनुर", "निर्दलीय", ""}, 
{"Karnataka",  "3795", "Chitradurga", "Ramesha V", "Independent", "24.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7880",  "कर्नाटक",  "चित्रदुर्ग", "रमेश वी", "निर्दलीय", ""}, 
{"Karnataka",  "3797", "Chitradurga", "V S Bhutharaja", "Independent", "7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7878",  "कर्नाटक",  "चित्रदुर्ग", "वीएस भूथराजा", "निर्दलीय", ""}, 
{"Karnataka",  "3799", "Chitradurga", "Lokesha M K", "Independent", "3.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7882",  "कर्नाटक",  "चित्रदुर्ग", "लोकेश एमके", "निर्दलीय", ""}, 
{"Karnataka",  "3801", "Chitradurga", "S Meetyanaik", "Pragatishil Samajwadi Party (Lohia)", "24.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7096",  "कर्नाटक",  "चित्रदुर्ग", "एस मलयानिक", "प्रगति समाजवादी पार्टी (लोहिया)", ""}, 
{"Karnataka",  "3803", "Chitradurga", "Arunachalam Y", "Pyramid Party of India", "16Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5128",  "कर्नाटक",  "चित्रदुर्ग", "अरुणाचलम वाई", "पिरामिड पार्टी ऑफ इंडिया", ""}, 
{"Karnataka",  "3779", "Dakshina Kannada", "Venkatesh Bende", "Independent", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7918",  "कर्नाटक",  "दक्षिण कन्नड़", "वेंकटेश बेंद", "निर्दलीय", ""}, 
{"Karnataka",  "7211", "Davanagere", "Subhan Khan", "Independent", "10.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7272",  "कर्नाटक",  "दावनगेरे", "सुभान खान", "निर्दलीय", ""}, 
{"Karnataka",  "7216", "Davanagere", "Mohamed Hayath", "Independent", "3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10423",  "कर्नाटक",  "दावनगेरे", "मोहम्मद हयात", "निर्दलीय", ""}, 
{"Karnataka",  "7229", "Davanagere", "Madhu T G", "Socialist Unity Centre of India (Communist)", "32.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7053",  "कर्नाटक",  "दावनगेरे", "मधु टीजी", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Karnataka",  "7230", "Davanagere", "Shashikumar R N", "Independent", "21.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10426",  "कर्नाटक",  "दावनगेरे", "शशिकुमार आर.एन.", "निर्दलीय", ""}, 
{"Karnataka",  "7233", "Davanagere", "V Manjunathachar", "Independent", "6.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7052",  "कर्नाटक",  "दावनगेरे", "वी मंजूनाथचर", "निर्दलीय", ""}, 
{"Karnataka",  "7181", "Dharwad", "Gangadhar Badiger", "Socialist Unity Centre of India (Communist)", "95105", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7044",  "कर्नाटक",  "धारवाड़", "गंगाधर बडिगर", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Karnataka",  "7184", "Dharwad", "Santosh Nandur", "Uttama Prajaakeeya Party", "22.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7046",  "कर्नाटक",  "धारवाड़", "संतोष नंदूर", "उत्तम प्रजाकेय पार्टी", ""}, 
{"Karnataka",  "7190", "Dharwad", "Raju Harishchandra Kamble", "Azad Mazdoor Kissan Party", "79835", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10411",  "कर्नाटक",  "धारवाड़", "राजू हरिश्चंद्र कांबले", "आजाद मजदूर किसन पार्टी", ""}, 
{"Karnataka",  "7191", "Dharwad", "B. G. Sangannavar", "Independent", "22.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10414",  "कर्नाटक",  "धारवाड़", "बीजी सांगनावार", "निर्दलीय", ""}, 
{"Karnataka",  "7195", "Dharwad", "Makhtum Khan Hasanalikhan Sirdesai", "Independent", "6.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10415",  "कर्नाटक",  "धारवाड़", "मखमत खान हसनलीखान सिरदेसाई", "निर्दलीय", ""}, 
{"Karnataka",  "7110", "Gulbarga", "Mahesh Lambani", "Uttama Prajaakeeya Party", "38000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7032",  "कर्नाटक",  "गुलबर्गा", "महेश लाम्बानी", "उत्तम प्रजाकेय पार्टी", ""}, 
{"Karnataka",  "7112", "Gulbarga", "D. K. Konkate Keroor", "Rashtriya Samaj Paksha", "11.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7252",  "कर्नाटक",  "गुलबर्गा", "डीके कोंकते करूर", "राष्ट्रीय समाज पक्ष", ""}, 
{"Karnataka",  "7115", "Gulbarga", "Dr. M. P. Darakeshwaraiah", "Independent", "31.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10405",  "कर्नाटक",  "गुलबर्गा", "डॉ। एमपी दरकेश्वरैया", "निर्दलीय", ""}, 
{"Karnataka",  "3769", "Hassan", "Prajwal R", "Janata Dal (Secular)", "9.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4959",  "कर्नाटक",  "हसन", "प्रज्वल आर", "जनता दल (सेक्युलर)", ""}, 
{"Karnataka",  "7174", "Haveri", "Shylesh Nazare Ashok", "Indian Labour Party (Ambedkar Phule)", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10395",  "कर्नाटक",  "हावेरी", "शैलेश नज़रे अशोक", "भारतीय मजदूर पार्टी (अम्बेडकर फुले)", ""}, 
{"Karnataka",  "7176", "Haveri", "Ayubakhan A Pathan", "Bahujan Samaj Party", "65.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10392",  "कर्नाटक",  "हावेरी", "अयूबखान ए पठान", "बहुजन समाज पार्टी", ""}, 
{"Karnataka",  "3978", "Kolar", "Ramanji. R", "Uttama Prajaakeeya Party", "86500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7280",  "कर्नाटक",  "कोलार", "Ramanji। आर", "उत्तम प्रजाकेय पार्टी", ""}, 
{"Karnataka",  "3979", "Kolar", "Dr. Ramesh Babu. V.M.", "Independent", "14.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8870",  "कर्नाटक",  "कोलार", "डॉ। रमेश बाबू वीएम", "निर्दलीय", ""}, 
{"Karnataka",  "3980", "Kolar", "Raj Kumaresan. L", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8871",  "कर्नाटक",  "कोलार", "राज कुमारसन। एल", "निर्दलीय", ""}, 
{"Karnataka",  "3981", "Kolar", "Jayaprasad M.G", "Bahujan Samaj Party", "4.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7296",  "कर्नाटक",  "कोलार", "जयप्रसाद एम.जी.", "बहुजन समाज पार्टी", ""}, 
{"Karnataka",  "3985", "Kolar", "G. Chikkanarayana", "Republican Sena", "9.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7297",  "कर्नाटक",  "कोलार", "जी। चिकनकारायण", "रिपब्लिकन सेना", ""}, 
{"Karnataka",  "3986", "Kolar", "N.C. Subbarayappa", "Independent", "6.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7281",  "कर्नाटक",  "कोलार", "NC सुब्बारायप्पा", "निर्दलीय", ""}, 
{"Karnataka",  "7150", "Koppal", "Satishreddy", "Independent", "82000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10390",  "कर्नाटक",  "कोप्पल", "Satishreddy", "निर्दलीय", ""}, 
{"Karnataka",  "7151", "Koppal", "Suresh.H", "Independent", "1.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10391",  "कर्नाटक",  "कोप्पल", "Suresh.H", "निर्दलीय", ""}, 
{"Karnataka",  "7152", "Koppal", "Pa.Ya. Ganesh", "Independent", "19Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10386",  "कर्नाटक",  "कोप्पल", "पाया। गणेश", "निर्दलीय", ""}, 
{"Karnataka",  "7155", "Koppal", "Hemaraj Veerapur", "Communist Party of India (Marxist–Leninist) Red Star", "50000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10385",  "कर्नाटक",  "कोप्पल", "हेमराज वीरपुर", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) रेड स्टार", ""}, 
{"Karnataka",  "3818", "Mandya", "Santhosh Mandya Gowda", "Engineers Party", "7.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7756",  "कर्नाटक",  "मंड्या", "संतोष मंड्या गौड़ा", "इंजीनियर्स पार्टी", ""}, 
{"Karnataka",  "3819", "Mandya", "Lingegowda S H", "Independent", "80.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7746",  "कर्नाटक",  "मंड्या", "लिंगेगौड़ा एस.एच.", "निर्दलीय", ""}, 
{"Karnataka",  "3822", "Mandya", "Nanjundaswamy", "Bahujan Samaj Party", "85Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7757",  "कर्नाटक",  "मंड्या", "Nanjundaswamy", "बहुजन समाज पार्टी", ""}, 
{"Karnataka",  "3826", "Mandya", "Arvind Premanand", "Independent", "81Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7755",  "कर्नाटक",  "मंड्या", "अरविंद प्रेमानंद", "निर्दलीय", ""}, 
{"Karnataka",  "3830", "Mandya", "Sumalatha W/O Darshan K.", "Independent", "28.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8673",  "कर्नाटक",  "मंड्या", "सुमलता डब्ल्यू / ओ दर्शन के।", "निर्दलीय", ""}, 
{"Karnataka",  "3834", "Mandya", "Nikhil Kumaraswamy", "Janata Dal (Secular)", "74Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7749",  "कर्नाटक",  "मंड्या", "निखिल कुमारस्वामी", "जनता दल (सेक्युलर)", ""}, 
{"Karnataka",  "3835", "Mandya", "T.K. Dasar", "Independent", "30.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7759",  "कर्नाटक",  "मंड्या", "टीके दसर", "निर्दलीय", ""}, 
{"Karnataka",  "3836", "Mandya", "Premakumara .V.V", "Independent", "1.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7744",  "कर्नाटक",  "मंड्या", "प्रेमकुमार .VV", "निर्दलीय", ""}, 
{"Karnataka",  "3840", "Mysore", "K.S.Somasunder", "Independent", "6.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7718",  "कर्नाटक",  "मैसूर", "KSSomasunder", "निर्दलीय", ""}, 
{"Karnataka",  "3841", "Mysore", "Alishan. S", "Independent", "2.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7739",  "कर्नाटक",  "मैसूर", "Alishan। एस", "निर्दलीय", ""}, 
{"Karnataka",  "3842", "Mysore", "Alagudu Lingaraju", "Independent", "11.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7713",  "कर्नाटक",  "मैसूर", "अलागुडु लिंगराजु", "निर्दलीय", ""}, 
{"Karnataka",  "3852", "Mysore", "Sandhya P S", "Socialist Unity Centre of India (Communist)", "24.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5143",  "कर्नाटक",  "मैसूर", "संध्या पीएस", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Karnataka",  "3858", "Mysore", "M J Suresh Gowda", "Independent", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5148",  "कर्नाटक",  "मैसूर", "एमजे सुरेश गौड़ा", "निर्दलीय", ""}, 
{"Karnataka",  "7118", "Raichur", "Niranjan Nayak", "Uttama Prajaakeeya Party", "13000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10379",  "कर्नाटक",  "रायचूर", "निरंजन नायक", "उत्तम प्रजाकेय पार्टी", ""}, 
{"Karnataka",  "7120", "Raichur", "B. Venkana Gouda Nayaka", "Bahujan Samaj Party", "17.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10378",  "कर्नाटक",  "रायचूर", "बी। वेंकणा गौड़ा नायक", "बहुजन समाज पार्टी", ""}, 
{"Karnataka",  "7242", "Shimoga", "K.C.Vinay Rajavath", "Independent", "18.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10377",  "कर्नाटक",  "शिमोगा", "केसीविनय राजावत", "निर्दलीय", ""}, 
{"Karnataka",  "7244", "Shimoga", "Shekara Naik", "Independent", "4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7054",  "कर्नाटक",  "शिमोगा", "शेखर नाइक", "निर्दलीय", ""}, 
{"Karnataka",  "3804", "Tumkur", "Kapanigowda", "Independent", "13.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5133",  "कर्नाटक",  "तुमकुर", "Kapanigowda", "निर्दलीय", ""}, 
{"Karnataka",  "3805", "Tumkur", "Chaya Rajashankar", "Uttama Prajaakeeya Party", "3.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5131",  "कर्नाटक",  "तुमकुर", "चाया राजशंकर", "उत्तम प्रजाकेय पार्टी", ""}, 
{"Karnataka",  "3809", "Tumkur", "Siddaramegowda T. B.", "Independent", "63Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7828",  "कर्नाटक",  "तुमकुर", "सिद्धारमेगौड़ा टी.बी.", "निर्दलीय", ""}, 
{"Karnataka",  "3811", "Tumkur", "K. C. Hanumantharaya", "Bahujan Samaj Party", "3.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7812",  "कर्नाटक",  "तुमकुर", "केसी हनुमंतराय", "बहुजन समाज पार्टी", ""}, 
{"Karnataka",  "3812", "Tumkur", "K V Srinivas Kalkere", "Independent", "3.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5135",  "कर्नाटक",  "तुमकुर", "केवी श्रीनिवास कालकेरे", "निर्दलीय", ""}, 
{"Karnataka",  "3813", "Tumkur", "Mahalakshmi C. P.", "Ambedkar Samaj Party", "20000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7827",  "कर्नाटक",  "तुमकुर", "महालक्ष्मी सी.पी.", "अंबेडकर समाज पार्टी", ""}, 
{"Karnataka",  "3816", "Tumkur", "Prakash. R. A. Jain", "Independent", "4.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7813",  "कर्नाटक",  "तुमकुर", "प्रकाश। रा जैन", "निर्दलीय", ""}, 
{"Karnataka",  "7200", "Uttara Kannada", "Sunil Pawar", "Uttama Prajaakeeya Party", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7270",  "कर्नाटक",  "उत्तर कन्नड़", "सुनील पवार", "उत्तम प्रजाकेय पार्टी", ""}, 
{"Karnataka",  "7201", "Uttara Kannada", "Balakrishna Arjun Patil", "Independent", "22Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7047",  "कर्नाटक",  "उत्तर कन्नड़", "बालकृष्ण अर्जुन पाटिल", "निर्दलीय", ""}, 
{"Karnataka",  "7204", "Uttara Kannada", "Kundabai Ganapati Parulekar", "Independent", "91.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10370",  "कर्नाटक",  "उत्तर कन्नड़", "कुंदाबाई गणपति पारुलेकर", "निर्दलीय", ""}, 
{"Karnataka",  "7207", "Uttara Kannada", "Manjunath Sadashiv", "Bharat Bhoomi Party", "8.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10369",  "कर्नाटक",  "उत्तर कन्नड़", "मंजूनाथ सदाशिव", "भारतभूमि पार्टी", ""}, 
{"Karnataka",  "7209", "Uttara Kannada", "Sudhakar Kira Jogalekar", "Bahujan Samaj Party", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10366",  "कर्नाटक",  "उत्तर कन्नड़", "सुधाकर किर जोगलेकर", "बहुजन समाज पार्टी", ""}, 
};

public static final String[][] red_bucket = {
{ "Karnataka",  "7081",  "Bagalkot", "Basanagouda Ramanagouda Meti", "NotGraduate",  " ","कर्नाटक",  "बागलकोट", "बसनगौड़ा रामानुगौदा मेटी", " "}, 
{ "Karnataka",  "3754",  "Bagalkot", "M Shashikumar Hlepadi", "NotGraduate",  " ","कर्नाटक",  "बागलकोट", "एम शशिकुमार हेलेपाडी", " "}, 
{ "Karnataka",  "7082",  "Bagalkot", "Gaddigoudar Parvatagouda Chandanagouda", "ForeignFunding",  " ","कर्नाटक",  "बागलकोट", "गद्दीगौदर पार्वतगौड़ा चंदनगौड़ा", " "}, 
{ "Karnataka",  "7084",  "Bagalkot", "Veena Kashappanavar", "ForeignFunding",  " ","कर्नाटक",  "बागलकोट", "वीणा कशप्पनवर", " "}, 
{ "Karnataka",  "7085",  "Bagalkot", "Adagal Rajendra", "NotGraduate",  " ","कर्नाटक",  "बागलकोट", "आदगल राजेंद्र", " "}, 
{ "Karnataka",  "7086",  "Bagalkot", "Muttu S Surakod", "NotGraduate",  " ","कर्नाटक",  "बागलकोट", "मुट्टु एस सुरकोड", " "}, 
{ "Karnataka",  "7088",  "Bagalkot", "Muttappa Mudakappa Hirekumbi", "NotGraduate",  " ","कर्नाटक",  "बागलकोट", "मुत्तप्पा मुदप्पप्पा हिरेकुम्बी", " "}, 
{ "Karnataka",  "7089",  "Bagalkot", "Parashuram Laxman Neelnaik", "CriminalCases",  " ","कर्नाटक",  "बागलकोट", "परशुराम लक्ष्मण नीलाणिक", " "}, 
{ "Karnataka",  "7091",  "Bagalkot", "Ravi Shivappa Padasalagi", "CriminalCases",  " ","कर्नाटक",  "बागलकोट", "रवि शिवप्पा पदासलगी", " "}, 
{ "Karnataka",  "3916",  "Bangalore Central", "Dr. Philip Mariyan", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर सेंट्रल", "डॉ। फिलिप मारियान", " "}, 
{ "Karnataka",  "3919",  "Bangalore Central", "C. B. K. Rama", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर सेंट्रल", "सीबीके राम", " "}, 
{ "Karnataka",  "3921",  "Bangalore Central", "S. Pandurangan", "OverAged",  " ","कर्नाटक",  "बैंगलोर सेंट्रल", "एस। पांडुरंगन", " "}, 
{ "Karnataka",  "3922",  "Bangalore Central", "Nawaz Dilber", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर सेंट्रल", "नवाज दिलबर", " "}, 
{ "Karnataka",  "3923",  "Bangalore Central", "Arun Prasad A", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर सेंट्रल", "अरुण प्रसाद ए", " "}, 
{ "Karnataka",  "3925",  "Bangalore Central", "B. Krishna Prasad", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर सेंट्रल", "बी। कृष्ण प्रसाद", " "}, 
{ "Karnataka",  "3926",  "Bangalore Central", "Prakash Raj", "CriminalCases",  " ","कर्नाटक",  "बैंगलोर सेंट्रल", "प्रकाश राज", " "}, 
{ "Karnataka",  "3927",  "Bangalore Central", "P. C. Mohan", "ForeignFunding",  " ","कर्नाटक",  "बैंगलोर सेंट्रल", "पीसी मोहन", " "}, 
{ "Karnataka",  "3930",  "Bangalore Central", "Rizwan Arshad", "ForeignFunding",  " ","कर्नाटक",  "बैंगलोर सेंट्रल", "रिजवान अरशद", " "}, 
{ "Karnataka",  "3933",  "Bangalore Central", "C.J. Aditya", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर सेंट्रल", "सीजे आदित्य", " "}, 
{ "Karnataka",  "3934",  "Bangalore Central", "A. Christhuraj", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर सेंट्रल", "ए। क्रिसथुराज", " "}, 
{ "Karnataka",  "3886",  "Bangalore North", "Santhosh M.", "CriminalCases",  " ","कर्नाटक",  "बैंगलोर उत्तर", "संतोष एम।", " "}, 
{ "Karnataka",  "3887",  "Bangalore North", "C. Ravi Kumar", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर उत्तर", "सी। रवि कुमार", " "}, 
{ "Karnataka",  "3889",  "Bangalore North", "K.N. Jagadesh Kumar", "CriminalCases",  " ","कर्नाटक",  "बैंगलोर उत्तर", "केएन जगदेश कुमार", " "}, 
{ "Karnataka",  "3890",  "Bangalore North", "N. Narayana Swamy Navakoti", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर उत्तर", "एन। नारायण स्वामी नवकोटि", " "}, 
{ "Karnataka",  "3894",  "Bangalore North", "Amirtha Jai Kumar Essac Yesaiah", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर उत्तर", "अमिरथा जय कुमार एस्सेक यसैया", " "}, 
{ "Karnataka",  "3896",  "Bangalore North", "Abdul Basheer", "OverAged",  " ","कर्नाटक",  "बैंगलोर उत्तर", "अब्दुल बशीर", " "}, 
{ "Karnataka",  "3897",  "Bangalore North", "Abdul Azeez", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर उत्तर", "अब्दुल अज़ीज़", " "}, 
{ "Karnataka",  "3898",  "Bangalore North", "Kumar L.", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर उत्तर", "कुमार एल।", " "}, 
{ "Karnataka",  "3899",  "Bangalore North", "Venkatesa Setty", "OverAged",  " ","कर्नाटक",  "बैंगलोर उत्तर", "वेंकटेश सेट्टी", " "}, 
{ "Karnataka",  "3901",  "Bangalore North", "Krishna Byregowda", "ForeignFunding",  " ","कर्नाटक",  "बैंगलोर उत्तर", "कृष्ण बृजगौड़ा", " "}, 
{ "Karnataka",  "3902",  "Bangalore North", "D.V. Sadananda Gowda", "ForeignFunding",  " ","कर्नाटक",  "बैंगलोर उत्तर", "डीवी सदानंद गौड़ा", " "}, 
{ "Karnataka",  "3904",  "Bangalore North", "Venu M.", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर उत्तर", "वेणु एम।", " "}, 
{ "Karnataka",  "3906",  "Bangalore North", "V. Venkataraju", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर उत्तर", "वी। वेंकटराजू", " "}, 
{ "Karnataka",  "3908",  "Bangalore North", "Krishnaiah", "CriminalCases",  " ","कर्नाटक",  "बैंगलोर उत्तर", "कृष्णैया", " "}, 
{ "Karnataka",  "3909",  "Bangalore North", "L. Nagaraj", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर उत्तर", "एल। नागराज", " "}, 
{ "Karnataka",  "3910",  "Bangalore North", "Thimmaraj Gowda (Shenganadu)", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर उत्तर", "थिमाराज गौड़ा (शेंगनाडु)", " "}, 
{ "Karnataka",  "3912",  "Bangalore North", "Ahmed Khan", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर उत्तर", "अहमद खान", " "}, 
{ "Karnataka",  "3913",  "Bangalore North", "Sun Star D.Jairam", "OverAged",  " ","कर्नाटक",  "बैंगलोर उत्तर", "सन स्टार डी। जयराम", " "}, 
{ "Karnataka",  "3914",  "Bangalore North", "N.Hanume Gowda", "CriminalCases",  " ","कर्नाटक",  "बैंगलोर उत्तर", "एन हनुम गौड़ा", " "}, 
{ "Karnataka",  "3871",  "Bangalore Rural", "Ashwathnarayangowda", "ForeignFunding",  " ","कर्नाटक",  "बैंगलोर ग्रामीण", "Ashwathnarayangowda", " "}, 
{ "Karnataka",  "3872",  "Bangalore Rural", "M.C. Devaraju", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर ग्रामीण", "एमसी देवराजु", " "}, 
{ "Karnataka",  "3875",  "Bangalore Rural", "Venkateshappa", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर ग्रामीण", "Venkateshappa", " "}, 
{ "Karnataka",  "3876",  "Bangalore Rural", "N. Krishnappa", "OverAged",  " ","कर्नाटक",  "बैंगलोर ग्रामीण", "एन। कृष्णप्पा", " "}, 
{ "Karnataka",  "3878",  "Bangalore Rural", "D.K. Suresh", "ForeignFunding",  " ","कर्नाटक",  "बैंगलोर ग्रामीण", "डीके सुरेश", " "}, 
{ "Karnataka",  "3880",  "Bangalore Rural", "J T Prakash", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर ग्रामीण", "जेटी प्रकाश", " "}, 
{ "Karnataka",  "3881",  "Bangalore Rural", "H.T. Chikkaraju", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर ग्रामीण", "एचटी चिककारजू", " "}, 
{ "Karnataka",  "3882",  "Bangalore Rural", "D M Madegowda", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर ग्रामीण", "डीएम मडगौड़ा", " "}, 
{ "Karnataka",  "3883",  "Bangalore Rural", "B. Gopal", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर ग्रामीण", "बी। गोपाल", " "}, 
{ "Karnataka",  "3884",  "Bangalore Rural", "Manjunatha M", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर ग्रामीण", "मंजुनाथ एम", " "}, 
{ "Karnataka",  "3885",  "Bangalore Rural", "Eswara", "OverAged",  " ","कर्नाटक",  "बैंगलोर ग्रामीण", "Eswara", " "}, 
{ "Karnataka",  "3938",  "Bangalore South", "Brahmanand.N", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर दक्षिण", "Brahmanand.N", " "}, 
{ "Karnataka",  "3939",  "Bangalore South", "Tejasvi Surya", "ForeignFunding",  " ","कर्नाटक",  "बैंगलोर दक्षिण", "तेजस्वी सूर्या", " "}, 
{ "Karnataka",  "3940",  "Bangalore South", "Bhagya.S", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर दक्षिण", "Bhagya.S", " "}, 
{ "Karnataka",  "3944",  "Bangalore South", "Dr.John Basco Philips", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर दक्षिण", "डॉ। जॉन बास्को फिलिप्स", " "}, 
{ "Karnataka",  "3945",  "Bangalore South", "G Venkatesh Bhovi", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर दक्षिण", "जी वेंकटेश भोई", " "}, 
{ "Karnataka",  "3946",  "Bangalore South", "Vatal Nagaraj", "OverAged",  " ","कर्नाटक",  "बैंगलोर दक्षिण", "वटाल नागराज", " "}, 
{ "Karnataka",  "3947",  "Bangalore South", "Thyagaraj", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर दक्षिण", "Thyagaraj", " "}, 
{ "Karnataka",  "3951",  "Bangalore South", "Syed Sadiq Pasha", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर दक्षिण", "सैयद सादिक पाशा", " "}, 
{ "Karnataka",  "3952",  "Bangalore South", "Yogeesh Nagaraj", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर दक्षिण", "योगेश नागराज", " "}, 
{ "Karnataka",  "3953",  "Bangalore South", "B.Chikka Nagesha", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर दक्षिण", "बी चिखा नागेश", " "}, 
{ "Karnataka",  "3954",  "Bangalore South", "Kollur Manjunatha Naik", "CriminalCases",  " ","कर्नाटक",  "बैंगलोर दक्षिण", "कोल्लूर मंजुनाथ नाइक", " "}, 
{ "Karnataka",  "3955",  "Bangalore South", "Madesh.V", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर दक्षिण", "Madesh.V", " "}, 
{ "Karnataka",  "3958",  "Bangalore South", "Santhosh Min B", "NotGraduate",  " ","कर्नाटक",  "बैंगलोर दक्षिण", "संतोष मिन बी", " "}, 
{ "Karnataka",  "3959",  "Bangalore South", "B.K.Hariprasad", "ForeignFunding",  " ","कर्नाटक",  "बैंगलोर दक्षिण", "BKHariprasad", " "}, 
{ "Karnataka",  "3723",  "Belgaum", "Shrikant Balkrishna Kadam", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "श्रीकांत बालकृष्ण कदम", " "}, 
{ "Karnataka",  "3724",  "Belgaum", "Nanda Maruti Kodachwadkar", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "नंदा मारुति कोड़वाडकर", " "}, 
{ "Karnataka",  "3725",  "Belgaum", "Buland Deepak Dalavi", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "बुलंद दीपक दलवी", " "}, 
{ "Karnataka",  "3726",  "Belgaum", "Pandurang Mallappa Pattan", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "पांडुरंग मल्लप्पा पट्टन", " "}, 
{ "Karnataka",  "3727",  "Belgaum", "Raju Changappa Divatage", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "राजू चंगप्पा दिवागत", " "}, 
{ "Karnataka",  "7055",  "Belgaum", "Vinayak Gopal Gunjatkar", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "विनायक गोपाल गुंजतकर", " "}, 
{ "Karnataka",  "3728",  "Belgaum", "Lakshmanarav Melage", "OverAged",  " ","कर्नाटक",  "बेलगाम", "लक्ष्मणाराव मेलागे", " "}, 
{ "Karnataka",  "3729",  "Belgaum", "Sanjay Kamble", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "संजय कांबले", " "}, 
{ "Karnataka",  "7057",  "Belgaum", "Angadi Suresh", "ForeignFunding",  " ","कर्नाटक",  "बेलगाम", "अंगदी सुरेश", " "}, 
{ "Karnataka",  "3730",  "Belgaum", "Maruti Siddappa Chougule", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "मारुति सिद्धप्पा चौगुले", " "}, 
{ "Karnataka",  "7058",  "Belgaum", "Ganesh Daddikar", "CriminalCases",  " ","कर्नाटक",  "बेलगाम", "गणेश दद्दिकर", " "}, 
{ "Karnataka",  "3731",  "Belgaum", "Prakash Balappa Nesarkar", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "प्रकाश बालप्पा नेसारकर", " "}, 
{ "Karnataka",  "7059",  "Belgaum", "Mahadev Maruti Manganakar", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "महादेव मारुति मंगणकर", " "}, 
{ "Karnataka",  "3732",  "Belgaum", "Kavita Deepak Kole", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "कविता दीपक कोइल", " "}, 
{ "Karnataka",  "3733",  "Belgaum", "Prabhakar Bhujang Patil", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "प्रभाकर भुजंग पाटिल", " "}, 
{ "Karnataka",  "7061",  "Belgaum", "Dilshaad Sikandar Tahashildar", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "दिलशाद सिकंदर तहसीलदार", " "}, 
{ "Karnataka",  "3734",  "Belgaum", "Ranjit Kallappa Patil", "CriminalCases",  " ","कर्नाटक",  "बेलगाम", "रंजीत कल्लप्पा पाटिल", " "}, 
{ "Karnataka",  "3735",  "Belgaum", "Dhananjay Rajaram Patil", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "धनंजय राजाराम पाटिल", " "}, 
{ "Karnataka",  "7063",  "Belgaum", "Gajanan Amrut Thokanekar", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "गजानन अमृत ठोकनेकर", " "}, 
{ "Karnataka",  "7064",  "Belgaum", "Shankar Pandappa Rathod", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "शंकर पंडप्पा राठौड़", " "}, 
{ "Karnataka",  "3737",  "Belgaum", "Nagesh Subhash Bobate", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "नागेश सुभाष बोबते", " "}, 
{ "Karnataka",  "7065",  "Belgaum", "Shubham Vikrant Shelke", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "शुभम विक्रांत शेलके", " "}, 
{ "Karnataka",  "3738",  "Belgaum", "Ashutosh Shashikant Kamble", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "आशुतोष शशिकांत कांबले", " "}, 
{ "Karnataka",  "3739",  "Belgaum", "Pranam Prakash Patil", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "प्रणाम प्रकाश पाटिल", " "}, 
{ "Karnataka",  "3740",  "Belgaum", "Ramchandra Dattoba Patil", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "रामचंद्र दत्तोबा पाटिल", " "}, 
{ "Karnataka",  "7068",  "Belgaum", "Vinayak Balakrishna More", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "विनायक बालकृष्ण मोरे", " "}, 
{ "Karnataka",  "3741",  "Belgaum", "Megharaj Shivagoudappa Khanagoudar", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "मेघराज शिवगौडप्पा खानगौदर", " "}, 
{ "Karnataka",  "3742",  "Belgaum", "Sachin Manohar Nikam", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "सचिन मनोहर निकम", " "}, 
{ "Karnataka",  "3743",  "Belgaum", "Krishnakant Kamanna Birje", "OverAged",  " ","कर्नाटक",  "बेलगाम", "कृष्णकांत कामना बिरजे", " "}, 
{ "Karnataka",  "3744",  "Belgaum", "Ramchandra Krishna Gaonkar", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "रामचंद्र कृष्ण गोदकर", " "}, 
{ "Karnataka",  "7072",  "Belgaum", "Shivaraj Narayan Patil", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "शिवराज नारायण पाटिल", " "}, 
{ "Karnataka",  "3745",  "Belgaum", "Rajendra Yallappa Patil", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "राजेंद्र यलप्पा पाटिल", " "}, 
{ "Karnataka",  "7073",  "Belgaum", "Dr.Virupakshappa Sadhunavar", "ForeignFunding",  " ","कर्नाटक",  "बेलगाम", "डॉ.विरूपक्षपा साधुनावर", " "}, 
{ "Karnataka",  "3747",  "Belgaum", "Kallappa Krishnappa Kowadkar", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "कल्लप्पा कृष्णप्पा कोवाडकर", " "}, 
{ "Karnataka",  "3748",  "Belgaum", "Onkarsingh C Bhatia", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "ओंकारसिंह सी भाटिया", " "}, 
{ "Karnataka",  "7076",  "Belgaum", "Sunil Vittal Dasar", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "सुनील विट्ठल दासर", " "}, 
{ "Karnataka",  "3749",  "Belgaum", "Sachin Shantaram Kelavekar", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "सचिन शांताराम केलवेकर", " "}, 
{ "Karnataka",  "7077",  "Belgaum", "Anil Baban Hegade", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "अनिल बबन हेगड़े", " "}, 
{ "Karnataka",  "3750",  "Belgaum", "Gopal Balavantrao Desai", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "गोपाल बलवंतराव देसाई", " "}, 
{ "Karnataka",  "7078",  "Belgaum", "Vishwanath Buwaji", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "विश्वनाथ बुवाजी", " "}, 
{ "Karnataka",  "3751",  "Belgaum", "Laxman Bhimarao Dalavi", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "लक्ष्मण भीमराव दलवी", " "}, 
{ "Karnataka",  "3753",  "Belgaum", "Neelkanth Mahadev Patil", "NotGraduate",  " ","कर्नाटक",  "बेलगाम", "नीलकंठ महादेव पाटिल", " "}, 
{ "Karnataka",  "7158",  "Bellary", "A. Devadas", "NotGraduate",  " ","कर्नाटक",  "बेल्लारी", "ए देवदास", " "}, 
{ "Karnataka",  "7160",  "Bellary", "V. S. Ugrappa", "ForeignFunding",  " ","कर्नाटक",  "बेल्लारी", "वीएस उग्रप्पा", " "}, 
{ "Karnataka",  "7161",  "Bellary", "K. Gulappa", "OverAged",  " ","कर्नाटक",  "बेल्लारी", "के। गुलप्पा", " "}, 
{ "Karnataka",  "7162",  "Bellary", "B. Eshwarappa", "CriminalCases",  " ","कर्नाटक",  "बेल्लारी", "बी ईश्वरप्पा", " "}, 
{ "Karnataka",  "7163",  "Bellary", "Yeruru Pampapathi", "NotGraduate",  " ","कर्नाटक",  "बेल्लारी", "येरु पमपपति", " "}, 
{ "Karnataka",  "7164",  "Bellary", "Y. Devendrappa", "ForeignFunding",  " ","कर्नाटक",  "बेल्लारी", "वाई। देवेंद्रप्पा", " "}, 
{ "Karnataka",  "7165",  "Bellary", "T. Veeresh", "NotGraduate",  " ","कर्नाटक",  "बेल्लारी", "टी। वीरेश", " "}, 
{ "Karnataka",  "7166",  "Bellary", "P. D. Ramanayaka", "NotGraduate",  " ","कर्नाटक",  "बेल्लारी", "पीडी रामनायका", " "}, 
{ "Karnataka",  "7167",  "Bellary", "B. Raghu", "NotGraduate",  " ","कर्नाटक",  "बेल्लारी", "बी रघु ने", " "}, 
{ "Karnataka",  "7122",  "Bidar", "Bhagwanth Khuba", "ForeignFunding",  " ","कर्नाटक",  "बीदर", "भगवंत खुबा", " "}, 
{ "Karnataka",  "7123",  "Bidar", "Mohammed Abdul Wakeel", "NotGraduate",  " ","कर्नाटक",  "बीदर", "मोहम्मद अब्दुल वेकेल", " "}, 
{ "Karnataka",  "7124",  "Bidar", "Mohammed Yousuf", "NotGraduate",  " ","कर्नाटक",  "बीदर", "मोहम्मद यूसुफ", " "}, 
{ "Karnataka",  "7125",  "Bidar", "Abdus Sattar Mujahed", "CriminalCases",  " ","कर्नाटक",  "बीदर", "अब्दुस सत्तार मुजाहिद", " "}, 
{ "Karnataka",  "7126",  "Bidar", "Sharad", "NotGraduate",  " ","कर्नाटक",  "बीदर", "शरद", " "}, 
{ "Karnataka",  "7127",  "Bidar", "Eshwar", "ForeignFunding",  " ","कर्नाटक",  "बीदर", "ईश्वर", " "}, 
{ "Karnataka",  "7128",  "Bidar", "Sugriv Bharat Kachave", "NotGraduate",  " ","कर्नाटक",  "बीदर", "सुग्रीव भारत कछवे", " "}, 
{ "Karnataka",  "7131",  "Bidar", "Md Merajuddin", "NotGraduate",  " ","कर्नाटक",  "बीदर", "एमडी मरजुद्दीन", " "}, 
{ "Karnataka",  "7134",  "Bidar", "S.H Bukhari", "OverAged",  " ","कर्नाटक",  "बीदर", "एसएच बुखारी", " "}, 
{ "Karnataka",  "7135",  "Bidar", "Shrimanth Yevate Patil", "OverAged",  " ","कर्नाटक",  "बीदर", "श्रीमंत येवते पाटिल", " "}, 
{ "Karnataka",  "7136",  "Bidar", "Rajambi", "NotGraduate",  " ","कर्नाटक",  "बीदर", "Rajambi", " "}, 
{ "Karnataka",  "7137",  "Bidar", "Shivaraj", "OverAged",  " ","कर्नाटक",  "बीदर", "शिवराज", " "}, 
{ "Karnataka",  "7138",  "Bidar", "Dayanand", "NotGraduate",  " ","कर्नाटक",  "बीदर", "दयानंद", " "}, 
{ "Karnataka",  "7142",  "Bidar", "Moulvi Zameruddin", "OverAged",  " ","कर्नाटक",  "बीदर", "मौलवी ज़मीरुद्दीन", " "}, 
{ "Karnataka",  "7143",  "Bidar", "Santosh", "NotGraduate",  " ","कर्नाटक",  "बीदर", "संतोष", " "}, 
{ "Karnataka",  "7093",  "Bijapur", "Pujari Shrinath Sangappa", "CriminalCases",  " ","कर्नाटक",  "बीजापुर", "पुजारी श्रीनाथ संगप्पा", " "}, 
{ "Karnataka",  "7094",  "Bijapur", "Ramappa Harijan", "CriminalCases",  " ","कर्नाटक",  "बीजापुर", "रामप्पा हरिजन", " "}, 
{ "Karnataka",  "7095",  "Bijapur", "Jigajinagi Ramesh Chandappa", "ForeignFunding",  " ","कर्नाटक",  "बीजापुर", "जिगजिनागी रमेश चंदप्पा", " "}, 
{ "Karnataka",  "7097",  "Bijapur", "Yamanappa Vittal Gunadal", "CriminalCases",  " ","कर्नाटक",  "बीजापुर", "यमनप्पा विट्टल गुनदाल", " "}, 
{ "Karnataka",  "7100",  "Bijapur", "Dondiba Ramu Rathod", "NotGraduate",  " ","कर्नाटक",  "बीजापुर", "डोंडिबा रामू राठौड़", " "}, 
{ "Karnataka",  "7101",  "Bijapur", "Balaji Dyamanna Waddar", "CriminalCases",  " ","कर्नाटक",  "बीजापुर", "बालाजी दायमन्ना वद्दार", " "}, 
{ "Karnataka",  "7103",  "Bijapur", "Gurubasava. P . Rabakavi", "NotGraduate",  " ","कर्नाटक",  "बीजापुर", "Gurubasava। पी। Rabakavi", " "}, 
{ "Karnataka",  "7104",  "Bijapur", "Dadasab Siddappa Bagayat", "NotGraduate",  " ","कर्नाटक",  "बीजापुर", "दादासाब सिद्दप्पा बागायत", " "}, 
{ "Karnataka",  "3862",  "Chamarajanagar", "Subbaiah", "NotGraduate",  " ","कर्नाटक",  "चामराजनगर", "सुब्बैया", " "}, 
{ "Karnataka",  "3863",  "Chamarajanagar", "G.D. Rajagopal", "NotGraduate",  " ","कर्नाटक",  "चामराजनगर", "जीडी राजगोपाल", " "}, 
{ "Karnataka",  "3864",  "Chamarajanagar", "R Dhruvanarayana", "ForeignFunding",  " ","कर्नाटक",  "चामराजनगर", "आर ध्रुवनारायण", " "}, 
{ "Karnataka",  "3865",  "Chamarajanagar", "N Ambarish", "NotGraduate",  " ","कर्नाटक",  "चामराजनगर", "एन अंबरीश", " "}, 
{ "Karnataka",  "3866",  "Chamarajanagar", "V Srinivas Prasad", "ForeignFunding",  " ","कर्नाटक",  "चामराजनगर", "वी श्रीनिवास प्रसाद", " "}, 
{ "Karnataka",  "3868",  "Chamarajanagar", "Anand Jivan Ram", "NotGraduate",  " ","कर्नाटक",  "चामराजनगर", "आनंद जीवन राम", " "}, 
{ "Karnataka",  "3870",  "Chamarajanagar", "M Pradeep Kumar", "NotGraduate",  " ","कर्नाटक",  "चामराजनगर", "एम प्रदीप कुमार", " "}, 
{ "Karnataka",  "3961",  "Chikkballapur", "Nalina.K.S", "NotGraduate",  " ","कर्नाटक",  "चिकबल्लपुर", "Nalina.KS", " "}, 
{ "Karnataka",  "3962",  "Chikkballapur", "Muniraju.G", "NotGraduate",  " ","कर्नाटक",  "चिकबल्लपुर", "Muniraju.G", " "}, 
{ "Karnataka",  "3963",  "Chikkballapur", "L. Nagaraj", "NotGraduate",  " ","कर्नाटक",  "चिकबल्लपुर", "एल। नागराज", " "}, 
{ "Karnataka",  "3964",  "Chikkballapur", "M.Veerappa Moily", "ForeignFunding",  " ","कर्नाटक",  "चिकबल्लपुर", "एम. वीरप्पा मोइली", " "}, 
{ "Karnataka",  "3966",  "Chikkballapur", "Dr. C.S.Dwarakanath", "OverAged",  " ","कर्नाटक",  "चिकबल्लपुर", "डॉ। CSDwarakanath", " "}, 
{ "Karnataka",  "3968",  "Chikkballapur", "Phaniraj.S.V", "NotGraduate",  " ","कर्नाटक",  "चिकबल्लपुर", "Phaniraj.SV", " "}, 
{ "Karnataka",  "3969",  "Chikkballapur", "Nasrulla", "NotGraduate",  " ","कर्नाटक",  "चिकबल्लपुर", "Nasrulla", " "}, 
{ "Karnataka",  "3970",  "Chikkballapur", "D.Palya Khadar Subhan Khan", "NotGraduate",  " ","कर्नाटक",  "चिकबल्लपुर", "डी.पल्या खादर सुभान खान", " "}, 
{ "Karnataka",  "3971",  "Chikkballapur", "S.Varalakshmi", "CriminalCases",  " ","कर्नाटक",  "चिकबल्लपुर", "S.Varalakshmi", " "}, 
{ "Karnataka",  "3972",  "Chikkballapur", "S.R.Nageshareddy", "NotGraduate",  " ","कर्नाटक",  "चिकबल्लपुर", "SRNageshareddy", " "}, 
{ "Karnataka",  "3973",  "Chikkballapur", "Nazir Ahmed", "NotGraduate",  " ","कर्नाटक",  "चिकबल्लपुर", "नजीर अहमद", " "}, 
{ "Karnataka",  "3974",  "Chikkballapur", "Alanguru Kanakalakshmi", "NotGraduate",  " ","कर्नाटक",  "चिकबल्लपुर", "अलंगुरु कनकलक्ष्मी", " "}, 
{ "Karnataka",  "3975",  "Chikkballapur", "B.N.Bache Gowda", "ForeignFunding",  " ","कर्नाटक",  "चिकबल्लपुर", "BNBache गौड़ा", " "}, 
{ "Karnataka",  "7045",  "Chikkodi", "Shrinik Annasaheb Jangate", "NotGraduate",  " ","कर्नाटक",  "चिक्कोडी", "श्रीनिक अन्नसाहेब जंगटे", " "}, 
{ "Karnataka",  "7048",  "Chikkodi", "Machchendra Davalu Kadapure", "NotGraduate",  " ","कर्नाटक",  "चिक्कोडी", "मचकेन्द्र दावालु कदपुरे", " "}, 
{ "Karnataka",  "7049",  "Chikkodi", "Jitendra Subhash Nerle", "NotGraduate",  " ","कर्नाटक",  "चिक्कोडी", "जितेंद्र सुभाष नेरले", " "}, 
{ "Karnataka",  "3722",  "Chikkodi", "Appasaheb Shripati Kurane", "NotGraduate",  " ","कर्नाटक",  "चिक्कोडी", "अप्पासाहेब श्रीपति कुराने", " "}, 
{ "Karnataka",  "7050",  "Chikkodi", "Magdum Ismailmagdum", "NotGraduate",  " ","कर्नाटक",  "चिक्कोडी", "मागदुम इस्माइलमगदुम", " "}, 
{ "Karnataka",  "7051",  "Chikkodi", "Prakash Babanna Hukkeri", "ForeignFunding",  " ","कर्नाटक",  "चिक्कोडी", "प्रकाश बबना हुक्केरी", " "}, 
{ "Karnataka",  "7052",  "Chikkodi", "Vishwnath Kalloli Wajantri", "NotGraduate",  " ","कर्नाटक",  "चिक्कोडी", "विश्वनाथ कल्लोली वजंत्री", " "}, 
{ "Karnataka",  "7053",  "Chikkodi", "Annasaheb Shankar Jolle", "ForeignFunding",  " ","कर्नाटक",  "चिक्कोडी", "अन्नासाहेब शंकर जोले", " "}, 
{ "Karnataka",  "7054",  "Chikkodi", "Kallappa Adiveppa Gudasi", "NotGraduate",  " ","कर्नाटक",  "चिक्कोडी", "कल्लप्पा आदिवप्पा गुडासी", " "}, 
{ "Karnataka",  "3786",  "Chitradurga", "L Venugopal", "NotGraduate",  " ","कर्नाटक",  "चित्रदुर्ग", "एल वेणुगोपाल", " "}, 
{ "Karnataka",  "3787",  "Chitradurga", "R Hanumanthappa", "OverAged",  " ","कर्नाटक",  "चित्रदुर्ग", "आर हनुमनथप्पा", " "}, 
{ "Karnataka",  "3789",  "Chitradurga", "A Narayanaswamy", "ForeignFunding",  " ","कर्नाटक",  "चित्रदुर्ग", "एक नारायणस्वामी", " "}, 
{ "Karnataka",  "3790",  "Chitradurga", "Ganesh", "NotGraduate",  " ","कर्नाटक",  "चित्रदुर्ग", "गणेश", " "}, 
{ "Karnataka",  "3791",  "Chitradurga", "Kumar Y", "CriminalCases",  " ","कर्नाटक",  "चित्रदुर्ग", "कुमार वाई", " "}, 
{ "Karnataka",  "3792",  "Chitradurga", "B N Chandrappa", "ForeignFunding",  " ","कर्नाटक",  "चित्रदुर्ग", "बीएन चंद्रप्पा", " "}, 
{ "Karnataka",  "3793",  "Chitradurga", "C H Narayanaswamy", "NotGraduate",  " ","कर्नाटक",  "चित्रदुर्ग", "सीएच नारायणस्वामी", " "}, 
{ "Karnataka",  "3796",  "Chitradurga", "L Rangappa", "CriminalCases",  " ","कर्नाटक",  "चित्रदुर्ग", "एल रंगप्पा", " "}, 
{ "Karnataka",  "3798",  "Chitradurga", "Thippeswamy T", "NotGraduate",  " ","कर्नाटक",  "चित्रदुर्ग", "थिप्पेस्वामी टी", " "}, 
{ "Karnataka",  "3800",  "Chitradurga", "Devendrappa", "NotGraduate",  " ","कर्नाटक",  "चित्रदुर्ग", "Devendrappa", " "}, 
{ "Karnataka",  "3802",  "Chitradurga", "Mahanthesh C U", "CriminalCases",  " ","कर्नाटक",  "चित्रदुर्ग", "महंतेश सीयू", " "}, 
{ "Karnataka",  "3773",  "Dakshina Kannada", "Mohammad Khalid", "NotGraduate",  " ","कर्नाटक",  "दक्षिण कन्नड़", "मोहम्मद खालिद", " "}, 
{ "Karnataka",  "3774",  "Dakshina Kannada", "Mohammed Eliyas", "CriminalCases",  " ","कर्नाटक",  "दक्षिण कन्नड़", "मोहम्मद इलियास", " "}, 
{ "Karnataka",  "3775",  "Dakshina Kannada", "H. Suresh Poojary", "NotGraduate",  " ","कर्नाटक",  "दक्षिण कन्नड़", "एच। सुरेश पूजारी", " "}, 
{ "Karnataka",  "3776",  "Dakshina Kannada", "Abdul Hameed", "NotGraduate",  " ","कर्नाटक",  "दक्षिण कन्नड़", "अब्दुल हमीद", " "}, 
{ "Karnataka",  "3777",  "Dakshina Kannada", "Nalin Kumar Kateel", "ForeignFunding",  " ","कर्नाटक",  "दक्षिण कन्नड़", "नलिन कुमार काटेल", " "}, 
{ "Karnataka",  "3778",  "Dakshina Kannada", "Alexander", "CriminalCases",  " ","कर्नाटक",  "दक्षिण कन्नड़", "सिकंदर", " "}, 
{ "Karnataka",  "3780",  "Dakshina Kannada", "Mithun M Rai", "ForeignFunding",  " ","कर्नाटक",  "दक्षिण कन्नड़", "मिथुन एम राय", " "}, 
{ "Karnataka",  "3781",  "Dakshina Kannada", "Supreeth Kumar Poojary", "NotGraduate",  " ","कर्नाटक",  "दक्षिण कन्नड़", "सुप्रीत कुमार पूजा", " "}, 
{ "Karnataka",  "3782",  "Dakshina Kannada", "S. Sathish Saliyan", "NotGraduate",  " ","कर्नाटक",  "दक्षिण कन्नड़", "एस। सतीश सलियान", " "}, 
{ "Karnataka",  "3783",  "Dakshina Kannada", "Vijay Shreenivas C", "NotGraduate",  " ","कर्नाटक",  "दक्षिण कन्नड़", "विजय श्रीनिवास सी", " "}, 
{ "Karnataka",  "3784",  "Dakshina Kannada", "Deepak Rajesh Coelho", "NotGraduate",  " ","कर्नाटक",  "दक्षिण कन्नड़", "दीपक राजेश कोल्हो", " "}, 
{ "Karnataka",  "3785",  "Dakshina Kannada", "Maxim Pinto", "NotGraduate",  " ","कर्नाटक",  "दक्षिण कन्नड़", "मैक्सिम पिंटो", " "}, 
{ "Karnataka",  "7210",  "Davanagere", "Ganesha B A", "NotGraduate",  " ","कर्नाटक",  "दावनगेरे", "गणेश बीए", " "}, 
{ "Karnataka",  "7212",  "Davanagere", "M B Veerabhadrappa", "NotGraduate",  " ","कर्नाटक",  "दावनगेरे", "एमबी वीरभद्रप्पा", " "}, 
{ "Karnataka",  "7213",  "Davanagere", "G M Siddeshwar", "ForeignFunding",  " ","कर्नाटक",  "दावनगेरे", "जीएम सिद्धेश्वर", " "}, 
{ "Karnataka",  "7214",  "Davanagere", "Mohammed Aleemulla", "NotGraduate",  " ","कर्नाटक",  "दावनगेरे", "मोहम्मद अलीमुल्ला", " "}, 
{ "Karnataka",  "7215",  "Davanagere", "H B Manjappa", "ForeignFunding",  " ","कर्नाटक",  "दावनगेरे", "एचबी मंजप्पा", " "}, 
{ "Karnataka",  "7217",  "Davanagere", "Siddappa B H", "CriminalCases",  " ","कर्नाटक",  "दावनगेरे", "सिद्दप्पा बी.एच.", " "}, 
{ "Karnataka",  "7218",  "Davanagere", "V Iqbal Ahamed", "NotGraduate",  " ","कर्नाटक",  "दावनगेरे", "वी इकबाल अहमद", " "}, 
{ "Karnataka",  "7219",  "Davanagere", "Manjunatha Marikoppa", "NotGraduate",  " ","कर्नाटक",  "दावनगेरे", "मंजूनाथ मारिकोप्पा", " "}, 
{ "Karnataka",  "7220",  "Davanagere", "Ravindra Navale", "OverAged",  " ","कर्नाटक",  "दावनगेरे", "रवींद्र नवले", " "}, 
{ "Karnataka",  "7221",  "Davanagere", "Dr Sridhara Udupa", "OverAged",  " ","कर्नाटक",  "दावनगेरे", "डॉ। श्रीधरा उडुपा", " "}, 
{ "Karnataka",  "7222",  "Davanagere", "Abdul Nazeer Sab", "NotGraduate",  " ","कर्नाटक",  "दावनगेरे", "अब्दुल नज़ीर सब", " "}, 
{ "Karnataka",  "7223",  "Davanagere", "Harish Halli", "NotGraduate",  " ","कर्नाटक",  "दावनगेरे", "हरीश होली", " "}, 
{ "Karnataka",  "7224",  "Davanagere", "Syed Zabiulla K", "NotGraduate",  " ","कर्नाटक",  "दावनगेरे", "सैयद जबीउल्ला के", " "}, 
{ "Karnataka",  "7225",  "Davanagere", "C M Manjunatha Swami", "NotGraduate",  " ","कर्नाटक",  "दावनगेरे", "सीएम मंजूनाथ स्वामी", " "}, 
{ "Karnataka",  "7226",  "Davanagere", "A T Dadakhalandar", "NotGraduate",  " ","कर्नाटक",  "दावनगेरे", "एटी दादाखेलदार", " "}, 
{ "Karnataka",  "7227",  "Davanagere", "S K Afzalkhan", "NotGraduate",  " ","कर्नाटक",  "दावनगेरे", "एसके अफजलखान", " "}, 
{ "Karnataka",  "7228",  "Davanagere", "H Eshwarappa", "OverAged",  " ","कर्नाटक",  "दावनगेरे", "एच ईश्वरप्पा", " "}, 
{ "Karnataka",  "7231",  "Davanagere", "Barkath Ali", "NotGraduate",  " ","कर्नाटक",  "दावनगेरे", "बरकत अली", " "}, 
{ "Karnataka",  "7232",  "Davanagere", "B V Tippeswamy Goshale", "NotGraduate",  " ","कर्नाटक",  "दावनगेरे", "बीवी तिप्पेस्वामी गोशले", " "}, 
{ "Karnataka",  "7178",  "Dharwad", "Udayakumar Ayyappa Ambiger", "NotGraduate",  " ","कर्नाटक",  "धारवाड़", "उदयकुमार अयप्पा अंबिगर", " "}, 
{ "Karnataka",  "7179",  "Dharwad", "Mallikarjunagouda Giriyappagouda Balanagoudra", "NotGraduate",  " ","कर्नाटक",  "धारवाड़", "मल्लिकार्जुनगौड़ा गिरियप्पगौड़ा बालनगौड़ा", " "}, 
{ "Karnataka",  "7180",  "Dharwad", "Hashinabanu Tapalvale", "NotGraduate",  " ","कर्नाटक",  "धारवाड़", "हशिनाबनु तपवेल", " "}, 
{ "Karnataka",  "7182",  "Dharwad", "Irappa Madar", "NotGraduate",  " ","कर्नाटक",  "धारवाड़", "इरापा मदार", " "}, 
{ "Karnataka",  "7183",  "Dharwad", "Vinay Kulkarni", "ForeignFunding",  " ","कर्नाटक",  "धारवाड़", "विनय कुलकर्णी", " "}, 
{ "Karnataka",  "7185",  "Dharwad", "Maradagi Veerappa Gurushantappa", "NotGraduate",  " ","कर्नाटक",  "धारवाड़", "मरदगी वीरप्पा गुरुशांतप्पा", " "}, 
{ "Karnataka",  "7186",  "Dharwad", "Vinod D Ghodke", "NotGraduate",  " ","कर्नाटक",  "धारवाड़", "विनोद डी घोडके", " "}, 
{ "Karnataka",  "7187",  "Dharwad", "Somashekhar Peeraji Yadav", "NotGraduate",  " ","कर्नाटक",  "धारवाड़", "सोमशेखर पीरजी यादव", " "}, 
{ "Karnataka",  "7188",  "Dharwad", "Raju Anantsa Naikwadi", "CriminalCases",  " ","कर्नाटक",  "धारवाड़", "राजू अनंता नाइकवाडी", " "}, 
{ "Karnataka",  "7189",  "Dharwad", "Revanshiddappa Basavaraj Talawar", "NotGraduate",  " ","कर्नाटक",  "धारवाड़", "रेवंशीदप्पा बसवराज तलवार", " "}, 
{ "Karnataka",  "7192",  "Dharwad", "Pralhad Joshi", "ForeignFunding",  " ","कर्नाटक",  "धारवाड़", "प्रल्हाद जोशी", " "}, 
{ "Karnataka",  "7193",  "Dharwad", "Vadiraj Mannari Madhusudhan", "CriminalCases",  " ","कर्नाटक",  "धारवाड़", "वदिराज मन्नारी मधुसूदन", " "}, 
{ "Karnataka",  "7194",  "Dharwad", "Shakeel Ahmad Abdulsattar Dodwad", "NotGraduate",  " ","कर्नाटक",  "धारवाड़", "शकील अहमद अब्दुलात्सर डोडवाड", " "}, 
{ "Karnataka",  "7196",  "Dharwad", "Dundasi Abdulrahiman Mahammad Hanif", "CriminalCases",  " ","कर्नाटक",  "धारवाड़", "दुन्दसी अब्दुलरहिमन मोहम्मद हनीफ", " "}, 
{ "Karnataka",  "7105",  "Gulbarga", "Rajkumar", "NotGraduate",  " ","कर्नाटक",  "गुलबर्गा", "राजकुमार", " "}, 
{ "Karnataka",  "7106",  "Gulbarga", "G. Timmaraju", "NotGraduate",  " ","कर्नाटक",  "गुलबर्गा", "जी। तिमाराजू", " "}, 
{ "Karnataka",  "7107",  "Gulbarga", "Dr. Umesh G Jadhav", "ForeignFunding",  " ","कर्नाटक",  "गुलबर्गा", "डॉ। उमेश जी जाधव", " "}, 
{ "Karnataka",  "7108",  "Gulbarga", "Mallikarjun Kharge", "ForeignFunding",  " ","कर्नाटक",  "गुलबर्गा", "मल्लिकार्जुन खड़गे", " "}, 
{ "Karnataka",  "7109",  "Gulbarga", "Shankar Jadhav", "NotGraduate",  " ","कर्नाटक",  "गुलबर्गा", "शंकर जाधव", " "}, 
{ "Karnataka",  "7111",  "Gulbarga", "Vijay Jadhav", "NotGraduate",  " ","कर्नाटक",  "गुलबर्गा", "विजय जाधव", " "}, 
{ "Karnataka",  "7113",  "Gulbarga", "Ramesh Bheemsingh Chavan", "CriminalCases",  " ","कर्नाटक",  "गुलबर्गा", "रमेश भीमसिंह चव्हाण", " "}, 
{ "Karnataka",  "7114",  "Gulbarga", "S. M. Sharma", "CriminalCases",  " ","कर्नाटक",  "गुलबर्गा", "एसएम शर्मा", " "}, 
{ "Karnataka",  "7116",  "Gulbarga", "K. B. Vasu", "CriminalCases",  " ","कर्नाटक",  "गुलबर्गा", "केबी वासु", " "}, 
{ "Karnataka",  "3767",  "Hassan", "Vinodraj K H", "NotGraduate",  " ","कर्नाटक",  "हसन", "विनोदराज के", " "}, 
{ "Karnataka",  "3768",  "Hassan", "H M Chandregowda", "OverAged",  " ","कर्नाटक",  "हसन", "एचएम चंद्रागौड़ा", " "}, 
{ "Karnataka",  "3770",  "Hassan", "M. Mahesh (Al: Lokesh)", "NotGraduate",  " ","कर्नाटक",  "हसन", "एम। महेश (अल: लोकेश)", " "}, 
{ "Karnataka",  "3771",  "Hassan", "Manju A", "ForeignFunding",  " ","कर्नाटक",  "हसन", "मंजू ए", " "}, 
{ "Karnataka",  "3772",  "Hassan", "R G Sathisha", "NotGraduate",  " ","कर्नाटक",  "हसन", "आरजी सतीशा", " "}, 
{ "Karnataka",  "7168",  "Haveri", "Ishwar Patil", "NotGraduate",  " ","कर्नाटक",  "हावेरी", "ईश्वर पाटिल", " "}, 
{ "Karnataka",  "7169",  "Haveri", "Veerabhadrappa Veerappa Kabbinada", "OverAged",  " ","कर्नाटक",  "हावेरी", "वीरभद्रप्पा वीरप्पा कबिनदा", " "}, 
{ "Karnataka",  "7170",  "Haveri", "Basavaraj. S. Desai", "NotGraduate",  " ","कर्नाटक",  "हावेरी", "बासवराज। एस। देसाई", " "}, 
{ "Karnataka",  "7171",  "Haveri", "Bommoji Ramappa Siddappa", "OverAged",  " ","कर्नाटक",  "हावेरी", "बोम्मोजी रामप्पा सिद्धप्पा", " "}, 
{ "Karnataka",  "7172",  "Haveri", "Udasi. S.C.", "ForeignFunding",  " ","कर्नाटक",  "हावेरी", "उदासी। अनुसूचित जाति", " "}, 
{ "Karnataka",  "7173",  "Haveri", "D.R. Patil", "ForeignFunding",  " ","कर्नाटक",  "हावेरी", "डीआर पाटिल", " "}, 
{ "Karnataka",  "7175",  "Haveri", "Hanumanthappa D Kabbar", "NotGraduate",  " ","कर्नाटक",  "हावेरी", "हनुमनथप्पा डी कबर", " "}, 
{ "Karnataka",  "7177",  "Haveri", "Siddappa Kallappa Poojar", "NotGraduate",  " ","कर्नाटक",  "हावेरी", "सिदप्पा कल्लप्पा पुजार", " "}, 
{ "Karnataka",  "3976",  "Kolar", "K.H. Muniyappa", "ForeignFunding",  " ","कर्नाटक",  "कोलार", "केएच मुनियप्पा", " "}, 
{ "Karnataka",  "3977",  "Kolar", "S. Muniswamy", "ForeignFunding",  " ","कर्नाटक",  "कोलार", "एस। मुनीस्वामी", " "}, 
{ "Karnataka",  "3982",  "Kolar", "Medihala Chalavadi M Chandrashekar", "NotGraduate",  " ","कर्नाटक",  "कोलार", "मेदिहाला चलवदी एम चंद्रशेखर", " "}, 
{ "Karnataka",  "3983",  "Kolar", "C. Shankarappa", "NotGraduate",  " ","कर्नाटक",  "कोलार", "सी। शंकरप्पा", " "}, 
{ "Karnataka",  "3984",  "Kolar", "Sarvesh N.M.", "NotGraduate",  " ","कर्नाटक",  "कोलार", "सर्वेश एन.एम.", " "}, 
{ "Karnataka",  "3987",  "Kolar", "Ashok Chakravarthi M.B", "NotGraduate",  " ","कर्नाटक",  "कोलार", "अशोक चक्रवर्ती एमबी", " "}, 
{ "Karnataka",  "3988",  "Kolar", "Dhanamatnalli Venkateshappa", "NotGraduate",  " ","कर्नाटक",  "कोलार", "धनात्मनल्ली वेंकटेशप्पा", " "}, 
{ "Karnataka",  "3989",  "Kolar", "Munirajappa. P", "NotGraduate",  " ","कर्नाटक",  "कोलार", "Munirajappa। पी", " "}, 
{ "Karnataka",  "7144",  "Koppal", "Mallikarjun Hadapad", "NotGraduate",  " ","कर्नाटक",  "कोप्पल", "मल्लिकार्जुन हड़पड़", " "}, 
{ "Karnataka",  "7145",  "Koppal", "Bandimath Sharanayya", "NotGraduate",  " ","कर्नाटक",  "कोप्पल", "बांदीमठ शरणाय", " "}, 
{ "Karnataka",  "7146",  "Koppal", "Comrade B.Basavalingappa", "NotGraduate",  " ","कर्नाटक",  "कोप्पल", "कॉमरेड बी.बासावलिंगप्पा", " "}, 
{ "Karnataka",  "7147",  "Koppal", "Nagaraj Kalal", "NotGraduate",  " ","कर्नाटक",  "कोप्पल", "नागराज कलाल", " "}, 
{ "Karnataka",  "7148",  "Koppal", "Karadi Sanganna Amarappa", "ForeignFunding",  " ","कर्नाटक",  "कोप्पल", "करदी संगना अमरप्पा", " "}, 
{ "Karnataka",  "7149",  "Koppal", "Suresh Gouda Mundinamane", "NotGraduate",  " ","कर्नाटक",  "कोप्पल", "सुरेश गौड़ा मुंडिनामने", " "}, 
{ "Karnataka",  "7153",  "Koppal", "Annojirao.G", "NotGraduate",  " ","कर्नाटक",  "कोप्पल", "Annojirao.G", " "}, 
{ "Karnataka",  "7154",  "Koppal", "K.Rajashekar Basavaraj Hitnal", "ForeignFunding",  " ","कर्नाटक",  "कोप्पल", "के राजशेखर बसवराज हिटलल", " "}, 
{ "Karnataka",  "7156",  "Koppal", "Shivaputrappa. Gumagera", "NotGraduate",  " ","कर्नाटक",  "कोप्पल", "Shivaputrappa। Gumagera", " "}, 
{ "Karnataka",  "3820",  "Mandya", "M.L. Shashikumar", "NotGraduate",  " ","कर्नाटक",  "मंड्या", "एमएल शशिकुमार", " "}, 
{ "Karnataka",  "3821",  "Mandya", "H.Narayana", "NotGraduate",  " ","कर्नाटक",  "मंड्या", "H.Narayana", " "}, 
{ "Karnataka",  "3823",  "Mandya", "C. Lingegowda", "OverAged",  " ","कर्नाटक",  "मंड्या", "सी। लिंगेगौड़ा", " "}, 
{ "Karnataka",  "3824",  "Mandya", "G. Manjunath", "NotGraduate",  " ","कर्नाटक",  "मंड्या", "जी। मंजूनाथ", " "}, 
{ "Karnataka",  "3825",  "Mandya", "D C Jayashankara", "NotGraduate",  " ","कर्नाटक",  "मंड्या", "डीसी जयशंकर", " "}, 
{ "Karnataka",  "3827",  "Mandya", "Gurulingaiah", "NotGraduate",  " ","कर्नाटक",  "मंड्या", "Gurulingaiah", " "}, 
{ "Karnataka",  "3828",  "Mandya", "Sumalatha Ambareesh", "NotGraduate",  " ","कर्नाटक",  "मंड्या", "सुमलाथा अंबरीश", " "}, 
{ "Karnataka",  "3829",  "Mandya", "Satheesh Kumar .T.N", "NotGraduate",  " ","कर्नाटक",  "मंड्या", "सतीश कुमार .TN", " "}, 
{ "Karnataka",  "3831",  "Mandya", "Manjunath B", "CriminalCases",  " ","कर्नाटक",  "मंड्या", "मंजूनाथ बी", " "}, 
{ "Karnataka",  "3832",  "Mandya", "Kowdle Channappa", "OverAged",  " ","कर्नाटक",  "मंड्या", "कोवल चन्नप्पा", " "}, 
{ "Karnataka",  "3833",  "Mandya", "C.P. Divakar", "CriminalCases",  " ","कर्नाटक",  "मंड्या", "सीपी दिवाकर", " "}, 
{ "Karnataka",  "3837",  "Mandya", "M. Sumalatha", "NotGraduate",  " ","कर्नाटक",  "मंड्या", "एम। सुमलथा", " "}, 
{ "Karnataka",  "3838",  "Mandya", "Sumalatha", "NotGraduate",  " ","कर्नाटक",  "मंड्या", "सुमालाथा", " "}, 
{ "Karnataka",  "3843",  "Mysore", "C.H.Vijayashankar", "ForeignFunding",  " ","कर्नाटक",  "मैसूर", "CHVijayashankar", " "}, 
{ "Karnataka",  "3844",  "Mysore", "Anand Kumar. M", "NotGraduate",  " ","कर्नाटक",  "मैसूर", "आनंद कुमार। एम", " "}, 
{ "Karnataka",  "3845",  "Mysore", "Asharani V", "NotGraduate",  " ","कर्नाटक",  "मैसूर", "आशारानी वी", " "}, 
{ "Karnataka",  "3846",  "Mysore", "R. Mahesha", "NotGraduate",  " ","कर्नाटक",  "मैसूर", "आर। महेशा", " "}, 
{ "Karnataka",  "3847",  "Mysore", "Kaveriamma.N.K.", "NotGraduate",  " ","कर्नाटक",  "मैसूर", "Kaveriamma.NK", " "}, 
{ "Karnataka",  "3848",  "Mysore", "Lokesh Kumar.G.", "CriminalCases",  " ","कर्नाटक",  "मैसूर", "लोकेश कुमार.जी.", " "}, 
{ "Karnataka",  "3849",  "Mysore", "Dr. B. Chandra (Chandregowda)", "CriminalCases",  " ","कर्नाटक",  "मैसूर", "डॉ। बी। चंद्रा (चंद्रगौड़ा)", " "}, 
{ "Karnataka",  "3850",  "Mysore", "Prathap Simha", "ForeignFunding",  " ","कर्नाटक",  "मैसूर", "प्रताप सिम्हा", " "}, 
{ "Karnataka",  "3851",  "Mysore", "Ayub Khan", "CriminalCases",  " ","कर्नाटक",  "मैसूर", "अयूब खान", " "}, 
{ "Karnataka",  "3853",  "Mysore", "Raju S/O Late Chaluvashetty", "OverAged",  " ","कर्नाटक",  "मैसूर", "राजू एस / ओ स्वर्गीय चुल्लूवासटी", " "}, 
{ "Karnataka",  "3854",  "Mysore", "Venkatesha D Nayaka", "NotGraduate",  " ","कर्नाटक",  "मैसूर", "वेंकटेश डी नायक", " "}, 
{ "Karnataka",  "3855",  "Mysore", "Ravi", "NotGraduate",  " ","कर्नाटक",  "मैसूर", "रवि", " "}, 
{ "Karnataka",  "3856",  "Mysore", "Ningappa B D", "NotGraduate",  " ","कर्नाटक",  "मैसूर", "निंगप्पा बी.डी.", " "}, 
{ "Karnataka",  "3857",  "Mysore", "N. Nagesh", "NotGraduate",  " ","कर्नाटक",  "मैसूर", "एन। नागेश", " "}, 
{ "Karnataka",  "3859",  "Mysore", "G.M. Mahadeva", "CriminalCases",  " ","कर्नाटक",  "मैसूर", "जीएम महादेवा", " "}, 
{ "Karnataka",  "3860",  "Mysore", "P.K. Biddappa", "NotGraduate",  " ","कर्नाटक",  "मैसूर", "पीके बिद्दप्पा", " "}, 
{ "Karnataka",  "3839",  "Mysore", "Srinivasaiah", "OverAged",  " ","कर्नाटक",  "मैसूर", "Srinivasaiah", " "}, 
{ "Karnataka",  "7117",  "Raichur", "K. Somashekhar Yadagiri", "NotGraduate",  " ","कर्नाटक",  "रायचूर", "के। सोमशेखर यादगिरी", " "}, 
{ "Karnataka",  "7119",  "Raichur", "B. V Naik", "ForeignFunding",  " ","कर्नाटक",  "रायचूर", "बी। वी। नाइक", " "}, 
{ "Karnataka",  "7121",  "Raichur", "Raja Amareshwara Naik", "ForeignFunding",  " ","कर्नाटक",  "रायचूर", "राजा अमरेश्वर नाइक", " "}, 
{ "Karnataka",  "7234",  "Shimoga", "Krishna K", "CriminalCases",  " ","कर्नाटक",  "शिमोगा", "कृष्ण के", " "}, 
{ "Karnataka",  "7235",  "Shimoga", "N.T.Vijayakumar", "NotGraduate",  " ","कर्नाटक",  "शिमोगा", "NTVijayakumar", " "}, 
{ "Karnataka",  "7236",  "Shimoga", "Mohammed Yusuf Khan", "NotGraduate",  " ","कर्नाटक",  "शिमोगा", "मोहम्मद यूसुफ खान", " "}, 
{ "Karnataka",  "7237",  "Shimoga", "S.Umesha Varma", "NotGraduate",  " ","कर्नाटक",  "शिमोगा", "एस.उमेश वर्मा", " "}, 
{ "Karnataka",  "7238",  "Shimoga", "S.Madhubangarappa", "CriminalCases",  " ","कर्नाटक",  "शिमोगा", "S.Madhubangarappa", " "}, 
{ "Karnataka",  "7239",  "Shimoga", "Shashikumar S.Gowda", "NotGraduate",  " ","कर्नाटक",  "शिमोगा", "शशिकुमार एस। गौड़ा", " "}, 
{ "Karnataka",  "7240",  "Shimoga", "B.Y.Raghavendra", "ForeignFunding",  " ","कर्नाटक",  "शिमोगा", "BYRaghavendra", " "}, 
{ "Karnataka",  "7241",  "Shimoga", "Guddappa", "CriminalCases",  " ","कर्नाटक",  "शिमोगा", "Guddappa", " "}, 
{ "Karnataka",  "7243",  "Shimoga", "Venkatesh R", "NotGraduate",  " ","कर्नाटक",  "शिमोगा", "वेंकटेश आर", " "}, 
{ "Karnataka",  "7245",  "Shimoga", "S.Umeshappa", "NotGraduate",  " ","कर्नाटक",  "शिमोगा", "S.Umeshappa", " "}, 
{ "Karnataka",  "3806",  "Tumkur", "T. N. Kumara Swamy", "NotGraduate",  " ","कर्नाटक",  "तुमकुर", "टीएन कुमारा स्वामी", " "}, 
{ "Karnataka",  "3807",  "Tumkur", "H. D. Devegowda", "OverAged",  " ","कर्नाटक",  "तुमकुर", "एचडी देवेगौड़ा", " "}, 
{ "Karnataka",  "3808",  "Tumkur", "B. S. Mallikarjunaiah", "CriminalCases",  " ","कर्नाटक",  "तुमकुर", "बीएस मल्लिकार्जुनैया", " "}, 
{ "Karnataka",  "3810",  "Tumkur", "J. K. Sami", "CriminalCases",  " ","कर्नाटक",  "तुमकुर", "जेके सामी", " "}, 
{ "Karnataka",  "3814",  "Tumkur", "G S Basavaraj", "ForeignFunding",  " ","कर्नाटक",  "तुमकुर", "जीएस बसवराज", " "}, 
{ "Karnataka",  "3815",  "Tumkur", "D Sharadhishayana", "OverAged",  " ","कर्नाटक",  "तुमकुर", "D शारदीयशायण", " "}, 
{ "Karnataka",  "3817",  "Tumkur", "G Nagendra", "NotGraduate",  " ","कर्नाटक",  "तुमकुर", "जी नागेंद्र", " "}, 
{ "Karnataka",  "3755",  "Udupi Chikmagalur", "Maggalamakki Ganesh", "NotGraduate",  " ","कर्नाटक",  "उडुपी चिकमगलूर", "मग्गलकमकी गणेश", " "}, 
{ "Karnataka",  "3756",  "Udupi Chikmagalur", "Shekar Havanje", "CriminalCases",  " ","कर्नाटक",  "उडुपी चिकमगलूर", "शेखर हवनजी", " "}, 
{ "Karnataka",  "3757",  "Udupi Chikmagalur", "Shobha Karandlaje", "ForeignFunding",  " ","कर्नाटक",  "उडुपी चिकमगलूर", "शोभा करंदलाजे", " "}, 
{ "Karnataka",  "3758",  "Udupi Chikmagalur", "Amrith Shenoy P", "CriminalCases",  " ","कर्नाटक",  "उडुपी चिकमगलूर", "अमृत शेनॉय पी", " "}, 
{ "Karnataka",  "3759",  "Udupi Chikmagalur", "Suresh Kunder", "NotGraduate",  " ","कर्नाटक",  "उडुपी चिकमगलूर", "सुरेश कुंदर", " "}, 
{ "Karnataka",  "3760",  "Udupi Chikmagalur", "Abdul Rahman", "NotGraduate",  " ","कर्नाटक",  "उडुपी चिकमगलूर", "अब्दुल रहमान", " "}, 
{ "Karnataka",  "3761",  "Udupi Chikmagalur", "Pramod Madhwaraj", "CriminalCases",  " ","कर्नाटक",  "उडुपी चिकमगलूर", "प्रमोद माधवराज", " "}, 
{ "Karnataka",  "3762",  "Udupi Chikmagalur", "P. Goutham Prabhu", "NotGraduate",  " ","कर्नाटक",  "उडुपी चिकमगलूर", "पी। गौतम प्रभु", " "}, 
{ "Karnataka",  "3763",  "Udupi Chikmagalur", "M.K Dayananda", "OverAged",  " ","कर्नाटक",  "उडुपी चिकमगलूर", "एमके दयानंद", " "}, 
{ "Karnataka",  "3764",  "Udupi Chikmagalur", "K.C. Prakash", "NotGraduate",  " ","कर्नाटक",  "उडुपी चिकमगलूर", "केसी प्रकाश", " "}, 
{ "Karnataka",  "3765",  "Udupi Chikmagalur", "P. Parameshwara", "CriminalCases",  " ","कर्नाटक",  "उडुपी चिकमगलूर", "पी। परमेस्वर", " "}, 
{ "Karnataka",  "3766",  "Udupi Chikmagalur", "Comrade Vijaykumar", "NotGraduate",  " ","कर्नाटक",  "उडुपी चिकमगलूर", "कामरेड विजयकुमार", " "}, 
{ "Karnataka",  "7197",  "Uttara Kannada", "Anand Asnotikar", "CriminalCases",  " ","कर्नाटक",  "उत्तर कन्नड़", "आनंद आसनटीकर", " "}, 
{ "Karnataka",  "7198",  "Uttara Kannada", "Nagaraj Anant Shirali", "NotGraduate",  " ","कर्नाटक",  "उत्तर कन्नड़", "नागराज अनंत शिराली", " "}, 
{ "Karnataka",  "7199",  "Uttara Kannada", "Mohammed Zabrood Khateeb", "CriminalCases",  " ","कर्नाटक",  "उत्तर कन्नड़", "मोहम्मद ज़बरूद खतीब", " "}, 
{ "Karnataka",  "7202",  "Uttara Kannada", "Nagraj Shridhar Shet", "NotGraduate",  " ","कर्नाटक",  "उत्तर कन्नड़", "नागराज श्रीधर शेट", " "}, 
{ "Karnataka",  "7203",  "Uttara Kannada", "Nagaraj Naik", "CriminalCases",  " ","कर्नाटक",  "उत्तर कन्नड़", "नागराज नाइक", " "}, 
{ "Karnataka",  "7205",  "Uttara Kannada", "Anita Ashok Shet", "NotGraduate",  " ","कर्नाटक",  "उत्तर कन्नड़", "अनीता अशोक शेट", " "}, 
{ "Karnataka",  "7206",  "Uttara Kannada", "Chidanand Harijan", "NotGraduate",  " ","कर्नाटक",  "उत्तर कन्नड़", "चिदानंद हरिजन", " "}, 
{ "Karnataka",  "7208",  "Uttara Kannada", "Anantkumar Hegde", "ForeignFunding",  " ","कर्नाटक",  "उत्तर कन्नड़", "अनंतकुमार हेगड़े", " "}, 
};

}