/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Kerala {
public static final String[][] green_bucket = {
        {"Kerala", "Alathur", "Dr.Jayan.C.Kuthanur", "Bahujan Samaj Party", "9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9260", "केरल", "अलथुर", "Dr.Jayan.C.Kuthanur", "बहुजन समाज पार्टी"},
        {"Kerala", "Alathur", "P.K.Biju", "Communist Party of India (Marxist)", "40.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9258", "केरल", "अलथुर", "PKBiju", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
        {"Kerala", "Alathur", "Pretheep Kumar P K", "Independent", "6.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9263", "केरल", "अलथुर", "प्रीतेप कुमार पीके", "निर्दलीय"},
        {"Kerala", "Attingal", "A.Sampath", "Communist Party of India (Marxist)", "3.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9107", "केरल", "अत्तिन्गल", "A.Sampath", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
        {"Kerala", "Attingal", "Anitha", "Independent", "25000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9110", "केरल", "अत्तिन्गल", "अनीता", "निर्दलीय"},
        {"Kerala", "Chalakudy", "Jose Thomas", "Marxist Communist Party of India (United)", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9133", "केरल", "चलाकुडी", "जोस थॉमस", "मार्क्सवादी कम्युनिस्ट पार्टी ऑफ़ इंडिया (यूनाइटेड)"},
        {"Kerala", "Chalakudy", "Sujatha N A", "Socialist Unity Centre of India (Communist)", "3.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9134", "केरल", "चलाकुडी", "सुजाथा एनए", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Kerala", "Ernakulam", "Aswathi Rajappan", "Independent", "2026", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8841", "केरल", "एर्नाकुलम", "असावती राजप्पन", "निर्दलीय"},
        {"Kerala", "Ernakulam", "Niamathulla", "Bahujan Samaj Party", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8840", "केरल", "एर्नाकुलम", "Niamathulla", "बहुजन समाज पार्टी"},
        {"Kerala", "Ernakulam", "Vivek K Vijayan", "Rashtriya Samaj Paksha", "35.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8834", "केरल", "एर्नाकुलम", "विवेक के विजयन", "राष्ट्रीय समाज पक्ष"},
        {"Kerala", "Idukki", "Leethesh P. T.", "Bahujan Samaj Party", "3.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8852", "केरल", "इडुक्की", "लेथेश पीटी", "बहुजन समाज पार्टी"},
        {"Kerala", "Idukki", "Biju Krishnan", "Bharath Dharma Jana Sena", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8846", "केरल", "इडुक्की", "बीजू कृष्णन", "भरत धर्म जन सेना"},
        {"Kerala", "Kannur", "Aparna R", "Socialist Unity Centre of India (Communist)", "7.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9163", "केरल", "कन्नूर", "अपर्णा आर", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Kerala", "Kannur", "Praveen Arimbrathodiyil", "Independent", "39.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9169", "केरल", "कन्नूर", "प्रवीण अरिमब्रतोदियिल", "निर्दलीय"},
        {"Kerala", "Kasaragod", "Adv. Basheer Alady", "Bahujan Samaj Party", "14.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10355", "केरल", "कासरगोड", "अभिभाषक। बशीर अलादी", "बहुजन समाज पार्टी"},
        {"Kerala", "Kollam", "Twinkle Prabhakaran", "Socialist Unity Centre of India (Communist)", "70150", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9097", "केरल", "कोल्लम", "ट्विंकल प्रभाकरन", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Kerala", "Kottayam", "Jijo Joseph", "Bahujan Samaj Party", "3.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8855", "केरल", "कोट्टायम", "जीजो जोसेफ", "बहुजन समाज पार्टी"},
        {"Kerala", "Kozhikode", "Raghu K", "Bahujan Samaj Party", "55.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9220", "केरल", "कोझिकोड", "रघु के", "बहुजन समाज पार्टी"},
        {"Kerala", "Malappuram", "Praveen Kumar", "Bahujan Samaj Party", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9234", "केरल", "मलप्पुरम", "प्रवीण कुमार", "बहुजन समाज पार्टी"},
        {"Kerala", "Mavelikkara", "Bimalji K", "Socialist Unity Centre of India (Communist)", "52486", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8861", "केरल", "मवेलीकारा", "बिमलजी के", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Kerala", "Pathanamthitta", "Veena George", "Communist Party of India (Marxist)", "2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9083", "केरल", "पथानामथिट्टा", "वीना जॉर्ज", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
        {"Kerala", "Ponnani", "Anwar P.V. Alumkuzhi", "Independent", "1.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9247", "केरल", "पोन्नानी", "अनवर पीवी अलुमकुज़ी", "निर्दलीय"},
        {"Kerala", "Thiruvananthapuram", "Jain Wilson", "Independent", "1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9275", "केरल", "तिरुवनंतपुरम", "जैन विल्सन", "निर्दलीय"},
        {"Kerala", "Thiruvananthapuram", "Vishnu S Ambadi", "Independent", "17.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9274", "केरल", "तिरुवनंतपुरम", "विष्णु एस अम्बादी", "निर्दलीय"},
        {"Kerala", "Thiruvananthapuram", "Mithra Kumar G", "Independent", "27.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9272", "केरल", "तिरुवनंतपुरम", "मिश्रा कुमार जी", "निर्दलीय"},
        {"Kerala", "Thrissur", "Rajaji Mathew Thomas", "Communist Party of India", "28.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9158", "केरल", "त्रिशूर", "राजाजी मैथ्यू थॉमस", "भारतीय कम्युनिस्ट पार्टी"},
        {"Kerala", "Thrissur", "Nikhil", "Bahujan Samaj Party", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9155", "केरल", "त्रिशूर", "निखिल", "बहुजन समाज पार्टी"},
        {"Kerala", "Vadakara", "K.Sudhakaran", "Communist Party of India (Marxist–Leninist) Red Star", "11Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9181", "केरल", "वाटकरा", "K.Sudhakaran", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) रेड स्टार"},
        {"Kerala", "Vadakara", "Musthafa Kommeri", "Social Democratic Party of India", "12.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10359", "केरल", "वाटकरा", "मुस्तफा कोमेरी", "सोशल डेमोक्रेटिक पार्टी ऑफ इंडिया"},
        {"Kerala", "Wayanad", "Rahul Gandhi K E S/O Valsamma", "Independent", "5515", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9215", "केरल", "वायनाड", "राहुल गांधी केईएस / ओ वलसम्मा", "निर्दलीय"},
        {"Kerala", "Wayanad", "John P P", "Secular Democratic Congress", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9207", "केरल", "वायनाड", "जॉन पीपी", "सेकुलर डेमोक्रेटिक कांग्रेस"},
        {"Kerala", "Wayanad", "Dr. K Padmarajan", "Independent", "15.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10362", "केरल", "वायनाड", "डॉ। के पद्मराजन", "निर्दलीय"},
        {"Kerala", "Wayanad", "K M Sivaprasad Gandhi", "Indian Gandhiyan Party", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9210", "केरल", "वायनाड", "केएम शिवप्रसाद गांधी", "भारतीय गांधीवादी पार्टी"},
        {"Kerala", "Wayanad", "P.P. Suneer", "Communist Party of India", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9200", "केरल", "वायनाड", "पीपी सुनीर", "भारतीय कम्युनिस्ट पार्टी"},
};

public static final String[][] red_bucket = {
        {"Kerala", "Alappuzha", "Santhosh", "4", " ", "केरल", "अलाप्पुझा", "संतोष", " "},
        {"Kerala", "Alappuzha", "Parthasarathy Varma", "4", " ", "केरल", "अलाप्पुझा", "पार्थसारथी वर्मा", " "},
        {"Kerala", "Alappuzha", "Rajeevan", "4", " ", "केरल", "अलाप्पुझा", "राजीवन", " "},
        {"Kerala", "Alappuzha", "A M Ariff", "2", " ", "केरल", "अलाप्पुझा", "एएम आरिफ", " "},
        {"Kerala", "Alappuzha", "Radhakrishnan", "1", " ", "केरल", "अलाप्पुझा", "राधाकृष्णन", " "},
        {"Kerala", "Alappuzha", "Akhilesh", "4", " ", "केरल", "अलाप्पुझा", "अखिलेश", " "},
        {"Kerala", "Alappuzha", "Varkala Raj", "4", " ", "केरल", "अलाप्पुझा", "वर्कला राज", " "},
        {"Kerala", "Alappuzha", "Satheesh Shenoy", "4", " ", "केरल", "अलाप्पुझा", "सतीश शेनॉय", " "},
        {"Kerala", "Alappuzha", "Prasanth", "2", " ", "केरल", "अलाप्पुझा", "प्रशांत", " "},
        {"Kerala", "Alappuzha", "Shan K S", "2", " ", "केरल", "अलाप्पुझा", "शान के.एस.", " "},
        {"Kerala", "Alappuzha", "Thahir", "4", " ", "केरल", "अलाप्पुझा", "Thahir", " "},
        {"Kerala", "Alappuzha", "Shanimol", "1", " ", "केरल", "अलाप्पुझा", "Shanimol", " "},
        {"Kerala", "Alathur", "Ramya P M", "1", " ", "केरल", "अलथुर", "राम्या पीएम", " "},
        {"Kerala", "Alathur", "Babu T V", "2", " ", "केरल", "अलथुर", "बाबू टी.वी.", " "},
        {"Kerala", "Alathur", "Krishnankutty", "4", " ", "केरल", "अलथुर", "Krishnankutty", " "},
        {"Kerala", "Attingal", "Vipinlal V A", "2", " ", "केरल", "अत्तिन्गल", "विपिनलाल वीए", " "},
        {"Kerala", "Attingal", "Devadathan", "3", " ", "केरल", "अत्तिन्गल", "Devadathan", " "},
        {"Kerala", "Attingal", "Manoj M", "4", " ", "केरल", "अत्तिन्गल", "मनोज एम", " "},
        {"Kerala", "Attingal", "P.Ramsagar", "4", " ", "केरल", "अत्तिन्गल", "P.Ramsagar", " "},
        {"Kerala", "Attingal", "K.G.Mohanan", "4", " ", "केरल", "अत्तिन्गल", "KGMohanan", " "},
        {"Kerala", "Attingal", "Maheen Thevarupara", "4", " ", "केरल", "अत्तिन्गल", "महेन थ्वारुपारा", " "},
        {"Kerala", "Attingal", "Vipinlal Palode", "2", " ", "केरल", "अत्तिन्गल", "विपिनलाल पालोडे", " "},
        {"Kerala", "Attingal", "Sunil Soman", "4", " ", "केरल", "अत्तिन्गल", "सुनील सोमन", " "},
        {"Kerala", "Attingal", "Vivekanandhan", "3", " ", "केरल", "अत्तिन्गल", "Vivekanandhan", " "},
        {"Kerala", "Attingal", "Ajmal Ismail", "2", " ", "केरल", "अत्तिन्गल", "अजमल इस्माइल", " "},
        {"Kerala", "Attingal", "Attingal Ajith Kumar", "4", " ", "केरल", "अत्तिन्गल", "अटल अजीत कुमार", " "},
        {"Kerala", "Attingal", "Irinjayam Suresh", "4", " ", "केरल", "अत्तिन्गल", "इरिंजयम सुरेश", " "},
        {"Kerala", "Attingal", "Prakash G", "4", " ", "केरल", "अत्तिन्गल", "प्रकाश जी", " "},
        {"Kerala", "Attingal", "Sobha Surendran", "1", " ", "केरल", "अत्तिन्गल", "सोभा सुरेंद्रन", " "},
        {"Kerala", "Attingal", "Adoor Prakash", "1", " ", "केरल", "अत्तिन्गल", "अदूर प्रकाश", " "},
        {"Kerala", "Attingal", "Shailaja", "4", " ", "केरल", "अत्तिन्गल", "शैलजा", " "},
        {"Kerala", "Attingal", "Satheesh Kumar", "4", " ", "केरल", "अत्तिन्गल", "सतीश कुमार", " "},
        {"Kerala", "Chalakudy", "Benny Behanan", "1", " ", "केरल", "चलाकुडी", "बेनी बिहानन", " "},
        {"Kerala", "Chalakudy", "Fredy Jackson Pereira", "4", " ", "केरल", "चलाकुडी", "फ्रेडी जैक्सन परेरा", " "},
        {"Kerala", "Chalakudy", "Subramanian", "4", " ", "केरल", "चलाकुडी", "सुब्रमण्यम", " "},
        {"Kerala", "Chalakudy", "Innocent", "3", " ", "केरल", "चलाकुडी", "मासूम", " "},
        {"Kerala", "Chalakudy", "Moideen Kunju P P", "2", " ", "केरल", "चलाकुडी", "मोइदीन कुंजु पीपी", " "},
        {"Kerala", "Chalakudy", "Radhakrishnan", "1", " ", "केरल", "चलाकुडी", "राधाकृष्णन", " "},
        {"Kerala", "Chalakudy", "Mujeeb Rahman T A", "4", " ", "केरल", "चलाकुडी", "मुजीब रहमान टीए", " "},
        {"Kerala", "Chalakudy", "Johnson N", "4", " ", "केरल", "चलाकुडी", "जॉनसन एन", " "},
        {"Kerala", "Ernakulam", "Laila Rasheed", "4", " ", "केरल", "एर्नाकुलम", "लैला रशीद", " "},
        {"Kerala", "Ernakulam", "Alphons Kannanthanam", "1", " ", "केरल", "एर्नाकुलम", "अल्फोंस कन्ननथनम", " "},
        {"Kerala", "Ernakulam", "Rajeev Nagan", "4", " ", "केरल", "एर्नाकुलम", "राजीव नागन", " "},
        {"Kerala", "Ernakulam", "Shajahan Abdulkhadar", "4", " ", "केरल", "एर्नाकुलम", "शाज़ान अब्दुलखादर", " "},
        {"Kerala", "Ernakulam", "Sreedharan", "3", " ", "केरल", "एर्नाकुलम", "श्रीधरन", " "},
        {"Kerala", "Ernakulam", "Abdul Khader", "4", " ", "केरल", "एर्नाकुलम", "अब्दुल खदर", " "},
        {"Kerala", "Ernakulam", "P Rajeev", "2", " ", "केरल", "एर्नाकुलम", "पी राजीव", " "},
        {"Kerala", "Ernakulam", "Kumar", "4", " ", "केरल", "एर्नाकुलम", "कुमार", " "},
        {"Kerala", "Ernakulam", "Hibi Eden", "1", " ", "केरल", "एर्नाकुलम", "हबी ईडन", " "},
        {"Kerala", "Idukki", "Joice George", "2", " ", "केरल", "इडुक्की", "जोर्ज जॉर्ज", " "},
        {"Kerala", "Idukki", "Dean Kuriakose", "1", " ", "केरल", "इडुक्की", "डीन कुरीकोज", " "},
        {"Kerala", "Idukki", "Baby K. A.", "4", " ", "केरल", "इडुक्की", "बेबी केए", " "},
        {"Kerala", "Idukki", "M. Selvaraj", "2", " ", "केरल", "इडुक्की", "एम। सेल्वराज", " "},
        {"Kerala", "Idukki", "Reji Njallani", "4", " ", "केरल", "इडुक्की", "रीजी नजलानी", " "},
        {"Kerala", "Idukki", "Gomathy", "2", " ", "केरल", "इडुक्की", "Gomathy", " "},
        {"Kerala", "Kannur", "Radhamani Narayanakumar", "4", " ", "केरल", "कन्नूर", "राधमनी नारायणकुमार", " "},
        {"Kerala", "Kannur", "K. Sreemathi W/O Sudeep Kumar C. V", "4", " ", "केरल", "कन्नूर", "के। सेरेमथी डब्ल्यू / ओ सुदीप कुमार सी। वी", " "},
        {"Kerala", "Kannur", "Abdul Jabbar K K", "2", " ", "केरल", "कन्नूर", "अब्दुल जब्बार के.के.", " "},
        {"Kerala", "Kannur", "Sudhakaran P. K S/O Krishna Pilla", "4", " ", "केरल", "कन्नूर", "सुधाकरन पी। केएस / ओ कृष्णा पिला", " "},
        {"Kerala", "Kannur", "Kuriakose", "4", " ", "केरल", "कन्नूर", "कुरिएकोस", " "},
        {"Kerala", "Kannur", "K Sudhakaran", "1", " ", "केरल", "कन्नूर", "के सुधाकरन", " "},
        {"Kerala", "Kannur", "P. Sreemathi W/O Raveendran", "4", " ", "केरल", "कन्नूर", "पी। सेरेमथी डब्ल्यू / ओ रवींद्रन", " "},
        {"Kerala", "Kannur", "K. Sudhakaran S/O Krishnan", "2", " ", "केरल", "कन्नूर", "के। सुधाकरन एस / ओ कृष्णन", " "},
        {"Kerala", "Kannur", "K. Sudhakaran S/O Kunhiraman", "3", " ", "केरल", "कन्नूर", "के। सुधाकरन एस / ओ कुनिरामन", " "},
        {"Kerala", "Kannur", "P K Sreemathi", "2", " ", "केरल", "कन्नूर", "पीके श्रीमाथी", " "},
        {"Kerala", "Kannur", "C K Padmanabhan", "1", " ", "केरल", "कन्नूर", "सीके पद्मनाभन", " "},
        {"Kerala", "Kasaragod", "Rameshan Bandadka", "4", " ", "केरल", "कासरगोड", "रमेश बांदका", " "},
        {"Kerala", "Kasaragod", "Rajmohan Unnithan", "1", " ", "केरल", "कासरगोड", "राजमोहन उन्नीथन", " "},
        {"Kerala", "Kasaragod", "Saji", "4", " ", "केरल", "कासरगोड", "साजी", " "},
        {"Kerala", "Kasaragod", "K P Sathishchnadran", "2", " ", "केरल", "कासरगोड", "केपी सतीशचंद्रन", " "},
        {"Kerala", "Kasaragod", "Narendra Kumar K", "2", " ", "केरल", "कासरगोड", "नरेंद्र कुमार के", " "},
        {"Kerala", "Kasaragod", "Ranadivan R K", "4", " ", "केरल", "कासरगोड", "राणादिवन आर.के.", " "},
        {"Kerala", "Kasaragod", "Ravish Thanthri Kuntar", "1", " ", "केरल", "कासरगोड", "रवीश थंथरी कुंतर", " "},
        {"Kerala", "Kasaragod", "Govindan B Alinthazhe", "4", " ", "केरल", "कासरगोड", "गोविंदन बी अलिन्थज़े", " "},
        {"Kerala", "Kollam", "Adv.K.V.Sabu", "1", " ", "केरल", "कोल्लम", "Adv.KVSabu", " "},
        {"Kerala", "Kollam", "Jayarajan", "4", " ", "केरल", "कोल्लम", "जयराजन", " "},
        {"Kerala", "Kollam", "Saji Kollam", "4", " ", "केरल", "कोल्लम", "साजी कोल्लम", " "},
        {"Kerala", "Kollam", "Suni Kalluvathukkal", "4", " ", "केरल", "कोल्लम", "सुनी कल्लूवथुक्कल", " "},
        {"Kerala", "Kollam", "Premachandran N K", "2", " ", "केरल", "कोल्लम", "प्रेमचंद्रन एन.के.", " "},
        {"Kerala", "Kollam", "Nagaraj G", "2", " ", "केरल", "कोल्लम", "नागराज जी", " "},
        {"Kerala", "Kollam", "K N Balagopal", "2", " ", "केरल", "कोल्लम", "केएन बालगोपाल", " "},
        {"Kerala", "Kottayam", "Thomas Chazhikadan", "3", " ", "केरल", "कोट्टायम", "थॉमस चाझिकादान", " "},
        {"Kerala", "Kottayam", "Prakash", "2", " ", "केरल", "कोट्टायम", "प्रकाश", " "},
        {"Kerala", "Kottayam", "Thomas J Nidhiry", "3", " ", "केरल", "कोट्टायम", "थॉमस जे निधिरि", " "},
        {"Kerala", "Kottayam", "P C Thomas", "2", " ", "केरल", "कोट्टायम", "पीसी थॉमस", " "},
        {"Kerala", "Kottayam", "Ignatious Illimoottil", "4", " ", "केरल", "कोट्टायम", "अज्ञानपूर्ण इल्म्युट्टिल", " "},
        {"Kerala", "Kottayam", "Vasavan", "4", " ", "केरल", "कोट्टायम", "Vasavan", " "},
        {"Kerala", "Kozhikode", "Pradeepan N", "4", " ", "केरल", "कोझिकोड", "प्रदीपन एन", " "},
        {"Kerala", "Kozhikode", "P Sankaran (A.Sekhar)", "3", " ", "केरल", "कोझिकोड", "पी शंकरन (ए.सेकर)", " "},
        {"Kerala", "Kozhikode", "Prakash Babu Chaithram", "4", " ", "केरल", "कोझिकोड", "प्रकाश बाबू चैथराम", " "},
        {"Kerala", "Kozhikode", "Adv.Prakash Babu", "1", " ", "केरल", "कोझिकोड", "सलाह.प्रकाश बाबू", " "},
        {"Kerala", "Kozhikode", "P. Raghavan", "3", " ", "केरल", "कोझिकोड", "पी। राघवन", " "},
        {"Kerala", "Kozhikode", "T. Raghavan", "4", " ", "केरल", "कोझिकोड", "टी। राघवन", " "},
        {"Kerala", "Kozhikode", "M.K.Raghavan", "1", " ", "केरल", "कोझिकोड", "MKRaghavan", " "},
        {"Kerala", "Kozhikode", "Pradeep.V.K", "4", " ", "केरल", "कोझिकोड", "Pradeep.VK", " "},
        {"Kerala", "Kozhikode", "Pradeep Kumar E T", "4", " ", "केरल", "कोझिकोड", "प्रदीप कुमार ईटी", " "},
        {"Kerala", "Kozhikode", "N. Raghavn", "3", " ", "केरल", "कोझिकोड", "एन। राघवन", " "},
        {"Kerala", "Kozhikode", "M.K. Raghavan Nair", "3", " ", "केरल", "कोझिकोड", "एमके राघवन नायर", " "},
        {"Kerala", "Kozhikode", "Nusrath Jahan", "4", " ", "केरल", "कोझिकोड", "नुसरत जहान", " "},
        {"Kerala", "Kozhikode", "A Pradeep Kumar", "2", " ", "केरल", "कोझिकोड", "एक प्रदीप कुमार", " "},
        {"Kerala", "Malappuram", "Sanu Nk", "4", " ", "केरल", "मलप्पुरम", "सानू एनके", " "},
        {"Kerala", "Malappuram", "Abdul Salam", "4", " ", "केरल", "मलप्पुरम", "अब्दुल सलाम", " "},
        {"Kerala", "Malappuram", "Kunhalikutty", "2", " ", "केरल", "मलप्पुरम", "कुन्हलिकुट्टी", " "},
        {"Kerala", "Malappuram", "Unnikrishnan", "1", " ", "केरल", "मलप्पुरम", "उन्नीकृष्णन", " "},
        {"Kerala", "Malappuram", "V.P. Sanu", "2", " ", "केरल", "मलप्पुरम", "वीपी सानू", " "},
        {"Kerala", "Malappuram", "Os Nissar Methar", "4", " ", "केरल", "मलप्पुरम", "ओएस निसार मेथर", " "},
        {"Kerala", "Malappuram", "Abdul Majeed Faizy", "2", " ", "केरल", "मलप्पुरम", "अब्दुल मजीद फैजी", " "},
        {"Kerala", "Mavelikkara", "Chittayam Gopakumar", "4", " ", "केरल", "मवेलीकारा", "चित्तम गोपकुमार", " "},
        {"Kerala", "Mavelikkara", "Rajagopalan", "4", " ", "केरल", "मवेलीकारा", "राजगोपालन", " "},
        {"Kerala", "Mavelikkara", "Usha", "4", " ", "केरल", "मवेलीकारा", "उषा", " "},
        {"Kerala", "Mavelikkara", "Ajayakumar", "4", " ", "केरल", "मवेलीकारा", "Ajayakumar", " "},
        {"Kerala", "Mavelikkara", "Raghavan R", "3", " ", "केरल", "मवेलीकारा", "राघवन आर", " "},
        {"Kerala", "Mavelikkara", "Kuttan K", "4", " ", "केरल", "मवेलीकारा", "कुट्टन के", " "},
        {"Kerala", "Mavelikkara", "Aji Pathanapuram", "4", " ", "केरल", "मवेलीकारा", "अजी पठानपुरम", " "},
        {"Kerala", "Mavelikkara", "Kodikunnil Suresh", "1", " ", "केरल", "मवेलीकारा", "कोडिकुन्निल सुरेश", " "},
        {"Kerala", "Mavelikkara", "Sahadevan", "4", " ", "केरल", "मवेलीकारा", "Sahadevan", " "},
        {"Kerala", "Palakkad", "V K Sreekandan", "1", " ", "केरल", "पलक्कड़", "वीके श्रीकंदन", " "},
        {"Kerala", "Palakkad", "Rajesh S/O Mani", "2", " ", "केरल", "पलक्कड़", "राजेश एस / ओ मणि", " "},
        {"Kerala", "Palakkad", "C Chandran", "4", " ", "केरल", "पलक्कड़", "C चंद्रन", " "},
        {"Kerala", "Palakkad", "P Rajesh", "4", " ", "केरल", "पलक्कड़", "पी राजेश", " "},
        {"Kerala", "Palakkad", "Krishnakumar C", "1", " ", "केरल", "पलक्कड़", "कृष्णकुमार सी", " "},
        {"Kerala", "Palakkad", "M B Rajesh", "2", " ", "केरल", "पलक्कड़", "एमबी राजेश", " "},
        {"Kerala", "Palakkad", "Thulaseedharan", "2", " ", "केरल", "पलक्कड़", "Thulaseedharan", " "},
        {"Kerala", "Palakkad", "Balakrishnan", "4", " ", "केरल", "पलक्कड़", "बालाकृष्णन", " "},
        {"Kerala", "Pathanamthitta", "Shibu P", "4", " ", "केरल", "पथानामथिट्टा", "शिबू पी", " "},
        {"Kerala", "Pathanamthitta", "Ratheesh Kumar R", "4", " ", "केरल", "पथानामथिट्टा", "रत्नेश कुमार आर", " "},
        {"Kerala", "Pathanamthitta", "Veena V", "4", " ", "केरल", "पथानामथिट्टा", "वीना वी", " "},
        {"Kerala", "Pathanamthitta", "K Surendran", "1", " ", "केरल", "पथानामथिट्टा", "के सुरेंद्रन", " "},
        {"Kerala", "Pathanamthitta", "Anto Antony", "1", " ", "केरल", "पथानामथिट्टा", "एंटो एंटनी", " "},
        {"Kerala", "Pathanamthitta", "Binu", "4", " ", "केरल", "पथानामथिट्टा", "बीनू", " "},
        {"Kerala", "Pathanamthitta", "Jose George", "4", " ", "केरल", "पथानामथिट्टा", "जोस जॉर्ज", " "},
        {"Kerala", "Ponnani", "Rema", "1", " ", "केरल", "पोन्नानी", "Rema", " "},
        {"Kerala", "Ponnani", "Sameera Pa", "4", " ", "केरल", "पोन्नानी", "समीरा पा", " "},
        {"Kerala", "Ponnani", "Muhammed Basheer Koyissery", "3", " ", "केरल", "पोन्नानी", "मुहम्मद बशीर कोइरीज़ीन", " "},
        {"Kerala", "Ponnani", "Muhammed Basheer Mangalassery", "4", " ", "केरल", "पोन्नानी", "मुहम्मद बशीर मंगलसरी", " "},
        {"Kerala", "Ponnani", "Poonthura Siraj", "4", " ", "केरल", "पोन्नानी", "पूनतुरा सिराज", " "},
        {"Kerala", "Ponnani", "Muhammed Basheer Nechiyan", "4", " ", "केरल", "पोन्नानी", "मुहम्मद बशीर नेचियान", " "},
        {"Kerala", "Ponnani", "Adv. K.C. Nazeer", "2", " ", "केरल", "पोन्नानी", "अभिभाषक। केसी नाज़ेर", " "},
        {"Kerala", "Ponnani", "Anvar P.V. Raseena Manzil", "4", " ", "केरल", "पोन्नानी", "अनवर पीवी रसेना मैन्ज़िल", " "},
        {"Kerala", "Ponnani", "Bindu", "4", " ", "केरल", "पोन्नानी", "बिन्दु", " "},
        {"Kerala", "Ponnani", "E T Mohammed Basheer", "3", " ", "केरल", "पोन्नानी", "ईटी मोहम्मद बशीर", " "},
        {"Kerala", "Thiruvananthapuram", "Shashi Tharoor", "1", " ", "केरल", "तिरुवनंतपुरम", "शशि थरूर", " "},
        {"Kerala", "Thiruvananthapuram", "Sasi T", "3", " ", "केरल", "तिरुवनंतपुरम", "ससी टी", " "},
        {"Kerala", "Thiruvananthapuram", "Gopakumar", "4", " ", "केरल", "तिरुवनंतपुरम", "Gopakumar", " "},
        {"Kerala", "Thiruvananthapuram", "Johny Thampy", "2", " ", "केरल", "तिरुवनंतपुरम", "जॉनी थम्पी", " "},
        {"Kerala", "Thiruvananthapuram", "Mini S", "2", " ", "केरल", "तिरुवनंतपुरम", "मिनी एस", " "},
        {"Kerala", "Thiruvananthapuram", "Binu.D", "4", " ", "केरल", "तिरुवनंतपुरम", "Binu.D", " "},
        {"Kerala", "Thiruvananthapuram", "Subi", "4", " ", "केरल", "तिरुवनंतपुरम", "Subi", " "},
        {"Kerala", "Thiruvananthapuram", "Kirankumar.S.K", "4", " ", "केरल", "तिरुवनंतपुरम", "Kirankumar.SK", " "},
        {"Kerala", "Thiruvananthapuram", "Kummanam Rajasekharan", "1", " ", "केरल", "तिरुवनंतपुरम", "कुम्मनम राजशेखरन", " "},
        {"Kerala", "Thiruvananthapuram", "S Suseelan", "2", " ", "केरल", "तिरुवनंतपुरम", "S सूसीलन", " "},
        {"Kerala", "Thiruvananthapuram", "P Keralavarmaraja", "3", " ", "केरल", "तिरुवनंतपुरम", "पी। केरलवर्मराज", " "},
        {"Kerala", "Thiruvananthapuram", "Christopher Shaju", "4", " ", "केरल", "तिरुवनंतपुरम", "क्रिस्टोफर शजू", " "},
        {"Kerala", "Thiruvananthapuram", "Devadathan", "3", " ", "केरल", "तिरुवनंतपुरम", "Devadathan", " "},
        {"Kerala", "Thiruvananthapuram", "Divakaran.C", "2", " ", "केरल", "तिरुवनंतपुरम", "Divakaran.C", " "},
        {"Kerala", "Thrissur", "Suvith", "2", " ", "केरल", "त्रिशूर", "Suvith", " "},
        {"Kerala", "Thrissur", "Suresh Gopi", "1", " ", "केरल", "त्रिशूर", "सुरेश गोपी", " "},
        {"Kerala", "Thrissur", "T. N. Prathapan", "1", " ", "केरल", "त्रिशूर", "टीएन प्रतापन", " "},
        {"Kerala", "Thrissur", "N D Venu", "2", " ", "केरल", "त्रिशूर", "एनडी वेणु", " "},
        {"Kerala", "Thrissur", "Sonu", "2", " ", "केरल", "त्रिशूर", "सोनू", " "},
        {"Kerala", "Thrissur", "Praveen K P", "2", " ", "केरल", "त्रिशूर", "प्रवीण के.पी.", " "},
        {"Kerala", "Vadakara", "Jatheesh A P", "4", " ", "केरल", "वाटकरा", "जथेश एपी", " "},
        {"Kerala", "Vadakara", "Aluva Aneesh", "4", " ", "केरल", "वाटकरा", "अलुवा अनीश", " "},
        {"Kerala", "Vadakara", "C.O.T. Naseer", "2", " ", "केरल", "वाटकरा", "COT नसीर", " "},
        {"Kerala", "Vadakara", "K. Muraleedharan", "1", " ", "केरल", "वाटकरा", "के मुरलीधरन", " "},
        {"Kerala", "Vadakara", "Muraleedharan.K Kuttiyil Veedu", "4", " ", "केरल", "वाटकरा", "मुरलीधरन। के। कुटियाल विडू", " "},
        {"Kerala", "Vadakara", "Jayarajan Pandaraparambil", "3", " ", "केरल", "वाटकरा", "जयराजन पंडरापरांबिल", " "},
        {"Kerala", "Vadakara", "Santosh Kumar", "4", " ", "केरल", "वाटकरा", "संतोष कुमार", " "},
        {"Kerala", "Vadakara", "Jayarajan.P", "2", " ", "केरल", "वाटकरा", "Jayarajan.P", " "},
        {"Kerala", "Vadakara", "Muraleedharan.K Sandram", "4", " ", "केरल", "वाटकरा", "मुरलीधरन। के। संद्रम", " "},
        {"Kerala", "Vadakara", "Sajeevan V. K", "1", " ", "केरल", "वाटकरा", "सजीवन वी। के", " "},
        {"Kerala", "Wayanad", "Narukara Gopi", "2", " ", "केरल", "वायनाड", "नरुकरा गोपी", " "},
        {"Kerala", "Wayanad", "Siby Vayalil", "4", " ", "केरल", "वायनाड", "सिबि वायलिल", " "},
        {"Kerala", "Wayanad", "Raghul Gandhi K S/O Krishnan P", "4", " ", "केरल", "वायनाड", "रघुल गांधी केएस / ओ कृष्णन पी", " "},
        {"Kerala", "Wayanad", "Shijo M Varghese", "4", " ", "केरल", "वायनाड", "शिजो एम वर्गीज", " "},
        {"Kerala", "Wayanad", "Adv. Sreejith P R", "2", " ", "केरल", "वायनाड", "अभिभाषक। श्रीजिथ पीआर", " "},
        {"Kerala", "Wayanad", "Rahul Gandhi", "1", " ", "केरल", "वायनाड", "राहुल गांधी", " "},
        {"Kerala", "Wayanad", "Babu Mani", "2", " ", "केरल", "वायनाड", "बाबू मणि", " "},
        {"Kerala", "Wayanad", "Praveen K P", "2", " ", "केरल", "वायनाड", "प्रवीण के.पी.", " "},
        {"Kerala", "Wayanad", "Mujeeb Rahman", "4", " ", "केरल", "वायनाड", "मुजीब रहमान", " "},
        {"Kerala", "Wayanad", "Biju Kakkathode", "4", " ", "केरल", "वायनाड", "बीजू कक्क्ठोडे", " "},
        {"Kerala", "Wayanad", "Mohamed P K", "3", " ", "केरल", "वायनाड", "मोहम्मद पी.के.", " "},
        {"Kerala", "Wayanad", "Usha K", "4", " ", "केरल", "वायनाड", "उषा के", " "},
        {"Kerala", "Wayanad", "Sebastian Wayanad", "4", " ", "केरल", "वायनाड", "सेबस्टियन वायनाड", " "},
        {"Kerala", "Wayanad", "Thrissur Nazeer", "4", " ", "केरल", "वायनाड", "त्रिशूर नाज़ेर", " "},
};

}