/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Kerala {
public static final String[][] green_bucket = {
{"Kerala",  "7327", "Alathur", "Dr.Jayan.C.Kuthanur", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9260",  "केरल",  "अलथुर", "Dr.Jayan.C.Kuthanur", "बहुजन समाज पार्टी", ""}, 
{"Kerala",  "7329", "Alathur", "P.K.Biju", "Communist Party of India (Marxist)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9258",  "केरल",  "अलथुर", "PKBiju", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)", ""}, 
{"Kerala",  "7330", "Alathur", "Pretheep Kumar P K", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9263",  "केरल",  "अलथुर", "प्रीतेप कुमार पीके", "निर्दलीय", ""}, 
{"Kerala",  "4013", "Attingal", "A.Sampath", "Communist Party of India (Marxist)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9107",  "केरल",  "अत्तिन्गल", "A.Sampath", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)", ""}, 
{"Kerala",  "7409", "Attingal", "Anitha", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9110",  "केरल",  "अत्तिन्गल", "अनीता", "निर्दलीय", ""}, 
{"Kerala",  "7342", "Chalakudy", "Jose Thomas", "Marxist Communist Party of India (United)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9133",  "केरल",  "चलाकुडी", "जोस थॉमस", "मार्क्सवादी कम्युनिस्ट पार्टी ऑफ़ इंडिया (यूनाइटेड)", ""}, 
{"Kerala",  "7345", "Chalakudy", "Sujatha N A", "Socialist Unity Centre of India (Communist)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9134",  "केरल",  "चलाकुडी", "सुजाथा एनए", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Kerala",  "4006", "Ernakulam", "Aswathi Rajappan", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8841",  "केरल",  "एर्नाकुलम", "असावती राजप्पन", "निर्दलीय", ""}, 
{"Kerala",  "7355", "Ernakulam", "Niamathulla", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8840",  "केरल",  "एर्नाकुलम", "Niamathulla", "बहुजन समाज पार्टी", ""}, 
{"Kerala",  "7356", "Ernakulam", "Vivek K Vijayan", "Rashtriya Samaj Paksha", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8834",  "केरल",  "एर्नाकुलम", "विवेक के विजयन", "राष्ट्रीय समाज पक्ष", ""}, 
{"Kerala",  "7362", "Idukki", "Leethesh P. T.", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8852",  "केरल",  "इडुक्की", "लेथेश पीटी", "बहुजन समाज पार्टी", ""}, 
{"Kerala",  "7364", "Idukki", "Biju Krishnan", "Bharath Dharma Jana Sena", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8846",  "केरल",  "इडुक्की", "बीजू कृष्णन", "", ""}, 
{"Kerala",  "7262", "Kannur", "Aparna R", "Socialist Unity Centre of India (Communist)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9163",  "केरल",  "कन्नूर", "अपर्णा आर", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Kerala",  "7266", "Kannur", "Praveen Arimbrathodiyil", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9169",  "केरल",  "कन्नूर", "प्रवीण अरिमब्रतोदियिल", "निर्दलीय", ""}, 
{"Kerala",  "7246", "Kasaragod", "Adv. Basheer Alady", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10355",  "केरल",  "कासरगोड", "अभिभाषक। बशीर अलादी", "बहुजन समाज पार्टी", ""}, 
{"Kerala",  "7402", "Kollam", "Twinkle Prabhakaran", "Socialist Unity Centre of India (Communist)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9097",  "केरल",  "कोल्लम", "ट्विंकल प्रभाकरन", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Kerala",  "7370", "Kottayam", "Jijo Joseph", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8855",  "केरल",  "कोट्टायम", "जीजो जोसेफ", "बहुजन समाज पार्टी", ""}, 
{"Kerala",  "3992", "Kozhikode", "Raghu K", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9220",  "केरल",  "कोझिकोड", "रघु के", "बहुजन समाज पार्टी", ""}, 
{"Kerala",  "7314", "Malappuram", "Praveen Kumar", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9234",  "केरल",  "मलप्पुरम", "प्रवीण कुमार", "बहुजन समाज पार्टी", ""}, 
{"Kerala",  "7389", "Mavelikkara", "Bimalji K", "Socialist Unity Centre of India (Communist)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8861",  "केरल",  "मवेलीकारा", "बिमलजी के", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Kerala",  "7391", "Pathanamthitta", "Veena George", "Communist Party of India (Marxist)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9083",  "केरल",  "पथानामथिट्टा", "वीना जॉर्ज", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)", ""}, 
{"Kerala",  "3994", "Ponnani", "Anwar P.V. Alumkuzhi", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9247",  "केरल",  "पोन्नानी", "अनवर पीवी अलुमकुज़ी", "निर्दलीय", ""}, 
{"Kerala",  "4017", "Thiruvananthapuram", "Jain Wilson", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9275",  "केरल",  "तिरुवनंतपुरम", "जैन विल्सन", "निर्दलीय", ""}, 
{"Kerala",  "4022", "Thiruvananthapuram", "Vishnu S Ambadi", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9274",  "केरल",  "तिरुवनंतपुरम", "विष्णु एस अम्बादी", "निर्दलीय", ""}, 
{"Kerala",  "4029", "Thiruvananthapuram", "Mithra Kumar G", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9272",  "केरल",  "तिरुवनंतपुरम", "मिश्रा कुमार जी", "निर्दलीय", ""}, 
{"Kerala",  "4003", "Thrissur", "Rajaji Mathew Thomas", "Communist Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9158",  "केरल",  "त्रिशूर", "राजाजी मैथ्यू थॉमस", "भारतीय कम्युनिस्ट पार्टी", ""}, 
{"Kerala",  "7334", "Thrissur", "Nikhil", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9155",  "केरल",  "त्रिशूर", "निखिल", "बहुजन समाज पार्टी", ""}, 
{"Kerala",  "7267", "Vadakara", "K.Sudhakaran", "Communist Party of India (Marxist–Leninist) Red Star", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9181",  "केरल",  "वाटकरा", "K.Sudhakaran", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) रेड स्टार", ""}, 
{"Kerala",  "7273", "Vadakara", "Musthafa Kommeri", "Social Democratic Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10359",  "केरल",  "वाटकरा", "मुस्तफा कोमेरी", "सोशल डेमोक्रेटिक पार्टी ऑफ इंडिया", ""}, 
{"Kerala",  "7281", "Wayanad", "Rahul Gandhi K E S/O Valsamma", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9215",  "केरल",  "वायनाड", "राहुल गांधी केईएस / ओ वलसम्मा", "निर्दलीय", ""}, 
{"Kerala",  "7283", "Wayanad", "John P P", "Secular Democratic Congress", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9207",  "केरल",  "वायनाड", "जॉन पीपी", "सेकुलर डेमोक्रेटिक कांग्रेस", ""}, 
{"Kerala",  "7284", "Wayanad", "Dr. K Padmarajan", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10362",  "केरल",  "वायनाड", "डॉ। के पद्मराजन", "निर्दलीय", ""}, 
{"Kerala",  "7286", "Wayanad", "K M Sivaprasad Gandhi", "Indian Gandhiyan Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9210",  "केरल",  "वायनाड", "केएम शिवप्रसाद गांधी", "", ""}, 
{"Kerala",  "7294", "Wayanad", "P.P. Suneer", "Communist Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9200",  "केरल",  "वायनाड", "पीपी सुनीर", "भारतीय कम्युनिस्ट पार्टी", ""}, 
};

public static final String[][] red_bucket = {
{ "Kerala",  "7374",  "Alappuzha", "Santhosh", "NotGraduate",  " ","केरल",  "अलाप्पुझा", "संतोष", " "}, 
{ "Kerala",  "7375",  "Alappuzha", "Parthasarathy Varma", "NotGraduate",  " ","केरल",  "अलाप्पुझा", "पार्थसारथी वर्मा", " "}, 
{ "Kerala",  "7376",  "Alappuzha", "Rajeevan", "NotGraduate",  " ","केरल",  "अलाप्पुझा", "राजीवन", " "}, 
{ "Kerala",  "7377",  "Alappuzha", "A M Ariff", "CriminalCases",  " ","केरल",  "अलाप्पुझा", "एएम आरिफ", " "}, 
{ "Kerala",  "7378",  "Alappuzha", "Radhakrishnan", "ForeignFunding",  " ","केरल",  "अलाप्पुझा", "राधाकृष्णन", " "}, 
{ "Kerala",  "7379",  "Alappuzha", "Akhilesh", "NotGraduate",  " ","केरल",  "अलाप्पुझा", "अखिलेश", " "}, 
{ "Kerala",  "7380",  "Alappuzha", "Varkala Raj", "NotGraduate",  " ","केरल",  "अलाप्पुझा", "वर्कला राज", " "}, 
{ "Kerala",  "7381",  "Alappuzha", "Satheesh Shenoy", "NotGraduate",  " ","केरल",  "अलाप्पुझा", "सतीश शेनॉय", " "}, 
{ "Kerala",  "7382",  "Alappuzha", "Prasanth", "CriminalCases",  " ","केरल",  "अलाप्पुझा", "प्रशांत", " "}, 
{ "Kerala",  "7383",  "Alappuzha", "Shan K S", "CriminalCases",  " ","केरल",  "अलाप्पुझा", "शान के.एस.", " "}, 
{ "Kerala",  "7384",  "Alappuzha", "Thahir", "NotGraduate",  " ","केरल",  "अलाप्पुझा", "Thahir", " "}, 
{ "Kerala",  "7385",  "Alappuzha", "Shanimol", "ForeignFunding",  " ","केरल",  "अलाप्पुझा", "Shanimol", " "}, 
{ "Kerala",  "7328",  "Alathur", "Ramya P M", "ForeignFunding",  " ","केरल",  "अलथुर", "राम्या पीएम", " "}, 
{ "Kerala",  "7331",  "Alathur", "Babu T V", "CriminalCases",  " ","केरल",  "अलथुर", "बाबू टी.वी.", " "}, 
{ "Kerala",  "7332",  "Alathur", "Krishnankutty", "NotGraduate",  " ","केरल",  "अलथुर", "Krishnankutty", " "}, 
{ "Kerala",  "4014",  "Attingal", "Vipinlal V A", "CriminalCases",  " ","केरल",  "अत्तिन्गल", "विपिनलाल वीए", " "}, 
{ "Kerala",  "7406",  "Attingal", "Devadathan", "OverAged",  " ","केरल",  "अत्तिन्गल", "Devadathan", " "}, 
{ "Kerala",  "7407",  "Attingal", "Manoj M", "NotGraduate",  " ","केरल",  "अत्तिन्गल", "मनोज एम", " "}, 
{ "Kerala",  "7408",  "Attingal", "P.Ramsagar", "NotGraduate",  " ","केरल",  "अत्तिन्गल", "P.Ramsagar", " "}, 
{ "Kerala",  "7410",  "Attingal", "K.G.Mohanan", "NotGraduate",  " ","केरल",  "अत्तिन्गल", "KGMohanan", " "}, 
{ "Kerala",  "7411",  "Attingal", "Maheen Thevarupara", "NotGraduate",  " ","केरल",  "अत्तिन्गल", "महेन थ्वारुपारा", " "}, 
{ "Kerala",  "7412",  "Attingal", "Vipinlal Palode", "CriminalCases",  " ","केरल",  "अत्तिन्गल", "विपिनलाल पालोडे", " "}, 
{ "Kerala",  "7413",  "Attingal", "Sunil Soman", "NotGraduate",  " ","केरल",  "अत्तिन्गल", "सुनील सोमन", " "}, 
{ "Kerala",  "7414",  "Attingal", "Vivekanandhan", "OverAged",  " ","केरल",  "अत्तिन्गल", "Vivekanandhan", " "}, 
{ "Kerala",  "7415",  "Attingal", "Ajmal Ismail", "CriminalCases",  " ","केरल",  "अत्तिन्गल", "अजमल इस्माइल", " "}, 
{ "Kerala",  "7416",  "Attingal", "Attingal Ajith Kumar", "NotGraduate",  " ","केरल",  "अत्तिन्गल", "अटल अजीत कुमार", " "}, 
{ "Kerala",  "7417",  "Attingal", "Irinjayam Suresh", "NotGraduate",  " ","केरल",  "अत्तिन्गल", "इरिंजयम सुरेश", " "}, 
{ "Kerala",  "7418",  "Attingal", "Prakash G", "NotGraduate",  " ","केरल",  "अत्तिन्गल", "प्रकाश जी", " "}, 
{ "Kerala",  "7419",  "Attingal", "Sobha Surendran", "ForeignFunding",  " ","केरल",  "अत्तिन्गल", "सोभा सुरेंद्रन", " "}, 
{ "Kerala",  "7420",  "Attingal", "Adoor Prakash", "ForeignFunding",  " ","केरल",  "अत्तिन्गल", "अदूर प्रकाश", " "}, 
{ "Kerala",  "7421",  "Attingal", "Shailaja", "NotGraduate",  " ","केरल",  "अत्तिन्गल", "शैलजा", " "}, 
{ "Kerala",  "7422",  "Attingal", "Satheesh Kumar", "NotGraduate",  " ","केरल",  "अत्तिन्गल", "सतीश कुमार", " "}, 
{ "Kerala",  "7340",  "Chalakudy", "Benny Behanan", "ForeignFunding",  " ","केरल",  "चलाकुडी", "बेनी बिहानन", " "}, 
{ "Kerala",  "7341",  "Chalakudy", "Fredy Jackson Pereira", "NotGraduate",  " ","केरल",  "चलाकुडी", "फ्रेडी जैक्सन परेरा", " "}, 
{ "Kerala",  "7343",  "Chalakudy", "Subramanian", "NotGraduate",  " ","केरल",  "चलाकुडी", "सुब्रमण्यम", " "}, 
{ "Kerala",  "7344",  "Chalakudy", "Innocent", "OverAged",  " ","केरल",  "चलाकुडी", "मासूम", " "}, 
{ "Kerala",  "7346",  "Chalakudy", "Moideen Kunju P P", "CriminalCases",  " ","केरल",  "चलाकुडी", "मोइदीन कुंजु पीपी", " "}, 
{ "Kerala",  "7347",  "Chalakudy", "Radhakrishnan", "ForeignFunding",  " ","केरल",  "चलाकुडी", "राधाकृष्णन", " "}, 
{ "Kerala",  "7348",  "Chalakudy", "Mujeeb Rahman T A", "NotGraduate",  " ","केरल",  "चलाकुडी", "मुजीब रहमान टीए", " "}, 
{ "Kerala",  "7349",  "Chalakudy", "Johnson N", "NotGraduate",  " ","केरल",  "चलाकुडी", "जॉनसन एन", " "}, 
{ "Kerala",  "4004",  "Ernakulam", "Laila Rasheed", "NotGraduate",  " ","केरल",  "एर्नाकुलम", "लैला रशीद", " "}, 
{ "Kerala",  "4005",  "Ernakulam", "Alphons Kannanthanam", "ForeignFunding",  " ","केरल",  "एर्नाकुलम", "अल्फोंस कन्ननथनम", " "}, 
{ "Kerala",  "7350",  "Ernakulam", "Rajeev Nagan", "NotGraduate",  " ","केरल",  "एर्नाकुलम", "राजीव नागन", " "}, 
{ "Kerala",  "7351",  "Ernakulam", "Shajahan Abdulkhadar", "NotGraduate",  " ","केरल",  "एर्नाकुलम", "शाज़ान अब्दुलखादर", " "}, 
{ "Kerala",  "7352",  "Ernakulam", "Sreedharan", "OverAged",  " ","केरल",  "एर्नाकुलम", "श्रीधरन", " "}, 
{ "Kerala",  "7353",  "Ernakulam", "Abdul Khader", "NotGraduate",  " ","केरल",  "एर्नाकुलम", "अब्दुल खदर", " "}, 
{ "Kerala",  "7354",  "Ernakulam", "P Rajeev", "CriminalCases",  " ","केरल",  "एर्नाकुलम", "पी राजीव", " "}, 
{ "Kerala",  "7357",  "Ernakulam", "Kumar", "NotGraduate",  " ","केरल",  "एर्नाकुलम", "कुमार", " "}, 
{ "Kerala",  "7358",  "Ernakulam", "Hibi Eden", "ForeignFunding",  " ","केरल",  "एर्नाकुलम", "हबी ईडन", " "}, 
{ "Kerala",  "7359",  "Idukki", "Joice George", "CriminalCases",  " ","केरल",  "इडुक्की", "जोर्ज जॉर्ज", " "}, 
{ "Kerala",  "7360",  "Idukki", "Dean Kuriakose", "ForeignFunding",  " ","केरल",  "इडुक्की", "डीन कुरीकोज", " "}, 
{ "Kerala",  "7361",  "Idukki", "Baby K. A.", "NotGraduate",  " ","केरल",  "इडुक्की", "बेबी केए", " "}, 
{ "Kerala",  "7363",  "Idukki", "M. Selvaraj", "CriminalCases",  " ","केरल",  "इडुक्की", "एम। सेल्वराज", " "}, 
{ "Kerala",  "7365",  "Idukki", "Reji Njallani", "NotGraduate",  " ","केरल",  "इडुक्की", "रीजी नजलानी", " "}, 
{ "Kerala",  "7366",  "Idukki", "Gomathy", "CriminalCases",  " ","केरल",  "इडुक्की", "Gomathy", " "}, 
{ "Kerala",  "7255",  "Kannur", "Radhamani Narayanakumar", "NotGraduate",  " ","केरल",  "कन्नूर", "राधमनी नारायणकुमार", " "}, 
{ "Kerala",  "7256",  "Kannur", "K. Sreemathi W/O Sudeep Kumar C. V", "NotGraduate",  " ","केरल",  "कन्नूर", "के। सेरेमथी डब्ल्यू / ओ सुदीप कुमार सी। वी", " "}, 
{ "Kerala",  "7257",  "Kannur", "Abdul Jabbar K K", "CriminalCases",  " ","केरल",  "कन्नूर", "अब्दुल जब्बार के.के.", " "}, 
{ "Kerala",  "7258",  "Kannur", "Sudhakaran P. K S/O Krishna Pilla", "NotGraduate",  " ","केरल",  "कन्नूर", "सुधाकरन पी। केएस / ओ कृष्णा पिला", " "}, 
{ "Kerala",  "7259",  "Kannur", "Kuriakose", "NotGraduate",  " ","केरल",  "कन्नूर", "कुरिएकोस", " "}, 
{ "Kerala",  "7260",  "Kannur", "K Sudhakaran", "ForeignFunding",  " ","केरल",  "कन्नूर", "के सुधाकरन", " "}, 
{ "Kerala",  "7261",  "Kannur", "P. Sreemathi W/O Raveendran", "NotGraduate",  " ","केरल",  "कन्नूर", "पी। सेरेमथी डब्ल्यू / ओ रवींद्रन", " "}, 
{ "Kerala",  "7263",  "Kannur", "K. Sudhakaran S/O Krishnan", "CriminalCases",  " ","केरल",  "कन्नूर", "के। सुधाकरन एस / ओ कृष्णन", " "}, 
{ "Kerala",  "7264",  "Kannur", "K. Sudhakaran S/O Kunhiraman", "OverAged",  " ","केरल",  "कन्नूर", "के। सुधाकरन एस / ओ कुनिरामन", " "}, 
{ "Kerala",  "7265",  "Kannur", "P K Sreemathi", "CriminalCases",  " ","केरल",  "कन्नूर", "पीके श्रीमाथी", " "}, 
{ "Kerala",  "3990",  "Kannur", "C K Padmanabhan", "ForeignFunding",  " ","केरल",  "कन्नूर", "सीके पद्मनाभन", " "}, 
{ "Kerala",  "7247",  "Kasaragod", "Rameshan Bandadka", "NotGraduate",  " ","केरल",  "कासरगोड", "रमेश बांदका", " "}, 
{ "Kerala",  "7248",  "Kasaragod", "Rajmohan Unnithan", "ForeignFunding",  " ","केरल",  "कासरगोड", "राजमोहन उन्नीथन", " "}, 
{ "Kerala",  "7249",  "Kasaragod", "Saji", "NotGraduate",  " ","केरल",  "कासरगोड", "साजी", " "}, 
{ "Kerala",  "7250",  "Kasaragod", "K P Sathishchnadran", "CriminalCases",  " ","केरल",  "कासरगोड", "केपी सतीशचंद्रन", " "}, 
{ "Kerala",  "7251",  "Kasaragod", "Narendra Kumar K", "CriminalCases",  " ","केरल",  "कासरगोड", "नरेंद्र कुमार के", " "}, 
{ "Kerala",  "7252",  "Kasaragod", "Ranadivan R K", "NotGraduate",  " ","केरल",  "कासरगोड", "राणादिवन आर.के.", " "}, 
{ "Kerala",  "7253",  "Kasaragod", "Ravish Thanthri Kuntar", "ForeignFunding",  " ","केरल",  "कासरगोड", "रवीश थंथरी कुंतर", " "}, 
{ "Kerala",  "7254",  "Kasaragod", "Govindan B Alinthazhe", "NotGraduate",  " ","केरल",  "कासरगोड", "गोविंदन बी अलिन्थज़े", " "}, 
{ "Kerala",  "7398",  "Kollam", "Adv.K.V.Sabu", "ForeignFunding",  " ","केरल",  "कोल्लम", "Adv.KVSabu", " "}, 
{ "Kerala",  "7399",  "Kollam", "Jayarajan", "NotGraduate",  " ","केरल",  "कोल्लम", "जयराजन", " "}, 
{ "Kerala",  "7400",  "Kollam", "Saji Kollam", "NotGraduate",  " ","केरल",  "कोल्लम", "साजी कोल्लम", " "}, 
{ "Kerala",  "7401",  "Kollam", "Suni Kalluvathukkal", "NotGraduate",  " ","केरल",  "कोल्लम", "सुनी कल्लूवथुक्कल", " "}, 
{ "Kerala",  "7403",  "Kollam", "Premachandran N K", "CriminalCases",  " ","केरल",  "कोल्लम", "प्रेमचंद्रन एन.के.", " "}, 
{ "Kerala",  "7404",  "Kollam", "Nagaraj G", "CriminalCases",  " ","केरल",  "कोल्लम", "नागराज जी", " "}, 
{ "Kerala",  "7405",  "Kollam", "K N Balagopal", "CriminalCases",  " ","केरल",  "कोल्लम", "केएन बालगोपाल", " "}, 
{ "Kerala",  "7367",  "Kottayam", "Thomas Chazhikadan", "OverAged",  " ","केरल",  "कोट्टायम", "थॉमस चाझिकादान", " "}, 
{ "Kerala",  "7368",  "Kottayam", "Prakash", "CriminalCases",  " ","केरल",  "कोट्टायम", "प्रकाश", " "}, 
{ "Kerala",  "7369",  "Kottayam", "Thomas J Nidhiry", "OverAged",  " ","केरल",  "कोट्टायम", "थॉमस जे निधिरि", " "}, 
{ "Kerala",  "7371",  "Kottayam", "P C Thomas", "CriminalCases",  " ","केरल",  "कोट्टायम", "पीसी थॉमस", " "}, 
{ "Kerala",  "7372",  "Kottayam", "Ignatious Illimoottil", "NotGraduate",  " ","केरल",  "कोट्टायम", "अज्ञानपूर्ण इल्म्युट्टिल", " "}, 
{ "Kerala",  "7373",  "Kottayam", "Vasavan", "NotGraduate",  " ","केरल",  "कोट्टायम", "Vasavan", " "}, 
{ "Kerala",  "7297",  "Kozhikode", "Pradeepan N", "NotGraduate",  " ","केरल",  "कोझिकोड", "प्रदीपन एन", " "}, 
{ "Kerala",  "7298",  "Kozhikode", "P Sankaran (A.Sekhar)", "OverAged",  " ","केरल",  "कोझिकोड", "पी शंकरन (ए.सेकर)", " "}, 
{ "Kerala",  "7299",  "Kozhikode", "Prakash Babu Chaithram", "NotGraduate",  " ","केरल",  "कोझिकोड", "प्रकाश बाबू चैथराम", " "}, 
{ "Kerala",  "7300",  "Kozhikode", "Adv.Prakash Babu", "ForeignFunding",  " ","केरल",  "कोझिकोड", "सलाह.प्रकाश बाबू", " "}, 
{ "Kerala",  "7301",  "Kozhikode", "P. Raghavan", "OverAged",  " ","केरल",  "कोझिकोड", "पी। राघवन", " "}, 
{ "Kerala",  "7302",  "Kozhikode", "T. Raghavan", "NotGraduate",  " ","केरल",  "कोझिकोड", "टी। राघवन", " "}, 
{ "Kerala",  "7303",  "Kozhikode", "M.K.Raghavan", "ForeignFunding",  " ","केरल",  "कोझिकोड", "MKRaghavan", " "}, 
{ "Kerala",  "7304",  "Kozhikode", "Pradeep.V.K", "NotGraduate",  " ","केरल",  "कोझिकोड", "Pradeep.VK", " "}, 
{ "Kerala",  "7305",  "Kozhikode", "Pradeep Kumar E T", "NotGraduate",  " ","केरल",  "कोझिकोड", "प्रदीप कुमार ईटी", " "}, 
{ "Kerala",  "7306",  "Kozhikode", "N. Raghavn", "OverAged",  " ","केरल",  "कोझिकोड", "एन। राघवन", " "}, 
{ "Kerala",  "7307",  "Kozhikode", "M.K. Raghavan Nair", "OverAged",  " ","केरल",  "कोझिकोड", "एमके राघवन नायर", " "}, 
{ "Kerala",  "7308",  "Kozhikode", "Nusrath Jahan", "NotGraduate",  " ","केरल",  "कोझिकोड", "नुसरत जहान", " "}, 
{ "Kerala",  "7309",  "Kozhikode", "A Pradeep Kumar", "CriminalCases",  " ","केरल",  "कोझिकोड", "एक प्रदीप कुमार", " "}, 
{ "Kerala",  "7310",  "Malappuram", "Sanu Nk", "NotGraduate",  " ","केरल",  "मलप्पुरम", "सानू एनके", " "}, 
{ "Kerala",  "7311",  "Malappuram", "Abdul Salam", "NotGraduate",  " ","केरल",  "मलप्पुरम", "अब्दुल सलाम", " "}, 
{ "Kerala",  "7312",  "Malappuram", "Kunhalikutty", "CriminalCases",  " ","केरल",  "मलप्पुरम", "कुन्हलिकुट्टी", " "}, 
{ "Kerala",  "7313",  "Malappuram", "Unnikrishnan", "ForeignFunding",  " ","केरल",  "मलप्पुरम", "उन्नीकृष्णन", " "}, 
{ "Kerala",  "7315",  "Malappuram", "V.P. Sanu", "CriminalCases",  " ","केरल",  "मलप्पुरम", "वीपी सानू", " "}, 
{ "Kerala",  "7316",  "Malappuram", "Os Nissar Methar", "NotGraduate",  " ","केरल",  "मलप्पुरम", "ओएस निसार मेथर", " "}, 
{ "Kerala",  "7317",  "Malappuram", "Abdul Majeed Faizy", "CriminalCases",  " ","केरल",  "मलप्पुरम", "अब्दुल मजीद फैजी", " "}, 
{ "Kerala",  "4007",  "Mavelikkara", "Chittayam Gopakumar", "NotGraduate",  " ","केरल",  "मवेलीकारा", "चित्तम गोपकुमार", " "}, 
{ "Kerala",  "4008",  "Mavelikkara", "Rajagopalan", "NotGraduate",  " ","केरल",  "मवेलीकारा", "राजगोपालन", " "}, 
{ "Kerala",  "4009",  "Mavelikkara", "Usha", "NotGraduate",  " ","केरल",  "मवेलीकारा", "उषा", " "}, 
{ "Kerala",  "4010",  "Mavelikkara", "Ajayakumar", "NotGraduate",  " ","केरल",  "मवेलीकारा", "Ajayakumar", " "}, 
{ "Kerala",  "4011",  "Mavelikkara", "Raghavan R", "OverAged",  " ","केरल",  "मवेलीकारा", "राघवन आर", " "}, 
{ "Kerala",  "7386",  "Mavelikkara", "Kuttan K", "NotGraduate",  " ","केरल",  "मवेलीकारा", "कुट्टन के", " "}, 
{ "Kerala",  "7387",  "Mavelikkara", "Aji Pathanapuram", "NotGraduate",  " ","केरल",  "मवेलीकारा", "अजी पठानपुरम", " "}, 
{ "Kerala",  "7388",  "Mavelikkara", "Kodikunnil Suresh", "ForeignFunding",  " ","केरल",  "मवेलीकारा", "कोडिकुन्निल सुरेश", " "}, 
{ "Kerala",  "7390",  "Mavelikkara", "Sahadevan", "NotGraduate",  " ","केरल",  "मवेलीकारा", "Sahadevan", " "}, 
{ "Kerala",  "7319",  "Palakkad", "V K Sreekandan", "ForeignFunding",  " ","केरल",  "पलक्कड़", "वीके श्रीकंदन", " "}, 
{ "Kerala",  "7320",  "Palakkad", "Rajesh S/O Mani", "CriminalCases",  " ","केरल",  "पलक्कड़", "राजेश एस / ओ मणि", " "}, 
{ "Kerala",  "7321",  "Palakkad", "C Chandran", "NotGraduate",  " ","केरल",  "पलक्कड़", "C चंद्रन", " "}, 
{ "Kerala",  "7322",  "Palakkad", "P Rajesh", "NotGraduate",  " ","केरल",  "पलक्कड़", "पी राजेश", " "}, 
{ "Kerala",  "7323",  "Palakkad", "Krishnakumar C", "ForeignFunding",  " ","केरल",  "पलक्कड़", "कृष्णकुमार सी", " "}, 
{ "Kerala",  "7324",  "Palakkad", "M B Rajesh", "CriminalCases",  " ","केरल",  "पलक्कड़", "एमबी राजेश", " "}, 
{ "Kerala",  "7325",  "Palakkad", "Thulaseedharan", "CriminalCases",  " ","केरल",  "पलक्कड़", "Thulaseedharan", " "}, 
{ "Kerala",  "7326",  "Palakkad", "Balakrishnan", "NotGraduate",  " ","केरल",  "पलक्कड़", "बालाकृष्णन", " "}, 
{ "Kerala",  "4012",  "Pathanamthitta", "Shibu P", "NotGraduate",  " ","केरल",  "पथानामथिट्टा", "शिबू पी", " "}, 
{ "Kerala",  "7392",  "Pathanamthitta", "Ratheesh Kumar R", "NotGraduate",  " ","केरल",  "पथानामथिट्टा", "रत्नेश कुमार आर", " "}, 
{ "Kerala",  "7393",  "Pathanamthitta", "Veena V", "NotGraduate",  " ","केरल",  "पथानामथिट्टा", "वीना वी", " "}, 
{ "Kerala",  "7394",  "Pathanamthitta", "K Surendran", "ForeignFunding",  " ","केरल",  "पथानामथिट्टा", "के सुरेंद्रन", " "}, 
{ "Kerala",  "7395",  "Pathanamthitta", "Anto Antony", "ForeignFunding",  " ","केरल",  "पथानामथिट्टा", "एंटो एंटनी", " "}, 
{ "Kerala",  "7396",  "Pathanamthitta", "Binu", "NotGraduate",  " ","केरल",  "पथानामथिट्टा", "बीनू", " "}, 
{ "Kerala",  "7397",  "Pathanamthitta", "Jose George", "NotGraduate",  " ","केरल",  "पथानामथिट्टा", "जोस जॉर्ज", " "}, 
{ "Kerala",  "7318",  "Ponnani", "Rema", "ForeignFunding",  " ","केरल",  "पोन्नानी", "Rema", " "}, 
{ "Kerala",  "3993",  "Ponnani", "Sameera Pa", "NotGraduate",  " ","केरल",  "पोन्नानी", "समीरा पा", " "}, 
{ "Kerala",  "3995",  "Ponnani", "Muhammed Basheer Koyissery", "OverAged",  " ","केरल",  "पोन्नानी", "मुहम्मद बशीर कोइरीज़ीन", " "}, 
{ "Kerala",  "3996",  "Ponnani", "Muhammed Basheer Mangalassery", "NotGraduate",  " ","केरल",  "पोन्नानी", "मुहम्मद बशीर मंगलसरी", " "}, 
{ "Kerala",  "3997",  "Ponnani", "Poonthura Siraj", "NotGraduate",  " ","केरल",  "पोन्नानी", "पूनतुरा सिराज", " "}, 
{ "Kerala",  "3998",  "Ponnani", "Muhammed Basheer Nechiyan", "NotGraduate",  " ","केरल",  "पोन्नानी", "मुहम्मद बशीर नेचियान", " "}, 
{ "Kerala",  "3999",  "Ponnani", "Adv. K.C. Nazeer", "CriminalCases",  " ","केरल",  "पोन्नानी", "अभिभाषक। केसी नाज़ेर", " "}, 
{ "Kerala",  "4000",  "Ponnani", "Anvar P.V. Raseena Manzil", "NotGraduate",  " ","केरल",  "पोन्नानी", "अनवर पीवी रसेना मैन्ज़िल", " "}, 
{ "Kerala",  "4001",  "Ponnani", "Bindu", "NotGraduate",  " ","केरल",  "पोन्नानी", "बिन्दु", " "}, 
{ "Kerala",  "4002",  "Ponnani", "E T Mohammed Basheer", "OverAged",  " ","केरल",  "पोन्नानी", "ईटी मोहम्मद बशीर", " "}, 
{ "Kerala",  "7424",  "Thiruvananthapuram", "Shashi Tharoor", "ForeignFunding",  " ","केरल",  "तिरुवनंतपुरम", "शशि थरूर", " "}, 
{ "Kerala",  "4015",  "Thiruvananthapuram", "Sasi T", "OverAged",  " ","केरल",  "तिरुवनंतपुरम", "ससी टी", " "}, 
{ "Kerala",  "4016",  "Thiruvananthapuram", "Gopakumar", "NotGraduate",  " ","केरल",  "तिरुवनंतपुरम", "Gopakumar", " "}, 
{ "Kerala",  "4018",  "Thiruvananthapuram", "Johny Thampy", "CriminalCases",  " ","केरल",  "तिरुवनंतपुरम", "जॉनी थम्पी", " "}, 
{ "Kerala",  "4019",  "Thiruvananthapuram", "Mini S", "CriminalCases",  " ","केरल",  "तिरुवनंतपुरम", "मिनी एस", " "}, 
{ "Kerala",  "4020",  "Thiruvananthapuram", "Binu.D", "NotGraduate",  " ","केरल",  "तिरुवनंतपुरम", "Binu.D", " "}, 
{ "Kerala",  "4021",  "Thiruvananthapuram", "Subi", "NotGraduate",  " ","केरल",  "तिरुवनंतपुरम", "Subi", " "}, 
{ "Kerala",  "4023",  "Thiruvananthapuram", "Kirankumar.S.K", "NotGraduate",  " ","केरल",  "तिरुवनंतपुरम", "Kirankumar.SK", " "}, 
{ "Kerala",  "4024",  "Thiruvananthapuram", "Kummanam Rajasekharan", "ForeignFunding",  " ","केरल",  "तिरुवनंतपुरम", "कुम्मनम राजशेखरन", " "}, 
{ "Kerala",  "4025",  "Thiruvananthapuram", "S Suseelan", "CriminalCases",  " ","केरल",  "तिरुवनंतपुरम", "S सूसीलन", " "}, 
{ "Kerala",  "4026",  "Thiruvananthapuram", "P Keralavarmaraja", "OverAged",  " ","केरल",  "तिरुवनंतपुरम", "पी। केरलवर्मराज", " "}, 
{ "Kerala",  "4027",  "Thiruvananthapuram", "Christopher Shaju", "NotGraduate",  " ","केरल",  "तिरुवनंतपुरम", "क्रिस्टोफर शजू", " "}, 
{ "Kerala",  "4028",  "Thiruvananthapuram", "Devadathan", "OverAged",  " ","केरल",  "तिरुवनंतपुरम", "Devadathan", " "}, 
{ "Kerala",  "7423",  "Thiruvananthapuram", "Divakaran.C", "CriminalCases",  " ","केरल",  "तिरुवनंतपुरम", "Divakaran.C", " "}, 
{ "Kerala",  "7333",  "Thrissur", "Suvith", "CriminalCases",  " ","केरल",  "त्रिशूर", "Suvith", " "}, 
{ "Kerala",  "7335",  "Thrissur", "Suresh Gopi", "ForeignFunding",  " ","केरल",  "त्रिशूर", "सुरेश गोपी", " "}, 
{ "Kerala",  "7336",  "Thrissur", "T. N. Prathapan", "ForeignFunding",  " ","केरल",  "त्रिशूर", "टीएन प्रतापन", " "}, 
{ "Kerala",  "7337",  "Thrissur", "N D Venu", "CriminalCases",  " ","केरल",  "त्रिशूर", "एनडी वेणु", " "}, 
{ "Kerala",  "7338",  "Thrissur", "Sonu", "CriminalCases",  " ","केरल",  "त्रिशूर", "सोनू", " "}, 
{ "Kerala",  "7339",  "Thrissur", "Praveen K P", "CriminalCases",  " ","केरल",  "त्रिशूर", "प्रवीण के.पी.", " "}, 
{ "Kerala",  "7268",  "Vadakara", "Jatheesh A P", "NotGraduate",  " ","केरल",  "वाटकरा", "जथेश एपी", " "}, 
{ "Kerala",  "7269",  "Vadakara", "Aluva Aneesh", "NotGraduate",  " ","केरल",  "वाटकरा", "अलुवा अनीश", " "}, 
{ "Kerala",  "7270",  "Vadakara", "C.O.T. Naseer", "CriminalCases",  " ","केरल",  "वाटकरा", "COT नसीर", " "}, 
{ "Kerala",  "7271",  "Vadakara", "K. Muraleedharan", "ForeignFunding",  " ","केरल",  "वाटकरा", "के मुरलीधरन", " "}, 
{ "Kerala",  "7272",  "Vadakara", "Muraleedharan.K Kuttiyil Veedu", "NotGraduate",  " ","केरल",  "वाटकरा", "मुरलीधरन। के। कुटियाल विडू", " "}, 
{ "Kerala",  "7274",  "Vadakara", "Jayarajan Pandaraparambil", "OverAged",  " ","केरल",  "वाटकरा", "जयराजन पंडरापरांबिल", " "}, 
{ "Kerala",  "7275",  "Vadakara", "Santosh Kumar", "NotGraduate",  " ","केरल",  "वाटकरा", "संतोष कुमार", " "}, 
{ "Kerala",  "7276",  "Vadakara", "Jayarajan.P", "CriminalCases",  " ","केरल",  "वाटकरा", "Jayarajan.P", " "}, 
{ "Kerala",  "7277",  "Vadakara", "Muraleedharan.K Sandram", "NotGraduate",  " ","केरल",  "वाटकरा", "मुरलीधरन। के। संद्रम", " "}, 
{ "Kerala",  "3991",  "Vadakara", "Sajeevan V. K", "ForeignFunding",  " ","केरल",  "वाटकरा", "सजीवन वी। के", " "}, 
{ "Kerala",  "7278",  "Wayanad", "Narukara Gopi", "CriminalCases",  " ","केरल",  "वायनाड", "नरुकरा गोपी", " "}, 
{ "Kerala",  "7279",  "Wayanad", "Siby Vayalil", "NotGraduate",  " ","केरल",  "वायनाड", "सिबि वायलिल", " "}, 
{ "Kerala",  "7280",  "Wayanad", "Raghul Gandhi K S/O Krishnan P", "NotGraduate",  " ","केरल",  "वायनाड", "रघुल गांधी केएस / ओ कृष्णन पी", " "}, 
{ "Kerala",  "7282",  "Wayanad", "Shijo M Varghese", "NotGraduate",  " ","केरल",  "वायनाड", "शिजो एम वर्गीज", " "}, 
{ "Kerala",  "7285",  "Wayanad", "Adv. Sreejith P R", "CriminalCases",  " ","केरल",  "वायनाड", "अभिभाषक। श्रीजिथ पीआर", " "}, 
{ "Kerala",  "7287",  "Wayanad", "Rahul Gandhi", "ForeignFunding",  " ","केरल",  "वायनाड", "राहुल गांधी", " "}, 
{ "Kerala",  "7288",  "Wayanad", "Babu Mani", "CriminalCases",  " ","केरल",  "वायनाड", "बाबू मणि", " "}, 
{ "Kerala",  "7289",  "Wayanad", "Praveen K P", "CriminalCases",  " ","केरल",  "वायनाड", "प्रवीण के.पी.", " "}, 
{ "Kerala",  "7290",  "Wayanad", "Mujeeb Rahman", "NotGraduate",  " ","केरल",  "वायनाड", "मुजीब रहमान", " "}, 
{ "Kerala",  "7291",  "Wayanad", "Biju Kakkathode", "NotGraduate",  " ","केरल",  "वायनाड", "बीजू कक्क्ठोडे", " "}, 
{ "Kerala",  "7292",  "Wayanad", "Mohamed P K", "OverAged",  " ","केरल",  "वायनाड", "मोहम्मद पी.के.", " "}, 
{ "Kerala",  "7293",  "Wayanad", "Usha K", "NotGraduate",  " ","केरल",  "वायनाड", "उषा के", " "}, 
{ "Kerala",  "7295",  "Wayanad", "Sebastian Wayanad", "NotGraduate",  " ","केरल",  "वायनाड", "सेबस्टियन वायनाड", " "}, 
{ "Kerala",  "7296",  "Wayanad", "Thrissur Nazeer", "NotGraduate",  " ","केरल",  "वायनाड", "त्रिशूर नाज़ेर", " "}, 
};

}