/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Madhya_Pradesh {
    public static final String[][] green_bucket = {
            {"Madhya Pradesh", "Balaghat", "Abhishek Bilhore", "Bhartiya Shakti Chetna Party", "20.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10329", "मध्य प्रदेश", "बालाघाट", "अभिषेक बिल्हौर", "भारतीय शक्ति चेतना पार्टी"},
            {"Madhya Pradesh", "Balaghat", "Advocate Satyaprakash Shulke (Lodhi)", "Madhya Pradesh Jan Vikas Party", "5.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10635", "मध्य प्रदेश", "बालाघाट", "एडवोकेट सत्यप्रकाश शुल्के (लोधी)", "मध्य प्रदेश जन विकास पार्टी"},
            {"Madhya Pradesh", "Balaghat", "Shrimati Manisha Vaid", "Independent", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10650", "मध्य प्रदेश", "बालाघाट", "श्रीमति मनीषा वैद", "निर्दलीय"},
            {"Madhya Pradesh", "Balaghat", "Shatish Kumar", "Bhartiya Lokmat Rashtrwadi Party", "21.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10335", "मध्य प्रदेश", "बालाघाट", "शतीश कुमार", "भारतीय लोकमत राष्ट्रवादी पार्टी"},
            {"Madhya Pradesh", "Balaghat", "Pitam Borkar", "Independent", "72000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10646", "मध्य प्रदेश", "बालाघाट", "पीतम बोरकर", "निर्दलीय"},
            {"Madhya Pradesh", "Balaghat", "Narayan Banjare", "Independent", "2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10645", "मध्य प्रदेश", "बालाघाट", "नारायण बंजारे", "निर्दलीय"},
            {"Madhya Pradesh", "Balaghat", "Baboo Rajendra Dhoke", "Peoples Party of India (Democratic)", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10636", "मध्य प्रदेश", "बालाघाट", "बाबू राजेंद्र ढोके", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
            {"Madhya Pradesh", "Balaghat", "Makbool Shah", "Independent", "90000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10641", "मध्य प्रदेश", "बालाघाट", "मकबूल शाह", "निर्दलीय"},
            {"Madhya Pradesh", "Balaghat", "Bodhsingh Bhagat", "Independent", "7.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10637", "मध्य प्रदेश", "बालाघाट", "बोधसिंह भगत", "निर्दलीय"},
            {"Madhya Pradesh", "Balaghat", "Meershyam Lilhare Lodhi", "Independent", "25Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10643", "मध्य प्रदेश", "बालाघाट", "मीरश्याम लिल्हारे लोधी", "निर्दलीय"},
            {"Madhya Pradesh", "Balaghat", "Glg Tandekar", "Independent", "19.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10638", "मध्य प्रदेश", "बालाघाट", "ग्लग टांडेकर", "निर्दलीय"},
            {"Madhya Pradesh", "Betul", "Pushpa Dr. Shailendra Pendam", "Akhil Bhartiya Gondwana Party", "52.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11214", "", "", "पुष्पा डॉ। शैलेंद्र पेंडम", "अखिल भारतीय गोंडवाना पार्टी"},
            {"Madhya Pradesh", "Betul", "Sunil Kumar Kawde", "Independent", "6.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11988", "", "", "सुनील कुमार कावड़े", "निर्दलीय"},
            {"Madhya Pradesh", "Betul", "Pushpa Marskole", "Bahujan Mukti Party", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11989", "", "", "पुष्पा मर्सकोले", "बहुजन मुक्ति पार्टी"},
            {"Madhya Pradesh", "Chhindwara", "Rajkumar Saryam", "Gondvana Gantantra Party", "8.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10341", "मध्य प्रदेश", "छिंदवाड़ा", "राजकुमार सरियाम", "गोंडवाना गणतंत्र पार्टी"},
            {"Madhya Pradesh", "Chhindwara", "Jogilal Irpachi", "Independent", "3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10659", "मध्य प्रदेश", "छिंदवाड़ा", "जोगीलाल इरपाची", "निर्दलीय"},
            {"Madhya Pradesh", "Damoh", "Man Singh", "Bhartiya Shakti Chetna Party", "18.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11582", "", "", "मान सिंह", "भारतीय शक्ति चेतना पार्टी"},
            {"Madhya Pradesh", "Damoh", "Thakur Das", "Pragatishil Samajwadi Party (Lohia)", "2.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11584", "", "", "ठाकुर दास", "प्रगति समाजवादी पार्टी (लोहिया)"},
            {"Madhya Pradesh", "Damoh", "Prahlad Bhaiya", "Independent", "23.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12584", "", "", "प्रहलाद भैया", "निर्दलीय"},
            {"Madhya Pradesh", "Damoh", "Vikas Kewalrao Nagvanshi", "Bharat Prabhat Party", "95Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12000", "", "", "विकास केवलाराव नागवंशी", "भारत प्रभात पार्टी"},
            {"Madhya Pradesh", "Hoshangabad", "Shailendra", "Independent", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12008", "", "", "शैलेंद्र", "निर्दलीय"},
            {"Madhya Pradesh", "Hoshangabad", "Dinesh Katare", "Ambedkarite Party of India", "30500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12002", "", "", "दिनेश कटारे", "भारत की अम्बेडकरवादी पार्टी"},
            {"Madhya Pradesh", "Hoshangabad", "Pandit Devendra Sharma", "Sapaks Party", "32000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12006", "", "", "पंडित देवेंद्र शर्मा", "सपाक्स पार्टी"},
            {"Madhya Pradesh", "Hoshangabad", "Saligram Makodiya", "Independent", "52.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11589", "", "", "सालिगराम मकोडिया", "निर्दलीय"},
            {"Madhya Pradesh", "Hoshangabad", "Madan Mohan", "Independent", "30.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12004", "", "", "मदन मोहन", "निर्दलीय"},
            {"Madhya Pradesh", "Jabalpur", "Chandra Prakash Bhatnagar", "AARAKSHAN VIRODHI PARTY", "22.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10311", "मध्य प्रदेश", "जबलपुर", "चंद्र प्रकाश भटनागर", "AAKAKSHAN VIRODHI पार्टी"},
            {"Madhya Pradesh", "Jabalpur", "Dr. Dhai Akshar (Rakesh Sonkar)", "Independent", "14.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10627", "मध्य प्रदेश", "जबलपुर", "डॉ। ढाई अक्षर (राकेश सोनकर)", "निर्दलीय"},
            {"Madhya Pradesh", "Jabalpur", "Er. Rupram Singh", "Independent", "40.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10628", "मध्य प्रदेश", "जबलपुर", "एर। रूपराम सिंह", "निर्दलीय"},
            {"Madhya Pradesh", "Jabalpur", "Lakshminarayan Jagnnath Singh Lodhi", "Independent", "15.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10630", "मध्य प्रदेश", "जबलपुर", "लक्ष्मीनारायण जगन्नाथ सिंह लोधी", "निर्दलीय"},
            {"Madhya Pradesh", "Khajuraho", "Rajkumar Sharma", "Independent", "6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12025", "", "", "राजकुमार शर्मा", "निर्दलीय"},
            {"Madhya Pradesh", "Khajuraho", "Narendra", "Independent", "37.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12020", "", "", "नरेंद्र", "निर्दलीय"},
            {"Madhya Pradesh", "Khajuraho", "Sant Kumar Sharma", "Samagra Utthan Party", "3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12026", "", "", "संत कुमार शर्मा", "समागम उत्थान पार्टी"},
            {"Madhya Pradesh", "Khajuraho", "Ashwani Kumar Dubey", "Sarvodaya Bharat Party", "24.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12012", "", "", "अश्वनी कुमार दुबे", "सर्वोदय भारत पार्टी"},
            {"Madhya Pradesh", "Khajuraho", "Bhoopat Kumar", "Independent", "2.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12014", "", "", "भूपत कुमार", "निर्दलीय"},
            {"Madhya Pradesh", "Khajuraho", "Giriraj Kishor", "Independent", "26Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12016", "", "", "गिरिराज किशोर", "निर्दलीय"},
            {"Madhya Pradesh", "Khajuraho", "Mohammad Imran", "Independent", "18.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12019", "", "", "मोहम्मद इमरान", "निर्दलीय"},
            {"Madhya Pradesh", "Khajuraho", "Desh Pal", "Ambedkarite Party of India", "7.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12015", "", "", "देश पाल", "भारत की अम्बेडकरवादी पार्टी"},
            {"Madhya Pradesh", "Khajuraho", "Advocate Rakesh Kumar Shukla", "All India Forward Bloc", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12011", "", "", "एडवोकेट राकेश कुमार शुक्ला", "ऑल इंडिया फॉरवर्ड ब्लॉक"},
            {"Madhya Pradesh", "Mandla", "Sanjeev Kumar Pandram", "Hindusthan Nirman Dal", "18.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10326", "मध्य प्रदेश", "मंडला", "संजीव कुमार पंडराम", "हिंदुस्तान निर्माण दल"},
            {"Madhya Pradesh", "Mandla", "Advocate-Devsingh Kumre", "Independent", "24.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10666", "मध्य प्रदेश", "मंडला", "वकील-देवीसिंह कुमरे", "निर्दलीय"},
            {"Madhya Pradesh", "Mandla", "Bharat Singh Poosam", "Independent", "23.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10327", "मध्य प्रदेश", "मंडला", "भरत सिंह पूसाम", "निर्दलीय"},
            {"Madhya Pradesh", "Mandla", "Ajeet Dhurwey", "Independent", "6.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10667", "मध्य प्रदेश", "मंडला", "अजीत धुर्वे", "निर्दलीय"},
            {"Madhya Pradesh", "Rewa", "Sushil Kumar Mishra", "Independent", "62.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12041", "", "", "सुशील कुमार मिश्रा", "निर्दलीय"},
            {"Madhya Pradesh", "Rewa", "Akhilesh Saket", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12030", "", "", "अखिलेश साकेत", "निर्दलीय"},
            {"Madhya Pradesh", "Rewa", "Ram Kalesh Saket", "Independent", "1.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11604", "", "", "राम कलेश साकेत", "निर्दलीय"},
            {"Madhya Pradesh", "Rewa", "Vikash Kumar", "Bahujan Samaj Party", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11598", "", "", "विकाश कुमार", "बहुजन समाज पार्टी"},
            {"Madhya Pradesh", "Rewa", "Shakuntala", "Sapaks Party", "3.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12039", "", "", "शकुंतला", "सपाक्स पार्टी"},
            {"Madhya Pradesh", "Rewa", "Subhranshu Dwivedi", "Kisan Party of India", "6.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12040", "", "", "सुभ्रांशु द्विवेदी", "भारत की किसान पार्टी"},
            {"Madhya Pradesh", "Rewa", "Girijesh Singh Senger", "Communist Party of India (Marxist)", "35Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11221", "", "", "गिरिजेश सिंह सेंगर", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
            {"Madhya Pradesh", "Rewa", "Arun Kumar Satnami", "Bahujan Mukti Party", "38.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11605", "", "", "अरुण कुमार सतनामी", "बहुजन मुक्ति पार्टी"},
            {"Madhya Pradesh", "Satna", "Shashank Singh Baghel", "Sapaks Party", "2.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11610", "", "", "शशांक सिंह बघेल", "सपाक्स पार्टी"},
            {"Madhya Pradesh", "Satna", "Rajendra Tripathi", "Bharatiya Jan Morcha Party", "1.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12049", "", "", "राजेंद्र त्रिपाठी", "भारतीय जन मोर्चा पार्टी"},
            {"Madhya Pradesh", "Satna", "Dr Suresh Tripathi", "Independent", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11617", "", "", "डॉ। सुरेश त्रिपाठी", "निर्दलीय"},
            {"Madhya Pradesh", "Sidhi", "Rakesh", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10602", "मध्य प्रदेश", "सीधी", "राकेश", "निर्दलीय"},
            {"Madhya Pradesh", "Sidhi", "Ramraj", "Independent", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10607", "मध्य प्रदेश", "सीधी", "रामराज", "निर्दलीय"},
            {"Madhya Pradesh", "Sidhi", "Dileep", "Independent", "45000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10597", "मध्य प्रदेश", "सीधी", "दिलीप", "निर्दलीय"},
            {"Madhya Pradesh", "Sidhi", "Lalta", "Independent", "1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10599", "मध्य प्रदेश", "सीधी", "Lalta", "निर्दलीय"},
            {"Madhya Pradesh", "Sidhi", "Fatte Bahadur Singh Markam", "Gondvana Gantantra Party", "61.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10274", "मध्य प्रदेश", "सीधी", "फत्ते बहादुर सिंह मरकाम", "गोंडवाना गणतंत्र पार्टी"},
            {"Madhya Pradesh", "Sidhi", "Anup Kumar Singh", "Samagra Utthan Party", "28.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10594", "मध्य प्रदेश", "सीधी", "अनूप कुमार सिंह", "समागम उत्थान पार्टी"},
            {"Madhya Pradesh", "Sidhi", "Dharmendra Singh Baghel", "Independent", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10596", "मध्य प्रदेश", "सीधी", "धर्मेंद्र सिंह बघेल", "निर्दलीय"},
            {"Madhya Pradesh", "Tikamgarh", "Kamta Prasad", "Pragatishil Samajwadi Party (Lohia)", "18.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11623", "", "", "कामता प्रसाद", "प्रगति समाजवादी पार्टी (लोहिया)"},
            {"Madhya Pradesh", "Tikamgarh", "R.D. Prajapati", "Samajwadi Party", "83.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11226", "", "", "आरडी प्रजापति", "समाजवादी पार्टी"},
            {"Madhya Pradesh", "Tikamgarh", "R.B. Prajapati Advocate", "Independent", "4.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11620", "", "", "आरबी प्रजापति एडवोकेट", "निर्दलीय"},
            {"Madhya Pradesh", "Tikamgarh", "Shriram Nagar", "Sapaks Party", "6.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12063", "", "", "श्रीराम नगर", "सपाक्स पार्टी"},
            {"Madhya Pradesh", "Tikamgarh", "Nandram Prajapati", "Adarsh Nyay Rakshak Party", "12.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11227", "", "", "नंदराम प्रजापति", "आदर्श न्याय रक्षक पार्टी"},
    };

    public static final String[][] red_bucket = {
            {"Madhya Pradesh", "Balaghat", "Karan Singh Naagpure", "2", " ", "मध्य प्रदेश", "बालाघाट", "करण सिंह नागपुरे", " "},
            {"Madhya Pradesh", "Balaghat", "Jesingh Tekam", "3", " ", "मध्य प्रदेश", "बालाघाट", "जेसिंह टेकाम", " "},
            {"Madhya Pradesh", "Balaghat", "Madhu Kumar", "1", " ", "मध्य प्रदेश", "बालाघाट", "मधु कुमार", " "},
            {"Madhya Pradesh", "Balaghat", "Kankar", "2", " ", "मध्य प्रदेश", "बालाघाट", "kankar", " "},
            {"Madhya Pradesh", "Balaghat", "Yuvraj Singh Bais", "3", " ", "मध्य प्रदेश", "बालाघाट", "युवराज सिंह बैस", " "},
            {"Madhya Pradesh", "Balaghat", "Ruplal Kutrahe (Samaj Sevak ) Lodhi", "2", " ", "मध्य प्रदेश", "बालाघाट", "रूपलाल कुत्रे (समाज सेवक) लोधी", " "},
            {"Madhya Pradesh", "Balaghat", "Dr. Dhal Singh Bisen", "1", " ", "मध्य प्रदेश", "बालाघाट", "डॉ। ढाल सिंह बिसेन", " "},
            {"Madhya Pradesh", "Balaghat", "Ali . M. R. Khan", "2", " ", "मध्य प्रदेश", "बालाघाट", "अली। एमआर खान", " "},
            {"Madhya Pradesh", "Balaghat", "Rajan Masih", "4", " ", "मध्य प्रदेश", "बालाघाट", "राजन मासिह", " "},
            {"Madhya Pradesh", "Balaghat", "Mukesh Bansod", "4", " ", "मध्य प्रदेश", "बालाघाट", "मुकेश बंसोड़", " "},
            {"Madhya Pradesh", "Balaghat", "Kishor Samrite", "2", " ", "मध्य प्रदेश", "बालाघाट", "किशोर समरीते", " "},
            {"Madhya Pradesh", "Balaghat", "Rakesh Kumar", "2", " ", "मध्य प्रदेश", "बालाघाट", "राकेश कुमार", " "},
            {"Madhya Pradesh", "Betul", "Bisram Uikey", "4", " ", "", "", "बिसराम उइके", " "},
            {"Madhya Pradesh", "Betul", "Bhagcharan Warkade", "4", " ", "", "", "भगचरन वरकडे", " "},
            {"Madhya Pradesh", "Betul", "Ashok Bhalavi", "4", " ", "", "", "अशोक भालवी", " "},
            {"Madhya Pradesh", "Betul", "Ramu Tekam", "1", " ", "", "", "रामू टेकम", " "},
            {"Madhya Pradesh", "Betul", "Durga Das (D.D.) Uikey", "1", " ", "", "", "दुर्गा दास (डीडी) उइके", " "},
            {"Madhya Pradesh", "Betul", "Nimish Sariyam", "2", " ", "", "", "निमिष सरियाम", " "},
            {"Madhya Pradesh", "Chhindwara", "Subhash Shukla", "4", " ", "मध्य प्रदेश", "छिंदवाड़ा", "सुभाष शुक्ला", " "},
            {"Madhya Pradesh", "Chhindwara", "Rameshwar Dhurve", "4", " ", "मध्य प्रदेश", "छिंदवाड़ा", "रामेश्वर धुर्वे", " "},
            {"Madhya Pradesh", "Chhindwara", "Dinesh Singh Uikey", "4", " ", "मध्य प्रदेश", "छिंदवाड़ा", "दिनेश सिंह उइके", " "},
            {"Madhya Pradesh", "Chhindwara", "Ramdas Uikey", "4", " ", "मध्य प्रदेश", "छिंदवाड़ा", "रामदास उइके", " "},
            {"Madhya Pradesh", "Chhindwara", "Nakul Nath", "1", " ", "मध्य प्रदेश", "छिंदवाड़ा", "नकुल नाथ", " "},
            {"Madhya Pradesh", "Chhindwara", "M. P. Vishwakarma", "3", " ", "मध्य प्रदेश", "छिंदवाड़ा", "सांसद विश्वकर्मा", " "},
            {"Madhya Pradesh", "Chhindwara", "Dhaniram Yaduwanshi", "4", " ", "मध्य प्रदेश", "छिंदवाड़ा", "धनीराम यदुवंशी", " "},
            {"Madhya Pradesh", "Chhindwara", "Nathanshah Kawret", "1", " ", "मध्य प्रदेश", "छिंदवाड़ा", "नतनशाह कवरात", " "},
            {"Madhya Pradesh", "Chhindwara", "Manmohan Shah Batti", "2", " ", "मध्य प्रदेश", "छिंदवाड़ा", "मनमोहन शाह बत्तीसी", " "},
            {"Madhya Pradesh", "Chhindwara", "Rajesh Tantrik", "2", " ", "मध्य प्रदेश", "छिंदवाड़ा", "राजेश तांत्रिक", " "},
            {"Madhya Pradesh", "Chhindwara", "Gyaneshwar Gajbhiye", "4", " ", "मध्य प्रदेश", "छिंदवाड़ा", "ज्ञानेश्वर गजभिये", " "},
            {"Madhya Pradesh", "Chhindwara", "Hemendra Gohar", "2", " ", "मध्य प्रदेश", "छिंदवाड़ा", "हेमेंद्र गोहर", " "},
            {"Madhya Pradesh", "Damoh", "Richa Purshottam Choubey (Hariom)", "4", " ", "", "", "ऋचा पुरुषोत्तम चौबे (हरिओम)", " "},
            {"Madhya Pradesh", "Damoh", "Sharada Parsad Patel", "3", " ", "", "", "शारदा पारस पटेल", " "},
            {"Madhya Pradesh", "Damoh", "Manvendra Singh", "4", " ", "", "", "मानवेन्द्र सिंह", " "},
            {"Madhya Pradesh", "Damoh", "Prahalad", "4", " ", "", "", "प्रहलाद", " "},
            {"Madhya Pradesh", "Damoh", "Devi Prasad", "4", " ", "", "", "देवी प्रसाद", " "},
            {"Madhya Pradesh", "Damoh", "Manu Singh Maravi", "4", " ", "", "", "मनु सिंह मरावी", " "},
            {"Madhya Pradesh", "Damoh", "Prahalad Singh Patel", "1", " ", "", "", "प्रहलाद सिंह पटेल", " "},
            {"Madhya Pradesh", "Damoh", "Jitendra Khare", "4", " ", "", "", "जितेंद्र खरे", " "},
            {"Madhya Pradesh", "Damoh", "Anant Lal Basor", "3", " ", "", "", "अनंत लाल बसोर", " "},
            {"Madhya Pradesh", "Damoh", "Kamlesh Asati", "4", " ", "", "", "कमलेश असाटी", " "},
            {"Madhya Pradesh", "Damoh", "Pratap Singh", "1", " ", "", "", "प्रताप सिंह", " "},
            {"Madhya Pradesh", "Hoshangabad", "Rajesh Kumar Uikey", "4", " ", "", "", "राजेश कुमार उइके", " "},
            {"Madhya Pradesh", "Hoshangabad", "Arya Ravi Parihar", "4", " ", "", "", "आर्य रवि परिहार", " "},
            {"Madhya Pradesh", "Hoshangabad", "Bhavanishankar", "2", " ", "", "", "Bhavanishankar", " "},
            {"Madhya Pradesh", "Hoshangabad", "Shailendra Diwan Chandarbhan Singh", "1", " ", "", "", "शैलेंद्र दीवान चंद्रभान सिंह", " "},
            {"Madhya Pradesh", "Hoshangabad", "M.P. Choudhary", "3", " ", "", "", "सांसद चौधरी", " "},
            {"Madhya Pradesh", "Hoshangabad", "Rao Uday Pratap Singh", "1", " ", "", "", "राव उदय प्रताप सिंह", " "},
            {"Madhya Pradesh", "Jabalpur", "Dhanuk", "4", " ", "मध्य प्रदेश", "जबलपुर", "Dhanuk", " "},
            {"Madhya Pradesh", "Jabalpur", "Ramdayal Prajapat", "4", " ", "मध्य प्रदेश", "जबलपुर", "रामदयाल प्रजापत", " "},
            {"Madhya Pradesh", "Jabalpur", "Rakesh Singh", "1", " ", "मध्य प्रदेश", "जबलपुर", "राकेश सिंह", " "},
            {"Madhya Pradesh", "Jabalpur", "Shahnaz B Ansari", "4", " ", "मध्य प्रदेश", "जबलपुर", "शहनाज बी अंसारी", " "},
            {"Madhya Pradesh", "Jabalpur", "Rakesh Singh S/O Nathuram", "4", " ", "मध्य प्रदेश", "जबलपुर", "राकेश सिंह एस / ओ नाथूराम", " "},
            {"Madhya Pradesh", "Jabalpur", "Kuldeep Ahirwar", "4", " ", "मध्य प्रदेश", "जबलपुर", "कुलदीप अहिरवार", " "},
            {"Madhya Pradesh", "Jabalpur", "Gulab Singh @ Vivek", "4", " ", "मध्य प्रदेश", "जबलपुर", "गुलाब सिंह @ विवेक", " "},
            {"Madhya Pradesh", "Jabalpur", "Vinay Kumar Jain", "4", " ", "मध्य प्रदेश", "जबलपुर", "विनय कुमार जैन विष्णु भैया", " "},
            {"Madhya Pradesh", "Jabalpur", "Ashok Singh Lodhi", "4", " ", "मध्य प्रदेश", "जबलपुर", "अशोक सिंह लोधी", " "},
            {"Madhya Pradesh", "Jabalpur", "Shree Lal Markam(Bade Shri)", "4", " ", "मध्य प्रदेश", "जबलपुर", "श्री लाल मरकाम (बाडे श्री)", " "},
            {"Madhya Pradesh", "Jabalpur", "Sukhdev Dahiya", "4", " ", "मध्य प्रदेश", "जबलपुर", "सुखदेव दहिया", " "},
            {"Madhya Pradesh", "Jabalpur", "Vivek Krishna Tankha", "1", " ", "मध्य प्रदेश", "जबलपुर", "विवेक कृष्ण तन्खा", " "},
            {"Madhya Pradesh", "Jabalpur", "Amjad Khan", "4", " ", "मध्य प्रदेश", "जबलपुर", "अमजद खान", " "},
            {"Madhya Pradesh", "Jabalpur", "Rakesh Singh S/O Baljor Singh", "4", " ", "मध्य प्रदेश", "जबलपुर", "राकेश सिंह एस / ओ बलजोर सिंह", " "},
            {"Madhya Pradesh", "Jabalpur", "Mahu Singh", "4", " ", "मध्य प्रदेश", "जबलपुर", "महू सिंह", " "},
            {"Madhya Pradesh", "Jabalpur", "Devendra Kumar Yadav", "4", " ", "मध्य प्रदेश", "जबलपुर", "देवेंद्र कुमार यादव", " "},
            {"Madhya Pradesh", "Jabalpur", "Ramraj Ram", "3", " ", "मध्य प्रदेश", "जबलपुर", "रामराज राम", " "},
            {"Madhya Pradesh", "Jabalpur", "Bhushan Prasad Shukla", "4", " ", "मध्य प्रदेश", "जबलपुर", "भूषण प्रसाद शुक्ल", " "},
            {"Madhya Pradesh", "Khajuraho", "Vishnu Datt Sharma", "1", " ", "", "", "विष्णु दत्त शर्मा", " "},
            {"Madhya Pradesh", "Khajuraho", "Jagdesh Kumar Patel", "4", " ", "", "", "जगदीश कुमार पटेल", " "},
            {"Madhya Pradesh", "Khajuraho", "Parwat Singh", "4", " ", "", "", "परवत सिंह", " "},
            {"Madhya Pradesh", "Khajuraho", "Vinod Kumar", "4", " ", "", "", "विनोद कुमार", " "},
            {"Madhya Pradesh", "Khajuraho", "Meena Raikwar", "4", " ", "", "", "मीना रायकवार", " "},
            {"Madhya Pradesh", "Khajuraho", "Maharani Kavita Singh Natiraja", "1", " ", "", "", "महारानी कविता सिंह नतिराज", " "},
            {"Madhya Pradesh", "Khajuraho", "Manish Mishra", "4", " ", "", "", "मनीष मिश्रा", " "},
            {"Madhya Pradesh", "Khajuraho", "Veer Singh Patel", "2", " ", "", "", "वीर सिंह पटेल", " "},
            {"Madhya Pradesh", "Mandla", "Manita Markam", "4", " ", "मध्य प्रदेश", "मंडला", "मनिता मरकाम", " "},
            {"Madhya Pradesh", "Mandla", "Chandra Singh Kushram", "4", " ", "मध्य प्रदेश", "मंडला", "चन्द्र सिंह कुशराम", " "},
            {"Madhya Pradesh", "Mandla", "Kamal Singh Maravi", "1", " ", "मध्य प्रदेश", "मंडला", "कमल सिंह मरावी", " "},
            {"Madhya Pradesh", "Mandla", "R. S. Paraste (Ramsingh)", "3", " ", "मध्य प्रदेश", "मंडला", "आरएस परस्ते (रामसिंह)", " "},
            {"Madhya Pradesh", "Mandla", "Dada Ramgulam Uikey", "4", " ", "मध्य प्रदेश", "मंडला", "दादा रामगुलाम उइके", " "},
            {"Madhya Pradesh", "Mandla", "Faggan Singh Kulaste", "1", " ", "मध्य प्रदेश", "मंडला", "फग्गन सिंह कुलस्ते", " "},
            {"Madhya Pradesh", "Rewa", "Siyasharan Kevat", "4", " ", "", "", "सियाशरण केवट", " "},
            {"Madhya Pradesh", "Rewa", "Reeta Tripathi", "4", " ", "", "", "रीता त्रिपाठी", " "},
            {"Madhya Pradesh", "Rewa", "Brahm Datta Mishra", "2", " ", "", "", "ब्रह्मदत्त मिश्र", " "},
            {"Madhya Pradesh", "Rewa", "Chhotu Kol", "4", " ", "", "", "छोटू कोल", " "},
            {"Madhya Pradesh", "Rewa", "Babulal Kol", "4", " ", "", "", "बाबूलाल कोल", " "},
            {"Madhya Pradesh", "Rewa", "Ram Gopal Singh", "2", " ", "", "", "राम गोपाल सिंह", " "},
            {"Madhya Pradesh", "Rewa", "Sunit Kumar Pandey", "2", " ", "", "", "सुनीत कुमार पांडे", " "},
            {"Madhya Pradesh", "Rewa", "Devendra Kumar", "4", " ", "", "", "देवेंद्र कुमार", " "},
            {"Madhya Pradesh", "Rewa", "Arun Kumar", "2", " ", "", "", "अरुण कुमार", " "},
            {"Madhya Pradesh", "Rewa", "Janardan Prasad Mishra", "1", " ", "", "", "जनार्दन प्रसाद मिश्र", " "},
            {"Madhya Pradesh", "Rewa", "Sanat Kumar", "4", " ", "", "", "सनत कुमार", " "},
            {"Madhya Pradesh", "Rewa", "Shivkumar Mishra", "4", " ", "", "", "शिवकुमार मिश्रा", " "},
            {"Madhya Pradesh", "Rewa", "Badriprasad", "4", " ", "", "", "Badriprasad", " "},
            {"Madhya Pradesh", "Rewa", "Siddharth Tiwari", "1", " ", "", "", "सिद्धार्थ तिवारी", " "},
            {"Madhya Pradesh", "Satna", "Nand Kishore", "4", " ", "", "", "नंद किशोर", " "},
            {"Madhya Pradesh", "Satna", "Mahesh Sahu", "4", " ", "", "", "महेश साहू", " "},
            {"Madhya Pradesh", "Satna", "Munni Kranti", "4", " ", "", "", "मुन्नी क्रांति", " "},
            {"Madhya Pradesh", "Satna", "Ram Nivas Sen", "4", " ", "", "", "राम निवास सेन", " "},
            {"Madhya Pradesh", "Satna", "Babu Lal", "4", " ", "", "", "बाबू लाल", " "},
            {"Madhya Pradesh", "Satna", "Ganesh Singh", "1", " ", "", "", "गणेश सिंह", " "},
            {"Madhya Pradesh", "Satna", "Acche Lal Kushawaha", "2", " ", "", "", "असे लाल कुशवाहा", " "},
            {"Madhya Pradesh", "Satna", "Ramkushal Kewat", "4", " ", "", "", "रामकुशल केवट", " "},
            {"Madhya Pradesh", "Satna", "Mahendra Singh", "3", " ", "", "", "महेंद्र सिंह", " "},
            {"Madhya Pradesh", "Satna", "Surendra Prasad Pandey", "3", " ", "", "", "सुरेंद्र प्रसाद पांडे", " "},
            {"Madhya Pradesh", "Satna", "Rajaram Tripathi", "1", " ", "", "", "राजाराम त्रिपाठी", " "},
            {"Madhya Pradesh", "Satna", "Ashok Vishwakarma", "4", " ", "", "", "अशोक विश्वकर्मा", " "},
            {"Madhya Pradesh", "Satna", "Mo. Jibrail", "4", " ", "", "", "मो। जिबरईल", " "},
            {"Madhya Pradesh", "Satna", "Vipin Singh Tiwari", "4", " ", "", "", "विपिन सिंह तिवारी", " "},
            {"Madhya Pradesh", "Satna", "Ram Vishwash Pal", "4", " ", "", "", "रामविश्व पाल", " "},
            {"Madhya Pradesh", "Satna", "Manoraj Dwivedi", "4", " ", "", "", "मनोरज द्विवेदी", " "},
            {"Madhya Pradesh", "Satna", "Sandeep Kumar Tiwari", "4", " ", "", "", "संदीप कुमार तिवारी", " "},
            {"Madhya Pradesh", "Satna", "Nasir Khan", "3", " ", "", "", "नासिर खान", " "},
            {"Madhya Pradesh", "Shahdol", "Vimal Singh Korche", "4", " ", "मध्य प्रदेश", "शाहडोल", "विमल सिंह कोरचे", " "},
            {"Madhya Pradesh", "Shahdol", "Pramila Singh", "1", " ", "मध्य प्रदेश", "शाहडोल", "प्रमिला सिंह", " "},
            {"Madhya Pradesh", "Shahdol", "Durga Mosi", "4", " ", "मध्य प्रदेश", "शाहडोल", "दुर्गा मोशी", " "},
            {"Madhya Pradesh", "Shahdol", "Lakshyapat Singh", "4", " ", "मध्य प्रदेश", "शाहडोल", "लक्ष्मीपत सिंह", " "},
            {"Madhya Pradesh", "Shahdol", "Kamla Prasad Baiga", "4", " ", "मध्य प्रदेश", "शाहडोल", "कमला प्रसाद बैगा", " "},
            {"Madhya Pradesh", "Shahdol", "Keshkali", "4", " ", "मध्य प्रदेश", "शाहडोल", "Keshkali", " "},
            {"Madhya Pradesh", "Shahdol", "Narayan Singh Uike", "4", " ", "मध्य प्रदेश", "शाहडोल", "नारायण सिंह उइके", " "},
            {"Madhya Pradesh", "Shahdol", "Meera Singh", "4", " ", "मध्य प्रदेश", "शाहडोल", "मीरा सिंह", " "},
            {"Madhya Pradesh", "Shahdol", "Manna Singh", "4", " ", "मध्य प्रदेश", "शाहडोल", "मन्ना सिंह", " "},
            {"Madhya Pradesh", "Shahdol", "Himadri Singh", "1", " ", "मध्य प्रदेश", "शाहडोल", "हिमाद्री सिंह", " "},
            {"Madhya Pradesh", "Shahdol", "Jhamaklal", "3", " ", "मध्य प्रदेश", "शाहडोल", "Jhamaklal", " "},
            {"Madhya Pradesh", "Shahdol", "Mohadal", "3", " ", "मध्य प्रदेश", "शाहडोल", "Mohadal", " "},
            {"Madhya Pradesh", "Shahdol", "Gokul Singh", "4", " ", "मध्य प्रदेश", "शाहडोल", "गोकुल सिंह", " "},
            {"Madhya Pradesh", "Sidhi", "Sanjay Kumar Namdeo", "2", " ", "मध्य प्रदेश", "सीधी", "संजय कुमार नामदेव", " "},
            {"Madhya Pradesh", "Sidhi", "Ram Kripal Basor", "4", " ", "मध्य प्रदेश", "सीधी", "राम कृपाल बसोर", " "},
            {"Madhya Pradesh", "Sidhi", "Ramsahay", "4", " ", "मध्य प्रदेश", "सीधी", "Ramsahay", " "},
            {"Madhya Pradesh", "Sidhi", "Ramawatar Vishwakarma", "2", " ", "मध्य प्रदेश", "सीधी", "रामावतार विश्वकर्मा", " "},
            {"Madhya Pradesh", "Sidhi", "Ram Rahees Kol", "4", " ", "मध्य प्रदेश", "सीधी", "राम रहीस कोल", " "},
            {"Madhya Pradesh", "Sidhi", "Ajay Arjun Singh", "1", " ", "मध्य प्रदेश", "सीधी", "अजय अर्जुन सिंह", " "},
            {"Madhya Pradesh", "Sidhi", "Ashish Kumar Singh Chauhan", "4", " ", "मध्य प्रदेश", "सीधी", "आशीष कुमार सिंह चौहान", " "},
            {"Madhya Pradesh", "Sidhi", "Ramadhar", "4", " ", "मध्य प्रदेश", "सीधी", "रामाधार", " "},
            {"Madhya Pradesh", "Sidhi", "Shyam Lal", "4", " ", "मध्य प्रदेश", "सीधी", "श्याम लाल", " "},
            {"Madhya Pradesh", "Sidhi", "Lalan", "4", " ", "मध्य प्रदेश", "सीधी", "ललन", " "},
            {"Madhya Pradesh", "Sidhi", "Ram Das", "3", " ", "मध्य प्रदेश", "सीधी", "राम दास", " "},
            {"Madhya Pradesh", "Sidhi", "Ram Lal Panika", "4", " ", "मध्य प्रदेश", "सीधी", "राम लाल पनिका", " "},
            {"Madhya Pradesh", "Sidhi", "Gyani Jaiswal", "4", " ", "मध्य प्रदेश", "सीधी", "ज्ञानी जायसवाल", " "},
            {"Madhya Pradesh", "Sidhi", "Nirmala Prajapati", "4", " ", "मध्य प्रदेश", "सीधी", "निर्मला प्रजापति", " "},
            {"Madhya Pradesh", "Sidhi", "Ramkumar Jaysval", "3", " ", "मध्य प्रदेश", "सीधी", "रामकुमार जैसवाल", " "},
            {"Madhya Pradesh", "Tikamgarh", "Virendra Kumar", "1", " ", "", "", "वीरेन्द्र कुमार", " "},
            {"Madhya Pradesh", "Tikamgarh", "Ahirwar Shripat Shikshak", "4", " ", "", "", "अहिरवार श्रीपत शिक्षा", " "},
            {"Madhya Pradesh", "Tikamgarh", "Suresh Kumar Kori", "4", " ", "", "", "सुरेश कुमार कोरी", " "},
            {"Madhya Pradesh", "Tikamgarh", "Jitendra Banshkar", "4", " ", "", "", "जितेंद्र बंशकार", " "},
            {"Madhya Pradesh", "Tikamgarh", "Surjeet Chadar", "4", " ", "", "", "सुरजीत चदर", " "},
            {"Madhya Pradesh", "Tikamgarh", "Kiran Singh Ahirwar", "1", " ", "", "", "किरण सिंह अहिरवार", " "},
            {"Madhya Pradesh", "Tikamgarh", "Pramod Prajapati", "4", " ", "", "", "प्रमोद प्रजापति", " "},
            {"Madhya Pradesh", "Tikamgarh", "Shobha Valmiki", "3", " ", "", "", "शोभा वाल्मीकि", " "},
            {"Madhya Pradesh", "Tikamgarh", "Narayan Das Jatav", "4", " ", "", "", "नारायण दास जाटव", " "},
    };

}