/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Madhya_Pradesh {
    public static final String[][] green_bucket = {
            {"Madhya Pradesh", "Balaghat", "Abhishek Bilhore", "Bhartiya Shakti Chetna Party", "20.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10329", "मध्य प्रदेश", "बालाघाट", "अभिषेक बिल्हौर", "भारतीय शक्ति चेतना पार्टी"},
            {"Madhya Pradesh", "Balaghat", "Advocate Satyaprakash Shulke (Lodhi)", "Madhya Pradesh Jan Vikas Party", "5.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10635", "मध्य प्रदेश", "बालाघाट", "एडवोकेट सत्यप्रकाश शुल्के (लोधी)", "मध्य प्रदेश जन विकास पार्टी"},
            {"Madhya Pradesh", "Balaghat", "Shrimati Manisha Vaid", "Independent", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10650", "मध्य प्रदेश", "बालाघाट", "श्रीमति मनीषा वैद", "निर्दलीय"},
            {"Madhya Pradesh", "Balaghat", "Shatish Kumar", "Bhartiya Lokmat Rashtrwadi Party", "21.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10335", "मध्य प्रदेश", "बालाघाट", "शतीश कुमार", "भारतीय लोकमत राष्ट्रवादी पार्टी"},
            {"Madhya Pradesh", "Balaghat", "Pitam Borkar", "Independent", "72000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10646", "मध्य प्रदेश", "बालाघाट", "पीतम बोरकर", "निर्दलीय"},
            {"Madhya Pradesh", "Balaghat", "Narayan Banjare", "Independent", "2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10645", "मध्य प्रदेश", "बालाघाट", "नारायण बंजारे", "निर्दलीय"},
            {"Madhya Pradesh", "Balaghat", "Baboo Rajendra Dhoke", "Peoples Party of India (Democratic)", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10636", "मध्य प्रदेश", "बालाघाट", "बाबू राजेंद्र ढोके", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
            {"Madhya Pradesh", "Balaghat", "Makbool Shah", "Independent", "90000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10641", "मध्य प्रदेश", "बालाघाट", "मकबूल शाह", "निर्दलीय"},
            {"Madhya Pradesh", "Balaghat", "Bodhsingh Bhagat", "Independent", "7.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10637", "मध्य प्रदेश", "बालाघाट", "बोधसिंह भगत", "निर्दलीय"},
            {"Madhya Pradesh", "Balaghat", "Meershyam Lilhare Lodhi", "Independent", "25Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10643", "मध्य प्रदेश", "बालाघाट", "मीरश्याम लिल्हारे लोधी", "निर्दलीय"},
            {"Madhya Pradesh", "Balaghat", "Glg Tandekar", "Independent", "19.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10638", "मध्य प्रदेश", "बालाघाट", "ग्लग टांडेकर", "निर्दलीय"},
            {"Madhya Pradesh", "Betul", "Pushpa Dr. Shailendra Pendam", "Akhil Bhartiya Gondwana Party", "52.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11214", "मध्य प्रदेश", "बेतुल", "पुष्पा डॉ। शैलेंद्र पेंडम", "अखिल भारतीय गोंडवाना पार्टी"},
            {"Madhya Pradesh", "Betul", "Sunil Kumar Kawde", "Independent", "6.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11988", "मध्य प्रदेश", "बेतुल", "सुनील कुमार कावड़े", "निर्दलीय"},
            {"Madhya Pradesh", "Betul", "Pushpa Marskole", "Bahujan Mukti Party", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11989", "मध्य प्रदेश", "बेतुल", "पुष्पा मर्सकोले", "बहुजन मुक्ति पार्टी"},
            {"Madhya Pradesh", "Bhind", "Ramnaresh Jatav", "Independent", "4.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12601", "मध्य प्रदेश", "भिंड", "रामनरेश जाटव", "निर्दलीय"},
            {"Madhya Pradesh", "Bhopal", "Ca Pramod Bhojwani", "Sanatan Sanskriti Raksha Dal", "71.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13332", "मध्य प्रदेश", "भोपाल", "सीए प्रमोद भोजवानी", "सनातन संस्कृति रक्षा दल"},
            {"Madhya Pradesh", "Bhopal", "Alok Kumar", "Independent", "2.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13338", "मध्य प्रदेश", "भोपाल", "आलोक कुमार", "निर्दलीय"},
            {"Madhya Pradesh", "Bhopal", "Rajesh Keer", "Bahujan Mukti Party", "7.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12618", "मध्य प्रदेश", "भोपाल", "राजेश कीर", "बहुजन मुक्ति पार्टी"},
            {"Madhya Pradesh", "Bhopal", "Deshmukh Riyazuddin Ghayasuddin", "Independent", "9.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13342", "मध्य प्रदेश", "भोपाल", "देशमुख रियाजुद्दीन ग़यासुद्दीन", "निर्दलीय"},
            {"Madhya Pradesh", "Bhopal", "Sunil Kumar Dodeja", "Independent", "1.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12615", "मध्य प्रदेश", "भोपाल", "सुनील कुमार डोडेजा", "निर्दलीय"},
            {"Madhya Pradesh", "Bhopal", "Bhaurao Vithoba Fulzele", "Bharat Prabhat Party", "52.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13334", "मध्य प्रदेश", "भोपाल", "भाऊराव विठोबा फुलझले", "भारत प्रभात पार्टी"},
            {"Madhya Pradesh", "Bhopal", "Abdul Tahir Ansari", "Swarnim Bharat Inquilab", "51.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13328", "मध्य प्रदेश", "भोपाल", "अब्दुल ताहिर अंसारी", "स्वर्णिम भारत इंकलाब"},
            {"Madhya Pradesh", "Bhopal", "Dr. Veena Ghanekar Rtd. Ias", "Sapaks Party", "5.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12612", "मध्य प्रदेश", "भोपाल", "डॉ। वीणा घानेकर Rtd आईएएस", "सपाक्स पार्टी"},
            {"Madhya Pradesh", "Bhopal", "Raj Kumar Shakya (Kori)", "Jan Adhikar Party", "21500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13335", "मध्य प्रदेश", "भोपाल", "राज कुमार शाक्य (कोरी)", "जन आढ़ती पार्टी"},
            {"Madhya Pradesh", "Bhopal", "Piyush Jain", "Right to Recall Party", "12.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13330", "मध्य प्रदेश", "भोपाल", "पीयूष जैन", "राइट टू रिकॉल पार्टी"},
            {"Madhya Pradesh", "Bhopal", "Praveen Singh Thakur", "Independent", "1.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13339", "मध्य प्रदेश", "भोपाल", "प्रवीण सिंह ठाकुर", "निर्दलीय"},
            {"Madhya Pradesh", "Bhopal", "Mahendra Katiyar", "Independent", "8.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13340", "मध्य प्रदेश", "भोपाल", "महेंद्र कटियार", "निर्दलीय"},
            {"Madhya Pradesh", "Chhindwara", "Rajkumar Saryam", "Gondvana Gantantra Party", "8.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10341", "मध्य प्रदेश", "छिंदवाड़ा", "राजकुमार सरियाम", "गोंडवाना गणतंत्र पार्टी"},
            {"Madhya Pradesh", "Chhindwara", "Jogilal Irpachi", "Independent", "3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10659", "मध्य प्रदेश", "छिंदवाड़ा", "जोगीलाल इरपाची", "निर्दलीय"},
            {"Madhya Pradesh", "Damoh", "Man Singh", "Bhartiya Shakti Chetna Party", "18.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11582", "मध्य प्रदेश", "दमोह", "मान सिंह", "भारतीय शक्ति चेतना पार्टी"},
            {"Madhya Pradesh", "Damoh", "Thakur Das", "Pragatishil Samajwadi Party (Lohia)", "2.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11584", "मध्य प्रदेश", "दमोह", "ठाकुर दास", "प्रगति समाजवादी पार्टी (लोहिया)"},
            {"Madhya Pradesh", "Damoh", "Prahlad Bhaiya", "Independent", "23.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12584", "मध्य प्रदेश", "दमोह", "प्रहलाद भैया", "निर्दलीय"},
            {"Madhya Pradesh", "Damoh", "Vikas Kewalrao Nagvanshi", "Bharat Prabhat Party", "95Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12000", "मध्य प्रदेश", "दमोह", "विकास केवलाराव नागवंशी", "भारत प्रभात पार्टी"},
            {"Madhya Pradesh", "Guna", "Rekha Bai", "Aajad Bharat Party (Democratic)", "2.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12656", "मध्य प्रदेश", "गुना", "रेखा बाई", "आजाद भारत पार्टी (लोकतांत्रिक)"},
            {"Madhya Pradesh", "Guna", "Amit Khare", "Ambedkarite Party of India", "1.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12659", "मध्य प्रदेश", "गुना", "अमित खरे", "भारत की अम्बेडकरवादी पार्टी"},
            {"Madhya Pradesh", "Guna", "Harbhajan Singh Rajpoot", "Bharat Prabhat Party", "2.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12654", "मध्य प्रदेश", "गुना", "हरभजन सिंह राजपूत", "भारत प्रभात पार्टी"},
            {"Madhya Pradesh", "Guna", "Bhoopendra Singh Chauhan", "Independent", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12238", "मध्य प्रदेश", "गुना", "भूपेंद्र सिंह चौहान", "निर्दलीय"},
            {"Madhya Pradesh", "Guna", "Manish Shrivastav", "Socialist Unity Centre of India (Communist)", "1.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12232", "मध्य प्रदेश", "गुना", "मनीष श्रीवास्तव", "भारतीय समाजवादी एकता केंद्र (कम्युनिस्ट)"},
            {"Madhya Pradesh", "Gwalior", "Jitendra Jain", "Bharat Prabhat Party", "77.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12671", "मध्य प्रदेश", "ग्वालियर", "जितेंद्र जैन", "भारत प्रभात पार्टी"},
            {"Madhya Pradesh", "Gwalior", "Sugreev Singh", "Jan Adhikar Party", "60.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12682", "मध्य प्रदेश", "ग्वालियर", "सुग्रीव सिंह", "जन आढ़ती पार्टी"},
            {"Madhya Pradesh", "Gwalior", "Deepak Kumar", "Independent", "64.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12673", "मध्य प्रदेश", "ग्वालियर", "दीपक कुमार", "निर्दलीय"},
            {"Madhya Pradesh", "Gwalior", "Geeta Rani", "Peoples Party of India (Democratic)", "11.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12684", "मध्य प्रदेश", "ग्वालियर", "गीता रानी", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
            {"Madhya Pradesh", "Hoshangabad", "Shailendra", "Independent", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12008", "मध्य प्रदेश", "होशंगाबाद", "शैलेंद्र", "निर्दलीय"},
            {"Madhya Pradesh", "Hoshangabad", "Dinesh Katare", "Ambedkarite Party of India", "30500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12002", "मध्य प्रदेश", "होशंगाबाद", "दिनेश कटारे", "भारत की अम्बेडकरवादी पार्टी"},
            {"Madhya Pradesh", "Hoshangabad", "Pandit Devendra Sharma", "Sapaks Party", "32000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12006", "मध्य प्रदेश", "होशंगाबाद", "पंडित देवेंद्र शर्मा", "सपाक्स पार्टी"},
            {"Madhya Pradesh", "Hoshangabad", "Saligram Makodiya", "Independent", "52.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11589", "मध्य प्रदेश", "होशंगाबाद", "सालिगराम मकोडिया", "निर्दलीय"},
            {"Madhya Pradesh", "Hoshangabad", "Madan Mohan", "Independent", "30.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12004", "मध्य प्रदेश", "होशंगाबाद", "मदन मोहन", "निर्दलीय"},
            {"Madhya Pradesh", "Jabalpur", "Chandra Prakash Bhatnagar", "AARAKSHAN VIRODHI PARTY", "22.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10311", "मध्य प्रदेश", "जबलपुर", "चंद्र प्रकाश भटनागर", "AAKAKSHAN VIRODHI पार्टी"},
            {"Madhya Pradesh", "Jabalpur", "Dr. Dhai Akshar (Rakesh Sonkar)", "Independent", "14.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10627", "मध्य प्रदेश", "जबलपुर", "डॉ। ढाई अक्षर (राकेश सोनकर)", "निर्दलीय"},
            {"Madhya Pradesh", "Jabalpur", "Er. Rupram Singh", "Independent", "40.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10628", "मध्य प्रदेश", "जबलपुर", "एर। रूपराम सिंह", "निर्दलीय"},
            {"Madhya Pradesh", "Jabalpur", "Lakshminarayan Jagnnath Singh Lodhi", "Independent", "15.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10630", "मध्य प्रदेश", "जबलपुर", "लक्ष्मीनारायण जगन्नाथ सिंह लोधी", "निर्दलीय"},
            {"Madhya Pradesh", "Khajuraho", "Rajkumar Sharma", "Independent", "6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12025", "मध्य प्रदेश", "खजुराहो", "राजकुमार शर्मा", "निर्दलीय"},
            {"Madhya Pradesh", "Khajuraho", "Narendra", "Independent", "37.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12020", "मध्य प्रदेश", "खजुराहो", "नरेंद्र", "निर्दलीय"},
            {"Madhya Pradesh", "Khajuraho", "Sant Kumar Sharma", "Samagra Utthan Party", "3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12026", "मध्य प्रदेश", "खजुराहो", "संत कुमार शर्मा", "समागम उत्थान पार्टी"},
            {"Madhya Pradesh", "Khajuraho", "Ashwani Kumar Dubey", "Sarvodaya Bharat Party", "24.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12012", "मध्य प्रदेश", "खजुराहो", "अश्वनी कुमार दुबे", "सर्वोदय भारत पार्टी"},
            {"Madhya Pradesh", "Khajuraho", "Bhoopat Kumar", "Independent", "2.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12014", "मध्य प्रदेश", "खजुराहो", "भूपत कुमार", "निर्दलीय"},
            {"Madhya Pradesh", "Khajuraho", "Giriraj Kishor", "Independent", "26Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12016", "मध्य प्रदेश", "खजुराहो", "गिरिराज किशोर", "निर्दलीय"},
            {"Madhya Pradesh", "Khajuraho", "Mohammad Imran", "Independent", "18.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12019", "मध्य प्रदेश", "खजुराहो", "मोहम्मद इमरान", "निर्दलीय"},
            {"Madhya Pradesh", "Khajuraho", "Desh Pal", "Ambedkarite Party of India", "7.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12015", "मध्य प्रदेश", "खजुराहो", "देश पाल", "भारत की अम्बेडकरवादी पार्टी"},
            {"Madhya Pradesh", "Khajuraho", "Advocate Rakesh Kumar Shukla", "All India Forward Bloc", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12011", "मध्य प्रदेश", "खजुराहो", "एडवोकेट राकेश कुमार शुक्ला", "ऑल इंडिया फॉरवर्ड ब्लॉक"},
            {"Madhya Pradesh", "Mandla", "Sanjeev Kumar Pandram", "Hindusthan Nirman Dal", "18.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10326", "मध्य प्रदेश", "मंडला", "संजीव कुमार पंडराम", "हिंदुस्तान निर्माण दल"},
            {"Madhya Pradesh", "Mandla", "Advocate-Devsingh Kumre", "Independent", "24.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10666", "मध्य प्रदेश", "मंडला", "वकील-देवीसिंह कुमरे", "निर्दलीय"},
            {"Madhya Pradesh", "Mandla", "Bharat Singh Poosam", "Independent", "23.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10327", "मध्य प्रदेश", "मंडला", "भरत सिंह पूसाम", "निर्दलीय"},
            {"Madhya Pradesh", "Mandla", "Ajeet Dhurwey", "Independent", "6.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10667", "मध्य प्रदेश", "मंडला", "अजीत धुर्वे", "निर्दलीय"},
            {"Madhya Pradesh", "Morena", "Tofeek Khan", "Independent", "18.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12249", "मध्य प्रदेश", "मोरैना", "टोफिक खान", "निर्दलीय"},
            {"Madhya Pradesh", "Morena", "Laxmi Baghel", "Independent", "38Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12650", "मध्य प्रदेश", "मोरैना", "लक्ष्मी बघेल", "निर्दलीय"},
            {"Madhya Pradesh", "Morena", "Ramlakhan Meena", "Rashtriya Krantikari Samajwadi Party", "46Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12643", "मध्य प्रदेश", "मोरैना", "रामलखन मीणा", "राष्ट्रीय क्रांति समाजवादी पार्टी"},
            {"Madhya Pradesh", "Morena", "Narendra Singh", "Republican Party of India (Reformist)", "3.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=13713", "मध्य प्रदेश", "मोरैना", "नरेंद्र सिंह", "भारतीय रिपब्लिकन पार्टी (सुधारवादी)"},
            {"Madhya Pradesh", "Morena", "Dr. Randhir Singh Ruhal", "Rashtra Nirman Party", "4.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12634", "मध्य प्रदेश", "मोरैना", "डॉ। रणधीर सिंह रुहल", "राष्ट्र निर्माण पार्टी"},
            {"Madhya Pradesh", "Morena", "Rajveer", "Independent", "69.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12651", "मध्य प्रदेश", "मोरैना", "राजवीर", "निर्दलीय"},
            {"Madhya Pradesh", "Morena", "Vivek", "Hindusthan Nirman Dal", "10.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12653", "मध्य प्रदेश", "मोरैना", "विवेक", "हिंदुस्तान निर्माण दल"},
            {"Madhya Pradesh", "Morena", "Ashok Rajoriya", "Vishva SHakti Party", "54.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12644", "मध्य प्रदेश", "मोरैना", "अशोक राजोरिया", "विश्वाशक्ति पार्टी"},
            {"Madhya Pradesh", "Rajgarh", "Imamuddin Khan", "Independent", "13.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12629", "मध्य प्रदेश", "राजगढ़", "इमामुद्दीन खान", "निर्दलीय"},
            {"Madhya Pradesh", "Rajgarh", "Parvat Singh", "Ambedkarite Party of India", "56000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12632", "मध्य प्रदेश", "राजगढ़", "पर्वत सिंह", "भारत की अम्बेडकरवादी पार्टी"},
            {"Madhya Pradesh", "Rajgarh", "Divyendra Dubey Advocate", "Independent", "15.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12255", "मध्य प्रदेश", "राजगढ़", "दिव्येंद्र दुबे एडवोकेट", "निर्दलीय"},
            {"Madhya Pradesh", "Rajgarh", "Sanjey Gupta", "Sapaks Party", "37Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12631", "मध्य प्रदेश", "राजगढ़", "संजी गुप्ता", "सपाक्स पार्टी"},
            {"Madhya Pradesh", "Rewa", "Sushil Kumar Mishra", "Independent", "62.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12041", "मध्य प्रदेश", "रीवा", "सुशील कुमार मिश्रा", "निर्दलीय"},
            {"Madhya Pradesh", "Rewa", "Akhilesh Saket", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12030", "मध्य प्रदेश", "रीवा", "अखिलेश साकेत", "निर्दलीय"},
            {"Madhya Pradesh", "Rewa", "Ram Kalesh Saket", "Independent", "1.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11604", "मध्य प्रदेश", "रीवा", "राम कलेश साकेत", "निर्दलीय"},
            {"Madhya Pradesh", "Rewa", "Vikash Kumar", "Bahujan Samaj Party", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11598", "मध्य प्रदेश", "रीवा", "विकाश कुमार", "बहुजन समाज पार्टी"},
            {"Madhya Pradesh", "Rewa", "Shakuntala", "Sapaks Party", "3.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12039", "मध्य प्रदेश", "रीवा", "शकुंतला", "सपाक्स पार्टी"},
            {"Madhya Pradesh", "Rewa", "Subhranshu Dwivedi", "Kisan Party of India", "6.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12040", "मध्य प्रदेश", "रीवा", "सुभ्रांशु द्विवेदी", "भारत की किसान पार्टी"},
            {"Madhya Pradesh", "Rewa", "Girijesh Singh Senger", "Communist Party of India (Marxist)", "35Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11221", "मध्य प्रदेश", "रीवा", "गिरिजेश सिंह सेंगर", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
            {"Madhya Pradesh", "Rewa", "Arun Kumar Satnami", "Bahujan Mukti Party", "38.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11605", "मध्य प्रदेश", "रीवा", "अरुण कुमार सतनामी", "बहुजन मुक्ति पार्टी"},
            {"Madhya Pradesh", "Satna", "Shashank Singh Baghel", "Sapaks Party", "2.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11610", "मध्य प्रदेश", "सतना", "शशांक सिंह बघेल", "सपाक्स पार्टी"},
            {"Madhya Pradesh", "Satna", "Rajendra Tripathi", "Bharatiya Jan Morcha Party", "1.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12049", "मध्य प्रदेश", "सतना", "राजेंद्र त्रिपाठी", "भारतीय जन मोर्चा पार्टी"},
            {"Madhya Pradesh", "Satna", "Dr Suresh Tripathi", "Independent", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11617", "मध्य प्रदेश", "सतना", "डॉ। सुरेश त्रिपाठी", "निर्दलीय"},
            {"Madhya Pradesh", "Sidhi", "Rakesh", "Independent", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10602", "मध्य प्रदेश", "सीधी", "राकेश", "निर्दलीय"},
            {"Madhya Pradesh", "Sidhi", "Ramraj", "Independent", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10607", "मध्य प्रदेश", "सीधी", "रामराज", "निर्दलीय"},
            {"Madhya Pradesh", "Sidhi", "Dileep", "Independent", "45000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10597", "मध्य प्रदेश", "सीधी", "दिलीप", "निर्दलीय"},
            {"Madhya Pradesh", "Sidhi", "Lalta", "Independent", "1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10599", "मध्य प्रदेश", "सीधी", "Lalta", "निर्दलीय"},
            {"Madhya Pradesh", "Sidhi", "Fatte Bahadur Singh Markam", "Gondvana Gantantra Party", "61.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10274", "मध्य प्रदेश", "सीधी", "फत्ते बहादुर सिंह मरकाम", "गोंडवाना गणतंत्र पार्टी"},
            {"Madhya Pradesh", "Sidhi", "Anup Kumar Singh", "Samagra Utthan Party", "28.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10594", "मध्य प्रदेश", "सीधी", "अनूप कुमार सिंह", "समागम उत्थान पार्टी"},
            {"Madhya Pradesh", "Sidhi", "Dharmendra Singh Baghel", "Independent", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10596", "मध्य प्रदेश", "सीधी", "धर्मेंद्र सिंह बघेल", "निर्दलीय"},
            {"Madhya Pradesh", "Tikamgarh", "Kamta Prasad", "Pragatishil Samajwadi Party (Lohia)", "18.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11623", "मध्य प्रदेश", "टीकमगढ़", "कामता प्रसाद", "प्रगति समाजवादी पार्टी (लोहिया)"},
            {"Madhya Pradesh", "Tikamgarh", "R.D. Prajapati", "Samajwadi Party", "83.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11226", "मध्य प्रदेश", "टीकमगढ़", "आरडी प्रजापति", "समाजवादी पार्टी"},
            {"Madhya Pradesh", "Tikamgarh", "R.B. Prajapati Advocate", "Independent", "4.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11620", "मध्य प्रदेश", "टीकमगढ़", "आरबी प्रजापति एडवोकेट", "निर्दलीय"},
            {"Madhya Pradesh", "Tikamgarh", "Shriram Nagar", "Sapaks Party", "6.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12063", "मध्य प्रदेश", "टीकमगढ़", "श्रीराम नगर", "सपाक्स पार्टी"},
            {"Madhya Pradesh", "Tikamgarh", "Nandram Prajapati", "Adarsh Nyay Rakshak Party", "12.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11227", "मध्य प्रदेश", "टीकमगढ़", "नंदराम प्रजापति", "आदर्श न्याय रक्षक पार्टी"},
            {"Madhya Pradesh", "Vidisha", "Geetawali Er. P.S. Ahirwar", "Bahujan Samaj Party", "4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12262", "मध्य प्रदेश", "विदिशा", "गीतावली एर। पीएस अहिरवार", "बहुजन समाज पार्टी"},
            {"Madhya Pradesh", "Vidisha", "Devendra Singh Chouhan", "Independent", "3.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12663", "मध्य प्रदेश", "विदिशा", "देवेंद्र सिंह चौहान", "निर्दलीय"},
            {"Madhya Pradesh", "Vidisha", "Sudhir Kumar", "Independent", "69.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12667", "मध्य प्रदेश", "विदिशा", "सुधीर कुमार", "निर्दलीय"},
            {"Madhya Pradesh", "Vidisha", "Vivek", "Independent", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12662", "मध्य प्रदेश", "विदिशा", "विवेक", "निर्दलीय"},
            {"Madhya Pradesh", "Vidisha", "Anil Malviya Patrakar", "Independent", "19.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=12661", "मध्य प्रदेश", "विदिशा", "अनिल मालवीय पाटकर", "निर्दलीय"},
    };

    public static final String[][] red_bucket = {
            {"Madhya Pradesh", "Balaghat", "Karan Singh Naagpure", "2", " ", "मध्य प्रदेश", "बालाघाट", "करण सिंह नागपुरे", " "},
            {"Madhya Pradesh", "Balaghat", "Jesingh Tekam", "3", " ", "मध्य प्रदेश", "बालाघाट", "जेसिंह टेकाम", " "},
            {"Madhya Pradesh", "Balaghat", "Madhu Kumar", "1", " ", "मध्य प्रदेश", "बालाघाट", "मधु कुमार", " "},
            {"Madhya Pradesh", "Balaghat", "Kankar", "2", " ", "मध्य प्रदेश", "बालाघाट", "kankar", " "},
            {"Madhya Pradesh", "Balaghat", "Yuvraj Singh Bais", "3", " ", "मध्य प्रदेश", "बालाघाट", "युवराज सिंह बैस", " "},
            {"Madhya Pradesh", "Balaghat", "Ruplal Kutrahe (Samaj Sevak ) Lodhi", "2", " ", "मध्य प्रदेश", "बालाघाट", "रूपलाल कुत्रे (समाज सेवक) लोधी", " "},
            {"Madhya Pradesh", "Balaghat", "Dr. Dhal Singh Bisen", "1", " ", "मध्य प्रदेश", "बालाघाट", "डॉ। ढाल सिंह बिसेन", " "},
            {"Madhya Pradesh", "Balaghat", "Ali . M. R. Khan", "2", " ", "मध्य प्रदेश", "बालाघाट", "अली। एमआर खान", " "},
            {"Madhya Pradesh", "Balaghat", "Rajan Masih", "4", " ", "मध्य प्रदेश", "बालाघाट", "राजन मासिह", " "},
            {"Madhya Pradesh", "Balaghat", "Mukesh Bansod", "4", " ", "मध्य प्रदेश", "बालाघाट", "मुकेश बंसोड़", " "},
            {"Madhya Pradesh", "Balaghat", "Kishor Samrite", "2", " ", "मध्य प्रदेश", "बालाघाट", "किशोर समरीते", " "},
            {"Madhya Pradesh", "Balaghat", "Rakesh Kumar", "2", " ", "मध्य प्रदेश", "बालाघाट", "राकेश कुमार", " "},
            {"Madhya Pradesh", "Betul", "Bisram Uikey", "4", " ", "मध्य प्रदेश", "बेतुल", "बिसराम उइके", " "},
            {"Madhya Pradesh", "Betul", "Bhagcharan Warkade", "4", " ", "मध्य प्रदेश", "बेतुल", "भगचरन वरकडे", " "},
            {"Madhya Pradesh", "Betul", "Ashok Bhalavi", "4", " ", "मध्य प्रदेश", "बेतुल", "अशोक भालवी", " "},
            {"Madhya Pradesh", "Betul", "Ramu Tekam", "1", " ", "मध्य प्रदेश", "बेतुल", "रामू टेकम", " "},
            {"Madhya Pradesh", "Betul", "Durga Das (D.D.) Uikey", "1", " ", "मध्य प्रदेश", "बेतुल", "दुर्गा दास (डीडी) उइके", " "},
            {"Madhya Pradesh", "Betul", "Nimish Sariyam", "2", " ", "मध्य प्रदेश", "बेतुल", "निमिष सरियाम", " "},
            {"Madhya Pradesh", "Bhind", "Madan Chhilwar", "4", " ", "मध्य प्रदेश", "भिंड", "मदन छिलवार", " "},
            {"Madhya Pradesh", "Bhind", "Dharm Singh Bhargav", "4", " ", "मध्य प्रदेश", "भिंड", "धर्म सिंह भार्गव", " "},
            {"Madhya Pradesh", "Bhind", "Jitendra Singh", "4", " ", "मध्य प्रदेश", "भिंड", "जितेंद्र सिंह", " "},
            {"Madhya Pradesh", "Bhind", "Babu Ram Jamor", "3", " ", "मध्य प्रदेश", "भिंड", "बाबू राम जमर", " "},
            {"Madhya Pradesh", "Bhind", "Manohar Lal Patwa (Lalu Kori)", "2", " ", "मध्य प्रदेश", "भिंड", "मनोहर लाल पटवा (लालू कोरी)", " "},
            {"Madhya Pradesh", "Bhind", "Roop Singh", "4", " ", "मध्य प्रदेश", "भिंड", "रूप सिंह", " "},
            {"Madhya Pradesh", "Bhind", "Vijay Singh Patwa", "4", " ", "मध्य प्रदेश", "भिंड", "विजय सिंह पटवा", " "},
            {"Madhya Pradesh", "Bhind", "Harkisor Kori", "4", " ", "मध्य प्रदेश", "भिंड", "हरकिसर कोरी", " "},
            {"Madhya Pradesh", "Bhind", "Brikhbhan Dohare", "4", " ", "मध्य प्रदेश", "भिंड", "बृहभान दोहारे", " "},
            {"Madhya Pradesh", "Bhind", "Rajesh Kumar Jatav", "4", " ", "मध्य प्रदेश", "भिंड", "राजेश कुमार जाटव", " "},
            {"Madhya Pradesh", "Bhind", "Sandhya Ray", "1", " ", "मध्य प्रदेश", "भिंड", "संध्या रे", " "},
            {"Madhya Pradesh", "Bhind", "Omprakash Shakya", "2", " ", "मध्य प्रदेश", "भिंड", "ओमप्रकाश शाक्य", " "},
            {"Madhya Pradesh", "Bhind", "Umesh Garg", "4", " ", "मध्य प्रदेश", "भिंड", "उमेश गर्ग", " "},
            {"Madhya Pradesh", "Bhind", "Ashok Singh", "4", " ", "मध्य प्रदेश", "भिंड", "अशोक सिंह", " "},
            {"Madhya Pradesh", "Bhind", "Devashish", "1", " ", "मध्य प्रदेश", "भिंड", "Devashish", " "},
            {"Madhya Pradesh", "Bhind", "Dileep Kumar Dohare (Advocat)", "2", " ", "मध्य प्रदेश", "भिंड", "दिलीप कुमार दोहारे (एडवोकेट)", " "},
            {"Madhya Pradesh", "Bhind", "Kishori Lal Shakya", "3", " ", "मध्य प्रदेश", "भिंड", "किशोरी लाल शाक्य", " "},
            {"Madhya Pradesh", "Bhopal", "Priyanka Khare", "4", " ", "मध्य प्रदेश", "भोपाल", "प्रियंका खरे", " "},
            {"Madhya Pradesh", "Bhopal", "Lata Suryawanshi", "4", " ", "मध्य प्रदेश", "भोपाल", "लता सूर्यवंशी", " "},
            {"Madhya Pradesh", "Bhopal", "Moh. Ateek", "4", " ", "मध्य प्रदेश", "भोपाल", "मोह। Ateek", " "},
            {"Madhya Pradesh", "Bhopal", "Gautam Nagdavane", "4", " ", "मध्य प्रदेश", "भोपाल", "गौतम नागदावने", " "},
            {"Madhya Pradesh", "Bhopal", "J.C. Barai", "4", " ", "मध्य प्रदेश", "भोपाल", "जे सी बरई", " "},
            {"Madhya Pradesh", "Bhopal", "Kamlesh Dangi Thakur", "2", " ", "मध्य प्रदेश", "भोपाल", "कमलेश डांगी ठाकुर", " "},
            {"Madhya Pradesh", "Bhopal", "Bal Ram Singh Tomar", "4", " ", "मध्य प्रदेश", "भोपाल", "बाल राम सिंह तोमर", " "},
            {"Madhya Pradesh", "Bhopal", "Digvijaya Singh", "1", " ", "मध्य प्रदेश", "भोपाल", "दिग्विजय सिंह", " "},
            {"Madhya Pradesh", "Bhopal", "Shrimati Hemlata Pathak", "4", " ", "मध्य प्रदेश", "भोपाल", "श्रीमति हेमलता पाठक", " "},
            {"Madhya Pradesh", "Bhopal", "Sadhvi Pragya Singh Thakur", "1", " ", "मध्य प्रदेश", "भोपाल", "साध्वी प्रज्ञा सिंह ठाकुर", " "},
            {"Madhya Pradesh", "Bhopal", "Devendra Prakash Mishra", "2", " ", "मध्य प्रदेश", "भोपाल", "देवेंद्र प्रकाश मिश्र", " "},
            {"Madhya Pradesh", "Bhopal", "Mukesh Kumar Gupta", "4", " ", "मध्य प्रदेश", "भोपाल", "मुकेश कुमार गुप्ता", " "},
            {"Madhya Pradesh", "Bhopal", "Ramsushil Sharma", "4", " ", "मध्य प्रदेश", "भोपाल", "रामसुशील शर्मा", " "},
            {"Madhya Pradesh", "Bhopal", "Madho Singh Ahirwar", "4", " ", "मध्य प्रदेश", "भोपाल", "माधोसिंह अहिरवार", " "},
            {"Madhya Pradesh", "Bhopal", "Prabha Bharti", "4", " ", "मध्य प्रदेश", "भोपाल", "प्रभा भारती", " "},
            {"Madhya Pradesh", "Bhopal", "Mahendra Kumar", "4", " ", "मध्य प्रदेश", "भोपाल", "महेंद्र कुमार", " "},
            {"Madhya Pradesh", "Bhopal", "Md. Iqbal Khan", "4", " ", "मध्य प्रदेश", "भोपाल", "मो। इकबाल खान", " "},
            {"Madhya Pradesh", "Bhopal", "Kamlesh Namdev", "4", " ", "मध्य प्रदेश", "भोपाल", "कमलेश नामदेव", " "},
            {"Madhya Pradesh", "Chhindwara", "Subhash Shukla", "4", " ", "मध्य प्रदेश", "छिंदवाड़ा", "सुभाष शुक्ला", " "},
            {"Madhya Pradesh", "Chhindwara", "Rameshwar Dhurve", "4", " ", "मध्य प्रदेश", "छिंदवाड़ा", "रामेश्वर धुर्वे", " "},
            {"Madhya Pradesh", "Chhindwara", "Dinesh Singh Uikey", "4", " ", "मध्य प्रदेश", "छिंदवाड़ा", "दिनेश सिंह उइके", " "},
            {"Madhya Pradesh", "Chhindwara", "Ramdas Uikey", "4", " ", "मध्य प्रदेश", "छिंदवाड़ा", "रामदास उइके", " "},
            {"Madhya Pradesh", "Chhindwara", "Nakul Nath", "1", " ", "मध्य प्रदेश", "छिंदवाड़ा", "नकुल नाथ", " "},
            {"Madhya Pradesh", "Chhindwara", "M. P. Vishwakarma", "3", " ", "मध्य प्रदेश", "छिंदवाड़ा", "सांसद विश्वकर्मा", " "},
            {"Madhya Pradesh", "Chhindwara", "Dhaniram Yaduwanshi", "4", " ", "मध्य प्रदेश", "छिंदवाड़ा", "धनीराम यदुवंशी", " "},
            {"Madhya Pradesh", "Chhindwara", "Nathanshah Kawret", "1", " ", "मध्य प्रदेश", "छिंदवाड़ा", "नतनशाह कवरात", " "},
            {"Madhya Pradesh", "Chhindwara", "Manmohan Shah Batti", "2", " ", "मध्य प्रदेश", "छिंदवाड़ा", "मनमोहन शाह बत्तीसी", " "},
            {"Madhya Pradesh", "Chhindwara", "Rajesh Tantrik", "2", " ", "मध्य प्रदेश", "छिंदवाड़ा", "राजेश तांत्रिक", " "},
            {"Madhya Pradesh", "Chhindwara", "Gyaneshwar Gajbhiye", "4", " ", "मध्य प्रदेश", "छिंदवाड़ा", "ज्ञानेश्वर गजभिये", " "},
            {"Madhya Pradesh", "Chhindwara", "Hemendra Gohar", "2", " ", "मध्य प्रदेश", "छिंदवाड़ा", "हेमेंद्र गोहर", " "},
            {"Madhya Pradesh", "Damoh", "Richa Purshottam Choubey (Hariom)", "4", " ", "मध्य प्रदेश", "दमोह", "ऋचा पुरुषोत्तम चौबे (हरिओम)", " "},
            {"Madhya Pradesh", "Damoh", "Sharada Parsad Patel", "3", " ", "मध्य प्रदेश", "दमोह", "शारदा पारस पटेल", " "},
            {"Madhya Pradesh", "Damoh", "Manvendra Singh", "4", " ", "मध्य प्रदेश", "दमोह", "मानवेन्द्र सिंह", " "},
            {"Madhya Pradesh", "Damoh", "Prahalad", "4", " ", "मध्य प्रदेश", "दमोह", "प्रहलाद", " "},
            {"Madhya Pradesh", "Damoh", "Devi Prasad", "4", " ", "मध्य प्रदेश", "दमोह", "देवी प्रसाद", " "},
            {"Madhya Pradesh", "Damoh", "Manu Singh Maravi", "4", " ", "मध्य प्रदेश", "दमोह", "मनु सिंह मरावी", " "},
            {"Madhya Pradesh", "Damoh", "Prahalad Singh Patel", "1", " ", "मध्य प्रदेश", "दमोह", "प्रहलाद सिंह पटेल", " "},
            {"Madhya Pradesh", "Damoh", "Jitendra Khare", "4", " ", "मध्य प्रदेश", "दमोह", "जितेंद्र खरे", " "},
            {"Madhya Pradesh", "Damoh", "Anant Lal Basor", "3", " ", "मध्य प्रदेश", "दमोह", "अनंत लाल बसोर", " "},
            {"Madhya Pradesh", "Damoh", "Kamlesh Asati", "4", " ", "मध्य प्रदेश", "दमोह", "कमलेश असाटी", " "},
            {"Madhya Pradesh", "Damoh", "Pratap Singh", "1", " ", "मध्य प्रदेश", "दमोह", "प्रताप सिंह", " "},
            {"Madhya Pradesh", "Guna", "Ajay Singh Kushwah", "4", " ", "मध्य प्रदेश", "गुना", "अजय सिंह कुशवाह", " "},
            {"Madhya Pradesh", "Guna", "Chandr Kumar Shrivastava (Chandu)", "4", " ", "मध्य प्रदेश", "गुना", "चंद्र कुमार श्रीवास्तव (चंदू)", " "},
            {"Madhya Pradesh", "Guna", "Santosh Yadav", "4", " ", "मध्य प्रदेश", "गुना", "संतोष यादव", " "},
            {"Madhya Pradesh", "Guna", "Jyotiraditya M. Scindia", "1", " ", "मध्य प्रदेश", "गुना", "ज्योतिरादित्य एम। सिंधिया", " "},
            {"Madhya Pradesh", "Guna", "Krishna Pal Singh", "1", " ", "मध्य प्रदेश", "गुना", "कृष्ण पाल सिंह", " "},
            {"Madhya Pradesh", "Guna", "Dhakad Lokendra Singh Rajpoot", "2", " ", "मध्य प्रदेश", "गुना", "धाकड़ लोकेंद्र सिंह राजपूत", " "},
            {"Madhya Pradesh", "Guna", "Bhan Singh", "4", " ", "मध्य प्रदेश", "गुना", "भान सिंह", " "},
            {"Madhya Pradesh", "Guna", "Omprakash", "4", " ", "मध्य प्रदेश", "गुना", "ओमप्रकाश", " "},
            {"Madhya Pradesh", "Gwalior", "Mamta Balveer Singh Kushwah", "4", " ", "मध्य प्रदेश", "ग्वालियर", "ममता बलवीर सिंह कुशवाह", " "},
            {"Madhya Pradesh", "Gwalior", "Govind Singh", "4", " ", "मध्य प्रदेश", "ग्वालियर", "गोविंद सिंह", " "},
            {"Madhya Pradesh", "Gwalior", "Pransingh", "4", " ", "मध्य प्रदेश", "ग्वालियर", "Pransingh", " "},
            {"Madhya Pradesh", "Gwalior", "Vishnukant Sharma", "4", " ", "मध्य प्रदेश", "ग्वालियर", "विष्णुकांत शर्मा", " "},
            {"Madhya Pradesh", "Gwalior", "Ashok Khan", "2", " ", "मध्य प्रदेश", "ग्वालियर", "अशोक खान", " "},
            {"Madhya Pradesh", "Gwalior", "Nandkishor Sahu", "4", " ", "मध्य प्रदेश", "ग्वालियर", "नंदकिशोर साहू", " "},
            {"Madhya Pradesh", "Gwalior", "Braj Mohan", "4", " ", "मध्य प्रदेश", "ग्वालियर", "ब्रज मोहन", " "},
            {"Madhya Pradesh", "Gwalior", "Keshav Rai Chaudhari", "4", " ", "मध्य प्रदेश", "ग्वालियर", "केशव राय चौधरी", " "},
            {"Madhya Pradesh", "Gwalior", "Sovran Singh", "4", " ", "मध्य प्रदेश", "ग्वालियर", "सोवरन सिंह", " "},
            {"Madhya Pradesh", "Gwalior", "Vivek Narayan Shejwalkar", "1", " ", "मध्य प्रदेश", "ग्वालियर", "विवेक नारायण शेजवलकर", " "},
            {"Madhya Pradesh", "Gwalior", "Hanumant Singh", "4", " ", "मध्य प्रदेश", "ग्वालियर", "हनुमंत सिंह", " "},
            {"Madhya Pradesh", "Gwalior", "Sunil Gopal", "2", " ", "मध्य प्रदेश", "ग्वालियर", "सुनील गोपाल", " "},
            {"Madhya Pradesh", "Gwalior", "Narayan Namdev", "4", " ", "मध्य प्रदेश", "ग्वालियर", "नारायण नामदेव", " "},
            {"Madhya Pradesh", "Gwalior", "Ashok Singh", "1", " ", "मध्य प्रदेश", "ग्वालियर", "अशोक सिंह", " "},
            {"Madhya Pradesh", "Hoshangabad", "Rajesh Kumar Uikey", "4", " ", "मध्य प्रदेश", "होशंगाबाद", "राजेश कुमार उइके", " "},
            {"Madhya Pradesh", "Hoshangabad", "Arya Ravi Parihar", "4", " ", "मध्य प्रदेश", "होशंगाबाद", "आर्य रवि परिहार", " "},
            {"Madhya Pradesh", "Hoshangabad", "Bhavanishankar", "2", " ", "मध्य प्रदेश", "होशंगाबाद", "Bhavanishankar", " "},
            {"Madhya Pradesh", "Hoshangabad", "Shailendra Diwan Chandarbhan Singh", "1", " ", "मध्य प्रदेश", "होशंगाबाद", "शैलेंद्र दीवान चंद्रभान सिंह", " "},
            {"Madhya Pradesh", "Hoshangabad", "M.P. Choudhary", "3", " ", "मध्य प्रदेश", "होशंगाबाद", "सांसद चौधरी", " "},
            {"Madhya Pradesh", "Hoshangabad", "Rao Uday Pratap Singh", "1", " ", "मध्य प्रदेश", "होशंगाबाद", "राव उदय प्रताप सिंह", " "},
            {"Madhya Pradesh", "Jabalpur", "Dhanuk", "4", " ", "मध्य प्रदेश", "जबलपुर", "Dhanuk", " "},
            {"Madhya Pradesh", "Jabalpur", "Ramdayal Prajapat", "4", " ", "मध्य प्रदेश", "जबलपुर", "रामदयाल प्रजापत", " "},
            {"Madhya Pradesh", "Jabalpur", "Rakesh Singh", "1", " ", "मध्य प्रदेश", "जबलपुर", "राकेश सिंह", " "},
            {"Madhya Pradesh", "Jabalpur", "Shahnaz B Ansari", "4", " ", "मध्य प्रदेश", "जबलपुर", "शहनाज बी अंसारी", " "},
            {"Madhya Pradesh", "Jabalpur", "Rakesh Singh S/O Nathuram", "4", " ", "मध्य प्रदेश", "जबलपुर", "राकेश सिंह एस / ओ नाथूराम", " "},
            {"Madhya Pradesh", "Jabalpur", "Kuldeep Ahirwar", "4", " ", "मध्य प्रदेश", "जबलपुर", "कुलदीप अहिरवार", " "},
            {"Madhya Pradesh", "Jabalpur", "Gulab Singh @ Vivek", "4", " ", "मध्य प्रदेश", "जबलपुर", "गुलाब सिंह @ विवेक", " "},
            {"Madhya Pradesh", "Jabalpur", "Vinay Kumar Jain", "4", " ", "मध्य प्रदेश", "जबलपुर", "विनय कुमार जैन विष्णु भैया", " "},
            {"Madhya Pradesh", "Jabalpur", "Ashok Singh Lodhi", "4", " ", "मध्य प्रदेश", "जबलपुर", "अशोक सिंह लोधी", " "},
            {"Madhya Pradesh", "Jabalpur", "Shree Lal Markam(Bade Shri)", "4", " ", "मध्य प्रदेश", "जबलपुर", "श्री लाल मरकाम (बाडे श्री)", " "},
            {"Madhya Pradesh", "Jabalpur", "Sukhdev Dahiya", "4", " ", "मध्य प्रदेश", "जबलपुर", "सुखदेव दहिया", " "},
            {"Madhya Pradesh", "Jabalpur", "Vivek Krishna Tankha", "1", " ", "मध्य प्रदेश", "जबलपुर", "विवेक कृष्ण तन्खा", " "},
            {"Madhya Pradesh", "Jabalpur", "Amjad Khan", "4", " ", "मध्य प्रदेश", "जबलपुर", "अमजद खान", " "},
            {"Madhya Pradesh", "Jabalpur", "Rakesh Singh S/O Baljor Singh", "4", " ", "मध्य प्रदेश", "जबलपुर", "राकेश सिंह एस / ओ बलजोर सिंह", " "},
            {"Madhya Pradesh", "Jabalpur", "Mahu Singh", "4", " ", "मध्य प्रदेश", "जबलपुर", "महू सिंह", " "},
            {"Madhya Pradesh", "Jabalpur", "Devendra Kumar Yadav", "4", " ", "मध्य प्रदेश", "जबलपुर", "देवेंद्र कुमार यादव", " "},
            {"Madhya Pradesh", "Jabalpur", "Ramraj Ram", "3", " ", "मध्य प्रदेश", "जबलपुर", "रामराज राम", " "},
            {"Madhya Pradesh", "Jabalpur", "Bhushan Prasad Shukla", "4", " ", "मध्य प्रदेश", "जबलपुर", "भूषण प्रसाद शुक्ल", " "},
            {"Madhya Pradesh", "Khajuraho", "Vishnu Datt Sharma", "1", " ", "मध्य प्रदेश", "खजुराहो", "विष्णु दत्त शर्मा", " "},
            {"Madhya Pradesh", "Khajuraho", "Jagdesh Kumar Patel", "4", " ", "मध्य प्रदेश", "खजुराहो", "जगदीश कुमार पटेल", " "},
            {"Madhya Pradesh", "Khajuraho", "Parwat Singh", "4", " ", "मध्य प्रदेश", "खजुराहो", "परवत सिंह", " "},
            {"Madhya Pradesh", "Khajuraho", "Vinod Kumar", "4", " ", "मध्य प्रदेश", "खजुराहो", "विनोद कुमार", " "},
            {"Madhya Pradesh", "Khajuraho", "Meena Raikwar", "4", " ", "मध्य प्रदेश", "खजुराहो", "मीना रायकवार", " "},
            {"Madhya Pradesh", "Khajuraho", "Maharani Kavita Singh Natiraja", "1", " ", "मध्य प्रदेश", "खजुराहो", "महारानी कविता सिंह नतिराज", " "},
            {"Madhya Pradesh", "Khajuraho", "Manish Mishra", "4", " ", "मध्य प्रदेश", "खजुराहो", "मनीष मिश्रा", " "},
            {"Madhya Pradesh", "Khajuraho", "Veer Singh Patel", "2", " ", "मध्य प्रदेश", "खजुराहो", "वीर सिंह पटेल", " "},
            {"Madhya Pradesh", "Mandla", "Manita Markam", "4", " ", "मध्य प्रदेश", "मंडला", "मनिता मरकाम", " "},
            {"Madhya Pradesh", "Mandla", "Chandra Singh Kushram", "4", " ", "मध्य प्रदेश", "मंडला", "चन्द्र सिंह कुशराम", " "},
            {"Madhya Pradesh", "Mandla", "Kamal Singh Maravi", "1", " ", "मध्य प्रदेश", "मंडला", "कमल सिंह मरावी", " "},
            {"Madhya Pradesh", "Mandla", "R. S. Paraste (Ramsingh)", "3", " ", "मध्य प्रदेश", "मंडला", "आरएस परस्ते (रामसिंह)", " "},
            {"Madhya Pradesh", "Mandla", "Dada Ramgulam Uikey", "4", " ", "मध्य प्रदेश", "मंडला", "दादा रामगुलाम उइके", " "},
            {"Madhya Pradesh", "Mandla", "Faggan Singh Kulaste", "1", " ", "मध्य प्रदेश", "मंडला", "फग्गन सिंह कुलस्ते", " "},
            {"Madhya Pradesh", "Morena", "Sonu Agrwal", "4", " ", "मध्य प्रदेश", "मोरैना", "सोनू अग्रवाल", " "},
            {"Madhya Pradesh", "Morena", "Sumit Mishra", "4", " ", "मध्य प्रदेश", "मोरैना", "सुमित मिश्रा", " "},
            {"Madhya Pradesh", "Morena", "Patiram Shakya", "4", " ", "मध्य प्रदेश", "मोरैना", "पतिराम शाक्य", " "},
            {"Madhya Pradesh", "Morena", "Rajesh Singh Bhadoria", "4", " ", "मध्य प्रदेश", "मोरैना", "राजेश सिंह भदोरिया", " "},
            {"Madhya Pradesh", "Morena", "Mehabub Khan", "4", " ", "मध्य प्रदेश", "मोरैना", "महबूब खान", " "},
            {"Madhya Pradesh", "Morena", "Dhara Singh", "4", " ", "मध्य प्रदेश", "मोरैना", "धरा सिंह", " "},
            {"Madhya Pradesh", "Morena", "Narendra Singh Tomar", "1", " ", "मध्य प्रदेश", "मोरैना", "नरेंद्र सिंह तोमर", " "},
            {"Madhya Pradesh", "Morena", "Prabhu Singh", "4", " ", "मध्य प्रदेश", "मोरैना", "प्रभु सिंह", " "},
            {"Madhya Pradesh", "Morena", "Ramniwas Rawat", "1", " ", "मध्य प्रदेश", "मोरैना", "रामनिवास रावत", " "},
            {"Madhya Pradesh", "Morena", "Sanju Sharma", "4", " ", "मध्य प्रदेश", "मोरैना", "संजू शर्मा", " "},
            {"Madhya Pradesh", "Morena", "Dheeraj Singh Mavai", "4", " ", "मध्य प्रदेश", "मोरैना", "धीरज सिंह मावई", " "},
            {"Madhya Pradesh", "Morena", "Bajuddeen Baj", "2", " ", "मध्य प्रदेश", "मोरैना", "बाजुद्दीन बाज", " "},
            {"Madhya Pradesh", "Morena", "Tejpal Singh Rawat", "4", " ", "मध्य प्रदेश", "मोरैना", "तेजपाल सिंह रावत", " "},
            {"Madhya Pradesh", "Morena", "Bhante Sangh Ratan", "4", " ", "मध्य प्रदेश", "मोरैना", "भंते संघ रतन", " "},
            {"Madhya Pradesh", "Morena", "Kartar Singh Bhadana", "2", " ", "मध्य प्रदेश", "मोरैना", "करतार सिंह भड़ाना", " "},
            {"Madhya Pradesh", "Morena", "Munna", "2", " ", "मध्य प्रदेश", "मोरैना", "मुन्ना", " "},
            {"Madhya Pradesh", "Morena", "Pawan Kumar Goyal", "2", " ", "मध्य प्रदेश", "मोरैना", "पवन कुमार गोयल", " "},
            {"Madhya Pradesh", "Rajgarh", "Mohsin", "4", " ", "मध्य प्रदेश", "राजगढ़", "मोहसिन", " "},
            {"Madhya Pradesh", "Rajgarh", "Susheel Kumar Prasad", "2", " ", "मध्य प्रदेश", "राजगढ़", "सुशील कुमार प्रसाद", " "},
            {"Madhya Pradesh", "Rajgarh", "Santosh Rao", "4", " ", "मध्य प्रदेश", "राजगढ़", "संतोष राव", " "},
            {"Madhya Pradesh", "Rajgarh", "Mukesh Kumar Dangi", "4", " ", "मध्य प्रदेश", "राजगढ़", "मुकेश कुमार दांगी", " "},
            {"Madhya Pradesh", "Rajgarh", "Jagdeesh Singh Parmar", "4", " ", "मध्य प्रदेश", "राजगढ़", "जगदीश सिंह परमार", " "},
            {"Madhya Pradesh", "Rajgarh", "Mona Sustani", "1", " ", "मध्य प्रदेश", "राजगढ़", "मोना सुस्तानी", " "},
            {"Madhya Pradesh", "Rajgarh", "Rodmal Nagar", "1", " ", "मध्य प्रदेश", "राजगढ़", "रोडमल नगर", " "},
            {"Madhya Pradesh", "Rewa", "Siyasharan Kevat", "4", " ", "मध्य प्रदेश", "रीवा", "सियाशरण केवट", " "},
            {"Madhya Pradesh", "Rewa", "Reeta Tripathi", "4", " ", "मध्य प्रदेश", "रीवा", "रीता त्रिपाठी", " "},
            {"Madhya Pradesh", "Rewa", "Brahm Datta Mishra", "2", " ", "मध्य प्रदेश", "रीवा", "ब्रह्मदत्त मिश्र", " "},
            {"Madhya Pradesh", "Rewa", "Chhotu Kol", "4", " ", "मध्य प्रदेश", "रीवा", "छोटू कोल", " "},
            {"Madhya Pradesh", "Rewa", "Babulal Kol", "4", " ", "मध्य प्रदेश", "रीवा", "बाबूलाल कोल", " "},
            {"Madhya Pradesh", "Rewa", "Ram Gopal Singh", "2", " ", "मध्य प्रदेश", "रीवा", "राम गोपाल सिंह", " "},
            {"Madhya Pradesh", "Rewa", "Sunit Kumar Pandey", "2", " ", "मध्य प्रदेश", "रीवा", "सुनीत कुमार पांडे", " "},
            {"Madhya Pradesh", "Rewa", "Devendra Kumar", "4", " ", "मध्य प्रदेश", "रीवा", "देवेंद्र कुमार", " "},
            {"Madhya Pradesh", "Rewa", "Arun Kumar", "2", " ", "मध्य प्रदेश", "रीवा", "अरुण कुमार", " "},
            {"Madhya Pradesh", "Rewa", "Janardan Prasad Mishra", "1", " ", "मध्य प्रदेश", "रीवा", "जनार्दन प्रसाद मिश्र", " "},
            {"Madhya Pradesh", "Rewa", "Sanat Kumar", "4", " ", "मध्य प्रदेश", "रीवा", "सनत कुमार", " "},
            {"Madhya Pradesh", "Rewa", "Shivkumar Mishra", "4", " ", "मध्य प्रदेश", "रीवा", "शिवकुमार मिश्रा", " "},
            {"Madhya Pradesh", "Rewa", "Badriprasad", "4", " ", "मध्य प्रदेश", "रीवा", "Badriprasad", " "},
            {"Madhya Pradesh", "Rewa", "Siddharth Tiwari", "1", " ", "मध्य प्रदेश", "रीवा", "सिद्धार्थ तिवारी", " "},
            {"Madhya Pradesh", "Sagar", "Rajkumar Yadav", "4", " ", "मध्य प्रदेश", "सागर", "राजकुमार यादव", " "},
            {"Madhya Pradesh", "Sagar", "Devendra Jain", "3", " ", "मध्य प्रदेश", "सागर", "देवेंद्र जैन", " "},
            {"Madhya Pradesh", "Sagar", "Moh. Khurram Qureshi", "4", " ", "मध्य प्रदेश", "सागर", "मोह। खुर्रम कुरैशी", " "},
            {"Madhya Pradesh", "Sagar", "Ramnaresh Tiwari", "4", " ", "मध्य प्रदेश", "सागर", "रामनरेश तिवारी", " "},
            {"Madhya Pradesh", "Sagar", "Kamal Kumar Khatik", "4", " ", "मध्य प्रदेश", "सागर", "कमल कुमार खटीक", " "},
            {"Madhya Pradesh", "Sagar", "Kanchedilal Kushwaha", "4", " ", "मध्य प्रदेश", "सागर", "कांचीलाल कुशवाहा", " "},
            {"Madhya Pradesh", "Sagar", "Prabhu Singh Thakur", "1", " ", "मध्य प्रदेश", "सागर", "प्रभु सिंह ठाकुर", " "},
            {"Madhya Pradesh", "Sagar", "Mahendra Singh Patel", "4", " ", "मध्य प्रदेश", "सागर", "महेंद्र सिंह पटेल &quot;बरूअल&quot;", " "},
            {"Madhya Pradesh", "Sagar", "Vinay Kumar Sen", "4", " ", "मध्य प्रदेश", "सागर", "विनय कुमार सेन", " "},
            {"Madhya Pradesh", "Sagar", "Rajbahadur Singh", "1", " ", "मध्य प्रदेश", "सागर", "राजबहादुर सिंह", " "},
            {"Madhya Pradesh", "Satna", "Nand Kishore", "4", " ", "मध्य प्रदेश", "सतना", "नंद किशोर", " "},
            {"Madhya Pradesh", "Satna", "Mahesh Sahu", "4", " ", "मध्य प्रदेश", "सतना", "महेश साहू &quot;पप्पू&quot;", " "},
            {"Madhya Pradesh", "Satna", "Munni Kranti", "4", " ", "मध्य प्रदेश", "सतना", "मुन्नी क्रांति", " "},
            {"Madhya Pradesh", "Satna", "Ram Nivas Sen", "4", " ", "मध्य प्रदेश", "सतना", "राम निवास सेन", " "},
            {"Madhya Pradesh", "Satna", "Babu Lal", "4", " ", "मध्य प्रदेश", "सतना", "बाबू लाल", " "},
            {"Madhya Pradesh", "Satna", "Ganesh Singh", "1", " ", "मध्य प्रदेश", "सतना", "गणेश सिंह", " "},
            {"Madhya Pradesh", "Satna", "Acche Lal Kushawaha", "2", " ", "मध्य प्रदेश", "सतना", "असे लाल कुशवाहा", " "},
            {"Madhya Pradesh", "Satna", "Ramkushal Kewat", "4", " ", "मध्य प्रदेश", "सतना", "रामकुशल केवट", " "},
            {"Madhya Pradesh", "Satna", "Mahendra Singh", "3", " ", "मध्य प्रदेश", "सतना", "महेंद्र सिंह", " "},
            {"Madhya Pradesh", "Satna", "Surendra Prasad Pandey", "3", " ", "मध्य प्रदेश", "सतना", "सुरेंद्र प्रसाद पांडे", " "},
            {"Madhya Pradesh", "Satna", "Rajaram Tripathi", "1", " ", "मध्य प्रदेश", "सतना", "राजाराम त्रिपाठी", " "},
            {"Madhya Pradesh", "Satna", "Ashok Vishwakarma", "4", " ", "मध्य प्रदेश", "सतना", "अशोक विश्वकर्मा", " "},
            {"Madhya Pradesh", "Satna", "Mo. Jibrail", "4", " ", "मध्य प्रदेश", "सतना", "मो। जिबरईल", " "},
            {"Madhya Pradesh", "Satna", "Vipin Singh Tiwari", "4", " ", "मध्य प्रदेश", "सतना", "विपिन सिंह तिवारी", " "},
            {"Madhya Pradesh", "Satna", "Ram Vishwash Pal", "4", " ", "मध्य प्रदेश", "सतना", "रामविश्व पाल", " "},
            {"Madhya Pradesh", "Satna", "Manoraj Dwivedi", "4", " ", "मध्य प्रदेश", "सतना", "मनोरज द्विवेदी", " "},
            {"Madhya Pradesh", "Satna", "Sandeep Kumar Tiwari", "4", " ", "मध्य प्रदेश", "सतना", "संदीप कुमार तिवारी", " "},
            {"Madhya Pradesh", "Satna", "Nasir Khan", "3", " ", "मध्य प्रदेश", "सतना", "नासिर खान", " "},
            {"Madhya Pradesh", "Shahdol", "Vimal Singh Korche", "4", " ", "मध्य प्रदेश", "शाहडोल", "विमल सिंह कोरचे", " "},
            {"Madhya Pradesh", "Shahdol", "Pramila Singh", "1", " ", "मध्य प्रदेश", "शाहडोल", "प्रमिला सिंह", " "},
            {"Madhya Pradesh", "Shahdol", "Durga Mosi", "4", " ", "मध्य प्रदेश", "शाहडोल", "दुर्गा मोशी", " "},
            {"Madhya Pradesh", "Shahdol", "Lakshyapat Singh", "4", " ", "मध्य प्रदेश", "शाहडोल", "लक्ष्मीपत सिंह", " "},
            {"Madhya Pradesh", "Shahdol", "Kamla Prasad Baiga", "4", " ", "मध्य प्रदेश", "शाहडोल", "कमला प्रसाद बैगा", " "},
            {"Madhya Pradesh", "Shahdol", "Keshkali", "4", " ", "मध्य प्रदेश", "शाहडोल", "Keshkali", " "},
            {"Madhya Pradesh", "Shahdol", "Narayan Singh Uike", "4", " ", "मध्य प्रदेश", "शाहडोल", "नारायण सिंह उइके", " "},
            {"Madhya Pradesh", "Shahdol", "Meera Singh", "4", " ", "मध्य प्रदेश", "शाहडोल", "मीरा सिंह", " "},
            {"Madhya Pradesh", "Shahdol", "Manna Singh", "4", " ", "मध्य प्रदेश", "शाहडोल", "मन्ना सिंह", " "},
            {"Madhya Pradesh", "Shahdol", "Himadri Singh", "1", " ", "मध्य प्रदेश", "शाहडोल", "हिमाद्री सिंह", " "},
            {"Madhya Pradesh", "Shahdol", "Jhamaklal", "3", " ", "मध्य प्रदेश", "शाहडोल", "Jhamaklal", " "},
            {"Madhya Pradesh", "Shahdol", "Mohadal", "3", " ", "मध्य प्रदेश", "शाहडोल", "Mohadal", " "},
            {"Madhya Pradesh", "Shahdol", "Gokul Singh", "4", " ", "मध्य प्रदेश", "शाहडोल", "गोकुल सिंह", " "},
            {"Madhya Pradesh", "Sidhi", "Sanjay Kumar Namdeo", "2", " ", "मध्य प्रदेश", "सीधी", "संजय कुमार नामदेव", " "},
            {"Madhya Pradesh", "Sidhi", "Ram Kripal Basor", "4", " ", "मध्य प्रदेश", "सीधी", "राम कृपाल बसोर", " "},
            {"Madhya Pradesh", "Sidhi", "Ramsahay", "4", " ", "मध्य प्रदेश", "सीधी", "Ramsahay", " "},
            {"Madhya Pradesh", "Sidhi", "Ramawatar Vishwakarma", "2", " ", "मध्य प्रदेश", "सीधी", "रामावतार विश्वकर्मा", " "},
            {"Madhya Pradesh", "Sidhi", "Ram Rahees Kol", "4", " ", "मध्य प्रदेश", "सीधी", "राम रहीस कोल", " "},
            {"Madhya Pradesh", "Sidhi", "Ajay Arjun Singh", "1", " ", "मध्य प्रदेश", "सीधी", "अजय अर्जुन सिंह", " "},
            {"Madhya Pradesh", "Sidhi", "Ashish Kumar Singh Chauhan", "4", " ", "मध्य प्रदेश", "सीधी", "आशीष कुमार सिंह चौहान", " "},
            {"Madhya Pradesh", "Sidhi", "Ramadhar", "4", " ", "मध्य प्रदेश", "सीधी", "रामाधार", " "},
            {"Madhya Pradesh", "Sidhi", "Shyam Lal", "4", " ", "मध्य प्रदेश", "सीधी", "श्याम लाल", " "},
            {"Madhya Pradesh", "Sidhi", "Lalan", "4", " ", "मध्य प्रदेश", "सीधी", "ललन", " "},
            {"Madhya Pradesh", "Sidhi", "Ram Das", "3", " ", "मध्य प्रदेश", "सीधी", "राम दास", " "},
            {"Madhya Pradesh", "Sidhi", "Ram Lal Panika", "4", " ", "मध्य प्रदेश", "सीधी", "राम लाल पनिका", " "},
            {"Madhya Pradesh", "Sidhi", "Gyani Jaiswal", "4", " ", "मध्य प्रदेश", "सीधी", "ज्ञानी जायसवाल", " "},
            {"Madhya Pradesh", "Sidhi", "Nirmala Prajapati", "4", " ", "मध्य प्रदेश", "सीधी", "निर्मला प्रजापति", " "},
            {"Madhya Pradesh", "Sidhi", "Ramkumar Jaysval", "3", " ", "मध्य प्रदेश", "सीधी", "रामकुमार जैसवाल", " "},
            {"Madhya Pradesh", "Tikamgarh", "Virendra Kumar", "1", " ", "मध्य प्रदेश", "टीकमगढ़", "वीरेन्द्र कुमार", " "},
            {"Madhya Pradesh", "Tikamgarh", "Ahirwar Shripat Shikshak", "4", " ", "मध्य प्रदेश", "टीकमगढ़", "अहिरवार श्रीपत शिक्षा", " "},
            {"Madhya Pradesh", "Tikamgarh", "Suresh Kumar Kori", "4", " ", "मध्य प्रदेश", "टीकमगढ़", "सुरेश कुमार कोरी", " "},
            {"Madhya Pradesh", "Tikamgarh", "Jitendra Banshkar", "4", " ", "मध्य प्रदेश", "टीकमगढ़", "जितेंद्र बंशकार", " "},
            {"Madhya Pradesh", "Tikamgarh", "Surjeet Chadar", "4", " ", "मध्य प्रदेश", "टीकमगढ़", "सुरजीत चदर", " "},
            {"Madhya Pradesh", "Tikamgarh", "Kiran Singh Ahirwar", "1", " ", "मध्य प्रदेश", "टीकमगढ़", "किरण सिंह अहिरवार", " "},
            {"Madhya Pradesh", "Tikamgarh", "Pramod Prajapati", "4", " ", "मध्य प्रदेश", "टीकमगढ़", "प्रमोद प्रजापति", " "},
            {"Madhya Pradesh", "Tikamgarh", "Shobha Valmiki", "3", " ", "मध्य प्रदेश", "टीकमगढ़", "शोभा वाल्मीकि", " "},
            {"Madhya Pradesh", "Tikamgarh", "Narayan Das Jatav", "4", " ", "मध्य प्रदेश", "टीकमगढ़", "नारायण दास जाटव", " "},
            {"Madhya Pradesh", "Vidisha", "Ramakant Bhargava", "1", " ", "मध्य प्रदेश", "विदिशा", "रमाकांत भार्गव", " "},
            {"Madhya Pradesh", "Vidisha", "Naveen Jatav", "4", " ", "मध्य प्रदेश", "विदिशा", "नवीन जाटव", " "},
            {"Madhya Pradesh", "Vidisha", "Shailendra Kumar", "4", " ", "मध्य प्रदेश", "विदिशा", "शैलेंद्र कुमार", " "},
            {"Madhya Pradesh", "Vidisha", "Shailendra Rameshchandra Patel", "1", " ", "मध्य प्रदेश", "विदिशा", "शैलेंद्र रमेशचंद्र पटेल", " "},
            {"Madhya Pradesh", "Vidisha", "Ramkrishna Surywanshi", "4", " ", "मध्य प्रदेश", "विदिशा", "रामकृष्ण सूर्यवंशी", " "},
            {"Madhya Pradesh", "Vidisha", "Mahant Pratap Giri", "4", " ", "मध्य प्रदेश", "विदिशा", "महंत प्रताप गिरि", " "},
            {"Madhya Pradesh", "Vidisha", "Madan Lal Bhadoriya", "4", " ", "मध्य प्रदेश", "विदिशा", "मदन लाल भदौरिया", " "},
            {"Madhya Pradesh", "Vidisha", "Mo. Talat Khan", "4", " ", "मध्य प्रदेश", "विदिशा", "मो। तलत खान", " "},
    };

}