/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Maharashtra {
public static final String[][] green_bucket = {
{"Maharashtra",  "4270", "Ahmednagar", "Sudhakar Laxman Avhad", "Vanchit Bahujan Aaghadi", "http://myneta.info/ls2014/candidate.php?candidate_id=8677",  "",  "", "", "", ""}, 
{"Maharashtra",  "4271", "Ahmednagar", "Appasaheb Navnath Palve", "IND", "http://myneta.info/ls2014/candidate.php?candidate_id=10882",  "",  "", "", "", ""}, 
{"Maharashtra",  "4052", "Akola", "Pravin Chandrakant Kaurpuriya", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5002",  "",  "", "", "", ""}, 
{"Maharashtra",  "4053", "Akola", "Ambedkar Prakash Yashwant", "Vanchit Bahujan Aaghadi", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6360",  "",  "", "", "", ""}, 
{"Maharashtra",  "4055", "Akola", "Murlidhar Lalsingh Pawar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5001",  "",  "", "", "", ""}, 
{"Maharashtra",  "4060", "Akola", "Sau. Pravina Laxman Bhatkar", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5828",  "",  "", "", "", ""}, 
{"Maharashtra",  "4068", "Amravati", "Pankaj Liladhar Meshram", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6404",  "",  "", "", "", ""}, 
{"Maharashtra",  "4069", "Amravati", "Sonone Raju Mahadeo", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5453",  "",  "", "", "", ""}, 
{"Maharashtra",  "4070", "Amravati", "Raju Bakshi Jamnekar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6399",  "",  "", "", "", ""}, 
{"Maharashtra",  "4079", "Amravati", "Panchshila Vijay Mohod", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6403",  "",  "", "", "", ""}, 
{"Maharashtra",  "4080", "Amravati", "Nilima Nitin Bhatkar", "Peoples Party of India (Democratic)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6379",  "",  "", "", "", ""}, 
{"Maharashtra",  "4081", "Amravati", "Shrikant Ulhas Raibole", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6383",  "",  "", "", "", ""}, 
{"Maharashtra",  "4085", "Amravati", "Pramod Laxman Meshram", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6425",  "",  "", "", "", ""},
        {"Maharashtra", "4266", "Baramati", "Mangesh Nilkanth Vanshiv", "BSP", "http://myneta.info/ls2014/candidate.php?candidate_id=8516", "", "", "", "", ""},
        {"Maharashtra", "4274", "Beed", "Veer Shesherao Chokhoba", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6537", "", "", "", "", ""},
{"Maharashtra",  "4285", "Beed", "Shaikh Yashed Shaikh Tayyab", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8626",  "",  "", "", "", ""}, 
{"Maharashtra",  "4288", "Beed", "Ganesh Navnathrao Karande", "Maharashtra Kranti Sena", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8611",  "",  "", "", "", ""}, 
{"Maharashtra",  "4296", "Beed", "Pathan Musakhan Yunuskhan", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8621",  "",  "", "", "", ""}, 
{"Maharashtra",  "4298", "Beed", "Adv. Sharad Bahinaji Kamble", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6520",  "",  "", "", "", ""}, 
{"Maharashtra",  "4303", "Beed", "Vijay Rangnath Salve", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6536",  "",  "", "", "", ""}, 
{"Maharashtra",  "4146", "Bhandara-Gondiya", "Suhas Anil Funde", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4596",  "",  "", "", "", ""}, 
{"Maharashtra",  "4149", "Bhandara-Gondiya", "Devidas Santuji Lanjewar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4898",  "",  "", "", "", ""}, 
{"Maharashtra",  "4150", "Bhandara-Gondiya", "Dr. Vijaya Rajesh Nandurkar", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5412",  "",  "", "", "", ""}, 
{"Maharashtra",  "4151", "Bhandara-Gondiya", "Dr. Sunil Sampat Chawale", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6981",  "",  "", "", "", ""}, 
{"Maharashtra",  "4155", "Bhandara-Gondiya", "Sumit Vijay Pande", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6041",  "",  "", "", "", ""}, 
{"Maharashtra",  "4158", "Bhandara-Gondiya", "Jaiswal Virendrakumar Kasturchand", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5180",  "",  "", "", "", ""}, 
{"Maharashtra",  "4047", "Buldhana", "Vijay Banwarilal Masani", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5174",  "",  "", "", "", ""}, 
{"Maharashtra",  "4169", "Chandrapur", "Gautam Ganpat Nagrale", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5809",  "",  "", "", "", ""}, 
{"Maharashtra",  "4174", "Chandrapur", "Dashrath Pandurang Madavi", "Bahujan Republican Socialist Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4712",  "",  "", "", "", ""}, 
{"Maharashtra",  "4177", "Chandrapur", "Rajendra Krishnarao Hajare", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5811",  "",  "", "", "", ""}, 
{"Maharashtra",  "4163", "Gadchiroli-Chimur", "Deorao Monba Nannaware", "Ambedkarite Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4929",  "",  "", "", "", ""}, 
{"Maharashtra",  "4202", "Hingoli", "Altaf Ahmed", "IUML", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6547",  "",  "", "", "", ""}, 
{"Maharashtra",  "4204", "Hingoli", "Wasant Kisan Paikrao", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7637",  "",  "", "", "", ""}, 
{"Maharashtra",  "4207", "Hingoli", "Sandip Nikhate", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6565",  "",  "", "", "", ""}, 
{"Maharashtra",  "4212", "Hingoli", "Uttam Bhagaji Kamble", "Prabuddha Republican Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6558",  "",  "", "", "", ""}, 
{"Maharashtra",  "4215", "Hingoli", "Marotrao Kanhobarao Hukke Patil", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6566",  "",  "", "", "", ""}, 
{"Maharashtra",  "4222", "Hingoli", "Sandesh Ramchandra Chavan", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7642",  "",  "", "", "", ""}, 
{"Maharashtra",  "4224", "Hingoli", "Mohan Fattusing Rathod", "Vanchit Bahujan Aaghadi", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6550",  "",  "", "", "", ""}, 
{"Maharashtra",  "4225", "Hingoli", "Patil Hemant Shriram", "SHS", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6559",  "",  "", "", "", ""},
        {"Maharashtra", "4037", "Jalgaon", "Anjali Ratnakar Baviskar", "Vanchit Bahujan Aaghadi", "http://myneta.info/ls2014/candidate.php?candidate_id=8718", "", "", "", "", ""},
        {"Maharashtra", "4348", "Kolhapur", "Sandeep Bhairavnath Kogale", "IND", "http://myneta.info/ls2014/candidate.php?candidate_id=8732", "", "", "", "", ""},
        {"Maharashtra", "4349", "Kolhapur", "Sanjay Sadashivrao Mandlik", "SHS", "http://myneta.info/ls2014/candidate.php?candidate_id=7767", "", "", "", "", ""},
        {"Maharashtra", "4325", "Latur", "Ramrao Garkar", "Vanchit Bahujan Aaghadi", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6568", "", "", "", "", ""},
{"Maharashtra",  "4330", "Latur", "Siddharthkumar Digambarrao Suryawanshi", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5478",  "",  "", "", "", ""},
        {"Maharashtra", "4346", "Madha", "Ramchandra Mayyappa Ghutukade", "Bahujan Republican Socialist Party", "http://myneta.info/ls2014/candidate.php?candidate_id=8744", "", "", "", "", ""},
        {"Maharashtra", "4118", "Nagpur", "Adv. Ulhas Shalikaram Dupare", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4595", "", "", "", "", ""},
{"Maharashtra",  "4123", "Nagpur", "Dikshita Anand Tembhurne", "Desh Janhit Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6988",  "",  "", "", "", ""}, 
{"Maharashtra",  "4124", "Nagpur", "Mane Suresh Tatoba", "Bahujan Republican Socialist Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4893",  "",  "", "", "", ""}, 
{"Maharashtra",  "4129", "Nagpur", "Siddharth Asaram Kurve", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5807",  "",  "", "", "", ""}, 
{"Maharashtra",  "4130", "Nagpur", "Satish Vitthal Nikhar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6997",  "",  "", "", "", ""}, 
{"Maharashtra",  "4131", "Nagpur", "Manohar Alias Sagar Pundlikrao Dabrase", "Vanchit Bahujan Aaghadi", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5806",  "",  "", "", "", ""}, 
{"Maharashtra",  "4136", "Nagpur", "Adv. Vijaya Dilip Bagde", "Ambedkarite Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4890",  "",  "", "", "", ""}, 
{"Maharashtra",  "4137", "Nagpur", "Dr. Manisha Bangar", "Peoples Party of India (Democratic)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6991",  "",  "", "", "", ""}, 
{"Maharashtra",  "4139", "Nagpur", "Dr. Vinod Kashiram Badole", "Akhil Bhartiya Sarvadharma Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6982",  "",  "", "", "", ""}, 
{"Maharashtra",  "4141", "Nagpur", "Shridhar Narayan Salve", "Rashtriya Jansambhavna Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6992",  "",  "", "", "", ""}, 
{"Maharashtra",  "4144", "Nagpur", "Ali Ashfaque Ahmed", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6983",  "",  "", "", "", ""}, 
{"Maharashtra",  "4230", "Nanded", "Mahesh Prakashrao Talegaonkar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7647",  "",  "", "", "", ""}, 
{"Maharashtra",  "4232", "Nanded", "Shivanand Ashokrao Deshmukh", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7650",  "",  "", "", "", ""}, 
{"Maharashtra",  "4238", "Nanded", "Ranjit Gangadharrao Deshmukh", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7649",  "",  "", "", "", ""}, 
{"Maharashtra",  "4242", "Nanded", "Bhinge Yashpal Narsinghrao", "Vanchit Bahujan Aaghadi", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6578",  "",  "", "", "", ""}, 
{"Maharashtra",  "4311", "Osmanabad", "Dr. Shivaji Pandharinath Oman", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8630",  "",  "", "", "", ""}, 
{"Maharashtra",  "4313", "Osmanabad", "Aryanraje Kisanrao Shinde", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4978",  "",  "", "", "", ""}, 
{"Maharashtra",  "4316", "Osmanabad", "Jagannath Nivrutti Munde", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8634",  "",  "", "", "", ""}, 
{"Maharashtra",  "4322", "Osmanabad", "Shankar Pandurang Gaikwad", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6584",  "",  "", "", "", ""}, 
{"Maharashtra",  "4245", "Parbhani", "Bobade Sakharam Gyanba", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6587",  "",  "", "", "", ""}, 
{"Maharashtra",  "4246", "Parbhani", "Dr.Appasaheb Onkar Kadam", "Swatantra Bharat Paksha", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6592",  "",  "", "", "", ""}, 
{"Maharashtra",  "4247", "Parbhani", "Yashwant Rambhau Kasbe", "Bahujan Republican Socialist Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6590",  "",  "", "", "", ""}, 
{"Maharashtra",  "4250", "Parbhani", "Harishchandra Dattu Patil", "Sangharsh Sena", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6585",  "",  "", "", "", ""}, 
{"Maharashtra",  "4255", "Parbhani", "Santosh Govind Rathod", "Bhartiya Bahujan Kranti Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6588",  "",  "", "", "", ""}, 
{"Maharashtra",  "4256", "Parbhani", "Rajesh Uttamrao Vitekar", "NCP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6591",  "",  "", "", "", ""}, 
{"Maharashtra",  "4100", "Ramtek", "Krupal Balaji Tumane", "SHS", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5725",  "",  "", "", "", ""}, 
{"Maharashtra",  "4110", "Ramtek", "Laxman Jyotik Kanhekar", "Peoples Party of India (Democratic)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5727",  "",  "", "", "", ""}, 
{"Maharashtra",  "4111", "Ramtek", "Sonali Ravindra Bagde", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5732",  "",  "", "", "", ""}, 
{"Maharashtra",  "4333", "Solapur", "Ad. Karande Manisha Manohar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6606",  "",  "", "", "", ""}, 
{"Maharashtra",  "4334", "Solapur", "Shri Ambedkar Prakash Yashwant", "Vanchit Bahujan Aaghadi", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5198",  "",  "", "", "", ""}, 
{"Maharashtra",  "4336", "Solapur", "Prof. Dr. Ohal Arjun Gena", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6603",  "",  "", "", "", ""}, 
{"Maharashtra",  "4338", "Solapur", "Shrivenkateswar Maha Swamiji (Katakdhond. D. G.)", "Hindustan Janta Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4973",  "",  "", "", "", ""}, 
{"Maharashtra",  "4340", "Solapur", "Shri Gaydhankar Vishnu Shidram", "Bharatiya Praja Surajya Paksha", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6593",  "",  "", "", "", ""}, 
{"Maharashtra",  "4344", "Solapur", "Ad. Vikram Uttam Kasabe", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5495",  "",  "", "", "", ""}, 
{"Maharashtra",  "4098", "Wardha", "Zitruji Chandruji Borutkar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5739",  "",  "", "", "", ""}, 
{"Maharashtra",  "4099", "Wardha", "Adv. Bhaskar Marotrao Neware", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4711",  "",  "", "", "", ""}, 
{"Maharashtra",  "4087", "Wardha", "Rajesh Marotrao Balpande", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4883",  "",  "", "", "", ""}, 
{"Maharashtra",  "4178", "Yavatmal-Washim", "Uttam Bhagaji Kamble", "Prabuddha Republican Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5754",  "",  "", "", "", ""}, 
{"Maharashtra",  "4181", "Yavatmal-Washim", "Simpal Rajkumar Rathod", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5750",  "",  "", "", "", ""}, 
{"Maharashtra",  "4183", "Yavatmal-Washim", "Ankit Mohan Chandak", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4600",  "",  "", "", "", ""}, 
{"Maharashtra",  "4185", "Yavatmal-Washim", "Pravin Govind Pawar", "Vanchit Bahujan Aaghadi", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5755",  "",  "", "", "", ""}, 
{"Maharashtra",  "4187", "Yavatmal-Washim", "Parashram Bhaosing Ade", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6116",  "",  "", "", "", ""}, 
{"Maharashtra",  "4188", "Yavatmal-Washim", "Dr. Rajiv Agrawal", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5759",  "",  "", "", "", ""}, 
{"Maharashtra",  "4192", "Yavatmal-Washim", "Shahejad Samiullah Khan", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4924",  "",  "", "", "", ""}, 
{"Maharashtra",  "4193", "Yavatmal-Washim", "Anil Jayram Rathod", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4922",  "",  "", "", "", ""}, 
};

public static final String[][] red_bucket = {
{ "Maharashtra",  "4267",  "Ahmednagar", "Bhaskar Fakira Patole", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4268",  "Ahmednagar", "Kaliram Bahiru Popalghat", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4269",  "Ahmednagar", "Dattatraya Appa Waghmode", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4272",  "Ahmednagar", "Dhiraj Motilal Batade", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4051",  "Akola", "Kamble Bhanudas Chokhoba", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4054",  "Akola", "Arun Kankar Wankhede", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4056",  "Akola", "Sachin Ganpatlal Sharma", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4057",  "Akola", "Arun Manohar Thakare", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4058",  "Akola", "Hidayatulla Barakatulla Patel", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4059",  "Akola", "Gajanan Onkar Harne", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4061",  "Akola", "Sanjay Shamrao Dhotre", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4062",  "Amravati", "Navneet Ravi Rana", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4063",  "Amravati", "Gunavant Deopare", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4064",  "Amravati", "Ambadas Shamrao Wankhade", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4065",  "Amravati", "Anandrao Vithoba Adsul", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4066",  "Amravati", "Vilas Sheshrao Thorat", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4067",  "Amravati", "Dnyaneshwar Kashirao Mankar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4071",  "Amravati", "Nilesh Anandrao Patil", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4072",  "Amravati", "Narendra Babulal Kathane", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4073",  "Amravati", "Arun Motiramji Wankhade", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4074",  "Amravati", "Rahulbhau Laxmanrao Mohod", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4075",  "Amravati", "Raju Shamraoji Mankar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4076",  "Amravati", "Sanjay Hiramanji Athwale", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4077",  "Amravati", "Vijay Yashvant Vilhekar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4078",  "Amravati", "Pravin Mahadeo Sarode", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4082",  "Amravati", "Kurwade Meenakshi Someshwar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4083",  "Amravati", "Anil Namdevrao Jamnekar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4084",  "Amravati", "Gade Vinod Milind", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4265",  "Baramati", "Yuvraj Prakash Bhujbal", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4273",  "Beed", "Kalidas Pandharinath Aapet", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4275",  "Beed", "Bajrang Digambar Sonwane", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4276",  "Beed", "Shivaji Naraynrao Kawathekar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4277",  "Beed", "Sayed Mujammil Sayed Jamil", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4278",  "Beed", "Kolekar Ganesh Bhausaheb", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4279",  "Beed", "Vishnu Jadhav", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4280",  "Beed", "Sajan Raees Chaodhri", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4281",  "Beed", "Patil Yashashri Pramod", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4282",  "Beed", "Ramesh Ramkisan Gavhane", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4283",  "Beed", "Galebkhan Jabbarkhan Pathan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4284",  "Beed", "Shaikh Sadek Shaikh Ibrahim", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4286",  "Beed", "Khan Majhar Habib", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4287",  "Beed", "Jamir Bashir Shaikh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4289",  "Beed", "Mujeeb Naimoddin Inamdar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4290",  "Beed", "Bajarang Manohar Sonwane", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4291",  "Beed", "Ashok Bhagoji Thorat", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4292",  "Beed", "Shinde Chandraprakash Ganpatrao", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4293",  "Beed", "Pathan Sarfarzkhan Mahetabkhan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4294",  "Beed", "Chavan Sampat Ramsing", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4295",  "Beed", "Sadek Muniroddin Shaikh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4297",  "Beed", "Sayyad Minhaj", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4299",  "Beed", "Jagtap Nilesh Murlidhar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4300",  "Beed", "Kalyan Bhanudas Gurav", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4301",  "Beed", "Pritam Gopinathrao Munde", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4302",  "Beed", "Anwar Khan Mirza Khan", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4304",  "Beed", "Tukaram Vyankati Chate", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4305",  "Beed", "Nisar Ahemad", "NotGraduate",  " ","",  "", "", " "},
        {"Maharashtra", "4306", "Beed", "Juber Munshi Kureshi", "NotGraduate", " ", "", "", "", " "},
{ "Maharashtra",  "4307",  "Beed", "Pandit Damodhar Khande", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4308",  "Beed", "Rajeshkumar Annasaheb Bhadgale", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4147",  "Bhandara-Gondiya", "Nanhe Karu Nagoji", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4148",  "Bhandara-Gondiya", "Kalchuri Nilesh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4152",  "Bhandara-Gondiya", "Sunil Baburao Mendhe", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4153",  "Bhandara-Gondiya", "Nana Jairam", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4154",  "Bhandara-Gondiya", "Bhimrao Duryodhan Borkar", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4156",  "Bhandara-Gondiya", "Gajbhiye Pramod Hiraman", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4157",  "Bhandara-Gondiya", "Patle Rajendra Sahasram", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4159",  "Bhandara-Gondiya", "Maraskolhe Bhojraj Isulal", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4040",  "Buldhana", "A. Hafeez A. Aziz", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4041",  "Buldhana", "Baliram Bhagwan Siraskar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4042",  "Buldhana", "Wamanrao Ganpatrao Akhare", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4043",  "Buldhana", "Dinkar Tukaram Sambare", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4044",  "Buldhana", "Prataprao Ganpatrao Jadhav", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4045",  "Buldhana", "Dr. Rajendra Bhaskarrav Shingne", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4046",  "Buldhana", "Gajanan Uttam Shantabai", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4048",  "Buldhana", "Ananta Datta Puri", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4049",  "Buldhana", "Vikas Prakash Nandve", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4050",  "Buldhana", "Pratap Pandharinath Patil", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4165",  "Chandrapur", "Dhanorkar Suresh Narayan", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4166",  "Chandrapur", "Ahir Hansraj Gangaramji", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4167",  "Chandrapur", "Nitesh Anandrao Dongre", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4168",  "Chandrapur", "Namdeo Keshao Kinnake", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4170",  "Chandrapur", "Sushil Wasnik", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4171",  "Chandrapur", "Madhukar Vithal Nistane", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4172",  "Chandrapur", "Namdeo Shedmake", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4173",  "Chandrapur", "Milind Pralhad Dahiwale", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4175",  "Chandrapur", "Arvind Nanaji Raut", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4176",  "Chandrapur", "Rajendra Shriramji Mahadole", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4160",  "Gadchiroli-Chimur", "Rameshkumar Baburaoji Gajbe", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4161",  "Gadchiroli-Chimur", "Namdeo Dalluji Usendi", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4162",  "Gadchiroli-Chimur", "Harichandra Nagoji Mangam", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4164",  "Gadchiroli-Chimur", "Ashok Mahadevrao Nete", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4350",  "Hatkanangle", "Aslam Badshahaji Sayyad", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4351",  "Hatkanangle", "Dr.Prashant Dnyaneshwar Gangavane", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4201",  "Hingoli", "Jaywanta Vishwambhar Wanole", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4203",  "Hingoli", "Maqbul Ahmed A.Habib", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4205",  "Hingoli", "Devji Gangaram Asole", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4206",  "Hingoli", "Santosh Maroti Boinwad", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4208",  "Hingoli", "Gajanan Haribhau Bhalerao", "CriminalCases",  " ","",  "", "", " "},
        {"Maharashtra", "4209", "Hingoli", "Subhash Maroti Wankhede", "NotGraduate", " ", "", "", "", " "},
{ "Maharashtra",  "4210",  "Hingoli", "Subhash Nagorao Wankhede", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4211",  "Hingoli", "Wankhede Subhashrao Bapurao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4213",  "Hingoli", "Kamble Trishala Milind", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4214",  "Hingoli", "Patrakar P Sattar Khan Kasim Kha", "NotGraduate",  " ","",  "", "", " "},
        {"Maharashtra", "4216", "Hingoli", "Subhash Kashiba Wankhede", "NotGraduate", " ", "", "", "", " "},
{ "Maharashtra",  "4217",  "Hingoli", "Subhash Vitthal Wankhede", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4218",  "Hingoli", "Sunil Dashrath Ingole", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4219",  "Hingoli", "Dr. Dhanve Datta Maroti", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4220",  "Hingoli", "Prakash Vitthalrao Ghunnar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4221",  "Hingoli", "Varsha Shivajirao Devsarkar", "CriminalCases",  " ","",  "", "", " "},
        {"Maharashtra", "4223", "Hingoli", "Asadkhan Mohammedkhan", "NotGraduate", " ", "", "", "", " "},
{ "Maharashtra",  "4226",  "Hingoli", "Uttam Maroti Dhabe", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4227",  "Hingoli", "Abdul Kadir Mastan Sayyed", "NotGraduate",  " ","",  "", "", " "},
        {"Maharashtra", "4228", "Hingoli", "Subhash Parasram Wankhede", "NotGraduate", " ", "", "", "", " "},
{ "Maharashtra",  "4036",  "Jalgaon", "Sharad Gorakh Bhamre (Sutar)", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4038",  "Jalgaon", "Mohan Shankar Birhade", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4039",  "Jalgaon", "Sant Shri Mahahansaji Maharaj Patil", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4260",  "Jalna", "Autade Vilas Keshavrao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4347",  "Kolhapur", "Kisan Keraba Katkar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4323",  "Latur", "Madhukar Sambhaji Kamble", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4324",  "Latur", "Dattu Prabhakar Karanjikar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4326",  "Latur", "Arun Ramrao Sontakke", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4327",  "Latur", "Kamant Machindra Gunaji", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4328",  "Latur", "Ramesh Nivrati Kambale", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4329",  "Latur", "Sudhakar Tukaram Shrangare", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4331",  "Latur", "Rupesh Shamrao Shanke", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4332",  "Latur", "Papita Raosaheb Randive", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4116",  "Nagpur", "Vitthhal Nanaji Gaikwad", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4117",  "Nagpur", "Sachin Haridas Somkuwar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4119",  "Nagpur", "Mohammad Jamal", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4120",  "Nagpur", "Uday Rambhauji Borkar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4121",  "Nagpur", "Prabhakar Krushnaji Satpaise", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4122",  "Nagpur", "Sahil Balchand Turkar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4125",  "Nagpur", "Prafulla Manikchand Bhange", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4126",  "Nagpur", "Manoj Kothuji Bawane", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4127",  "Nagpur", "Asim Ali", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4128",  "Nagpur", "Nitin Jairam Gadkari", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4132",  "Nagpur", "Sunil Suryabhan Kawade", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4133",  "Nagpur", "Ruben Domnik Francis", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4134",  "Nagpur", "Sachin Jagorao Patil", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4135",  "Nagpur", "Kartik Gendalal Doke", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4138",  "Nagpur", "Gopalkumar Ganeshu Kashyap", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4140",  "Nagpur", "Comrade Yogesh Krishnarao Thakare", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4142",  "Nagpur", "Dipak Laxmanrao Maske", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4143",  "Nagpur", "Nanabhau Falgunrao Patole", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4145",  "Nagpur", "Vanita Jitendra Raut", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4229",  "Nanded", "Abdul Samad", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4231",  "Nanded", "Ashok Shankarrao Chavan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4233",  "Nanded", "Chikhalikar Pratap Govindrao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4234",  "Nanded", "Ashokrao Shankarrao Chavan", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4235",  "Nanded", "Abdul Rais Ahmed Abdul Jabbar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4236",  "Nanded", "Mohan Anandrao Waghmare", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4237",  "Nanded", "Manish Dattatray Wadje", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4239",  "Nanded", "Madhavrao Sambhaji Gaikwad", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4240",  "Nanded", "Sunil Manohar Sonsale", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4241",  "Nanded", "Kadam Shrirang Uttomrao", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4309",  "Osmanabad", "Tukaram Dasrao Gangawane", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4310",  "Osmanabad", "Deepak Mahadev Tate", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4312",  "Osmanabad", "Dr.Vasant Raghunath Munde", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4314",  "Osmanabad", "Omprakash Bhupalsinh Alias Pavan Rajenimbalkar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4315",  "Osmanabad", "Sayyad Sultan Ladkhan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4317",  "Osmanabad", "Arjun (Dada) Salgar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4318",  "Osmanabad", "Ranajagjitsinha Padmasinh Patil", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4319",  "Osmanabad", "Annasaheb Ramchandra Rathod", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4320",  "Osmanabad", "Phulsure Vishwanth Sadashiv", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4321",  "Osmanabad", "Gore Netaji Nagnathrao", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4243",  "Parbhani", "Kishor Namdeo Gaware", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4244",  "Parbhani", "Kishor Baburao Munnemanik", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4248",  "Parbhani", "Govind Ramrao Deshmukh", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4249",  "Parbhani", "Rajan Ramchandra Kshirsagar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4251",  "Parbhani", "Subhash Ashokrao Ambhore (Dudhgaonkar)", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4252",  "Parbhani", "Alamgir Mohammad Khan", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4253",  "Parbhani", "Dr.Vaijnath Sitaram Phad", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4254",  "Parbhani", "Shaikh Salim Shaikh Ibrahim", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4257",  "Parbhani", "Uttamrao Pandurangrao Rathod", "OverAged",  " ","",  "", "", " "},
        {"Maharashtra", "4258", "Parbhani", "Sangita Kalyanrao Nirmal", "NotGraduate", " ", "", "", "", " "},
{ "Maharashtra",  "4259",  "Parbhani", "Jadhav Sanjay (Bandu) Haribhau", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4262",  "Pune", "Mohan Ramkisan Joshi", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4263",  "Pune", "Suhas Popat Gajarmal", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4264",  "Pune", "Chandrakant Parmeshwar Sawant", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4261",  "Raigad", "Milind Bhaguram Salvi", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4101",  "Ramtek", "Archana Chandrakumar Ukey", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4102",  "Ramtek", "Subhash Dharmdas Gajbhiye", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4103",  "Ramtek", "Bandu Ramchandra Meshram", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4104",  "Ramtek", "Vinod Bhiwaji Patil", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4105",  "Ramtek", "Anil Mahadeo Dhone", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4106",  "Ramtek", "Kanteshwar Khushalji Tumane", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4107",  "Ramtek", "Chandrabhan Baliram Ramteke", "NotGraduate",  " ","",  "", "", " "},
        {"Maharashtra", "4108", "Ramtek", "Kiran Premkumar Rodge", "NotGraduate", " ", "", "", "", " "},
{ "Maharashtra",  "4109",  "Ramtek", "Shailesh Sambhaji Janbandhu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4112",  "Ramtek", "Sandesh Bhioram Bhalekar", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4113",  "Ramtek", "Kishore Uttamrao Gajbhiye", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4114",  "Ramtek", "Natthu Madhav Lokhande", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4115",  "Ramtek", "Gautam Shriram Wasnik", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4335",  "Solapur", "Shri. Sha. Bra. Dr. Jay Siddeshwar Shivachrya Mahaswamiji", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4337",  "Solapur", "Shri Maske Shrimant Murlidhar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4339",  "Solapur", "Shri Bhise Krishna Nagnath", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4341",  "Solapur", "Shri Shinde Sushilkumar Sambhajirao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4342",  "Solapur", "Shri Ashok Bhagavan Ughade", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4343",  "Solapur", "Shri Khandare Sudarshan Raychand", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4345",  "Solapur", "Shri Patole Malhari Gulab", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4096",  "Wardha", "Dnyaneshwar Laxamnrao Wakudkar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4097",  "Wardha", "Shaileshkumar Premkishorji Agrawal", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4086",  "Wardha", "Charulata Khajansing Tokas", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4088",  "Wardha", "Ramdas Chandrabhanji Tadas", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4089",  "Wardha", "Gadhave Pravin Rameshwarrao", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4090",  "Wardha", "Umesh Sadashiv Neware", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4091",  "Wardha", "Dhanraj Kotiram Vanjari", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4092",  "Wardha", "Arvind Shamrao Lillore", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4093",  "Wardha", "Jagdish Uddhavrao Wankhede", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4094",  "Wardha", "Nandkishor Ramaji Sagar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4095",  "Wardha", "Ganesh Kisanrao Lade", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4179",  "Yavatmal-Washim", "Thakre Manikrao Govindrao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4180",  "Yavatmal-Washim", "Noorali Maheboob Ali Shah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4182",  "Yavatmal-Washim", "Bhavana Pundlikrao Gawali", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4184",  "Yavatmal-Washim", "Ramrao Sawai Pawar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4186",  "Yavatmal-Washim", "Vaishali Sudhakar Yede", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4189",  "Yavatmal-Washim", "Shaikh Javed Shaikh Mushtaq", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4190",  "Yavatmal-Washim", "Pundlik Baliram Rathod", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4191",  "Yavatmal-Washim", "Sameer Arunrao Deshpande", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4194",  "Yavatmal-Washim", "Ravi Sampatrao Jadhao", "OverAged",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4195",  "Yavatmal-Washim", "Premasai Maharaj", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4196",  "Yavatmal-Washim", "Rajesh Bhauraoji Raut", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4197",  "Yavatmal-Washim", "Pawar Ramesh Gorsing", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4198",  "Yavatmal-Washim", "Purushottam Domaji Bhajghaware", "NotGraduate",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4199",  "Yavatmal-Washim", "Salim Shah Suleman Shah", "CriminalCases",  " ","",  "", "", " "}, 
{ "Maharashtra",  "4200",  "Yavatmal-Washim", "Naresh Mahadev Ghughane", "NotGraduate",  " ","",  "", "", " "}, 
};

}