/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Maharashtra {
public static final String[][] green_bucket = {
{"Maharashtra",  "7548", "Ahmednagar", "Shridhar Jakhuji Darekar", "Independent", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10892",  "महाराष्ट्र",  "अहमदनगर", "श्रीधर जाखूजी दरेकर", "निर्दलीय", ""}, 
{"Maharashtra",  "7552", "Ahmednagar", "Wakale Namdeo Arjun", "Bahujan Samaj Party", "18.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8512",  "महाराष्ट्र",  "अहमदनगर", "वकाले नामदेव अर्जुन", "बहुजन समाज पार्टी", ""}, 
{"Maharashtra",  "4270", "Ahmednagar", "Sudhakar Laxman Avhad", "Vanchit Bahujan Aaghadi", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8677",  "महाराष्ट्र",  "अहमदनगर", "सुधाकर लक्ष्मण अवहद", "वनचत बहुजन अघादी", ""}, 
{"Maharashtra",  "4271", "Ahmednagar", "Appasaheb Navnath Palve", "Independent", "1.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10882",  "महाराष्ट्र",  "अहमदनगर", "अप्पासाहेब नवनाथ पालवे", "निर्दलीय", ""}, 
{"Maharashtra",  "4052", "Akola", "Pravin Chandrakant Kaurpuriya", "Independent", "5.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5002",  "महाराष्ट्र",  "अकोला", "प्रवीण चंद्रकांत कौरपुरिया", "निर्दलीय", ""}, 
{"Maharashtra",  "4053", "Akola", "Ambedkar Prakash Yashwant", "Vanchit Bahujan Aaghadi", "5.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6360",  "महाराष्ट्र",  "अकोला", "अम्बेडकर प्रकाश यशवंत", "वनचत बहुजन अघादी", ""}, 
{"Maharashtra",  "4055", "Akola", "Murlidhar Lalsingh Pawar", "Independent", "47.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5001",  "महाराष्ट्र",  "अकोला", "मुरलीधर लालसिंह पवार", "निर्दलीय", ""}, 
{"Maharashtra",  "4060", "Akola", "Sau. Pravina Laxman Bhatkar", "Bahujan Mukti Party", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5828",  "महाराष्ट्र",  "अकोला", "सौ। प्रवीण लक्ष्मण भटकर", "बहुजन मुक्ति पार्टी", ""}, 
{"Maharashtra",  "4068", "Amravati", "Pankaj Liladhar Meshram", "Independent", "26.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6404",  "महाराष्ट्र",  "अमरावती", "पंकज लीलाधर मेश्राम", "निर्दलीय", ""}, 
{"Maharashtra",  "4069", "Amravati", "Sonone Raju Mahadeo", "Independent", "61.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5453",  "महाराष्ट्र",  "अमरावती", "सोनोन राजू महादेव", "निर्दलीय", ""}, 
{"Maharashtra",  "4070", "Amravati", "Raju Bakshi Jamnekar", "Independent", "5.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6399",  "महाराष्ट्र",  "अमरावती", "राजू बख्शी जमनेकर", "निर्दलीय", ""}, 
{"Maharashtra",  "4079", "Amravati", "Panchshila Vijay Mohod", "Bahujan Mukti Party", "54.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6403",  "महाराष्ट्र",  "अमरावती", "पंचशिला विजय मोहोड़", "बहुजन मुक्ति पार्टी", ""}, 
{"Maharashtra",  "4080", "Amravati", "Nilima Nitin Bhatkar", "Peoples Party of India (Democratic)", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6379",  "महाराष्ट्र",  "अमरावती", "नीलिमा नितिन भटकर", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", ""}, 
{"Maharashtra",  "4081", "Amravati", "Shrikant Ulhas Raibole", "Independent", "10.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6383",  "महाराष्ट्र",  "अमरावती", "श्रीकांत उल्हास रायबोले", "निर्दलीय", ""}, 
{"Maharashtra",  "4085", "Amravati", "Pramod Laxman Meshram", "Independent", "31.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6425",  "महाराष्ट्र",  "अमरावती", "प्रमोद लक्ष्मण मेश्राम", "निर्दलीय", ""}, 
{"Maharashtra",  "7469", "Aurangabad", "Dipali Lalaji Misal", "Bahujan Mukti Party", "2.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10872",  "महाराष्ट्र",  "औरंगाबाद महा", "दिपाली लालाजी मिसल", "बहुजन मुक्ति पार्टी", ""}, 
{"Maharashtra",  "7471", "Aurangabad", "Jagan Baburao Salve", "Independent", "13000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10875",  "महाराष्ट्र",  "औरंगाबाद महा", "जगन बाबूराव साल्वे", "निर्दलीय", ""}, 
{"Maharashtra",  "7478", "Aurangabad", "Madhukar Bansi Magare", "Peoples Party of India (Democratic)", "92.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8687",  "महाराष्ट्र",  "औरंगाबाद महा", "मधुकर बंसी मगरे", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", ""}, 
{"Maharashtra",  "7482", "Aurangabad", "Arvind Kisanrao Kamble", "Bahujan Republican Socialist Party", "75000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8681",  "महाराष्ट्र",  "औरंगाबाद महा", "अरविंद किसनराव कांबले", "बहुजन रिपब्लिकन सोशलिस्ट पार्टी", ""}, 
{"Maharashtra",  "7527", "Baramati", "Vijaynath Ramchandra Chandere", "Independent", "37.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8701",  "महाराष्ट्र",  "बारामती", "विजयनाथ रामचंद्र चंदेरे", "निर्दलीय", ""}, 
{"Maharashtra",  "7532", "Baramati", "Supriya Sadanand Sule", "Nationalist Congress Party", "140.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7991",  "महाराष्ट्र",  "बारामती", "सुप्रिया सदानंद सुले", "राष्ट्रवादी कांग्रेस पार्टी", ""}, 
{"Maharashtra",  "7534", "Baramati", "Deepak Shantaram Watvisave", "Independent", "5.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8694",  "महाराष्ट्र",  "बारामती", "दीपक शांताराम वाटरविसवे", "निर्दलीय", ""}, 
{"Maharashtra",  "7538", "Baramati", "Adv.Girish Madan Patil", "Independent", "5.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8695",  "महाराष्ट्र",  "बारामती", "अधिवक्तागण मदन पाटिल", "निर्दलीय", ""}, 
{"Maharashtra",  "7539", "Baramati", "Alankruta Abhijeet Awade-Bichukale", "Independent", "4.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10868",  "महाराष्ट्र",  "बारामती", "अलंकृता अभिजीत अवदे-बिचुकले", "निर्दलीय", ""}, 
{"Maharashtra",  "4266", "Baramati", "Mangesh Nilkanth Vanshiv", "Bahujan Samaj Party", "57.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8516",  "महाराष्ट्र",  "बारामती", "मंगेश नीलकंठ वंशी", "बहुजन समाज पार्टी", ""}, 
{"Maharashtra",  "4274", "Beed", "Veer Shesherao Chokhoba", "Independent", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6537",  "महाराष्ट्र",  "बीड", "वीर शेषराव चोखोबा", "निर्दलीय", ""}, 
{"Maharashtra",  "4285", "Beed", "Shaikh Yashed Shaikh Tayyab", "Independent", "94500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8626",  "महाराष्ट्र",  "बीड", "शेख यशेद शेख तैयब", "निर्दलीय", ""}, 
{"Maharashtra",  "4288", "Beed", "Ganesh Navnathrao Karande", "Maharashtra Kranti Sena", "2.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8611",  "महाराष्ट्र",  "बीड", "गणेश नवनाथराव करंडे", "महाराष्ट्र क्रांति सेना", ""}, 
{"Maharashtra",  "4296", "Beed", "Pathan Musakhan Yunuskhan", "Independent", "6.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8621",  "महाराष्ट्र",  "बीड", "पठान मुसाखन यूनुसखान", "निर्दलीय", ""}, 
{"Maharashtra",  "4298", "Beed", "Adv. Sharad Bahinaji Kamble", "Independent", "1.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6520",  "महाराष्ट्र",  "बीड", "अभिभाषक। शरद बहिनाजी कांबले", "निर्दलीय", ""}, 
{"Maharashtra",  "4303", "Beed", "Vijay Rangnath Salve", "Independent", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6536",  "महाराष्ट्र",  "बीड", "विजय रंगनाथ साल्वे", "निर्दलीय", ""}, 
{"Maharashtra",  "7918", "Bhandara Gondiya", "Suhas Anil Funde", "Independent", "1.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4596",  "महाराष्ट्र",  "भंडारा-गोंदिया जिला", "सुहास अनिल फंडे", "निर्दलीय", ""}, 
{"Maharashtra",  "7920", "Bhandara Gondiya", "Sumit Vijay Pande", "Independent", "7.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6041",  "महाराष्ट्र",  "भंडारा-गोंदिया जिला", "सुमित विजय पांडे", "निर्दलीय", ""}, 
{"Maharashtra",  "7925", "Bhandara Gondiya", "Devidas Santuji Lanjewar", "Independent", "47.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4898",  "महाराष्ट्र",  "भंडारा-गोंदिया जिला", "देवीदास संतूजी लांजेवार", "निर्दलीय", ""}, 
{"Maharashtra",  "7926", "Bhandara Gondiya", "Dr. Sunil Sampat Chawale", "Independent", "36Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6981",  "महाराष्ट्र",  "भंडारा-गोंदिया जिला", "डॉ। सुनील संपत चावले", "निर्दलीय", ""}, 
{"Maharashtra",  "7929", "Bhandara Gondiya", "Jaiswal Virendrakumar Kasturchand", "Independent", "3.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5180",  "महाराष्ट्र",  "भंडारा-गोंदिया जिला", "जायसवाल वीरेंद्रकुमार कस्तूरचंद", "निर्दलीय", ""}, 
{"Maharashtra",  "7930", "Bhandara Gondiya", "Dr. Vijaya Rajesh Nandurkar", "Bahujan Samaj Party", "3.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5412",  "महाराष्ट्र",  "भंडारा-गोंदिया जिला", "डॉ। विजया राजेश नंदुरकर", "बहुजन समाज पार्टी", ""}, 
{"Maharashtra",  "4146", "Bhandara-Gondiya", "Suhas Anil Funde", "Independent", "1.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4596",  "महाराष्ट्र",  "भंडारा-गोंदिया जिला", "सुहास अनिल फंडे", "निर्दलीय", ""}, 
{"Maharashtra",  "4149", "Bhandara-Gondiya", "Devidas Santuji Lanjewar", "Independent", "47.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4898",  "महाराष्ट्र",  "भंडारा-गोंदिया जिला", "देवीदास संतूजी लांजेवार", "निर्दलीय", ""}, 
{"Maharashtra",  "4150", "Bhandara-Gondiya", "Dr. Vijaya Rajesh Nandurkar", "Bahujan Samaj Party", "3.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5412",  "महाराष्ट्र",  "भंडारा-गोंदिया जिला", "डॉ। विजया राजेश नंदुरकर", "बहुजन समाज पार्टी", ""}, 
{"Maharashtra",  "4151", "Bhandara-Gondiya", "Dr. Sunil Sampat Chawale", "Independent", "36Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6981",  "महाराष्ट्र",  "भंडारा-गोंदिया जिला", "डॉ। सुनील संपत चावले", "निर्दलीय", ""}, 
{"Maharashtra",  "4155", "Bhandara-Gondiya", "Sumit Vijay Pande", "Independent", "7.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6041",  "महाराष्ट्र",  "भंडारा-गोंदिया जिला", "सुमित विजय पांडे", "निर्दलीय", ""}, 
{"Maharashtra",  "4158", "Bhandara-Gondiya", "Jaiswal Virendrakumar Kasturchand", "Independent", "3.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5180",  "महाराष्ट्र",  "भंडारा-गोंदिया जिला", "जायसवाल वीरेंद्रकुमार कस्तूरचंद", "निर्दलीय", ""}, 
{"Maharashtra",  "4047", "Buldhana", "Vijay Banwarilal Masani", "Independent", "11.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5174",  "महाराष्ट्र",  "बुलढाना", "विजय बनवारीलाल मसानी", "निर्दलीय", ""}, 
{"Maharashtra",  "4169", "Chandrapur", "Gautam Ganpat Nagrale", "Bahujan Mukti Party", "55.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5809",  "महाराष्ट्र",  "चंद्रपुर", "गौतम गणपत नागराले", "बहुजन मुक्ति पार्टी", ""}, 
{"Maharashtra",  "4174", "Chandrapur", "Dashrath Pandurang Madavi", "Bahujan Republican Socialist Party", "94Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4712",  "महाराष्ट्र",  "चंद्रपुर", "दशरथ पांडुरंग मदावी", "बहुजन रिपब्लिकन सोशलिस्ट पार्टी", ""}, 
{"Maharashtra",  "4177", "Chandrapur", "Rajendra Krishnarao Hajare", "Independent", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5811",  "महाराष्ट्र",  "चंद्रपुर", "राजेंद्र कृष्णराव हजारे", "निर्दलीय", ""}, 
{"Maharashtra",  "7917", "Gadchiroli Chimur", "Deorao Monba Nannaware", "Ambedkarite Party of India", "48.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4929",  "महाराष्ट्र",  "गढ़चिरोली-चिमूर", "देवरो मोनबा ननवारे", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Maharashtra",  "4163", "Gadchiroli-Chimur", "Deorao Monba Nannaware", "Ambedkarite Party of India", "48.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4929",  "महाराष्ट्र",  "गढ़चिरोली-चिमूर", "देवरो मोनबा ननवारे", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Maharashtra",  "7632", "Hatkanangle", "Dhairyashil Sambhajirao Mane", "Shiv Sena", "4.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8517",  "महाराष्ट्र",  "हातकणंगले", "धरायाशिल संभाजीराव माने", "शिवसेना", ""}, 
{"Maharashtra",  "7633", "Hatkanangle", "Sangramsinh Jaysingrao Gaikwad", "Independent", "27.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11213",  "महाराष्ट्र",  "हातकणंगले", "संग्रामसिंह जयसिंगराव गायकवाड़", "निर्दलीय", ""}, 
{"Maharashtra",  "7634", "Hatkanangle", "Kishor Rajaram Panhalkar", "Independent", "76138", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10861",  "महाराष्ट्र",  "हातकणंगले", "किशोर राजाराम पन्हालकर", "निर्दलीय", ""}, 
{"Maharashtra",  "7635", "Hatkanangle", "Kamble Vishwas Ananda", "Independent", "7.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10858",  "महाराष्ट्र",  "हातकणंगले", "कांबले विश्वास आनंद", "निर्दलीय", ""}, 
{"Maharashtra",  "7642", "Hatkanangle", "Ajay Prakash Kurane", "Bahujan Samaj Party", "35.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8518",  "महाराष्ट्र",  "हातकणंगले", "अजय प्रकाश कुराने", "बहुजन समाज पार्टी", ""}, 
{"Maharashtra",  "7643", "Hatkanangle", "Dr. Nitin Udal Bhat", "Independent", "20.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10862",  "महाराष्ट्र",  "हातकणंगले", "डॉ। नितिन उदल भट", "निर्दलीय", ""}, 
{"Maharashtra",  "4202", "Hingoli", "Altaf Ahmed", "Indian Union Muslim League", "67.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6547",  "महाराष्ट्र",  "हिंगोली", "अल्ताफ अहमद", "इंडियन यूनियन मुस्लिम लीग", ""}, 
{"Maharashtra",  "4204", "Hingoli", "Wasant Kisan Paikrao", "Independent", "2.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7637",  "महाराष्ट्र",  "हिंगोली", "वसन्त किसान पाइकराव", "निर्दलीय", ""}, 
{"Maharashtra",  "4207", "Hingoli", "Sandip Nikhate", "Independent", "11.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6565",  "महाराष्ट्र",  "हिंगोली", "संदीप निकहत", "निर्दलीय", ""}, 
{"Maharashtra",  "4212", "Hingoli", "Uttam Bhagaji Kamble", "Prabuddha Republican Party", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6558",  "महाराष्ट्र",  "हिंगोली", "उत्तम भागाजी कांबले", "प्रबुद्ध रिपब्लिकन पार्टी", ""}, 
{"Maharashtra",  "4215", "Hingoli", "Marotrao Kanhobarao Hukke Patil", "Independent", "22.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6566",  "महाराष्ट्र",  "हिंगोली", "मरोत्रो कान्होबाराओ हुक्के पाटिल", "निर्दलीय", ""}, 
{"Maharashtra",  "4222", "Hingoli", "Sandesh Ramchandra Chavan", "Independent", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7642",  "महाराष्ट्र",  "हिंगोली", "संध्या रामचंद्र चव्हाण", "निर्दलीय", ""}, 
{"Maharashtra",  "4224", "Hingoli", "Mohan Fattusing Rathod", "Vanchit Bahujan Aaghadi", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6550",  "महाराष्ट्र",  "हिंगोली", "मोहन फतूसिंग राठौड़", "वनचत बहुजन अघादी", ""}, 
{"Maharashtra",  "4225", "Hingoli", "Patil Hemant Shriram", "Shiv Sena", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6559",  "महाराष्ट्र",  "हिंगोली", "पाटिल हेमंत श्रीराम", "शिवसेना", ""}, 
{"Maharashtra",  "7427", "Jalgaon", "Anant Prabhakar Mahajan", "Independent", "10.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10850",  "महाराष्ट्र",  "जलगांव", "अनंत प्रभाकर महाजन", "निर्दलीय", ""}, 
{"Maharashtra",  "7430", "Jalgaon", "Sancheti Rupesh Parasmal", "Independent", "8.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10855",  "महाराष्ट्र",  "जलगांव", "संचेती रूपेश पारसमल", "निर्दलीय", ""}, 
{"Maharashtra",  "7432", "Jalgaon", "Subhash Shivlal Khairnar", "Independent", "20.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10854",  "महाराष्ट्र",  "जलगांव", "सुभाष शिवलाल खैरनार", "निर्दलीय", ""}, 
{"Maharashtra",  "7433", "Jalgaon", "Mukesh Rajesh Kuril", "Independent", "5.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10852",  "महाराष्ट्र",  "जलगांव", "मुकेश राजेश कुरील", "निर्दलीय", ""}, 
{"Maharashtra",  "4037", "Jalgaon", "Anjali Ratnakar Baviskar", "Vanchit Bahujan Aaghadi", "2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8718",  "महाराष्ट्र",  "जलगांव", "अंजलि रत्नाकर बविस्कर", "वनचत बहुजन अघादी", ""}, 
{"Maharashtra",  "7447", "Jalna", "Arun Chintaman Chavhan", "Independent", "58100", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10839",  "महाराष्ट्र",  "जलना", "अरुण चिंतामन चौहान", "निर्दलीय", ""}, 
{"Maharashtra",  "7455", "Jalna", "Sirsath Sham", "Independent", "77Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10847",  "महाराष्ट्र",  "जलना", "सिरसथ शाम", "निर्दलीय", ""}, 
{"Maharashtra",  "7456", "Jalna", "Adv. Yogesh Dattu Gullapelli", "Independent", "4.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10842",  "महाराष्ट्र",  "जलना", "अभिभाषक। योगेश दत्तू गुलापल्ली", "निर्दलीय", ""}, 
{"Maharashtra",  "7465", "Jalna", "Trimabak Baburao Jadhav", "Swatantra Bharat Paksha", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8722",  "महाराष्ट्र",  "जलना", "त्रिमबक बाबूराव जाधव", "स्वातंत्र्य भारत पक्ष", ""}, 
{"Maharashtra",  "7620", "Kolhapur", "Yuvraj Bhimrao Desai", "Independent", "28.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10836",  "महाराष्ट्र",  "कोल्हापुर", "युवराज भीमराव देसाई", "निर्दलीय", ""}, 
{"Maharashtra",  "4348", "Kolhapur", "Sandeep Bhairavnath Kogale", "Independent", "37.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8732",  "महाराष्ट्र",  "कोल्हापुर", "संदीप भैरवनाथ कोगले", "निर्दलीय", ""}, 
{"Maharashtra",  "4349", "Kolhapur", "Sanjay Sadashivrao Mandlik", "Shiv Sena", "9.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7767",  "महाराष्ट्र",  "कोल्हापुर", "संजय सदाशिवराव मांडलिक", "शिवसेना", ""}, 
{"Maharashtra",  "4325", "Latur", "Ramrao Garkar", "Vanchit Bahujan Aaghadi", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6568",  "महाराष्ट्र",  "लातूर", "रामराव सरकार", "वनचत बहुजन अघादी", ""}, 
{"Maharashtra",  "4330", "Latur", "Siddharthkumar Digambarrao Suryawanshi", "Bahujan Samaj Party", "18.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5478",  "महाराष्ट्र",  "लातूर", "सिद्धार्थकुमार दिगंबरराव सूर्यवंशी", "बहुजन समाज पार्टी", ""}, 
{"Maharashtra",  "7556", "Madha", "Rohit More", "Independent", "44.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10808",  "महाराष्ट्र",  "माढा", "रोहित मोरे", "निर्दलीय", ""}, 
{"Maharashtra",  "7560", "Madha", "Ajinkya Aakaram Salunkhe", "Independent", "50000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10799",  "महाराष्ट्र",  "माढा", "अजिंक्य आकरम सालुंके", "निर्दलीय", ""}, 
{"Maharashtra",  "7569", "Madha", "Ajinath Laxman Kevate", "Independent", "19.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10798",  "महाराष्ट्र",  "माढा", "अजिनाथ लक्ष्मण केवट", "निर्दलीय", ""}, 
{"Maharashtra",  "7570", "Madha", "Adv. Vijayanand Shankarrao Shinde", "Independent", "13.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10810",  "महाराष्ट्र",  "माढा", "अभिभाषक। विजयानंद शंकरराव शिंदे", "निर्दलीय", ""}, 
{"Maharashtra",  "7573", "Madha", "Santosh Balasaheb Bichukale", "Independent", "62.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10815",  "महाराष्ट्र",  "माढा", "संतोष बालासाहेब बिचुकले", "निर्दलीय", ""}, 
{"Maharashtra",  "4346", "Madha", "Ramchandra Mayyappa Ghutukade", "Bahujan Republican Socialist Party", "2.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8744",  "महाराष्ट्र",  "माढा", "रामचंद्र मयप्पा घोटुकडे", "बहुजन रिपब्लिकन सोशलिस्ट पार्टी", ""}, 
{"Maharashtra",  "4118", "Nagpur", "Adv. Ulhas Shalikaram Dupare", "Independent", "1.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4595",  "महाराष्ट्र",  "नागपुर", "अभिभाषक। उल्हास शालिकाराम दुपारे", "निर्दलीय", ""}, 
{"Maharashtra",  "4123", "Nagpur", "Dikshita Anand Tembhurne", "Desh Janhit Party", "98884", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6988",  "महाराष्ट्र",  "नागपुर", "दीक्षा आनंद तंभरने", "देश जनहित पार्टी", ""}, 
{"Maharashtra",  "4124", "Nagpur", "Mane Suresh Tatoba", "Bahujan Republican Socialist Party", "8.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4893",  "महाराष्ट्र",  "नागपुर", "माने सुरेश तोतोबा", "बहुजन रिपब्लिकन सोशलिस्ट पार्टी", ""}, 
{"Maharashtra",  "4129", "Nagpur", "Siddharth Asaram Kurve", "Independent", "50000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5807",  "महाराष्ट्र",  "नागपुर", "सिद्धार्थ आसाराम कुर्वे", "निर्दलीय", ""}, 
{"Maharashtra",  "4130", "Nagpur", "Satish Vitthal Nikhar", "Independent", "24.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6997",  "महाराष्ट्र",  "नागपुर", "सतीश विठ्ठल निखर", "निर्दलीय", ""}, 
{"Maharashtra",  "4131", "Nagpur", "Manohar Alias Sagar Pundlikrao Dabrase", "Vanchit Bahujan Aaghadi", "42Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5806",  "महाराष्ट्र",  "नागपुर", "मनोहर उर्फ सागर पुंडलीकराव डबरासे", "वनचत बहुजन अघादी", ""}, 
{"Maharashtra",  "4136", "Nagpur", "Adv. Vijaya Dilip Bagde", "Ambedkarite Party of India", "2.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4890",  "महाराष्ट्र",  "नागपुर", "अभिभाषक। विजया दिलीप बागड़े", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Maharashtra",  "4137", "Nagpur", "Dr. Manisha Bangar", "Peoples Party of India (Democratic)", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6991",  "महाराष्ट्र",  "नागपुर", "डॉ। मनीषा बांगर", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", ""}, 
{"Maharashtra",  "4139", "Nagpur", "Dr. Vinod Kashiram Badole", "Akhil Bhartiya Sarvadharma Samaj Party", "1.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6982",  "महाराष्ट्र",  "नागपुर", "डॉ। विनोद काशीराम बडोले", "अखिल भारतीय सर्वधर्म समाज पार्टी", ""}, 
{"Maharashtra",  "4141", "Nagpur", "Shridhar Narayan Salve", "Rashtriya Jansambhavna Party", "2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6992",  "महाराष्ट्र",  "नागपुर", "श्रीधर नारायण साल्वे", "राष्ट्रीय जनसंवाद पार्टी", ""}, 
{"Maharashtra",  "4144", "Nagpur", "Ali Ashfaque Ahmed", "Bahujan Mukti Party", "14.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6983",  "महाराष्ट्र",  "नागपुर", "अली अशफाक अहमद", "बहुजन मुक्ति पार्टी", ""}, 
{"Maharashtra",  "4230", "Nanded", "Mahesh Prakashrao Talegaonkar", "Independent", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7647",  "महाराष्ट्र",  "नांदेड़", "महेश प्रकाशराव तालेगांवकर", "निर्दलीय", ""}, 
{"Maharashtra",  "4232", "Nanded", "Shivanand Ashokrao Deshmukh", "Independent", "13137", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7650",  "महाराष्ट्र",  "नांदेड़", "शिवानंद अशोकराव देशमुख", "निर्दलीय", ""}, 
{"Maharashtra",  "4238", "Nanded", "Ranjit Gangadharrao Deshmukh", "Independent", "3.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7649",  "महाराष्ट्र",  "नांदेड़", "रंजीत गंगाधरराव देशमुख", "निर्दलीय", ""}, 
{"Maharashtra",  "4242", "Nanded", "Bhinge Yashpal Narsinghrao", "Vanchit Bahujan Aaghadi", "88.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6578",  "महाराष्ट्र",  "नांदेड़", "भिंगे यशपाल नरसिंहराव", "वनचत बहुजन अघादी", ""}, 
{"Maharashtra",  "4311", "Osmanabad", "Dr. Shivaji Pandharinath Oman", "Bahujan Samaj Party", "91.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8630",  "महाराष्ट्र",  "उस्मानाबाद", "डॉ। शिवाजी पंढरीनाथ ओमान", "बहुजन समाज पार्टी", ""}, 
{"Maharashtra",  "4313", "Osmanabad", "Aryanraje Kisanrao Shinde", "Independent", "30000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4978",  "महाराष्ट्र",  "उस्मानाबाद", "आर्यनराजे किसनराव शिंदे", "निर्दलीय", ""}, 
{"Maharashtra",  "4316", "Osmanabad", "Jagannath Nivrutti Munde", "Independent", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8634",  "महाराष्ट्र",  "उस्मानाबाद", "जगन्नाथ निवृत्ती मुंडे", "निर्दलीय", ""}, 
{"Maharashtra",  "4322", "Osmanabad", "Shankar Pandurang Gaikwad", "Independent", "49.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6584",  "महाराष्ट्र",  "उस्मानाबाद", "शंकर पांडुरंग गायकवाड़", "निर्दलीय", ""}, 
{"Maharashtra",  "4245", "Parbhani", "Bobade Sakharam Gyanba", "Independent", "11Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6587",  "महाराष्ट्र",  "परभनी", "बोबडे सखाराम ज्ञानबा", "निर्दलीय", ""}, 
{"Maharashtra",  "4246", "Parbhani", "Dr.Appasaheb Onkar Kadam", "Swatantra Bharat Paksha", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6592",  "महाराष्ट्र",  "परभनी", "डॉ.पतासाहेब ओंकार कदम", "स्वातंत्र्य भारत पक्ष", ""}, 
{"Maharashtra",  "4247", "Parbhani", "Yashwant Rambhau Kasbe", "Bahujan Republican Socialist Party", "14.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6590",  "महाराष्ट्र",  "परभनी", "यशवंत रामभाऊ कस्बे", "बहुजन रिपब्लिकन सोशलिस्ट पार्टी", ""}, 
{"Maharashtra",  "4250", "Parbhani", "Harishchandra Dattu Patil", "Sangharsh Sena", "51.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6585",  "महाराष्ट्र",  "परभनी", "हरिश्चंद्र दत्तू पाटिल", "संघर्ष सेना", ""}, 
{"Maharashtra",  "4255", "Parbhani", "Santosh Govind Rathod", "Bhartiya Bahujan Kranti Dal", "16.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6588",  "महाराष्ट्र",  "परभनी", "संतोष गोविंद राठौड़", "भारतीय बहुजन क्रांति दल", ""}, 
{"Maharashtra",  "4256", "Parbhani", "Rajesh Uttamrao Vitekar", "Nationalist Congress Party", "5.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6591",  "महाराष्ट्र",  "परभनी", "राजेश उत्तमराव विटेकर", "राष्ट्रवादी कांग्रेस पार्टी", ""}, 
{"Maharashtra",  "7502", "Pune", "Prof. Nalawade Hanmant Mahadeo", "Ambedkarite Party of India", "47Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8750",  "महाराष्ट्र",  "पुणे", "नलवाडे हनमंत महादेव के प्रो", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Maharashtra",  "7503", "Pune", "Adv. Mahesh Gajendragadkar", "Swarna Bharat Party", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10758",  "महाराष्ट्र",  "पुणे", "अभिभाषक। महेश गजेन्द्रगढ़कर", "स्वर्ण भारत पार्टी", ""}, 
{"Maharashtra",  "7505", "Pune", "Amol Jayraj Shinde", "Hum Bhartiya Party", "3.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10752",  "महाराष्ट्र",  "पुणे", "अमोल जयराज शिंदे", "हम भारतीय पार्टी", ""}, 
{"Maharashtra",  "7506", "Pune", "Kshirsagar Kanchan Devdas", "Independent", "13.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10776",  "महाराष्ट्र",  "पुणे", "क्षीरसागर कंचन देवदास", "निर्दलीय", ""}, 
{"Maharashtra",  "7507", "Pune", "Adv. Kumar Devba Kalel Patil", "Independent", "3.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10765",  "महाराष्ट्र",  "पुणे", "अभिभाषक। कुमार देवबा कलाल पाटिल", "निर्दलीय", ""}, 
{"Maharashtra",  "7509", "Pune", "Balasaheb Misal Patil", "Bahujan Mukti Party", "19.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10757",  "महाराष्ट्र",  "पुणे", "बालासाहेब मिशाल पाटिल", "बहुजन मुक्ति पार्टी", ""}, 
{"Maharashtra",  "7512", "Pune", "Sayyad Raj Faiyaz", "Bhartiya Kisan Party", "52Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10761",  "महाराष्ट्र",  "पुणे", "सय्यद राज फय्याज", "भारतीय किसान पार्टी", ""}, 
{"Maharashtra",  "7513", "Pune", "Sim Khirid", "Bahujan Maha Party", "3.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10762",  "महाराष्ट्र",  "पुणे", "सिम खिरिद", "बहुजन महा पार्टी", ""}, 
{"Maharashtra",  "7515", "Pune", "Krupal Paluskar", "Prabuddha Republican Party", "5.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10753",  "महाराष्ट्र",  "पुणे", "कृपाल पलुस्कर", "प्रबुद्ध रिपब्लिकन पार्टी", ""}, 
{"Maharashtra",  "7518", "Pune", "Rahul Vishwas Joshi", "Independent", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10771",  "महाराष्ट्र",  "पुणे", "राहुल विश्वास जोशी", "निर्दलीय", ""}, 
{"Maharashtra",  "7521", "Pune", "Adv. Ramesh Devaram Dharmavat", "Peopleâ€™s Union Party", "23.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10759",  "महाराष्ट्र",  "पुणे", "अभिभाषक। रमेश देवाराम धर्मावत", "पीपुल्स यूनियन पार्टी", ""}, 
{"Maharashtra",  "7523", "Pune", "Nikhil Umesh Zingade", "Bharatiya Praja Surajya Paksha", "27.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10756",  "महाराष्ट्र",  "पुणे", "निखिल उमेश झिंगडे", "भारतीय प्रजा सूरज पक्ष", ""}, 
{"Maharashtra",  "7492", "Raigad", "Prakash Sakharam Kalke", "Bhartiya Kisan Party", "37.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8757",  "महाराष्ट्र",  "रायगढ़", "प्रकाश सखाराम कल्के", "भारतीय किसान पार्टी", ""}, 
{"Maharashtra",  "4100", "Ramtek", "Krupal Balaji Tumane", "Shiv Sena", "9.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5725",  "महाराष्ट्र",  "रामटेक", "कृपाल बालाजी तुमणे", "शिवसेना", ""}, 
{"Maharashtra",  "4110", "Ramtek", "Laxman Jyotik Kanhekar", "Peoples Party of India (Democratic)", "74.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5727",  "महाराष्ट्र",  "रामटेक", "लक्ष्मण ज्योतिक कान्हेकर", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", ""}, 
{"Maharashtra",  "4111", "Ramtek", "Sonali Ravindra Bagde", "Independent", "15000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5732",  "महाराष्ट्र",  "रामटेक", "सोनाली रवींद्र बागड़े", "निर्दलीय", ""}, 
{"Maharashtra",  "7606", "Ratnagiri Sindhudurg", "Rajesh Dilipkumar Jadhav", "Bahujan Republican Socialist Party", "2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8762",  "महाराष्ट्र",  "रत्नागिरी-सिंधुदुर्ग", "राजेश दिलीपकुमार जाधव", "बहुजन रिपब्लिकन सोशलिस्ट पार्टी", ""}, 
{"Maharashtra",  "7608", "Ratnagiri Sindhudurg", "Narayan Dasharath Gavas", "Independent", "3.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10741",  "महाराष्ट्र",  "रत्नागिरी-सिंधुदुर्ग", "नारायण दशरथ गवास", "निर्दलीय", ""}, 
{"Maharashtra",  "7612", "Ratnagiri Sindhudurg", "Nilesh Bhikaji Bhatade", "Independent", "3.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10742",  "महाराष्ट्र",  "रत्नागिरी-सिंधुदुर्ग", "नीलेश भीकाजी भटेड़े", "निर्दलीय", ""}, 
{"Maharashtra",  "7613", "Ratnagiri Sindhudurg", "Bhikuram Kashiram Palkar", "Bahujan Mukti Party", "53.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8764",  "महाराष्ट्र",  "रत्नागिरी-सिंधुदुर्ग", "भिकुरम काशीराम पालकर", "बहुजन मुक्ति पार्टी", ""}, 
{"Maharashtra",  "7617", "Ratnagiri Sindhudurg", "Adv. Sanjay Sharad Gangnaik8", "Samajwadi Forward Bloc", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8763",  "महाराष्ट्र",  "रत्नागिरी-सिंधुदुर्ग", "अभिभाषक। संजय शरद गंगानिक na", "समाजवादी फॉरवर्ड ब्लॉक", ""}, 
{"Maharashtra",  "7587", "Sangli", "Rajendra Namdev Kavthekar", "Bahujan Mukti Party", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8768",  "महाराष्ट्र",  "सांगली", "राजेंद्र नामदेव कवठेकर", "बहुजन मुक्ति पार्टी", ""}, 
{"Maharashtra",  "7599", "Satara", "Sahdev Kerappa Aiwale", "Vanchit Bahujan Aaghadi", "14.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8773",  "महाराष्ट्र",  "सतारा", "सहदेव केरप्पा अइवाले", "वनचत बहुजन अघादी", ""}, 
{"Maharashtra",  "7602", "Satara", "Shailendra Veer", "Independent", "2.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8772",  "महाराष्ट्र",  "सतारा", "शैलेंद्र वीर", "निर्दलीय", ""}, 
{"Maharashtra",  "7603", "Satara", "Dilip Shreerang Jagtap", "Bahujan Republican Socialist Party", "13.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8774",  "महाराष्ट्र",  "सतारा", "दिलीप श्रीरंग जगताप", "बहुजन रिपब्लिकन सोशलिस्ट पार्टी", ""}, 
{"Maharashtra",  "4333", "Solapur", "Ad. Karande Manisha Manohar", "Independent", "20000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6606",  "महाराष्ट्र",  "सोलापुर", "विज्ञापन। करन्दे मनीषा मनोहर", "निर्दलीय", ""}, 
{"Maharashtra",  "4334", "Solapur", "Shri Ambedkar Prakash Yashwant", "Vanchit Bahujan Aaghadi", "5.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5198",  "महाराष्ट्र",  "सोलापुर", "श्री अम्बेडकर प्रकाश यशवंत", "वनचत बहुजन अघादी", ""}, 
{"Maharashtra",  "4336", "Solapur", "Prof. Dr. Ohal Arjun Gena", "Bahujan Mukti Party", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6603",  "महाराष्ट्र",  "सोलापुर", "डॉ। ओहाल अर्जुन गेना", "बहुजन मुक्ति पार्टी", ""}, 
{"Maharashtra",  "4338", "Solapur", "Shrivenkateswar Maha Swamiji (Katakdhond. D. G.)", "Hindustan Janta Party", "9", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4973",  "महाराष्ट्र",  "सोलापुर", "श्रीवेंकटेश्वर महास्वामी (कटकखंड)", "हिंदुस्तान जनता पार्टी", ""}, 
{"Maharashtra",  "4340", "Solapur", "Shri Gaydhankar Vishnu Shidram", "Bharatiya Praja Surajya Paksha", "56100", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6593",  "महाराष्ट्र",  "सोलापुर", "श्री गढ़ंकर विष्णु शिद्रम", "भारतीय प्रजा सूरज पक्ष", ""}, 
{"Maharashtra",  "4344", "Solapur", "Ad. Vikram Uttam Kasabe", "Independent", "99924", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5495",  "महाराष्ट्र",  "सोलापुर", "विज्ञापन। विक्रम उत्तम कसबे", "निर्दलीय", ""}, 
{"Maharashtra",  "4098", "Wardha", "Zitruji Chandruji Borutkar", "Independent", "2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5739",  "महाराष्ट्र",  "वर्धा", "जीतरू चंद्रूजी बोरुटकर", "निर्दलीय", ""}, 
{"Maharashtra",  "4099", "Wardha", "Adv. Bhaskar Marotrao Neware", "Independent", "1.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4711",  "महाराष्ट्र",  "वर्धा", "अभिभाषक। भास्कर मारोत्रो न्यारे", "निर्दलीय", ""}, 
{"Maharashtra",  "4087", "Wardha", "Rajesh Marotrao Balpande", "Independent", "80.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4883",  "महाराष्ट्र",  "वर्धा", "राजेश मारोत्रो बालपांडे", "निर्दलीय", ""}, 
{"Maharashtra",  "7936", "Yavatmal Washim", "Parashram Bhaosing Ade", "Independent", "18.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6116",  "महाराष्ट्र",  "यवतमाल-वाशिम", "परशराम भोसिंग एडे", "निर्दलीय", ""}, 
{"Maharashtra",  "7943", "Yavatmal Washim", "Simpal Rajkumar Rathod", "Independent", "9.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5750",  "महाराष्ट्र",  "यवतमाल-वाशिम", "सिंपल राजकुमार राठौड़", "निर्दलीय", ""}, 
{"Maharashtra",  "7945", "Yavatmal Washim", "Dr. Rajiv Agrawal", "Independent", "87.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5759",  "महाराष्ट्र",  "यवतमाल-वाशिम", "डॉ। राजीव अग्रवाल", "निर्दलीय", ""}, 
{"Maharashtra",  "7946", "Yavatmal Washim", "Anil Jayram Rathod", "Independent", "48.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4922",  "महाराष्ट्र",  "यवतमाल-वाशिम", "अनिल जयराम राठौड़", "निर्दलीय", ""}, 
{"Maharashtra",  "7952", "Yavatmal Washim", "Pravin Govind Pawar", "Vanchit Bahujan Aaghadi", "4.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5755",  "महाराष्ट्र",  "यवतमाल-वाशिम", "प्रवीण गोविंद पवार", "वनचत बहुजन अघादी", ""}, 
{"Maharashtra",  "7932", "Yavatmal Washim", "Shahejad Samiullah Khan", "Independent", "1.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4924",  "महाराष्ट्र",  "यवतमाल-वाशिम", "शहजाद समीउल्लाह खान", "निर्दलीय", ""}, 
{"Maharashtra",  "7933", "Yavatmal Washim", "Ankit Mohan Chandak", "Independent", "3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4600",  "महाराष्ट्र",  "यवतमाल-वाशिम", "अंकित मोहन चांडक", "निर्दलीय", ""}, 
{"Maharashtra",  "7935", "Yavatmal Washim", "Uttam Bhagaji Kamble", "Prabuddha Republican Party", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5754",  "महाराष्ट्र",  "यवतमाल-वाशिम", "उत्तम भागाजी कांबले", "प्रबुद्ध रिपब्लिकन पार्टी", ""}, 
{"Maharashtra",  "4178", "Yavatmal-Washim", "Uttam Bhagaji Kamble", "Prabuddha Republican Party", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5754",  "महाराष्ट्र",  "यवतमाल-वाशिम", "उत्तम भागाजी कांबले", "प्रबुद्ध रिपब्लिकन पार्टी", ""}, 
{"Maharashtra",  "4181", "Yavatmal-Washim", "Simpal Rajkumar Rathod", "Independent", "9.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5750",  "महाराष्ट्र",  "यवतमाल-वाशिम", "सिंपल राजकुमार राठौड़", "निर्दलीय", ""}, 
{"Maharashtra",  "4183", "Yavatmal-Washim", "Ankit Mohan Chandak", "Independent", "3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4600",  "महाराष्ट्र",  "यवतमाल-वाशिम", "अंकित मोहन चांडक", "निर्दलीय", ""}, 
{"Maharashtra",  "4185", "Yavatmal-Washim", "Pravin Govind Pawar", "Vanchit Bahujan Aaghadi", "4.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5755",  "महाराष्ट्र",  "यवतमाल-वाशिम", "प्रवीण गोविंद पवार", "वनचत बहुजन अघादी", ""}, 
{"Maharashtra",  "4187", "Yavatmal-Washim", "Parashram Bhaosing Ade", "Independent", "18.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6116",  "महाराष्ट्र",  "यवतमाल-वाशिम", "परशराम भोसिंग एडे", "निर्दलीय", ""}, 
{"Maharashtra",  "4188", "Yavatmal-Washim", "Dr. Rajiv Agrawal", "Independent", "87.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5759",  "महाराष्ट्र",  "यवतमाल-वाशिम", "डॉ। राजीव अग्रवाल", "निर्दलीय", ""}, 
{"Maharashtra",  "4192", "Yavatmal-Washim", "Shahejad Samiullah Khan", "Independent", "1.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4924",  "महाराष्ट्र",  "यवतमाल-वाशिम", "शहजाद समीउल्लाह खान", "निर्दलीय", ""}, 
{"Maharashtra",  "4193", "Yavatmal-Washim", "Anil Jayram Rathod", "Independent", "48.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4922",  "महाराष्ट्र",  "यवतमाल-वाशिम", "अनिल जयराम राठौड़", "निर्दलीय", ""}, 
};

public static final String[][] red_bucket = {
{ "Maharashtra",  "7543",  "Ahmednagar", "Sanjay Dagdu Sawant", "NotGraduate",  " ","महाराष्ट्र",  "अहमदनगर", "संजय दगडू सावंत", " "}, 
{ "Maharashtra",  "7544",  "Ahmednagar", "Sangram Arunkaka Jagtap", "CriminalCases",  " ","महाराष्ट्र",  "अहमदनगर", "संग्राम अरुनका जगताप", " "}, 
{ "Maharashtra",  "7545",  "Ahmednagar", "Sanjiv Baban Bhor", "CriminalCases",  " ","महाराष्ट्र",  "अहमदनगर", "संजीव बबन भोर", " "}, 
{ "Maharashtra",  "7546",  "Ahmednagar", "Shaikh Abid Mohammad Hanif", "NotGraduate",  " ","महाराष्ट्र",  "अहमदनगर", "शेख आबिद मोहम्मद हनीफ", " "}, 
{ "Maharashtra",  "7547",  "Ahmednagar", "Kamal Dashrath Sawant", "CriminalCases",  " ","महाराष्ट्र",  "अहमदनगर", "कमल दशरथ सावंत", " "}, 
{ "Maharashtra",  "7549",  "Ahmednagar", "Sandip Laxman Sakat", "CriminalCases",  " ","महाराष्ट्र",  "अहमदनगर", "संदीप लक्ष्मण सकत", " "}, 
{ "Maharashtra",  "7550",  "Ahmednagar", "Farukh Ismail Shaikh", "NotGraduate",  " ","महाराष्ट्र",  "अहमदनगर", "फारुख इस्माइल शेख", " "}, 
{ "Maharashtra",  "7551",  "Ahmednagar", "Supekar Dnyandeo Narhari", "OverAged",  " ","महाराष्ट्र",  "अहमदनगर", "सुपेकर ज्ञानदेव नरहरि", " "}, 
{ "Maharashtra",  "7553",  "Ahmednagar", "Sujay Radhakrishna Vikhe", "ForeignFunding",  " ","महाराष्ट्र",  "अहमदनगर", "सुजय राधाकृष्ण विखे", " "}, 
{ "Maharashtra",  "7554",  "Ahmednagar", "Sainath Bhausaheb Ghorpade", "CriminalCases",  " ","महाराष्ट्र",  "अहमदनगर", "साईनाथ भाऊसाहेब घोरपड़े", " "}, 
{ "Maharashtra",  "7555",  "Ahmednagar", "Ramnath Gahininath Golhar", "NotGraduate",  " ","महाराष्ट्र",  "अहमदनगर", "रामनाथ गहिनीनाथ गोलहर", " "}, 
{ "Maharashtra",  "4267",  "Ahmednagar", "Bhaskar Fakira Patole", "NotGraduate",  " ","महाराष्ट्र",  "अहमदनगर", "भास्कर फकीरा पटोले", " "}, 
{ "Maharashtra",  "4268",  "Ahmednagar", "Kaliram Bahiru Popalghat", "OverAged",  " ","महाराष्ट्र",  "अहमदनगर", "कालीराम बहिरू पोपटघाट", " "}, 
{ "Maharashtra",  "4269",  "Ahmednagar", "Dattatraya Appa Waghmode", "NotGraduate",  " ","महाराष्ट्र",  "अहमदनगर", "दत्तात्रेय अप्पा वाघमोडे", " "}, 
{ "Maharashtra",  "4272",  "Ahmednagar", "Dhiraj Motilal Batade", "NotGraduate",  " ","महाराष्ट्र",  "अहमदनगर", "धीरज मोतीलाल बाटाडे", " "}, 
{ "Maharashtra",  "4051",  "Akola", "Kamble Bhanudas Chokhoba", "NotGraduate",  " ","महाराष्ट्र",  "अकोला", "कांबले भानुदास चोखोबा", " "}, 
{ "Maharashtra",  "4054",  "Akola", "Arun Kankar Wankhede", "NotGraduate",  " ","महाराष्ट्र",  "अकोला", "अरुण कंकर वानखेड़े", " "}, 
{ "Maharashtra",  "4056",  "Akola", "Sachin Ganpatlal Sharma", "NotGraduate",  " ","महाराष्ट्र",  "अकोला", "सचिन गणपतलाल शर्मा", " "}, 
{ "Maharashtra",  "4057",  "Akola", "Arun Manohar Thakare", "NotGraduate",  " ","महाराष्ट्र",  "अकोला", "अरुण मनोहर ठाकरे", " "}, 
{ "Maharashtra",  "4058",  "Akola", "Hidayatulla Barakatulla Patel", "ForeignFunding",  " ","महाराष्ट्र",  "अकोला", "हिदायतुल्ला बरकतुल्ला पटेल", " "}, 
{ "Maharashtra",  "4059",  "Akola", "Gajanan Onkar Harne", "NotGraduate",  " ","महाराष्ट्र",  "अकोला", "गजानन ओंकार हरने", " "}, 
{ "Maharashtra",  "4061",  "Akola", "Sanjay Shamrao Dhotre", "ForeignFunding",  " ","महाराष्ट्र",  "अकोला", "संजय शामराव धोत्रे", " "}, 
{ "Maharashtra",  "4062",  "Amravati", "Navneet Ravi Rana", "CriminalCases",  " ","महाराष्ट्र",  "अमरावती", "नवनीत रवि राणा", " "}, 
{ "Maharashtra",  "4063",  "Amravati", "Gunavant Deopare", "CriminalCases",  " ","महाराष्ट्र",  "अमरावती", "गुणवंत दिपारे", " "}, 
{ "Maharashtra",  "4064",  "Amravati", "Ambadas Shamrao Wankhade", "NotGraduate",  " ","महाराष्ट्र",  "अमरावती", "अम्बादास शामराव वानखड़े", " "}, 
{ "Maharashtra",  "4065",  "Amravati", "Anandrao Vithoba Adsul", "CriminalCases",  " ","महाराष्ट्र",  "अमरावती", "आनंदराव विठोबा एडसूल", " "}, 
{ "Maharashtra",  "4066",  "Amravati", "Vilas Sheshrao Thorat", "NotGraduate",  " ","महाराष्ट्र",  "अमरावती", "विलास शेषराव थोरात", " "}, 
{ "Maharashtra",  "4067",  "Amravati", "Dnyaneshwar Kashirao Mankar", "NotGraduate",  " ","महाराष्ट्र",  "अमरावती", "ज्ञानेश्वर काशीराव मानकर", " "}, 
{ "Maharashtra",  "4071",  "Amravati", "Nilesh Anandrao Patil", "NotGraduate",  " ","महाराष्ट्र",  "अमरावती", "नीलेश आनंदराव पाटिल", " "}, 
{ "Maharashtra",  "4072",  "Amravati", "Narendra Babulal Kathane", "NotGraduate",  " ","महाराष्ट्र",  "अमरावती", "नरेंद्र बाबूलाल कथाने", " "}, 
{ "Maharashtra",  "4073",  "Amravati", "Arun Motiramji Wankhade", "CriminalCases",  " ","महाराष्ट्र",  "अमरावती", "अरुण मोतीरामजी वानखड़े", " "}, 
{ "Maharashtra",  "4074",  "Amravati", "Rahulbhau Laxmanrao Mohod", "CriminalCases",  " ","महाराष्ट्र",  "अमरावती", "राहुलभाऊ लक्ष्मणराव मोहोड़", " "}, 
{ "Maharashtra",  "4075",  "Amravati", "Raju Shamraoji Mankar", "NotGraduate",  " ","महाराष्ट्र",  "अमरावती", "राजू शामरावजी मानकर", " "}, 
{ "Maharashtra",  "4076",  "Amravati", "Sanjay Hiramanji Athwale", "CriminalCases",  " ","महाराष्ट्र",  "अमरावती", "संजय हीरामनजी अठावले", " "}, 
{ "Maharashtra",  "4077",  "Amravati", "Vijay Yashvant Vilhekar", "NotGraduate",  " ","महाराष्ट्र",  "अमरावती", "विजय यशवंत विल्हेकर", " "}, 
{ "Maharashtra",  "4078",  "Amravati", "Pravin Mahadeo Sarode", "NotGraduate",  " ","महाराष्ट्र",  "अमरावती", "प्रवीण महादेव सरोदे", " "}, 
{ "Maharashtra",  "4082",  "Amravati", "Kurwade Meenakshi Someshwar", "NotGraduate",  " ","महाराष्ट्र",  "अमरावती", "कुरावडे मीनाक्षी सोमेश्वर", " "}, 
{ "Maharashtra",  "4083",  "Amravati", "Anil Namdevrao Jamnekar", "NotGraduate",  " ","महाराष्ट्र",  "अमरावती", "अनिल नामदेवराव जमनेकर", " "}, 
{ "Maharashtra",  "4084",  "Amravati", "Gade Vinod Milind", "NotGraduate",  " ","महाराष्ट्र",  "अमरावती", "गाडे विनोद मिलिंद", " "}, 
{ "Maharashtra",  "7466",  "Aurangabad", "Habib Gayas Shaikh", "NotGraduate",  " ","महाराष्ट्र",  "औरंगाबाद महा", "हबीब ग्यास शेख", " "}, 
{ "Maharashtra",  "7467",  "Aurangabad", "Mahamad Jakir Abdul Kadar", "NotGraduate",  " ","महाराष्ट्र",  "औरंगाबाद महा", "महामद जाकिर अब्दुल कादर", " "}, 
{ "Maharashtra",  "7468",  "Aurangabad", "Shaikh Khaja Shaikh Kasim Kismatwala", "NotGraduate",  " ","महाराष्ट्र",  "औरंगाबाद महा", "शेख खाजा शेख कासिम किस्मतवाला", " "}, 
{ "Maharashtra",  "7470",  "Aurangabad", "Shaikh Nadim Shaikh Karim", "NotGraduate",  " ","महाराष्ट्र",  "औरंगाबाद महा", "शेख नादिम शेख करीम", " "}, 
{ "Maharashtra",  "7472",  "Aurangabad", "Sangita Kalyanrao Nirmal", "NotGraduate",  " ","महाराष्ट्र",  "औरंगाबाद महा", "संगिता कल्याणराव निर्मल", " "}, 
{ "Maharashtra",  "7473",  "Aurangabad", "Khan Aejaz Ahemad", "CriminalCases",  " ","महाराष्ट्र",  "औरंगाबाद महा", "खान एजाज अहमद", " "}, 
{ "Maharashtra",  "7474",  "Aurangabad", "Imtiaz Jaleel Syed", "CriminalCases",  " ","महाराष्ट्र",  "औरंगाबाद महा", "इम्तियाज जलील सैयद", " "}, 
{ "Maharashtra",  "7475",  "Aurangabad", "Kurangal Sanjay Baburao", "NotGraduate",  " ","महाराष्ट्र",  "औरंगाबाद महा", "कुरंगल संजय बाबूराव", " "}, 
{ "Maharashtra",  "7476",  "Aurangabad", "Fulare Suresh Asaram", "CriminalCases",  " ","महाराष्ट्र",  "औरंगाबाद महा", "फुलारे सुरेश आसाराम", " "}, 
{ "Maharashtra",  "7477",  "Aurangabad", "Khaire Chandrakant", "CriminalCases",  " ","महाराष्ट्र",  "औरंगाबाद महा", "खैरे चंद्रकांत", " "}, 
{ "Maharashtra",  "7479",  "Aurangabad", "Uttam Dhanu Rathod", "OverAged",  " ","महाराष्ट्र",  "औरंगाबाद महा", "उत्तम धनु राठौड़", " "}, 
{ "Maharashtra",  "7480",  "Aurangabad", "Mohammad Mohasin", "NotGraduate",  " ","महाराष्ट्र",  "औरंगाबाद महा", "मोहम्मद मोहसिन", " "}, 
{ "Maharashtra",  "7481",  "Aurangabad", "Zambad Subhash Manakchand", "ForeignFunding",  " ","महाराष्ट्र",  "औरंगाबाद महा", "जांबाज सुभाष माणकचंद", " "}, 
{ "Maharashtra",  "7483",  "Aurangabad", "Kunjbihari Jugalkishor Agrawal", "CriminalCases",  " ","महाराष्ट्र",  "औरंगाबाद महा", "कुंजबिहारी जुगलकिशोर अग्रवाल", " "}, 
{ "Maharashtra",  "7484",  "Aurangabad", "Harshwardhandada Raibhanji Jadhav", "CriminalCases",  " ","महाराष्ट्र",  "औरंगाबाद महा", "हर्षवर्धन रायभानजी जाधव", " "}, 
{ "Maharashtra",  "7485",  "Aurangabad", "Tribhuvan Madhukar Padmakar", "NotGraduate",  " ","महाराष्ट्र",  "औरंगाबाद महा", "त्रिभुवन मधुकर पद्माकर", " "}, 
{ "Maharashtra",  "7486",  "Aurangabad", "Ravindra Bhanudas Kale", "NotGraduate",  " ","महाराष्ट्र",  "औरंगाबाद महा", "रवींद्र भानुदास काले", " "}, 
{ "Maharashtra",  "7528",  "Baramati", "Vishvanath Sitaram Gargade", "NotGraduate",  " ","महाराष्ट्र",  "बारामती", "विश्वनाथ सीताराम गर्गडे", " "}, 
{ "Maharashtra",  "7529",  "Baramati", "Sanjay Shinde", "NotGraduate",  " ","महाराष्ट्र",  "बारामती", "संजय शिंदे", " "}, 
{ "Maharashtra",  "7530",  "Baramati", "Dr. Balasaheb Arjun Pol", "CriminalCases",  " ","महाराष्ट्र",  "बारामती", "डॉ। बालासाहेब अर्जुन पोल", " "}, 
{ "Maharashtra",  "7531",  "Baramati", "Dashrath Nana Raut", "NotGraduate",  " ","महाराष्ट्र",  "बारामती", "दशरथ नाना राउत", " "}, 
{ "Maharashtra",  "7533",  "Baramati", "Ulhas Mugut Chormale", "NotGraduate",  " ","महाराष्ट्र",  "बारामती", "उल्हास मुगुट चर्मले", " "}, 
{ "Maharashtra",  "7535",  "Baramati", "Hemant Baburao Kolekar Patil", "CriminalCases",  " ","महाराष्ट्र",  "बारामती", "हेमंत बाबूराव कोलेकर पाटिल", " "}, 
{ "Maharashtra",  "7536",  "Baramati", "Suresh Baburao Veer", "OverAged",  " ","महाराष्ट्र",  "बारामती", "सुरेश बाबूराव वीर", " "}, 
{ "Maharashtra",  "7537",  "Baramati", "Padalkar Navanath Vishnu", "CriminalCases",  " ","महाराष्ट्र",  "बारामती", "पादालकर नवनाथ विष्णु", " "}, 
{ "Maharashtra",  "7540",  "Baramati", "Savita Bhimrao Kadale", "NotGraduate",  " ","महाराष्ट्र",  "बारामती", "सविता भीमराव कड़ले", " "}, 
{ "Maharashtra",  "7541",  "Baramati", "Kanchan Rahul Kul", "ForeignFunding",  " ","महाराष्ट्र",  "बारामती", "कंचन राहुल कुल", " "}, 
{ "Maharashtra",  "7542",  "Baramati", "Shivaji Rambhau Nandkhile", "CriminalCases",  " ","महाराष्ट्र",  "बारामती", "शिवाजी रामभाऊ नंदखिले", " "}, 
{ "Maharashtra",  "4265",  "Baramati", "Yuvraj Prakash Bhujbal", "NotGraduate",  " ","महाराष्ट्र",  "बारामती", "युवराज प्रकाश भुजबल", " "}, 
{ "Maharashtra",  "4273",  "Beed", "Kalidas Pandharinath Aapet", "CriminalCases",  " ","महाराष्ट्र",  "बीड", "कालिदास पंढरीनाथ आपेत", " "}, 
{ "Maharashtra",  "4275",  "Beed", "Bajrang Digambar Sonwane", "OverAged",  " ","महाराष्ट्र",  "बीड", "बजरंग दिगंबर सोनवाने", " "}, 
{ "Maharashtra",  "4276",  "Beed", "Shivaji Naraynrao Kawathekar", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "शिवाजी नारायणराव कवठेकर", " "}, 
{ "Maharashtra",  "4277",  "Beed", "Sayed Mujammil Sayed Jamil", "CriminalCases",  " ","महाराष्ट्र",  "बीड", "सईद मुजम्मिल सईद जमील", " "}, 
{ "Maharashtra",  "4278",  "Beed", "Kolekar Ganesh Bhausaheb", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "कोलेकर गणेश भाऊसाहेब", " "}, 
{ "Maharashtra",  "4279",  "Beed", "Vishnu Jadhav", "CriminalCases",  " ","महाराष्ट्र",  "बीड", "विष्णु जाधव", " "}, 
{ "Maharashtra",  "4280",  "Beed", "Sajan Raees Chaodhri", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "साजन रईस चोधरी", " "}, 
{ "Maharashtra",  "4281",  "Beed", "Patil Yashashri Pramod", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "पाटिल यशश्री प्रमोद", " "}, 
{ "Maharashtra",  "4282",  "Beed", "Ramesh Ramkisan Gavhane", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "रमेश रामकिशन गावाने", " "}, 
{ "Maharashtra",  "4283",  "Beed", "Galebkhan Jabbarkhan Pathan", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "गेलभान जब्बारखान पठान", " "}, 
{ "Maharashtra",  "4284",  "Beed", "Shaikh Sadek Shaikh Ibrahim", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "शेख सादिक शेख इब्राहिम", " "}, 
{ "Maharashtra",  "4286",  "Beed", "Khan Majhar Habib", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "खान मजहर हबीब", " "}, 
{ "Maharashtra",  "4287",  "Beed", "Jamir Bashir Shaikh", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "जमीर बशीर शेख", " "}, 
{ "Maharashtra",  "4289",  "Beed", "Mujeeb Naimoddin Inamdar", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "मुजीब नईमदीन इनामदार", " "}, 
{ "Maharashtra",  "4290",  "Beed", "Bajarang Manohar Sonwane", "CriminalCases",  " ","महाराष्ट्र",  "बीड", "बजरंग मनोहर सोनवणे", " "}, 
{ "Maharashtra",  "4291",  "Beed", "Ashok Bhagoji Thorat", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "अशोक भगो जी थोराट", " "}, 
{ "Maharashtra",  "4292",  "Beed", "Shinde Chandraprakash Ganpatrao", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "शिंदे चंद्रप्रकाश गणपतराव", " "}, 
{ "Maharashtra",  "4293",  "Beed", "Pathan Sarfarzkhan Mahetabkhan", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "पठान सरफराजखां महताबखान", " "}, 
{ "Maharashtra",  "4294",  "Beed", "Chavan Sampat Ramsing", "CriminalCases",  " ","महाराष्ट्र",  "बीड", "चवन संपत रामसिंग", " "}, 
{ "Maharashtra",  "4295",  "Beed", "Sadek Muniroddin Shaikh", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "सादेक मुनिरुद्दीन शेख", " "}, 
{ "Maharashtra",  "4297",  "Beed", "Sayyad Minhaj", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "सैय्यद मिन्हाज", " "}, 
{ "Maharashtra",  "4299",  "Beed", "Jagtap Nilesh Murlidhar", "CriminalCases",  " ","महाराष्ट्र",  "बीड", "जगताप नीलेश मुरलीधर", " "}, 
{ "Maharashtra",  "4300",  "Beed", "Kalyan Bhanudas Gurav", "OverAged",  " ","महाराष्ट्र",  "बीड", "कल्याण भानुदास गुरव", " "}, 
{ "Maharashtra",  "4301",  "Beed", "Pritam Gopinathrao Munde", "ForeignFunding",  " ","महाराष्ट्र",  "बीड", "प्रीतम गोपीनाथराव मुंडे", " "}, 
{ "Maharashtra",  "4302",  "Beed", "Anwar Khan Mirza Khan", "CriminalCases",  " ","महाराष्ट्र",  "बीड", "अनवर खान मिर्ज़ा खान", " "}, 
{ "Maharashtra",  "4304",  "Beed", "Tukaram Vyankati Chate", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "तुकाराम व्यंकति चते", " "}, 
{ "Maharashtra",  "4305",  "Beed", "Nisar Ahemad", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "निसार अहमद", " "}, 
{ "Maharashtra",  "4306",  "Beed", "Juber Munshi Kureshi", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "जुबेर मुंशी कुरैशी", " "}, 
{ "Maharashtra",  "4307",  "Beed", "Pandit Damodhar Khande", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "पंडित दामोदर खांडे", " "}, 
{ "Maharashtra",  "4308",  "Beed", "Rajeshkumar Annasaheb Bhadgale", "NotGraduate",  " ","महाराष्ट्र",  "बीड", "राजेशकुमार अन्नासाहेब भदगले", " "}, 
{ "Maharashtra",  "7919",  "Bhandara Gondiya", "Kalchuri Nilesh", "NotGraduate",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "कलचुरी नीलेश", " "}, 
{ "Maharashtra",  "7921",  "Bhandara Gondiya", "Patle Rajendra Sahasram", "CriminalCases",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "पटले राजेंद्र सहसराम", " "}, 
{ "Maharashtra",  "7922",  "Bhandara Gondiya", "Gajbhiye Pramod Hiraman", "CriminalCases",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "गजभिये प्रमोद हीरामन", " "}, 
{ "Maharashtra",  "7923",  "Bhandara Gondiya", "Nana Jairam", "NotGraduate",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "नाना जयराम", " "}, 
{ "Maharashtra",  "7924",  "Bhandara Gondiya", "Nanhe Karu Nagoji", "OverAged",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "नन्हे करु नागो जी", " "}, 
{ "Maharashtra",  "7927",  "Bhandara Gondiya", "Sunil Baburao Mendhe", "ForeignFunding",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "सुनील बाबूराव मेंढे", " "}, 
{ "Maharashtra",  "7928",  "Bhandara Gondiya", "Maraskolhe Bhojraj Isulal", "NotGraduate",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "मरस्कोले भोजराज इसुलाल", " "}, 
{ "Maharashtra",  "7931",  "Bhandara Gondiya", "Bhimrao Duryodhan Borkar", "OverAged",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "भीमराव दुर्योधन बोरकर", " "}, 
{ "Maharashtra",  "4147",  "Bhandara-Gondiya", "Nanhe Karu Nagoji", "OverAged",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "नन्हे करु नागो जी", " "}, 
{ "Maharashtra",  "4148",  "Bhandara-Gondiya", "Kalchuri Nilesh", "NotGraduate",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "कलचुरी नीलेश", " "}, 
{ "Maharashtra",  "4152",  "Bhandara-Gondiya", "Sunil Baburao Mendhe", "ForeignFunding",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "सुनील बाबूराव मेंढे", " "}, 
{ "Maharashtra",  "4153",  "Bhandara-Gondiya", "Nana Jairam", "NotGraduate",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "नाना जयराम", " "}, 
{ "Maharashtra",  "4154",  "Bhandara-Gondiya", "Bhimrao Duryodhan Borkar", "OverAged",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "भीमराव दुर्योधन बोरकर", " "}, 
{ "Maharashtra",  "4156",  "Bhandara-Gondiya", "Gajbhiye Pramod Hiraman", "CriminalCases",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "गजभिये प्रमोद हीरामन", " "}, 
{ "Maharashtra",  "4157",  "Bhandara-Gondiya", "Patle Rajendra Sahasram", "CriminalCases",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "पटले राजेंद्र सहसराम", " "}, 
{ "Maharashtra",  "4159",  "Bhandara-Gondiya", "Maraskolhe Bhojraj Isulal", "NotGraduate",  " ","महाराष्ट्र",  "भंडारा-गोंदिया जिला", "मरस्कोले भोजराज इसुलाल", " "}, 
{ "Maharashtra",  "4040",  "Buldhana", "A. Hafeez A. Aziz", "NotGraduate",  " ","महाराष्ट्र",  "बुलढाना", "ए हफीज ए। अजीज", " "}, 
{ "Maharashtra",  "4041",  "Buldhana", "Baliram Bhagwan Siraskar", "CriminalCases",  " ","महाराष्ट्र",  "बुलढाना", "बलिराम भगवान सिरस्कर", " "}, 
{ "Maharashtra",  "4042",  "Buldhana", "Wamanrao Ganpatrao Akhare", "NotGraduate",  " ","महाराष्ट्र",  "बुलढाना", "वामनराव गणपतराव अखाड़े", " "}, 
{ "Maharashtra",  "4043",  "Buldhana", "Dinkar Tukaram Sambare", "OverAged",  " ","महाराष्ट्र",  "बुलढाना", "दिनकर तुकाराम सांभरे", " "}, 
{ "Maharashtra",  "4044",  "Buldhana", "Prataprao Ganpatrao Jadhav", "CriminalCases",  " ","महाराष्ट्र",  "बुलढाना", "प्रतापराव गणपतराव जाधव", " "}, 
{ "Maharashtra",  "4045",  "Buldhana", "Dr. Rajendra Bhaskarrav Shingne", "CriminalCases",  " ","महाराष्ट्र",  "बुलढाना", "डॉ। राजेंद्र भास्करराव शिंगने", " "}, 
{ "Maharashtra",  "4046",  "Buldhana", "Gajanan Uttam Shantabai", "NotGraduate",  " ","महाराष्ट्र",  "बुलढाना", "गजानन उत्तम शांताबाई", " "}, 
{ "Maharashtra",  "4048",  "Buldhana", "Ananta Datta Puri", "NotGraduate",  " ","महाराष्ट्र",  "बुलढाना", "अनंत दत्त पुरी", " "}, 
{ "Maharashtra",  "4049",  "Buldhana", "Vikas Prakash Nandve", "CriminalCases",  " ","महाराष्ट्र",  "बुलढाना", "विकास प्रकाश नंदवे", " "}, 
{ "Maharashtra",  "4050",  "Buldhana", "Pratap Pandharinath Patil", "NotGraduate",  " ","महाराष्ट्र",  "बुलढाना", "प्रताप पंढरीनाथ पाटिल", " "}, 
{ "Maharashtra",  "4165",  "Chandrapur", "Dhanorkar Suresh Narayan", "ForeignFunding",  " ","महाराष्ट्र",  "चंद्रपुर", "धनोरकर सुरेश नारायण", " "}, 
{ "Maharashtra",  "4166",  "Chandrapur", "Ahir Hansraj Gangaramji", "ForeignFunding",  " ","महाराष्ट्र",  "चंद्रपुर", "अहीर हंसराज गंगारामजी", " "}, 
{ "Maharashtra",  "4167",  "Chandrapur", "Nitesh Anandrao Dongre", "NotGraduate",  " ","महाराष्ट्र",  "चंद्रपुर", "नितेश आनंदराव डोंगरे", " "}, 
{ "Maharashtra",  "4168",  "Chandrapur", "Namdeo Keshao Kinnake", "NotGraduate",  " ","महाराष्ट्र",  "चंद्रपुर", "नामदेवो केशो किनाके", " "}, 
{ "Maharashtra",  "4170",  "Chandrapur", "Sushil Wasnik", "NotGraduate",  " ","महाराष्ट्र",  "चंद्रपुर", "सुशील वासनिक", " "}, 
{ "Maharashtra",  "4171",  "Chandrapur", "Madhukar Vithal Nistane", "CriminalCases",  " ","महाराष्ट्र",  "चंद्रपुर", "मधुकर विट्ठल निस्ताने", " "}, 
{ "Maharashtra",  "4172",  "Chandrapur", "Namdeo Shedmake", "NotGraduate",  " ","महाराष्ट्र",  "चंद्रपुर", "नमदे शेदमके", " "}, 
{ "Maharashtra",  "4173",  "Chandrapur", "Milind Pralhad Dahiwale", "NotGraduate",  " ","महाराष्ट्र",  "चंद्रपुर", "मिलिंद प्रल्हाद दहिवाले", " "}, 
{ "Maharashtra",  "4175",  "Chandrapur", "Arvind Nanaji Raut", "CriminalCases",  " ","महाराष्ट्र",  "चंद्रपुर", "अरविंद नानाजी राउत", " "}, 
{ "Maharashtra",  "4176",  "Chandrapur", "Rajendra Shriramji Mahadole", "CriminalCases",  " ","महाराष्ट्र",  "चंद्रपुर", "राजेंद्र श्रीरामजी महादोले", " "}, 
{ "Maharashtra",  "7913",  "Gadchiroli Chimur", "Ashok Mahadevrao Nete", "ForeignFunding",  " ","महाराष्ट्र",  "गढ़चिरोली-चिमूर", "अशोक महादेवराव नेते", " "}, 
{ "Maharashtra",  "7914",  "Gadchiroli Chimur", "Rameshkumar Baburaoji Gajbe", "OverAged",  " ","महाराष्ट्र",  "गढ़चिरोली-चिमूर", "रमेशकुमार बाबूरावजी गजबे", " "}, 
{ "Maharashtra",  "7915",  "Gadchiroli Chimur", "Namdeo Dalluji Usendi", "ForeignFunding",  " ","महाराष्ट्र",  "गढ़चिरोली-चिमूर", "नामदेव दल्लूजी उसेंडी", " "}, 
{ "Maharashtra",  "7916",  "Gadchiroli Chimur", "Harichandra Nagoji Mangam", "NotGraduate",  " ","महाराष्ट्र",  "गढ़चिरोली-चिमूर", "हरिचंद्र नागोजी मंगम", " "}, 
{ "Maharashtra",  "4160",  "Gadchiroli-Chimur", "Rameshkumar Baburaoji Gajbe", "OverAged",  " ","महाराष्ट्र",  "गढ़चिरोली-चिमूर", "रमेशकुमार बाबूरावजी गजबे", " "}, 
{ "Maharashtra",  "4161",  "Gadchiroli-Chimur", "Namdeo Dalluji Usendi", "ForeignFunding",  " ","महाराष्ट्र",  "गढ़चिरोली-चिमूर", "नामदेव दल्लूजी उसेंडी", " "}, 
{ "Maharashtra",  "4162",  "Gadchiroli-Chimur", "Harichandra Nagoji Mangam", "NotGraduate",  " ","महाराष्ट्र",  "गढ़चिरोली-चिमूर", "हरिचंद्र नागोजी मंगम", " "}, 
{ "Maharashtra",  "4164",  "Gadchiroli-Chimur", "Ashok Mahadevrao Nete", "ForeignFunding",  " ","महाराष्ट्र",  "गढ़चिरोली-चिमूर", "अशोक महादेवराव नेते", " "}, 
{ "Maharashtra",  "7630",  "Hatkanangle", "Madan Vajir Sardar", "NotGraduate",  " ","महाराष्ट्र",  "हातकणंगले", "मदन वजीर सरदार", " "}, 
{ "Maharashtra",  "7631",  "Hatkanangle", "Patil Raghunath Ramchandra", "CriminalCases",  " ","महाराष्ट्र",  "हातकणंगले", "पाटिल रघुनाथ रामचंद्र", " "}, 
{ "Maharashtra",  "7636",  "Hatkanangle", "Shetty Raju Anna", "CriminalCases",  " ","महाराष्ट्र",  "हातकणंगले", "शेट्टी राजू अन्ना", " "}, 
{ "Maharashtra",  "7637",  "Hatkanangle", "Vijay Bhagwan Chougule", "NotGraduate",  " ","महाराष्ट्र",  "हातकणंगले", "विजय भगवान चौगुले", " "}, 
{ "Maharashtra",  "7638",  "Hatkanangle", "Mahadev Jagannath Jagadale", "NotGraduate",  " ","महाराष्ट्र",  "हातकणंगले", "महादेव जगन्नाथ जगदले", " "}, 
{ "Maharashtra",  "7639",  "Hatkanangle", "Aitawade Vidyasagar Devappa", "OverAged",  " ","महाराष्ट्र",  "हातकणंगले", "ऐतवाडे विद्यासागर देवप्पा", " "}, 
{ "Maharashtra",  "7640",  "Hatkanangle", "Sanjay Ghanshyam Agrawal", "NotGraduate",  " ","महाराष्ट्र",  "हातकणंगले", "संजय घनश्याम अग्रवाल", " "}, 
{ "Maharashtra",  "7641",  "Hatkanangle", "Raju Mujikrao Shetty", "OverAged",  " ","महाराष्ट्र",  "हातकणंगले", "राजू मुजिकराव शेट्टी", " "}, 
{ "Maharashtra",  "7644",  "Hatkanangle", "Anandrao Vasantrao Sarnaik (Fouji Bapu)", "NotGraduate",  " ","महाराष्ट्र",  "हातकणंगले", "आनंदराव वसंतराव सरनाइक (फौजी बापू)", " "}, 
{ "Maharashtra",  "4350",  "Hatkanangle", "Aslam Badshahaji Sayyad", "NotGraduate",  " ","महाराष्ट्र",  "हातकणंगले", "असलम बादशाहजी सैय्यद", " "}, 
{ "Maharashtra",  "4351",  "Hatkanangle", "Dr.Prashant Dnyaneshwar Gangavane", "CriminalCases",  " ","महाराष्ट्र",  "हातकणंगले", "डॉ.प्रशांत ज्ञानेश्वर गंगावने", " "}, 
{ "Maharashtra",  "4201",  "Hingoli", "Jaywanta Vishwambhar Wanole", "CriminalCases",  " ","महाराष्ट्र",  "हिंगोली", "जयवंता विश्वंभर वानोले", " "}, 
{ "Maharashtra",  "4203",  "Hingoli", "Maqbul Ahmed A.Habib", "NotGraduate",  " ","महाराष्ट्र",  "हिंगोली", "मकबूल अहमद ए। हबीब", " "}, 
{ "Maharashtra",  "4205",  "Hingoli", "Devji Gangaram Asole", "OverAged",  " ","महाराष्ट्र",  "हिंगोली", "देवजी गंगाराम सांत्वना", " "}, 
{ "Maharashtra",  "4206",  "Hingoli", "Santosh Maroti Boinwad", "NotGraduate",  " ","महाराष्ट्र",  "हिंगोली", "संतोष मारोती बोनीवाड", " "}, 
{ "Maharashtra",  "4208",  "Hingoli", "Gajanan Haribhau Bhalerao", "CriminalCases",  " ","महाराष्ट्र",  "हिंगोली", "गजानन हरिभाऊ भालेराव", " "}, 
{ "Maharashtra",  "4209",  "Hingoli", "Subhash Maroti Wankhede", "NotGraduate",  " ","महाराष्ट्र",  "हिंगोली", "सुभाष मारोती वानखेड़े", " "}, 
{ "Maharashtra",  "4210",  "Hingoli", "Subhash Nagorao Wankhede", "NotGraduate",  " ","महाराष्ट्र",  "हिंगोली", "सुभाष नागोरो वानखेड़े", " "}, 
{ "Maharashtra",  "4211",  "Hingoli", "Wankhede Subhashrao Bapurao", "ForeignFunding",  " ","महाराष्ट्र",  "हिंगोली", "वानखेड़े सुभाषराव बापुरो", " "}, 
{ "Maharashtra",  "4213",  "Hingoli", "Kamble Trishala Milind", "NotGraduate",  " ","महाराष्ट्र",  "हिंगोली", "कांबले त्रिशला मिलिंद", " "}, 
{ "Maharashtra",  "4214",  "Hingoli", "Patrakar P Sattar Khan Kasim Kha", "NotGraduate",  " ","महाराष्ट्र",  "हिंगोली", "पातरकर पी सत्तार खान कासिम खा", " "}, 
{ "Maharashtra",  "4216",  "Hingoli", "Subhash Kashiba Wankhede", "NotGraduate",  " ","महाराष्ट्र",  "हिंगोली", "सुभाष काशिबा वानखेड़े", " "}, 
{ "Maharashtra",  "4217",  "Hingoli", "Subhash Vitthal Wankhede", "NotGraduate",  " ","महाराष्ट्र",  "हिंगोली", "सुभाष विठ्ठल वानखेड़े", " "}, 
{ "Maharashtra",  "4218",  "Hingoli", "Sunil Dashrath Ingole", "CriminalCases",  " ","महाराष्ट्र",  "हिंगोली", "सुनील दशरथ इंगोले", " "}, 
{ "Maharashtra",  "4219",  "Hingoli", "Dr. Dhanve Datta Maroti", "CriminalCases",  " ","महाराष्ट्र",  "हिंगोली", "डॉ। धनवे दत्ता मारोती", " "}, 
{ "Maharashtra",  "4220",  "Hingoli", "Prakash Vitthalrao Ghunnar", "NotGraduate",  " ","महाराष्ट्र",  "हिंगोली", "प्रकाश विठ्ठलराव घुन्नार", " "}, 
{ "Maharashtra",  "4221",  "Hingoli", "Varsha Shivajirao Devsarkar", "CriminalCases",  " ","महाराष्ट्र",  "हिंगोली", "वर्षा शिवाजीराव देवसरकर", " "}, 
{ "Maharashtra",  "4223",  "Hingoli", "Asadkhan Mohammedkhan", "NotGraduate",  " ","महाराष्ट्र",  "हिंगोली", "असदखान मोहम्मदखान", " "}, 
{ "Maharashtra",  "4226",  "Hingoli", "Uttam Maroti Dhabe", "OverAged",  " ","महाराष्ट्र",  "हिंगोली", "उत्तम मारोती ढाबे", " "}, 
{ "Maharashtra",  "4227",  "Hingoli", "Abdul Kadir Mastan Sayyed", "NotGraduate",  " ","महाराष्ट्र",  "हिंगोली", "अब्दुल कादिर मस्तान सैय्यद", " "}, 
{ "Maharashtra",  "4228",  "Hingoli", "Subhash Parasram Wankhede", "NotGraduate",  " ","महाराष्ट्र",  "हिंगोली", "सुभाष परसराम वानखेड़े", " "}, 
{ "Maharashtra",  "7425",  "Jalgaon", "Onkaraba Chensing Jadhav", "NotGraduate",  " ","महाराष्ट्र",  "जलगांव", "ओंकारबा चेसिंग जाधव", " "}, 
{ "Maharashtra",  "7426",  "Jalgaon", "Ishwar Dayaram More", "CriminalCases",  " ","महाराष्ट्र",  "जलगांव", "ईश्वर दयाराम मोर", " "}, 
{ "Maharashtra",  "7428",  "Jalgaon", "Gulabrao Baburao Deokar", "CriminalCases",  " ","महाराष्ट्र",  "जलगांव", "गुलाबराव बाबूराव देवकर", " "}, 
{ "Maharashtra",  "7429",  "Jalgaon", "Lalit Gaurishankar Sharma (Bunty)", "NotGraduate",  " ","महाराष्ट्र",  "जलगांव", "ललित गौरीशंकर शर्मा (बंटी)", " "}, 
{ "Maharashtra",  "7431",  "Jalgaon", "Unmesh Bhaiyyasaheb Patil", "ForeignFunding",  " ","महाराष्ट्र",  "जलगांव", "अनमेश भैय्यासाहेब पाटिल", " "}, 
{ "Maharashtra",  "7434",  "Jalgaon", "Rahul Narayan Bansode", "NotGraduate",  " ","महाराष्ट्र",  "जलगांव", "राहुल नारायण बंसोड", " "}, 
{ "Maharashtra",  "4036",  "Jalgaon", "Sharad Gorakh Bhamre (Sutar)", "NotGraduate",  " ","महाराष्ट्र",  "जलगांव", "शरद गोरख भामरे (सुतार)", " "}, 
{ "Maharashtra",  "4038",  "Jalgaon", "Mohan Shankar Birhade", "CriminalCases",  " ","महाराष्ट्र",  "जलगांव", "मोहन शंकर बिरहड़े", " "}, 
{ "Maharashtra",  "4039",  "Jalgaon", "Sant Shri Mahahansaji Maharaj Patil", "CriminalCases",  " ","महाराष्ट्र",  "जलगांव", "संत श्री महाजनजी महाराज पाटिल", " "}, 
{ "Maharashtra",  "7448",  "Jalna", "Danve Raosaheb Dadarao", "ForeignFunding",  " ","महाराष्ट्र",  "जलना", "दानवे रावसाहेब दादराव", " "}, 
{ "Maharashtra",  "7449",  "Jalna", "Feroz Ali", "NotGraduate",  " ","महाराष्ट्र",  "जलना", "फ़िरोज़ अली", " "}, 
{ "Maharashtra",  "7450",  "Jalna", "Nade Dnyaneshwar Dagduji", "CriminalCases",  " ","महाराष्ट्र",  "जलना", "नाद ज्ञानेश्वर दगडूजी", " "}, 
{ "Maharashtra",  "7451",  "Jalna", "Ratan Aasaram Landge", "NotGraduate",  " ","महाराष्ट्र",  "जलना", "रतन आसाराम लांडगे", " "}, 
{ "Maharashtra",  "7452",  "Jalna", "Annasaheb Devidasrao Ugale", "NotGraduate",  " ","महाराष्ट्र",  "जलना", "अन्नासाहेब देवीदासराव उगले", " "}, 
{ "Maharashtra",  "7453",  "Jalna", "Mahendra Kacharu Sonwane", "NotGraduate",  " ","महाराष्ट्र",  "जलना", "महेंद्र कछारू सोनवणे", " "}, 
{ "Maharashtra",  "7454",  "Jalna", "Sapkal Lilabai Dharma", "NotGraduate",  " ","महाराष्ट्र",  "जलना", "सपकल लीलाबाई धर्म", " "}, 
{ "Maharashtra",  "7457",  "Jalna", "Sharadchandra Ganpatrao Wankhede", "CriminalCases",  " ","महाराष्ट्र",  "जलना", "शरदचंद्र गणपतराव वानखेड़े", " "}, 
{ "Maharashtra",  "7458",  "Jalna", "Uttam Dhanu Rathod", "OverAged",  " ","महाराष्ट्र",  "जलना", "उत्तम धनु राठौड़", " "}, 
{ "Maharashtra",  "7459",  "Jalna", "Ganesh Shankar Chandode", "CriminalCases",  " ","महाराष्ट्र",  "जलना", "गणेश शंकर चंदोडे", " "}, 
{ "Maharashtra",  "7460",  "Jalna", "Anita Lalchand Khandade (Rajput)", "NotGraduate",  " ","महाराष्ट्र",  "जलना", "अनीता लालचंद खांडडे (राजपूत)", " "}, 
{ "Maharashtra",  "7461",  "Jalna", "Ahemad Rahim Shaikh", "NotGraduate",  " ","महाराष्ट्र",  "जलना", "अहमद रहीम शेख", " "}, 
{ "Maharashtra",  "7462",  "Jalna", "Raju Ashok Gawali", "NotGraduate",  " ","महाराष्ट्र",  "जलना", "राजू अशोक गवली", " "}, 
{ "Maharashtra",  "7463",  "Jalna", "Shahadev Mahadev Palve", "CriminalCases",  " ","महाराष्ट्र",  "जलना", "शाहदेव महादेव पालवे", " "}, 
{ "Maharashtra",  "7464",  "Jalna", "Pramod Baburao Kharat", "NotGraduate",  " ","महाराष्ट्र",  "जलना", "प्रमोद बाबूराव खरात", " "}, 
{ "Maharashtra",  "4260",  "Jalna", "Autade Vilas Keshavrao", "ForeignFunding",  " ","महाराष्ट्र",  "जलना", "आत्देव विलास केशवराव", " "}, 
{ "Maharashtra",  "7618",  "Kolhapur", "Dundappa Kundappa Shrikant Sir", "OverAged",  " ","महाराष्ट्र",  "कोल्हापुर", "डंडप्पा कुंडप्पा श्रीकांत सर", " "}, 
{ "Maharashtra",  "7619",  "Kolhapur", "Dayanand Maruti Kamble", "NotGraduate",  " ","महाराष्ट्र",  "कोल्हापुर", "दयानंद मारुति कांबले", " "}, 
{ "Maharashtra",  "7621",  "Kolhapur", "Bajirao Sadashiv Naik", "CriminalCases",  " ","महाराष्ट्र",  "कोल्हापुर", "बाजीराव सदाशिव नाइक", " "}, 
{ "Maharashtra",  "7622",  "Kolhapur", "Mane Arvind Bhiva", "NotGraduate",  " ","महाराष्ट्र",  "कोल्हापुर", "माने अरविंद भीवा", " "}, 
{ "Maharashtra",  "7623",  "Kolhapur", "Rajendra Balaso Koli (Galatage)", "NotGraduate",  " ","महाराष्ट्र",  "कोल्हापुर", "राजेंद्र बालासो कोली (गैलाटेज)", " "}, 
{ "Maharashtra",  "7624",  "Kolhapur", "Sandeep Gundopant Sankpal", "NotGraduate",  " ","महाराष्ट्र",  "कोल्हापुर", "संदीप गुंडोपंत संकपाल", " "}, 
{ "Maharashtra",  "7625",  "Kolhapur", "Siddharth Abaso Nagaratna", "NotGraduate",  " ","महाराष्ट्र",  "कोल्हापुर", "सिद्धार्थ अबासो नगरताना", " "}, 
{ "Maharashtra",  "7626",  "Kolhapur", "Dhananjay Mahadik", "CriminalCases",  " ","महाराष्ट्र",  "कोल्हापुर", "धनंजय महादिक", " "}, 
{ "Maharashtra",  "7627",  "Kolhapur", "Aruna Mohan Mali", "CriminalCases",  " ","महाराष्ट्र",  "कोल्हापुर", "अरुणा मोहन माली", " "}, 
{ "Maharashtra",  "7628",  "Kolhapur", "Paresh Dattatray Bhosale", "NotGraduate",  " ","महाराष्ट्र",  "कोल्हापुर", "परेश दत्तात्रे भोसले", " "}, 
{ "Maharashtra",  "7629",  "Kolhapur", "Mulla Mushtak Ajij", "NotGraduate",  " ","महाराष्ट्र",  "कोल्हापुर", "मुल्ला मुश्तक अजिज", " "}, 
{ "Maharashtra",  "4347",  "Kolhapur", "Kisan Keraba Katkar", "NotGraduate",  " ","महाराष्ट्र",  "कोल्हापुर", "किसान केराबा कटकर", " "}, 
{ "Maharashtra",  "4323",  "Latur", "Madhukar Sambhaji Kamble", "OverAged",  " ","महाराष्ट्र",  "लातूर", "मधुकर संभाजी कांबले", " "}, 
{ "Maharashtra",  "4324",  "Latur", "Dattu Prabhakar Karanjikar", "NotGraduate",  " ","महाराष्ट्र",  "लातूर", "दत्तू प्रभाकर करंजिकर", " "}, 
{ "Maharashtra",  "4326",  "Latur", "Arun Ramrao Sontakke", "NotGraduate",  " ","महाराष्ट्र",  "लातूर", "अरुण रामराव सोंटाके", " "}, 
{ "Maharashtra",  "4327",  "Latur", "Kamant Machindra Gunaji", "ForeignFunding",  " ","महाराष्ट्र",  "लातूर", "कामंत मछिंद्र गुणाजी", " "}, 
{ "Maharashtra",  "4328",  "Latur", "Ramesh Nivrati Kambale", "NotGraduate",  " ","महाराष्ट्र",  "लातूर", "रमेश निवृति कांबले", " "}, 
{ "Maharashtra",  "4329",  "Latur", "Sudhakar Tukaram Shrangare", "ForeignFunding",  " ","महाराष्ट्र",  "लातूर", "सुधाकर तुकाराम श्रंगारे", " "}, 
{ "Maharashtra",  "4331",  "Latur", "Rupesh Shamrao Shanke", "NotGraduate",  " ","महाराष्ट्र",  "लातूर", "रूपेश शमराव शंके", " "}, 
{ "Maharashtra",  "4332",  "Latur", "Papita Raosaheb Randive", "NotGraduate",  " ","महाराष्ट्र",  "लातूर", "पापिता रावसाहेब रणदिवे", " "}, 
{ "Maharashtra",  "7557",  "Madha", "Sachin Dnyaneshwar Padalkar", "NotGraduate",  " ","महाराष्ट्र",  "माढा", "सचिन ज्ञानेश्वर पाडलकर", " "}, 
{ "Maharashtra",  "7558",  "Madha", "Annaso Sukhadev Maske", "CriminalCases",  " ","महाराष्ट्र",  "माढा", "अन्नसो सुखदेव मस्के", " "}, 
{ "Maharashtra",  "7559",  "Madha", "Nandu Sambhaji More", "CriminalCases",  " ","महाराष्ट्र",  "माढा", "नंदू संभाजी मोर", " "}, 
{ "Maharashtra",  "7561",  "Madha", "Sandip Janaradhan Kharat", "NotGraduate",  " ","महाराष्ट्र",  "माढा", "संदीप जनार्दन खरात", " "}, 
{ "Maharashtra",  "7562",  "Madha", "Navnath Bhimrao Patil", "CriminalCases",  " ","महाराष्ट्र",  "माढा", "नवनाथ भीमराव पाटिल", " "}, 
{ "Maharashtra",  "7563",  "Madha", "Ramdas Mane", "NotGraduate",  " ","महाराष्ट्र",  "माढा", "रामदास माने", " "}, 
{ "Maharashtra",  "7564",  "Madha", "Sanjaymama Vittalrao Shinde", "CriminalCases",  " ","महाराष्ट्र",  "माढा", "संजयम्मा विट्ठलराव शिंदे", " "}, 
{ "Maharashtra",  "7565",  "Madha", "Daulat Umaji Shitole", "NotGraduate",  " ","महाराष्ट्र",  "माढा", "दौलत उमाजी शिटोले", " "}, 
{ "Maharashtra",  "7566",  "Madha", "Vishvambhar Narayan Kashid", "CriminalCases",  " ","महाराष्ट्र",  "माढा", "विश्वम्भर नारायण काशिद", " "}, 
{ "Maharashtra",  "7567",  "Madha", "Dilip Ramchandra Jadhav", "NotGraduate",  " ","महाराष्ट्र",  "माढा", "दिलीप रामचंद्र जाधव", " "}, 
{ "Maharashtra",  "7568",  "Madha", "Shahajahan Paigmber Shaikh", "NotGraduate",  " ","महाराष्ट्र",  "माढा", "शाहजहां पैगम्बर शेख", " "}, 
{ "Maharashtra",  "7571",  "Madha", "Adv. Sachin Bhaskar Jore", "CriminalCases",  " ","महाराष्ट्र",  "माढा", "अभिभाषक। सचिन भास्कर जोरे", " "}, 
{ "Maharashtra",  "7572",  "Madha", "Savita Ankush Aiwle", "NotGraduate",  " ","महाराष्ट्र",  "माढा", "सविता अंकुश अिवले", " "}, 
{ "Maharashtra",  "7574",  "Madha", "Dattatrya Bhanudas Khatke Alias Bandunana Khatke", "NotGraduate",  " ","महाराष्ट्र",  "माढा", "दत्ताचार्य भानुदास खटके अलियास बंदुनाना खटके", " "}, 
{ "Maharashtra",  "7575",  "Madha", "Nanasaheb Ramhari Yadav", "NotGraduate",  " ","महाराष्ट्र",  "माढा", "नानासाहेब रामहरि यादव", " "}, 
{ "Maharashtra",  "7576",  "Madha", "Aappa Aaba Lokare", "NotGraduate",  " ","महाराष्ट्र",  "माढा", "आपा आब लोकरे", " "}, 
{ "Maharashtra",  "7577",  "Madha", "Vijayraj Balasaheb Mane Deshmukh", "NotGraduate",  " ","महाराष्ट्र",  "माढा", "विजयराज बालासाहेब माने देशमुख", " "}, 
{ "Maharashtra",  "7578",  "Madha", "Vijayrao More", "CriminalCases",  " ","महाराष्ट्र",  "माढा", "विजयराव मोरे", " "}, 
{ "Maharashtra",  "7579",  "Madha", "Ranjeetsinha Hindurao Naik Nimbalkar", "ForeignFunding",  " ","महाराष्ट्र",  "माढा", "रणजीतसिंह हिन्दुराव नाइक निंबालकर", " "}, 
{ "Maharashtra",  "7580",  "Madha", "Sunil Gunda Jadhav", "NotGraduate",  " ","महाराष्ट्र",  "माढा", "सुनील गुंडा जाधव", " "}, 
{ "Maharashtra",  "7581",  "Madha", "Sandip Vitthal Pol", "NotGraduate",  " ","महाराष्ट्र",  "माढा", "संदीप विठ्ठल पोल", " "}, 
{ "Maharashtra",  "7582",  "Madha", "Maruti Shivram Keskar", "CriminalCases",  " ","महाराष्ट्र",  "माढा", "मारुति शिवराम केसकर", " "}, 
{ "Maharashtra",  "7583",  "Madha", "Mohan Vishnu Raut", "CriminalCases",  " ","महाराष्ट्र",  "माढा", "मोहन विष्णु राउत", " "}, 
{ "Maharashtra",  "7584",  "Madha", "Bramhakumari Pramilaben", "CriminalCases",  " ","महाराष्ट्र",  "माढा", "ब्रम्हाकुमारी प्रमिलाबेन", " "}, 
{ "Maharashtra",  "7585",  "Madha", "Aware Siddheshwar Bharat", "CriminalCases",  " ","महाराष्ट्र",  "माढा", "अवध सिद्धेश्वर भारत", " "}, 
{ "Maharashtra",  "4116",  "Nagpur", "Vitthhal Nanaji Gaikwad", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "विट्ठल नानाजी गायकवाड़", " "}, 
{ "Maharashtra",  "4117",  "Nagpur", "Sachin Haridas Somkuwar", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "सचिन हरिदास सोमकुवार", " "}, 
{ "Maharashtra",  "4119",  "Nagpur", "Mohammad Jamal", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "मोहम्मद जमाल", " "}, 
{ "Maharashtra",  "4120",  "Nagpur", "Uday Rambhauji Borkar", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "उदय रामभाऊजी बोरकर", " "}, 
{ "Maharashtra",  "4121",  "Nagpur", "Prabhakar Krushnaji Satpaise", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "प्रभाकर कृष्णजी सतपाइस", " "}, 
{ "Maharashtra",  "4122",  "Nagpur", "Sahil Balchand Turkar", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "साहिल बालचंद तुर्क", " "}, 
{ "Maharashtra",  "4125",  "Nagpur", "Prafulla Manikchand Bhange", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "प्रफुल्ल मानिकचंद भंगे", " "}, 
{ "Maharashtra",  "4126",  "Nagpur", "Manoj Kothuji Bawane", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "मनोज कोठुजी बावने", " "}, 
{ "Maharashtra",  "4127",  "Nagpur", "Asim Ali", "CriminalCases",  " ","महाराष्ट्र",  "नागपुर", "असीम अली", " "}, 
{ "Maharashtra",  "4128",  "Nagpur", "Nitin Jairam Gadkari", "ForeignFunding",  " ","महाराष्ट्र",  "नागपुर", "नितिन जयराम गडकरी", " "}, 
{ "Maharashtra",  "4132",  "Nagpur", "Sunil Suryabhan Kawade", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "सुनील सूर्यभान कावड़े", " "}, 
{ "Maharashtra",  "4133",  "Nagpur", "Ruben Domnik Francis", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "रुबेन डोमनिक फ्रांसिस", " "}, 
{ "Maharashtra",  "4134",  "Nagpur", "Sachin Jagorao Patil", "CriminalCases",  " ","महाराष्ट्र",  "नागपुर", "सचिन जगोरो पाटिल", " "}, 
{ "Maharashtra",  "4135",  "Nagpur", "Kartik Gendalal Doke", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "कार्तिक गेंदालाल डोक", " "}, 
{ "Maharashtra",  "4138",  "Nagpur", "Gopalkumar Ganeshu Kashyap", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "गोपालकुमार गणेशु कश्यप", " "}, 
{ "Maharashtra",  "4140",  "Nagpur", "Comrade Yogesh Krishnarao Thakare", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "कामरेड योगेश कृष्णराव ठाकरे", " "}, 
{ "Maharashtra",  "4142",  "Nagpur", "Dipak Laxmanrao Maske", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "दिपक लक्ष्मणराव मासके", " "}, 
{ "Maharashtra",  "4143",  "Nagpur", "Nanabhau Falgunrao Patole", "ForeignFunding",  " ","महाराष्ट्र",  "नागपुर", "नानाभाऊ फाल्गुनराव पटोले", " "}, 
{ "Maharashtra",  "4145",  "Nagpur", "Vanita Jitendra Raut", "NotGraduate",  " ","महाराष्ट्र",  "नागपुर", "वनिता जितेंद्र राउत", " "}, 
{ "Maharashtra",  "4229",  "Nanded", "Abdul Samad", "NotGraduate",  " ","महाराष्ट्र",  "नांदेड़", "अब्दुल समद", " "}, 
{ "Maharashtra",  "4231",  "Nanded", "Ashok Shankarrao Chavan", "NotGraduate",  " ","महाराष्ट्र",  "नांदेड़", "अशोक शंकरराव चव्हाण", " "}, 
{ "Maharashtra",  "4233",  "Nanded", "Chikhalikar Pratap Govindrao", "ForeignFunding",  " ","महाराष्ट्र",  "नांदेड़", "चिखलीकर प्रताप गोविंदराव", " "}, 
{ "Maharashtra",  "4234",  "Nanded", "Ashokrao Shankarrao Chavan", "ForeignFunding",  " ","महाराष्ट्र",  "नांदेड़", "अशोकराव शंकरराव चव्हाण", " "}, 
{ "Maharashtra",  "4235",  "Nanded", "Abdul Rais Ahmed Abdul Jabbar", "CriminalCases",  " ","महाराष्ट्र",  "नांदेड़", "अब्दुल रईस अहमद अब्दुल जब्बार", " "}, 
{ "Maharashtra",  "4236",  "Nanded", "Mohan Anandrao Waghmare", "NotGraduate",  " ","महाराष्ट्र",  "नांदेड़", "मोहन आनंदराव वाघमारे", " "}, 
{ "Maharashtra",  "4237",  "Nanded", "Manish Dattatray Wadje", "NotGraduate",  " ","महाराष्ट्र",  "नांदेड़", "मनीष दत्तात्रे वडजे", " "}, 
{ "Maharashtra",  "4239",  "Nanded", "Madhavrao Sambhaji Gaikwad", "NotGraduate",  " ","महाराष्ट्र",  "नांदेड़", "माधवराव संभाजी गायकवाड़", " "}, 
{ "Maharashtra",  "4240",  "Nanded", "Sunil Manohar Sonsale", "NotGraduate",  " ","महाराष्ट्र",  "नांदेड़", "सुनील मनोहर सोंसले", " "}, 
{ "Maharashtra",  "4241",  "Nanded", "Kadam Shrirang Uttomrao", "NotGraduate",  " ","महाराष्ट्र",  "नांदेड़", "कदम श्रीरंग उत्तराव", " "}, 
{ "Maharashtra",  "4309",  "Osmanabad", "Tukaram Dasrao Gangawane", "OverAged",  " ","महाराष्ट्र",  "उस्मानाबाद", "तुकाराम दासराव गंगावने", " "}, 
{ "Maharashtra",  "4310",  "Osmanabad", "Deepak Mahadev Tate", "NotGraduate",  " ","महाराष्ट्र",  "उस्मानाबाद", "दीपक महादेव टेटे", " "}, 
{ "Maharashtra",  "4312",  "Osmanabad", "Dr.Vasant Raghunath Munde", "OverAged",  " ","महाराष्ट्र",  "उस्मानाबाद", "डॉ.वसंत रघुनाथ मुंडे", " "}, 
{ "Maharashtra",  "4314",  "Osmanabad", "Omprakash Bhupalsinh Alias Pavan Rajenimbalkar", "CriminalCases",  " ","महाराष्ट्र",  "उस्मानाबाद", "ओमप्रकाश भूपालसिंह उर्फ पवन राजनिंबालकर", " "}, 
{ "Maharashtra",  "4315",  "Osmanabad", "Sayyad Sultan Ladkhan", "NotGraduate",  " ","महाराष्ट्र",  "उस्मानाबाद", "सैय्यद सुल्तान लद्दाखान", " "}, 
{ "Maharashtra",  "4317",  "Osmanabad", "Arjun (Dada) Salgar", "CriminalCases",  " ","महाराष्ट्र",  "उस्मानाबाद", "अर्जुन (दादा) सालगर", " "}, 
{ "Maharashtra",  "4318",  "Osmanabad", "Ranajagjitsinha Padmasinh Patil", "CriminalCases",  " ","महाराष्ट्र",  "उस्मानाबाद", "रणजगजीतसिंह पद्मसिंह पाटिल", " "}, 
{ "Maharashtra",  "4319",  "Osmanabad", "Annasaheb Ramchandra Rathod", "CriminalCases",  " ","महाराष्ट्र",  "उस्मानाबाद", "अन्नासाहेब रामचंद्र राठौड़", " "}, 
{ "Maharashtra",  "4320",  "Osmanabad", "Phulsure Vishwanth Sadashiv", "OverAged",  " ","महाराष्ट्र",  "उस्मानाबाद", "स्फुरित विश्वनाथ सदाशिव", " "}, 
{ "Maharashtra",  "4321",  "Osmanabad", "Gore Netaji Nagnathrao", "CriminalCases",  " ","महाराष्ट्र",  "उस्मानाबाद", "गोरे नेताजी नागनाथराव", " "}, 
{ "Maharashtra",  "4243",  "Parbhani", "Kishor Namdeo Gaware", "NotGraduate",  " ","महाराष्ट्र",  "परभनी", "किशोर नामदेव गावरे", " "}, 
{ "Maharashtra",  "4244",  "Parbhani", "Kishor Baburao Munnemanik", "NotGraduate",  " ","महाराष्ट्र",  "परभनी", "किशोर बाबूराव मुनीमनिक", " "}, 
{ "Maharashtra",  "4248",  "Parbhani", "Govind Ramrao Deshmukh", "CriminalCases",  " ","महाराष्ट्र",  "परभनी", "गोविंद रामराव देशमुख", " "}, 
{ "Maharashtra",  "4249",  "Parbhani", "Rajan Ramchandra Kshirsagar", "CriminalCases",  " ","महाराष्ट्र",  "परभनी", "राजन रामचंद्र क्षीरसागर", " "}, 
{ "Maharashtra",  "4251",  "Parbhani", "Subhash Ashokrao Ambhore (Dudhgaonkar)", "NotGraduate",  " ","महाराष्ट्र",  "परभनी", "सुभाष अशोकराव अंबोरे (दुधगांवकर)", " "}, 
{ "Maharashtra",  "4252",  "Parbhani", "Alamgir Mohammad Khan", "CriminalCases",  " ","महाराष्ट्र",  "परभनी", "आलमगीर मोहम्मद खान", " "}, 
{ "Maharashtra",  "4253",  "Parbhani", "Dr.Vaijnath Sitaram Phad", "CriminalCases",  " ","महाराष्ट्र",  "परभनी", "डॉ.वैजनाथ सीताराम फड़", " "}, 
{ "Maharashtra",  "4254",  "Parbhani", "Shaikh Salim Shaikh Ibrahim", "NotGraduate",  " ","महाराष्ट्र",  "परभनी", "शेख सलीम शेख इब्राहिम", " "}, 
{ "Maharashtra",  "4257",  "Parbhani", "Uttamrao Pandurangrao Rathod", "OverAged",  " ","महाराष्ट्र",  "परभनी", "उत्तमराव पांडुरंगराव राठौड़", " "}, 
{ "Maharashtra",  "4258",  "Parbhani", "Sangita Kalyanrao Nirmal", "NotGraduate",  " ","महाराष्ट्र",  "परभनी", "संगिता कल्याणराव निर्मल", " "}, 
{ "Maharashtra",  "4259",  "Parbhani", "Jadhav Sanjay (Bandu) Haribhau", "CriminalCases",  " ","महाराष्ट्र",  "परभनी", "जाधव संजय (बंधु) हरिभाऊ", " "}, 
{ "Maharashtra",  "7501",  "Pune", "Javed Shabbir Sayyed", "NotGraduate",  " ","महाराष्ट्र",  "पुणे", "जावेद शब्बीर सैय्यद", " "}, 
{ "Maharashtra",  "7504",  "Pune", "Jafar Khursid Choudhari", "NotGraduate",  " ","महाराष्ट्र",  "पुणे", "जाफर खुर्शीद चौधरी", " "}, 
{ "Maharashtra",  "7508",  "Pune", "Chincholikar Jayant Eknath", "CriminalCases",  " ","महाराष्ट्र",  "पुणे", "चिंचोलिकर जयंत एकनाथ", " "}, 
{ "Maharashtra",  "7510",  "Pune", "Rakesh Prabhakar Chavan", "NotGraduate",  " ","महाराष्ट्र",  "पुणे", "राकेश प्रभाकर चव्हाण", " "}, 
{ "Maharashtra",  "7511",  "Pune", "Anand Prakash Vanjape", "NotGraduate",  " ","महाराष्ट्र",  "पुणे", "आनंद प्रकाश वंजपे", " "}, 
{ "Maharashtra",  "7514",  "Pune", "Uttam Pandurang Shinde", "CriminalCases",  " ","महाराष्ट्र",  "पुणे", "उत्तम पांडुरंग शिंदे", " "}, 
{ "Maharashtra",  "7516",  "Pune", "Rajesh Surendrakumar Agarwal", "CriminalCases",  " ","महाराष्ट्र",  "पुणे", "राजेश सुरेन्द्रकुमार अग्रवाल", " "}, 
{ "Maharashtra",  "7517",  "Pune", "Johnson Vasant Kolhapure", "NotGraduate",  " ","महाराष्ट्र",  "पुणे", "जॉनसन वसंत कोल्हापुरे", " "}, 
{ "Maharashtra",  "7519",  "Pune", "Jadhav Anil Narayan", "CriminalCases",  " ","महाराष्ट्र",  "पुणे", "जाधव अनिल नारायण", " "}, 
{ "Maharashtra",  "7520",  "Pune", "Hemant Baburao Kolekar Patil Alias Hemant Patil", "CriminalCases",  " ","महाराष्ट्र",  "पुणे", "हेमंत बाबूराव कोलेकर पाटिल उर्फ हेमंत पाटिल", " "}, 
{ "Maharashtra",  "7522",  "Pune", "Ravindra Bansiram Mahapure", "NotGraduate",  " ","महाराष्ट्र",  "पुणे", "रवींद्र बंसीराम महापुरे", " "}, 
{ "Maharashtra",  "7524",  "Pune", "Sanjay Baburao Jadhav", "NotGraduate",  " ","महाराष्ट्र",  "पुणे", "संजय बाबूराव जाधव", " "}, 
{ "Maharashtra",  "7525",  "Pune", "Girish Bhalchandra Bapat", "ForeignFunding",  " ","महाराष्ट्र",  "पुणे", "गिरीश भालचंद्र बापट", " "}, 
{ "Maharashtra",  "7526",  "Pune", "Amol Alias Yabes S. Tujare", "CriminalCases",  " ","महाराष्ट्र",  "पुणे", "अमोल अलियास यबेस एस तुजारे", " "}, 
{ "Maharashtra",  "4262",  "Pune", "Mohan Ramkisan Joshi", "ForeignFunding",  " ","महाराष्ट्र",  "पुणे", "मोहन रामकिसन जोशी", " "}, 
{ "Maharashtra",  "4263",  "Pune", "Suhas Popat Gajarmal", "NotGraduate",  " ","महाराष्ट्र",  "पुणे", "सुहास पोपट गजरमल", " "}, 
{ "Maharashtra",  "4264",  "Pune", "Chandrakant Parmeshwar Sawant", "NotGraduate",  " ","महाराष्ट्र",  "पुणे", "चंद्रकांत परमेश्वर सावंत", " "}, 
{ "Maharashtra",  "7487",  "Raigad", "Sunil Pandurang Tatkare", "NotGraduate",  " ","महाराष्ट्र",  "रायगढ़", "सुनील पांडुरंग तटकरे", " "}, 
{ "Maharashtra",  "7488",  "Raigad", "Subhash Janardan Patil", "NotGraduate",  " ","महाराष्ट्र",  "रायगढ़", "सुभाष जनार्दन पाटिल", " "}, 
{ "Maharashtra",  "7489",  "Raigad", "Yogesh Kadam", "NotGraduate",  " ","महाराष्ट्र",  "रायगढ़", "योगेश कदम", " "}, 
{ "Maharashtra",  "7490",  "Raigad", "Suman Bhaskar Koli", "NotGraduate",  " ","महाराष्ट्र",  "रायगढ़", "सुमन भास्कर कोली", " "}, 
{ "Maharashtra",  "7491",  "Raigad", "Ghag Sanjay Arjun", "CriminalCases",  " ","महाराष्ट्र",  "रायगढ़", "घुग संजय अर्जुन", " "}, 
{ "Maharashtra",  "7493",  "Raigad", "Anant Gangaram Geete", "OverAged",  " ","महाराष्ट्र",  "रायगढ़", "अनंत गंगाराम गीते", " "}, 
{ "Maharashtra",  "7494",  "Raigad", "Avinash Vasant Patil", "NotGraduate",  " ","महाराष्ट्र",  "रायगढ़", "अविनाश वसंत पाटिल", " "}, 
{ "Maharashtra",  "7495",  "Raigad", "Tatkare Sunil Dattatray", "NotGraduate",  " ","महाराष्ट्र",  "रायगढ़", "तटकरे सुनील दत्तात्रय", " "}, 
{ "Maharashtra",  "7496",  "Raigad", "Munafar Jainubhidin Choudhary", "NotGraduate",  " ","महाराष्ट्र",  "रायगढ़", "मुनफ़र जैनुभिदीन चौधरी", " "}, 
{ "Maharashtra",  "7497",  "Raigad", "Nathuram Bhaguram Hate", "NotGraduate",  " ","महाराष्ट्र",  "रायगढ़", "नाथूराम भागुराम हते", " "}, 
{ "Maharashtra",  "7498",  "Raigad", "Gajendra Parshuram Turbadkar", "NotGraduate",  " ","महाराष्ट्र",  "रायगढ़", "गजेन्द्र परशुराम तुर्बडकर", " "}, 
{ "Maharashtra",  "7499",  "Raigad", "Madhukar Mahadev Khamkar", "NotGraduate",  " ","महाराष्ट्र",  "रायगढ़", "मधुकर महादेव खामकर", " "}, 
{ "Maharashtra",  "7500",  "Raigad", "Sunil Sakharam Tatkare", "NotGraduate",  " ","महाराष्ट्र",  "रायगढ़", "सुनील सखाराम तटकरे", " "}, 
{ "Maharashtra",  "4261",  "Raigad", "Milind Bhaguram Salvi", "CriminalCases",  " ","महाराष्ट्र",  "रायगढ़", "मिलिंद भागुराम सालवी", " "}, 
{ "Maharashtra",  "4101",  "Ramtek", "Archana Chandrakumar Ukey", "NotGraduate",  " ","महाराष्ट्र",  "रामटेक", "अर्चना चंद्रकुमार उके", " "}, 
{ "Maharashtra",  "4102",  "Ramtek", "Subhash Dharmdas Gajbhiye", "NotGraduate",  " ","महाराष्ट्र",  "रामटेक", "सुभाष धर्मदास गजभिये", " "}, 
{ "Maharashtra",  "4103",  "Ramtek", "Bandu Ramchandra Meshram", "NotGraduate",  " ","महाराष्ट्र",  "रामटेक", "बंदु रामचंद्र मेश्राम", " "}, 
{ "Maharashtra",  "4104",  "Ramtek", "Vinod Bhiwaji Patil", "NotGraduate",  " ","महाराष्ट्र",  "रामटेक", "विनोद भीवाजी पाटिल", " "}, 
{ "Maharashtra",  "4105",  "Ramtek", "Anil Mahadeo Dhone", "NotGraduate",  " ","महाराष्ट्र",  "रामटेक", "अनिल महादेव धोन", " "}, 
{ "Maharashtra",  "4106",  "Ramtek", "Kanteshwar Khushalji Tumane", "NotGraduate",  " ","महाराष्ट्र",  "रामटेक", "कांतेश्वर खुशालजी तुमने", " "}, 
{ "Maharashtra",  "4107",  "Ramtek", "Chandrabhan Baliram Ramteke", "NotGraduate",  " ","महाराष्ट्र",  "रामटेक", "चंद्रभान बलिराम रामटेके", " "}, 
{ "Maharashtra",  "4108",  "Ramtek", "Kiran Premkumar Rodge", "NotGraduate",  " ","महाराष्ट्र",  "रामटेक", "किरण प्रेमकुमार लॉज", " "}, 
{ "Maharashtra",  "4109",  "Ramtek", "Shailesh Sambhaji Janbandhu", "NotGraduate",  " ","महाराष्ट्र",  "रामटेक", "शैलेश संभाजी जनबंधु", " "}, 
{ "Maharashtra",  "4112",  "Ramtek", "Sandesh Bhioram Bhalekar", "OverAged",  " ","महाराष्ट्र",  "रामटेक", "संध्या भीयाराम भालेकर", " "}, 
{ "Maharashtra",  "4113",  "Ramtek", "Kishore Uttamrao Gajbhiye", "ForeignFunding",  " ","महाराष्ट्र",  "रामटेक", "किशोर उत्तमराव गजभिये", " "}, 
{ "Maharashtra",  "4114",  "Ramtek", "Natthu Madhav Lokhande", "OverAged",  " ","महाराष्ट्र",  "रामटेक", "नत्थू माधव लोखंडे", " "}, 
{ "Maharashtra",  "4115",  "Ramtek", "Gautam Shriram Wasnik", "NotGraduate",  " ","महाराष्ट्र",  "रामटेक", "गौतम श्रीराम वासनिक", " "}, 
{ "Maharashtra",  "7607",  "Ratnagiri Sindhudurg", "Maruti Ramchandra Joshi", "OverAged",  " ","महाराष्ट्र",  "रत्नागिरी-सिंधुदुर्ग", "मारुति रामचंद्र जोशी", " "}, 
{ "Maharashtra",  "7609",  "Ratnagiri Sindhudurg", "Vinayak Bhaurao Raut", "CriminalCases",  " ","महाराष्ट्र",  "रत्नागिरी-सिंधुदुर्ग", "विनायक भाउराव राउत", " "}, 
{ "Maharashtra",  "7610",  "Ratnagiri Sindhudurg", "Kishor Sidu Varak", "CriminalCases",  " ","महाराष्ट्र",  "रत्नागिरी-सिंधुदुर्ग", "किशोर सिद्दू वरक", " "}, 
{ "Maharashtra",  "7611",  "Ratnagiri Sindhudurg", "Amberkar Pandharinath Vidyadhar", "CriminalCases",  " ","महाराष्ट्र",  "रत्नागिरी-सिंधुदुर्ग", "अम्बरकर पंढरीनाथ विद्याधर", " "}, 
{ "Maharashtra",  "7614",  "Ratnagiri Sindhudurg", "Nilesh Narayan Rane", "CriminalCases",  " ","महाराष्ट्र",  "रत्नागिरी-सिंधुदुर्ग", "नीलेश नारायण राणे", " "}, 
{ "Maharashtra",  "7615",  "Ratnagiri Sindhudurg", "Vinayak Lavu Raut", "CriminalCases",  " ","महाराष्ट्र",  "रत्नागिरी-सिंधुदुर्ग", "विनायक लावु राउत", " "}, 
{ "Maharashtra",  "7616",  "Ratnagiri Sindhudurg", "Navinchandra Bhalchandra Bandivadekar", "ForeignFunding",  " ","महाराष्ट्र",  "रत्नागिरी-सिंधुदुर्ग", "नवीनचंद्र भालचंद्र बांदीवडेकर", " "}, 
{ "Maharashtra",  "7435",  "Raver", "Madhukar Sopan Patil", "OverAged",  " ","महाराष्ट्र",  "रावेर", "मधुकर सोपान पाटिल", " "}, 
{ "Maharashtra",  "7436",  "Raver", "Nitin Pralhad Kandelkar", "NotGraduate",  " ","महाराष्ट्र",  "रावेर", "नितिन प्रल्हाद कंडेलकर", " "}, 
{ "Maharashtra",  "7437",  "Raver", "Khadse Raksha Nikhil", "ForeignFunding",  " ","महाराष्ट्र",  "रावेर", "खडसे रक्षा निखिल", " "}, 
{ "Maharashtra",  "7438",  "Raver", "Nazmin Shaikh Ramjan", "NotGraduate",  " ","महाराष्ट्र",  "रावेर", "नाजमीन शेख रमजान", " "}, 
{ "Maharashtra",  "7439",  "Raver", "Adakmol Rohidas Ramesh", "NotGraduate",  " ","महाराष्ट्र",  "रावेर", "आदकमोल रोहिदास रमेश", " "}, 
{ "Maharashtra",  "7440",  "Raver", "Gaurav Damodar Surwade", "NotGraduate",  " ","महाराष्ट्र",  "रावेर", "गौरव दामोदर सूरवाडे", " "}, 
{ "Maharashtra",  "7441",  "Raver", "Dr.Ulhas Vasudeo Patil", "ForeignFunding",  " ","महाराष्ट्र",  "रावेर", "डॉ। उल्हास वासुदेव पाटिल", " "}, 
{ "Maharashtra",  "7442",  "Raver", "Tawar Vijay Jagan", "NotGraduate",  " ","महाराष्ट्र",  "रावेर", "तवर विजय जगन", " "}, 
{ "Maharashtra",  "7443",  "Raver", "D. D. Wani [Photographer]", "NotGraduate",  " ","महाराष्ट्र",  "रावेर", "डीडी वानी [फोटोग्राफर]", " "}, 
{ "Maharashtra",  "7444",  "Raver", "Yogendra Viththal Kolate", "CriminalCases",  " ","महाराष्ट्र",  "रावेर", "योगेन्द्र विठ्ठल कोलायत", " "}, 
{ "Maharashtra",  "7445",  "Raver", "Roshan Aara Sadique Ali", "NotGraduate",  " ","महाराष्ट्र",  "रावेर", "रोशन आरा सादिक अली", " "}, 
{ "Maharashtra",  "7446",  "Raver", "Ajit Namdar Tadvi", "NotGraduate",  " ","महाराष्ट्र",  "रावेर", "अजीत नामदार तडवी", " "}, 
{ "Maharashtra",  "7586",  "Sangli", "Patil Vishal Prakashrao", "CriminalCases",  " ","महाराष्ट्र",  "सांगली", "पाटिल विशाल प्रकाशराव", " "}, 
{ "Maharashtra",  "7588",  "Sangli", "Bhaktraj Raghunath Thigale", "NotGraduate",  " ","महाराष्ट्र",  "सांगली", "भक्तराज रघुनाथ थिगले", " "}, 
{ "Maharashtra",  "7589",  "Sangli", "Nalage Ananda Shankar", "CriminalCases",  " ","महाराष्ट्र",  "सांगली", "नलज आनंद शंकर", " "}, 
{ "Maharashtra",  "7590",  "Sangli", "Gopichand Kundlik Padalkar", "CriminalCases",  " ","महाराष्ट्र",  "सांगली", "गोपीचंद कुंडलिक पादालकर", " "}, 
{ "Maharashtra",  "7591",  "Sangli", "Abhijit Vamanrao Awade-Bichukle", "CriminalCases",  " ","महाराष्ट्र",  "सांगली", "अभिजीत वामनराव अवाडे-बिचुकले", " "}, 
{ "Maharashtra",  "7592",  "Sangli", "Sanjay Ramchandra Patil", "ForeignFunding",  " ","महाराष्ट्र",  "सांगली", "संजय रामचंद्र पाटिल", " "}, 
{ "Maharashtra",  "7593",  "Sangli", "Shankar Martand Mane", "CriminalCases",  " ","महाराष्ट्र",  "सांगली", "शंकर मार्तंड माने", " "}, 
{ "Maharashtra",  "7594",  "Sangli", "Dattatray Pandit Patil", "NotGraduate",  " ","महाराष्ट्र",  "सांगली", "दत्तात्रय पंडित पाटिल", " "}, 
{ "Maharashtra",  "7595",  "Sangli", "Narayan Chandar Mulik", "CriminalCases",  " ","महाराष्ट्र",  "सांगली", "नारायण चंदर मुलिक", " "}, 
{ "Maharashtra",  "7596",  "Sangli", "Himmat Pandurang Koli", "CriminalCases",  " ","महाराष्ट्र",  "सांगली", "हिम्मत पांडुरंग कोली", " "}, 
{ "Maharashtra",  "7597",  "Sangli", "Adhik Sampat Channe", "CriminalCases",  " ","महाराष्ट्र",  "सांगली", "आदिक संपत चने", " "}, 
{ "Maharashtra",  "7598",  "Satara", "Panjabrao Mahadev Patil", "CriminalCases",  " ","महाराष्ट्र",  "सतारा", "पंजरावराव महादेव पाटिल", " "}, 
{ "Maharashtra",  "7600",  "Satara", "Sagar Sharad Bhise", "CriminalCases",  " ","महाराष्ट्र",  "सतारा", "सागर शरद भिसे", " "}, 
{ "Maharashtra",  "7601",  "Satara", "Bhonsle Shrimant Chhatrapati Udayanraje Pratapasinh Maharaj", "CriminalCases",  " ","महाराष्ट्र",  "सतारा", "भोंसले श्रीमंत छत्रपति उदयनराजे प्रतापसिंह महाराज", " "}, 
{ "Maharashtra",  "7604",  "Satara", "Abhijit Wamanrao -Bichukale", "CriminalCases",  " ","महाराष्ट्र",  "सतारा", "अभिजीत वामनराव -बिचुकले", " "}, 
{ "Maharashtra",  "7605",  "Satara", "Narendra Annasaheb Patil", "CriminalCases",  " ","महाराष्ट्र",  "सतारा", "नरेंद्र अन्नासाहेब पाटिल", " "}, 
{ "Maharashtra",  "4335",  "Solapur", "Shri. Sha. Bra. Dr. Jay Siddeshwar Shivachrya Mahaswamiji", "ForeignFunding",  " ","महाराष्ट्र",  "सोलापुर", "श्री। शा। ब्रा। डॉ। जय सिद्धेश्वर शिवाचार्य महास्वामीजी", " "}, 
{ "Maharashtra",  "4337",  "Solapur", "Shri Maske Shrimant Murlidhar", "NotGraduate",  " ","महाराष्ट्र",  "सोलापुर", "श्री मस्के श्रीमंत मुरलीधर", " "}, 
{ "Maharashtra",  "4339",  "Solapur", "Shri Bhise Krishna Nagnath", "NotGraduate",  " ","महाराष्ट्र",  "सोलापुर", "श्री भिसे कृष्ण नागनाथ", " "}, 
{ "Maharashtra",  "4341",  "Solapur", "Shri Shinde Sushilkumar Sambhajirao", "ForeignFunding",  " ","महाराष्ट्र",  "सोलापुर", "श्री शिंदे सुशीलकुमार संभाजीराव", " "}, 
{ "Maharashtra",  "4342",  "Solapur", "Shri Ashok Bhagavan Ughade", "OverAged",  " ","महाराष्ट्र",  "सोलापुर", "श्री अशोक भगवान औघड़े", " "}, 
{ "Maharashtra",  "4343",  "Solapur", "Shri Khandare Sudarshan Raychand", "NotGraduate",  " ","महाराष्ट्र",  "सोलापुर", "श्री खंडारे सुदर्शन रायचंद", " "}, 
{ "Maharashtra",  "4345",  "Solapur", "Shri Patole Malhari Gulab", "OverAged",  " ","महाराष्ट्र",  "सोलापुर", "श्री पटोले मल्हारी गुलाब", " "}, 
{ "Maharashtra",  "4096",  "Wardha", "Dnyaneshwar Laxamnrao Wakudkar", "CriminalCases",  " ","महाराष्ट्र",  "वर्धा", "ज्ञानेश्वर लक्ष्मणराव वकुडकर", " "}, 
{ "Maharashtra",  "4097",  "Wardha", "Shaileshkumar Premkishorji Agrawal", "CriminalCases",  " ","महाराष्ट्र",  "वर्धा", "शैलेशकुमार प्रेमकिशोरजी अग्रवाल", " "}, 
{ "Maharashtra",  "4086",  "Wardha", "Charulata Khajansing Tokas", "ForeignFunding",  " ","महाराष्ट्र",  "वर्धा", "चारुलता खजानसिंग टोकस", " "}, 
{ "Maharashtra",  "4088",  "Wardha", "Ramdas Chandrabhanji Tadas", "ForeignFunding",  " ","महाराष्ट्र",  "वर्धा", "रामदास चंद्रभानजी तदास", " "}, 
{ "Maharashtra",  "4089",  "Wardha", "Gadhave Pravin Rameshwarrao", "NotGraduate",  " ","महाराष्ट्र",  "वर्धा", "गधवे प्रवीण रामेश्वरो", " "}, 
{ "Maharashtra",  "4090",  "Wardha", "Umesh Sadashiv Neware", "NotGraduate",  " ","महाराष्ट्र",  "वर्धा", "उमेश सदाशिव नवारे", " "}, 
{ "Maharashtra",  "4091",  "Wardha", "Dhanraj Kotiram Vanjari", "CriminalCases",  " ","महाराष्ट्र",  "वर्धा", "धनराज कोटिराम वंजारी", " "}, 
{ "Maharashtra",  "4092",  "Wardha", "Arvind Shamrao Lillore", "NotGraduate",  " ","महाराष्ट्र",  "वर्धा", "अरविंद शामराव लिलोरे", " "}, 
{ "Maharashtra",  "4093",  "Wardha", "Jagdish Uddhavrao Wankhede", "NotGraduate",  " ","महाराष्ट्र",  "वर्धा", "जगदीश उद्धवराव वानखेड़े", " "}, 
{ "Maharashtra",  "4094",  "Wardha", "Nandkishor Ramaji Sagar", "CriminalCases",  " ","महाराष्ट्र",  "वर्धा", "नंदकिशोर रामजी सागर", " "}, 
{ "Maharashtra",  "4095",  "Wardha", "Ganesh Kisanrao Lade", "NotGraduate",  " ","महाराष्ट्र",  "वर्धा", "गणेश किशनराव लाडे", " "}, 
{ "Maharashtra",  "7937",  "Yavatmal Washim", "Thakre Manikrao Govindrao", "ForeignFunding",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "ठाकरे मणिकराव गोविंदराव", " "}, 
{ "Maharashtra",  "7938",  "Yavatmal Washim", "Noorali Maheboob Ali Shah", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "नूरली महबूब अली शाह", " "}, 
{ "Maharashtra",  "7939",  "Yavatmal Washim", "Sameer Arunrao Deshpande", "OverAged",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "समीर अरुणराव देशपांडे", " "}, 
{ "Maharashtra",  "7940",  "Yavatmal Washim", "Rajesh Bhauraoji Raut", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "राजेश भाऊरावजी राउत", " "}, 
{ "Maharashtra",  "7941",  "Yavatmal Washim", "Shaikh Javed Shaikh Mushtaq", "CriminalCases",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "शेख जावेद शेख मुश्ताक", " "}, 
{ "Maharashtra",  "7942",  "Yavatmal Washim", "Vaishali Sudhakar Yede", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "वैशाली सुधाकर येड", " "}, 
{ "Maharashtra",  "7944",  "Yavatmal Washim", "Premasai Maharaj", "CriminalCases",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "प्रेमासई महाराज", " "}, 
{ "Maharashtra",  "7947",  "Yavatmal Washim", "Ravi Sampatrao Jadhao", "OverAged",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "रवि संपतराव जादो", " "}, 
{ "Maharashtra",  "7948",  "Yavatmal Washim", "Bhavana Pundlikrao Gawali", "CriminalCases",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "भावना पुंडलीकराव गवली", " "}, 
{ "Maharashtra",  "7949",  "Yavatmal Washim", "Naresh Mahadev Ghughane", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "नरेश महादेव घुघाने", " "}, 
{ "Maharashtra",  "7950",  "Yavatmal Washim", "Purushottam Domaji Bhajghaware", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "पुरुषोत्तम दोमाजी भजगावारे", " "}, 
{ "Maharashtra",  "7951",  "Yavatmal Washim", "Salim Shah Suleman Shah", "CriminalCases",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "सलीम शाह सुलेमान शाह", " "}, 
{ "Maharashtra",  "7953",  "Yavatmal Washim", "Pawar Ramesh Gorsing", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "पवार रमेश गोर्शिंग", " "}, 
{ "Maharashtra",  "7954",  "Yavatmal Washim", "Ramrao Sawai Pawar", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "रामराव सवाई पवार", " "}, 
{ "Maharashtra",  "7934",  "Yavatmal Washim", "Pundlik Baliram Rathod", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "पुंडलीक बलिराम राठौड़", " "}, 
{ "Maharashtra",  "4179",  "Yavatmal-Washim", "Thakre Manikrao Govindrao", "ForeignFunding",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "ठाकरे मणिकराव गोविंदराव", " "}, 
{ "Maharashtra",  "4180",  "Yavatmal-Washim", "Noorali Maheboob Ali Shah", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "नूरली महबूब अली शाह", " "}, 
{ "Maharashtra",  "4182",  "Yavatmal-Washim", "Bhavana Pundlikrao Gawali", "CriminalCases",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "भावना पुंडलीकराव गवली", " "}, 
{ "Maharashtra",  "4184",  "Yavatmal-Washim", "Ramrao Sawai Pawar", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "रामराव सवाई पवार", " "}, 
{ "Maharashtra",  "4186",  "Yavatmal-Washim", "Vaishali Sudhakar Yede", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "वैशाली सुधाकर येड", " "}, 
{ "Maharashtra",  "4189",  "Yavatmal-Washim", "Shaikh Javed Shaikh Mushtaq", "CriminalCases",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "शेख जावेद शेख मुश्ताक", " "}, 
{ "Maharashtra",  "4190",  "Yavatmal-Washim", "Pundlik Baliram Rathod", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "पुंडलीक बलिराम राठौड़", " "}, 
{ "Maharashtra",  "4191",  "Yavatmal-Washim", "Sameer Arunrao Deshpande", "OverAged",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "समीर अरुणराव देशपांडे", " "}, 
{ "Maharashtra",  "4194",  "Yavatmal-Washim", "Ravi Sampatrao Jadhao", "OverAged",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "रवि संपतराव जादो", " "}, 
{ "Maharashtra",  "4195",  "Yavatmal-Washim", "Premasai Maharaj", "CriminalCases",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "प्रेमासई महाराज", " "}, 
{ "Maharashtra",  "4196",  "Yavatmal-Washim", "Rajesh Bhauraoji Raut", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "राजेश भाऊरावजी राउत", " "}, 
{ "Maharashtra",  "4197",  "Yavatmal-Washim", "Pawar Ramesh Gorsing", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "पवार रमेश गोर्शिंग", " "}, 
{ "Maharashtra",  "4198",  "Yavatmal-Washim", "Purushottam Domaji Bhajghaware", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "पुरुषोत्तम दोमाजी भजगावारे", " "}, 
{ "Maharashtra",  "4199",  "Yavatmal-Washim", "Salim Shah Suleman Shah", "CriminalCases",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "सलीम शाह सुलेमान शाह", " "}, 
{ "Maharashtra",  "4200",  "Yavatmal-Washim", "Naresh Mahadev Ghughane", "NotGraduate",  " ","महाराष्ट्र",  "यवतमाल-वाशिम", "नरेश महादेव घुघाने", " "}, 
};

}