/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Odisha {
public static final String[][] green_bucket = {
        {"Odisha", "Aska", "Sankar Sahu", "Communist Party of India (Marxist–Leninist) Red Star", "5.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4969", "ओडिशा", "अस्का", "शंकर साहू", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) रेड स्टार"},
        {"Odisha", "Aska", "Purna Chandra Nayak", "Bahujan Samaj Party", "20000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5872", "ओडिशा", "अस्का", "पूर्ण चंद्र नायक", "बहुजन समाज पार्टी"},
        {"Odisha", "Balasore", "Mohammed Alli", "Ambedkar National Congress", "2.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9923", "ओडिशा", "बालासोर", "मोहम्मद अल्ली", "अंबेडकर राष्ट्रीय कांग्रेस"},
        {"Odisha", "Balasore", "Ramakanta Panda", "Purvanchal Janta Party (Secular)", "27Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9917", "ओडिशा", "बालासोर", "रमाकांत पांडा", "पूर्वांचल जनता पार्टी (सेक्युलर)"},
        {"Odisha", "Balasore", "Haji Sk Abdul Istar", "All India Trinamool Congress", "25.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9921", "ओडिशा", "बालासोर", "हाजी स्क अब्दुल इस्टार", "अखिल भारतीय तृणमूल कांग्रेस"},
        {"Odisha", "Balasore", "Jagannath Das", "Independent", "11.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9920", "ओडिशा", "बालासोर", "जगन्नाथ दास", "निर्दलीय"},
        {"Odisha", "Balasore", "Jadunath Sethi", "Independent", "30.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9919", "ओडिशा", "बालासोर", "जदुनाथ सेठी", "निर्दलीय"},
        {"Odisha", "Balasore", "Subhash", "Pragatishil Samajwadi Party (Lohia)", "7000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9924", "ओडिशा", "बालासोर", "सुभाष", "प्रगति समाजवादी पार्टी (लोहिया)"},
        {"Odisha", "Balasore", "Saroj Kumar Panda", "Independent", "2.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9914", "ओडिशा", "बालासोर", "सरोज कुमार पंडा", "निर्दलीय"},
        {"Odisha", "Bargarh", "Kousika Suna", "Bahujan Samaj Party", "10Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5875", "ओडिशा", "बारगढ़", "कौसिक सुनय", "बहुजन समाज पार्टी"},
        {"Odisha", "Berhampur", "Tirupati Rao Karanam", "Bahujan Samaj Party", "9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5550", "ओडिशा", "बेरहामपुर", "तिरुपति राव करणम", "बहुजन समाज पार्टी"},
        {"Odisha", "Berhampur", "Somanath Behera", "Socialist Unity Centre of India (Communist)", "37000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4704", "ओडिशा", "बेरहामपुर", "सोमनाथ बेहरा", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Odisha", "Bhadrak", "Manjulata Mandal", "Biju Janata Dal", "3.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9927", "ओडिशा", "भद्रक", "मंजुलता मंडल", "बीजू जनता दल"},
        {"Odisha", "Bhadrak", "Laxmipriya Jena", "Kalinga Sena", "74000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9930", "ओडिशा", "भद्रक", "लक्ष्मीप्रिया जेना", "कलिंग सेना"},
        {"Odisha", "Bhubaneswar", "Biswanath Rout", "Krupaa Party", "42.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7837", "ओडिशा", "भुवनेश्वर", "बिस्वनाथ राउत", "कृपा पार्टी"},
        {"Odisha", "Bhubaneswar", "Sanjaya Kumar Sahoo", "Independent", "21.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7832", "ओडिशा", "भुवनेश्वर", "संजय कुमार साहू", "निर्दलीय"},
        {"Odisha", "Bhubaneswar", "Pramila Behera", "Communist Party of India (Marxist–Leninist) Red Star", "47252", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7833", "ओडिशा", "भुवनेश्वर", "प्रमिला बेहरा", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) रेड स्टार"},
        {"Odisha", "Bhubaneswar", "Arup Mohan Patnaik", "Biju Janata Dal", "9.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8378", "ओडिशा", "भुवनेश्वर", "अरूप मोहन पटनायक", "बीजू जनता दल"},
        {"Odisha", "Bhubaneswar", "Susil Kumar Jena", "Independent", "30.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9912", "ओडिशा", "भुवनेश्वर", "सुशील कुमार जेना", "निर्दलीय"},
        {"Odisha", "Bhubaneswar", "Lalita Kumar Nayak", "Bahujan Samaj Party", "17Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9908", "ओडिशा", "भुवनेश्वर", "ललिता कुमार नायक", "बहुजन समाज पार्टी"},
        {"Odisha", "Bolangir", "Dinesh Nag", "Ambedkarite Party of India", "18.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4972", "ओडिशा", "बोलंगीर", "दिनेश नाग", "भारत की अम्बेडकरवादी पार्टी"},
        {"Odisha", "Bolangir", "Suresh Kumar Putel", "Bahujan Mukti Party", "1.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5876", "ओडिशा", "बोलंगीर", "सुरेश कुमार पुतेल", "बहुजन मुक्ति पार्टी"},
        {"Odisha", "Bolangir", "Hrudananda Karuan", "Socialist Unity Centre of India (Communist)", "26.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4971", "ओडिशा", "बोलंगीर", "हृदयानंद करुण", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Odisha", "Bolangir", "Kalikesh Narayan Singh Deo", "Biju Janata Dal", "20.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5558", "ओडिशा", "बोलंगीर", "कलिकेश नारायण सिंह देव", "बीजू जनता दल"},
        {"Odisha", "Bolangir", "Dr Bipin Kusulia", "Independent", "13.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5402", "ओडिशा", "बोलंगीर", "डॉ। बिपिन कुसुलिया", "निर्दलीय"},
        {"Odisha", "Cuttack", "Rajakishore Mallik", "Socialist Unity Centre of India (Communist)", "1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7873", "ओडिशा", "कटक", "राजकिशोर मल्लिक", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Odisha", "Cuttack", "Akshaya Kumar Kar", "Krupaa Party", "3.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8381", "ओडिशा", "कटक", "अक्षय कुमार कर", "कृपा पार्टी"},
        {"Odisha", "Cuttack", "Bhartruhari Mahtab", "Biju Janata Dal", "10.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8379", "ओडिशा", "कटक", "भर्तृहरि महताब", "बीजू जनता दल"},
        {"Odisha", "Cuttack", "Somiya Ranjan Das", "Bharat Prabhat Party", "7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8422", "ओडिशा", "कटक", "सोमिया रंजन दास", "भारत प्रभात पार्टी"},
        {"Odisha", "Cuttack", "Pramod Kumar Mallick", "Bahujan Samaj Party", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8421", "ओडिशा", "कटक", "प्रमोद कुमार मल्लिक", "बहुजन समाज पार्टी"},
        {"Odisha", "Cuttack", "Sanjaya Kumar Sahoo", "Independent", "11.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7874", "ओडिशा", "कटक", "संजय कुमार साहू", "निर्दलीय"},
        {"Odisha", "Cuttack", "Biswajit Goswami", "Kalinga Sena", "87412", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8424", "ओडिशा", "कटक", "बिस्वजीत गोस्वामी", "कलिंग सेना"},
        {"Odisha", "Dhenkanal", "Ranjan Kumar Sahoo", "Bhartiya Manvadhikaar Federal Party", "5.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7871", "ओडिशा", "ढेंकनाल", "रंजन कुमार साहू", "भारतीय मानववादी फेडरल पार्टी"},
        {"Odisha", "Dhenkanal", "Pradyumna Kumar Naik", "Bahujan Samaj Party", "4.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8385", "ओडिशा", "ढेंकनाल", "प्रद्युम्न कुमार नाइक", "बहुजन समाज पार्टी"},
        {"Odisha", "Dhenkanal", "Saroj Kumar Satpathy", "Samata Kranti Dal", "96702", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8388", "ओडिशा", "ढेंकनाल", "सरोज कुमार सतपथी", "समता क्रांति दल"},
        {"Odisha", "Dhenkanal", "Bijaya Kumar Behera", "Ambedkarite Party of India", "25.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7872", "ओडिशा", "ढेंकनाल", "बिजय कुमार बेहरा", "भारत की अम्बेडकरवादी पार्टी"},
        {"Odisha", "Jagatsinghpur", "Jagannath Megh", "Jai Prakash Janata Dal", "2.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9944", "ओडिशा", "जगतसिंहपुर", "जगन्नाथ मेघ", "जय प्रकाश जनता दल"},
        {"Odisha", "Jagatsinghpur", "Bibhuti Bhusan Majhi", "Bahujan Samaj Party", "88264", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9943", "ओडिशा", "जगतसिंहपुर", "बिभूति भूसन मझि", "बहुजन समाज पार्टी"},
        {"Odisha", "Jagatsinghpur", "Dipak Kumar Das", "Akhil Bharat Hindu Mahasabha", "20.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9940", "ओडिशा", "जगतसिंहपुर", "दीपक कुमार दास", "अखिल भारत हिंदू महासभा"},
        {"Odisha", "Jagatsinghpur", "Peeyuush Das", "Ambedkarite Party of India", "6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9939", "ओडिशा", "जगतसिंहपुर", "पीयूष दास", "भारत की अम्बेडकरवादी पार्टी"},
        {"Odisha", "Jagatsinghpur", "Sasmita Das", "Independent", "15.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9942", "ओडिशा", "जगतसिंहपुर", "सस्मिता दास", "निर्दलीय"},
        {"Odisha", "Jagatsinghpur", "Rajashree Mallick", "Biju Janata Dal", "4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9936", "ओडिशा", "जगतसिंहपुर", "राजश्री मल्लिक", "बीजू जनता दल"},
        {"Odisha", "Jajpur", "Subasa Chandra Malik", "Socialist Unity Centre of India (Communist)", "96000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10119", "ओडिशा", "जाजपुर", "सुबास चंद्र मलिक", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Odisha", "Jajpur", "Sarmistha Sethi", "Biju Janata Dal", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10122", "ओडिशा", "जाजपुर", "सरमिन्था सेठी", "बीजू जनता दल"},
        {"Odisha", "Kalahandi", "Chhabilal Nial", "Ambedkarite Party of India", "23.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4686", "ओडिशा", "कालाहांडी", "छबील नाल", "भारत की अम्बेडकरवादी पार्टी"},
        {"Odisha", "Kalahandi", "Premananda Bag", "Bahujan Samaj Party", "67.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5794", "ओडिशा", "कालाहांडी", "प्रेमानंद बाग", "बहुजन समाज पार्टी"},
        {"Odisha", "Kandhamal", "Amir Nayak", "Bahujan Samaj Party", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5880", "ओडिशा", "कंधमाल", "अमीर नायक", "बहुजन समाज पार्टी"},
        {"Odisha", "Kandhamal", "Achyutananda Samanta", "Biju Janata Dal", "12.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5403", "ओडिशा", "कंधमाल", "अच्युतानंद सामंत", "बीजू जनता दल"},
        {"Odisha", "Kendrapara", "Anubhav Mohanty", "Biju Janata Dal", "2.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10133", "ओडिशा", "केंद्रपाड़ा", "अनुभव मोहंती", "बीजू जनता दल"},
        {"Odisha", "Kendrapara", "Srikanta Samal", "Krupaa Party", "29.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10129", "ओडिशा", "केंद्रपाड़ा", "श्रीकांत समल", "कृपा पार्टी"},
        {"Odisha", "Keonjhar", "Ramesh Laguri", "Bahujan Mukti Party", "6.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8450", "ओडिशा", "क्योंझर", "रमेश लगुरी", "बहुजन मुक्ति पार्टी"},
        {"Odisha", "Keonjhar", "Prafulla Nayak", "All India Forward Bloc", "7.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8446", "ओडिशा", "क्योंझर", "प्रफुल्ल नायक", "ऑल इंडिया फॉरवर्ड ब्लॉक"},
        {"Odisha", "Keonjhar", "Chandrani Murmu", "Biju Janata Dal", "3.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8443", "ओडिशा", "क्योंझर", "चंद्रानी मुर्मू", "बीजू जनता दल"},
        {"Odisha", "Koraput", "Banamali Majhi", "Ambedkarite Party of India", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5870", "ओडिशा", "कोरापुट", "बनमाली माझी", "भारत की अम्बेडकरवादी पार्टी"},
        {"Odisha", "Koraput", "Bhaskar Mutuka", "Bahujan Samaj Party", "3.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5869", "ओडिशा", "कोरापुट", "भास्कर मुतुक्का", "बहुजन समाज पार्टी"},
        {"Odisha", "Mayurbhanj", "Dr Debashis Marndi", "Biju Janata Dal", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10139", "ओडिशा", "मयूरभंज", "डॉ। देबाशीष मरांडी", "बीजू जनता दल"},
        {"Odisha", "Mayurbhanj", "Parbati Purty", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10146", "ओडिशा", "मयूरभंज", "पारबती पुरी", "निर्दलीय"},
        {"Odisha", "Mayurbhanj", "Ramchandra Singh", "Bahujan Samaj Party", "16.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10147", "ओडिशा", "मयूरभंज", "रामचंद्र सिंह", "बहुजन समाज पार्टी"},
        {"Odisha", "Mayurbhanj", "Rabindra Nath Singh", "Independent", "49.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10142", "ओडिशा", "मयूरभंज", "रवीन्द्र नाथ सिंह", "निर्दलीय"},
        {"Odisha", "Nabarangpur", "Ramesh Chandra Majhi", "Biju Janata Dal", "81Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5544", "ओडिशा", "नबरंगपुर", "रमेश चंद्र माझी", "बीजू जनता दल"},
        {"Odisha", "Nabarangpur", "Chandradhwaj Majhi", "Bahujan Samaj Party", "21.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5543", "ओडिशा", "नबरंगपुर", "चंद्रध्वज माझी", "बहुजन समाज पार्टी"},
        {"Odisha", "Puri", "Pinaki Misra", "Biju Janata Dal", "117.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8390", "ओडिशा", "पुरी", "पिनाकी मिश्रा", "बीजू जनता दल"},
        {"Odisha", "Puri", "Sabyasachi Mohapatra", "Kalinga Sena", "15Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7866", "ओडिशा", "पुरी", "सब्यसाची महापात्र", "कलिंग सेना"},
        {"Odisha", "Sambalpur", "Ashutosh Kumar Hanuman", "Bharat Prabhat Party", "50690", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8474", "ओडिशा", "संबलपुर", "आशुतोष कुमार हनुमान", "भारत प्रभात पार्टी"},
        {"Odisha", "Sambalpur", "Nalini Kanta Pradhan", "Biju Janata Dal", "7.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8480", "ओडिशा", "संबलपुर", "नलिनी कांता प्रधान", "बीजू जनता दल"},
        {"Odisha", "Sambalpur", "Binay Ocean", "Ambedkarite Party of India", "87000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7869", "ओडिशा", "संबलपुर", "बिनय महासागर", "भारत की अम्बेडकरवादी पार्टी"},
        {"Odisha", "Sundargarh", "Sunita Biswal", "Biju Janata Dal", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5887", "ओडिशा", "सुंदरगढ़", "सुनीता बिस्वाल", "बीजू जनता दल"},
};

public static final String[][] red_bucket = {
        {"Odisha", "Aska", "Chakradhar Sahu", "4", " ", "ओडिशा", "अस्का", "चक्रधर साहू", " "},
        {"Odisha", "Aska", "Pramila Bisoyi", "3", " ", "ओडिशा", "अस्का", "प्रमिला बिसोई", " "},
        {"Odisha", "Aska", "K. Shyambabu Subudhi", "3", " ", "ओडिशा", "अस्का", "के। श्यामबाबू सुबुद्धि", " "},
        {"Odisha", "Aska", "Rama Krushna Panda", "2", " ", "ओडिशा", "अस्का", "राम कृष्ण पंडा", " "},
        {"Odisha", "Aska", "Anita Subhadarshini", "1", " ", "ओडिशा", "अस्का", "अनिता सुभद्राशिनी", " "},
        {"Odisha", "Aska", "Rajeeb Chandra Khadanga", "2", " ", "ओडिशा", "अस्का", "राजीब चंद्र खडंगा", " "},
        {"Odisha", "Balasore", "Navajyoti Patnaik", "1", " ", "ओडिशा", "बालासोर", "नवज्योति पटनायक", " "},
        {"Odisha", "Balasore", "Ramanath Barik", "3", " ", "ओडिशा", "बालासोर", "रमानाथ बारिक", " "},
        {"Odisha", "Balasore", "Rabindra Kumar Jena", "4", " ", "ओडिशा", "बालासोर", "रवीन्द्र कुमार जेना", " "},
        {"Odisha", "Balasore", "Pratap Chandra Sarangi", "1", " ", "ओडिशा", "बालासोर", "प्रताप चंद्र सारंगी", " "},
        {"Odisha", "Balasore", "Basantalata Pattanayak", "3", " ", "ओडिशा", "बालासोर", "बसंतलता पट्टनायक", " "},
        {"Odisha", "Bargarh", "Pradeep Kumar Debta", "1", " ", "ओडिशा", "बारगढ़", "प्रदीप कुमार देबता", " "},
        {"Odisha", "Bargarh", "Prasanna Acharya", "3", " ", "ओडिशा", "बारगढ़", "प्रसन्न आचार्य", " "},
        {"Odisha", "Bargarh", "Suresh Pujari", "1", " ", "ओडिशा", "बारगढ़", "सुरेश पुजारी", " "},
        {"Odisha", "Bargarh", "Kulamani Urma", "4", " ", "ओडिशा", "बारगढ़", "कुलमणि उर्म", " "},
        {"Odisha", "Bargarh", "M D Nizamuddin", "2", " ", "ओडिशा", "बारगढ़", "एमडी निजामुद्दीन", " "},
        {"Odisha", "Berhampur", "Bhrugu Baxipatra", "1", " ", "ओडिशा", "बेरहामपुर", "भृगु बक्सिपत्र", " "},
        {"Odisha", "Berhampur", "Chandra Sekhar Sahu", "3", " ", "ओडिशा", "बेरहामपुर", "चन्द्रशेखर साहू", " "},
        {"Odisha", "Berhampur", "Chakradhar Sahu", "4", " ", "ओडिशा", "बेरहामपुर", "चक्रधर साहू", " "},
        {"Odisha", "Berhampur", "V.Chandrasekhar Naidu", "1", " ", "ओडिशा", "बेरहामपुर", "वी। चंद्रशेखर नायडू", " "},
        {"Odisha", "Berhampur", "K. Shyambabu Subudhi", "3", " ", "ओडिशा", "बेरहामपुर", "के। श्यामबाबू सुबुद्धि", " "},
        {"Odisha", "Berhampur", "Srihari Patnaik", "4", " ", "ओडिशा", "बेरहामपुर", "श्रीहरि पटनायक", " "},
        {"Odisha", "Bhadrak", "Madhumita Sethi", "1", " ", "ओडिशा", "भद्रक", "मधुमिता सेठी", " "},
        {"Odisha", "Bhadrak", "Kirtan Bihari Malik", "3", " ", "ओडिशा", "भद्रक", "कीर्तन बिहारी मलिक", " "},
        {"Odisha", "Bhadrak", "Avimanyu Sethi", "1", " ", "ओडिशा", "भद्रक", "अविमन्यु सेठी", " "},
        {"Odisha", "Bhadrak", "Tilottama Jena", "4", " ", "ओडिशा", "भद्रक", "तिलोत्तमा जेना", " "},
        {"Odisha", "Bhadrak", "Muralidhar Jena", "3", " ", "ओडिशा", "भद्रक", "मुरलीधर जेना", " "},
        {"Odisha", "Bhadrak", "Pitamber Sethi", "4", " ", "ओडिशा", "भद्रक", "पीताम्बर सेठी", " "},
        {"Odisha", "Bhubaneswar", "Janardan Pati", "2", " ", "ओडिशा", "भुवनेश्वर", "जनार्दन पति", " "},
        {"Odisha", "Bhubaneswar", "Madhu Sudan Yadav", "3", " ", "ओडिशा", "भुवनेश्वर", "मधु सूदन यादव", " "},
        {"Odisha", "Bhubaneswar", "Biswanath Ramachandra", "3", " ", "ओडिशा", "भुवनेश्वर", "बिश्वनाथ रामचंद्र", " "},
        {"Odisha", "Bhubaneswar", "Subhranshu Sekhar Padhi", "2", " ", "ओडिशा", "भुवनेश्वर", "सुभ्रांशु सेखर पाढ़ी", " "},
        {"Odisha", "Bhubaneswar", "Jayant Kumar Das", "4", " ", "ओडिशा", "भुवनेश्वर", "जयंत कुमार दास", " "},
        {"Odisha", "Bhubaneswar", "Aparajita Sarangi", "1", " ", "ओडिशा", "भुवनेश्वर", "अपराजिता सारंगी", " "},
        {"Odisha", "Bhubaneswar", "Bhakta Sekhar Ray", "2", " ", "ओडिशा", "भुवनेश्वर", "भक्त शेखर रे", " "},
        {"Odisha", "Bolangir", "Smt. Sangeeta Kumari Singh Deo", "1", " ", "ओडिशा", "बोलंगीर", "श्रीमती। संगीता कुमारी सिंह देव", " "},
        {"Odisha", "Bolangir", "Rana Nag", "3", " ", "ओडिशा", "बोलंगीर", "राणा नाग", " "},
        {"Odisha", "Bolangir", "Samarendra Mishra", "1", " ", "ओडिशा", "बोलंगीर", "समरेंद्र मिश्रा", " "},
        {"Odisha", "Cuttack", "Prakash Mishra", "1", " ", "ओडिशा", "कटक", "प्रकाश मिश्रा", " "},
        {"Odisha", "Cuttack", "Ashok Pradhan", "4", " ", "ओडिशा", "कटक", "अशोक प्रधान", " "},
        {"Odisha", "Cuttack", "Panchanan Kanungo", "1", " ", "ओडिशा", "कटक", "पंचानन कानूनगो", " "},
        {"Odisha", "Cuttack", "Brundaban Das Ajad", "2", " ", "ओडिशा", "कटक", "ब्रंदबन दास अजाद", " "},
        {"Odisha", "Dhenkanal", "Priyabrata Garnaik", "2", " ", "ओडिशा", "ढेंकनाल", "प्रियब्रत गार्णिक", " "},
        {"Odisha", "Dhenkanal", "Raja Kamakhya Prasad Singh Deo", "1", " ", "ओडिशा", "ढेंकनाल", "राजा कामाख्या प्रसाद सिंह देव", " "},
        {"Odisha", "Dhenkanal", "Mahesh Sahoo", "2", " ", "ओडिशा", "ढेंकनाल", "महेश साहू", " "},
        {"Odisha", "Dhenkanal", "Rudranarayan Pany", "1", " ", "ओडिशा", "ढेंकनाल", "रुद्रनारायण पाणि", " "},
        {"Odisha", "Dhenkanal", "Manasi Swain", "2", " ", "ओडिशा", "ढेंकनाल", "मानसी स्वैन", " "},
        {"Odisha", "Jagatsinghpur", "Bibhu Prasad Tarai", "1", " ", "ओडिशा", "जगतसिंहपुर", "बिभु प्रसाद तराई", " "},
        {"Odisha", "Jagatsinghpur", "Anil Kumar Behera", "4", " ", "ओडिशा", "जगतसिंहपुर", "अनिल कुमार बेहरा", " "},
        {"Odisha", "Jagatsinghpur", "Pratima Mallick", "1", " ", "ओडिशा", "जगतसिंहपुर", "प्रतिमा मल्लिक", " "},
        {"Odisha", "Jajpur", "Ranjit Malik", "2", " ", "ओडिशा", "जाजपुर", "रंजीत मलिक", " "},
        {"Odisha", "Jajpur", "Amiya Kanta Mallick", "1", " ", "ओडिशा", "जाजपुर", "अमिय कांता मल्लिक", " "},
        {"Odisha", "Jajpur", "Manas Jena", "1", " ", "ओडिशा", "जाजपुर", "मानस जेना", " "},
        {"Odisha", "Jajpur", "Sunakar Behera", "3", " ", "ओडिशा", "जाजपुर", "सुनकर बेहरा", " "},
        {"Odisha", "Jajpur", "Bhimasen Behera", "2", " ", "ओडिशा", "जाजपुर", "भीमसेन बेहरा", " "},
        {"Odisha", "Jajpur", "Tilottama Sethy", "4", " ", "ओडिशा", "जाजपुर", "तिलोत्तमा सेठ", " "},
        {"Odisha", "Kalahandi", "Basanta Kumar Panda", "1", " ", "ओडिशा", "कालाहांडी", "बसंत कुमार पांडा", " "},
        {"Odisha", "Kalahandi", "Bhakta Charan Das", "1", " ", "ओडिशा", "कालाहांडी", "भक्त चरण दास", " "},
        {"Odisha", "Kalahandi", "Hatiram Durga", "4", " ", "ओडिशा", "कालाहांडी", "हतीराम दुर्गा", " "},
        {"Odisha", "Kalahandi", "Kamalini Yadav", "4", " ", "ओडिशा", "कालाहांडी", "कमलिनी यादव", " "},
        {"Odisha", "Kalahandi", "Puspendra Singh Deo", "4", " ", "ओडिशा", "कालाहांडी", "पुष्पेन्द्र सिंह देव", " "},
        {"Odisha", "Kandhamal", "Manoj Kumar Acharya", "1", " ", "ओडिशा", "कंधमाल", "मनोज कुमार आचार्य", " "},
        {"Odisha", "Kandhamal", "Tuna Mallick", "4", " ", "ओडिशा", "कंधमाल", "टूना मल्लिक", " "},
        {"Odisha", "Kandhamal", "Mahameghabahan Aira Kharabela Swain", "1", " ", "ओडिशा", "कंधमाल", "महामेघभान ऐरा खरबेला स्वैन", " "},
        {"Odisha", "Kendrapara", "Santosh Kumar Das", "4", " ", "ओडिशा", "केंद्रपाड़ा", "संतोष कुमार दास", " "},
        {"Odisha", "Kendrapara", "Baijayant Panda", "1", " ", "ओडिशा", "केंद्रपाड़ा", "बैजयंत पांडा", " "},
        {"Odisha", "Kendrapara", "Dharanidhar Nayak", "1", " ", "ओडिशा", "केंद्रपाड़ा", "धरणीधर नायक", " "},
        {"Odisha", "Kendrapara", "Santosh Kumar Patra", "4", " ", "ओडिशा", "केंद्रपाड़ा", "संतोष कुमार पात्रा", " "},
        {"Odisha", "Kendrapara", "Rabindra Nath Behera", "2", " ", "ओडिशा", "केंद्रपाड़ा", "रवीन्द्र नाथ बेहरा", " "},
        {"Odisha", "Keonjhar", "Durga Chandra Pingua", "4", " ", "ओडिशा", "क्योंझर", "दुर्गा चंद्र पिंगुआ", " "},
        {"Odisha", "Keonjhar", "Dr. Sudarshan Lohar", "3", " ", "ओडिशा", "क्योंझर", "डॉ। सुदर्शन लोहार", " "},
        {"Odisha", "Keonjhar", "Lalmohan Hansdah", "4", " ", "ओडिशा", "क्योंझर", "लालमोहन हंसदाह", " "},
        {"Odisha", "Keonjhar", "Ananta Nayak", "1", " ", "ओडिशा", "क्योंझर", "अनंत नायक", " "},
        {"Odisha", "Keonjhar", "Mohan Kumar Hembram", "1", " ", "ओडिशा", "क्योंझर", "मोहन कुमार हेम्ब्रम", " "},
        {"Odisha", "Koraput", "Kausalya Hikaka", "4", " ", "ओडिशा", "कोरापुट", "कौसल्या हिकाका", " "},
        {"Odisha", "Koraput", "Jayaram Pangi", "1", " ", "ओडिशा", "कोरापुट", "जयराम पांगी", " "},
        {"Odisha", "Koraput", "Saptagiri Sankar Ulaka", "1", " ", "ओडिशा", "कोरापुट", "सप्तगिरि संकर उलका", " "},
        {"Odisha", "Koraput", "Damodara Sabar", "3", " ", "ओडिशा", "कोरापुट", "दामोदर सबर", " "},
        {"Odisha", "Koraput", "Rajendra Kendruka", "2", " ", "ओडिशा", "कोरापुट", "राजेंद्र केंद्रुका", " "},
        {"Odisha", "Mayurbhanj", "Anjani Soren", "4", " ", "ओडिशा", "मयूरभंज", "अंजनी सोरेन", " "},
        {"Odisha", "Mayurbhanj", "Nanda Kishore Kisku", "3", " ", "ओडिशा", "मयूरभंज", "नंद किशोर किस्कू", " "},
        {"Odisha", "Mayurbhanj", "Bharat Chandra Singh", "4", " ", "ओडिशा", "मयूरभंज", "भरत चंद्र सिंह", " "},
        {"Odisha", "Mayurbhanj", "Bishweswar Tudu", "1", " ", "ओडिशा", "मयूरभंज", "बिशेश्वर टुडू", " "},
        {"Odisha", "Nabarangpur", "Balabhadra Majhi", "1", " ", "ओडिशा", "नबरंगपुर", "बलभद्र माझी", " "},
        {"Odisha", "Nabarangpur", "Pradeep Kumar Majhi", "1", " ", "ओडिशा", "नबरंगपुर", "प्रदीप कुमार मांझी", " "},
        {"Odisha", "Puri", "Satya Prakash Nayak", "1", " ", "ओडिशा", "पुरी", "सत्य प्रकाश नायक", " "},
        {"Odisha", "Puri", "Nrusingha Charan Das", "3", " ", "ओडिशा", "पुरी", "नृसिंह चरण दास", " "},
        {"Odisha", "Puri", "Mandakini Sethi", "4", " ", "ओडिशा", "पुरी", "मंदाकिनी सेठी", " "},
        {"Odisha", "Puri", "Sambit Patra", "1", " ", "ओडिशा", "पुरी", "संमित पात्र", " "},
        {"Odisha", "Puri", "Jayaprakash Sethi", "4", " ", "ओडिशा", "पुरी", "जयप्रकाश सेठी", " "},
        {"Odisha", "Puri", "Ranjan Kumar Mishra", "4", " ", "ओडिशा", "पुरी", "रंजन कुमार मिश्र", " "},
        {"Odisha", "Sambalpur", "Nabakishore Pradhan", "2", " ", "ओडिशा", "संबलपुर", "नबकिशोर प्रधान", " "},
        {"Odisha", "Sambalpur", "Prabhat Kumar Dharua", "4", " ", "ओडिशा", "संबलपुर", "प्रभात कुमार धारुआ", " "},
        {"Odisha", "Sambalpur", "Mustukim", "2", " ", "ओडिशा", "संबलपुर", "Mustukim", " "},
        {"Odisha", "Sambalpur", "Sarat Pattanayak", "1", " ", "ओडिशा", "संबलपुर", "शरत पट्टनायक", " "},
        {"Odisha", "Sambalpur", "Santoshini Karna", "4", " ", "ओडिशा", "संबलपुर", "संतोषिनी कर्ण", " "},
        {"Odisha", "Sambalpur", "Nitesh Ganga Deb", "1", " ", "ओडिशा", "संबलपुर", "नितेश गंगा देब", " "},
        {"Odisha", "Sambalpur", "Kanhu Charan Sanbad", "3", " ", "ओडिशा", "संबलपुर", "कान्हू चरण सनबाद", " "},
        {"Odisha", "Sambalpur", "Atma Ram Supkar", "4", " ", "ओडिशा", "संबलपुर", "एतमा राम सुपकर", " "},
        {"Odisha", "Sundargarh", "Jual Oram", "1", " ", "ओडिशा", "सुंदरगढ़", "जुअल ओराम", " "},
        {"Odisha", "Sundargarh", "Miss Juspin Lakra", "2", " ", "ओडिशा", "सुंदरगढ़", "मिस जसपिन लकड़ा", " "},
        {"Odisha", "Sundargarh", "Dayananda Bhitria", "4", " ", "ओडिशा", "सुंदरगढ़", "दयानंद भितरिया", " "},
        {"Odisha", "Sundargarh", "Udit Chandra Amat", "3", " ", "ओडिशा", "सुंदरगढ़", "उदित चंद्र अमत", " "},
        {"Odisha", "Sundargarh", "Justin Lugun", "4", " ", "ओडिशा", "सुंदरगढ़", "जस्टिन लुगुन", " "},
        {"Odisha", "Sundargarh", "Basil Ekka", "4", " ", "ओडिशा", "सुंदरगढ़", "तुलसी एक्का", " "},
        {"Odisha", "Sundargarh", "George Tirkey", "1", " ", "ओडिशा", "सुंदरगढ़", "जॉर्ज तिर्की", " "},
};

}