/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Odisha {
public static final String[][] green_bucket = {
{"Odisha",  "4429", "Aska", "Sankar Sahu", "Communist Party of India (Marxist–Leninist) Red Star", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4969",  "ओडिशा",  "अस्का", "शंकर साहू", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) रेड स्टार", ""}, 
{"Odisha",  "4435", "Aska", "Purna Chandra Nayak", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5872",  "ओडिशा",  "अस्का", "पूर्ण चंद्र नायक", "बहुजन समाज पार्टी", ""}, 
{"Odisha",  "4395", "Bargarh", "Kousika Suna", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5875",  "ओडिशा",  "बारगढ़", "कौसिक सुनय", "बहुजन समाज पार्टी", ""}, 
{"Odisha",  "4436", "Berhampur", "Tirupati Rao Karanam", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5550",  "ओडिशा",  "बेरहामपुर", "तिरुपति राव करणम", "बहुजन समाज पार्टी", ""}, 
{"Odisha",  "4438", "Berhampur", "Somanath Behera", "Socialist Unity Centre of India (Communist)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4704",  "ओडिशा",  "बेरहामपुर", "सोमनाथ बेहरा", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Odisha",  "7693", "Bhubaneswar", "Biswanath Rout", "Krupaa Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7837",  "ओडिशा",  "भुवनेश्वर", "बिस्वनाथ राउत", "", ""}, 
{"Odisha",  "7695", "Bhubaneswar", "Sanjaya Kumar Sahoo", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7832",  "ओडिशा",  "भुवनेश्वर", "संजय कुमार साहू", "निर्दलीय", ""}, 
{"Odisha",  "7696", "Bhubaneswar", "Pramila Behera", "Communist Party of India (Marxist–Leninist) Red Star", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7833",  "ओडिशा",  "भुवनेश्वर", "प्रमिला बेहरा", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) रेड स्टार", ""}, 
{"Odisha",  "7698", "Bhubaneswar", "Arup Mohan Patnaik", "Biju Janata Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8378",  "ओडिशा",  "भुवनेश्वर", "अरूप मोहन पटनायक", "बीजू जनता दल", ""}, 
{"Odisha",  "7701", "Bhubaneswar", "Susil Kumar Jena", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9912",  "ओडिशा",  "भुवनेश्वर", "सुशील कुमार जेना", "निर्दलीय", ""}, 
{"Odisha",  "7703", "Bhubaneswar", "Lalita Kumar Nayak", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9908",  "ओडिशा",  "भुवनेश्वर", "ललिता कुमार नायक", "बहुजन समाज पार्टी", ""}, 
{"Odisha",  "4404", "Bolangir", "Dinesh Nag", "Ambedkarite Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4972",  "ओडिशा",  "बोलंगीर", "दिनेश नाग", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Odisha",  "4406", "Bolangir", "Suresh Kumar Putel", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5876",  "ओडिशा",  "बोलंगीर", "सुरेश कुमार पुतेल", "बहुजन मुक्ति पार्टी", ""}, 
{"Odisha",  "4407", "Bolangir", "Hrudananda Karuan", "Socialist Unity Centre of India (Communist)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4971",  "ओडिशा",  "बोलंगीर", "हृदयानंद करुण", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Odisha",  "4408", "Bolangir", "Kalikesh Narayan Singh Deo", "Biju Janata Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5558",  "ओडिशा",  "बोलंगीर", "कलिकेश नारायण सिंह देव", "बीजू जनता दल", ""}, 
{"Odisha",  "4411", "Bolangir", "Dr Bipin Kusulia", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5402",  "ओडिशा",  "बोलंगीर", "डॉ। बिपिन कुसुलिया", "निर्दलीय", ""}, 
{"Odisha",  "7680", "Cuttack", "Rajakishore Mallik", "Socialist Unity Centre of India (Communist)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7873",  "ओडिशा",  "कटक", "राजकिशोर मल्लिक", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Odisha",  "7673", "Cuttack", "Akshaya Kumar Kar", "Krupaa Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8381",  "ओडिशा",  "कटक", "अक्षय कुमार कर", "", ""}, 
{"Odisha",  "7674", "Cuttack", "Bhartruhari Mahtab", "Biju Janata Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8379",  "ओडिशा",  "कटक", "भर्तृहरि महताब", "बीजू जनता दल", ""}, 
{"Odisha",  "7675", "Cuttack", "Somiya Ranjan Das", "Bharat Prabhat Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8422",  "ओडिशा",  "कटक", "सोमिया रंजन दास", "", ""}, 
{"Odisha",  "7676", "Cuttack", "Pramod Kumar Mallick", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8421",  "ओडिशा",  "कटक", "प्रमोद कुमार मल्लिक", "बहुजन समाज पार्टी", ""}, 
{"Odisha",  "7677", "Cuttack", "Sanjaya Kumar Sahoo", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7874",  "ओडिशा",  "कटक", "संजय कुमार साहू", "निर्दलीय", ""}, 
{"Odisha",  "7679", "Cuttack", "Biswajit Goswami", "Kalinga Sena", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8424",  "ओडिशा",  "कटक", "बिस्वजीत गोस्वामी", "", ""}, 
{"Odisha",  "7667", "Dhenkanal", "Pradyumna Kumar Naik", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8385",  "ओडिशा",  "ढेंकनाल", "प्रद्युम्न कुमार नाइक", "बहुजन समाज पार्टी", ""}, 
{"Odisha",  "7668", "Dhenkanal", "Saroj Kumar Satpathy", "Samata Kranti Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8388",  "ओडिशा",  "ढेंकनाल", "सरोज कुमार सतपथी", "", ""}, 
{"Odisha",  "7672", "Dhenkanal", "Bijaya Kumar Behera", "Ambedkarite Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7872",  "ओडिशा",  "ढेंकनाल", "बिजय कुमार बेहरा", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Odisha",  "4413", "Kalahandi", "Chhabilal Nial", "Ambedkarite Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4686",  "ओडिशा",  "कालाहांडी", "छबील नाल", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Odisha",  "4418", "Kalahandi", "Premananda Bag", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5794",  "ओडिशा",  "कालाहांडी", "प्रेमानंद बाग", "बहुजन समाज पार्टी", ""}, 
{"Odisha",  "4425", "Kandhamal", "Amir Nayak", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5880",  "ओडिशा",  "कंधमाल", "अमीर नायक", "बहुजन समाज पार्टी", ""}, 
{"Odisha",  "4427", "Kandhamal", "Achyutananda Samanta", "Biju Janata Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5403",  "ओडिशा",  "कंधमाल", "अच्युतानंद सामंत", "बीजू जनता दल", ""}, 
{"Odisha",  "7658", "Keonjhar", "Ramesh Laguri", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8450",  "ओडिशा",  "क्योंझर", "रमेश लगुरी", "बहुजन मुक्ति पार्टी", ""}, 
{"Odisha",  "7659", "Keonjhar", "Prafulla Nayak", "All India Forward Bloc", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8446",  "ओडिशा",  "क्योंझर", "प्रफुल्ल नायक", "ऑल इंडिया फॉरवर्ड ब्लॉक", ""}, 
{"Odisha",  "7663", "Keonjhar", "Chandrani Murmu", "Biju Janata Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8443",  "ओडिशा",  "क्योंझर", "चंद्रानी मुर्मू", "बीजू जनता दल", ""}, 
{"Odisha",  "4446", "Koraput", "Banamali Majhi", "Ambedkarite Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5870",  "ओडिशा",  "कोरापुट", "बनमाली माझी", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Odisha",  "4447", "Koraput", "Bhaskar Mutuka", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5869",  "ओडिशा",  "कोरापुट", "भास्कर मुतुक्का", "बहुजन समाज पार्टी", ""}, 
{"Odisha",  "4419", "Nabarangpur", "Ramesh Chandra Majhi", "Biju Janata Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5544",  "ओडिशा",  "नबरंगपुर", "रमेश चंद्र माझी", "बीजू जनता दल", ""}, 
{"Odisha",  "4421", "Nabarangpur", "Chandradhwaj Majhi", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5543",  "ओडिशा",  "नबरंगपुर", "चंद्रध्वज माझी", "बहुजन समाज पार्टी", ""}, 
{"Odisha",  "7689", "Puri", "Pinaki Misra", "Biju Janata Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8390",  "ओडिशा",  "पुरी", "पिनाकी मिश्रा", "बीजू जनता दल", ""}, 
{"Odisha",  "7690", "Puri", "Sabyasachi Mohapatra", "Kalinga Sena", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7866",  "ओडिशा",  "पुरी", "सब्यसाची महापात्र", "", ""}, 
{"Odisha",  "7646", "Sambalpur", "Ashutosh Kumar Hanuman", "Bharat Prabhat Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8474",  "ओडिशा",  "संबलपुर", "आशुतोष कुमार हनुमान", "", ""}, 
{"Odisha",  "7649", "Sambalpur", "Nalini Kanta Pradhan", "Biju Janata Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8480",  "ओडिशा",  "संबलपुर", "नलिनी कांता प्रधान", "बीजू जनता दल", ""}, 
{"Odisha",  "7655", "Sambalpur", "Binay Ocean", "Ambedkarite Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7869",  "ओडिशा",  "संबलपुर", "बिनय महासागर", "भारत की अम्बेडकरवादी पार्टी", ""}, 
{"Odisha",  "4400", "Sundargarh", "Sunita Biswal", "Biju Janata Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5887",  "ओडिशा",  "सुंदरगढ़", "सुनीता बिस्वाल", "बीजू जनता दल", ""}, 
};

public static final String[][] red_bucket = {
{ "Odisha",  "4428",  "Aska", "Chakradhar Sahu", "NotGraduate",  " ","ओडिशा",  "अस्का", "चक्रधर साहू", " "}, 
{ "Odisha",  "4430",  "Aska", "Pramila Bisoyi", "OverAged",  " ","ओडिशा",  "अस्का", "प्रमिला बिसोई", " "}, 
{ "Odisha",  "4431",  "Aska", "K. Shyambabu Subudhi", "OverAged",  " ","ओडिशा",  "अस्का", "के। श्यामबाबू सुबुद्धि", " "}, 
{ "Odisha",  "4432",  "Aska", "Rama Krushna Panda", "CriminalCases",  " ","ओडिशा",  "अस्का", "राम कृष्ण पंडा", " "}, 
{ "Odisha",  "4433",  "Aska", "Anita Subhadarshini", "ForeignFunding",  " ","ओडिशा",  "अस्का", "अनिता सुभद्राशिनी", " "}, 
{ "Odisha",  "4434",  "Aska", "Rajeeb Chandra Khadanga", "CriminalCases",  " ","ओडिशा",  "अस्का", "राजीब चंद्र खडंगा", " "}, 
{ "Odisha",  "4390",  "Bargarh", "Pradeep Kumar Debta", "ForeignFunding",  " ","ओडिशा",  "बारगढ़", "प्रदीप कुमार देबता", " "}, 
{ "Odisha",  "4391",  "Bargarh", "Prasanna Acharya", "OverAged",  " ","ओडिशा",  "बारगढ़", "प्रसन्न आचार्य", " "}, 
{ "Odisha",  "4392",  "Bargarh", "Suresh Pujari", "ForeignFunding",  " ","ओडिशा",  "बारगढ़", "सुरेश पुजारी", " "}, 
{ "Odisha",  "4393",  "Bargarh", "Kulamani Urma", "NotGraduate",  " ","ओडिशा",  "बारगढ़", "कुलमणि उर्म", " "}, 
{ "Odisha",  "4394",  "Bargarh", "M D Nizamuddin", "CriminalCases",  " ","ओडिशा",  "बारगढ़", "एमडी निजामुद्दीन", " "}, 
{ "Odisha",  "4437",  "Berhampur", "Bhrugu Baxipatra", "ForeignFunding",  " ","ओडिशा",  "बेरहामपुर", "भृगु बक्सिपत्र", " "}, 
{ "Odisha",  "4439",  "Berhampur", "Chandra Sekhar Sahu", "OverAged",  " ","ओडिशा",  "बेरहामपुर", "चन्द्रशेखर साहू", " "}, 
{ "Odisha",  "4440",  "Berhampur", "Chakradhar Sahu", "NotGraduate",  " ","ओडिशा",  "बेरहामपुर", "चक्रधर साहू", " "}, 
{ "Odisha",  "4441",  "Berhampur", "V.Chandrasekhar Naidu", "ForeignFunding",  " ","ओडिशा",  "बेरहामपुर", "वी। चंद्रशेखर नायडू", " "}, 
{ "Odisha",  "4442",  "Berhampur", "K. Shyambabu Subudhi", "OverAged",  " ","ओडिशा",  "बेरहामपुर", "के। श्यामबाबू सुबुद्धि", " "}, 
{ "Odisha",  "4443",  "Berhampur", "Srihari Patnaik", "NotGraduate",  " ","ओडिशा",  "बेरहामपुर", "श्रीहरि पटनायक", " "}, 
{ "Odisha",  "7692",  "Bhubaneswar", "Janardan Pati", "CriminalCases",  " ","ओडिशा",  "भुवनेश्वर", "जनार्दन पति", " "}, 
{ "Odisha",  "7694",  "Bhubaneswar", "Madhu Sudan Yadav", "OverAged",  " ","ओडिशा",  "भुवनेश्वर", "मधु सूदन यादव", " "}, 
{ "Odisha",  "7697",  "Bhubaneswar", "Biswanath Ramachandra", "OverAged",  " ","ओडिशा",  "भुवनेश्वर", "बिश्वनाथ रामचंद्र", " "}, 
{ "Odisha",  "7699",  "Bhubaneswar", "Subhranshu Sekhar Padhi", "CriminalCases",  " ","ओडिशा",  "भुवनेश्वर", "सुभ्रांशु सेखर पाढ़ी", " "}, 
{ "Odisha",  "7700",  "Bhubaneswar", "Jayant Kumar Das", "NotGraduate",  " ","ओडिशा",  "भुवनेश्वर", "जयंत कुमार दास", " "}, 
{ "Odisha",  "7702",  "Bhubaneswar", "Aparajita Sarangi", "ForeignFunding",  " ","ओडिशा",  "भुवनेश्वर", "अपराजिता सारंगी", " "}, 
{ "Odisha",  "7704",  "Bhubaneswar", "Bhakta Sekhar Ray", "CriminalCases",  " ","ओडिशा",  "भुवनेश्वर", "भक्त शेखर रे", " "}, 
{ "Odisha",  "4405",  "Bolangir", "Smt. Sangeeta Kumari Singh Deo", "ForeignFunding",  " ","ओडिशा",  "बोलंगीर", "श्रीमती। संगीता कुमारी सिंह देव", " "}, 
{ "Odisha",  "4409",  "Bolangir", "Rana Nag", "OverAged",  " ","ओडिशा",  "बोलंगीर", "राणा नाग", " "}, 
{ "Odisha",  "4410",  "Bolangir", "Samarendra Mishra", "ForeignFunding",  " ","ओडिशा",  "बोलंगीर", "समरेंद्र मिश्रा", " "}, 
{ "Odisha",  "7681",  "Cuttack", "Prakash Mishra", "ForeignFunding",  " ","ओडिशा",  "कटक", "प्रकाश मिश्रा", " "}, 
{ "Odisha",  "7682",  "Cuttack", "Ashok Pradhan", "NotGraduate",  " ","ओडिशा",  "कटक", "अशोक प्रधान", " "}, 
{ "Odisha",  "7683",  "Cuttack", "Panchanan Kanungo", "ForeignFunding",  " ","ओडिशा",  "कटक", "पंचानन कानूनगो", " "}, 
{ "Odisha",  "7678",  "Cuttack", "Brundaban Das Ajad", "CriminalCases",  " ","ओडिशा",  "कटक", "ब्रंदबन दास अजाद", " "}, 
{ "Odisha",  "7664",  "Dhenkanal", "Ranjan Kumar Sahoo", "NotGraduate",  " ","ओडिशा",  "ढेंकनाल", "रंजन कुमार साहू", " "}, 
{ "Odisha",  "7665",  "Dhenkanal", "Priyabrata Garnaik", "CriminalCases",  " ","ओडिशा",  "ढेंकनाल", "प्रियब्रत गार्णिक", " "}, 
{ "Odisha",  "7666",  "Dhenkanal", "Raja Kamakhya Prasad Singh Deo", "ForeignFunding",  " ","ओडिशा",  "ढेंकनाल", "राजा कामाख्या प्रसाद सिंह देव", " "}, 
{ "Odisha",  "7669",  "Dhenkanal", "Mahesh Sahoo", "CriminalCases",  " ","ओडिशा",  "ढेंकनाल", "महेश साहू", " "}, 
{ "Odisha",  "7670",  "Dhenkanal", "Rudranarayan Pany", "ForeignFunding",  " ","ओडिशा",  "ढेंकनाल", "रुद्रनारायण पाणि", " "}, 
{ "Odisha",  "7671",  "Dhenkanal", "Manasi Swain", "CriminalCases",  " ","ओडिशा",  "ढेंकनाल", "मानसी स्वैन", " "}, 
{ "Odisha",  "4412",  "Kalahandi", "Basanta Kumar Panda", "ForeignFunding",  " ","ओडिशा",  "कालाहांडी", "बसंत कुमार पांडा", " "}, 
{ "Odisha",  "4414",  "Kalahandi", "Bhakta Charan Das", "ForeignFunding",  " ","ओडिशा",  "कालाहांडी", "भक्त चरण दास", " "}, 
{ "Odisha",  "4415",  "Kalahandi", "Hatiram Durga", "NotGraduate",  " ","ओडिशा",  "कालाहांडी", "हतीराम दुर्गा", " "}, 
{ "Odisha",  "4416",  "Kalahandi", "Kamalini Yadav", "NotGraduate",  " ","ओडिशा",  "कालाहांडी", "कमलिनी यादव", " "}, 
{ "Odisha",  "4417",  "Kalahandi", "Puspendra Singh Deo", "NotGraduate",  " ","ओडिशा",  "कालाहांडी", "पुष्पेन्द्र सिंह देव", " "}, 
{ "Odisha",  "4423",  "Kandhamal", "Manoj Kumar Acharya", "ForeignFunding",  " ","ओडिशा",  "कंधमाल", "मनोज कुमार आचार्य", " "}, 
{ "Odisha",  "4424",  "Kandhamal", "Tuna Mallick", "NotGraduate",  " ","ओडिशा",  "कंधमाल", "टूना मल्लिक", " "}, 
{ "Odisha",  "4426",  "Kandhamal", "Mahameghabahan Aira Kharabela Swain", "ForeignFunding",  " ","ओडिशा",  "कंधमाल", "महामेघभान ऐरा खरबेला स्वैन", " "}, 
{ "Odisha",  "7656",  "Keonjhar", "Durga Chandra Pingua", "NotGraduate",  " ","ओडिशा",  "क्योंझर", "दुर्गा चंद्र पिंगुआ", " "}, 
{ "Odisha",  "7657",  "Keonjhar", "Dr. Sudarshan Lohar", "OverAged",  " ","ओडिशा",  "क्योंझर", "डॉ। सुदर्शन लोहार", " "}, 
{ "Odisha",  "7660",  "Keonjhar", "Lalmohan Hansdah", "NotGraduate",  " ","ओडिशा",  "क्योंझर", "लालमोहन हंसदाह", " "}, 
{ "Odisha",  "7661",  "Keonjhar", "Ananta Nayak", "ForeignFunding",  " ","ओडिशा",  "क्योंझर", "अनंत नायक", " "}, 
{ "Odisha",  "7662",  "Keonjhar", "Mohan Kumar Hembram", "ForeignFunding",  " ","ओडिशा",  "क्योंझर", "मोहन कुमार हेम्ब्रम", " "}, 
{ "Odisha",  "4444",  "Koraput", "Kausalya Hikaka", "NotGraduate",  " ","ओडिशा",  "कोरापुट", "कौसल्या हिकाका", " "}, 
{ "Odisha",  "4445",  "Koraput", "Jayaram Pangi", "ForeignFunding",  " ","ओडिशा",  "कोरापुट", "जयराम पांगी", " "}, 
{ "Odisha",  "4448",  "Koraput", "Saptagiri Sankar Ulaka", "ForeignFunding",  " ","ओडिशा",  "कोरापुट", "सप्तगिरि संकर उलका", " "}, 
{ "Odisha",  "4449",  "Koraput", "Damodara Sabar", "OverAged",  " ","ओडिशा",  "कोरापुट", "दामोदर सबर", " "}, 
{ "Odisha",  "4450",  "Koraput", "Rajendra Kendruka", "CriminalCases",  " ","ओडिशा",  "कोरापुट", "राजेंद्र केंद्रुका", " "}, 
{ "Odisha",  "4420",  "Nabarangpur", "Balabhadra Majhi", "ForeignFunding",  " ","ओडिशा",  "नबरंगपुर", "बलभद्र माझी", " "}, 
{ "Odisha",  "4422",  "Nabarangpur", "Pradeep Kumar Majhi", "ForeignFunding",  " ","ओडिशा",  "नबरंगपुर", "प्रदीप कुमार मांझी", " "}, 
{ "Odisha",  "7684",  "Puri", "Satya Prakash Nayak", "ForeignFunding",  " ","ओडिशा",  "पुरी", "सत्य प्रकाश नायक", " "}, 
{ "Odisha",  "7685",  "Puri", "Nrusingha Charan Das", "OverAged",  " ","ओडिशा",  "पुरी", "नृसिंह चरण दास", " "}, 
{ "Odisha",  "7686",  "Puri", "Mandakini Sethi", "NotGraduate",  " ","ओडिशा",  "पुरी", "मंदाकिनी सेठी", " "}, 
{ "Odisha",  "7687",  "Puri", "Sambit Patra", "ForeignFunding",  " ","ओडिशा",  "पुरी", "संमित पात्र", " "}, 
{ "Odisha",  "7688",  "Puri", "Jayaprakash Sethi", "NotGraduate",  " ","ओडिशा",  "पुरी", "जयप्रकाश सेठी", " "}, 
{ "Odisha",  "7691",  "Puri", "Ranjan Kumar Mishra", "NotGraduate",  " ","ओडिशा",  "पुरी", "रंजन कुमार मिश्र", " "}, 
{ "Odisha",  "7645",  "Sambalpur", "Nabakishore Pradhan", "CriminalCases",  " ","ओडिशा",  "संबलपुर", "नबकिशोर प्रधान", " "}, 
{ "Odisha",  "7647",  "Sambalpur", "Prabhat Kumar Dharua", "NotGraduate",  " ","ओडिशा",  "संबलपुर", "प्रभात कुमार धारुआ", " "}, 
{ "Odisha",  "7648",  "Sambalpur", "Mustukim", "CriminalCases",  " ","ओडिशा",  "संबलपुर", "Mustukim", " "}, 
{ "Odisha",  "7650",  "Sambalpur", "Sarat Pattanayak", "ForeignFunding",  " ","ओडिशा",  "संबलपुर", "शरत पट्टनायक", " "}, 
{ "Odisha",  "7651",  "Sambalpur", "Santoshini Karna", "NotGraduate",  " ","ओडिशा",  "संबलपुर", "संतोषिनी कर्ण", " "}, 
{ "Odisha",  "7652",  "Sambalpur", "Nitesh Ganga Deb", "ForeignFunding",  " ","ओडिशा",  "संबलपुर", "नितेश गंगा देब", " "}, 
{ "Odisha",  "7653",  "Sambalpur", "Kanhu Charan Sanbad", "OverAged",  " ","ओडिशा",  "संबलपुर", "कान्हू चरण सनबाद", " "}, 
{ "Odisha",  "7654",  "Sambalpur", "Atma Ram Supkar", "NotGraduate",  " ","ओडिशा",  "संबलपुर", "एतमा राम सुपकर", " "}, 
{ "Odisha",  "4396",  "Sundargarh", "Jual Oram", "ForeignFunding",  " ","ओडिशा",  "सुंदरगढ़", "जुअल ओराम", " "}, 
{ "Odisha",  "4397",  "Sundargarh", "Miss Juspin Lakra", "CriminalCases",  " ","ओडिशा",  "सुंदरगढ़", "मिस जसपिन लकड़ा", " "}, 
{ "Odisha",  "4398",  "Sundargarh", "Dayananda Bhitria", "NotGraduate",  " ","ओडिशा",  "सुंदरगढ़", "दयानंद भितरिया", " "}, 
{ "Odisha",  "4399",  "Sundargarh", "Udit Chandra Amat", "OverAged",  " ","ओडिशा",  "सुंदरगढ़", "उदित चंद्र अमत", " "}, 
{ "Odisha",  "4401",  "Sundargarh", "Justin Lugun", "NotGraduate",  " ","ओडिशा",  "सुंदरगढ़", "जस्टिन लुगुन", " "}, 
{ "Odisha",  "4402",  "Sundargarh", "Basil Ekka", "NotGraduate",  " ","ओडिशा",  "सुंदरगढ़", "तुलसी एक्का", " "}, 
{ "Odisha",  "4403",  "Sundargarh", "George Tirkey", "ForeignFunding",  " ","ओडिशा",  "सुंदरगढ़", "जॉर्ज तिर्की", " "}, 
};

}