/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Odisha {
public static final String[][] green_bucket = {
{"Odisha",  "4429", "Aska", "Sankar Sahu", "CPI(ML) Red Star", "http://myneta.info/ls2014/candidate.php?candidate_id=4969",  "",  "", "", "", ""}, 
{"Odisha",  "4435", "Aska", "Purna Chandra Nayak", "BSP", "http://myneta.info/ls2014/candidate.php?candidate_id=5872",  "",  "", "", "", ""}, 
{"Odisha",  "4395", "Bargarh", "Kousika Suna", "BSP", "http://myneta.info/ls2014/candidate.php?candidate_id=5875",  "",  "", "", "", ""}, 
{"Odisha",  "4436", "Berhampur", "Tirupati Rao Karanam", "BSP", "http://myneta.info/ls2014/candidate.php?candidate_id=5550",  "",  "", "", "", ""}, 
{"Odisha",  "4438", "Berhampur", "Somanath Behera", "SUCI(C)", "http://myneta.info/ls2014/candidate.php?candidate_id=4704",  "",  "", "", "", ""}, 
{"Odisha",  "4404", "Bolangir", "Dinesh Nag", "Ambedkarite Party of India", "http://myneta.info/ls2014/candidate.php?candidate_id=4972",  "",  "", "", "", ""}, 
{"Odisha",  "4406", "Bolangir", "Suresh Kumar Putel", "Bahujan Mukti Party", "http://myneta.info/ls2014/candidate.php?candidate_id=5876",  "",  "", "", "", ""}, 
{"Odisha",  "4407", "Bolangir", "Hrudananda Karuan", "SUCI(C)", "http://myneta.info/ls2014/candidate.php?candidate_id=4971",  "",  "", "", "", ""}, 
{"Odisha",  "4408", "Bolangir", "Kalikesh Narayan Singh Deo", "BJD", "http://myneta.info/ls2014/candidate.php?candidate_id=5558",  "",  "", "", "", ""}, 
{"Odisha",  "4411", "Bolangir", "Dr Bipin Kusulia", "IND", "http://myneta.info/ls2014/candidate.php?candidate_id=5402",  "",  "", "", "", ""}, 
{"Odisha",  "4413", "Kalahandi", "Chhabilal Nial", "Ambedkarite Party of India", "http://myneta.info/ls2014/candidate.php?candidate_id=4686",  "",  "", "", "", ""}, 
{"Odisha",  "4418", "Kalahandi", "Premananda Bag", "BSP", "http://myneta.info/ls2014/candidate.php?candidate_id=5794",  "",  "", "", "", ""}, 
{"Odisha",  "4425", "Kandhamal", "Amir Nayak", "BSP", "http://myneta.info/ls2014/candidate.php?candidate_id=5880",  "",  "", "", "", ""}, 
{"Odisha",  "4427", "Kandhamal", "Achyutananda Samanta", "BJD", "http://myneta.info/ls2014/candidate.php?candidate_id=5403",  "",  "", "", "", ""}, 
{"Odisha",  "4446", "Koraput", "Banamali Majhi", "Ambedkarite Party of India", "http://myneta.info/ls2014/candidate.php?candidate_id=5870",  "",  "", "", "", ""}, 
{"Odisha",  "4447", "Koraput", "Bhaskar Mutuka", "BSP", "http://myneta.info/ls2014/candidate.php?candidate_id=5869",  "",  "", "", "", ""}, 
{"Odisha",  "4419", "Nabarangpur", "Ramesh Chandra Majhi", "BJD", "http://myneta.info/ls2014/candidate.php?candidate_id=5544",  "",  "", "", "", ""}, 
{"Odisha",  "4421", "Nabarangpur", "Chandradhwaj Majhi", "BSP", "http://myneta.info/ls2014/candidate.php?candidate_id=5543",  "",  "", "", "", ""}, 
{"Odisha",  "4400", "Sundargarh", "Sunita Biswal", "BJD", "http://myneta.info/ls2014/candidate.php?candidate_id=5887",  "",  "", "", "", ""}, 
};

public static final String[][] red_bucket = {
{ "Odisha",  "4428",  "Aska", "Chakradhar Sahu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Odisha",  "4430",  "Aska", "Pramila Bisoyi", "OverAged",  " ","",  "", "", " "}, 
{ "Odisha",  "4431",  "Aska", "K. Shyambabu Subudhi", "OverAged",  " ","",  "", "", " "}, 
{ "Odisha",  "4432",  "Aska", "Rama Krushna Panda", "CriminalCases",  " ","",  "", "", " "}, 
{ "Odisha",  "4433",  "Aska", "Anita Subhadarshini", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4434",  "Aska", "Rajeeb Chandra Khadanga", "CriminalCases",  " ","",  "", "", " "}, 
{ "Odisha",  "4390",  "Bargarh", "Pradeep Kumar Debta", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4391",  "Bargarh", "Prasanna Acharya", "OverAged",  " ","",  "", "", " "}, 
{ "Odisha",  "4392",  "Bargarh", "Suresh Pujari", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4393",  "Bargarh", "Kulamani Urma", "NotGraduate",  " ","",  "", "", " "}, 
{ "Odisha",  "4394",  "Bargarh", "M D Nizamuddin", "CriminalCases",  " ","",  "", "", " "}, 
{ "Odisha",  "4437",  "Berhampur", "Bhrugu Baxipatra", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4439",  "Berhampur", "Chandra Sekhar Sahu", "OverAged",  " ","",  "", "", " "}, 
{ "Odisha",  "4440",  "Berhampur", "Chakradhar Sahu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Odisha",  "4441",  "Berhampur", "V.Chandrasekhar Naidu", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4442",  "Berhampur", "K. Shyambabu Subudhi", "OverAged",  " ","",  "", "", " "}, 
{ "Odisha",  "4443",  "Berhampur", "Srihari Patnaik", "NotGraduate",  " ","",  "", "", " "}, 
{ "Odisha",  "4405",  "Bolangir", "Smt. Sangeeta Kumari Singh Deo", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4409",  "Bolangir", "Rana Nag", "OverAged",  " ","",  "", "", " "}, 
{ "Odisha",  "4410",  "Bolangir", "Samarendra Mishra", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4412",  "Kalahandi", "Basanta Kumar Panda", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4414",  "Kalahandi", "Bhakta Charan Das", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4415",  "Kalahandi", "Hatiram Durga", "NotGraduate",  " ","",  "", "", " "}, 
{ "Odisha",  "4416",  "Kalahandi", "Kamalini Yadav", "NotGraduate",  " ","",  "", "", " "}, 
{ "Odisha",  "4417",  "Kalahandi", "Puspendra Singh Deo", "NotGraduate",  " ","",  "", "", " "}, 
{ "Odisha",  "4423",  "Kandhamal", "Manoj Kumar Acharya", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4424",  "Kandhamal", "Tuna Mallick", "NotGraduate",  " ","",  "", "", " "}, 
{ "Odisha",  "4426",  "Kandhamal", "Mahameghabahan Aira Kharabela Swain", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4444",  "Koraput", "Kausalya Hikaka", "NotGraduate",  " ","",  "", "", " "}, 
{ "Odisha",  "4445",  "Koraput", "Jayaram Pangi", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4448",  "Koraput", "Saptagiri Sankar Ulaka", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4449",  "Koraput", "Damodara Sabar", "OverAged",  " ","",  "", "", " "}, 
{ "Odisha",  "4450",  "Koraput", "Rajendra Kendruka", "CriminalCases",  " ","",  "", "", " "}, 
{ "Odisha",  "4420",  "Nabarangpur", "Balabhadra Majhi", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4422",  "Nabarangpur", "Pradeep Kumar Majhi", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4396",  "Sundargarh", "Jual Oram", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Odisha",  "4397",  "Sundargarh", "Miss Juspin Lakra", "CriminalCases",  " ","",  "", "", " "}, 
{ "Odisha",  "4398",  "Sundargarh", "Dayananda Bhitria", "NotGraduate",  " ","",  "", "", " "}, 
{ "Odisha",  "4399",  "Sundargarh", "Udit Chandra Amat", "OverAged",  " ","",  "", "", " "}, 
{ "Odisha",  "4401",  "Sundargarh", "Justin Lugun", "NotGraduate",  " ","",  "", "", " "}, 
{ "Odisha",  "4402",  "Sundargarh", "Basil Ekka", "NotGraduate",  " ","",  "", "", " "}, 
{ "Odisha",  "4403",  "Sundargarh", "George Tirkey", "ForeignFunding",  " ","",  "", "", " "}, 
};

}