/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Rajasthan {
    public static final String[][] green_bucket = {
            {"Rajasthan", "Ajmer", "Durga Lal Regar", "Bahujan Samaj Party", "4.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9618", "राजस्थान", "अजमेर", "दुर्गा लाल रेगर", "बहुजन समाज पार्टी"},
            {"Rajasthan", "Ajmer", "Vishram Babu", "Ambedkarite Party of India", "2.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11148", "राजस्थान", "अजमेर", "विश्राम बाबू", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Banswara", "Kantilal Roat", "Bhartiya Tribal Party", "12.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9578", "राजस्थान", "बांसवाड़ा", "कांतिलाल रोत", "भारतीय ट्राइबल पार्टी"},
            {"Rajasthan", "Banswara", "Nitesh Damor", "Independent", "30811", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11150", "राजस्थान", "बांसवाड़ा", "नितेश डामोर", "निर्दलीय"},
            {"Rajasthan", "Barmer", "Mula Ram", "Independent", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11154", "राजस्थान", "बाड़मेर", "मुल्ला राम", "निर्दलीय"},
            {"Rajasthan", "Bhilwara", "Pawan Kumar Sharma", "Right to Recall Party", "10.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10974", "राजस्थान", "भीलवाड़ा", "पवन कुमार शर्मा", "राइट टू रिकॉल पार्टी"},
            {"Rajasthan", "Chittorgarh", "Jai Prakash Regar", "Ambedkarite Party of India", "11.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11156", "राजस्थान", "चित्तौड़गढ़", "जय प्रकाश रेगर", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Chittorgarh", "Radha Bhandari", "Communist Party of India", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9568", "राजस्थान", "चित्तौड़गढ़", "राधा भंडारी", "भारतीय कम्युनिस्ट पार्टी"},
            {"Rajasthan", "Jalore", "Bhava Ram", "Independent", "8.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9590", "राजस्थान", "जालोर", "भव राम", "निर्दलीय"},
            {"Rajasthan", "Jalore", "Kapoora Ram Meena", "Independent", "4.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9594", "राजस्थान", "जालोर", "कपूर राम मीणा", "निर्दलीय"},
            {"Rajasthan", "Jalore", "Ram Prasad Jatav", "Ambedkarite Party of India", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9600", "राजस्थान", "जालोर", "राम प्रसाद जाटव", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Jalore", "Mohan Lal", "Independent", "21105", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10718", "राजस्थान", "जालोर", "मोहन लाल", "निर्दलीय"},
            {"Rajasthan", "Jalore", "Dinesh Singh", "Independent", "4.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9593", "राजस्थान", "जालोर", "दिनेश सिंह", "निर्दलीय"},
            {"Rajasthan", "Jhalawar Baran", "Badree Lal", "Bahujan Samaj Party", "3.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9586", "राजस्थान", "झालावाड़", "बद्रीलाल", "बहुजन समाज पार्टी"},
            {"Rajasthan", "Jhalawar Baran", "Abdul Qayyum Siddiqui", "Independent", "14.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10954", "राजस्थान", "झालावाड़", "अब्दुल कय्यूम सिद्दीकी", "निर्दलीय"},
            {"Rajasthan", "Jodhpur", "Amar Singh Kalundha", "Bhartiya Tribal Party", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10959", "राजस्थान", "जोधपुर", "अमर सिंह कालुन्धा", "भारतीय ट्राइबल पार्टी"},
            {"Rajasthan", "Jodhpur", "Moda Ram Meghwal", "Independent", "1.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10962", "राजस्थान", "जोधपुर", "मोडा राम मेघवाल", "निर्दलीय"},
            {"Rajasthan", "Jodhpur", "Vishek Vishnoi", "Independent", "34.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9608", "राजस्थान", "जोधपुर", "विशेक विश्नोई", "निर्दलीय"},
            {"Rajasthan", "Kota", "Hergovind", "Independent", "7.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10784", "राजस्थान", "कोटा", "Hergovind", "निर्दलीय"},
            {"Rajasthan", "Pali", "Hemant Kumar Singhvi", "Independent", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9609", "राजस्थान", "पाली", "हेमंत कुमार सिंघवी", "निर्दलीय"},
            {"Rajasthan", "Pali", "Ramprasad Jatav", "Ambedkarite Party of India", "1.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10703", "राजस्थान", "पाली", "रामप्रसाद जाटव", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Rajsamand", "Jitendra Kumar Khatik", "Independent", "35.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10827", "राजस्थान", "राजसमंद", "जितेंद्र कुमार खटीक", "निर्दलीय"},
            {"Rajasthan", "Rajsamand", "Rakesh Choudhari (Rakesh Samdolav)", "Independent", "16Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10831", "राजस्थान", "राजसमंद", "राकेश चौधरी (राकेश समदोलव)", "निर्दलीय"},
            {"Rajasthan", "Rajsamand", "Neeru Ram Kapri", "Independent", "57.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10830", "राजस्थान", "राजसमंद", "नीरू राम कापरी", "निर्दलीय"},
            {"Rajasthan", "Rajsamand", "Chenaram", "Bahujan Samaj Party", "73.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10826", "राजस्थान", "राजसमंद", "Chenaram", "बहुजन समाज पार्टी"},
            {"Rajasthan", "Tonk Sawai Madhopur", "Laxmi Kant (Bairwa)", "Bahujan Samaj Party", "1.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10820", "राजस्थान", "टोंक-सवाई माधोपुर", "लक्ष्मी कांत (बैरवा)", "बहुजन समाज पार्टी"},
            {"Rajasthan", "Tonk Sawai Madhopur", "Naresh Kumar Atal", "Ambedkarite Party of India", "3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10821", "राजस्थान", "टोंक-सवाई माधोपुर", "नरेश कुमार अटल", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Udaipur", "Harji Lal Meena", "Ambedkarite Party of India", "2.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10706", "राजस्थान", "उदयपुर", "हरजी लाल मीणा", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Udaipur", "Ghanshyam Singh Tawar", "Communist Party of India", "3.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9579", "राजस्थान", "उदयपुर", "घनश्याम सिंह तवर", "भारतीय कम्युनिस्ट पार्टी"},
    };

    public static final String[][] red_bucket = {
            {"Rajasthan", "Ajmer", "Mukesh Gena", "2", " ", "राजस्थान", "अजमेर", "मुकेश गेना", " "},
            {"Rajasthan", "Ajmer", "Soniya Regar", "4", " ", "राजस्थान", "अजमेर", "सोनिया रेगर", " "},
            {"Rajasthan", "Ajmer", "Riju Jhunjhunwala", "1", " ", "राजस्थान", "अजमेर", "रिजु झुनझुनवाला", " "},
            {"Rajasthan", "Ajmer", "Bhagirath Chaudhary", "1", " ", "राजस्थान", "अजमेर", "भागीरथ चौधरी", " "},
            {"Rajasthan", "Ajmer", "Pramod Kumar", "4", " ", "राजस्थान", "अजमेर", "प्रमोद कुमार", " "},
            {"Rajasthan", "Banswara", "Kanakmal Katara", "1", " ", "राजस्थान", "बांसवाड़ा", "कनकमल कटारा", " "},
            {"Rajasthan", "Banswara", "Bapulal", "4", " ", "राजस्थान", "बांसवाड़ा", "Bapulal", " "},
            {"Rajasthan", "Banswara", "Tarachand Bhagora", "1", " ", "राजस्थान", "बांसवाड़ा", "ताराचंद भगोरा", " "},
            {"Rajasthan", "Barmer", "Bheraram Jakhar", "2", " ", "राजस्थान", "बाड़मेर", "भेराराम जाखड़", " "},
            {"Rajasthan", "Barmer", "Ramesh Kumar", "4", " ", "राजस्थान", "बाड़मेर", "रमेश कुमार", " "},
            {"Rajasthan", "Barmer", "Haneef", "4", " ", "राजस्थान", "बाड़मेर", "हनीफ", " "},
            {"Rajasthan", "Barmer", "Kailash Choudhary", "1", " ", "राजस्थान", "बाड़मेर", "कैलाश चौधरी", " "},
            {"Rajasthan", "Barmer", "Manvendra Singh", "1", " ", "राजस्थान", "बाड़मेर", "मानवेन्द्र सिंह", " "},
            {"Rajasthan", "Barmer", "Popatlal", "4", " ", "राजस्थान", "बाड़मेर", "Popatlal", " "},
            {"Rajasthan", "Bhilwara", "Shivlal Gurjar", "2", " ", "राजस्थान", "भीलवाड़ा", "शिवलाल गुर्जर", " "},
            {"Rajasthan", "Bhilwara", "Rampal Sharma", "1", " ", "राजस्थान", "भीलवाड़ा", "रामपाल शर्मा", " "},
            {"Rajasthan", "Bhilwara", "Subhash Chandra Baheria", "1", " ", "राजस्थान", "भीलवाड़ा", "सुभाष चंद्र बहेरिया", " "},
            {"Rajasthan", "Chittorgarh", "Prakash Chandra Meena", "2", " ", "राजस्थान", "चित्तौड़गढ़", "प्रकाश चंद्र मीणा", " "},
            {"Rajasthan", "Chittorgarh", "Jagdish Chandra Sharma", "3", " ", "राजस्थान", "चित्तौड़गढ़", "जगदीश चंद्र शर्मा", " "},
            {"Rajasthan", "Chittorgarh", "Mangilal Meena", "4", " ", "राजस्थान", "चित्तौड़गढ़", "मांगीलाल मीणा", " "},
            {"Rajasthan", "Chittorgarh", "Chandra Prakash", "1", " ", "राजस्थान", "चित्तौड़गढ़", "चंद्र प्रकाश", " "},
            {"Rajasthan", "Chittorgarh", "Gopal Singh Shekhawat", "1", " ", "राजस्थान", "चित्तौड़गढ़", "गोपाल सिंह शेखावत", " "},
            {"Rajasthan", "Chittorgarh", "Gopal Dhakad", "4", " ", "राजस्थान", "चित्तौड़गढ़", "गोपाल धाकड़", " "},
            {"Rajasthan", "Chittorgarh", "Shamshuddin", "3", " ", "राजस्थान", "चित्तौड़गढ़", "Shamshuddin", " "},
            {"Rajasthan", "Chittorgarh", "Gulab Sehlot", "3", " ", "राजस्थान", "चित्तौड़गढ़", "गुलाब सहलोत", " "},
            {"Rajasthan", "Jalore", "Nimbaram", "4", " ", "राजस्थान", "जालोर", "Nimbaram", " "},
            {"Rajasthan", "Jalore", "Devaji Patel", "1", " ", "राजस्थान", "जालोर", "देवजी पटेल", " "},
            {"Rajasthan", "Jalore", "Vijay Shree", "4", " ", "राजस्थान", "जालोर", "विजय श्री", " "},
            {"Rajasthan", "Jalore", "Bheraram Barar Meghwal", "4", " ", "राजस्थान", "जालोर", "भेराराम बरार मेघवाल", " "},
            {"Rajasthan", "Jalore", "Bhanwerlal", "4", " ", "राजस्थान", "जालोर", "Bhanwerlal", " "},
            {"Rajasthan", "Jalore", "Lukaram", "4", " ", "राजस्थान", "जालोर", "Lukaram", " "},
            {"Rajasthan", "Jalore", "Kaluram", "4", " ", "राजस्थान", "जालोर", "Kaluram", " "},
            {"Rajasthan", "Jalore", "Ratan", "1", " ", "राजस्थान", "जालोर", "रतन", " "},
            {"Rajasthan", "Jalore", "Lakharam Choudhary", "4", " ", "राजस्थान", "जालोर", "लखाराम चौधरी", " "},
            {"Rajasthan", "Jalore", "Kheta Ram", "4", " ", "राजस्थान", "जालोर", "खेता राम", " "},
            {"Rajasthan", "Jhalawar Baran", "Prince Kumar", "4", " ", "राजस्थान", "झालावाड़", "राजकुमार कुमार", " "},
            {"Rajasthan", "Jhalawar Baran", "Dushyant", "1", " ", "राजस्थान", "झालावाड़", "दुष्यंत", " "},
            {"Rajasthan", "Jhalawar Baran", "Mohammad Nasir", "4", " ", "राजस्थान", "झालावाड़", "मोहम्मद नासिर", " "},
            {"Rajasthan", "Jhalawar Baran", "Harish Kumar Dhakar", "2", " ", "राजस्थान", "झालावाड़", "हरीश कुमार धाकड़", " "},
            {"Rajasthan", "Jhalawar Baran", "Pramod Kumar", "1", " ", "राजस्थान", "झालावाड़", "प्रमोद कुमार", " "},
            {"Rajasthan", "Jodhpur", "Shambhu Ram", "4", " ", "राजस्थान", "जोधपुर", "शंभु राम", " "},
            {"Rajasthan", "Jodhpur", "Gajendra Singh Shekhawat", "1", " ", "राजस्थान", "जोधपुर", "गजेंद्र सिंह शेखावत", " "},
            {"Rajasthan", "Jodhpur", "Tasleem", "4", " ", "राजस्थान", "जोधपुर", "Tasleem", " "},
            {"Rajasthan", "Jodhpur", "Mukul Chaudhary", "2", " ", "राजस्थान", "जोधपुर", "मुकुल चौधरी", " "},
            {"Rajasthan", "Jodhpur", "Chand Mohammad", "4", " ", "राजस्थान", "जोधपुर", "चांद मोहम्मद", " "},
            {"Rajasthan", "Jodhpur", "Anil Joya Meghwal", "4", " ", "राजस्थान", "जोधपुर", "अनिल जोया मेघवाल", " "},
            {"Rajasthan", "Jodhpur", "Vaibhav Gehlot", "1", " ", "राजस्थान", "जोधपुर", "वैभव गहलोत", " "},
            {"Rajasthan", "Kota", "Mahesh Kumar Raniwal", "4", " ", "राजस्थान", "कोटा", "महेश कुमार रानीवाल", " "},
            {"Rajasthan", "Kota", "Shobha Ram Nirmal", "3", " ", "राजस्थान", "कोटा", "शोभा राम निर्मल", " "},
            {"Rajasthan", "Kota", "Om Birla", "1", " ", "राजस्थान", "कोटा", "ओम बिरला", " "},
            {"Rajasthan", "Kota", "Abdul Asiph", "4", " ", "राजस्थान", "कोटा", "अब्दुल आसिफ", " "},
            {"Rajasthan", "Kota", "Praveen Khandelwal", "4", " ", "राजस्थान", "कोटा", "प्रवीण खंडेलवाल", " "},
            {"Rajasthan", "Kota", "Satish Bhardwaj", "2", " ", "राजस्थान", "कोटा", "सतीश भारद्वाज", " "},
            {"Rajasthan", "Kota", "Somesh Bhatnagar", "2", " ", "राजस्थान", "कोटा", "सोमेश भटनागर", " "},
            {"Rajasthan", "Kota", "Harish Kumar", "3", " ", "राजस्थान", "कोटा", "हरीश कुमार", " "},
            {"Rajasthan", "Kota", "Bhim Singh5", "4", " ", "राजस्थान", "कोटा", "भीम सिंह ५", " "},
            {"Rajasthan", "Kota", "Rajendra Prasad Singor", "2", " ", "राजस्थान", "कोटा", "राजेंद्र प्रसाद सिंगर", " "},
            {"Rajasthan", "Kota", "Keshri Lal", "3", " ", "राजस्थान", "कोटा", "केशरी लाल", " "},
            {"Rajasthan", "Kota", "Sunil", "4", " ", "राजस्थान", "कोटा", "सुनील", " "},
            {"Rajasthan", "Kota", "Ram Narain", "1", " ", "राजस्थान", "कोटा", "राम नारायण", " "},
            {"Rajasthan", "Kota", "Chandra Prakash", "4", " ", "राजस्थान", "कोटा", "चंद्र प्रकाश", " "},
            {"Rajasthan", "Pali", "Badri Ram", "1", " ", "राजस्थान", "पाली", "बद्री राम", " "},
            {"Rajasthan", "Pali", "P. P. Chaudhary", "1", " ", "राजस्थान", "पाली", "पीपी चौधरी", " "},
            {"Rajasthan", "Pali", "Ramlal Mohbarsha", "3", " ", "राजस्थान", "पाली", "रामलाल मोहबाजार", " "},
            {"Rajasthan", "Pali", "Kanhaiyalal Vaishnav", "2", " ", "राजस्थान", "पाली", "कन्हैयालाल वैष्णव", " "},
            {"Rajasthan", "Pali", "Jagdish Chandra", "4", " ", "राजस्थान", "पाली", "जगदीश चंद्र", " "},
            {"Rajasthan", "Pali", "Laxman Kumar", "4", " ", "राजस्थान", "पाली", "लक्ष्मण कुमार", " "},
            {"Rajasthan", "Rajsamand", "Bhanwar Lal Kumawat", "4", " ", "राजस्थान", "राजसमंद", "भंवर लाल कुमावत", " "},
            {"Rajasthan", "Rajsamand", "Bhanwer Lal Mali", "4", " ", "राजस्थान", "राजसमंद", "भंवर लाल माली", " "},
            {"Rajasthan", "Rajsamand", "Diya Kumari", "1", " ", "राजस्थान", "राजसमंद", "दीया कुमारी", " "},
            {"Rajasthan", "Rajsamand", "Mishri Kathat", "3", " ", "राजस्थान", "राजसमंद", "मिश्री कथत", " "},
            {"Rajasthan", "Rajsamand", "Devkinandan (Kaka)", "1", " ", "राजस्थान", "राजसमंद", "देवकीनंदन (काका)", " "},
            {"Rajasthan", "Rajsamand", "Chandra Prakash Tanwar", "4", " ", "राजस्थान", "राजसमंद", "चंद्र प्रकाश तंवर", " "},
            {"Rajasthan", "Tonk Sawai Madhopur", "Mukesh Kumar", "2", " ", "राजस्थान", "टोंक-सवाई माधोपुर", "मुकेश कुमार", " "},
            {"Rajasthan", "Tonk Sawai Madhopur", "Bajrang Lal Meena", "4", " ", "राजस्थान", "टोंक-सवाई माधोपुर", "बजरंग लाल मीणा", " "},
            {"Rajasthan", "Tonk Sawai Madhopur", "Sukhbir Singh Jaunapuria", "1", " ", "राजस्थान", "टोंक-सवाई माधोपुर", "सुखबीर सिंह जौनपुरिया", " "},
            {"Rajasthan", "Tonk Sawai Madhopur", "Ganesh Meena", "4", " ", "राजस्थान", "टोंक-सवाई माधोपुर", "गणेश मीणा", " "},
            {"Rajasthan", "Tonk Sawai Madhopur", "Namonarayan", "1", " ", "राजस्थान", "टोंक-सवाई माधोपुर", "Namonarayan", " "},
            {"Rajasthan", "Tonk Sawai Madhopur", "Prem Lata Banshiwal", "4", " ", "राजस्थान", "टोंक-सवाई माधोपुर", "प्रेम लता बंशीवाल", " "},
            {"Rajasthan", "Udaipur", "Arjunlal Meena", "1", " ", "राजस्थान", "उदयपुर", "अर्जुनलाल मीणा", " "},
            {"Rajasthan", "Udaipur", "Kesu Lal Meena", "4", " ", "राजस्थान", "उदयपुर", "केसू लाल मीणा", " "},
            {"Rajasthan", "Udaipur", "Birdhi Lal Chhanwal", "3", " ", "राजस्थान", "उदयपुर", "बिरधी लाल छनवाल", " "},
            {"Rajasthan", "Udaipur", "Shankerlal", "4", " ", "राजस्थान", "उदयपुर", "Shankerlal", " "},
            {"Rajasthan", "Udaipur", "Parbhulal Meena", "4", " ", "राजस्थान", "उदयपुर", "परभूलाल मीणा", " "},
            {"Rajasthan", "Udaipur", "Raghuvir Singh Meena", "1", " ", "राजस्थान", "उदयपुर", "रघुवीर सिंह मीणा", " "},
            {"Rajasthan", "Udaipur", "Kika Mina", "3", " ", "राजस्थान", "उदयपुर", "काका मीना", " "},
    };

}