/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Rajasthan {
    public static final String[][] green_bucket = {
            {"Rajasthan", "Ajmer", "Durga Lal Regar", "Bahujan Samaj Party", "4.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9618", "राजस्थान", "अजमेर", "दुर्गा लाल रेगर", "बहुजन समाज पार्टी"},
            {"Rajasthan", "Ajmer", "Vishram Babu", "Ambedkarite Party of India", "2.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11148", "राजस्थान", "अजमेर", "विश्राम बाबू", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Alwar", "Anand Kumar Sain", "Independent", "69.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11172", "राजस्थान", "अलवर", "आनंद कुमार सेन", "निर्दलीय"},
            {"Rajasthan", "Alwar", "Pawan Kumar Jain", "Independent", "98.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11685", "राजस्थान", "अलवर", "पवन कुमार जैन", "निर्दलीय"},
            {"Rajasthan", "Alwar", "Gulab Singh", "Poorvanchal Rashtriya Congress", "9.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11684", "राजस्थान", "अलवर", "गुलाब सिंह", "पूर्वांचल राष्ट्रीय कांग्रेस"},
            {"Rajasthan", "Alwar", "Advocate Amit Kumar Gupta", "Independent", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11686", "राजस्थान", "अलवर", "अधिवक्ता अमित कुमार गुप्ता", "निर्दलीय"},
            {"Rajasthan", "Banswara", "Kantilal Roat", "Bhartiya Tribal Party", "12.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9578", "राजस्थान", "बांसवाड़ा", "कांतिलाल रोत", "भारतीय ट्राइबल पार्टी"},
            {"Rajasthan", "Banswara", "Nitesh Damor", "Independent", "30811", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11150", "राजस्थान", "बांसवाड़ा", "नितेश डामोर", "निर्दलीय"},
            {"Rajasthan", "Barmer", "Mula Ram", "Independent", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11154", "राजस्थान", "बाड़मेर", "मुल्ला राम", "निर्दलीय"},
            {"Rajasthan", "Bharatpur", "Purushottam Lal", "Independent", "10.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11532", "राजस्थान", "भरतपुर", "पुरुषोत्तम लाल", "निर्दलीय"},
            {"Rajasthan", "Bharatpur", "Surajmal", "Bahujan Samaj Party", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11535", "राजस्थान", "भरतपुर", "सूरजमल", "बहुजन समाज पार्टी"},
            {"Rajasthan", "Bhilwara", "Pawan Kumar Sharma", "Right to Recall Party", "10.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10974", "राजस्थान", "भीलवाड़ा", "पवन कुमार शर्मा", "राइट टू रिकॉल पार्टी"},
            {"Rajasthan", "Chittorgarh", "Jai Prakash Regar", "Ambedkarite Party of India", "11.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11156", "राजस्थान", "चित्तौड़गढ़", "जय प्रकाश रेगर", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Chittorgarh", "Radha Bhandari", "Communist Party of India", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9568", "राजस्थान", "चित्तौड़गढ़", "राधा भंडारी", "भारतीय कम्युनिस्ट पार्टी"},
            {"Rajasthan", "Churu", "Sukhdev Meghwal", "Independent", "10.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11707", "राजस्थान", "चुरू", "सुखदेव मेघवाल", "निर्दलीय"},
            {"Rajasthan", "Churu", "Sheela Shekhawat", "Independent", "20.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11537", "राजस्थान", "चुरू", "शीला शेखावत", "निर्दलीय"},
            {"Rajasthan", "Churu", "Bishanaram", "Independent", "1.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11706", "राजस्थान", "चुरू", "Bishanaram", "निर्दलीय"},
            {"Rajasthan", "Churu", "Dararam Nayak", "Independent", "5.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11710", "राजस्थान", "चुरू", "दराराम नायक", "निर्दलीय"},
            {"Rajasthan", "Dausa", "Anju Devi Dhanka", "Independent", "71.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11712", "राजस्थान", "दौसा", "अंजू देवी धानका", "निर्दलीय"},
            {"Rajasthan", "Dausa", "Dwarka Prasad", "Bahujan Samaj Party", "1000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11715", "राजस्थान", "दौसा", "द्वारका प्रसाद", "बहुजन समाज पार्टी"},
            {"Rajasthan", "Dausa", "Rinku Kumar Meena", "Peoples Party of India (Democratic)", "1000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11713", "राजस्थान", "दौसा", "रिंकू कुमार मीणा", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
            {"Rajasthan", "Dausa", "Bimla Devi Meena", "Independent", "4.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11541", "राजस्थान", "दौसा", "बिमला देवी मीणा", "निर्दलीय"},
            {"Rajasthan", "Dausa", "Chandra Prakash Meena", "Nationalist Peoples Front", "6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11716", "राजस्थान", "दौसा", "चंद्र प्रकाश मीणा", "राष्ट्रवादी पीपुल्स फ्रंट"},
            {"Rajasthan", "Ganganagar", "Dr. Balkrishan Panwar", "Independent", "73.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11283", "राजस्थान", "गंगानगर", "डॉ। बालकृष्ण पंवार", "निर्दलीय"},
            {"Rajasthan", "Ganganagar", "Bhajan Singh Gharoo", "Independent", "98.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11282", "राजस्थान", "गंगानगर", "भजन सिंह घरू", "निर्दलीय"},
            {"Rajasthan", "Jaipur", "Kuldeep Singh", "Socialist Unity Centre of India (Communist)", "21.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11730", "राजस्थान", "जयपुर", "कुलदीप सिंह", "भारतीय समाजवादी एकता केंद्र (कम्युनिस्ट)"},
            {"Rajasthan", "Jaipur", "Sharad Chand Jain", "Independent", "30.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11729", "राजस्थान", "जयपुर", "शरद चंद जैन", "निर्दलीय"},
            {"Rajasthan", "Jaipur", "Kailash Chand Jagarwal", "Ambedkarite Party of India", "30Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11731", "राजस्थान", "जयपुर", "कैलाश चंद जगरवाल", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Jaipur", "Pankaj Patel", "Independent", "1.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11728", "राजस्थान", "जयपुर", "पंकज पटेल", "निर्दलीय"},
            {"Rajasthan", "Jaipur", "Ram Charan Joshi", "Independent", "16.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11544", "राजस्थान", "जयपुर", "राम चरण जोशी", "निर्दलीय"},
            {"Rajasthan", "Jaipur", "Babita Wadhwani", "Independent", "18.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11291", "राजस्थान", "जयपुर", "बबिता वाधवानी", "निर्दलीय"},
            {"Rajasthan", "Jaipur", "Bhanwar Lal Joshi", "Rashtriya Jansambhavna Party", "9.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11727", "राजस्थान", "जयपुर", "भंवर लाल जोशी", "राष्ट्रीय जनसंवाद पार्टी"},
            {"Rajasthan", "Jaipur", "Prashant Saini", "Independent", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11302", "राजस्थान", "जयपुर", "प्रशांत सैनी", "निर्दलीय"},
            {"Rajasthan", "Jaipur", "Virad Singla", "Independent", "4.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11293", "राजस्थान", "जयपुर", "विरद सिंगला", "निर्दलीय"},
            {"Rajasthan", "Jaipur", "Shobhal Singh", "Independent", "49.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11545", "राजस्थान", "जयपुर", "शोभल सिंह", "निर्दलीय"},
            {"Rajasthan", "Jaipur Rural", "Rajendra Kumar", "Ambedkarite Party of India", "26.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11289", "राजस्थान", "जयपुर ग्रामीण", "राजेंद्र कुमार", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Jaipur Rural", "Banwari Lal", "Independent", "31.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11742", "राजस्थान", "जयपुर ग्रामीण", "बनवारी लाल", "निर्दलीय"},
            {"Rajasthan", "Jaipur Rural", "Vinod Sharma", "Independent", "63.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11741", "राजस्थान", "जयपुर ग्रामीण", "विनोद शर्मा", "निर्दलीय"},
            {"Rajasthan", "Jalore", "Bhava Ram", "Independent", "8.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9590", "राजस्थान", "जालोर", "भव राम", "निर्दलीय"},
            {"Rajasthan", "Jalore", "Kapoora Ram Meena", "Independent", "4.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9594", "राजस्थान", "जालोर", "कपूर राम मीणा", "निर्दलीय"},
            {"Rajasthan", "Jalore", "Ram Prasad Jatav", "Ambedkarite Party of India", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9600", "राजस्थान", "जालोर", "राम प्रसाद जाटव", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Jalore", "Mohan Lal", "Independent", "21105", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10718", "राजस्थान", "जालोर", "मोहन लाल", "निर्दलीय"},
            {"Rajasthan", "Jalore", "Dinesh Singh", "Independent", "4.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9593", "राजस्थान", "जालोर", "दिनेश सिंह", "निर्दलीय"},
            {"Rajasthan", "Jhalawar Baran", "Badree Lal", "Bahujan Samaj Party", "3.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9586", "राजस्थान", "झालावाड़", "बद्रीलाल", "बहुजन समाज पार्टी"},
            {"Rajasthan", "Jhalawar Baran", "Abdul Qayyum Siddiqui", "Independent", "14.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10954", "राजस्थान", "झालावाड़", "अब्दुल कय्यूम सिद्दीकी", "निर्दलीय"},
            {"Rajasthan", "Jhunjhunu", "Dr. Tejpal", "Right to Recall Party", "6.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11563", "राजस्थान", "झुंझुनू", "डॉ। तेजपाल", "राइट टू रिकॉल पार्टी"},
            {"Rajasthan", "Jhunjhunu", "Ajay Pal", "Bahujan Mukti Party", "3.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11751", "राजस्थान", "झुंझुनू", "अजय पाल", "बहुजन मुक्ति पार्टी"},
            {"Rajasthan", "Jhunjhunu", "Mohd. Yunus", "Independent", "5.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11236", "राजस्थान", "झुंझुनू", "मोहम्मद। यूनुस", "निर्दलीय"},
            {"Rajasthan", "Jodhpur", "Amar Singh Kalundha", "Bhartiya Tribal Party", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10959", "राजस्थान", "जोधपुर", "अमर सिंह कालुन्धा", "भारतीय ट्राइबल पार्टी"},
            {"Rajasthan", "Jodhpur", "Moda Ram Meghwal", "Independent", "1.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10962", "राजस्थान", "जोधपुर", "मोडा राम मेघवाल", "निर्दलीय"},
            {"Rajasthan", "Jodhpur", "Vishek Vishnoi", "Independent", "34.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9608", "राजस्थान", "जोधपुर", "विशेक विश्नोई", "निर्दलीय"},
            {"Rajasthan", "Karauli Dholpur", "Jeet Ram Bairwa", "Ambedkarite Party of India", "2.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11756", "राजस्थान", "करौली-धौलपुर", "जीत राम बैरवा", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Karauli Dholpur", "Ramkumar", "Bahujan Samaj Party", "35Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11565", "राजस्थान", "करौली-धौलपुर", "रामकुमार", "बहुजन समाज पार्टी"},
            {"Rajasthan", "Kota", "Hergovind", "Independent", "7.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10784", "राजस्थान", "कोटा", "Hergovind", "निर्दलीय"},
            {"Rajasthan", "Nagaur", "Sohanaram Rathi", "Independent", "88.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11568", "राजस्थान", "नागौर", "सोहनराम राठी", "निर्दलीय"},
            {"Rajasthan", "Nagaur", "Hanuman Beniwal", "Rashtriya Loktantrik Party", "42.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11760", "राजस्थान", "नागौर", "हनुमान बेनीवाल", "राष्ट्रीय लोकतांत्रिक पार्टी"},
            {"Rajasthan", "Nagaur", "Ravindra Singh Shekhawat", "Independent", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11238", "राजस्थान", "नागौर", "रवींद्र सिंह शेखावत", "निर्दलीय"},
            {"Rajasthan", "Nagaur", "Rastra Putra Hindu", "Independent", "68.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11759", "राजस्थान", "नागौर", "रस्त्र पुत्रा हिंदू", "निर्दलीय"},
            {"Rajasthan", "Nagaur", "Saroj Prajapat", "Independent", "83.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11761", "राजस्थान", "नागौर", "सरोज प्रजापत", "निर्दलीय"},
            {"Rajasthan", "Pali", "Hemant Kumar Singhvi", "Independent", "1.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9609", "राजस्थान", "पाली", "हेमंत कुमार सिंघवी", "निर्दलीय"},
            {"Rajasthan", "Pali", "Ramprasad Jatav", "Ambedkarite Party of India", "1.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10703", "राजस्थान", "पाली", "रामप्रसाद जाटव", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Rajsamand", "Jitendra Kumar Khatik", "Independent", "35.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10827", "राजस्थान", "राजसमंद", "जितेंद्र कुमार खटीक", "निर्दलीय"},
            {"Rajasthan", "Rajsamand", "Rakesh Choudhari (Rakesh Samdolav)", "Independent", "16Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10831", "राजस्थान", "राजसमंद", "राकेश चौधरी (राकेश समदोलव)", "निर्दलीय"},
            {"Rajasthan", "Rajsamand", "Neeru Ram Kapri", "Independent", "57.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10830", "राजस्थान", "राजसमंद", "नीरू राम कापरी", "निर्दलीय"},
            {"Rajasthan", "Rajsamand", "Chenaram", "Bahujan Samaj Party", "73.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10826", "राजस्थान", "राजसमंद", "Chenaram", "बहुजन समाज पार्टी"},
            {"Rajasthan", "Sikar", "Bhagirath Singh Kharrte Bhadhadar", "Independent", "50.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11772", "राजस्थान", "सीकर", "भागीरथ सिंह खर्राटे भदधर", "निर्दलीय"},
            {"Rajasthan", "Sikar", "Vikas Kumar", "Independent", "16000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11770", "राजस्थान", "सीकर", "विकास कुमार", "निर्दलीय"},
            {"Rajasthan", "Sikar", "Amraram", "Communist Party of India (Marxist)", "44.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11571", "राजस्थान", "सीकर", "Amraram", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
            {"Rajasthan", "Sikar", "Ankur Sharma", "Independent", "2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11241", "राजस्थान", "सीकर", "अंकुर शर्मा", "निर्दलीय"},
            {"Rajasthan", "Tonk Sawai Madhopur", "Laxmi Kant (Bairwa)", "Bahujan Samaj Party", "1.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10820", "राजस्थान", "टोंक-सवाई माधोपुर", "लक्ष्मी कांत (बैरवा)", "बहुजन समाज पार्टी"},
            {"Rajasthan", "Tonk Sawai Madhopur", "Naresh Kumar Atal", "Ambedkarite Party of India", "3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10821", "राजस्थान", "टोंक-सवाई माधोपुर", "नरेश कुमार अटल", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Udaipur", "Harji Lal Meena", "Ambedkarite Party of India", "2.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10706", "राजस्थान", "उदयपुर", "हरजी लाल मीणा", "भारत की अम्बेडकरवादी पार्टी"},
            {"Rajasthan", "Udaipur", "Ghanshyam Singh Tawar", "Communist Party of India", "3.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9579", "राजस्थान", "उदयपुर", "घनश्याम सिंह तवर", "भारतीय कम्युनिस्ट पार्टी"},
    };

    public static final String[][] red_bucket = {
            {"Rajasthan", "Ajmer", "Mukesh Gena", "2", " ", "राजस्थान", "अजमेर", "मुकेश गेना", " "},
            {"Rajasthan", "Ajmer", "Soniya Regar", "4", " ", "राजस्थान", "अजमेर", "सोनिया रेगर", " "},
            {"Rajasthan", "Ajmer", "Riju Jhunjhunwala", "1", " ", "राजस्थान", "अजमेर", "रिजु झुनझुनवाला", " "},
            {"Rajasthan", "Ajmer", "Bhagirath Chaudhary", "1", " ", "राजस्थान", "अजमेर", "भागीरथ चौधरी", " "},
            {"Rajasthan", "Ajmer", "Pramod Kumar", "4", " ", "राजस्थान", "अजमेर", "प्रमोद कुमार", " "},
            {"Rajasthan", "Alwar", "Madan Lal", "4", " ", "राजस्थान", "अलवर", "मदन लाल", " "},
            {"Rajasthan", "Alwar", "Mahant Balak Nath", "1", " ", "राजस्थान", "अलवर", "महंत बालक नाथ", " "},
            {"Rajasthan", "Alwar", "Tilak Raj Munjal", "3", " ", "राजस्थान", "अलवर", "तिलक राज मुंजाल", " "},
            {"Rajasthan", "Alwar", "Jitendra Singh", "1", " ", "राजस्थान", "अलवर", "जितेंद्र सिंह", " "},
            {"Rajasthan", "Alwar", "Imran Khan", "4", " ", "राजस्थान", "अलवर", "इमरान खान", " "},
            {"Rajasthan", "Alwar", "Anoop Kumar", "4", " ", "राजस्थान", "अलवर", "अनूप कुमार", " "},
            {"Rajasthan", "Alwar", "Amit Sharma Jangir", "4", " ", "राजस्थान", "अलवर", "अमित शर्मा जांगिड़", " "},
            {"Rajasthan", "Banswara", "Kanakmal Katara", "1", " ", "राजस्थान", "बांसवाड़ा", "कनकमल कटारा", " "},
            {"Rajasthan", "Banswara", "Bapulal", "4", " ", "राजस्थान", "बांसवाड़ा", "Bapulal", " "},
            {"Rajasthan", "Banswara", "Tarachand Bhagora", "1", " ", "राजस्थान", "बांसवाड़ा", "ताराचंद भगोरा", " "},
            {"Rajasthan", "Barmer", "Bheraram Jakhar", "2", " ", "राजस्थान", "बाड़मेर", "भेराराम जाखड़", " "},
            {"Rajasthan", "Barmer", "Ramesh Kumar", "4", " ", "राजस्थान", "बाड़मेर", "रमेश कुमार", " "},
            {"Rajasthan", "Barmer", "Haneef", "4", " ", "राजस्थान", "बाड़मेर", "हनीफ", " "},
            {"Rajasthan", "Barmer", "Kailash Choudhary", "1", " ", "राजस्थान", "बाड़मेर", "कैलाश चौधरी", " "},
            {"Rajasthan", "Barmer", "Manvendra Singh", "1", " ", "राजस्थान", "बाड़मेर", "मानवेन्द्र सिंह", " "},
            {"Rajasthan", "Barmer", "Popatlal", "4", " ", "राजस्थान", "बाड़मेर", "Popatlal", " "},
            {"Rajasthan", "Bharatpur", "Ranjeeta Kumari", "1", " ", "राजस्थान", "भरतपुर", "रंजीता कुमारी", " "},
            {"Rajasthan", "Bharatpur", "Sunil", "4", " ", "राजस्थान", "भरतपुर", "सुनील", " "},
            {"Rajasthan", "Bharatpur", "Ghanshyam Singh Yadav", "3", " ", "राजस्थान", "भरतपुर", "घनश्याम सिंह यादव", " "},
            {"Rajasthan", "Bharatpur", "Abhijeet Kumar", "1", " ", "राजस्थान", "भरतपुर", "अभिजीत कुमार", " "},
            {"Rajasthan", "Bharatpur", "Mangal Ram Godra", "3", " ", "राजस्थान", "भरतपुर", "मंगल राम गोदरा", " "},
            {"Rajasthan", "Bharatpur", "Tejveer Singh", "4", " ", "राजस्थान", "भरतपुर", "तेजवीर सिंह", " "},
            {"Rajasthan", "Bhilwara", "Shivlal Gurjar", "2", " ", "राजस्थान", "भीलवाड़ा", "शिवलाल गुर्जर", " "},
            {"Rajasthan", "Bhilwara", "Rampal Sharma", "1", " ", "राजस्थान", "भीलवाड़ा", "रामपाल शर्मा", " "},
            {"Rajasthan", "Bhilwara", "Subhash Chandra Baheria", "1", " ", "राजस्थान", "भीलवाड़ा", "सुभाष चंद्र बहेरिया", " "},
            {"Rajasthan", "Bikaner", "Punamchand", "4", " ", "राजस्थान", "बीकानेर", "Punamchand", " "},
            {"Rajasthan", "Bikaner", "Shyopat Ram", "2", " ", "राजस्थान", "बीकानेर", "श्योपत राम", " "},
            {"Rajasthan", "Bikaner", "Bhaira Ram", "4", " ", "राजस्थान", "बीकानेर", "भैरा राम", " "},
            {"Rajasthan", "Bikaner", "Triloki Narayan Hatila", "4", " ", "राजस्थान", "बीकानेर", "त्रिलोकी नारायण हटिला", " "},
            {"Rajasthan", "Bikaner", "Madan Gopal", "1", " ", "राजस्थान", "बीकानेर", "मदन गोपाल", " "},
            {"Rajasthan", "Bikaner", "Arjunram", "4", " ", "राजस्थान", "बीकानेर", "Arjunram", " "},
            {"Rajasthan", "Bikaner", "Arjun Ram Meghwal", "1", " ", "राजस्थान", "बीकानेर", "अर्जुन राम मेघवाल", " "},
            {"Rajasthan", "Bikaner", "Ghanshyam Meghwal", "4", " ", "राजस्थान", "बीकानेर", "घनश्याम मेघवाल", " "},
            {"Rajasthan", "Bikaner", "Babulal", "4", " ", "राजस्थान", "बीकानेर", "बाबूलाल", " "},
            {"Rajasthan", "Chittorgarh", "Prakash Chandra Meena", "2", " ", "राजस्थान", "चित्तौड़गढ़", "प्रकाश चंद्र मीणा", " "},
            {"Rajasthan", "Chittorgarh", "Jagdish Chandra Sharma", "3", " ", "राजस्थान", "चित्तौड़गढ़", "जगदीश चंद्र शर्मा", " "},
            {"Rajasthan", "Chittorgarh", "Mangilal Meena", "4", " ", "राजस्थान", "चित्तौड़गढ़", "मांगीलाल मीणा", " "},
            {"Rajasthan", "Chittorgarh", "Chandra Prakash", "1", " ", "राजस्थान", "चित्तौड़गढ़", "चंद्र प्रकाश", " "},
            {"Rajasthan", "Chittorgarh", "Gopal Singh Shekhawat", "1", " ", "राजस्थान", "चित्तौड़गढ़", "गोपाल सिंह शेखावत", " "},
            {"Rajasthan", "Chittorgarh", "Gopal Dhakad", "4", " ", "राजस्थान", "चित्तौड़गढ़", "गोपाल धाकड़", " "},
            {"Rajasthan", "Chittorgarh", "Shamshuddin", "3", " ", "राजस्थान", "चित्तौड़गढ़", "Shamshuddin", " "},
            {"Rajasthan", "Chittorgarh", "Gulab Sehlot", "3", " ", "राजस्थान", "चित्तौड़गढ़", "गुलाब सहलोत", " "},
            {"Rajasthan", "Churu", "Rafique Mandelia", "1", " ", "राजस्थान", "चुरू", "रफीक मंडेलिया", " "},
            {"Rajasthan", "Churu", "Rahul Kaswan", "1", " ", "राजस्थान", "चुरू", "राहुल कस्वां", " "},
            {"Rajasthan", "Churu", "Satyapal Bauddh", "4", " ", "राजस्थान", "चुरू", "सत्यपाल बुड्ढा", " "},
            {"Rajasthan", "Churu", "Balwan Poonia", "2", " ", "राजस्थान", "चुरू", "बलवान पूनिया", " "},
            {"Rajasthan", "Churu", "Kumbharam Meena", "4", " ", "राजस्थान", "चुरू", "कुंभाराम मीणा", " "},
            {"Rajasthan", "Churu", "Gomati Dharampal Kataria", "4", " ", "राजस्थान", "चुरू", "गोमती धर्मपाल कटारिया", " "},
            {"Rajasthan", "Churu", "Hari Singh", "4", " ", "राजस्थान", "चुरू", "हरि सिंह", " "},
            {"Rajasthan", "Churu", "Aslam", "4", " ", "राजस्थान", "चुरू", "असलम", " "},
            {"Rajasthan", "Dausa", "Jaskaur Meena", "1", " ", "राजस्थान", "दौसा", "जसकौर मीणा", " "},
            {"Rajasthan", "Dausa", "Maliram Nayaka", "3", " ", "राजस्थान", "दौसा", "मालीराम नायक", " "},
            {"Rajasthan", "Dausa", "Savita Meena", "1", " ", "राजस्थान", "दौसा", "सविता मीणा", " "},
            {"Rajasthan", "Dausa", "Radhey Shyam Meena", "4", " ", "राजस्थान", "दौसा", "राधेश्याम मीणा", " "},
            {"Rajasthan", "Dausa", "Bharti Meena", "2", " ", "राजस्थान", "दौसा", "भारती मीणा", " "},
            {"Rajasthan", "Dausa", "Ramphool Meena", "4", " ", "राजस्थान", "दौसा", "रामफूल मीणा", " "},
            {"Rajasthan", "Ganganagar", "Naresh Kumar", "4", " ", "राजस्थान", "गंगानगर", "नरेश कुमार", " "},
            {"Rajasthan", "Ganganagar", "Bharat Ram Meghwal", "1", " ", "राजस्थान", "गंगानगर", "भरत राम मेघवाल", " "},
            {"Rajasthan", "Ganganagar", "Satish Kumar", "4", " ", "राजस्थान", "गंगानगर", "सतीश कुमार", " "},
            {"Rajasthan", "Ganganagar", "Nihal Chand", "1", " ", "राजस्थान", "गंगानगर", "निहाल चंद", " "},
            {"Rajasthan", "Ganganagar", "Ravtaram", "3", " ", "राजस्थान", "गंगानगर", "Ravtaram", " "},
            {"Rajasthan", "Ganganagar", "Lunarama", "4", " ", "राजस्थान", "गंगानगर", "Lunarama", " "},
            {"Rajasthan", "Ganganagar", "Titara Singh", "3", " ", "राजस्थान", "गंगानगर", "तितारा सिंह", " "},
            {"Rajasthan", "Jaipur", "Manoj Kumar Joshi", "4", " ", "राजस्थान", "जयपुर", "मनोज कुमार जोशी", " "},
            {"Rajasthan", "Jaipur", "Yogesh Sharma", "3", " ", "राजस्थान", "जयपुर", "योगेश शर्मा", " "},
            {"Rajasthan", "Jaipur", "P. Trilok Tiwari (Trilok Tiwari)", "4", " ", "राजस्थान", "जयपुर", "पी। त्रिलोक तिवारी (त्रिलोक तिवारी)", " "},
            {"Rajasthan", "Jaipur", "R. S. Meena Kalky", "2", " ", "राजस्थान", "जयपुर", "आरएस मीणा कल्कि", " "},
            {"Rajasthan", "Jaipur", "Haripal Bairwa", "4", " ", "राजस्थान", "जयपुर", "हरिपाल बैरवा", " "},
            {"Rajasthan", "Jaipur", "Vinay Kumar Varma", "4", " ", "राजस्थान", "जयपुर", "विनय कुमार वर्मा", " "},
            {"Rajasthan", "Jaipur", "Ramlal Dhanaka", "4", " ", "राजस्थान", "जयपुर", "रामलाल धनाका", " "},
            {"Rajasthan", "Jaipur", "Ram Janki Swami", "4", " ", "राजस्थान", "जयपुर", "राम जानकी स्वामी", " "},
            {"Rajasthan", "Jaipur", "Ram Charan Bohra", "1", " ", "राजस्थान", "जयपुर", "राम चरण बोहरा", " "},
            {"Rajasthan", "Jaipur", "Umrao Salodia", "2", " ", "राजस्थान", "जयपुर", "उमराव सालोदिया", " "},
            {"Rajasthan", "Jaipur", "Jyoti Khandelwal", "1", " ", "राजस्थान", "जयपुर", "ज्योति खंडेलवाल", " "},
            {"Rajasthan", "Jaipur", "Kamal Bhargav", "4", " ", "राजस्थान", "जयपुर", "कमल भार्गव", " "},
            {"Rajasthan", "Jaipur", "Sanjay Garg", "4", " ", "राजस्थान", "जयपुर", "संजय गर्ग", " "},
            {"Rajasthan", "Jaipur", "Yakub Khan", "4", " ", "राजस्थान", "जयपुर", "याकूब खान", " "},
            {"Rajasthan", "Jaipur Rural", "Krishna Poonia", "1", " ", "राजस्थान", "जयपुर ग्रामीण", "कृष्णा पूनिया", " "},
            {"Rajasthan", "Jaipur Rural", "Ram Singh Kasana", "4", " ", "राजस्थान", "जयपुर ग्रामीण", "राम सिंह कसाना", " "},
            {"Rajasthan", "Jaipur Rural", "Col. Rajyavardhan Rathore", "1", " ", "राजस्थान", "जयपुर ग्रामीण", "कर्नल राज्यवर्धन राठौर", " "},
            {"Rajasthan", "Jaipur Rural", "Ram Niwas", "4", " ", "राजस्थान", "जयपुर ग्रामीण", "राम निवास", " "},
            {"Rajasthan", "Jaipur Rural", "Virender Singh", "4", " ", "राजस्थान", "जयपुर ग्रामीण", "वीरेंद्र सिंह", " "},
            {"Rajasthan", "Jalore", "Nimbaram", "4", " ", "राजस्थान", "जालोर", "Nimbaram", " "},
            {"Rajasthan", "Jalore", "Devaji Patel", "1", " ", "राजस्थान", "जालोर", "देवजी पटेल", " "},
            {"Rajasthan", "Jalore", "Vijay Shree", "4", " ", "राजस्थान", "जालोर", "विजय श्री", " "},
            {"Rajasthan", "Jalore", "Bheraram Barar Meghwal", "4", " ", "राजस्थान", "जालोर", "भेराराम बरार मेघवाल", " "},
            {"Rajasthan", "Jalore", "Bhanwerlal", "4", " ", "राजस्थान", "जालोर", "Bhanwerlal", " "},
            {"Rajasthan", "Jalore", "Lukaram", "4", " ", "राजस्थान", "जालोर", "Lukaram", " "},
            {"Rajasthan", "Jalore", "Kaluram", "4", " ", "राजस्थान", "जालोर", "Kaluram", " "},
            {"Rajasthan", "Jalore", "Ratan", "1", " ", "राजस्थान", "जालोर", "रतन", " "},
            {"Rajasthan", "Jalore", "Lakharam Choudhary", "4", " ", "राजस्थान", "जालोर", "लखाराम चौधरी", " "},
            {"Rajasthan", "Jalore", "Kheta Ram", "4", " ", "राजस्थान", "जालोर", "खेता राम", " "},
            {"Rajasthan", "Jhalawar Baran", "Prince Kumar", "4", " ", "राजस्थान", "झालावाड़", "राजकुमार कुमार", " "},
            {"Rajasthan", "Jhalawar Baran", "Dushyant", "1", " ", "राजस्थान", "झालावाड़", "दुष्यंत", " "},
            {"Rajasthan", "Jhalawar Baran", "Mohammad Nasir", "4", " ", "राजस्थान", "झालावाड़", "मोहम्मद नासिर", " "},
            {"Rajasthan", "Jhalawar Baran", "Harish Kumar Dhakar", "2", " ", "राजस्थान", "झालावाड़", "हरीश कुमार धाकड़", " "},
            {"Rajasthan", "Jhalawar Baran", "Pramod Kumar", "1", " ", "राजस्थान", "झालावाड़", "प्रमोद कुमार", " "},
            {"Rajasthan", "Jhunjhunu", "Narendra Kumar", "1", " ", "राजस्थान", "झुंझुनू", "नरेंद्र कुमार", " "},
            {"Rajasthan", "Jhunjhunu", "Sharwan Kumar", "1", " ", "राजस्थान", "झुंझुनू", "शरवन कुमार", " "},
            {"Rajasthan", "Jhunjhunu", "Sharwan Kumar S/O Hukma Ram", "4", " ", "राजस्थान", "झुंझुनू", "शरवन कुमार एस / ओ हुकमा राम", " "},
            {"Rajasthan", "Jhunjhunu", "Bhim Singh", "3", " ", "राजस्थान", "झुंझुनू", "भीम सिंह", " "},
            {"Rajasthan", "Jhunjhunu", "Kailash Karwasara", "4", " ", "राजस्थान", "झुंझुनू", "कैलाश करवासरा", " "},
            {"Rajasthan", "Jhunjhunu", "Mahant Akash Giri", "4", " ", "राजस्थान", "झुंझुनू", "महंत आकाश गिरि", " "},
            {"Rajasthan", "Jhunjhunu", "Bal Dev Prasad Saini", "4", " ", "राजस्थान", "झुंझुनू", "बाल देव प्रसाद सैनी", " "},
            {"Rajasthan", "Jhunjhunu", "Krishan Kumar", "4", " ", "राजस्थान", "झुंझुनू", "कृष्ण कुमार", " "},
            {"Rajasthan", "Jhunjhunu", "Guru Gokulchand Rashtarwadi", "3", " ", "राजस्थान", "झुंझुनू", "गुरु गोकुलचंद रश्तरवाड़ी", " "},
            {"Rajasthan", "Jodhpur", "Shambhu Ram", "4", " ", "राजस्थान", "जोधपुर", "शंभु राम", " "},
            {"Rajasthan", "Jodhpur", "Gajendra Singh Shekhawat", "1", " ", "राजस्थान", "जोधपुर", "गजेंद्र सिंह शेखावत", " "},
            {"Rajasthan", "Jodhpur", "Tasleem", "4", " ", "राजस्थान", "जोधपुर", "Tasleem", " "},
            {"Rajasthan", "Jodhpur", "Mukul Chaudhary", "2", " ", "राजस्थान", "जोधपुर", "मुकुल चौधरी", " "},
            {"Rajasthan", "Jodhpur", "Chand Mohammad", "4", " ", "राजस्थान", "जोधपुर", "चांद मोहम्मद", " "},
            {"Rajasthan", "Jodhpur", "Anil Joya Meghwal", "4", " ", "राजस्थान", "जोधपुर", "अनिल जोया मेघवाल", " "},
            {"Rajasthan", "Jodhpur", "Vaibhav Gehlot", "1", " ", "राजस्थान", "जोधपुर", "वैभव गहलोत", " "},
            {"Rajasthan", "Karauli Dholpur", "Sanjay Kumar", "1", " ", "राजस्थान", "करौली-धौलपुर", "संजय कुमार", " "},
            {"Rajasthan", "Karauli Dholpur", "Vijay Babu", "4", " ", "राजस्थान", "करौली-धौलपुर", "विजय बाबू", " "},
            {"Rajasthan", "Karauli Dholpur", "Manoj Rajoria", "1", " ", "राजस्थान", "करौली-धौलपुर", "मनोज राजोरिया", " "},
            {"Rajasthan", "Kota", "Mahesh Kumar Raniwal", "4", " ", "राजस्थान", "कोटा", "महेश कुमार रानीवाल", " "},
            {"Rajasthan", "Kota", "Shobha Ram Nirmal", "3", " ", "राजस्थान", "कोटा", "शोभा राम निर्मल", " "},
            {"Rajasthan", "Kota", "Om Birla", "1", " ", "राजस्थान", "कोटा", "ओम बिरला", " "},
            {"Rajasthan", "Kota", "Abdul Asiph", "4", " ", "राजस्थान", "कोटा", "अब्दुल आसिफ", " "},
            {"Rajasthan", "Kota", "Praveen Khandelwal", "4", " ", "राजस्थान", "कोटा", "प्रवीण खंडेलवाल", " "},
            {"Rajasthan", "Kota", "Satish Bhardwaj", "2", " ", "राजस्थान", "कोटा", "सतीश भारद्वाज", " "},
            {"Rajasthan", "Kota", "Somesh Bhatnagar", "2", " ", "राजस्थान", "कोटा", "सोमेश भटनागर", " "},
            {"Rajasthan", "Kota", "Harish Kumar", "3", " ", "राजस्थान", "कोटा", "हरीश कुमार", " "},
            {"Rajasthan", "Kota", "Bhim Singh5", "4", " ", "राजस्थान", "कोटा", "भीम सिंह ५", " "},
            {"Rajasthan", "Kota", "Rajendra Prasad Singor", "2", " ", "राजस्थान", "कोटा", "राजेंद्र प्रसाद सिंगर", " "},
            {"Rajasthan", "Kota", "Keshri Lal", "3", " ", "राजस्थान", "कोटा", "केशरी लाल", " "},
            {"Rajasthan", "Kota", "Sunil", "4", " ", "राजस्थान", "कोटा", "सुनील", " "},
            {"Rajasthan", "Kota", "Ram Narain", "1", " ", "राजस्थान", "कोटा", "राम नारायण", " "},
            {"Rajasthan", "Kota", "Chandra Prakash", "4", " ", "राजस्थान", "कोटा", "चंद्र प्रकाश", " "},
            {"Rajasthan", "Nagaur", "Madanalal", "4", " ", "राजस्थान", "नागौर", "Madanalal", " "},
            {"Rajasthan", "Nagaur", "Dharmendra", "4", " ", "राजस्थान", "नागौर", "धर्मेंद्र", " "},
            {"Rajasthan", "Nagaur", "Ram Chandra", "4", " ", "राजस्थान", "नागौर", "राम चंद्र", " "},
            {"Rajasthan", "Nagaur", "Dr. Jyoti Mirdha", "1", " ", "राजस्थान", "नागौर", "डॉ। ज्योति मिर्धा", " "},
            {"Rajasthan", "Nagaur", "Hanuman Ram", "4", " ", "राजस्थान", "नागौर", "हनुमान राम", " "},
            {"Rajasthan", "Nagaur", "Prem Raj", "4", " ", "राजस्थान", "नागौर", "प्रेम राज", " "},
            {"Rajasthan", "Nagaur", "Shiv Narayan", "2", " ", "राजस्थान", "नागौर", "शिव नारायण", " "},
            {"Rajasthan", "Nagaur", "Dharmi Chand", "4", " ", "राजस्थान", "नागौर", "धर्म चंद", " "},
            {"Rajasthan", "Pali", "Badri Ram", "1", " ", "राजस्थान", "पाली", "बद्री राम", " "},
            {"Rajasthan", "Pali", "P. P. Chaudhary", "1", " ", "राजस्थान", "पाली", "पीपी चौधरी", " "},
            {"Rajasthan", "Pali", "Ramlal Mohbarsha", "3", " ", "राजस्थान", "पाली", "रामलाल मोहबाजार", " "},
            {"Rajasthan", "Pali", "Kanhaiyalal Vaishnav", "2", " ", "राजस्थान", "पाली", "कन्हैयालाल वैष्णव", " "},
            {"Rajasthan", "Pali", "Jagdish Chandra", "4", " ", "राजस्थान", "पाली", "जगदीश चंद्र", " "},
            {"Rajasthan", "Pali", "Laxman Kumar", "4", " ", "राजस्थान", "पाली", "लक्ष्मण कुमार", " "},
            {"Rajasthan", "Rajsamand", "Bhanwar Lal Kumawat", "4", " ", "राजस्थान", "राजसमंद", "भंवर लाल कुमावत", " "},
            {"Rajasthan", "Rajsamand", "Bhanwer Lal Mali", "4", " ", "राजस्थान", "राजसमंद", "भंवर लाल माली", " "},
            {"Rajasthan", "Rajsamand", "Diya Kumari", "1", " ", "राजस्थान", "राजसमंद", "दीया कुमारी", " "},
            {"Rajasthan", "Rajsamand", "Mishri Kathat", "3", " ", "राजस्थान", "राजसमंद", "मिश्री कथत", " "},
            {"Rajasthan", "Rajsamand", "Devkinandan (Kaka)", "1", " ", "राजस्थान", "राजसमंद", "देवकीनंदन (काका)", " "},
            {"Rajasthan", "Rajsamand", "Chandra Prakash Tanwar", "4", " ", "राजस्थान", "राजसमंद", "चंद्र प्रकाश तंवर", " "},
            {"Rajasthan", "Sikar", "Subhash Maharia", "1", " ", "राजस्थान", "सीकर", "सुभाष महरिया", " "},
            {"Rajasthan", "Sikar", "Bhagwan Sahay", "4", " ", "राजस्थान", "सीकर", "भगवान सहाय", " "},
            {"Rajasthan", "Sikar", "Ajaypal", "4", " ", "राजस्थान", "सीकर", "Ajaypal", " "},
            {"Rajasthan", "Sikar", "Sumedhanand Saraswati", "1", " ", "राजस्थान", "सीकर", "सुमेधानंद सरस्वती", " "},
            {"Rajasthan", "Sikar", "Shiv Bhagawan", "2", " ", "राजस्थान", "सीकर", "शिवभगवान", " "},
            {"Rajasthan", "Sikar", "Sita Devi", "4", " ", "राजस्थान", "सीकर", "सीता देवी", " "},
            {"Rajasthan", "Sikar", "Vijendra Kumar", "4", " ", "राजस्थान", "सीकर", "विजयेंद्र कुमार", " "},
            {"Rajasthan", "Sikar", "Bansilal Kataria", "4", " ", "राजस्थान", "सीकर", "बंसीलाल कटारिया", " "},
            {"Rajasthan", "Tonk Sawai Madhopur", "Mukesh Kumar", "2", " ", "राजस्थान", "टोंक-सवाई माधोपुर", "मुकेश कुमार", " "},
            {"Rajasthan", "Tonk Sawai Madhopur", "Bajrang Lal Meena", "4", " ", "राजस्थान", "टोंक-सवाई माधोपुर", "बजरंग लाल मीणा", " "},
            {"Rajasthan", "Tonk Sawai Madhopur", "Sukhbir Singh Jaunapuria", "1", " ", "राजस्थान", "टोंक-सवाई माधोपुर", "सुखबीर सिंह जौनपुरिया", " "},
            {"Rajasthan", "Tonk Sawai Madhopur", "Ganesh Meena", "4", " ", "राजस्थान", "टोंक-सवाई माधोपुर", "गणेश मीणा", " "},
            {"Rajasthan", "Tonk Sawai Madhopur", "Namonarayan", "1", " ", "राजस्थान", "टोंक-सवाई माधोपुर", "Namonarayan", " "},
            {"Rajasthan", "Tonk Sawai Madhopur", "Prem Lata Banshiwal", "4", " ", "राजस्थान", "टोंक-सवाई माधोपुर", "प्रेम लता बंशीवाल", " "},
            {"Rajasthan", "Udaipur", "Arjunlal Meena", "1", " ", "राजस्थान", "उदयपुर", "अर्जुनलाल मीणा", " "},
            {"Rajasthan", "Udaipur", "Kesu Lal Meena", "4", " ", "राजस्थान", "उदयपुर", "केसू लाल मीणा", " "},
            {"Rajasthan", "Udaipur", "Birdhi Lal Chhanwal", "3", " ", "राजस्थान", "उदयपुर", "बिरधी लाल छनवाल", " "},
            {"Rajasthan", "Udaipur", "Shankerlal", "4", " ", "राजस्थान", "उदयपुर", "Shankerlal", " "},
            {"Rajasthan", "Udaipur", "Parbhulal Meena", "4", " ", "राजस्थान", "उदयपुर", "परभूलाल मीणा", " "},
            {"Rajasthan", "Udaipur", "Raghuvir Singh Meena", "1", " ", "राजस्थान", "उदयपुर", "रघुवीर सिंह मीणा", " "},
            {"Rajasthan", "Udaipur", "Kika Mina", "3", " ", "राजस्थान", "उदयपुर", "काका मीना", " "},
    };

}