/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Telangana {
public static final String[][] green_bucket = {
{"Telangana",  "5280", "Adilabad", "Godam Nagesh", "TRS", "http://myneta.info/ls2014/candidate.php?candidate_id=5814",  "",  "", "", "", ""}, 
{"Telangana",  "5281", "Adilabad", "Pawar Krishna", "IND", "http://myneta.info/ls2014/candidate.php?candidate_id=5824",  "",  "", "", "", ""}, 
{"Telangana",  "5284", "Adilabad", "Nethavath Ramdas", "IND", "http://myneta.info/ls2014/candidate.php?candidate_id=5823",  "",  "", "", "", ""}, 
{"Telangana",  "5286", "Adilabad", "Ganta Pentanna", "IND", "http://myneta.info/ls2014/candidate.php?candidate_id=5813",  "",  "", "", "", ""}, 
{"Telangana",  "5287", "Adilabad", "Dharavth Narendhar", "Janasena Party", "http://myneta.info/ls2014/candidate.php?candidate_id=5815",  "",  "", "", "", ""}, 
{"Telangana",  "5972", "Bhongir", "Samrat Narender Boilla", "RPI", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6861",  "",  "", "", "", ""}, 
{"Telangana",  "5977", "Bhongir", "Dr. Narsaiah Boora", "TRS", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5089",  "",  "", "", "", ""}, 
{"Telangana",  "5979", "Bhongir", "Sapavat Devaram", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6867",  "",  "", "", "", ""}, 
{"Telangana",  "5981", "Bhongir", "Moorigaadi Krishna", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6860",  "",  "", "", "", ""}, 
{"Telangana",  "5899", "Chevella", "Sanem Raju Goud", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6829",  "",  "", "", "", ""}, 
{"Telangana",  "5900", "Chevella", "Anusha Keshavabhatla", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6818",  "",  "", "", "", ""}, 
{"Telangana",  "5904", "Chevella", "Ija Venkatesh Goud", "Social Justice Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6823",  "",  "", "", "", ""}, 
{"Telangana",  "5906", "Chevella", "P. Purushotham", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6826",  "",  "", "", "", ""}, 
{"Telangana",  "5908", "Chevella", "T. Durga Prasad", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6830",  "",  "", "", "", ""}, 
{"Telangana",  "5910", "Chevella", "Dr.Gaddam Ranjith Reddy", "TRS", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4846",  "",  "", "", "", ""}, 
{"Telangana",  "5914", "Chevella", "Ragam Sathesh Yadav", "AIFB", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6828",  "",  "", "", "", ""}, 
{"Telangana",  "5920", "Chevella", "Vanam Sudhakar", "Marxist Communist Party of India (United)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6831",  "",  "", "", "", ""}, 
{"Telangana",  "5921", "Chevella", "G. Ravi Kumar Yadav", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6822",  "",  "", "", "", ""}, 
{"Telangana",  "5891", "Hyderabad", "V Bal Krishna", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6804",  "",  "", "", "", ""}, 
{"Telangana",  "5885", "Hyderabad", "Pusthe Srikanth", "TRS", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6800",  "",  "", "", "", ""}, 
{"Telangana",  "5308", "Karimnagar", "Vinod Kumar Boianapalli", "TRS", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4593",  "",  "", "", "", ""}, 
{"Telangana",  "5309", "Karimnagar", "Chintha Anil Kumar", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4592",  "",  "", "", "", ""}, 
{"Telangana",  "5314", "Karimnagar", "Rameshbabu Shanigarapu", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4827",  "",  "", "", "", ""}, 
{"Telangana",  "5318", "Karimnagar", "Palle Prashanth", "Jai Swaraj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4633",  "",  "", "", "", ""}, 
{"Telangana",  "5320", "Karimnagar", "Reddy Venugopal", "Samajwadi Forward Bloc", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6277",  "",  "", "", "", ""}, 
{"Telangana",  "6014", "Khammam", "Mutyam Arjuna Raju", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6905",  "",  "", "", "", ""}, 
{"Telangana",  "6017", "Khammam", "Lakavath Nageswara Rao", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6896",  "",  "", "", "", ""}, 
{"Telangana",  "6020", "Khammam", "Boda Venkat", "CPI(M)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4868",  "",  "", "", "", ""}, 
{"Telangana",  "6021", "Khammam", "Umamaheswara Rao Cherukupalli", "Telangana Yuva Shakti", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6892",  "",  "", "", "", ""}, 
{"Telangana",  "6023", "Khammam", "Dunuku Veladri", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6902",  "",  "", "", "", ""}, 
{"Telangana",  "6025", "Khammam", "Narala Satyanarayana", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6895",  "",  "", "", "", ""}, 
{"Telangana",  "6028", "Khammam", "Shankara Rao Gopagani", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6901",  "",  "", "", "", ""}, 
{"Telangana",  "6002", "Mahabubabad", "Balsingh Daravath", "Bhartiya Anarakshit Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6880",  "",  "", "", "", ""}, 
{"Telangana",  "6003", "Mahabubabad", "Parvathi Bhukya", "Pyramid Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4646",  "",  "", "", "", ""}, 
{"Telangana",  "6004", "Mahabubabad", "Bhaskar Naik Bhukya.", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6883",  "",  "", "", "", ""}, 
{"Telangana",  "6005", "Mahabubabad", "Vaditya Shriram Naik", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6890",  "",  "", "", "", ""}, 
{"Telangana",  "6007", "Mahabubabad", "Palvancha. Durga.", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6888",  "",  "", "", "", ""}, 
{"Telangana",  "6012", "Mahabubabad", "Balu Nayak Bhukya", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6881",  "",  "", "", "", ""}, 
{"Telangana",  "5924", "Mahbubnagar", "Vishweshwar J", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6835",  "",  "", "", "", ""}, 
{"Telangana",  "5929", "Mahbubnagar", "Md. Abdul Azeez Khan", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4668",  "",  "", "", "", ""}, 
{"Telangana",  "5932", "Mahbubnagar", "Pola Prashanth Kumar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4606",  "",  "", "", "", ""}, 
{"Telangana",  "5933", "Mahbubnagar", "Mohammed Imtiyaz Ahmad", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4607",  "",  "", "", "", ""}, 
{"Telangana",  "5844", "Malkajgiri", "Donthula Bikshapathi", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6777",  "",  "", "", "", ""}, 
{"Telangana",  "5846", "Malkajgiri", "Rajender Ponnala", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7242",  "",  "", "", "", ""}, 
{"Telangana",  "5847", "Malkajgiri", "Balamani Buru", "India Praja Bandhu Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6774",  "",  "", "", "", ""}, 
{"Telangana",  "5850", "Malkajgiri", "Sai Kiran Gone", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6779",  "",  "", "", "", ""}, 
{"Telangana",  "5855", "Malkajgiri", "Chalika Chandra Sekhar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4664",  "",  "", "", "", ""}, 
{"Telangana",  "5835", "Medak", "Kallu Narsimlu Goud", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6768",  "",  "", "", "", ""}, 
{"Telangana",  "5839", "Medak", "Bharatesh", "SUCI(C)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6765",  "",  "", "", "", ""}, 
{"Telangana",  "5840", "Medak", "Kotha Prabhakar Reddy", "TRS", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5079",  "",  "", "", "", ""}, 
{"Telangana",  "5940", "Nagarkurnool", "Gaddam Vijay Kumar", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5787",  "",  "", "", "", ""}, 
{"Telangana",  "5945", "Nalgonda", "Jakkula Naveen Yadav", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6847",  "",  "", "", "", ""}, 
{"Telangana",  "5947", "Nalgonda", "Mekala Satheesh Reddy", "Janasena Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6841",  "",  "", "", "", ""}, 
{"Telangana",  "5948", "Nalgonda", "Royyala Srinivasulu", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6857",  "",  "", "", "", ""}, 
{"Telangana",  "5949", "Nalgonda", "Lingidi Venkateswarlu", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6858",  "",  "", "", "", ""}, 
{"Telangana",  "5951", "Nalgonda", "Vemireddy Narasimha Reddy", "TRS", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6838",  "",  "", "", "", ""}, 
{"Telangana",  "5953", "Nalgonda", "Ramesh Sunkara", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6856",  "",  "", "", "", ""}, 
{"Telangana",  "5955", "Nalgonda", "Katravath Venkatesh", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6839",  "",  "", "", "", ""}, 
{"Telangana",  "5958", "Nalgonda", "Lithesh Sunkari", "Social Justice Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6843",  "",  "", "", "", ""}, 
{"Telangana",  "5963", "Nalgonda", "Thagulla Janardhan", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6848",  "",  "", "", "", ""}, 
{"Telangana",  "5964", "Nalgonda", "Bandaru Nagaraju", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6852",  "",  "", "", "", ""}, 
{"Telangana",  "5968", "Nalgonda", "Sreenu Vadthya", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4864",  "",  "", "", "", ""}, 
{"Telangana",  "5970", "Nalgonda", "Janaiah Nandipati", "Telangana Sakalajanula Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6840",  "",  "", "", "", ""}, 
{"Telangana",  "5645", "Nizamabad", "Yellala Rajitha", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6750",  "",  "", "", "", ""}, 
{"Telangana",  "5646", "Nizamabad", "Raj Kumar Sunkari", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6700",  "",  "", "", "", ""}, 
{"Telangana",  "5661", "Nizamabad", "Katipelli Ramesh", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6638",  "",  "", "", "", ""}, 
{"Telangana",  "5674", "Nizamabad", "Ganga Reddy Kallem", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6618",  "",  "", "", "", ""}, 
{"Telangana",  "5678", "Nizamabad", "Kanaka Pramod", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6634",  "",  "", "", "", ""}, 
{"Telangana",  "5684", "Nizamabad", "S. Sagar", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6714",  "",  "", "", "", ""}, 
{"Telangana",  "5693", "Nizamabad", "Madhu Butti", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6655",  "",  "", "", "", ""}, 
{"Telangana",  "5694", "Nizamabad", "Shankar Yenugu", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6723",  "",  "", "", "", ""}, 
{"Telangana",  "5701", "Nizamabad", "Talari Suman", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6736",  "",  "", "", "", ""}, 
{"Telangana",  "5706", "Nizamabad", "Dabba Raja Reddy", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6344",  "",  "", "", "", ""}, 
{"Telangana",  "5707", "Nizamabad", "Ayileni Vikram Reddy", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6322",  "",  "", "", "", ""}, 
{"Telangana",  "5719", "Nizamabad", "Limbaiah Somidi", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6649",  "",  "", "", "", ""}, 
{"Telangana",  "5720", "Nizamabad", "N. Omkar Reddy", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6683",  "",  "", "", "", ""}, 
{"Telangana",  "5721", "Nizamabad", "Mamidi Rajashekar Reddy", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6664",  "",  "", "", "", ""}, 
{"Telangana",  "5723", "Nizamabad", "Thota Srinivas", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6742",  "",  "", "", "", ""}, 
{"Telangana",  "5726", "Nizamabad", "Gaddam Mohan", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6607",  "",  "", "", "", ""}, 
{"Telangana",  "5739", "Nizamabad", "Mohan Chintala Palli", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6674",  "",  "", "", "", ""}, 
{"Telangana",  "5740", "Nizamabad", "Gaddam Purushotham", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6608",  "",  "", "", "", ""}, 
{"Telangana",  "5744", "Nizamabad", "Suresh Basa", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6733",  "",  "", "", "", ""}, 
{"Telangana",  "5752", "Nizamabad", "Sanjeeva Reddy Gaddam", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6718",  "",  "", "", "", ""}, 
{"Telangana",  "5756", "Nizamabad", "Raju Somireddy", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6707",  "",  "", "", "", ""}, 
{"Telangana",  "5758", "Nizamabad", "Baddam Srinivasa Reddy", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6328",  "",  "", "", "", ""}, 
{"Telangana",  "5759", "Nizamabad", "Sama Thirupathi", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4654",  "",  "", "", "", ""}, 
{"Telangana",  "5765", "Nizamabad", "Praveen Neeradi", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6698",  "",  "", "", "", ""}, 
{"Telangana",  "5786", "Nizamabad", "Mohd Jameel", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6676",  "",  "", "", "", ""}, 
{"Telangana",  "5795", "Nizamabad", "Sunketa Ravi", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6730",  "",  "", "", "", ""}, 
{"Telangana",  "5797", "Nizamabad", "Akula Hanmandlu", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6313",  "",  "", "", "", ""}, 
{"Telangana",  "5817", "Nizamabad", "Nomula Gopal Reddy", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4655",  "",  "", "", "", ""}, 
{"Telangana",  "5293", "Peddapalle", "Bala Kalyan Panja", "BSP", "http://myneta.info/ls2014/candidate.php?candidate_id=6216",  "",  "", "", "", ""}, 
{"Telangana",  "5295", "Peddapalle", "Erugurala Bhagya Laxmi", "Pyramid Party of India", "http://myneta.info/ls2014/candidate.php?candidate_id=4631",  "",  "", "", "", ""}, 
{"Telangana",  "5296", "Peddapalle", "Rajesh Erikilla", "IND", "http://myneta.info/ls2014/candidate.php?candidate_id=7239",  "",  "", "", "", ""}, 
{"Telangana",  "5297", "Peddapalle", "Venkatesh Netha Borlakunta", "TRS", "http://myneta.info/ls2014/candidate.php?candidate_id=5071",  "",  "", "", "", ""}, 
{"Telangana",  "5298", "Peddapalle", "Durgam. Rajanna", "IND", "http://myneta.info/ls2014/candidate.php?candidate_id=4649",  "",  "", "", "", ""}, 
{"Telangana",  "5302", "Peddapalle", "Thadem Raj Prakash", "India Praja Bandhu Party", "http://myneta.info/ls2014/candidate.php?candidate_id=4591",  "",  "", "", "", ""}, 
{"Telangana",  "5862", "Secunderabad", "Boddu Satish", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6797",  "",  "", "", "", ""}, 
{"Telangana",  "5864", "Secunderabad", "Nandipati Vinod Kumar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6799",  "",  "", "", "", ""}, 
{"Telangana",  "5866", "Secunderabad", "Mallesh Jatavath", "SUCI(C)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5085",  "",  "", "", "", ""}, 
{"Telangana",  "5869", "Secunderabad", "Meesala Gopal Sai Baba", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4840",  "",  "", "", "", ""}, 
{"Telangana",  "5873", "Secunderabad", "Andukuri Vijaya Bhaskar", "India Praja Bandhu Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6790",  "",  "", "", "", ""}, 
{"Telangana",  "5874", "Secunderabad", "Ravi Kumar Vodela", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6784",  "",  "", "", "", ""}, 
{"Telangana",  "5876", "Secunderabad", "J . N . Rao", "Dalita Bahujana Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6798",  "",  "", "", "", ""}, 
{"Telangana",  "5877", "Secunderabad", "Challa Ram Kalyan", "Bhartiya Anarakshit Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6789",  "",  "", "", "", ""}, 
{"Telangana",  "5880", "Secunderabad", "Akhil Chirravuri", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6791",  "",  "", "", "", ""}, 
{"Telangana",  "5881", "Secunderabad", "M . Ashok Kumar", "Samajwadi Forward Bloc", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6788",  "",  "", "", "", ""}, 
{"Telangana",  "5882", "Secunderabad", "Andrapu Sudharshan Gangaputra", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6795",  "",  "", "", "", ""}, 
{"Telangana",  "5987", "Warangal", "Dayakar Pasnori", "TRS", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5094",  "",  "", "", "", ""}, 
{"Telangana",  "5988", "Warangal", "Upendar Jeripothula", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5778",  "",  "", "", "", ""}, 
{"Telangana",  "5990", "Warangal", "Bollapally Saraiah", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6870",  "",  "", "", "", ""}, 
{"Telangana",  "5991", "Warangal", "Barla Srinivas", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5783",  "",  "", "", "", ""}, 
{"Telangana",  "5998", "Warangal", "Bochu Krupakar", "Hum Bhartiya Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6873",  "",  "", "", "", ""}, 
{"Telangana",  "5823", "Zahirabad", "Ramarao Patil", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6757",  "",  "", "", "", ""}, 
{"Telangana",  "5825", "Zahirabad", "Alige Jeevan", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6759",  "",  "", "", "", ""}, 
{"Telangana",  "5829", "Zahirabad", "Nangunoori Lata", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6755",  "",  "", "", "", ""}, 
{"Telangana",  "5830", "Zahirabad", "Benjamin Raju", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6752",  "",  "", "", "", ""}, 
{"Telangana",  "5833", "Zahirabad", "Kalesh", "Bhartiya Anarakshit Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7243",  "",  "", "", "", ""}, 
};

public static final String[][] red_bucket = {
{ "Telangana",  "5282",  "Adilabad", "Aare Ellanna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5283",  "Adilabad", "Kumra Raju", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5285",  "Adilabad", "Ramesh Rathod", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5288",  "Adilabad", "Bapu Rao Soyam", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5289",  "Adilabad", "Bheem Rao", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5290",  "Adilabad", "Kumram Vandana", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5973",  "Bhongir", "Sirivolu Venkata Ramana Rao", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5974",  "Bhongir", "Komatireddy Venakat Reddy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5975",  "Bhongir", "Goda Sriramulu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5976",  "Bhongir", "Kotha Kistaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5978",  "Bhongir", "Padala Venkata Shyam Sunder Rao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5980",  "Bhongir", "Sriramulu Muthyala", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5982",  "Bhongir", "Bheemanaboina Ramesh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5983",  "Bhongir", "Singapaka Lingam", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5901",  "Chevella", "Nalla Prem Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5902",  "Chevella", "Yedla Suresh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5903",  "Chevella", "Bennala Julee", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5905",  "Chevella", "Palamakula Madhu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5907",  "Chevella", "Baswaiah Madiga", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5909",  "Chevella", "Vijay Aarya", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5911",  "Chevella", "A.A. Sabri", "OverAged",  " ","",  "", "", " "}, 
{ "Telangana",  "5912",  "Chevella", "Gurram Papi Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5913",  "Chevella", "B. Janardhan Reddy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5915",  "Chevella", "Kummari Giri", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5916",  "Chevella", "Konda Vishweshwar Reddy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5917",  "Chevella", "Korra Pandu Naik", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5918",  "Chevella", "Chepuri Raju", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5919",  "Chevella", "Jaidupally Yadaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5888",  "Hyderabad", "Mohammed Abdul Azeem", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5889",  "Hyderabad", "Bhagavanth Rao Pawar", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5890",  "Hyderabad", "Dornala Jaya Prakash", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5892",  "Hyderabad", "L Ashok Nath", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5893",  "Hyderabad", "Sanjay Kumar Shukla", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5894",  "Hyderabad", "K Rangacharya", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5895",  "Hyderabad", "Mohd Ahmed", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5896",  "Hyderabad", "Asaduddin Owaisi", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5897",  "Hyderabad", "K. Nagaraj", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5898",  "Hyderabad", "Mohammed Feroz Khan", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5884",  "Hyderabad", "Dr.Hingolikar Susheel Raj", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5886",  "Hyderabad", "Beeramganti Venkat Ramesh Naidu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5887",  "Hyderabad", "Ka Maheshwar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5310",  "Karimnagar", "Ponnam Prabhakar", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5311",  "Karimnagar", "Bhanu Laxman Pabba", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5312",  "Karimnagar", "Aila Prasanna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5313",  "Karimnagar", "Durvasa Reddy Pakala", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5315",  "Karimnagar", "Kota Shyamkumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5316",  "Karimnagar", "Anagandula Venkanna", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5317",  "Karimnagar", "Mukkisa Ratnakar Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5319",  "Karimnagar", "Srikanth Chiliveru", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5321",  "Karimnagar", "Gangarapu Thirupathi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5322",  "Karimnagar", "Bandi Sanjay Kumar", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "6013",  "Khammam", "Avutapalli Rambabu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "6015",  "Khammam", "Gugulothu Ramesh", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "6016",  "Khammam", "Koppula Sreenivasa Rao", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "6018",  "Khammam", "Venkateshwar Rao Pullakandam", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "6019",  "Khammam", "Gokinapalli Venkateswarlu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "6022",  "Khammam", "Katta Srinivas", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "6024",  "Khammam", "Parsagani Nageswara Rao", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "6026",  "Khammam", "Anil Kumar Maddineni", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "6027",  "Khammam", "Nakirikanti Sanjeeva Rao", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "6029",  "Khammam", "Gopoju Ramesh Babu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "6030",  "Khammam", "Renuka Chowdhury", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "6031",  "Khammam", "Devaki Vasudeva Rao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "6032",  "Khammam", "Laxmana Chary Bhanala", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "6033",  "Khammam", "Banoth Laxma Naik", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "6034",  "Khammam", "Nama Nageswr Rao", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "6035",  "Khammam", "Palvancha Rama Rao", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5999",  "Mahabubabad", "Uke Kousalya", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "6000",  "Mahabubabad", "Jatothu Hussain", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "6001",  "Mahabubabad", "Kalluri. Venkateswara Rao", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "6006",  "Mahabubabad", "Kalthi Yarraiah", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "6008",  "Mahabubabad", "Arun Kumar Mypathi", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "6009",  "Mahabubabad", "Mokalla. Murali Krishna", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "6010",  "Mahabubabad", "Kavitha Malothu", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "6011",  "Mahabubabad", "Balaram Naik Porika", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5922",  "Mahbubnagar", "Manne Srinivas Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5923",  "Mahbubnagar", "Challa Vamshi Chand Reddy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5925",  "Mahbubnagar", "S Gopal Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5926",  "Mahbubnagar", "V Dasram", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5927",  "Mahbubnagar", "Ergamreddy Shivadurgavaraprasad Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5928",  "Mahbubnagar", "Imran Ahmed Khan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5930",  "Mahbubnagar", "D. K. Aruna", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5931",  "Mahbubnagar", "D Thimmappa", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5845",  "Malkajgiri", "Ramchander Rao N", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5848",  "Malkajgiri", "Mahender Reddy Bongunoori", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5849",  "Malkajgiri", "Dharmasanam Bhanumurthy", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5851",  "Malkajgiri", "Rajashekar Reddy Marri", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5852",  "Malkajgiri", "Chamakura Rajaiah", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5853",  "Malkajgiri", "Anumula Revanth Reddy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5854",  "Malkajgiri", "Thirupataiah Enduram", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5834",  "Medak", "Gajabinkar Bansilal", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5836",  "Medak", "Madavaneni Raghunandan Rao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5837",  "Medak", "Anil Kumar Gali", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5838",  "Medak", "Merige Santhosh Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5841",  "Medak", "Bangaru Krishna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5842",  "Medak", "Madhava Reddy Gari Hanmantha Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5843",  "Medak", "Thummalapally Pruthviraj", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5934",  "Nagarkurnool", "Baaki Renuka", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5935",  "Nagarkurnool", "B Yosef", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5936",  "Nagarkurnool", "Pothuganti Ramulu", "OverAged",  " ","",  "", "", " "}, 
{ "Telangana",  "5937",  "Nagarkurnool", "Charagonda Krishnamma", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5938",  "Nagarkurnool", "Shruthi Bangaru", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5939",  "Nagarkurnool", "Dr Mallu Ravi", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5941",  "Nagarkurnool", "Srinivasulu Buddula", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5942",  "Nagarkurnool", "V Amarnath", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5943",  "Nagarkurnool", "Prabhudas Bandaru Thumu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5944",  "Nagarkurnool", "Karvanga Sharath", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5946",  "Nalgonda", "Mallu Laxmi", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5950",  "Nalgonda", "Nalamada Uttam Kumar Reddy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5952",  "Nalgonda", "Marri. Nehemiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5954",  "Nalgonda", "Solipuram Venugopal Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5956",  "Nalgonda", "Lalu Naik Ramavath", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5957",  "Nalgonda", "Thandu Upender", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5959",  "Nalgonda", "Karamtothu Mangtha", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5960",  "Nalgonda", "Polishetty Venkateshwarlu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5961",  "Nalgonda", "Madhu Sapavath", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5962",  "Nalgonda", "Maram Venkat Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5965",  "Nalgonda", "Mekala Venkanna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5966",  "Nalgonda", "Akula Paul", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5967",  "Nalgonda", "Kiran Vangapalli", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5969",  "Nalgonda", "Nakirikanti. Chittemma", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5971",  "Nalgonda", "Garlapati Jithendra Kumar", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5640",  "Nizamabad", "Tummala Naveen", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5641",  "Nizamabad", "Pundra Srinivas Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5642",  "Nizamabad", "Mahender Nalimela", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5643",  "Nizamabad", "Asli Ganesh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5644",  "Nizamabad", "Kondhapuram Narsaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5647",  "Nizamabad", "Thirupathi Gaddam", "OverAged",  " ","",  "", "", " "}, 
{ "Telangana",  "5648",  "Nizamabad", "Sujith Gadepalli", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5649",  "Nizamabad", "Ettedi Saireddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5650",  "Nizamabad", "Vinay Tankasaala", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5651",  "Nizamabad", "Gummerla Vijay", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5652",  "Nizamabad", "Anugu Thirumal", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5653",  "Nizamabad", "Kumbala Sanjeeva Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5654",  "Nizamabad", "Lingapuram Bhumeshwar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5655",  "Nizamabad", "Enugu Mallesh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5656",  "Nizamabad", "Nalla Nadipi Muthenna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5657",  "Nizamabad", "Macharla Prathap", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5658",  "Nizamabad", "Maggidi Narsaiah Mamidi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5659",  "Nizamabad", "Theegala Thirupathi Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5660",  "Nizamabad", "Bakkashetti Ganagdhar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5662",  "Nizamabad", "Gaddam Gangareddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5663",  "Nizamabad", "Srinivas Gundeti", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5664",  "Nizamabad", "Soma Srinivas", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5665",  "Nizamabad", "Bodugam Narender", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5666",  "Nizamabad", "Raja Venkat Reddy Pashapu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5667",  "Nizamabad", "Linga Reddy Santha", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5668",  "Nizamabad", "Gujjula Ramesh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5669",  "Nizamabad", "Mahesh Rayidi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5670",  "Nizamabad", "Maggidi Katipally Rajesh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5671",  "Nizamabad", "Venkatesh Kola", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5672",  "Nizamabad", "Sai Reddy Puttiniti", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5673",  "Nizamabad", "Admala Mahipal Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5675",  "Nizamabad", "Kongari Sanjiv", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5676",  "Nizamabad", "Swami Reddy Sama", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5677",  "Nizamabad", "Gangareddy Mailaram", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5679",  "Nizamabad", "N Mallareddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5680",  "Nizamabad", "Nomula Mohan Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5681",  "Nizamabad", "Ganga Reddy Peesu Peesu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5682",  "Nizamabad", "Mittapally Jeevan Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5683",  "Nizamabad", "Madhusudan Alias Madhu Goud Yaskhi", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5685",  "Nizamabad", "Theetla Anil", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5686",  "Nizamabad", "Gangareddy Musku", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5687",  "Nizamabad", "M. Malla Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5688",  "Nizamabad", "Rajareddi Rikkala", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5689",  "Nizamabad", "Santhosh Kamareddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5690",  "Nizamabad", "K Kavitha", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5691",  "Nizamabad", "Rajendar Pasapu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5692",  "Nizamabad", "Baddam Devendar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5695",  "Nizamabad", "Nemilla Linga Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5696",  "Nizamabad", "Sama Bhaskar Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5697",  "Nizamabad", "Gaddam Rajeshwar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5698",  "Nizamabad", "Kommula Buchireddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5699",  "Nizamabad", "Bejjenki Linga Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5700",  "Nizamabad", "Aleti Malla Reddy", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5702",  "Nizamabad", "Pedda Gangaram Turpu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5703",  "Nizamabad", "Gadepalli Prthviraj", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5704",  "Nizamabad", "Chinthalapally Raghupathi Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5705",  "Nizamabad", "Rapelly Srinivas", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5708",  "Nizamabad", "Natta Bavanna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5709",  "Nizamabad", "Venkat Reddy Jaidi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5710",  "Nizamabad", "Edamala Ravinder Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5711",  "Nizamabad", "Hanmandlu Puppala", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5712",  "Nizamabad", "Gaddam Rajendharreddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5713",  "Nizamabad", "Muthenna Lakkara", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5714",  "Nizamabad", "Penta Narsaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5715",  "Nizamabad", "Gadepally Ramesh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5716",  "Nizamabad", "Balije Laxmirajam", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5717",  "Nizamabad", "Ravindhar Bandi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5718",  "Nizamabad", "Rotte Chakradhar Sharma", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5722",  "Nizamabad", "Laxman Ganna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5724",  "Nizamabad", "Rajashekar Sarikela", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5725",  "Nizamabad", "Aare Sayanna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5727",  "Nizamabad", "Pedda Gangadar Talari", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5728",  "Nizamabad", "Gaddam Suman", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5729",  "Nizamabad", "Linga Reddy Doddikindi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5730",  "Nizamabad", "Aleti Rajareddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5731",  "Nizamabad", "Prakash Manchiryala", "OverAged",  " ","",  "", "", " "}, 
{ "Telangana",  "5732",  "Nizamabad", "Kandukala Shiva Kumar Goud", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5733",  "Nizamabad", "Mandala Shekhar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5734",  "Nizamabad", "Aloori Anil Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5735",  "Nizamabad", "Bathnathe Shankar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5736",  "Nizamabad", "Limba Reddy Perkit", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5737",  "Nizamabad", "Narsareddy Pannala", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5738",  "Nizamabad", "Kurma Divakar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5741",  "Nizamabad", "Komati Reddy Prashanth", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5742",  "Nizamabad", "Loka Subhash", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5743",  "Nizamabad", "Mamidi Thirupathireddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5745",  "Nizamabad", "Nadisharam Mallaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5746",  "Nizamabad", "Gadkolu Ramesh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5747",  "Nizamabad", "Santosh Komamula", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5748",  "Nizamabad", "Urumalla Lakshma Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5749",  "Nizamabad", "Nadipi Gangaram Niradi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5750",  "Nizamabad", "Alakunta Rajanna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5751",  "Nizamabad", "Suresh Baddam", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5753",  "Nizamabad", "Nagulapalli Devendhar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5754",  "Nizamabad", "Mekkonda Ramreddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5755",  "Nizamabad", "Mittapalli Malliah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5757",  "Nizamabad", "Jaidi Chinna Gangaram", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5760",  "Nizamabad", "Goskula Mahesh Babu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5761",  "Nizamabad", "Anjaiah Kondani", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5762",  "Nizamabad", "Ganganna Chilkuri", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5763",  "Nizamabad", "Santosh Barla", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5764",  "Nizamabad", "Dharmapuri Arvind", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5766",  "Nizamabad", "Gangadhar Baddam", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5767",  "Nizamabad", "Gangareddy Thorthi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5768",  "Nizamabad", "Ramesh Reddy Sama", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5769",  "Nizamabad", "Turaga Narsareddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5770",  "Nizamabad", "Baddam Indrasena Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5771",  "Nizamabad", "Guradi Srinivas", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5772",  "Nizamabad", "K. Ram Raj", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5773",  "Nizamabad", "Katipally Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5774",  "Nizamabad", "Bandela Venkatarajam", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5775",  "Nizamabad", "Velma Mallareddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5776",  "Nizamabad", "Balakishna Nalla", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5777",  "Nizamabad", "Kunta Narayana Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5778",  "Nizamabad", "Narsaiah Gunda", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5779",  "Nizamabad", "Eleti Laxmareddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5780",  "Nizamabad", "Gangareddy Rikkala", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5781",  "Nizamabad", "Rajareddy Gangasaram", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5782",  "Nizamabad", "Suman Maggidi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5783",  "Nizamabad", "Theegala Ashok Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5784",  "Nizamabad", "Sayanna Bai", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5785",  "Nizamabad", "Mahendhar Kottala", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5787",  "Nizamabad", "Chintalapelly Gangareddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5788",  "Nizamabad", "Thirupathi Reddy Pannala", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5789",  "Nizamabad", "Devanna Pindi", "OverAged",  " ","",  "", "", " "}, 
{ "Telangana",  "5790",  "Nizamabad", "Baddam Ashok", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5791",  "Nizamabad", "Ippa Lachchanna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5792",  "Nizamabad", "Rajeshwar Musku", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5793",  "Nizamabad", "Surakanti Raja Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5794",  "Nizamabad", "Rajeshwar Enugu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5796",  "Nizamabad", "Medipalli Shekar Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5798",  "Nizamabad", "Mamidi Chinna Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5799",  "Nizamabad", "Maru Janardhan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5800",  "Nizamabad", "Gangadhar Andheti", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5801",  "Nizamabad", "Alluri Limba Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5802",  "Nizamabad", "Borranna Gummerla", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5803",  "Nizamabad", "Mohanareddy Eleti", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5804",  "Nizamabad", "Angu Poshetty", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5805",  "Nizamabad", "Chinnaiah Mukkera", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5806",  "Nizamabad", "Byagari Shanthaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5807",  "Nizamabad", "Sandireddy Gopal Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5808",  "Nizamabad", "Praveen Paidigela", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5809",  "Nizamabad", "Mahendhar Musku", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5810",  "Nizamabad", "Ravishankar Kunta", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5811",  "Nizamabad", "Pothuganti Venkatesh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5812",  "Nizamabad", "B. Srinivas", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5813",  "Nizamabad", "Armoor Sagar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5814",  "Nizamabad", "J. Chinna Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5815",  "Nizamabad", "Baddam Balaraju", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5816",  "Nizamabad", "Gadkole Chinna Gangareddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5818",  "Nizamabad", "Teegala Rajeshwar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5819",  "Nizamabad", "Doda Mutta Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5820",  "Nizamabad", "Aleti Sanjeev Reddy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5821",  "Nizamabad", "Surukanti Chinna Anjaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5822",  "Nizamabad", "Gajjala Sai Prasad", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5291",  "Peddapalle", "Arsham Ashok", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5292",  "Peddapalle", "Sankenapalli. Devadas", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5294",  "Peddapalle", "Velthuru Mallaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5299",  "Peddapalle", "Godisella Nagamani", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5300",  "Peddapalle", "Dr. Agama Chandrashekar", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5301",  "Peddapalle", "Sirikonda Krishna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5303",  "Peddapalle", "Gaddala Vinay Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5304",  "Peddapalle", "Ambala Mahendar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5305",  "Peddapalle", "Kuntala Narsaiah", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5306",  "Peddapalle", "Krishna Sabbani", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5307",  "Peddapalle", "Kumar Sogula", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5856",  "Secunderabad", "Gangapuram Kishan Reddy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5857",  "Secunderabad", "R Laxman Rao Gangaputra", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5858",  "Secunderabad", "Shakti Satayavathi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5859",  "Secunderabad", "G . Laxminarsimha Rao", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5860",  "Secunderabad", "Anjan Kumar Yadav", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5861",  "Secunderabad", "Dornala Jaya Prakash", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5863",  "Secunderabad", "Bathula Ravi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5865",  "Secunderabad", "Junaid Anam Siddiqui", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5867",  "Secunderabad", "N . Shankar Goud", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5868",  "Secunderabad", "Talasani Sai Kiran", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5870",  "Secunderabad", "Abdul Azeem", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5871",  "Secunderabad", "M . D . Nazeer Uddin Quadri", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5872",  "Secunderabad", "Shaik Muneer Pasha", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5875",  "Secunderabad", "Farah Naaz Khan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5878",  "Secunderabad", "Abdallah Ibrahim", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5879",  "Secunderabad", "K Venkatanarayana", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5883",  "Secunderabad", "Srirama Naik Munavath", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5984",  "Warangal", "Chintha Sambamurthy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5985",  "Warangal", "Kannam Venkanna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5986",  "Warangal", "Pasula Rammurthy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5989",  "Warangal", "Sambaiah Dommati", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5992",  "Warangal", "Chiluveru Prathap", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5993",  "Warangal", "Paniganti Rajithavani", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5994",  "Warangal", "Bunga Jyothi Ramana", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5995",  "Warangal", "Aitha Praveen Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5996",  "Warangal", "Jannu Narsaiah", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5997",  "Warangal", "Suresh Kanakam", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5824",  "Zahirabad", "Mudiraj Venkatesham", "NotGraduate",  " ","",  "", "", " "}, 
{ "Telangana",  "5826",  "Zahirabad", "B.B.Patil", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5827",  "Zahirabad", "Mark Babu", "CriminalCases",  " ","",  "", "", " "}, 
{ "Telangana",  "5828",  "Zahirabad", "Banala Laxma Reddy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5831",  "Zahirabad", "K. Madan Mohan Rao", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Telangana",  "5832",  "Zahirabad", "Mohammed Nawaz", "NotGraduate",  " ","",  "", "", " "}, 
};

}