/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Telangana {
public static final String[][] green_bucket = {
        {"Telangana", "Adilabad", "Godam Nagesh", "Telangana Rashtra Samithi", "1.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5814", "तेलंगाना", "आदिलाबाद", "गोधाम नागेश", "तेलंगाना राष्ट्र समिति"},
        {"Telangana", "Adilabad", "Pawar Krishna", "Independent", "11.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5824", "तेलंगाना", "आदिलाबाद", "पवार कृष्ण", "निर्दलीय"},
        {"Telangana", "Adilabad", "Ganta Pentanna", "Independent", "6.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5813", "तेलंगाना", "आदिलाबाद", "गन्ता पेन्टाना", "निर्दलीय"},
        {"Telangana", "Adilabad", "Dharavth Narendhar", "Janasena Party", "50000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5815", "तेलंगाना", "आदिलाबाद", "धरावत नरेंद्र", "जनसेना पार्टी"},
        {"Telangana", "Bhongir", "Samrat Narender Boilla", "Republican Party of India", "35.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6861", "तेलंगाना", "भोंगीर", "सम्राट नरेन्द्र बोइला", "रिपब्लिकन पार्टी ऑफ इंडिया"},
        {"Telangana", "Bhongir", "Dr. Narsaiah Boora", "Telangana Rashtra Samithi", "23.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5089", "तेलंगाना", "भोंगीर", "डॉ। नरसैया बोरिया", "तेलंगाना राष्ट्र समिति"},
        {"Telangana", "Bhongir", "Sapavat Devaram", "Independent", "64986", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6867", "तेलंगाना", "भोंगीर", "सपवत देवराम", "निर्दलीय"},
        {"Telangana", "Bhongir", "Moorigaadi Krishna", "Independent", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6860", "तेलंगाना", "भोंगीर", "मूरईगाड़ी कृष्णा", "निर्दलीय"},
        {"Telangana", "Chevella", "Sanem Raju Goud", "Independent", "21.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6829", "तेलंगाना", "चेवेल्ला", "सनम राजू गौड", "निर्दलीय"},
        {"Telangana", "Chevella", "Anusha Keshavabhatla", "Independent", "92.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6818", "तेलंगाना", "चेवेल्ला", "अनुषा केशवभटला", "निर्दलीय"},
        {"Telangana", "Chevella", "Ija Venkatesh Goud", "Social Justice Party of India", "98Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6823", "तेलंगाना", "चेवेल्ला", "इजा वेंकटेश गौड", "सोशल जस्टिस पार्टी ऑफ इंडिया"},
        {"Telangana", "Chevella", "P. Purushotham", "Independent", "2.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6826", "तेलंगाना", "चेवेल्ला", "पी। पुरुषोत्तम", "निर्दलीय"},
        {"Telangana", "Chevella", "T. Durga Prasad", "Independent", "2.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6830", "तेलंगाना", "चेवेल्ला", "टी। दुर्गा प्रसाद", "निर्दलीय"},
        {"Telangana", "Chevella", "Dr.Gaddam Ranjith Reddy", "Telangana Rashtra Samithi", "163.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4846", "तेलंगाना", "चेवेल्ला", "डॉ। गद्दाम रंजीथ रेड्डी", "तेलंगाना राष्ट्र समिति"},
        {"Telangana", "Chevella", "Ragam Sathesh Yadav", "All India Forward Bloc", "4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6828", "तेलंगाना", "चेवेल्ला", "रागम सठेश यादव", "ऑल इंडिया फॉरवर्ड ब्लॉक"},
        {"Telangana", "Chevella", "G. Ravi Kumar Yadav", "Independent", "91000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6822", "तेलंगाना", "चेवेल्ला", "जी। रवि कुमार यादव", "निर्दलीय"},
        {"Telangana", "Hyderabad", "V Bal Krishna", "Independent", "2.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6804", "तेलंगाना", "हैदराबाद", "वी बाल कृष्ण", "निर्दलीय"},
        {"Telangana", "Hyderabad", "Pusthe Srikanth", "Telangana Rashtra Samithi", "3.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6800", "तेलंगाना", "हैदराबाद", "पुस्टे श्रीकांत", "तेलंगाना राष्ट्र समिति"},
        {"Telangana", "Karimnagar", "Vinod Kumar Boianapalli", "Telangana Rashtra Samithi", "12.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4593", "तेलंगाना", "करीमनगर", "विनोद कुमार बोयनापल्ली", "तेलंगाना राष्ट्र समिति"},
        {"Telangana", "Karimnagar", "Chintha Anil Kumar", "Pyramid Party of India", "25000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4592", "तेलंगाना", "करीमनगर", "चिंथा अनिल कुमार", "पिरामिड पार्टी ऑफ इंडिया"},
        {"Telangana", "Karimnagar", "Rameshbabu Shanigarapu", "Independent", "56500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4827", "तेलंगाना", "करीमनगर", "रमेशबाबू शनीगारपु", "निर्दलीय"},
        {"Telangana", "Karimnagar", "Palle Prashanth", "Jai Swaraj Party", "36.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4633", "तेलंगाना", "करीमनगर", "पलले प्रशांत", "जय स्वराज पार्टी"},
        {"Telangana", "Karimnagar", "Reddy Venugopal", "Samajwadi Forward Bloc", "30500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6277", "तेलंगाना", "करीमनगर", "रेड्डी वेणुगोपाल", "समाजवादी फॉरवर्ड ब्लॉक"},
        {"Telangana", "Khammam", "Mutyam Arjuna Raju", "Independent", "24.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6905", "तेलंगाना", "खम्मम", "मुतम अर्जुन राजू", "निर्दलीय"},
        {"Telangana", "Khammam", "Lakavath Nageswara Rao", "Bahujan Mukti Party", "7.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6896", "तेलंगाना", "खम्मम", "लखावत नागेश्वर राव", "बहुजन मुक्ति पार्टी"},
        {"Telangana", "Khammam", "Boda Venkat", "Communist Party of India (Marxist)", "96.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4868", "तेलंगाना", "खम्मम", "बोड़ा वेंकट", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
        {"Telangana", "Khammam", "Umamaheswara Rao Cherukupalli", "Telangana Yuva Shakti", "76.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6892", "तेलंगाना", "खम्मम", "उमामहेश्वर राव चेरुपुपल्ली", "तेलंगाना युवा शक्ति"},
        {"Telangana", "Khammam", "Dunuku Veladri", "Independent", "5.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6902", "तेलंगाना", "खम्मम", "दुनुकु वलाद्री", "निर्दलीय"},
        {"Telangana", "Khammam", "Narala Satyanarayana", "Janasena Party", "22Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6895", "तेलंगाना", "खम्मम", "नारला सत्यनारायण", "जनसेना पार्टी"},
        {"Telangana", "Khammam", "Shankara Rao Gopagani", "Independent", "66.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6901", "तेलंगाना", "खम्मम", "शंकर राव गोपगानी", "निर्दलीय"},
        {"Telangana", "Mahabubabad", "Balsingh Daravath", "Bhartiya Anarakshit Party", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6880", "तेलंगाना", "महबुबाबाद", "बलसिंह दरवथ", "भारतीय अनारक्षित पार्टी"},
        {"Telangana", "Mahabubabad", "Bhaskar Naik Bhukya.", "Janasena Party", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6883", "तेलंगाना", "महबुबाबाद", "भास्कर नाइक भुक्ा।", "जनसेना पार्टी"},
        {"Telangana", "Mahabubabad", "Vaditya Shriram Naik", "Independent", "48.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6890", "तेलंगाना", "महबुबाबाद", "वदित्य श्रीराम नाइक", "निर्दलीय"},
        {"Telangana", "Mahabubabad", "Palvancha. Durga.", "Independent", "11.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6888", "तेलंगाना", "महबुबाबाद", "Palvancha। दुर्गा।", "निर्दलीय"},
        {"Telangana", "Mahabubabad", "Balu Nayak Bhukya", "Independent", "27.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6881", "तेलंगाना", "महबुबाबाद", "बलु नायक भुक्", "निर्दलीय"},
        {"Telangana", "Mahbubnagar", "Vishweshwar J", "Independent", "47.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6835", "तेलंगाना", "महबूबनगर", "विश्वेश्वर जे", "निर्दलीय"},
        {"Telangana", "Mahbubnagar", "Md. Abdul Azeez Khan", "Independent", "56.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4668", "तेलंगाना", "महबूबनगर", "मो। अब्दुल अज़ीज़ खान", "निर्दलीय"},
        {"Telangana", "Mahbubnagar", "Pola Prashanth Kumar", "Independent", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4606", "तेलंगाना", "महबूबनगर", "पोला प्रशांत कुमार", "निर्दलीय"},
        {"Telangana", "Mahbubnagar", "Mohammed Imtiyaz Ahmad", "Independent", "66.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4607", "तेलंगाना", "महबूबनगर", "मोहम्मद इम्तियाज अहमद", "निर्दलीय"},
        {"Telangana", "Malkajgiri", "Donthula Bikshapathi", "Independent", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6777", "तेलंगाना", "मल्काजगिरि", "दुन्दुला बिकासपति", "निर्दलीय"},
        {"Telangana", "Malkajgiri", "Rajender Ponnala", "Independent", "10.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7242", "तेलंगाना", "मल्काजगिरि", "राजेन्द्र पोन्नाला", "निर्दलीय"},
        {"Telangana", "Malkajgiri", "Balamani Buru", "India Praja Bandhu Party", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6774", "तेलंगाना", "मल्काजगिरि", "बालमणि बुरु", "भारत प्रजा बंधु पार्टी"},
        {"Telangana", "Malkajgiri", "Sai Kiran Gone", "Independent", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6779", "तेलंगाना", "मल्काजगिरि", "साईं किरण गया", "निर्दलीय"},
        {"Telangana", "Malkajgiri", "Chalika Chandra Sekhar", "Independent", "42.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4664", "तेलंगाना", "मल्काजगिरि", "चालिका चन्द्रशेखर", "निर्दलीय"},
        {"Telangana", "Medak", "Kallu Narsimlu Goud", "Independent", "27.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6768", "तेलंगाना", "मेडक", "कल्लू नरसिम्लु गौड", "निर्दलीय"},
        {"Telangana", "Medak", "Bharatesh", "Socialist Unity Centre of India (Communist)", "42300", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6765", "तेलंगाना", "मेडक", "Bharatesh", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Telangana", "Medak", "Kotha Prabhakar Reddy", "Telangana Rashtra Samithi", "126.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5079", "तेलंगाना", "मेडक", "कोठा प्रभाकर रेड्डी", "तेलंगाना राष्ट्र समिति"},
        {"Telangana", "Nagarkurnool", "Gaddam Vijay Kumar", "Bahujan Mukti Party", "18Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5787", "तेलंगाना", "नगरकुरनूल", "गद्दाम विजय कुमार", "बहुजन मुक्ति पार्टी"},
        {"Telangana", "Nalgonda", "Jakkula Naveen Yadav", "Independent", "10Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6847", "तेलंगाना", "नलगोंडा", "जक्कूला नवीन यादव", "निर्दलीय"},
        {"Telangana", "Nalgonda", "Mekala Satheesh Reddy", "Janasena Party", "34.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6841", "तेलंगाना", "नलगोंडा", "मेकाला सतीश रेड्डी", "जनसेना पार्टी"},
        {"Telangana", "Nalgonda", "Royyala Srinivasulu", "Independent", "86.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6857", "तेलंगाना", "नलगोंडा", "रोयला श्रीनिवासुलु", "निर्दलीय"},
        {"Telangana", "Nalgonda", "Lingidi Venkateswarlu", "Independent", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6858", "तेलंगाना", "नलगोंडा", "लिंगीदी वेंकटेश्वरलु", "निर्दलीय"},
        {"Telangana", "Nalgonda", "Vemireddy Narasimha Reddy", "Telangana Rashtra Samithi", "94.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6838", "तेलंगाना", "नलगोंडा", "वेमिरेड्डी नरसिम्हा रेड्डी", "तेलंगाना राष्ट्र समिति"},
        {"Telangana", "Nalgonda", "Ramesh Sunkara", "Independent", "15.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6856", "तेलंगाना", "नलगोंडा", "रमेश सुनकारा", "निर्दलीय"},
        {"Telangana", "Nalgonda", "Katravath Venkatesh", "Bahujan Mukti Party", "21300", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6839", "तेलंगाना", "नलगोंडा", "कत्रवथ वेंकटेश", "बहुजन मुक्ति पार्टी"},
        {"Telangana", "Nalgonda", "Lithesh Sunkari", "Social Justice Party of India", "48.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6843", "तेलंगाना", "नलगोंडा", "लीठेश सुनकारी", "सोशल जस्टिस पार्टी ऑफ इंडिया"},
        {"Telangana", "Nalgonda", "Thagulla Janardhan", "Independent", "2.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6848", "तेलंगाना", "नलगोंडा", "ठगुल्ला जनार्दन", "निर्दलीय"},
        {"Telangana", "Nalgonda", "Bandaru Nagaraju", "Independent", "2.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6852", "तेलंगाना", "नलगोंडा", "बंडारू नागराजू", "निर्दलीय"},
        {"Telangana", "Nalgonda", "Sreenu Vadthya", "Independent", "19.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4864", "तेलंगाना", "नलगोंडा", "श्रीनु वधथया", "निर्दलीय"},
        {"Telangana", "Nalgonda", "Janaiah Nandipati", "Telangana Sakalajanula Party", "16Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6840", "तेलंगाना", "नलगोंडा", "जनाया नंदीपति", "तेलंगाना सकलजानुला पार्टी"},
        {"Telangana", "Nizamabad", "Yellala Rajitha", "Independent", "19.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6750", "तेलंगाना", "निजामाबाद", "येलाला रजिथा", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Raj Kumar Sunkari", "Independent", "8.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6700", "तेलंगाना", "निजामाबाद", "राज कुमार सुनकारी", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Katipelli Ramesh", "Independent", "5.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6638", "तेलंगाना", "निजामाबाद", "कटिपेली रमेश", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Ganga Reddy Kallem", "Independent", "21.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6618", "तेलंगाना", "निजामाबाद", "गंगा रेड्डी कालिम", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Kanaka Pramod", "Independent", "3.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6634", "तेलंगाना", "निजामाबाद", "कनक प्रमोद", "निर्दलीय"},
        {"Telangana", "Nizamabad", "S. Sagar", "Bahujan Mukti Party", "75000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6714", "तेलंगाना", "निजामाबाद", "एस सागर", "बहुजन मुक्ति पार्टी"},
        {"Telangana", "Nizamabad", "Madhu Butti", "Independent", "4.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6655", "तेलंगाना", "निजामाबाद", "मधु बुट्टी", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Shankar Yenugu", "Independent", "12.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6723", "तेलंगाना", "निजामाबाद", "शंकर येनगु", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Talari Suman", "Independent", "3.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6736", "तेलंगाना", "निजामाबाद", "तलारी सुमन", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Ayileni Vikram Reddy", "Independent", "65000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6322", "तेलंगाना", "निजामाबाद", "अइलेंनी विक्रम रेड्डी", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Limbaiah Somidi", "Independent", "2.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6649", "तेलंगाना", "निजामाबाद", "लिंबैया सोमदीदी", "निर्दलीय"},
        {"Telangana", "Nizamabad", "N. Omkar Reddy", "Independent", "18.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6683", "तेलंगाना", "निजामाबाद", "एन। ओंकार रेड्डी", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Mamidi Rajashekar Reddy", "Independent", "18.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6664", "तेलंगाना", "निजामाबाद", "ममदी राजशेखर रेड्डी", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Thota Srinivas", "Independent", "24.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6742", "तेलंगाना", "निजामाबाद", "थोटा श्रीनिवास", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Gaddam Mohan", "Independent", "10500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6607", "तेलंगाना", "निजामाबाद", "गद्दाम मोहन", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Mohan Chintala Palli", "Independent", "9.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6674", "तेलंगाना", "निजामाबाद", "मोहन चिंतला पल्ली", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Gaddam Purushotham", "Independent", "8.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6608", "तेलंगाना", "निजामाबाद", "गद्दाम पुरुषोत्तम", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Suresh Basa", "Independent", "10.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6733", "तेलंगाना", "निजामाबाद", "सुरेश बासा", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Sanjeeva Reddy Gaddam", "Independent", "55.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6718", "तेलंगाना", "निजामाबाद", "संजीव रेड्डी गद्दाम", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Raju Somireddy", "Independent", "4.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6707", "तेलंगाना", "निजामाबाद", "राजू सोमरेड्डी", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Baddam Srinivasa Reddy", "Independent", "20.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6328", "तेलंगाना", "निजामाबाद", "बादाम श्रीनिवास रेड्डी", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Sama Thirupathi", "Independent", "11.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4654", "तेलंगाना", "निजामाबाद", "साम थिरुपथी", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Praveen Neeradi", "Independent", "1.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6698", "तेलंगाना", "निजामाबाद", "प्रवीण नीरड़ी", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Mohd Jameel", "Independent", "10.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6676", "तेलंगाना", "निजामाबाद", "मोहम्मद जमील", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Sunketa Ravi", "Independent", "93.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6730", "तेलंगाना", "निजामाबाद", "सुनकेत रवि", "निर्दलीय"},
        {"Telangana", "Nizamabad", "Nomula Gopal Reddy", "Independent", "40000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4655", "तेलंगाना", "निजामाबाद", "नोमुला गोपाल रेड्डी", "निर्दलीय"},
        {"Telangana", "Peddapalle", "Bala Kalyan Panja", "Bahujan Samaj Party", "7.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6216", "तेलंगाना", "पेडेपल्लै", "बाला कल्याण पांजा", "बहुजन समाज पार्टी"},
        {"Telangana", "Peddapalle", "Erugurala Bhagya Laxmi", "Pyramid Party of India", "2000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4631", "तेलंगाना", "पेडेपल्लै", "एरुगुरला भाग्य लक्ष्मी", "पिरामिड पार्टी ऑफ इंडिया"},
        {"Telangana", "Peddapalle", "Rajesh Erikilla", "Independent", "4.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7239", "तेलंगाना", "पेडेपल्लै", "राजेश एरिकिला", "निर्दलीय"},
        {"Telangana", "Peddapalle", "Venkatesh Netha Borlakunta", "Telangana Rashtra Samithi", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5071", "तेलंगाना", "पेडेपल्लै", "वेंकटेश नेथा बोरलाकुंटा", "तेलंगाना राष्ट्र समिति"},
        {"Telangana", "Peddapalle", "Durgam. Rajanna", "Independent", "15500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4649", "तेलंगाना", "पेडेपल्लै", "Durgam। Rajanna", "निर्दलीय"},
        {"Telangana", "Peddapalle", "Thadem Raj Prakash", "India Praja Bandhu Party", "2.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4591", "तेलंगाना", "पेडेपल्लै", "ठाडेम राज प्रकाश", "भारत प्रजा बंधु पार्टी"},
        {"Telangana", "Secunderabad", "Boddu Satish", "Independent", "33000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6797", "तेलंगाना", "सिकंदराबाद", "बोधु सतीश", "निर्दलीय"},
        {"Telangana", "Secunderabad", "Nandipati Vinod Kumar", "Independent", "30000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6799", "तेलंगाना", "सिकंदराबाद", "नंदीपति विनोद कुमार", "निर्दलीय"},
        {"Telangana", "Secunderabad", "Mallesh Jatavath", "Socialist Unity Centre of India (Communist)", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5085", "तेलंगाना", "सिकंदराबाद", "मल्लेश जाटवथ", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"Telangana", "Secunderabad", "Meesala Gopal Sai Baba", "Independent", "97.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4840", "तेलंगाना", "सिकंदराबाद", "मीसाला गोपाल साईं बाबा", "निर्दलीय"},
        {"Telangana", "Secunderabad", "Andukuri Vijaya Bhaskar", "India Praja Bandhu Party", "5000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6790", "तेलंगाना", "सिकंदराबाद", "अंदुकुरी विजया भास्कर", "भारत प्रजा बंधु पार्टी"},
        {"Telangana", "Secunderabad", "Ravi Kumar Vodela", "Independent", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6784", "तेलंगाना", "सिकंदराबाद", "रवि कुमार वोडेला", "निर्दलीय"},
        {"Telangana", "Secunderabad", "J . N . Rao", "Dalita Bahujana Party", "15.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6798", "तेलंगाना", "सिकंदराबाद", "जे। एन। राव", "दलिता बहुजन पार्टी"},
        {"Telangana", "Secunderabad", "Challa Ram Kalyan", "Bhartiya Anarakshit Party", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6789", "तेलंगाना", "सिकंदराबाद", "चल्ला राम कल्याण", "भारतीय अनारक्षित पार्टी"},
        {"Telangana", "Secunderabad", "Akhil Chirravuri", "Independent", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6791", "तेलंगाना", "सिकंदराबाद", "अखिल चिरवरी", "निर्दलीय"},
        {"Telangana", "Secunderabad", "M . Ashok Kumar", "Samajwadi Forward Bloc", "3.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6788", "तेलंगाना", "सिकंदराबाद", "एम। अशोक कुमार", "समाजवादी फॉरवर्ड ब्लॉक"},
        {"Telangana", "Secunderabad", "Andrapu Sudharshan Gangaputra", "Independent", "60000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6795", "तेलंगाना", "सिकंदराबाद", "आद्रापु सुधर्शन गंगापुत्र", "निर्दलीय"},
        {"Telangana", "Warangal", "Dayakar Pasnori", "Telangana Rashtra Samithi", "2.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5094", "तेलंगाना", "वारंगल", "दयाकर पासनोरी", "तेलंगाना राष्ट्र समिति"},
        {"Telangana", "Warangal", "Upendar Jeripothula", "Independent", "6.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5778", "तेलंगाना", "वारंगल", "उपेंडर जेरिपोथुला", "निर्दलीय"},
        {"Telangana", "Warangal", "Bollapally Saraiah", "Bahujan Samaj Party", "96.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6870", "तेलंगाना", "वारंगल", "बोलपल्ली साराया", "बहुजन समाज पार्टी"},
        {"Telangana", "Warangal", "Barla Srinivas", "Independent", "15000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5783", "तेलंगाना", "वारंगल", "बराला श्रीनिवास", "निर्दलीय"},
        {"Telangana", "Warangal", "Bochu Krupakar", "Hum Bhartiya Party", "11.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6873", "तेलंगाना", "वारंगल", "बोचु क्रुपाकर", "हम भारतीय पार्टी"},
        {"Telangana", "Zahirabad", "Ramarao Patil", "Independent", "2.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6757", "तेलंगाना", "जहीराबाद", "रामाराव पाटिल", "निर्दलीय"},
        {"Telangana", "Zahirabad", "Alige Jeevan", "Bahujan Mukti Party", "51000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6759", "तेलंगाना", "जहीराबाद", "आजीवन जीवन", "बहुजन मुक्ति पार्टी"},
        {"Telangana", "Zahirabad", "Nangunoori Lata", "Independent", "2.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6755", "तेलंगाना", "जहीराबाद", "नंगुनूरी लता", "निर्दलीय"},
        {"Telangana", "Zahirabad", "Benjamin Raju", "Independent", "75.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6752", "तेलंगाना", "जहीराबाद", "बेंजामिन राजू", "निर्दलीय"},
        {"Telangana", "Zahirabad", "Kalesh", "Bhartiya Anarakshit Party", "10.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7243", "तेलंगाना", "जहीराबाद", "Kalesh", "भारतीय अनारक्षित पार्टी"},
};

public static final String[][] red_bucket = {
        {"Telangana", "Adilabad", "Aare Ellanna", "4", " ", "तेलंगाना", "आदिलाबाद", "आरे इल्न्ना", " "},
        {"Telangana", "Adilabad", "Kumra Raju", "4", " ", "तेलंगाना", "आदिलाबाद", "कुमरा राजू", " "},
        {"Telangana", "Adilabad", "Nethavath Ramdas", "4", " ", "तेलंगाना", "आदिलाबाद", "नेत्रनाथ रामदास", " "},
        {"Telangana", "Adilabad", "Ramesh Rathod", "1", " ", "तेलंगाना", "आदिलाबाद", "रमेश राठौड़", " "},
        {"Telangana", "Adilabad", "Bapu Rao Soyam", "1", " ", "तेलंगाना", "आदिलाबाद", "बापू राव सोयम", " "},
        {"Telangana", "Adilabad", "Bheem Rao", "4", " ", "तेलंगाना", "आदिलाबाद", "भीम राव", " "},
        {"Telangana", "Adilabad", "Kumram Vandana", "4", " ", "तेलंगाना", "आदिलाबाद", "कुमारम वंदना", " "},
        {"Telangana", "Bhongir", "Sirivolu Venkata Ramana Rao", "4", " ", "तेलंगाना", "भोंगीर", "सिरिवोलु वेंकट रमना राव", " "},
        {"Telangana", "Bhongir", "Komatireddy Venakat Reddy", "1", " ", "तेलंगाना", "भोंगीर", "कोमाटेड्डी वेंकट रेड्डी", " "},
        {"Telangana", "Bhongir", "Goda Sriramulu", "4", " ", "तेलंगाना", "भोंगीर", "गोदा श्रीरामुलु", " "},
        {"Telangana", "Bhongir", "Kotha Kistaiah", "4", " ", "तेलंगाना", "भोंगीर", "कोठा किस्तेया", " "},
        {"Telangana", "Bhongir", "Padala Venkata Shyam Sunder Rao", "1", " ", "तेलंगाना", "भोंगीर", "पडाला वेंकट श्याम सुन्दर राव", " "},
        {"Telangana", "Bhongir", "Sriramulu Muthyala", "4", " ", "तेलंगाना", "भोंगीर", "श्रीरामुलु मुथयला", " "},
        {"Telangana", "Bhongir", "Bheemanaboina Ramesh", "4", " ", "तेलंगाना", "भोंगीर", "भीमनबॉइन रमेश", " "},
        {"Telangana", "Bhongir", "Singapaka Lingam", "4", " ", "तेलंगाना", "भोंगीर", "सिंगापक लिंगम", " "},
        {"Telangana", "Chevella", "Nalla Prem Kumar", "4", " ", "तेलंगाना", "चेवेल्ला", "नाला प्रेम कुमार", " "},
        {"Telangana", "Chevella", "Yedla Suresh", "4", " ", "तेलंगाना", "चेवेल्ला", "येदला सुरेश", " "},
        {"Telangana", "Chevella", "Bennala Julee", "4", " ", "तेलंगाना", "चेवेल्ला", "बेनाला जुले", " "},
        {"Telangana", "Chevella", "Palamakula Madhu", "4", " ", "तेलंगाना", "चेवेल्ला", "पालमकुला मधु", " "},
        {"Telangana", "Chevella", "Baswaiah Madiga", "4", " ", "तेलंगाना", "चेवेल्ला", "बसवाइया मडिगा", " "},
        {"Telangana", "Chevella", "Vijay Aarya", "4", " ", "तेलंगाना", "चेवेल्ला", "विजय आर्या", " "},
        {"Telangana", "Chevella", "A.A. Sabri", "3", " ", "तेलंगाना", "चेवेल्ला", "एए साबरी", " "},
        {"Telangana", "Chevella", "Gurram Papi Reddy", "4", " ", "तेलंगाना", "चेवेल्ला", "गुर्रम पापी रेड्डी", " "},
        {"Telangana", "Chevella", "B. Janardhan Reddy", "1", " ", "तेलंगाना", "चेवेल्ला", "बी। जनार्दन रेड्डी", " "},
        {"Telangana", "Chevella", "Kummari Giri", "4", " ", "तेलंगाना", "चेवेल्ला", "कुमारी गिरि", " "},
        {"Telangana", "Chevella", "Konda Vishweshwar Reddy", "1", " ", "तेलंगाना", "चेवेल्ला", "कोंडा विश्वेश्वर रेड्डी", " "},
        {"Telangana", "Chevella", "Korra Pandu Naik", "4", " ", "तेलंगाना", "चेवेल्ला", "कोरा पांडु नाइक", " "},
        {"Telangana", "Chevella", "Chepuri Raju", "4", " ", "तेलंगाना", "चेवेल्ला", "चेपुरी राजू", " "},
        {"Telangana", "Chevella", "Jaidupally Yadaiah", "4", " ", "तेलंगाना", "चेवेल्ला", "जयदुपल्ली यदैया", " "},
        {"Telangana", "Chevella", "Vanam Sudhakar", "4", " ", "तेलंगाना", "चेवेल्ला", "वनम सुधाकर", " "},
        {"Telangana", "Hyderabad", "Mohammed Abdul Azeem", "4", " ", "तेलंगाना", "हैदराबाद", "मोहम्मद अब्दुल अज़ीम", " "},
        {"Telangana", "Hyderabad", "Bhagavanth Rao Pawar", "1", " ", "तेलंगाना", "हैदराबाद", "भगवंत राव पवार", " "},
        {"Telangana", "Hyderabad", "Dornala Jaya Prakash", "2", " ", "तेलंगाना", "हैदराबाद", "दोरनाला जय प्रकाश", " "},
        {"Telangana", "Hyderabad", "L Ashok Nath", "4", " ", "तेलंगाना", "हैदराबाद", "एल अशोक नाथ", " "},
        {"Telangana", "Hyderabad", "Sanjay Kumar Shukla", "4", " ", "तेलंगाना", "हैदराबाद", "संजय कुमार शुक्ला", " "},
        {"Telangana", "Hyderabad", "K Rangacharya", "4", " ", "तेलंगाना", "हैदराबाद", "के रंगाचार्य", " "},
        {"Telangana", "Hyderabad", "Mohd Ahmed", "4", " ", "तेलंगाना", "हैदराबाद", "मोहम्मद अहमद", " "},
        {"Telangana", "Hyderabad", "Asaduddin Owaisi", "2", " ", "तेलंगाना", "हैदराबाद", "असदुद्दीन ओवैसी", " "},
        {"Telangana", "Hyderabad", "K. Nagaraj", "4", " ", "तेलंगाना", "हैदराबाद", "के। नागराज", " "},
        {"Telangana", "Hyderabad", "Mohammed Feroz Khan", "1", " ", "तेलंगाना", "हैदराबाद", "मोहम्मद फ़िरोज़ खान", " "},
        {"Telangana", "Hyderabad", "Dr.Hingolikar Susheel Raj", "4", " ", "तेलंगाना", "हैदराबाद", "डॉ। हिंगोलिकर सुशील राज", " "},
        {"Telangana", "Hyderabad", "Beeramganti Venkat Ramesh Naidu", "4", " ", "तेलंगाना", "हैदराबाद", "बीरमुगंति वेंकट रमेश नायडू", " "},
        {"Telangana", "Hyderabad", "Ka Maheshwar", "2", " ", "तेलंगाना", "हैदराबाद", "का महेश्वर", " "},
        {"Telangana", "Karimnagar", "Ponnam Prabhakar", "1", " ", "तेलंगाना", "करीमनगर", "पोन्नम प्रभाकर", " "},
        {"Telangana", "Karimnagar", "Bhanu Laxman Pabba", "4", " ", "तेलंगाना", "करीमनगर", "भानु लक्ष्मण पबबा", " "},
        {"Telangana", "Karimnagar", "Aila Prasanna", "4", " ", "तेलंगाना", "करीमनगर", "आइला प्रसन्ना", " "},
        {"Telangana", "Karimnagar", "Durvasa Reddy Pakala", "2", " ", "तेलंगाना", "करीमनगर", "दुर्वासा रेड्डी पकाला", " "},
        {"Telangana", "Karimnagar", "Kota Shyamkumar", "4", " ", "तेलंगाना", "करीमनगर", "कोटा श्यामकुमार", " "},
        {"Telangana", "Karimnagar", "Anagandula Venkanna", "2", " ", "तेलंगाना", "करीमनगर", "अनगनदुला वेंकन्ना", " "},
        {"Telangana", "Karimnagar", "Mukkisa Ratnakar Reddy", "4", " ", "तेलंगाना", "करीमनगर", "मुकीसा रत्नाकर रेड्डी", " "},
        {"Telangana", "Karimnagar", "Srikanth Chiliveru", "2", " ", "तेलंगाना", "करीमनगर", "श्रीकांत चिलिवरु", " "},
        {"Telangana", "Karimnagar", "Gangarapu Thirupathi", "4", " ", "तेलंगाना", "करीमनगर", "गंगारापु थिरुपथी", " "},
        {"Telangana", "Karimnagar", "Bandi Sanjay Kumar", "1", " ", "तेलंगाना", "करीमनगर", "बंदी संजय कुमार", " "},
        {"Telangana", "Khammam", "Avutapalli Rambabu", "4", " ", "तेलंगाना", "खम्मम", "अवुतपल्ली रामबाबू", " "},
        {"Telangana", "Khammam", "Gugulothu Ramesh", "2", " ", "तेलंगाना", "खम्मम", "गुगुलोथु रमेश", " "},
        {"Telangana", "Khammam", "Koppula Sreenivasa Rao", "4", " ", "तेलंगाना", "खम्मम", "कोप्पुला श्रीनिवास राव", " "},
        {"Telangana", "Khammam", "Venkateshwar Rao Pullakandam", "4", " ", "तेलंगाना", "खम्मम", "वेंकटेश्वर राव पुल्लाकंदम", " "},
        {"Telangana", "Khammam", "Gokinapalli Venkateswarlu", "4", " ", "तेलंगाना", "खम्मम", "गोकिनापल्ली वेंकटेश्वरलु", " "},
        {"Telangana", "Khammam", "Katta Srinivas", "4", " ", "तेलंगाना", "खम्मम", "कट्टा श्रीनिवास", " "},
        {"Telangana", "Khammam", "Parsagani Nageswara Rao", "2", " ", "तेलंगाना", "खम्मम", "परसागनी नागेश्वर राव", " "},
        {"Telangana", "Khammam", "Anil Kumar Maddineni", "2", " ", "तेलंगाना", "खम्मम", "अनिल कुमार मद्दीनैनी", " "},
        {"Telangana", "Khammam", "Nakirikanti Sanjeeva Rao", "4", " ", "तेलंगाना", "खम्मम", "नकीरकांति संजीव राव", " "},
        {"Telangana", "Khammam", "Gopoju Ramesh Babu", "4", " ", "तेलंगाना", "खम्मम", "गोपोजु रमेश बाबू", " "},
        {"Telangana", "Khammam", "Renuka Chowdhury", "1", " ", "तेलंगाना", "खम्मम", "रेणुका चौधरी", " "},
        {"Telangana", "Khammam", "Devaki Vasudeva Rao", "1", " ", "तेलंगाना", "खम्मम", "देवकी वासुदेव राव", " "},
        {"Telangana", "Khammam", "Laxmana Chary Bhanala", "4", " ", "तेलंगाना", "खम्मम", "लक्ष्मण चरी भनाला", " "},
        {"Telangana", "Khammam", "Banoth Laxma Naik", "4", " ", "तेलंगाना", "खम्मम", "बनथ लक्ष्मण नाइक", " "},
        {"Telangana", "Khammam", "Nama Nageswr Rao", "2", " ", "तेलंगाना", "खम्मम", "नामा नागसेवक राव", " "},
        {"Telangana", "Khammam", "Palvancha Rama Rao", "2", " ", "तेलंगाना", "खम्मम", "पलवंच रामा राव", " "},
        {"Telangana", "Mahabubabad", "Uke Kousalya", "4", " ", "तेलंगाना", "महबुबाबाद", "उके कुसलया", " "},
        {"Telangana", "Mahabubabad", "Jatothu Hussain", "1", " ", "तेलंगाना", "महबुबाबाद", "जटोथु हुसैन", " "},
        {"Telangana", "Mahabubabad", "Kalluri. Venkateswara Rao", "4", " ", "तेलंगाना", "महबुबाबाद", "कल्लूरी। वेंकटेश्वर राव", " "},
        {"Telangana", "Mahabubabad", "Parvathi Bhukya", "4", " ", "तेलंगाना", "महबुबाबाद", "पार्वती भुक्ा", " "},
        {"Telangana", "Mahabubabad", "Kalthi Yarraiah", "2", " ", "तेलंगाना", "महबुबाबाद", "कलथी यारैया", " "},
        {"Telangana", "Mahabubabad", "Arun Kumar Mypathi", "2", " ", "तेलंगाना", "महबुबाबाद", "अरुण कुमार मिपाठी", " "},
        {"Telangana", "Mahabubabad", "Mokalla. Murali Krishna", "2", " ", "तेलंगाना", "महबुबाबाद", "Mokalla। मुरली कृष्ण", " "},
        {"Telangana", "Mahabubabad", "Kavitha Malothu", "2", " ", "तेलंगाना", "महबुबाबाद", "कविता मलोथू", " "},
        {"Telangana", "Mahabubabad", "Balaram Naik Porika", "1", " ", "तेलंगाना", "महबुबाबाद", "बलराम नाइक पोरिका", " "},
        {"Telangana", "Mahbubnagar", "Manne Srinivas Reddy", "4", " ", "तेलंगाना", "महबूबनगर", "मन्ने श्रीनिवास रेड्डी", " "},
        {"Telangana", "Mahbubnagar", "Challa Vamshi Chand Reddy", "1", " ", "तेलंगाना", "महबूबनगर", "चल्ला वामशी चंद रेड्डी", " "},
        {"Telangana", "Mahbubnagar", "S Gopal Reddy", "4", " ", "तेलंगाना", "महबूबनगर", "एस गोपाल रेड्डी", " "},
        {"Telangana", "Mahbubnagar", "V Dasram", "2", " ", "तेलंगाना", "महबूबनगर", "वी दशराम", " "},
        {"Telangana", "Mahbubnagar", "Ergamreddy Shivadurgavaraprasad Reddy", "4", " ", "तेलंगाना", "महबूबनगर", "एर्माग्रेड्डी शिवदुर्गावराप्रसाद रेड्डी", " "},
        {"Telangana", "Mahbubnagar", "Imran Ahmed Khan", "4", " ", "तेलंगाना", "महबूबनगर", "इमरान अहमद खान", " "},
        {"Telangana", "Mahbubnagar", "D. K. Aruna", "1", " ", "तेलंगाना", "महबूबनगर", "डीके अरुणा", " "},
        {"Telangana", "Mahbubnagar", "D Thimmappa", "4", " ", "तेलंगाना", "महबूबनगर", "डी थिमप्पा", " "},
        {"Telangana", "Malkajgiri", "Ramchander Rao N", "1", " ", "तेलंगाना", "मल्काजगिरि", "रामचंदर राव एन", " "},
        {"Telangana", "Malkajgiri", "Mahender Reddy Bongunoori", "4", " ", "तेलंगाना", "मल्काजगिरि", "महेंदर रेड्डी बोंगुनूरी", " "},
        {"Telangana", "Malkajgiri", "Dharmasanam Bhanumurthy", "2", " ", "तेलंगाना", "मल्काजगिरि", "धर्मसनं भानुमूर्ति", " "},
        {"Telangana", "Malkajgiri", "Rajashekar Reddy Marri", "4", " ", "तेलंगाना", "मल्काजगिरि", "राजशेखर रेड्डी विवाह", " "},
        {"Telangana", "Malkajgiri", "Chamakura Rajaiah", "2", " ", "तेलंगाना", "मल्काजगिरि", "चमकुरा राजािया", " "},
        {"Telangana", "Malkajgiri", "Anumula Revanth Reddy", "1", " ", "तेलंगाना", "मल्काजगिरि", "अनमुला रेवंत रेड्डी", " "},
        {"Telangana", "Malkajgiri", "Thirupataiah Enduram", "4", " ", "तेलंगाना", "मल्काजगिरि", "थिरुपतैया एंडुराम", " "},
        {"Telangana", "Medak", "Gajabinkar Bansilal", "4", " ", "तेलंगाना", "मेडक", "गजबिन्कर बंसीलाल", " "},
        {"Telangana", "Medak", "Madavaneni Raghunandan Rao", "1", " ", "तेलंगाना", "मेडक", "मदावनेनी रघुनंदन राव", " "},
        {"Telangana", "Medak", "Anil Kumar Gali", "1", " ", "तेलंगाना", "मेडक", "अनिल कुमार गली", " "},
        {"Telangana", "Medak", "Merige Santhosh Reddy", "4", " ", "तेलंगाना", "मेडक", "मेरीज संतोष रेड्डी", " "},
        {"Telangana", "Medak", "Bangaru Krishna", "4", " ", "तेलंगाना", "मेडक", "बंगारु कृष्ण", " "},
        {"Telangana", "Medak", "Madhava Reddy Gari Hanmantha Reddy", "4", " ", "तेलंगाना", "मेडक", "माधव रेड्डी गारी हनमंथा रेड्डी", " "},
        {"Telangana", "Medak", "Thummalapally Pruthviraj", "4", " ", "तेलंगाना", "मेडक", "थुम्मलपल्ली पृथ्वीराज", " "},
        {"Telangana", "Nagarkurnool", "Baaki Renuka", "4", " ", "तेलंगाना", "नगरकुरनूल", "बाकि रेणुका", " "},
        {"Telangana", "Nagarkurnool", "B Yosef", "4", " ", "तेलंगाना", "नगरकुरनूल", "B योसेफ", " "},
        {"Telangana", "Nagarkurnool", "Pothuganti Ramulu", "3", " ", "तेलंगाना", "नगरकुरनूल", "पोथुगांती रामुलु", " "},
        {"Telangana", "Nagarkurnool", "Charagonda Krishnamma", "4", " ", "तेलंगाना", "नगरकुरनूल", "चरगोंदा कृष्णम्मा", " "},
        {"Telangana", "Nagarkurnool", "Shruthi Bangaru", "1", " ", "तेलंगाना", "नगरकुरनूल", "श्रुति बंगारु", " "},
        {"Telangana", "Nagarkurnool", "Dr Mallu Ravi", "1", " ", "तेलंगाना", "नगरकुरनूल", "डॉ मल्लू रवि", " "},
        {"Telangana", "Nagarkurnool", "Srinivasulu Buddula", "4", " ", "तेलंगाना", "नगरकुरनूल", "श्रीनिवासुलु बुद्धु", " "},
        {"Telangana", "Nagarkurnool", "V Amarnath", "4", " ", "तेलंगाना", "नगरकुरनूल", "वी अमरनाथ", " "},
        {"Telangana", "Nagarkurnool", "Prabhudas Bandaru Thumu", "4", " ", "तेलंगाना", "नगरकुरनूल", "प्रभुदास बंडारू ठुमू", " "},
        {"Telangana", "Nagarkurnool", "Karvanga Sharath", "4", " ", "तेलंगाना", "नगरकुरनूल", "करवंगा शरथ", " "},
        {"Telangana", "Nalgonda", "Mallu Laxmi", "2", " ", "तेलंगाना", "नलगोंडा", "मल्लू लक्ष्मी", " "},
        {"Telangana", "Nalgonda", "Nalamada Uttam Kumar Reddy", "1", " ", "तेलंगाना", "नलगोंडा", "नालमदा उत्तम कुमार रेड्डी", " "},
        {"Telangana", "Nalgonda", "Marri. Nehemiah", "4", " ", "तेलंगाना", "नलगोंडा", "मर्री। नहेमायाह", " "},
        {"Telangana", "Nalgonda", "Solipuram Venugopal Reddy", "4", " ", "तेलंगाना", "नलगोंडा", "सोलीपुरम वेणुगोपाल रेड्डी", " "},
        {"Telangana", "Nalgonda", "Lalu Naik Ramavath", "4", " ", "तेलंगाना", "नलगोंडा", "लालू नाइक रामावत", " "},
        {"Telangana", "Nalgonda", "Thandu Upender", "4", " ", "तेलंगाना", "नलगोंडा", "थांडू उपेंद्र", " "},
        {"Telangana", "Nalgonda", "Karamtothu Mangtha", "4", " ", "तेलंगाना", "नलगोंडा", "करमथोथु मंगथा", " "},
        {"Telangana", "Nalgonda", "Polishetty Venkateshwarlu", "4", " ", "तेलंगाना", "नलगोंडा", "पोलीसिट्टी वेंकटेश्वरु", " "},
        {"Telangana", "Nalgonda", "Madhu Sapavath", "4", " ", "तेलंगाना", "नलगोंडा", "मधु सपवथ", " "},
        {"Telangana", "Nalgonda", "Maram Venkat Reddy", "4", " ", "तेलंगाना", "नलगोंडा", "मरम वेंकट रेड्डी", " "},
        {"Telangana", "Nalgonda", "Mekala Venkanna", "4", " ", "तेलंगाना", "नलगोंडा", "मेकाला वेंकन्ना", " "},
        {"Telangana", "Nalgonda", "Akula Paul", "4", " ", "तेलंगाना", "नलगोंडा", "अकुला पॉल", " "},
        {"Telangana", "Nalgonda", "Kiran Vangapalli", "4", " ", "तेलंगाना", "नलगोंडा", "किरण वनपल्ली", " "},
        {"Telangana", "Nalgonda", "Nakirikanti. Chittemma", "4", " ", "तेलंगाना", "नलगोंडा", "Nakirikanti। Chittemma", " "},
        {"Telangana", "Nalgonda", "Garlapati Jithendra Kumar", "1", " ", "तेलंगाना", "नलगोंडा", "गरलापति जितेंद्र कुमार", " "},
        {"Telangana", "Nizamabad", "Tummala Naveen", "4", " ", "तेलंगाना", "निजामाबाद", "तुममला नवीन", " "},
        {"Telangana", "Nizamabad", "Pundra Srinivas Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "पुंद्रा श्रीनिवास रेड्डी", " "},
        {"Telangana", "Nizamabad", "Mahender Nalimela", "4", " ", "तेलंगाना", "निजामाबाद", "महेन्द्र नलिमेला", " "},
        {"Telangana", "Nizamabad", "Asli Ganesh", "4", " ", "तेलंगाना", "निजामाबाद", "असली गणेश", " "},
        {"Telangana", "Nizamabad", "Kondhapuram Narsaiah", "4", " ", "तेलंगाना", "निजामाबाद", "कोंडापुरम नरसैया", " "},
        {"Telangana", "Nizamabad", "Thirupathi Gaddam", "3", " ", "तेलंगाना", "निजामाबाद", "तिरुपति गद्दाम", " "},
        {"Telangana", "Nizamabad", "Sujith Gadepalli", "4", " ", "तेलंगाना", "निजामाबाद", "सुजीत गदपल्ली", " "},
        {"Telangana", "Nizamabad", "Ettedi Saireddy", "4", " ", "तेलंगाना", "निजामाबाद", "एतेदी सैयारेडी", " "},
        {"Telangana", "Nizamabad", "Vinay Tankasaala", "4", " ", "तेलंगाना", "निजामाबाद", "विनय टंकसला", " "},
        {"Telangana", "Nizamabad", "Gummerla Vijay", "4", " ", "तेलंगाना", "निजामाबाद", "गुम्मरला विजय", " "},
        {"Telangana", "Nizamabad", "Anugu Thirumal", "4", " ", "तेलंगाना", "निजामाबाद", "अनुगु थिरुमल", " "},
        {"Telangana", "Nizamabad", "Kumbala Sanjeeva Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "कुंभल संजीव रेड्डी", " "},
        {"Telangana", "Nizamabad", "Lingapuram Bhumeshwar", "4", " ", "तेलंगाना", "निजामाबाद", "लिंगपुरम भुमेश्वर", " "},
        {"Telangana", "Nizamabad", "Enugu Mallesh", "4", " ", "तेलंगाना", "निजामाबाद", "एनुगु मल्लेश", " "},
        {"Telangana", "Nizamabad", "Nalla Nadipi Muthenna", "4", " ", "तेलंगाना", "निजामाबाद", "नल्ला नादिपि मुत्थेना", " "},
        {"Telangana", "Nizamabad", "Macharla Prathap", "4", " ", "तेलंगाना", "निजामाबाद", "मचरला प्रताप", " "},
        {"Telangana", "Nizamabad", "Maggidi Narsaiah Mamidi", "4", " ", "तेलंगाना", "निजामाबाद", "मग्गिदी नरसैया मामीदी", " "},
        {"Telangana", "Nizamabad", "Theegala Thirupathi Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "थेगला थिरुपथी रेड्डी", " "},
        {"Telangana", "Nizamabad", "Bakkashetti Ganagdhar", "4", " ", "तेलंगाना", "निजामाबाद", "बकाक्षेति गणगधर", " "},
        {"Telangana", "Nizamabad", "Gaddam Gangareddy", "4", " ", "तेलंगाना", "निजामाबाद", "गद्दाम गैंगरेड्डी", " "},
        {"Telangana", "Nizamabad", "Srinivas Gundeti", "4", " ", "तेलंगाना", "निजामाबाद", "श्रीनिवास गुंडेटी", " "},
        {"Telangana", "Nizamabad", "Soma Srinivas", "4", " ", "तेलंगाना", "निजामाबाद", "सोमा श्रीनिवास", " "},
        {"Telangana", "Nizamabad", "Bodugam Narender", "4", " ", "तेलंगाना", "निजामाबाद", "बोधुगम नरेंद्र", " "},
        {"Telangana", "Nizamabad", "Raja Venkat Reddy Pashapu", "4", " ", "तेलंगाना", "निजामाबाद", "राजा वेंकट रेड्डी पाशुपु", " "},
        {"Telangana", "Nizamabad", "Linga Reddy Santha", "4", " ", "तेलंगाना", "निजामाबाद", "लिंगा रेड्डी संथा", " "},
        {"Telangana", "Nizamabad", "Gujjula Ramesh", "4", " ", "तेलंगाना", "निजामाबाद", "गुजुला रमेश", " "},
        {"Telangana", "Nizamabad", "Mahesh Rayidi", "4", " ", "तेलंगाना", "निजामाबाद", "महेश रायदी", " "},
        {"Telangana", "Nizamabad", "Maggidi Katipally Rajesh", "4", " ", "तेलंगाना", "निजामाबाद", "मग्गी कटिपल्ली राजेश", " "},
        {"Telangana", "Nizamabad", "Venkatesh Kola", "2", " ", "तेलंगाना", "निजामाबाद", "वेंकटेश कोला", " "},
        {"Telangana", "Nizamabad", "Sai Reddy Puttiniti", "4", " ", "तेलंगाना", "निजामाबाद", "साई रेड्डी पुतिनिती", " "},
        {"Telangana", "Nizamabad", "Admala Mahipal Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "अदमाला महिपाल रेड्डी", " "},
        {"Telangana", "Nizamabad", "Kongari Sanjiv", "4", " ", "तेलंगाना", "निजामाबाद", "कोंगरी संजीव", " "},
        {"Telangana", "Nizamabad", "Swami Reddy Sama", "4", " ", "तेलंगाना", "निजामाबाद", "स्वामी रेड्डी साम", " "},
        {"Telangana", "Nizamabad", "Gangareddy Mailaram", "4", " ", "तेलंगाना", "निजामाबाद", "गंगारेड्डी मेलाराम", " "},
        {"Telangana", "Nizamabad", "N Mallareddy", "4", " ", "तेलंगाना", "निजामाबाद", "एन मल्लारेड्डी", " "},
        {"Telangana", "Nizamabad", "Nomula Mohan Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "नोमुला मोहन रेड्डी", " "},
        {"Telangana", "Nizamabad", "Ganga Reddy Peesu Peesu", "4", " ", "तेलंगाना", "निजामाबाद", "गंगा रेड्डी पीसू पीसू", " "},
        {"Telangana", "Nizamabad", "Mittapally Jeevan Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "मित्तपल्ली जीवन रेड्डी", " "},
        {"Telangana", "Nizamabad", "Madhusudan Alias Madhu Goud Yaskhi", "1", " ", "तेलंगाना", "निजामाबाद", "मधुसूदन उर्फ मधु गौड़ यक्षी", " "},
        {"Telangana", "Nizamabad", "Theetla Anil", "4", " ", "तेलंगाना", "निजामाबाद", "थेटला अनिल", " "},
        {"Telangana", "Nizamabad", "Gangareddy Musku", "4", " ", "तेलंगाना", "निजामाबाद", "गंगरेड्डी मुस्कु", " "},
        {"Telangana", "Nizamabad", "M. Malla Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "एम। मल्ला रेड्डी", " "},
        {"Telangana", "Nizamabad", "Rajareddi Rikkala", "4", " ", "तेलंगाना", "निजामाबाद", "राजारेड्डी रिक्कला", " "},
        {"Telangana", "Nizamabad", "Santhosh Kamareddy", "4", " ", "तेलंगाना", "निजामाबाद", "संतोष कमारेड्डी", " "},
        {"Telangana", "Nizamabad", "K Kavitha", "2", " ", "तेलंगाना", "निजामाबाद", "के कविथा", " "},
        {"Telangana", "Nizamabad", "Rajendar Pasapu", "4", " ", "तेलंगाना", "निजामाबाद", "राजेन्द्र पसापू", " "},
        {"Telangana", "Nizamabad", "Baddam Devendar", "4", " ", "तेलंगाना", "निजामाबाद", "बददाम देवेन्द्र", " "},
        {"Telangana", "Nizamabad", "Nemilla Linga Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "नेमिला लिंगा रेड्डी", " "},
        {"Telangana", "Nizamabad", "Sama Bhaskar Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "साम भास्कर रेड्डी", " "},
        {"Telangana", "Nizamabad", "Gaddam Rajeshwar", "4", " ", "तेलंगाना", "निजामाबाद", "गद्दाम राजेश्वर", " "},
        {"Telangana", "Nizamabad", "Kommula Buchireddy", "4", " ", "तेलंगाना", "निजामाबाद", "कोमूला बुचिरेड्डी", " "},
        {"Telangana", "Nizamabad", "Bejjenki Linga Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "बेजेंकी लिंग रेड्डी", " "},
        {"Telangana", "Nizamabad", "Aleti Malla Reddy", "2", " ", "तेलंगाना", "निजामाबाद", "अलेटि मल्ला रेड्डी", " "},
        {"Telangana", "Nizamabad", "Pedda Gangaram Turpu", "4", " ", "तेलंगाना", "निजामाबाद", "पेड़ा गंगाराम तुरपु", " "},
        {"Telangana", "Nizamabad", "Gadepalli Prthviraj", "4", " ", "तेलंगाना", "निजामाबाद", "गदपल्ली पृथ्वीराज", " "},
        {"Telangana", "Nizamabad", "Chinthalapally Raghupathi Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "चिन्तलपल्ली रघुपति रेड्डी", " "},
        {"Telangana", "Nizamabad", "Rapelly Srinivas", "4", " ", "तेलंगाना", "निजामाबाद", "रापेली श्रीनिवास", " "},
        {"Telangana", "Nizamabad", "Dabba Raja Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "डब्बा राजा रेड्डी", " "},
        {"Telangana", "Nizamabad", "Natta Bavanna", "4", " ", "तेलंगाना", "निजामाबाद", "नत्त बवाना", " "},
        {"Telangana", "Nizamabad", "Venkat Reddy Jaidi", "4", " ", "तेलंगाना", "निजामाबाद", "वेंकट रेड्डी जैदी", " "},
        {"Telangana", "Nizamabad", "Edamala Ravinder Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "एडमाला रविन्दर रेड्डी", " "},
        {"Telangana", "Nizamabad", "Hanmandlu Puppala", "4", " ", "तेलंगाना", "निजामाबाद", "हनमंडलु पुपाल", " "},
        {"Telangana", "Nizamabad", "Gaddam Rajendharreddy", "4", " ", "तेलंगाना", "निजामाबाद", "गद्दाम राजेन्द्रहेडी", " "},
        {"Telangana", "Nizamabad", "Muthenna Lakkara", "4", " ", "तेलंगाना", "निजामाबाद", "मुथेना लकड़ा", " "},
        {"Telangana", "Nizamabad", "Penta Narsaiah", "4", " ", "तेलंगाना", "निजामाबाद", "पेंटा नरसैया", " "},
        {"Telangana", "Nizamabad", "Gadepally Ramesh", "4", " ", "तेलंगाना", "निजामाबाद", "गद्दीपद रमेश", " "},
        {"Telangana", "Nizamabad", "Balije Laxmirajam", "4", " ", "तेलंगाना", "निजामाबाद", "बलिजे लक्ष्मीराजम्", " "},
        {"Telangana", "Nizamabad", "Ravindhar Bandi", "4", " ", "तेलंगाना", "निजामाबाद", "रविन्द्र बांधी", " "},
        {"Telangana", "Nizamabad", "Rotte Chakradhar Sharma", "4", " ", "तेलंगाना", "निजामाबाद", "रोट चक्रधर शर्मा", " "},
        {"Telangana", "Nizamabad", "Laxman Ganna", "4", " ", "तेलंगाना", "निजामाबाद", "लक्ष्मण गण", " "},
        {"Telangana", "Nizamabad", "Rajashekar Sarikela", "4", " ", "तेलंगाना", "निजामाबाद", "राजशेखर सरीकेला", " "},
        {"Telangana", "Nizamabad", "Aare Sayanna", "4", " ", "तेलंगाना", "निजामाबाद", "आरे स्याना", " "},
        {"Telangana", "Nizamabad", "Pedda Gangadar Talari", "4", " ", "तेलंगाना", "निजामाबाद", "पेड़ा गंगाधर तलारी", " "},
        {"Telangana", "Nizamabad", "Gaddam Suman", "4", " ", "तेलंगाना", "निजामाबाद", "गद्दाम सुमन", " "},
        {"Telangana", "Nizamabad", "Linga Reddy Doddikindi", "4", " ", "तेलंगाना", "निजामाबाद", "लिंगा रेड्डी डोडिकंडी", " "},
        {"Telangana", "Nizamabad", "Aleti Rajareddy", "4", " ", "तेलंगाना", "निजामाबाद", "अलेटी राजारेड्डी", " "},
        {"Telangana", "Nizamabad", "Prakash Manchiryala", "3", " ", "तेलंगाना", "निजामाबाद", "प्रकाश मंचरीला", " "},
        {"Telangana", "Nizamabad", "Kandukala Shiva Kumar Goud", "4", " ", "तेलंगाना", "निजामाबाद", "कंदुकला शिव कुमार गौड़", " "},
        {"Telangana", "Nizamabad", "Mandala Shekhar", "4", " ", "तेलंगाना", "निजामाबाद", "मंडल शेखर", " "},
        {"Telangana", "Nizamabad", "Aloori Anil Kumar", "4", " ", "तेलंगाना", "निजामाबाद", "अलोरी अनिल कुमार", " "},
        {"Telangana", "Nizamabad", "Bathnathe Shankar", "4", " ", "तेलंगाना", "निजामाबाद", "बथनाथे शंकर", " "},
        {"Telangana", "Nizamabad", "Limba Reddy Perkit", "4", " ", "तेलंगाना", "निजामाबाद", "लिम्बा रेड्डी पर्किट", " "},
        {"Telangana", "Nizamabad", "Narsareddy Pannala", "4", " ", "तेलंगाना", "निजामाबाद", "नरसारेड्डी पन्नाला", " "},
        {"Telangana", "Nizamabad", "Kurma Divakar", "4", " ", "तेलंगाना", "निजामाबाद", "कूर्म दिवाकर", " "},
        {"Telangana", "Nizamabad", "Komati Reddy Prashanth", "2", " ", "तेलंगाना", "निजामाबाद", "कोमाती रेड्डी प्रशांत", " "},
        {"Telangana", "Nizamabad", "Loka Subhash", "2", " ", "तेलंगाना", "निजामाबाद", "लोका सुभाष", " "},
        {"Telangana", "Nizamabad", "Mamidi Thirupathireddy", "4", " ", "तेलंगाना", "निजामाबाद", "ममीदी थिरुपथिरेड्डी", " "},
        {"Telangana", "Nizamabad", "Nadisharam Mallaiah", "4", " ", "तेलंगाना", "निजामाबाद", "नादिशारम मल्लैया", " "},
        {"Telangana", "Nizamabad", "Gadkolu Ramesh", "4", " ", "तेलंगाना", "निजामाबाद", "गडकोलु रमेश", " "},
        {"Telangana", "Nizamabad", "Santosh Komamula", "4", " ", "तेलंगाना", "निजामाबाद", "संतोष कोमूला", " "},
        {"Telangana", "Nizamabad", "Urumalla Lakshma Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "उरुमल लक्ष्मण रेड्डी", " "},
        {"Telangana", "Nizamabad", "Nadipi Gangaram Niradi", "4", " ", "तेलंगाना", "निजामाबाद", "नादिपि गंगाराम निरादी", " "},
        {"Telangana", "Nizamabad", "Alakunta Rajanna", "4", " ", "तेलंगाना", "निजामाबाद", "अलकुन्ता राजन्ना", " "},
        {"Telangana", "Nizamabad", "Suresh Baddam", "4", " ", "तेलंगाना", "निजामाबाद", "सुरेश बद्दाम", " "},
        {"Telangana", "Nizamabad", "Nagulapalli Devendhar", "4", " ", "तेलंगाना", "निजामाबाद", "नागुलपल्ली देवेंद्र", " "},
        {"Telangana", "Nizamabad", "Mekkonda Ramreddy", "4", " ", "तेलंगाना", "निजामाबाद", "मेककोंडा रामरेड्डी", " "},
        {"Telangana", "Nizamabad", "Mittapalli Malliah", "4", " ", "तेलंगाना", "निजामाबाद", "मित्तपल्ली मल्लाह", " "},
        {"Telangana", "Nizamabad", "Jaidi Chinna Gangaram", "4", " ", "तेलंगाना", "निजामाबाद", "जैदी चिन्ना गंगाराम", " "},
        {"Telangana", "Nizamabad", "Goskula Mahesh Babu", "4", " ", "तेलंगाना", "निजामाबाद", "गोसकुला महेश बाबू", " "},
        {"Telangana", "Nizamabad", "Anjaiah Kondani", "4", " ", "तेलंगाना", "निजामाबाद", "अंजिया कोंडानी", " "},
        {"Telangana", "Nizamabad", "Ganganna Chilkuri", "4", " ", "तेलंगाना", "निजामाबाद", "गंगना चिलकुरी", " "},
        {"Telangana", "Nizamabad", "Santosh Barla", "4", " ", "तेलंगाना", "निजामाबाद", "संतोष बराला", " "},
        {"Telangana", "Nizamabad", "Dharmapuri Arvind", "1", " ", "तेलंगाना", "निजामाबाद", "धर्मपुरी अरविंद", " "},
        {"Telangana", "Nizamabad", "Gangadhar Baddam", "4", " ", "तेलंगाना", "निजामाबाद", "गंगाधर बादाम", " "},
        {"Telangana", "Nizamabad", "Gangareddy Thorthi", "4", " ", "तेलंगाना", "निजामाबाद", "गंगारेड्डी थोरथी", " "},
        {"Telangana", "Nizamabad", "Ramesh Reddy Sama", "4", " ", "तेलंगाना", "निजामाबाद", "रमेश रेड्डी समामा", " "},
        {"Telangana", "Nizamabad", "Turaga Narsareddy", "4", " ", "तेलंगाना", "निजामाबाद", "तुरगा नरसारेड्डी", " "},
        {"Telangana", "Nizamabad", "Baddam Indrasena Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "बादाम इंद्रसेन रेड्डी", " "},
        {"Telangana", "Nizamabad", "Guradi Srinivas", "4", " ", "तेलंगाना", "निजामाबाद", "गुरदी श्रीनिवास", " "},
        {"Telangana", "Nizamabad", "K. Ram Raj", "4", " ", "तेलंगाना", "निजामाबाद", "के राम राज", " "},
        {"Telangana", "Nizamabad", "Katipally Kumar", "4", " ", "तेलंगाना", "निजामाबाद", "काटिपल्ली कुमार", " "},
        {"Telangana", "Nizamabad", "Bandela Venkatarajam", "4", " ", "तेलंगाना", "निजामाबाद", "बंदेला वेंकटराजम", " "},
        {"Telangana", "Nizamabad", "Velma Mallareddy", "4", " ", "तेलंगाना", "निजामाबाद", "वेलमा मल्लेरड्डी", " "},
        {"Telangana", "Nizamabad", "Balakishna Nalla", "4", " ", "तेलंगाना", "निजामाबाद", "बालकृष्ण नाला", " "},
        {"Telangana", "Nizamabad", "Kunta Narayana Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "कुंता नारायण रेड्डी", " "},
        {"Telangana", "Nizamabad", "Narsaiah Gunda", "4", " ", "तेलंगाना", "निजामाबाद", "नरसैया गुंडा", " "},
        {"Telangana", "Nizamabad", "Eleti Laxmareddy", "4", " ", "तेलंगाना", "निजामाबाद", "एलेटि लक्ष्मर्दी", " "},
        {"Telangana", "Nizamabad", "Gangareddy Rikkala", "4", " ", "तेलंगाना", "निजामाबाद", "गंगरेड्डी रिक्काला", " "},
        {"Telangana", "Nizamabad", "Rajareddy Gangasaram", "4", " ", "तेलंगाना", "निजामाबाद", "राजारेड्डी गंगासाराम", " "},
        {"Telangana", "Nizamabad", "Suman Maggidi", "4", " ", "तेलंगाना", "निजामाबाद", "सुमन मग्गिदी", " "},
        {"Telangana", "Nizamabad", "Theegala Ashok Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "थेगला अशोक रेड्डी", " "},
        {"Telangana", "Nizamabad", "Sayanna Bai", "4", " ", "तेलंगाना", "निजामाबाद", "सयना बाई", " "},
        {"Telangana", "Nizamabad", "Mahendhar Kottala", "4", " ", "तेलंगाना", "निजामाबाद", "महेंद्र कोट्टला", " "},
        {"Telangana", "Nizamabad", "Chintalapelly Gangareddy", "4", " ", "तेलंगाना", "निजामाबाद", "चिंतलपेली गंगारेड्डी", " "},
        {"Telangana", "Nizamabad", "Thirupathi Reddy Pannala", "4", " ", "तेलंगाना", "निजामाबाद", "तिरुपति रेड्डी पन्नला", " "},
        {"Telangana", "Nizamabad", "Devanna Pindi", "3", " ", "तेलंगाना", "निजामाबाद", "देवना पिंडी", " "},
        {"Telangana", "Nizamabad", "Baddam Ashok", "4", " ", "तेलंगाना", "निजामाबाद", "बद्दाम अशोक", " "},
        {"Telangana", "Nizamabad", "Ippa Lachchanna", "4", " ", "तेलंगाना", "निजामाबाद", "इप्पा लछन्ना", " "},
        {"Telangana", "Nizamabad", "Rajeshwar Musku", "4", " ", "तेलंगाना", "निजामाबाद", "राजेश्वर मुस्कु", " "},
        {"Telangana", "Nizamabad", "Surakanti Raja Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "सुरकांति राजा रेड्डी", " "},
        {"Telangana", "Nizamabad", "Rajeshwar Enugu", "4", " ", "तेलंगाना", "निजामाबाद", "राजेश्वर एनुगु", " "},
        {"Telangana", "Nizamabad", "Medipalli Shekar Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "मेडिपल्ली शकर रेड्डी", " "},
        {"Telangana", "Nizamabad", "Akula Hanmandlu", "4", " ", "तेलंगाना", "निजामाबाद", "अकुला हनमंडलु", " "},
        {"Telangana", "Nizamabad", "Mamidi Chinna Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "ममदी चिन्ना रेड्डी", " "},
        {"Telangana", "Nizamabad", "Maru Janardhan", "4", " ", "तेलंगाना", "निजामाबाद", "मारु जनार्दन", " "},
        {"Telangana", "Nizamabad", "Gangadhar Andheti", "4", " ", "तेलंगाना", "निजामाबाद", "गंगाधर अन्धेती", " "},
        {"Telangana", "Nizamabad", "Alluri Limba Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "अल्लूरी लिम्बा रेड्डी", " "},
        {"Telangana", "Nizamabad", "Borranna Gummerla", "4", " ", "तेलंगाना", "निजामाबाद", "बोरना गुम्मरला", " "},
        {"Telangana", "Nizamabad", "Mohanareddy Eleti", "4", " ", "तेलंगाना", "निजामाबाद", "मोहनरेड्डी एलेटि", " "},
        {"Telangana", "Nizamabad", "Angu Poshetty", "4", " ", "तेलंगाना", "निजामाबाद", "आंगु पाशेति", " "},
        {"Telangana", "Nizamabad", "Chinnaiah Mukkera", "4", " ", "तेलंगाना", "निजामाबाद", "चिन्नाहिया मुकेरा", " "},
        {"Telangana", "Nizamabad", "Byagari Shanthaiah", "4", " ", "तेलंगाना", "निजामाबाद", "बयागरी शांतिहाया", " "},
        {"Telangana", "Nizamabad", "Sandireddy Gopal Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "संदीपारी गोपाल रेड्डी", " "},
        {"Telangana", "Nizamabad", "Praveen Paidigela", "4", " ", "तेलंगाना", "निजामाबाद", "प्रवीण पेडिगेला", " "},
        {"Telangana", "Nizamabad", "Mahendhar Musku", "4", " ", "तेलंगाना", "निजामाबाद", "महेंद्र मुस्कू", " "},
        {"Telangana", "Nizamabad", "Ravishankar Kunta", "4", " ", "तेलंगाना", "निजामाबाद", "रविशंकर कुंता", " "},
        {"Telangana", "Nizamabad", "Pothuganti Venkatesh", "4", " ", "तेलंगाना", "निजामाबाद", "पोथुगांती वेंकटेश", " "},
        {"Telangana", "Nizamabad", "B. Srinivas", "4", " ", "तेलंगाना", "निजामाबाद", "बी। श्रीनिवास", " "},
        {"Telangana", "Nizamabad", "Armoor Sagar", "4", " ", "तेलंगाना", "निजामाबाद", "कवच सागर", " "},
        {"Telangana", "Nizamabad", "J. Chinna Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "जे। चिन्ना रेड्डी", " "},
        {"Telangana", "Nizamabad", "Baddam Balaraju", "4", " ", "तेलंगाना", "निजामाबाद", "बादाम बलराजु", " "},
        {"Telangana", "Nizamabad", "Gadkole Chinna Gangareddy", "4", " ", "तेलंगाना", "निजामाबाद", "गडकोले चिन्ना गंगारेड्डी", " "},
        {"Telangana", "Nizamabad", "Teegala Rajeshwar", "4", " ", "तेलंगाना", "निजामाबाद", "तेगला राजेश्वर", " "},
        {"Telangana", "Nizamabad", "Doda Mutta Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "डोडा मुत्ता रेड्डी", " "},
        {"Telangana", "Nizamabad", "Aleti Sanjeev Reddy", "4", " ", "तेलंगाना", "निजामाबाद", "अलेटि संजीव रेड्डी", " "},
        {"Telangana", "Nizamabad", "Surukanti Chinna Anjaiah", "4", " ", "तेलंगाना", "निजामाबाद", "सुरुकन्ती चिन्ना अंजैया", " "},
        {"Telangana", "Nizamabad", "Gajjala Sai Prasad", "4", " ", "तेलंगाना", "निजामाबाद", "गज्जला साईं प्रसाद", " "},
        {"Telangana", "Peddapalle", "Arsham Ashok", "4", " ", "तेलंगाना", "पेडेपल्लै", "अरशम अशोक", " "},
        {"Telangana", "Peddapalle", "Sankenapalli. Devadas", "4", " ", "तेलंगाना", "पेडेपल्लै", "Sankenapalli। देवदास", " "},
        {"Telangana", "Peddapalle", "Velthuru Mallaiah", "4", " ", "तेलंगाना", "पेडेपल्लै", "वेल्थुरु मल्लैया", " "},
        {"Telangana", "Peddapalle", "Godisella Nagamani", "4", " ", "तेलंगाना", "पेडेपल्लै", "गोडिसेला नागमणि", " "},
        {"Telangana", "Peddapalle", "Dr. Agama Chandrashekar", "1", " ", "तेलंगाना", "पेडेपल्लै", "डॉ। अगमा चंद्रशेखर", " "},
        {"Telangana", "Peddapalle", "Sirikonda Krishna", "4", " ", "तेलंगाना", "पेडेपल्लै", "सिरिकोंडा कृष्णा", " "},
        {"Telangana", "Peddapalle", "Gaddala Vinay Kumar", "4", " ", "तेलंगाना", "पेडेपल्लै", "गद्दाला विनय कुमार", " "},
        {"Telangana", "Peddapalle", "Ambala Mahendar", "4", " ", "तेलंगाना", "पेडेपल्लै", "अंबाला महेंद्र", " "},
        {"Telangana", "Peddapalle", "Kuntala Narsaiah", "4", " ", "तेलंगाना", "पेडेपल्लै", "कुंतला नरसैया", " "},
        {"Telangana", "Peddapalle", "Krishna Sabbani", "2", " ", "तेलंगाना", "पेडेपल्लै", "कृष्णा सबबानी", " "},
        {"Telangana", "Peddapalle", "Kumar Sogula", "1", " ", "तेलंगाना", "पेडेपल्लै", "कुमार सोगुला", " "},
        {"Telangana", "Secunderabad", "Gangapuram Kishan Reddy", "1", " ", "तेलंगाना", "सिकंदराबाद", "गंगापुरम किशन रेड्डी", " "},
        {"Telangana", "Secunderabad", "R Laxman Rao Gangaputra", "4", " ", "तेलंगाना", "सिकंदराबाद", "आर लक्ष्मण राव गंगापुत्र", " "},
        {"Telangana", "Secunderabad", "Shakti Satayavathi", "4", " ", "तेलंगाना", "सिकंदराबाद", "शक्ति सत्यवती", " "},
        {"Telangana", "Secunderabad", "G . Laxminarsimha Rao", "2", " ", "तेलंगाना", "सिकंदराबाद", "जी। लक्ष्मीनारसिम्हा राव", " "},
        {"Telangana", "Secunderabad", "Anjan Kumar Yadav", "1", " ", "तेलंगाना", "सिकंदराबाद", "अंजन कुमार यादव", " "},
        {"Telangana", "Secunderabad", "Dornala Jaya Prakash", "2", " ", "तेलंगाना", "सिकंदराबाद", "दोरनाला जय प्रकाश", " "},
        {"Telangana", "Secunderabad", "Bathula Ravi", "4", " ", "तेलंगाना", "सिकंदराबाद", "बथुला रवि", " "},
        {"Telangana", "Secunderabad", "Junaid Anam Siddiqui", "4", " ", "तेलंगाना", "सिकंदराबाद", "जुनैद अनम सिद्दीकी", " "},
        {"Telangana", "Secunderabad", "N . Shankar Goud", "4", " ", "तेलंगाना", "सिकंदराबाद", "एन। शंकर गौड", " "},
        {"Telangana", "Secunderabad", "Talasani Sai Kiran", "2", " ", "तेलंगाना", "सिकंदराबाद", "तलसानी साई किरन", " "},
        {"Telangana", "Secunderabad", "Abdul Azeem", "4", " ", "तेलंगाना", "सिकंदराबाद", "अब्दुल अज़ीम", " "},
        {"Telangana", "Secunderabad", "M . D . Nazeer Uddin Quadri", "4", " ", "तेलंगाना", "सिकंदराबाद", "एम। डी। नज़ीर उद्दीन क्वाडरी", " "},
        {"Telangana", "Secunderabad", "Shaik Muneer Pasha", "4", " ", "तेलंगाना", "सिकंदराबाद", "शेख मुनीर पाशा", " "},
        {"Telangana", "Secunderabad", "Farah Naaz Khan", "4", " ", "तेलंगाना", "सिकंदराबाद", "फराह नाज़ खान", " "},
        {"Telangana", "Secunderabad", "Abdallah Ibrahim", "4", " ", "तेलंगाना", "सिकंदराबाद", "अब्दुल्ला इब्राहिम", " "},
        {"Telangana", "Secunderabad", "K Venkatanarayana", "4", " ", "तेलंगाना", "सिकंदराबाद", "के वेंकटनारायण", " "},
        {"Telangana", "Secunderabad", "Srirama Naik Munavath", "2", " ", "तेलंगाना", "सिकंदराबाद", "श्रीराम नाइक मुनवथ", " "},
        {"Telangana", "Warangal", "Chintha Sambamurthy", "1", " ", "तेलंगाना", "वारंगल", "चिन्ता सम्बामूर्ति", " "},
        {"Telangana", "Warangal", "Kannam Venkanna", "4", " ", "तेलंगाना", "वारंगल", "कन्नम वेंकन्ना", " "},
        {"Telangana", "Warangal", "Pasula Rammurthy", "4", " ", "तेलंगाना", "वारंगल", "पसुला राममूर्ति", " "},
        {"Telangana", "Warangal", "Sambaiah Dommati", "1", " ", "तेलंगाना", "वारंगल", "सांभिया दम्मति", " "},
        {"Telangana", "Warangal", "Chiluveru Prathap", "4", " ", "तेलंगाना", "वारंगल", "चिलुवरु प्रताप", " "},
        {"Telangana", "Warangal", "Paniganti Rajithavani", "4", " ", "तेलंगाना", "वारंगल", "पाणिगंति राजितवनी", " "},
        {"Telangana", "Warangal", "Bunga Jyothi Ramana", "2", " ", "तेलंगाना", "वारंगल", "बुंगा ज्योति रमणा", " "},
        {"Telangana", "Warangal", "Aitha Praveen Kumar", "4", " ", "तेलंगाना", "वारंगल", "ऐथा प्रवीण कुमार", " "},
        {"Telangana", "Warangal", "Jannu Narsaiah", "2", " ", "तेलंगाना", "वारंगल", "जन्नु नरसैया", " "},
        {"Telangana", "Warangal", "Suresh Kanakam", "4", " ", "तेलंगाना", "वारंगल", "सुरेश कनकम", " "},
        {"Telangana", "Zahirabad", "Mudiraj Venkatesham", "4", " ", "तेलंगाना", "जहीराबाद", "मुदिराज वेंकटेशम", " "},
        {"Telangana", "Zahirabad", "B.B.Patil", "2", " ", "तेलंगाना", "जहीराबाद", "BBPatil", " "},
        {"Telangana", "Zahirabad", "Mark Babu", "2", " ", "तेलंगाना", "जहीराबाद", "मार्क बाबू", " "},
        {"Telangana", "Zahirabad", "Banala Laxma Reddy", "1", " ", "तेलंगाना", "जहीराबाद", "बनाला लक्ष्मा रेड्डी", " "},
        {"Telangana", "Zahirabad", "K. Madan Mohan Rao", "1", " ", "तेलंगाना", "जहीराबाद", "के। मदन मोहन राव", " "},
        {"Telangana", "Zahirabad", "Mohammed Nawaz", "4", " ", "तेलंगाना", "जहीराबाद", "मोहम्मद नवाज", " "},
};

}