/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Telangana {
public static final String[][] green_bucket = {
{"Telangana",  "5280", "Adilabad", "Godam Nagesh", "Telangana Rashtra Samithi", "1.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5814",  "तेलंगाना",  "आदिलाबाद", "गोधाम नागेश", "तेलंगाना राष्ट्र समिति", ""}, 
{"Telangana",  "5281", "Adilabad", "Pawar Krishna", "Independent", "11.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5824",  "तेलंगाना",  "आदिलाबाद", "पवार कृष्ण", "निर्दलीय", ""}, 
{"Telangana",  "5286", "Adilabad", "Ganta Pentanna", "Independent", "6.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5813",  "तेलंगाना",  "आदिलाबाद", "गन्ता पेन्टाना", "निर्दलीय", ""}, 
{"Telangana",  "5287", "Adilabad", "Dharavth Narendhar", "Janasena Party", "50000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5815",  "तेलंगाना",  "आदिलाबाद", "धरावत नरेंद्र", "जनसेना पार्टी", ""}, 
{"Telangana",  "5972", "Bhongir", "Samrat Narender Boilla", "Republican Party of India", "35.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6861",  "तेलंगाना",  "भोंगीर", "सम्राट नरेन्द्र बोइला", "रिपब्लिकन पार्टी ऑफ इंडिया", ""}, 
{"Telangana",  "5977", "Bhongir", "Dr. Narsaiah Boora", "Telangana Rashtra Samithi", "23.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5089",  "तेलंगाना",  "भोंगीर", "डॉ। नरसैया बोरिया", "तेलंगाना राष्ट्र समिति", ""}, 
{"Telangana",  "5979", "Bhongir", "Sapavat Devaram", "Independent", "64986", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6867",  "तेलंगाना",  "भोंगीर", "सपवत देवराम", "निर्दलीय", ""}, 
{"Telangana",  "5981", "Bhongir", "Moorigaadi Krishna", "Independent", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6860",  "तेलंगाना",  "भोंगीर", "मूरईगाड़ी कृष्णा", "निर्दलीय", ""}, 
{"Telangana",  "5899", "Chevella", "Sanem Raju Goud", "Independent", "21.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6829",  "तेलंगाना",  "चेवेल्ला", "सनम राजू गौड", "निर्दलीय", ""}, 
{"Telangana",  "5900", "Chevella", "Anusha Keshavabhatla", "Independent", "92.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6818",  "तेलंगाना",  "चेवेल्ला", "अनुषा केशवभटला", "निर्दलीय", ""}, 
{"Telangana",  "5904", "Chevella", "Ija Venkatesh Goud", "Social Justice Party of India", "98Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6823",  "तेलंगाना",  "चेवेल्ला", "इजा वेंकटेश गौड", "सोशल जस्टिस पार्टी ऑफ इंडिया", ""}, 
{"Telangana",  "5906", "Chevella", "P. Purushotham", "Independent", "2.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6826",  "तेलंगाना",  "चेवेल्ला", "पी। पुरुषोत्तम", "निर्दलीय", ""}, 
{"Telangana",  "5908", "Chevella", "T. Durga Prasad", "Independent", "2.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6830",  "तेलंगाना",  "चेवेल्ला", "टी। दुर्गा प्रसाद", "निर्दलीय", ""}, 
{"Telangana",  "5910", "Chevella", "Dr.Gaddam Ranjith Reddy", "Telangana Rashtra Samithi", "163.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4846",  "तेलंगाना",  "चेवेल्ला", "डॉ। गद्दाम रंजीथ रेड्डी", "तेलंगाना राष्ट्र समिति", ""}, 
{"Telangana",  "5914", "Chevella", "Ragam Sathesh Yadav", "All India Forward Bloc", "4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6828",  "तेलंगाना",  "चेवेल्ला", "रागम सठेश यादव", "ऑल इंडिया फॉरवर्ड ब्लॉक", ""}, 
{"Telangana",  "5921", "Chevella", "G. Ravi Kumar Yadav", "Independent", "91000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6822",  "तेलंगाना",  "चेवेल्ला", "जी। रवि कुमार यादव", "निर्दलीय", ""}, 
{"Telangana",  "5891", "Hyderabad", "V Bal Krishna", "Independent", "2.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6804",  "तेलंगाना",  "हैदराबाद", "वी बाल कृष्ण", "निर्दलीय", ""}, 
{"Telangana",  "5885", "Hyderabad", "Pusthe Srikanth", "Telangana Rashtra Samithi", "3.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6800",  "तेलंगाना",  "हैदराबाद", "पुस्टे श्रीकांत", "तेलंगाना राष्ट्र समिति", ""}, 
{"Telangana",  "5308", "Karimnagar", "Vinod Kumar Boianapalli", "Telangana Rashtra Samithi", "12.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4593",  "तेलंगाना",  "करीमनगर", "विनोद कुमार बोयनापल्ली", "तेलंगाना राष्ट्र समिति", ""}, 
{"Telangana",  "5309", "Karimnagar", "Chintha Anil Kumar", "Pyramid Party of India", "25000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4592",  "तेलंगाना",  "करीमनगर", "चिंथा अनिल कुमार", "पिरामिड पार्टी ऑफ इंडिया", ""}, 
{"Telangana",  "5314", "Karimnagar", "Rameshbabu Shanigarapu", "Independent", "56500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4827",  "तेलंगाना",  "करीमनगर", "रमेशबाबू शनीगारपु", "निर्दलीय", ""}, 
{"Telangana",  "5318", "Karimnagar", "Palle Prashanth", "Jai Swaraj Party", "36.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4633",  "तेलंगाना",  "करीमनगर", "पलले प्रशांत", "जय स्वराज पार्टी", ""}, 
{"Telangana",  "5320", "Karimnagar", "Reddy Venugopal", "Samajwadi Forward Bloc", "30500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6277",  "तेलंगाना",  "करीमनगर", "रेड्डी वेणुगोपाल", "समाजवादी फॉरवर्ड ब्लॉक", ""}, 
{"Telangana",  "6014", "Khammam", "Mutyam Arjuna Raju", "Independent", "24.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6905",  "तेलंगाना",  "खम्मम", "मुतम अर्जुन राजू", "निर्दलीय", ""}, 
{"Telangana",  "6017", "Khammam", "Lakavath Nageswara Rao", "Bahujan Mukti Party", "7.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6896",  "तेलंगाना",  "खम्मम", "लखावत नागेश्वर राव", "बहुजन मुक्ति पार्टी", ""}, 
{"Telangana",  "6020", "Khammam", "Boda Venkat", "Communist Party of India (Marxist)", "96.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4868",  "तेलंगाना",  "खम्मम", "बोड़ा वेंकट", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)", ""}, 
{"Telangana",  "6021", "Khammam", "Umamaheswara Rao Cherukupalli", "Telangana Yuva Shakti", "76.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6892",  "तेलंगाना",  "खम्मम", "उमामहेश्वर राव चेरुपुपल्ली", "तेलंगाना युवा शक्ति", ""}, 
{"Telangana",  "6023", "Khammam", "Dunuku Veladri", "Independent", "5.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6902",  "तेलंगाना",  "खम्मम", "दुनुकु वलाद्री", "निर्दलीय", ""}, 
{"Telangana",  "6025", "Khammam", "Narala Satyanarayana", "Janasena Party", "22Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6895",  "तेलंगाना",  "खम्मम", "नारला सत्यनारायण", "जनसेना पार्टी", ""}, 
{"Telangana",  "6028", "Khammam", "Shankara Rao Gopagani", "Independent", "66.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6901",  "तेलंगाना",  "खम्मम", "शंकर राव गोपगानी", "निर्दलीय", ""}, 
{"Telangana",  "6002", "Mahabubabad", "Balsingh Daravath", "Bhartiya Anarakshit Party", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6880",  "तेलंगाना",  "महबुबाबाद", "बलसिंह दरवथ", "भारतीय अनारक्षित पार्टी", ""}, 
{"Telangana",  "6004", "Mahabubabad", "Bhaskar Naik Bhukya.", "Janasena Party", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6883",  "तेलंगाना",  "महबुबाबाद", "भास्कर नाइक भुक्ा।", "जनसेना पार्टी", ""}, 
{"Telangana",  "6005", "Mahabubabad", "Vaditya Shriram Naik", "Independent", "48.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6890",  "तेलंगाना",  "महबुबाबाद", "वदित्य श्रीराम नाइक", "निर्दलीय", ""}, 
{"Telangana",  "6007", "Mahabubabad", "Palvancha. Durga.", "Independent", "11.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6888",  "तेलंगाना",  "महबुबाबाद", "Palvancha। दुर्गा।", "निर्दलीय", ""}, 
{"Telangana",  "6012", "Mahabubabad", "Balu Nayak Bhukya", "Independent", "27.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6881",  "तेलंगाना",  "महबुबाबाद", "बलु नायक भुक्", "निर्दलीय", ""}, 
{"Telangana",  "5924", "Mahbubnagar", "Vishweshwar J", "Independent", "47.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6835",  "तेलंगाना",  "महबूबनगर", "विश्वेश्वर जे", "निर्दलीय", ""}, 
{"Telangana",  "5929", "Mahbubnagar", "Md. Abdul Azeez Khan", "Independent", "56.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4668",  "तेलंगाना",  "महबूबनगर", "मो। अब्दुल अज़ीज़ खान", "निर्दलीय", ""}, 
{"Telangana",  "5932", "Mahbubnagar", "Pola Prashanth Kumar", "Independent", "1.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4606",  "तेलंगाना",  "महबूबनगर", "पोला प्रशांत कुमार", "निर्दलीय", ""}, 
{"Telangana",  "5933", "Mahbubnagar", "Mohammed Imtiyaz Ahmad", "Independent", "66.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4607",  "तेलंगाना",  "महबूबनगर", "मोहम्मद इम्तियाज अहमद", "निर्दलीय", ""}, 
{"Telangana",  "5844", "Malkajgiri", "Donthula Bikshapathi", "Independent", "1.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6777",  "तेलंगाना",  "मल्काजगिरि", "दुन्दुला बिकासपति", "निर्दलीय", ""}, 
{"Telangana",  "5846", "Malkajgiri", "Rajender Ponnala", "Independent", "10.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7242",  "तेलंगाना",  "मल्काजगिरि", "राजेन्द्र पोन्नाला", "निर्दलीय", ""}, 
{"Telangana",  "5847", "Malkajgiri", "Balamani Buru", "India Praja Bandhu Party", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6774",  "तेलंगाना",  "मल्काजगिरि", "बालमणि बुरु", "भारत प्रजा बंधु पार्टी", ""}, 
{"Telangana",  "5850", "Malkajgiri", "Sai Kiran Gone", "Independent", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6779",  "तेलंगाना",  "मल्काजगिरि", "साईं किरण गया", "निर्दलीय", ""}, 
{"Telangana",  "5855", "Malkajgiri", "Chalika Chandra Sekhar", "Independent", "42.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4664",  "तेलंगाना",  "मल्काजगिरि", "चालिका चन्द्रशेखर", "निर्दलीय", ""}, 
{"Telangana",  "5835", "Medak", "Kallu Narsimlu Goud", "Independent", "27.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6768",  "तेलंगाना",  "मेडक", "कल्लू नरसिम्लु गौड", "निर्दलीय", ""}, 
{"Telangana",  "5839", "Medak", "Bharatesh", "Socialist Unity Centre of India (Communist)", "42300", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6765",  "तेलंगाना",  "मेडक", "Bharatesh", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Telangana",  "5840", "Medak", "Kotha Prabhakar Reddy", "Telangana Rashtra Samithi", "126.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5079",  "तेलंगाना",  "मेडक", "कोठा प्रभाकर रेड्डी", "तेलंगाना राष्ट्र समिति", ""}, 
{"Telangana",  "5940", "Nagarkurnool", "Gaddam Vijay Kumar", "Bahujan Mukti Party", "18Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5787",  "तेलंगाना",  "नगरकुरनूल", "गद्दाम विजय कुमार", "बहुजन मुक्ति पार्टी", ""}, 
{"Telangana",  "5945", "Nalgonda", "Jakkula Naveen Yadav", "Independent", "10Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6847",  "तेलंगाना",  "नलगोंडा", "जक्कूला नवीन यादव", "निर्दलीय", ""}, 
{"Telangana",  "5947", "Nalgonda", "Mekala Satheesh Reddy", "Janasena Party", "34.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6841",  "तेलंगाना",  "नलगोंडा", "मेकाला सतीश रेड्डी", "जनसेना पार्टी", ""}, 
{"Telangana",  "5948", "Nalgonda", "Royyala Srinivasulu", "Independent", "86.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6857",  "तेलंगाना",  "नलगोंडा", "रोयला श्रीनिवासुलु", "निर्दलीय", ""}, 
{"Telangana",  "5949", "Nalgonda", "Lingidi Venkateswarlu", "Independent", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6858",  "तेलंगाना",  "नलगोंडा", "लिंगीदी वेंकटेश्वरलु", "निर्दलीय", ""}, 
{"Telangana",  "5951", "Nalgonda", "Vemireddy Narasimha Reddy", "Telangana Rashtra Samithi", "94.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6838",  "तेलंगाना",  "नलगोंडा", "वेमिरेड्डी नरसिम्हा रेड्डी", "तेलंगाना राष्ट्र समिति", ""}, 
{"Telangana",  "5953", "Nalgonda", "Ramesh Sunkara", "Independent", "15.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6856",  "तेलंगाना",  "नलगोंडा", "रमेश सुनकारा", "निर्दलीय", ""}, 
{"Telangana",  "5955", "Nalgonda", "Katravath Venkatesh", "Bahujan Mukti Party", "21300", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6839",  "तेलंगाना",  "नलगोंडा", "कत्रवथ वेंकटेश", "बहुजन मुक्ति पार्टी", ""}, 
{"Telangana",  "5958", "Nalgonda", "Lithesh Sunkari", "Social Justice Party of India", "48.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6843",  "तेलंगाना",  "नलगोंडा", "लीठेश सुनकारी", "सोशल जस्टिस पार्टी ऑफ इंडिया", ""}, 
{"Telangana",  "5963", "Nalgonda", "Thagulla Janardhan", "Independent", "2.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6848",  "तेलंगाना",  "नलगोंडा", "ठगुल्ला जनार्दन", "निर्दलीय", ""}, 
{"Telangana",  "5964", "Nalgonda", "Bandaru Nagaraju", "Independent", "2.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6852",  "तेलंगाना",  "नलगोंडा", "बंडारू नागराजू", "निर्दलीय", ""}, 
{"Telangana",  "5968", "Nalgonda", "Sreenu Vadthya", "Independent", "19.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4864",  "तेलंगाना",  "नलगोंडा", "श्रीनु वधथया", "निर्दलीय", ""}, 
{"Telangana",  "5970", "Nalgonda", "Janaiah Nandipati", "Telangana Sakalajanula Party", "16Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6840",  "तेलंगाना",  "नलगोंडा", "जनाया नंदीपति", "तेलंगाना सकलजानुला पार्टी", ""}, 
{"Telangana",  "5645", "Nizamabad", "Yellala Rajitha", "Independent", "19.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6750",  "तेलंगाना",  "निजामाबाद", "येलाला रजिथा", "निर्दलीय", ""}, 
{"Telangana",  "5646", "Nizamabad", "Raj Kumar Sunkari", "Independent", "8.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6700",  "तेलंगाना",  "निजामाबाद", "राज कुमार सुनकारी", "निर्दलीय", ""}, 
{"Telangana",  "5661", "Nizamabad", "Katipelli Ramesh", "Independent", "5.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6638",  "तेलंगाना",  "निजामाबाद", "कटिपेली रमेश", "निर्दलीय", ""}, 
{"Telangana",  "5674", "Nizamabad", "Ganga Reddy Kallem", "Independent", "21.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6618",  "तेलंगाना",  "निजामाबाद", "गंगा रेड्डी कालिम", "निर्दलीय", ""}, 
{"Telangana",  "5678", "Nizamabad", "Kanaka Pramod", "Independent", "3.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6634",  "तेलंगाना",  "निजामाबाद", "कनक प्रमोद", "निर्दलीय", ""}, 
{"Telangana",  "5684", "Nizamabad", "S. Sagar", "Bahujan Mukti Party", "75000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6714",  "तेलंगाना",  "निजामाबाद", "एस सागर", "बहुजन मुक्ति पार्टी", ""}, 
{"Telangana",  "5693", "Nizamabad", "Madhu Butti", "Independent", "4.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6655",  "तेलंगाना",  "निजामाबाद", "मधु बुट्टी", "निर्दलीय", ""}, 
{"Telangana",  "5694", "Nizamabad", "Shankar Yenugu", "Independent", "12.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6723",  "तेलंगाना",  "निजामाबाद", "शंकर येनगु", "निर्दलीय", ""}, 
{"Telangana",  "5701", "Nizamabad", "Talari Suman", "Independent", "3.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6736",  "तेलंगाना",  "निजामाबाद", "तलारी सुमन", "निर्दलीय", ""}, 
{"Telangana",  "5707", "Nizamabad", "Ayileni Vikram Reddy", "Independent", "65000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6322",  "तेलंगाना",  "निजामाबाद", "अइलेंनी विक्रम रेड्डी", "निर्दलीय", ""}, 
{"Telangana",  "5719", "Nizamabad", "Limbaiah Somidi", "Independent", "2.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6649",  "तेलंगाना",  "निजामाबाद", "लिंबैया सोमदीदी", "निर्दलीय", ""}, 
{"Telangana",  "5720", "Nizamabad", "N. Omkar Reddy", "Independent", "18.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6683",  "तेलंगाना",  "निजामाबाद", "एन। ओंकार रेड्डी", "निर्दलीय", ""}, 
{"Telangana",  "5721", "Nizamabad", "Mamidi Rajashekar Reddy", "Independent", "18.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6664",  "तेलंगाना",  "निजामाबाद", "ममदी राजशेखर रेड्डी", "निर्दलीय", ""}, 
{"Telangana",  "5723", "Nizamabad", "Thota Srinivas", "Independent", "24.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6742",  "तेलंगाना",  "निजामाबाद", "थोटा श्रीनिवास", "निर्दलीय", ""}, 
{"Telangana",  "5726", "Nizamabad", "Gaddam Mohan", "Independent", "10500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6607",  "तेलंगाना",  "निजामाबाद", "गद्दाम मोहन", "निर्दलीय", ""}, 
{"Telangana",  "5739", "Nizamabad", "Mohan Chintala Palli", "Independent", "9.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6674",  "तेलंगाना",  "निजामाबाद", "मोहन चिंतला पल्ली", "निर्दलीय", ""}, 
{"Telangana",  "5740", "Nizamabad", "Gaddam Purushotham", "Independent", "8.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6608",  "तेलंगाना",  "निजामाबाद", "गद्दाम पुरुषोत्तम", "निर्दलीय", ""}, 
{"Telangana",  "5744", "Nizamabad", "Suresh Basa", "Independent", "10.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6733",  "तेलंगाना",  "निजामाबाद", "सुरेश बासा", "निर्दलीय", ""}, 
{"Telangana",  "5752", "Nizamabad", "Sanjeeva Reddy Gaddam", "Independent", "55.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6718",  "तेलंगाना",  "निजामाबाद", "संजीव रेड्डी गद्दाम", "निर्दलीय", ""}, 
{"Telangana",  "5756", "Nizamabad", "Raju Somireddy", "Independent", "4.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6707",  "तेलंगाना",  "निजामाबाद", "राजू सोमरेड्डी", "निर्दलीय", ""}, 
{"Telangana",  "5758", "Nizamabad", "Baddam Srinivasa Reddy", "Independent", "20.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6328",  "तेलंगाना",  "निजामाबाद", "बादाम श्रीनिवास रेड्डी", "निर्दलीय", ""}, 
{"Telangana",  "5759", "Nizamabad", "Sama Thirupathi", "Independent", "11.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4654",  "तेलंगाना",  "निजामाबाद", "साम थिरुपथी", "निर्दलीय", ""}, 
{"Telangana",  "5765", "Nizamabad", "Praveen Neeradi", "Independent", "1.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6698",  "तेलंगाना",  "निजामाबाद", "प्रवीण नीरड़ी", "निर्दलीय", ""}, 
{"Telangana",  "5786", "Nizamabad", "Mohd Jameel", "Independent", "10.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6676",  "तेलंगाना",  "निजामाबाद", "मोहम्मद जमील", "निर्दलीय", ""}, 
{"Telangana",  "5795", "Nizamabad", "Sunketa Ravi", "Independent", "93.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6730",  "तेलंगाना",  "निजामाबाद", "सुनकेत रवि", "निर्दलीय", ""}, 
{"Telangana",  "5817", "Nizamabad", "Nomula Gopal Reddy", "Independent", "40000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4655",  "तेलंगाना",  "निजामाबाद", "नोमुला गोपाल रेड्डी", "निर्दलीय", ""}, 
{"Telangana",  "5293", "Peddapalle", "Bala Kalyan Panja", "Bahujan Samaj Party", "7.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6216",  "तेलंगाना",  "पेडेपल्लै", "बाला कल्याण पांजा", "बहुजन समाज पार्टी", ""}, 
{"Telangana",  "5295", "Peddapalle", "Erugurala Bhagya Laxmi", "Pyramid Party of India", "2000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4631",  "तेलंगाना",  "पेडेपल्लै", "एरुगुरला भाग्य लक्ष्मी", "पिरामिड पार्टी ऑफ इंडिया", ""}, 
{"Telangana",  "5296", "Peddapalle", "Rajesh Erikilla", "Independent", "4.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7239",  "तेलंगाना",  "पेडेपल्लै", "राजेश एरिकिला", "निर्दलीय", ""}, 
{"Telangana",  "5297", "Peddapalle", "Venkatesh Netha Borlakunta", "Telangana Rashtra Samithi", "1.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5071",  "तेलंगाना",  "पेडेपल्लै", "वेंकटेश नेथा बोरलाकुंटा", "तेलंगाना राष्ट्र समिति", ""}, 
{"Telangana",  "5298", "Peddapalle", "Durgam. Rajanna", "Independent", "15500", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4649",  "तेलंगाना",  "पेडेपल्लै", "Durgam। Rajanna", "निर्दलीय", ""}, 
{"Telangana",  "5302", "Peddapalle", "Thadem Raj Prakash", "India Praja Bandhu Party", "2.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4591",  "तेलंगाना",  "पेडेपल्लै", "ठाडेम राज प्रकाश", "भारत प्रजा बंधु पार्टी", ""}, 
{"Telangana",  "5862", "Secunderabad", "Boddu Satish", "Independent", "33000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6797",  "तेलंगाना",  "सिकंदराबाद", "बोधु सतीश", "निर्दलीय", ""}, 
{"Telangana",  "5864", "Secunderabad", "Nandipati Vinod Kumar", "Independent", "30000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6799",  "तेलंगाना",  "सिकंदराबाद", "नंदीपति विनोद कुमार", "निर्दलीय", ""}, 
{"Telangana",  "5866", "Secunderabad", "Mallesh Jatavath", "Socialist Unity Centre of India (Communist)", "0", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5085",  "तेलंगाना",  "सिकंदराबाद", "मल्लेश जाटवथ", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)", ""}, 
{"Telangana",  "5869", "Secunderabad", "Meesala Gopal Sai Baba", "Independent", "97.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4840",  "तेलंगाना",  "सिकंदराबाद", "मीसाला गोपाल साईं बाबा", "निर्दलीय", ""}, 
{"Telangana",  "5873", "Secunderabad", "Andukuri Vijaya Bhaskar", "India Praja Bandhu Party", "5000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6790",  "तेलंगाना",  "सिकंदराबाद", "अंदुकुरी विजया भास्कर", "भारत प्रजा बंधु पार्टी", ""}, 
{"Telangana",  "5874", "Secunderabad", "Ravi Kumar Vodela", "Independent", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6784",  "तेलंगाना",  "सिकंदराबाद", "रवि कुमार वोडेला", "निर्दलीय", ""}, 
{"Telangana",  "5876", "Secunderabad", "J . N . Rao", "Dalita Bahujana Party", "15.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6798",  "तेलंगाना",  "सिकंदराबाद", "जे। एन। राव", "दलिता बहुजन पार्टी", ""}, 
{"Telangana",  "5877", "Secunderabad", "Challa Ram Kalyan", "Bhartiya Anarakshit Party", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6789",  "तेलंगाना",  "सिकंदराबाद", "चल्ला राम कल्याण", "भारतीय अनारक्षित पार्टी", ""}, 
{"Telangana",  "5880", "Secunderabad", "Akhil Chirravuri", "Independent", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6791",  "तेलंगाना",  "सिकंदराबाद", "अखिल चिरवरी", "निर्दलीय", ""}, 
{"Telangana",  "5881", "Secunderabad", "M . Ashok Kumar", "Samajwadi Forward Bloc", "3.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6788",  "तेलंगाना",  "सिकंदराबाद", "एम। अशोक कुमार", "समाजवादी फॉरवर्ड ब्लॉक", ""}, 
{"Telangana",  "5882", "Secunderabad", "Andrapu Sudharshan Gangaputra", "Independent", "60000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6795",  "तेलंगाना",  "सिकंदराबाद", "आद्रापु सुधर्शन गंगापुत्र", "निर्दलीय", ""}, 
{"Telangana",  "5987", "Warangal", "Dayakar Pasnori", "Telangana Rashtra Samithi", "2.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5094",  "तेलंगाना",  "वारंगल", "दयाकर पासनोरी", "तेलंगाना राष्ट्र समिति", ""}, 
{"Telangana",  "5988", "Warangal", "Upendar Jeripothula", "Independent", "6.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5778",  "तेलंगाना",  "वारंगल", "उपेंडर जेरिपोथुला", "निर्दलीय", ""}, 
{"Telangana",  "5990", "Warangal", "Bollapally Saraiah", "Bahujan Samaj Party", "96.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6870",  "तेलंगाना",  "वारंगल", "बोलपल्ली साराया", "बहुजन समाज पार्टी", ""}, 
{"Telangana",  "5991", "Warangal", "Barla Srinivas", "Independent", "15000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5783",  "तेलंगाना",  "वारंगल", "बराला श्रीनिवास", "निर्दलीय", ""}, 
{"Telangana",  "5998", "Warangal", "Bochu Krupakar", "Hum Bhartiya Party", "11.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6873",  "तेलंगाना",  "वारंगल", "बोचु क्रुपाकर", "हम भारतीय पार्टी", ""}, 
{"Telangana",  "5823", "Zahirabad", "Ramarao Patil", "Independent", "2.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6757",  "तेलंगाना",  "जहीराबाद", "रामाराव पाटिल", "निर्दलीय", ""}, 
{"Telangana",  "5825", "Zahirabad", "Alige Jeevan", "Bahujan Mukti Party", "51000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6759",  "तेलंगाना",  "जहीराबाद", "आजीवन जीवन", "बहुजन मुक्ति पार्टी", ""}, 
{"Telangana",  "5829", "Zahirabad", "Nangunoori Lata", "Independent", "2.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6755",  "तेलंगाना",  "जहीराबाद", "नंगुनूरी लता", "निर्दलीय", ""}, 
{"Telangana",  "5830", "Zahirabad", "Benjamin Raju", "Independent", "75.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6752",  "तेलंगाना",  "जहीराबाद", "बेंजामिन राजू", "निर्दलीय", ""}, 
{"Telangana",  "5833", "Zahirabad", "Kalesh", "Bhartiya Anarakshit Party", "10.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7243",  "तेलंगाना",  "जहीराबाद", "Kalesh", "भारतीय अनारक्षित पार्टी", ""}, 
};

public static final String[][] red_bucket = {
{ "Telangana",  "5282",  "Adilabad", "Aare Ellanna", "NotGraduate",  " ","तेलंगाना",  "आदिलाबाद", "आरे इल्न्ना", " "}, 
{ "Telangana",  "5283",  "Adilabad", "Kumra Raju", "NotGraduate",  " ","तेलंगाना",  "आदिलाबाद", "कुमरा राजू", " "}, 
{ "Telangana",  "5284",  "Adilabad", "Nethavath Ramdas", "NotGraduate",  " ","तेलंगाना",  "आदिलाबाद", "नेत्रनाथ रामदास", " "}, 
{ "Telangana",  "5285",  "Adilabad", "Ramesh Rathod", "ForeignFunding",  " ","तेलंगाना",  "आदिलाबाद", "रमेश राठौड़", " "}, 
{ "Telangana",  "5288",  "Adilabad", "Bapu Rao Soyam", "ForeignFunding",  " ","तेलंगाना",  "आदिलाबाद", "बापू राव सोयम", " "}, 
{ "Telangana",  "5289",  "Adilabad", "Bheem Rao", "NotGraduate",  " ","तेलंगाना",  "आदिलाबाद", "भीम राव", " "}, 
{ "Telangana",  "5290",  "Adilabad", "Kumram Vandana", "NotGraduate",  " ","तेलंगाना",  "आदिलाबाद", "कुमारम वंदना", " "}, 
{ "Telangana",  "5973",  "Bhongir", "Sirivolu Venkata Ramana Rao", "NotGraduate",  " ","तेलंगाना",  "भोंगीर", "सिरिवोलु वेंकट रमना राव", " "}, 
{ "Telangana",  "5974",  "Bhongir", "Komatireddy Venakat Reddy", "ForeignFunding",  " ","तेलंगाना",  "भोंगीर", "कोमाटेड्डी वेंकट रेड्डी", " "}, 
{ "Telangana",  "5975",  "Bhongir", "Goda Sriramulu", "NotGraduate",  " ","तेलंगाना",  "भोंगीर", "गोदा श्रीरामुलु", " "}, 
{ "Telangana",  "5976",  "Bhongir", "Kotha Kistaiah", "NotGraduate",  " ","तेलंगाना",  "भोंगीर", "कोठा किस्तेया", " "}, 
{ "Telangana",  "5978",  "Bhongir", "Padala Venkata Shyam Sunder Rao", "ForeignFunding",  " ","तेलंगाना",  "भोंगीर", "पडाला वेंकट श्याम सुन्दर राव", " "}, 
{ "Telangana",  "5980",  "Bhongir", "Sriramulu Muthyala", "NotGraduate",  " ","तेलंगाना",  "भोंगीर", "श्रीरामुलु मुथयला", " "}, 
{ "Telangana",  "5982",  "Bhongir", "Bheemanaboina Ramesh", "NotGraduate",  " ","तेलंगाना",  "भोंगीर", "भीमनबॉइन रमेश", " "}, 
{ "Telangana",  "5983",  "Bhongir", "Singapaka Lingam", "NotGraduate",  " ","तेलंगाना",  "भोंगीर", "सिंगापक लिंगम", " "}, 
{ "Telangana",  "5901",  "Chevella", "Nalla Prem Kumar", "NotGraduate",  " ","तेलंगाना",  "चेवेल्ला", "नाला प्रेम कुमार", " "}, 
{ "Telangana",  "5902",  "Chevella", "Yedla Suresh", "NotGraduate",  " ","तेलंगाना",  "चेवेल्ला", "येदला सुरेश", " "}, 
{ "Telangana",  "5903",  "Chevella", "Bennala Julee", "NotGraduate",  " ","तेलंगाना",  "चेवेल्ला", "बेनाला जुले", " "}, 
{ "Telangana",  "5905",  "Chevella", "Palamakula Madhu", "NotGraduate",  " ","तेलंगाना",  "चेवेल्ला", "पालमकुला मधु", " "}, 
{ "Telangana",  "5907",  "Chevella", "Baswaiah Madiga", "NotGraduate",  " ","तेलंगाना",  "चेवेल्ला", "बसवाइया मडिगा", " "}, 
{ "Telangana",  "5909",  "Chevella", "Vijay Aarya", "NotGraduate",  " ","तेलंगाना",  "चेवेल्ला", "विजय आर्या", " "}, 
{ "Telangana",  "5911",  "Chevella", "A.A. Sabri", "OverAged",  " ","तेलंगाना",  "चेवेल्ला", "एए साबरी", " "}, 
{ "Telangana",  "5912",  "Chevella", "Gurram Papi Reddy", "NotGraduate",  " ","तेलंगाना",  "चेवेल्ला", "गुर्रम पापी रेड्डी", " "}, 
{ "Telangana",  "5913",  "Chevella", "B. Janardhan Reddy", "ForeignFunding",  " ","तेलंगाना",  "चेवेल्ला", "बी। जनार्दन रेड्डी", " "}, 
{ "Telangana",  "5915",  "Chevella", "Kummari Giri", "NotGraduate",  " ","तेलंगाना",  "चेवेल्ला", "कुमारी गिरि", " "}, 
{ "Telangana",  "5916",  "Chevella", "Konda Vishweshwar Reddy", "ForeignFunding",  " ","तेलंगाना",  "चेवेल्ला", "कोंडा विश्वेश्वर रेड्डी", " "}, 
{ "Telangana",  "5917",  "Chevella", "Korra Pandu Naik", "NotGraduate",  " ","तेलंगाना",  "चेवेल्ला", "कोरा पांडु नाइक", " "}, 
{ "Telangana",  "5918",  "Chevella", "Chepuri Raju", "NotGraduate",  " ","तेलंगाना",  "चेवेल्ला", "चेपुरी राजू", " "}, 
{ "Telangana",  "5919",  "Chevella", "Jaidupally Yadaiah", "NotGraduate",  " ","तेलंगाना",  "चेवेल्ला", "जयदुपल्ली यदैया", " "}, 
{ "Telangana",  "5920",  "Chevella", "Vanam Sudhakar", "NotGraduate",  " ","तेलंगाना",  "चेवेल्ला", "वनम सुधाकर", " "}, 
{ "Telangana",  "5888",  "Hyderabad", "Mohammed Abdul Azeem", "NotGraduate",  " ","तेलंगाना",  "हैदराबाद", "मोहम्मद अब्दुल अज़ीम", " "}, 
{ "Telangana",  "5889",  "Hyderabad", "Bhagavanth Rao Pawar", "ForeignFunding",  " ","तेलंगाना",  "हैदराबाद", "भगवंत राव पवार", " "}, 
{ "Telangana",  "5890",  "Hyderabad", "Dornala Jaya Prakash", "CriminalCases",  " ","तेलंगाना",  "हैदराबाद", "दोरनाला जय प्रकाश", " "}, 
{ "Telangana",  "5892",  "Hyderabad", "L Ashok Nath", "NotGraduate",  " ","तेलंगाना",  "हैदराबाद", "एल अशोक नाथ", " "}, 
{ "Telangana",  "5893",  "Hyderabad", "Sanjay Kumar Shukla", "NotGraduate",  " ","तेलंगाना",  "हैदराबाद", "संजय कुमार शुक्ला", " "}, 
{ "Telangana",  "5894",  "Hyderabad", "K Rangacharya", "NotGraduate",  " ","तेलंगाना",  "हैदराबाद", "के रंगाचार्य", " "}, 
{ "Telangana",  "5895",  "Hyderabad", "Mohd Ahmed", "NotGraduate",  " ","तेलंगाना",  "हैदराबाद", "मोहम्मद अहमद", " "}, 
{ "Telangana",  "5896",  "Hyderabad", "Asaduddin Owaisi", "CriminalCases",  " ","तेलंगाना",  "हैदराबाद", "असदुद्दीन ओवैसी", " "}, 
{ "Telangana",  "5897",  "Hyderabad", "K. Nagaraj", "NotGraduate",  " ","तेलंगाना",  "हैदराबाद", "के। नागराज", " "}, 
{ "Telangana",  "5898",  "Hyderabad", "Mohammed Feroz Khan", "ForeignFunding",  " ","तेलंगाना",  "हैदराबाद", "मोहम्मद फ़िरोज़ खान", " "}, 
{ "Telangana",  "5884",  "Hyderabad", "Dr.Hingolikar Susheel Raj", "NotGraduate",  " ","तेलंगाना",  "हैदराबाद", "डॉ। हिंगोलिकर सुशील राज", " "}, 
{ "Telangana",  "5886",  "Hyderabad", "Beeramganti Venkat Ramesh Naidu", "NotGraduate",  " ","तेलंगाना",  "हैदराबाद", "बीरमुगंति वेंकट रमेश नायडू", " "}, 
{ "Telangana",  "5887",  "Hyderabad", "Ka Maheshwar", "CriminalCases",  " ","तेलंगाना",  "हैदराबाद", "का महेश्वर", " "}, 
{ "Telangana",  "5310",  "Karimnagar", "Ponnam Prabhakar", "ForeignFunding",  " ","तेलंगाना",  "करीमनगर", "पोन्नम प्रभाकर", " "}, 
{ "Telangana",  "5311",  "Karimnagar", "Bhanu Laxman Pabba", "NotGraduate",  " ","तेलंगाना",  "करीमनगर", "भानु लक्ष्मण पबबा", " "}, 
{ "Telangana",  "5312",  "Karimnagar", "Aila Prasanna", "NotGraduate",  " ","तेलंगाना",  "करीमनगर", "आइला प्रसन्ना", " "}, 
{ "Telangana",  "5313",  "Karimnagar", "Durvasa Reddy Pakala", "CriminalCases",  " ","तेलंगाना",  "करीमनगर", "दुर्वासा रेड्डी पकाला", " "}, 
{ "Telangana",  "5315",  "Karimnagar", "Kota Shyamkumar", "NotGraduate",  " ","तेलंगाना",  "करीमनगर", "कोटा श्यामकुमार", " "}, 
{ "Telangana",  "5316",  "Karimnagar", "Anagandula Venkanna", "CriminalCases",  " ","तेलंगाना",  "करीमनगर", "अनगनदुला वेंकन्ना", " "}, 
{ "Telangana",  "5317",  "Karimnagar", "Mukkisa Ratnakar Reddy", "NotGraduate",  " ","तेलंगाना",  "करीमनगर", "मुकीसा रत्नाकर रेड्डी", " "}, 
{ "Telangana",  "5319",  "Karimnagar", "Srikanth Chiliveru", "CriminalCases",  " ","तेलंगाना",  "करीमनगर", "श्रीकांत चिलिवरु", " "}, 
{ "Telangana",  "5321",  "Karimnagar", "Gangarapu Thirupathi", "NotGraduate",  " ","तेलंगाना",  "करीमनगर", "गंगारापु थिरुपथी", " "}, 
{ "Telangana",  "5322",  "Karimnagar", "Bandi Sanjay Kumar", "ForeignFunding",  " ","तेलंगाना",  "करीमनगर", "बंदी संजय कुमार", " "}, 
{ "Telangana",  "6013",  "Khammam", "Avutapalli Rambabu", "NotGraduate",  " ","तेलंगाना",  "खम्मम", "अवुतपल्ली रामबाबू", " "}, 
{ "Telangana",  "6015",  "Khammam", "Gugulothu Ramesh", "CriminalCases",  " ","तेलंगाना",  "खम्मम", "गुगुलोथु रमेश", " "}, 
{ "Telangana",  "6016",  "Khammam", "Koppula Sreenivasa Rao", "NotGraduate",  " ","तेलंगाना",  "खम्मम", "कोप्पुला श्रीनिवास राव", " "}, 
{ "Telangana",  "6018",  "Khammam", "Venkateshwar Rao Pullakandam", "NotGraduate",  " ","तेलंगाना",  "खम्मम", "वेंकटेश्वर राव पुल्लाकंदम", " "}, 
{ "Telangana",  "6019",  "Khammam", "Gokinapalli Venkateswarlu", "NotGraduate",  " ","तेलंगाना",  "खम्मम", "गोकिनापल्ली वेंकटेश्वरलु", " "}, 
{ "Telangana",  "6022",  "Khammam", "Katta Srinivas", "NotGraduate",  " ","तेलंगाना",  "खम्मम", "कट्टा श्रीनिवास", " "}, 
{ "Telangana",  "6024",  "Khammam", "Parsagani Nageswara Rao", "CriminalCases",  " ","तेलंगाना",  "खम्मम", "परसागनी नागेश्वर राव", " "}, 
{ "Telangana",  "6026",  "Khammam", "Anil Kumar Maddineni", "CriminalCases",  " ","तेलंगाना",  "खम्मम", "अनिल कुमार मद्दीनैनी", " "}, 
{ "Telangana",  "6027",  "Khammam", "Nakirikanti Sanjeeva Rao", "NotGraduate",  " ","तेलंगाना",  "खम्मम", "नकीरकांति संजीव राव", " "}, 
{ "Telangana",  "6029",  "Khammam", "Gopoju Ramesh Babu", "NotGraduate",  " ","तेलंगाना",  "खम्मम", "गोपोजु रमेश बाबू", " "}, 
{ "Telangana",  "6030",  "Khammam", "Renuka Chowdhury", "ForeignFunding",  " ","तेलंगाना",  "खम्मम", "रेणुका चौधरी", " "}, 
{ "Telangana",  "6031",  "Khammam", "Devaki Vasudeva Rao", "ForeignFunding",  " ","तेलंगाना",  "खम्मम", "देवकी वासुदेव राव", " "}, 
{ "Telangana",  "6032",  "Khammam", "Laxmana Chary Bhanala", "NotGraduate",  " ","तेलंगाना",  "खम्मम", "लक्ष्मण चरी भनाला", " "}, 
{ "Telangana",  "6033",  "Khammam", "Banoth Laxma Naik", "NotGraduate",  " ","तेलंगाना",  "खम्मम", "बनथ लक्ष्मण नाइक", " "}, 
{ "Telangana",  "6034",  "Khammam", "Nama Nageswr Rao", "CriminalCases",  " ","तेलंगाना",  "खम्मम", "नामा नागसेवक राव", " "}, 
{ "Telangana",  "6035",  "Khammam", "Palvancha Rama Rao", "CriminalCases",  " ","तेलंगाना",  "खम्मम", "पलवंच रामा राव", " "}, 
{ "Telangana",  "5999",  "Mahabubabad", "Uke Kousalya", "NotGraduate",  " ","तेलंगाना",  "महबुबाबाद", "उके कुसलया", " "}, 
{ "Telangana",  "6000",  "Mahabubabad", "Jatothu Hussain", "ForeignFunding",  " ","तेलंगाना",  "महबुबाबाद", "जटोथु हुसैन", " "}, 
{ "Telangana",  "6001",  "Mahabubabad", "Kalluri. Venkateswara Rao", "NotGraduate",  " ","तेलंगाना",  "महबुबाबाद", "कल्लूरी। वेंकटेश्वर राव", " "}, 
{ "Telangana",  "6003",  "Mahabubabad", "Parvathi Bhukya", "NotGraduate",  " ","तेलंगाना",  "महबुबाबाद", "पार्वती भुक्ा", " "}, 
{ "Telangana",  "6006",  "Mahabubabad", "Kalthi Yarraiah", "CriminalCases",  " ","तेलंगाना",  "महबुबाबाद", "कलथी यारैया", " "}, 
{ "Telangana",  "6008",  "Mahabubabad", "Arun Kumar Mypathi", "CriminalCases",  " ","तेलंगाना",  "महबुबाबाद", "अरुण कुमार मिपाठी", " "}, 
{ "Telangana",  "6009",  "Mahabubabad", "Mokalla. Murali Krishna", "CriminalCases",  " ","तेलंगाना",  "महबुबाबाद", "Mokalla। मुरली कृष्ण", " "}, 
{ "Telangana",  "6010",  "Mahabubabad", "Kavitha Malothu", "CriminalCases",  " ","तेलंगाना",  "महबुबाबाद", "कविता मलोथू", " "}, 
{ "Telangana",  "6011",  "Mahabubabad", "Balaram Naik Porika", "ForeignFunding",  " ","तेलंगाना",  "महबुबाबाद", "बलराम नाइक पोरिका", " "}, 
{ "Telangana",  "5922",  "Mahbubnagar", "Manne Srinivas Reddy", "NotGraduate",  " ","तेलंगाना",  "महबूबनगर", "मन्ने श्रीनिवास रेड्डी", " "}, 
{ "Telangana",  "5923",  "Mahbubnagar", "Challa Vamshi Chand Reddy", "ForeignFunding",  " ","तेलंगाना",  "महबूबनगर", "चल्ला वामशी चंद रेड्डी", " "}, 
{ "Telangana",  "5925",  "Mahbubnagar", "S Gopal Reddy", "NotGraduate",  " ","तेलंगाना",  "महबूबनगर", "एस गोपाल रेड्डी", " "}, 
{ "Telangana",  "5926",  "Mahbubnagar", "V Dasram", "CriminalCases",  " ","तेलंगाना",  "महबूबनगर", "वी दशराम", " "}, 
{ "Telangana",  "5927",  "Mahbubnagar", "Ergamreddy Shivadurgavaraprasad Reddy", "NotGraduate",  " ","तेलंगाना",  "महबूबनगर", "एर्माग्रेड्डी शिवदुर्गावराप्रसाद रेड्डी", " "}, 
{ "Telangana",  "5928",  "Mahbubnagar", "Imran Ahmed Khan", "NotGraduate",  " ","तेलंगाना",  "महबूबनगर", "इमरान अहमद खान", " "}, 
{ "Telangana",  "5930",  "Mahbubnagar", "D. K. Aruna", "ForeignFunding",  " ","तेलंगाना",  "महबूबनगर", "डीके अरुणा", " "}, 
{ "Telangana",  "5931",  "Mahbubnagar", "D Thimmappa", "NotGraduate",  " ","तेलंगाना",  "महबूबनगर", "डी थिमप्पा", " "}, 
{ "Telangana",  "5845",  "Malkajgiri", "Ramchander Rao N", "ForeignFunding",  " ","तेलंगाना",  "मल्काजगिरि", "रामचंदर राव एन", " "}, 
{ "Telangana",  "5848",  "Malkajgiri", "Mahender Reddy Bongunoori", "NotGraduate",  " ","तेलंगाना",  "मल्काजगिरि", "महेंदर रेड्डी बोंगुनूरी", " "}, 
{ "Telangana",  "5849",  "Malkajgiri", "Dharmasanam Bhanumurthy", "CriminalCases",  " ","तेलंगाना",  "मल्काजगिरि", "धर्मसनं भानुमूर्ति", " "}, 
{ "Telangana",  "5851",  "Malkajgiri", "Rajashekar Reddy Marri", "NotGraduate",  " ","तेलंगाना",  "मल्काजगिरि", "राजशेखर रेड्डी विवाह", " "}, 
{ "Telangana",  "5852",  "Malkajgiri", "Chamakura Rajaiah", "CriminalCases",  " ","तेलंगाना",  "मल्काजगिरि", "चमकुरा राजािया", " "}, 
{ "Telangana",  "5853",  "Malkajgiri", "Anumula Revanth Reddy", "ForeignFunding",  " ","तेलंगाना",  "मल्काजगिरि", "अनमुला रेवंत रेड्डी", " "}, 
{ "Telangana",  "5854",  "Malkajgiri", "Thirupataiah Enduram", "NotGraduate",  " ","तेलंगाना",  "मल्काजगिरि", "थिरुपतैया एंडुराम", " "}, 
{ "Telangana",  "5834",  "Medak", "Gajabinkar Bansilal", "NotGraduate",  " ","तेलंगाना",  "मेडक", "गजबिन्कर बंसीलाल", " "}, 
{ "Telangana",  "5836",  "Medak", "Madavaneni Raghunandan Rao", "ForeignFunding",  " ","तेलंगाना",  "मेडक", "मदावनेनी रघुनंदन राव", " "}, 
{ "Telangana",  "5837",  "Medak", "Anil Kumar Gali", "ForeignFunding",  " ","तेलंगाना",  "मेडक", "अनिल कुमार गली", " "}, 
{ "Telangana",  "5838",  "Medak", "Merige Santhosh Reddy", "NotGraduate",  " ","तेलंगाना",  "मेडक", "मेरीज संतोष रेड्डी", " "}, 
{ "Telangana",  "5841",  "Medak", "Bangaru Krishna", "NotGraduate",  " ","तेलंगाना",  "मेडक", "बंगारु कृष्ण", " "}, 
{ "Telangana",  "5842",  "Medak", "Madhava Reddy Gari Hanmantha Reddy", "NotGraduate",  " ","तेलंगाना",  "मेडक", "माधव रेड्डी गारी हनमंथा रेड्डी", " "}, 
{ "Telangana",  "5843",  "Medak", "Thummalapally Pruthviraj", "NotGraduate",  " ","तेलंगाना",  "मेडक", "थुम्मलपल्ली पृथ्वीराज", " "}, 
{ "Telangana",  "5934",  "Nagarkurnool", "Baaki Renuka", "NotGraduate",  " ","तेलंगाना",  "नगरकुरनूल", "बाकि रेणुका", " "}, 
{ "Telangana",  "5935",  "Nagarkurnool", "B Yosef", "NotGraduate",  " ","तेलंगाना",  "नगरकुरनूल", "B योसेफ", " "}, 
{ "Telangana",  "5936",  "Nagarkurnool", "Pothuganti Ramulu", "OverAged",  " ","तेलंगाना",  "नगरकुरनूल", "पोथुगांती रामुलु", " "}, 
{ "Telangana",  "5937",  "Nagarkurnool", "Charagonda Krishnamma", "NotGraduate",  " ","तेलंगाना",  "नगरकुरनूल", "चरगोंदा कृष्णम्मा", " "}, 
{ "Telangana",  "5938",  "Nagarkurnool", "Shruthi Bangaru", "ForeignFunding",  " ","तेलंगाना",  "नगरकुरनूल", "श्रुति बंगारु", " "}, 
{ "Telangana",  "5939",  "Nagarkurnool", "Dr Mallu Ravi", "ForeignFunding",  " ","तेलंगाना",  "नगरकुरनूल", "डॉ मल्लू रवि", " "}, 
{ "Telangana",  "5941",  "Nagarkurnool", "Srinivasulu Buddula", "NotGraduate",  " ","तेलंगाना",  "नगरकुरनूल", "श्रीनिवासुलु बुद्धु", " "}, 
{ "Telangana",  "5942",  "Nagarkurnool", "V Amarnath", "NotGraduate",  " ","तेलंगाना",  "नगरकुरनूल", "वी अमरनाथ", " "}, 
{ "Telangana",  "5943",  "Nagarkurnool", "Prabhudas Bandaru Thumu", "NotGraduate",  " ","तेलंगाना",  "नगरकुरनूल", "प्रभुदास बंडारू ठुमू", " "}, 
{ "Telangana",  "5944",  "Nagarkurnool", "Karvanga Sharath", "NotGraduate",  " ","तेलंगाना",  "नगरकुरनूल", "करवंगा शरथ", " "}, 
{ "Telangana",  "5946",  "Nalgonda", "Mallu Laxmi", "CriminalCases",  " ","तेलंगाना",  "नलगोंडा", "मल्लू लक्ष्मी", " "}, 
{ "Telangana",  "5950",  "Nalgonda", "Nalamada Uttam Kumar Reddy", "ForeignFunding",  " ","तेलंगाना",  "नलगोंडा", "नालमदा उत्तम कुमार रेड्डी", " "}, 
{ "Telangana",  "5952",  "Nalgonda", "Marri. Nehemiah", "NotGraduate",  " ","तेलंगाना",  "नलगोंडा", "मर्री। नहेमायाह", " "}, 
{ "Telangana",  "5954",  "Nalgonda", "Solipuram Venugopal Reddy", "NotGraduate",  " ","तेलंगाना",  "नलगोंडा", "सोलीपुरम वेणुगोपाल रेड्डी", " "}, 
{ "Telangana",  "5956",  "Nalgonda", "Lalu Naik Ramavath", "NotGraduate",  " ","तेलंगाना",  "नलगोंडा", "लालू नाइक रामावत", " "}, 
{ "Telangana",  "5957",  "Nalgonda", "Thandu Upender", "NotGraduate",  " ","तेलंगाना",  "नलगोंडा", "थांडू उपेंद्र", " "}, 
{ "Telangana",  "5959",  "Nalgonda", "Karamtothu Mangtha", "NotGraduate",  " ","तेलंगाना",  "नलगोंडा", "करमथोथु मंगथा", " "}, 
{ "Telangana",  "5960",  "Nalgonda", "Polishetty Venkateshwarlu", "NotGraduate",  " ","तेलंगाना",  "नलगोंडा", "पोलीसिट्टी वेंकटेश्वरु", " "}, 
{ "Telangana",  "5961",  "Nalgonda", "Madhu Sapavath", "NotGraduate",  " ","तेलंगाना",  "नलगोंडा", "मधु सपवथ", " "}, 
{ "Telangana",  "5962",  "Nalgonda", "Maram Venkat Reddy", "NotGraduate",  " ","तेलंगाना",  "नलगोंडा", "मरम वेंकट रेड्डी", " "}, 
{ "Telangana",  "5965",  "Nalgonda", "Mekala Venkanna", "NotGraduate",  " ","तेलंगाना",  "नलगोंडा", "मेकाला वेंकन्ना", " "}, 
{ "Telangana",  "5966",  "Nalgonda", "Akula Paul", "NotGraduate",  " ","तेलंगाना",  "नलगोंडा", "अकुला पॉल", " "}, 
{ "Telangana",  "5967",  "Nalgonda", "Kiran Vangapalli", "NotGraduate",  " ","तेलंगाना",  "नलगोंडा", "किरण वनपल्ली", " "}, 
{ "Telangana",  "5969",  "Nalgonda", "Nakirikanti. Chittemma", "NotGraduate",  " ","तेलंगाना",  "नलगोंडा", "Nakirikanti। Chittemma", " "}, 
{ "Telangana",  "5971",  "Nalgonda", "Garlapati Jithendra Kumar", "ForeignFunding",  " ","तेलंगाना",  "नलगोंडा", "गरलापति जितेंद्र कुमार", " "}, 
{ "Telangana",  "5640",  "Nizamabad", "Tummala Naveen", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "तुममला नवीन", " "}, 
{ "Telangana",  "5641",  "Nizamabad", "Pundra Srinivas Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "पुंद्रा श्रीनिवास रेड्डी", " "}, 
{ "Telangana",  "5642",  "Nizamabad", "Mahender Nalimela", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "महेन्द्र नलिमेला", " "}, 
{ "Telangana",  "5643",  "Nizamabad", "Asli Ganesh", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "असली गणेश", " "}, 
{ "Telangana",  "5644",  "Nizamabad", "Kondhapuram Narsaiah", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "कोंडापुरम नरसैया", " "}, 
{ "Telangana",  "5647",  "Nizamabad", "Thirupathi Gaddam", "OverAged",  " ","तेलंगाना",  "निजामाबाद", "तिरुपति गद्दाम", " "}, 
{ "Telangana",  "5648",  "Nizamabad", "Sujith Gadepalli", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "सुजीत गदपल्ली", " "}, 
{ "Telangana",  "5649",  "Nizamabad", "Ettedi Saireddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "एतेदी सैयारेडी", " "}, 
{ "Telangana",  "5650",  "Nizamabad", "Vinay Tankasaala", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "विनय टंकसला", " "}, 
{ "Telangana",  "5651",  "Nizamabad", "Gummerla Vijay", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गुम्मरला विजय", " "}, 
{ "Telangana",  "5652",  "Nizamabad", "Anugu Thirumal", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "अनुगु थिरुमल", " "}, 
{ "Telangana",  "5653",  "Nizamabad", "Kumbala Sanjeeva Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "कुंभल संजीव रेड्डी", " "}, 
{ "Telangana",  "5654",  "Nizamabad", "Lingapuram Bhumeshwar", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "लिंगपुरम भुमेश्वर", " "}, 
{ "Telangana",  "5655",  "Nizamabad", "Enugu Mallesh", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "एनुगु मल्लेश", " "}, 
{ "Telangana",  "5656",  "Nizamabad", "Nalla Nadipi Muthenna", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "नल्ला नादिपि मुत्थेना", " "}, 
{ "Telangana",  "5657",  "Nizamabad", "Macharla Prathap", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "मचरला प्रताप", " "}, 
{ "Telangana",  "5658",  "Nizamabad", "Maggidi Narsaiah Mamidi", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "मग्गिदी नरसैया मामीदी", " "}, 
{ "Telangana",  "5659",  "Nizamabad", "Theegala Thirupathi Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "थेगला थिरुपथी रेड्डी", " "}, 
{ "Telangana",  "5660",  "Nizamabad", "Bakkashetti Ganagdhar", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "बकाक्षेति गणगधर", " "}, 
{ "Telangana",  "5662",  "Nizamabad", "Gaddam Gangareddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गद्दाम गैंगरेड्डी", " "}, 
{ "Telangana",  "5663",  "Nizamabad", "Srinivas Gundeti", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "श्रीनिवास गुंडेटी", " "}, 
{ "Telangana",  "5664",  "Nizamabad", "Soma Srinivas", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "सोमा श्रीनिवास", " "}, 
{ "Telangana",  "5665",  "Nizamabad", "Bodugam Narender", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "बोधुगम नरेंद्र", " "}, 
{ "Telangana",  "5666",  "Nizamabad", "Raja Venkat Reddy Pashapu", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "राजा वेंकट रेड्डी पाशुपु", " "}, 
{ "Telangana",  "5667",  "Nizamabad", "Linga Reddy Santha", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "लिंगा रेड्डी संथा", " "}, 
{ "Telangana",  "5668",  "Nizamabad", "Gujjula Ramesh", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गुजुला रमेश", " "}, 
{ "Telangana",  "5669",  "Nizamabad", "Mahesh Rayidi", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "महेश रायदी", " "}, 
{ "Telangana",  "5670",  "Nizamabad", "Maggidi Katipally Rajesh", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "मग्गी कटिपल्ली राजेश", " "}, 
{ "Telangana",  "5671",  "Nizamabad", "Venkatesh Kola", "CriminalCases",  " ","तेलंगाना",  "निजामाबाद", "वेंकटेश कोला", " "}, 
{ "Telangana",  "5672",  "Nizamabad", "Sai Reddy Puttiniti", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "साई रेड्डी पुतिनिती", " "}, 
{ "Telangana",  "5673",  "Nizamabad", "Admala Mahipal Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "अदमाला महिपाल रेड्डी", " "}, 
{ "Telangana",  "5675",  "Nizamabad", "Kongari Sanjiv", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "कोंगरी संजीव", " "}, 
{ "Telangana",  "5676",  "Nizamabad", "Swami Reddy Sama", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "स्वामी रेड्डी साम", " "}, 
{ "Telangana",  "5677",  "Nizamabad", "Gangareddy Mailaram", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गंगारेड्डी मेलाराम", " "}, 
{ "Telangana",  "5679",  "Nizamabad", "N Mallareddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "एन मल्लारेड्डी", " "}, 
{ "Telangana",  "5680",  "Nizamabad", "Nomula Mohan Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "नोमुला मोहन रेड्डी", " "}, 
{ "Telangana",  "5681",  "Nizamabad", "Ganga Reddy Peesu Peesu", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गंगा रेड्डी पीसू पीसू", " "}, 
{ "Telangana",  "5682",  "Nizamabad", "Mittapally Jeevan Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "मित्तपल्ली जीवन रेड्डी", " "}, 
{ "Telangana",  "5683",  "Nizamabad", "Madhusudan Alias Madhu Goud Yaskhi", "ForeignFunding",  " ","तेलंगाना",  "निजामाबाद", "मधुसूदन उर्फ मधु गौड़ यक्षी", " "}, 
{ "Telangana",  "5685",  "Nizamabad", "Theetla Anil", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "थेटला अनिल", " "}, 
{ "Telangana",  "5686",  "Nizamabad", "Gangareddy Musku", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गंगरेड्डी मुस्कु", " "}, 
{ "Telangana",  "5687",  "Nizamabad", "M. Malla Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "एम। मल्ला रेड्डी", " "}, 
{ "Telangana",  "5688",  "Nizamabad", "Rajareddi Rikkala", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "राजारेड्डी रिक्कला", " "}, 
{ "Telangana",  "5689",  "Nizamabad", "Santhosh Kamareddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "संतोष कमारेड्डी", " "}, 
{ "Telangana",  "5690",  "Nizamabad", "K Kavitha", "CriminalCases",  " ","तेलंगाना",  "निजामाबाद", "के कविथा", " "}, 
{ "Telangana",  "5691",  "Nizamabad", "Rajendar Pasapu", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "राजेन्द्र पसापू", " "}, 
{ "Telangana",  "5692",  "Nizamabad", "Baddam Devendar", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "बददाम देवेन्द्र", " "}, 
{ "Telangana",  "5695",  "Nizamabad", "Nemilla Linga Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "नेमिला लिंगा रेड्डी", " "}, 
{ "Telangana",  "5696",  "Nizamabad", "Sama Bhaskar Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "साम भास्कर रेड्डी", " "}, 
{ "Telangana",  "5697",  "Nizamabad", "Gaddam Rajeshwar", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गद्दाम राजेश्वर", " "}, 
{ "Telangana",  "5698",  "Nizamabad", "Kommula Buchireddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "कोमूला बुचिरेड्डी", " "}, 
{ "Telangana",  "5699",  "Nizamabad", "Bejjenki Linga Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "बेजेंकी लिंग रेड्डी", " "}, 
{ "Telangana",  "5700",  "Nizamabad", "Aleti Malla Reddy", "CriminalCases",  " ","तेलंगाना",  "निजामाबाद", "अलेटि मल्ला रेड्डी", " "}, 
{ "Telangana",  "5702",  "Nizamabad", "Pedda Gangaram Turpu", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "पेड़ा गंगाराम तुरपु", " "}, 
{ "Telangana",  "5703",  "Nizamabad", "Gadepalli Prthviraj", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गदपल्ली पृथ्वीराज", " "}, 
{ "Telangana",  "5704",  "Nizamabad", "Chinthalapally Raghupathi Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "चिन्तलपल्ली रघुपति रेड्डी", " "}, 
{ "Telangana",  "5705",  "Nizamabad", "Rapelly Srinivas", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "रापेली श्रीनिवास", " "}, 
{ "Telangana",  "5706",  "Nizamabad", "Dabba Raja Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "डब्बा राजा रेड्डी", " "}, 
{ "Telangana",  "5708",  "Nizamabad", "Natta Bavanna", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "नत्त बवाना", " "}, 
{ "Telangana",  "5709",  "Nizamabad", "Venkat Reddy Jaidi", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "वेंकट रेड्डी जैदी", " "}, 
{ "Telangana",  "5710",  "Nizamabad", "Edamala Ravinder Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "एडमाला रविन्दर रेड्डी", " "}, 
{ "Telangana",  "5711",  "Nizamabad", "Hanmandlu Puppala", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "हनमंडलु पुपाल", " "}, 
{ "Telangana",  "5712",  "Nizamabad", "Gaddam Rajendharreddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गद्दाम राजेन्द्रहेडी", " "}, 
{ "Telangana",  "5713",  "Nizamabad", "Muthenna Lakkara", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "मुथेना लकड़ा", " "}, 
{ "Telangana",  "5714",  "Nizamabad", "Penta Narsaiah", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "पेंटा नरसैया", " "}, 
{ "Telangana",  "5715",  "Nizamabad", "Gadepally Ramesh", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गद्दीपद रमेश", " "}, 
{ "Telangana",  "5716",  "Nizamabad", "Balije Laxmirajam", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "बलिजे लक्ष्मीराजम्", " "}, 
{ "Telangana",  "5717",  "Nizamabad", "Ravindhar Bandi", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "रविन्द्र बांधी", " "}, 
{ "Telangana",  "5718",  "Nizamabad", "Rotte Chakradhar Sharma", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "रोट चक्रधर शर्मा", " "}, 
{ "Telangana",  "5722",  "Nizamabad", "Laxman Ganna", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "लक्ष्मण गण", " "}, 
{ "Telangana",  "5724",  "Nizamabad", "Rajashekar Sarikela", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "राजशेखर सरीकेला", " "}, 
{ "Telangana",  "5725",  "Nizamabad", "Aare Sayanna", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "आरे स्याना", " "}, 
{ "Telangana",  "5727",  "Nizamabad", "Pedda Gangadar Talari", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "पेड़ा गंगाधर तलारी", " "}, 
{ "Telangana",  "5728",  "Nizamabad", "Gaddam Suman", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गद्दाम सुमन", " "}, 
{ "Telangana",  "5729",  "Nizamabad", "Linga Reddy Doddikindi", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "लिंगा रेड्डी डोडिकंडी", " "}, 
{ "Telangana",  "5730",  "Nizamabad", "Aleti Rajareddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "अलेटी राजारेड्डी", " "}, 
{ "Telangana",  "5731",  "Nizamabad", "Prakash Manchiryala", "OverAged",  " ","तेलंगाना",  "निजामाबाद", "प्रकाश मंचरीला", " "}, 
{ "Telangana",  "5732",  "Nizamabad", "Kandukala Shiva Kumar Goud", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "कंदुकला शिव कुमार गौड़", " "}, 
{ "Telangana",  "5733",  "Nizamabad", "Mandala Shekhar", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "मंडल शेखर", " "}, 
{ "Telangana",  "5734",  "Nizamabad", "Aloori Anil Kumar", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "अलोरी अनिल कुमार", " "}, 
{ "Telangana",  "5735",  "Nizamabad", "Bathnathe Shankar", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "बथनाथे शंकर", " "}, 
{ "Telangana",  "5736",  "Nizamabad", "Limba Reddy Perkit", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "लिम्बा रेड्डी पर्किट", " "}, 
{ "Telangana",  "5737",  "Nizamabad", "Narsareddy Pannala", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "नरसारेड्डी पन्नाला", " "}, 
{ "Telangana",  "5738",  "Nizamabad", "Kurma Divakar", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "कूर्म दिवाकर", " "}, 
{ "Telangana",  "5741",  "Nizamabad", "Komati Reddy Prashanth", "CriminalCases",  " ","तेलंगाना",  "निजामाबाद", "कोमाती रेड्डी प्रशांत", " "}, 
{ "Telangana",  "5742",  "Nizamabad", "Loka Subhash", "CriminalCases",  " ","तेलंगाना",  "निजामाबाद", "लोका सुभाष", " "}, 
{ "Telangana",  "5743",  "Nizamabad", "Mamidi Thirupathireddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "ममीदी थिरुपथिरेड्डी", " "}, 
{ "Telangana",  "5745",  "Nizamabad", "Nadisharam Mallaiah", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "नादिशारम मल्लैया", " "}, 
{ "Telangana",  "5746",  "Nizamabad", "Gadkolu Ramesh", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गडकोलु रमेश", " "}, 
{ "Telangana",  "5747",  "Nizamabad", "Santosh Komamula", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "संतोष कोमूला", " "}, 
{ "Telangana",  "5748",  "Nizamabad", "Urumalla Lakshma Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "उरुमल लक्ष्मण रेड्डी", " "}, 
{ "Telangana",  "5749",  "Nizamabad", "Nadipi Gangaram Niradi", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "नादिपि गंगाराम निरादी", " "}, 
{ "Telangana",  "5750",  "Nizamabad", "Alakunta Rajanna", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "अलकुन्ता राजन्ना", " "}, 
{ "Telangana",  "5751",  "Nizamabad", "Suresh Baddam", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "सुरेश बद्दाम", " "}, 
{ "Telangana",  "5753",  "Nizamabad", "Nagulapalli Devendhar", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "नागुलपल्ली देवेंद्र", " "}, 
{ "Telangana",  "5754",  "Nizamabad", "Mekkonda Ramreddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "मेककोंडा रामरेड्डी", " "}, 
{ "Telangana",  "5755",  "Nizamabad", "Mittapalli Malliah", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "मित्तपल्ली मल्लाह", " "}, 
{ "Telangana",  "5757",  "Nizamabad", "Jaidi Chinna Gangaram", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "जैदी चिन्ना गंगाराम", " "}, 
{ "Telangana",  "5760",  "Nizamabad", "Goskula Mahesh Babu", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गोसकुला महेश बाबू", " "}, 
{ "Telangana",  "5761",  "Nizamabad", "Anjaiah Kondani", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "अंजिया कोंडानी", " "}, 
{ "Telangana",  "5762",  "Nizamabad", "Ganganna Chilkuri", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गंगना चिलकुरी", " "}, 
{ "Telangana",  "5763",  "Nizamabad", "Santosh Barla", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "संतोष बराला", " "}, 
{ "Telangana",  "5764",  "Nizamabad", "Dharmapuri Arvind", "ForeignFunding",  " ","तेलंगाना",  "निजामाबाद", "धर्मपुरी अरविंद", " "}, 
{ "Telangana",  "5766",  "Nizamabad", "Gangadhar Baddam", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गंगाधर बादाम", " "}, 
{ "Telangana",  "5767",  "Nizamabad", "Gangareddy Thorthi", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गंगारेड्डी थोरथी", " "}, 
{ "Telangana",  "5768",  "Nizamabad", "Ramesh Reddy Sama", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "रमेश रेड्डी समामा", " "}, 
{ "Telangana",  "5769",  "Nizamabad", "Turaga Narsareddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "तुरगा नरसारेड्डी", " "}, 
{ "Telangana",  "5770",  "Nizamabad", "Baddam Indrasena Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "बादाम इंद्रसेन रेड्डी", " "}, 
{ "Telangana",  "5771",  "Nizamabad", "Guradi Srinivas", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गुरदी श्रीनिवास", " "}, 
{ "Telangana",  "5772",  "Nizamabad", "K. Ram Raj", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "के राम राज", " "}, 
{ "Telangana",  "5773",  "Nizamabad", "Katipally Kumar", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "काटिपल्ली कुमार", " "}, 
{ "Telangana",  "5774",  "Nizamabad", "Bandela Venkatarajam", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "बंदेला वेंकटराजम", " "}, 
{ "Telangana",  "5775",  "Nizamabad", "Velma Mallareddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "वेलमा मल्लेरड्डी", " "}, 
{ "Telangana",  "5776",  "Nizamabad", "Balakishna Nalla", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "बालकृष्ण नाला", " "}, 
{ "Telangana",  "5777",  "Nizamabad", "Kunta Narayana Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "कुंता नारायण रेड्डी", " "}, 
{ "Telangana",  "5778",  "Nizamabad", "Narsaiah Gunda", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "नरसैया गुंडा", " "}, 
{ "Telangana",  "5779",  "Nizamabad", "Eleti Laxmareddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "एलेटि लक्ष्मर्दी", " "}, 
{ "Telangana",  "5780",  "Nizamabad", "Gangareddy Rikkala", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गंगरेड्डी रिक्काला", " "}, 
{ "Telangana",  "5781",  "Nizamabad", "Rajareddy Gangasaram", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "राजारेड्डी गंगासाराम", " "}, 
{ "Telangana",  "5782",  "Nizamabad", "Suman Maggidi", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "सुमन मग्गिदी", " "}, 
{ "Telangana",  "5783",  "Nizamabad", "Theegala Ashok Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "थेगला अशोक रेड्डी", " "}, 
{ "Telangana",  "5784",  "Nizamabad", "Sayanna Bai", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "सयना बाई", " "}, 
{ "Telangana",  "5785",  "Nizamabad", "Mahendhar Kottala", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "महेंद्र कोट्टला", " "}, 
{ "Telangana",  "5787",  "Nizamabad", "Chintalapelly Gangareddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "चिंतलपेली गंगारेड्डी", " "}, 
{ "Telangana",  "5788",  "Nizamabad", "Thirupathi Reddy Pannala", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "तिरुपति रेड्डी पन्नला", " "}, 
{ "Telangana",  "5789",  "Nizamabad", "Devanna Pindi", "OverAged",  " ","तेलंगाना",  "निजामाबाद", "देवना पिंडी", " "}, 
{ "Telangana",  "5790",  "Nizamabad", "Baddam Ashok", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "बद्दाम अशोक", " "}, 
{ "Telangana",  "5791",  "Nizamabad", "Ippa Lachchanna", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "इप्पा लछन्ना", " "}, 
{ "Telangana",  "5792",  "Nizamabad", "Rajeshwar Musku", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "राजेश्वर मुस्कु", " "}, 
{ "Telangana",  "5793",  "Nizamabad", "Surakanti Raja Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "सुरकांति राजा रेड्डी", " "}, 
{ "Telangana",  "5794",  "Nizamabad", "Rajeshwar Enugu", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "राजेश्वर एनुगु", " "}, 
{ "Telangana",  "5796",  "Nizamabad", "Medipalli Shekar Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "मेडिपल्ली शकर रेड्डी", " "}, 
{ "Telangana",  "5797",  "Nizamabad", "Akula Hanmandlu", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "अकुला हनमंडलु", " "}, 
{ "Telangana",  "5798",  "Nizamabad", "Mamidi Chinna Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "ममदी चिन्ना रेड्डी", " "}, 
{ "Telangana",  "5799",  "Nizamabad", "Maru Janardhan", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "मारु जनार्दन", " "}, 
{ "Telangana",  "5800",  "Nizamabad", "Gangadhar Andheti", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गंगाधर अन्धेती", " "}, 
{ "Telangana",  "5801",  "Nizamabad", "Alluri Limba Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "अल्लूरी लिम्बा रेड्डी", " "}, 
{ "Telangana",  "5802",  "Nizamabad", "Borranna Gummerla", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "बोरना गुम्मरला", " "}, 
{ "Telangana",  "5803",  "Nizamabad", "Mohanareddy Eleti", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "मोहनरेड्डी एलेटि", " "}, 
{ "Telangana",  "5804",  "Nizamabad", "Angu Poshetty", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "आंगु पाशेति", " "}, 
{ "Telangana",  "5805",  "Nizamabad", "Chinnaiah Mukkera", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "चिन्नाहिया मुकेरा", " "}, 
{ "Telangana",  "5806",  "Nizamabad", "Byagari Shanthaiah", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "बयागरी शांतिहाया", " "}, 
{ "Telangana",  "5807",  "Nizamabad", "Sandireddy Gopal Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "संदीपारी गोपाल रेड्डी", " "}, 
{ "Telangana",  "5808",  "Nizamabad", "Praveen Paidigela", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "प्रवीण पेडिगेला", " "}, 
{ "Telangana",  "5809",  "Nizamabad", "Mahendhar Musku", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "महेंद्र मुस्कू", " "}, 
{ "Telangana",  "5810",  "Nizamabad", "Ravishankar Kunta", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "रविशंकर कुंता", " "}, 
{ "Telangana",  "5811",  "Nizamabad", "Pothuganti Venkatesh", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "पोथुगांती वेंकटेश", " "}, 
{ "Telangana",  "5812",  "Nizamabad", "B. Srinivas", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "बी। श्रीनिवास", " "}, 
{ "Telangana",  "5813",  "Nizamabad", "Armoor Sagar", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "कवच सागर", " "}, 
{ "Telangana",  "5814",  "Nizamabad", "J. Chinna Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "जे। चिन्ना रेड्डी", " "}, 
{ "Telangana",  "5815",  "Nizamabad", "Baddam Balaraju", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "बादाम बलराजु", " "}, 
{ "Telangana",  "5816",  "Nizamabad", "Gadkole Chinna Gangareddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गडकोले चिन्ना गंगारेड्डी", " "}, 
{ "Telangana",  "5818",  "Nizamabad", "Teegala Rajeshwar", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "तेगला राजेश्वर", " "}, 
{ "Telangana",  "5819",  "Nizamabad", "Doda Mutta Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "डोडा मुत्ता रेड्डी", " "}, 
{ "Telangana",  "5820",  "Nizamabad", "Aleti Sanjeev Reddy", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "अलेटि संजीव रेड्डी", " "}, 
{ "Telangana",  "5821",  "Nizamabad", "Surukanti Chinna Anjaiah", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "सुरुकन्ती चिन्ना अंजैया", " "}, 
{ "Telangana",  "5822",  "Nizamabad", "Gajjala Sai Prasad", "NotGraduate",  " ","तेलंगाना",  "निजामाबाद", "गज्जला साईं प्रसाद", " "}, 
{ "Telangana",  "5291",  "Peddapalle", "Arsham Ashok", "NotGraduate",  " ","तेलंगाना",  "पेडेपल्लै", "अरशम अशोक", " "}, 
{ "Telangana",  "5292",  "Peddapalle", "Sankenapalli. Devadas", "NotGraduate",  " ","तेलंगाना",  "पेडेपल्लै", "Sankenapalli। देवदास", " "}, 
{ "Telangana",  "5294",  "Peddapalle", "Velthuru Mallaiah", "NotGraduate",  " ","तेलंगाना",  "पेडेपल्लै", "वेल्थुरु मल्लैया", " "}, 
{ "Telangana",  "5299",  "Peddapalle", "Godisella Nagamani", "NotGraduate",  " ","तेलंगाना",  "पेडेपल्लै", "गोडिसेला नागमणि", " "}, 
{ "Telangana",  "5300",  "Peddapalle", "Dr. Agama Chandrashekar", "ForeignFunding",  " ","तेलंगाना",  "पेडेपल्लै", "डॉ। अगमा चंद्रशेखर", " "}, 
{ "Telangana",  "5301",  "Peddapalle", "Sirikonda Krishna", "NotGraduate",  " ","तेलंगाना",  "पेडेपल्लै", "सिरिकोंडा कृष्णा", " "}, 
{ "Telangana",  "5303",  "Peddapalle", "Gaddala Vinay Kumar", "NotGraduate",  " ","तेलंगाना",  "पेडेपल्लै", "गद्दाला विनय कुमार", " "}, 
{ "Telangana",  "5304",  "Peddapalle", "Ambala Mahendar", "NotGraduate",  " ","तेलंगाना",  "पेडेपल्लै", "अंबाला महेंद्र", " "}, 
{ "Telangana",  "5305",  "Peddapalle", "Kuntala Narsaiah", "NotGraduate",  " ","तेलंगाना",  "पेडेपल्लै", "कुंतला नरसैया", " "}, 
{ "Telangana",  "5306",  "Peddapalle", "Krishna Sabbani", "CriminalCases",  " ","तेलंगाना",  "पेडेपल्लै", "कृष्णा सबबानी", " "}, 
{ "Telangana",  "5307",  "Peddapalle", "Kumar Sogula", "ForeignFunding",  " ","तेलंगाना",  "पेडेपल्लै", "कुमार सोगुला", " "}, 
{ "Telangana",  "5856",  "Secunderabad", "Gangapuram Kishan Reddy", "ForeignFunding",  " ","तेलंगाना",  "सिकंदराबाद", "गंगापुरम किशन रेड्डी", " "}, 
{ "Telangana",  "5857",  "Secunderabad", "R Laxman Rao Gangaputra", "NotGraduate",  " ","तेलंगाना",  "सिकंदराबाद", "आर लक्ष्मण राव गंगापुत्र", " "}, 
{ "Telangana",  "5858",  "Secunderabad", "Shakti Satayavathi", "NotGraduate",  " ","तेलंगाना",  "सिकंदराबाद", "शक्ति सत्यवती", " "}, 
{ "Telangana",  "5859",  "Secunderabad", "G . Laxminarsimha Rao", "CriminalCases",  " ","तेलंगाना",  "सिकंदराबाद", "जी। लक्ष्मीनारसिम्हा राव", " "}, 
{ "Telangana",  "5860",  "Secunderabad", "Anjan Kumar Yadav", "ForeignFunding",  " ","तेलंगाना",  "सिकंदराबाद", "अंजन कुमार यादव", " "}, 
{ "Telangana",  "5861",  "Secunderabad", "Dornala Jaya Prakash", "CriminalCases",  " ","तेलंगाना",  "सिकंदराबाद", "दोरनाला जय प्रकाश", " "}, 
{ "Telangana",  "5863",  "Secunderabad", "Bathula Ravi", "NotGraduate",  " ","तेलंगाना",  "सिकंदराबाद", "बथुला रवि", " "}, 
{ "Telangana",  "5865",  "Secunderabad", "Junaid Anam Siddiqui", "NotGraduate",  " ","तेलंगाना",  "सिकंदराबाद", "जुनैद अनम सिद्दीकी", " "}, 
{ "Telangana",  "5867",  "Secunderabad", "N . Shankar Goud", "NotGraduate",  " ","तेलंगाना",  "सिकंदराबाद", "एन। शंकर गौड", " "}, 
{ "Telangana",  "5868",  "Secunderabad", "Talasani Sai Kiran", "CriminalCases",  " ","तेलंगाना",  "सिकंदराबाद", "तलसानी साई किरन", " "}, 
{ "Telangana",  "5870",  "Secunderabad", "Abdul Azeem", "NotGraduate",  " ","तेलंगाना",  "सिकंदराबाद", "अब्दुल अज़ीम", " "}, 
{ "Telangana",  "5871",  "Secunderabad", "M . D . Nazeer Uddin Quadri", "NotGraduate",  " ","तेलंगाना",  "सिकंदराबाद", "एम। डी। नज़ीर उद्दीन क्वाडरी", " "}, 
{ "Telangana",  "5872",  "Secunderabad", "Shaik Muneer Pasha", "NotGraduate",  " ","तेलंगाना",  "सिकंदराबाद", "शेख मुनीर पाशा", " "}, 
{ "Telangana",  "5875",  "Secunderabad", "Farah Naaz Khan", "NotGraduate",  " ","तेलंगाना",  "सिकंदराबाद", "फराह नाज़ खान", " "}, 
{ "Telangana",  "5878",  "Secunderabad", "Abdallah Ibrahim", "NotGraduate",  " ","तेलंगाना",  "सिकंदराबाद", "अब्दुल्ला इब्राहिम", " "}, 
{ "Telangana",  "5879",  "Secunderabad", "K Venkatanarayana", "NotGraduate",  " ","तेलंगाना",  "सिकंदराबाद", "के वेंकटनारायण", " "}, 
{ "Telangana",  "5883",  "Secunderabad", "Srirama Naik Munavath", "CriminalCases",  " ","तेलंगाना",  "सिकंदराबाद", "श्रीराम नाइक मुनवथ", " "}, 
{ "Telangana",  "5984",  "Warangal", "Chintha Sambamurthy", "ForeignFunding",  " ","तेलंगाना",  "वारंगल", "चिन्ता सम्बामूर्ति", " "}, 
{ "Telangana",  "5985",  "Warangal", "Kannam Venkanna", "NotGraduate",  " ","तेलंगाना",  "वारंगल", "कन्नम वेंकन्ना", " "}, 
{ "Telangana",  "5986",  "Warangal", "Pasula Rammurthy", "NotGraduate",  " ","तेलंगाना",  "वारंगल", "पसुला राममूर्ति", " "}, 
{ "Telangana",  "5989",  "Warangal", "Sambaiah Dommati", "ForeignFunding",  " ","तेलंगाना",  "वारंगल", "सांभिया दम्मति", " "}, 
{ "Telangana",  "5992",  "Warangal", "Chiluveru Prathap", "NotGraduate",  " ","तेलंगाना",  "वारंगल", "चिलुवरु प्रताप", " "}, 
{ "Telangana",  "5993",  "Warangal", "Paniganti Rajithavani", "NotGraduate",  " ","तेलंगाना",  "वारंगल", "पाणिगंति राजितवनी", " "}, 
{ "Telangana",  "5994",  "Warangal", "Bunga Jyothi Ramana", "CriminalCases",  " ","तेलंगाना",  "वारंगल", "बुंगा ज्योति रमणा", " "}, 
{ "Telangana",  "5995",  "Warangal", "Aitha Praveen Kumar", "NotGraduate",  " ","तेलंगाना",  "वारंगल", "ऐथा प्रवीण कुमार", " "}, 
{ "Telangana",  "5996",  "Warangal", "Jannu Narsaiah", "CriminalCases",  " ","तेलंगाना",  "वारंगल", "जन्नु नरसैया", " "}, 
{ "Telangana",  "5997",  "Warangal", "Suresh Kanakam", "NotGraduate",  " ","तेलंगाना",  "वारंगल", "सुरेश कनकम", " "}, 
{ "Telangana",  "5824",  "Zahirabad", "Mudiraj Venkatesham", "NotGraduate",  " ","तेलंगाना",  "जहीराबाद", "मुदिराज वेंकटेशम", " "}, 
{ "Telangana",  "5826",  "Zahirabad", "B.B.Patil", "CriminalCases",  " ","तेलंगाना",  "जहीराबाद", "BBPatil", " "}, 
{ "Telangana",  "5827",  "Zahirabad", "Mark Babu", "CriminalCases",  " ","तेलंगाना",  "जहीराबाद", "मार्क बाबू", " "}, 
{ "Telangana",  "5828",  "Zahirabad", "Banala Laxma Reddy", "ForeignFunding",  " ","तेलंगाना",  "जहीराबाद", "बनाला लक्ष्मा रेड्डी", " "}, 
{ "Telangana",  "5831",  "Zahirabad", "K. Madan Mohan Rao", "ForeignFunding",  " ","तेलंगाना",  "जहीराबाद", "के। मदन मोहन राव", " "}, 
{ "Telangana",  "5832",  "Zahirabad", "Mohammed Nawaz", "NotGraduate",  " ","तेलंगाना",  "जहीराबाद", "मोहम्मद नवाज", " "}, 
};

}