/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Uttar_Pradesh {
public static final String[][] green_bucket = {
{"Uttar Pradesh",  "6270", "Agra", "Manoj Kumar Soni", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5519",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6271", "Agra", "Babu Lal", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7133",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6272", "Agra", "Himanshi", "Lok Gathbandhan Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7134",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6237", "Aligarh", "Ajeet Kumar", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5508",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6240", "Aligarh", "Satish Chandra Sharma", "AAP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5513",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6242", "Aligarh", "Amar Singh Mahaur", "Swatantra Jantaraj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7110",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6243", "Aligarh", "Dileep Sharma", "Peace Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7114",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6164", "Amroha", "Vikar Ahmad", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6123",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6165", "Amroha", "Naresh Kumar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6127",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6166", "Amroha", "Akhtar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6122",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6167", "Amroha", "Rajpal Singh", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6125",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6170", "Amroha", "Kunwar Danish Ali", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5501",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6172", "Amroha", "Rajpal Singh Saini", "Jan Shakti Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6124",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6185", "Baghpat", "Jayant Chaudhary", "RLD", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5469",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6190", "Baghpat", "Ruby Kashyap", "Hindusthan Nirman Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6151",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6195", "Baghpat", "Subhash", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5470",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6152", "Bijnor", "Mahak Singh", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6114",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6155", "Bijnor", "Parvej Aqil", "All India Minorities Front", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6109",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6156", "Bijnor", "Mohammad Zahid", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6107",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6223", "Bulandshahr", "Vinay Kumar", "Aapki Apni Party (Peoples)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5503",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6224", "Bulandshahr", "Satish", "Bharatiya Bahujan Parivartan Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7109",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6226", "Bulandshahr", "Pramod Kumar", "Rashtriya Samaj Paksha", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7106",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6227", "Bulandshahr", "Radhika Devi", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7107",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6229", "Bulandshahr", "Manoj Kumar Singh", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7105",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6274", "Fatehpur Sikri", "Sarvesh Kumar", "Bharatiya Majdoor Janta Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7146",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6275", "Fatehpur Sikri", "Sadab Noor", "Adarsh Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7145",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6280", "Fatehpur Sikri", "Anil Kumar Kushwaha", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7137",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6281", "Fatehpur Sikri", "Purushottam Das (Fauzi Bhai)", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7143",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6282", "Fatehpur Sikri", "Naresh Kumar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7140",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6287", "Fatehpur Sikri", "Satendar", "Aam Janta Party (India)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5527",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6210", "Gautam Buddha Nagar", "Rampal", "Rashtriya Samaj Paksha", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6167",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6211", "Gautam Buddha Nagar", "Jagdeep Singh", "Loktantrik Janshakti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6168",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6212", "Gautam Buddha Nagar", "Rodash Gupta", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6169",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6214", "Gautam Buddha Nagar", "Raghuvendra Kumar", "Subhashwadi Bhartiya Samajwadi Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6333",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6198", "Ghaziabad", "Mohan Lal", "RPI(A)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6160",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6199", "Ghaziabad", "Ashok Sharma", "Subhashwadi Bhartiya Samajwadi Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4947",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6202", "Ghaziabad", "Rakesh Suri", "Right to Recall Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4945",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6206", "Ghaziabad", "Nagendra Kumar", "SHS", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6162",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6208", "Ghaziabad", "Mohd. Salim Ahmed", "Sabse Achchhi Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6155",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6245", "Hathras", "Dinesh Sai", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5518",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6121", "Kairana", "Mukesh Devi", "Mahasankalp Janta Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5463",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6124", "Kairana", "Mohd Saleem", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4774",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6133", "Kairana", "Mohd Gufran Kazmi", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5460",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6253", "Mathura", "Jagvir Singh", "Pragatishil Samajwadi Party (Lohia)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7124",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6254", "Mathura", "Ramdas Tyagi", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7131",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6256", "Mathura", "Chattar Alias Chatrapal Singh Nishad", "Bahujan Mukti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7122",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6258", "Mathura", "Omprakash", "Swatantra Jantaraj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7128",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6260", "Mathura", "Dinesh Kumar Gautam", "Bhartiya Anarakshit Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5489",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6177", "Meerut", "Sahansar Pal Singh", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6142",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6181", "Meerut", "Arti Agrawal", "SHS", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6137",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6184", "Meerut", "Dharmendra", "BHARTIYA JANTA DAL", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6141",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6135", "Muzaffarnagar", "Ankit", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6103",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6140", "Muzaffarnagar", "Mangeram Kashyap", "Majdoor Kisan Union Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6099",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6142", "Muzaffarnagar", "S.S.K.S. Gangwal", "Bharatiya Bahujan Samta Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6098",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6143", "Muzaffarnagar", "Neel Kumar", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6100",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6157", "Nagina", "Kamesh Kumar", "Peoples Party of India (Democratic)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5493",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6161", "Nagina", "Charan Singh", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6119",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6115", "Saharanpur", "Ravindra Kumar", "Inqalab Vikas Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6080",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6117", "Saharanpur", "Brijpal Singh", "Hindusthan Nirman Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6079",  "",  "", "", "", ""}, 
{"Uttar Pradesh",  "6118", "Saharanpur", "Haji Fazlur Rehman", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6076",  "",  "", "", "", ""}, 
};

public static final String[][] red_bucket = {
{ "Uttar Pradesh",  "6266",  "Agra", "Ramji Lal Vidhyarthi", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6267",  "Agra", "Ambedkari Hasnuram Ambedkari", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6268",  "Agra", "Preeta Harit", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6269",  "Agra", "Satyapal Singh Baghel", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6273",  "Agra", "Raja", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6232",  "Aligarh", "Shaheen", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6233",  "Aligarh", "Sanjay Balmiki", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6234",  "Aligarh", "Thakur Manoj Singh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6235",  "Aligarh", "Charan Singh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6236",  "Aligarh", "Mohd. Shakeel (Adv.)", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6238",  "Aligarh", "Satish Kumar Gautam", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6239",  "Aligarh", "Bijendra Singh", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6241",  "Aligarh", "Deepak Chaudhary", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6244",  "Aligarh", "Ashok Kumar Pandey", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6168",  "Amroha", "Robin Tyagi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6169",  "Amroha", "Matloob Ahmad", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6171",  "Amroha", "Sachin Choudhary", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6173",  "Amroha", "Kanwar Singh Tanwar", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6186",  "Baghpat", "Istakar Ali", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6187",  "Baghpat", "Davender", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6188",  "Baghpat", "Jafar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6189",  "Baghpat", "Parveen Yogi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6191",  "Baghpat", "Ramkumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6192",  "Baghpat", "Uttar Kumar Jindal", "OverAged",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6193",  "Baghpat", "Manoj Rana", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6194",  "Baghpat", "Dr. Satyapal Singh", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6196",  "Baghpat", "Chaudhary Mohkam", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6197",  "Baghpat", "Dr. Saleem Ahmad", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6144",  "Bijnor", "Mukesh Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6145",  "Bijnor", "Ilam Singh", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6146",  "Bijnor", "Rajiv Choudhary", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6147",  "Bijnor", "Malook Nagar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6148",  "Bijnor", "Nasimuddin Siddqui", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6149",  "Bijnor", "Sonu", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6150",  "Bijnor", "Raja Bhartendra Singh", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6151",  "Bijnor", "Babloo Ram", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6153",  "Bijnor", "Mangeram", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6154",  "Bijnor", "Anshu Chaitanya Maharaj", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6225",  "Bulandshahr", "Bhola Singh", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6228",  "Bulandshahr", "Banshi Singh", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6230",  "Bulandshahr", "Reena Devi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6231",  "Bulandshahr", "Yogesh Verma", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6276",  "Fatehpur Sikri", "Manisha Singh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6277",  "Fatehpur Sikri", "Arti Sharma", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6278",  "Fatehpur Sikri", "Rajkumar Chahar", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6279",  "Fatehpur Sikri", "Ram Bahori", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6283",  "Fatehpur Sikri", "Vijay Singh Baghel", "OverAged",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6284",  "Fatehpur Sikri", "Pastar Thomsan Massy", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6285",  "Fatehpur Sikri", "Nawab Gul Chaman Sherwani", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6286",  "Fatehpur Sikri", "Raj Babbar", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6288",  "Fatehpur Sikri", "Shreebhagwan Sharma", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6213",  "Gautam Buddha Nagar", "Dr. Mahesh Sharma", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6215",  "Gautam Buddha Nagar", "Ashok Kumar Adhana", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6216",  "Gautam Buddha Nagar", "Vinod Sharma", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6217",  "Gautam Buddha Nagar", "Vinod Kumar Nagar", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6218",  "Gautam Buddha Nagar", "Jitendra Singh", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6219",  "Gautam Buddha Nagar", "Dayaram", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6220",  "Gautam Buddha Nagar", "Satveer", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6221",  "Gautam Buddha Nagar", "Dr. Arvind Kumar Singh", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6222",  "Gautam Buddha Nagar", "Sher Singh Upaddhaya", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6200",  "Ghaziabad", "Vijay Kumar Singh", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6201",  "Ghaziabad", "Sewa Ram Kasana", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6203",  "Ghaziabad", "Suresh Bansal", "OverAged",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6204",  "Ghaziabad", "Divya Yog Maya Saraswati", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6205",  "Ghaziabad", "Dolly Sharma", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6207",  "Ghaziabad", "Amit Sharma", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6209",  "Ghaziabad", "Sunil Nair", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6246",  "Hathras", "Rajaram", "OverAged",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6247",  "Hathras", "Triloki Ram", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6248",  "Hathras", "Ramji Lal Suman", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6249",  "Hathras", "Tilak Singh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6250",  "Hathras", "Harswaroop", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6251",  "Hathras", "Bhupendra Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6252",  "Hathras", "Rajvir Diler", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6122",  "Kairana", "Rekha", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6123",  "Kairana", "Harish Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6125",  "Kairana", "Tabassum Begum", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6126",  "Kairana", "Harendra Singh Malik", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6127",  "Kairana", "Shripal Singh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6128",  "Kairana", "Yogesh Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6129",  "Kairana", "Sheshraj", "OverAged",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6130",  "Kairana", "Pradeep Kumar", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6131",  "Kairana", "Manoj Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6132",  "Kairana", "Imran", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6255",  "Mathura", "Pramod Krishna", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6257",  "Mathura", "Jasveer Singh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6259",  "Mathura", "Phakkad Baba", "OverAged",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6261",  "Mathura", "Mahesh Pathak", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6262",  "Mathura", "Jasvant Singh Baghel", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6263",  "Mathura", "Narendra Singh", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6264",  "Mathura", "Ramdev Gautam", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6265",  "Mathura", "Hema Malini Dharmendra Deol", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6174",  "Meerut", "Rajendra Agarwal", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6175",  "Meerut", "Harendra Agarwal", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6176",  "Meerut", "Afzaal", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6178",  "Meerut", "Shrawan Kumar Agarwal", "OverAged",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6179",  "Meerut", "Haji Mohammad Yaqoob", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6180",  "Meerut", "Rajesh Giri", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6182",  "Meerut", "Nasir Ali Khan", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6183",  "Meerut", "Kiran R. C. Jatav", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6134",  "Muzaffarnagar", "Ajit Singh", "OverAged",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6136",  "Muzaffarnagar", "Jaipal Singh Saini", "OverAged",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6137",  "Muzaffarnagar", "Krishan Pal Singh", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6138",  "Muzaffarnagar", "Yajpal Singh Rathi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6139",  "Muzaffarnagar", "Sanjeev Kumar Balyan", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6141",  "Muzaffarnagar", "Ashok", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6158",  "Nagina", "Girish Chandra", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6159",  "Nagina", "Omvati Devi", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6160",  "Nagina", "Yashwant Singh", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6162",  "Nagina", "Amichand", "OverAged",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6163",  "Nagina", "Tej Singh", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6110",  "Saharanpur", "Yogesh Dahiya", "CriminalCases",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6111",  "Saharanpur", "Pawan Kumar", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6112",  "Saharanpur", "Amar Bahadur", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6113",  "Saharanpur", "Shabnam", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6114",  "Saharanpur", "Indu Devi", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6116",  "Saharanpur", "Raghav Lakhanpal", "ForeignFunding",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6119",  "Saharanpur", "Mohd. Uvais", "NotGraduate",  " ","",  "", "", " "}, 
{ "Uttar Pradesh",  "6120",  "Saharanpur", "Imran Masood", "ForeignFunding",  " ","",  "", "", " "}, 
};

}