/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Uttarakhand {
public static final String[][] green_bucket = {
{"Uttarakhand",  "6084", "Almora", "Dropadi Verma", "Uttarakhand Kranti Dal (Democratic)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5170",  "उत्तराखण्ड",  "अल्मोड़ा", "द्रोपदी वर्मा", "उत्तराखंड क्रांति दल (लोकतांत्रिक)", ""}, 
{"Uttarakhand",  "6087", "Almora", "Vimla Arya", "UTTARAKHAND PARIVARTAN PARTY", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5169",  "उत्तराखण्ड",  "अल्मोड़ा", "विमला आर्य", "UTTARAKHAND पैरिवार्टन पार्टी", ""}, 
{"Uttarakhand",  "6088", "Almora", "Sunder Dhauni", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4913",  "उत्तराखण्ड",  "अल्मोड़ा", "सुंदर धौनी", "बहुजन समाज पार्टी", ""}, 
{"Uttarakhand",  "6074", "Garhwal", "Dr. Ramendra Singh Bhandari", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5431",  "उत्तराखण्ड",  "गढ़वाल", "डॉ। रामेंद्र सिंह भंडारी", "निर्दलीय", ""}, 
{"Uttarakhand",  "6097", "Haridwar", "Dharmendra", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7183",  "उत्तराखण्ड",  "हरिद्वार", "धर्मेंद्र", "निर्दलीय", ""}, 
{"Uttarakhand",  "6101", "Haridwar", "Narendra Chauhan", "Bhartiya Sarvodaya Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5451",  "उत्तराखण्ड",  "हरिद्वार", "नरेंद्र चौहान", "भारतीय सर्वोदय पार्टी", ""}, 
{"Uttarakhand",  "6103", "Haridwar", "Furkan Ali", "Pragatishil Samajwadi Party (Lohia)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5450",  "उत्तराखण्ड",  "हरिद्वार", "फुरकान अली", "प्रगति समाजवादी पार्टी (लोहिया)", ""}, 
{"Uttarakhand",  "6105", "Haridwar", "Dr. Antriksh Saini", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4914",  "उत्तराखण्ड",  "हरिद्वार", "डॉ। अंतीक्ष सैनी", "बहुजन समाज पार्टी", ""}, 
{"Uttarakhand",  "6107", "Haridwar", "Surendra Kumar Upadhayay", "Uttarakhand Kranti Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5841",  "उत्तराखण्ड",  "हरिद्वार", "सुरेन्द्र कुमार उपाध्याय", "उत्तराखंड क्रांति दल", ""}, 
{"Uttarakhand",  "6108", "Haridwar", "Lalit Kumar", "Peoples Party of India (Democratic)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5842",  "उत्तराखण्ड",  "हरिद्वार", "ललित कुमार", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", ""}, 
{"Uttarakhand",  "6109", "Haridwar", "Reenu", "Hindusthan Nirman Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7182",  "उत्तराखण्ड",  "हरिद्वार", "Reenu", "हिंदुस्तान निर्माण दल", ""}, 
{"Uttarakhand",  "6421", "Nainital UdhamSingh Nagar", "Navneet Agarwal", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4999",  "उत्तराखण्ड",  "नैनीताल-उधमसिंह नगर", "नवनीत अग्रवाल", "बहुजन समाज पार्टी", ""}, 
{"Uttarakhand",  "6423", "Nainital UdhamSingh Nagar", "Kailash Pandey", "Communist Party of India (Marxist–Leninist) Liberation", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4997",  "उत्तराखण्ड",  "नैनीताल-उधमसिंह नगर", "कैलाश पांडे", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) मुक्ति", ""}, 
{"Uttarakhand",  "6092", "Nainital-UdhamSingh Nagar", "Kailash Pandey", "Communist Party of India (Marxist–Leninist) Liberation", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4997",  "उत्तराखण्ड",  "नैनीताल-उधमसिंह नगर", "कैलाश पांडे", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) मुक्ति", ""}, 
{"Uttarakhand",  "6093", "Nainital-UdhamSingh Nagar", "Navneet Agarwal", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4999",  "उत्तराखण्ड",  "नैनीताल-उधमसिंह नगर", "नवनीत अग्रवाल", "बहुजन समाज पार्टी", ""}, 
{"Uttarakhand",  "6060", "Tehri Garhwal", "Gopal Mani", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4994",  "उत्तराखण्ड",  "टिहरी गढ़वाल", "गोपाल मणि", "निर्दलीय", ""}, 
{"Uttarakhand",  "6068", "Tehri Garhwal", "Rajendra Purohit", "Communist Party of India (Marxist)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4995",  "उत्तराखण्ड",  "टिहरी गढ़वाल", "राजेंद्र पुरोहित", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)", ""}, 
{"Uttarakhand",  "6069", "Tehri Garhwal", "Sanjay Kundaliya", "Uttarakhand Pragatisheel Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5423",  "उत्तराखण्ड",  "टिहरी गढ़वाल", "संजय कुंडलिया", "उत्तराखंड प्रगतिशील पार्टी", ""}, 
{"Uttarakhand",  "6071", "Tehri Garhwal", "Brij Bhushan Karanwal", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5829",  "उत्तराखण्ड",  "टिहरी गढ़वाल", "बृज भूषण करनवाल", "निर्दलीय", ""}, 
{"Uttarakhand",  "6073", "Tehri Garhwal", "Barhm Dev Jha", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5424",  "उत्तराखण्ड",  "टिहरी गढ़वाल", "बरहम देव झा", "निर्दलीय", ""}, 
};

public static final String[][] red_bucket = {
{ "Uttarakhand",  "6083",  "Almora", "K.L. Arya", "NotGraduate",  " ","उत्तराखण्ड",  "अल्मोड़ा", "केएल आर्य", " "}, 
{ "Uttarakhand",  "6085",  "Almora", "Pradeep Tamta", "ForeignFunding",  " ","उत्तराखण्ड",  "अल्मोड़ा", "प्रदीप टम्टा", " "}, 
{ "Uttarakhand",  "6086",  "Almora", "Ajay Tamta", "ForeignFunding",  " ","उत्तराखण्ड",  "अल्मोड़ा", "अजय टम्टा", " "}, 
{ "Uttarakhand",  "6075",  "Garhwal", "Anandmani Dutt Joshi", "NotGraduate",  " ","उत्तराखण्ड",  "गढ़वाल", "आनंदमणि दत्त जोशी", " "}, 
{ "Uttarakhand",  "6076",  "Garhwal", "Dr. Mukesh Semwal", "CriminalCases",  " ","उत्तराखण्ड",  "गढ़वाल", "डॉ। मुकेश सेमवाल", " "}, 
{ "Uttarakhand",  "6077",  "Garhwal", "Shanti Prasad Bhatt", "CriminalCases",  " ","उत्तराखण्ड",  "गढ़वाल", "शांति प्रसाद भट्ट", " "}, 
{ "Uttarakhand",  "6078",  "Garhwal", "Dilendrr Pal Singh", "NotGraduate",  " ","उत्तराखण्ड",  "गढ़वाल", "दिलेंद्र पाल सिंह", " "}, 
{ "Uttarakhand",  "6079",  "Garhwal", "Tirath Singh Rawat", "ForeignFunding",  " ","उत्तराखण्ड",  "गढ़वाल", "तीरथ सिंह रावत", " "}, 
{ "Uttarakhand",  "6080",  "Garhwal", "Bhagwat Prasad", "NotGraduate",  " ","उत्तराखण्ड",  "गढ़वाल", "भागवत प्रसाद", " "}, 
{ "Uttarakhand",  "6081",  "Garhwal", "Manish Khanduri", "ForeignFunding",  " ","उत्तराखण्ड",  "गढ़वाल", "मनीष खंडूरी", " "}, 
{ "Uttarakhand",  "6082",  "Garhwal", "Vinod Prasad Notiyal", "NotGraduate",  " ","उत्तराखण्ड",  "गढ़वाल", "विनोद प्रसाद नोटियाल", " "}, 
{ "Uttarakhand",  "6096",  "Haridwar", "Ramesh Pokhriyal Nishank", "ForeignFunding",  " ","उत्तराखण्ड",  "हरिद्वार", "रमेश पोखरियाल निशंक", " "}, 
{ "Uttarakhand",  "6098",  "Haridwar", "Aadil", "NotGraduate",  " ","उत्तराखण्ड",  "हरिद्वार", "आदिल", " "}, 
{ "Uttarakhand",  "6099",  "Haridwar", "Tribirendra Singh Rawat", "NotGraduate",  " ","उत्तराखण्ड",  "हरिद्वार", "त्रिवेंद्र सिंह रावत", " "}, 
{ "Uttarakhand",  "6100",  "Haridwar", "Shishupal Singh", "NotGraduate",  " ","उत्तराखण्ड",  "हरिद्वार", "शिशुपाल सिंह", " "}, 
{ "Uttarakhand",  "6102",  "Haridwar", "Ambrish Kumar", "ForeignFunding",  " ","उत्तराखण्ड",  "हरिद्वार", "अंबरीश कुमार", " "}, 
{ "Uttarakhand",  "6104",  "Haridwar", "Bhanpal Singh", "OverAged",  " ","उत्तराखण्ड",  "हरिद्वार", "भानपाल सिंह", " "}, 
{ "Uttarakhand",  "6106",  "Haridwar", "Bachi Singh", "NotGraduate",  " ","उत्तराखण्ड",  "हरिद्वार", "बच्ची सिंह", " "}, 
{ "Uttarakhand",  "6422",  "Nainital UdhamSingh Nagar", "Prem Prasad Arya", "OverAged",  " ","उत्तराखण्ड",  "नैनीताल-उधमसिंह नगर", "प्रेम प्रसाद आर्य", " "}, 
{ "Uttarakhand",  "6424",  "Nainital UdhamSingh Nagar", "Jyoti Prakash Tamta", "OverAged",  " ","उत्तराखण्ड",  "नैनीताल-उधमसिंह नगर", "ज्योति प्रकाश टम्टा", " "}, 
{ "Uttarakhand",  "6425",  "Nainital UdhamSingh Nagar", "Ajay Bhatt", "ForeignFunding",  " ","उत्तराखण्ड",  "नैनीताल-उधमसिंह नगर", "अजय भट्ट", " "}, 
{ "Uttarakhand",  "6426",  "Nainital UdhamSingh Nagar", "Harish Rawat", "ForeignFunding",  " ","उत्तराखण्ड",  "नैनीताल-उधमसिंह नगर", "हरीश रावत", " "}, 
{ "Uttarakhand",  "6427",  "Nainital UdhamSingh Nagar", "Sukumar Vishwash", "OverAged",  " ","उत्तराखण्ड",  "नैनीताल-उधमसिंह नगर", "सुकुमार विश्वाश", " "}, 
{ "Uttarakhand",  "6089",  "Nainital-UdhamSingh Nagar", "Harish Rawat", "ForeignFunding",  " ","उत्तराखण्ड",  "नैनीताल-उधमसिंह नगर", "हरीश रावत", " "}, 
{ "Uttarakhand",  "6090",  "Nainital-UdhamSingh Nagar", "Sukumar Vishwash", "OverAged",  " ","उत्तराखण्ड",  "नैनीताल-उधमसिंह नगर", "सुकुमार विश्वाश", " "}, 
{ "Uttarakhand",  "6091",  "Nainital-UdhamSingh Nagar", "Prem Prasad Arya", "OverAged",  " ","उत्तराखण्ड",  "नैनीताल-उधमसिंह नगर", "प्रेम प्रसाद आर्य", " "}, 
{ "Uttarakhand",  "6094",  "Nainital-UdhamSingh Nagar", "Jyoti Prakash Tamta", "OverAged",  " ","उत्तराखण्ड",  "नैनीताल-उधमसिंह नगर", "ज्योति प्रकाश टम्टा", " "}, 
{ "Uttarakhand",  "6095",  "Nainital-UdhamSingh Nagar", "Ajay Bhatt", "ForeignFunding",  " ","उत्तराखण्ड",  "नैनीताल-उधमसिंह नगर", "अजय भट्ट", " "}, 
{ "Uttarakhand",  "6059",  "Tehri Garhwal", "Sardar Khan", "NotGraduate",  " ","उत्तराखण्ड",  "टिहरी गढ़वाल", "सरदार खान", " "}, 
{ "Uttarakhand",  "6061",  "Tehri Garhwal", "Jay Prakash Upadhyay", "CriminalCases",  " ","उत्तराखण्ड",  "टिहरी गढ़वाल", "जय प्रकाश उपाध्याय", " "}, 
{ "Uttarakhand",  "6062",  "Tehri Garhwal", "Mala Rajya Laxmi Shah", "ForeignFunding",  " ","उत्तराखण्ड",  "टिहरी गढ़वाल", "माला राज्य लक्ष्मी शाह", " "}, 
{ "Uttarakhand",  "6063",  "Tehri Garhwal", "Daulat Kunwar", "NotGraduate",  " ","उत्तराखण्ड",  "टिहरी गढ़वाल", "दौलत कुंवर", " "}, 
{ "Uttarakhand",  "6064",  "Tehri Garhwal", "Madhu Shah", "NotGraduate",  " ","उत्तराखण्ड",  "टिहरी गढ़वाल", "मधु शाह", " "}, 
{ "Uttarakhand",  "6065",  "Tehri Garhwal", "Sanjay Goyal", "NotGraduate",  " ","उत्तराखण्ड",  "टिहरी गढ़वाल", "संजय गोयल", " "}, 
{ "Uttarakhand",  "6066",  "Tehri Garhwal", "Anu Pant", "CriminalCases",  " ","उत्तराखण्ड",  "टिहरी गढ़वाल", "अनु पंत", " "}, 
{ "Uttarakhand",  "6067",  "Tehri Garhwal", "Satyapal", "CriminalCases",  " ","उत्तराखण्ड",  "टिहरी गढ़वाल", "सत्यपाल", " "}, 
{ "Uttarakhand",  "6070",  "Tehri Garhwal", "Gautam Singh Bisht", "NotGraduate",  " ","उत्तराखण्ड",  "टिहरी गढ़वाल", "गौतम सिंह बिष्ट", " "}, 
{ "Uttarakhand",  "6072",  "Tehri Garhwal", "Pritam Singh", "ForeignFunding",  " ","उत्तराखण्ड",  "टिहरी गढ़वाल", "प्रीतम सिंह", " "}, 
};

}