/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Uttarakhand {
public static final String[][] green_bucket = {
        {"Uttarakhand", "Almora", "Dropadi Verma", "Uttarakhand Kranti Dal (Democratic)", "2.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5170", "उत्तराखण्ड", "अल्मोड़ा", "द्रोपदी वर्मा", "उत्तराखंड क्रांति दल (लोकतांत्रिक)"},
        {"Uttarakhand", "Almora", "Vimla Arya", "UTTARAKHAND PARIVARTAN PARTY", "1.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5169", "उत्तराखण्ड", "अल्मोड़ा", "विमला आर्य", "UTTARAKHAND पैरिवार्टन पार्टी"},
        {"Uttarakhand", "Almora", "Sunder Dhauni", "Bahujan Samaj Party", "28.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4913", "उत्तराखण्ड", "अल्मोड़ा", "सुंदर धौनी", "बहुजन समाज पार्टी"},
        {"Uttarakhand", "Garhwal", "Dr. Ramendra Singh Bhandari", "Independent", "6.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5431", "उत्तराखण्ड", "गढ़वाल", "डॉ। रामेंद्र सिंह भंडारी", "निर्दलीय"},
        {"Uttarakhand", "Haridwar", "Dharmendra", "Independent", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7183", "उत्तराखण्ड", "हरिद्वार", "धर्मेंद्र", "निर्दलीय"},
        {"Uttarakhand", "Haridwar", "Narendra Chauhan", "Bhartiya Sarvodaya Party", "28.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5451", "उत्तराखण्ड", "हरिद्वार", "नरेंद्र चौहान", "भारतीय सर्वोदय पार्टी"},
        {"Uttarakhand", "Haridwar", "Furkan Ali", "Pragatishil Samajwadi Party (Lohia)", "71.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5450", "उत्तराखण्ड", "हरिद्वार", "फुरकान अली", "प्रगति समाजवादी पार्टी (लोहिया)"},
        {"Uttarakhand", "Haridwar", "Dr. Antriksh Saini", "Bahujan Samaj Party", "86.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4914", "उत्तराखण्ड", "हरिद्वार", "डॉ। अंतीक्ष सैनी", "बहुजन समाज पार्टी"},
        {"Uttarakhand", "Haridwar", "Surendra Kumar Upadhayay", "Uttarakhand Kranti Dal", "42.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5841", "उत्तराखण्ड", "हरिद्वार", "सुरेन्द्र कुमार उपाध्याय", "उत्तराखंड क्रांति दल"},
        {"Uttarakhand", "Haridwar", "Lalit Kumar", "Peoples Party of India (Democratic)", "1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5842", "उत्तराखण्ड", "हरिद्वार", "ललित कुमार", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)"},
        {"Uttarakhand", "Haridwar", "Reenu", "Hindusthan Nirman Dal", "21.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7182", "उत्तराखण्ड", "हरिद्वार", "Reenu", "हिंदुस्तान निर्माण दल"},
        {"Uttarakhand", "Nainital UdhamSingh Nagar", "Navneet Agarwal", "Bahujan Samaj Party", "8.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4999", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "नवनीत अग्रवाल", "बहुजन समाज पार्टी"},
        {"Uttarakhand", "Nainital UdhamSingh Nagar", "Kailash Pandey", "Communist Party of India (Marxist–Leninist) Liberation", "12.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4997", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "कैलाश पांडे", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) मुक्ति"},
        {"Uttarakhand", "Nainital-UdhamSingh Nagar", "Kailash Pandey", "Communist Party of India (Marxist–Leninist) Liberation", "12.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4997", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "कैलाश पांडे", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) मुक्ति"},
        {"Uttarakhand", "Nainital-UdhamSingh Nagar", "Navneet Agarwal", "Bahujan Samaj Party", "8.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4999", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "नवनीत अग्रवाल", "बहुजन समाज पार्टी"},
        {"Uttarakhand", "Tehri Garhwal", "Gopal Mani", "Independent", "1.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4994", "उत्तराखण्ड", "टिहरी गढ़वाल", "गोपाल मणि", "निर्दलीय"},
        {"Uttarakhand", "Tehri Garhwal", "Rajendra Purohit", "Communist Party of India (Marxist)", "1.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4995", "उत्तराखण्ड", "टिहरी गढ़वाल", "राजेंद्र पुरोहित", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
        {"Uttarakhand", "Tehri Garhwal", "Sanjay Kundaliya", "Uttarakhand Pragatisheel Party", "12.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5423", "उत्तराखण्ड", "टिहरी गढ़वाल", "संजय कुंडलिया", "उत्तराखंड प्रगतिशील पार्टी"},
        {"Uttarakhand", "Tehri Garhwal", "Brij Bhushan Karanwal", "Independent", "3.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5829", "उत्तराखण्ड", "टिहरी गढ़वाल", "बृज भूषण करनवाल", "निर्दलीय"},
        {"Uttarakhand", "Tehri Garhwal", "Barhm Dev Jha", "Independent", "2.5Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5424", "उत्तराखण्ड", "टिहरी गढ़वाल", "बरहम देव झा", "निर्दलीय"},
};

public static final String[][] red_bucket = {
        {"Uttarakhand", "Almora", "K.L. Arya", "4", " ", "उत्तराखण्ड", "अल्मोड़ा", "केएल आर्य", " "},
        {"Uttarakhand", "Almora", "Pradeep Tamta", "1", " ", "उत्तराखण्ड", "अल्मोड़ा", "प्रदीप टम्टा", " "},
        {"Uttarakhand", "Almora", "Ajay Tamta", "1", " ", "उत्तराखण्ड", "अल्मोड़ा", "अजय टम्टा", " "},
        {"Uttarakhand", "Garhwal", "Anandmani Dutt Joshi", "4", " ", "उत्तराखण्ड", "गढ़वाल", "आनंदमणि दत्त जोशी", " "},
        {"Uttarakhand", "Garhwal", "Dr. Mukesh Semwal", "2", " ", "उत्तराखण्ड", "गढ़वाल", "डॉ। मुकेश सेमवाल", " "},
        {"Uttarakhand", "Garhwal", "Shanti Prasad Bhatt", "2", " ", "उत्तराखण्ड", "गढ़वाल", "शांति प्रसाद भट्ट", " "},
        {"Uttarakhand", "Garhwal", "Dilendrr Pal Singh", "4", " ", "उत्तराखण्ड", "गढ़वाल", "दिलेंद्र पाल सिंह", " "},
        {"Uttarakhand", "Garhwal", "Tirath Singh Rawat", "1", " ", "उत्तराखण्ड", "गढ़वाल", "तीरथ सिंह रावत", " "},
        {"Uttarakhand", "Garhwal", "Bhagwat Prasad", "4", " ", "उत्तराखण्ड", "गढ़वाल", "भागवत प्रसाद", " "},
        {"Uttarakhand", "Garhwal", "Manish Khanduri", "1", " ", "उत्तराखण्ड", "गढ़वाल", "मनीष खंडूरी", " "},
        {"Uttarakhand", "Garhwal", "Vinod Prasad Notiyal", "4", " ", "उत्तराखण्ड", "गढ़वाल", "विनोद प्रसाद नोटियाल", " "},
        {"Uttarakhand", "Haridwar", "Ramesh Pokhriyal Nishank", "1", " ", "उत्तराखण्ड", "हरिद्वार", "रमेश पोखरियाल निशंक", " "},
        {"Uttarakhand", "Haridwar", "Aadil", "4", " ", "उत्तराखण्ड", "हरिद्वार", "आदिल", " "},
        {"Uttarakhand", "Haridwar", "Tribirendra Singh Rawat", "4", " ", "उत्तराखण्ड", "हरिद्वार", "त्रिवेंद्र सिंह रावत", " "},
        {"Uttarakhand", "Haridwar", "Shishupal Singh", "4", " ", "उत्तराखण्ड", "हरिद्वार", "शिशुपाल सिंह", " "},
        {"Uttarakhand", "Haridwar", "Ambrish Kumar", "1", " ", "उत्तराखण्ड", "हरिद्वार", "अंबरीश कुमार", " "},
        {"Uttarakhand", "Haridwar", "Bhanpal Singh", "3", " ", "उत्तराखण्ड", "हरिद्वार", "भानपाल सिंह", " "},
        {"Uttarakhand", "Haridwar", "Bachi Singh", "4", " ", "उत्तराखण्ड", "हरिद्वार", "बच्ची सिंह", " "},
        {"Uttarakhand", "Nainital UdhamSingh Nagar", "Prem Prasad Arya", "3", " ", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "प्रेम प्रसाद आर्य", " "},
        {"Uttarakhand", "Nainital UdhamSingh Nagar", "Jyoti Prakash Tamta", "3", " ", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "ज्योति प्रकाश टम्टा", " "},
        {"Uttarakhand", "Nainital UdhamSingh Nagar", "Ajay Bhatt", "1", " ", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "अजय भट्ट", " "},
        {"Uttarakhand", "Nainital UdhamSingh Nagar", "Harish Rawat", "1", " ", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "हरीश रावत", " "},
        {"Uttarakhand", "Nainital UdhamSingh Nagar", "Sukumar Vishwash", "3", " ", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "सुकुमार विश्वाश", " "},
        {"Uttarakhand", "Nainital-UdhamSingh Nagar", "Harish Rawat", "1", " ", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "हरीश रावत", " "},
        {"Uttarakhand", "Nainital-UdhamSingh Nagar", "Sukumar Vishwash", "3", " ", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "सुकुमार विश्वाश", " "},
        {"Uttarakhand", "Nainital-UdhamSingh Nagar", "Prem Prasad Arya", "3", " ", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "प्रेम प्रसाद आर्य", " "},
        {"Uttarakhand", "Nainital-UdhamSingh Nagar", "Jyoti Prakash Tamta", "3", " ", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "ज्योति प्रकाश टम्टा", " "},
        {"Uttarakhand", "Nainital-UdhamSingh Nagar", "Ajay Bhatt", "1", " ", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "अजय भट्ट", " "},
        {"Uttarakhand", "Tehri Garhwal", "Sardar Khan", "4", " ", "उत्तराखण्ड", "टिहरी गढ़वाल", "सरदार खान", " "},
        {"Uttarakhand", "Tehri Garhwal", "Jay Prakash Upadhyay", "2", " ", "उत्तराखण्ड", "टिहरी गढ़वाल", "जय प्रकाश उपाध्याय", " "},
        {"Uttarakhand", "Tehri Garhwal", "Mala Rajya Laxmi Shah", "1", " ", "उत्तराखण्ड", "टिहरी गढ़वाल", "माला राज्य लक्ष्मी शाह", " "},
        {"Uttarakhand", "Tehri Garhwal", "Daulat Kunwar", "4", " ", "उत्तराखण्ड", "टिहरी गढ़वाल", "दौलत कुंवर", " "},
        {"Uttarakhand", "Tehri Garhwal", "Madhu Shah", "4", " ", "उत्तराखण्ड", "टिहरी गढ़वाल", "मधु शाह", " "},
        {"Uttarakhand", "Tehri Garhwal", "Sanjay Goyal", "4", " ", "उत्तराखण्ड", "टिहरी गढ़वाल", "संजय गोयल", " "},
        {"Uttarakhand", "Tehri Garhwal", "Anu Pant", "2", " ", "उत्तराखण्ड", "टिहरी गढ़वाल", "अनु पंत", " "},
        {"Uttarakhand", "Tehri Garhwal", "Satyapal", "2", " ", "उत्तराखण्ड", "टिहरी गढ़वाल", "सत्यपाल", " "},
        {"Uttarakhand", "Tehri Garhwal", "Gautam Singh Bisht", "4", " ", "उत्तराखण्ड", "टिहरी गढ़वाल", "गौतम सिंह बिष्ट", " "},
        {"Uttarakhand", "Tehri Garhwal", "Pritam Singh", "1", " ", "उत्तराखण्ड", "टिहरी गढ़वाल", "प्रीतम सिंह", " "},
};

}