/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class Uttar_Pradesh {
public static final String[][] green_bucket = {
{"Uttar Pradesh",  "6270", "Agra", "Manoj Kumar Soni", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5519",  "उत्तर प्रदेश",  "आगरा", "मनोज कुमार सोनी", "बहुजन समाज पार्टी", ""}, 
{"Uttar Pradesh",  "6271", "Agra", "Babu Lal", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7133",  "उत्तर प्रदेश",  "आगरा", "बाबू लाल", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6272", "Agra", "Himanshi", "Lok Gathbandhan Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7134",  "उत्तर प्रदेश",  "आगरा", "हिमांशी", "लोक गठबंधन पार्टी", ""}, 
{"Uttar Pradesh",  "6237", "Aligarh", "Ajeet Kumar", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5508",  "उत्तर प्रदेश",  "अलीगढ़", "अजीत कुमार", "बहुजन समाज पार्टी", ""}, 
{"Uttar Pradesh",  "6242", "Aligarh", "Amar Singh Mahaur", "Swatantra Jantaraj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7110",  "उत्तर प्रदेश",  "अलीगढ़", "अमर सिंह माहौर", "स्वंतत्र जनराज पार्टी", ""}, 
{"Uttar Pradesh",  "6243", "Aligarh", "Dileep Sharma", "Peace Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7114",  "उत्तर प्रदेश",  "अलीगढ़", "दिलीप शर्मा", "पीस पार्टी", ""}, 
{"Uttar Pradesh",  "6165", "Amroha", "Naresh Kumar", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6127",  "उत्तर प्रदेश",  "अमरोहा", "नरेश कुमार", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6170", "Amroha", "Kunwar Danish Ali", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5501",  "उत्तर प्रदेश",  "अमरोहा", "कुंवर दानिश अली", "बहुजन समाज पार्टी", ""}, 
{"Uttar Pradesh",  "6172", "Amroha", "Rajpal Singh Saini", "Jan Shakti Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6124",  "उत्तर प्रदेश",  "अमरोहा", "राजपाल सिंह सैनी", "जन शक्ति दल", ""}, 
{"Uttar Pradesh",  "7783", "Aonla", "Hemendra Pal Singh", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8307",  "उत्तर प्रदेश",  "आंवला", "हेमेंद्र पाल सिंह", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "7785", "Aonla", "Mohd Ateeq", "National Fifty Fifty Front", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7400",  "उत्तर प्रदेश",  "आंवला", "मोहम्मद अतीक", "", ""}, 
{"Uttar Pradesh",  "7786", "Aonla", "Irshad Ali Ansari", "VANCHITSAMAJ INSAAF PARTY", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8310",  "उत्तर प्रदेश",  "आंवला", "इरशाद अली अंसारी", "VANCHITSAMAJ INSAAF PARTY", ""}, 
{"Uttar Pradesh",  "7790", "Aonla", "Dharmendra", "Shiv Sena", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11159",  "उत्तर प्रदेश",  "आंवला", "धर्मेंद्र", "शिवसेना", ""}, 
{"Uttar Pradesh",  "7793", "Aonla", "Pramod Kumar Yadav", "Bhartiya Krishak Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8303",  "उत्तर प्रदेश",  "आंवला", "प्रमोद कुमार यादव", "", ""}, 
{"Uttar Pradesh",  "7777", "Badaun", "Atul Kumar", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9529",  "उत्तर प्रदेश",  "बदायूं", "अतुल कुमार", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "7778", "Badaun", "Kailash Kumar Mishra", "All India Forward Bloc", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9528",  "उत्तर प्रदेश",  "बदायूं", "कैलाश कुमार मिश्रा", "ऑल इंडिया फॉरवर्ड ब्लॉक", ""}, 
{"Uttar Pradesh",  "6185", "Baghpat", "Jayant Chaudhary", "Rashtriya Lok Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5469",  "उत्तर प्रदेश",  "बागपत", "जयंत चौधरी", "राष्ट्रीय लोकदल", ""}, 
{"Uttar Pradesh",  "6190", "Baghpat", "Ruby Kashyap", "Hindusthan Nirman Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6151",  "उत्तर प्रदेश",  "बागपत", "रूबी कश्यप", "हिंदुस्तान निर्माण दल", ""}, 
{"Uttar Pradesh",  "7797", "Bareilly", "Nitin Mohan", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7407",  "उत्तर प्रदेश",  "बरेली", "नितिन मोहन", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "7799", "Bareilly", "Usha Agarwal", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8320",  "उत्तर प्रदेश",  "बरेली", "उषा अग्रवाल", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "7800", "Bareilly", "Saman Tahir", "Pragatishil Samajwadi Party (Lohia)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7409",  "उत्तर प्रदेश",  "बरेली", "समन ताहिर", "प्रगति समाजवादी पार्टी (लोहिया)", ""}, 
{"Uttar Pradesh",  "7805", "Bareilly", "Satish Kumar", "Communist Party of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8323",  "उत्तर प्रदेश",  "बरेली", "सतीश कुमार", "भारतीय कम्युनिस्ट पार्टी", ""}, 
{"Uttar Pradesh",  "7807", "Bareilly", "Syed Rashid Ali", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7408",  "उत्तर प्रदेश",  "बरेली", "सैयद राशिद अली", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "7811", "Bareilly", "Rakesh Agarwal Advocate", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7406",  "उत्तर प्रदेश",  "बरेली", "राकेश अग्रवाल एडवोकेट", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6152", "Bijnor", "Mahak Singh", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6114",  "उत्तर प्रदेश",  "बिजनौर", "महक सिंह", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6155", "Bijnor", "Parvej Aqil", "All India Minorities Front", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6109",  "उत्तर प्रदेश",  "बिजनौर", "परवेज अकील", "अखिल भारतीय अल्पसंख्यक मोर्चा", ""}, 
{"Uttar Pradesh",  "6156", "Bijnor", "Mohammad Zahid", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6107",  "उत्तर प्रदेश",  "बिजनौर", "मोहम्मद जाहिद", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6223", "Bulandshahr", "Vinay Kumar", "Aapki Apni Party (Peoples)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5503",  "उत्तर प्रदेश",  "बुलंदशहर", "विनय कुमार", "अपना दल (पीपल्स)", ""}, 
{"Uttar Pradesh",  "6226", "Bulandshahr", "Pramod Kumar", "Rashtriya Samaj Paksha", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7106",  "उत्तर प्रदेश",  "बुलंदशहर", "प्रमोद कुमार", "राष्ट्रीय समाज पक्ष", ""}, 
{"Uttar Pradesh",  "6227", "Bulandshahr", "Radhika Devi", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7107",  "उत्तर प्रदेश",  "बुलंदशहर", "राधिका देवी", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6229", "Bulandshahr", "Manoj Kumar Singh", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7105",  "उत्तर प्रदेश",  "बुलंदशहर", "मनोज कुमार सिंह", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "7762", "Etah", "Parvati Nandan", "Rashtriya Bharatiya Jan Jan Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7415",  "उत्तर प्रदेश",  "एटा", "पार्वती नंदन", "राष्ट्रीय भारतीय जन पार्टी", ""}, 
{"Uttar Pradesh",  "7763", "Etah", "Atar Singh", "Rashtriya Shoshit Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7416",  "उत्तर प्रदेश",  "एटा", "अतर सिंह", "राष्ट्रीय शोषित समाज पार्टी", ""}, 
{"Uttar Pradesh",  "7764", "Etah", "Anand Prakash Singh Rajput", "Rashtriya Backward Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7900",  "उत्तर प्रदेश",  "एटा", "आनंद प्रकाश सिंह राजपूत", "", ""}, 
{"Uttar Pradesh",  "7765", "Etah", "Anuj Kumar", "Subhashwadi Bhartiya Samajwadi Party (Subhas", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7898",  "उत्तर प्रदेश",  "एटा", "अनुज कुमार", "", ""}, 
{"Uttar Pradesh",  "7770", "Etah", "Rashmi Yadav", "Pragatishil Samajwadi Party (Lohia)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9532",  "उत्तर प्रदेश",  "एटा", "रश्मि यादव", "प्रगति समाजवादी पार्टी (लोहिया)", ""}, 
{"Uttar Pradesh",  "6274", "Fatehpur Sikri", "Sarvesh Kumar", "Bharatiya Majdoor Janta Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7146",  "उत्तर प्रदेश",  "फतेहपुर सीकरी", "सर्वेश कुमार", "भारतीय मजदूर जनता पार्टी", ""}, 
{"Uttar Pradesh",  "6280", "Fatehpur Sikri", "Anil Kumar Kushwaha", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7137",  "उत्तर प्रदेश",  "फतेहपुर सीकरी", "अनिल कुमार कुशवाहा", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6281", "Fatehpur Sikri", "Purushottam Das (Fauzi Bhai)", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7143",  "उत्तर प्रदेश",  "फतेहपुर सीकरी", "पुरुषोत्तम दास (फौजी भाई)", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6287", "Fatehpur Sikri", "Satendar", "Aam Janta Party (India)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5527",  "उत्तर प्रदेश",  "फतेहपुर सीकरी", "Satendar", "आम जनता पार्टी (भारत)", ""}, 
{"Uttar Pradesh",  "7742", "Firozabad", "Shivpal Singh Yadav", "Pragatishil Samajwadi Party (Lohia)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7420",  "उत्तर प्रदेश",  "फिरोजाबाद", "शिवपाल सिंह यादव", "प्रगति समाजवादी पार्टी (लोहिया)", ""}, 
{"Uttar Pradesh",  "7746", "Firozabad", "Upendra Singh Rajput", "Bharatiya Kisan Parivartan Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7421",  "उत्तर प्रदेश",  "फिरोजाबाद", "उपेंद्र सिंह राजपूत", "", ""}, 
{"Uttar Pradesh",  "7747", "Firozabad", "Akshay Yadav", "Samajwadi Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7419",  "उत्तर प्रदेश",  "फिरोजाबाद", "अक्षय यादव", "समाजवादी पार्टी", ""}, 
{"Uttar Pradesh",  "6210", "Gautam Buddha Nagar", "Rampal", "Rashtriya Samaj Paksha", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6167",  "उत्तर प्रदेश",  "गौतम बुद्ध नगर", "रामपाल", "राष्ट्रीय समाज पक्ष", ""}, 
{"Uttar Pradesh",  "6211", "Gautam Buddha Nagar", "Jagdeep Singh", "Loktantrik Janshakti Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6168",  "उत्तर प्रदेश",  "गौतम बुद्ध नगर", "जगदीप सिंह", "लोकतान्त्रिक जनशक्ति पार्टी", ""}, 
{"Uttar Pradesh",  "6212", "Gautam Buddha Nagar", "Rodash Gupta", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6169",  "उत्तर प्रदेश",  "गौतम बुद्ध नगर", "रोडश गुप्ता", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6214", "Gautam Buddha Nagar", "Raghuvendra Kumar", "Subhashwadi Bhartiya Samajwadi Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6333",  "उत्तर प्रदेश",  "गौतम बुद्ध नगर", "रघुवेंद्र कुमार", "सुभाषवादी भारतीय समाजवादी पार्टी", ""}, 
{"Uttar Pradesh",  "6198", "Ghaziabad", "Mohan Lal", "Republican Party of India (Athawale)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6160",  "उत्तर प्रदेश",  "गाज़ियाबाद", "मोहन लाल", "भारतीय रिपब्लिकन पार्टी (अठावले)", ""}, 
{"Uttar Pradesh",  "6199", "Ghaziabad", "Ashok Sharma", "Subhashwadi Bhartiya Samajwadi Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4947",  "उत्तर प्रदेश",  "गाज़ियाबाद", "अशोक शर्मा", "सुभाषवादी भारतीय समाजवादी पार्टी", ""}, 
{"Uttar Pradesh",  "6202", "Ghaziabad", "Rakesh Suri", "Right to Recall Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4945",  "उत्तर प्रदेश",  "गाज़ियाबाद", "राकेश सूरी", "राइट टू रिकॉल पार्टी", ""}, 
{"Uttar Pradesh",  "6206", "Ghaziabad", "Nagendra Kumar", "Shiv Sena", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6162",  "उत्तर प्रदेश",  "गाज़ियाबाद", "नागेंद्र कुमार", "शिवसेना", ""}, 
{"Uttar Pradesh",  "6245", "Hathras", "Dinesh Sai", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5518",  "उत्तर प्रदेश",  "हाथरस", "दिनेश साय", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6133", "Kairana", "Mohd Gufran Kazmi", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5460",  "उत्तर प्रदेश",  "कैराना", "मोहम्मद गुफरान काजमी", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "7748", "Mainpuri", "Kuldeep Kumar", "Bhartiya Kisan Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8354",  "उत्तर प्रदेश",  "मैनपुरी", "कुलदीप कुमार", "भारतीय किसान पार्टी", ""}, 
{"Uttar Pradesh",  "7752", "Mainpuri", "Shyam Singh", "Swatantra Jantaraj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8347",  "उत्तर प्रदेश",  "मैनपुरी", "श्याम सिंह", "स्वंतत्र जनराज पार्टी", ""}, 
{"Uttar Pradesh",  "7753", "Mainpuri", "Ravindra Singh Katar", "Bhartiya Navodaya Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8346",  "उत्तर प्रदेश",  "मैनपुरी", "रविन्द्र सिंह कटार", "", ""}, 
{"Uttar Pradesh",  "7755", "Mainpuri", "Ravindra Singh Yadav", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11162",  "उत्तर प्रदेश",  "मैनपुरी", "रविन्द्र सिंह यादव", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "7757", "Mainpuri", "Savendra Singh", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8349",  "उत्तर प्रदेश",  "मैनपुरी", "सवेंद्र सिंह", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6258", "Mathura", "Omprakash", "Swatantra Jantaraj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7128",  "उत्तर प्रदेश",  "मथुरा", "ओमप्रकाश", "स्वंतत्र जनराज पार्टी", ""}, 
{"Uttar Pradesh",  "6260", "Mathura", "Dinesh Kumar Gautam", "Bhartiya Anarakshit Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5489",  "उत्तर प्रदेश",  "मथुरा", "दिनेश कुमार गौतम", "भारतीय अनारक्षित पार्टी", ""}, 
{"Uttar Pradesh",  "6177", "Meerut", "Sahansar Pal Singh", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6142",  "उत्तर प्रदेश",  "मेरठ", "सहंसर पाल सिंह", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6181", "Meerut", "Arti Agrawal", "Shiv Sena", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6137",  "उत्तर प्रदेश",  "मेरठ", "आरती अग्रवाल", "शिवसेना", ""}, 
{"Uttar Pradesh",  "6184", "Meerut", "Dharmendra", "BHARTIYA JANTA DAL", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6141",  "उत्तर प्रदेश",  "मेरठ", "धर्मेंद्र", "भर्तृ य जनत दल", ""}, 
{"Uttar Pradesh",  "7708", "Moradabad", "Musaraat Hussain", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8363",  "उत्तर प्रदेश",  "मुरादाबाद", "मुसरत हुसैन", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "7715", "Moradabad", "Dr. S T Hasan", "Samajwadi Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8357",  "उत्तर प्रदेश",  "मुरादाबाद", "डॉ। एसटी हसन", "समाजवादी पार्टी", ""}, 
{"Uttar Pradesh",  "7718", "Moradabad", "Prince Kumar Sharma", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8358",  "उत्तर प्रदेश",  "मुरादाबाद", "प्रिंस कुमार शर्मा", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6135", "Muzaffarnagar", "Ankit", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6103",  "उत्तर प्रदेश",  "मुजफ्फरनगर", "अंकित", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6140", "Muzaffarnagar", "Mangeram Kashyap", "Majdoor Kisan Union Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6099",  "उत्तर प्रदेश",  "मुजफ्फरनगर", "मांगेराम कश्यप", "मज़दूर किसान यूनियन पार्टी", ""}, 
{"Uttar Pradesh",  "6142", "Muzaffarnagar", "S.S.K.S. Gangwal", "Bharatiya Bahujan Samta Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6098",  "उत्तर प्रदेश",  "मुजफ्फरनगर", "SSKS गंगवाल", "भारतीय बहुजन समता पार्टी", ""}, 
{"Uttar Pradesh",  "6143", "Muzaffarnagar", "Neel Kumar", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6100",  "उत्तर प्रदेश",  "मुजफ्फरनगर", "नील कुमार", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "6157", "Nagina", "Kamesh Kumar", "Peoples Party of India (Democratic)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5493",  "उत्तर प्रदेश",  "नगीना", "कामेश कुमार", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", ""}, 
{"Uttar Pradesh",  "6161", "Nagina", "Charan Singh", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6119",  "उत्तर प्रदेश",  "नगीना", "चरण सिंह", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "7813", "Pilibhit", "Dr. Sita Ram Rajput", "Sabka Dal United", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8371",  "उत्तर प्रदेश",  "पीलीभीत", "डॉ। सीता राम राजपूत", "", ""}, 
{"Uttar Pradesh",  "7816", "Pilibhit", "Varun Gandhi", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9545",  "उत्तर प्रदेश",  "पीलीभीत", "वरुण गांधी", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "7818", "Pilibhit", "Dr. Bharat", "Janata Dal (United)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8369",  "उत्तर प्रदेश",  "पीलीभीत", "डॉ। भारत", "जनता दल (यूनाइटेड)", ""}, 
{"Uttar Pradesh",  "7819", "Pilibhit", "Urvashi Singh", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9546",  "उत्तर प्रदेश",  "पीलीभीत", "उर्वशी सिंह", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "7823", "Pilibhit", "Kaif Raza Khan", "Independent", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9548",  "उत्तर प्रदेश",  "पीलीभीत", "कैफ रजा खान", "निर्दलीय", ""}, 
{"Uttar Pradesh",  "7725", "Rampur", "Saroj", "Peoples Party of India (Democratic)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9553",  "उत्तर प्रदेश",  "रामपुर", "सरोज", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", ""}, 
{"Uttar Pradesh",  "7729", "Rampur", "Ishrat Khan", "All India Minorities Front", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8373",  "उत्तर प्रदेश",  "रामपुर", "इशरत खान", "अखिल भारतीय अल्पसंख्यक मोर्चा", ""}, 
{"Uttar Pradesh",  "6115", "Saharanpur", "Ravindra Kumar", "Inqalab Vikas Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6080",  "उत्तर प्रदेश",  "सहारनपुर", "रविन्द्र कुमार", "इंकलाब विकास दल", ""}, 
{"Uttar Pradesh",  "6117", "Saharanpur", "Brijpal Singh", "Hindusthan Nirman Dal", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6079",  "उत्तर प्रदेश",  "सहारनपुर", "बृजपाल सिंह", "हिंदुस्तान निर्माण दल", ""}, 
{"Uttar Pradesh",  "6118", "Saharanpur", "Haji Fazlur Rehman", "Bahujan Samaj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=6076",  "उत्तर प्रदेश",  "सहारनपुर", "हाजी फजलुर रहमान", "बहुजन समाज पार्टी", ""}, 
{"Uttar Pradesh",  "7733", "Sambhal", "Ram Chandra", "Bharat Prabhat Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7920",  "उत्तर प्रदेश",  "संभल", "राम चंद्र", "", ""}, 
{"Uttar Pradesh",  "7737", "Sambhal", "Hasan Raza", "Rashtriya Ulama Council", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9560",  "उत्तर प्रदेश",  "संभल", "हसन रज़ा", "राष्ट्रीय उलमा परिषद", ""}, 
{"Uttar Pradesh",  "7738", "Sambhal", "Bhoj Raj", "Swatantra Jantaraj Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8377",  "उत्तर प्रदेश",  "संभल", "भोज राज", "स्वंतत्र जनराज पार्टी", ""}, 
};

public static final String[][] red_bucket = {
{ "Uttar Pradesh",  "6266",  "Agra", "Ramji Lal Vidhyarthi", "CriminalCases",  " ","उत्तर प्रदेश",  "आगरा", "रामजी लाल विद्यार्थी", " "}, 
{ "Uttar Pradesh",  "6267",  "Agra", "Ambedkari Hasnuram Ambedkari", "CriminalCases",  " ","उत्तर प्रदेश",  "आगरा", "अम्बेडकर हसनूराम अम्बेडकर", " "}, 
{ "Uttar Pradesh",  "6268",  "Agra", "Preeta Harit", "ForeignFunding",  " ","उत्तर प्रदेश",  "आगरा", "प्रीता हरित", " "}, 
{ "Uttar Pradesh",  "6269",  "Agra", "Satyapal Singh Baghel", "ForeignFunding",  " ","उत्तर प्रदेश",  "आगरा", "सत्यपाल सिंह बघेल", " "}, 
{ "Uttar Pradesh",  "6273",  "Agra", "Raja", "NotGraduate",  " ","उत्तर प्रदेश",  "आगरा", "राजा", " "}, 
{ "Uttar Pradesh",  "6232",  "Aligarh", "Shaheen", "NotGraduate",  " ","उत्तर प्रदेश",  "अलीगढ़", "शाहीन", " "}, 
{ "Uttar Pradesh",  "6233",  "Aligarh", "Sanjay Balmiki", "NotGraduate",  " ","उत्तर प्रदेश",  "अलीगढ़", "संजय बाल्मीकि", " "}, 
{ "Uttar Pradesh",  "6234",  "Aligarh", "Thakur Manoj Singh", "NotGraduate",  " ","उत्तर प्रदेश",  "अलीगढ़", "ठाकुर मनोज सिंह", " "}, 
{ "Uttar Pradesh",  "6235",  "Aligarh", "Charan Singh", "NotGraduate",  " ","उत्तर प्रदेश",  "अलीगढ़", "चरण सिंह", " "}, 
{ "Uttar Pradesh",  "6236",  "Aligarh", "Mohd. Shakeel (Adv.)", "CriminalCases",  " ","उत्तर प्रदेश",  "अलीगढ़", "मोहम्मद। शकील (सलाहकार)", " "}, 
{ "Uttar Pradesh",  "6238",  "Aligarh", "Satish Kumar Gautam", "ForeignFunding",  " ","उत्तर प्रदेश",  "अलीगढ़", "सतीश कुमार गौतम", " "}, 
{ "Uttar Pradesh",  "6239",  "Aligarh", "Bijendra Singh", "ForeignFunding",  " ","उत्तर प्रदेश",  "अलीगढ़", "बिजेंद्र सिंह", " "}, 
{ "Uttar Pradesh",  "6240",  "Aligarh", "Satish Chandra Sharma", "NotGraduate",  " ","उत्तर प्रदेश",  "अलीगढ़", "सतीश चंद्र शर्मा", " "}, 
{ "Uttar Pradesh",  "6241",  "Aligarh", "Deepak Chaudhary", "CriminalCases",  " ","उत्तर प्रदेश",  "अलीगढ़", "दीपक चौधरी", " "}, 
{ "Uttar Pradesh",  "6244",  "Aligarh", "Ashok Kumar Pandey", "CriminalCases",  " ","उत्तर प्रदेश",  "अलीगढ़", "अशोक कुमार पांडे", " "}, 
{ "Uttar Pradesh",  "6164",  "Amroha", "Vikar Ahmad", "NotGraduate",  " ","उत्तर प्रदेश",  "अमरोहा", "विकार अहमद", " "}, 
{ "Uttar Pradesh",  "6166",  "Amroha", "Akhtar", "NotGraduate",  " ","उत्तर प्रदेश",  "अमरोहा", "अख्तर", " "}, 
{ "Uttar Pradesh",  "6167",  "Amroha", "Rajpal Singh", "NotGraduate",  " ","उत्तर प्रदेश",  "अमरोहा", "राजपाल सिंह", " "}, 
{ "Uttar Pradesh",  "6168",  "Amroha", "Robin Tyagi", "NotGraduate",  " ","उत्तर प्रदेश",  "अमरोहा", "रॉबिन त्यागी", " "}, 
{ "Uttar Pradesh",  "6169",  "Amroha", "Matloob Ahmad", "CriminalCases",  " ","उत्तर प्रदेश",  "अमरोहा", "मतलूब अहमद", " "}, 
{ "Uttar Pradesh",  "6171",  "Amroha", "Sachin Choudhary", "ForeignFunding",  " ","उत्तर प्रदेश",  "अमरोहा", "सचिन चौधरी", " "}, 
{ "Uttar Pradesh",  "6173",  "Amroha", "Kanwar Singh Tanwar", "ForeignFunding",  " ","उत्तर प्रदेश",  "अमरोहा", "कंवर सिंह तंवर", " "}, 
{ "Uttar Pradesh",  "7784",  "Aonla", "Dinesh Kumar", "NotGraduate",  " ","उत्तर प्रदेश",  "आंवला", "दिनेश कुमार", " "}, 
{ "Uttar Pradesh",  "7787",  "Aonla", "Rishi Pal", "NotGraduate",  " ","उत्तर प्रदेश",  "आंवला", "ऋषि पाल", " "}, 
{ "Uttar Pradesh",  "7788",  "Aonla", "Priti Kashyap", "NotGraduate",  " ","उत्तर प्रदेश",  "आंवला", "प्रीति कश्यप", " "}, 
{ "Uttar Pradesh",  "7789",  "Aonla", "Lakshmi", "NotGraduate",  " ","उत्तर प्रदेश",  "आंवला", "लक्ष्मी", " "}, 
{ "Uttar Pradesh",  "7791",  "Aonla", "Dharmendra Kumar", "ForeignFunding",  " ","उत्तर प्रदेश",  "आंवला", "धर्मेंद्र कुमार", " "}, 
{ "Uttar Pradesh",  "7792",  "Aonla", "Sunil Kumar", "CriminalCases",  " ","उत्तर प्रदेश",  "आंवला", "सुनील कुमार", " "}, 
{ "Uttar Pradesh",  "7794",  "Aonla", "Ram Phal Shakya", "OverAged",  " ","उत्तर प्रदेश",  "आंवला", "राम फाल शाक्य", " "}, 
{ "Uttar Pradesh",  "7795",  "Aonla", "Ruchi Vira", "CriminalCases",  " ","उत्तर प्रदेश",  "आंवला", "रूचि विरा", " "}, 
{ "Uttar Pradesh",  "7796",  "Aonla", "Kunwar Sarvraj Singh", "ForeignFunding",  " ","उत्तर प्रदेश",  "आंवला", "कुंवर सर्वराज सिंह", " "}, 
{ "Uttar Pradesh",  "7774",  "Badaun", "Mahesh Shriwastav", "NotGraduate",  " ","उत्तर प्रदेश",  "बदायूं", "महेश श्रीवास्तव", " "}, 
{ "Uttar Pradesh",  "7775",  "Badaun", "Kirpa Shankar Shakya", "NotGraduate",  " ","उत्तर प्रदेश",  "बदायूं", "किरपा शंकर शाक्य", " "}, 
{ "Uttar Pradesh",  "7776",  "Badaun", "Swami Paglanand", "NotGraduate",  " ","उत्तर प्रदेश",  "बदायूं", "स्वामी पगलानंद", " "}, 
{ "Uttar Pradesh",  "7779",  "Badaun", "Sangh Mitra Maurya", "ForeignFunding",  " ","उत्तर प्रदेश",  "बदायूं", "संघ मित्र मौर्य", " "}, 
{ "Uttar Pradesh",  "7780",  "Badaun", "Saleem Iqwal Shervani", "ForeignFunding",  " ","उत्तर प्रदेश",  "बदायूं", "सलीम इकवाल शेरवानी", " "}, 
{ "Uttar Pradesh",  "7781",  "Badaun", "Dharmendra Yadav", "CriminalCases",  " ","उत्तर प्रदेश",  "बदायूं", "धर्मेंद्र यादव", " "}, 
{ "Uttar Pradesh",  "7782",  "Badaun", "Hari Singh", "NotGraduate",  " ","उत्तर प्रदेश",  "बदायूं", "हरि सिंह", " "}, 
{ "Uttar Pradesh",  "6186",  "Baghpat", "Istakar Ali", "NotGraduate",  " ","उत्तर प्रदेश",  "बागपत", "इस्तकार अली", " "}, 
{ "Uttar Pradesh",  "6187",  "Baghpat", "Davender", "NotGraduate",  " ","उत्तर प्रदेश",  "बागपत", "Davender", " "}, 
{ "Uttar Pradesh",  "6188",  "Baghpat", "Jafar", "NotGraduate",  " ","उत्तर प्रदेश",  "बागपत", "जाफर", " "}, 
{ "Uttar Pradesh",  "6189",  "Baghpat", "Parveen Yogi", "NotGraduate",  " ","उत्तर प्रदेश",  "बागपत", "परवीन योगी", " "}, 
{ "Uttar Pradesh",  "6191",  "Baghpat", "Ramkumar", "NotGraduate",  " ","उत्तर प्रदेश",  "बागपत", "रामकुमार", " "}, 
{ "Uttar Pradesh",  "6192",  "Baghpat", "Uttar Kumar Jindal", "OverAged",  " ","उत्तर प्रदेश",  "बागपत", "उत्तर कुमार जिंदल", " "}, 
{ "Uttar Pradesh",  "6193",  "Baghpat", "Manoj Rana", "NotGraduate",  " ","उत्तर प्रदेश",  "बागपत", "मनोज राणा", " "}, 
{ "Uttar Pradesh",  "6194",  "Baghpat", "Dr. Satyapal Singh", "ForeignFunding",  " ","उत्तर प्रदेश",  "बागपत", "डॉ। सत्यपाल सिंह", " "}, 
{ "Uttar Pradesh",  "6195",  "Baghpat", "Subhash", "NotGraduate",  " ","उत्तर प्रदेश",  "बागपत", "सुभाष", " "}, 
{ "Uttar Pradesh",  "6196",  "Baghpat", "Chaudhary Mohkam", "CriminalCases",  " ","उत्तर प्रदेश",  "बागपत", "चौधरी मोहकम", " "}, 
{ "Uttar Pradesh",  "6197",  "Baghpat", "Dr. Saleem Ahmad", "CriminalCases",  " ","उत्तर प्रदेश",  "बागपत", "डॉ। सलीम अहमद", " "}, 
{ "Uttar Pradesh",  "7798",  "Bareilly", "Yatendra Singh", "NotGraduate",  " ","उत्तर प्रदेश",  "बरेली", "यतेंद्र सिंह", " "}, 
{ "Uttar Pradesh",  "7801",  "Bareilly", "Rabiya Akhtar", "CriminalCases",  " ","उत्तर प्रदेश",  "बरेली", "राबिया अख्तर", " "}, 
{ "Uttar Pradesh",  "7802",  "Bareilly", "Manoj Vikat", "CriminalCases",  " ","उत्तर प्रदेश",  "बरेली", "मनोज विकट", " "}, 
{ "Uttar Pradesh",  "7803",  "Bareilly", "Jagpal", "NotGraduate",  " ","उत्तर प्रदेश",  "बरेली", "जगपाल", " "}, 
{ "Uttar Pradesh",  "7804",  "Bareilly", "Raheesh Miyan", "NotGraduate",  " ","उत्तर प्रदेश",  "बरेली", "राहीश मियाँ", " "}, 
{ "Uttar Pradesh",  "7806",  "Bareilly", "Laeek Ahmad Mansoori", "NotGraduate",  " ","उत्तर प्रदेश",  "बरेली", "लईक अहमद मंसूरी", " "}, 
{ "Uttar Pradesh",  "7808",  "Bareilly", "Javed Khan", "CriminalCases",  " ","उत्तर प्रदेश",  "बरेली", "जावेद खान", " "}, 
{ "Uttar Pradesh",  "7809",  "Bareilly", "Santosh Kumar Gangwar", "ForeignFunding",  " ","उत्तर प्रदेश",  "बरेली", "संतोष कुमार गंगवार", " "}, 
{ "Uttar Pradesh",  "7810",  "Bareilly", "Bhagwat Saran Gangwar", "CriminalCases",  " ","उत्तर प्रदेश",  "बरेली", "भागवत सरन गंगवार", " "}, 
{ "Uttar Pradesh",  "7812",  "Bareilly", "Praveen Singh Aron", "ForeignFunding",  " ","उत्तर प्रदेश",  "बरेली", "प्रवीण सिंह एरन", " "}, 
{ "Uttar Pradesh",  "6144",  "Bijnor", "Mukesh Kumar", "NotGraduate",  " ","उत्तर प्रदेश",  "बिजनौर", "मुकेश कुमार", " "}, 
{ "Uttar Pradesh",  "6145",  "Bijnor", "Ilam Singh", "CriminalCases",  " ","उत्तर प्रदेश",  "बिजनौर", "इलम सिंह", " "}, 
{ "Uttar Pradesh",  "6146",  "Bijnor", "Rajiv Choudhary", "NotGraduate",  " ","उत्तर प्रदेश",  "बिजनौर", "राजीव चौधरी", " "}, 
{ "Uttar Pradesh",  "6147",  "Bijnor", "Malook Nagar", "CriminalCases",  " ","उत्तर प्रदेश",  "बिजनौर", "मलूक नगर", " "}, 
{ "Uttar Pradesh",  "6148",  "Bijnor", "Nasimuddin Siddqui", "ForeignFunding",  " ","उत्तर प्रदेश",  "बिजनौर", "नसीमुद्दीन सिद्दीकी", " "}, 
{ "Uttar Pradesh",  "6149",  "Bijnor", "Sonu", "NotGraduate",  " ","उत्तर प्रदेश",  "बिजनौर", "सोनू", " "}, 
{ "Uttar Pradesh",  "6150",  "Bijnor", "Raja Bhartendra Singh", "ForeignFunding",  " ","उत्तर प्रदेश",  "बिजनौर", "राजा भारतेन्द्र सिंह", " "}, 
{ "Uttar Pradesh",  "6151",  "Bijnor", "Babloo Ram", "NotGraduate",  " ","उत्तर प्रदेश",  "बिजनौर", "बबलू राम", " "}, 
{ "Uttar Pradesh",  "6153",  "Bijnor", "Mangeram", "NotGraduate",  " ","उत्तर प्रदेश",  "बिजनौर", "Mangeram", " "}, 
{ "Uttar Pradesh",  "6154",  "Bijnor", "Anshu Chaitanya Maharaj", "NotGraduate",  " ","उत्तर प्रदेश",  "बिजनौर", "अंशु चैतन्य महाराज", " "}, 
{ "Uttar Pradesh",  "6224",  "Bulandshahr", "Satish", "NotGraduate",  " ","उत्तर प्रदेश",  "बुलंदशहर", "सतीश", " "}, 
{ "Uttar Pradesh",  "6225",  "Bulandshahr", "Bhola Singh", "ForeignFunding",  " ","उत्तर प्रदेश",  "बुलंदशहर", "भोला सिंह", " "}, 
{ "Uttar Pradesh",  "6228",  "Bulandshahr", "Banshi Singh", "ForeignFunding",  " ","उत्तर प्रदेश",  "बुलंदशहर", "बंशी सिंह", " "}, 
{ "Uttar Pradesh",  "6230",  "Bulandshahr", "Reena Devi", "NotGraduate",  " ","उत्तर प्रदेश",  "बुलंदशहर", "रीना देवी", " "}, 
{ "Uttar Pradesh",  "6231",  "Bulandshahr", "Yogesh Verma", "CriminalCases",  " ","उत्तर प्रदेश",  "बुलंदशहर", "योगेश वर्मा", " "}, 
{ "Uttar Pradesh",  "7760",  "Etah", "Satendra Kumar Panda", "OverAged",  " ","उत्तर प्रदेश",  "एटा", "सतेंद्र कुमार पांडा", " "}, 
{ "Uttar Pradesh",  "7761",  "Etah", "Ashok Kumar", "CriminalCases",  " ","उत्तर प्रदेश",  "एटा", "अशोक कुमार", " "}, 
{ "Uttar Pradesh",  "7766",  "Etah", "Indrapal", "NotGraduate",  " ","उत्तर प्रदेश",  "एटा", "Indrapal", " "}, 
{ "Uttar Pradesh",  "7767",  "Etah", "Suraj Singh", "OverAged",  " ","उत्तर प्रदेश",  "एटा", "सूरज सिंह", " "}, 
{ "Uttar Pradesh",  "7768",  "Etah", "Rajveer Singh", "ForeignFunding",  " ","उत्तर प्रदेश",  "एटा", "राजवीर सिंह", " "}, 
{ "Uttar Pradesh",  "7769",  "Etah", "Hariom", "NotGraduate",  " ","उत्तर प्रदेश",  "एटा", "हरि ओम", " "}, 
{ "Uttar Pradesh",  "7771",  "Etah", "Bharat Singh", "CriminalCases",  " ","उत्तर प्रदेश",  "एटा", "भरत सिंह", " "}, 
{ "Uttar Pradesh",  "7772",  "Etah", "Naresh Chandra", "CriminalCases",  " ","उत्तर प्रदेश",  "एटा", "नरेश चंद्र", " "}, 
{ "Uttar Pradesh",  "7773",  "Etah", "Ku. Devendra Singh Yadav", "OverAged",  " ","उत्तर प्रदेश",  "एटा", "कु। देवेंद्र सिंह यादव", " "}, 
{ "Uttar Pradesh",  "6275",  "Fatehpur Sikri", "Sadab Noor", "NotGraduate",  " ","उत्तर प्रदेश",  "फतेहपुर सीकरी", "सदाब नूर", " "}, 
{ "Uttar Pradesh",  "6276",  "Fatehpur Sikri", "Manisha Singh", "NotGraduate",  " ","उत्तर प्रदेश",  "फतेहपुर सीकरी", "मनीषा सिंह", " "}, 
{ "Uttar Pradesh",  "6277",  "Fatehpur Sikri", "Arti Sharma", "NotGraduate",  " ","उत्तर प्रदेश",  "फतेहपुर सीकरी", "आरती शर्मा", " "}, 
{ "Uttar Pradesh",  "6278",  "Fatehpur Sikri", "Rajkumar Chahar", "ForeignFunding",  " ","उत्तर प्रदेश",  "फतेहपुर सीकरी", "राजकुमार चाहर", " "}, 
{ "Uttar Pradesh",  "6279",  "Fatehpur Sikri", "Ram Bahori", "NotGraduate",  " ","उत्तर प्रदेश",  "फतेहपुर सीकरी", "राम बहोरी", " "}, 
{ "Uttar Pradesh",  "6282",  "Fatehpur Sikri", "Naresh Kumar", "NotGraduate",  " ","उत्तर प्रदेश",  "फतेहपुर सीकरी", "नरेश कुमार", " "}, 
{ "Uttar Pradesh",  "6283",  "Fatehpur Sikri", "Vijay Singh Baghel", "OverAged",  " ","उत्तर प्रदेश",  "फतेहपुर सीकरी", "विजय सिंह बघेल", " "}, 
{ "Uttar Pradesh",  "6284",  "Fatehpur Sikri", "Pastar Thomsan Massy", "NotGraduate",  " ","उत्तर प्रदेश",  "फतेहपुर सीकरी", "पास्टर थॉमसन मासी", " "}, 
{ "Uttar Pradesh",  "6285",  "Fatehpur Sikri", "Nawab Gul Chaman Sherwani", "CriminalCases",  " ","उत्तर प्रदेश",  "फतेहपुर सीकरी", "नवाब गुल चमन शेरवानी", " "}, 
{ "Uttar Pradesh",  "6286",  "Fatehpur Sikri", "Raj Babbar", "ForeignFunding",  " ","उत्तर प्रदेश",  "फतेहपुर सीकरी", "राज बब्बर", " "}, 
{ "Uttar Pradesh",  "6288",  "Fatehpur Sikri", "Shreebhagwan Sharma", "CriminalCases",  " ","उत्तर प्रदेश",  "फतेहपुर सीकरी", "श्रीभगवान शर्मा", " "}, 
{ "Uttar Pradesh",  "7743",  "Firozabad", "Chaudhary Basheer", "CriminalCases",  " ","उत्तर प्रदेश",  "फिरोजाबाद", "चौधरी बशीर", " "}, 
{ "Uttar Pradesh",  "7744",  "Firozabad", "Dr. Chandra Sen Jadon", "ForeignFunding",  " ","उत्तर प्रदेश",  "फिरोजाबाद", "डॉ। चंद्र सेन जादोन", " "}, 
{ "Uttar Pradesh",  "7745",  "Firozabad", "Rajveer", "NotGraduate",  " ","उत्तर प्रदेश",  "फिरोजाबाद", "राजवीर", " "}, 
{ "Uttar Pradesh",  "6213",  "Gautam Buddha Nagar", "Dr. Mahesh Sharma", "ForeignFunding",  " ","उत्तर प्रदेश",  "गौतम बुद्ध नगर", "डॉ। महेश शर्मा", " "}, 
{ "Uttar Pradesh",  "6215",  "Gautam Buddha Nagar", "Ashok Kumar Adhana", "NotGraduate",  " ","उत्तर प्रदेश",  "गौतम बुद्ध नगर", "अशोक कुमार अधाना", " "}, 
{ "Uttar Pradesh",  "6216",  "Gautam Buddha Nagar", "Vinod Sharma", "NotGraduate",  " ","उत्तर प्रदेश",  "गौतम बुद्ध नगर", "विनोद शर्मा", " "}, 
{ "Uttar Pradesh",  "6217",  "Gautam Buddha Nagar", "Vinod Kumar Nagar", "CriminalCases",  " ","उत्तर प्रदेश",  "गौतम बुद्ध नगर", "विनोद कुमार नागर", " "}, 
{ "Uttar Pradesh",  "6218",  "Gautam Buddha Nagar", "Jitendra Singh", "CriminalCases",  " ","उत्तर प्रदेश",  "गौतम बुद्ध नगर", "जितेंद्र सिंह", " "}, 
{ "Uttar Pradesh",  "6219",  "Gautam Buddha Nagar", "Dayaram", "NotGraduate",  " ","उत्तर प्रदेश",  "गौतम बुद्ध नगर", "दयाराम", " "}, 
{ "Uttar Pradesh",  "6220",  "Gautam Buddha Nagar", "Satveer", "CriminalCases",  " ","उत्तर प्रदेश",  "गौतम बुद्ध नगर", "Satveer", " "}, 
{ "Uttar Pradesh",  "6221",  "Gautam Buddha Nagar", "Dr. Arvind Kumar Singh", "ForeignFunding",  " ","उत्तर प्रदेश",  "गौतम बुद्ध नगर", "डॉ। अरविंद कुमार सिंह", " "}, 
{ "Uttar Pradesh",  "6222",  "Gautam Buddha Nagar", "Sher Singh Upaddhaya", "NotGraduate",  " ","उत्तर प्रदेश",  "गौतम बुद्ध नगर", "शेर सिंह उपाध्याय", " "}, 
{ "Uttar Pradesh",  "6200",  "Ghaziabad", "Vijay Kumar Singh", "ForeignFunding",  " ","उत्तर प्रदेश",  "गाज़ियाबाद", "विजय कुमार सिंह", " "}, 
{ "Uttar Pradesh",  "6201",  "Ghaziabad", "Sewa Ram Kasana", "CriminalCases",  " ","उत्तर प्रदेश",  "गाज़ियाबाद", "सेवा राम कसाना", " "}, 
{ "Uttar Pradesh",  "6203",  "Ghaziabad", "Suresh Bansal", "OverAged",  " ","उत्तर प्रदेश",  "गाज़ियाबाद", "सुरेश बंसल", " "}, 
{ "Uttar Pradesh",  "6204",  "Ghaziabad", "Divya Yog Maya Saraswati", "CriminalCases",  " ","उत्तर प्रदेश",  "गाज़ियाबाद", "दिव्य योग माया सरस्वती", " "}, 
{ "Uttar Pradesh",  "6205",  "Ghaziabad", "Dolly Sharma", "ForeignFunding",  " ","उत्तर प्रदेश",  "गाज़ियाबाद", "डॉली शर्मा", " "}, 
{ "Uttar Pradesh",  "6207",  "Ghaziabad", "Amit Sharma", "NotGraduate",  " ","उत्तर प्रदेश",  "गाज़ियाबाद", "अमित शर्मा", " "}, 
{ "Uttar Pradesh",  "6208",  "Ghaziabad", "Mohd. Salim Ahmed", "NotGraduate",  " ","उत्तर प्रदेश",  "गाज़ियाबाद", "मोहम्मद। सलीम अहमद", " "}, 
{ "Uttar Pradesh",  "6209",  "Ghaziabad", "Sunil Nair", "CriminalCases",  " ","उत्तर प्रदेश",  "गाज़ियाबाद", "सुनील नायर", " "}, 
{ "Uttar Pradesh",  "6246",  "Hathras", "Rajaram", "OverAged",  " ","उत्तर प्रदेश",  "हाथरस", "राजा राम", " "}, 
{ "Uttar Pradesh",  "6247",  "Hathras", "Triloki Ram", "ForeignFunding",  " ","उत्तर प्रदेश",  "हाथरस", "त्रिलोकी राम", " "}, 
{ "Uttar Pradesh",  "6248",  "Hathras", "Ramji Lal Suman", "CriminalCases",  " ","उत्तर प्रदेश",  "हाथरस", "रामजी लाल सुमन", " "}, 
{ "Uttar Pradesh",  "6249",  "Hathras", "Tilak Singh", "NotGraduate",  " ","उत्तर प्रदेश",  "हाथरस", "तिलक सिंह", " "}, 
{ "Uttar Pradesh",  "6250",  "Hathras", "Harswaroop", "NotGraduate",  " ","उत्तर प्रदेश",  "हाथरस", "Harswaroop", " "}, 
{ "Uttar Pradesh",  "6251",  "Hathras", "Bhupendra Kumar", "NotGraduate",  " ","उत्तर प्रदेश",  "हाथरस", "भूपेंद्र कुमार", " "}, 
{ "Uttar Pradesh",  "6252",  "Hathras", "Rajvir Diler", "ForeignFunding",  " ","उत्तर प्रदेश",  "हाथरस", "राजवीर दलेर", " "}, 
{ "Uttar Pradesh",  "6121",  "Kairana", "Mukesh Devi", "NotGraduate",  " ","उत्तर प्रदेश",  "कैराना", "मुकेश देवी", " "}, 
{ "Uttar Pradesh",  "6122",  "Kairana", "Rekha", "NotGraduate",  " ","उत्तर प्रदेश",  "कैराना", "रेखा", " "}, 
{ "Uttar Pradesh",  "6123",  "Kairana", "Harish Kumar", "NotGraduate",  " ","उत्तर प्रदेश",  "कैराना", "हरीश कुमार", " "}, 
{ "Uttar Pradesh",  "6124",  "Kairana", "Mohd Saleem", "NotGraduate",  " ","उत्तर प्रदेश",  "कैराना", "मोहम्मद सलीम", " "}, 
{ "Uttar Pradesh",  "6125",  "Kairana", "Tabassum Begum", "NotGraduate",  " ","उत्तर प्रदेश",  "कैराना", "तबस्सुम बेगम", " "}, 
{ "Uttar Pradesh",  "6126",  "Kairana", "Harendra Singh Malik", "ForeignFunding",  " ","उत्तर प्रदेश",  "कैराना", "हरेंद्र सिंह मलिक", " "}, 
{ "Uttar Pradesh",  "6127",  "Kairana", "Shripal Singh", "NotGraduate",  " ","उत्तर प्रदेश",  "कैराना", "श्रीपाल सिंह", " "}, 
{ "Uttar Pradesh",  "6128",  "Kairana", "Yogesh Kumar", "NotGraduate",  " ","उत्तर प्रदेश",  "कैराना", "योगेश कुमार", " "}, 
{ "Uttar Pradesh",  "6129",  "Kairana", "Sheshraj", "OverAged",  " ","उत्तर प्रदेश",  "कैराना", "Sheshraj", " "}, 
{ "Uttar Pradesh",  "6130",  "Kairana", "Pradeep Kumar", "ForeignFunding",  " ","उत्तर प्रदेश",  "कैराना", "प्रदीप कुमार", " "}, 
{ "Uttar Pradesh",  "6131",  "Kairana", "Manoj Kumar", "NotGraduate",  " ","उत्तर प्रदेश",  "कैराना", "मनोज कुमार", " "}, 
{ "Uttar Pradesh",  "6132",  "Kairana", "Imran", "NotGraduate",  " ","उत्तर प्रदेश",  "कैराना", "इमरान", " "}, 
{ "Uttar Pradesh",  "7749",  "Mainpuri", "Chakrapan5", "NotGraduate",  " ","उत्तर प्रदेश",  "मैनपुरी", "Chakrapan5", " "}, 
{ "Uttar Pradesh",  "7750",  "Mainpuri", "Tej Pratap Singh Jatav", "NotGraduate",  " ","उत्तर प्रदेश",  "मैनपुरी", "तेज प्रताप सिंह जाटव", " "}, 
{ "Uttar Pradesh",  "7751",  "Mainpuri", "Rajat Kumar", "CriminalCases",  " ","उत्तर प्रदेश",  "मैनपुरी", "रजत कुमार", " "}, 
{ "Uttar Pradesh",  "7754",  "Mainpuri", "Hariram Shakya", "OverAged",  " ","उत्तर प्रदेश",  "मैनपुरी", "हरिराम शाक्य", " "}, 
{ "Uttar Pradesh",  "7756",  "Mainpuri", "Mulayam Singh Yadav", "CriminalCases",  " ","उत्तर प्रदेश",  "मैनपुरी", "मुलायम सिंह यादव", " "}, 
{ "Uttar Pradesh",  "7758",  "Mainpuri", "Ombeer Lodhi", "NotGraduate",  " ","उत्तर प्रदेश",  "मैनपुरी", "ओमबीर लोधी", " "}, 
{ "Uttar Pradesh",  "7759",  "Mainpuri", "Prem Singh Shakya", "ForeignFunding",  " ","उत्तर प्रदेश",  "मैनपुरी", "प्रेम सिंह शाक्य", " "}, 
{ "Uttar Pradesh",  "6253",  "Mathura", "Jagvir Singh", "NotGraduate",  " ","उत्तर प्रदेश",  "मथुरा", "जगवीर सिंह", " "}, 
{ "Uttar Pradesh",  "6254",  "Mathura", "Ramdas Tyagi", "NotGraduate",  " ","उत्तर प्रदेश",  "मथुरा", "रामदास त्यागी", " "}, 
{ "Uttar Pradesh",  "6255",  "Mathura", "Pramod Krishna", "NotGraduate",  " ","उत्तर प्रदेश",  "मथुरा", "प्रमोद कृष्ण", " "}, 
{ "Uttar Pradesh",  "6256",  "Mathura", "Chattar Alias Chatrapal Singh Nishad", "NotGraduate",  " ","उत्तर प्रदेश",  "मथुरा", "चतुर अलियास छत्रपाल सिंह निषाद", " "}, 
{ "Uttar Pradesh",  "6257",  "Mathura", "Jasveer Singh", "NotGraduate",  " ","उत्तर प्रदेश",  "मथुरा", "जसवीर सिंह", " "}, 
{ "Uttar Pradesh",  "6259",  "Mathura", "Phakkad Baba", "OverAged",  " ","उत्तर प्रदेश",  "मथुरा", "फक्कड़ बाबा", " "}, 
{ "Uttar Pradesh",  "6261",  "Mathura", "Mahesh Pathak", "ForeignFunding",  " ","उत्तर प्रदेश",  "मथुरा", "महेश पाठक", " "}, 
{ "Uttar Pradesh",  "6262",  "Mathura", "Jasvant Singh Baghel", "NotGraduate",  " ","उत्तर प्रदेश",  "मथुरा", "जसवंत सिंह बघेल", " "}, 
{ "Uttar Pradesh",  "6263",  "Mathura", "Narendra Singh", "CriminalCases",  " ","उत्तर प्रदेश",  "मथुरा", "नरेंद्र सिंह", " "}, 
{ "Uttar Pradesh",  "6264",  "Mathura", "Ramdev Gautam", "NotGraduate",  " ","उत्तर प्रदेश",  "मथुरा", "रामदेव गौतम", " "}, 
{ "Uttar Pradesh",  "6265",  "Mathura", "Hema Malini Dharmendra Deol", "ForeignFunding",  " ","उत्तर प्रदेश",  "मथुरा", "हेमा मालिनी धर्मेंद्र देओल", " "}, 
{ "Uttar Pradesh",  "6174",  "Meerut", "Rajendra Agarwal", "ForeignFunding",  " ","उत्तर प्रदेश",  "मेरठ", "राजेंद्र अग्रवाल", " "}, 
{ "Uttar Pradesh",  "6175",  "Meerut", "Harendra Agarwal", "ForeignFunding",  " ","उत्तर प्रदेश",  "मेरठ", "हरेंद्र अग्रवाल", " "}, 
{ "Uttar Pradesh",  "6176",  "Meerut", "Afzaal", "CriminalCases",  " ","उत्तर प्रदेश",  "मेरठ", "अफजल", " "}, 
{ "Uttar Pradesh",  "6178",  "Meerut", "Shrawan Kumar Agarwal", "OverAged",  " ","उत्तर प्रदेश",  "मेरठ", "श्रवण कुमार अग्रवाल", " "}, 
{ "Uttar Pradesh",  "6179",  "Meerut", "Haji Mohammad Yaqoob", "CriminalCases",  " ","उत्तर प्रदेश",  "मेरठ", "हाजी मोहम्मद याक़ूब", " "}, 
{ "Uttar Pradesh",  "6180",  "Meerut", "Rajesh Giri", "NotGraduate",  " ","उत्तर प्रदेश",  "मेरठ", "राजेश गिरी", " "}, 
{ "Uttar Pradesh",  "6182",  "Meerut", "Nasir Ali Khan", "NotGraduate",  " ","उत्तर प्रदेश",  "मेरठ", "नासिर अली खान", " "}, 
{ "Uttar Pradesh",  "6183",  "Meerut", "Kiran R. C. Jatav", "CriminalCases",  " ","उत्तर प्रदेश",  "मेरठ", "किरण आरसी जाटव", " "}, 
{ "Uttar Pradesh",  "7706",  "Moradabad", "Tej Singh Seny", "NotGraduate",  " ","उत्तर प्रदेश",  "मुरादाबाद", "तेज सिंह सेनी", " "}, 
{ "Uttar Pradesh",  "7707",  "Moradabad", "Kunwar Sarvesh Kumar", "ForeignFunding",  " ","उत्तर प्रदेश",  "मुरादाबाद", "कुंवर सर्वेश कुमार", " "}, 
{ "Uttar Pradesh",  "7709",  "Moradabad", "Mo. Aslam Alias Pasha", "NotGraduate",  " ","उत्तर प्रदेश",  "मुरादाबाद", "मो। असलम अलियास पाशा", " "}, 
{ "Uttar Pradesh",  "7710",  "Moradabad", "Dileram", "NotGraduate",  " ","उत्तर प्रदेश",  "मुरादाबाद", "Dileram", " "}, 
{ "Uttar Pradesh",  "7711",  "Moradabad", "Roopchand Singh", "OverAged",  " ","उत्तर प्रदेश",  "मुरादाबाद", "रूपचंद सिंह", " "}, 
{ "Uttar Pradesh",  "7712",  "Moradabad", "Mo. Imran Khan", "ForeignFunding",  " ","उत्तर प्रदेश",  "मुरादाबाद", "मो। इमरान खान", " "}, 
{ "Uttar Pradesh",  "7713",  "Moradabad", "Akeel", "NotGraduate",  " ","उत्तर प्रदेश",  "मुरादाबाद", "Akeel", " "}, 
{ "Uttar Pradesh",  "7714",  "Moradabad", "Nadir", "CriminalCases",  " ","उत्तर प्रदेश",  "मुरादाबाद", "पतन", " "}, 
{ "Uttar Pradesh",  "7716",  "Moradabad", "Bhishm Jeet Singh", "NotGraduate",  " ","उत्तर प्रदेश",  "मुरादाबाद", "भीष्म जीत सिंह", " "}, 
{ "Uttar Pradesh",  "7717",  "Moradabad", "Naresh Kumar Saini", "NotGraduate",  " ","उत्तर प्रदेश",  "मुरादाबाद", "नरेश कुमार सैनी", " "}, 
{ "Uttar Pradesh",  "6134",  "Muzaffarnagar", "Ajit Singh", "OverAged",  " ","उत्तर प्रदेश",  "मुजफ्फरनगर", "अजीत सिंह", " "}, 
{ "Uttar Pradesh",  "6136",  "Muzaffarnagar", "Jaipal Singh Saini", "OverAged",  " ","उत्तर प्रदेश",  "मुजफ्फरनगर", "जयपाल सिंह सैनी", " "}, 
{ "Uttar Pradesh",  "6137",  "Muzaffarnagar", "Krishan Pal Singh", "NotGraduate",  " ","उत्तर प्रदेश",  "मुजफ्फरनगर", "कृष्णपाल सिंह", " "}, 
{ "Uttar Pradesh",  "6138",  "Muzaffarnagar", "Yajpal Singh Rathi", "NotGraduate",  " ","उत्तर प्रदेश",  "मुजफ्फरनगर", "यजपाल सिंह राठी", " "}, 
{ "Uttar Pradesh",  "6139",  "Muzaffarnagar", "Sanjeev Kumar Balyan", "ForeignFunding",  " ","उत्तर प्रदेश",  "मुजफ्फरनगर", "संजीव कुमार बाल्यान", " "}, 
{ "Uttar Pradesh",  "6141",  "Muzaffarnagar", "Ashok", "NotGraduate",  " ","उत्तर प्रदेश",  "मुजफ्फरनगर", "अशोक", " "}, 
{ "Uttar Pradesh",  "6158",  "Nagina", "Girish Chandra", "CriminalCases",  " ","उत्तर प्रदेश",  "नगीना", "गिरीश चंद्र", " "}, 
{ "Uttar Pradesh",  "6159",  "Nagina", "Omvati Devi", "ForeignFunding",  " ","उत्तर प्रदेश",  "नगीना", "ओमवती देवी", " "}, 
{ "Uttar Pradesh",  "6160",  "Nagina", "Yashwant Singh", "ForeignFunding",  " ","उत्तर प्रदेश",  "नगीना", "यशवंत सिंह", " "}, 
{ "Uttar Pradesh",  "6162",  "Nagina", "Amichand", "OverAged",  " ","उत्तर प्रदेश",  "नगीना", "Amichand", " "}, 
{ "Uttar Pradesh",  "6163",  "Nagina", "Tej Singh", "CriminalCases",  " ","उत्तर प्रदेश",  "नगीना", "तेज सिंह", " "}, 
{ "Uttar Pradesh",  "7814",  "Pilibhit", "Surendra Kumar Gupta", "OverAged",  " ","उत्तर प्रदेश",  "पीलीभीत", "सुरेंद्र कुमार गुप्ता", " "}, 
{ "Uttar Pradesh",  "7815",  "Pilibhit", "Munesh Singh", "NotGraduate",  " ","उत्तर प्रदेश",  "पीलीभीत", "मुनेश सिंह", " "}, 
{ "Uttar Pradesh",  "7817",  "Pilibhit", "Anita Tripathi", "NotGraduate",  " ","उत्तर प्रदेश",  "पीलीभीत", "अनीता त्रिपाठी", " "}, 
{ "Uttar Pradesh",  "7820",  "Pilibhit", "Sanjay Kumar Bharti", "NotGraduate",  " ","उत्तर प्रदेश",  "पीलीभीत", "संजय कुमार भारती", " "}, 
{ "Uttar Pradesh",  "7821",  "Pilibhit", "Jafri Begum", "NotGraduate",  " ","उत्तर प्रदेश",  "पीलीभीत", "जाफरी बेगम", " "}, 
{ "Uttar Pradesh",  "7822",  "Pilibhit", "Hemraj Verma", "CriminalCases",  " ","उत्तर प्रदेश",  "पीलीभीत", "हेमराज वर्मा", " "}, 
{ "Uttar Pradesh",  "7824",  "Pilibhit", "Mo. Hanif", "NotGraduate",  " ","उत्तर प्रदेश",  "पीलीभीत", "मो.हनीफ", " "}, 
{ "Uttar Pradesh",  "7825",  "Pilibhit", "Feroze Varun Gandhi", "ForeignFunding",  " ","उत्तर प्रदेश",  "पीलीभीत", "फिरोज वरुण गांधी", " "}, 
{ "Uttar Pradesh",  "7719",  "Rampur", "Arshad Warsi", "CriminalCases",  " ","उत्तर प्रदेश",  "रामपुर", "अरशद वारसी", " "}, 
{ "Uttar Pradesh",  "7720",  "Rampur", "Javed Khan", "CriminalCases",  " ","उत्तर प्रदेश",  "रामपुर", "जावेद खान", " "}, 
{ "Uttar Pradesh",  "7721",  "Rampur", "Mohammad Azam Khan", "CriminalCases",  " ","उत्तर प्रदेश",  "रामपुर", "मोहम्मद आज़म खान", " "}, 
{ "Uttar Pradesh",  "7722",  "Rampur", "Sanjay Kapoor", "ForeignFunding",  " ","उत्तर प्रदेश",  "रामपुर", "संजय कपूर", " "}, 
{ "Uttar Pradesh",  "7723",  "Rampur", "Jayaprada Nahata", "ForeignFunding",  " ","उत्तर प्रदेश",  "रामपुर", "जयप्रदा नाहटा", " "}, 
{ "Uttar Pradesh",  "7724",  "Rampur", "Sameena Begum", "CriminalCases",  " ","उत्तर प्रदेश",  "रामपुर", "समीना बेगम", " "}, 
{ "Uttar Pradesh",  "7726",  "Rampur", "Haneef Khan", "OverAged",  " ","उत्तर प्रदेश",  "रामपुर", "हनीफ खान", " "}, 
{ "Uttar Pradesh",  "7727",  "Rampur", "Mohd. Khushi", "CriminalCases",  " ","उत्तर प्रदेश",  "रामपुर", "मोहम्मद। खुशी", " "}, 
{ "Uttar Pradesh",  "7728",  "Rampur", "Naim", "NotGraduate",  " ","उत्तर प्रदेश",  "रामपुर", "नाइम", " "}, 
{ "Uttar Pradesh",  "6110",  "Saharanpur", "Yogesh Dahiya", "CriminalCases",  " ","उत्तर प्रदेश",  "सहारनपुर", "योगेश दहिया", " "}, 
{ "Uttar Pradesh",  "6111",  "Saharanpur", "Pawan Kumar", "NotGraduate",  " ","उत्तर प्रदेश",  "सहारनपुर", "पवन कुमार", " "}, 
{ "Uttar Pradesh",  "6112",  "Saharanpur", "Amar Bahadur", "NotGraduate",  " ","उत्तर प्रदेश",  "सहारनपुर", "अमर बहादुर", " "}, 
{ "Uttar Pradesh",  "6113",  "Saharanpur", "Shabnam", "NotGraduate",  " ","उत्तर प्रदेश",  "सहारनपुर", "शबनम", " "}, 
{ "Uttar Pradesh",  "6114",  "Saharanpur", "Indu Devi", "NotGraduate",  " ","उत्तर प्रदेश",  "सहारनपुर", "इंदु देवी", " "}, 
{ "Uttar Pradesh",  "6116",  "Saharanpur", "Raghav Lakhanpal", "ForeignFunding",  " ","उत्तर प्रदेश",  "सहारनपुर", "राघव लखनपाल", " "}, 
{ "Uttar Pradesh",  "6119",  "Saharanpur", "Mohd. Uvais", "NotGraduate",  " ","उत्तर प्रदेश",  "सहारनपुर", "मोहम्मद। Uvais", " "}, 
{ "Uttar Pradesh",  "6120",  "Saharanpur", "Imran Masood", "ForeignFunding",  " ","उत्तर प्रदेश",  "सहारनपुर", "इमरान मसूद", " "}, 
{ "Uttar Pradesh",  "7730",  "Sambhal", "Firoz Khan", "NotGraduate",  " ","उत्तर प्रदेश",  "संभल", "फिरोज खान", " "}, 
{ "Uttar Pradesh",  "7731",  "Sambhal", "Major Jagat Pal Singh", "ForeignFunding",  " ","उत्तर प्रदेश",  "संभल", "मेजर जगत पाल सिंह", " "}, 
{ "Uttar Pradesh",  "7732",  "Sambhal", "Dr. Shafiqur Rehman Barq", "OverAged",  " ","उत्तर प्रदेश",  "संभल", "डॉ। शफीकुर रहमान बर्क", " "}, 
{ "Uttar Pradesh",  "7734",  "Sambhal", "Ilyas", "NotGraduate",  " ","उत्तर प्रदेश",  "संभल", "इलियास", " "}, 
{ "Uttar Pradesh",  "7735",  "Sambhal", "Virendra Kumar", "NotGraduate",  " ","उत्तर प्रदेश",  "संभल", "वीरेन्द्र कुमार", " "}, 
{ "Uttar Pradesh",  "7736",  "Sambhal", "Karan Singh", "NotGraduate",  " ","उत्तर प्रदेश",  "संभल", "कारन सिंह", " "}, 
{ "Uttar Pradesh",  "7739",  "Sambhal", "Mohd. Masroor", "NotGraduate",  " ","उत्तर प्रदेश",  "संभल", "मोहम्मद। मसरूर", " "}, 
{ "Uttar Pradesh",  "7740",  "Sambhal", "Parameshvar Lal", "ForeignFunding",  " ","उत्तर प्रदेश",  "संभल", "परमेस्वर लाल", " "}, 
{ "Uttar Pradesh",  "7741",  "Sambhal", "Shahla Wajid", "NotGraduate",  " ","उत्तर प्रदेश",  "संभल", "शाहला वाजिद", " "}, 
};

}