/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class West_Bengal {
public static final String[][] green_bucket = {
{"West Bengal",  "6289", "Alipurduars", "Gergory Trikey", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5711",  "",  "", "", "", ""}, 
{"West Bengal",  "6290", "Alipurduars", "Prasen Jayant Kindo", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5713",  "",  "", "", "", ""}, 
{"West Bengal",  "6291", "Alipurduars", "Dasrath Tirkey", "AITC", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4695",  "",  "", "", "", ""}, 
{"West Bengal",  "6293", "Alipurduars", "Mili Oraon", "Revolutionary Socialist Party", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4616",  "",  "", "", "", ""}, 
{"West Bengal",  "6343", "Cooch behar", "Naresh Chandra Roy", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5410",  "",  "", "", "", ""}, 
{"West Bengal",  "6346", "Cooch behar", "Dhananjoy Barman", "Welfare Party Of India", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5409",  "",  "", "", "", ""}, 
{"West Bengal",  "6347", "Cooch behar", "Nirmal Kumar Roy", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5411",  "",  "", "", "", ""}, 
{"West Bengal",  "6309", "Darjeeling", "Tanmay Dutta", "SUCI(C)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7216",  "",  "", "", "", ""}, 
{"West Bengal",  "6297", "Jalpaiguri", "Bhagirath Chandra Roy", "CPI(M)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5533",  "",  "", "", "", ""}, 
{"West Bengal",  "6298", "Jalpaiguri", "Sachimohan Barman", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5531",  "",  "", "", "", ""}, 
{"West Bengal",  "6299", "Jalpaiguri", "Jiban Krishna Majumder", "BSP", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5105",  "",  "", "", "", ""}, 
{"West Bengal",  "6300", "Jalpaiguri", "Ranjit Kumar Roy", "Samajwadi Jan Parishad", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5532",  "",  "", "", "", ""}, 
{"West Bengal",  "6303", "Jalpaiguri", "Bijoy Chandra Barman", "AITC", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4967",  "",  "", "", "", ""}, 
{"West Bengal",  "6326", "Raiganj", "Advocate Anjay Debsarma", "IND", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7235",  "",  "", "", "", ""}, 
{"West Bengal",  "6332", "Raiganj", "Akik Hossain Chowdhury", "Kamatapur Peoples Party (United)", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7232",  "",  "", "", "", ""}, 
{"West Bengal",  "6335", "Raiganj", "Santhapan Hasdak", "JMM", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7234",  "",  "", "", "", ""}, 
};

public static final String[][] red_bucket = {
{ "West Bengal",  "6292",  "Alipurduars", "John Barla", "ForeignFunding",  " ","",  "", "", " "}, 
{ "West Bengal",  "6294",  "Alipurduars", "Mohanlal Basumata", "ForeignFunding",  " ","",  "", "", " "}, 
{ "West Bengal",  "6295",  "Alipurduars", "Rabichan Rabha", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6338",  "Cooch behar", "Sri Nisith Pramanik", "ForeignFunding",  " ","",  "", "", " "}, 
{ "West Bengal",  "6339",  "Cooch behar", "Piya Roy Chowdhury", "ForeignFunding",  " ","",  "", "", " "}, 
{ "West Bengal",  "6340",  "Cooch behar", "Kangsa Raj Barman", "CriminalCases",  " ","",  "", "", " "}, 
{ "West Bengal",  "6341",  "Cooch behar", "Adhikary Paresh Chandra", "OverAged",  " ","",  "", "", " "}, 
{ "West Bengal",  "6342",  "Cooch behar", "Prabhat Roy", "CriminalCases",  " ","",  "", "", " "}, 
{ "West Bengal",  "6344",  "Cooch behar", "Gobinda Chandra Roy", "CriminalCases",  " ","",  "", "", " "}, 
{ "West Bengal",  "6345",  "Cooch behar", "Harekrishna Sarkar", "CriminalCases",  " ","",  "", "", " "}, 
{ "West Bengal",  "6348",  "Cooch behar", "Subodh Barman", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6308",  "Darjeeling", "Christopher Gahatraj", "OverAged",  " ","",  "", "", " "}, 
{ "West Bengal",  "6310",  "Darjeeling", "Bharat Dong", "CriminalCases",  " ","",  "", "", " "}, 
{ "West Bengal",  "6311",  "Darjeeling", "Sudip Mandal", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6312",  "Darjeeling", "Sankar Malakar", "ForeignFunding",  " ","",  "", "", " "}, 
{ "West Bengal",  "6313",  "Darjeeling", "Saman Pathak", "CriminalCases",  " ","",  "", "", " "}, 
{ "West Bengal",  "6314",  "Darjeeling", "Dipak Kumar Roy", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6315",  "Darjeeling", "Amar Singh Rai", "CriminalCases",  " ","",  "", "", " "}, 
{ "West Bengal",  "6316",  "Darjeeling", "Raju Bista", "ForeignFunding",  " ","",  "", "", " "}, 
{ "West Bengal",  "6317",  "Darjeeling", "Sunil Pandit", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6318",  "Darjeeling", "Rajesh Singh", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6319",  "Darjeeling", "Digbijay Mandal", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6320",  "Darjeeling", "Nirode Chandra Adhikary", "OverAged",  " ","",  "", "", " "}, 
{ "West Bengal",  "6321",  "Darjeeling", "Ajay Dahal", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6322",  "Darjeeling", "Reseeka Chettri", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6323",  "Darjeeling", "Harka Bahadur Chhetri", "CriminalCases",  " ","",  "", "", " "}, 
{ "West Bengal",  "6296",  "Jalpaiguri", "Subal Chandra Roy", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6301",  "Jalpaiguri", "Khushi Ranjan Mondal", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6302",  "Jalpaiguri", "Harekrishna Sarkar", "CriminalCases",  " ","",  "", "", " "}, 
{ "West Bengal",  "6304",  "Jalpaiguri", "Mani Kumar Darnal", "ForeignFunding",  " ","",  "", "", " "}, 
{ "West Bengal",  "6305",  "Jalpaiguri", "Haribhakta Sardar", "CriminalCases",  " ","",  "", "", " "}, 
{ "West Bengal",  "6306",  "Jalpaiguri", "Subhash Biswas", "OverAged",  " ","",  "", "", " "}, 
{ "West Bengal",  "6307",  "Jalpaiguri", "Jayanta Kumar Roy", "ForeignFunding",  " ","",  "", "", " "}, 
{ "West Bengal",  "6324",  "Raiganj", "Md. Salim", "CriminalCases",  " ","",  "", "", " "}, 
{ "West Bengal",  "6325",  "Raiganj", "Churka Murmu", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6327",  "Raiganj", "Kumaresh Sarkar", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6328",  "Raiganj", "Deepa Dasmunsi", "ForeignFunding",  " ","",  "", "", " "}, 
{ "West Bengal",  "6329",  "Raiganj", "Agarwal Kanaialal", "CriminalCases",  " ","",  "", "", " "}, 
{ "West Bengal",  "6330",  "Raiganj", "Binoy Kumar Das", "OverAged",  " ","",  "", "", " "}, 
{ "West Bengal",  "6331",  "Raiganj", "Sujan Krishna Paul", "CriminalCases",  " ","",  "", "", " "}, 
{ "West Bengal",  "6333",  "Raiganj", "Lakshman Murmu", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6334",  "Raiganj", "Raju Paul", "CriminalCases",  " ","",  "", "", " "}, 
{ "West Bengal",  "6336",  "Raiganj", "Md. Sahajan Badsha", "NotGraduate",  " ","",  "", "", " "}, 
{ "West Bengal",  "6337",  "Raiganj", "Debasree Chaudhuri", "ForeignFunding",  " ","",  "", "", " "}, 
};

}