/* Auto-generated file from db2java.php*/
package in.filternet.jantamalik.LokSabha_Election_2019;

public class West_Bengal {
public static final String[][] green_bucket = {
        {"West Bengal", "Alipurduars", "Gergory Trikey", "Independent", "14.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5711", "पश्चिम बंगाल", "अलीपुरद्वार लोक", "Gergory Trikey", "निर्दलीय"},
        {"West Bengal", "Alipurduars", "Prasen Jayant Kindo", "Independent", "86659", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5713", "पश्चिम बंगाल", "अलीपुरद्वार लोक", "प्रसेन जयंत किंडो", "निर्दलीय"},
        {"West Bengal", "Alipurduars", "Dasrath Tirkey", "All India Trinamool Congress", "90.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4695", "पश्चिम बंगाल", "अलीपुरद्वार लोक", "दशरथ तिर्की", "अखिल भारतीय तृणमूल कांग्रेस"},
        {"West Bengal", "Alipurduars", "Mili Oraon", "Revolutionary Socialist Party", "28Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4616", "पश्चिम बंगाल", "अलीपुरद्वार लोक", "मिलि उरांव", "क्रांतिकारी सोशलिस्ट पार्टी"},
        {"West Bengal", "Arambag", "Prosanta Malik", "Socialist Unity Centre of India (Communist)", "2.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11176", "पश्चिम बंगाल", "आरामबाग", "प्रोसांता मलिक", "भारतीय समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"West Bengal", "Arambag", "Samir Mitra", "Bahujan Samaj Party", "41565", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11546", "पश्चिम बंगाल", "आरामबाग", "समीर मित्रा", "बहुजन समाज पार्टी"},
        {"West Bengal", "Asansol", "Abhishek Kumar Singh", "Shiv Sena", "88.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10074", "पश्चिम बंगाल", "आसनसोल", "अभिषेक कुमार सिंह", "शिवसेना"},
        {"West Bengal", "Asansol", "Md Zahir Alam", "Bahujan Mukti Party", "1748", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10073", "पश्चिम बंगाल", "आसनसोल", "एमडी जहीर आलम", "बहुजन मुक्ति पार्टी"},
        {"West Bengal", "Asansol", "Kajal Banerjee", "Independent", "13600", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10078", "पश्चिम बंगाल", "आसनसोल", "काजल बनर्जी", "निर्दलीय"},
        {"West Bengal", "Asansol", "Amarnath Chowdhury", "Socialist Unity Centre of India (Communist)", "1.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10068", "पश्चिम बंगाल", "आसनसोल", "अमरनाथ चौधरी", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"West Bengal", "Baharampur", "Anisul Ambia", "Socialist Unity Centre of India (Communist)", "75.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10079", "पश्चिम बंगाल", "बरहाम्पुर", "अनीसुल अम्बिया", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"West Bengal", "Balurghat", "Ranjit Kumar Mohanta", "Shiv Sena", "39.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8254", "पश्चिम बंगाल", "बेलूरघाट", "रंजीत कुमार मोहंता", "शिवसेना"},
        {"West Bengal", "Balurghat", "Arpita Ghosh", "All India Trinamool Congress", "28.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7426", "पश्चिम बंगाल", "बेलूरघाट", "अर्पिता घोष", "अखिल भारतीय तृणमूल कांग्रेस"},
        {"West Bengal", "Bangaon", "Swapan Kumar Roy", "Independent", "24.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11933", "पश्चिम बंगाल", "बंगाव", "स्वपन कुमार रॉय", "निर्दलीय"},
        {"West Bengal", "Bangaon", "Subrata Biswas", "Bahujan Mukti Party", "19.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11931", "पश्चिम बंगाल", "बंगाव", "सुब्रत बिस्वास", "बहुजन मुक्ति पार्टी"},
        {"West Bengal", "Bangaon", "Chandan Mallick", "Bahujan Samaj Party", "84000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11182", "पश्चिम बंगाल", "बंगाव", "चंदन मल्लिक", "बहुजन समाज पार्टी"},
        {"West Bengal", "Bangaon", "Swapan Mondal", "Socialist Unity Centre of India (Communist)", "19760", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11181", "पश्चिम बंगाल", "बंगाव", "स्वपन मंडल", "भारतीय समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"West Bengal", "Bardhaman Durgapur", "Sucheta Banerjee", "Socialist Unity Centre of India (Communist)", "13Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10090", "पश्चिम बंगाल", "बर्धमान-दुर्गापुर", "सुचेता बनर्जी", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"West Bengal", "Bardhaman Durgapur", "Ramkrishna Malik", "Bahujan Samaj Party", "74000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10093", "पश्चिम बंगाल", "बर्धमान-दुर्गापुर", "रामकृष्ण मलिक", "बहुजन समाज पार्टी"},
        {"West Bengal", "Bardhaman Purba", "Sunil Kumar Mondal", "All India Trinamool Congress", "2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10100", "पश्चिम बंगाल", "बर्धमान पूर्ब", "सुनील कुमार मोंडल", "अखिल भारतीय तृणमूल कांग्रेस"},
        {"West Bengal", "Bardhaman Purba", "Mukul Biswas", "Bahujan Samaj Party", "44.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10101", "पश्चिम बंगाल", "बर्धमान पूर्ब", "मुकुल विश्वास", "बहुजन समाज पार्टी"},
        {"West Bengal", "Barrackpur", "Shampa Sil", "Independent", "22.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11938", "पश्चिम बंगाल", "बैरकपुर", "शम्पा सिल", "निर्दलीय"},
        {"West Bengal", "Barrackpur", "Uday Veer Choudhury", "Independent", "26.8Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11515", "पश्चिम बंगाल", "बैरकपुर", "उदय वीर चौधरी", "निर्दलीय"},
        {"West Bengal", "Barrackpur", "Gargi Chatterjee", "Communist Party of India (Marxist)", "57140", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11512", "पश्चिम बंगाल", "बैरकपुर", "गार्गी चटर्जी", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
        {"West Bengal", "Birbhum", "Md. Rezaul Karim", "Communist Party of India (Marxist)", "1.2Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10108", "पश्चिम बंगाल", "बीरभूम", "मो.रजुल करीम", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
        {"West Bengal", "Birbhum", "Satabdi Roy (Banerjee)", "All India Trinamool Congress", "4.9Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10106", "पश्चिम बंगाल", "बीरभूम", "सतबदी रॉय (बनर्जी)", "अखिल भारतीय तृणमूल कांग्रेस"},
        {"West Bengal", "Birbhum", "Ayesha Khatun", "Socialist Unity Centre of India (Communist)", "83300", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10104", "पश्चिम बंगाल", "बीरभूम", "आयशा खातुन", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"West Bengal", "Birbhum", "Chittaranjan Hansda", "Independent", "5.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10107", "पश्चिम बंगाल", "बीरभूम", "चित्तरंजन हांसदा", "निर्दलीय"},
        {"West Bengal", "Bolpur", "Simanta Mondal", "Rashtravadi Janata Party", "11.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10537", "पश्चिम बंगाल", "बोलपुर", "सिमंता मोंडल", "राष्ट्रवादी जनता पार्टी"},
        {"West Bengal", "Bolpur", "Bijoy Krishna Dolui", "Socialist Unity Centre of India (Communist)", "44.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10533", "पश्चिम बंगाल", "बोलपुर", "बिजॉय कृष्णा डोलुई", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"West Bengal", "Cooch behar", "Naresh Chandra Roy", "Independent", "70.4Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5410", "पश्चिम बंगाल", "कूचबिहार", "नरेश चंद्र रॉय", "निर्दलीय"},
        {"West Bengal", "Cooch behar", "Dhananjoy Barman", "Welfare Party Of India", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5409", "पश्चिम बंगाल", "कूचबिहार", "धनंजय बर्मन", "वेलफेयर पार्टी ऑफ इंडिया"},
        {"West Bengal", "Cooch behar", "Nirmal Kumar Roy", "Independent", "25.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5411", "पश्चिम बंगाल", "कूचबिहार", "निर्मल कुमार रॉय", "निर्दलीय"},
        {"West Bengal", "Darjeeling", "Tanmay Dutta", "Socialist Unity Centre of India (Communist)", "7.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7216", "पश्चिम बंगाल", "दार्जिलिंग", "तन्मय दत्ता", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"West Bengal", "Hooghly", "Bhaskar Ghosh", "Socialist Unity Centre of India (Communist)", "48.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11194", "पश्चिम बंगाल", "हुगली", "भास्कर घोष", "भारतीय समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"West Bengal", "Howrah", "Md. Shanawaz", "Socialist Unity Centre of India (Communist)", "1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11198", "पश्चिम बंगाल", "हावड़ा", "एमडी शनावाज़", "भारतीय समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"West Bengal", "Howrah", "Gautam Kumar Shaw", "Purvanchal Janta Party (Secular)", "37941", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11523", "पश्चिम बंगाल", "हावड़ा", "गौतम कुमार शॉ", "पूर्वांचल जनता पार्टी (सेक्युलर)"},
        {"West Bengal", "Howrah", "Sumitro Adhikary", "Communist Party of India (Marxist)", "19.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11199", "पश्चिम बंगाल", "हावड़ा", "सुमित्रो आदिकारी", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
        {"West Bengal", "Howrah", "Debasish Mandal", "Independent", "68190", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11203", "पश्चिम बंगाल", "हावड़ा", "देबाशीष मंडल", "निर्दलीय"},
        {"West Bengal", "Jalpaiguri", "Bhagirath Chandra Roy", "Communist Party of India (Marxist)", "3.1Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5533", "पश्चिम बंगाल", "जलपाईगुड़ी", "भागीरथ चंद्र रॉय", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
        {"West Bengal", "Jalpaiguri", "Sachimohan Barman", "Independent", "15.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5531", "पश्चिम बंगाल", "जलपाईगुड़ी", "सचिमोहन बर्मन", "निर्दलीय"},
        {"West Bengal", "Jalpaiguri", "Jiban Krishna Majumder", "Bahujan Samaj Party", "59.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5105", "पश्चिम बंगाल", "जलपाईगुड़ी", "जीबन कृष्णा मजुमदार", "बहुजन समाज पार्टी"},
        {"West Bengal", "Jalpaiguri", "Ranjit Kumar Roy", "Samajwadi Jan Parishad", "43.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=5532", "पश्चिम बंगाल", "जलपाईगुड़ी", "रंजीत कुमार रॉय", "समाजवादी जन परिषद"},
        {"West Bengal", "Jalpaiguri", "Bijoy Chandra Barman", "All India Trinamool Congress", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=4967", "पश्चिम बंगाल", "जलपाईगुड़ी", "बिजय चंद्र बर्मन", "अखिल भारतीय तृणमूल कांग्रेस"},
        {"West Bengal", "Jangipur", "Md. Taiedul Islam", "Social Democratic Party of India", "25.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7435", "पश्चिम बंगाल", "जंगीपुर", "एमडी। ताईदुल इस्लाम", "सोशल डेमोक्रेटिक पार्टी ऑफ इंडिया"},
        {"West Bengal", "Jangipur", "Md. Samiruddin", "Socialist Unity Centre of India (Communist)", "26267", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7436", "पश्चिम बंगाल", "जंगीपुर", "मो। समिरुद्दीन", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"West Bengal", "Jangipur", "Md. Zulfikar Ali", "Communist Party of India (Marxist)", "86.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7438", "पश्चिम बंगाल", "जंगीपुर", "मो। ज़ुल्फ़िकार अली", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
        {"West Bengal", "Jangipur", "Khalilur Rahaman", "All India Trinamool Congress", "36.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7854", "पश्चिम बंगाल", "जंगीपुर", "खलीलुर रहमान", "अखिल भारतीय तृणमूल कांग्रेस"},
        {"West Bengal", "Jangipur", "Dhananjoy Banerjee", "Purvanchal Janta Party (Secular)", "20.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9881", "पश्चिम बंगाल", "जंगीपुर", "धनंजय बनर्जी", "पूर्वांचल जनता पार्टी (सेक्युलर)"},
        {"West Bengal", "Krishnanagar", "Mahua Moitra", "All India Trinamool Congress", "2.7Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10544", "पश्चिम बंगाल", "कृष्णनगर", "महुआ मोइत्रा", "अखिल भारतीय तृणमूल कांग्रेस"},
        {"West Bengal", "Krishnanagar", "Ashok Agarwala", "Independent", "3.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10538", "पश्चिम बंगाल", "कृष्णनगर", "अशोक अग्रवाल", "निर्दलीय"},
        {"West Bengal", "Krishnanagar", "Subimal Sengupta", "Communist Party of India (Marxist–Leninist) Liberation", "1.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10547", "पश्चिम बंगाल", "कृष्णनगर", "सुबिमल सेनगुप्ता", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) मुक्ति"},
        {"West Bengal", "Krishnanagar", "Uddhab Roy", "Bahujan Samaj Party", "77.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10548", "पश्चिम बंगाल", "कृष्णनगर", "उद्धव रॉय", "बहुजन समाज पार्टी"},
        {"West Bengal", "Maldaha Dakshin", "Md Moazzem Hossain", "All India Trinamool Congress", "1.4Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8255", "पश्चिम बंगाल", "मालदा दक्षिण", "मो। मोअज्जम हुसैन", "अखिल भारतीय तृणमूल कांग्रेस"},
        {"West Bengal", "Maldaha Dakshin", "Angshudhar Mandal", "Socialist Unity Centre of India (Communist)", "20.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7447", "पश्चिम बंगाल", "मालदा दक्षिण", "अंगशुधर मंडल", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"West Bengal", "Maldaha Uttar", "Nitish Kumar Mandal", "Bahujan Samaj Party", "37.3Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7453", "पश्चिम बंगाल", "मालदा उत्तर", "नीतीश कुमार मंडल", "बहुजन समाज पार्टी"},
        {"West Bengal", "Maldaha Uttar", "Noorsed Alam", "Independent", "56.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7456", "पश्चिम बंगाल", "मालदा उत्तर", "नूर आलम", "निर्दलीय"},
        {"West Bengal", "Maldaha Uttar", "Monatan Hembram", "Bahujan Mukti Party", "65000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7861", "पश्चिम बंगाल", "मालदा उत्तर", "मोनातन हेम्ब्रम", "बहुजन मुक्ति पार्टी"},
        {"West Bengal", "Maldaha Uttar", "Mohan Hasda", "Independent", "4.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=8257", "पश्चिम बंगाल", "मालदा उत्तर", "मोहन हसदा", "निर्दलीय"},
        {"West Bengal", "Maldaha Uttar", "Subhash Sarkar", "Socialist Unity Centre of India (Communist)", "2.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7452", "पश्चिम बंगाल", "मालदा उत्तर", "सुभाष सरकार", "भारत का समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"West Bengal", "Maldaha Uttar", "Joseph Kisku", "Jharkhand Mukti Morcha", "8.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7455", "पश्चिम बंगाल", "मालदा उत्तर", "जोसेफ किस्कू", "झारखंड मुक्ति मोर्चा"},
        {"West Bengal", "Murshidabad", "Dhananjoy Sarkar", "Bahujan Mukti Party", "6.2Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9900", "पश्चिम बंगाल", "मुर्शिदाबाद", "धनंजय सरकार", "बहुजन मुक्ति पार्टी"},
        {"West Bengal", "Murshidabad", "Badaruddoza Khan", "Communist Party of India (Marxist)", "48.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7459", "पश्चिम बंगाल", "मुर्शिदाबाद", "बदरुद्दोज़ा खान", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
        {"West Bengal", "Murshidabad", "Md Habibur Rahaman", "Jamat-E-Seratul Mustakim", "56Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7458", "पश्चिम बंगाल", "मुर्शिदाबाद", "एमडी हबीबुर रहमान", "जमात-ए-सेरातुल मुस्तकीम"},
        {"West Bengal", "Murshidabad", "Md. Jalaluddin Mondal", "Independent", "80.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=9902", "पश्चिम बंगाल", "मुर्शिदाबाद", "मो। जलालुद्दीन मोंडल", "निर्दलीय"},
        {"West Bengal", "Raiganj", "Advocate Anjay Debsarma", "Independent", "7.1Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7235", "पश्चिम बंगाल", "रायगंज", "एडवोकेट अंजय देबसर्मा", "निर्दलीय"},
        {"West Bengal", "Raiganj", "Akik Hossain Chowdhury", "Kamatapur Peoples Party (United)", "10.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7232", "पश्चिम बंगाल", "रायगंज", "अकीक हुसैन चौधरी", "कामतापुर पीपल्स पार्टी (यूनाइटेड)"},
        {"West Bengal", "Raiganj", "Santhapan Hasdak", "Jharkhand Mukti Morcha", "5.6Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=7234", "पश्चिम बंगाल", "रायगंज", "संथापान हसदाक", "झारखंड मुक्ति मोर्चा"},
        {"West Bengal", "Ranaghat", "Rupali Biswas", "All India Trinamool Congress", "73.7Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=10557", "पश्चिम बंगाल", "रानाघाट", "रूपाली बिस्वास", "अखिल भारतीय तृणमूल कांग्रेस"},
        {"West Bengal", "Sreerampur", "Tirthankar Ray", "Communist Party of India (Marxist)", "2.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11206", "पश्चिम बंगाल", "श्रीरामपुर", "तीर्थंकर रे", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
        {"West Bengal", "Sreerampur", "Swapan Manna", "Independent", "32000", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11947", "पश्चिम बंगाल", "श्रीरामपुर", "स्वपन मन्ना", "निर्दलीय"},
        {"West Bengal", "Sreerampur", "Kalyan Banerjee", "All India Trinamool Congress", "17.6Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11205", "पश्चिम बंगाल", "श्रीरामपुर", "कल्याण बनर्जी", "अखिल भारतीय तृणमूल कांग्रेस"},
        {"West Bengal", "Uluberia", "Sajda Ahmed", "All India Trinamool Congress", "2.8Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11212", "पश्चिम बंगाल", "उलूबेरिया", "सजदा अहमद", "अखिल भारतीय तृणमूल कांग्रेस"},
        {"West Bengal", "Uluberia", "Minati Sarkar", "Socialist Unity Centre of India (Communist)", "10.9Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11209", "पश्चिम बंगाल", "उलूबेरिया", "मिनती सरकार", "भारतीय समाजवादी एकता केंद्र (कम्युनिस्ट)"},
        {"West Bengal", "Uluberia", "Simal Saren", "Indian Unity Centre", "9.5Lac", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11211", "पश्चिम बंगाल", "उलूबेरिया", "सिमल सरन", "भारतीय एकता केंद्र"},
        {"West Bengal", "Uluberia", "Maksuda Khatun", "Communist Party of India (Marxist)", "1.3Crore", "http://myneta.info/LokSabha2019/candidate.php?candidate_id=11210", "पश्चिम बंगाल", "उलूबेरिया", "मकसुदा खातुन", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)"},
};

public static final String[][] red_bucket = {
        {"West Bengal", "Alipurduars", "John Barla", "1", " ", "पश्चिम बंगाल", "अलीपुरद्वार लोक", "जॉन बारला", " "},
        {"West Bengal", "Alipurduars", "Mohanlal Basumata", "1", " ", "पश्चिम बंगाल", "अलीपुरद्वार लोक", "मोहनलाल बसुमाता", " "},
        {"West Bengal", "Alipurduars", "Rabichan Rabha", "4", " ", "पश्चिम बंगाल", "अलीपुरद्वार लोक", "राबिचन राभा", " "},
        {"West Bengal", "Arambag", "Binay Kumar Malik", "4", " ", "पश्चिम बंगाल", "आरामबाग", "बिनय कुमार मलिक", " "},
        {"West Bengal", "Arambag", "Chittaranjan Mallick", "4", " ", "पश्चिम बंगाल", "आरामबाग", "चित्तरंजन मल्लिक", " "},
        {"West Bengal", "Arambag", "Tapan Kumar Ray", "1", " ", "पश्चिम बंगाल", "आरामबाग", "तपन कुमार रे", " "},
        {"West Bengal", "Arambag", "Jhantu Lal Pakre", "2", " ", "पश्चिम बंगाल", "आरामबाग", "झंटू लाल पकेरे", " "},
        {"West Bengal", "Arambag", "Aparupa Poddar (Afrin Ali)", "2", " ", "पश्चिम बंगाल", "आरामबाग", "वानर पोद्दार (अफरीन अली)", " "},
        {"West Bengal", "Arambag", "Jyoti Kumari Das", "1", " ", "पश्चिम बंगाल", "आरामबाग", "ज्योति कुमारी दास", " "},
        {"West Bengal", "Arambag", "Sakti Mohan Malik", "2", " ", "पश्चिम बंगाल", "आरामबाग", "शक्ति मोहन मलिक", " "},
        {"West Bengal", "Asansol", "Sreemati (Moon Moon) Dev Varma (Sen)", "3", " ", "पश्चिम बंगाल", "आसनसोल", "सरमती (चंद्रमा चंद्रमा) देव वर्मा (सेन)", " "},
        {"West Bengal", "Asansol", "Swaraj Das", "2", " ", "पश्चिम बंगाल", "आसनसोल", "स्वराज दास", " "},
        {"West Bengal", "Asansol", "Gouranga Chatterjee", "2", " ", "पश्चिम बंगाल", "आसनसोल", "गौरंगा चटर्जी", " "},
        {"West Bengal", "Asansol", "Sandip Sarkar", "4", " ", "पश्चिम बंगाल", "आसनसोल", "संदीप सरकार", " "},
        {"West Bengal", "Asansol", "Biswarup Mondal", "1", " ", "पश्चिम बंगाल", "आसनसोल", "बिसवरुप मोंडल", " "},
        {"West Bengal", "Asansol", "Babul Supriya Baral", "1", " ", "पश्चिम बंगाल", "आसनसोल", "बाबुल सुप्रिया बराल", " "},
        {"West Bengal", "Baharampur", "Kushadhaj Bala", "4", " ", "पश्चिम बंगाल", "बरहाम्पुर", "कुशधज बाला", " "},
        {"West Bengal", "Baharampur", "Durbadal Das", "4", " ", "पश्चिम बंगाल", "बरहाम्पुर", "दुर्बलदास दास", " "},
        {"West Bengal", "Baharampur", "Saikh Id Mohammad", "3", " ", "पश्चिम बंगाल", "बरहाम्पुर", "शेख ईद मोहम्मद", " "},
        {"West Bengal", "Baharampur", "Krishna Joyardar", "1", " ", "पश्चिम बंगाल", "बरहाम्पुर", "कृष्ण जोयदार", " "},
        {"West Bengal", "Baharampur", "Asish Singha", "4", " ", "पश्चिम बंगाल", "बरहाम्पुर", "आशीष सिंघा", " "},
        {"West Bengal", "Baharampur", "Apurba Sarkar", "2", " ", "पश्चिम बंगाल", "बरहाम्पुर", "अपूर्वा सरकार", " "},
        {"West Bengal", "Baharampur", "Samir Biswas", "4", " ", "पश्चिम बंगाल", "बरहाम्पुर", "समीर बिस्वास", " "},
        {"West Bengal", "Baharampur", "Kashinath Dutta", "3", " ", "पश्चिम बंगाल", "बरहाम्पुर", "काशीनाथ दत्ता", " "},
        {"West Bengal", "Baharampur", "Md. Ezaruddin", "3", " ", "पश्चिम बंगाल", "बरहाम्पुर", "मो। एजरुद्दीन", " "},
        {"West Bengal", "Baharampur", "Adhir Ranjan Chowdhury", "1", " ", "पश्चिम बंगाल", "बरहाम्पुर", "अधीर रंजन चौधरी", " "},
        {"West Bengal", "Balurghat", "Nubash Chandra Barman", "2", " ", "पश्चिम बंगाल", "बेलूरघाट", "नुबाश चंद्र बर्मन", " "},
        {"West Bengal", "Balurghat", "Muslima Khatun", "4", " ", "पश्चिम बंगाल", "बेलूरघाट", "मुस्लिमा खातुन", " "},
        {"West Bengal", "Balurghat", "Nalin Chandra Murmu", "4", " ", "पश्चिम बंगाल", "बेलूरघाट", "नलिन चंद्र मुर्मू", " "},
        {"West Bengal", "Balurghat", "Abdus Sadek Sarkar", "1", " ", "पश्चिम बंगाल", "बेलूरघाट", "अब्दुस सादिक सरकार", " "},
        {"West Bengal", "Balurghat", "Bibhuti Tudu", "4", " ", "पश्चिम बंगाल", "बेलूरघाट", "विभूति टुडू", " "},
        {"West Bengal", "Balurghat", "Sukanta Majumdar", "1", " ", "पश्चिम बंगाल", "बेलूरघाट", "सुकांत मजूमदार", " "},
        {"West Bengal", "Balurghat", "Ranendra Nath Mali", "3", " ", "पश्चिम बंगाल", "बेलूरघाट", "रणेंद्र नाथ माली", " "},
        {"West Bengal", "Balurghat", "Naran Tudu", "4", " ", "पश्चिम बंगाल", "बेलूरघाट", "नारन टुडू", " "},
        {"West Bengal", "Balurghat", "Manas Chakraborty", "2", " ", "पश्चिम बंगाल", "बेलूरघाट", "मानस चक्रवर्ती", " "},
        {"West Bengal", "Balurghat", "Ranen Barman", "4", " ", "पश्चिम बंगाल", "बेलूरघाट", "रैनन बर्मन", " "},
        {"West Bengal", "Balurghat", "Biren Mahanta", "2", " ", "पश्चिम बंगाल", "बेलूरघाट", "बिरेन महंत", " "},
        {"West Bengal", "Bangaon", "Mamata Thakur", "2", " ", "पश्चिम बंगाल", "बंगाव", "ममता ठाकुर", " "},
        {"West Bengal", "Bangaon", "Shantanu Thakur", "1", " ", "पश्चिम बंगाल", "बंगाव", "शांतनु ठाकुर", " "},
        {"West Bengal", "Bangaon", "Alakesh Das", "2", " ", "पश्चिम बंगाल", "बंगाव", "अलकेश दास", " "},
        {"West Bengal", "Bangaon", "Sourav Prosad", "1", " ", "पश्चिम बंगाल", "बंगाव", "सौरव प्रसाद", " "},
        {"West Bengal", "Bangaon", "Samaresh Biswas", "4", " ", "पश्चिम बंगाल", "बंगाव", "समरेश विश्वास", " "},
        {"West Bengal", "Bangaon", "Animesh Chandra Halder", "4", " ", "पश्चिम बंगाल", "बंगाव", "अनिमेष चंद्र हलदर", " "},
        {"West Bengal", "Bardhaman Durgapur", "Mamtaz Sanghamita", "3", " ", "पश्चिम बंगाल", "बर्धमान-दुर्गापुर", "ममताज संघमित्रा", " "},
        {"West Bengal", "Bardhaman Durgapur", "Abhas Ray Chaudhuri", "2", " ", "पश्चिम बंगाल", "बर्धमान-दुर्गापुर", "आभास रे चौधुरी", " "},
        {"West Bengal", "Bardhaman Durgapur", "Ranajit Mukherjee", "1", " ", "पश्चिम बंगाल", "बर्धमान-दुर्गापुर", "रणजीत मुखर्जी", " "},
        {"West Bengal", "Bardhaman Durgapur", "Surendrajeet Singh Ahluwalia", "1", " ", "पश्चिम बंगाल", "बर्धमान-दुर्गापुर", "सुरेंद्रजीत सिंह अहलूवालिया", " "},
        {"West Bengal", "Bardhaman Purba", "Paresh Chandra Das", "1", " ", "पश्चिम बंगाल", "बर्धमान पूर्ब", "परेश चंद्र दास", " "},
        {"West Bengal", "Bardhaman Purba", "Nirmal Majhi", "4", " ", "पश्चिम बंगाल", "बर्धमान पूर्ब", "निर्मल मांझी", " "},
        {"West Bengal", "Bardhaman Purba", "Siddhartha Majumdar", "1", " ", "पश्चिम बंगाल", "बर्धमान पूर्ब", "सिद्धार्थ मजूमदार", " "},
        {"West Bengal", "Bardhaman Purba", "Biplab Mistri", "4", " ", "पश्चिम बंगाल", "बर्धमान पूर्ब", "बिप्लब मिस्त्री", " "},
        {"West Bengal", "Bardhaman Purba", "Iswar Chandra Das", "2", " ", "पश्चिम बंगाल", "बर्धमान पूर्ब", "ईश्वर चंद्र दास", " "},
        {"West Bengal", "Barrackpur", "Sourav Singh", "2", " ", "पश्चिम बंगाल", "बैरकपुर", "सौरव सिंह", " "},
        {"West Bengal", "Barrackpur", "Arjun Singh", "1", " ", "पश्चिम बंगाल", "बैरकपुर", "अर्जुन सिंह", " "},
        {"West Bengal", "Barrackpur", "Ganesh Das", "2", " ", "पश्चिम बंगाल", "बैरकपुर", "गणेश दास", " "},
        {"West Bengal", "Barrackpur", "Dinesh Trivedi", "3", " ", "पश्चिम बंगाल", "बैरकपुर", "दिनेश त्रिवेदी", " "},
        {"West Bengal", "Barrackpur", "Pradip Chaudhuri", "3", " ", "पश्चिम बंगाल", "बैरकपुर", "प्रदीप चौधरी", " "},
        {"West Bengal", "Barrackpur", "Md. Alam", "1", " ", "पश्चिम बंगाल", "बैरकपुर", "मो। आलम", " "},
        {"West Bengal", "Barrackpur", "Ramu Mandi", "4", " ", "पश्चिम बंगाल", "बैरकपुर", "रामू मंडी", " "},
        {"West Bengal", "Barrackpur", "Tapash Sarkar", "4", " ", "पश्चिम बंगाल", "बैरकपुर", "तपश सरकार", " "},
        {"West Bengal", "Barrackpur", "Gopal Raut", "2", " ", "पश्चिम बंगाल", "बैरकपुर", "गोपाल राउत", " "},
        {"West Bengal", "Barrackpur", "Md. Shyead Ahamed", "4", " ", "पश्चिम बंगाल", "बैरकपुर", "म.द.शायेद अहमद", " "},
        {"West Bengal", "Barrackpur", "Kundan Singh", "4", " ", "पश्चिम बंगाल", "बैरकपुर", "कुंदन सिंह", " "},
        {"West Bengal", "Barrackpur", "Krishanpal Balmiki", "4", " ", "पश्चिम बंगाल", "बैरकपुर", "कृष्णपाल बाल्मीकि", " "},
        {"West Bengal", "Birbhum", "Imam Hossain", "1", " ", "पश्चिम बंगाल", "बीरभूम", "इमाम हुसैन", " "},
        {"West Bengal", "Birbhum", "Dudh Kumar Mondal", "1", " ", "पश्चिम बंगाल", "बीरभूम", "दुध कुमार मोंडल", " "},
        {"West Bengal", "Birbhum", "Firoj Ali", "4", " ", "पश्चिम बंगाल", "बीरभूम", "फिरोज अली", " "},
        {"West Bengal", "Birbhum", "Faruk Ahamed", "4", " ", "पश्चिम बंगाल", "बीरभूम", "फारुक अहमद", " "},
        {"West Bengal", "Birbhum", "Prabir Mukhopadhyay", "4", " ", "पश्चिम बंगाल", "बीरभूम", "प्रबीर मुखोपाध्याय", " "},
        {"West Bengal", "Bolpur", "Ramprasad Das", "1", " ", "पश्चिम बंगाल", "बोलपुर", "रामप्रसाद दास", " "},
        {"West Bengal", "Bolpur", "Ramchandra Dome", "2", " ", "पश्चिम बंगाल", "बोलपुर", "रामचंद्र डोम", " "},
        {"West Bengal", "Bolpur", "Asit Kumar Mal", "4", " ", "पश्चिम बंगाल", "बोलपुर", "असित कुमार मल", " "},
        {"West Bengal", "Bolpur", "Samiran Das", "4", " ", "पश्चिम बंगाल", "बोलपुर", "समीरन दास", " "},
        {"West Bengal", "Bolpur", "Abhijit Saha", "1", " ", "पश्चिम बंगाल", "बोलपुर", "अभिजीत साहा", " "},
        {"West Bengal", "Cooch behar", "Sri Nisith Pramanik", "1", " ", "पश्चिम बंगाल", "कूचबिहार", "श्री निसिथ प्रमाणिक", " "},
        {"West Bengal", "Cooch behar", "Piya Roy Chowdhury", "1", " ", "पश्चिम बंगाल", "कूचबिहार", "पिया रॉय चौधरी", " "},
        {"West Bengal", "Cooch behar", "Kangsa Raj Barman", "2", " ", "पश्चिम बंगाल", "कूचबिहार", "कंगसा राज बर्मन", " "},
        {"West Bengal", "Cooch behar", "Adhikary Paresh Chandra", "3", " ", "पश्चिम बंगाल", "कूचबिहार", "आदिकेश परेश चंद्रा", " "},
        {"West Bengal", "Cooch behar", "Prabhat Roy", "2", " ", "पश्चिम बंगाल", "कूचबिहार", "प्रभात रॉय", " "},
        {"West Bengal", "Cooch behar", "Gobinda Chandra Roy", "2", " ", "पश्चिम बंगाल", "कूचबिहार", "गोबिंदा चंद्र रॉय", " "},
        {"West Bengal", "Cooch behar", "Harekrishna Sarkar", "2", " ", "पश्चिम बंगाल", "कूचबिहार", "हरेकृष्ण सरकार", " "},
        {"West Bengal", "Cooch behar", "Subodh Barman", "4", " ", "पश्चिम बंगाल", "कूचबिहार", "सुबोध बर्मन", " "},
        {"West Bengal", "Darjeeling", "Christopher Gahatraj", "3", " ", "पश्चिम बंगाल", "दार्जिलिंग", "क्रिस्टोफर गहतराज", " "},
        {"West Bengal", "Darjeeling", "Bharat Dong", "2", " ", "पश्चिम बंगाल", "दार्जिलिंग", "भरत डोंग", " "},
        {"West Bengal", "Darjeeling", "Sudip Mandal", "4", " ", "पश्चिम बंगाल", "दार्जिलिंग", "सुदीप मंडल", " "},
        {"West Bengal", "Darjeeling", "Sankar Malakar", "1", " ", "पश्चिम बंगाल", "दार्जिलिंग", "शंकर मालाकार", " "},
        {"West Bengal", "Darjeeling", "Saman Pathak", "2", " ", "पश्चिम बंगाल", "दार्जिलिंग", "समन पाठक", " "},
        {"West Bengal", "Darjeeling", "Dipak Kumar Roy", "4", " ", "पश्चिम बंगाल", "दार्जिलिंग", "दीपक कुमार रॉय", " "},
        {"West Bengal", "Darjeeling", "Amar Singh Rai", "2", " ", "पश्चिम बंगाल", "दार्जिलिंग", "अमर सिंह राय", " "},
        {"West Bengal", "Darjeeling", "Raju Bista", "1", " ", "पश्चिम बंगाल", "दार्जिलिंग", "राजू बिस्सा", " "},
        {"West Bengal", "Darjeeling", "Sunil Pandit", "4", " ", "पश्चिम बंगाल", "दार्जिलिंग", "सुनील पंडित", " "},
        {"West Bengal", "Darjeeling", "Rajesh Singh", "4", " ", "पश्चिम बंगाल", "दार्जिलिंग", "राजेश सिंह", " "},
        {"West Bengal", "Darjeeling", "Digbijay Mandal", "4", " ", "पश्चिम बंगाल", "दार्जिलिंग", "दिगबिजय मंडल", " "},
        {"West Bengal", "Darjeeling", "Nirode Chandra Adhikary", "3", " ", "पश्चिम बंगाल", "दार्जिलिंग", "निरोद चन्द्र विशेष", " "},
        {"West Bengal", "Darjeeling", "Ajay Dahal", "4", " ", "पश्चिम बंगाल", "दार्जिलिंग", "अजय दहल", " "},
        {"West Bengal", "Darjeeling", "Reseeka Chettri", "4", " ", "पश्चिम बंगाल", "दार्जिलिंग", "रसेका चेट्री", " "},
        {"West Bengal", "Darjeeling", "Harka Bahadur Chhetri", "2", " ", "पश्चिम बंगाल", "दार्जिलिंग", "हरका बहादुर छेत्री", " "},
        {"West Bengal", "Hooghly", "Ratna De", "3", " ", "पश्चिम बंगाल", "हुगली", "रत्न डे", " "},
        {"West Bengal", "Hooghly", "Sajal Adhikari", "2", " ", "पश्चिम बंगाल", "हुगली", "सजल अधकारी", " "},
        {"West Bengal", "Hooghly", "Dulal Chandra Hembram", "4", " ", "पश्चिम बंगाल", "हुगली", "दुलाल चंद्र हेम्ब्रम", " "},
        {"West Bengal", "Hooghly", "Pratul Chandra Saha", "1", " ", "पश्चिम बंगाल", "हुगली", "प्रतुल चंद्र साहा", " "},
        {"West Bengal", "Hooghly", "Vijay Kumar Mahato", "2", " ", "पश्चिम बंगाल", "हुगली", "विजय कुमार महतो", " "},
        {"West Bengal", "Hooghly", "Locket Chatterjee", "1", " ", "पश्चिम बंगाल", "हुगली", "लॉकेट चटर्जी", " "},
        {"West Bengal", "Hooghly", "Noor Hossain Mondal", "4", " ", "पश्चिम बंगाल", "हुगली", "नूर हुसैन मोंडल", " "},
        {"West Bengal", "Hooghly", "Pradip Saha", "2", " ", "पश्चिम बंगाल", "हुगली", "प्रदीप साहा", " "},
        {"West Bengal", "Howrah", "Ashraf Ali", "4", " ", "पश्चिम बंगाल", "हावड़ा", "अशरफ अली", " "},
        {"West Bengal", "Howrah", "Kanai Sit", "4", " ", "पश्चिम बंगाल", "हावड़ा", "कनाई बैठो", " "},
        {"West Bengal", "Howrah", "Shyam Prasad Ram", "4", " ", "पश्चिम बंगाल", "हावड़ा", "श्याम प्रसाद राम", " "},
        {"West Bengal", "Howrah", "Kashi Nath Malick", "4", " ", "पश्चिम बंगाल", "हावड़ा", "काशी नाथ मलिक", " "},
        {"West Bengal", "Howrah", "Chandra Sekhar Jha", "2", " ", "पश्चिम बंगाल", "हावड़ा", "चन्द्रशेखर झा", " "},
        {"West Bengal", "Howrah", "Samir Mondal", "4", " ", "पश्चिम बंगाल", "हावड़ा", "समीर मोंडल", " "},
        {"West Bengal", "Howrah", "Prasun Banerjee", "2", " ", "पश्चिम बंगाल", "हावड़ा", "प्रसून बनर्जी", " "},
        {"West Bengal", "Howrah", "Imtiaz Ahmed Mollah", "2", " ", "पश्चिम बंगाल", "हावड़ा", "इम्तियाज अहमद मोल्लाह", " "},
        {"West Bengal", "Howrah", "Sekhar Mondal", "4", " ", "पश्चिम बंगाल", "हावड़ा", "शेखर मोंडल", " "},
        {"West Bengal", "Howrah", "Shailendra Kumar Jaiswal", "2", " ", "पश्चिम बंगाल", "हावड़ा", "शैलेंद्र कुमार जायसवाल", " "},
        {"West Bengal", "Howrah", "Rantidev Sengupta", "1", " ", "पश्चिम बंगाल", "हावड़ा", "रंतिदेव सेनगुप्ता", " "},
        {"West Bengal", "Howrah", "Pankaj Gar", "4", " ", "पश्चिम बंगाल", "हावड़ा", "पंकज गर", " "},
        {"West Bengal", "Howrah", "Sisir Samanta", "4", " ", "पश्चिम बंगाल", "हावड़ा", "सिसिर सामंत", " "},
        {"West Bengal", "Howrah", "Suvra Ghosh", "1", " ", "पश्चिम बंगाल", "हावड़ा", "सुव्रा घोष", " "},
        {"West Bengal", "Howrah", "Sudarsan Manna", "3", " ", "पश्चिम बंगाल", "हावड़ा", "सुदर्शन मन्ना", " "},
        {"West Bengal", "Jalpaiguri", "Subal Chandra Roy", "4", " ", "पश्चिम बंगाल", "जलपाईगुड़ी", "सुबल चंद्र रॉय", " "},
        {"West Bengal", "Jalpaiguri", "Khushi Ranjan Mondal", "4", " ", "पश्चिम बंगाल", "जलपाईगुड़ी", "ख़ुशी रंजन मंडल", " "},
        {"West Bengal", "Jalpaiguri", "Harekrishna Sarkar", "2", " ", "पश्चिम बंगाल", "जलपाईगुड़ी", "हरेकृष्ण सरकार", " "},
        {"West Bengal", "Jalpaiguri", "Mani Kumar Darnal", "1", " ", "पश्चिम बंगाल", "जलपाईगुड़ी", "मणि कुमार दरनल", " "},
        {"West Bengal", "Jalpaiguri", "Haribhakta Sardar", "2", " ", "पश्चिम बंगाल", "जलपाईगुड़ी", "हरिभक्त सरदार", " "},
        {"West Bengal", "Jalpaiguri", "Subhash Biswas", "3", " ", "पश्चिम बंगाल", "जलपाईगुड़ी", "सुभाष विश्वास", " "},
        {"West Bengal", "Jalpaiguri", "Jayanta Kumar Roy", "1", " ", "पश्चिम बंगाल", "जलपाईगुड़ी", "जयंत कुमार रॉय", " "},
        {"West Bengal", "Jangipur", "Syed Qasim Rasool Ilyas", "3", " ", "पश्चिम बंगाल", "जंगीपुर", "सैयद कासिम रसूल इलियास", " "},
        {"West Bengal", "Jangipur", "Abhijit Mukherjee", "1", " ", "पश्चिम बंगाल", "जंगीपुर", "अभिजीत मुखर्जी", " "},
        {"West Bengal", "Jangipur", "Prasad Halder", "4", " ", "पश्चिम बंगाल", "जंगीपुर", "प्रसाद हलदर", " "},
        {"West Bengal", "Jangipur", "Mafuja Khatun", "1", " ", "पश्चिम बंगाल", "जंगीपुर", "मफूजा खातुन", " "},
        {"West Bengal", "Jangipur", "Shamimul Islam", "4", " ", "पश्चिम बंगाल", "जंगीपुर", "शमीमुल इस्लाम", " "},
        {"West Bengal", "Jangipur", "Avijit Khamaru", "4", " ", "पश्चिम बंगाल", "जंगीपुर", "अविजित खमरू", " "},
        {"West Bengal", "Krishnanagar", "Shaikh Khoda Box", "3", " ", "पश्चिम बंगाल", "कृष्णनगर", "शेख खोड़ा बॉक्स", " "},
        {"West Bengal", "Krishnanagar", "Bhaskar Paul", "4", " ", "पश्चिम बंगाल", "कृष्णनगर", "भास्कर पॉल", " "},
        {"West Bengal", "Krishnanagar", "Jayanta Debnath", "4", " ", "पश्चिम बंगाल", "कृष्णनगर", "जयंत देबनाथ", " "},
        {"West Bengal", "Krishnanagar", "Intaj Ali Shah", "1", " ", "पश्चिम बंगाल", "कृष्णनगर", "इंटाज अली शाह", " "},
        {"West Bengal", "Krishnanagar", "Jha Shantanu", "2", " ", "पश्चिम बंगाल", "कृष्णनगर", "झा शांतनु", " "},
        {"West Bengal", "Krishnanagar", "Nirapada Modak", "2", " ", "पश्चिम बंगाल", "कृष्णनगर", "निरापद मोदक", " "},
        {"West Bengal", "Krishnanagar", "Kalyan Chaubey", "1", " ", "पश्चिम बंगाल", "कृष्णनगर", "कल्याण चौबे", " "},
        {"West Bengal", "Maldaha Dakshin", "Pappu Ahamed", "2", " ", "पश्चिम बंगाल", "मालदा दक्षिण", "पप्पू अहमद", " "},
        {"West Bengal", "Maldaha Dakshin", "Manjur Alahi Munshi", "4", " ", "पश्चिम बंगाल", "मालदा दक्षिण", "मंजूर अलही मुंशी", " "},
        {"West Bengal", "Maldaha Dakshin", "Nasmul Hoque", "4", " ", "पश्चिम बंगाल", "मालदा दक्षिण", "नसमुल होके", " "},
        {"West Bengal", "Maldaha Dakshin", "Abu Hasem Khan Chowdhury", "1", " ", "पश्चिम बंगाल", "मालदा दक्षिण", "अबू हसीम खान चौधरी", " "},
        {"West Bengal", "Maldaha Dakshin", "Fulchand Mandal", "4", " ", "पश्चिम बंगाल", "मालदा दक्षिण", "फुलचंद मंडल", " "},
        {"West Bengal", "Maldaha Dakshin", "Hasim Akhtar", "2", " ", "पश्चिम बंगाल", "मालदा दक्षिण", "हसीम अख्तर", " "},
        {"West Bengal", "Maldaha Dakshin", "Sreerupa Mitra Chaudhury", "1", " ", "पश्चिम बंगाल", "मालदा दक्षिण", "श्रीरूपा मित्र चौधरी", " "},
        {"West Bengal", "Maldaha Dakshin", "Ratan Mandal", "4", " ", "पश्चिम बंगाल", "मालदा दक्षिण", "रतन मंडल", " "},
        {"West Bengal", "Maldaha Uttar", "Md. Dulal Hoque", "4", " ", "पश्चिम बंगाल", "मालदा उत्तर", "मो। दुलाल होके", " "},
        {"West Bengal", "Maldaha Uttar", "Isha Khan Choudhury", "1", " ", "पश्चिम बंगाल", "मालदा उत्तर", "ईशा खान चौधरी", " "},
        {"West Bengal", "Maldaha Uttar", "Nitya Das", "4", " ", "पश्चिम बंगाल", "मालदा उत्तर", "नित्या दास", " "},
        {"West Bengal", "Maldaha Uttar", "Subhash Barman", "2", " ", "पश्चिम बंगाल", "मालदा उत्तर", "सुभाष बर्मन", " "},
        {"West Bengal", "Maldaha Uttar", "Mausam Noor", "2", " ", "पश्चिम बंगाल", "मालदा उत्तर", "मौसम नूर", " "},
        {"West Bengal", "Maldaha Uttar", "Al Monowara Begam", "4", " ", "पश्चिम बंगाल", "मालदा उत्तर", "अल मोनोवारा बेगम", " "},
        {"West Bengal", "Maldaha Uttar", "Nimai Besara", "3", " ", "पश्चिम बंगाल", "मालदा उत्तर", "निमाई बेसरा", " "},
        {"West Bengal", "Maldaha Uttar", "Arjun Keshari", "2", " ", "पश्चिम बंगाल", "मालदा उत्तर", "अर्जुन केशरी", " "},
        {"West Bengal", "Maldaha Uttar", "Biswanath Ghosh", "2", " ", "पश्चिम बंगाल", "मालदा उत्तर", "बिस्वनाथ घोष", " "},
        {"West Bengal", "Maldaha Uttar", "Khagen Murmu", "1", " ", "पश्चिम बंगाल", "मालदा उत्तर", "खगेन मुर्मू", " "},
        {"West Bengal", "Murshidabad", "Mijanul Haque", "4", " ", "पश्चिम बंगाल", "मुर्शिदाबाद", "मिजानुल हक", " "},
        {"West Bengal", "Murshidabad", "Humayun Kabir Sekh", "4", " ", "पश्चिम बंगाल", "मुर्शिदाबाद", "हुमायूँ कबीर सेख", " "},
        {"West Bengal", "Murshidabad", "Abu Hena, S/O - Late Abdus Sattar", "1", " ", "पश्चिम बंगाल", "मुर्शिदाबाद", "अबू हेना, एस / ओ - स्वर्गीय अब्दुस सत्तार", " "},
        {"West Bengal", "Murshidabad", "Abu Hena, S/O - Sazzad Ali", "4", " ", "पश्चिम बंगाल", "मुर्शिदाबाद", "अबू हेना, एस / ओ - सज्जाद अली", " "},
        {"West Bengal", "Murshidabad", "Kamarujjaman Khandekar", "4", " ", "पश्चिम बंगाल", "मुर्शिदाबाद", "कमरुज्जमाँ खांडेकर", " "},
        {"West Bengal", "Murshidabad", "Humayun Kabir", "1", " ", "पश्चिम बंगाल", "मुर्शिदाबाद", "हुमायूँ कबीर", " "},
        {"West Bengal", "Murshidabad", "Abu Taher Khan", "2", " ", "पश्चिम बंगाल", "मुर्शिदाबाद", "अबू ताहिर खान", " "},
        {"West Bengal", "Raiganj", "Md. Salim", "2", " ", "पश्चिम बंगाल", "रायगंज", "मो। सलीम", " "},
        {"West Bengal", "Raiganj", "Churka Murmu", "4", " ", "पश्चिम बंगाल", "रायगंज", "चुरका मुर्मू", " "},
        {"West Bengal", "Raiganj", "Kumaresh Sarkar", "4", " ", "पश्चिम बंगाल", "रायगंज", "कुमारेश सरकार", " "},
        {"West Bengal", "Raiganj", "Deepa Dasmunsi", "1", " ", "पश्चिम बंगाल", "रायगंज", "दीपा दासमुंशी", " "},
        {"West Bengal", "Raiganj", "Agarwal Kanaialal", "2", " ", "पश्चिम बंगाल", "रायगंज", "अग्रवाल कनियालाल", " "},
        {"West Bengal", "Raiganj", "Binoy Kumar Das", "3", " ", "पश्चिम बंगाल", "रायगंज", "बिनॉय कुमार दास", " "},
        {"West Bengal", "Raiganj", "Sujan Krishna Paul", "2", " ", "पश्चिम बंगाल", "रायगंज", "सुजान कृष्ण पॉल", " "},
        {"West Bengal", "Raiganj", "Lakshman Murmu", "4", " ", "पश्चिम बंगाल", "रायगंज", "लक्ष्मण मुर्मू", " "},
        {"West Bengal", "Raiganj", "Raju Paul", "2", " ", "पश्चिम बंगाल", "रायगंज", "राजू पॉल", " "},
        {"West Bengal", "Raiganj", "Md. Sahajan Badsha", "4", " ", "पश्चिम बंगाल", "रायगंज", "एमडी। सहजन बादशाह", " "},
        {"West Bengal", "Raiganj", "Debasree Chaudhuri", "1", " ", "पश्चिम बंगाल", "रायगंज", "देबाश्री चौधरी", " "},
        {"West Bengal", "Ranaghat", "Gautam Ray", "4", " ", "पश्चिम बंगाल", "रानाघाट", "गौतम रे", " "},
        {"West Bengal", "Ranaghat", "Biswas Rama", "2", " ", "पश्चिम बंगाल", "रानाघाट", "बिस्वास राम", " "},
        {"West Bengal", "Ranaghat", "Minati Biswas", "1", " ", "पश्चिम बंगाल", "रानाघाट", "मिनती बिस्वास", " "},
        {"West Bengal", "Ranaghat", "Bidyut Biswas", "4", " ", "पश्चिम बंगाल", "रानाघाट", "बिद्युत बिस्वास", " "},
        {"West Bengal", "Ranaghat", "Paresh Haldar", "4", " ", "पश्चिम बंगाल", "रानाघाट", "परेश हलधर", " "},
        {"West Bengal", "Ranaghat", "Jagannath Sarkar", "1", " ", "पश्चिम बंगाल", "रानाघाट", "जगन्नाथ सरकार", " "},
        {"West Bengal", "Sreerampur", "Mangal Sarkar", "4", " ", "पश्चिम बंगाल", "श्रीरामपुर", "मंगल सरकार", " "},
        {"West Bengal", "Sreerampur", "Pradyut Chowdhuri", "3", " ", "पश्चिम बंगाल", "श्रीरामपुर", "प्रदुत चौधरी", " "},
        {"West Bengal", "Sreerampur", "Debjit Sarkar", "1", " ", "पश्चिम बंगाल", "श्रीरामपुर", "देबजीत सरकार", " "},
        {"West Bengal", "Sreerampur", "Avash Munshi", "4", " ", "पश्चिम बंगाल", "श्रीरामपुर", "अविनाश मुंशी", " "},
        {"West Bengal", "Sreerampur", "Kashinath Murmu", "4", " ", "पश्चिम बंगाल", "श्रीरामपुर", "काशीनाथ मुर्मू", " "},
        {"West Bengal", "Sreerampur", "Lachman Rajak", "4", " ", "पश्चिम बंगाल", "श्रीरामपुर", "लछमन रजक", " "},
        {"West Bengal", "Sreerampur", "Debabrata Biswas", "1", " ", "पश्चिम बंगाल", "श्रीरामपुर", "देवव्रत बिस्वास", " "},
        {"West Bengal", "Sreerampur", "Prabhash Chandra Kar", "4", " ", "पश्चिम बंगाल", "श्रीरामपुर", "प्रभाष चंद्र कर", " "},
        {"West Bengal", "Uluberia", "Susanta Kumar Dalui", "4", " ", "पश्चिम बंगाल", "उलूबेरिया", "सुशांत कुमार दलुई", " "},
        {"West Bengal", "Uluberia", "Amal Barman", "4", " ", "पश्चिम बंगाल", "उलूबेरिया", "अमल बर्मन", " "},
        {"West Bengal", "Uluberia", "Durgadas Hajra", "4", " ", "पश्चिम बंगाल", "उलूबेरिया", "दुर्गादास हाजरा", " "},
        {"West Bengal", "Uluberia", "Joy Banerjee", "1", " ", "पश्चिम बंगाल", "उलूबेरिया", "जॉय बनर्जी", " "},
        {"West Bengal", "Uluberia", "Alimuddin Nazir", "4", " ", "पश्चिम बंगाल", "उलूबेरिया", "अलीमुद्दीन नज़ीर", " "},
        {"West Bengal", "Uluberia", "Shoma Ranisree Roy", "1", " ", "पश्चिम बंगाल", "उलूबेरिया", "शोमा रानीश्री रॉय", " "},
};

}