/* Auto-generated file from db2MPjava.php*/

    package in.filternet.jantamalik.Rajya;

    public final class Bihar {

    	public static final String[][] MLAs = {

		{"Bihar", "Agiaon (SC)", "Prabhu Nath Prasad", "बिहार", "अगिआव (एस सी)", "Prabhu Nath Prasad",  "  9471096769", "", "", "", "", " Village-Devdi Post.Gadhani Thana-Charpokhari, Dist. Bhojpur "},
		{"Bihar", "Alamnagar", "Narendra Narayan Yadav", "बिहार", "आलमनगर", "Narendra Narayan Yadav",  "  7250351324", "", "", "", "", " House No.42, Village-Balatol, Post-Nayatola, Thana-Puraini, Dist-Madhepura, Pin-852116 "},
		{"Bihar", "Alauli (SC)", "Chandan Kumar", "बिहार", "अलौली (एस सी)", "Chandan Kumar",  "  7549356931", "", "", "", "", " Vill. & Post. Khargi Tirasi, Dist. Khagaria "},
		{"Bihar", "Alinagar", "Abdul Bari Siddiqui", "बिहार", "अलीनगर", "Abdul Bari Siddiqui",  "  9471000707", "", "", " abdulbarisiddiquimla@gmail.com", "", " Village-Rupaspur Circle ,P.S. Alinagar dist-Darbhanga, 847405 "},
		{"Bihar", "Amarpur", "Janardan Manjhi", "बिहार", "अमरपुर", "Janardan Manjhi",  "  9431800555", "", "", "", "", " Village Dhaliya, Post and Thana Bauri, Dist Banka 813104 "},
		{"Bihar", "Amnour", "Shatrudhan Tiwari", "बिहार", "अमनौर", "Shatrudhan Tiwari",  "  9507765474", "", "", " chakarbaba7@gmail.com", "", " Vill. Sirisia Jagdev, Post. Hussepur, PS. Amnour, Dist. Saran "},
		{"Bihar", "Amour", "Abdul Jalil Mastan", "बिहार", "अमौर", "Abdul Jalil Mastan",  "  7250140188", "", "", "", "", " Vill. Silla Raghunath Pur Tola Sirsi, Post. Asja, PS. Rauta, Dist. Purnia "},
		{"Bihar", "Araria", "Abidur Rahman", "बिहार", "अररिया", "Abidur Rahman",  "  9431087766", "", "", "", "", " Village & Post Office- Chandardai, Thana- Araria, R.S. Dist-Araria Pin No- 854312 Bihar "},
		{"Bihar", "Arrah", "Mohamad Nawaz Alam", "बिहार", "आरा", "Mohamad Nawaz Alam",  "  9835059616", "", "", " mdnawaz.alamara@gmail.com", "", " Village & Post Office- Daulatpur, P.S- Arra, Dist- Bhojpur "},
		{"Bihar", "Arwal", "Ravindra Singh", "बिहार", "अरवल", "Ravindra Singh",  "  9931403728", "", "", "", "", " Mahmadpur Tola Hicchan Bigha, P.O- Singhari. P.S- Daudnagar Dist- Aurangabad "},
		{"Bihar", "Asthawan", "Jitendra Kumar", "बिहार", "अस्थावां", "Jitendra Kumar",  "  9431815846", "", "", "", "", " Village Utrathu ka tola dharampur, P.O. Utrathu, P.S. Bind, Dist. Nalanda "},
		{"Bihar", "Atri", "Kunti Devi", "बिहार", "अतरी", "Kunti Devi",  "  9801702946", "", "", "", "", " Vill. & Post. Bathana, Dist. Gaya "},
		{"Bihar", "Aurai", "Surendra Kumar", "बिहार", "औराई", "Surendra Kumar",  "  9572040502", "", "", " drsurendr2044@gmail.com", "", " Resident Of Gram Kalyanpur, Post Office Chandwara, Thana Aurai, Distt. Muzaffarpur, Bihar "},
		{"Bihar", "Aurangabad", "Anand Shankar Singh", "बिहार", "औरंगाबाद", "Anand Shankar Singh",  "  8002854499", "", "", " anand_xiss@yahoo.co.in", "", " Vill. Rampura, Post-Ramvilas Nagar, Dist.Aurangabad "},
		{"Bihar", "Babubarhi", "Kapil Deo Kamat", "बिहार", "बाबूबरही", "Kapil Deo Kamat",  "  9973535120", "", "", "", "", " Vill. Motnaje, Post Lataniya, Thana Lataniya, Dist. MAdhubani "},
		{"Bihar", "Bachhwara", "Ramdeo Rai", "बिहार", "बछवाड़ा", "Ramdeo Rai",  "  9709881598", "", "", "", "", " Vill. Sherpur Sahilori, Post. Jayantigram, PS. Bhagwanpur, Dist. Begusarai "},
		{"Bihar", "Bagaha", "Raghaw Sharan Pandey", "बिहार", "बगहा", "Raghaw Sharan Pandey",  "  09810609404", "", "", " raghaw_pandey@hotmail.com", "", " Resident Of Village Rasoli, Post Dhobani, Thana Loriya, Distt. Paschim Champaran, Pin Code. 845453 "},
		{"Bihar", "Bahadurganj", "M.d. Tauseef Alam", "बिहार", "बहादुरगंज", "M.d. Tauseef Alam",  "  9431216786", " 9431219141", "", "", "", " Village- Bhadgaon Milik, Post Office- Lohagada Hat, Thana- Bahadurganj, Dist- Kishanganj 855101 "},
		{"Bihar", "Bahadurpur", "Bhola Yadav", "बिहार", "बहादुरपुर", "Bhola Yadav",  "  06122580848", " 7250090555", "", " bholayadavrjd@gmail.com", "", " R/O.VPO.-Kapchhahi, PS.-Bahadurpur, District-Darbhanga "},
		{"Bihar", "Baikunthpur", "Mithilesh Kumar Tiwari", "बिहार", "बैकुंठपुर", "Mithilesh Kumar Tiwari",  "  09431035735", "", "", " tiwarimithlesh.baba@gmail.com", "", " Vill. and Post Dumariya, Thana Mahommadpur, Distt. Gopalganj "},
		{"Bihar", "Baisi", "Abdus Subhan", "बिहार", "बैसी", "Abdus Subhan",  "  9430522257", "", "", " hajeabdussubhan786@gmail.com", "", " Village-Charaiya, post-Charaiya, thana-Baisi, Dist-Purnia "},
		{"Bihar", "Bajpatti", "Ranju Geeta", "बिहार", "बाजपट्टी", "Ranju Geeta",  "  9473400227", " 9430617931", "", "", "", " Resident Of Gram Basaha, Post Madhuban Basaha, Thana Bajpatti, Distt. Sitamarhi "},
		{"Bihar", "Bakhri (SC)", "Upendra Paswan", "बिहार", "बखरी (एस सी)", "Upendra Paswan",  "  9631400349", "", "", "", "", " Village & Post- Kumharso, Thana Gadhpur, Dist- Begusarai "},
		{"Bihar", "Bakhtiarpur", "Ranvijay Singh", "बिहार", "बख्तियारपुर", "Ranvijay Singh",  "  9771045321", "", "", "", "", " Vill.Tekabigha, Post-Lakhanpura, Thana-Bakhtiarpur, Dist.Patna, Pin-803202 "},
		{"Bihar", "Balrampur", "Mahboob Alam", "बिहार", "बलरामपुर", "Mahboob Alam",  "  8521116610", "", "", "", "", " Vill. and Post Shivnandpur, Thana Aabarpur, Dist. Katihar "},
		{"Bihar", "Baniapur", "Kedar Nath Singh", "बिहार", "बनियापुर", "Kedar Nath Singh",  "  9431812521", "", "", "", "", " Masrak, Saran, Bihar "},
		{"Bihar", "Banka", "Ram Narayan Mandal", "बिहार", "बांका", "Ram Narayan Mandal",  "  9473192725", "", "", " ramnarayanmandal1953@gmail.com", "", " Village Jitarpur, Post Maheshdih, Thana District Banka "},
		{"Bihar", "Bankipur", "Nitin Navin", "बिहार", "बांकीपुर", "Nitin Navin",  "  9431011451", "", "", " nitin.nabin1@gmail.com", "", " 137, M.L.A., Flat, Post-GPO Patna, Thana-Kotwali, Dist.Patna, State-Bihar "},
		{"Bihar", "Banmankhi (SC)", "Krishna Kumar Rishi", "बिहार", "बनमखी (एस सी)", "Krishna Kumar Rishi",  "  9431800562", "", "", " 59banmankhividhansabha@gmail.com", "", " Vill.+Post-Rasad, Thana-Banmankhi, Dist.Purnia "},
		{"Bihar", "Barachatti (SC)", "Samta Devi", "बिहार", "बाराचट्टी (एस सी)", "Samta Devi",  "  9955948707", "", "", "", "", " Village- Gajragarh, P.O & P.S- Barachatti , Dist-Gaya "},
		{"Bihar", "Barari", "Neeraj Kumar", "बिहार", "बरारी", "Neeraj Kumar",  "  8471281546", "", "", "", "", " Village and Post Office- Pothiya, Distt.- Katihar, Bihar Pin No. 854114 "},
		{"Bihar", "Barauli", "Md Nematullah", "बिहार", "बरौली", "Md Nematullah",  "  9471810596", "", "", "", "", " Gram-Hatkhamba, post-Koirigava, DSist- Siwan "},
		{"Bihar", "Barbigha", "Sudarshan Kumar", "बिहार", "बारबीघा", "Sudarshan Kumar",  "  9955333333", "", "", "", "", " Vill+P.O. hathiyawa, P.S.+Dist. Shekhpura Bihar Pin 811105 "},
		{"Bihar", "Barh", "Gyanendra Kumar Singh", "बिहार", "बाढ़", "Gyanendra Kumar Singh",  "  9431042146", "", "", "", "", " Vill.Sakunpura, Post-Khushrupur, Thana-Salimpur, Dist.Patna, Pincode-803202 "},
		{"Bihar", "Brahmpur", "Shambhu Nath Yadav", "बिहार", "ब्रह्मपुर", "Shambhu Nath Yadav",  "  9661352225", "", "", " wwwsmy7@gamil.com", "", " Village-Chakki Lahna Bhola Dera P.S.Brahmapur Dist-Buxer Bihar "},
		{"Bihar", "Barhara", "Saroj Yadav", "बिहार", "बरहरा", "Saroj Yadav",  "  9471246715", "", "", " sarojkumar303@gmail.com", "", " Village- Keshopur, Post Office- Badhara, Thana- Badhara, Dist- Bhojpur "},
		{"Bihar", "Barharia", "Shyam Bahadur Singh", "बिहार", "बरहरिया", "Shyam Bahadur Singh",  "  9471004655", "", "", "", "", " VPO.-Tarwara, PS.-G.B.Nagar, District-Siwan, Bihar "},
		{"Bihar", "Baruraj", "Nand Kumar Rai", "बिहार", "बरुराज", "Nand Kumar Rai",  "  9661727528", " 9431238760", "", "", "", " Resident Of Gram Sadha Dumber, Post Motipur, Thana Motipur, Distt. Muzaffarpur, Bihar "},
		{"Bihar", "Bathnaha (SC)", "Dinkar Ram", "बिहार", "बथनाहा (एस सी)", "Dinkar Ram",  "  9431025951", "", "", " dinkarrammla24bihar@gmail.com", "", " Village Khairwa, PO. Majorganj, District-Sitamarhi "},
		{"Bihar", "Begusarai", "Amita Bhushan", "बिहार", "बेगूसराय", "Amita Bhushan",  "  9199824377", "", "", " amybhushan@gmail.com", "", " Swami Vivekanand Path,P.O- Pradhan, Bhagalpur, Dist Bhagalpur Pin Code- 812001 "},
		{"Bihar", "Belaganj", "Surendra Prasad Yadav", "बिहार", "बेलागंज", "Surendra Prasad Yadav",  "  9431247326", "", "", "", "", " Village- Chiraiya Town, Gaya, PO & Thana- Rampur, Dist- Gya "},
		{"Bihar", "Beldaur", "Panna Lal Singh Patel", "बिहार", "बेलदौर", "Panna Lal Singh Patel",  "  9431231033", "", "", " mlapannalal@gmail.com", "", " Vill & P.O. Pansalwa, P.S. baisdaur Dist. Khagaria "},
		{"Bihar", "Belhar", "Ramdeo Yadav", "बिहार", "बेलहार", "Ramdeo Yadav",  "  9546171042", "", "", "", "", " Village-Dhanjorva,Post-Jhikuliya,Thana-Belhar,District-Banka "},
		{"Bihar", "Belsand", "Sunita Singh", "बिहार", "बेलसंद", "Sunita Singh",  "  9471001542", "", "", " sunitasinghmla@gmail.com", "", " R/o Raghunathpath, Raghunathpatti, Shitamadi, Bihar "},
		{"Bihar", "Benipatti", "Bhawana Jha", "बिहार", "बेनीपट्टी", "Bhawana Jha",  "  9470051222", "", "", " bhawana639@gmail.com", "", " R/O.-43/60, Office Flat Near Hartali More, Boli Road Patna-800001 "},
		{"Bihar", "Benipur", "Sunil Choudhary", "बिहार", "बेनीपुर", "Sunil Choudhary",  "  06272275000 ", " 9431594315", "", " choudharysunil1969@gmail.com", "", " Vill.+ Post Nehra, Thana Manigachhi, Dist. Darbhanga 847233 "},
		{"Bihar", "Bettiah", "Madan Mohan Tiwari", "बिहार", "बेतिया", "Madan Mohan Tiwari",  "  9431275421 ", " 8002081182", "", "", "", " Vill. Rani Pakari, Post Pipara Pakari P.s. Bettiah Muffassil, Distt. West Champaran (Bihar) Pin - 845438 "},
		{"Bihar", "Bhabua", "Rinki Rani Pandey", "बिहार", "भाबुआ", "Rinki Rani Pandey",  "  9431680916", "", "", "", "", " Vill.+P.O.+P.S.-Bhagwanpur, Dist.Kaimur "},
		{"Bihar", "Bhagalpur", "Ajeet Sharma", "बिहार", "भागलपुर", "Ajeet Sharma",  "  9431214911", "", "", " ajeetsharma_54@yahoo.in", "", " Shiv Bhawan Campus, S.S. Sarai Road, PS. Ishakchak, Dist. Bhagalpur "},
		{"Bihar", "Bhorey (SC)", "Anil Kumar", "बिहार", "भोरे (एस सी)", "Anil Kumar",  "  9931280133", "", "", "", "", " Gram-Mahuava, Post-Vijayipur, Thana-Vijayipur, Dist-Gopalganj, Bihar "},
		{"Bihar", "Bibhutipur", "Rambalak Singh", "बिहार", "विभूतिपुर", "Rambalak Singh",  "  9431010807", " 8292918413", "", " rbsinghmla@gmail.com", "", " Vill. Sindhiya Bujurg, Post Sindhiya Ghat, P.S Bibhutipur, Dist. Samastipur "},
		{"Bihar", "Bihariganj", "Niranjan Kumar Mehta", "बिहार", "बिहारीगंज", "Niranjan Kumar Mehta",  "  9431657271", " 9801577116", "", "", "", " Vill. & Post. Madhuban, PS. Bihariganj, Distt. Madhepura, Pin No. 852101 "},
		{"Bihar", "Biharsharif", "Dr.sunil Kumar", "बिहार", "बिहारशरीफ़", "Dr.sunil Kumar",  "  06112-232210", "", "", " drsunilmla@gmail.com", "", " Mohalla Ashanagar, Post Sohsarai, P.S. Sohasarai, Dist. Nalanda 803118 "},
		{"Bihar", "Bihpur", "Varsha Rani", "बिहार", "बिहपुर", "Varsha Rani",  "  9931894749", "", "", " varsharani.sk.15@gmail.com", "", " Vill.Raghopur, Post-Raghopur, Thana-Kharik, Dist.Bhagalpur, Bihar "},
		{"Bihar", "Bikram", "Siddharth", "बिहार", "बिक्रम", "Siddharth",  "  9570363680", " 9852144220", "", "", "", " Vill. Arhara P.O. Arhara, P.S. Bihata, Patna Bihar "},
		{"Bihar", "Bisfi", "Faiyaz Ahmad", "बिहार", "बिस्फी", "Faiyaz Ahmad",  "  9471650157", "", "", " drfaiyazahmad786@gmail.com", "", " Raghonagar, Post Bhoaada, Dist. Madhubani, Pin 847212 "},
		{"Bihar", "Bochaha (SC)", "Beby Kumari", "बिहार", "बोचहां (एस सी)", "Beby Kumari",  "  9709584262", "", "", " babykumari422@gmail.com", "", " Mithnapur Lala, Post Office- Ramna, Thana- Mithanpur, Dist- Muzaffarpur "},
		{"Bihar", "Bodh Gaya (SC)", "Kumar Sarvjeet", "बिहार", "बोध गया (एस सी)", "Kumar Sarvjeet",  "  9431229898", "", "", " kumarsarvjeet@gmail.com", "", " Mastipur Bodhgaya, Post. & PS. Bodh Gaya, Dist. Gaya "},
		{"Bihar", "Buxar", "Sanjay Kumar Tiwari Alias Munna Tiwari", "बिहार", "बक्सर", "Sanjay Kumar Tiwari Alias Munna Tiwari",  "  9431433758", "", "", "", "", " Village+P.O.-Koran Sarai ,P.S.-Koransarai Dist-Buxer "},
		{"Bihar", "Chainpur", "Brij Kishor Bind", "बिहार", "चैनपुर", "Brij Kishor Bind",  "  9431680473", "", "", "", "", " Vill. Jaitpur Khurd, Jaitpur Kala, P.S. Bhagwanpur, Dist. Kaimur "},
		{"Bihar", "Chakai", "Savitri Devi", "बिहार", "चकई", "Savitri Devi",  "  9430774126", "", "", "", "", " Village Sirayndih, Post Saraswati Watpar, Thana chakai, Dist. Jamui "},
		{"Bihar", "Chanpatia", "Prakash Rai", "बिहार", "चनपटिया", "Prakash Rai",  "  9431212011", "", "", " bettiah.pr@gmail.com", "", " Resident Of Supriya Cinema Road, Ward No. 35, Thana Betiya Nagar, Distt. Paschim Champaran, Pin Code 845438 "},
		{"Bihar", "Chapra", "Dr. C.N. Gupta", "बिहार", "छपरा", "Dr. C.N. Gupta",  "  9431218881", "", "", " drcngupta2012@gmail.com", "", " Muz.-Bhagwan bazar, Thana-Bhagwan bazar, Chapra Dist-Saran (Pin Code).841301 "},
		{"Bihar", "Chenari (SC)", "Lallan Paswan", "बिहार", "चेनारी (एस सी)", "Lallan Paswan",  "  9431800501", " 9431483540", "", " lalanp16@gmail.com", "", " Village Badui, P.O. Darigaon, P.S. Sasaram, Dist. Rohtas "},
		{"Bihar", "Cheria Bariarpur", "Kumari Manju Verma", "बिहार", "चेरिया बरिआरपुर", "Kumari Manju Verma",  "  9473199433", "", "", " vermakumarimanju@gmail.com", "", " Vill.Arjun Tola, P.O.-Shreepur, Thana-Cheria, Bariyapur, Dist.Begusarai "},
		{"Bihar", "Chhatapur", "Niraj Kumar Singh", "बिहार", "छातापुर", "Niraj Kumar Singh",  "  9431243590", "", "", "", "", " Resident Of Ward No. 18, Gangajala, Post Saharsa, Distt. Saharsa "},
		{"Bihar", "Chiraia", "Lal Babu Prasad Gupta", "बिहार", "चिरईया", "Lal Babu Prasad Gupta",  "  8002753890", "", "", " lalbabuprasadgupta3333@gmail.com", "", " Village and Post-Bakhari Bazar, Thana- Patahi, Dist- East Champaran, Bihar "},
		{"Bihar", "Danapur", "Asha Devi", "बिहार", "दानापुर", "Asha Devi",  "  9431023934", "", "", "", "", " Vill.Sarari, Post-Neura(Khegaru), Thana-Sahapur, Dist.Patna, Pin code- 801113 "},
		{"Bihar", "Darauli (SC)", "Satydev Ram", "बिहार", "दरौली (एस सी)", "Satydev Ram",  "  9934488133", "", "", "", "", " Vill. And Post Krishanpal, Ditt. Siwan "},
		{"Bihar", "Daraundha", "Karnjeet Singh Alias Vyas Singh", "बिहार", "दरौंदा", "Karnjeet Singh Alias Vyas Singh",  "  9431207520", "", "", " kr905643@gmailcom", "", " Mo. Fatepur,Ward No- 33 P.S. - Siwan Nagar, Dist-Siwan "},
		{"Bihar", "Darbhanga", "Sanjay Saraogi", "बिहार", "दरभंगा", "Sanjay Saraogi",  "  06272-247604 ", " 9431219050", "", " sanjaysaraogimla@gmail.com", "", " Mohalla Ram Chowk, Gandhi Chowk, Ward No.7, Post Darbhanga, Thana Nagar, Distt. Darbhanga "},
		{"Bihar", "Darbhanga Rural", "Lalit Kumar Yadav", "बिहार", "दरभंगा ग्रामीण", "Lalit Kumar Yadav",  "  9431821873", " 06272-251410", "", " mlalalitkryadav@gmail.com", "", " Gram-tardih, Fakirana, post-kaithwar, thana-sakatpur,dist-darbhanga, bihar, 847204 "},
		{"Bihar", "Dehri", "Satyanarayan Singh", "बिहार", "डेहरी", "Satyanarayan Singh",  "  9162388151", " 9431815151", "", " satyanarainsinghmla@gmail.com", "", " Mohalla Canal Road, PO. & PS. Dehri, Dist. Rohtas Bihar "},
		{"Bihar", "Dhaka", "Faisal Rahman", "बिहार", "ढाका", "Faisal Rahman",  "  9431233700", "", "", " faisalrahman.jdu.dhaka@gmail.com", "", " Vill. Sapahi, Post. Jhitkathi, PS. Dhaka, Dist. East Champaran "},
		{"Bihar", "Dhamdaha", "Leshi Singh", "बिहार", "धमदाहा", "Leshi Singh",  "  8292657195", " 06454-228893", "", " jdupurnia94312@gmail.com", "", " Village-Sarasi, Post Office-Sarasi, Thana-Sarsi, Dist-Purnea, Pin No-854306 "},
		{"Bihar", "Dhauraiya (SC)", "Manish Kumar", "बिहार", "धोरैया (एस सी)", "Manish Kumar",  "  9470404040", "", "", " mkumarmla@gmail.com", "", " RBI Colony Bhutnath Road, P.O. Bhadurpur, P.S. Agamkuan, Dist. Patna "},
		{"Bihar", "Digha", "Sanjeev Chaurasiya", "बिहार", "दीघा", "Sanjeev Chaurasiya",  "  9431020110", "", "", " sanjivchaurasia06@yahoo.com", "", " Arya Bhawan, Mundar Saha Cold Storage, Khajpura Baily Road, Post-B.V.College, Thana-Shastrinagar, Patna "},
		{"Bihar", "Dinara", "Jay Kumar Singh", "बिहार", "दिनारा", "Jay Kumar Singh",  "  9199449228", "", "", " jaikumarsinghbihar@gmail.com", "", " Village Parsdiha, P.O. Dumri (Shahpur), P.S. Shivsagar, Dist. Rohtas (Bihar) pin 82111 "},
		{"Bihar", "Dumraon", "Dadan Yadav", "बिहार", "डुमरांव", "Dadan Yadav",  "  9431027411", "", "", " dadanyadav786@gmail.com", "", " Village-Samhaar P.o.Nenua P.S.Dumrao Dist-Buxer Pin-802119 "},
		{"Bihar", "Ekma", "Manoranjan Singh", "बिहार", "एकमा", "Manoranjan Singh",  "  9471004848", "", "", " smanoranjan@gmail.com", "", " Vill. Bhajauna, PO. Nachap, PS. Manjhi, Dist. Saran at Chapra, Bihar "},
		{"Bihar", "Fatuha", "Dr. Ramanand Yadav", "बिहार", "फतुहा", "Dr. Ramanand Yadav",  "  9835044621", "", "", " ramanandyadavjd@gmail.com", "", " Vill. Mauzipur, P.O. Fatuha, P.S. Patuha, Dist. Patna 803201 "},
		{"Bihar", "Forbesganj", "Vidya Sagar Keshri", "बिहार", "फारबिसगंज", "Vidya Sagar Keshri",  "  9470487987", "", "", " vidyasagarkeshari@gmail.com", "", " Ward No.03, Forbesganj, Post+Thana+Nagar Parishad-Forbesganj, Dist.Araria, Bihar,Pin-854318 "},
		{"Bihar", "Gaighat", "Maheshwar Prasad Yadav", "बिहार", "गायघाट", "Maheshwar Prasad Yadav",  "  9431239019", "", "", "", "", " Village- Kumharol Tola Motnaje, Post Office- Jauta, Block- Gaighat, Dsit- Muzaffarpur, "},
		{"Bihar", "Garkha (SC)", "Muneshwar Chaudhary", "बिहार", "गरखा (एस सी)", "Muneshwar Chaudhary",  "  09431479103", "", "", "", "", " Vill. Mithepur, Post. & PS. Garkha, Dist. Saran (Bihar), Pin Code 841311 "},
		{"Bihar", "Gaya Town", "Prem Kumar", "बिहार", "गया टाउन", "Prem Kumar",  "  9473400422", "", "", " premkumar@gmail.com", "", " Makhkot Ganj, Mahavir Place Gali Gaya-823001 "},
		{"Bihar", "Ghosi", "Krishna Nandan Prasad Verma", "बिहार", "घोसी", "Krishna Nandan Prasad Verma",  "  7739996228", " 9431271328 ", "", "", "", " Village-Sugaon P.o.Tehta P.s.-Makhdumpur Dist-Jhanabad "},
		{"Bihar", "Gobindpur", "Purnima Yadav", "बिहार", "गोबिंदपुर", "Purnima Yadav",  "  9431227228", "", "", "", "", " Mahalla Prasad Bigha po. Nawada Thana, Nawada Dist, Bihar "},
		{"Bihar", "Goh", "Manoj Kumar", "बिहार", "गोह", "Manoj Kumar",  "  9431103200", "", "", " manojsharma.goh@gmail.com", "", " Vill+Post-Bithra, Thana-Kurtha, Dist.Arwal, Bihar "},
		{"Bihar", "Gopalganj", "Subash Singh", "बिहार", "गोपालगंज", "Subash Singh",  "  9431217130", "", "", " ssinghmla-101@gmail.com", "", " Village- Khavajepur, Post Office- Khawajepur, Thana- Jodpur, Dist- Gopalganj Bihar Pin No- 841428 "},
		{"Bihar", "Gopalpur", "Narendra Kumar Neeraj", "बिहार", "गोपालपुर", "Narendra Kumar Neeraj",  "  9931853095", "", "", "", "", " Vill.Parbanta, P.O.-Ismailpur, Thana-Parbanta, Dist.Bhagalpur "},
		{"Bihar", "Gaura Bauram", "Madan Sahni", "बिहार", "गौरा बौरम", "Madan Sahni",  "  9471006025", "", "", "", "", " Vill. And Post Kharajpur, Thana Bhadurpur, Anumandal Sadar, Distt. Darbhanga, Bihar, Pin No. 846003 "},
		{"Bihar", "Goriyakothi", "Satyadeo Prasad Singh", "बिहार", "गोरियाकोठी", "Satyadeo Prasad Singh",  "  9470615040", "", "", "", "", " Gram-Kodiya, tola Bhalan miya, post- Kodiya, Bhagwanpur, dist-Suwan "},
		{"Bihar", "Govindganj", "Raju Tiwari", "बिहार", "गोविंदगंज", "Raju Tiwari",  "  9471005499", "", "", "", "", " R/O.-Village-Kamalua, PO.-Mamarkha Bhaiya, PS.-Malahi, District-East Champaran "},
		{"Bihar", "Gurua", "Rajiv Nandan", "बिहार", "गुरुआ", "Rajiv Nandan",  "  9431083177", "", "", " rajivnandanbjp@gmail.com", "", " Village-Gulriyachak P.o.-Simuaara ,P.s.-Tikari, Dist-Gaya Pin-824236 "},
		{"Bihar", "Hajipur", "Awadhesh Singh", "बिहार", "हाजीपुर", "Awadhesh Singh",  "  9801103287", "", "", " awadhesh.hajipur@gmail.com", "", " Village and Post Panapur Dharampur, Thana Bindupur, Dist. Vaishali, Bihar "},
		{"Bihar", "Harlakhi", "Sudhanshu Shekhar", "बिहार", "हरलाखी", "Sudhanshu Shekhar",  "  8809041093", " 9801720403 ", "", " sudhanshu.31harlakhi@gmail.com", "", " Village & Post -Utra P.s.-Saharghat Dist-Madhubani (Bihar)Pin -847308 "},
		{"Bihar", "Harnaut", "Hari Narayan Singh", "बिहार", "हरनौत", "Hari Narayan Singh",  "  9431821883", "", "", "", "", " Vill. Maansingpur, Po. Bodhibigha Ramghat, Ps. Nagarnusa, Dist. Nalanda "},
		{"Bihar", "Harsidhi (SC)", "Rajendra Kumar", "बिहार", "हरसिद्धि (एस सी)", "Rajendra Kumar", "", "", "", " 9934608512", "", " Gram-Mathurapur, Post-Mathurapur, Thana- Turkosiya, Dist- Purvi Champaran, Bihar "},
		{"Bihar", "Hasanpur", "Raj Kumar Rai", "बिहार", "हसनपुर", "Raj Kumar Rai",  "  9473400382", "", "", "", "", " Village +P.o.-Belsandi Bithan Dist-Samstipur "},
		{"Bihar", "Hathua", "Ram Sewak Singh", "बिहार", "हथुआ", "Ram Sewak Singh",  "  9973975818", "", "", "", "", " Vill. Asanand Tola, Post Blesra, Thana Uchkagaon, Distt. Gopalganj, Bihar-841438 "},
		{"Bihar", "Hayaghat", "Amar Nath Gami", "बिहार", "हायाघाट", "Amar Nath Gami",  "  9471006008", "", "", "", "", " Resident Of Kashisthan Masraf Bazar, Post Lalbag, Distt. Darbhanga, Pin Code 846004 "},
		{"Bihar", "Hilsa", "Atri Muni Alias Shakti Singh Yadav", "बिहार", "हिलसा", "Atri Muni Alias Shakti Singh Yadav",  "  9430015024", "", "", " shaktisinghydv@gmail.com", "", " Vill. Birnava, Po. Dosud, Ps. Bena, Dist. Nalanda Bihar "},
		{"Bihar", "Hisua", "Anil Singh", "बिहार", "हिसुआ", "Anil Singh",  "  9431280305", "", "", " anilsinghmlahisua99@gmail.com", "", " Vill-Fulma ,P.o.-Nemdaarganj P.S -Akabarpur, Dist-Nawada. Pin- 805121 "},
		{"Bihar", "Imamganj (SC)", "Jitan Ram Manjhi", "बिहार", "इमामगंज (एस सी)", "Jitan Ram Manjhi",  "  9431284086", "", "", " jrmpatna@gmail.com", "", " Vill. Mahkar, Po. Sapneri, Ps. Khizarsarai Gaya "},
		{"Bihar", "Islampur", "Chandrasen Prasad", "बिहार", "इस्लामपुर", "Chandrasen Prasad",  "  9430248251", "", "", "", "", " Vill. Dhanhar, Po.+Ps. Ekangarsarai, Dist. Nalanda "},
		{"Bihar", "Jagdishpur", "Ram Vishun Singh", "बिहार", "जगदीशपुर", "Ram Vishun Singh",  "  8292360090", "", "", "", "", " Village Dhakakaram, P.O. Barnav, Dist Bhojpur "},
		{"Bihar", "Jahanabad", "Kumar Krishna Mohan Suday Yadav", "बिहार", "जहानाबाद", "Kumar Krishna Mohan Suday Yadav",  "  9431408915", "", "", "", "", " Mohalla -Deoria ,P.O.-+P.S.+District-Jahanabad . "},
		{"Bihar", "Jale", "Jibesh Kumar", "बिहार", "जाले", "Jibesh Kumar",  "  09955997002", "", "", " kumarjibesh@gmail.com", " kumarjibesh36@gmail.com", " Resident Of Gram & Post Chandona, Distt. Darbhanga, Bihar, Pin Code 847303 "},
		{"Bihar", "Jamalpur", "Shailesh Kumar", "बिहार", "जमालपुर", "Shailesh Kumar",  "  9431024629", "", "", "", "", " Vill. Paria, PO. & PS. Bariarpur, Dist. Munger "},
		{"Bihar", "Jamui", "Vijay Prakash", "बिहार", "जमुई", "Vijay Prakash",  "  09661548889", "", "", " rjdvijay@gmail.com", "", " Barhat Tola Salaiya, P.O.+ P.S. Barhat, Distt. Jamui, 811313 "},
		{"Bihar", "Jhajha", "Rabindra Yadav", "बिहार", "झाझा", "Rabindra Yadav",  "  9473463019", "", "", "", "", " Vill. Chandwari, Post. Jhajha, PS. Jhajha, Dist. Jamui "},
		{"Bihar", "Jhanjharpur", "Gulab Yadav", "बिहार", "झंझारपुर", "Gulab Yadav",  "  9325565151", "", "", " gulabyadav5151@gmail.com", "", " Village+post Gangapur, via-Jhanjharpur,847403 "},
		{"Bihar", "Jokhihat", "Shahnawaz", "बिहार", "जोकीहाट", "Shahnawaz",  "  8809055203", "", "", " alamshandy@gmail.com", "", " Sisona Dhobi Tola, P.O.-Jokihat, Thana-Jokihat, Dist.Araria, Pin-854329 "},
		{"Bihar", "Kadwa", "Shakeel Ahmad Khan", "बिहार", "कड़वा", "Shakeel Ahmad Khan",  "  7260964957", "", "", " shakeelkadwa@gmail.com", "", " Vill. and Post Kabar, Distt. Katihar, Bihar "},
		{"Bihar", "Kahalgaon", "Sadanand Singh", "बिहार", "कहलगांव", "Sadanand Singh",  "  9431016600", "", "", " sadanandsinghcongressbihar@hotmail.com", "", " Choudhary Tola Kahalgaon, Dist. Bhagalpur "},
		{"Bihar", "Kalyanpur", "Sachindra Prasad Singh", "बिहार", "कल्याणपुर", "Sachindra Prasad Singh",  "  9471005877", "", "", " spdssingh@gmail.com", "", " Resident Of Gram Fulwariya, Post Mirchiya Vrindavan, Thana Kalyanpur, Distt. Purvi Champaran "},
		{"Bihar", "Kalyanpur (SC)", "Maheshwar Hazari", "बिहार", "कल्याणपुर (एस सी)", "Maheshwar Hazari",  "  9473193337", " 09013180081", "", "", "", " Vill. Chakmahi Mujari, Post. Shripur Gahar, PS. Khanpur, Dist. Samastipur "},
		{"Bihar", "Kanti", "Ashok Kumar Choudhary", "बिहार", "कान्ति", "Ashok Kumar Choudhary S/o Ram Lakhan Chaudhary",  "  9334392511", "", "", " chaudharyacn@gmail.com", "", " Village - Sadanpur, Post-Kolhua Paigambpur, Thana-Kanti, Dist-Muzaffarpur Bihar "},
		{"Bihar", "Karakat", "Sanjay Kumar Singh", "बिहार", "काराकाट", "Sanjay Kumar Singh",  "  9431447647", "", "", " sanjaybik2007@gmail.com", "", " Village Tenduli ward No.04, Post+Thana Bikramganj Dist. Rohtas "},
		{"Bihar", "Kargahar", "Bashisht Singh", "बिहार", "करगहर", "Bashisht Singh",  "  9431430231", "", "", " bashishthajdu@gmail.com", "", " Vill. Bailaspur, P.O. Ghordiha, P.S. Karaghar, Dist. Rohtas, Bihar "},
		{"Bihar", "Kasba", "Md. Afaque Alam", "बिहार", "क़स्बा", "Md. Afaque Alam",  "  9801540149", " 9473199249", "", " mdafaquealam58@gmail.com", "", " Village-Jiyanganj ,P.O.-Matkopa ,Kasba Dist-Purnia, Bihar "},
		{"Bihar", "Katihar", "Tarkishore Prasad", "बिहार", "कटिहार", "Tarkishore Prasad",  "  06542231944", "", "", " tarkishorp@gmail.com", "", " R/O.-Mircharwari, PO.-Katihar, District-Katihar, Pin-854109 "},
		{"Bihar", "Katoria (ST)", "Sweety Sima Hembram", "बिहार", "कटोरिया (एस टी)", "Sweety Sima Hembram",  "  9955934625", "", "", "", "", " Vill. Tengapaja, Post. Bhitiya, PS. Fullidumar, Dist. Banka "},
		{"Bihar", "Keoti", "Faraz Fatmi", "बिहार", "कवेटी", "Faraz Fatmi",  "  09708181666", "", "", " dr_farazfatmi@yahoo.com", "", " Resident Of Gram Vankepur, Post Laheriya Sarai, Thana Bahadurpur, Distt. Darbhanga "},
		{"Bihar", "Kesaria", "Dr Rajesh Kumar", "बिहार", "केसरिया", "Dr Rajesh Kumar",  "  9431294027", "", "", " purainahospital@gmail.com", "", " Resident Of Gram Puraina, Post Sarotar, Maya Huseni, Thana Dumriyaghat, Distt. Purvi Champaran, Pin Code 845423 "},
		{"Bihar", "Khagaria", "Poonam Devi Yadav", "बिहार", "खगरिया", "Poonam Devi Yadav", "  9431455772", "", "", " poonamyadavmla@gmail.com", "", " Vill. Bajrangbali Tola Chukati, Post. Mansi, Dist. Khagaria "},
		{"Bihar", "Khajauli", "Sitaram Yadav", "बिहार", "खजौली", "Sitaram Yadav", "", "", "", "", "", " Vill. Narkatia, Post. Madiya, PS. Basopatti, Dist. Madhubani, Bihar "},
		{"Bihar", "Kishanganj", "Qamrul Hoda", "बिहार", "किशनगंज", "Qamrul Hoda",  "  9431267614", "", "", " qamrulhoda@gmail.com", "", " Village Teusa (Bali chukka) Post Office Teusa District and Police Station kishanganj "},
		{"Bihar", "Kochadhaman", "Mujahid Alam", "बिहार", "कोचाधामन", "Mujahid Alam",  "  9431204127", "", "", " mujahidkne@rediffmail.com", "", " Resident Of Village Kairibirpur, Po. Vishanpur, Thana Kochadhaman, Distt. Kishanganj, Bihar "},
		{"Bihar", "Korha (SC)", "Punam Kumari Alias Punam Paswan", "बिहार", "कोढ़ा (एस सी)", "Punam Kumari Alias Punam Paswan",  "  9431667552", "", "", "", "", " Vill. Baghmara, Post R.N. Bouliya, Thana Manihari, Distt. Katihar "},
		{"Bihar", "Kuchaikot", "Amarendra Kumar Pandey", "बिहार", "कुछाईकोटे", "Amarendra Kumar Pandey",  "  9431812497", "", "", " pamrendra8@gmail.com", "", " Resident Of Gram Sigaha Tola Tulsiya Pagalam- Hathua, Distt. Gopalganj "},
		{"Bihar", "Kumhrar", "Arun Kumar Sinha", "बिहार", "कुम्हरार", "Arun Kumar Sinha",  "  0612-2667556", "", "", " arunkumarsinhamla@gmail.com", "", " 101, Ramvilas Enclave, East Lohanipur, Post-Kadamkuan, Patna "},
		{"Bihar", "Kurhani", "Kedar Prasad Gupta", "बिहार", "कुरहानी", "Kedar Prasad Gupta",  "  9334218308", "", "", " kedarprasadguptabjp@gmail.com", "", " Village- Gobarsahi, Post Office- Khabda, PO- Sadar, Dist- Muzaffarpur, Pin No- 843146 "},
		{"Bihar", "Kurtha", "Satyadeo Singh", "बिहार", "कुर्था", "Satyadeo Singh",  "  9473199343", "", "", " satyadevsinghjdu@gmail.com", "", " Village Bhimali Chakra, Post Hariyara, Thana Devkund, Dist. Aurangabad "},
		{"Bihar", "Kusheshwar Asthan (SC)", "Shashi Bhusan Hazari", "बिहार", "कुशेश्वर स्थान (एस सी)", "Shashi Bhusan Hazari",  "  9801783646", "", "", "", "", " R/O.-Village-Rampur Raout, PO+PS.-Kusheshwar Asthan, District-Darbhanga, Bihar-848213 "},
		{"Bihar", "Kutumba (SC)", "Rajesh Kumar", "बिहार", "कुटुम्बा (एस सी)", "Rajesh Kumar",  "  9431821817", "", "", " rajeshkr.bpc@gmail.com", "", " Village- Obra, P.O/P.S- Obra, Dist- Aurangabad, State- Bihar "},
		{"Bihar", "Lakhisarai", "Vijay Kumar Sinha", "बिहार", "लखीसराय", "Vijay Kumar Sinha",  "  9431011811", " 9473400218", "", " vksmla@gmail.com", "", " Bharadwaj Bhawan, New Area Kadam Kuan, Patna Bihar 800003 "},
		{"Bihar", "Lalganj", "Raj Kumar Sah", "बिहार", "लालगंज", "Raj Kumar Sah",  "  9334368246", "", "", "", "", " Village-Shahpur Kasim, Post.lalganj, Dist. Vaishali Pin.844121 "},
		{"Bihar", "Laukaha", "Lakshmeshwar Roy", "बिहार", "लौकहा", "Lakshmeshwar Roy",  "  9430446648", " 8292476221 ", "", " lakshmeshwarroy@gmail.com", "", " V+P-Thathi P.s.-Ladniyan Dist-Madhubani Pin -847232 "},
		{"Bihar", "Lauriya", "Vinay Bihari", "बिहार", "लौरिया", "Vinay Bihari",  "  9431203456", " 9006262557", "", " vinaybiharivb@gmail.com", "", " Vill. and Post Macharganwa, Thana Yogapatti, Distt. West Champaran "},
		{"Bihar", "Madhepura", "Chandra Shekhar", "बिहार", "मधेपुरा", "Chandra Shekhar",  "  9473194231", "", "", " cshekhar3361@gmail.com", "", " Resident Of Gram Melwa, Post Office Simaraha, Thana Madhepur, Distt. Madhepura "},
		{"Bihar", "Madhuban", "Rana Randhir", "बिहार", "मधुबन", "Rana Randhir",  "  9939941022", "", "", " ranarandhir.18.madhuban@gmail.com", "", " R/O.-Village-Banjria, PO.-Krishnanagar, Madhuban, PS.-Madhuban, District-East Champaran, Bihar-845420 "},
		{"Bihar", "Madhubani", "Samir Kumar Mahaseth", "बिहार", "मधुबनी", "Samir Kumar Mahaseth",  "  9431011416 ", " 9835030015", "", " samirmahasethmlc@gmail.com", "", " Village-Gandhi Bazar Ward No 15, P.O.+P.S-Madhubani Pin-847211 "},
		{"Bihar", "Maharajganj", "Hem Narayan Sah", "बिहार", "महाराजगंज", "Hem Narayan Sah",  "  9939270921", "", "", "", "", " Vill. and Post Kashdawra Bangra, Thana Maharajganj, Distt. Siwan "},
		{"Bihar", "Mahishi", "Dr. Abdul Ghafoor", "बिहार", "महिषी", "Dr. Abdul Ghafoor",  "  9473194331", "", "", " abdulgafoormla@gmail.com", "", " Village & Post Office- Bhelahi, Thana- Jalai, Prakhand- Mahishi, District- Saharsa, Pin No- 852216 "},
		{"Bihar", "Mahnar", "Umesh Singh Kushwaha", "बिहार", "महनार", "Umesh Singh Kushwaha",  "  9934928553", "", "", " umeshkushwaha4people@gmail.com", "", " Village Kajri Bujurg,Post. Thana Jandaha, Prakhand Jandaha Dist. Vaishali Bihar "},
		{"Bihar", "Mahua", "Tej Pratap Yadav", "बिहार", "महुआ", "Tej Pratap Yadav",  "  0612-2217222", "", "", " yadav.tejpratap@gmail.com", "", " 208, Kautilya nagar, MP MLA Colony, P.O. B.V.College, Distt. Patna "},
		{"Bihar", "Makhdumpur (SC)", "Subedar Das", "बिहार", "मखदूमपुर (एस सी)", "Subedar Das",  "  9199211408", "", "", "", "", " Village- Pipara, P.O- Chhatiyana, Thana- Makhadumapur, Dist- Jahanabad, Biahr Pin No- 804403 "},
		{"Bihar", "Maner", "Bhai Verendra", "बिहार", "मनेर", "Bhai Verendra",  "  9473386304", "", "", "", "", " Vill. Mahinava, P.O. Mahinava, P.S. Maner, Dist. Patna "},
		{"Bihar", "Manihari (ST)", "Manohar Prasad Singh", "बिहार", "मनिहारी (एस टी)", "Manohar Prasad Singh",  "  06452254377", "", "", " mpsingmlamanihar67@gmail.com", "", " Resident Of Naya Tola Ward No. 2, Post Manihari, Thana Manihari, Distt. Karihar, Bihar "},
		{"Bihar", "Manjhi", "Vijay Shanker Dubey", "बिहार", "मांझी", "Vijay Shanker Dubey",  "  9431015231", "", "", " vijaydubey166@gmail.com", "", " Vill. & Post. Gayaspur, Dist. Siwan 841210 (Bihar) "},
		{"Bihar", "Marhaura", "Jeetendra Kumar Rai", "बिहार", "मढौरा", "Jeetendra Kumar Rai",  "  9471004128", "", "", "", "", " Vill. Pojhi Buzurg, Post. Bhualpur, Ps. Marhaura, Dist. Saran "},
		{"Bihar", "Masaurhi (SC)", "Rekha Devi", "बिहार", "मसौढ़ी (एस सी)", "Rekha Devi",  "  9430253147", " 9708820406", "", "", "", " Vill+p.O. Pamera, P.S. Dhanrua, Dist. Patna, Pin No. 804451 "},
		{"Bihar", "Matihani", "Narendra Kumar Singh Alias Bogo Singh", "बिहार", "मटिहानी", "Narendra Kumar Singh Alias Bogo Singh",  "  9431211413", "", "", "", "", " Vill+Post-Keshave, Thana-Baroni, Dist.Begusarai, State-Bihar "},
		{"Bihar", "Minapur", "Rajeev Kumar Urf Munna Yadav	", "बिहार", "मीनापुर", "Rajeev Kumar Urf Munna Yadav	",  "  9931477202", "", "", "", "", " Gram-Chapada, post-Muzaffpur,Ramour, dist-Muzaffpur,843117 "},
		{"Bihar", "Mohania (SC)", "Niranjan Ram", "बिहार", "मोहानिया (एस सी)", "Niranjan Ram",  "  9973702162", "", "", " niranjanram2268@gmail.com", "", " Vill. Barhuli, Po. Mitti, Ps. Mohania, Dist Kaimur "},
		{"Bihar", "Mohiuddinnagar", "Ejya Yadav", "बिहार", "मोहिउद्दीन नगर", "Ejya Yadav",  "  9334411011", "", "", " ejyayadav76@gmail.com", "", " SDO Road, Hajipur District Vaishali, 844101 "},
		{"Bihar", "Mokama", "Anant Kumar Singh", "बिहार", "मोकामा", "Anant Kumar Singh",  "  9431800577", " 9431878696 ", "", " sanjitsingh1mall25@gmail.com", "", " Resident-Nadawan, P.o.-NadawanTola ,P.S. Barh ,District-Patna Bihar Patna 803213 "},
		{"Bihar", "Morwa", "Vidya Sagar Singh Nishad", "बिहार", "मोरवा", "Vidya Sagar Singh Nishad",  "  9546676474", "", "", "", "", " Village Post Chaksikandar, Thana- Tajpur, Prakhand- Morwa, District- Samastipur "},
		{"Bihar", "Motihari", "Pramod Kumar", "बिहार", "मोतिहारी", "Pramod Kumar",  "  9431811031", "", "", " pramod.kumar19mth@gmail.com", "", " Vill. Suryapur, Post. Jeevdhara, Ps. Pipra Kothi, Dist. East Champaran "},
		{"Bihar", "Munger", "Vijay Kumar Vijay", "बिहार", "मुंगेर", "Vijay Kumar Vijay",  "  9431236056", "", "", "", "", " Mohalla Haji Sujan(Dilwarpur), P.O+Dist.Munger, Bihar "},
		{"Bihar", "Muzaffarpur", "Suresh Kumar Sharma", "बिहार", "मुजफ्फरपुर", "Suresh Kumar Sharma",  "  9431603807", "", "", " sureshsharmabjp94@gmail.com", "", " Resident Of Raj Bhawan, Chakkar Maidan, Than Kaji Mohammadpur, Post Pradhan Post Office, Distt. Muzaffarpur, Pin Code. 842001 "},
		{"Bihar", "Nabinagar", "Birendra Kumar Singh", "बिहार", "नबीनगर", "Birendra Kumar Singh",  "  9473199355", "", "", " virendra2453@gmail.com", "", " Vill. Tola, P.O. Nabinagar, P.S. Nabinagar, Dist. Aurangabad, Bihar, Pin Code 824301 "},
		{"Bihar", "Nalanda", "Shrawan Kumar", "बिहार", "नालंदा", "Shrawan Kumar",  "  9431023194", "", "", " shravankumarmla@gmail.com", "", " Village and post and police station Ben, Dist. Nalanda "},
		{"Bihar", "Narkatia", "Shamim Ahmad", "बिहार", "नरकटिया", "Shamim Ahmad",  "  9771764110", "", "", "", "", " Vill.Kherwa, Post-Bela Chamahi, Maya-Chodadano, Dist.East Champaran,Bihar,Pin-845302 "},
		{"Bihar", "Narkatiaganj", "Vinay Varma", "बिहार", "नरकटियागंज", "Vinay Varma",  "  9431427555", " 9771595777", "", " vinayvarma321@gmail.com", "", " Vill. and Post D.K Shikarpur, Thana Shikarpur, Distt. Paschimi Champaran "},
		{"Bihar", "Narpatganj", "Anil Kumar Yadav", "बिहार", "नरपतगंज", "Anil Kumar Yadav",  "  9006722722", " 9431292651", "", " anilkuamryadavnarpatganj@gmail.com", "", " Vill+P.O. Khajuri, P.S. Bhargama, Dist. Araraiya Bihar "},
		{"Bihar", "Nathnagar", "Laxmikant Mandal", "बिहार", "नाथनगर", "Laxmikant Mandal",  "  9934051498", "", "", "", "", " Village-Biharipur PO- Bhatoria,Dist- Bhagalpur- 812006 "},
		{"Bihar", "Nautan", "Narayan Prasad", "बिहार", "नौतन", "Narayan Prasad",  "  9939587607", " 9431212097", "", "", "", " R/O.-Village-Vishunpur, PO.-Jagdishpur, PS.-Jagdishpur, District-West Champaran "},
		{"Bihar", "Nawada", "Kaushal Yadav", "बिहार", "नवादा", "Kaushal Yadav",  "  9431227116", "", "", " Skrmay2014@gmail.com ", "", " Mahlla Prasad Bigha Post office + Police Station + Dist = Nawada State Bihar "},
		{"Bihar", "Nirmali", "Anirudh Prasad Yadav", "बिहार", "निर्मली", "Anirudh Prasad Yadav",  "  9431821910", "", "", "", "", " Resident Of Gram & Post Chodpiper, Thana Kisanpur, Distt. Supaul, Pin Code 852105 "},
		{"Bihar", "Nokha", "Anita Devi", "बिहार", "नोखा", "Anita Devi",  "  8521340412", "", "", "", "", " Vill. Akashi, Po. Mokar, Ps. Agrer, Dist Rohtas "},
		{"Bihar", "Obra", "Birendra Kumar Sinha", "बिहार", "ओबरा", "Birendra Kumar Sinha",  "  8084484418", "", "", "", "", " Village bhagwan Bigha, Post Pilchhi, P.s. Daudangar, Dist. Aurangabad, Bihar "},
		{"Bihar", "Paliganj", "Jay Wardhan Yadav", "बिहार", "पालीगंज", "Jay Wardhan Yadav",  "  7488066060", "", "", "", "", " Vill. Amdihri, P.O. Razipur, P.S. Rani Talab, Dist. Patna "},
		{"Bihar", "Parbatta", "Ramanand Prasad Singh", "बिहार", "परबत्ता", "Ramanand Prasad Singh",  "  06245-257008", " 9431432049", " 9431821887 ", "", "", " Resident-Jorwapur Nayagaon ,P.S.Parbatta Thana- Dist-Khagria Pin -851215 "},
		{"Bihar", "Parihar", "Gaytri Devi", "बिहार", "परिहार", "Gaytri Devi",  "  9955313826", "", "", "", "", " R/O.-Village-Maanikpur Musharniya, PO.-Andauli, PS.-Parihar, District-Sitamarhi, Pin-843324 "},
		{"Bihar", "Paroo", "Ashok Kumar Singh", "बिहार", "पारु", "Ashok Kumar Singh",  "  9934872525", "", "", "", "", " Resident Of Vill. Ghoghraha, Post Office Sareya Factory, Thana Sareya, Distt. Muzaffarpur, Pin Code. 843126 "},
		{"Bihar", "Parsa", "Chandrika Rai", "बिहार", "परसा", "Chandrika Rai",  "  9631883888", "", "", " roy.chandrika.roy@gmail.com", "", " Vill. & Post. Bajhiya, Ps. Dariyapur, Dist. Saran "},
		{"Bihar", "Patepur (SC)", "Prema Chaudhary", "बिहार", "पातेपुर (एस सी)", "Prema Chaudhary",  "  9835668567", "", "", " premapatepur@yahoo.in", "", " Village-Iyadpur Post- Pastara, Thana Baligaon Prakhand Patepur, Dist Vaishali "},
		{"Bihar", "Patna Sahib", "Nand Kishor Yadav", "बिहार", "पटना साहिब", "Nand Kishor Yadav",  "  9431022112", "", "", " nandkishore@yahoo.co.in", "", " Khajkala, Patna City, Patna 800008 Bihar "},
		{"Bihar", "Phulparas", "Guljar Devi", "बिहार", "फुलपरास", "Guljar Devi",  "  06277-272625", "", "", "", "", " Vill+Post-Siswabarhi, Maya-Phulparas, Dist.Madhubani, Bihar "},
		{"Bihar", "Phulwari (SC)", "Shyam Rajak", "बिहार", "फुलवारी (एस सी)", "Shyam Rajak",  "  0612-2205740", "", "", " shyamrajak.com@gmail.com", "", " Railway Hunder Road, East Lohanipur, Patna 800003 "},
		{"Bihar", "Pipra (Purvi Champaran)", "Shyambabu Prasad Yadav", "बिहार", "पीपरा (पूर्वी चंपारण)", "Shyambabu Prasad Yadav",  "  7260011089", "", "", "", "", " Vill. Manjhrima, Thana Pipra Kothi, Distt. East Champaran "},
		{"Bihar", "Pipra (Supaul)", "Yaduwansh Kumar Yadav", "बिहार", "पीपरा (सुपौल)", "Yaduwansh Kumar Yadav",  "  9431288556", "", "", "", "", " Vill. Parsa Madho-Dumaria, Post. Parsa Madho, PS. Kisanpur, Dist. Supaul "},
		{"Bihar", "Pirpainti (SC)", "Ram Vilash Paswan", "बिहार", "पीरपैंती (एस सी)", "Ram Vilash Paswan",  "  9431204895", "", "", "", "", " Vill.Channo, P.O.-Channo, Thana-Rasalpur, Dist.Bhagalpur, Dist.Bihar "},
		{"Bihar", "Pranpur", "Binod Kumar Singh", "बिहार", "प्राणपुर", "Binod Kumar Singh",  "  09473199366", "", "", " binodkumarsinghmlapranpur@gmail.com", "", " Post-sirniya,DIst-Katihar "},
		{"Bihar", "Purnia", "Vijay Kumar Khemka", "बिहार", "पूर्णिया", "Vijay Kumar Khemka",  "  9572714733", "", "", " vkhemka.bjp@gmail.com", "", " Sanauli Chowk, N.H.31, Gulabbagh, Purnia "},
		{"Bihar", "Rafiganj", "Ashok Kumar Singh", "बिहार", "रफ़ीगंज", "Ashok Kumar Singh",  "  9431074565", "", "", " singh.ashok.kumar224@gmail.com", "", " Vill. Darmiya Tola Balvant Bigha, Post. Kona, PS. Rafiganj, Dist. Aurangabad, Bihar 824103 "},
		{"Bihar", "Raghopur", "Tejashwi Prasad Yadav", "बिहार", "राघोपुर", "Tejashwi Prasad Yadav",  "  06122217222", "", "", " tejashwi.yadav@gmail.com", "", " 208, Kautilya Nagar, MP MLA Colony, P.O- B.V College, Dsitt- Patna "},
		{"Bihar", "Raghunathpur", "Harishankar Yadav", "बिहार", "रघुनाथपुर", "Harishankar Yadav",  "  7321892003", "", "", "", "", " Vill. Mirpur Andar "},
		{"Bihar", "Raja Pakar (SC)", "Shivchandra Ram", "बिहार", "राजा पाकर (एस सी)", "Shivchandra Ram",  "  9431018339", "", "", " shivchanderram6@gmail.com", "", " Village Mahua, Mukundpur, P.O.+P.S. Mahua, Dist. Vaishali "},
		{"Bihar", "Rajauli (SC)", "Prakash Veer", "बिहार", "रजौली (एस सी)", "Prakash Veer",  "  7321864425", "", "", "", "", " Vill-Ramdasi P.o.+P.s.-Rajauli Dist-Nawada Bihar pin-805125 "},
		{"Bihar", "Rajgir (SC)", "Ravi Jyoti Kumar", "बिहार", "राजगीर (एस सी)", "Ravi Jyoti Kumar",  "  9431402749", "", "", " ravijyoti2000@yahoo.com", "", " Ward No. 45, Navtolia, Po. Latheriasarai, Prakhand +P.S. Bahadurpur, Dist. Darbhanga 846001 "},
		{"Bihar", "Rajnagar (SC)", "Ram Prit Paswan", "बिहार", "राजनगर (एस सी)", "Ram Prit Paswan",  "  9431402258", "", "", " paswanramprit@gmail.com", "", " Vill. & Post. Selibeli, Jainagar, Dist. Madhubani, Pin Code 847226 "},
		{"Bihar", "Rajpur (SC)", "Santosh Kumar Nirala", "बिहार", "राजपुर (एस सी)", "Santosh Kumar Nirala",  "  8969269230", "", "", "", "", " Village-Chunni Tola ,P.o.Chunni P.s.-Buxer Dist-Buxer "},
		{"Bihar", "Ramgarh", "Ashok Kumar Singh", "बिहार", "रामगढ़", "Ashok Kumar Singh",  "  9431410928", "", "", " ashoksinghbjp0005@gmail.com", "", " Village-Godsara Post office+Thana-Ramgarh, Dist. Kaimur(Bihar) "},
		{"Bihar", "Ramnagar (SC)", "Bhagirathi Devi", "बिहार", "रामनगर (एस सी)", "Bhagirathi Devi",  "  9431023640", "", "", " bhagirathidevibjp81@gmail.com", "", " Ward No. 20 Block Road Narkatiaganj, Post Narkatiaganj, Thana Shikarpur, West Champaran "},
		{"Bihar", "Raniganj (SC)", "Achmit Rishidev", "बिहार", "रानीगंज (एस सी)", "Achmit Rishidev",  "  9631553857", "", "", "", "", " Vill. Hansa, Post. Hansa, Dist. Araria "}, 
		{"Bihar", "Raxaul", "Ajay Kumar Singh", "बिहार", "रक्सौल", "Ajay Kumar Singh",  "  9431233031", "", "", "", "", " R/O.-Village+PO.-Raghunathpur, PS.-Ramgarhwa, East Champaran "},
		{"Bihar", "Riga", "Amit Kumar", "बिहार", "रीगा", "Amit Kumar",  "  9955034973", "", "", " tunaamitkumar@gmail.com", "", " Vill. Sonar Tola, Bin Tola, A Post Pokhar Bhinda, Dist. Sitamarhi Pin- 8843329 "},
		{"Bihar", "Rosera (SC)", "Dr. Ashok Kumar", "बिहार", "रोसेरा (एस सी)", "Dr. Ashok Kumar",  "  9431021170", "", "", " ashokkumarinc@gmail.com", "", " 42/B, Sri Krishnapuri, Post GPO, PS. Sri Krishnapuri, Dist. Patna "},
		{"Bihar", "Runnisaidpur", "Mangita Devi", "बिहार", "रूनी सैदपुर", "Mangita Devi",  "  8873181648", "", "", "", "", " Village & PO.-Sirkhiria, PS. Runisaidpur, District-Sitamarhi "},
		{"Bihar", "Rupauli", "Bima Bharti", "बिहार", "रुपौली", "Bima Bharti",  "  9431800563", " 9931504314", "", "", "", " Vill. Bhitta, Post. Dumra, Ps. Bhawanipur, Dist. Purnea "},
		{"Bihar", "Saharsa", "Arun Kumar", "बिहार", "सहरसा", "Arun Kumar",  "  06478-225569", "", "", "", "", " Panchwati Chowk, Ward No. 17, Gangajal, Post Office & Thana- Saharsa Bihar "},
		{"Bihar", "Sahebganj", "Ram Vichar Rai", "बिहार", "साहेबगंज", "Ram Vichar Rai",  "  9934953852", "", "", "", "", " Vill. Madhopur Bujurg, Post Gharfari, Thana Devariya, Distt. Muzaffarpur "},
		{"Bihar", "Sahebpur Kamal", "Shrinarayan Yadav", "बिहार", "साहेबपुर कमल", "Shrinarayan Yadav",  "  9661113707", "", "", "", "", " Vill. Khadhat, P.O. Fulmalik, P.S. Sahebpur Kamal, Dist. Begusari "},
		{"Bihar", "Sakra (SC)", "Lal Babu Ram", "बिहार", "सकरा (एस सी)", "Lal Babu Ram",  "  9431067245", "", "", "", "", " Village +P.o.-Katesar ,P.s.-Sakra Dist-Muzzafarpur "},
		{"Bihar", "Samastipur", "Akhtarul Islam Sahin", "बिहार", "समस्तीपुर", "Akhtarul Islam Sahin",  "  226555", "", "", " akhtarulislammla@gmail.com", "", " M- Dharampur Ward No-2, Samastipur "},
		{"Bihar", "Sandesh", "Arun Kumar", "बिहार", "सन्देश", "Arun Kumar",  "  9431027266", "", "", " arunyadav8765@gmail.com", "", " Village & P.S- Lasadi, Thana- Agiaon (Garhani), Dist- Bhojpur "},
		{"Bihar", "Sarairanjan", "Vijay Kumar Choudhary", "बिहार", "सरायरंजन", "Vijay Kumar Choudhary",  "  9534099997", "", "", "", "", " Vill. & PO. Keota, PS. Dalsinghsarai, Dist. Samastipur "},
		{"Bihar", "Sasaram", "Ashok Kumar", "बिहार", "सासाराम", "Ashok Kumar",  "  9431286901", "", "", " ashokkumar19601@gmail.com", "", " Moll.-Nayka Gaon Dharamshala Road, Sasaram, P.O.+Thana-Sasaram, Dist.Rohtas, Bihar "},
		{"Bihar", "Shahpur", "Rahul Tiwary", "बिहार", "शाहपुर", "Rahul Tiwary",  "  9334101221", "", "", " trikayasalonspa@gmail.com", "", " Village- Ramdihara, PS- Belavaniya, Dist- Bhojpur "},
		{"Bihar", "Sheikhpura", "Randhir Kumar Sony", "बिहार", "शेखपुरा", "Randhir Kumar Sony",  "  9473195703", "", "", " randhirkumarsoni@gmail.com", "", " Village Murarpur (Katari), Post Katari (Sheikhpura), Dist. Sheikhpura -811105 "},
		{"Bihar", "Sheohar", "Sharfuddin", "बिहार", "शिवहर", "Sharfuddin",  "  9006032487", "", "", "", "", " R/O.-Ambakala Tole, Mahuawa, Piprahi, Sheohar "},
		{"Bihar", "Sherghati", "Vinod Prasad Yadav", "बिहार", "शेरघाटी", "Vinod Prasad Yadav",  "  9471006789", " 9471093989", "", " drvinod989@gmail.com", "", " Moh. Nai Bazar Sherghati, P.O.+P.S. Sherghati, Dist. Gaya Bihar "},
		{"Bihar", "Sikandra (SC)", "Sudhir Kumar Alias Banty Choudhary", "बिहार", "सिकंदरा (एस सी)", "Sudhir Kumar Alias Banty Choudhary",  "  9473424782", "", "", " sovlovsri@gmail.com", "", " Village-Machiyar, Post-Jamui, Thana and Dist.Jamui-811307 "},
		{"Bihar", "Sikta", "Khurshid Urf Firoj Ahmad", "बिहार", "सिकता", "Khurshid Urf Firoj Ahmad",  "  9431809613", "", "", "", "", " Resident of Village Majhriya, Post Bhaluhiya, Thana Purshottampur, Distt. West Champaran "},
		{"Bihar", "Sikti", "Vijay Kumar Mandal", "बिहार", "सिकटी", "Vijay Kumar Mandal",  "  8521882398", "", "", "", "", " Village Batraha Mandal Tola Post Batraha Dist Araria Dist Bihar "},
		{"Bihar", "Simri Bakhtiarpur", "Zafar Alam", "बिहार", "सिमरी बख्तियारपुर", "Zafar Alam",  "  947290022", " 8809911379", "", "", "", " Vill. Lakshminiya P.O. Paharpur, Police Station Salkhua Saharsa Pin No. 852127 "},
		{"Bihar", "Singheshwar (SC)", "Ramesh Rishidev", "बिहार", "सिंगेश्वर (एस सी)", "Ramesh Rishidev",  "  9431800558", "", "", " mlarameshrishidev@gmail.com", "", " Vill. Shripur Ka Tola, Gopalpur, Post-Rauta, Thana Kumarkhand, Distt. Madhepur Bihar, Pin 852112 "},
		{"Bihar", "Sitamarhi", "Sunil Kumar", "बिहार", "सीतामढ़ी", "Sunil Kumar",  "  9504003232", " 9431615557", "", "", "", " R/O.-Village-Warishpur Dharamwana, Vishanpur, PO.- Lagma Aajamgarh, PS.-Dumat, District-Sitamarhi "},
		{"Bihar", "Siwan", "Vyas Deo Prasad", "बिहार", "सिवान", "Vyas Deo Prasad",  "  9431009825", "", "", " mlasiwan105@gmail.com", "", " R/O.-Muhalla-Fatehpur, Ward No.33, PO.-Siwan, PS.-Siwan Town, District-Siwan, Bihar-841226 "},
		{"Bihar", "Sonbarsha (SC)", "Ratnesh Sada", "बिहार", "सोनबर्षा (एस सी)", "Ratnesh Sada",  "  9473199255", "", "", "", "", " Resident Of Gram Baliya, Post Kundah, Thana Jalai, Distt. Saharsa "},
		{"Bihar", "Sonepur", "Dr Ramanuj Prasad", "बिहार", "सोनपुर", "Dr Ramanuj Prasad",  "  9431812900", "", "", " ramanuj.pd.sonepur@gmail.com", "", " Village-Najarmeera, Postoffice+thana-Sonepur, Dist. Saran "},
		{"Bihar", "Sugauli", "Ramchandra Sahani", "बिहार", "सुगौली", "Ramchandra Sahani",  "  9431053271", "", "", " ramchandrasahnisgl@gmail.com", "", " Vill+P.o.-Kaithbaliya P.s.Sugauli Dist-East Champaran Pin 845456 Bihar "},
		{"Bihar", "Sultanganj", "Subodh Roy", "बिहार", "सुल्तानगंज", "Subodh Roy",  "  9473199436", "", "", "", "", " Budhiya Kali Place Post. Champanagar Thana, Nathnagar, Dist. Bhagalpur Pin Code-818004 "},
		{"Bihar", "Supaul", "Bijendra Prasad Yadav", "बिहार", "सुपौल", "Bijendra Prasad Yadav",  "  9472306685", "", "", "", "", " Ward No. 4, Kisanpur Road, Post. & PS. & Dist. Supaul 852131 "},
		{"Bihar", "Sursand", "Syed Abu Dojana", "बिहार", "सुरसंद", "Syed Abu Dojana",  "  9431016147", " 9334112227", "", "", "", " Muhalla-32212, Harun Nagar, post- Phulwari sharif, Thana Phulwari sharif "},
		{"Bihar", "Suryagarha", "Prahlad Yadav", "बिहार", "सूर्यगढ़ा", "Prahlad Yadav",  "  7319755074", "", "", "", "", " Village Karari Pipariya Purvi Bhag Prakhand Vadhiya Thana Post. Pipriya Dist., LAKHISARAI Pin Code.811302 "},
		{"Bihar", "Taraiya", "Mudrika Prasad Roy", "बिहार", "तरैया", "Mudrika Prasad Roy",  "  9973418201", " 9473101235", "", "", "", " Village- Chakhan, Post. Shamkauria, PS. Ishuapur, Dist. Saran, Bihar "},
		{"Bihar", "Tarapur", "Mewalal Choudhary", "बिहार", "तारापुर", "Mewalal Choudhary",  "  09431021452", " 9631873433", "", " mlcdr53@gmail.com", "", " Kamargama, Post-Lakhanpur, Thana-Tarapur, Dist. Munger, State-Bihar "},
		{"Bihar", "Tarari", "Sudama Prasad", "बिहार", "तराई", "Sudama Prasad",  "  9931453952", "", "", "", "", " Vill.- Araila(Pawana), Post Office- Pawana, Thana- Pawana, Dist- Bhojpur "},
		{"Bihar", "Teghra", "Birendra Kumar", "बिहार", "तेघड़ा", "Birendra Kumar",  "  0612-2673617", "", "", "", "", " Rajendra Nagar, P.S.-Kadamkuan, Patna-800003 "},
		{"Bihar", "Thakurganj", "Naushad Alam (tatpauwa)", "बिहार", "ठाकुरगंज", "Naushad Alam (tatpauwa)",  "  9471007100", "", "", "", "", " R/O.-Village-Tatpaua Duraghati, PS.-Sukhani, PO.-Bibi Bharatpur, District-Kishanganj "},
		{"Bihar", "Tikari", "Abhay Kumar Sinha", "बिहार", "टिकारी", "Abhay Kumar Sinha",  "  9934400809", "", "", " kumarabhay2244@gmail.com", "", " Village-Chandauli ,Dist- Gaya Bihar "},
		{"Bihar", "Triveniganj (SC)", "Veena Bharti", "बिहार", "त्रिवेणीगंज (एस सी)", "Veena Bharti",  "  9939194427", "", "", " veenabhartimla@gmail.com", "", " Vill. + Post- Daprkha, Ward No.3, PS.- Triveniganj, Dist- Supaul -852139 "},
		{"Bihar", "Ujiarpur", "Alok Kumar Mehta", "बिहार", "उजियारपुर", "Alok Kumar Mehta",  "  9431807369", "", "", " alokmehtamp@yahoo.com", "", " V+P.o.-Mirjanagar P.s.-Mahua, Dist-Vaishali "},
		{"Bihar", "Vaishali", "Raj Kishore Singh", "बिहार", "वैशाली", "Raj Kishore Singh",  "  9431449899", " 9431441362", "", " rajkishoresinghrahsa123@gmail.com", "", " Village Raisa Purvi, Post and Thana Bhagwanpur, Dist. Vaishali, Pin 844114 "},
		{"Bihar", "Valmiki Nagar", "Dhirendra Pratap Singh", "बिहार", "वाल्मीकि नगर", "Dhirendra Pratap Singh",  "  995566745", " 9798105666", "", " yashwi45@gmail.com", "", " village & post office & Police Station - valmikinagar, west champaran "},
		{"Bihar", "Warisnagar", "Ashok Kumar", "बिहार", "वारिसनगर", "Ashok Kumar",  "  0612-2574745", " 9473199993", "", " mandarashokkumar@gmail.com", "", " Village Katghara, Post Bhatora, Maya- Dalmas Nagar, Dist. Samastipur "},
		{"Bihar", "Warsaliganj", "Aruna Devi", "बिहार", "वारिसलीगंज", "Aruna Devi",  "  7783832672", " 9955071986", "", "", "", " Vill+Post-Aapsad, Thana-Warasaliganj, Dist.Nawada, Bihar "},
		{"Bihar", "Wazirganj", "Awadhesh Kumar Singh", "बिहार", "वजीरगंज", "Awadhesh Kumar Singh",  "  9431224081", "", "", "", "", " Village-Gere Post. Manpur, Dist. Gaya, Bihar Pin.823003 "},
		{"Bihar", "Ziradei", "Ramesh Singh Kushwaha", "बिहार", "जीरादेई", "Ramesh Singh Kushwaha",  "  9472672518", "", "", "", "", " Vill. Baraso, Post Anugraha Nagar, Thana Mairwa, Distt. Siwan "},

	};

}