/* Auto-generated file from db2MPjava.php*/

    package in.filternet.jantamalik.Rajya;

    public final class Haryana {

    	public static final String[][] MLAs = {

		{"Haryana", "Adampur", "Kuldeep Bishnoi", "हरियाणा", "आदमपुर", "Kuldeep Bishnoi",  "  01669-248080", "", "", " bhoopsharma11@gmail.com", "", " 80, New Anaj Mandi, Adampur, Distt- Hisar 125052 "},
		{"Haryana", "Ambala Cantt.", "Anil Vij", "हरियाणा", "अंबाला कैंट.", "Anil Vij",  "  0171-2970066", " 01712611216", " 9416211001", " anilvijmla@gmail.com ", "", " H No. 62A Shastri Colony Ambala Cantt 133001 "},
		{"Haryana", "Ambala City", "Aseem Goel", "हरियाणा", "अंबाला सिटी", "Aseem Goel",  "  9416600007", " 9728200007", " 01712551007", " bjpoffice14@gmail.com", "", " Village and Post Office Naneola tehsil And Dist Ambala Haryana "},
		{"Haryana", "Assandh", "Shamsher Singh Gogi", "हरियाणा", "असंध", "Shamsher Singh Gogi",  "  9416000541", "", "", " ssgogi1956@gmail.com", "", " R/o- VPO Thari, Assandh "},
		{"Haryana", "Ateli", "Sitaram", "हरियाणा", "अटेली", "Sitaram",  "  9416065623", "", "", " sitaramsarpanch8262@gmail.com", "", " R/O Village Sujapur PO Ganiyar Teh Ateli Dist, M.Garh HR "},
		{"Haryana", "Badkhal", "Seema Trikha", "हरियाणा", "बडखल", "Seema Trikha",  "  9891051557", " 8195900087", "", "", "", " R/O House No-3F/163, NIT Fridabad, Dist Faridabad "},
		{"Haryana", "Badhra", "Naina Singh", "हरियाणा", "बधरा", "Naina Singh",  "  9812100017", "", "", " dehautala@gmail.com", "", " R/o H No-803 Ram Colony, Ward No. 5 Sirsa HR "},
		{"Haryana", "Badli", "Kuldeep Vats", "हरियाणा", "बादली", "Kuldeep Vats",  "  9416390255", "", "", " kuldeepvats@gmail.com", "", " Village Surheti, Teh Dist Jhajjar "},
		{"Haryana", "Badshahpur", "Rakesh Janghu (Rakesh Daultabad)", "हरियाणा", "बादशाहपुर", "Rakesh Janghu (Rakesh Daultabad)",  "  9891337799", "", "", " rakesh@rakeshdaultabad.com", "", " H.No.181, VPO Daultabad, Gurgaon "},
		{"Haryana", "Bahadurgarh", "Rajinder Singh Joon", "हरियाणा", "बहादुरगढ़", "Rajinder Singh Joon",  "  9416055340", " 9899044432", "", " joonrajindersingh@gmail.com", "", " 72, Prakash Bhawan, Dharampura & H.No. 1999, Sec-2, Bahadurgarh Distt. Jhajjar Haryana "},
		{"Haryana", "Ballabhgarh", "Mool Chand Sharma", "हरियाणा", "बल्लभगढ़", "Mool Chand Sharma",  "  9811556272", "", "", " mulchandsharmabjp@gmail.com", "", " R/o H No-1112C Sec-2, Ballabgarh Faridabad "},
		{"Haryana", "Baroda", "Sri Krishan Hooda", "हरियाणा", "बड़ौदा", "Sri Krishan Hooda",  "  9896424000", " 9729123088", "", " dpkhuda@gmail.com", "", " H.No.682,Vill Khidwali Teh & Dist Rohtak "},
		{"Haryana", "Barwala", "Jogi Ram Sihag", "हरियाणा", "बरवाला", "Jogi Ram Sihag",  "  9416044753", "", "", " jrsihag@gmail.com", "", " H.No. 430/1, Ward No. 15, Near Durga Mandir Khedar Road Barwala Dist. Hisar "},
		{"Haryana", "Bawal", "Dr. Banwari Lal", "हरियाणा", "बावल", "Dr. Banwari Lal",  "  01284-260560", " 9416346880", "", " mail2pankj644@gmail.com", "", " Ward No. 13, H.No. 211/A-21 Railway Road Bawal, Dist. Rewari Haryana - 123501 "},
		{"Haryana", "Bawani Khera", "Bishamber Singh", "हरियाणा", "बवानी खेड़ा", "Bishamber Singh",  "  7777011200", " 8647038000", "", " balmikibishamber@gmail.com", "", " R/o- Village Kharak Kalan, Dist. Bhiwani Haryana "},
		{"Haryana", "Beri", "Dr. Raghuvir Singh Kadian", "हरियाणा", "बेरी", "Dr. Raghuvir Singh Kadian",  "  9812355500", "", "", " drreskberi@yahoo.com", "", " R/O Village & Post Office Dubaldhan Ghikyan , Teh Beri Dist Jhajjar "},
		{"Haryana", "Bhiwani", "Ghanshyam Saraf", "हरियाणा", "भिवानी", "Ghanshyam Saraf",  "  01664-242861", "", "", " ghanshyamdasssaraf@gmail.com", "", " Gali No.-3, Bagh Kothi Bhiwani "},
		{"Haryana", "Dabwali", "Amit Sihag", "हरियाणा", "डबवाली", "Amit Sihag",  "  9876400585", "", "", " amit.sihag.jyc@gmail.com", "", " H.No.651 VPO Chautala Teh Mandi Dabwali Dist Sirsa "},
		{"Haryana", "Dadri", "Sombir", "हरियाणा", "दादरी", "Sombir",  "  9813790000", "", "", " sombirsangwan90000@gmail.com", "", " R/O Village Charkhi Dadri Distt. Charkhi Dadri Haryana "},
		{"Haryana", "Ellenabad", "Abhay Singh Chautala", "हरियाणा", "ऐलनाबाद", "Abhay Singh Chautala",  "  9808200007", "", "", " abhaysinghchautala@gmail.com", "", " R/o H No.233, Village Tejakhera, Tehsil Dabwali, Dist.Sirsa "},
		{"Haryana", "Faridabad", "Narender Gupta", "हरियाणा", "फरीदाबाद", "Narender Gupta",  "  9811150300", "", "", " narender.gupta@styricchem.com", "", " House No. 1126, Sector-15, Faridabad, Haryana "},
		{"Haryana", "Faridabad NIT", "Neeraj Sharma", "हरियाणा", "फरीदाबाद एनआईटी", "Neeraj Sharma",  "  9717312121", "", "", " neeraj.sharma0456@gmail.com", "", " R/o- 1623 Jawahar Colony NIT Faridabad -121005 "},
		{"Haryana", "Fatehabad", "Dura Ram", "हरियाणा", "फतेहाबाद", "Dura Ram",  "  9812035872", "", "", "", "", " House No.95 Village Mohmadpur Rohi Teh & Dist Fatehabad "},
		{"Haryana", "Ferozepur Jhirka", "Mamman Khan", "हरियाणा", "फिरोजपुर झिरका", "Mamman Khan",  "  09818300005", "", "", " kmamman@ymail.com", "", " R/O H no-433/2 VPO Bhadas Sub Tehsil Nagina "},
		{"Haryana", "Ganaur", "Nirmal Rani", "हरियाणा", "गनौर", "Nirmal Rani",  "  9811966723", "", "", " chaudhary.nirmal68@gmail.com", "", " H.No.160 Village And Post Office Jharsa Teh & Dist Gurugram Haryana "},
		{"Haryana", "Garhi Sampla-Kiloi", "Bhupinder Singh Hooda", "हरियाणा", "गढ़ी सांपला-किलोई", "Bhupinder Singh Hooda",  "  01262-282283", " 011-23737019", "", " bshooda.office@gmail.com", "", " R/O Village & PO Sanghi, Teh and Dist Rohtak "},
		{"Haryana", "Gharaunda", "Harvinder Kalyan", "हरियाणा", "घरौंदा", "Harvinder Kalyan",  "  9215552666", "9416000666", "", " harvinderkalyanbjp275@gmail.com", "", " R/o- Kalyan Farm, G.T. Road, Madhuban, Dist. Karnal "},
		{"Haryana", "Gohana", "Jagbir Singh Malik", "हरियाणा", "गोहाना", "Jagbir Singh Malik",  "  9812323202", "", "", "", "", " Tehsil Road Gohana "},
		{"Haryana", "Guhla", "Ishwar Singh", "हरियाणा", "गुहला", "Ishwar Singh",  "  9416035784", "", "", " ishwarsinghkkr@gmail.com", "", " H.No. 70/13, Sector-13, Urban Estate Kurukeshetra Haryana "},
		{"Haryana", "Gurgaon", "Sudhir Singla", "हरियाणा", "गुडगाँव", "Sudhir Singla",  "  9811060302", "", "", " sudhirsinglaadv@gmail.com", "", " 516/16, Baraf Khana, Civil Lines, Gurugram "},
		{"Haryana", "Hansi", "Vinod Bhayana", "हरियाणा", "हांसी", "Vinod Bhayana",  "  9467522222", "", "", " vinodbhayan@gmail.com", "", " 503/1 8Bank Colony Hansi "},
		{"Haryana", "Hathin", "Praveen Dagar", "हरियाणा", "हथीन", "Praveen Dagar",  "  9050131730", "", "", " dagarpraveen295@gmail.com", "", " R/o- Ward No-20, Gujariya Patti, Village & Post Office Mandkola, Tehsil Hathin Dist. Palwal-121103 "},
		{"Haryana", "Hisar", "Dr. Kamal Gupta", "हरियाणा", "हिसार", "Dr. Kamal Gupta",  "  9812080109", "", "", " drkamalgupta2gmail.com", "", " Apollo Hospital , Balsamand Chowk , Hisar "},
		{"Haryana", "Hodal", "Jagdish Nayar", "हरियाणा", "होडल", "Jagdish Nayar",  "  9996373001", "", "", " jagdishnayar3@gmail.com", "", " H.No. 202, Village, Pangaltu, Post Office Gorota, Teh. Hodal Dist. Palwal 121106 "},
		{"Haryana", "Indri", "Ram Kumar", "हरियाणा", "इंद्री", "Ram Kumar",  "  9416294757", " 9416912139", "", " rkkashyap.mpbjp@gmail.com", "", " H.No.391, Sector-8, Urban Estate Kurukshetra "},
		{"Haryana", "Israna", "Balbir Singh", "हरियाणा", "इसराना", "Balbir Singh",  "  9050586690", " 9467313444", "", "", "", " VPO Gwalara Tehsil Israna Distt Panipat "},
		{"Haryana", "Jagadhri", "Kanwar Pal", "हरियाणा", "जगाधरी", "Kanwar Pal",  "  9416023666", "", "", " kanwarpal666@gmail.com", "", " Village Bahadurpur, P.O Pratap Nagar, Tehsil Pratap Nagar, District Yamuna Nagar "},
		{"Haryana", "Jhajjar", "Geeta Bhukkal", "हरियाणा", "झज्जर", "Geeta Bhukkal",  "  9592111555", " 8222951111", "", " bhukkalgeeta@gmail.com", "", " H.NO. 608, Ward No.-17, Talao Road, Jhajjar Haryana "},
		{"Haryana", "Jind", "Dr. Krishan Lal Middha", "हरियाणा", "जींद", "Dr. Krishan Lal Middha",  "  9416060298", "", "", " drkrishanlalmidha@gmail.com", "", " Middha Clinic, Dayal Bagh Colony, Near Old Sabji Mandi, Jind Tehsil & Dist. Jind Haryana "},
		{"Haryana", "Julana", "Amarjeet Dhanda", "हरियाणा", "जुलाना", "Amarjeet Dhanda",  "  9416060210", "", "", "", "", " Village Kharak Ramji , Tehsil & Distt.Jind "},
		{"Haryana", "Kaithal", "Leela Ram", "हरियाणा", "कैथल", "Leela Ram",  "  9466575175", "", "", " leelarambjp@gmail.com", "", " Village Ujjana Post Office Kultaran Tehsil & Dist. kaithal "},
		{"Haryana", "Kalanaur", "Shakuntla Khatak", "हरियाणा", "कलानौर", "Shakuntla Khatak",  "  01262-280666", "", "", " shakuntlakhatak@gmail.com", "", " H. No. 1540/21 Adarsh Nagar, Rohtak "},
		{"Haryana", "Kalanwali", "Shishpal Singh", "हरियाणा", "कालांवाली", "Shishpal Singh",  "  9416036011", "", "", "", "", " R/o- Meerpur Colony Sirsa "},
		{"Haryana", "Kalayat", "Kamlesh Dhanda", "हरियाणा", "कलायत", "Kamlesh Dhanda",  "  9467077001", "", "", " dhanda.tushar1@gmail.com", "", " H.No. 1674/4, Rajendra Seth Colony, Ambala Road, Kaithal "},
		{"Haryana", "Kalka", "Pardeep Chaudhary", "हरियाणा", "कालका", "Pardeep Chaudhary",  "  9814004153", "", "", " pardeepchaudharyINC@gmail.com", "", " House No. 153-154, Sector-2, Panchkula (134112) Haryana "},
		{"Haryana", "Karnal", "Manohar Lal", "हरियाणा", "करनाल", "Manohar Lal",  "  9991119919", "", "", " cmharyana14@gmail.com", "", " H.No.719 New Prem Nagar Karnal Haryana "},
		{"Haryana", "Kharkhauda", "Jaiveer Singh", "हरियाणा", "खरखौदा", "Jaiveer Singh",  "  9467000910", "", "", " jaiveerbalmiki1112@gmail.com", "", " R/o- Ward No-7, Partap Colony Kharkhoda "},
		{"Haryana", "Kosli", "Laxman Singh Yadav", "हरियाणा", "कोसली", "Laxman Singh Yadav",  "  9416064315", "", "", " laxmanyadavbjp@gmail.com", "", " H.No.- 1794, Sec-4, Distt. Rewari Haryana "},
		{"Haryana", "Ladwa", "Mewa Singh", "हरियाणा", "लाडवा", "Mewa Singh",  "  9896341367", "", "", " mewasingh644@gmail.com", "", " R/O H No-644 Sec-5 Urban Estate Kurukshetra "},
		{"Haryana", "Loharu", "Jai Parkash Dalal", "हरियाणा", "लोहारू", "Jai Parkash Dalal",  "  9728454444", " 0124-2340494", "", " jpdalal2000@gmail.com", "", " H.No.-1809, Sec-17A, Gurgaon, Haryana-122001 "},
		{"Haryana", "Mahendragarh", "Rao Dan Singh", "हरियाणा", "महेंद्रगढ़", "Rao Dan Singh",  "  9015300007", "", "", " raodan0909@gmail.com", "", " House No. 99, Ward No. 14, Near Post Office , Mahendargarh Haryana "},
		{"Haryana", "Meham", "Balraj Kundu", "हरियाणा", "मेहम", "Balraj Kundu",  "  7027750555", "", "", " balrajkundumeham@gmail.com", "", " R/o- 115, Sector-14, Rohtak Haryana-124001 "},
		{"Haryana", "Mulana", "Varun Chaudhary", "हरियाणा", "मुलाना", "Varun Chaudhary",  "  9896483003", "", "", " varun.amb@gmail.com", "", " H.No. 936, Sector 7, Ambala City "},
		{"Haryana", "Nalwa", "Ranbir Gangwa", "हरियाणा", "नलवा", "Ranbir Gangwa",  "  9416000457", "", "", " ranbirsinghgangwa4@gmail.com", "", " R/o- Raja Ram Garden, Kaimri Road, Hisar Haryana "},
		{"Haryana", "Nangal Chaudhry", "Dr. Abhe Singh Yadav", "हरियाणा", "नांगल चौधरी", "Dr. Abhe Singh Yadav",  "  9050722533", "", "", " drabhesinghyadav@gmail.com", "", " House No 1055/3 Huda Sector -1 Singhana Road Nanaul Haryana "},
		{"Haryana", "Naraingarh", "Shalley", "हरियाणा", "नारायणगढ़", "Shalley",  "  9988952691", "", "", " brijamg@icloud.com", "", " H.No 06, Ward No 1 Naveen Colony , Naraingarh , Distt. Ambala "},
		{"Haryana", "Narnaul", "Om Prakash Yadav", "हरियाणा", "नारनौल", "Om Prakash Yadav",  "  9416400164", "", "", " vidhayaknnl2014@gmail.com", "", " R/o- Village Bazar Tehsil. Ateli, Dist. Mehendergarh Haryana "},
		{"Haryana", "Narnaund", "Ram Kumar Gautam", "हरियाणा", "नारनौंद", "Ram Kumar Gautam",  "  9416044837", " 8059999256", "", " rajatgautamaag@gmail.com", "", " House No. 163, Ward No. 11, Narnaund, Tehsil Narnaund, District Hisar "},
		{"Haryana", "Narwana", "Ram Niwas", "हरियाणा", "नरवाना", "Ram Niwas",  "  9467751870", "", "", " surajkheraramniwas@gmail.com", "", " R/o- Indra Colony Narwana "},
		{"Haryana", "Nilokheri", "Dharam Pal Gonder", "हरियाणा", "नीलोखेड़ी", "Dharam Pal Gonder",  "  9255178700", "", "", " dharampalgonder1957@gmail.com", "", " R/O V.P.O,Gonder Tehsil Nilokheri & Dist Karanl-132024, now at H.No.670 New Prem Nagar Karnal-132001 "},
		{"Haryana", "Nuh", "Aftab Ahmed", "हरियाणा", "नूह", "Aftab Ahmed",  "  9416266786", "09891353668", "", " aftab814@gmail.com", "", " R/o- 20 Village Khanpur Tehsil And Dist. Nuh "},
		{"Haryana", "Palwal", "Deepak Mangla", "हरियाणा", "पलवल", "Deepak Mangla",  "  9813202384", "", "", " dmanglabjp@gmail.com", "", " R/o House No.DA-212/2, Ward No.1, near Loins Club, Dharam Nagar Palwal, Tehsil and District Palwal-121102 "},
		{"Haryana", "Panchkula", "Gian Chand Gupta", "हरियाणा", "पंचकूला", "Gian Chand Gupta",  "  0172-2564404", " 9815002653", "", " guptagianchand25@gmail", "", " H.no.94 Sector 17 Panchkula 134109 "},
		{"Haryana", "Panipat City", "Parmod Kumar Vij", "हरियाणा", "पानीपत सिटी", "Parmod Kumar Vij",  "  9812069982", "", "", " vijparmod@gmail.com", "", " H.No.1-A, New Friends Colony, Near Shivaji Stadium Model Town Panipat-132103, Haryana "},
		{"Haryana", "Panipat Rural", "Mahipal Dhanda", "हरियाणा", "पानीपत ग्रामीण", "Mahipal Dhanda",  "  9416050827", "", "", " mahipaldhanda.bjp@gmail.com ", " bjpmahipaldhanda@gmail.com", " R/O H.No 1692 Sector-18 Panipat , Haryana "},
		{"Haryana", "Pataudi", "Satya Parkash", "हरियाणा", "पटौदी", "Satya Parkash",  "  9868473501", "", "", " s.pjrawta@gmail.com", "", " Vill & Po Lokra Teh Pataudi Dist Gurugram "},
		{"Haryana", "Pehowa", "Sandeep Singh", "हरियाणा", "पिहोवा", "Sandeep Singh",  "  8569922232", "", "", " flickersingh@hotmail.com", "", " R/o- 1436, Sector-1 Part-2 huda Shahabad Markanda Dist. Kurukeshetra Haryana "},
		{"Haryana", "Prithla", "Nayan Pal Rawat", "हरियाणा", "पृथला", "Nayan Pal Rawat",  "  9810414734", "", "", " nayanpalrawat@gmail.com", "", " VPO Asaoti , Tehsil & Dist. Palwal 121102 Haryana "},
		{"Haryana", "Pundri", "Randhir Singh Gollen", "हरियाणा", "पुंडरी", "Randhir Singh Gollen",  "  9416562678", "", "", " randhirgollen@gmail.com", "", " R/o-Mohala Kaithali Gate Pundri Tehsil P, Dist. Kaithal "},
		{"Haryana", "Punahana", "Mohammad Ilyas", "हरियाणा", "पुन्हाना", "Mohammad Ilyas", "  09813688319", "", "", " javedkhanmeo@gmail.com", "", " R/O Village Sultanpur Punhana Teh Punhana Dist Nuh HR "},
		{"Haryana", "Radaur", "Bishan Lal", "हरियाणा", "रादौर", "Bishan Lal", "", "", "", "", "", " VPO. Saran, Sub Teh. Saraswati Nagar Mustafabad Teh. Jagadhri Dist. Yamuna Nagar "},
		{"Haryana", "Rai", "Mohan Lal Badoli", "हरियाणा", "राई", "Mohan Lal Badoli",  "  9416013687", " 9588534121", "", " mohanlala13687@gmail.com", "", " Village And Post Office Badoli Tehsil Rai, Dist Sonipat "},
		{"Haryana", "Rania", "Ranjit Singh", "हरियाणा", "रणिया", "Ranjit Singh",  "  9416048386", "", "", " chranjitsinghrania@gmail.com", "", " Ram Colony, Barnala Road, Sirsa (Haryana) "},
		{"Haryana", "Ratia", "Lakshman Dass", "हरियाणा", "रतिया", "Lakshman Dass",  "  9416726900 ", " 01697-253303", "", " lakshmannapa900@gmail.com", "", " R/o- 27, Block No-2, VPO Jallopur, Tehsil Ratia Dist. Fatehabad "},
		{"Haryana", "Rewari", "Chiranjeev Rao", "हरियाणा", "रेवाड़ी", "Chiranjeev Rao",  "  9416372035 ", " 01274-225253", "", " crao.hpyc@gmail.com", "", " R/o- 315-L, Model Town, Rewari "},
		{"Haryana", "Rohtak", "Bharat Bhushan Batra", "हरियाणा", "रोहतक", "Bharat Bhushan Batra",  "  01262268022", " 9812211177", "", " office.bbbatra@gmail.com", "", " H.No. 86 Shakti Nagar Green Road Rohtak 124001 "},
		{"Haryana", "Sadhaura", "Renu Bala", "हरियाणा", "सढ़ौरा", "Renu Bala",  "  9467556702", "", "", " pallrishi53@gmail.com", "", " Village Baroli Majra, P.O. Ledi, Teh Chhachhrauli Distt. Yamuna Nagar "},
		{"Haryana", "Safidon", "Subhash Gangoli", "हरियाणा", "सफीदों", "Subhash Gangoli",  "  7056060000", " 9416062590", "", " kissanhatcheries@gmail.com", "", " Vill. & Po.Gangoli Teh Safidon Distt. Jind Haryana "},
		{"Haryana", "Samalkha", "Dharam Singh Chhoker", "हरियाणा", "समालखा", "Dharam Singh Chhoker",  "  9811566843", "", "", " dharamschhoker@gmail.com", "", " Shop No. 83, New Grain Market Samalkha, District Panipat "},
		{"Haryana", "Shahbad", "Ram Karan", "हरियाणा", "शाहाबाद", "Ram Karan",  "  9416514737", "", "", "", "", " R/o- Village Teora, Tehsil Shahabad Dist. Kurukshetra "},
		{"Haryana", "Sirsa", "Gopal Kanda", "हरियाणा", "सिरसा", "Gopal Kanda",  "  9953100000", "9811498114", "", " sirsagopalkanda@gmail.com", "", " R/O H No-335, Ward No-15 Gali Khazanchian Wali Sirsa, "},
		{"Haryana", "Sohna", "Sanjay Singh", "हरियाणा", "सोहना", "Sanjay Singh",  "  9990000044", "", "", " kanwarsanjaysingh@gmail.com", "", " Village Ujina, Tehsil & District Nuh "},
		{"Haryana", "Sonipat", "Surender Panwar", "हरियाणा", "सोनीपत", "Surender Panwar",  "  9896337544", "", "", " spawar2627@gmail.com", "", " H.no.26-27,Sec 15 Sonipat Haryana 131001 "},
		{"Haryana", "Thanesar", "Subhash Sudha", "हरियाणा", "थानेसर", "Subhash Sudha",  "  9215751665", "", "", " sudhasubhashkkr@gmail.com", "", " H.NO 66 & H.NO 07, Sector 7, Urban Estate , Kurukshetra, Tehsil Thanrsar Distt. Kurukshetra "},
		{"Haryana", "Tigaon", "Rajesh Nagar", "हरियाणा", "तिगांव", "Rajesh Nagar",  "  9891272727", "", "", " rajeshnagar641@gmail.com", "", " R/O H.No.11 VPO Tigaon Sub Tehsil Tigaon Dist Faridabad Haryana 121101 "},
		{"Haryana", "Tohana", "Devender Singh Babli", "हरियाणा", "टोहाना", "Devender Singh Babli",  "  9729947777", "", "", " sherawat.suraj45@yahoo.com", "", " Vill. Bidhai Khera, PO. Dangra Teh. Tohana, Dist. Fatehabad "},
		{"Haryana", "Tosham", "Kiran Choudhry", "हरियाणा", "तोशाम", "Kiran Choudhry",  "  01664-252432 ", " 01664-254822", "", " office@kiranchoudhary.com", "", " 116, Sunder Nagar, New Delhi 110003 "},
		{"Haryana", "Uchana Kalan", "Dushyant Chautala", "हरियाणा", "उचाना कलां", "Dushyant Chautala",  "  9811600003", "", "", " dchautala@gmail.com", "", " R/O H No-803 Ram Colony Ward No-05 Sirsa 125055 "},
		{"Haryana", "Uklana", "Anoop Dhanak", "हरियाणा", "उकलाना", "Anoop Dhanak",  "  9416971065 ", " 9813339737", "", " anoopdhanak@gmail.com", "", " R/o- 97A, FC Colony, Uklana Mandi Dist. Hisar "},
		{"Haryana", "Yamunanagar", "Ghanshyam Dass", "हरियाणा", "यमुनानगर", "Ghanshyam Dass",  "  9896027305", "", "", " bjpghanshyamarora@gmail.com", "", " 120 A/R Model Town Yamuna Nagar, Dist.Yamuna Nagar "},

	};

}