/* Auto-generated file from db2MPjava.php*/

    package in.filternet.jantamalik.Rajya;

    public final class Jammu_and_Kashmir {

    	public static final String[][] MLAs = {

		{"Jammu & Kashmir", "Akhnoor", "Rajeev Sharma", "जम्मू और कश्मीर", "Akhnoor", "Rajeev Sharma",  "  9419188968", "", "", " sharmarajeev88968@yahoo.in", "", " H.No.125 Ward-12, Sharma Complex Ind. Estate Road Akhnoor "}, 
		{"Jammu & Kashmir", "Amirakadal", "Syed Mohammad Altaf Bukhari", "जम्मू और कश्मीर", "Amirakadal", "Syed Mohammad Altaf Bukhari",  "  0194-2468889", " 941943087", "", " altafbukharipdp@amirakadal.com", "", " 7, Kohinoor House Sheikh Bagh Srinagar J&K "}, 
		{"Jammu & Kashmir", "Anantnag", "Mufti Mohd Syed", "जम्मू और कश्मीर", "Anantnag", "Mufti Mohd Syed",  "  9419000971", "", "", "", "", " Bijbehara(Baba Mohalla), Teh- Bijbehara & Dist Anatnag "}, 
		{"Jammu & Kashmir", "Badgam", "Aga Syed Ruhullah Mehdi", "जम्मू और कश्मीर", "Badgam", "Aga Syed Ruhullah Mehdi",  "  9419002717", "", "", " ruhullahmehdi@yahoo.com", "", " Vill Shariatalad, Teh & Dist Budgam "}, 
		{"Jammu & Kashmir", "Bandipora", "Usman Abdul Majid", "जम्मू और कश्मीर", "Bandipora", "Usman Abdul Majid",  "  9419000837", "", "", " usmanmajid111@yahoo.com", "", " R/O Garoora Bandipora (J&K) "}, 
		{"Jammu & Kashmir", "Bani", "Jewan Lal", "जम्मू और कश्मीर", "Bani", "Jewan Lal",  "  9419223788", "", "", "", "", " R/O. KANTHAL, TEHSIL BANI V.P.O. TEHSIL BANI & DIST. KATHUA (J&K) "}, 
		{"Jammu & Kashmir", "Banihal", "Vikar Rassol Wani", "जम्मू और कश्मीर", "Banihal", "Vikar Rassol Wani",  "  9419167678", "", "", " vikarrasool@gmail.com", "", " R/O Devgole Banihal "}, 
		{"Jammu & Kashmir", "Baramulla", "Javid Hassan Baig", "जम्मू और कश्मीर", "Baramulla", "Javid Hassan Baig",  "  9419035003", "", "", "", "", " R/O. WEHIDINA, POST OFFICE CHANDOOSA TEHSIL & DIST. BARAMULLA "}, 
		{"Jammu & Kashmir", "Basohli", "Lal Singh", "जम्मू और कश्मीर", "Basohli", "Lal Singh",  "  9469811111", "", "", " choudharylalsingh@icloud.com", "", " Kothi.no.1 Ward no.2 Kathua "}, 
		{"Jammu & Kashmir", "Batamaloo", "Noor Mohamad Sheikh", "जम्मू और कश्मीर", "Batamaloo", "Noor Mohamad Sheikh",  "  9419056827", "", "", " leoshabir@gmail.com", "", " Resident of Lawaypora Srinagar "}, 
		{"Jammu & Kashmir", "Beerwah", "Omar Abdullah", "जम्मू और कश्मीर", "Beerwah", "Omar Abdullah",  "  9797305555", " 9469800786", "", " omar_abdullah@mac.com", "", " Resident of G-1, Gupkar Road Srinagar "}, 
		{"Jammu & Kashmir", "Bhaderwah", "Daleep Singh", "जम्मू और कश्मीर", "Bhaderwah", "Daleep Singh",  "  8803685954", "", "", "", "", " R/ village Batra , Tehshil Garhwa "}, 
		{"Jammu & Kashmir", "Bijbehara", "Abdul Rehman Bhat", "जम्मू और कश्मीर", "Bijbehara", "Abdul Rehman Bhat",  "  9419000759", "", "", "", "", " Veeri Bijbehara, Anantnag 192124 "}, 
		{"Jammu & Kashmir", "Billawar", "Dr. Nirmal Kumar Singh", "जम्मू और कश्मीर", "Billawar", "Dr. Nirmal Kumar Singh",  "  9419149494", "", "", " dr.nirmalsinghbjp@gmail.com", "", " Resident of Karanwara - Sabar, teh. Basholi, Dist. Kathua "}, 
		{"Jammu & Kashmir", "Bishnah", "Kamal Verma", "जम्मू और कश्मीर", "Bishnah", "Kamal Verma",  "  7298855555", "", "", "", "", " Ward No-8 Village & Post Officer Arania, Teh. Bishnah Dist Jammu, J&K "}, 
		{"Jammu & Kashmir", "Chadoora", "Javaid Mustafa Mir", "जम्मू और कश्मीर", "Chadoora", "Javaid Mustafa Mir",  "  9419000766", "", "", " javaidmustaffamir@gmail.com", "", " Lasjan, Teh.Chadoora, Dist.Budgam, P.O.Panthachowk "}, 
		{"Jammu & Kashmir", "Chenani (sc)", "Dina Nath", "जम्मू और कश्मीर", "Chenani (sc)", "Dina Nath",  "  9419255367", " 7298583677", "", " bhagatdinanath128@gmail.com", "", " House No.30, Ward No.7, Udhampur-182101 (J&K) "}, 
		{"Jammu & Kashmir", "Chhamb (sc)", "Dr. Kirshan Lal", "जम्मू और कश्मीर", "Chhamb (sc)", "Dr. Kirshan Lal",  "  9419823298", "", "", "", "", " Resident of (Nandwal) Naryana, P.O.-Khour, Teh.-Khour, Dist.-Jammu "}, 
		{"Jammu & Kashmir", "Chrar-i- Sharief", "Ghulam Nabi Lone", "जम्मू और कश्मीर", "Chrar-i- Sharief", "Ghulam Nabi Lone",  "  9419000868", "", "", " ghulamnabilonehanjura@yahoo.com", "", " R/O. HANJURA TEHSIL CHADOORA DIST. BUDGAM POST. OFFICE HANJURA PIN CODE 191113 "}, 
		{"Jammu & Kashmir", "Darhal", "Ch Zulfkar Ali", "जम्मू और कश्मीर", "Darhal", "Ch Zulfkar Ali",  "  9419116551", "", "", " chzulfkarali@gmail.com", "", " Tralla Gujjera, Teh.Budhal, Dist.Rajouri "}, 
		{"Jammu & Kashmir", "Devsar", "Mohammad Amin Bhat", "जम्मू और कश्मीर", "Devsar", "Mohammad Amin Bhat",  "  9419000597", " 9596885555", "", "", "", " Resident of 145, Lalipora Malapora, P.O.Khanabal, P.S. Qazlgund, Pin-192102 "}, 
		{"Jammu & Kashmir", "Doda", "Shakti Parihar", "जम्मू और कश्मीर", "Doda", "Shakti Parihar",  "  9906372019", "", "", " shaktiparihar@rediffmail.com", "", " R/O Village Salana, BPO Badhat, Tehshil & District Kishtwar "}, 
		{"Jammu & Kashmir", "Doru", "Syed Farooq Ahmad Andrabi", "जम्मू और कश्मीर", "Doru", "Syed Farooq Ahmad Andrabi",  "  9419007577", "", "", " andrabi.farooq@gmail.com", "", " Chanpora Ujroo Doru Tehsil Doru District Anantang "}, 
		{"Jammu & Kashmir", "Ganderbal", "Ishfaq Ahmad", "जम्मू और कश्मीर", "Ganderbal", "Ishfaq Ahmad",  "  9419203932", "", "", "", "", " R/O Lar Tehshil Lar District ganderbal, Post Office Tullamulla "}, 
		{"Jammu & Kashmir", "Gandhinagar", "Kavinder Gupta", "जम्मू और कश्मीर", "Gandhinagar", "Kavinder Gupta",  "  9419133322", "", "", " kavinder.02@gmail.com", "", " 44-A, Excelsior Lane, Old Janipur, Jammu(Tawi)-180007 "}, 
		{"Jammu & Kashmir", "Gool Arnas", "Ajaz Ahmed Khan", "जम्मू और कश्मीर", "Gool Arnas", "Ajaz Ahmed Khan",  "  9419000842", "", "", " ajazahmedkhan842@gmail.com", "", " Village Thuroo, Post Office Dharmari, Thsil-Thuroo Distt. Reasi, J&K "}, 
		{"Jammu & Kashmir", "Gulabgarh", "Mumtaz Ahmed", "जम्मू और कश्मीर", "Gulabgarh", "Mumtaz Ahmed",  "  9697597033", "", "", "", "", " Village Thuroo, Post Office Dharmari, Teh. Thuroo, Dist. Reasi (J&K) "}, 
		{"Jammu & Kashmir", "Gulmarg", "Mohd Abbas Wani", "जम्मू और कश्मीर", "Gulmarg", "Mohd Abbas Wani",  "  9596000232", "", "", " abbaswani@gmail.com", "", " Vill-Chandilora Tangmarg Pin 193402 "}, 
		{"Jammu & Kashmir", "Gurez", "Nazir Ahmad Khan Gurezi", "जम्मू और कश्मीर", "Gurez", "Nazir Ahmad Khan Gurezi",  "  9419000874", "", "", "", "", " R/o Badwam Teh. Gurez, PO. Gurez "}, 
		{"Jammu & Kashmir", "Habbakadal", "Shamim Firdous", "जम्मू और कश्मीर", "Habbakadal", "Shamim Firdous",  "  9419000863", "", "", "", "", " FATEH KADAL MALIKYAR SRINAGAR "}, 
		{"Jammu & Kashmir", "Handwara", "Sajad Gani Lone", "जम्मू और कश्मीर", "Handwara", "Sajad Gani Lone",  "  9797555550", "", "", " lone.sajad@gmail.com", "", " Lone Manzil, Banday Mohalla handwara "}, 
		{"Jammu & Kashmir", "Hazratbal", "Asiea", "जम्मू और कश्मीर", "Hazratbal", "Asiea",  "  9419015798", "", "", "", "", " Habak Naseembagh,Teh and Dist Srinagar "}, 
		{"Jammu & Kashmir", "Hiranagar (sc)", "Kuldeep Raj", "जम्मू और कश्मीर", "Hiranagar (sc)", "Kuldeep Raj",  "  7298243072", "", "", " bjpkuldeep@gmail.com", "", " Vill. Jandi teh. Hiranagar Dist. Kathua "}, 
		{"Jammu & Kashmir", "Home-shalibugh", "Ab. Majeed Butt", "जम्मू और कश्मीर", "Home-shalibugh", "Ab. Majeed Butt",  "  9419150583", "", "", " ambhat11@gmail.com", "", " 171-Larm Ganjipora, P.O. Wanpoh, Pin Code 192102 "}, 
		{"Jammu & Kashmir", "Idgah", "Mubarak Ahmed Gul", "जम्मू और कश्मीर", "Idgah", "Mubarak Ahmed Gul",  "  9419000872", "", "", " imubarakgul@gmail.com", "", " Shah Mohalla, P.O. SR Gunj, Srinagar 190002 "}, 
		{"Jammu & Kashmir", "Inderwal", "Ghulam	Mohd. Saroori", "जम्मू और कश्मीर", "Inderwal", "Ghulam	Mohd. Saroori",  "  9622181566", "", "", " saroorigm@gmail.com", "", " R/o Vill. Karool Sarthal Tehsil & Distt. Kishtwar "}, 
		{"Jammu & Kashmir", "Jammu East", "Rajesh Gupta", "जम्मू और कश्मीर", "Jammu East", "Rajesh Gupta",  "  9419118360", "", "", " rajeshgupta7365@gmail.com", "", " H.No. 92 Mohalla Jatkatian Lakhdata Bazar Jammu "}, 
		{"Jammu & Kashmir", "Jammu West", "Sat Paul Sharma", "जम्मू और कश्मीर", "Jammu West", "Sat Paul Sharma",  "  9419194320 ", " 9858575757", "", " ssajammu@gmail.com", "", " Resident -H.NO.268 Near J&K State Board Of School Education Rehari Colony Jammu Tawi 180005 "}, 
		{"Jammu & Kashmir", "Kalakote", "Abdul Ghani Kohli", "जम्मू और कश्मीर", "Kalakote", "Abdul Ghani Kohli",  "  9419195161", "", "", " agkohli43@gmail.com", "", " Vill. Sialsui, Teh-Kalakote "}, 
		{"Jammu & Kashmir", "Kangan", "Altaf Ahmad", "जम्मू और कश्मीर", "Kangan", "Altaf Ahmad",  "  9906000880", "", "", "", "", " Wangath Kangan, District Ganderbal "}, 
		{"Jammu & Kashmir", "Kargil", "Asgar Ali Karbalaie", "जम्मू और कश्मीर", "Kargil", "Asgar Ali Karbalaie",  "  01985-233798 ", " 9419176414", "", " aakarbalai@gmail.com", "", " R/O Bagh-e-Khumainee Kargil Tehshil & District Kargil "}, 
		{"Jammu & Kashmir", "Karnah", "Raja Manzoor Ahmad Khan", "जम्मू और कश्मीर", "Karnah", "Raja Manzoor Ahmad Khan",  "  9906828210", "", "", "", "", " Nachian Karnah "}, 
		{"Jammu & Kashmir", "Kathua", "Rajiv Jasrotia", "जम्मू और कश्मीर", "Kathua", "Rajiv Jasrotia",  "  9419208007", "", "", " rajivjasrotia13@gmail.com", "", " Ward no.9 Hira Nagar, Distt. Kathua "}, 
		{"Jammu & Kashmir", "Khansahib", "Hakeem Mohammad Yaseen Shah", "जम्मू और कश्मीर", "Khansahib", "Hakeem Mohammad Yaseen Shah",  "  9419000895", "", "", " hakeemvaseen@gmail.com", "", " Resident of Khansahib Teh. Khansahib, Dist. Budgam "}, 
		{"Jammu & Kashmir", "Khanyar", "Ali Mohd Sagar", "जम्मू और कश्मीर", "Khanyar", "Ali Mohd Sagar",  "  9419000875", "", "", "", "", " Shah Mohalla A/P M-3 Sonawar "}, 
		{"Jammu & Kashmir", "Kishtwar", "Sunil Kumar Sharma", "जम्मू और कश्मीर", "Kishtwar", "Sunil Kumar Sharma",  "  9419159555", " 9858094445", "", " tell2sunil@gmail.com", "", " R/O Village Hatta Kishtwar "}, 
		{"Jammu & Kashmir", "Kokernag", "Abdul Rahim Rather", "जम्मू और कश्मीर", "Kokernag", "Abdul Rahim Rather",  "  9419008284", "", "", " arrather@yahoo.in", "", " R/O. NAGAM TEHSIL KOKERNAG "}, 
		{"Jammu & Kashmir", "Kulgam", "Mohamad Yousuf Tarigami", "जम्मू और कश्मीर", "Kulgam", "Mohamad Yousuf Tarigami",  "  9419000950", "", "", " tarigami@gmail.com", "", " Village Tarigam Devsar, Teh. & Dist. Kulgam, J&K 192231 "}, 
		{"Jammu & Kashmir", "Kupwara", "Bashir Ahmad Dar", "जम्मू और कश्मीर", "Kupwara", "Bashir Ahmad Dar",  "  9906709292", "", "", "", "", " Jaggerpora, Tehsil Handwara Dist. Kupwara "}, 
		{"Jammu & Kashmir", "Langate", "Abdul Rashid Sheik", "जम्मू और कश्मीर", "Langate", "Abdul Rashid Sheik",  "  9906663777", "", "", " mlalangate@gmail.com", "", " Lach Mawar Handwara, Dist.Kupwara Kashmir J&K "}, 
		{"Jammu & Kashmir", "Leh", "Nawang Rigzin", "जम्मू और कश्मीर", "Leh", "Nawang Rigzin",  "  9622222888", " 949000765", "", " nrigzinjora@gmail.com", "", " Resident Of Vill. Nimmu, Jora P.O. Leh, Ladakh 194101 "}, 
		{"Jammu & Kashmir", "Lolab", "Abdul Haq Khan", "जम्मू और कश्मीर", "Lolab", "Abdul Haq Khan",  "  ", "", "", "", "", " DOVER ARDUBUGH LOLAB "}, 
		{"Jammu & Kashmir", "Marh", "Sukhnandan Kumar", "जम्मू और कश्मीर", "Marh", "Sukhnandan Kumar",  "  9419128005", "", "", "", "", " VILLAGE AND POST OFFICE GAJANSOO JAMMU "}, 
		{"Jammu & Kashmir", "Mendhar", "Javed Ahmed Rana", "जम्मू और कश्मीर", "Mendhar", "Javed Ahmed Rana",  "  9419000685", " 9596959996", "", "", "", " Village Kalaban, Post office Kalaban, Tehsil Mendhar, Dist. poonch "}, 
		{"Jammu & Kashmir", "Nagrota", "Devender Singh Rana", "जम्मू और कश्मीर", "Nagrota", "Devender Singh Rana",  "  9419000011", "", "", " dsrana65@gmail.com", "", " 184 A/D, Gandhi Nagar, Jammu "}, 
		{"Jammu & Kashmir", "Nobra", "Deldan Namgial", "जम्मू और कश्मीर", "Nobra", "Deldan Namgial",  "  9469490777", "", "", " delkobet12@gmail.com", "", " R/O village Kubed Nubra "}, 
		{"Jammu & Kashmir", "Noorabad", "Ab Majeed Padder", "जम्मू और कश्मीर", "Noorabad", "Ab Majeed Padder",  "  9419040288", "", "", "", "", " D.H.Pura "}, 
		{"Jammu & Kashmir", "Nowshara", "Ravinder Kumar", "जम्मू और कश्मीर", "Nowshara", "Ravinder Kumar",  "  9419144078", "", "", " indian kashmir@gmail.com", "", " Vill. Lamberi, teh. Nowshera, Dist. Rajouri, State J&K "}, 
		{"Jammu & Kashmir", "Pahalgam", "Altaf Ahmad Wani", "जम्मू और कश्मीर", "Pahalgam", "Altaf Ahmad Wani",  "  9906048786", "", "", "", "", " Grend Aish Aishmuqam, Teh.Pahalgam, Dist.Anantnag "}, 
		{"Jammu & Kashmir", "Pampore", "Zahoor Ahmad Mir", "जम्मू और कश्मीर", "Pampore", "Zahoor Ahmad Mir",  "  9419000885", "", "", "", "", " Konibal-192121 "}, 
		{"Jammu & Kashmir", "Pattan", "Imran Raza Ansari", "जम्मू और कश्मीर", "Pattan", "Imran Raza Ansari",  "  9906600000", "", "", " imranreza@hotmail.com", "", " Resident-Sheri Kashmir colony,Darul Jawad Qantaraum Tehsil& Dist.Srinagar Kashmir "}, 
		{"Jammu & Kashmir", "Poonch Haveli", "Shah Mohd Tantray", "जम्मू और कश्मीर", "Poonch Haveli", "Shah Mohd Tantray",  "  9906239092", "", "", " poonchpdpunit@gmail.com", " ajaztantray-8-@gmail.com", " Vill.- Loran, Teh.- Mandi, Dist.- Poonch, "}, 
		{"Jammu & Kashmir", "Pulwama", "Mohd Khalil Bandh", "जम्मू और कश्मीर", "Pulwama", "Mohd Khalil Bandh",  "  9419000878", "", "", "", "", " Vill.Banderpora, P.O.Banderpora, P.S.Pulwama "}, 
		{"Jammu & Kashmir", "R S Pura (sc)", "Dr. Gagan Bhagat", "जम्मू और कश्मीर", "R S Pura (sc)", "Dr. Gagan Bhagat",  "  9419156578", "", "", " drgaganbhagat@gmail.com", "", " H.No. 52 Word no,9 R.S.Pura Jammu "}, 
		{"Jammu & Kashmir", "Rafiabad", "Yawar Ahmad Mir", "जम्मू और कश्मीर", "Rafiabad", "Yawar Ahmad Mir",  "  9419067070", "", "", "", "", " Resident-Rohama, Rafiabad, Dist.-Baramulla J&K State "}, 
		{"Jammu & Kashmir", "Raipur Domana (sc)", "Bali Bhagat", "जम्मू और कश्मीर", "Raipur Domana (sc)", "Bali Bhagat",  "  9419110709", "", "", " bhagat.bali@gmail.com", "", " 73-C Bhawani Nagar, Teh. & Dist.Jammu-180007 "}, 
		{"Jammu & Kashmir", "Rajouri", "Qamar Hussain", "जम्मू और कश्मीर", "Rajouri", "Qamar Hussain",  "  9419170914", "", "", "", "", " Village Lah, Tehsil Thana Handi "}, 
		{"Jammu & Kashmir", "Rajpora", "Haseeb A Drabu", "जम्मू और कश्मीर", "Rajpora", "Haseeb A Drabu",  "  9797881111", "", "", " hassebdrabu@gmail.com", "", " 122, Rajpora, P.O Rajpora "}, 
		{"Jammu & Kashmir", "Ramban (sc)", "Neelam Kumar Lahgeh", "जम्मू और कश्मीर", "Ramban (sc)", "Neelam Kumar Lahgeh",  "  ", "", "", "", "", " Maitra Govindpura "}, 
		{"Jammu & Kashmir", "Ramnagar", "Ranbir Singh Pathania", "जम्मू और कश्मीर", "Ramnagar", "Ranbir Singh Pathania",  "  9419212259", " 9419160313", "", " rspathnjapye@gmail.com", "", " Vill. Kall, Teh. Majalta Dist Udhampur "}, 
		{"Jammu & Kashmir", "Reasi", "Ajay Nanda", "जम्मू और कश्मीर", "Reasi", "Ajay Nanda",  "  9419185432", "", "", " ajaynanda_mlnanda@yahoo.com", "", " Ward No 3, Reasi, Teh & Dist Reasi "}, 
		{"Jammu & Kashmir", "Samba (sc)", "Devinder Kumar Manyal", "जम्मू और कश्मीर", "Samba (sc)", "Devinder Kumar Manyal",  "  9419176785", "", "", " dr_devinder2155@yahoo.in", "", " VPO Diani, Tehsil & District Samba "}, 
		{"Jammu & Kashmir", "Sangrama", "Syed Basharat Ahmed Bukhari", "जम्मू और कश्मीर", "Sangrama", "Syed Basharat Ahmed Bukhari",  "  9419017349", "", "", " basharat7867@gmail.com", "", " R/o Kreeri P/O Kreeri Pin code 193108, Dist.-Baramulla J&k "}, 
		{"Jammu & Kashmir", "Shangus", "Gulzar Ahmad Wani", "जम्मू और कश्मीर", "Shangus", "Gulzar Ahmad Wani",  "  9596143123", "", "", "", "", " CHITTER GULL P/O ALBABAL "}, 
		{"Jammu & Kashmir", "Shopian", "Mohammad Yousuf Bhat", "जम्मू और कश्मीर", "Shopian", "Mohammad Yousuf Bhat",  "  01933-260244 ", " 9419019031 ", " 9697019031", " advocatemybhat@gmail.com", "", " New Colony Meemander Shopian "}, 
		{"Jammu & Kashmir", "Sonawar", "Mohammad Ashraf Mir", "जम्मू और कश्मीर", "Sonawar", "Mohammad Ashraf Mir",  "  0194-2465172 ", " 9419001485 ", "", " asmccpvtltd@gmail.com", "", " Resident-By-Pass CrossingAthwajan Srinagar J&K "}, 
		{"Jammu & Kashmir", "Sonawari", "Mohd. Akbar Lone", "जम्मू और कश्मीर", "Sonawari", "Mohd. Akbar Lone",  "  09419000812", " 09697001301", "", "", "", " R/o Naidkhai BPO Naidkhai P/O Sambal "}, 
		{"Jammu & Kashmir", "Sopore", "Abdul Rashid Dar", "जम्मू और कश्मीर", "Sopore", "Abdul Rashid Dar",  "  9419000887", "", "", " hajibdulrashiddar@gmail.com", "", " Vill. Dangerpora Tehsil Dangerpora, Dist. Baramulla, J&K State "}, 
		{"Jammu & Kashmir", "Suehetgarh", "Sham Lal Choudhary", "जम्मू और कश्मीर", "Suehetgarh", "Sham Lal Choudhary",  "  9419184926", "", "", " mlashamchoudhary@gmail.com", "", " Resident -V.P.O.Chakrohi ,Teh Suchetgarh Distt.Jammu "}, 
		{"Jammu & Kashmir", "Surankote", "Ch Mohd Akram", "जम्मू और कश्मीर", "Surankote", "Ch Mohd Akram",  "  9797569112", "", "", "", "", " Lassana, Teh.Surankote "}, 
		{"Jammu & Kashmir", "Tral", "Mushtaq Ahmad Shah", "जम्मू और कश्मीर", "Tral", "Mushtaq Ahmad Shah",  "  9419004995", " 9797112501", "", "", "", " Tral-i-bala, Teh.Tral "}, 
		{"Jammu & Kashmir", "Udhampur", "Pawan Kumar Gupta", "जम्मू और कश्मीर", "Udhampur", "Pawan Kumar Gupta",  "  9419160307", "", "", "", "", " R/O Shiv Shanti Niwas, Near Forest Range Office, Ward No. 12, Udhampur 182101 "}, 
		{"Jammu & Kashmir", "Uri", "Mohammed Shafi", "जम्मू और कश्मीर", "Uri", "Mohammed Shafi",  "  09868181943", "", "", " m.shafiuri@gmail.com", "", " Village Garkote Teh Url, Dist Baramulla J&K. "}, 
		{"Jammu & Kashmir", "Vijaypur", "Chander Parkash", "जम्मू और कश्मीर", "Vijaypur", "Chander Parkash",  "  9419199053", "", "", " chanderprakashganga@gmail.com", "", " Adda Sarore(Kartholi), Teh.Bari Brahmana, Dist.Samba "}, 
		{"Jammu & Kashmir", "Wachi", "Aijaz Ahmad Mir", "जम्मू और कश्मीर", "Wachi", "Aijaz Ahmad Mir",  "  9906628600", " 8803453618", "", "", "", " Resident of Zainapora Shopian "}, 
		{"Jammu & Kashmir", "Zadibal", "Abid Hussain Ansari", "जम्मू और कश्मीर", "Zadibal", "Abid Hussain Ansari",  "  9419407665", "", "", "", "", " Sheri Kashmir Colony, Darul-Jawad, Qamarwari, Teh. & Dist.Srinagar, Kashmir "}, 
		{"Jammu & Kashmir", "Zanskar", "Syed Mohammad Baqir Rizvi", "जम्मू और कश्मीर", "Zanskar", "Syed Mohammad Baqir Rizvi",  "  9469210149", "", "", "", "", " Residence Of Panikhar Tai Suru "}, 

	};

}