/* Auto-generated file from db2MPjava.php*/

    package in.filternet.jantamalik.Rajya;

    public final class Kerala {

    	public static final String[][] MLAs = {

		{"Kerala", "Adoor (SC)", "Chittayam Gopakumar", "केरल", "अडूर (एस सी)", "Chittayam Gopakumar",  "  9847103731", "", "", " chittayam@gmail.com", "", " Shangrila, Konnamankara, Adoor, PO, 691523 "},
		{"Kerala", "Alappuzha", "Thomas Isaac.T.M", "केरल", "अलप्पुझा", "Thomas Isaac.T.M",  "  9447733600", "", "", " tisaaq@gmail.com", "", " 10/1212 A(NEW 1212), MLA OFFICE,JILLACOURT ALAPUZHA,MUNICIPALITY, PINCODE:688013 "},
		{"Kerala", "Alathur", "Prasenan K D", "केरल", "अलथुर", "Prasenan K D",  "  9495056056", "", "", " KDP056@gmail.com", "", " Kizhakkumpuram House, Kattusseri, Alathur,Palakkad 678541 "},
		{"Kerala", "Aluva", "Anvar Sadath", "केरल", "अलुवा", "Anvar Sadath",  "  9846887886", "0484-2623003", "", " anwarsadath18@gmail.com", "", " Oolikkara House, Perumbayam, Nedumbassery P.O., Chengamanad,Aluva Taluk, PIN - 683 585 "},
		{"Kerala", "Ambalappuzha", "G.sudhakaran", "केरल", "अम्बालापुझा", "G.sudhakaran",  "  2266853", " 9447755200", "", " mlaofficeambalapuzha@gmail.com", "", " NAVANEETHAM, SANATHANAPURAM .P.O ALAPUZHA. "},
		{"Kerala", "Angamaly", "Roji M John", "केरल", "अंगमाल्य", "Roji M John",  "  9971392134", " 9544355555", "", " rojimjohn@gmail.com", "", " Mullanmadackal House, Ayroor. P.O.Ernakulam Pin.683579. Kerala "},
		{"Kerala", "Aranmula", "Veena George", "केरल", "अरानमुला", "Veena George",  "  8547007032", "", "", " veenageorge03@gmail.com", "", " velasheeri pala muttathu veedu, kozhencherry, mylipara po,Pathanamthitta "},
		{"Kerala", "Aroor", "A.M.Ariff", "केरल", "अरूर", "A.M.Ariff",  "  9447260665", "", "", " ariffmla@gmail.com", "", " Aarunyam,iruvakad ward,thiruvambadi p.o alapuzha,688002 "},
		{"Kerala", "Aruvikkara", "Sabarinadhan.K.S", "केरल", "अरुविक्कारा", "Sabarinadhan.K.S",  "  0471-2315596", " 9447736033", "", " sabari.ks@gmail.", "com", " Abhayam, T.C-9/2130/1(OLD) 31/2007(New), B-21 Sreerangom Lane Sasthamangalam, Thiruvannathapuram-695010 "},
		{"Kerala", "Attingal (SC)", "B.Satyan", "केरल", "अत्तिन्गल (एस सी)", "B.Satyan",  "  9447142211", " 04712542211", "", " satyanmla@gmail.com", "", " Boys Land, Anupamanagar, Muttoda. P.O. "},
		{"Kerala", "Azhikode", "K M Shaji", "केरल", "अझिकोड", "K M Shaji",  "  9895488888", "", "", " kmshaji111@gmail.com", "", " House No-5 Alliance Greens Village Ottathengu, Manal Alavil Kannur 670008, Kannur Taluk & District "},
		{"Kerala", "Balusseri (SC)", "Purushuan Kadalundy", "केरल", "बलुसेरी (एस सी)", "Purushuan Kadalundy",  "  9495677127", "", "", " purushanepim@gmail.com", "", " Thanal, Thondayad, Chevarambalam P O "},
		{"Kerala", "Beypore", "V K C Mammed Koya", "केरल", "बयपुर", "V K C Mammed Koya",  "  9847002412", "", "", " vkcmammedkoya@vkcgroup.com", "", " Veluthedathu, Cheruvannoor, Kolathara P O, PIN-673655 "},
		{"Kerala", "Chadayamangalam", "Retnakaran", "केरल", "चदयमंगलम", "Retnakaran",  "  0474-2472888", " 9846347900", "", " mullakkararetnakaran@gmail.com", "", " Ragam, Ambalakara.P.O, Kottarakara. "},
		{"Kerala", "Chalakudy", "B D Devassy", "केरल", "चलाकुडी", "B D Devassy",  "  9446087325", "", "", " bddevassy@gmail.com", "", " Bhrammakulathu Kunnikuru veedu,Palamuri Kenuoor,Nalukettu Po,680308 "},
		{"Kerala", "Changanassery", "C F Thomas", "केरल", "चंगनासैरी", "C F Thomas",  "  0401-242530", "", "", "", "", " Chennikkara House, Angadi, Changassery "},
		{"Kerala", "Chathannoor", "G.S.Jayalal", "केरल", "चथन्नूर", "G.S.Jayalal",  "  9447092323", "", "", " gsjayalalmla@gmail.com", "", " S.G. Vihar, Chirakkara P.O. Kollam "},
		{"Kerala", "Chavara", "N.Vijayan Pillai", "केरल", "चावरा", "N.Vijayan Pillai",  "  9447074190", "", "", " chavaravijayanpillai@gmail.com", "", " Vijayasree, Madappally, Mukundapuram Po., Chavara 691585 "},
		{"Kerala", "Chelakkara (SC)", "U R Pradeep", "केरल", "चेल्लकारा (एस सी)", "U R Pradeep",  "  9072052295", " 9947644311", "", " pradeepdsm@gmail.com", "", " Santha Nivas, Thekkepurackal Veedu, Kondayoor Desham Valloor P.O "},
		{"Kerala", "Chengannur", "Ramachandran Nair", "केरल", "चेंगनूर", "Ramachandran Nair",  "  9447596250 ", " 0479-2452879", " 0479-2453088", "", "", " Prasanth Bhavan, Ala PO, Ala Village, Chengannur Taluk, Alappuzla Dist., Kerala Pin 689126 "},
		{"Kerala", "Cherthala", "Thilothaman", "केरल", "चेरथला", "Thilothaman",  "  9497245656", "", "", " pthilothaman@gmail.com", "", " CHERTHALA THEKKE VILLAGE,KURUPUMKULANAGARA P.O VATTATARA VEETIL "},
		{"Kerala", "Chirayinkeezhu", "V Sasi", "केरल", "चिरयिनकीजहु", "V Sasi",  "  09847311660", "", "", " chrayinkeezhumla@gmail.com", "", " Poika, TC 2/1152(1) 13/2448 paloor lane medical college trivamdrum "},
		{"Kerala", "Chittur", "Krishnankutty K", "केरल", "चित्तूर", "Krishnankutty K",  "  9447012369", "", "", " kkrishnankutti@gmail.com", "", " Ezhuthani Kalam Vilayodi, PO- Vilayodi Pin No- 678103 "},
		{"Kerala", "Devikulam (SC)", "S Rajendran", "केरल", "देवीकुलम (एस सी)", "S Rajendran",  "  9447051410", "", "", " mlarajendran@gmail.com", "", " 17/1886, Ikka Bhavan, Ikka Nagar, Munnar, P.o 685612 "},
		{"Kerala", "Dharmadam", "Pinarayi Vijayan", "केरल", "धर्मदम", "Pinarayi Vijayan",  "  9447135000", "", "", "", "", " Pravik Pandyala Mukku, P.O.- Pinarayi Pin No- 670741 "},
		{"Kerala", "Elathur", "A K Saseendran", "केरल", "एलाथुर", "A K Saseendran",  "  9847001879", "", "", " elathur-mla@niyamasabha.org", " sasindranak2014@gmail.com", " Varsha, Chowa, Kannur "},
		{"Kerala", "Ernad", "P K Basheer", "केरल", "एरानाड", "P K Basheer",  "  9496606060", " 0483-2700394", "", " pkb394@gmail.com", "", " FHIRDOUSE, HOUSE NO.4/281,PATHAPPIRIYAM.P.O.MALAPPURAM.DIST.676123 "},
		{"Kerala", "Ernakulam", "Vinod", "केरल", "एर्नाकुलम", "Vinod",  "  9447044047", "", "", " tjvinod3@gmail.com", "", " 32/118, Thaivelikkakathu House, Naroth Road, Thammanam PO, Ernakulam Kochi 682032 "},
		{"Kerala", "Eravipuram", "M. Noushad", "केरल", "एरविपुरम", "M. Noushad",  "  9447454097", "", "", "", "", " THENGAZHIKAM,MANACAUD VADAKKEVILA PO "},
		{"Kerala", "Ettumanoor", "Suresh Kurup", "केरल", "एट्टुमनूर", "Suresh Kurup",  "  9446333730", "", "", " adv.k.sureshkurup@gmail.com", "", " Kuttikkattu House,Thirunakkara Kara, Thirunakkara. P.O., Kottayam. "},
		{"Kerala", "Guruvayoor", "K.V. Abdul Khader", "केरल", "गुरुवायुर", "K.V. Abdul Khader",  "  0487-2532900", "", "", " kvabdulkhader@gmail.com", "", " Karappan Vettil House, P.O.Blangad, Chavakkad Taluk "},
		{"Kerala", "Haripad", "Ramesh Chennithala", "केरल", "हरिपद", "Ramesh Chennithala",  "  9447777100 ", " 0479-2415555", "", " rameshchennithala@gmail.com", "", " Kottoor Kizhakkethil Thripperumthura PO, Chennithala, Mavelikkara, Alleppey Dist., Kerala, Pin 690105 "},
		{"Kerala", "Idukki", "Roshy Augustine", "केरल", "इडुक्की", "Roshy Augustine",  "  9447021314", "", "", " roshymla@gmail.com", "", " R/O Cherunilathuchalil, Vazhathope, Thadiampadu PO., Idukki "},
		{"Kerala", "Irikkur", "K C Joseph", "केरल", "इरिक्कुर", "K C Joseph",  "  9447074003", "", "", " sarahandyesph@gmail.com", "", " Karuvelithara House,congress House,Indira Bhavan,Sreekandapuram. P.O "},
		{"Kerala", "Irinjalakuda", "Prof. K.U. Arunan", "केरल", "इरिन्जालकुडा", "Prof. K.U. Arunan",  "  9497560097", "", "", " kuarunan@gmail.com", "", " KUMBALAPARAMBIL HOUSE, EDATHURUTHIL PO "},
		{"Kerala", "Kaduthuruthy", "Adv. Mons Joseph", "केरल", "कादुतुर्ती", "Adv. Mons Joseph",  "  9447306270", " 04828282666", "", " admonsjoseph@gmail.com", "", " Narimattathumyalil, Poozhikkol P.O., Kaduthuruthi "},
		{"Kerala", "Kaipamangalam", "E T Taison Master", "केरल", "कइपमंगलम", "E T Taison Master",  "  9846958317", "", "", "", "", " Elanjikal Kannathupadikkal House, Kara, P.O. Kodugallur, Thrissur "},
		{"Kerala", "Kalamassery", "V K Ibrahim Kunu", "केरल", "कलमस्सरी", "V K Ibrahim Kunu",  "  9846099400", "", "", " ebrahimkunjuvk@gmail.com", "", " R/O Valiyaparambil, Kongorpilly PO., Ernakulam (Dt.)-683518 "},
		{"Kerala", "Kalliasseri", "T V Rajesh", "केरल", "कालियासीरी", "T V Rajesh",  "  9446400828", "", "", " tvrajeshmla@gmail.com", "", " R/O Kulappuram, Vilayancode (PO.), Cheruthazham Village, Kannur Taluk "},
		{"Kerala", "Kalpetta", "C K Saseendran", "केरल", "कालपेट्टा", "C K Saseendran",  "  9446891227", " 04936-205729", "", " cksaseendranwayanad@gmail.com", "", " R/O Ushas, Ponnada, Maniyankode Post, Kalpetta Village, Vythiri Taluk, Wayanad District "},
		{"Kerala", "Kanhangad", "E.Chandrashekaran", "केरल", "कान्हागढ़", "E.Chandrashekaran",  "  4994-237669", "", "", "", "", " Parvath Perumbala, Perumbala P.O. Kalanad, Kasargod Dist. "},
		{"Kerala", "Kanjirappally", "Dr. N Jayaraj", "केरल", "कंजीरापल्ली", "Dr. N Jayaraj",  "  9447464451", "", "", " n.jayaraj.vazhoor@gmail.com", "", " SANGIVANAM HOUSE , CHEMBAKARA P/O KARUKACHAL ,KOTTAYAM "},
		{"Kerala", "Kannur", "Ramachandran Kadannappalli", "केरल", "कन्नूर", "Ramachandran Kadannappalli",  "  9447150599 ", " 9446423727", "", " ramachandran.kadannappallil505@gmail.com", "", " NO/5 Manikya Jawahal N agar Housing colony Kannur "},
		{"Kerala", "Karunagappally", "R.Ramachandran", "केरल", "करुनागाप्पली", "R.Ramachandran",  "  9447160458", "", "", "", "", " Kalathil, Kallelibhagom.P.O, Kallelibhagom, Karunagappally. "},
		{"Kerala", "Kasaragod", "N A Nellikkunnu", "केरल", "कासरगोड", "N A Nellikkunnu",  "  9447010338", "", "", " nanellikunnu@yahoo.com", "", " Bangara Kunnu Road, Nellikunnu Kasargo,671121 "},
		{"Kerala", "Kattakkada", "Satheesh", "केरल", "कात्तक्कड़ा", "Satheesh",  "  9446558430", "", "", " balaksatish@gmail.com", "", " Ashwathy Bhawan, Kandala P.O, Koovalasseri (via), Tiruvananthapuram-695512. "},
		{"Kerala", "Kayamkulam", "Adv.U.Prathibha Hari", "केरल", "कायमकुलम", "Adv.U.Prathibha Hari",  "  9495465666", "", "", "", "", " PAYYINARPADI VEETIL THAKIZHI P O "},
		{"Kerala", "Kazhakkoottam", "Kadakampally Surendran", "केरल", "कझाकुट्टम", "Kadakampally Surendran",  "  9447048543", "", "", " kadakampallysurendran99@gmail.com", "", " Kadampally Veedu, Karikkom, Tibamil "},
		{"Kerala", "Kochi", "K J Maxi", "केरल", "कोच्चि", "K J Maxi",  "  9447136374", " 0484-2236374", "", " kjmaxy@gmail.com", "", " Konnoth House, 16/1741 (9/1043), Kochi 682005 "},
		{"Kerala", "Kodungallur", "V R Sunilkumar", "केरल", "कोडुन्गल्लुर", "V R Sunilkumar",  "  0480-2802690", " 9656965759", "", " sunilkumar69@gmail.com", "", " VATTAPARABIL House pulloor p.o kodangallur-680663 "},
		{"Kerala", "Koduvally", "Karat Razack", "केरल", "कोदुवल्ली", "Karat Razack",  "  9446373743", "", "", " karatrazak.743@gmail.com", "", " KARAT HOUSE KODUVALI "},
		{"Kerala", "Kollam", "M Mukesh", "केरल", "कोल्लम", "M Mukesh",  "  9847072122", " 9447072122", "", " mukeshomadhavan@yahoo.co.in", "", " Kizhakke Veedu, Vadakkevila, Kollam 691010 "},
		{"Kerala", "Kondotty", "Ibrahim T V", "केरल", "कोंडोट्टी", "Ibrahim T V",  "  04832774400", " 09446774400", "", " tvibrabeen@gmail.com", "", " Thazhathuveettil House Valluvambram(PO), Malappuram Pin No- 673642 "},
		{"Kerala", "Kongad (SC)", "Vijayadas", "केरल", "कोंगड (एस सी)", "Vijayadas",  "  9447183343", "", "", " kvvijayadasmla@gmail.com", "", " Kakkathodu veedu Thenari p.o Elappulli Palakkadu "},
		{"Kerala", "Konni", "K.U.Jenish Kumar", "केरल", "कोणी", "K.U.Jenish Kumar",  "  9446115329", " 6238044859", "", "", "", " Resident-Kalayil House Kochukoikkal P.o.-Seethaode, Pathanamthitta -689667 "},
		{"Kerala", "Kothamangalam", "Antony Johny", "केरल", "कोठमंगलम", "Antony Johny",  "  9946640994", " 0485-2861558", "", " antonykothamangalam@gmail.com", "", " Kumbappilly House, Kozhippilly, Kozhippilly P.O., Kothamangalam, Pin 686691 "},
		{"Kerala", "Kottakkal", "Abid Hussain Thangal", "केरल", "कोट्टाकल", "Abid Hussain Thangal",  "  9447282329", "", "", " abthangal@gmail.com", "", " Kodakkadakath,Vadakkumkara P O Malapuram "},
		{"Kerala", "Kottarakkara", "Adv. P.Aisha Potty", "केरल", "कोट्टरक्कारा", "Adv. P.Aisha Potty",  "  9447557370", " 0474-2454268.", "", " aishapotty@yahoo.com", "", " Sree Shankaram, Padinjattinkara, Kottarakara.P.O, Pin.691506. "},
		{"Kerala", "Kottayam", "Thiruvanchoor Radhakrishnan", "केरल", "कोट्टायम", "Thiruvanchoor Radhakrishnan",  "  9447018116", " 0481-2568116", "", " thiruvanchoor.radhakrishnan@gmail.com", "", " MADASA VAYASKARAKUNNU KODIMATHA, KOTTAYAM 686013 "},
		{"Kerala", "Kovalam", "M.Vincent", "केरल", "कोवलम", "M.Vincent",  "  9847346077", "", "", " mvincentblpm1234@gmail.com", "", " Vattavilakathu Veedu, R.C.Street, Balaramapuram P.O, Tiruvananthapuram Dist. "},
		{"Kerala", "Kozhikode North", "A Pradeep Kumar", "केरल", "कोझिकोड उत्तर", "A Pradeep Kumar",  "  9447130082", "", "", " pradeepkumar64@gmail.com", "", " 38/261 C, Neelambari, West Hill P.O., Kozhikode - 673005 "},
		{"Kerala", "Kozhikode South", "Dr. M.k.muneer", "केरल", "कोझिकोड दक्षिण", "Dr. M.k.muneer",  "  9947041000", " 9446042285", "", " mkmuneer2@gmail.com", "", " Mehfil Jafar Khan Colony Kozhikode 6, "},
		{"Kerala", "Kundara", "J.Mercy Kutty Amma", "केरल", "कुंदरा", "J.Mercy Kutty Amma",  "  9447024855", "", "", " mercykuttyamma@gmail.com", "", " Ashwathi, Vellimon P.O, Keralapuram, Kollam "},
		{"Kerala", "Kunnamangalam", "Adv. P.T.A. Rahim", "केरल", "कुन्नमंगलम", "Adv. P.T.A. Rahim",  "  9847510238", "", "", " ptarahim@gmail.com", "", " misfa koduvali po kozhikode 673572 "},
		{"Kerala", "Kunnamkulam", "A C Moideen", "केरल", "कुन्नमकुलम", "A C Moideen",  "  04884-265545", " 9447390239", "", " acmoideen56@gmail.com", "", " Resident of Akkaparambil House, Panangatturkara P.O., Pin-680623, Thekkumkara Vill., Thalappilly Taluk, Thrissur Dist. "},
		{"Kerala", "Kunnathunad (SC)", "V P Sajeendran", "केरल", "कुणथुनाद (एस सी)", "V P Sajeendran",  "  9447065000", "", "", " sajeendranvp@gmail.com", "", " Vallothiamala, Kolenchery, Ernakulam "},
		{"Kerala", "Kunnathur (SC)", "Kovoor Kunjumon", "केरल", "कुन्नथूर (एस सी)", "Kovoor Kunjumon",  "  9447500371", "", "", " kovoorkunjumon@gmail.com", "", " Charuvilayil Kovoor Arinalloor Kollam-690538 "},
		{"Kerala", "Kuthuparamba", "K K Shailaja Teacher", "केरल", "कुतुपरम्बा", "K K Shailaja Teacher",  "  9447694326", "", "", " KKshailajateacher@gmail.com", "", " Aarathi Pazhassi Uruvachal "},
		{"Kerala", "Kuttanad", "Thomas Chandy", "केरल", "कुट्टनाद", "Thomas Chandy",  "  9447051333", "", "", " vettikad@hotmail.com", "", " Vettikadu, Chennamkary Kuttanadu "},
		{"Kerala", "Kuttiadi", "Parakkal Abdulla", "केरल", "कुट्टियदी", "Parakkal Abdulla",  "  9544161616", "", "", " parakkalabdulla@gmail.com", "", " Resident of Thazhe Parakkal, Eramala, Vatakara "},
		{"Kerala", "Malampuzha", "Achuthanandan", "केरल", "मालमपुझा", "Achuthanandan",  "  09447711500", "", "", "", "", " Velikkakathu, Punnapra North PO- Alappuzha 688014 "},
		{"Kerala", "Malappuram", "Ubaidulla", "केरल", "मलप्पुरम", "Ubaidulla",  "  9447353079", " 04832848121", "", " pubaidulla.akm@gmail.com", " paubaidullamla@gmail.com", " Poojakkanni House, Anakkayam "},
		{"Kerala", "Manalur", "Murali", "केरल", "मनालुर", "Murali",  "  9447015284", "", "", " mperunelly@gmail.com", "", " perunelli veedu, oorakam, pathiyarkulangara po "},
		{"Kerala", "Mananthavady (ST)", "O R Kelu", "केरल", "मनंतवाड़ी (एस टी)", "O R Kelu",  "  9446545146", "", "", "", "", " Olenchery Puthenmittam House, Kartikulam Post Thrissilery Village Mananthavady Taluk Wayanand Dist. "},
		{"Kerala", "Manjeri", "Ummer", "केरल", "मंजेरी", "Ummer",  "  9447004515", "", "", " MUMMERMANJERI@GMAIL.COM", "", " MAMBADAN HOUSE, CHERANI, KARUVAMPRAM PO, MANJERI "},
		{"Kerala", "Manjeshwar", "M C Kamaruddin", "केरल", "मंजेश्वर", "M C Kamaruddin",  "  9447077647", " 9446077647", "", " mckamaruddin@gmail.com", "", " Resident of Karma Edachakal Post Udinpur ,Hosdurg Taluk ,Kasargod 671310 "},
		{"Kerala", "Mankada", "Ahammed Kabeer", "केरल", "मनकादा", "Ahammed Kabeer",  "  9447153246", "", "", " sargadhara@gmail.com", "", " tazni manzil, pathadipalam, changampuzha nagar, po, kochi-33 "},
		{"Kerala", "Mannarkkad", "Adv. N. Samsudheen.N", "केरल", "मन्नारकड", "Adv. N. Samsudheen.N",  "  9447340892", "", "", " advsamsu@gmail.com", "", " R/O Kolappat House, Paravanna Post, Tirur, Malappuram District. "},
		{"Kerala", "Mattannur", "E. P. Jayarajan", "केरल", "मत्तनूर", "E. P. Jayarajan",  "  9447087633", "", "", " epjayarajan@gmail.com", "", " Jaisons, Ikal, Aroli, Pappinasherry,Kannur "},
		{"Kerala", "Mavelikkara (SC)", "R.Rajesh", "केरल", "मवेलिक्कारा (एस सी)", "R.Rajesh",  "  9605838180 ", "", "", " rajeshmvkmla@gmail.com", "", " BAD SCAN "},
		{"Kerala", "Muvattupuzha", "Eldho Abraham", "केरल", "मुवत्तुपुषा", "Eldho Abraham",  "  9447700958", "", "", "", "", " Meppurathu House, Thrikkalathoor P.O.Muvattupuzha-683557 "},
		{"Kerala", "Nadapuram", "E K Vijayan", "केरल", "नादपुरम", "E K Vijayan",  "  9447426175", "", "", " ekvijayan1952@gmail.com", "", " Komath Veedu Kollam P.O Koyilandi(vazhi) Kozhikkodu District Pin:673307 "},
		{"Kerala", "Nattika (SC)", "Geetha", "केरल", "नट्टिका (एस सी)", "Geetha",  "  9961264111", " 9447671020", "", " geethagopimlamattika@gmail.com", "", " Kakkat(H),Desabhimani Road, Guruvayur, Thrissur-680101 "},
		{"Kerala", "Nedumangad", "Divakaran.C", "केरल", "नेदुमंगड़", "Divakaran.C",  "  9447777300", "", "", " com.cdivakaran@gmail.com", "", " Deepam T.C 43/258(New 61/2540) ERA 118, Thottam Manacaud Thiruvananthapuram Pin No- 695009 "},
		{"Kerala", "Nemom", "O Rajagopal", "केरल", "नेमम", "O Rajagopal",  "  9447095118", "", "", " o.rajagopalbjp@gmail.com", "", " DO safair javaharnagar kavadiyar TVM "},
		{"Kerala", "Nenmara", "K. Babu", "केरल", "नेनमारा", "K. Babu",  "  9447514738", "", "", " babuknenmara123@gmail.com", "", " Sreedalam, Pezhumpara,Chathamangalam P O, Nenmara "},
		{"Kerala", "Neyyattinkara", "K.Ansalan", "केरल", "नय्यट्टिनकरा", "K.Ansalan",  "  9995191282", "", "", " kanasalannta@gmail.com", "", " Vattavila puthen veedu, vazhuthoor "},
		{"Kerala", "Nilambur", "P. V. Anvar", "केरल", "नीलाम्बुर", "P. V. Anvar",  "9447060901", "", "", "nilambur-mla@niyamasabha.nic.in", "pranvarindia@gmail.com", "PUTHAN VEETIL PERAKAMANA PO MALAPPURAM 676541"},
		{"Kerala", "Ollur", "Adv. K. Rajan", "केरल", "ओल्लुर", "Adv. K. Rajan",  "  4872636836", " 9961375280", "", " krajanaiyf@gmail.com", "", " Pulikkal House, Anthikad P.O., Thrissur - 680641 "},
		{"Kerala", "Ottappalam", "Unni P", "केरल", "ओट्टापलम", "Unni P",  "  0491-2506060", "9447144246", "", " unnicpim@gmail.com", "", " Aayilyam (H)karinkarapully PO,Palakkad "},
		{"Kerala", "Pala", "K M Mani", "केरल", "पाला", "K M Mani",  "  04822215471", "", "", " manikmpala@gmail.com", "", " Karinagazhackal, Pala "},
		{"Kerala", "Palakkad", "Shafi Parambil", "केरल", "पलक्कड़", "Shafi Parambil",  "  9400000006", "", "", " shafiparambilpkd@gmail.com", "", " A19 New Civil Nagar Palakkadu "},
		{"Kerala", "Parassala", "C.K.Harindrakumar", "केरल", "परस्सला", "C.K.Harindrakumar",  "  9447696005", "", "", " ckhparassala@gmail.com", "", " Sindhuram Maruthur Kuttappana Neyyattinkara P.o "},
		{"Kerala", "Paravur", "V D Satheesan", "केरल", "पारावुर", "V D Satheesan",  "  9447018183", "", "", " vdsatheesan@gmail.com", "", "Devaragam, Kesari Junction, North Paravur "},
		{"Kerala", "Pathanapuram", "K.B. Ganesh Kumar", "केरल", "पठानपुरम", "K.B. Ganesh Kumar",  "  9447747274", "", "", " ganeshkumarkb@gmail.com", "", " 4/504,KRISHNA,MANCHOOLR,PATHANAPURAM PO PIN 689695 "},
		{"Kerala", "Pattambi", "Muhammed Muhassin", "केरल", "पट्टाम्बि", "Muhammed Muhassin",  "  9895319684", "", "", " MUHASSINP@GMAIL.COM", "", " PUTHANPIDIKIL PO KONDURKARA 679313 "},
		{"Kerala", "Payyannur", "C Krishnan", "केरल", "पय्यन्नूर", "C Krishnan",  "  9446630930", "", "", " Paymala @gmail.com", "", " Chorootta House. P.O. Velloor, Poyyanur "},
		{"Kerala", "Peerumade", "E S Bijimol", "केरल", "पीरमदे", "E S Bijimol",  "  9446225273", "", "", " esbijimolmla@gmail.com", "", " R/O Panthalooparambil House, Elappara Po., Pin 685501, Elappara Village "},
		{"Kerala", "Perambra", "T P Ramakrishnan", "केरल", "पेराम्ब्रा", "T P Ramakrishnan",  "  9446485543", "04962610894", "", " t.pramakrishnan49@gmail.com", "", " Kottarakkal Veedu, Nochad P O,Naduvanoor "},
		{"Kerala", "Peravoor", "Adv. Sunny Joseph", "केरल", "पेरावूर", "Adv. Sunny Joseph",  "  9447046694", "", "", "", "", " Payyam Village P.O. irrity Kannur "},
		{"Kerala", "Perinthalmanna", "Ali Manjalamkuzhi", "केरल", "पेरिन्तल्मन्ना", "Ali Manjalamkuzhi",  "  9846222202", " 9447082166", "", " manjalamkuzhi@gmail.com", "", " R/O Panangangara, Ramapuram PO., Malappuram District., Pin 679350 "},
		{"Kerala", "Perumbavoor", "Eldose P Kunnappally", "केरल", "पेरुम्बवूर", "Eldose P Kunnappally",  "  9446300547", "", "", " eldhoseiyc@gmail.com", "", " Kunnappillilveedu,South Maradi P O, Moovattupuzha "},
		{"Kerala", "Piravom", "Anoop Jacob", "केरल", "पिरवोम", "Anoop Jacob",  "  9447303934", "", "", " anoopjacobpvm@gmail.com", "", " Thannekunnel, Oliyappuram, PO- Koothattukulam "},
		{"Kerala", "Ponnani", "P.Sreeramakrishnan", "केरल", "पोन्नानी", "P.Sreeramakrishnan",  "  9447799329", "", "", " sveedyfi@gmail.com", "", " Niranjanam, Pattambi Road, Perinthalmanna, Malappuram "},
		{"Kerala", "Poonjar", "P C George", "केरल", "पून्जार", "P C George",  "  9447043027", " 04822-272114", "", " pcgeorge100@gmail.com", "", " planthottam vettil,perunilamkara,Aruvithura.p.o-686122 "},
		{"Kerala", "Punalur", "Adv.K.Raju", "केरल", "पुनलुर", "Adv.K.Raju",  "  9447864486", " 0475-2273914", "", " krajumlapunalur@gmail.com", "", " Puthenpura Veedu, Nediyara P.O, Nettayam, Eroor Village, Punalur, Kollam Dist. "},
		{"Kerala", "Puthukkad", "C Raveendranathan", "केरल", "पुतुक्कड़", "C Raveendranathan",  "  9446848800", " 9349759468", "", " ravinath101@gmail.com", "", " Thrisur kanatukara po 68011 panthalathuline Lakshmi bhavan "},
		{"Kerala", "Puthuppally", "Oommen Chandy", "केरल", "पुथुप्पली", "Oommen Chandy",  "  0481-2351135", "", "", "", "", " Karottuvallakkalil House, Puthuppally Po. "},
		{"Kerala", "Quilandy", "K.Dasan", "केरल", "कोयिलान्दी", "K.Dasan",  "  9447721922", "", "", " kdasan2016@gmail.com", "", " Viyoor village, puliyancherry po,quilandy "},
		{"Kerala", "Ranni", "Raju Abraham", "केरल", "राणी", "Raju Abraham",  "  9447125090", "", "", " rajumla7@gmail.com", "", " KANDANAD VEETIL ANGADHI MURIYAL PO RANNI KERALA PIN 689674 "},
		{"Kerala", "Shoranur", "Sasi P K", "केरल", "शोरानूर", "Sasi P K",  "  9447036295", "", "", " pksasimkd@gmail.com", "", " pandamangalam (H)kottapuram po, shornur "},
		{"Kerala", "Sulthanbathery (ST)", "I C Balakrishnan", "केरल", "सुल्तानबथरी (एस टी)", "I C Balakrishnan",  "  9947675080", "", "", " mlaicbalakrishnan@gmail.com", "", " ILLATHUMULA VEED, VALAD POST, THALAPUZHA (VIA), PIN-670644 "},
		{"Kerala", "Taliparamba", "James Mathew", "केरल", "तालीपरम्बा", "James Mathew",  "  9447706782", "", "", " jamesmathewknr@gmail.com", "", " Sukritham, Ramatheru Pallikunnu P.O. Kannur-4, "},
		{"Kerala", "Tanur", "V Abdurahiman", "केरल", "तनुर", "V Abdurahiman",  "  9895804000", "", "", " AMANKSA@GMAIL.COM", "", " VELLEKKATTU VEEDU, POOKAYIL BAZAR PO, TIRUR "},
		{"Kerala", "Tarur (SC)", "A K Balan", "केरल", "थरूर (एस सी)", "A K Balan",  "  9846361111", "", "", "", "", " Janani, Parakkunnam, Palakkad, "},
		{"Kerala", "Thalassery", "Adv. A N Shamseer", "केरल", "थलसेरी", "Adv. A N Shamseer",  "  9447056803", "", "", " anshamseer2@gmail.com", "", " Ameenas P.O. Paral Thalasserry 670671 "},
		{"Kerala", "Thavanur", "K.T. Jaleel", "केरल", "तवानुर", "K.T. Jaleel",  "  9895073107", "", "", " drktjaleel1967@gmail.com", "", " Ghazal , kooriparambil thekkumpattum (h)thozhuvanthal po,malappuram "},
		{"Kerala", "Thiruvalla", "Mathew T Thomas", "केरल", "तिरुवल्ला", "Mathew T Thomas",  "  9447802865", "", "", " mathewthomastvla@gmail.com", "", " Thoompumpattu House Kuttapuzha PO- Thiruvalla, Pathanamathitta Dist- 689103 "},
		{"Kerala", "Thiruvambadi", "George M. Thomas", "केरल", "तिरुवाम्बड़ी", "George M. Thomas",  "  9447159028", "", "", " gmt.tmbdy@gmail.com", "", " MEKKATUKUNNEL PANAMBILAVUPO 673639 "},
		{"Kerala", "Thiruvananthapuram", "V S Sivakumar", "केरल", "तिरुवनंतपुरम", "V S Sivakumar",  "  9447586061", " 9447401543", "", " vss4tvm@gmail.com", "", " R/O TC-9/2376(3), Sreerangam Lane, Sasthamangalam PO., Thiruvananthapuram, Pin 695010 "},
		{"Kerala", "Thodupuzha", "P.J. Joseph", "केरल", "थोडुपुझा", "P.J. Joseph",  "  9495766600", "", "", " palathinaljoseph@gmail.com", "", " R/O Palathinal House, Purapuzha Kara, Purapuzha Village, Thodupuzha Taluk 685583 "},
		{"Kerala", "Thrikkakara", "P T Thomas", "केरल", "त्रिक्ककारा", "P T Thomas",  "  9447029595", "", "", " ptthomasidk@gmail.com", "", " Puthiyaparambil, H.No. 44/1362 (27/41/100A) Vylassery Road, Palarivattom P.O. Kochi - 682025 "},
		{"Kerala", "Tripunithura", "M Swaraj", "केरल", "त्रिपुणितुरा", "M Swaraj",  "  9447681581", "", "", " swarajdyfi@gmail.com", "", " BHOTHATHAN COLONY MALAPPURM "},
		{"Kerala", "Thrissur", "V S Sunilkumar", "केरल", "त्रिशूर", "V S Sunilkumar",  "  0487-2631696", " 9447319239", "", " vssunilkumaraiyb@gmail.com", "", " Velichappatth House, Anthikkad PO., Thrissur 680841 "},
		{"Kerala", "Thrithala", "V.T. Balram", "केरल", "त्रितला", "V.T. Balram",  "  9895972376", "", "", " vtbalram@gmail.com", "", " Ratnayalam urallur PO THRITHALA via Palakkad dist "},
		{"Kerala", "Tirur", "Mammutty", "केरल", "तिरूर", "Mammutty",  "  9447262319", "", "", " cmammutty6@gmail.com", "", " Kasant Manzil, Karakkamala P.O. Mananthavady "},
		{"Kerala", "Tirurangadi", "Pandikkdavath Abdu Rabb", "केरल", "तिरुरंगादी", "Pandikkdavath Abdu Rabb",  "  9495355500", "", "", " pkabdurabb1948@gmail.com", "", " grace, beach road po, parappanangadi "},
		{"Kerala", "Trikaripur", "M.Rajagopalan", "केरल", "त्रिकरपुर", "M.Rajagopalan",  "  9446168577", "", "", " mrgkyr 1943@gmail.com", "", " Phynex kayoor cheruvathoor "},
		{"Kerala", "Udma", "K Kunhiraman", "केरल", "उदमा", "K Kunhiraman",  "  9447439196", "", "", " kunhiramanmla@gmail.com", "", " Alakode House PO Pakkam(Via) Bekal Fort Kasaragod Dist "},
		{"Kerala", "Udumbanchola", "M.M. Mani", "केरल", "उदूम्बंचोला", "M.M. Mani",  "  9447512082", "", "", "", "", " Mundakkal, 20 Acre Pottankadu P.O. Pin No. 685565 "},
		{"Kerala", "Vadakara", "C K Nanu", "केरल", "वाटकरा", "C K Nanu",  "  9847002506", "", "", " cknanumla@gmail.com", "", " konothu sujithalyam thayakuniyil near rilwaysation vadakara "},
		{"Kerala", "Vaikom (SC)", "Asha C K", "केरल", "वैकोम (एस सी)", "Asha C K",  "  9947178605", "", "", " ashavaikom@gmail.com", "", " Kiran Nivas, Kudavechoor P.O., Vaikom "},
		{"Kerala", "Vallikkunnu", "Abdul Hameed", "केरल", "वल्लिकुन्नू", "Abdul Hameed",  "  04933-235722", " 9847327102", "", " pabdulhameed47@gmail.com", "", " Puliyakath House, Pattikkad Post, Pin 679325 Malapuram Dist., Kerala "},
		{"Kerala", "Vamanapuram", "Muraleedharan Nair.D.Kk", "केरल", "वमनपुरम", "Muraleedharan Nair.D.K",  "  9447428205", "", "", " dkmuralivjd@gmail.com", "", " Sree Veedu, Nellanadu(Village), Venjaramoodu P O, Nedumangadu(Taluk) "},
		{"Kerala", "Varkala", "Joy V", "केरल", "वर्कला", "Joy V",  "  9447206270", "", "", " Joyperunnguzhi@gmail.com", "", " SAUHRIDAM PERUMGUZHI P.O AZHOOR, CHIRAYINKEEZHU "},
		{"Kerala", "Vattiyoorkavu (SC)", "K Muraleedharan", "केरल", "वट्टियूरकवु (एस सी)", "K Muraleedharan",  "  9895930303", " 9447064056", "", " k.muraleedharanmla@gmail.com", "", " JYOTHIS BHAGAVATHY NAGAR 171/A TVM "},
		{"Kerala", "Vengara7", "Adv. K.N.A Khader", "केरल", "वेंगारा", "Adv. K.N.A. Khader",  "  04832752560", " 9846256060", "", " isknakadar@gmail.com", "", " Resident of Kannanavil House, ottathara, Kodur PO, Malappuram-676504 "},
		{"Kerala", "Vypeen", "S Sarma", "केरल", "वाइपिन", "S Sarma",  "  9846054054", " 2442997", "", " s.sarma.mla@gmail.com", "", " Reshmas, Mannappasseril, Perumpadanna, North Paravur "},
		{"Kerala", "Wadakkanchery", "Anil Akkara", "केरल", "वडक्कान्चेरी", "Anil Akkara",  "  9387103701", "", "", " anilakkara100@gmail.com", "", " Akkarapattekyal veettil, puranattukara village, thrissur taluk "},
		{"Kerala", "Wandoor (SC)", "A.p. Anil Kumar", "केरल", "वंडूर (एस सी)", "A.p. Anil Kumar",  "  9447115677", "", "", " anilk.mlpm@gmail.com", "", " Akkarapurakkal House, Malappuram "},



	};

}