/* Auto-generated file from db2MPjava.php*/

    package in.filternet.jantamalik.Rajya;

    public final class Manipur {

    	public static final String[][] MLAs = {

		{"Manipur", "Andro", "Thounaojam Shamkumar", "मणिपुर", "एंड्रो", "Thounaojam Shamkumar",  "  9862899665", "", "", " shyamkumarthounaojam20@gmail.com", "", " Yairiok Yambem Mathak Leikai, P.O. Yairipok, P.S. Andro, Imphal East District Manipur "},
		{"Manipur", "Bishenpur", "Konthoujam Govindas", "मणिपुर", "बिशेनपुर", "Konthoujam Govindas",  "  9436892005", "", "", " govindaskonthoujam@gmail.com", "", " Ningthoukhong Bazar, Ward No. 2, PO Ningthoukhong, PS and Distt. Bishnupur 795126 "},
		{"Manipur", "Chandel (ST)", "Letpao Haokip", "मणिपुर", "चंदेल (एस टी)", "Letpao Haokip",  "  8118946746", "", "", " haokipletpao780@gmail.com", "", " Aihang Village, P.O and P.S Waikhong, Distt. Chandel Manipur "},
		{"Manipur", "Chingai (ST)", "Khashim Vashum", "मणिपुर", "चिंगाई (एस टी)", "Khashim Vashum",  "  9436032028", "", "", " khashimvashum2017@gmail.com", "", " Tusom Christian Village P.O. Ukhrul, P.S. Jessami, Chingai Sub Division Distt. Ukhrul, Manipur "},
		{"Manipur", "Churachandpur (ST)", "V. Hangkhanlian", "मणिपुर", "चुराचंदपुर (एस टी)", "V. Hangkhanlian",  "  9856211179", "", "", " hangkhanlianv@gmail.com", " ktonsing@gmail.com", " Zenhang Lamka, P.O, P.S District Churachandpur, Manipur 795128 "},
		{"Manipur", "Heingang", "Nongthombam Biren", "मणिपुर", "हेंगंग", "Nongthombam Biren",  "  9612157715", "", "", " biren.nong@yahoo.com", "", " Luwangsagbam Mamang Leikai, post-Mantripukhri, Heingang,Imphal east Manipur. "},
		{"Manipur", "Heirok", "Thokchom Radheshyam Singh", "मणिपुर", "हैरोक़", "Thokchom Radheshyam Singh",  "  9436023204", " 9612260184", "", " radheshyamthokochom@gmail.com", "", " Heirok Part II, Thokchom Leikai, P.O Wangjing 795148, P.S Heirok, Thoubal District Manipur "},
		{"Manipur", "Henglep (ST)", "Thangzalam", "मणिपुर", "हेंगलेप (एस टी)", "Thangzalam",  "  9862112917", "9436025124", "", " tthaokip@ymail.com", "", " S. Kotlian Village, Post office and police station , Churachandpur Distt. Churachandpur, Manipur "},
		{"Manipur", "Hiyanglam", "Yumnam Radheshyam", "मणिपुर", "हियांगलाम", "Yumnam Radheshyam",  "  8730989609", "", "", " dr.yradheshyam@gmail.com", "", " Langmeidong, PO Kakching 795103 and PS waikhong, Distt. Kakching Manipur "},
		{"Manipur", "Jiribam", "Ashab Uddin", "मणिपुर", "जिरिबाम", "Ashab Uddin",  "  8131951021", "", "", "", "", " Sonapur Part I,P.O and P.S Jiribam, Distt. Jiribam, Manipur Pin 795116 "},
		{"Manipur", "Kakching", "Yengkhom Surchandra Singh", "मणिपुर", "काकचिंग", "Yengkhom Surchandra Singh",  "  9436021760", "", "", "", "", " Kakching Turei, Wangma, P.O &P.S Kakching, Kakching Dist Manipur- 795103 "},
		{"Manipur", "Kangpokpi", "Nemcha Kipgen", "मणिपुर", "कांगपोकपी", "Nemcha Kipgen",  "  918732056425", "", "", " nemcha.kipgen@gamil.com", "", " Gunphaijang Village, Po, PS and District Kangpokpi, Manipur "},
		{"Manipur", "Karong (ST)", "D.D. Thaisii", "मणिपुर", "कारॉन्ग (एस टी)", "D.D. Thaisii",  "  9436035497", "", "", "", "", " Purul Atongba Village P.O. Maram, P.s Tadubi, Senapati District, Manipur 795105 "},
		{"Manipur", "Keirao", "Lourembam Rameshwor Meetei", "मणिपुर", "कैराओ", "Lourembam Rameshwor Meetei",  "  9863521126", " 9402881482", "", " lourembamenterprises@gmail.com", "", " Kyamgei Mamang Leikai, P.O. Canchipur, P.S. Irilbung, Imphal East Distt. Manipur. "},
		{"Manipur", "Keisamthong", "Langpoklakpam Jayantakumar", "मणिपुर", "किशाम्थोंग", "Langpoklakpam Jayantakumar",  "  9436027494", "", "", "", "", " Pishumthong Oinam Leikai, P.O. Imphal, P.S singjamei, Imphal West Distt.Manipur "},
		{"Manipur", "Khangabo", "Surjakumar Okram", "मणिपुर", "खांगाबो", "Surjakumar Okram",  "  8974059562", "", "", "", "", " Thoubal Athokpam Makha Leikai Ward No 7, Thoubal Muncipal Council, Thoubal Manipur-795138 "},
		{"Manipur", "Khetrigao", "Nahakpam Indrajit", "मणिपुर", "क्षेत्रिगाओ", "Nahakpam Indrajit",  "  9436027444", "8256966206", "", " nindrajit2016@gmail.com", "", " Thambalkhong Sabal Leikai P.O and P.S Porompat, Distt. Imphal East Manipur 795005 "},
		{"Manipur", "Khurai", "Leishangthem Susindro Meitei", "मणिपुर", "खुरई", "Leishangthem Susindro Meitei",  "  9862559703", "", "", " susindro@gmail.com", "", " Khurai Sajor Laikai, Tinsid Road, P.O. and P.S. Porompat, Imphal East Distt., Mainpur Pin No. 795005 "},
		{"Manipur", "Konthoujam", "Sapam Ranjan", "मणिपुर", "कोंथौजम", "Sapam Ranjan",  "  8414811333", "", "", " rsapam@yahoo.com", "", " Konthoujam Awang Leikai, PO. Langjing, Imphal West District, Mainpur "},
		{"Manipur", "Kumbi", "Sanasam Bira Singh", "मणिपुर", "कुमबी", "Sanasam Bira Singh",  "  8731864526", "", "", "", "", " Wangoo Ahallup Leikai, BPO Wangoo, PO Moirang P.S. Kumbi Bishnupur 795133 "},
		{"Manipur", "Khundrakpam", "Thokchom Lokeshwor Singh", "मणिपुर", "खुन्द्रक्पम", "Thokchom Lokeshwor Singh",  "  9436026665", "", "", " thokchomlokeswarsingh2007@gmail.com", "", " Sagolmang Mamang Leikai, P.O Pangei, P.S Sangolmang "},
		{"Manipur", "Lamlai", "Kshetrimayum Biren Singh", "मणिपुर", "लामलाई", "Kshetrimayum Biren Singh",  "  8974001815", "", "", " birenkshetri@yahoo.co.in", "", " Sabungkhok, B.P.O Yaingangpokpi P.S Lamlai, Imphal East Distt., Manipur "},
		{"Manipur", "Lamsang", "Shorokhaibam Rajen", "मणिपुर", "लम्बसंग", "Shorokhaibam Rajen",  "  9612529099", "", "", "", "", " Salam Maning Leikai, Po. Langjing PS. patsoi, Dist. Imphal West "},
		{"Manipur", "Langthabal", "Karam Shyam", "मणिपुर", "लंग्थाबल", "Karam Shyam",  "  9862242090", "", "", " karamshyam321@gmail.com", "", " Lilong Chajing Mairenkhong Po Lilong 795130 "},
		{"Manipur", "Lilong", "Muhammad Abdul Nasir", "मणिपुर", "लिलौंग", "Muhammad Abdul Nasir",  "  8729826770", "", "", " abdulnasir301177@yahoo.com", "", " Lilong Chaobok Mairenkul, P.O & P.S Lilong Thoubal District Manipur Pin 795130 "},
		{"Manipur", "Mao (ST)", "Losii Dikho", "मणिपुर", "माओ (एस टी)", "Losii Dikho",  "  8414099654", "", "", " dikhomao61@rediffmail.com", "", " Puananmei Village P.O Mao, P.S Mao, District Senapati , Manipur "},
		{"Manipur", "Mayang Imphal", "Kongkham Robindro Singh", "मणिपुर", "मेयांग इम्फाल", "Kongkham Robindro Singh",  "  9856306151", " 03852445616", "", " kongkham_robz@yahoo.com.", "", " Mayang Imphal Thana I.B Road Awang, P.O/P.S. Mayang Imphal, Distt. Imphal west, Pin 795132 Manipur "},
		{"Manipur", "Moirang", "Pukhrem Sharatchandra Singh", "मणिपुर", "मोइरांग", "Pukhrem Sharatchandra Singh",  "  9436234423", "", "", " schandra.pukhrem@gmail.com", "", " Phairembam Leikai, Moirang, P.O and P.S Moirang, Bishnupur Distt. Manipur 795133 "},
		{"Manipur", "Nambol", "Nameirakpam Loken Singh", "मणिपुर", "नाम्बोल", "Nameirakpam Loken Singh",  "  9436894678", "", "", " loken03@gmail.com", "", " Leimapokpam, P.O.&P.S. Nambol, Dist Bishnupur, Pin-795134, Manipur "},
		{"Manipur", "Naoriya Pakhanglakpa", "Soibam Subhachandra", "मणिपुर", "नोरिया पाखंगलक्पा", "Soibam Subhachandra",  "  9089714685", "", "", " soibamsubhaschandra09@gmail.com", "", " Ningombam Mayai Leikai, P.O. Canchipur, P.S. Singjamei, Imphal West Distt., Manipur, Pin No. 795003, India "},
		{"Manipur", "Nungba (ST)", "Gaikhangam", "मणिपुर", "नुंग्बा (एस टी)", "Gaikhangam",  "  9436021714", "", "", " gaikhangam@yahoo.com", "", " Gaidimjang Village, B.P.O P.S Khoupum P.O. Nungba Pin No. 795147 Noney (Longmai) District Manipur "},
		{"Manipur", "Oinam", "Laishram Radhakishore Singh", "मणिपुर", "ओइनाम", "Laishram Radhakishore Singh",  "  8014167089", "", "", " radhakishorerk26@gamail.com", "", " Keinou Thongkha Makha Leikai, P.O Nambol, P.S Bishnupur, Bishnupur Distt. Manipur "},
		{"Manipur", "Patsoi", "Akoijam Mirabai Devi", "मणिपुर", "पातसोई", "Akoijam Mirabai Devi",  "  8414976557", "0385-2436386", "", " akoijammirabai@gmail.com", "", " Taobungkhok awang leikai, N.C. Road, P.O Langjing and P.S. Patsoi, Imphal West District 795113 Manipur "},
		{"Manipur", "Phungyar (ST) ", "K. Leishiyo", "मणिपुर", "फुंग्यार (एस टी) ", "K. Leishiyo",  "  9436801765", "", "", " lkeishing37@gmail.com", "", " Nambashi Horton Village, P.O Yairipok and p.S kasom Khullen, Ukhrul Distt. Manipur "},
		{"Manipur", "Sagolband", "Rajkumar Imo Singh", "मणिपुर", "सगोलबंद", "Rajkumar Imo Singh",  "  9436027245", "", "", " imosingh@yahoo.com", "", " Sagolband Bijoy Govinda, P.O. and P.S Imphal, Imphal west Disttrict. Manipur 795001 "},
		{"Manipur", "Saikot (ST)", "T. N. Haokip", "मणिपुर", "साइकोट (एस टी)", "T. N. Haokip",  "  9436021706", "", "", " tnhaokip123@gmail.com", "", " B. Vengnom, Churachandpur Po., PS & District Churachandpur, Manipur, Pin No. 795128 "},
		{"Manipur", "Saikul (ST)", "Yamthong Haokip", "मणिपुर", "सैकुल (एस टी)", "Yamthong Haokip",  "  943603564; 0385-2450779", "", "", "", "", " Ekou Mulam, Village, post- Saikul, dist-Kangpokpi, Manipur "},
		{"Manipur", "Saitu (ST)", "Ngamthang Haokip", "मणिपुर", "सैतु (एस टी)", "Ngamthang Haokip",  "  8415903108", "", "", "", "", " Gamnom Saparmcina, P.O Motbung, P.S. G. Saparmeina Sadar Hills, Distt. Senapati, Manipur "},
		{"Manipur", "Sekmai (SC)", "Heikham Dingo Singh", "मणिपुर", "सेकमाई (एस सी)", "Heikham Dingo Singh",  "  7005293429 ", " 8131073144", "", "", "", " Khurakhul Makha Leikai,Near P.H.C, P.O.Mantripukhri, P.S.Sekmai, Imphal West District manipur "},
		{"Manipur", "Singhat (ST)", "Ginsuanhau", "मणिपुर", "सिंघट (एस टी)", "Ginsuanhau", "  9862268893", "", "", "", "", " Buangmun Village, P.O, P.S Singhat, District Churachandpur, Manipur "},
		{"Manipur", "Singjamei", "Yumnam Khemchand", "मणिपुर", "सिंगजमेई", "Yumnam Khemchand", "", "", "", "", "", " Singjamei Chingamathak, Yumnam Leikai, Lairembi Maning, Imphal west Distt. P.o and P.S. Imphal "},
		{"Manipur", "Sugnoo", "Kangujam Ranjit Singh", "मणिपुर", "सुग्नू", "Kangujam Ranjit Singh",  "  7628054615", "", "", "", "", " Serou Bazar, PO and PS Sugnu, Sub Division Walkhong, District Kakching, Manipur India Pin Code 795101 "},
		{"Manipur", "Tadubi (ST)", "N. Kayisii", "मणिपुर", "ताडुबी (एस टी)", "N. Kayisii",  "  9436031829", "", "", "", "", " Makhan Khaman Village , P.O Maram,P.O Mao, Sub Division Mao Maram, Senapti, Distrcit, Manipur795007 "},
		{"Manipur", "Tamei (ST)", "Awangbow Newmai", "मणिपुर", "तामै (एस टी)", "Awangbow Newmai",  "  9436033706", "", "", " awangewmai7@gmail.com", "", " Tamei Headquarter, (A) P.S.P.O Temai, Sub Division Temai, District Tamenglong, State Manipur 795125 "},
		{"Manipur", "Tamenglong (ST)", "Samuel Jendai Kamei", "मणिपुर", "तामेंगलांग (एस टी)", "Samuel Jendai Kamei",  "  8132081333", "", "", "", "", " Khumji (Lukhambi), Tamenglong sub-division ,Tamenglong District, Manipur "},
		{"Manipur", "Tengnoupal (ST)", "D. Korunthang", "मणिपुर", "टेंग्नौपाल (एस टी)", "D. Korunthang",  "  8414017367", "", "", "", "", " Langol Village, Machi Sub-division, PO. Pallel, Tengnoupal District Manipur "},
		{"Manipur", "Thanga", "Tongbram Robindro Singh", "मणिपुर", "थांगा", "Tongbram Robindro Singh",  "  9774505781", "", "", "", "", " Keirenphabi Mamang Leikai, P.O. Moirang, P.S. Keibul Lamjao, Bishnupur Distt. Manipur "},
		{"Manipur", "Thangmeiband", "Khumukcham Joykisan Singh", "मणिपुर", "थंगमेबंद", "Khumukcham Joykisan Singh",  "  8014485993", "", "", " joy_kisan@yahoo.com", "", " Thangmeiband Khoyathong Polem leikai, Imphal 795004 "},
		{"Manipur", "Thanlon (ST)", "Vungzagin Valte", "मणिपुर", "थान्लोन (एस टी)", "Vungzagin Valte",  "  9862434311", "", "", "", "", " Bungmual Village, PO New Lamkam, P.S & Dist Churachandpur, Manipur C/O Nlangzen Khualbuuk, New Lamka, Churachandpur, Manipur "},
		{"Manipur", "Thongju", "Thongam Biswajit Singh", "मणिपुर", "थोंगजू", "Thongam Biswajit Singh",  "  9436892786", "", "", " biswathongam@gmail.com", "", " Thongju Ningomthong, Imphal East, P.O Singjamei 795008 "},
		{"Manipur", "Thoubal", "Okram Ibobi Singh", "मणिपुर", "थौबल", "Okram Ibobi Singh",  "  9436021222", "", "", "", "", " Thoubal Athokapam Makhal Leikai, Ward No. 7 of Thoubal Municipal council, P.O and P.S Thoubal, Thoubal Distt. Manipur 795138 "},
		{"Manipur", "Tipaimukh (ST)", "Chaltonlien Amo", "मणिपुर", "तिपाईमुख (एस टी)", "Chaltonlien Amo",  "  9436021862", " 9612900874", "", "", "", " Patpuihmun Village, BPO. Patpuihnum, PO. Churachandpur, Tipaimukh Sub-Division, Pherzawl/Churachandpur District, Manipur "},
		{"Manipur", "Ukhrul", "Alfred Kanngam S. Arthur", "मणिपुर", "उखरुल", "Alfred Kanngam S. Arthur",  "  9436020309", "", "", " akanngamz@yahoo.com", "", " Shangshak Kn. P.S. Shangshak, P.O.Litan, Ukhrul District, Pin 795142, Manipur "},
		{"Manipur", "Uripok", "Yumnam Joykumar", "मणिपुर", "उरीपोक", "Yumnam Joykumar",  "9436021897", "09810857076", "", " ipsjoykumar@gmail.com", "", " Uripok Naoremthing, post-Imphal, dist-Imphal west, Manipur, 795001 "},
		{"Manipur", "Wabgai", "Chesham Fazoor Rahim", "मणिपुर", "वाबगई", "Chesham Fazoor Rahim",  "  8118936153", "", "", "", "", " Irong Chesaba Mathak Leikai, P.O and P.S Mayang Imphal, Thoubal Distt. Manipur "},
		{"Manipur", "Wangjing Tentha", "Paonam Brojen Singh", "मणिपुर", "वांगजिंग टेंथा", "Paonam Brojen Singh",  "  8014066858", "", "", " paonambrojan@icloud.com", "", " Wangjing Bazar, P.O Wangjing P.S Thoubal Pin Code 795148., District Thoubal Manipur "},
		{"Manipur", "Wangkhei", "Okram Henry", "मणिपुर", "वांग्केई", "Okram Henry",  "  9825890000", "", "", "", "", " Mantripukhri, P.O Mantripukhri, P.S Heingang, Imphal 795002 "},
		{"Manipur", "Wangkhem", "Keisam Meghachandra Singh", "मणिपुर", "वांगखेम", "Keisam Meghachandra Singh",  "  9862588231", "", " 9436023029", " meghachandrakeishammia@gmail.com", "", " Yairipok Bishnunha, P.O & P.S Yairipok Pin 795149 "},
		{"Manipur", "Wangoi", "Oinam Lukhoi Singh", "मणिपुर", "वंगोई", "Oinam Lukhoi Singh",  "  9612959543", "", "", " oinamlukhoisingh@gmail.com", "", " Yumnam Huidrom, Thiyam Leishangkhong, post-Wangoi, Imphal West, Manipur "},
		{"Manipur", "Yaiskul", "Thokchom Satyabrata Singh", "मणिपुर", "येसकुल", "Thokchom Satyabrata Singh",  "  8974057781", "", "", " sattya.sanithakur@gmail.com", "", " Singjamei Wangma Bhagyabati Leikai, I.E. PO. P.s. Porompat & Dist "},

	};

}