/* Auto-generated file from db2MPjava.php*/

    package in.filternet.jantamalik.Rajya;

    public final class Meghalaya {

    	public static final String[][] MLAs = {

		{"Meghalaya", "Amlarem", "Lahkmen Rymbui", "मेघालय", "अमलारेम", "Lahkmen Rymbui",  "  9436106092", "", "", " lahrymbui@gmail.com", "", " Khlachympa, Nongtalang, West Jaintia Hills Dist. Meghalaya "},
		{"Meghalaya", "Ampathi", "Miani D Shira", "मेघालय", "अम्पति", "Miani D Shira",  "  8415918990", "", "", " miani.shira@gmail.com", "", " R/O Chengkompara, Ampati, PO. & PS. Ampati, District South West Garo Hills, Meghalaya "},
		{"Meghalaya", "Baghmara", "Samuel M. Sangma", "मेघालय", "बाघमारा", "Samuel M. Sangma",  "  09436300055", "", "", " smlsangma@gmail.com", "", " R/O Gasaupara, Post Office & Police Station Gasaupara, South Garo Hills District, Meghalaya "},
		{"Meghalaya", "Bajengdoba", "Pongseng Marak", "मेघालय", "बजेंगदोबा", "Pongseng Marak",  "  7005419247", "", "", "", "", " R/o Line Ading, P.O. & P.S. Bajengdoba, Dist. North Garo Hills Meghalaya, Permanent R/o of Bakenang Nalsa, Dist. North Garo Hills Meghalaya Pin 794003 "},
		{"Meghalaya", "Chokpot", "Lazarus M. Sangma", "मेघालय", "चोकपोट", "Lazarus M. Sangma",  "  9485183241", " 7005658341", "", " lazarussangma@gmail.com", "", " Village Mindikgre, PO. Mindikgre, PS. Baghmara, District South Garo Hills, Meghalaya pin 794102 "},
		{"Meghalaya", "Dadenggre", "James Pangsang Kongkal Sangma", "मेघालय", "ददेनगग्रे", "James Pangsang Kongkal Sangma",  "  9862050810", " 9089960908", "", " jamessangma@yahoo.com ", " jamesksangma@gmail.com", " House No 78, Dadenggre, PO Dadenggre, West Garo Hills, Meghalaya, PIN No 794003 "},
		{"Meghalaya", "Dalu", "Brening A. Sangma", "मेघालय", "डालू", "Brening A. Sangma",  "  9436111915", "", "", "", "", " R/o Matchakolgre P.O. Araimile P.S. Tura West Garo Hills, Meghalaya Pin No. 794101 "},
		{"Meghalaya", "East Shillong", "Mazel Ampareen Lyngdoh", "मेघालय", "पूर्व शिलांग", "Mazel Ampareen Lyngdoh",  "  09436100281", "", "", " ampareen05@gmail.com", "", " R/O Dei-ngi, Nongrim Road, Laitumkhrah, Shillong 793003 "},
		{"Meghalaya", "Gambegre", "Saleng A. Sangma", "मेघालय", "गाम्बेग्रे", "Saleng A. Sangma",  "  9862572723", " 7085529631", "", "", "", " Burny Hills, Tura PO Dakopgre, PS Tura, Dist West Garo Hills Meghalaya "},
		{"Meghalaya", "Jirang", "Sosthenes Sohtun", "मेघालय", "जिरंग", "Sosthenes Sohtun",  "  9436108872", " 8794748872", "", " sohtunsosthenes@gmail.com", "", " Resident of Lum Nongthymmai Byrnihat, P.O.-Byrnihat, Ri-Bhoi, Dist., Meghalaya "},
		{"Meghalaya", "Jowai", "Wailadmiki Shylla", "मेघालय", "जोवै", "Wailadmiki Shylla",  "  8787616751", "", "", " wailadmiki@yahoo.in", "", " Mukhla Nongrim Village, West Jaintia Hills Dist. Meghalaya "},
		{"Meghalaya", "Kharkutta", "Rupert Momin", "मेघालय", "खरकुट्टा", "Rupert Momin",  "  8014325806", "", "", " rupertmomin@yahoo.co.in", "", " Resident of Vill. Lower,Kharkutta, P.O. & P.S.-Kharkutta, Dist.North Garo Hills, Meghalaya, Pin-783130 "},
		{"Meghalaya", "Khliehriat", "Kyrmen Shylla", "मेघालय", "खलिएहरिएट", "Kyrmen Shylla",  "  08731906790", " 07005374669", " 09383143931", " kyrmenshylla78@gmail.com", "", " Byndihati Village, PO Khliehriat, PS Khliehrtiat, East Jaintia Hills District, Meghalaya 793200 "},
		{"Meghalaya", "Mahendraganj", "Dikkanchi D. Shira", "मेघालय", "महेंद्रगंज", "Dikkanchi D. Shira",  "  9436113025", " 8415905865", "", " dikkanchi@gmail.com", "", " R/o Chengkompara. P.O. Ampati, South West Garo Hills Meghalaya 794115 "},
		{"Meghalaya", "Mairang", "Metbah Lyngdoh", "मेघालय", "मैरंग", "Metbah Lyngdoh",  "  9862005060", "", "", " metbah@gmail.com", "", " Resident of Vill. & B.P.O. Manai, P.S.-Mairang, West Khasi Hills, Meghalaya, Pin-793120 "},
		{"Meghalaya", "Mawhati", "Dasakhiatbha Lamare", "मेघालय", "मौहाटी", "Dasakhiatbha Lamare",  "  8415900072", "", "", " dome.lamare@gmail.com", "", " House No. 223, Mawlasnai, Ri Bhoi District, Meghalaya "},
		{"Meghalaya", "Mawkynrew", "Banteidor Lyngdoh", "मेघालय", "मवकीनरेव", "Banteidor Lyngdoh",  "  8415903344", "", "", " banteidorly@gmail.com", "", " Permanent Resident of House No.80, Thangsning Vill.East Khasi Hills Dist., Meghalaya-793015, Presently Residing at House No.28, Jaiaw Langsning, Shillong-793002, East Khasi Hills DIst., Meghalaya "},
		{"Meghalaya", "Mawkyrwat", "Renikton Lyngdoh Tongkhar", "मेघालय", "मौकैवत", "Renikton Lyngdoh Tongkhar",  "  9436105890", " 8837474900", "", " reniklyngdoh@gmail.com", "", " Resident of Mawkyrwat, P.O.-Mawkyrwat, South West Khasi Hills District, Meghalaya, Pin-793114 "},
		{"Meghalaya", "Mawlai", "Process T. Sawkmie", "मेघालय", "मवलै", "Process T. Sawkmie",  "  9856517902", "", "", "", "", " Resident-Mawlai,Nongpdeng Block A Shillong 793008 East Khasi Hills "},
		{"Meghalaya", "Mawphlang", "Syntar Klas Sunn", "मेघालय", "मावफ्लांग", "Syntar Klas Sunn",  "  9436104286", "", "", "", "", " Mawngap Dukan, East Khasi Hills District Meghalaya "},
		{"Meghalaya", "Mawryngkneng", "David A Nongrum", "मेघालय", "मौर्यनगकनंग", "David A Nongrum",  "  9436104830", "", "", " atu_jr@yahoo.com", "", " R/O Lummawrie West, Laitumkhrah, Shillong-793003, District East Khasi Hills, Meghalaya "},
		{"Meghalaya", "Mawshynrut", "Gigur Myrthong", "मेघालय", "मौशीनरूट", "Gigur Myrthong",  "  9856050175", "", "", "", "", " Resident of Vill.Shahlang Sohbar, Post Office Riangdo and Police Station Shahlang, West Khasi Hills District, Meghalaya "},
		{"Meghalaya", "Mawsynram", "Himalaya Muktan Shangpliang", "मेघालय", "मौसिनराम", "Himalaya Muktan Shangpliang",  "  9863021317", " 9436101317", "", " hmshang_44@yahoo.co.in", "", " Mawsynram Dongncng Mawsynram East Khasi Hills ,Meghalaya "},
		{"Meghalaya", "Mawthadraishan", "Brolding Nongsiej", "मेघालय", "माथाद्रिशाम", "Brolding Nongsiej",  "  8131996644", "", "", " brolding18@gmail.com", "", " R/o Kynshi Village, P.O. Mairang, West Khasi Hills, Dist. Meghalaya 793120 "},
		{"Meghalaya", "Mendipathar", "Marthon Sangma", "मेघालय", "मेंदीपाथर", "Marthon Sangma",  "  08415922060", "", "", " maltonsangma@gmail.com", "", " Village Dilma Rejak Gittim, Post Office Mendipathar, North Garo Hills District, Meghalaya "},
		{"Meghalaya", "Mowkaiaw", "Nujorki Sungoh", "मेघालय", "मोकायव", "Nujorki Sungoh",  "  9612174120", "", "", "", "", " R/o Mukhap Village, West Jaintia Hills Meghalaya "},
		{"Meghalaya", "Mylliem", "Hamletson Dohling", "मेघालय", "मिलिएम", "Hamletson Dohling",  "  9436205225", "", "", " hamlet.dohling@yahoo.co.in", "", " Resident of Lummawbah, Block-IV, Shillong-793005, East Khasi Hills Dist.Meghalaya "},
		{"Meghalaya", "Nartiang", "Sniawbhalang Dhar", "मेघालय", "नारतीयंग", "Sniawbhalang Dhar",  "  9856040141", " 9612161224", "", "", "", " Resident-Of Wahlajer Village West Jaintia Hills District Meghalya "},
		{"Meghalaya", "Nongkrem", "Lambor Malngiang", "मेघालय", "नोंगक्रेम", "Lambor Malngiang",  "  84141086961", "", "", "", "", " Laitkor Nongdaneng, East Khasi Hills District, Meghalaya "},
		{"Meghalaya", "Nongpoh", "Mayralborn Syiem", "मेघालय", "नोंगपोह", "Mayralborn Syiem",  "  9862177177", "", "", " myralborn@gmail.com", "", " R/o Diwon Village P.O. & P.S. Nongpoh Ri Bhoi Mehgalaya "},
		{"Meghalaya", "Nongstoin", "Macmillan Byrsat", "मेघालय", "नांगस्टॉइन", "Macmillan Byrsat",  "  9436108164", " 9856008164", " 7005651384", " mcbyrsat@gmail.com", "", " Pyndengrei Village Nongstoin-793119, West Khasi Hills District Meghalaya "},
		{"Meghalaya", "Nongthymmai", "Charles Pyngrope", "मेघालय", "नोंग्थिम्मै", "Charles Pyngrope",  "  9612400009", "", "", " pyngrope.charles@gmail.com", "", " R/o Hosanna, Pohkseh Shillong 793006, East Khasi Hills District Meghalaya "},
		{"Meghalaya", "North Shillong", "Adelbert Nongrum", "मेघालय", "उत्तर शिलांग", "Adelbert Nongrum",  "  9436703519", "", "", " adelbert25.nongrum@gmail.com", "", " R/o Jaiaw Lower Lansonalance Shillong East Khasi Hills Dist. Meghalaya "},
		{"Meghalaya", "North Tura", "Thomas A. Sangma", "मेघालय", "उत्तर तुरा", "Thomas A. Sangma",  "  9868181031", " 9971896188", "", " tasangma@yahoo.com", "", " Resident of Spring Hills, P.O.-Chandmary, P.S.-Tura, West Garo Hills, Meghalaya, Pin-794002 "},
		{"Meghalaya", "Phulbari", "S G Esmatur Mominin", "मेघालय", "फुलबारी", "S G Esmatur Mominin",  "  7005679799", " 9862288388", "", " sgemominin951@gmail.com", "", " Vill. Bholarbita, PO. Bholarbita, PS. Phulbari, West Garo Hills, Meghalaya "},
		{"Meghalaya", "Pynthorumkhrah", "Alexander Laloo Hek", "मेघालय", "प्यनथोरुम्कहराह", "Alexander Laloo Hek",  "  9436103383", " 9774003383", "", " mebaai@yahoo.co.in", "", " Resident of 98-Mawpun West (Golflinks), Shillong-793001, East Khasi Hills Dist., Meghalaya "},
		{"Meghalaya", "Pynursla", "Prestone Tynnsong", "मेघालय", "पिनूरसला", "Prestone Tynnsong",  "  9862570164", "", "", " ptysong251@gmail.com", "", " R/o Rngain Vill. P.O. Pynrsla East Khasi Hills District Meghalaya "},
		{"Meghalaya", "Rajabala", "Azad Zaman", "मेघालय", "राजाबाला", "Azad Zaman", "  9856026435", " 9612484942", "", " drazadzaman@gmail.com", "", " Bowabari, PO New Bhaitbari, PS Phulbari, District West Garo Hillas Meghalaya "},
		{"Meghalaya", "Raksamgre", "Benedic R. Marak", "मेघालय", "रकसंगरे", "Benedic R. Marak", "", "", "", " 8014496270", " 8794376456", " Resident of Roni A Sim, P.O.-Bollongitok, P.S.-Tikrikilla, West Garo Hills, Meghalaya-794109 "},
		{"Meghalaya", "Raliang", "Comingone Ymbon", "मेघालय", "रलिअंग", "Comingone Ymbon",  "  9612171335", "", "", "", "", " Resident-33 Shangpung Pohshong 'A' Shangpung Dolloiship),Shangpung West Jaintia Hills Meghalya "},
		{"Meghalaya", "Rambrai Jyrngam", "Kimfa Sidney Marbaniang", "मेघालय", "रामबरै जयरंगम", "Kimfa Sidney Marbaniang",  "  9774001688", " 8575744209", "", " kimfasidneymarbaniang@gmail.com", "", " R/O Rambrai, Rambrai Syiemship, West Khasi Hills District, Meghalaya "},
		{"Meghalaya", "Rangsakona", "Zenith M Sangma", "मेघालय", "रंगसाकोना", "Zenith M Sangma",  "  9862155527", " 09436703696", "", " zenithsangma@gmail.com", "", " R/O Sonamite, PO. Garobadha, PS. Ampati, South West Garo Hills, Meghalaya "},
		{"Meghalaya", "Ranikor", "Pius Marwein", "मेघालय", "रानीकोर", "Pius Marwein",  "  8787533645", "", "", " marweinpius25@gmail.com", "", " R/o Nonghyllam Village, P.O. Balat, South West Khasi Hills District, Meghalaya - 793106 "},
		{"Meghalaya", "Resubelpara", "Timothy Shira", "मेघालय", "रेसुबेलपारा", "Timothy Shira",  "  9615170106", "", "", "", "", " Vill. Tekachang, PO. Resubelpara & PS. Resubelpara, District North Garo "},
		{"Meghalaya", "Rongara-Siju", "Rakkam A. Sangma", "मेघालय", "रोंगरा-सीजू", "Rakkam A. Sangma",  "  9436567355", "", "", " rakkamsangma@gmail.com", "", " R/O Tainangiri, Po. Balkal, Ps. Baghmara South Garo Hills Meghalaya pin 794102 "},
		{"Meghalaya", "Rongjeng", "Jim M Sangma", "मेघालय", "रोंगजेन्ग", "Jim M Sangma",  "  8837415433", " 9615930086", "", " jimsangma38@gmail.com", "", " Village Upper Rongjeng, Po. & Ps. Rongjeng, East Garo Hills, Meghalaya "},
		{"Meghalaya", "Salmanpara", "Winnerson D. Sangma", "मेघालय", "सलमानपारा", "Winnerson D. Sangma",  "  8575900706", " 8974077418", "", " winnerdsangma@gmail.com", "", " R/o Anangpara P.O. & P.S. Ampati South West Garo Hills Meghalaya 794115 "},
		{"Meghalaya", "Selsella", "Ferlin C. A. Sangma", "मेघालय", "सेलसेला", "Ferlin C. A. Sangma",  "  9077197944", "", "", " f.c.a.sangama@gmail.com ", "", " Gandopara Balalgre P.O Garobadha P.S Tura West Garo Hills Meghalaya 794105 "},
		{"Meghalaya", "Shella", "Balajied Kupar Synrem", "मेघालय", "शेल्ला", "Balajied Kupar Synrem",  "  9774331143", "", "", " jieds70@gmail.com", "", " R/o Jamew, Shella Village, East Khasi Hills Pin No. 793108 "},
		{"Meghalaya", "Sohing", "Samlin Malngiang", "मेघालय", "Sohiong", "Samlin Malngiang",  "  8787449170", "", "", "", "", " Resident of Umsaw, East Khasi Hills Dist., Meghalaya "},
		{"Meghalaya", "Sohra", "Gavin Miguel Mylliem", "मेघालय", "सोहरा", "Gavin Miguel Mylliem",  "  9436318888", "", "", " gavin18888@gmail.com", "", " Resident-House No.129,Umthli Village Sohra East Khasi Hills District.Meghalya "},
		{"Meghalaya", "Songsak", "Dr. Mukul Sangma", "मेघालय", "सोंगसाक", "Dr. Mukul Sangma",  "  9862566276", "9856080845", "", " drmukul3333@gmail.com", "", " Chengkompara, P.O. Ampati, South West Garo Hills, Meghalaya 794115 "},
		{"Meghalaya", "South Shillong", "Sanbor Shullai", "मेघालय", "दक्षिण शिलांग", "Sanbor Shullai",  "  9436104339", "", "", " sanborshullai1966@gmail.com", "", " Kench's Trace, PO & PS Laban, Shillong- 793004, District East Khasi Hills, Meghalaya "},
		{"Meghalaya", "South Tura", "Conrad Kongkal Sangma", "मेघालय", "दक्षिण तुरा", "Conrad Kongkal Sangma",  "  9856001009", "", "", " conradsangma@gmail.com", "", " Village Gandopara Balalgre, PO Selsella, West Garo Hills, Meghalaya "},
		{"Meghalaya", "Sutnga-Saipung", "Shitlang Pale", "मेघालय", "सुतंगा-सैपुन्ग", "Shitlang Pale",  "  7085544202", " 9856222702", "", " shitlang1@gmail.com", "", " House No 154, Jalaphet Sumer, East Jaintia Hills District "},
		{"Meghalaya", "Tikrikila", "Jimmy D. Sangma", "मेघालय", "टीकृकिला", "Jimmy D. Sangma",  "  9856050175", "", "", "", "", " R/o Village 24-Khamri, Post office Hollaidanga and Police Station Tikrikila West Garo hills Dist. Meghalaya "},
		{"Meghalaya", "Umroi", "George Bankyntiewlang Lyngdoh", "मेघालय", "उमरोई", "George Bankyntiewlang Lyngdoh",  "  9612170942", "", "", " georgeumroi2018@gmail.com", "", " Umroi Umdohbyrthim. P.O. & P.S. Umain, Ri Bhoi Dist. Meghalaya "},
		{"Meghalaya", "Umsning", "Jason Sawkmie Mawlong", "मेघालय", "उमसिंनिंग", "Jason Sawkmie Mawlong",  "  9774009321", "", "", " hunsun21@gmail.com", "", " Resident of Mawlein, Mawkhan, Umsning, District Ri-Bhoi, Pin-793013, Meghalaya "},
		{"Meghalaya", "West Shillong", "Mohendro Rapsang", "मेघालय", "पश्चिम शिलांग", "Mohendro Rapsang",  "  9436105368", "", "", " rapsang.mahendro@gmail.com", "", " Jaiaw Langsning, Shillong-793002, East Khasi Hills District Meghalaya "},
		{"Meghalaya", "William Nagar", "Marcuise N Marak", "मेघालय", "विलियम नगर", "Marcuise N Marak",  "  9612155597", " 7628834663", "", " marakmarcuise@gmail.com", "", " Village Balsrigittim, PO. & PS. Williamnagar, East Garo Hills, Meghalaya "},

	};

}