package in.filternet.jantamalik.Rajya;

public final class MP_2_MLA_part2 {

    // splitting in 2 parts to avoid build error - code too large
    public static final String[][] mapping = {

            {"Tamil Nadu", "Arakkonam", "Tiruttani", "Arakkonam", "Sholingur", "Katpadi", "Ranipet", "Arcot"},
            {"तमिल नाडु", "अराकोणम", "तिरुत्तनी", "अराकोणम", "शोलिंगुर", "कटपदी", "रानीपेट", "अर्काट"},
            {"Tamil Nadu", "Arani", "Polur", "Arani", "Cheyyar", "Vandavasi", "Gingee", "Mailam"},
            {"तमिल नाडु", "अरणि", "पोलुर", "अरणि", "चेय्यार", "वंदावसी", "जिंगी", "मैलम"},
            {"Tamil Nadu", "Chennai Central", "Villivakkam", "Egmore", "Harbour", "Chepauk-Thiruvallikeni", "Thousand Lights", "Anna Nagar"},
            {"तमिल नाडु", "चेन्नई सेंट्रल", "विलिवक्कम", "एग्मोर", "हार्बर", "चेपक-थिरुवल्लिकेनि", "थाउज़ेंड लाइट्स", "अन्ना नगर"},
            {"Tamil Nadu", "Chennai North", "Tiruvottiyur", "Dr.Radhakrishnan Nagar", "Perambur", "Kolathur", "Thiru-Vi-Ka-Nagar", "Royapuram"},
            {"तमिल नाडु", "चेन्नई उत्तर", "तिरुवोट्टियुर", "डॉ राधाकृष्णन नगर", "पेरम्बूर", "कोलाथुर", "थिरु-वि-का-नगर", "रॉयपुरम"},
            {"Tamil Nadu", "Chennai South", "Virugambakkam", "Saidapet", "Thiyagarayanagar", "Mylapore", "Velachery", "Sholinganallur"},
            {"तमिल नाडु", "चेन्नई दक्षिण", "विरुगम्बक्कम", "सैदापेट", "थियागरायनगर", "मायलापुर", "वेलाचेरी", "शोलिंगनल्लूर"},
            {"Tamil Nadu", "Chidambaram", "Kunnam", "Ariyalur", "Jayankondam", "Bhuvanagiri", "Chidambaram", "Kattumannarkoil"},
            {"तमिल नाडु", "चिदंबरम", "कुन्नम", "अरियालुर", "जयमकोण्डम", "भुवनगिरि", "चिदंबरम", "कट्टुमन्नारकोइल"},
            {"Tamil Nadu", "Coimbatore", "Palladam", "Sulur", "Kavundampalayam", "Coimbatore (North)", "Coimbatore (South)", "Singanallur"},
            {"तमिल नाडु", "कोयंबटूर", "पल्लादम", "सुलूर", "कौन्दम्पलयम", "कोयंबटूर (उत्तर)", "कोयंबटूर (दक्षिण)", "Singanallur"},
            {"Tamil Nadu", "Cuddalore", "Tittakudi", "Vriddhachalam", "Neyveli", "Panruti", "Cuddalore", "Kurinjipadi"},
            {"तमिल नाडु", "कुड्डालोर", "तित्ताकुडी", "विरुधाचलम", "नयवेली", "पनरुति", "कुड्डालोर", "कुरिन्जिपदी"},
            {"Tamil Nadu", "Dharmapuri", "Palacodu", "Pennagaram", "Dharmapuri", "Pappireddippatti", "Harur", "Mettur"},
            {"तमिल नाडु", "धर्मपुरी", "पलाकोडु", "पेन्नगराम", "धर्मपुरी", "पप्पीरेड्डीप्पट्टी", "हरूर", "मेटूर"},
            {"Tamil Nadu", "Dindigul", "Palani", "Oddanchatram", "Attur", "Nilakkottai", "Natham", "Dindigul"},
            {"तमिल नाडु", "डिंडीगुल", "पलानी", "ओद्दचतरम", "अथूर", "नीलकोट्टई", "नाथम", "डिंडीगुल"},
            {"Tamil Nadu", "Erode", "Kumarapalayam", "Erode (East)", "Erode (West)", "Modakkurichi", "Dharapuram", "Kangayam"},
            {"तमिल नाडु", "इरोड", "कुमारपलयम", "इरोड (ईस्ट)", "इरोड (वेस्ट)", "मोदकुरिची", "धरापुरम", "कंगयम"},
            {"Tamil Nadu", "Kallakurichi", "Rishivandiyam", "Sankarapuram", "Kallakurichi", "Gangavalli", "Attur", "Yercaud"},
            {"तमिल नाडु", "कल्लाकुरिची", "ऋषिवंदियम्", "शंकरपुरम", "कल्लाकुरिची", "गंगावली", "अथूर", "यैरकॉड"},
            {"Tamil Nadu", "Kancheepuram", "Chengalpattu", "Thiruporur", "Cheyyur", "Madurantakam", "Uthiramerur", "Kancheepuram"},
            {"तमिल नाडु", "कांचीपुरम", "चेंगलपट्टू", "तिरूपोरूर", "छेय्युर", "मदुरान्तकम", "उतिरामेरुर ", "कांचीपुरम"},
            {"Tamil Nadu", "Kanniyakumari", "Kanniyakumari", "Nagercoil", "Colachel", "Padmanabhapuram", "Vilavancode", "Killiyoor"},
            {"तमिल नाडु", "कन्याकूमारी", "कन्याकूमारी", "नागरकोइल", "कोलाचल", "पद्मनाभपुरम", "विलावनकोड", "किलयुर"},
            {"Tamil Nadu", "Karur", "Vedasandur", "Aravakurichi", "Karur", "Krishnarayapuram", "Manapparai", "Viralimalai"},
            {"तमिल नाडु", "करूर", "वेदसन्दूर", "अरावकुरिची", "करूर", "कृष्णरायपुरम", "मनाप्परई", "विरालिमलई"},
            {"Tamil Nadu", "Krishnagiri", "Uthangarai", "Bargur", "Krishnagiri", "Veppanahalli", "Hosur", "Thalli"},
            {"तमिल नाडु", "कृष्णागिरी", "उथंगराई", "बरगुर", "कृष्णागिरी", "वेप्पन्नपल्ली", "होसुर", "थल्ली"},
            {"Tamil Nadu", "Madurai", "Melur", "Madurai East", "Madurai North", "Madurai South", "Madurai Central", "Madurai West"},
            {"तमिल नाडु", "मदुरै", "मेलुर", "मदुराई पूर्व", "मदुरै उत्तर", "मदुराई दक्षिण", "मदुराई मध्य", "मदुरै पश्चिम"},
            {"Tamil Nadu", "Mayiladuthurai", "Sirkazhi", "Mayiladuthurai", "Poompuhar", "Thiruvidaimarudur", "Kumbakonam", "Papanasam"},
            {"तमिल नाडु", "माइलादुत्रयी", "सिरकाज़ी", "माइलादुत्रयी", "पूम्पुहार", "तिरुविदमरदुर", "कुम्भकोणम", "Papanasam"},
            {"Tamil Nadu", "Nagapattinam", "Nagapattinam", "Kilvelur", "Vedaranyam", "Thiruthuraipoondi", "Thiruvarur", "Nannilam"},
            {"तमिल नाडु", "नागपट्टिनम", "नागपट्टिनम", "किलवेलूर", "वेदारण्यम", "तिरुतुरईपुंडी", "तिरुवरूर", "नन्नीलम"},
            {"Tamil Nadu", "Namakkal", "Sankari", "Rasipuram", "Senthamangalam", "Namakkal", "Paramathi-Velur", "Tiruchengodu"},
            {"तमिल नाडु", "नमक्कल", "सांकारी", "राशिपुरम", "सेंतमंगलम", "नमक्कल", "परमाति-वेलूर", "तिरुचेनगोदु"},
            {"Tamil Nadu", "Nilgiris", "Bhavanisagar", "Udhagamandalam", "Gudalur", "Coonoor", "Mettuppalayam", "Avanashi"},
            {"तमिल नाडु", "नीलगिरी", "भवानीसागर", "उधगमंडलम", "गुदालूर", "कुन्नूर", "मेट्टुपलयम", "अवनाशी"},
            {"Tamil Nadu", "Perambalur", "Kulithalai", "Lalgudi", "Manachanallur", "Musiri", "Thuraiyur", "Perambalur"},
            {"तमिल नाडु", "पेरम्बलुर", "कुलीतलाई", "लालगुडी", "मानचनल्लूर", "मुसिरि", "थुरैयूर", "पेरम्बलूर"},
            {"Tamil Nadu", "Pollachi", "Thondamuthur", "Kinathukadavu", "Pollachi", "Valparai", "Udumalaipettai", "Madathukulam"},
            {"तमिल नाडु", "पोलाची", "थोंदामुतुर", "किनातुकदावु", "पोलाची", "वालपरई", "उदुमलाइपेट्टई", "मदातुकुलम"},
            {"Tamil Nadu", "Ramanathapuram", "Aranthangi", "Tiruchuli", "Paramakudi", "Tiruvadanai", "Ramanathapuram", "Mudhukulathur"},
            {"तमिल नाडु", "रामनाथपुरम", "अरंतंगी", "तिरुचुली", "परमकुडी", "तिरुवदनै", "रामनाथपुरम", "मुदुकुलतुर"},
            {"Tamil Nadu", "Salem", "Omalur", "Edappadi", "Salem (West)", "Salem (North)", "Salem (South)", "Veerapandi"},
            {"तमिल नाडु", "सलेम", "ओमालुर", "एदापद्दी", "सलेम (पश्चिम)", "सलेम (उत्तर)", "सलेम (दक्षिण)", "वीरापांडी"},
            {"Tamil Nadu", "Sivaganga", "Thirumayam", "Alangudi", "Karaikudi", "Tiruppattur (Sivaganga)", "Sivaganga", "Manamadurai"},
            {"तमिल नाडु", "शिवगंगा", "तिरुमायम", "अलनगुदी", "कराईकुदी", "तिरुप्पत्तूर (शिवगंगा)", "शिवगंगा", "मनमदुरै"},
            {"Tamil Nadu", "Sriperumbudur", "Maduravoyal", "Ambattur", "Alandur", "Sriperumbudur", "Pallavaram", "Tambaram"},
            {"तमिल नाडु", "श्रीपेरुमबुदुर", "मदुरावोयाल", "अंबत्तूर", "अलन्दूर", "श्रीपेरुमबुदुर", "पल्लवराम", "ताम्बरम"},
            {"Tamil Nadu", "Tenkasi", "Rajapalayam", "Srivilliputhur", "Sankarankovil", "Vasudevanallur", "Kadayanallur", "Tenkasi"},
            {"तमिल नाडु", "तेनकासी", "राजपलयम", "श्रीविल्लिपुतुर", "शंकरनकोविल", "वसुदेवनल्लूर", "कदयानल्लूर", "तेनकासी"},
            {"Tamil Nadu", "Thanjavur", "Mannargudi", "Thiruvaiyaru", "Thanjavur", "Orathanadu", "Pattukkottai", "Peravurani"},
            {"तमिल नाडु", "तंजावुर", "मन्नारगुडी", "तिरुवैयारू", "तंजावुर", "ओरातनाद", "पत्तुकोट्टई", "पेरावर्णी"},
            {"Tamil Nadu", "Theni", "Sholavandan", "Usilampatti", "Andipatti", "Periyakulam", "Bodinayakanur", "Cumbum"},
            {"तमिल नाडु", "थेनी", "शोलवंदन", "उसिलामपट्टी", "अंदिपट्टी", "पेरियाकुलम", "बोदिनायक्कनूर", "कुम्बुम"},
            {"Tamil Nadu", "Thoothukkudi", "Vilathikulam", "Thoothukkudi", "Tiruchendur", "Srivaikuntam", "Ottapidaram", "Kovilpatti"},
            {"तमिल नाडु", "थूथुकुडी", "विलातिकुलम", "थूथुकुडी", "तिरुचेंदूर", "श्रीवैकुंठम", "ओट्टपिदरम", "कोविलपट्टी"},
            {"Tamil Nadu", "Tiruchirappalli", "Srirangam", "Tiruchirappalli (West)", "Tiruchirappalli (East)", "Thiruverumbur", "Gandarvakottai", "Pudukkottai"},
            {"तमिल नाडु", "तिरुचिरापल्ली", "श्रीरंगम", "तिरुचिरापल्ली (पश्चिम)", "तिरुचिरापल्ली (पूर्व)", "तिरुवेरुम्बुर", "गंधर्वकोट्टई", "पुदुक्कोट्टई"},
            {"Tamil Nadu", "Tirunelveli", "Alangulam", "Tirunelveli", "Ambasamudram", "Palayamkottai", "Nanguneri", "Radhapuram"},
            {"तमिल नाडु", "तिरुनेलवेली", "अलंगुनम", "तिरुनेलवेली", "अम्बासमुद्रम", "पलयमकोट्टई", "नंगुनेरी", "राधापुरम"},
            {"Tamil Nadu", "Tiruppur", "Perundurai", "Bhavani", "Anthiyur", "Gobichettipalayam", "Tiruppur (North)", "Tiruppur (South)"},
            {"तमिल नाडु", "तिरुपूर", "पेरुनदुरई", "भवानी", "अंतियुर", "गोबिचेट्टिपलयम", "तिरुपूर (उत्तर)", "तिरुपूर (दक्षिण)"},
            {"Tamil Nadu", "Tiruvallur", "Gummidipoondi", "Ponneri", "Tiruvallur", "Poonamallee", "Avadi", "Madavaram"},
            {"तमिल नाडु", "तिरुवल्लुर", "गुम्मिदीपूंदी", "पोन्नेरी", "तिरुवल्लुर", "पूनमल्ली", "अवदी", "मादवराम"},
            {"Tamil Nadu", "Tiruvannamalai", "Jolarpet", "Tiruppattur", "Chengam", "Tiruvannamalai", "Kilpennathur", "Kalasapakkam"},
            {"तमिल नाडु", "तिरुवन्नामलाई", "जोलारपेट", "तिरुप्पत्तूर", "चेंगम", "तिरुवन्नामलाई", "किलपेन्नथुर", "Kalasapakkam"},
            {"Tamil Nadu", "Vellore", "Vellore", "Anaikattu", "Kilvaithinankuppam", "Gudiyattam", "Vaniyambadi", "Ambur"},
            {"तमिल नाडु", "वेल्लोर", "वेल्लोर", "अनईकट्टु", "किल्वेथिनांकुप्पम", "गुडियाट्टम", "वणियांबड़ी", "अम्बुर"},
            {"Tamil Nadu", "Viluppuram", "Tindivanam", "Vanur", "Viluppuram", "Vikravandi", "Tirukkoyilur", "Ulundurpettai"},
            {"तमिल नाडु", "विलुप्पुरम", "तिंडीवनम", "वनूर", "विलुप्पुरम", "विक्रवन्दी", "तिरुकोइलुर", "उलुन्दुरपेट्टई"},
            {"Tamil Nadu", "Virudhunagar", "Thiruparankundram", "Tirumangalam", "Sattur", "Sivakasi", "Virudhunagar", "Aruppukkottai"},
            {"तमिल नाडु", "विरुधुनगर", "तिरुप्पुरनकुंद्रम", "तिरुमंगलम", "सत्तूर", "शिवकाशी", "विरुधुनगर", "अरुप्पुकोट्टई"},
            //https://www.elections.in/telangana
            {"Telangana", "Adilabad", "Sirpur", "Asifabad", "Khanapur", "Adilabad", "Boath", "Nirmal", "Mudhole"},
            {"तेलंगाना", "आदिलाबाद", "सिरपुर", "आसिफाबाद", "खानपुर", "आदिलाबाद", "बोथ", "निर्मल", "मुधोले"},
            {"Telangana", "Bhongir", "Ibrahimpatnam", "Munugode", "Bhongir", "Nakrekal", "Thungathurthy", "Alair", "Jangaon"},
            {"तेलंगाना", "भोंगीर", "इब्राहिमपटनम", "मुनगोडे", "भोंगीर", "नाकरेकाल", "ठुंगतुर्थी", "अलैर", "जनगांव"},
            {"Telangana", "Chevella", "Maheshwaram", "Rajendranagar", "Serilingampally", "Chevella", "Pargi", "Vikarabad", "Tandur"},
            {"तेलंगाना", "चेवेल्ला", "महेश्वरम", "राजेंद्रनगर", "सेरिलिंगाम्पल्ली", "चेवेल्ला", "पारगी", "विकारबाद", "ताण्डूर"},
            {"Telangana", "Hyderabad", "Malakpet", "Karwan", "Goshamahal", "Charminar", "Chandrayangutta", "Yakutpura", "Bahadurpura"},
            {"तेलंगाना", "हैदराबाद", "मलकपेट", "करवान", "गोशामहल", "चारमीनार", "चंद्रायनगुट्टा", "याकूतपूरा", "बहादुरपुरा"},
            {"Telangana", "Karimnagar", "Karimnagar", "Choppadandi", "Vemulawada", "Sircilla", "Manakondur", "Huzurabad", "Husnabad"},
            {"तेलंगाना", "करीमनगर", "करीमनगर", "चोपपंडी", "वेमुलावाड़ा", "सिरसीला", "मनकोंडूर", "हुज़ूराबाद", "हुस्नाबाद"},
            {"Telangana", "Khammam", "Khammam", "Palair", "Madhira", "Wyra", "Sathupalli", "Kothagudem", "Aswaraopeta"},
            {"तेलंगाना", "खम्मम", "खम्मम", "पालेर", "माधिरा", "वैरा", "साथुपल्ली", "कोठागुडेम", "अस्वारोपता"},
            {"Telangana", "Mahabubabad", "Dornakal", "Mahabubabad", "Narsampet", "Mulug", "Pinapaka", "Yellandu", "Bhadrachalam"},
            {"तेलंगाना", "महबुबाबाद", "दोरनकाल", "महबुबाबाद", "नरसंपेट", "मुलुग", "पिनपाका", "येल्लांडु", "भद्राचलम"},
            {"Telangana", "Mahbubnagar", "Kodangal", "Narayanpet", "Mahbubnagar", "Jadcherla", "Devarkadra", "Makthal", "Shadnagar"},
            {"तेलंगाना", "महबूबनगर", "कोडंगल", "नारायणपेट", "महबूबनगर", "जादचरेला", "देवार्काद्र", "मक्थल", "शादनगर"},
            {"Telangana", "Malkajgiri", "Medchal", "Malkajgiri", "Quthbullapur", "Kukatpally", "Uppal", "Lal Bahadur Nagar", "Secunderabad Cantt"},
            {"तेलंगाना", "मल्काजगिरि", "मेडचाल", "मल्काजगिरि", "कुतुबुल्लापुर", "कुकटपल्ली", "उप्पल", "लालबहादुर नगर", "सिकंदराबाद कैंट"},
            {"Telangana", "Medak", "Siddipet", "Medak", "Narsapur", "Sangareddy", "Patancheru", "Dubbak", "Gajwel"},
            {"तेलंगाना", "मेदक", "सिद्दीपेट", "मेदक", "नरसारपुर", "संगारेड्डी", "पतनचेरु", "दुब्बक", "गज्वेल"},
            {"Telangana", "Nagarkurnool", "Wanaparthy", "Gadwal", "Alampur", "Nagarkurnool", "Achampet", "Kalwakurthy", "Kollapur"},
            {"तेलंगाना", "नगरकुरनूल", "वानापर्थी", "गडवाल", "आलमपुर", "नगरकुरनूल", "अचम्पेट", "कलवाकुर्ती", "कोल्लापूर"},
            {"Telangana", "Nalgonda", "Devarakonda", "Nagarjuna Sagar", "Miryalguda", "Huzurnagar", "Kodad", "Suryapet", "Nalgonda"},
            {"तेलंगाना", "नलगोंडा", "देवकारकोंडा", "नागार्जुन सागर", "मिरयालगुदा", "हुजूरनगर", "कोडेड", "सूर्यापेट", "नलगोंडा"},
            {"Telangana", "Nizamabad", "Armur", "Bodhan", "Nizamabad (Urban)", "Nizamabad (Rural)", "Balkonda", "Koratla", "Jagtial"},
            {"तेलंगाना", "निजामाबाद", "आर्मुर", "बोधन", "निजामाबाद (शहरी)", "निजामाबाद (ग्रामीण)", "बलकोंडा", "कोरटला", "जगित्याल"},
            {"Telangana", "Peddapalli", "Chennur", "Bellampalli", "Mancherial", "Dharmapuri", "Ramagundam", "Manthani", "Peddapalli"},
            {"तेलंगाना", "पेद्दापल्ली", "चेन्नूर", "बेलमपल्ली", "मनचेरियल", "धर्मपुरी", "रामागुंडम", "मंथनी", "पेद्दापल्ली"},
            {"Telangana", "Secunderabad", "Musheerabad", "Amberpet", "Khairatabad", "Jubilee Hills", "Sanathnagar", "Nampally", "Secunderabad"},
            {"तेलंगाना", "सिकंदराबाद", "मुशीराबाद", "अम्बेर्पट", "खैरताबाद", "जुबली हिल्स", "सनाथनगर", "नामपल्ली", "सिकंदराबाद"},
            {"Telangana", "Warangal", "Ghanpur (Station)", "Palakurthi", "Parkal", "Warangal East", "Warangal West", "Wardhannapet", "Bhupalpalle"},
            {"तेलंगाना", "वारंगल", "घानपुर (स्टेशन)", "पालकुरथी", "परकाल", "वारंगल पूर्व", "वारंगल पश्चिम", "वर्धननापेट", "भूपालपल्ले"},
            {"Telangana", "Zahirabad", "Jukkal", "Banswada", "Yellareddy", "Kamareddy", "Narayankhed", "Andole", "Zahirabad"},
            {"तेलंगाना", "जहीराबाद", "जुक्कल", "बांसवाडा", "येलारेड्डी", "कामारेड्डी", "नारायणखेड़", "एंडोल", "जहीराबाद"},
            {"Tripura", "Tripura East", "Ramchandraghat", "Khowai", "Asharambari", "Kalyanpur-Pramodenagar", "Teliamura", "Krishnapur", "Hrishyamukh", "Jolaibari", "Manu", "Sabroom", "Ampinagar", "Amarpur", "Karbook", "Raima Valley", "Kamalpur", "Surma", "Ambassa", "Karamchhara", "Chhawmanu", "Pabiachhara", "Fatikroy", "Chandipur", "Kailasahar", "Kadamtala-Kurti", "Bagbassa", "Dharmanagar", "Jubarajnagar", "Panisagar", "Pencharthal", "Kanchanpur"},
            {"त्रिपुरा", "त्रिपुरा पूर्व", "रामचन्द्रघाट", "खोवाई", "अशरम्बरी", "कल्याणपुर-प्रमोदनगर", "तेलियामुरा", "कृष्णापुर", "हृष्यामुख", "जौलीबारी", "मनू", "सबरूम", "एमपीनगर", "अमरपुर", "करबूक", "राइमा घाटी", "कमलपुर", "सूरमा", "अम्बस्सा", "कर्मछारा", "छावमनू", "पाबियाछारा", "फ़ातिक्रोय", "चांदीपुर", "कैलाशहर", "कदमतला-कुर्ती", "बागबासा", "धर्मनगर", "जुबराजनगर", "पानीसागर", "पंचरथाल", "कंचनपुर"},
            {"Tripura", "Tripura West", "Simna", "Mohanpur", "Bamutia", "Barjala", "Khayerpur", "Agartala", "Ramnagar", "Town Bordowali", "Banamalipur", "Majlishpur", "Mandaibazar", "Takarjala", "Pratapgarh", "Badharghat", "Kamalasagar", "Bishalgarh", "Golaghati", "Suryamaninagar", "Charilam", "Boxanagar", "Nalchar", "Sonamura", "Dhanpur", "Bagma", "Radhakishorepur", "Matarbari", "Kakraban-Salgarah", "Rajnagar", "Belonia", "Santirbazar"},
            {"त्रिपुरा", "त्रिपुरा पश्चिम", "सिमना", "मोहनपुर", "बमूतिया", "बर्जला", "खैरपुर", "अगरतला", "रामनगर", "टाउन बोरडोवाली", "बनमालीपुर", "मजलिशपुर", "मंदिआबाजार", "तकारजाला", "प्रतापगढ़", "बड़हरघाट", "कमलासागर", "बिशालगढ़", "गोलाघाटी", "सूर्यमणीनगर", "छरीलाम", "बौक्सनगर", "नलचर", "सोनमुड़ा", "धानपुर", "बाग्मा", "राधाकिशोरपुर", "मातारबारी", "ककरबान-सालगढ़", "राजनगर", "बेलोनिया", "सांतिरबाज़ार"},
            {"Uttar Pradesh", "Agra", "Etmadpur", "Agra Cantt.", "Agra South", "Agra North", "Jalesar"},
            {"उत्तर प्रदेश", "आगरा", "एतमादपुर", "आगरा कैंट.", "आगरा दक्षिण", "आगरा उत्तर", "जलेसर"},
            {"Uttar Pradesh", "Akbarpur", "Akbarpur Raniya", "Bithoor", "Kalyanpur", "Maharajpur", "Ghatampur"},
            {"उत्तर प्रदेश", "अकबरपुर", "अकबरपुर रनिया", "बिठूर", "कल्याणपुर", "महाराजपुर", "घाटमपुर"},
            {"Uttar Pradesh", "Aligarh", "Khair", "Barauli", "Atrauli", "Koil", "Aligarh"},
            {"उत्तर प्रदेश", "अलीगढ़", "खैर", "बरौली", "अतरौली", "कोइल", "अलीगढ़"},
            {"Uttar Pradesh", "Allahabad", "Meja", "Karachhana", "Allahabad South", "Bara", "Koraon"},
            {"उत्तर प्रदेश", "इलाहाबाद", "मेजा", "करचना", "इलाहाबाद दक्षिण", "बारा", "कोरों"},
            {"Uttar Pradesh", "Ambedkar Nagar", "Katehari", "Tanda", "Goshainganj", "Jalalpur", "Akbarpur"},
            {"उत्तर प्रदेश", "अंबेडकर नगर", "कटेहरी", "टांडा", "गोसाईगंज", "जलालपुर", "अकबरपुर"},
            {"Uttar Pradesh", "Amethi", "Tiloi", "Salon", "Jagdishpur", "Gauriganj", "Amethi"},
            {"उत्तर प्रदेश", "अमेठी", "तिलोई", "सलोन", "जगदीशपुर", "गौरीगंज", "अमेठी"},
            {"Uttar Pradesh", "Amroha", "Dhanaura", "Naugawan Sadat", "Amroha", "Hasanpur", "Garhmukteshwar"},
            {"उत्तर प्रदेश", "अमरोहा", "धनौरा", "नौगावां सादात", "अमरोहा", "हसनपुर", "गढ़मुक्तेश्वर"},
            {"Uttar Pradesh", "Aonla", "Shekhupur", "Dataganj", "Faridpur", "Bithari Chainpur", "Aonla"},
            {"उत्तर प्रदेश", "आंवला", "शेखूपुर", "दातागंज", "फरीदपुर", "बिथरी चैनपुर", "आंवला"},
            {"Uttar Pradesh", "Azamgarh", "Gopalpur", "Sagri", "Mubarakpur", "Azamgarh", "Mehnagar"},
            {"उत्तर प्रदेश", "आजमगढ़", "गोपालपुर", "सगरी", "मुबारकपुर", "आजमगढ़", "मेहनगर"},
            {"Uttar Pradesh", "Badaun", "Gunnaur", "Bisauli", "Sahaswan", "Bilsi", "Badaun"},
            {"उत्तर प्रदेश", "बदायूं", "गुन्नौर", "बिसौली", "सहसवान", "बिल्सी", "बदायूं"},
            {"Uttar Pradesh", "Baghpat", "Siwalkhas", "Chhaprauli", "Baraut", "Baghpat", "Modi Nagar"},
            {"उत्तर प्रदेश", "बागपत", "सिवालखास", "छपरौली", "बड़ौत", "बागपत", "मोदीनगर"},
            {"Uttar Pradesh", "Bahraich", "Balha", "Nanpara", "Matera", "Mahasi", "Bahraich"},
            {"उत्तर प्रदेश", "बहराइच", "बलहा", "नानपारा", "मटेरा", "महसी", "बहराइच"},
            {"Uttar Pradesh", "Ballia", "Phephana", "Ballia Nagar", "Bairia", "Zahoorabad", "Mohammadabad"},
            {"उत्तर प्रदेश", "बलिया", "फेफना", "बलिया नगर", "बैरिया", "जहूराबाद", "मोहम्मदाबाद"},
            {"Uttar Pradesh", "Banda", "Baberu", "Naraini", "Banda", "Chitrakoot", "Manikpur"},
            {"उत्तर प्रदेश", "बांदा", "बबेरू", "नरैनी", "बांदा", "चित्रकूट", "मानिकपुर"},
            {"Uttar Pradesh", "Bansgaon", "Chauri-Chaura", "Bansgaon", "Chillupar", "Rudrapur", "Barhaj"},
            {"उत्तर प्रदेश", "बांसगांव", "चौरी-चौरा", "बांसगांव", "चिल्लूपार", "रुद्रपुर", "बरहज"},
            {"Uttar Pradesh", "Barabanki", "Kursi", "Ram Nagar", "Barabanki", "Zaidpur", "Haidergarh"},
            {"उत्तर प्रदेश", "बाराबंकी", "कुर्सी", "रामनगर", "बाराबंकी", "जैदपुर", "हैदरगढ़"},
            {"Uttar Pradesh", "Bareilly", "Meerganj", "Bhojipura", "Nawabganj", "Bareilly", "Bareilly Cantt"},
            {"उत्तर प्रदेश", "बरेली", "मीरगंज", "भोजीपुरा", "नवाबगंज", "बरेली", "बरेली कैंट."},
            {"Uttar Pradesh", "Basti", "Harraiya", "Kaptanganj", "Rudhauli", "Basti Sadar", "Mahadewa"},
            {"उत्तर प्रदेश", "बस्ती", "हर्रैया", "कप्तानगंज", "रुधौली", "बस्ती सदर", "महादेवा"},
            {"Uttar Pradesh", "Bhadohi", "Pratappur", "Handia", "Bhadohi", "Gyanpur", "Aurai"},
            {"उत्तर प्रदेश", "भदोही", "प्रतापपुर", "हंडिया", "भदोही", "ज्ञानपुर", "औराई"},
            {"Uttar Pradesh", "Bijnor", "Purqazi", "Meerapur", "Bijnor", "Chandpur", "Hastinapur"},
            {"उत्तर प्रदेश", "बिजनौर", "पुरकाजी", "मीरापुर", "बिजनौर", "चांदपुर", "हस्तिनापुर"},
            {"Uttar Pradesh", "Bulandshahr", "Bulandshahr", "Syana", "Anupshahr", "Debai", "Shikarpur"},
            {"उत्तर प्रदेश", "बुलंदशहर", "बुलंदशहर", "स्याना", "अनूपशहर", "डिबाई", "शिकारपुर"},
            {"Uttar Pradesh", "Chandauli", "Mughalsarai", "Sakaldiha", "Saiyadraja", "Ajagara", "Shivpur"},
            {"उत्तर प्रदेश", "चंदौली", "मुगलसराय", "सकलडीहा", "सैयदराजा", "अजगर", "शिवपुर"},
            {"Uttar Pradesh", "Deoria", "Tamkuhi Raj", "Fazilnagar", "Deoria", "Pathardeva", "Rampur Karkhana"},
            {"उत्तर प्रदेश", "देवरिया", "तमकुही राज", "फाजिलनगर", "देवरिया", "पथरदेवा", "रामपुर कारखाना"},
            {"Uttar Pradesh", "Dhaurahra", "Dhaurahra", "Kasta", "Mohammdi", "Mohali", "Hargaon"},
            {"उत्तर प्रदेश", "धौरहरा", "धौरहरा", "कस्ता", "मोहम्मदी", "महोली", "हरगांव"},
            {"Uttar Pradesh", "Domariyaganj", "Shohratgarh", "Kapilvastu", "Bansi", "Itwa", "Domariyaganj"},
            {"उत्तर प्रदेश", "डुमरियागंज", "शोहरतगढ़", "कपिलवस्तु", "बांसी", "इटवा", "डुमरियागंज"},
            {"Uttar Pradesh", "Etah", "Kasganj", "Amanpur", "Patiyali", "Etah", "Marhara"},
            {"उत्तर प्रदेश", "एटा", "कासगंज", "अमांपुर", "पटियाली", "एटा", "मारहरा"},
            {"Uttar Pradesh", "Etawah", "Etawah", "Bharthana", "Dibiyapur", "Auraiya", "Sikandra"},
            {"उत्तर प्रदेश", "इटावा", "इटावा", "भरथना", "दिबियापुर", "औरैया", "सिकंदरा"},
            {"Uttar Pradesh", "Faizabad", "Dariyabad", "Rudauli", "Milkipur", "Bikapur", "Ayodhya"},
            {"उत्तर प्रदेश", "फैजाबाद", "दरियाबाद", "रुदौली", "मिल्कीपुर", "बीकापुर", "अयोध्या"},
            {"Uttar Pradesh", "Farrukhabad", "Aliganj", "Kaimganj", "Amritpur", "Farrukhabad", "Bhojpur"},
            {"उत्तर प्रदेश", "फर्रुखाबाद", "अलीगंज", "कायमगंज", "अमृतपुर", "फर्रुखाबाद", "भोजपुर"},
            {"Uttar Pradesh", "Fatehpur", "Jahanabad", "Bindki", "Fatehpur", "Ayah Shah", "Husainganj", "Khaga"},
            {"उत्तर प्रदेश", "फतेहपुर", "जहानाबाद", "बिंदकी", "फतेहपुर", "अयाह शाह", "हुसैनगंज", "खागा"},
            {"Uttar Pradesh", "Fatehpur Sikri", "Agra Rural", "Fatehpur Sikri", "Kheragarh", "Fatehabad", "Bah"},
            {"उत्तर प्रदेश", "फतेहपुर सीकरी", "आगरा ग्रामीण", "फतेहपुर सीकरी", "खेरागढ़", "फतेहाबाद", "बाह"},
            {"Uttar Pradesh", "Firozabad", "Tundla", "Jasrana", "Firozabad", "Shikohabad", "Sirsaganj"},
            {"उत्तर प्रदेश", "फिरोजाबाद", "टूंडला", "जसराना", "फिरोजाबाद", "शिकोहाबाद", "सिरसागंज"},
            {"Uttar Pradesh", "Gautam Buddha Nagar", "Noida", "Dadri", "Jewar", "Sikandrabad", "Khurja"},
            {"उत्तर प्रदेश", "गौतम बुद्ध नगर", "नोएडा", "दादरी", "जेवर", "सिकंदराबाद", "खुर्जा"},
            {"Uttar Pradesh", "Ghaziabad", "Loni", "Muradnagar", "Sahibabad", "Ghaziabad", "Dhaulana"},
            {"उत्तर प्रदेश", "गाज़ियाबाद", "लोनी", "मुरादनगर", "साहिबाबाद", "गाज़ियाबाद", "धौलाना"},
            {"Uttar Pradesh", "Ghazipur", "Jakhanian", "Saidpur", "Ghazipur", "Jangipur", "Zamania"},
            {"उत्तर प्रदेश", "गाजीपुर", "जखनियां", "सैदपुर", "गाजीपुर", "जंगीपुर", "ज़मानिया"},
            {"Uttar Pradesh", "Ghosi", "Madhuban", "Ghosi", "Muhammadabad-Gohna", "Mau", "Rasara"},
            {"उत्तर प्रदेश", "घोसी", "मधुबन", "घोसी", "मुहम्मदाबाद-गोहना(एस सी)", "मऊ", "रसड़ा"},
            {"Uttar Pradesh", "Gonda", "Utraula", "Mehnaun", "Gonda", "Mankapur", "Gaura"},
            {"उत्तर प्रदेश", "गोंडा", "उतरौला", "मेहनौन", "गोंडा", "मनकापुर", "गौरा"},
            {"Uttar Pradesh", "Gorakhpur", "Caimpiyarganj", "Pipraich", "Gorakhpur Urban", "Gorakhpur Rural", "Sahajanwa"},
            {"उत्तर प्रदेश", "गोरखपुर", "कैम्पियरगंज", "पिपराइच", "गोरखपुर शहरी", "गोरखपुर ग्रामीण", "सहजनवा"},
            {"Uttar Pradesh", "Hamirpur", "Hamirpur", "Rath", "Mahoba", "Charkhari", "Tindwari"},
            {"उत्तर प्रदेश", "हमीरपुर", "हमीरपुर", "राठ", "महोबा", "चरखारी", "तिंदवारी"},
            {"Uttar Pradesh", "Hardoi", "Sawaijpur", "Shahabad", "Hardoi", "Gopamau", "Sandi"},
            {"उत्तर प्रदेश", "हरदोई", "सवायजपुर", "शाहाबाद", "हरदोई", "गोपामऊ", "सांडि"},
            {"Uttar Pradesh", "Hathras", "Chharra", "Iglas", "Hathras", "Sadabad", "Sikandra Rao"},
            {"उत्तर प्रदेश", "हाथरस", "छर्रा", "इगलास", "हाथरस", "सादाबाद", "सिकंदरा राव"},
            {"Uttar Pradesh", "Jalaun", "Bhognipur", "Madhaugarh", "Kalpi", "Orai", "Garautha"},
            {"उत्तर प्रदेश", "जालौन", "भोगनीपुर", "माधौगढ़", "कालपी", "उरई", "गरौठा"},
            {"Uttar Pradesh", "Jaunpur", "Badlapur", "Shahganj", "Jaunpur", "Malhani", "Mungra Badshahpur"},
            {"उत्तर प्रदेश", "जौनपुर", "बदलापुर", "शाहगंज", "जौनपुर", "मल्हनी", "मुंगरा बादशाहपुर"},
            {"Uttar Pradesh", "Jhansi", "Babina", "Jhansi Nagar", "Mauranipur", "Lalitpur", "Mehroni"},
            {"उत्तर प्रदेश", "झांसी", "बबीना", "झांसी नगर", "मऊरानीपुर", "ललितपुर", "महरौनी"},
            {"Uttar Pradesh", "Kairana", "Nakur", "Gangoh", "Kairana", "Thana Bhawan", "Shamli"},
            {"उत्तर प्रदेश", "कैराना", "नकुड़", "गंगोह", "कैराना", "थाना भवन", "शामली"},
            {"Uttar Pradesh", "Kaiserganj", "Payagpur", "Kaiserganj", "Katra Bazar", "Colonelganj", "Tarabganj"},
            {"उत्तर प्रदेश", "कैसरगंज", "पयागपुर", "कैसरगंज", "कटरा बाजार", "कर्नलगंज", "तरबगंज"},
            {"Uttar Pradesh", "Kannauj", "Chhibramau", "Tirwa", "Kannauj", "Bidhuna", "Rasulabad"},
            {"उत्तर प्रदेश", "कन्नौज", "छिबरामऊ", "तिर्वा", "कन्नौज", "बिधूना", "रसूलाबाद"},
            {"Uttar Pradesh", "Kanpur", "Govindnagar", "Sishamau", "Arya Nagar", "Kidwai Nagar", "Kanpur Cantt"},
            {"उत्तर प्रदेश", "कानपुर", "गोविंद नगर", "सीसामऊ", "आर्य नगर", "किदवई नगर", "कानपुर कैंट"},
            {"Uttar Pradesh", "Kaushambi", "Babaganj", "Kunda", "Sirathu", "Manjhanpur", "Chail"},
            {"उत्तर प्रदेश", "कौशाम्बी", "बाबागंज", "कुंडा", "सिराथू", "मंझनपुर", "चैल"},
            {"Uttar Pradesh", "Kheri", "Palia", "Nighasan", "Gola Gokrannath", "Sri Nagar", "Lakhimpur"},
            {"उत्तर प्रदेश", "खेरी", "पलिया", "निघासन", "गोला गोकर्णनाथ", "श्री नगर", "लखीमपुर"},
            {"Uttar Pradesh", "Kushi Nagar", "Khadda", "Padrauna", "Kushinagar", "Hata", "Ramkola"},
            {"उत्तर प्रदेश", "कुशी नगर", "खड्डा", "पडरौना", "कुशी नगर", "हाटा", "रामकोला"},
            {"Uttar Pradesh", "Lalganj", "Atrauliya", "Nizamabad", "Phoolpur Pawai", "Didarganj", "Lalganj"},
            {"उत्तर प्रदेश", "लालगंज", "अतरौलिया", "निजामाबाद", "फूलपुर पवाई", "दीदारगंज", "लालगंज"},
            {"Uttar Pradesh", "Lucknow", "Lucknow West", "Lucknow North", "Lucknow East", "Lucknow Central", "Lucknow Cantt."},
            {"उत्तर प्रदेश", "लखनऊ", "लखनऊ पश्चिम", "लखनऊ उत्तर", "लखनऊ पूर्व", "लखनऊ सेंट्रल", "लखनऊ कैंट."},
            {"Uttar Pradesh", "Machhlishahr", "Machhlishahr", "Mariyahu", "Zafrabad", "Kerakat", "Pindra"},
            {"उत्तर प्रदेश", "मछलीशहर", "मछलीशहर", "मड़ियाहूं", "जफराबाद", "केराकत", "पिंडरा"},
            {"Uttar Pradesh", "Maharajganj", "Pharenda", "Nautanwa", "Siswa", "Maharajganj", "Paniyara"},
            {"उत्तर प्रदेश", "महाराजगंज", "फरेन्दा", "नौतनवा", "सिसवा", "महाराजगंज", "पनियरा"},
            {"Uttar Pradesh", "Mainpuri", "Mainpuri", "Bhongaon", "Kishni", "Karhal", "Jaswantnagar"},
            {"उत्तर प्रदेश", "मैनपुरी", "मैनपुरी", "भोगांव", "किशनी", "करहल", "जसवंतनगर"},
            {"Uttar Pradesh", "Mathura", "Chhata", "Mant", "Goverdhan", "Mathura", "Baldev"},
            {"उत्तर प्रदेश", "मथुरा", "छटा", "मंत", "गोवर्धन", "मथुरा", "बलदेव"},
            {"Uttar Pradesh", "Meerut", "Kithore", "Meerut Cantt.", "Meerut", "Meerut South", "Hapur"},
            {"उत्तर प्रदेश", "मेरठ", "किठौर", "मेरठ कैंट.", "मेरठ", "मेरठ दक्षिण", "हापुड़"},
            {"Uttar Pradesh", "Mirzapur", "Chhanbey", "Mirzapur", "Majhawan", "Chunar", "Marihan"},
            {"उत्तर प्रदेश", "मिर्जापुर", "छानबे", "मिर्जापुर", "मझवां", "चुनार", "मड़िहान"},
            {"Uttar Pradesh", "Misrikh", "Misrikh", "Bilgram Mallanwan", "Balamau", "Sandila", "Bilhaur"},
            {"उत्तर प्रदेश", "मिसरिख", "मिसरिख", "बिलग्राम मल्लावां", "बालामऊ", "सण्डीला", "बिल्हौर"},
            {"Uttar Pradesh", "Mohanlalganj", "Sidhauli", "Malihabad", "Bakshi Kaa Talab", "Sarojini Nagar", "Mohanlalganj"},
            {"उत्तर प्रदेश", "मोहनलालगंज", "सिधौली", "मलिहाबाद", "बक्शी का तालाब", "सरोजिनी नगर", "मोहनलालगंज"},
            {"Uttar Pradesh", "Moradabad", "Barhapur", "Kanth", "Thakurdwara", "Moradabad Rural", "Moradabad Nagar"},
            {"उत्तर प्रदेश", "मुरादाबाद", "बढ़ापुर", "काँठ", "ठाकुरद्वारा", "मुरादाबाद ग्रामीण", "मुरादाबाद नगर"},
            {"Uttar Pradesh", "Muzaffarnagar", "Budhana", "Charthawal", "Muzaffar Nagar", "Khatauli", "Sardhana"},
            {"उत्तर प्रदेश", "मुजफ्फरनगर", "बुढ़ाना", "चरथावल", "मुजफ्फर नगर", "खतौली", "सरधना"},
            {"Uttar Pradesh", "Nagina", "Najibabad", "Nagina", "Dhampur", "Nehtaur", "Noorpur"},
            {"उत्तर प्रदेश", "नगीना", "नजीबाबाद", "नगीना", "धामपुर", "नहटौर", "नूरपुर"},
            {"Uttar Pradesh", "Phulpur", "Phaphamau", "Soraon", "Phulpur", "Allahabad West", "Allahabad North"},
            {"उत्तर प्रदेश", "फूलपुर", "फाफामऊ", "सोराअों", "फूलपुर", "इलाहाबाद पश्चिम", "इलाहाबाद उत्तर"},
            {"Uttar Pradesh", "Pilibhit", "Baheri", "Pilibhit", "Barkhera", "Puranpur", "Bisalpur"},
            {"उत्तर प्रदेश", "पीलीभीत", "बहेरी", "पीलीभीत", "बरखेड़ा", "पूरनपुर", "बीसलपुर"},
            {"Uttar Pradesh", "Pratapgarh", "Rampur Khas", "Vishwanath Ganj", "Pratapgarh", "Patti", "Raniganj"},
            {"उत्तर प्रदेश", "प्रतापगढ़", "रामपुर खास", "विश्वनाथ गंज", "प्रतापगढ़", "पट्टी", "रानीगंज"},
            {"Uttar Pradesh", "Rae Bareli", "Bachhrawan", "Harchandpur", "Rae Bareli", "Sareni", "Unchahar"},
            {"उत्तर प्रदेश", "रायबरेली", "बछरावां", "हरचंदपुर", "रायबरेली", "सरेनी", "ऊंचाहार"},
            {"Uttar Pradesh", "Rampur", "Suar", "Chamraua", "Bilaspur", "Rampur", "Milak"},
            {"उत्तर प्रदेश", "रामपुर", "सूअर", "चमरौआ", "बिलासपुर", "रामपुर", "मिलक"},
            {"Uttar Pradesh", "Robertsganj", "Chakia", "Ghorawal", "Robertsganj", "Obra", "Duddhi"},
            {"उत्तर प्रदेश", "रोबर्टस गंज", "चकिया", "घोरावल", "रोबर्टस गंज", "ओबरा", "दुद्धी"},
            {"Uttar Pradesh", "Saharanpur", "Behat", "Saharanpur Nagar", "Saharanpur", "Deoband", "Rampur Maniharan"},
            {"उत्तर प्रदेश", "सहारनपुर", "बेहत", "सहारनपुर नगर", "सहारनपुर", "देवबन्द", "रामपुर मनिहारान"},
            {"Uttar Pradesh", "Salempur", "Bhatpar Rani", "Salempur", "Belthara Road", "Sikanderpur", "Bansdih"},
            {"उत्तर प्रदेश", "सलेमपुर", "भाटपार रानी", "सलेमपुर", "बेलथरा रोड", "सिकंदरपुर", "बांसडीह"},
            {"Uttar Pradesh", "Sambhal", "Kundarki", "Bilari", "Chandausi", "Asmoli", "Sambhal"},
            {"उत्तर प्रदेश", "संभल", "कुंदरकी", "बिलारी", "चन्दौसी", "असमोली", "संभल"},
            {"Uttar Pradesh", "Sant Kabir Nagar", "Alapur", "Menhdawal", "Khalilabad", "Dhanghata", "Khajani"},
            {"उत्तर प्रदेश", "संत कबीर नगर", "अलापुर", "मेंहदावल", "खलीलाबाद", "धनघटा", "खजनी"},
            {"Uttar Pradesh", "Shahjahanpur", "Katra", "Jalalabad", "Tilhar", "Powayan", "Shahjahanpur", "Dadraul"},
            {"उत्तर प्रदेश", "शाहजहांपुर", "कटरा", "Jalalabad", "तिलहर", "पुवायां", "शाहजहांपुर", "ददरौल"},
            {"Uttar Pradesh", "Shrawasti", "Bhinga", "Shrawasti", "Tulsipur", "Gainsari", "Balrampur"},
            {"उत्तर प्रदेश", "श्रावस्ती", "भिनगा", "श्रावस्ती", "तुलसीपुर", "गैसड़ी", "बलरामपुर"},
            {"Uttar Pradesh", "Sitapur", "Sitapur", "Laharpur", "Biswan", "Sevata", "Mohmoodabad"},
            {"उत्तर प्रदेश", "सीतापुर", "सीतापुर", "लहरपुर", "बिसवाँ", "सेवता", "महमूदाबाद"},
            {"Uttar Pradesh", "Sultanpur", "Isauli", "Sultanpur", "Sadar", "Lambhua", "Kadipur"},
            {"उत्तर प्रदेश", "सुल्तानपुर", "इसौली", "सुल्तानपुर", "सदर", "लम्भुआ", "कादीपुर"},
            {"Uttar Pradesh", "Unnao", "Bangermau", "Safipur", "Mohan", "Unnao", "Bhagwantnagar", "Purwa"},
            {"उत्तर प्रदेश", "उन्नाव", "बांगरमऊ", "सफीपुर", "मोहन", "उन्नाव", "भगवंतनगर", "पूर्वा"},
            {"Uttar Pradesh", "Varanasi", "Rohaniya", "Sevapuri", "Varanasi Cantt.", "Varanasi North", "Varanasi South"},
            {"उत्तर प्रदेश", "वाराणसी", "रोहनिया", "सेवापुरी", "वाराणसी कैंट.", "वाराणसी उत्तर", "वाराणसी दक्षिण"},
            {"Uttarakhand", "Almora", "Dharchula", "Didihat", "Pithoragarh", "Gangolihat", "Kapkote", "Bageshwar", "Dwarahat", "Salt", "Ranikhet", "Someshwar", "Almora", "Jageshwar", "Lohaghat", "Champawat"},
            {"उत्तराखण्ड", "अल्मोड़ा", "धारचूला", "डीडीहाट", "पिथौरागढ़", "गंगोलीहाट", "कपकोटे", "बागेश्वर", "द्वारहाट", "साल्ट", "रानीखेत", "सोमेश्वर", "अल्मोड़ा", "जागेश्वर", "लोहाघाट ", "चम्पावत"},
            {"Uttarakhand", "Garhwal", "Badrinath", "Tharali", "Karnprayag", "Kedarnath", "Rudraprayag", "Deoprayag", "Narendranagar", "Yamkeshwar", "Pauri", "Srinagar", "Chaubattakhal", "Lansdowne", "Kotdwar", "Ramnagar"},
            {"उत्तराखण्ड", "गढ़वाल", "बद्रीनाथ", "थराली", "कर्णप्रयाग", "केदारनाथ", "रुद्रप्रयाग", "देवप्रयाग", "नरेंद्रनगर", "यमकेश्वर", "पौड़ी", "श्रीनगर", "चौबत्ताखाल", "लैंसडाउन", "कोटद्वार ", "रामनगर"},
            {"Uttarakhand", "Haridwar", "Dharampur", "Doiwala", "Rishikesh", "Haridwar", "B.H.E.L Ranipur", "Jwalapur", "Bhagwanpur", "Jhabrera", "Pirankaliyar", "Roorkee", "Khanpur", "Manglaur", "Laksar", "Haridwar Rural"},
            {"उत्तराखण्ड", "हरिद्वार", "धर्मपुर", "डोईवाला", "ऋषिकेश", "हरिद्वार", "भेल रानीपुर", "ज्वालापुर", "भगवानपुर", "झबरेड़ा", "पिरानकालियार", "रुड़की", "खानपुर", "मंगलौर", "लक्सर", "हरिद्वार ग्रामीण"},
            {"Uttarakhand", "Nainital-UdhamSingh Nagar", "Lalkuwa", "Bhimtal", "Nainital", "Haldwani", "Kaladhungi", "Jaspur", "Kashipur", "Bajpur", "Gadarpur", "Rudrapur", "Kichha", "Sitarganj", "Nanak Matta", "Khatima"},
            {"उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "लालकुआं", "भीमताल", "नैनीताल", "हल्द्वानी", "कालाढूंगी", "जसपुर", "काशीपुर", "बाजपुर", "गदरपुर", "रुद्रपुर", "किच्छा", "सितारगंज", "नानकमत्ता ", "खटीमा"},
            {"Uttarakhand", "Tehri Garhwal", "Purola", "Yamunotri", "Gangotri", "Ghanshali", "Pratapnagar", "Tehri", "Dhanolti", "Chakrata", "Vikasnagar", "Sahaspur", "Raipur", "Rajpur Road", "Dehradun Cantt.", "Mussoorie"},
            {"उत्तराखण्ड", "टिहरी गढ़वाल", "पुरोला", "यमुनोत्री", "गंगोत्री", "घनशाली", "प्रतापनगर", "टिहरी", "धनौल्टी", "चकराता", "विकासनगर", "सहसपुर", "रायपुर", "राजपुर रोड", "देहरादून कैंट.", "मसूरी"},
            {"West Bengal", "Alipurduars", "Tufanganj", "Kumargram", "Kalchini", "Alipurduars", "Falakata", "Madarihat", "Nagrakata"},
            {"पश्चिम बंगाल", "अलीपुरद्वार", "तूफानगंज", "कुमारग्राम", "कालचिनी", "अलीपुरद्वार", "फालाकाटा", "मदारीहाट", "नागरकता"},
            {"West Bengal", "Arambag", "Haripal", "Tarakeswar", "Pursurah", "Arambag", "Goghat", "Khanakul", "Chandrakona"},
            {"पश्चिम बंगाल", "आरामबाग", "हरिपाल", "तारकेश्वर", "पुरशुराह", "आरामबाग", "गौघाट", "खानाकुल", "चंद्राकोना"},
            {"West Bengal", "Asansol", "Pandabeswar", "Raniganj", "Jamuria", "Asansol Dakshin", "Asansol Uttar", "Kulti", "Barabani"},
            {"पश्चिम बंगाल", "आसनसोल", "पांडवेश्वर", "रानीगंज", "जमुरिया", "आसनसोल दक्षिण", "आसनसोल उत्तर", "कुल्टी", "बाराबनी"},
            {"West Bengal", "Baharampur", "Burwan", "Kandi", "Bharatpur", "Rejinagar", "Beldanga", "Baharampur", "Naoda"},
            {"पश्चिम बंगाल", "बरहाम्पुर", "बुरवान", "कांडी", "भरतपुर", "रेजिनगर", "बेलडांगा", "बरहाम्पुर", "नोडा"},
            {"West Bengal", "Balurghat", "Itahar", "Kushmandi", "Kumarganj", "Balurghat", "Tapan", "Gangarampur", "Harirampur"},
            {"पश्चिम बंगाल", "बेलूरघाट", "इताहर", "कुशमंडी", "कुमारगंज", "बालुरघाट", "तपन", "गंगारामपुर", "हरीरामपुर"},
            {"West Bengal", "Bangaon", "Kalyani", "Haringhata", "Bagda", "Bangaon Uttar", "Bangaon Dakshin", "Gaighata", "Swarupnagar"},
            {"पश्चिम बंगाल", "बंगाव", "कल्याणी", "हरिनघाटा", "बागदा", "बनगाँव उत्तर", "बनगाँव दक्षिण", "गाईघाटा", "स्वरूपनगर"},
            {"West Bengal", "Bankura", "Raghunathpur", "Saltora", "Chhatna", "Ranibandh", "Raipur", "Taldangra", "Bankura"},
            {"पश्चिम बंगाल", "बांकुड़ा", "रघुनाथपुर", "सलतोरा", "छतना", "रानीबंध", "रायपुर", "तालडांगरा", "बांकुड़ा"},
            {"West Bengal", "Barasat", "Habra", "Ashoknagar", "Rajarhat New Town", "Bidhannagar", "Madhyamgram", "Barasat", "Deganga"},
            {"पश्चिम बंगाल", "बारासात", "हाबरा", "अशोकनगर", "राजारहाट न्यु टाउन", "बिधाननगर", "मध्यमग्राम", "बारासात", "देगंगा"},
            {"West Bengal", "Bardhaman Durgapur", "Bardhaman Dakshin", "Monteswar", "Bardhaman Uttar", "Bhatar", "Galsi", "Durgapur Purba", "Durgapur Paschim"},
            {"पश्चिम बंगाल", "बर्धमान-दुर्गापुर", "बर्धमान दक्षिण", "मोनतेश्वर", "बर्धमान उत्तर", "भातर", "गलसी", "दुर्गापुर पूर्व", "दुर्गापुर पश्चिम"},
            {"West Bengal", "Bardhaman Purba", "Raina", "Jamalpur", "Kalna", "Memari", "Purbasthali Dakshin", "Purbasthali Uttar", "Katwa"},
            {"पश्चिम बंगाल", "बर्धमान पूर्ब", "रैना", "जमालपुर", "कालना", "मेमारी", "पूर्बस्थली दक्षिण", "पूर्बस्थली उत्तर", "कटवा"},
            {"West Bengal", "Barrackpur", "Amdanga", "Bijpur", "Naihati", "Bhatpara", "Jagatdal", "Noapara ", "Barrackpur"},
            {"पश्चिम बंगाल", "बैरकपुर", "आमडांगा", "बिजपुर", "नैहाटी", "भाटपाड़ा", "जगदल", "नवापाड़ा ", "बैरकपुर"},
            {"West Bengal", "Basirhat", "Baduria", "Haroa", "Minakhan", "Sandeshkhali", "Basirhat Dakshin", "Basirhat Uttar", "Hingalganj"},
            {"पश्चिम बंगाल", "बशीरहाट", "बदुड़ीया", "हारोआ", "मिनाखा", "संदेशखाली", "बशीरहाट दक्षिण", "बशीरहाट उत्तर", "हिंगलगंज"},
            {"West Bengal", "Birbhum", "Dubrajpur", "Suri", "Sainthia", "Rampurhat", "Hansan", "Nalhati", "Murarai"},
            {"पश्चिम बंगाल", "बीरभूम", "दुबराजपुर", "सूरी", "सैन्थिआ", "रामपुरहाट", "हंसन", "नलहाटी", "मुरारई"},
            {"West Bengal", "Bishnupur", "Barjora", "Onda", "Bishnupur", "Katulpur", "Indus", "Sonamukhi", "Khandaghosh"},
            {"पश्चिम बंगाल", "बिश्नुपुर", "बारजोरा", "ओण्डा", "बिश्नुपुर", "काटुलपुर", "इंडस", "सोनामुखी", "खण्डघोष"},
            {"West Bengal", "Bolpur", "Ketugram", "Mangalkot", "Ausgram", "Bolpur", "Nanoor", "Labpur", "Mayureswar"},
            {"पश्चिम बंगाल", "बोलपुर", "केतुग्राम", "मंगलकोट", "आॅसग्राम", "बोलपुर", "नानूर", "लाबपुर", "मयूरेश्वर"},
            {"West Bengal", "Cooch behar", "Mathabhanga", "Coochbehar Uttar", "Coochbehar Dakshin", "Sitalkuchi", "Sitai", "Dinhata", "Natabari"},
            {"पश्चिम बंगाल", "कूचबिहार", "मथाभंगा", "कूचबिहार उत्तर", "कूचबिहार दक्षिण", "सितलकुचि", "सिताई", "दिनहाटा", "नाटाबाड़ी"},
            {"West Bengal", "Darjeeling", "Kalimpong", "Darjeeling", "Kurseong", "Matigara-Naxalbari", "Siliguri", "Phansidewa", "Chopra"},
            {"पश्चिम बंगाल", "दार्जिलिंग", "कालिंपोंग", "दार्जिलिंग", "कुर्सेओंग", "माटीगाड़ा-नक्सलबाड़ी", "सिलीगुड़ी", "फंसिडेवा", "चोपड़ा"},
            {"West Bengal", "Diamond Harbour", "Diamond Harbour", "Falta", "Satgachhia", "Bishnupur", "Maheshtala", "Budge Budge", "Metiaburuz"},
            {"पश्चिम बंगाल", "डायमंड हार्बर", "डायमंड हार्बर", "फलता", "सतगछिआ", "बिश्नुपुर", "महेशतला", "बुडगे बुडगे", "मेटियाबुरुज"},
            {"West Bengal", "Dum Dum", "Khardaha", "Dum Dum Uttar", "Panihati", "Kamarhati", "Baranagar", "Dum Dum", "Rajarhat Gopalpur"},
            {"पश्चिम बंगाल", "डम डम", "खड़दाह", "डम डम उत्तर", "पनिहाटी", "कमरहाटी", "बारानगर", "डम डम", "राजरहाट गोपालपुर"},
            {"West Bengal", "Ghatal", "Panskura Paschim", "Sabang", "Pingla", "Debra", "Daspur", "Ghatal", "Keshpur"},
            {"पश्चिम बंगाल", "घाटाल", "पाँसकुड़ा पश्चिम", "सबंग", "पिंगला", "डेबरा", "दासपुर", "घाटाल", "केशपुर"},
            {"West Bengal", "Hooghly", "Singur", "Chandannagar", "Chunchura", "Balagarh", "Pandua", "Saptagram", "Dhanekhali"},
            {"पश्चिम बंगाल", "हुगली", "सिंगुर", "चन्दननगर", "चिन्सुरा", "बालागढ़", "पांडुआ", "सप्तग्राम", "धनखेली"},
            {"West Bengal", "Howrah", "Bally", "Howrah Uttar", "Howrah Madhya", "Shibpur", "Howrah Dakshin", "Sankrail", "Panchla"},
            {"पश्चिम बंगाल", "हावड़ा", "बाली", "हावड़ा उत्तर", "हावड़ा मध्य", "शिबपुर", "हावड़ा दक्षिण", "सांकराइल", "पांचला"},
            {"West Bengal", "Jadavpur", "Baruipur Purba", "Baruipur Paschim", "Sonarpur Dakshin", "Bhangar", "Jadavpur", "Sonarpur Uttar", "Tollyganj"},
            {"पश्चिम बंगाल", "जादवपुर", "बारुईपुर पूर्व", "बारुईपुर पश्चिम", "सोनारपुर दक्षिण", "भानगर", "जादवपुर", "सोनारपुर उत्तर", "टॉलीगंज"},
            {"West Bengal", "Jalpaiguri", "Mekliganj", "Dhupguri", "Maynaguri", "Jalpaiguri", "Rajganj", "Dabgram-Phulbari", "Mal"},
            {"पश्चिम बंगाल", "जलपाईगुड़ी", "मेकलीगंज", "धुपगुड़ी", "मैनागुड़ी", "जलपाईगुड़ी", "राजगंज", "दबग्राम-फूलबाड़ी", "माल"},
            {"West Bengal", "Jangipur", "Suti", "Jangipur", "Raghunathganj", "Sagardighi", "Lalgola", "Nabagram", "Khargram"},
            {"पश्चिम बंगाल", "जंगीपुर", "सुति", "जंगीपुर", "रघुनाथगंज", "सागर्दिघी", "लालगोला", "नवग्राम", "खाराग्राम"},
            {"West Bengal", "Jaynagar", "Gosaba", "Basanti", "Kultali", "Jaynagar", "Canning Paschim", "Canning Purba", "Magrahat Purba"},
            {"पश्चिम बंगाल", "जयनगर", "गोसाबा", "बसंती", "कुलतली", "जयनगर", "कैनिंग पश्चिम", "कैनिंग पूर्वा", "मजरहत पूर्व"},
            {"West Bengal", "Jhargram", "Nayagram", "Gopiballavpur", "Jhargram", "Garbeta", "Salboni", "Binpur", "Bandwan"},
            {"पश्चिम बंगाल", "झारग्राम", "नयाग्राम", "गोपीबल्लवपुर", "झारग्राम", "गरबेटा", "सालबोनी", "बिनपुर", "बंदवान"},
            {"West Bengal", "Kanthi", "Chandipur", "Patashpur", "Kanthi Uttar", "Bhagabanpur", "Khejuri", "Kanthi Dakshin", "Ramnagar"},
            {"पश्चिम बंगाल", "कंठी", "चांदीपुर", "पाताशपुर", "कंठी उत्तर", "भगबानपुर", "खेजुरी", "कंठी दक्षिण", "रामनगर"},
            {"West Bengal", "Kolkata Dakshin", "Kasba", "Behala Purba", "Behala Paschim", "Kolkata Port", "Bhabanipur", "Rashbehari", "Ballygunge"},
            {"पश्चिम बंगाल", "कोलकाता दक्षिण", "क़स्बा", "बेहला पूर्व", "बेहला पश्चिम", "कोलकाता पोर्ट", "भवानीपुर", "रासबिहारी", "बल्लीगुंगे"},
            {"West Bengal", "Kolkata Uttar", "Chowrangee", "Entally", "Beleghata", "Jorasanko", "Shyampukur", "Maniktala", "Kashipur-Belgachhia"},
            {"पश्चिम बंगाल", "कोलकाता उत्तर", "चौविरंघी", "एंटली", "बेलियाघटा", "जोरांस्को", "श्यामपुकुर", "मणिकातला", "काशीपुर-बेलगछिआ"},
            {"West Bengal", "Krishnanagar", "Tehatta", "Palashipara", "Kaliganj", "Nakashipara", "Chapra", "Krishnanagar Uttar", "Nabadwip"},
            {"पश्चिम बंगाल", "कृष्णनगर", "तेहत्ता", "पलासीपारा", "कालीगंज", "नक्क्षीपारा", "छपरा", "कृष्णानगर उत्तर", "नवादीप"},
            {"West Bengal", "Maldaha Dakshin", "Manikchak", "English Bazar", "Mothabari", "Sujapur", "Baisnabnagar", "Farakka", "Samserganj"},
            {"पश्चिम बंगाल", "मालदा दक्षिण", "मानिकचक", "इंग्लिश बाजार", "मोठाबाडी", "सुजापुर", "वैष्णवनगर", "फरक्का", "समसेरगंज"},
            {"West Bengal", "Maldaha Uttar", "Habibpur", "Gazole", "Chanchal", "Harischandrapur", "Malatipur", "Ratua", "Maldaha"},
            {"पश्चिम बंगाल", "मालदा उत्तर", "हबीबपुर", "गजोल", "चंचल", "हरीशचंद्रपुर", "मालतीपुर", "रतुआ", "मालदा"},
            {"West Bengal", "Mathurapur", "Patharpratima", "Kakdwip", "Sagar", "Kulpi", "Raidighi", "Mandirbazar", "Magrahat Paschim"},
            {"पश्चिम बंगाल", "मथुरापुर", "पाथरप्रतिमा", "काकद्वीप", "सागर", "कुल्पी", "रायडीह", "मंदिर बाजार", "मगराहत पश्चिम"},
            {"West Bengal", "Medinipur", "Egra", "Dantan", "Keshiary", "Kharagpur Sadar", "Narayangarh", "Kharagpur", "Medinipur"},
            {"पश्चिम बंगाल", "मेदिनीपुर", "एगरा", "दांतन", "केशिआरी", "खड़गपुर सदर", "नारायणगढ़", "खड़गपुर", "मेदनीपुर"},
            {"West Bengal", "Murshidabad", "Bhagabangola", "Raninagar", "Murshidabad", "Hariharpara", "Domkal", "Jalangi", "Karimpur"},
            {"पश्चिम बंगाल", "मुर्शिदाबाद", "भगवानगोला", "रानीनगर", "मुर्शिदाबाद", "हरिहरपाड़ा", "दोमकल", "जलांगी", "करीमपुर"},
            {"West Bengal", "Purulia", "Balarampur", "Baghmundi", "Joypur", "Purulia", "Manbazar", "Kashipur", "Para"},
            {"पश्चिम बंगाल", "पुरुलिया", "बलरामपुर", "बघमुंडी", "जॉयपुर", "पुरुलिया", "मांबाज़ार", "काशीपुर", "पारा"},
            {"West Bengal", "Raiganj", "Islampur", "Goalpokhar", "Chakulia", "Karandighi", "Hemtabad", "Kaliaganj", "Raiganj"},
            {"पश्चिम बंगाल", "रायगंज", "इस्लामपुर", "गोपालपोखर", "चकुलिया", "करणदिघी", "हेमताबाद", "कालियागंज", "रायगंज"},
            {"West Bengal", "Ranaghat", "Krishnanagar Dakshin", "Santipur", "Ranaghat Uttar Paschim", "Krishnaganj", "Ranaghat Uttar Purba", "Ranaghat Dakshin", "Chakdaha"},
            {"पश्चिम बंगाल", "रानाघाट", "कृष्णानगर दक्षिण", "शांतिपुर", "रानाघाट उत्तर पश्चिम", "कृष्णगंज", "रानाघाट उत्तर पूर्व", "रानाघाट दक्षिण", "चकदाहा"},
            {"West Bengal", "Sreerampur", "Jagatballavpur", "Domjur", "Uttarpara", "Sreerampur", "Champdani", "Chanditala", "Jangipara"},
            {"पश्चिम बंगाल", "श्रीरामपुर", "जगतबल्लवपुर", "डोमजूर", "उत्तरपारा", "श्रीरामपुर", "चांपदानी", "चण्डीतला", "जंगीपाड़ा"},
            {"West Bengal", "Tamluk", "Tamluk", "Panskura Purba", "Moyna", "Nandakumar", "Mahisadal", "Haldia", "Nandigram"},
            {"पश्चिम बंगाल", "तामलुक", "तामलुक", "पंस्कुरा पूरबा", "मोयना", "नंदकुमार", "महिषादल", "हल्दिया", "नंदीग्राम"},
            {"West Bengal", "Uluberia", "Uluberia Purba", "Uluberia Uttar", "Uluberia Dakshin", "Shyampur", "Bagnan", "Amta", "Udaynarayanpur"},
            {"पश्चिम बंगाल", "उलूबेरिया", "उलुबेरिया पूर्व", "उलुबेरिया उत्तर", "उलुबेरिया दक्षिण", "श्यामपुर", "बगनान", "अमता", "उदयनारायणपुर"},
    };
}
