package in.filternet.jantamalik.Rajya;

public final class MP_2_MLA {

    public static final String[][] mapping = {

            {"Andhra Pradesh", "Amalapuram", "Ramachandrapuram", "Mummidivaram", "Amalapuram", "Razole", "Gannavaram", "Kothapeta", "Mandapeta"},
            {"आन्ध्र प्रदेश", "अमलापुरम", "रामचंद्रपुरम", "मुम्मिदिवरम", "अमलापुरम", "रज़ोल", "गन्नवरम", "कोथपेटा", "मंडपेटा"},
            {"Andhra Pradesh", "Anakapalle", "Chodavaram", "Madugula", "Anakapalle", "Pendurthi", "Yelamanchili", "Payakaraopet", "Narsipatnam"},
            {"आन्ध्र प्रदेश", "अनकापल्ली", "चोदावाराम", "मदुगुला", "अनकापल्ली", "पेंडुर्थी", "इलामनचिली", "पयाकरोपेट", "नरसीपट्टनम"},
            {"Andhra Pradesh", "Anantapur", "Rayadurg", "Uravakonda", "Guntakal", "Tadpatri", "Singanamala", "Anantapur Urban", "Kalyandurg"},
            {"आन्ध्र प्रदेश", "अनंतपुर", "रायदुर्ग", "उर्वकोंडा", "गुंतकल", "ताड़पत्री", "सिंगनमाला", "अनंतपुर शहर", "कल्याणदुर्ग"},
            {"Andhra Pradesh", "Araku", "Palakonda", "Kurupam", "Parvathipuram", "Salur", "Araku Valley", "Paderu", "Rampachodovaram"},
            {"आन्ध्र प्रदेश", "अरकू", "पालकोंडा", "कुरुपम", "पार्वतीपुरम", "सालुर", "अरकू घाटी", "पडरु", "रामपछोड़वराम"},
            {"Andhra Pradesh", "Bapatla", "Vemuru", "Repalle", "Bapatla", "Parchur", "Addanki", "Chirala", "Santhanuthalapadu"},
            {"आन्ध्र प्रदेश", "बापतला", "वेमुरू", "रेपल्ले", "बापतला", "परचूर", "अद्दन्की", "चिराला", "संथानुथलापादु"},
            {"Andhra Pradesh", "Chittoor", "Chandragiri", "Nagari", "Gangadhara Nellore", "Chittoor", "Puthalapattu", "Palamaner", "Kuppam"},
            {"आन्ध्र प्रदेश", "चित्तूर", "चंद्रगिरि", "नगरी", "गंगाधारा नेल्लोर", "चित्तूर", "पुथलपट्टू", "पल्मनेर", "Kuppam"},
            {"Andhra Pradesh", "Eluru", "Ungutur", "Denduluru", "Eluru", "Polavaram", "Chintalapudi", "Nuzvid", "Kaikalur"},
            {"आन्ध्र प्रदेश", "एलुरु", "उन्गुतुरु", "देनदुल्लुरु", "एलुरु", "पोलावरम", "चिंतालपुडी", "नुज्विद", "केकलुर"},
            {"Andhra Pradesh", "Guntur", "Tadikonda", "Mangalagiri", "Ponnur", "Tenali", "Prathipadu", "Guntur West", "Guntur East"},
            {"आन्ध्र प्रदेश", "गुंटूर", "ताड़ीकोंडा", "मंगलगिरी", "पोन्नूर", "तेनाली", "प्रथिपादु", "गुंटूर पश्चिम", "गुंटूर पूर्व"},
            {"Andhra Pradesh", "Hindupur", "Raptadu", "Madakasira", "Hindupur", "Penukonda", "Puttaparthi", "Dharmavaram", "Kadiri"},
            {"आन्ध्र प्रदेश", "हिन्दुपुर", "रपटदु", "मदाकासिरा", "हिन्दुपुर", "पेनुकोंडा", "पुट्टपर्थी", "धर्मावरम", "कादिरी"},
            {"Andhra Pradesh", "Kadapa", "Badvel", "Kadapa", "Pulivendla", "Kamalapuram", "Jammalamadugu", "Proddatur", "Mydukur"},
            {"आन्ध्र प्रदेश", "कडपा", "बडवेल", "कडपा", "पुलिवेंदला", "कमलापुरम", "जम्लदुगु", "प्रोद्दातुर", "मीदुकूर"},
            {"Andhra Pradesh", "Kakinada", "Tuni", "Prathipadu", "Pithapuram", "Kakinada Rural", "Peddapuram", "Kakinada City", "Jaggampeta"},
            {"आन्ध्र प्रदेश", "काकीनाडा", "तुनि", "प्रथिपाडू", "पीथापुरम", "काकीनाडा ग्रामीण", "पेद्दापुरम", "काकीनाडा शहर", "जग्गम्पेता"},
            {"Andhra Pradesh", "Kurnool", "Kurnool", "Pattikonda", "Kodumur", "Yemmiganur", "Mantralayam", "Adoni", "Alur"},
            {"आन्ध्र प्रदेश", "कुरनूल", "कुरनूल", "पट्टिकोण्डा", "कोडुमुर", "येम्मीगनूर", "मंत्रालयम", "अडोनी", "Alur"},
            {"Andhra Pradesh", "Machilipatnam", "Gannavaram", "Gudivada", "Pedana", "Machilipatnam", "Avanigadda", "Pamarru", "Penamaluru"},
            {"आन्ध्र प्रदेश", "मछलीपट्टनम", "गन्नवरम", "गुडिवाडा", "पेडाना", "मछलीपट्टनम", "अवनिगड्डा", "पमारू", "पेनमलुरु"},
            {"Andhra Pradesh", "Nandyal", "Allagadda", "Srisailam", "Nandikotkur", "Panyam", "Nandyal", "Banaganapalle", "Dhone"},
            {"आन्ध्र प्रदेश", "नांदयाल", "अल्लागड्डा", "श्रीशैलम", "नंदिकोटकुर", "पन्यम", "नांदयाल", "बनगनपल्ली", "धोने"},
            {"Andhra Pradesh", "Narasaraopet", "Pedakurapadu", "Chilakaluripet", "Narasaraopet", "Sattenapalle", "Vinukonda", "Gurajala", "Macherla"},
            {"आन्ध्र प्रदेश", "नरसरोपेट", "पेदाकुरापदु", "चिलकलुरिपेट", "नरसरोपेट", "सत्तेनापल्ली", "विनुकोंडा", "गुरजला", "मचेर्ला"},
            {"Andhra Pradesh", "Narsapuram", "Achanta", "Palacole", "Narsapuram", "Bhimavaram", "Undi", "Tanuku", "Tadepalligudem"},
            {"आन्ध्र प्रदेश", "नरसापुरम", "अचंता", "पालाकोल", "नरसापुरम", "भीमावरम", "उंडी", "टनुकु", "ताडेपल्लीगुडेम"},
            {"Andhra Pradesh", "Nellore", "Kandukur", "Kavali", "Atmakur", "Kovur", "Nellore City", "Nellore Rural", "Udayagiri"},
            {"आन्ध्र प्रदेश", "नेल्लोर", "कन्दुकुर", "कवाली", "आत्मकूर", "कोवूर", "नेल्लोर शहर", "नेल्लोर ग्रामीण", "उदयगिरि"},
            {"Andhra Pradesh", "Ongole", "Yerragondapalem", "Darsi", "Ongole", "Kondapi", "Markapuram", "Giddalur", "Kanigiri"},
            {"आन्ध्र प्रदेश", "ओंगोल", "येरगोंडापलम", "डार्सी", "ओंगोल", "कोंडापी", "मार्कापुरम", "गिद्दलूर", "कनिगिरी"},
            {"Andhra Pradesh", "Rajahmundry", "Anaparthy", "Rajanagaram", "Rajahmundry City", "Rajahmundry Rural", "Kovvur", "Nidadavole", "Gopalapuram"},
            {"आन्ध्र प्रदेश", "राजमुंदरी", "अनपर्थी", "राजनगरम", "राजमुंदरी शहर", "राजमुंदरी ग्रामीण", "कोव्वुर", "निदादावोल", "गोपालपुरम"},
            {"Andhra Pradesh", "Rajampet", "Rajampet", "Kodur", "Rayachoti", "Thamballapalle", "Pileru", "Madanapalle", "Punganur"},
            {"आन्ध्र प्रदेश", "राजमपेट", "राजमपेट", "कोदूर", "रायचोटि", "थांबलापल्ले", "पिलेरू", "मदनपल्ली", "पुंगनूर"},
            {"Andhra Pradesh", "Srikakulam", "Ichchapuram", "Palasa", "Tekkali", "Pathapatnam", "Srikakulam", "Amadalavalasa", "Narasannapeta"},
            {"आन्ध्र प्रदेश", "श्रीकाकुलम", "इच्चापुरम", "पलासा", "तेक्काली", "पथापत्राम", "श्रीकाकुलम", "अमुदलवलासा", "नारासंनापेता"},
            {"Andhra Pradesh", "Tirupati", "Sarvepalli", "Gudur", "Sullurpeta", "Venkatagiri", "Tirupati", "Srikalahasti", "Sathyavedu"},
            {"आन्ध्र प्रदेश", "तिरुपति", "सर्वेपल्ली", "गुदुर", "सुल्लुरपेटा", "वेंकटगिरि", "तिरुपति", "श्रीकालाहस्ती", "सत्यवेदु"},
            {"Andhra Pradesh", "Vijayawada", "Tiruvuru", "Vijayawada West", "Vijayawada Central", "Vijayawada East", "Mylavaram", "Nandigama", "Jaggayyapeta"},
            {"आन्ध्र प्रदेश", "विजयवाड़ा", "तिरुवुरु", "विजयवाड़ा पश्चिम", "विजयवाड़ा मध्य", "विजयवाड़ा पूर्व", "मायलावरम", "नंदीगामा", "जग्गय्यापेटा"},
            {"Andhra Pradesh", "Visakhapatnam", "Srungavarapukota", "Bhimli", "Visakhapatnam East", "Visakhapatnam South", "Visakhapatnam North", "Visakhapatnam West", "Gajuwaka"},
            {"आन्ध्र प्रदेश", "विशाखापत्तनम", "श्रींगवेरपुकोटा", "भीमली", "विशाखापत्तनम पूर्व", "विशाखापत्तनम दक्षिण", "विशाखापत्तनम उत्तर", "विशाखापत्तनम पश्चिम", "गजुवाका"},
            {"Andhra Pradesh", "Vizianagaram", "Etcherla", "Rajam", "Bobbili", "Chipurupalle", "Gajapathinagaram", "Nellimarla", "Vizianagaram"},
            {"आन्ध्र प्रदेश", "विजयनगरम", "एचेरला", "राजम", "बोबिली", "चीपुरुपल्ली", "गजपतिनगरम", "नेल्लिमार्ला", "विजयनगरम"},
            //Assam Parliamentary Constituencies wise list:- http://ceoassam.nic.in/Gen_Informations/2.2%20-%20PC-wise%20LAC%20breakup.pdf
            {"Assam", "Autonomous District", "Halflong", "Bokajan", "Howraghat", "Diphu", "Baithalangso"},
            {"असम", "स्वायत्त जिला", "हाफलोंग", "बोकाजन", "हावड़ाघाट", "दिफू", "बैथलंगसो"},
            {"Assam", "Barpeta", "Bongaigaon", "Abhayapuri North", "Abhayapuri South", "Patacharkuchi", "Barpeta", "Jania", "Baghbar", "Sarukhetri", "Chenga", "Dharmapur"},
            {"असम", "बारपेटा", "बोंगईगांव", "अभयपुरी उत्तर", "अभयपुरी दक्षिण", "पताचार्कुची", "बारपेटा", "जनिया", "बघबर", "सरुखेत्री", "चेंगा", "धरमपुर"},
            {"Assam", "Dhubri", "Mankachar", "Salmara South", "Dhubri", "Gauripur", "Golakganj", "Bilasipara West", "Bilasipara East", "Goalpara East", "Goalpara West", "Jaleswar"},
            {"असम", "धुबरी", "मनकचर", "सलमरा दक्षिण", "धुबरी", "गौरीपुर", "गोलकगंज", "बिलासीपारा पश्चिम", "बिलासीपारा पूर्व", "गोलपारा पूर्वी", "गोलपारा पश्चिम", "जलेश्वर"},
            {"Assam", "Dibrugarh", "Moran", "Dibrugarh", "Lahowal", "Duliajan", "Tingkhong", "Naharkatia", "Tinsukia", "Digboi", "Margherita"},
            {"असम", "डिब्रूगढ़", "मोरान", "डिब्रूगढ़", "लाहोवाल", "दुलियाजन", "टिंगखोंग", "नाहरकाटिया", "तिनसुकिया", "डिगबोई", "मार्गरेटा"},
            {"Assam", "Gauhati", "Dhudhnai", "Boko", "Chaygaon", "Palasbari", "Jalukbari", "Dispur", "Gauhati East", "Gauhati West", "Hajo", "Barkhetry"},
            {"असम", "गुवाहाटी", "दुध्नोई", "बोको", "छायगांव", "पलासबाड़ी", "जलुक्बरी", "दिसपुर", "गुवाहाटी पूर्व", "गुवाहाटी पश्चिम", "हाजो", "बर्खेत्री"},
            {"Assam", "Jorhat", "Jorhat", "Titabar", "Mariani", "Teok", "Amguri", "Nazira", "Mahmara", "Sonari", "Thowra", "Sibsagar"},
            {"असम", "जोरहाट", "जोरहाट", "तीताबार", "मरिआनी", "टीओक", "आमगुड़ी", "नाज़िरा", "महमोरा", "सोनारी", "थौरा", "सिबसागर"},
            {"Assam", "Kaliabor", "Dhing", "Batadroba", "Rupohihat", "Samaguri", "Kaliabor", "Bokakhat", "Sarupathar", "Golaghat", "Khumtai", "Dergaon"},
            {"असम", "कलियाबोर", "ढिंग", "बताद्रोबा", "रूपोहीहत", "सामगुरी", "कलियाबोर", "बोकाखाट", "सरूपाथर", "गोलाघाट", "खूंटै", "देरगांव"},
            {"Assam", "Karimganj", "Ratabari", "Patharkandi", "Karimganj North", "Karimganj South", "Badarpur", "Hailakandi", "Katlichera", "Algapur"},
            {"असम", "करीमगंज", "राताबरी", "पाथरकाण्डी", "करीमगंज उत्तर", "करीमगंज दक्षिण", "बदरपुर", "हैलाकांडी", "कतलीचेरा", "अल्गापुर"},
            {"Assam", "Kokrajhar", "Gossaigaon", "Kokrajhar West", "Kokrajhar East", "Sidli", "Bijni", "Sorbhog", "Bhabanipur", "Tamulpur", "Barama", "Chapaguri"},
            {"असम", "कोकराझार", "गोसाइगांव", "कोकराझार पश्चिम", "कोकराझार पूर्व", "सिडली", "बिजनी", "सोरभोग", "भवानीपुर", "तामूलपुर", "बारामा", "छापागुरी"},
            {"Assam", "Lakhimpur", "Majuli", "Naoboicha", "Lakhimpur", "Dhakuakhana", "Dhemaji", "Jonai", "Chabua", "Doom Dooma", "Sadiya"},
            {"असम", "लखीमपुर", "माजुली", "नाबोइचा", "लखीमपुर", "धाकुखाना", "धेमाजी", "जोनाई", "चबुआ", "दुम दुमा", "सादिया"},
            {"Assam", "Mangaldoi", "Kamalpur", "Rangiya", "Nalbari", "Panery", "Kalaigaon", "Sipajhar", "Mangaldoi", "Dalgaon", "Udalguri", "Majbat"},
            {"असम", "मंगलदोई", "कमलपुर", "रंगिआ", "नलबारी", "पानेरी", "कालाईगांव", "सिपाझार", "मंगलदोई", "डलगांव", "उदलगुड़ी", "मजबत"},
            {"Assam", "Nawgong", "Jagiroad", "Marigaon", "Laharighat", "Raha", "Nowgong", "Barhampur", "Jamunamukh", "Hojai", "Lumding"},
            {"असम", "नौगांव", "जागीरोड", "मारीगांव", "लहरीघाट", "राहा", "नौगांव", "बरहमपुर", "जमुनामुख", "होजाई", "लुमडिंग"},
            {"Assam", "Silchar", "Silchar", "Sonai", "Dholai", "Udharbond", "Lakhipur", "Barkhola", "Katigora"},
            {"असम", "सिलचर", "सिलचर", "सोनाई", "ढोलई", "उधारबोंड", "लखीपुर", "बोरखोला", "कटिगारा"},
            {"Assam", "Tezpur", "Dhekiajuli", "Barchalla", "Tezpur", "Rangapara", "Sootea", "Biswanath", "Behali", "Gohpur", "Bihpuria"},
            {"असम", "तेजपुर", "ढेकिआजुली", "बरछाला", "तेजपुर", "रांगापारा", "सूटिया", "बिश्वनाथ", "बेहाली", "गोहपुर", "बिहपुरिया"},
            {"Bihar", "Araria", "Narpatganj", "Raniganj", "Forbesganj", "Araria", "Jokhihat", "Sikti"},
            {"बिहार", "अररिया", "नरपतगंज", "रानीगंज", "फारबिसगंज", "अररिया", "जोकीहाट", "सिकटी"},
            {"Bihar", "Arrah", "Sandesh", "Barhara", "Arrah", "Agiaon", "Tarari", "Jagdishpur", "Shahpur"},
            {"बिहार", "आरा", "सन्देश", "बरहरा", "आरा", "अगिआव", "तराई", "जगदीशपुर", "शाहपुर"},
            {"Bihar", "Aurangabad", "Kutumba", "Aurangabad", "Rafiganj", "Gurua", "Imamganj", "Tikari"},
            {"बिहार", "औरंगाबाद बिहा", "कुटुम्बा", "औरंगाबाद", "रफ़ीगंज", "गुरुआ", "इमामगंज", "टिकारी"},
            {"Bihar", "Banka", "Sultanganj", "Amarpur", "Dhauraiya", "Banka", "Katoria", "Belhar"},
            {"बिहार", "बांका", "सुल्तानगंज", "अमरपुर", "धोरैया", "बांका", "कटोरिया", "बेलहार"},
            {"Bihar", "Begusarai", "Cheria Bariarpur", "Bachhwara", "Teghra", "Matihani", "Sahebpur Kamal", "Begusarai", "Bakhri"},
            {"बिहार", "बेगूसराय", "चेरिया बरिआरपुर", "बछवाड़ा", "तेघड़ा", "मटिहानी", "साहेबपुर कमल", "बेगूसराय", "बखरी"},
            {"Bihar", "Bhagalpur", "Bihpur", "Gopalpur", "Pirpainti", "Kahalgaon", "Bhagalpur", "Nathnagar"},
            {"बिहार", "भागलपुर", "बिहपुर", "गोपालपुर", "पीरपैंती", "कहलगांव", "भागलपुर", "नाथनगर"},
            {"Bihar", "Buxar", "Brahmpur", "Buxar", "Dumraon", "Rajpur", "Ramgarh", "Dinara"},
            {"बिहार", "बक्सर", "ब्रह्मपुर", "बक्सर", "डुमरांव", "राजपुर", "रामगढ़", "दिनारा"},
            {"Bihar", "Darbhanga", "Gaura Bauram", "Benipur", "Alinagar", "Darbhanga Rural", "Darbhanga", "Bahadurpur"},
            {"बिहार", "दरभंगा", "गौरा बौरम", "बेनीपुर", "अलीनगर", "दरभंगा ग्रामीण", "दरभंगा", "बहादुरपुर"},
            {"Bihar", "Gaya", "Sherghati", "Barachatti", "Bodh Gaya", "Gaya Town", "Belaganj", "Wazirganj"},
            {"बिहार", "गया", "शेरघाटी", "बाराचट्टी", "बोध गया", "गया टाउन", "बेलागंज", "वजीरगंज"},
            {"Bihar", "Gopalganj", "Baikunthpur", "Barauli", "Gopalganj", "Kuchaikot", "Bhorey", "Hathua"},
            {"बिहार", "गोपालगंज", "बैकुंठपुर", "बरौली", "गोपालगंज", "कुछाईकोटे", "भोरे", "हथुआ"},
            {"Bihar", "Hajipur", "Hajipur", "Lalganj", "Mahua", "Raja Pakar", "Raghopur", "Mahnar"},
            {"बिहार", "हाजीपुर", "हाजीपुर", "लालगंज", "महुआ", "राजा पाकर", "राघोपुर", "महनार"},
            {"Bihar", "Jahanabad", "Arwal", "Kurtha", "Jahanabad", "Ghosi", "Makhdumpur", "Atri"},
            {"बिहार", "जहानाबाद", "अरवल", "कुर्था", "जहानाबाद", "घोसी", "मखदूमपुर", "अतरी"},
            {"Bihar", "Jamui", "Tarapur", "Sheikhpura", "Sikandra", "Jamui", "Jhajha", "Chakai"},
            {"बिहार", "जमुई", "तारापुर", "शेखपुरा", "सिकंदरा", "जमुई", "झाझा", "चकई"},
            {"Bihar", "Jhanjharpur", "Khajauli", "Babubarhi", "Rajnagar", "Jhanjharpur", "Phulparas", "Laukaha"},
            {"बिहार", "झंझारपुर", "खजौली", "बाबूबरही", "राजनगर", "झंझारपुर", "फुलपरास", "लौकहा"},
            {"Bihar", "Karakat", "Nokha", "Dehri", "Karakat", "Goh", "Obra", "Nabinagar"},
            {"बिहार", "काराकाट", "नोखा", "डेहरी", "काराकाट", "गोह", "ओबरा", "नबीनगर"},
            {"Bihar", "Katihar", "Katihar", "Kadwa", "Balrampur", "Pranpur", "Manihari", "Barari"},
            {"बिहार", "कटिहार", "कटिहार", "कड़वा", "बलरामपुर", "प्राणपुर", "मनिहारी", "बरारी"},
            {"Bihar", "Khagaria", "Simri Bakhtiarpur", "Hasanpur", "Alauli", "Khagaria", "Beldaur", "Parbatta"},
            {"बिहार", "खगरिया", "सिमरी बख्तियारपुर", "हसनपुर", "अलौली", "खगरिया", "बेलदौर", "परबत्ता"},
            {"Bihar", "Kishanganj", "Bahadurganj", "Thakurganj", "Kishanganj", "Kochadhaman", "Amour", "Baisi"},
            {"बिहार", "किशनगंज", "बहादुरगंज", "ठाकुरगंज", "किशनगंज", "कोचाधामन", "अमौर", "बैसी"},
            {"Bihar", "Madhepura", "Alamnagar", "Bihariganj", "Madhepura", "Sonbarsha", "Saharsa", "Mahishi"},
            {"बिहार", "मधेपुरा", "आलमनगर", "बिहारीगंज", "मधेपुरा", "सोनबर्षा", "सहरसा", "Mahishi"},
            {"Bihar", "Madhubani", "Harlakhi", "Benipatti", "Bisfi", "Madhubani", "Keoti", "Jale"},
            {"बिहार", "मधुबनी", "हरलाखी", "बेनीपट्टी", "बिस्फी", "मधुबनी", "कवेटी", "Jale"},
            {"Bihar", "Maharajganj", "Goriyakothi", "Maharajganj", "Ekma", "Manjhi", "Baniapur", "Taraiya"},
            {"बिहार", "महाराजगंज", "गोरियाकोठी", "महाराजगंज", "एकमा", "मांझी", "बनियापुर", "तरैया"},
            {"Bihar", "Munger", "Munger", "Jamalpur", "Suryagarha", "Lakhisarai", "Mokama", "Barh"},
            {"बिहार", "मुंगेर", "मुंगेर", "जमालपुर", "सूर्यगढ़ा", "लखीसराय", "मोकामा", "बाढ़"},
            {"Bihar", "Muzaffarpur", "Gaighat", "Aurai", "Bochaha", "Sakra", "Kurhani", "Muzaffarpur"},
            {"बिहार", "मुजफ्फरपुर", "गायघाट", "औराई", "बोचहां", "सकरा", "Kurhani", "मुजफ्फरपुर"},
            {"Bihar", "Nalanda", "Asthawan", "Biharsharif", "Rajgir", "Islampur", "Hilsa", "Nalanda", "Harnaut"},
            {"बिहार", "नालंदा", "अस्थावां", "बिहारशरीफ़", "राजगीर", "इस्लामपुर", "हिलसा", "नालंदा", "हरनौत"},
            {"Bihar", "Nawada", "Barbigha", "Rajauli", "Hisua", "Nawada", "Gobindpur", "Warsaliganj"},
            {"बिहार", "नवादा", "बारबीघा", "रजौली", "हिसुआ", "नवादा", "गोबिंदपुर", "वारिसलीगंज"},
            {"Bihar", "Paschim Champaran", "Nautan", "Chanpatia", "Bettiah", "Raxaul", "Sugauli", "Narkatia"},
            {"बिहार", "पश्चिम चंपारण", "नौतन", "चनपटिया", "बेतिया", "रक्सौल", "सुगौली", "नरकटिया"},
            {"Bihar", "Pataliputra", "Danapur", "Maner", "Phulwari", "Masaurhi", "Paliganj", "Bikram"},
            {"बिहार", "पाटलिपुत्र", "दानापुर", "मनेर", "फुलवारी", "मसौढ़ी", "पालीगंज", "बिक्रम"},
            {"Bihar", "Patna Sahib", "Bakhtiarpur", "Digha", "Bankipur", "Kumhrar", "Patna Sahib", "Fatuha"},
            {"बिहार", "पटना साहिब", "बख्तियारपुर", "दीघा", "Bankipur", "कुम्हरार", "पटना साहिब", "फतुहा"},
            {"Bihar", "Purnia", "Kasba", "Banmankhi", "Rupauli", "Dhamdaha", "Purnia", "Korha"},
            {"बिहार", "पूर्णिया", "क़स्बा", "बनमखी", "रुपौली", "धमदाहा", "पूर्णिया", "कोढ़ा"},
            {"Bihar", "Purvi Champaran", "Harsidhi", "Govindganj", "Kesaria", "Kalyanpur", "Pipra (Purvi Champaran)", "Motihari"},
            {"बिहार", "पूर्वी चंपारण", "हरसिद्धि", "गोविंदगंज", "केसरिया", "कल्याणपुर", "पीपरा (पूर्वी चंपारण)", "मोतिहारी"},
            {"Bihar", "Samastipur", "Kusheshwar Asthan", "Hayaghat", "Kalyanpur", "Warisnagar", "Samastipur", "Rosera"},
            {"बिहार", "समस्तीपुर", "कुशेश्वर स्थान", "हायाघाट", "कल्याणपुर", "वारिसनगर", "समस्तीपुर", "रोसेरा"},
            {"Bihar", "Saran", "Marhaura", "Chapra", "Garkha", "Amnour", "Parsa", "Sonepur"},
            {"बिहार", "सारन", "मढौरा", "छपरा", "गरखा", "अमनौर", "परसा", "सोनपुर"},
            {"Bihar", "Sasaram", "Mohania", "Bhabua", "Chainpur", "Chenari", "Sasaram", "Kargahar"},
            {"बिहार", "सासाराम", "मोहानिया", "भाबुआ", "चैनपुर", "चेनारी", "सासाराम", "करगहर"},
            {"Bihar", "Sheohar", "Madhuban", "Chiraia", "Dhaka", "Sheohar", "Riga", "Belsand"},
            {"बिहार", "शिवहर", "मधुबन", "चिरईया", "ढाका", "शिवहर", "रीगा", "बेलसंद"},
            {"Bihar", "Sitamarhi", "Bathnaha", "Parihar", "Sursand", "Bajpatti", "Sitamarhi", "Runnisaidpur"},
            {"बिहार", "सीतामढ़ी", "बथनाहा", "परिहार", "सुरसंद", "बाजपट्टी", "सीतामढ़ी", "रूनी सैदपुर"},
            {"Bihar", "Siwan", "Siwan", "Ziradei", "Darauli", "Raghunathpur", "Daraundha", "Barharia"},
            {"बिहार", "सिवान", "सिवान", "जीरादेई", "दरौली", "रघुनाथपुर", "दरौंदा", "बरहरिया"},
            {"Bihar", "Supaul", "Nirmali", "Pipra (Supaul)", "Supaul", "Triveniganj", "Chhatapur", "Singheshwar"},
            {"बिहार", "सुपौल", "निर्मली", "पीपरा (सुपौल)", "सुपौल", "त्रिवेणीगंज", "छातापुर", "सिंगेश्वर"},
            {"Bihar", "Ujiarpur", "Patepur", "Ujiarpur", "Morwa", "Sarairanjan", "Mohiuddinnagar", "Bibhutipur"},
            {"बिहार", "उजियारपुर", "पातेपुर", "उजियारपुर", "मोरवा", "सरायरंजन", "मोहिउद्दीन नगर", "विभूतिपुर"},
            {"Bihar", "Vaishali", "Minapur", "Kanti", "Baruraj", "Paroo", "Sahebganj", "Vaishali"},
            {"बिहार", "वैशाली", "मीनापुर", "कान्ति", "बरुराज", "पारु", "साहेबगंज", "वैशाली"},
            {"Bihar", "Valmiki Nagar", "Valmiki Nagar", "Ramnagar", "Narkatiaganj", "Bagaha", "Lauriya", "Sikta"},
            {"बिहार", "वाल्मीकि नगर", "वाल्मीकि नगर", "रामनगर", "नरकटियागंज", "बगहा", "लौरिया", "सिकता"},
            {"Chhattisgarh", "Bastar", "Kondagaon", "Narayanpur", "Bastar", "Jagdalpur", "Chitrakot", "Dantewada", "Bijapur", "Konta"},
            {"छत्तीसगढ़", "बस्तर", "कोंडागांव", "नारायणपुर", "बस्तर", "जगदलपुर", "चित्रकूट", "दंतेवाड़ा", "बीजापुर", "कोंटा"},
            {"Chhattisgarh", "Bilaspur", "Kota", "Lormi", "Mungeli", "Takhatpur", "Bilha", "Bilaspur", "Beltara", "Masturi"},
            {"छत्तीसगढ़", "बिलासपुर", "कोटा", "लोरमी", "मुंगेली", "तखतपुर", "बिल्हा", "बिलासपुर", "बेलतेरा", "मस्तूरी"},
            {"Chhattisgarh", "Durg", "Patan", "Durg Rural", "Durg City", "Bhilai Nagar", "Vaishali Nagar", "Ahiwara", "Saja", "Bemetara", "Nawagarh"},
            {"छत्तीसगढ़", "दुर्ग", "पाटन", "दुर्ग ग्रामीण", "दुर्ग सिटी", "भिलाई नगर", "वैशाली नगर", "अहिवारा", "सजा", "बेमेतरा", "नवागढ़"},
            {"Chhattisgarh", "Janjgir Champa", "Akaltara", "Janjgir-Champa", "Sakti", "Chandrapur", "Jaijaipur", "Pamgarh", "Bilaigarh", "Kasdol"},
            {"छत्तीसगढ़", "जांजगीर-चम्पा", "अकलतरा", "जांजगीर-चम्पा", "शक्ति", "चंद्रपुर", "जैजैपुर", "पामगढ़", "बिलैगढ़", "कसडोल"},
            {"Chhattisgarh", "Kanker", "Sihawa", "Sanjari Balod", "Dondi Lohara", "Gunderdehi", "Antagarh", "Bhanupratappur", "Kanker", "Keshkal"},
            {"छत्तीसगढ़", "कांकेर", "सिहावा", "संजारी बालोद", "डोंडी लोहारा", "गुंडरदेही", "अंतागढ़", "भानुप्रतापपुर", "कांकेर", "केशकाल"},
            {"Chhattisgarh", "Korba", "Bharatpur-Sonhat", "Manendragarh", "Baikunthpur", "Rampur", "Korba", "Katghora", "Pali-Tanakhar", "Marwahi"},
            {"छत्तीसगढ़", "कोरबा", "भरतपुर-सोनहत", "मनेन्द्रगढ़", "बैकुंठपुर", "रामपुर", "कोरबा", "कटघोरा", "पाली-तनखार", "मरवाही"},
            {"Chhattisgarh", "Mahasamund", "Saraipali", "Basna", "Khallari", "Mahasamund", "Rajim", "Bindranawagarh", "Kurud", "Dhamtari"},
            {"छत्तीसगढ़", "महासमुंद", "सरायपाली", "बसना", "खल्लारी", "महासमुंद", "राजिम", "बिन्द्रानवागढ़", "कुरुद", "धमतरी"},
            {"Chhattisgarh", "Raigarh", "Jashpur", "Kunkuri", "Pathalgaon", "Lailunga", "Raigarh", "Sarangarh", "Kharsia", "Dharamjaigarh"},
            {"छत्तीसगढ़", "रायगढ़", "जशपुर", "कुनकुरी", "पत्थलगांव", "लैलूंगा", "रायगढ़", "सारनगढ़", "खरसिया", "धरमजयगढ़"},
            {"Chhattisgarh", "Raipur", "Baloda Bazar", "Bhatapara", "Dharsiwa", "Raipur Rural", "Raipur City West", "Raipur City North", "Raipur City South", "Arang", "Abhanpur"},
            {"छत्तीसगढ़", "रायपुर", "बलौदा बाजार", "भाटापारा", "धरसीवा", "रायपुर ग्रामीण", "रायपुर शहर पश्चिम", "रायपुर शहर उत्तर", "रायपुर शहर दक्षिण", "आरंग", "अभनपुर"},
            {"Chhattisgarh", "Rajnandgaon", "Pandariya", "Kawardha", "Khairagarh", "Dongargarh", "Rajnandgaon", "Dongargaon", "Khujji", "Mohla-Manpur"},
            {"छत्तीसगढ़", "राजनंदगांव", "पंडरिया", "कवर्धा", "खैरागढ़", "डोंगरगढ़", "राजनंदगांव", "डोंगरगांव", "खुज्जी", "मोहला-मानपुर"},
            {"Chhattisgarh", "Surguja", "Premnagar", "Bhatgaon", "Pratappur", "Ramanujganj", "Samri", "Lundra", "Ambikapur", "Sitapur"},
            {"छत्तीसगढ़", "सरगुजा", "प्रेमनगर", "भटगांव", "प्रतापपुर", "रमानुगंज", "समरी", "लुंड्रा", "अंबिकापुर", "सीतापुर"},
            {"Goa", "North Goa", "Mandrem", "Pernem", "Bicholim", "Tivim", "Mapusa", "Siolim", "Saligao", "Calangute", "Porvorim", "Aldona", "Panaji", "Taleigao", "St. Cruz", "St. Andre", "Cumbarjua", "Maem", "Sanquelim", "Poriem", "Valpoi", "Priol"},
            {"गोवा", "उत्तरी गोवा", "मांड्रेम", "पेरनेम", "बिचोलिम", "तिविम", "मापुसा", "सोइलिम", "सलिगो", "कलंगूट", "पोरवोरिम", "अलडोना", "पणजी", "तालेइगाओ", "सांताक्रूज़", "सेंट. आंद्रे", "कम्बर्जुआ", "मायेम", "संकेलिम", "पोरईएम", "वालपोई", "परिओल"},
            {"Goa", "South Goa", "Ponda", "Siroda", "Marcaim", "Mormugao", "Vasco-Da-Gama", "Dabolim", "Cortalim", "Nuvem", "Curtorim", "Fatorda", "Margao", "Benaulim", "Navelim", "Cuncolim", "Velim", "Quepem", "Curchorem", "Sanvordem", "Sanguem", "Canacona"},
            {"गोवा", "दक्षिण गोवा", "पोंडा", "सिरोडा", "मरकैम", "मरमुगाओ", "वास्को-डि-गामा", "डाबोलिम", "कोर्टालिम", "नवम", "करतोरिम", "फतरोडा", "मरगांव", "बेनाउलिम", "नवेलिम", "कन्सोलिम", "वेलिम", "क्वेपम", "करचोरेम", "संवरडेम", "संगुएम", "कनाकोना"},
            {"Haryana", "Ambala", "Kalka", "Panchkula", "Naraingarh", "Ambala Cantt.", "Ambala City", "Mulana", "Sadhaura", "Jagadhri", "Yamunanagar"},
            {"हरियाणा", "अंबाला", "कालका", "पंचकूला", "नारायणगढ़", "अंबाला कैंट.", "अंबाला सिटी", "मुलाना", "सढ़ौरा", "जगाधरी", "यमुनानगर"},
            {"Haryana", "Bhiwani Mahendragarh", "Loharu", "Badhra", "Dadri", "Bhiwani", "Tosham", "Ateli", "Mahendragarh", "Narnaul", "Nangal Chaudhry"},
            {"हरियाणा", "भिवानी-महेंद्रगढ़", "लोहारू", "बधरा", "दादरी", "भिवानी", "तोशाम", "अटेली", "महेंद्रगढ़", "नारनौल", "नांगल चौधरी"},
            {"Haryana", "Faridabad", "Hathin", "Hodal", "Palwal", "Prithla", "Faridabad NIT", "Badkhal", "Ballabhgarh", "Faridabad", "Tigaon"},
            {"हरियाणा", "फरीदाबाद", "हथीन", "होडल", "पलवल", "पृथला", "फरीदाबाद एनआईटी", "बडखल", "बल्लभगढ़", "फरीदाबाद", "तिगांव"},
            {"Haryana", "Gurgaon", "Bawal", "Rewari", "Pataudi", "Badshahpur", "Gurgaon", "Sohna", "Nuh", "Ferozepur Jhirka", "Punahana"},
            {"हरियाणा", "गुडगाँव", "बावल", "रेवाड़ी", "पटौदी", "बादशाहपुर", "गुडगाँव", "सोहना", "नूह", "फिरोजपुर झिरका", "Punahana"},
            {"Haryana", "Hisar", "Uchana Kalan", "Adampur", "Uklana", "Narnaund", "Hansi", "Barwala", "Hisar", "Nalwa", "Bawani Khera"},
            {"हरियाणा", "हिसार", "उचाना कलां", "आदमपुर", "उकलाना", "नारनौंद", "हांसी", "बरवाला", "हिसार", "नलवा", "बवानी खेड़ा"},
            {"Haryana", "Karnal", "Nilokheri", "Indri", "Karnal", "Gharaunda", "Assandh", "Panipat Rural", "Panipat City", "Israna", "Samalkha"},
            {"हरियाणा", "करनाल", "नीलोखेड़ी", "इंद्री", "करनाल", "घरौंदा", "असंध", "पानीपत ग्रामीण", "पानीपत सिटी", "इसराना", "समालखा"},
            {"Haryana", "Kurukshetra", "Radaur", "Ladwa", "Shahbad", "Thanesar", "Pehowa", "Guhla", "Kalayat", "Kaithal", "Pundri"},
            {"हरियाणा", "कुरुक्षेत्र", "रादौर", "लाडवा", "शाहाबाद", "थानेसर", "पिहोवा", "गुहला", "कलायत", "कैथल", "पुंडरी"},
            {"Haryana", "Rohtak", "Meham", "Garhi Sampla-Kiloi", "Rohtak", "Kalanaur", "Bahadurgarh", "Badli", "Jhajjar", "Beri", "Kosli"},
            {"हरियाणा", "रोहतक", "मेहम", "गढ़ी सांपला-किलोई", "रोहतक", "कलानौर", "बहादुरगढ़", "बादली", "झज्जर", "बेरी", "कोसली"},
            {"Haryana", "Sirsa", "Narwana", "Tohana", "Fatehabad", "Ratia", "Kalanwali", "Dabwali", "Rania", "Sirsa", "Ellenabad"},
            {"हरियाणा", "सिरसा", "नरवाना", "टोहाना", "फतेहाबाद", "रतिया", "कालांवाली", "डबवाली", "रणिया", "सिरसा", "ऐलनाबाद"},
            {"Haryana", "Sonipat", "Ganaur", "Rai", "Kharkhauda", "Sonipat", "Gohana", "Baroda", "Julana", "Safidon", "Jind"},
            {"हरियाणा", "सोनीपत", "गनौर", "राई", "खरखौदा", "सोनीपत", "गोहाना", "बड़ौदा", "जुलाना", "सफीदों", "जींद"},
            //Jharkhand Parliamentary Constituencies wise list:- http://164.100.150.3/ceoweb_bk/ACPCList.htm
            {"Jharkhand", "Chatra", "Panki", "Latehar", "Simaria", "Chatra", "Manika"},
            {"झारखण्ड", "चतरा", "पांकी", "लातेहार", "सिमरिया", "चतरा", "मनिका"},
            {"Jharkhand", "Dhanbad", "Bokaro", "Chandankyari", "Dhanbad", "Sindri", "Jharia", "Nirsa"},
            {"झारखण्ड", "धनबाद", "बोकारो", "चन्दनकियारी", "धनबाद", "सिन्दरी", "झरिया", "निरसा"},
            {"Jharkhand", "Dumka", "Jama", "Dumka", "Sarath", "Shikaripara", "Nala", "Jamtara"},
            {"झारखण्ड", "दुमका", "जामा", "दुमका", "सारठ", "शिकारीपाड़ा", "नाला", "जामताड़ा"},
            {"Jharkhand", "Giridih", "Dumri", "Giridih", "Gomia", "Bermo", "Tundi", "Baghmara"},
            {"झारखण्ड", "गिरिडीह", "डुमरी", "गिरिडीह", "गोमिया", "बेरमो", "टुन्डी", "बाघमारा"},
            {"Jharkhand", "Godda", "Godda", "Jarmundi", "Madhupur", "Deoghar", "Poraiyahat", "Mahagama"},
            {"झारखण्ड", "गोड्डा", "गोड्डा", "जरमुण्डी", "मधुपुर", "देवगढ़", "पोड़ैयाहाट", "महगामा"},
            {"Jharkhand", "Hazaribagh", "Barhi", "Barkagaon", "Hazaribagh", "Ramgarh", "Mandu"},
            {"झारखण्ड", "हजारीबाग", "बरही", "बड़कागांव", "हजारीबाग", "रामगढ़", "मांडू"},
            {"Jharkhand", "Jamshedpur", "Jugsalai", "Jamshedpur East", "Jamshedpur West", "Ghatshila", "Potka", "Baharagora"},
            {"झारखण्ड", "जमशेदपुर", "जुगसलाई", "जमशेदपुर पूर्व", "जमशेदपुर पश्चिम", "घाटशिला", "पोटका", "बहरागोड़ा"},
            {"Jharkhand", "Khunti", "Simdega", "Tamar", "Khunti", "Torpa", "Kharsawan", "Kolebira"},
            {"झारखण्ड", "खूंटी", "सिमडेगा", "तमाड़", "खूंटी", "तोरपा", "खरसावां", "कोलेबीरा"},
            {"Jharkhand", "Kodarma", "Kodarma", "Barkatha", "Dhanwar", "Bagodar", "Jamua", "Gandey"},
            {"झारखण्ड", "कोडरमा", "कोडरमा", "बरकट्ठा", "धनवार", "बगोदर", "जमुआ", "गाण्डेय"},
            {"Jharkhand", "Lohardaga", "Lohardaga", "Sisai", "Gumla", "Mandar", "Bishunpur"},
            {"झारखण्ड", "लोहरदगा", "लोहरदगा", "सिसई", "गुमला", "मांडर", "बिशुनपुर"},
            {"Jharkhand", "Palamu", "Bhawnathpur", "Bishrampur", "Garhwa", "Daltonganj", "Hussainabad", "Chhatarpur"},
            {"झारखण्ड", "पलामू", "भवनाथपुर", "बिश्रामपुर", "गढ़वा", "डाल्टनगंज", "हुसैनाबाद", "छतरपुर"},
            {"Jharkhand", "Rajmahal", "Rajmahal", "Borio", "Barhait", "Litipara", "Pakur", "Maheshpur"},
            {"झारखण्ड", "राजमहल", "राजमहल", "बोरियो", "बरहेट", "लिट्टीपाड़ा", "पाकुड़", "महेशपुर"},
            {"Jharkhand", "Ranchi", "Ichagarh", "Silli", "Khijri", "Ranchi", "Hatia", "Kanke"},
            {"झारखण्ड", "रांची", "ईचागढ़", "सिल्ली", "खिजरी", "रांची", "हटिया", "कांके"},
            {"Jharkhand", "Singhbhum", "Majhgaon", "Jagannathpur", "Chaibasa", "Chakradharpur", "Seraikela", "Manoharpur"},
            {"झारखण्ड", "सिंहभूम", "मझगांव", "जगन्नाथपुर", "चाईबासा", "चक्रधरपुर", "सरायकेला", "मनोहरपुर"},
            {"Karnataka", "Bagalkot", "Mudhol", "Terdal", "Jamkhandi", "Bilgi", "Badami", "Bagalkot", "Hungund", "Nargund"},
            {"कर्नाटक", "बागलकोट", "मुधोल", "टेरडाल", "जामखंडी", "बिलगी", "बादामी", "बागलकोट", "हुंगुंड", "नरगुंड"},
            {"Karnataka", "Bangalore Central", "Sarvagnanagar", "C.V. Raman Nagar", "Shivajinagar", "Shanti Nagar", "Gandhi Nagar", "Rajaji Nagar", "Chamrajpet", "Mahadevapura"},
            {"कर्नाटक", "बैंगलोर सेंट्रल", "सर्वज्ञनगर", "सी.वी. रमन नगर", "शिवाजीनगर", "शांति नगर", "गांधी नगर", "राजाजी नगर", "चामराजपेट", "महादेवपुरा"},
            {"Karnataka", "Bangalore North", "K.R.Pura", "Byatarayanapura", "Yeshvanthapura", "Dasarahalli", "Mahalakshmi Layout", "Malleshwaram", "Hebbal", "Pulakeshinagar"},
            {"कर्नाटक", "बैंगलोर उत्तर", "के. आर. पुरा", "ब्यातारायणपुरा", "यशवंतपुरा", "दसराहल्ली", "महालक्ष्मी लेआउट", "मल्लेश्वरम", "हेबल", "पुलकेशीनगर"},
            {"Karnataka", "Bangalore Rural", "Kunigal", "Rajarajeshwari Nagar", "Bangalore South", "Anekal", "Magadi", "Ramanagaram", "Kanakapura", "Channapatna"},
            {"कर्नाटक", "बैंगलोर ग्रामीण", "कुनिगल", "राजराजेश्वरी नगर", "बंगलौर दक्षिण", "अनेकल", "मगदी", "रामनगर", "कनकपुरा", "चन्नापटना"},
            {"Karnataka", "Bangalore South", "Govindraj Nagar", "Vijay Nagar", "Chickpet", "Basavanagudi", "Padmanaba Nagar", "B.T.M. Layout", "Jayanagar", "Bommanahalli"},
            {"कर्नाटक", "बैंगलोर दक्षिण", "गोविंदराज नगर", "विजय नगर", "चिकपेट", "बसवनगुड़ी", "पद्मनाभ नगर", "बी.टी.एम. लेआउट", "जयनगर", "बोम्मनहल्ली"},
            {"Karnataka", "Belgaum", "Arabhavi", "Gokak", "Belgaum Uttar", "Belgaum Dakshin", "Belgaum Rural", "Bailhongal", "Saundatti Yellamma", "Ramdurg"},
            {"कर्नाटक", "बेलगाम", "अराभवी", "गोकाक", "बेलगाम उत्तर", "बेलगाम दक्षिण", "बेलगाम ग्रामीण", "बैलहोंगल", "सौंदत्ती येल्लम्मा", "रामदुर्ग"},
            {"Karnataka", "Bellary", "Hadagalli", "Hagaribommanahalli", "Vijayanagara", "Kampli", "Bellary", "Bellary City", "Sandur", "Kudligi"},
            {"कर्नाटक", "बेल्लारी", "हड़गल्ली", "हगरीबोम्मनहल्ली", "विजयनगर", "काम्पली", "बेल्लारी", "बेल्लारी शहर", "संदुर", "कुदलिगी"},
            {"Karnataka", "Bidar", "Chincholi", "Aland", "Basavakalyan", "Humnabad", "Bidar South", "Bidar", "Bhalki", "Aurad"},
            {"कर्नाटक", "बीदर", "चिंचोली", "अलंद", "बसवकल्याण", "हुमनाबाद", "बीदर दक्षिण", "बीदर", "भालकी", "औरद"},
            {"Karnataka", "Bijapur", "Muddebihal", "Devar Hippargi", "Basavana Bagevadi", "Babaleshwar", "Bijapur City", "Nagthan", "Indi", "Sindgi"},
            {"कर्नाटक", "बीजापुर", "मुद्देबिहाल", "देवर हिप्पर्गी", "बसवना बागेवाड़ी", "बबलेश्वर", "बीजापुर सिटी", "नागथन", "इंदी", "सिंदगी"},
            {"Karnataka", "Chamarajanagar", "Heggadadevankote", "Nanjangud", "Varuna", "T.Narasipur", "Hanur", "Kollegal", "Chamarajanagar", "Gundlupet"},
            {"कर्नाटक", "चामराजनगर", "हेग्गड़ादेवनकोट", "नंजनगुड", "वरुणा", "टी. नरसीपुर", "हनूर", "कोल्लेगल", "चामराजनगर", "गुंडलूपेट"},
            {"Karnataka", "Chikkballapur", "Gauribidanur", "Bagepalli", "Chikkballapur", "Yelahanka", "Hosakote", "Devanahalli", "Doddaballapur", "Nelamangala"},
            {"कर्नाटक", "चिकबल्लपुर", "गौरीबिदनूर", "बागेपल्ली", "चिकबल्लपुर", "येलाहांका", "होसकोटे", "देवनहल्ली", "डोड्डाबल्लापुर", "नेलामंगला"},
            {"Karnataka", "Chikkodi", "Nippani", "Chikkodi-Sadalga", "Athni", "Kagawad", "Kudachi", "Raybag", "Hukeri", "Yemkanmardi"},
            {"कर्नाटक", "चिक्कोडी", "निप्पानी", "चिक्कोडी-सदालगा", "अथनी", "कागवाड़", "कुडाची", "रायबाग", "हुकेरी", "यमकनमर्दी"},
            {"Karnataka", "Chitradurga", "Molakalmuru", "Challakere", "Chitradurga", "Hiriyur", "Hosadurga", "Holalkere", "Sira", "Pavagada"},
            {"कर्नाटक", "चित्रदुर्ग", "मोलाकलमुरू", "चल्लाकेर", "चित्रदुर्ग", "हिरियूर", "होसदुर्गा", "होल्केर", "सिरा", "पवागड़ा"},
            {"Karnataka", "Dakshina Kannada", "Belthangady", "Moodabidri", "Mangalore City North", "Mangalore City South", "Mangalore", "Bantval", "Puttur", "Sullia"},
            {"कर्नाटक", "दक्षिण कन्नड़", "बेल्थांगड़ी", "मूड़ाबिदरी", "मैंगलोर सिटी नॉर्थ", "मैंगलोर सिटी साउथ", "मैंगलोर", "बंतवाल", "Puttur", "सुलिया"},
            {"Karnataka", "Davanagere", "Jagalur", "Harapanahalli", "Harihar", "Davanagere North", "Davanagere South", "Mayakonda", "Channagiri", "Honnali"},
            {"कर्नाटक", "दावनगेरे", "जगलुर", "हरपनहल्ली", "Harihar", "दावनगेरे उत्तर", "दावनगेरे दक्षिण", "मायाकोंडा", "चन्नागिरि", "होनाली"},
            {"Karnataka", "Dharwad", "Navalgund", "Kundgol", "Dharwad", "Hubli-Dharwad-East", "Hubli-Dharwad-Central", "Hubli-Dharwad-West", "Kalghatgi", "Shiggaon"},
            {"कर्नाटक", "धारवाड़", "नवलगुंड", "कुंडगोल", "धारवाड़", "हुबली-धारवाड़-पूर्व", "हुबली-धारवाड़-मध्य", "हुबली-धारवाड़-पश्चिम", "कालघटगी", "शिग्गांव"},
            {"Karnataka", "Gulbarga", "Afzalpur", "Jevargi", "Gurmitkal", "Chittapur", "Sedam", "Gulbarga Rural", "Gulbarga Dakshin", "Gulbarga Uttar"},
            {"कर्नाटक", "गुलबर्गा", "अफजलपुर", "जेवरगी", "Gurmitkal", "चित्तापुर", "सेदम", "गुलबर्गा ग्रामीण", "गुलबर्गा दक्षिण", "गुलबर्गा उत्तर"},
            {"Karnataka", "Hassan", "Kadur", "Shravanabelagola", "Arsikere", "Belur", "Hassan", "Holenarasipur", "Arkalgud", "Sakleshpur"},
            {"कर्नाटक", "हसन", "कदूर", "श्रवणबेलगोला", "अरसीकेर", "बेलूर", "हसन", "होलनरसीपुर", "अरकलगुड", "सकलेशपुर"},
            {"Karnataka", "Haveri", "Shirahatti", "Gadag", "Ron", "Hangal", "Haveri", "Byadgi", "Hirekerur", "Ranibennur"},
            {"कर्नाटक", "हावेरी", "शीराहट्टी", "गदग", "रॉन", "हंगल", "हावेरी", "ब्यादगी", "हिरेकेरूर", "रानीबेन्नूर"},
            {"Karnataka", "Kolar", "Sidlaghatta", "Chintamani", "Srinivaspur", "Mulbagal", "Kolar Gold Field", "Bangarapet", "Kolar", "Malur"},
            {"कर्नाटक", "कोलार", "सिलदाघाट", "चिंतामणि", "श्रीनिवासपुर", "मूलबगल", "कोलार गोल्ड फ़ील्ड्", "बंगरपेट", "कोलार", "मलूर"},
            {"Karnataka", "Koppal", "Sindhanur", "Maski", "Kushtagi", "Kanakagiri", "Gangawati", "Yelburga", "Koppal", "Siruguppa"},
            {"कर्नाटक", "कोप्पल", "सिंधनूर", "मस्की", "कुश्तगी", "कनकगिरी", "गंगावती", "येलबुर्गा", "कोप्पल", "सिरुगुप्पा"},
            {"Karnataka", "Mandya", "Malavalli", "Maddur", "Melukote", "Mandya", "Shrirangapattana", "Nagamangala", "Krishnarajpet", "Krishnarajanagara"},
            {"कर्नाटक", "मंड्या", "मलवल्ली", "मद्दूर", "मेलूकोट", "मंड्या", "श्रीरंगपटना", "नागमंगला", "कृष्णराजपेट", "कृष्णराजनगर"},
            {"Karnataka", "Mysore", "Madikeri", "Virajpet", "Piriyapatna", "Hunsur", "Chamundeshwari", "Krishnaraja", "Chamaraja", "Narasimharaja"},
            {"कर्नाटक", "मैसूर", "मदिकेरी", "विराजपेट", "पिरियापटना", "हुनसुर", "चामुंडेश्वरी", "कृष्णराज", "चामराज", "नरसिम्हराज"},
            {"Karnataka", "Raichur", "Shorapur", "Shahpur", "Yadgir", "Raichur Rural", "Raichur", "Manvi", "Devadurga", "Lingsugur"},
            {"कर्नाटक", "रायचूर", "शोरापुर", "शाहपुर", "यादगीर", "रायचूर ग्रामीण", "रायचूर", "मानवी", "देवदुर्ग", "लिंगसुगुर"},
            {"Karnataka", "Shimoga", "Shimoga Rural", "Bhadravati", "Shimoga", "Tirthahalli", "Shikaripura", "Sorab", "Sagar", "Byndoor"},
            {"कर्नाटक", "शिमोगा", "शिमोगा ग्रामीण", "भद्रावती", "शिमोगा", "तीर्थहल्ली", "शिकारीपुरा", "सोराब", "सागर", "बिंदूर"},
            {"Karnataka", "Tumkur", "Chiknayakanhalli", "Tiptur", "Turuvekere", "Tumkur City", "Tumkur Rural", "Koratagere", "Gubbi", "Madhugiri"},
            {"कर्नाटक", "तुमकुर", "चिक्कनायकनहल्ली", "टिप्तुर", "तुरुवेकेर", "तुमकुर सिटी", "तुमकुर ग्रामीण", "कोराटगेर", "गुब्बी", "मधुगिरि"},
            {"Karnataka", "Udupi Chikmagalur", "Kundapura", "Udupi", "Kapu", "Karkal", "Sringeri", "Mudigere", "Chikmagalur", "Tarikere"},
            {"कर्नाटक", "उडुपी चिकमगलूर", "कुंडापुरा", "उडुपि", "कापू", "करकल", "शृंगेरी", "मुदिगेर", "चिकमगलूर", "Tarikere"},
            {"Karnataka", "Uttara Kannada", "Khanapur", "Kittur", "Haliyal", "Karwar", "Kumta", "Bhatkal", "Sirsi", "Yellapur"},
            {"कर्नाटक", "उत्तर कन्नड़", "खानापुर", "कित्तूर", "हलियाल", "करवार", "कुमटा", "भटकल", "सिरसी", "येल्लापुर"},
            {"Kerala", "Alappuzha", "Aroor", "Cherthala", "Alappuzha", "Ambalappuzha", "Haripad", "Kayamkulam", "Karunagappally"},
            {"केरल", "अलाप्पुझा", "अरूर", "चेरथला", "अलप्पुझा", "अम्बालापुझा", "हरिपद", "कायमकुलम", "करुनागाप्पली"},
            {"Kerala", "Alathur", "Tarur", "Chittur", "Nenmara", "Alathur", "Chelakkara", "Kunnamkulam", "Wadakkanchery"},
            {"केरल", "अलथुर", "थरूर", "चित्तूर", "नेनमारा", "अलथुर", "चेल्लकारा", "कुन्नमकुलम", "वडक्कान्चेरी"},
            {"Kerala", "Attingal", "Varkala", "Attingal", "Chirayinkeezhu", "Nedumangad", "Vamanapuram", "Aruvikkara", "Kattakkada"},
            {"केरल", "अत्तिन्गल", "वर्कला", "अत्तिन्गल", "चिरयिनकीजहु", "नेदुमंगड़", "वमनपुरम", "अरुविक्कारा", "कात्तक्कड़"},
            {"Kerala", "Chalakudy", "Kaipamangalam", "Chalakudy", "Kodungallur", "Perumbavoor", "Angamaly", "Aluva", "Kunnathunad"},
            {"केरल", "चलाकुडी", "कइपमंगलम", "चलाकुडी", "कोडुन्गल्लुर", "पेरुम्बवूर", "अंगमाल्य", "अलुवा", "कुणथुनाद"},
            {"Kerala", "Ernakulam", "Kalamassery", "Paravur", "Vypeen", "Kochi", "Tripunithura", "Ernakulam", "Thrikkakara"},
            {"केरल", "एर्नाकुलम", "कलमस्सरी", "पारावुर", "वाइपिन", "कोच्चि", "त्रिपुणितुरा", "एर्नाकुलम", "त्रिक्ककारा"},
            {"Kerala", "Idukki", "Muvattupuzha", "Kothamangalam", "Devikulam", "Udumbanchola", "Thodupuzha", "Idukki", "Peerumade"},
            {"केरल", "इडुक्की", "मुवत्तुपुषा", "कोठमंगलम", "देवीकुलम", "उदूम्बंचोला", "थोडुपुझा", "इडुक्की", "पीरमदे"},
            {"Kerala", "Kannur", "Taliparamba", "Irikkur", "Azhikode", "Kannur", "Dharmadam", "Mattannur", "Peravoor"},
            {"केरल", "कन्नूर", "तालीपरम्बा", "इरिक्कुर", "अझिकोड", "कन्नूर", "धर्मदम", "मत्तनूर", "पेरावूर"},
            {"Kerala", "Kasaragod", "Manjeshwar", "Kasaragod", "Udma", "Kanhangad", "Trikaripur", "Payyannur", "Kalliasseri"},
            {"केरल", "कासरगोड", "मंजेश्वर", "कासरगोड", "उदमा", "कान्हागढ़", "त्रिकरपुर", "पय्यन्नूर", "कालियासीरी"},
            {"Kerala", "Kollam", "Chavara", "Punalur", "Chadayamangalam", "Kundara", "Kollam", "Eravipuram", "Chathannoor"},
            {"केरल", "कोल्लम", "चावरा", "पुनलुर", "चदयमंगलम", "कुंदरा", "कोल्लम", "एरविपुरम", "चथन्नूर"},
            {"Kerala", "Kottayam", "Piravom", "Pala", "Kaduthuruthy", "Vaikom", "Ettumanoor", "Kottayam", "Puthuppally"},
            {"केरल", "कोट्टायम", "पिरवोम", "पाला", "कादुतुर्ती", "वैकोम", "एट्टुमनूर", "कोट्टायम", "पुथुप्पली"},
            {"Kerala", "Kozhikode", "Balusseri", "Elathur", "Kozhikode North", "Kozhikode South", "Beypore", "Kunnamangalam", "Koduvally"},
            {"केरल", "कोझिकोड", "बलुसेरी", "एलाथुर", "कोझिकोड उत्तर", "कोझिकोड दक्षिण", "बयपुर", "कुन्नमंगलम", "कोदुवल्ली"},
            {"Kerala", "Malappuram", "Kondotty", "Manjeri", "Perinthalmanna", "Mankada", "Malappuram", "Vengara", "Vallikkunnu"},
            {"केरल", "मलप्पुरम", "कोंडोट्टी", "मंजेरी", "पेरिन्तल्मन्ना", "मनकादा", "मलप्पुरम", "वेंगारा", "वल्लिकुन्नू"},
            {"Kerala", "Mavelikkara", "Changanassery", "Kuttanad", "Mavelikkara", "Chengannur", "Kunnathur", "Kottarakkara", "Pathanapuram"},
            {"केरल", "मवेलीकारा", "चंगनासैरी", "कुट्टनाद", "मवेलिक्कारा", "चेंगनूर", "कुन्नथूर", "कोट्टरक्कारा", "पठानपुरम"},
            {"Kerala", "Palakkad", "Pattambi", "Shoranur", "Ottappalam", "Kongad", "Mannarkkad", "Malampuzha", "Palakkad"},
            {"केरल", "पलक्कड़", "पट्टाम्बि", "शोरानूर", "ओट्टापलम", "कोंगड", "मन्नारकड", "मालमपुझा", "पलक्कड़"},
            {"Kerala", "Pathanamthitta", "Kanjirappally", "Poonjar", "Thiruvalla", "Ranni", "Aranmula", "Konni", "Adoor"},
            {"केरल", "पथानामथिट्टा", "कंजीरापल्ली", "पून्जार", "तिरुवल्ला", "राणी", "अरानमुला", "कोणी", "अडूर"},
            {"Kerala", "Ponnani", "Tirurangadi", "Tanur", "Tirur", "Kottakkal", "Thavanur", "Ponnani", "Thrithala"},
            {"केरल", "पोन्नानी", "तिरुरंगादी", "तनुर", "तिरूर", "कोट्टाकल", "तवानुर", "पोन्नानी", "त्रितला"},
            {"Kerala", "Thiruvananthapuram", "Kazhakkoottam", "Vattiyoorkavu", "Thiruvananthapuram", "Nemom", "Parassala", "Kovalam", "Neyyattinkara"},
            {"केरल", "तिरुवनंतपुरम", "कझाकुट्टम", "वट्टियूरकवु", "तिरुवनंतपुरम", "नेमम", "परस्सला", "कोवलम", "नय्यट्टिनकरा"},
            {"Kerala", "Thrissur", "Guruvayoor", "Manalur", "Ollur", "Thrissur", "Nattika", "Irinjalakuda", "Puthukkad"},
            {"केरल", "त्रिशूर", "गुरुवायुर", "मनालुर", "ओल्लुर", "त्रिशूर", "नट्टिका", "इरिन्जालकुडा", "पुतुक्कड़"},
            {"Kerala", "Vadakara", "Thalassery", "Kuthuparamba", "Vadakara", "Kuttiadi", "Nadapuram", "Quilandy", "Perambra"},
            {"केरल", "वाटकरा", "थलसेरी", "कुतुपरम्बा", "वाटकरा", "कुट्टियदी", "नादपुरम", "कोयिलान्दी", "पेराम्ब्रा"},
            {"Kerala", "Wayanad", "Mananthavady", "Sulthanbathery", "Kalpetta", "Thiruvambadi", "Ernad", "Nilambur", "Wandoor"},
            {"केरल", "वायनाड", "मनंतवाड़ी", "सुल्तानबथरी", "कालपेट्टा", "तिरुवाम्बड़ी", "एरानाड", "नीलाम्बुर", "वंडूर"},
            {"Madhya Pradesh", "Balaghat", "Baihar", "Lanji", "Paraswada", "Balaghat", "Waraseoni", "Katangi", "Barghat", "Seoni"},
            {"मध्य प्रदेश", "बालाघाट", "बैहर", "लांजी", "परसवाड़ा", "बालाघाट", "वरासियोनी", "कटंगी", "बरघाट", "सिवनी"},
            {"Madhya Pradesh", "Betul", "Multai", "Amla", "Betul", "Ghoradongri", "Bhainsdehi", "Timarni", "Harda", "Harsud"},
            {"मध्य प्रदेश", "बेतुल", "मुलताई", "अमला", "बेतुल", "घोरादोंग्री", "भैंसदेही", "टिमरनी", "हरदा", "हरसूद"},
            {"Madhya Pradesh", "Bhind", "Ater", "Bhind", "Lahar", "Mehgaon", "Gohad", "Sewda", "Bhander", "Datia"},
            {"मध्य प्रदेश", "भिंड", "अटेर", "भिंड", "लहर", "मेहगांव", "गोहड़", "सेवाडा", "भांडेर", "Datia"},
            {"Madhya Pradesh", "Bhopal", "Berasia", "Bhopal Uttar", "Narela", "Bhopal Dakshin-Paschim", "Bhopal Madhya", "Govindpura", "Huzur", "Sehore"},
            {"मध्य प्रदेश", "भोपाल", "बैरसिया", "भोपाल उत्तर", "नरेला", "भोपाल दक्षिण-पश्चिम", "भोपाल मध्य", "गोविंदपुरा", "हुजूर", "सीहोर"},
            {"Madhya Pradesh", "Chhindwara", "Junnardeo", "Amarwara", "Chourai", "Saunsar", "Chhindwara", "Parasia", "Pandhurna"},
            {"मध्य प्रदेश", "छिंदवाड़ा", "जुन्नारदेव", "अमरवाड़ा", "चौरई", "सौंसर", "छिंदवाड़ा", "परासिया", "पंधुरना"},
            {"Madhya Pradesh", "Damoh", "Deori", "Rehli", "Banda", "Malhara", "Pathariya", "Damoh", "Jabera", "Hatta"},
            {"मध्य प्रदेश", "दमोह", "देवरी", "रहली", "बांदा", "मल्हार", "पथरिया", "दमोह", "जबरा", "हट्टा"},
            {"Madhya Pradesh", "Dewas", "Ashta", "Agar", "Shajapur", "Shujalpur", "Kalapipal", "Sonkatch", "Dewas", "Hatpipliya"},
            {"मध्य प्रदेश", "देवास", "आष्टा", "आगर", "शाजापुर", "शुजालपुर", "कालापीपल", "सोनकच्छ", "देवास", "हाटपिपलिया"},
            {"Madhya Pradesh", "Dhar", "Sardarpur", "Gandhwani", "Kukshi", "Manawar", "Dharampuri", "Dhar", "Badnawar", "Dr. AmbedkarNagar-Mhow"},
            {"मध्य प्रदेश", "धार", "सरदारपुर", "गंधवानी", "कुक्षी", "मनावर", "धर्मपुरी", "धार", "बदनावर", "डॉ अम्बेडकरनगर-महो"},
            {"Madhya Pradesh", "Guna", "Shivpuri", "Pichhore", "Kolaras", "Bamori", "Guna", "Ashok Nagar", "Chanderi", "Mungaoli"},
            {"मध्य प्रदेश", "गुना", "शिवपुरी", "पिछोर", "कोलारस", "बमोरी", "गुना", "अशोक नगर", "चंदेरी", "मुंगावली"},
            {"Madhya Pradesh", "Gwalior", "Gwalior Rural", "Gwalior", "Gwalior East", "Gwalior South", "Bhitarwar", "Dabra", "Karera", "Pohari"},
            {"मध्य प्रदेश", "ग्वालियर", "ग्वालियर ग्रामीण", "ग्वालियर", "ग्वालियर पूर्व", "ग्वालियर दक्षिण", "भितरवार", "डबरा", "करेरा", "पोहरी"},
            {"Madhya Pradesh", "Hoshangabad", "Narsingpur", "Tendukheda", "Gadarwara", "Seoni-Malwa", "Hoshangabad", "Sohagpur", "Pipariya", "Udaipura"},
            {"मध्य प्रदेश", "होशंगाबाद", "नरसिंहपुर", "तेंदूखेड़ा", "गाडरवारा", "सिवनी-मालवा", "होशंगाबाद", "सोहागपुर", "पिपरिया", "उदयपुरा "},
            {"Madhya Pradesh", "Indore", "Depalpur", "Indore-1", "Indore-2", "Indore-3", "Indore-4", "Indore-5", "Rau", "Sanwer"},
            {"मध्य प्रदेश", "इंदौर", "देपालपुर", "इंदौर-1", "इंदौर-2", "इंदौर-3", "इंदौर-4", "इंदौर-5", "राऊ", "सांवेर"},
            {"Madhya Pradesh", "Jabalpur", "Patan", "Bargi", "Jabalpur Purba", "Jabalpur Uttar", "Jabalpur Cantt.", "Jabalpur Paschim", "Panagar", "Sihora"},
            {"मध्य प्रदेश", "जबलपुर", "पाटन", "बरगी", "जबलपुर पूर्व", "जबलपुर उत्तर", "जबलपुर छावनी", "जबलपुर पश्चिम", "पनागर", "सिहोरा"},
            {"Madhya Pradesh", "Khajuraho", "Chandla", "Rajnagar", "Pawai", "Gunnaor", "Panna", "Vijayraghavgarh", "Murwara", "Bahoriband"},
            {"मध्य प्रदेश", "खजुराहो", "चंदला", "राजनगर", "पवई", "गुन्नौर", "पन्ना", "विजयराघवगढ़", "मुरवाड़ा", "बहोरीबंद"},
            {"Madhya Pradesh", "Khandwa", "Bagali", "Mandhata", "Khandwa", "Pandhana", "Nepanagar", "Burhanpur", "Bikhangaon", "Badwah"},
            {"मध्य प्रदेश", "खंडवा", "बागली", "मान्धाता", "खंडवा", "पंधाना", "नेपानगर", "बुरहानपुर", "बीकनगांव", "बड़वाह"},
            {"Madhya Pradesh", "Khargone", "Maheshwar", "Kasrawad", "Khargone", "Bhagwanpura", "Sendhawa", "Rajpur", "Pansemal", "Badwani"},
            {"मध्य प्रदेश", "खरगोन", "महेश्वर", "कसरावद", "खरगोन", "भगवानपुरा", "सेंधवा", "राजपुर", "पानसेमल", "बड़वानी"},
            {"Madhya Pradesh", "Mandla", "Shahpura", "Dindori", "Bichhiya", "Niwas", "Mandla", "Keolari", "Lakhnadon", "Gotegaon"},
            {"मध्य प्रदेश", "मंडला", "शाहपुर", "डिंडोरी", "बिछिया", "निवास", "मंडला", "केओलारी", "लखनादोन", "गोटेगांव"},
            {"Madhya Pradesh", "Mandsour", "Jaora", "Mandsour", "Malhargarh", "Suwasra", "Garoth", "Manasa", "Neemuch", "Jawad"},
            {"मध्य प्रदेश", "मंदसौर", "जावरा", "मंदसौर", "मल्हारगढ़", "सुवासर", "गरोठ", "मनासा", "नीमच", "जवाद"},
            {"Madhya Pradesh", "Morena", "Sheopur", "Vijaypur", "Sabalgarh", "Joura", "Sumawali", "Morena", "Dimani", "Ambah"},
            {"मध्य प्रदेश", "मोरैना", "श्योपुर", "विजयपुर", "सबलगढ़", "जोउरा", "सुमावली", "मोरैना", "दिमनी", "अम्बाह"},
            {"Madhya Pradesh", "Rajgarh", "Chachoura", "Raghogarh", "Narsinghgarh", "Biaora", "Rajgarh", "Khilchipur", "Sarangpur", "Susner"},
            {"मध्य प्रदेश", "राजगढ़", "चचौरा", "राघोगढ़", "नरसिंहगढ़", "ब्यावरा", "राजगढ़", "खिलचीपुर", "सारंगपुर", "सुसनेर"},
            {"Madhya Pradesh", "Ratlam", "Alirajpur", "Jobat", "Jhabua", "Thandla", "Petlawad", "Ratlam Rural", "Ratlam City", "Sailana"},
            {"मध्य प्रदेश", "रतलाम", "अलीराजपुर", "जोबट", "झाबुआ", "थांदला", "पेटलावद", "रतलाम ग्रामीण", "रतलाम शहर", "सैलाना"},
            {"Madhya Pradesh", "Rewa", "Sirmour", "Semariya", "Teonthar", "Mauganj", "Deotalab", "Mangawan", "Rewa", "Gurh"},
            {"मध्य प्रदेश", "रीवा", "सिरमौर", "सेमरिया", "तेओंथर", "मऊगंज", "देवतालाब", "मंगावा", "रीवा", "गुढ़"},
            {"Madhya Pradesh", "Sagar", "Bina", "Khurai", "Surkhi", "Naryawali", "Sagar", "Kurwai", "Sironj", "Shamshabad"},
            {"मध्य प्रदेश", "सागर", "बीना", "खुरई", "सुरखी", "नरयावली", "सागर", "कुरवाई", "सिरोंज", "शमशाबाद"},
            {"Madhya Pradesh", "Satna", "Chitrakoot", "Raigaon", "Satna", "Nagod", "Maihar", "Amarpatan", "Rampur-Baghelan"},
            {"मध्य प्रदेश", "सतना", "चित्रकूट", "रायगांव", "सतना", "नागोद", "मैहर", "अमरपाटन", "रामपुर-बघेलान"},
            {"Madhya Pradesh", "Shahdol", "Jaisingnagar", "Jaitpur", "Kotma", "Anuppur", "Pushprajgarh", "Bandhavgarh", "Manpur", "Barwara"},
            {"मध्य प्रदेश", "शाहडोल", "जयसिंहनगर", "जैतपुर", "कोतमा", "अनूपपुर", "पुष्पराजगढ़", "बांधवगढ़", "मानपुर", "बड़वारा"},
            {"Madhya Pradesh", "Sidhi", "Churhat", "Sidhi", "Sihawal", "Chitrangi", "Singrauli", "Devsar", "Dhauhani", "Beohari"},
            {"मध्य प्रदेश", "सीधी", "चुरहट", "सीधी", "सिहावल", "चितरंगी", "सिंगरौली", "देवसर", "धौहनी", "बेओहारी"},
            {"Madhya Pradesh", "Tikamgarh", "Tikamgarh", "Jatara", "Prithvipur", "Niwari", "Khargapur", "Maharajpur", "Chhatarpur", "Bijawar"},
            {"मध्य प्रदेश", "टीकमगढ़", "टीकमगढ़", "जतारा", "पृथ्वीपुर", "निवारी", "खरगरपुर", "महाराजपुर", "छतरपुर", "Bijawar"},
            {"Madhya Pradesh", "Ujjain", "Nagada-Khachrod", "Mahidpur", "Tarana", "Ghatiya", "Ujjain Uttar", "Ujjain Dakshin", "Badnagar", "Alot"},
            {"मध्य प्रदेश", "उज्जैन", "नगाड़ा-खाचरौद", "महिदपुर", "तराना", "घटिया", "उज्जैन उत्तर", "उज्जैन दक्षिण", "बड़नगर", "आलोट"},
            {"Madhya Pradesh", "Vidisha", "Bhojpur", "Sanchi", "Silwani", "Vidisha", "Basoda", "Budhni", "Ichhawar", "Khategaon"},
            {"मध्य प्रदेश", "विदिशा", "भोजपुर", "सांची", "सिलवानी", "विदिशा", "बासौदा", "बुधनी", "इछावर", "खातेंगांव"},
            {"Maharashtra", "Ahmednagar", "Shevgaon", "Rahuri", "Parner", "Ahmednagar City", "Shrigonda", "Karjat Jamkhed"},
            {"महाराष्ट्र", "अहमदनगर", "शेवगाँव", "राहुरी", "पारनेर", "अहमदनगर शहर", "श्रीगोंदा", "कर्जत जामखेड"},
            {"Maharashtra", "Akola", "Akot", "Balapur", "Akola West", "Akola East", "Murtizapur", "Risod"},
            {"महाराष्ट्र", "अकोला", "अकोट", "बालापुर", "अकोला पश्चिम", "अकोला पूर्व", "मूर्तिजापुर", "रिसोड"},
            {"Maharashtra", "Amravati", "Badnera", "Amravati", "Teosa", "Daryapur", "Melghat", "Achalpur"},
            {"महाराष्ट्र", "अमरावती", "बडनेरा", "अमरावती", "तिवसा", "दर्यापुर", "मेळघाट", "अचलपुर"},
            {"Maharashtra", "Aurangabad", "Kannad", "Aurangabad Central", "Aurangabad West", "Aurangabad East", "Gangapur", "Vaijapur"},
            {"महाराष्ट्र", "औरंगाबाद महा", "कन्नड", "औरंगाबाद सेंट्रल", "औरंगाबाद पश्चिम", "औरंगाबाद पूर्व", "गंगापुर", "वैजापुर"},
            {"Maharashtra", "Baramati", "Daund", "Indapur", "Baramati", "Purandar", "Bhor", "Khadakwasala"},
            {"महाराष्ट्र", "बारामती", "दौंड", "इंदापुर", "बारामती", "पुरंदर", "भोर", "खडकवासला"},
            {"Maharashtra", "Beed", "Georai", "Majalgaon", "Beed", "Ashti", "Kaij", "Parli"},
            {"महाराष्ट्र", "बीड", "गेवराई", "मजलगांव", "बीड", "अष्टि", "कैज़", "परली"},
            {"Maharashtra", "Bhandara Gondiya", "Tumsar", "Bhandara", "Sakoli", "Arjuni Morgaon", "Tirora", "Gondiya"},
            {"महाराष्ट्र", "भंडारा-गोंदिया जिला", "Tumsar", "भंडारा", "साकोली", "अर्जुनी मोरगांव", "तिरोडा", "गोंदिया"},
            {"Maharashtra", "Bhiwandi", "Bhiwandi Rural", "Shahapur", "Bhiwandi West", "Bhiwandi East", "Kalyan West", "Murbad"},
            {"महाराष्ट्र", "भिवंडी", "भिवंडी ग्रामीण", "शाहपुर", "भिवंडी पश्चिम", "भिवंडी पूर्व", "कल्याण पश्चिम", "मुरबाड"},
            {"Maharashtra", "Buldhana", "Buldhana", "Chikhli", "Sindkhed Raja", "Mehkar", "Khamgaon", "Jalgaon (Jamod)"},
            {"महाराष्ट्र", "बुलढाना", "बुलढाना", "चीखली", "सिंदखेड राजा", "मेहकर", "खामगांव", "जलगांव (जामोद)"},
            {"Maharashtra", "Chandrapur", "Rajura", "Chandrapur", "Ballarpur", "Warora", "Wani", "Arni"},
            {"महाराष्ट्र", "चंद्रपुर", "राजुरा", "चंद्रपुर", "बल्लारपुर", "वरोरा", "वानी", "आर्णी"},
            {"Maharashtra", "Dhule", "Dhule Rural", "Dhule City", "Sindkheda", "Malegaon Central", "Malegaon Outer", "Baglan"},
            {"महाराष्ट्र", "धुले", "धुले ग्रामीण", "धुले शहर", "शिंदखेडा", "मालेगांव सेंट्रल", "मालेगांव बाहरी", "बगलान"},
            {"Maharashtra", "Dindori", "Nandgaon", "Kalwan", "Chandvad", "Yevla", "Niphad", "Dindori"},
            {"महाराष्ट्र", "डिंडोरी", "नंदगांव", "कालवन", "चांदवड", "येवला", "निफाड", "डिंडोरी"},
            {"Maharashtra", "Gadchiroli Chimur", "Amgaon", "Armori", "Gadchiroli", "Aheri", "Brahmapuri", "Chimur"},
            {"महाराष्ट्र", "गढ़चिरोली-चिमूर", "आमगांव", "आरमोरी", "गढ़चिरोली", "अहेरी", "ब्रम्हपुरी", "चिमूर"},
            {"Maharashtra", "Hatkanangle", "Shahuwadi", "Hatkanangle", "Ichalkaranji", "Shirol", "Islampur", "Shirala"},
            {"महाराष्ट्र", "हातकणंगले", "शाहूवाडी", "हातकणंगले", "इचलकरंजी", "शिरोल", "इस्लामपुर", "शिराळा"},
            {"Maharashtra", "Hingoli", "Umarkhed", "Kinwat", "Hadgaon", "Basmath", "Kalamnuri", "Hingoli"},
            {"महाराष्ट्र", "हिंगोली", "उमरखेड", "किनवट", "हदगाव", "वसमत", "कलमनुरी", "हिंगोली"},
            {"Maharashtra", "Jalgaon", "Jalgaon City", "Jalgaon Rural", "Amalner", "Erandol", "Chalisgaon", "Pachora"},
            {"महाराष्ट्र", "जलगांव", "जलगांव शहर", "जलगांव ग्रामीण", "अमळनेर", "एरंडोल", "चाळीसगाव", "पाचोरा"},
            {"Maharashtra", "Jalna", "Jalna", "Badnapur", "Bhokardan", "Sillod", "Phulambri", "Paithan"},
            {"महाराष्ट्र", "जलना", "जलना", "बदनापुर", "भोकरदन", "सिल्लोड", "फुलंब्री", "पैठण"},
            {"Maharashtra", "Kalyan", "Ambernath", "Ulhas Nagar", "Kalyan East", "Dombivali", "Kalyan Rural", "Mumbra-Kalwa"},
            {"महाराष्ट्र", "कल्याण", "अंबरनाथ", "उल्हास नगर", "कल्याण पूर्व", "डोम्बिवली", "कल्याण ग्रामीण", "मुंब्रा-कलवा"},
            {"Maharashtra", "Kolhapur", "Chandgad", "Radhanagari", "Kagal", "Kolhapur South", "Karvir", "Kolhapur North"},
            {"महाराष्ट्र", "कोल्हापुर", "चंदगड", "राधानगरी", "कागल", "कोल्हापुर दक्षिण", "करवीर", "कोल्हापुर उत्तर"},
            {"Maharashtra", "Latur", "Latur Rural", "Latur City", "Ahmadpur", "Udgir(SC)", "Nilanga", "Loha"},
            {"महाराष्ट्र", "लातूर", "लातूर ग्रामीण", "लातूर शहर", "अहमदपुर", "उदगीर", "निलंगा", "लोहा"},
            {"Maharashtra", "Madha", "Karmala", "Madha", "Sangola", "Malshiras", "Phaltan", "Man"},
            {"महाराष्ट्र", "माढा", "करमाला", "माढा", "Sangola", "मालशिरस", "फलटण", "माण"},
            {"Maharashtra", "Maval", "Panvel", "Karjat", "Uran", "Maval", "Chinchwad", "Pimpri"},
            {"महाराष्ट्र", "मावल", "पनवेल", "कर्जत", "उरण", "मावल", "चिंचवड", "पिंपरी"},
            {"Maharashtra", "Mumbai North", "Borivali", "Dahisar", "Magathane", "Kandivali East", "Charkop", "Malad West"},
            {"महाराष्ट्र", "मुंबई उत्तर", "बोरीवली", "दहिसर", "मागाठाणे", "कांदिवली पूर्व", "चारकोप", "मलाड पश्चिम"},
            {"Maharashtra", "Mumbai North Central", "Vile Parle", "Chandivali", "Kurla", "Vandre East", "Vandre West", "Kalina"},
            {"महाराष्ट्र", "मुंबई उत्तर मध्य", "विले पार्ले", "चांदिवली", "कुर्ला", "वांद्रे पूर्व", "वांद्रे पश्चिम", "कलिना"},
            {"Maharashtra", "Mumbai North East", "Mulund", "Vikhroli", "Bhandup West", "Ghatkopar West", "Ghatkopar East", "Mankhurd Shivaji Nagar"},
            {"महाराष्ट्र", "मुंबई उत्तर पूर्व", "मुलुंड", "विक्रोली", "भांडुप पश्चिम", "घाटकोपर पश्चिम", "घाटकोपर पूर्व", "मानखुर्द शिवाजी नगर "},
            {"Maharashtra", "Mumbai North West", "Jogeshwari East", "Dindoshi", "Goregaon", "Versova", "Andheri West", "Andheri East"},
            {"महाराष्ट्र", "मुंबई उत्तर पश्चिम", "जोगेश्वरी पूर्व", "दिंडोशी", "गोरेगांव", "वर्सोवा", "अंधेरी पश्चिम", "अंधेरी पूर्व"},
            {"Maharashtra", "Mumbai South", "Worli", "Shivadi", "Byculla", "Malabar Hill", "Mumbadevi", "Colaba"},
            {"महाराष्ट्र", "मुंबई दक्षिण", "वर्ली", "शिवडी", "बायखला", "मालाबार हिल", "मुम्बादेवी", "कोलाबा"},
            {"Maharashtra", "Mumbai South Central", "Anushakti Nagar", "Chembur", "Dharavi", "Sion Koliwada", "Wadala", "Mahim"},
            {"महाराष्ट्र", "मुंबई दक्षिण मध्य", "अणुशक्ति नगर", "चेंबूर", "धारावी", "सायन कोलीवाड़ा", "वडाला", "माहिम"},
            {"Maharashtra", "Nagpur", "Nagpur South West", "Nagpur South", "Nagpur East", "Nagpur Central", "Nagpur West", "Nagpur North"},
            {"महाराष्ट्र", "नागपुर", "नागपुर दक्षिण पश्चिम", "नागपुर दक्षिण", "नागपुर पूर्व", "नागपुर सेंट्रल", "नागपुर पश्चिम", "नागपुर उत्तर"},
            {"Maharashtra", "Nanded", "Bhokar", "Nanded North", "Nanded South", "Naigaon", "Deglur", "Mukhed"},
            {"महाराष्ट्र", "नांदेड़", "भोकर", "नांदेड़ उत्तर", "नांदेड़ दक्षिण", "नायगांव", "देगलूर", "मुखेड"},
            {"Maharashtra", "Nandurbar", "Akkalkuwa", "Shahada", "Nandurbar", "Nawapur", "Sakri", "Shirpur"},
            {"महाराष्ट्र", "नंदुरबार", "अक्कलकुवा", "शहादा", "नंदुरबार", "नवापुर", "सकरी", "शिरपुर"},
            {"Maharashtra", "Nashik", "Sinnar", "Nashik East", "Nashik Central", "Nashik West", "Deolali", "Igatpuri"},
            {"महाराष्ट्र", "नासिक", "सिन्नर", "नासिक पूर्व", "नासिक सेंट्रल", "नासिक पश्चिम", "देवलाली", "इगतपुरी"},
            {"Maharashtra", "Osmanabad", "Ausa", "Umarga", "Tuljapur", "Osmanabad", "Paranda", "Barshi"},
            {"महाराष्ट्र", "उस्मानाबाद", "औसा", "उमरगा", "तुलजापुर", "उस्मानाबाद", "परांदा", "बार्शी"},
            {"Maharashtra", "Palghar", "Dahanu", "Vikramgad", "Palghar", "Boisar", "Nalasopara", "Vasai"},
            {"महाराष्ट्र", "पालघर", "डहाणू", "विक्रमगढ़", "पालघर", "बोईसर", "नालासोपारा", "वसई"},
            {"Maharashtra", "Parbhani", "Jintur", "Parbhani", "Gangakhed", "Pathri", "Partur", "Ghansawangi"},
            {"महाराष्ट्र", "परभनी", "जिंतूर", "परभणी", "गंगाखेड", "पथरी", "परतुर", "घणसावंगी"},
            {"Maharashtra", "Pune", "Vadgaon Sheri", "Shivajinagar", "Kothrud", "Parvati", "Pune Cantonment", "Kasba Peth"},
            {"महाराष्ट्र", "पुणे", "वड़गांव शेरी", "शिवाजीनगर", "कोथरूड", "पर्वती", "पुणे छावनी", "कस्बा पेठ"},
            {"Maharashtra", "Raigad", "Pen", "Alibag", "Shrivardhan", "Mahad", "Dapoli", "Guhagar"},
            {"महाराष्ट्र", "रायगढ़", "पेन", "अलीबाग", "श्रीवर्धन", "महाड", "दापोली", "Guhagar"},
            {"Maharashtra", "Ramtek", "Katol", "Savner", "Hingna", "Umred", "Kamthi", "Ramtek"},
            {"महाराष्ट्र", "रामटेक", "काटोल", "सावनेर", "हिंगणा", "उमरेड", "कामठी", "रामटेक"},
            {"Maharashtra", "Ratnagiri Sindhudurg", "Chiplun", "Ratnagiri", "Rajapur", "Kankavli", "Kudal", "Sawantwadi"},
            {"महाराष्ट्र", "रत्नागिरी-सिंधुदुर्ग", "चिपलूण", "रत्नागिरी", "राजपुर", "कणकवली", "कुडाल", "सावन्तवाडी"},
            {"Maharashtra", "Raver", "Chopda", "Raver", "Bhusawal", "Jamner", "Muktainagar", "Malkapur"},
            {"महाराष्ट्र", "रावेर", "चोपडा", "रावेर", "भुसावल", "जामनेर", "मुक्ताईनगर", "मलकापुर"},
            {"Maharashtra", "Sangli", "Miraj", "Sangli", "Palus-Kadegaon", "Khanapur", "Tasgaon-Kavathe Mahankal", "Jat"},
            {"महाराष्ट्र", "सांगली", "मिराज", "सांगली", "पलुस-कडेगांव", "खानापुर", "तासगांंव-कवठे महाकाल", "जत"},
            {"Maharashtra", "Satara", "Wai", "Koregaon", "Karad North", "Karad South", "Patan", "Satara"},
            {"महाराष्ट्र", "सतारा", "वाई", "कोरेगांव", "कराड उत्तर", "कराड दक्षिण", "पाटन", "सतारा"},
            {"Maharashtra", "Shirdi", "Akole", "Sangamner", "Shirdi", "Kopargaon", "Shrirampur", "Nevasa"},
            {"महाराष्ट्र", "शिरडी", "अकोले", "संगमनेर", "शिरडी", "कोपरगांव", "श्रीरामपुर", "नेवासा"},
            {"Maharashtra", "Shirur", "Junnar", "Ambegaon", "Khed Alandi", "Shirur", "Bhosari", "Hadapsar"},
            {"महाराष्ट्र", "शिरुर", "जुन्नर", "आंबेगांव", "खेद आलंदी", "शिरुर", "भोसरी", "हड़पसर"},
            {"Maharashtra", "Solapur", "Mohol", "Solapur City North", "Solapur City Central", "Akkalkot", "Solapur South", "Pandharpur"},
            {"महाराष्ट्र", "सोलापुर", "मोहोल", "सोलापुर शहर उत्तर", "सोलापुर सिटी सेंट्रल", "अक्कलकोट", "सोलापुर दक्षिण", "पंढरपुर"},
            {"Maharashtra", "Thane", "Mira Bhayandar", "Ovala-Majiwada", "Kopri-Pachpakhadi", "Thane", "Airoli", "Belapur"},
            {"महाराष्ट्र", "ठाणे", "मीरा भायंदर", "ओवला-माजीवाड़ा", "कोपरी-पाचपखाडी", "ठाणे", "ऐरोली", "बेलापुर"},
            {"Maharashtra", "Wardha", "Dhamangaon Railway", "Morshi", "Arvi", "Deoli", "Hinganghat", "Wardha"},
            {"महाराष्ट्र", "वर्धा", "धामणगांव रेलवे", "मोर्शी", "आर्वी", "देवली", "हिंगणघाट", "वर्धा"},
            {"Maharashtra", "Yavatmal-Washim", "Washim", "Karanja", "Ralegaon", "Yavatmal", "Digras", "Pusad"},
            {"महाराष्ट्र", "यवतमाल-वाशिम", "वाशिम", "करंजा", "रालेगांव", "यवतमाल", "दिग्रस", "पुसद"},
            //Inner Manipur Constituencies wise list:- https://www.elections.in/manipur/parliamentary-constituencies/inner-manipur.html
            {"Manipur", "Inner Manipur", "Khundrakpam", "Thangmeiband", "Lamsang", "Heingang", "Uripok", "Konthoujam", "Khurai", "Sagolband", "Patsoi", "Khetrigao", "Keisamthong", "Langthabal", "Thongju", "Singjamei", "Naoriya Pakhanglakpa", "Keirao", "Yaiskul", "Wangoi", "Andro", "Wangkhei", "Mayang Imphal", "Lamlai", "Sekmai", "Nambol", "Oinam", "Thanga", "Thoubal", "Bishenpur", "Kumbi", "Wangkhem", "Moirang", "Lilong"},
            {"मणिपुर", "इनर मणिपुर", "खुन्द्रक्पम", "थंगमेबंद", "लम्बसंग", "हेंगंग", "उरीपोक", "कोंथौजम", "खुरई", "सगोलबंद", "पातसोई", "क्षेत्रिगाओ", "किशाम्थोंग", "लंग्थाबल", "थोंगजू", "सिंगजमेई", "नोरिया पाखंगलक्पा", "कैराओ", "येसकुल", "वंगोई", "एंड्रो", "वांग्केई", "मेयांग इम्फाल", "लामलाई", "सेकमाई", "नाम्बोल", "ओइनाम", "थांगा", "थौबल", "बिशेनपुर", "कुमबी", "वांगखेम", "मोइरांग", "लिलौंग"},
            //Outer Manipur Constituencies wise list:- https://www.elections.in/manipur/parliamentary-constituencies/outer-manipur.html
            {"Manipur", "Outer Manipur", "Heirok", "Jiribam", "Karong", "Wangjing Tentha", "Chandel", "Mao", "Khangabo", "Tengnoupal", "Tadubi", "Wabgai", "Phungyar", "Kangpokpi ", "Kakching", "Ukhrul", "Saitu", "Hiyanglam", "Chingai", "Tamei", "Sugnoo", "Saikul", "Tamenglong", "Nungba", "Henglep", "Saikot", "Tipaimukh", "Churachandpur", "Singhat", "Thanlon"},
            {"मणिपुर", "बाहरी मणिपुर", "हैरोक़", "जिरिबाम", "कारॉन्ग", "वांगजिंग टेंथा", "चंदेल", "माओ", "खांगाबो", "टेंग्नौपाल", "ताडुबी", "वाबगई", "फुंग्यार", "कांगपोकपी ", "काकचिंग", "उखरुल", "सैतु", "हियांगलाम", "चिंगाई", "तामै", "सुग्नू", "सैकुल", "तामेंगलांग", "नुंग्बा", "हेंगलेप", "साइकोट", "तिपाईमुख", "चुराचंदपुर", "सिंघट", "थान्लोन"},
            {"Meghalaya", "Shillong", "Nartiang", "Jowai", "Raliang", "Mowkaiaw", "Sutnga-Saipung", "Khliehriat", "Amlarem", "Mawhati", "Nongpoh", "Jirang", "Umsning", "Umroi", "Mawryngkneng", "Pynthorumkhrah", "Mawlai", "East Shillong", "North Shillong", "West Shillong", "South Shillong", "Mylliem", "Nongthymmai", "Nongkrem", "Sohing", "Mawphlang", "Mawsynram", "Shella", "Pynursla", "Sohra", "Mawkynrew", "Mairang", "Mawthadraishan", "Nongstoin", "Rambrai Jyrngam", "Mawshynrut", "Ranikor", "Mawkyrwat"},
            {"मेघालय", "शिलांग", "नारतीयंग", "जोवै", "रलिअंग", "मोकायव", "सुतंगा-सैपुन्ग", "खलिएहरिएट", "अमलारेम", "मौहाटी", "नोंगपोह", "जिरंग", "उमसिंनिंग", "उमरोई", "मौर्यनगकनंग", "प्यनथोरुम्कहराह", "मवलै", "पूर्व शिलांग", "उत्तर शिलांग", "पश्चिम शिलांग", "दक्षिण शिलांग", "मिलिएम", "नोंग्थिम्मै", "नोंगक्रेम", "सोहिओंग", "मावफ्लांग", "मौसिनराम", "शेल्ला", "पिनूरसला", "सोहरा", "मवकीनरेव", "मैरंग", "माथाद्रिशाम", "नांगस्टॉइन", "रामबरै जयरंगम", "मौशीनरूट", "रानीकोर", "मौकैवत"},
            {"Meghalaya", "Tura", "Kharkutta", "Mendipathar", "Resubelpara", "Bajengdoba", "Songsak", "Rongjeng", "William Nagar", "Raksamgre", "Tikrikila", "Phulbari", "Rajabala", "Selsella", "Dadenggre", "North Tura", "South Tura", "Rangsakona", "Ampathi", "Mahendraganj", "Salmanpara", "Gambegre", "Dalu", "Rongara-Siju", "Chokpot", "Baghmara"},
            {"मेघालय", "तुरा", "खरकुट्टा", "मेंदीपाथर", "रेसुबेलपारा", "बजेंगदोबा", "सोंगसाक", "रोंगजेन्ग", "विलियम नगर", "रकसंगरे", "टीकृकिला", "फुलबारी", "राजाबाला", "सेलसेला", "ददेनगग्रे", "उत्तर तुरा", "दक्षिण तुरा", "रंगसाकोना", "अम्पति", "महेंद्रगंज", "सलमानपारा", "गाम्बेग्रे", "डालू", "रोंगरा-सीजू", "चोकपोट", "बाघमारा"},
            {"Mizoram", "Mizoram", "Hachhek", "Dampa", "Mamit", "Tuirial", "Kolasib", "Serlui", "Tuivawl", "Chalfilh", "Tawi", "Aizawl North-I", "Aizawl North-II", "Aizawl North-III", "Aizawl East-I", "Aizawl East-II", "Aizawl West-I", "Aizawl West-II", "Aizawl West-III", "Aizawl South-I", "Aizawl South-II", "Aizawl South-III", "Lengteng", "Tuichang", "Champhai North", "Champhai South", "East Tuipui", "Serchhip", "Tuikum", "Hrangturzo", "South Tuipui", "Lunglei North", "Lunglei East", "Lunglei West", "Lunglei South", "Thorang", "West Tuipui", "Tuichawng", "Lawngtlai West", "Lawngtlai East", "Saiha", "Palak"},
            {"मिज़ोरम", "मिजोरम", "हचेक", "डम्पा", "ममित", "तुइरियाल", "कोलासिब", "सेरलुई", "तुइवॉएल", "शैफिल", "तवी", "आइज़ॉल उत्तर-I", "आइज़ॉल उत्तर-II", "आइज़ॉल उत्तर-III", "आइज़ॉल ईस्ट-I", "आइज़ॉल ईस्ट-II", "आइज़ॉल वेस्ट-I", "आइज़ॉल वेस्ट-II", "आइज़ॉल वेस्ट-III", "आइज़ॉल साउथ-I", "आइज़ॉल साउथ-II", "आइज़ॉल साउथ-III", "लेंगटेंग", "तुइचांग", "चम्फाई उत्तर", "चम्फाई दक्षिण", "पूर्वी तुईपुई", "सेरशिप", "तुईकुम", "ह्रंगटुरजो", "दक्षिण तुइपुई", "लुंगलेई उत्तर", "लुंगलेई पूर्व", "लुंगलेई पश्चिम", "लुंगलेई दक्षिण", "थोरंग", "पश्चिम तुइपुई", "तुइचावंग", "लॉंग्टलाई वेस्ट", "लॉंग्टलाई ईस्ट", "साईहा", "पलक"},
            {"Nagaland", "Nagaland", "Dimapur-I", "Tuli", "Tizit", "Dimapur-II", "Arkakong", "Wakching", "Dimapur-III", "Impur", "Tapi", "Ghaspani-I", "Angetyongpang", "Phomching", "Ghaspani-II", "Mongoya", "Tehok", "Tenning", "Aonglenden", "Mon Town", "Peren", "Mokokchung Town", "Aboi", "Western Angami", "Koridang", "Moka", "Kohima Town", "Jangpetkong", "Tamlu", "Northern Angami-I", "Alongtaki", "Longleng", "Northern Angami-II", "Akuluto", "Noksen", "Tseminyu", "Atoizu", "Longkhim Chare", "Pughoboto", "Suruhoto", "Tuensang Sadar-I", "Southern Angami-I", "Aghunato", "Tuensang Sadar-II", "Southern Angami-II", "Zunheboto", "Tobu", "Pfutsero", "Satakha", "Noklak", "Chizami", "Tyui", "Thonoknyu", "Chazouba", "Wokha", "Shamator Chessore", "Phek", "Sanis", "Seyochung Sitimi", "Meluri", "Bhandari", "Pungro Kiphire"},
            {"नागालैण्ड", "नागालैण्ड", "दीमापुर-I", "तुली", "तिजीत", "दीमापुर-II", "अर्ककॉन्ग", "वकचिंग", "दीमापुर-III", "इमपुर", "तापी", "घसपनी-I", "अंगत्यांगपंग", "फॉमचिंग", "घसपनी-II", "मोंगोया", "तेहॉक", "टेनिंग", "ऑन्ग्लेंडेन", "मोन टाउन", "पेरेन", "मोकोकचुंग टाउन", "अबोई", "पश्चिमी अंगामी", "कोरिडांग", "मोका", "कोहिमा टाउन", "जंगपेटकॉन्ग", "तमलू", "उत्तरी अंगामी-I", "अलोंगटाकि", "लोंगलेंग", "उत्तरी अंगामी-II", "अकुलूतो", "नोकसेन", "त्समिनीयू", "अटोइजु", "लोंगखिम चारे", "पुगोबोटो", "सुरहोतो", "तुएनसांग सदर-I", "दक्षिणी अंगामी-I", "अघुनतो", "तुएनसांग सदर-II", "दक्षिणी अंगामी-II", "ज़ुन्हबोतो", "टोबू", "पफुटसेरो", "सातख", "नोक्लाक", "चिज़ामी", "त्यौइ,", "थोंकोन्यु", "चोज़ा", "वोखा", "शमटोर चेसोर", "फेक", "सानिस", "सेयोचुंग सीतिमी", "मेलुरी", "भंडारी", "पुंगरो किफिर"},
            {"National Capital Territory of Delhi", "Chandni Chowk", "Adarsh Nagar", "Shalimar Bagh", "Shakur Basti", "Tri Nagar", "Wazirpur", "Model Town", "Sadar Bazar", "Chandni Chowk", "Matia Mahal", "Ballimaran"},
            {"दिल्ली", "चांदनी चोक", "आदर्श नगर", "शालीमार बाग", "शकूर बस्ती", "त्रिनगर", "वज़ीरपुर", "मॉडल टाउन", "सदर बाज़ार", "चांदनी चोक", "मटिया महल", "बल्लीमारान"},
            {"National Capital Territory of Delhi", "East Delhi", "Jangpura", "Okhla", "Trilokpuri", "Kondli", "Patparganj", "Laxmi Nagar", "Vishwas Nagar", "Krishna Nagar", "Gandhi Nagar", "Shahdara"},
            {"दिल्ली", "पूर्वी दिल्ली", "जंगपुरा", "ओखला", "त्रिलोकपुरी", "कोंडली", "पटपड़गंज", "लक्ष्मी नगर", "विश्वास नगर", "कृष्णा नगर", "गांधी नगर", "शाहदरा"},
            {"National Capital Territory of Delhi", "New Delhi", "Karol Bagh", "Patel Nagar", "Moti Nagar", "Delhi Cantt.", "Rajinder Nagar", "New Delhi", "Kasturba Nagar", "Malviya Nagar", "R.K. Puram", "Greater Kailash"},
            {"दिल्ली", "नई दिल्ली", "करोल बाग", "पटेल नगर", "मोती नगर", "दिल्ली कैंट.", "राजेंद्र नगर", "नई दिल्ली", "कस्तूरबा नगर", "मालवीय नगर", "आर.के. पुरम", "ग्रेटर कैलाश"},
            {"National Capital Territory of Delhi", "North East Delhi", "Burari", "Timarpur", "Seemapuri", "Rohtas Nagar", "Seelampur", "Ghonda", "Babarpur", "Gokalpur", "Mustafabad", "Karawal Nagar"},
            {"दिल्ली", "नॉर्थ ईस्ट दिल्ली", "बुराड़ी", "तिमारपुर", "सीमापुरी", "रोहतास नगर", "सीलमपुर", "घोंडा", "बाबरपुर", "गोकलपुर", "मुस्तफाबाद", "करावल नगर"},
            {"National Capital Territory of Delhi", "North West Delhi", "Nerela", "Badli", "Rithala", "Bawana", "Mundka", "Kirari", "Sultanpur Majra", "Nangloi Jat", "Mangol Puri", "Rohini"},
            {"दिल्ली", "उत्तर पश्चिम दिल्ली", "नरेला", "बादली", "रिठाला", "बवाना", "मुंडका", "किराड़ी", "सुल्तानपुर माजरा", "नांगलोई जाट", "मंगोल पुरी", "रोहिणी"},
            {"National Capital Territory of Delhi", "South Delhi", "Bijwasan", "Palam", "Mehrauli", "Chhatarpur", "Deoli", "Ambedkar Nagar", "Sangam Vihar", "Kalkaji", "Tughlakabad", "Badarpur"},
            {"दिल्ली", "दक्षिण दिल्ली", "बिजवासन", "पालम", "महरौली", "छतरपुर", "देवली", "अम्बेडकर नगर", "संगम विहार", "कालकाजी", "तुगलकाबाद", "बदरपुर"},
            {"National Capital Territory of Delhi", "West Delhi", "Madipur", "Rajouri Garden", "Hari Nagar", "Tilak Nagar", "Janakpuri", "Vikaspuri", "Uttam Nagar", "Dwarka", "Matiala", "Najafgarh"},
            {"दिल्ली", "पश्चिमी दिल्ली", "मादीपुर", "राजौरी गार्डन", "हरि नगर", "तिलक नगर", "जनकपुरी", "विकासपुरी", "उत्तम नगर", "द्वारका", "मटियाला", "नजफगढ़"},
            {"Odisha", "Aska", "Polasara", "Kabisuryanagar", "Khalikote", "Aska", "Surada", "Sanakhemundi", "Hinjili"},
            {"ओडिशा", "अस्का", "पोलसरा", "कबिसूर्यनगर", "खैलीकोटे", "अस्का", "सुरादा", "सनखेमुंडी", "हिन्जिली"},
            {"Odisha", "Balasore", "Badasahi", "Jaleswar", "Bhograi", "Basta", "Balasore", "Remuna", "Nilgiri"},
            {"ओडिशा", "बालासोर", "बादशाही", "जलेश्वर", "भोगराई", "बस्ता", "बालासोर", "रेमुना", "नीलगिरि"},
            {"Odisha", "Bargarh", "Padampur", "Bijepur", "Bargarh", "Attabira", "Bhatli", "Brajarajnagar", "Jharsuguda"},
            {"ओडिशा", "बारगढ़", "पदमपुर", "बीजापुर", "बारगढ़", "अत्तबीरा", "भटली", "ब्रजराजनगर", "झारसुगुडा"},
            {"Odisha", "Berhampur", "Chhatrapur", "Gopalpur", "Berhampur", "Digapahandi", "Chikiti", "Mohana", "Paralakhemundi"},
            {"ओडिशा", "बेरहामपुर", "छतरपुर", "गोपालपुर", "बेरहामपुर", "दिगापहंदी", "चिकिटी", "मोहाना", "परलेखेमुंडी"},
            {"Odisha", "Bhadrak", "Soro", "Simulia", "Bhandaripokhari", "Bhadrak", "Basudevpur", "Dhamnagar", "Chandabali"},
            {"ओडिशा", "भद्रक", "सोरो", "सिमुलिया", "भंडारीपोखरी", "भद्रक", "बसुदेवपुर", "धामनगर", "चंदबली"},
            {"Odisha", "Bhubaneswar", "Jayadev", "Bhubaneswar Central", "Bhubaneswar North", "Ekamra-Bhubaneswar", "Jatani", "Begunia", "Khurda"},
            {"ओडिशा", "भुवनेश्वर", "जयदेव", "भुवनेश्वर सेंट्रल", "भुवनेश्वर नॉर्थ", "एकाम्रा-भुवनेश्वर", "जतनी", "बेगुनिया", "खुर्दा"},
            {"Odisha", "Bolangir", "Birmaharajpur", "Sonepur", "Loisingha", "Patnagarh", "Bolangir", "Titlagarh", "Kantabanji"},
            {"ओडिशा", "बोलंगीर", "बीरमहाराजपुर", "सोनपुर", "लोईसिंह", "पटनागढ़", "बोलंगीर", "टिटलागढ़", "कन्ताबंजी"},
            {"Odisha", "Cuttack", "Baramba", "Banki", "Athagarh", "Barabati-Cuttack", "Choudwar-Cuttack", "Cuttack Sadar", "Khandapada"},
            {"ओडिशा", "कटक", "बारमबा", "बांकी", "अथागढ़", "बाराबती-कटक", "चौदवार-कटक", "कटक-सदर", "खंडपाडा"},
            {"Odisha", "Dhenkanal", "Dhenkanal", "Hindol", "Kamakhyanagar", "Parjanga", "Pallahara", "Talcher", "Angul"},
            {"ओडिशा", "ढेंकनाल", "ढेंकनाल", "हिंडोल", "कामाख्यानगर", "परजंगा", "पल्लाहरा", "तालचेर", "अंगुल"},
            {"Odisha", "Jagatsinghpur", "Niali", "Paradeep", "Tirtol", "Balikudaerasama", "Jagatsinghpur", "Kakatpur", "Nimapara"},
            {"ओडिशा", "जगतसिंहपुर", "नियलि", "पारादीप", "टिरटोल", "बालिकुडाऐरासमा", "जगतसिंहपुर", "काकतपुर", "निमापारा"},
            {"Odisha", "Jajpur", "Binjharpur", "Bari", "Barachana", "Dharmasala", "Jajpur", "Korei", "Sukinda"},
            {"ओडिशा", "जाजपुर", "बिंझारपुर", "बारी", "बाराचां", "धर्मशाला", "जाजपुर", "कोरी", "सुकिंदा"},
            {"Odisha", "Kalahandi", "Nuapada", "Khariar", "Lanjigarh", "Junagarh", "Dharmgarh", "Bhawanipatna", "Narla"},
            {"ओडिशा", "कालाहांडी", "नुआपाड़ा", "खारीर", "लांजीगढ़", "जूनागढ़", "धर्मगढ़", "भवानीपटना", "नरला"},
            {"Odisha", "Kandhamal", "Baliguda", "G. Udayagiri", "Phulbani", "Kantamal", "BOUDH", "Daspalla", "BHANJANAGAR"},
            {"ओडिशा", "कंधमाल", "बालीगुडा", "जी. उदयगिरी", "फूलबनी", "कंतमाल", "बोध", "दसपल्ला", "भंजननगर"},
            {"Odisha", "Kendrapara", "Salipur", "Mahanga", "Patkura", "Kendrapara", "Aul", "Rajanagar", "Mahakalapada"},
            {"ओडिशा", "केंद्रपाड़ा", "सालीपुर", "महंगा", "पटकुरा", "केन्द्रपाड़ा", "औल", "राजानगर", "महाकलापाड़ा"},
            {"Odisha", "Keonjhar", "Telkoi", "Ghasipura", "Anandapur", "Patna", "Keonjhar", "Champua", "Karanjia"},
            {"ओडिशा", "क्योंझर", "तेलोकी", "घासीपुरा", "आनंदपुर", "पटना", "क्योंझर", "चंपुआ", "करंजिया"},
            {"Odisha", "Koraput", "Gunupur", "Bissam Cuttack", "Rayagada", "Lakshmipur", "Jeypore", "Koraput", "Pottangi"},
            {"ओडिशा", "कोरापुट", "गुणुपुर", "बिस्सम कुट्टक", "रायगड़ा", "लक्ष्मीपुर", "जैपोरे", "कोरापुट", "पोट्टांगी"},
            {"Odisha", "Mayurbhanj", "Jashipur", "Saraskana", "Rairangpur", "Bangriposi", "Udala", "Baripada", "Morada"},
            {"ओडिशा", "मयूरभंज", "जशपुर", "सरसकाना", "रायरंगपुर", "बंगारीपोसी", "उडाला", "बारीपदा", "मोरादा"},
            {"Odisha", "Nabarangpur", "Umarkote", "Jharigam", "Nabarangpur", "Dabugam", "Kotpad", "Malkangiri", "Chitrakonda"},
            {"ओडिशा", "नबरंगपुर", "उमरकोट", "झारिगाम", "नबरंगपुर", "दबुगम", "कोटपाड", "मलकानगिरी", "चित्रकोडा"},
            {"Odisha", "Puri", "Puri", "Brahmagiri", "Satyabadi", "Pipili", "Chilika", "Ranpur", "Nayagarh"},
            {"ओडिशा", "पुरी", "पुरी", "ब्रह्मगिरि", "सत्यबादी", "पीपली", "चिलिका", "राणपुर", "नयागढ़"},
            {"Odisha", "Sambalpur", "Kuchinda", "Rengali", "Sambalpur", "Rairakhol", "Deogarh", "Chhendipada", "Athamallik"},
            {"ओडिशा", "संबलपुर", "कुचिंडा", "रेंगाली", "सम्बलपुर", "रायराखोल", "देवगढ़", "छेदीपाड़ा", "अथमालिक"},
            {"Odisha", "Sundargarh", "Talsara", "Sundargarh", "Biramitrapur", "Raghunathpali", "Rourkela", "Rajgangapur", "Bonai"},
            {"ओडिशा", "सुंदरगढ़", "तिलसारा", "सुंदरगढ़", "बीरमित्रपुर", "रघुनाथपाली", "राउरकेला", "राजगंगापुर", "बोनाई"},
            {"Puducherry", "Puducherry", "Mannadipet", "Thirubhuvanai", "Oussudu", "Mangalam", "Villianur", "Ozhukarai", "Kadirgamam", "Indira Nagar", "Thattanchavady", "Kamraj Nagar", "Lawspet", "Kalapet", "Muthialpet", "Raj Bhavan", "Oupalam", "Orleampeth", "Nellithope", "Mudaliarpet", "Ariankuppam", "Manavely", "Embalam", "Nettapakkam", "Bahour", "Nedungadu", "Thirunallar", "Karaikal North", "Karaikal South", "Neravy T.R. Pattinam", "Mahe", "Yanam"},
            {"पुदुच्चेरी", "पुडुचेरी", "मन्नदीपेट", "थिरूभुवनै", "ओस्सुदू", "मंगलम", "विल्लिअनुर", "ओज़्हुकारै", "क़ादिरगमम", "इंदिरा नगर", "थट्टांचावडी", "कामराज नगर", "लॉस्पेट", "कालापेट", "मुठिआलपेट", "राज भवन", "अौपालम", "अोरलीमपेठ", "नेल्लीथोपे", "मुदालिअर्पेट", "अॅरियनकुप्पम", "मानवेळी", "एम्बलम", "नेत्तापक्कम", "बाहौर", "नेदुंगदु", "थिरुनल्लार", "काराइकाल उत्तर", "काराइकाल दक्षिण", "नेराव्य टी. आर. पट्टिनाम", "माहे", "यानम"},
            {"Punjab", "Amritsar", "Ajnala", "Raja Sansi", "Majitha", "Amritsar North", "Amritsar West", "Amritsar Central", "Amritsar East", "Amristar South", "Attari"},
            {"पंजाब", "अमृतसर", "अजनाला", "राजा सांसी", "मजीठा", "अमृतसर उत्तर", "अमृतसर पश्चिम", "अमृतसर सेंट्रल", "अमृतसर पूर्व", "अमृतसर दक्षिण", "अटारी"},
            {"Punjab", "Anandpur Sahib", "Garhshankar", "Banga", "Nawan Shahr", "Balachaur", "Anandpur Sahib", "Rupnagar", "Chamkaur Sahib", "Kharar", "S.A.S. Nagar"},
            {"पंजाब", "आनंदपुर साहिब", "गढ़शंकर", "बंगा", "नवांशहर", "बलाचौर", "आनंदपुर साहिब", "Rupnagar", "चमकौर साहिब", "खरड़", "एस.ए.एस. नगर"},
            {"Punjab", "Bathinda", "Lambi", "Bhucho Mandi", "Bathinda Urban", "Bathinda Rural", "Talwandi Sabo", "Maur", "Mansa", "Sardulgarh", "Budhlada"},
            {"पंजाब", "बठिंडा", "लांबी", "भुचो मंडी", "बठिंडा शहर", "बठिंडा ग्रामीण", "तलवंडी साबो", "मौर", "मनसा", "सरदूलगढ़", "बुढलाडा"},
            {"Punjab", "Faridkot", "Nihal Singhwala", "Bhagha Purana", "Moga", "Dharamkot", "Giddarbaha", "Faridkot", "Kotkapura", "Jaitu", "Rampura Phul"},
            {"पंजाब", "फरीदकोट", "निहाल सिंहवाला", "बाघा पुराना", "मोगा", "धरमकोट", "गिद्दड़बाहा", "फरीदकोट", "कोटकपूरा", "जैतो", "रामपुरा फुल"},
            {"Punjab", "Fatehgarh Sahib", "Bassi Pathana", "Fatehgarh Sahib", "Amloh", "Khanna", "Samrala", "Sahnewal", "Payal", "Raikot", "Amargarh"},
            {"पंजाब", "फतेहगढ़ साहिब", "बस्सी पठाना", "फतेहगढ़ साहिब", "अमलोह", "खन्ना", "समराला", "साहनेवाल", "पायल", "रायकोट", "अमरगढ़"},
            {"Punjab", "Firozpur", "Firozpur City", "Firozpur Rural", "Guru Har Sahai", "Jalalabad", "Fazilka", "Abohar", "Balluana", "Malout", "Muktsar"},
            {"पंजाब", "फिरोजपुर", "फिरोजपुर शहर", "फिरोजपुर ग्रामीण", "गुरु हरसहाय", "जलालाबाद", "फाजिल्का", "अबोहर", "बलुआना", "मलोट", "मुक्तसर"},
            {"Punjab", "Gurdaspur", "Sujanpur", "Bhoa", "Pathankot", "Gurdaspur", "Dina Nagar", "Qadian", "Batala", "Fatehgarh Churian", "Dera Baba Nanak"},
            {"पंजाब", "गुरदासपुर", "सुजानपुर", "भोआ", "पठानकोट", "गुरदासपुर", "दीनानगर", "कादियां", "बटाला", "फतेहगढ़ चुरियां", "डेरा बाबा नानक"},
            {"Punjab", "Hoshiarpur", "Sri Hargobindpur", "Bholath", "Phagwara", "Mukerian", "Dasuya", "Urmar", "Sham Chaurasi", "Hoshiarpur", "Chabbewal"},
            {"पंजाब", "होशियारपुर", "श्री हरगोबिंदपुर", "भोलाथ", "फगवाड़ा", "मुकेरियां", "दसूया", "उर्मर", "शाम चौरास्सी", "होशियारपुर", "चब्बेवाल"},
            {"Punjab", "Jalandhar", "Phillaur", "Nakodar", "Shahkot", "Kartarpur", "Jalandhar West", "Jalandhar Central", "Jalandhar North", "Jalandhar Cantt.", "Adampur"},
            {"पंजाब", "जालंधर", "फिल्लौर", "नकोदर", "शाहकोट", "करतारपुर", "जालंधर पश्चिम", "जालंधर सेंट्रल", "जालंधर उत्तर", "जालंधर कैंट.", "आदमपुर"},
            {"Punjab", "Khadoor Sahib", "Jandiala", "Tarn Taran", "Khem Karan", "Patti", "Khadoor Sahib", "Baba Bakala", "Kapurthala", "Sultanpur Lodhi", "Zira"},
            {"पंजाब", "खडूर साहिब", "जंडियाला", "तरन तारन", "खेम करन", "पट्टी", "खडूर साहिब", "बाबा बकाला", "कपूरथला", "सुल्तानपुर लोधी", "ज़ीरा"},
            {"Punjab", "Ludhiana", "Ludhiana East", "Ludhiana South", "Atam Nagar", "Ludhiana Central", "Ludhiana West", "Ludhiana North", "Gill", "Dakha", "Jagraon"},
            {"पंजाब", "लुधियाना", "लुधियाना पूर्व", "लुधियाना दक्षिण", "अतम नगर", "लुधियाना सेंट्रल", "लुधियाना पश्चिम", "लुधियाना उत्तर", "गिल", "दखा", "जगरांव"},
            {"Punjab", "Patiala", "Nabha", "Patiala Rural", "Rajpura", "Dera Bassi", "Ghanaur", "Sanour", "Patiala", "Samana", "Shutrana"},
            {"पंजाब", "पटियाला", "नाभा", "पटियाला ग्रामीण", "राजपुरा", "डेरा बस्सी", "घनौर", "सनौर", "पटियाला", "समाना", "शुतराणा"},
            {"Punjab", "Sangrur", "Lehra", "Dirba", "Sunam", "Bhadaur", "Barnala", "Mehal Kalan", "Malerkotla", "Dhuri", "Sangrur"},
            {"पंजाब", "संगरूर", "लेहरा", "दिरबा", "सुनाम", "बहादुर", "बरनाला", "मेहल कलां", "मलेरकोटला", "धुरी", "संगरूर"},
            {"Rajasthan", "Ajmer", "Dudu", "Kishangarh", "Pushkar", "Ajmer North", "Ajmer South", "Nasirabad", "Masuda", "Kekri"},
            {"राजस्थान", "अजमेर", "दूदू", "किशनगढ़", "पुष्कर", "अजमेर उत्तर", "अजमेर दक्षिण", "नसीराबाद", "मसूदा", "केकड़ी"},
            {"Rajasthan", "Alwar", "Tijara", "Kishangarh Bas", "Mundawar", "Behror", "Alwar Rural", "Alwar Urban", "Ramgarh", "Rajgarh Laxmangarh"},
            {"राजस्थान", "अलवर", "तिजारा", "किशनगढ़ बास", "मंडावर", "बहरोड़", "अलवर ग्रामीण", "अलवर शहर", "रामगढ़", "राजगढ़ लक्ष्मणगढ़"},
            {"Rajasthan", "Banswara", "Dungarpur", "Sagwara", "Chorasi", "Ghatol", "Garhi", "Banswara", "Bagidora", "Kushalgarh"},
            {"राजस्थान", "बांसवाड़ा", "डूंगरपुर", "सागवाड़ा", "चौरासी", "घाटोल", "गढ़ी", "बांसवाड़ा", "बागीदौरा", "कुशलगढ़"},
            {"Rajasthan", "Barmer", "Jaisalmer", "Sheo", "Barmer", "Baytoo", "Pachpadra", "Siwana", "Gudha Malani", "Chohtan"},
            {"राजस्थान", "बाड़मेर", "जैसलमेर", "शिव", "बाड़मेर", "वायतू", "पचपदरा", "सिवान", "गुढ़ामालानी", "चौहटन"},
            {"Rajasthan", "Bharatpur", "Kathumar", "Kaman", "Nagar", "Deeg Kumher", "Bharatpur", "Nadbai", "Weir", "Bayana"},
            {"राजस्थान", "भरतपुर", "कठूमर", "कामान", "नगर", "डीग कुम्हरे", "भरतपुर", "नदबई", "वैर", "बयाना"},
            {"Rajasthan", "Bhilwara", "Asind", "Mandal", "Sahara", "Bhilwara", "Shahpura", "Jahazpur", "Mandalgarh", "Hindoli"},
            {"राजस्थान", "भीलवाड़ा", "असिंद", "मंडल", "सहाड़ा", "भीलवाड़ा", "शाहपुरा", "जहाज़पुर", "मांडलगढ़", "हिन्दोली"},
            {"Rajasthan", "Bikaner", "Anupgarh", "Khajuwala", "Bikaner West", "Bikaner East", "Kolayat", "Lunkaransar", "Dungargarh", "Nokha"},
            {"राजस्थान", "बीकानेर", "अनूपगढ़", "खाजूवाल", "बीकानेर पश्चिम", "बीकानेर पूर्व", "कोलायत", "लूणकसर", "डूंगरगढ़", "नोखा"},
            {"Rajasthan", "Chittorgarh", "Mavli", "Vallabhnagar", "Kapasan", "Begun", "Chittorgarh", "Nimbahera", "Bari Sadri", "Pratapgarh"},
            {"राजस्थान", "चित्तौड़गढ़", "मावली", "वल्लभनगर", "कपासन", "बेगुन", "चित्तौड़गढ़", "निम्बाहेड़ा", "बड़ी सादड़ी", "प्रतापगढ़"},
            {"Rajasthan", "Churu", "Nohar", "Bhadra", "Sadulpur", "Taranagar", "Sardarshahar", "Churu", "Ratangarh", "Sujangarh"},
            {"राजस्थान", "चुरू", "नोहार", "भादरा", "सादूलपुर", "तारानगर", "सरदारशहर", "चुरू", "रतनगढ़", "सुजानगढ़"},
            {"Rajasthan", "Dausa", "Bassi", "Chaksu", "Thanagazi", "Bandikui", "Mahuwa", "Sikrai", "Dausa", "Lalsot"},
            {"राजस्थान", "दौसा", "बस्सी", "चाकसू", "थानागाजी", "बांदीकुई", "महुवा", "सिकराय", "दौसा", "लालसोट"},
            {"Rajasthan", "Ganganagar", "Sadulshahar", "Ganganagar", "Karanpur", "Suratgarh", "Raisinghnagar", "Sangaria", "Hanumangarh", "Pilibanga"},
            {"राजस्थान", "गंगानगर", "सादुलशहर", "गंगानगर", "करणपुर", "सूरतगढ़", "रायसिंहनगर", "संगरिया", "हनुमानगढ़", "पीलीबंगा"},
            {"Rajasthan", "Jaipur", "Hawa Mahal", "Vidhyadhar Nagar", "Civil Lines", "Kishan Pole", "Adarsh Nagar", "Malviya Nagar", "Sanganer", "Bagru"},
            {"राजस्थान", "जयपुर", "हवामहल", "विद्याधर नगर", "सिविल लाइंस", "किशन पोल", "आदर्श नगर", "मालवीय नगर", "सांगानेर", "बगरू"},
            {"Rajasthan", "Jaipur Rural", "Kotputli", "Viratnagar", "Shahpura", "Phulera", "Jhotwara", "Amber", "Jamwa Ramgarh", "Bansur"},
            {"राजस्थान", "जयपुर ग्रामीण", "कोटपुतली", "विराटनगर", "शाहपुरा", "फुलेरा", "झोंटवाड़ा", "अम्बर", "जामवा रामगढ़", "बानसूर"},
            {"Rajasthan", "Jalore", "Ahore", "Jalore", "Bhinmal", "Sanchore", "Raniwara", "Sirohi", "Pindwara-Abu", "Reodar"},
            {"राजस्थान", "जालोर", "आहोर", "जालौर", "भीनमाल", "सांचोर", "रानीवाड़ा", "सिरोही", "पिण्डवाड़ा-अबू", "रेवदर"},
            {"Rajasthan", "Jhalawar Baran", "Anta", "Kishanganj", "Baran-Atru", "Chhabra", "Dag", "Jhalrapatan", "Khanpur", "Manohar Thana"},
            {"राजस्थान", "झालावाड़ बारां", "अंता", "किशनगंज", "बरन-अटरू", "छाबड़ा", "दाग", "झालरापाटन", "खानपुर", "मनोहर थाना"},
            {"Rajasthan", "Jhunjhunu", "Pilani", "Surajgarh", "Jhunjhunu", "Mandawa", "Nawalgarh", "Udaipurwati", "Khetri", "Fatehpur"},
            {"राजस्थान", "झुंझुनू", "पिलानी", "सूरजगढ़", "झुंझुनू", "मंडावा", "नवलगढ़", "उदयपुरवाटी", "खेतड़ी", "फतेहपुर"},
            {"Rajasthan", "Jodhpur", "Phalodi", "Lohawat", "Shergarh", "Sardarpura", "Jodhpur", "Soorsagar", "Luni", "Pokaran"},
            {"राजस्थान", "जोधपुर", "फलौदी", "लोहावत", "शेरगढ़", "सरदारपुरा", "जोधपुर", "सूरसागर", "लूनी", "पोखरण"},
            {"Rajasthan", "Karauli Dholpur", "Baseri", "Bari", "Dholpur", "Rajakhera", "Todabhim", "Hindaun", "Karauli", "Sapotra"},
            {"राजस्थान", "करौली-धौलपुर", "बसेड़ी", "बारी", "धौलपुर", "राजाखेड़ा", "टोडाभीम", "हिंडौन", "करौली", "सपोतरा"},
            {"Rajasthan", "Kota", "Keshoraipatan", "Bundi", "Pipalda", "Sangod", "Kota North", "Kota South", "Ladpura", "Ramganj Mandi"},
            {"राजस्थान", "कोटा", "किशोरईपाटन", "बूंदी", "पीपल्दा", "सांगोद", "कोटा उत्तर", "कोटा दक्षिण", "लाड़पुरा", "रामगंज मंडी"},
            {"Rajasthan", "Nagaur", "Ladnun", "Deedwana", "Jayal", "Nagaur", "Khinvsar", "Makrana", "Parbatsar", "Nawan"},
            {"राजस्थान", "नागौर", "लाडनू", "डीडवाना", "जायल", "नागौर", "खींवसर", "मकराना", "परबतसर", "नवां"},
            {"Rajasthan", "Pali", "Sojat", "Pali", "Marwar Junction", "Bali", "Sumerpur", "Osian", "Bhopalgarh", "Bilara"},
            {"राजस्थान", "पाली", "सोजत", "पाली", "मारवाड़ जंक्शन", "बाली", "सुमेरपुर", "ओसियन", "भोपालगढ़", "बिलारा"},
            {"Rajasthan", "Rajsamand", "Beawar", "Merta", "Degana", "Jaitaran", "Bhim", "Kumbhalgarh", "Rajsamand", "Nathdwara"},
            {"राजस्थान", "राजसमंद", "ब्यावर", "मेड़ता", "डेगाना", "जैतारण", "भीम", "कुंभलगढ़", "राजसमंद", "नाथद्वारा"},
            {"Rajasthan", "Sikar", "Lachhmangarh", "Dhod", "Sikar", "Danta Ramgarh", "Khandela", "Neem Ka Thana", "Srimadhopur", "Chomu"},
            {"राजस्थान", "सीकर", "लक्ष्मणगढ़", "धोद", "सीकर", "दांतारामगढ़", "खंडेला", "नीम का थाना", "श्रीमाधोपुर", "चौमूं"},
            {"Rajasthan", "Tonk Sawai Madhopur", "Gangapur", "Bamanwas", "Sawai Madhopur", "Khandar", "Malpura", "Niwai", "Tonk", "Deoli Uniara"},
            {"राजस्थान", "टोंक-सवाई माधोपुर", "गंगापुर", "बामनवास", "सवाई माधोपुर", "खंडार", "मालपुरा", "निवाई", "टोंक", "देवली उनियारा"},
            {"Rajasthan", "Udaipur", "Gogunda", "Jhadol", "Kherwara", "Udaipur Rural", "Udaipur", "Salumber", "Dhariawad", "Aspur"},
            {"राजस्थान", "उदयपुर", "गोगुन्दा", "झाड़ोल", "खेरवाड़ा", "उदयपुर ग्रामीण", "उदयपुर", "सलूम्बर", "धरियावद", "आसपुर"},
            {"Sikkim", "Sikkim", "Yoksam-Tashiding (BL)", "Yangthang", "Maneybung-Dentam", "Gyalshing-Barnya", "Rinchenpong (BL)", "Daramdin (BL)", "Soreong-Chakung", "Salghari-Zoom", "Barfung (BL)", "Poklok-Kamrang", "Namchi-Singhithang", "Melli", "Namthang-Rateypani", "Temi-Namphing", "Rangang-Yangang", "Tumen-Lingi (BL)", "Khamdong-Singtam", "West Pendam", "Rhenock", "Chujachen", "Gnathang-Machong (BL)", "Namcheybung", "Shyari (BL)", "Martam-Rumtek (BL)", "Upper Tadong", "Arithang", "Gangtok (BL)", "Upper Burtuk", "Kabi Lungchuk (BL)", "Djongu (BL)", "Lachen Mangan (BL)", "Sangha"},
            {"सिक्किम", "सिक्किम", "योकसाम-ताशिडिंंग (बी. एल.)", "यांगथांग", "मानेयबुंग-डेनटाम", "ग्यालषिंग-बरनयाक", "रिनचेनपोंग (बी.एल.)", "दारामदीन (बी.एल.)", "सोरेओंग-चाकुंग", "सलघारी-जूम", "बरफुंग (बी.एल.)", "पोकलोक-कामरंग", "नामची-सिंघीथांग", "मेल्ली", "नामथंग-राटेयपान", "तेमी-नामफिंग", "रानगंग-यानगंग", "तुमेन-लिंगी (बी.एल.)", "खामदोंग-सिंगटम", "पश्चिम पेन्डम", "रहेनोक", "चुजाचेन", "ग्नाथांग-माचोंग (बी.एल.)", "नामचेयबुंग", "श्यारी (बी.एल.)", "मारतम-रूमटेक (बी.एल.)", "अपर तादोंग", "अरिथांग", "गंगटोक (बी.एल.)", "अपर बुरटुक", "काबी लुंगचुक (बी.एल.)", "दजोंगु (बी.एल.)", "लाचेन मन्गन (बी.एल.)", "संघा"},
    };
}
