package in.filternet.jantamalik.Rajya;

public final class MP_2_MLA {

    public static final String[][] mapping = {

            {"Uttar Pradesh", "Agra",        "Etmadpur",     "Agra Cantt. (SC)", "Agra South",   "Agra North", "Jalesar (SC)"},
            {"उत्तर प्रदेश", "आगरा",        "एतमादपुर",       "आगरा कैंट. (एस सी)", "आगरा दक्षिण",   "आगरा उत्तर", "जलेसर (एस सी)"},
            {"Uttar Pradesh", "Akbarpur", "Akbarpur Raniya", "Bithoor", "Kalyanpur", "Maharajpur", "Ghatampur (SC)"},
            {"उत्तर प्रदेश", "अकबरपुर", "अकबरपुर रनिया", "बिठूर", "कल्याणपुर", "महाराजपुर", "घाटमपुर (एस सी)"},
            {"Uttar Pradesh", "Aligarh", "Khair (SC)", "Barauli", "Atrauli", "Koil", "Aligarh"},
            {"उत्तर प्रदेश", "अलीगढ़", "खैर (एस सी)", "बरौली", "अतरौली", "कोइल", "अलीगढ़"},
            {"Uttar Pradesh", "Allahabad", "Meja", "Karachhana", "Allahabad South",   "Bara (SC)",     "Koraon (SC)"},
            {"उत्तर प्रदेश", "इलाहाबाद", "मेजा", "करचना", "इलाहाबाद दक्षिण", "बारा (एस सी)", "कोरों (एस सी)"},
            {"Uttar Pradesh", "Ambedkar Nagar", "Katehari", "Tanda", "Goshainganj", "Jalalpur", "Akbarpur"},
            {"उत्तर प्रदेश", "अंबेडकर नगर",           "कटेहरी",      "टांडा", "गोसाईगंज",    "जलालपुर",         "अकबरपुर"},
            {"Uttar Pradesh", "Amethi", "Tiloi" , "Salon (SC)", "Jagdishpur (SC)", "Gauriganj", "Amethi"},
            {"उत्तर प्रदेश", "अमेठी", "तिलोई", "सलोन (एस सी)", "जगदीशपुर (एस सी)", "गौरीगंज", "अमेठी"},
            {"Uttar Pradesh", "Amroha", "Dhanaura (SC)" , "Naugawan Sadat", "Amroha", "Hasanpur", "Garhmukteshwar"},
            {"उत्तर प्रदेश", "अमरोहा", "धनौरा (एस सी)" , "नौगावां सादात", "अमरोहा", "हसनपुर", "गढ़मुक्तेश्वर"},
            {"Uttar Pradesh", "Aonla", "Shekhupur", "Dataganj", "Faridpur (SC)", "Bithari Chainpur", "Aonla"},
            {"उत्तर प्रदेश", "आंवला", "शेखूपुर", "दातागंज", "फरीदपुर (एस सी)", "बिथरी चैनपुर", "आंवला"},
            {"Uttar Pradesh", "Azamgarh", "Gopalpur", "Sagri", "Mubarakpur", "Azamgarh", "Mehnagar (SC)"},
            {"उत्तर प्रदेश", "आजमगढ़", "गोपालपुर", "सगरी", "मुबारकपुर", "आजमगढ़", "मेहनगर (एस सी)"},
            {"Uttar Pradesh", "Badaun", "Gunnaur", "Bisauli (SC)", "Sahaswan", "Bilsi", "Badaun"},
            {"उत्तर प्रदेश", "बदायूं", "गुन्नौर", "बिसौली (एस सी)", "सहसवान", "बिल्सी", "बदायूं"},
            {"Uttar Pradesh", "Baghpat", "Siwalkhas", "Chhaprauli", "Baraut", "Baghpat", "Modi Nagar"},
            {"उत्तर प्रदेश", "बागपत", "सिवालखास", "छपरौली", "बड़ौत", "बागपत", "मोदीनगर"},
            {"Uttar Pradesh", "Bahraich", "Balha (SC)", "Nanpara", "Matera", "Mahasi", "Bahraich"},
            {"उत्तर प्रदेश", "बहराइच", "बलहा (एस सी)", "नानपारा", "मटेरा", "महसी", "बहराइच"},
            {"Uttar Pradesh", "Ballia", "Phephana", "Ballia Nagar", "Bairia", "Zahoorabad", "Mohammadabad"},
            {"उत्तर प्रदेश", "बलिया", "फेफना", "बलिया नगर", "बैरिया", "जहूराबाद", "मोहम्मदाबाद"},
            {"Uttar Pradesh", "Banda", "Baberu", "Naraini (SC)", "Banda", "Chitrakoot", "Manikpur"},
            {"उत्तर प्रदेश", "बांदा", "बबेरू", "नरैनी (एस सी)", "बांदा", "चित्रकूट", "मानिकपुर"},
            {"Uttar Pradesh", "Bansgaon", "Chauri-Chaura", "Bansgaon (SC)", "Chillupar", "Rudrapur", "Barhaj"},
            {"उत्तर प्रदेश", "बांसगांव", "चौरी-चौरा", "बांसगांव (एस सी)", "चिल्लूपार", "रुद्रपुर", "बरहज"},
            {"Uttar Pradesh", "Barabanki", "Kursi", "Ram Nagar", "Barabanki", "Zaidpur (SC)", "Haidergarh (SC)"},
            {"उत्तर प्रदेश", "बाराबंकी", "कुर्सी", "रामनगर", "बाराबंकी", "जैदपुर (एस सी)", "हैदरगढ़ (एस सी)"},
            {"Uttar Pradesh", "Bareilly", "Meerganj", "Bhojipura", "Nawabganj", "Bareilly", "Bareilly Cantt"},
            {"उत्तर प्रदेश", "बरेली", "मीरगंज", "भोजीपुरा", "नवाबगंज", "बरेली", "बरेली कैंट."},
            {"Uttar Pradesh", "Basti", "Harraiya", "Kaptanganj", "Rudhauli", "Basti Sadar", "Mahadewa (SC)"},
            {"उत्तर प्रदेश", "बस्ती", "हर्रैया", "कप्तानगंज", "रुधौली", "बस्ती सदर", "महादेवा (एस सी)"},
            {"Uttar Pradesh", "Bhadohi", "Pratappur", "Handia", "Bhadohi", "Gyanpur", "Aurai (SC)"},
            {"उत्तर प्रदेश", "भदोही", "प्रतापपुर", "हंडिया", "भदोही", "ज्ञानपुर", "औराई (एस सी)"},
            {"Uttar Pradesh", "Bijnor", "Purqazi (SC)", "Meerapur", "Bijnor", "Chandpur", "Hastinapur (SC)"},
            {"उत्तर प्रदेश", "बिजनौर", "पुरकाजी (एस सी)", "मीरापुर", "बिजनौर", "चांदपुर", "हस्तिनापुर (एस सी)"},
            {"Uttar Pradesh", "Bulandshahr", "Bulandshahr", "Syana", "Anupshahr", "Debai", "Shikarpur"},
            {"उत्तर प्रदेश", "बुलंदशहर", "बुलंदशहर", "स्याना", "अनूपशहर", "डिबाई", "शिकारपुर"},
            {"Uttar Pradesh", "Chandauli", "Mughalsarai", "Sakaldiha", "Saiyadraja", "Ajagara (SC)", "Shivpur"},
            {"उत्तर प्रदेश", "चंदौली", "मुगलसराय", "सकलडीहा", "सैयदराजा", "अजगर (एस सी)", "शिवपुर"},
            {"Uttar Pradesh", "Deoria", "Tamkuhi Raj", "Fazilnagar", "Deoria", "Pathardeva", "Rampur Karkhana"},
            {"उत्तर प्रदेश", "देवरिया", "तमकुही राज", "फाजिलनगर", "देवरिया", "पथरदेवा", "रामपुर कारखाना"},
            {"Uttar Pradesh", "Dhaurahra", "Dhaurahra", "Kasta (SC)", "Mohammdi", "Mohali", "Hargaon (SC)"},
            {"उत्तर प्रदेश", "धौरहरा", "धौरहरा", "कस्ता (एस सी)", "मोहम्मदी", "महोली", "हरगांव (एस सी)"},
            {"Uttar Pradesh", "Domariyaganj", "Shohratgarh", "Kapilvastu (SC)", "Bansi", "Itwa", "Domariyaganj"},
            {"उत्तर प्रदेश", "डुमरियागंज", "शोहरतगढ़", "कपिलवस्तु (एस सी)", "बांसी", "इटवा", "डुमरियागंज"},
            {"Uttar Pradesh", "Etah", "Kasganj", "Amanpur", "Patiyali", "Etah", "Marhara"},
            {"उत्तर प्रदेश", "एटा", "कासगंज", "अमांपुर", "पटियाली", "एटा", "मारहरा"},
            {"Uttar Pradesh", "Etawah", "Etawah", "Bharthana (SC)", "Dibiyapur", "Auraiya (SC)", "Sikandra"},
            {"उत्तर प्रदेश", "इटावा", "इटावा", "भरथना (एस सी)", "दिबियापुर", "औरैया (एस सी)", "सिकंदरा"},
            {"Uttar Pradesh", "Faizabad", "Dariyabad", "Rudauli", "Milkipur (SC)", "Bikapur", "Ayodhya"},
            {"उत्तर प्रदेश", "फैजाबाद", "दरियाबाद", "रुदौली", "मिल्कीपुर (एस सी)", "बीकापुर", "अयोध्या"},
            {"Uttar Pradesh", "Farrukhabad", "Aliganj", "Kaimganj (SC)", "Amritpur", "Farrukhabad", "Bhojpur"},
            {"उत्तर प्रदेश", "फर्रुखाबाद", "अलीगंज", "कायमगंज (एस सी)", "अमृतपुर", "फर्रुखाबाद", "भोजपुर"},
            {"Uttar Pradesh", "Fatehpur", "Jahanabad", "Bindki", "Fatehpur", "Ayah Shah", "Husainganj", "Khaga (SC)"},
            {"उत्तर प्रदेश", "फतेहपुर", "जहानाबाद", "बिंदकी", "फतेहपुर", "अयाह शाह", "हुसैनगंज", "खागा (एस सी)"},
            {"Uttar Pradesh", "Fatehpur Sikri", "Agra Rural (SC)", "Fatehpur Sikri", "Kheragarh", "Fatehabad", "Bah"},
            {"उत्तर प्रदेश", "फतेहपुर सीकरी", "आगरा ग्रामीण (एस सी)", "फतेहपुर सीकरी", "खेरागढ़", "फतेहाबाद", "बाह"},
            {"Uttar Pradesh", "Firozabad", "Tundla (SC)", "Jasrana", "Firozabad", "Shikohabad", "Sirsaganj"},
            {"उत्तर प्रदेश", "फिरोजाबाद", "टूंडला (एस सी)", "जसराना", "फिरोजाबाद", "शिकोहाबाद", "सिरसागंज"},
            {"Uttar Pradesh", "Gautam Buddha Nagar", "Noida", "Dadri", "Jewar", "Sikandrabad", "Khurja (SC)"},
            {"उत्तर प्रदेश", "गौतम बुद्ध नगर", "नोएडा", "दादरी", "जेवर", "सिकंदराबाद", "खुर्जा (एस सी)"},
            {"Uttar Pradesh", "Ghaziabad", "Loni", "Muradnagar", "Sahibabad", "Ghaziabad", "Dhaulana"},
            {"उत्तर प्रदेश", "गाज़ियाबाद", "लोनी", "मुरादनगर", "साहिबाबाद", "गाज़ियाबाद", "धौलाना"},
            {"Uttar Pradesh", "Ghazipur", "Jakhanian", "Saidpur (SC)", "Ghazipur", "Jangipur (SC)", "Zamania"},
            {"उत्तर प्रदेश", "गाजीपुर", "जखनियां", "सैदपुर (एस सी)", "गाजीपुर", "जंगीपुर (एस सी)", "ज़मानिया"},
            {"Uttar Pradesh", "Ghosi", "Madhuban", "Ghosi", "Muhammadabad-Gohna (SC)", "Mau", "Rasara"},
            {"उत्तर प्रदेश", "घोसी", "मधुबन", "घोसी", "मुहम्मदाबाद-गोहना(एस सी)", "मऊ", "रसड़ा"},
            {"Uttar Pradesh", "Gonda", "Utraula", "Mehnaun", "Gonda", "Mankapur (SC)", "Gaura"},
            {"उत्तर प्रदेश", "गोंडा", "उतरौला", "मेहनौन", "गोंडा", "मनकापुर (एस सी)", "गौरा"},
            {"Uttar Pradesh", "Gorakhpur", "Caimpiyarganj", "Pipraich", "Gorakhpur Urban", "Gorakhpur Rural", "Sahajanwa"},
            {"उत्तर प्रदेश", "गोरखपुर", "कैम्पियरगंज", "पिपराइच", "गोरखपुर शहरी", "गोरखपुर ग्रामीण", "सहजनवा"},
            {"Uttar Pradesh", "Hamirpur", "Hamirpur", "Rath (SC)", "Mahoba", "Charkhari", "Tindwari"},
            {"उत्तर प्रदेश", "हमीरपुर", "हमीरपुर", "राठ (एस सी)", "महोबा", "चरखारी", "तिंदवारी"},
            {"Uttar Pradesh", "Hardoi", "Sawaijpur", "Shahabad", "Hardoi", "Gopamau (SC)", "Sandi (SC)"},
            {"उत्तर प्रदेश", "हरदोई", "सवायजपुर", "शाहाबाद", "हरदोई", "गोपामऊ (एस सी)", "सांडि (एस सी)"},
            {"Uttar Pradesh", "Hathras", "Chharra", "Iglas (SC)", "Hathras (SC)", "Sadabad", "Sikandra Rao"},
            {"उत्तर प्रदेश", "हाथरस", "छर्रा", "इगलास (एस सी)", "हाथरस (एस सी)", "सादाबाद", "सिकंदरा राव"},
            {"Uttar Pradesh", "Jalaun", "Bhognipur", "Madhaugarh", "Kalpi", "Orai (SC)", "Garautha"},
            {"उत्तर प्रदेश", "जालौन", "भोगनीपुर", "माधौगढ़", "कालपी", "उरई (एस सी)", "गरौठा"},
            {"Uttar Pradesh", "Jaunpur", "Badlapur", "Shahganj", "Jaunpur", "Malhani", "Mungra Badshahpur"},
            {"उत्तर प्रदेश", "जौनपुर", "बदलापुर", "शाहगंज", "जौनपुर", "मल्हनी", "मुंगरा बादशाहपुर"},
            {"Uttar Pradesh", "Jhansi", "Babina", "Jhansi Nagar", "Mauranipur (SC)", "Lalitpur", "Mehroni (SC)"},
            {"उत्तर प्रदेश", "झांसी", "बबीना", "झांसी नगर", "मऊरानीपुर (एस सी)", "ललितपुर", "महरौनी (एस सी)"},
            {"Uttar Pradesh", "Kairana", "Nakur", "Gangoh", "Kairana", "Thana Bhawan", "Shamli"},
            {"उत्तर प्रदेश", "कैराना", "नकुड़", "गंगोह", "कैराना", "थाना भवन", "शामली"},
            {"Uttar Pradesh", "Kaiserganj", "Payagpur", "Kaiserganj", "Katra Bazar", "Colonelganj", "Tarabganj"},
            {"उत्तर प्रदेश", "कैसरगंज", "पयागपुर", "कैसरगंज", "कटरा बाजार", "कर्नलगंज", "तरबगंज"},
            {"Uttar Pradesh", "Kannauj", "Chhibramau", "Tirwa", "Kannauj (SC)", "Bidhuna", "Rasulabad (SC)"},
            {"उत्तर प्रदेश", "कन्नौज", "छिबरामऊ", "तिर्वा", "कन्नौज (एस सी)", "बिधूना", "रसूलाबाद (एस सी)"},
            {"Uttar Pradesh", "Kanpur", "Govindnagar", "Sishamau", "Arya Nagar", "Kidwai Nagar", "Kanpur Cantt"},
            {"उत्तर प्रदेश", "कानपुर", "गोविंद नगर", "सीसामऊ", "आर्य नगर", "किदवई नगर", "कानपुर कैंट"},
            {"Uttar Pradesh", "Kaushambi", "Babaganj (SC)", "Kunda", "Sirathu", "Manjhanpur (SC)", "Chail"},
            {"उत्तर प्रदेश", "कौशाम्बी", "बाबागंज (एस सी)", "कुंडा", "सिराथू", "मंझनपुर (एस सी)", "चैल"},
            {"Uttar Pradesh", "Kheri", "Palia", "Nighasan", "Gola Gokrannath", "Sri Nagar (SC)", "Lakhimpur"},
            {"उत्तर प्रदेश", "खेरी", "पलिया", "निघासन", "गोला गोकर्णनाथ", "श्री नगर (एस सी)", "लखीमपुर"},
            {"Uttar Pradesh", "Kushi Nagar", "Khadda", "Padrauna", "Kushinagar", "Hata", "Ramkola (SC)"},
            {"उत्तर प्रदेश", "कुशी नगर", "खड्डा", "पडरौना", "कुशी नगर", "हाटा", "रामकोला (एस सी)"},
            {"Uttar Pradesh", "Lalganj", "Atrauliya", "Nizamabad", "Phoolpur Pawai", "Didarganj", "Lalganj (SC)"},
            {"उत्तर प्रदेश", "लालगंज", "अतरौलिया", "निजामाबाद", "फूलपुर पवाई", "दीदारगंज", "लालगंज (एस सी)"},
            {"Uttar Pradesh", "Lucknow", "Lucknow West", "Lucknow North", "Lucknow East", "Lucknow Central", "Lucknow Cantt."},
            {"उत्तर प्रदेश", "लखनऊ", "लखनऊ पश्चिम", "लखनऊ उत्तर", "लखनऊ पूर्व", "लखनऊ सेंट्रल", "लखनऊ कैंट."},
            {"Uttar Pradesh", "Machhlishahr", "Machhlishahr (SC)", "Mariyahu", "Zafrabad", "Kerakat (SC)", "Pindra"},
            {"उत्तर प्रदेश", "मछलीशहर", "मछलीशहर (एस सी)", "मड़ियाहूं", "जफराबाद", "केराकत (एस सी)", "पिंडरा"},
            {"Uttar Pradesh", "Maharajganj", "Pharenda", "Nautanwa", "Siswa", "Maharajganj (SC)", "Paniyara"},
            {"उत्तर प्रदेश", "महाराजगंज", "फरेन्दा", "नौतनवा", "सिसवा", "महाराजगंज (एस सी)", "पनियरा"},
            {"Uttar Pradesh", "Mainpuri", "Mainpuri", "Bhongaon", "Kishni (SC)", "Karhal", "Jaswantnagar"},
            {"उत्तर प्रदेश", "मैनपुरी", "मैनपुरी", "भोगांव", "किशनी (एस सी)", "करहल", "जसवंतनगर"},
            {"Uttar Pradesh", "Mathura", "Chhata", "Mant", "Goverdhan", "Mathura", "Baldev (SC)"},
            {"उत्तर प्रदेश", "मथुरा", "छटा", "मंत", "गोवर्धन", "मथुरा", "बलदेव (एस सी)"},
            {"Uttar Pradesh", "Meerut", "Kithore", "Meerut Cantt.", "Meerut", "Meerut South", "Hapur (SC)"},
            {"उत्तर प्रदेश", "मेरठ", "किठौर", "मेरठ कैंट.", "मेरठ", "मेरठ दक्षिण", "हापुड़ (एस सी)"},
            {"Uttar Pradesh", "Mirzapur",    "Chhanbey (SC)",     "Mirzapur",         "Majhawan",     "Chunar",       "Marihan"},
            {"उत्तर प्रदेश", "मिर्जापुर",       "छानबे (एस सी)",          "मिर्जापुर",            "मझवां",          "चुनार",         "मड़िहान"},
            {"Uttar Pradesh", "Misrikh", "Misrikh (SC)", "Bilgram Mallanwan", "Balamau (SC)", "Sandila", "Bilhaur (SC)"},
            {"उत्तर प्रदेश", "मिसरिख", "मिसरिख (एस सी)", "बिलग्राम मल्लावां", "बालामऊ (एस सी)", "सण्डीला", "बिल्हौर (एस सी)"},
            {"Uttar Pradesh", "Mohanlalganj", "Sidhauli (SC)", "Malihabad (SC)", "Bakshi Kaa Talab", "Sarojini Nagar", "Mohanlalganj (SC)"},
            {"उत्तर प्रदेश", "मोहनलालगंज", "सिधौली (एस सी)", "मलिहाबाद (एस सी)", "बक्शी का तालाब", "सरोजिनी नगर", "मोहनलालगंज (एस सी)"},
            {"Uttar Pradesh", "Moradabad", "Barhapur", "Kanth", "Thakurdwara", "Moradabad Rural", "Moradabad Nagar"},
            {"उत्तर प्रदेश", "मुरादाबाद", "बढ़ापुर", "काँठ", "ठाकुरद्वारा", "मुरादाबाद ग्रामीण", "मुरादाबाद नगर"},
            {"Uttar Pradesh", "Muzaffarnagar", "Budhana", "Charthawal", "Muzaffar Nagar", "Khatauli", "Sardhana"},
            {"उत्तर प्रदेश", "मुजफ्फरनगर", "बुढ़ाना", "चरथावल", "मुजफ्फर नगर", "खतौली", "सरधना"},
            {"Uttar Pradesh", "Nagina", "Najibabad", "Nagina (SC)", "Dhampur", "Nehtaur (SC)", "Noorpur"},
            {"उत्तर प्रदेश", "नगीना", "नजीबाबाद", "नगीना (एस सी)", "धामपुर", "नहटौर (एस सी)", "नूरपुर"},
            {"Uttar Pradesh", "Phulpur", "Phaphamau", "Soraon (SC)", "Phulpur", "Allahabad West", "Allahabad North"},
            {"उत्तर प्रदेश", "फूलपुर", "फाफामऊ", "सोराअों (एस सी)", "फूलपुर", "इलाहाबाद पश्चिम", "इलाहाबाद उत्तर"},
            {"Uttar Pradesh", "Pilibhit", "Baheri", "Pilibhit", "Barkhera", "Puranpur (SC)", "Bisalpur"},
            {"उत्तर प्रदेश", "पीलीभीत", "बहेरी", "पीलीभीत", "बरखेड़ा", "पूरनपुर (एस सी)", "बीसलपुर"},
            {"Uttar Pradesh", "Pratapgarh", "Rampur Khas", "Vishwanath Ganj", "Pratapgarh", "Patti", "Raniganj"},
            {"उत्तर प्रदेश", "प्रतापगढ़", "रामपुर खास", "विश्वनाथ गंज", "प्रतापगढ़", "पट्टी", "रानीगंज"},
            {"Uttar Pradesh", "Rae Bareli", "Bachhrawan (SC)" ,"Harchandpur", "Rae Bareli", "Sareni", "Unchahar"},
            {"उत्तर प्रदेश", "रायबरेली", "बछरावां (एस सी)" ,"हरचंदपुर", "रायबरेली", "सरेनी", "ऊंचाहार"},
            {"Uttar Pradesh", "Rampur", "Suar", "Chamraua", "Bilaspur", "Rampur", "Milak (SC)"},
            {"उत्तर प्रदेश", "रामपुर", "सूअर", "चमरौआ", "बिलासपुर", "रामपुर", "मिलक (एस सी)"},
            {"Uttar Pradesh", "Robertsganj", "Chakia (SC)", "Ghorawal", "Robertsganj", "Obra", "Duddhi (SC)"},
            {"उत्तर प्रदेश", "रोबर्टस गंज", "चकिया (एस सी)", "घोरावल", "रोबर्टस गंज", "ओबरा", "दुद्धी (एस सी)"},
            {"Uttar Pradesh", "Saharanpur", "Behat", "Saharanpur Nagar", "Saharanpur", "Deoband", "Rampur Maniharan (SC)"},
            {"उत्तर प्रदेश", "सहारनपुर", "बेहत", "सहारनपुर नगर", "सहारनपुर", "देवबन्द", "रामपुर मनिहारान (एस सी)"},
            {"Uttar Pradesh", "Salempur", "Bhatpar Rani", "Salempur (SC)", "Belthara Road (SC)", "Sikanderpur", "Bansdih"},
            {"उत्तर प्रदेश", "सलेमपुर", "भाटपार रानी", "सलेमपुर (एस सी)", "बेलथरा रोड (एस सी)", "सिकंदरपुर", "बांसडीह"},
            {"Uttar Pradesh", "Sambhal", "Kundarki", "Bilari", "Chandausi (SC)", "Asmoli", "Sambhal"},
            {"उत्तर प्रदेश", "संभल", "कुंदरकी", "बिलारी", "चन्दौसी (एस सी)", "असमोली", "संभल"},
            {"Uttar Pradesh", "Sant Kabir Nagar", "Alapur (SC)", "Menhdawal", "Khalilabad", "Dhanghata (SC)", "Khajani (SC)"},
            {"उत्तर प्रदेश", "संत कबीर नगर", "अलापुर (एस सी)", "मेंहदावल", "खलीलाबाद", "धनघटा (एस सी)", "खजनी (एस सी)"},
            {"Uttar Pradesh", "Shahjahanpur", "Katra", "Jalalabad", "Tilhar", "Powayan (SC)", "Shahjahanpur", "Dadraul"},
            {"उत्तर प्रदेश", "शाहजहांपुर", "कटरा", "Jalalabad", "तिलहर", "पुवायां (एस सी)", "शाहजहांपुर", "ददरौल"},
            {"Uttar Pradesh", "Shrawasti", "Bhinga", "Shrawasti", "Tulsipur", "Gainsari", "Balrampur (SC)"},
            {"उत्तर प्रदेश", "श्रावस्ती", "भिनगा", "श्रावस्ती", "तुलसीपुर", "गैसड़ी", "बलरामपुर (एस सी)"},
            {"Uttar Pradesh", "Sitapur", "Sitapur", "Laharpur", "Biswan", "Sevata", "Mohmoodabad"},
            {"उत्तर प्रदेश", "सीतापुर", "सीतापुर", "लहरपुर", "बिसवाँ", "सेवता", "महमूदाबाद"},
            {"Uttar Pradesh", "Sultanpur", "Isauli", "Sultanpur", "Sadar", "Lambhua", "Kadipur (SC)"},
            {"उत्तर प्रदेश", "सुल्तानपुर", "इसौली", "सुल्तानपुर", "सदर", "लम्भुआ", "कादीपुर (एस सी)"},
            {"Uttar Pradesh", "Unnao", "Bangermau", "Safipur (SC)", "Mohan (SC)", "Unnao", "Bhagwantnagar", "Purwa"},
            {"उत्तर प्रदेश", "उन्नाव", "बांगरमऊ", "सफीपुर (एस सी)", "मोहन (एस सी)", "उन्नाव", "भगवंतनगर", "पूर्वा"},
            {"Uttar Pradesh", "Varanasi",    "Rohaniya",     "Sevapuri",     "Varanasi Cantt.",  "Varanasi North",   "Varanasi South"},
            {"उत्तर प्रदेश", "वाराणसी",       "रोहनिया",      "सेवापुरी",         "वाराणसी कैंट.",        "वाराणसी उत्तर",        "वाराणसी दक्षिण"}
    };
}
