/* Auto-generated file from db2MPjava.php*/

    package in.filternet.jantamalik.Rajya;

    public final class Nagaland {

    	public static final String[][] MLAs = {

		{"Nagaland", "Aboi", "Eshak Konyak", "नागालैण्ड", "अबोई", "Eshak Konyak",  "  9436015025", "", "", "", "", " H.NO.40 Longching Mon "},
		{"Nagaland", "Aghunato", "Pukhayi", "नागालैण्ड", "अघुनतो", "Pukhayi",  "  9436017944", "", "", " pukhayisumi@gmail.com", "", " House No.114, BPO Satami, Vill. P.O.-Zunheboto, Nagaland "},
		{"Nagaland", "Akuluto", "Kazheto Kinimi", "नागालैण्ड", "अकुलूतो", "Kazheto Kinimi",  "  9436004364", "", "", "", "", " Resident of North Point Colony, Akuluto Town, BPO Akuluto, H/No.46 "},
		{"Nagaland", "Alongtaki", "Temjen Imna Along", "नागालैण्ड", "अलोंगटाकि", "Temjen Imna Along",  "  9856001332", "", "", " temjenlonglongkumer@gmail.com", "", " H No. 83, Longtho, PO Mangkolemba "},
		{"Nagaland", "Angetyongpang", "Tongpang Ozukum", "नागालैण्ड", "अंगत्यांगपंग", "Tongpang Ozukum",  "  9612496168", "", "", " ozukum_79@yahoo.com", "", " R/o House NO. 57, Block 2, Alongmen Ward Mokokchung nagaland "},
		{"Nagaland", "Aonglenden", "Sharingain Longkumer", "नागालैण्ड", "ऑन्ग्लेंडेन", "Sharingain Longkumer",  "  8974025699", "", "", " Shari.lkr@gmail.com ", "", " House No 525 Mekumpong Ungma Village Mokokchung Nagaland "},
		{"Nagaland", "Arkakong", "Shri Imnatiba", "नागालैण्ड", "अर्ककॉन्ग", "Shri Imnatiba",  "  8131889708", " 7005128909", "", " jamir008@yahoo.com", "", " R/o House No. 491, Changtongya Town District Mokokchung, Nagaland "},
		{"Nagaland", "Atoizu", "Picto", "नागालैण्ड", "अटोइजु", "Picto",  "  9436004167", "", "", "", "", " Resident of Rotomi Village, BPO Aizuto, P.O.-Zunheboto(Dist)-798620, Nagaland "},
		{"Nagaland", "Bhandari", "Mmhonlumo Kikon", "नागालैण्ड", "भंडारी", "Mmhonlumo Kikon",  "  9856090900", "", "", " mkikon@gmail.com", "", " House No. 765, Block-05, Padumpukhri Village, Dimapur, Nagaland 797116 "},
		{"Nagaland", "Chizami", "Kezhienyi Khalo", "नागालैण्ड", "चिज़ामी", "Kezhienyi Khalo", "  9612851516", " 9436013013", "", "", "", " Resident of Mesulumi Village, PO/PS Chizami, Phek, Dist. "},
		{"Nagaland", "Chazouba", "Chotisuh Sazo", "नागालैण्ड", "चोज़ा", "Chotisuh Sazo", "", "", "", "", "", " Resident of Phusachodu Village, P.O.-Pfutsero, Phek Dist.-797107 "},
		{"Nagaland", "Dimapur-I", "H. Tovihoto Ayemi", "नागालैण्ड", "दीमापुर-I", "H. Tovihoto Ayemi",  "  9436002195", "", "", "", "", " Thahekhu Village, PO Dimapur, PS Sub Urban, District Dimapur Nagaland "},
		{"Nagaland", "Dimapur-II", "Moatoshi Longkumer", "नागालैण्ड", "दीमापुर-II", "Moatoshi Longkumer",  "  03862-248476", " 9436000069", "", " longkumer.moatoshi56@gmail.com", "", " House No 179, Indisen Village Dimapur, Nagaland "},
		{"Nagaland", "Dimapur-III", "Azheto Zhimomi", "नागालैण्ड", "दीमापुर-III", "Azheto Zhimomi",  "  9436002222", "", "", "", "", " H/No 48, Kiyeto Village, Dist-Dimapur-797112, State Nagaland "},
		{"Nagaland", "Ghaspani-I", "N. Jacob Zhimomi", "नागालैण्ड", "घसपनी-I", "N. Jacob Zhimomi",  "  9856009999", "", "", "", "", " House No. 1, Akito Village, PO. & PS. Niuland, Sub-Division Niuland, Dist. Dimapur 797112 "},
		{"Nagaland", "Ghaspani-II", "Zhaleo Rio", "नागालैण्ड", "घसपनी-II", "Zhaleo Rio",  "  9436000130", "", "", " riozhaleo@yahoo.com", "", " Lerie Colony, District Kohima, Nagaland "},
		{"Nagaland", "Impur", "Dr Imtiwapang Aier", "नागालैण्ड", "इमपुर", "Dr Imtiwapang Aier",  "  9856929905", "", "", " dr.imtiwapang@gmail.com", "", " R/o Sungratsu Village P.O. impur, Nagaland 798615 "},
		{"Nagaland", "Jangpetkong", "Longrineken", "नागालैण्ड", "जंगपेटकॉन्ग", "Longrineken",  "  7005433610", "", "", " longrinekenao@yahoo.com", "", " Khar Village, Dist. Mokokchung, Nagaland "},
		{"Nagaland", "Kohima Town", "Dr.neikiesalie Nicky Kire", "नागालैण्ड", "कोहिमा टाउन", "Dr.neikiesalie Nicky Kire",  "  9436000503", " 8414000100", "", " dr.nickykire@yahoo.co.in", "", " House No. 69, D Block Middle, District Kohima, Nagaland 797001 "},
		{"Nagaland", "Koridang", "Imkong L Imchen", "नागालैण्ड", "कोरिडांग", "Imkong L Imchen",  "  9436000070", "8974777781", "", "", "", " House No.183-B, Mangmetong Village, P.O. Mokokchung, Nagaland Pin 798617 "},
		{"Nagaland", "Longkhim Chare", "Muthingnyuba Sangtam", "नागालैण्ड", "लोंगखिम चारे", "Muthingnyuba Sangtam",  "  9436001573", "", "", " msangtam@gmail.com", "", " H.No. 70, Alisopur Village, District Tuensang Nagaland "},
		{"Nagaland", "Longleng", "S Pangnyu Phom", "नागालैण्ड", "लोंगलेंग", "S Pangnyu Phom",  "  9436003592", "", "", "", "", " H.No. 94, High School Colony, PO. Longleng 798625, Longleng, Nagaland "},
		{"Nagaland", "Meluri", "Yitachu", "नागालैण्ड", "मेलुरी", "Yitachu",  "  9436000079 ", " 8974053044", "", "", "", " Permanent resident of Yisisotha Village, PO & PS Meluri, Dist. Phek and Presently residing at Phezoucha, New Secretariat Area, Kohima, Nagaland "},
		{"Nagaland", "Moka", "E. E. Pangteang", "नागालैण्ड", "मोका", "E. E. Pangteang",  "  9436000080", "", "", "", "", " R/o Angphang Village, Mon "},
		{"Nagaland", "Mokokchung Town", "Metsubo Jamir", "नागालैण्ड", "मोकोकचुंग टाउन", "Metsubo Jamir",  "  9862089675", "", "", " metsubojamir@gmail.com", "", " H.No. 561A Mongsenbai Ward Mokokchung Town Dist. Mokokchung Nagaland "},
		{"Nagaland", "Mon Town", "N. Thongwang Konyak", "नागालैण्ड", "मोन टाउन", "N. Thongwang Konyak",  "  9436015061", "", "", "", "", " R/o Mon Town, Mon District-79862 "},
		{"Nagaland", "Mongoya", "Ngangshi K Ao", "नागालैण्ड", "मोंगोया", "Ngangshi K Ao",  "  9862020202", "9436006027", "", " drnkao@gmail.com", "", " Mokokchung Village "},
		{"Nagaland", "Noklak", "H.Haiying", "नागालैण्ड", "नोक्लाक", "H.Haiying",  "  9402908307", " 7630024875", "", "", "", " New Pangsha Village, Noklak "},
		{"Nagaland", "Noksen", "C.M. Chang", "नागालैण्ड", "नोकसेन", "C.M. Chang",  "  9436000980", "", "", "", "", " Resident of Green Meadow, House No 335, Burma Camp, Walford, Dimagpur, Nagaland-797112 "},
		{"Nagaland", "Northern Angami-I", "Khriehu Liezietsu", "नागालैण्ड", "उत्तरी अंगामी-I", "Khriehu Liezietsu",  "  9436002115", "", "", " khriehul@yahoo.com", "", " H No. 243, Middle Bayavu, Kohima 797001 "},
		{"Nagaland", "Northern Angami-II", "Neiphiu Rio", "नागालैण्ड", "उत्तरी अंगामी-II", "Neiphiu Rio",  "  9717861950", " 9436609010", " 03862-242963", " rioneiphiu@gmail.com", "", " R/O Tuophema Village (Basa), Kohima, Nagaland "},
		{"Nagaland", "Peren", "Taditui Rangkau Zeliang", "नागालैण्ड", "पेरेन", "Taditui Rangkau Zeliang",  "  9862007777", " 038622243138", " 039622243137", " trzeliang@yahoo.com", "", " House No G 365, 3rd Mile, Opposite ARTC, P.O. Dimapur, East, District Dimapur 797112, Nagaland "},
		{"Nagaland", "Pfutsero", "Neiba Kronu", "नागालैण्ड", "पफुटसेरो", "Neiba Kronu",  "  9436005156", "", "", " nkronu@yahoo.co.in", "", " Resident of Kami Village-P/o, P/S Pfutsero, Phek, Nagaland-797107 "},
		{"Nagaland", "Phek", "Kuzholuzo Nienu", "नागालैण्ड", "फेक", "Kuzholuzo Nienu",  "  9436000219", "", "", " nagaministerhealth@yahoo.com", "", " Permanent residing Phek Town, PO & PS Phek, District Phek and Presently residing at A205, Wood Rige Home Thugaba, Kohima Science College Road, Jotsoma, Kohima Nagaland 797001 "},
		{"Nagaland", "Phomching", "Pohwang Konyak", "नागालैण्ड", "फॉमचिंग", "Pohwang Konyak",  "  9612880916", "7058419334", "", "", "", " Sheanghah Tangten Village Pin No.798621 Nagaland "},
		{"Nagaland", "Pughoboto", "Y. Vikheho Swu", "नागालैण्ड", "पुगोबोटो", "Y. Vikheho Swu",  "  9436002579", "", "", " vikheho@yahoo.com", "", " Ghathashi Village ,Sub Div.Pughoboto Dist.Lunheboto Nagaland "},
		{"Nagaland", "Pungro Kiphire", "T. Torechu", "नागालैण्ड", "पुंगरो किफिर", "T. Torechu",  "  9436000122", "", "", "", "", " Pungro Town, BPO Pungro, PO Kiphire, PS Pungro "},
		{"Nagaland", "Sanis", "Mhathung Yanthan", "नागालैण्ड", "सानिस", "Mhathung Yanthan",  "  9436000483", "", "", " mhayanthan@gmail.com", "", " Forest Colony H.No 121, Kohlma-797001, Nagaland "},
		{"Nagaland", "Satakha", "G. Kaito Aye", "नागालैण्ड", "सातख", "G. Kaito Aye",  "  9436005243", "", "", "", "", " House No.6B Satoi Village, Dist., Zunheboto, Nagaland, Pin-798620 "},
		{"Nagaland", "Seyochung Sitimi", "V. Kashiho Sangtam", "नागालैण्ड", "सेयोचुंग सीतिमी", "V. Kashiho Sangtam",  "  9436000037", "", "", " kashihosangtam@gmail.com", "", " Permanent residence of New Monger, District Kiphire and Presently residing at Burma Camp, Veterinary Colony, Dimapur, District Dimapur, Nagaland "},
		{"Nagaland", "Shamator Chessore", "Toshi Wungtung", "नागालैण्ड", "शमटोर चेसोर", "Toshi Wungtung",  "  8787717301", " 8974798802", "", " saramatiapple@gmail.com", "", " House No. 36, ADC Ward, PS. Shamator, Tuensang District 798612 "},
		{"Nagaland", "Southern Angami-I", "Vikho-o YhoshÜ", "नागालैण्ड", "दक्षिणी अंगामी-I", "Vikho-o YhoshÜ",  "  9436000086", "", "", "", "", " Kigwema Village, Kohima Nagaland "},
		{"Nagaland", "Southern Angami-II", "Zale Neikha", "नागालैण्ड", "दक्षिणी अंगामी-II", "Zale Neikha",  "  7630878665", "", "", " zaleneikha@gmail.com", "", " Viswema Village, H.No. 36, Kohima, Nagaland "},
		{"Nagaland", "Suruhoto", "H Khehovi", "नागालैण्ड", "सुरहोतो", "H Khehovi",  "  9436002337", "", "", " kevisyepthomi@gmail.com", "", " Resident of H/No.10B, Akhakhu Village, Dist.Zunheboto, Nagalanad "},
		{"Nagaland", "Tamlu", "B. S. Nganlang Phom", "नागालैण्ड", "तमलू", "B. S. Nganlang Phom",  "  8974120324", "", "", "", "", " R/O Yongnyah Village, Dist. Longleng, Nagaland "},
		{"Nagaland", "Tapi", "Noke", "नागालैण्ड", "तापी", "Noke",  "  9436000193", "", "", "", "", " R/o Mon Village House No. & Dist. Mon Nagaland Pin 798621 "},
		{"Nagaland", "Tehok", "C.L John", "नागालैण्ड", "तेहॉक", "C.L John",  "  8414832841", "", "", "", "", " Chenwetnyu Village Mon-798621 "},
		{"Nagaland", "Tenning", "Namduadi Rangkau Zeliang", "नागालैण्ड", "टेनिंग", "Namduadi Rangkau Zeliang",  "  8787607131", " 9402679266", "", "", "", " House No 165, Colony Walford, Ward No 4, Dimapur, PO Dimapur, PS East Dimapur 797112, Nagaland "},
		{"Nagaland", "Thonoknyu", "L.khumo Khiamniungan", "नागालैण्ड", "थोंकोन्यु", "L.khumo Khiamniungan",  "  9402644769", "", "", "", "", " R/O Thonoknyu Town "},
		{"Nagaland", "Tizit", "P. Paiwang Konyak", "नागालैण्ड", "तिजीत", "P. Paiwang Konyak",  "  9862634044", " 9402025766", "", "", "", " R/o House No. 61, Sangsa Village. P.O. and P.S. Tizit Mon Dist. Nagaland "},
		{"Nagaland", "Tobu", "N. Bongkhao Konyak", "नागालैण्ड", "टोबू", "N. Bongkhao Konyak",  "  8413983302", "", "", "", "", " H.No. 41, Monyakshu Village, District Mon, Pin 798603, Nagaland "},
		{"Nagaland", "Tseminyu", "R. Khing", "नागालैण्ड", "त्समिनीयू", "R. Khing",  "  9436000350", "", "", "", "", " House No. 17, Tseminyu Village, PO/PS. Tseminyu, Pin Code 797109, District Kohima, Nagaland "},
		{"Nagaland", "Tuensang Sadar-I", "Toyang Chang", "नागालैण्ड", "तुएनसांग सदर-I", "Toyang Chang",  "  9436402366", "", "", " toyang_727@Yahoo.co.in", "", " R/o House No. 7B, Eastern Villa, Near Loyem Memorial High School, Tuensang Town "},
		{"Nagaland", "Tuensang Sadar-II", "Kejong Chang", "नागालैण्ड", "तुएनसांग सदर-II", "Kejong Chang",  "  9436830011", "", "", "", "", " R/o House No. 323, Bazar A Sector Tuensang Town Pin No. 798612 "},
		{"Nagaland", "Tuli", "Amenba Yaden", "नागालैण्ड", "तुली", "Amenba Yaden",  "  03702240130", " 9436006414", "", " amenba_dmp@yahoo.co.in", "", " R/o House No. 99, Merangkong Compound P.O. Tuli Dist. Mokokechung, Nagaland "},
		{"Nagaland", "Tyui", "Yanthungo Patton", "नागालैण्ड", "त्यौइ,", "Yanthungo Patton",  "  9436605971", "", "", "", "", " House No. 385 Duncan Basti, Dimapur, Nagaland "},
		{"Nagaland", "Wakching", "Shri. Y.m.yollow Konyak", "नागालैण्ड", "वकचिंग", "Shri. Y.m.yollow Konyak",  "  9436015080", "", "", " ymyollow@gmail.com", "", " Resident-Wakching Village ,P.O.-Naginimora Dist-Mon Nagaland.Pin -798622 "},
		{"Nagaland", "Western Angami", "Keneizhakho Nakhro", "नागालैण्ड", "पश्चिमी अंगामी", "Keneizhakho Nakhro",  "  9436005670", "", "", " keneizhakhonakhro@gmail.com", "", " H.No. 120A, Jotsoma Village, Po. Science College, Jotsoma, Kohima, Pin 797002 "},
		{"Nagaland", "Wokha", "Dr. Chumben Murry", "नागालैण्ड", "वोखा", "Dr. Chumben Murry",  "  9436009327", " 9774009327", "", " chumbenmurry@rediffmail.com", "", " Upper NST Colony Wokha Box No. 139, PO. Wokha Nagaland "},
		{"Nagaland", "Zunheboto", "K. Tokugha Sukhalu", "नागालैण्ड", "ज़ुन्हबोतो", "K. Tokugha Sukhalu",  "  9436000094", "", "", " ktsukhalu@yahoo.com", "", " H.No.14, Kawolo Village, Zunheboto, Nagaland "},

	};

}