/* Auto-generated file from db2MPjava.php*/

    package in.filternet.jantamalik.Rajya;

    public final class Punjab {

    	public static final String[][] MLAs = {

		{"Punjab", "Abohar", "Arun Narang", "पंजाब", "Abohar", "Arun Narang",  "  98889-14000", "", "", " arun.arunnarang55@gmail.com", "", " H.NO.2377,Street no 23,Abhor "}, 
		{"Punjab", "Adampur (sc)", "Pawan Kumar Tinu", "पंजाब", "Adampur (sc)", "Pawan Kumar Tinu",  "  9417033919", "", "", " kumarpawan43@yahoo.com", "", " H.No. 721/3, Mohalla Jattan Bagichi, Adampur-144102 "}, 
		{"Punjab", "Ajnala", "Harpartap Singh	", "पंजाब", "Ajnala", "Harpartap Singh	",  "  9876074954", "", "", " ", "", " Pind Lakuvala Tech Ajnala Distt Amritsar "}, 
		{"Punjab", "Amargarh", "Surjit Singh Dhiman", "पंजाब", "Amargarh", "Surjit Singh Dhiman",  "  9855147522", "", "", " Surjitsinghdhiman22@gmail.com", "", " H NO-266 Village Dirba Tehsil suman Distt sangurur "}, 
		{"Punjab", "Amloh", "Randeep Singh", "पंजाब", "Amloh", "Randeep Singh",  "  9814011401", "", "", " randeepnabha@gmail.com", "", " Sewa Bhawan Nabha, Teh. Nabha, Dist Patiala "}, 
		{"Punjab", "Amritsar Central", "Om Parkash Soni", "पंजाब", "Amritsar Central", "Om Parkash Soni",  "  9814418866", "", "", " officeopsoni @gmail.com", "", " Resident -115,Rani Ka bagh ,Amritsar ,Punjab "}, 
		{"Punjab", "Amritsar East", "Navjot Singh Sidhu", "पंजाब", "Amritsar East", "Navjot Singh Sidhu",  "  9478466666", "", "", " sidhunavjotsingh@gmail.com", "", " 110-Hply City Amritsar "}, 
		{"Punjab", "Amritsar North", "Sunil Dutti", "पंजाब", "Amritsar North", "Sunil Dutti",  "  9873056208", "8699925150", "", " adityadutta474@gmail.com.", "", " Shamsher Nagar ward No 38 House "}, 
		{"Punjab", "Amritsar South", "Inderbir Singh Bolaria", "पंजाब", "Amritsar South", "Inderbir Singh Bolaria",  "  9501400111", "", "", " inderbirsinghbolarial13@gmail.com", "", " R/O 415/13 Nawan Kot Amritsar "}, 
		{"Punjab", "Amritsar West (sc)", "Raj Kumar Verka", "पंजाब", "Amritsar West (sc)", "Raj Kumar Verka",  "  9868125444", "", "", " raj.kumar2017@yahoo.com", "", " 40-C,Kennedy Avenue, Amirtsar "}, 
		{"Punjab", "Anadpur Sahib", "Kanwar Pal Singh", "पंजाब", "Anadpur Sahib", "Kanwar Pal Singh",  "  9815600106", " 9781400106", "", " ranakp@ymail.com", "", " Village Khatana Po.Tibba Tapprian Tehsil Anandpur Sahib Dist Roopnagar "}, 
		{"Punjab", "Atam Nagar", "Simarjeet Singh Bains", "पंजाब", "Atam Nagar", "Simarjeet Singh Bains",  "  9814093795 ", " 9855093795", "", " bainssimarjeetsingh@gmail.com", "", " H. No. 9757, Street No. 5, Kot Mangal Singh, Ludhiana 141003 "}, 
		{"Punjab", "Attari (sc)", "Tarsem Singh", "पंजाब", "Attari (sc)", "Tarsem Singh",  "  9878687136", "", "", " tarsemdc2909@gmail.com", "", " Vpo Kathania Tehsil Amritsar - 2 Distt Amritsar "}, 
		{"Punjab", "Baba Bakala (sc)", "Santokh Singh", "पंजाब", "Baba Bakala (sc)", "Santokh Singh",  "  9872186026", "", "", " ", "", " VPO Bhalaipur Dogran Teh. Khadoor Sahib Dist. Taran Taran "}, 
		{"Punjab", "Balachaur", "Darshan Lal", "पंजाब", "Balachaur", "Darshan Lal",  "  ", "", "", " darshanlalmangurur@gmail.com", "", " VILLAGE MANGUPUR, P.O MAKHUPUR, TEHSIL, BALACHAUR, DIST SHAHEED BHAGAT SINGH, PUNJAB 144525 "}, 
		{"Punjab", "Balluana (sc)", "Nathu Ram", "पंजाब", "Balluana (sc)", "Nathu Ram",  "  9417263142", "", "", " nathuramballuana@gmail.com", "", " H. No. 353 Suraj Nagar W. No. 11 Malout "}, 
		{"Punjab", "Banga (sc)", "Sukhwinder Kumar", "पंजाब", "Banga (sc)", "Sukhwinder Kumar",  "  9872627998", "", "", " sukhisk@hotmail.com", "", " Sukhmani Enclave, Sotran Road, Banga District SBS Nagar District SBS Nagar "}, 
		{"Punjab", "Barnala", "Gurmeet Singh Haher", "पंजाब", "Barnala", "Gurmeet Singh Haher",  "  9780000971", "", "", " meet.hayer@gmail.com", "", " House No.B-XIII/147 Shaheed Jeeta Singh Nagar Barnala Dist.Barnala "}, 
		{"Punjab", "Bassi Pathana (sc)", "Gurpreet Singh", "पंजाब", "Bassi Pathana (sc)", "Gurpreet Singh",  "  9815765551", "", "", " accounts@degraphicsads.com", "", " House No. 109 Phase 3A, SAS Nagar, Mohali, Punjab 160059 "}, 
		{"Punjab", "Batala", "Lakhbir Singh", "पंजाब", "Batala", "Lakhbir Singh",  "  9646877777", "", "", " lodhinangalsing0007@gmail.com", "", " Village Lodhi Nangal, Teh. Batala, Dit. Gurdaspur 143602 "}, 
		{"Punjab", "Bathinda Rural (sc)", "Rupinder Kaur Ruby", "पंजाब", "Bathinda Rural (sc)", "Rupinder Kaur Ruby",  "  9464213275", "", "", " rupinderrubyaap@gmail.com", "", " H.No. 16420, Street No. 17/2, Guru Gobind Singh Nagar, Bathinda "}, 
		{"Punjab", "Bathinda Urban", "Manpreet Singh Badal", "पंजाब", "Bathinda Urban", "Manpreet Singh Badal",  "  9877900786", "", "", " manpreetbadal@outlook.com", "", " V.P.O. Badal Th.Malout District-Sri Muktar Sahib "}, 
		{"Punjab", "Bhadaur (sc)", "Pirmal Singh Dhaula", "पंजाब", "Bhadaur (sc)", "Pirmal Singh Dhaula",  "  9501005264", "", "", " pirmalsingh80@gmail.com", "", " H. No. 148, Dashmesh Nagar, Sangrur "}, 
		{"Punjab", "Bhagha Purana Tehsil", "Darshan Singh Brar", "पंजाब", "Bhagha Purana Tehsil", "Darshan Singh Brar",  "  9814466618", "", "", " ", "", " Khota Teh. Nishalsinghwala. Dist. Moga "}, 
		{"Punjab", "Bhoa (sc)", "Joginder Pal", "पंजाब", "Bhoa (sc)", "Joginder Pal",  "  9417044200", "", "", " joginderpalhalkabhoa@gmail.com", "", " Village -Bani Lodhi LAHRI MAHATAN P.O.SUNDER CHACK TEHSIL& DISTRICT-PATHANKOT "}, 
		{"Punjab", "Bholath", "Sukhpal Singh", "पंजाब", "Bholath", "Sukhpal Singh",  "  9815333333", "", "", " sukhpalkhaira@gmail.com", "", " R/O of VPO Ramgarh, Tes. Bholath Dist. Kapurthala "}, 
		{"Punjab", "Bhucho Mandi (sc)", "Pritam Singh", "पंजाब", "Bhucho Mandi (sc)", "Pritam Singh",  "  7087872818", "", "", " ", "", " Pind Kotbahi, Dist. Sri Muktsar Sahib "}, 
		{"Punjab", "Budhalada (sc)", "Budh Ram", "पंजाब", "Budhalada (sc)", "Budh Ram",  "  9815937418", "", "", " budhram1957@gmail.com", "", " Near Civil Hospital Budhlada "}, 
		{"Punjab", "Chabbewal (sc)", "Raj Kumar", "पंजाब", "Chabbewal (sc)", "Raj Kumar",  "  9815744705", "", "", " rajkumarchabbewal@gmail.com", "", " Village Manjhi, Po. Tehsil & Dist Hoshiarpur-146021 "}, 
		{"Punjab", "Chamkaur Sahib (sc)", "Charanjit Singh Channi", "पंजाब", "Chamkaur Sahib (sc)", "Charanjit Singh Channi",  "  9814460054", "", "", " mlachanni@gmail.com", "", " H. No. 1661, Kharar, Teh. Kharar, Dist. S.A.S. Nagar, Mohali "},
		{"Punjab", "Dakha", "Manpreet Singh Ayali", "पंजाब", "Dakha", "Manpreet Singh Ayali",  "  98140-46245", "", "", " manpreetsinghayali@yahoo.com", "", " Resident- V.P.O.-Gorsian Kadar Baksh ,Tehsil-Jagraon ,Distt -Ludhiana 142033 "},
		{"Punjab", "Dasuya", "Arun Dogra", "पंजाब", "Dasuya", "Arun Dogra",  "  9779700589", "", "", " rdgra445@gmail.com", "", " RESIDENT OF VILLAGE PALAHAR, TEHSIL MUKERIAN, DISTRICT HOSHIARPUR "},
		{"Punjab", "Dera Baba Nanak", "Sukhjinder Singh Randhawa", "पंजाब", "Dera Baba Nanak", "Sukhjinder Singh Randhawa",  "  9814212518", "", "", " ", "", " R/O Dharauali Hadbest no-0420,Teh Dera Baba Narak "}, 
		{"Punjab", "Dera Bassi", "Narinder Kumar Sharma", "पंजाब", "Dera Bassi", "Narinder Kumar Sharma",  "  9915751919", "", "", " nksharmamla@gmail.com", "", " H. No.176, MC-zirakpur, Tehsil-Derabessi, Dist. SAS Nagar (Mohali) pin no. 140603 "}, 
		{"Punjab", "Dharamkot", "Sukhjit Singh", "पंजाब", "Dharamkot", "Sukhjit Singh",  "  9872726180", "", "", " ", "", " H.No. 298, Village Lohgarh, Tehsil-Dharamkot Dist. Moga "}, 
		{"Punjab", "Dhuri", "Dalvir Singh Goldy", "पंजाब", "Dhuri", "Dalvir Singh Goldy",  "  9915300030", " 7087260005", " 9807000007", " dalvirgoldy@gmail.com", "", " Ward No.8-A/141, Guru Teg Bahadur Nagar Dhuri Tehsil Dhuri Dist Sangrur Dist Sangrur "}, 
		{"Punjab", "Dina Nagar (sc)", "Aruna Chaudhary", "पंजाब", "Dina Nagar (sc)", "Aruna Chaudhary",  "  9914800007", "9814072678", "", " Adesh99@gmail.com", "", " R/O Village and post office awankha teh. Distt gurdapur "}, 
		{"Punjab", "Dirba (sc)", "Harpal Singh", "पंजाब", "Dirba (sc)", "Harpal Singh",  "  9814915357", "", "", " cheemaharpaladv@gmail.com", "", " Vill. Cheema, Post Office Meemsa, Teh. Dhuri, Dist. Sangrur, Punjab "}, 
		{"Punjab", "Faridkot", "Kusaldeep Singh", "पंजाब", "Faridkot", "Kusaldeep Singh",  "  9815100595", "", "", " kikidhillon595@gmail.com", "", " Kotkapura Road Mai Godri Faridkot Dist Faridkot "}, 
		{"Punjab", "Fatehgarh Churian", "Tript Rajinder Singh", "पंजाब", "Fatehgarh Churian", "Tript Rajinder Singh",  "  9815360061", "", "", " triptrajindersinghbajwa@gmail.com", "", " R/O Civil Lines Qadian,Dist Gurdaspur "}, 
		{"Punjab", "Fatehgarh Sahib", "Kuljit Singh Nagra", "पंजाब", "Fatehgarh Sahib", "Kuljit Singh Nagra",  "  9888000020", "", "", " kuljitnagra@gmail.com", "", " R/O 305,Kartar Complex Opposit Deputy Commissioner Office,Fatehgarh Sahib "}, 
		{"Punjab", "Fazilka", "Davinder Singh Ghubaya", "पंजाब", "Fazilka", "Davinder Singh Ghubaya",  "  9592096222", "", "", " davinder.buke@gmail.com", "", " VPO Ghubaya Tehsil jalalabad Dist. Fazilka "}, 
		{"Punjab", "Ferozepur City", "Parminder Singh Pinki", "पंजाब", "Ferozepur City", "Parminder Singh Pinki",  "  9417020724", "", "", " psgi77@gmail.com", "", " 159-A Court Road Firozpur Cantt. "}, 
		{"Punjab", "Ferozepur Rural (sc)", "Satkar Kaur", "पंजाब", "Ferozepur Rural (sc)", "Satkar Kaur",  "  9815100018", "", "", " ferozepurrural077@gmail.com", "", " Shokoor, Dist. Ferozapur "}, 
		{"Punjab", "Garhshankar", "Jai Krishan", "पंजाब", "Garhshankar", "Jai Krishan",  "  9592854542", "", "", " jaisinghrouri@gmail.com", "", " RESIDENT OF NOORPUR BEDI ROAD, OPP B.A.M KHALSA COLLEGE GARHSHANKAR DIST-HOSHIARPUR "}, 
		{"Punjab", "Ghanaur", "Thekedar Madan Lal Jalalpur", "पंजाब", "Ghanaur", "Thekedar Madan Lal Jalalpur",  "  9814052349", "", "", " madanlaljalalpur@gmail.com", "", " H.No.22, Nagar panchayat Ward No.6, Ghanour, Tehsil Rajpura & Dist.Patiala "}, 
		{"Punjab", "Gidderbaha", "Amrinder Singh Alias Raja Warring", "पंजाब", "Gidderbaha", "Amrinder Singh Alias Raja Warring",  "  8872402500", "", "", " georgian2071@gmail.com", "", " H.no. 252, Aman Colony, Thandewala Road, Sri Muktsar Sahib "}, 
		{"Punjab", "Gill (sc)", "Kuldeep Singh Vaid(bulara)", "पंजाब", "Gill (sc)", "Kuldeep Singh Vaid(bulara)",  "  9872903777", "", "", " kdavaid@gmail.com", "", " H. No. 45-I, Sarabha Nagar, Ludhiana "}, 
		{"Punjab", "Gurdaspur", "Barindermeet Singh", "पंजाब", "Gurdaspur", "Barindermeet Singh",  "  9988459307", "", "", " pahraoffice@gmail.com", "", " Vill.Pahra, Ward No.9, Teh. & Dist.Gurdaspur-143521 "}, 
		{"Punjab", "Guru Har Sahai", "Gurmeet Singh Sodhi", "पंजाब", "Guru Har Sahai", "Gurmeet Singh Sodhi",  "  9818005888", "", "", " ranasodhi54@gmail.com", "", " Village Mohan ke Uttar, Tehsil Guruharsahai, Distt. Ferozepur "}, 
		{"Punjab", "Hoshiarpur", "Sunder Sham Arora", "पंजाब", "Hoshiarpur", "Sunder Sham Arora",  "  9815212222", "", "", " ssarora73@hotmail.com", "", " Resident of H.No. 152, Shankar nagar Fatehgarh Road, Hoshiarpur "}, 
		{"Punjab", "Jagraon (sc)", "Saravjit Kaur", "पंजाब", "Jagraon (sc)", "Saravjit Kaur",  "  9988777168", "", "", " aapsarvjit@gmail.com", "", " House No. 2950, Govt Quarters Ward No. 40 Ludhiana "}, 
		{"Punjab", "Jaitu (sc)", "Baldev Singh", "पंजाब", "Jaitu (sc)", "Baldev Singh",  "  9501200366", "", "", " baldevsinghjaito@gmail.com", "", " House No.125A, Ward No.4 Jaito Dist Faridkot "},
		{"Punjab", "Jalalabad", "Raminder Singh Awla", "पंजाब", "Jalalabad", "Raminder Singh Awla",  "  98145-30882", "", "", " awla.raminder@gmail.com", "", " Resident-Guruharsahai Ferozepur Punjab -152022 "},
		{"Punjab", "Jalandhar Cantt.", "Pargat Singh Powar", "पंजाब", "Jalandhar Cantt.", "Pargat Singh Powar",  "  9463500077", "", "", " sainiks3@gmail.com", "", " H.No. 5, Dasmesh Avenue, Mithapur, Jalandhar "},
		{"Punjab", "Jalandhar Central", "Rajinder Beri", "पंजाब", "Jalandhar Central", "Rajinder Beri",  "  9814468325", "", "", " rajinderberi181@gmail.com", "", " House no 390/7, Central town, Jalandhar "}, 
		{"Punjab", "Jalandhar North", "Avtar Singh Junior", "पंजाब", "Jalandhar North", "Avtar Singh Junior",  "  9888869000", "", "", " juniorsanghera@gmail.com", "", " OPPOSITE RAILWAY ROAD ,JALANDHAR CITY "}, 
		{"Punjab", "Jalandhar West (sc)", "Sushil Kumar", "पंजाब", "Jalandhar West (sc)", "Sushil Kumar",  "  9915900902", "", "", " daliaclinic17@gmail.com", "", " House no 19, Guru Ravidass Nagar, Basti Danishmandan Jalandhar "}, 
		{"Punjab", "Jandiala (sc)", "Sukhwinder Singh", "पंजाब", "Jandiala (sc)", "Sukhwinder Singh",  "  8195910007", "", "", " sukh592@gmail.com", "", " Resident of VPO Bundala Dist.Amritsar "}, 
		{"Punjab", "Kapurthala", "Rana Gurjit Singh", "पंजाब", "Kapurthala", "Rana Gurjit Singh",  "  9815900901", "", "", " ranagurjeetsingh@gmail.com", "", " Ekta Bhawana Circular Road Kanpurthala "}, 
		{"Punjab", "Kartarpur (sc)", "Ch. Surinder Singh", "पंजाब", "Kartarpur (sc)", "Ch. Surinder Singh",  "  9417020741", "", "", " ch.surindersingh15@gmail.com", "", " vpo dhaliwal,distt jalandhar "}, 
		{"Punjab", "Khadoor Sahib", "Ramanjeet Singh Sahota Sikki", "पंजाब", "Khadoor Sahib", "Ramanjeet Singh Sahota Sikki",  "  9814418805", "", "", " ramanjitsinghsikki05@gmail.com", "", " H. no. 144, phase -1 complex goindwal sahib 143422 "}, 
		{"Punjab", "Khanna", "Gurkirat Singh", "पंजाब", "Khanna", "Gurkirat Singh",  "  9815100019", "", "", " mankiratsinghtw@gmail.com", "", " Resident of Kotli House, Near PWD Rest House, Vill.Village Bhattian, Khanna, Dist.Ludhiana, PB "}, 
		{"Punjab", "Kharar", "Kanwar Sandhu", "पंजाब", "Kharar", "Kanwar Sandhu",  "  9779580011", "", "", " sankanwar@gmail.com", "", " #248, WWRW soc., Block C, kansal, tehsil kharar, dist. Sahibjada Ajit Singh Nagar 160103 "}, 
		{"Punjab", "Khemkaran", "Sukhpal Singh Bhullar", "पंजाब", "Khemkaran", "Sukhpal Singh Bhullar",  "  9814000002", "", "", " sukhpalbhullar@yahoo.com", "", " Vill. Mehmood Pura, Teh. Patti Dist. Taran Taran "}, 
		{"Punjab", "Kotkapura", "Kultar Singh", "पंजाब", "Kotkapura", "Kultar Singh",  "  9216400457", "", "", " kultarsinghsandhwan@gmail.com", "", " House No. 350, VPO Sandhwan, Tehsil Kotkapura Dist. Faridkot "}, 
		{"Punjab", "Lambi", "Parkash Singh", "पंजाब", "Lambi", "Parkash Singh",  "  01637-244671", "", "", " ", "", " V&P.O. Badal, Tehsil Malout, District Sri Muktsar Sahib, Punjab "}, 
		{"Punjab", "Lehra", "Parminder Singh", "पंजाब", "Lehra", "Parminder Singh",  "  09915178677", "", "", " dhindsa_parminder@yahoo.co", "", " UBHAWAL, DISTT. SANGRUR, PUNJAB "}, 
		{"Punjab", "Ludhiana Central", "Surinder Kumar Dawar", "पंजाब", "Ludhiana Central", "Surinder Kumar Dawar",  "  9814087944", "", "", " officcofdawar@gmail.comis@officcofskd", "", " B-111-327, Kucha Pandit Beli Ram,Near Police Station Daresi, Ludhiana, "}, 
		{"Punjab", "Ludhiana East", "Sanjeev Talwar", "पंजाब", "Ludhiana East", "Sanjeev Talwar",  "  098728-54951", "", "", " sanjaytalwar2224613@gmail.com", "", " B-XXIII-4942, Ram Nagar, Samrala Road, Ludhiana 141008 "}, 
		{"Punjab", "Ludhiana North", "Rakesh Pandey", "पंजाब", "Ludhiana North", "Rakesh Pandey",  "  9779400342", "", "", " rakeshpanday@gmail.com", "", " 21-C, South City, Village Ayalikurd, Ludhiana 142027 "}, 
		{"Punjab", "Ludhiana South", "Balvinder Singh", "पंजाब", "Ludhiana South", "Balvinder Singh",  "  9814027846", "", "", " bainselection2017@gmail.com", "", " House No 9757, Street No 5 Kot Mangal Singh Ludhiana-1410003 "}, 
		{"Punjab", "Ludhiana West", "Bharat Bhushan", "पंजाब", "Ludhiana West", "Bharat Bhushan",  "  9878316567", "", "", " mamtasharma7174@yahoo.com", "", " 50, Model Gram, Ludhiana "}, 
		{"Punjab", "Majitha", "Bikram Singh", "पंजाब", "Majitha", "Bikram Singh",  "  9814000001", "", "", " bikramsinghmajithi96@gmail.com", "", " 97-A Ward No.-5 Manjitha, Tehsil and District Amritsar Punjab. "}, 
		{"Punjab", "Malerkotla", "Razia Sultana", "पंजाब", "Malerkotla", "Razia Sultana",  "  9815623000", "", "", " raziasultanamkh@gmail.com", "", " Resident-Malerkotla House Village Hathoa Malerkotla Dist-Sangrur 148023 "}, 
		{"Punjab", "Malout (sc)", "Ajaib Singh Bhatti", "पंजाब", "Malout (sc)", "Ajaib Singh Bhatti",  "  9815472729", "", "", " guraman04@gmail.com", "", " 36 Model Town Phase III, Bathinda "}, 
		{"Punjab", "Mansa", "Nazar Singh Manshahia", "पंजाब", "Mansa", "Nazar Singh Manshahia",  "  9878950514", "", "", " manshahia07@yahoo.com", "", " 145, Dav School Street, Water Works Road, mansa "}, 
		{"Punjab", "Maur", "Jagdev Singh", "पंजाब", "Maur", "Jagdev Singh",  "  9463841121", "", "", " ", "", " Swaitch, Tehsil Maur, District Bathinda "}, 
		{"Punjab", "Mehal Kalan (sc)", "Kulwant Singh Pandori", "पंजाब", "Mehal Kalan (sc)", "Kulwant Singh Pandori",  "  9815923957", "", "", " ", "", " Resident of 145 Village Pandav Teh. & Dist.Barnala "}, 
		{"Punjab", "Moga", "Harjot Kamal Singh", "पंजाब", "Moga", "Harjot Kamal Singh",  "  775400001", "", "", " harjot33@live.com", "", " w no.1 st no.10, amritsar road , sant nagar , moga -142001 "},
		{"Punjab", "Mukerian", "Indu Bala", "पंजाब", "Mukerian", "Indu Bala",  "  9463703686", "", "", " ", "", " Krishana Gali Mukerian, Tehsil Mukerian, Distt Hoshiarpur (Punjab) "},
		{"Punjab", "Muktsar", "Kanwarjit Singh", "पंजाब", "Muktsar", "Kanwarjit Singh",  "  9688800001", "", "", " rosybarkandi@gmail.com", "", " P VILLAGE & POST OFFICE BARKANDI DISTRICT MUKTSAR (PUNJAB) 152026 "},
		{"Punjab", "Nabha (sc)", "Sadhu Singh", "पंजाब", "Nabha (sc)", "Sadhu Singh",  "  9815545390", "", "", " ", "", " H. No. 06, Birh Amloh, Tehsil Amloh, Dist. Fatehgarh Sahib (Punjab) "}, 
		{"Punjab", "Nakodar", "Gurpratap Singh", "पंजाब", "Nakodar", "Gurpratap Singh",  "  9781381963", "", "", " gurpratapwadala@yahoo.com", "", " H.No. 2, Village Wadala, Jalandhar "}, 
		{"Punjab", "Nawan Shahr", "Angad Singh", "पंजाब", "Nawan Shahr", "Angad Singh",  "  9888020444", "", "", " angadnsr@gmail.com", "", " h. no. 157, vill. saloh teh nawanshahr, distt s.b.s nagar "}, 
		{"Punjab", "Nihal Singh Wala (sc)", "Manjit Singh", "पंजाब", "Nihal Singh Wala (sc)", "Manjit Singh",  "  9914500289", "", "", " ", "", " Village Bilaspur tehsil, Nihal singh wala Dist. Moga 142039 "}, 
		{"Punjab", "Pathankot", "Amit Vij", "पंजाब", "Pathankot", "Amit Vij",  "  09871400099", "", "", " amit.vij911@gmail.com", "", " H.No. 269, Dashmesh Colony, Patel Nagar, Patahnkot-145001 "}, 
		{"Punjab", "Patiala", "Amarinder Singh", "पंजाब", "Patiala", "Amarinder Singh",  "  9871200042", "", "", " yuvie_42@hotmail.com", "", " H. No. 1669, New Moti Bagh Colony, Patiala "}, 
		{"Punjab", "Patiala Rural", "Brahm Mohindra", "पंजाब", "Patiala Rural", "Brahm Mohindra",  "  9815014500", "", "", " brahm_mohindra@yahoo.com", "", " 6, The Uppoermall, Patiala 147001 Punjab "}, 
		{"Punjab", "Patti", "Harminder Singh Gill", "पंजाब", "Patti", "Harminder Singh Gill",  "  9814451044", "", "", " h.s.gill2400@gmail.com", "", " Ward No 17 ,Garden Colony Patti "}, 
		{"Punjab", "Payal (sc)", "Lakhvir Singh", "पंजाब", "Payal (sc)", "Lakhvir Singh",  "  9915100866", "", "", " lakhvirsinghmahto@yahoo.com", "", " Ward No. 2 Payal dist. Ludhiana (Punjab) "},
		{"Punjab", "Phagwara (sc)", "Balwinder Singh Dhaliwal", "पंजाब", "Phagwara (sc)", "Balwinder Singh Dhaliwal",  "  9855233010", "", "", " balwinder.dhaliwal2019@gmail.com", "", " Stree No. 5, Sahibjada Ajit Singh Nagar Phagwara "},
		{"Punjab", "Phillaur (sc)", "Baldev Singh", "पंजाब", "Phillaur (sc)", "Baldev Singh",  "  9815040054", "", "", " ", "", " H. NO.121, VILLAGE KHAIHIRA, TEHSIL PHILLAUR, DISTRICT JALANDHAR "},
		{"Punjab", "Qadian", "Fatehjang Singh Bajwa", "पंजाब", "Qadian", "Fatehjang Singh Bajwa",  "  9876500786", "", "", " ", "", " Resident of Railway Road (Sant Nagar) Qadian, Dist.Gurdaspur Punjab "}, 
		{"Punjab", "Raikot (sc)", "Jagtar Singh", "पंजाब", "Raikot (sc)", "Jagtar Singh",  "  094630086", "01624271800", "", " jhissowal@gmail.com", "", " H.NO-126 HADBASI NAGAR 0081 TEH RAIKOT LUDHINA PIND CODE 141104 "}, 
		{"Punjab", "Raja Sansi", "Sukhbinder Singh Sarkaria", "पंजाब", "Raja Sansi", "Sukhbinder Singh Sarkaria",  "  9814050171", "", "", " ", "", " Village Dhaul Kalan, P.O Rajasansi Tahsil And Distt Amritsar "}, 
		{"Punjab", "Rajpura", "Hardial Singh", "पंजाब", "Rajpura", "Hardial Singh",  "  9872512000", "", "", " dccrpatiala@gmail.com", "", " H. No 8 Shaheed Bhagat Singh Colony, Rajpura Patiala "}, 
		{"Punjab", "Rampura Phul", "Gurpreet Singh Kangar", "पंजाब", "Rampura Phul", "Gurpreet Singh Kangar",  "  9876096155", "", "", " ", "", " Village Kangar, Tehsil Phul, Dist. Bhathinda "}, 
		{"Punjab", "Rupnagar", "Amarjit Singh", "पंजाब", "Rupnagar", "Amarjit Singh",  "  9599326931", "", "", " amarjeetsandoa@gmail.com", "", " Village Sandoa Po. Nurpur Bedi, Tehsil Shri Anandpur Sahib Dist Pupnagar PB "}, 
		{"Punjab", "S.a.s. Nagar", "Balbir Singh Sidhu", "पंजाब", "S.a.s. Nagar", "Balbir Singh Sidhu",  "  9872671010", "", "", " mlabalbirsindhu@gmail.com", "", " Resident of 2222, phase 7, Mohali Punjab 160060 "}, 
		{"Punjab", "Sahnewal", "Sharanjit Singh", "पंजाब", "Sahnewal", "Sharanjit Singh",  "  9779344466", "", "", " dhillon.snehwal17@gmail.com", "", " Resident Of house NO.60,Panchseel vihar , Barewal Octroi,Post Road Near Magnet resorts Ludhina Punjab "}, 
		{"Punjab", "Samana", "Rajinder Singh", "पंजाब", "Samana", "Rajinder Singh",  "  9779350003", "", "", " ", "", " Village Asarpur PO Jogipur Tehsil & Dist Patiala "}, 
		{"Punjab", "Samrala", "Amrik Singh", "पंजाब", "Samrala", "Amrik Singh",  "  9815535553", "", "", " amriksinghmlasamrala@gmail.com", "", " H. No. 181, Rama Mandi, Ward No. 13, Samrola Dist. Ludhiana Punjab 141114 "}, 
		{"Punjab", "Sangrur", "Vijay Inder Singla", "पंजाब", "Sangrur", "Vijay Inder Singla",  "  9013180244", "", "", " vijayindersingla@gmail.com", "", " R/O Singla Niwas,Haripur Road Dhuri Bypass Sangrur 148001 "}, 
		{"Punjab", "Sanour", "Harinder Pal Singh Chandumajra", "पंजाब", "Sanour", "Harinder Pal Singh Chandumajra",  "  7837170010", "", "", " hpchandumajra@gmail.com", "", " H. No. 34, Village Chandumajra, P.O. Bansantpuram, Rajpura (Punjab) "}, 
		{"Punjab", "Sardulgarh", "Dilraj Singh", "पंजाब", "Sardulgarh", "Dilraj Singh",  "  9814345444", "", "", " dsbhundar1@gmail.com", "", " Village Bhunder P.O.Sardulgarh Dist. Mansa "},
		{"Punjab", "Shahkot", "Hardev Singh", "पंजाब", "Shahkot", "Hardev Singh",  "  9814037387 ", " 8725037387", "", " hardevsinghladdi@gmail.com", "", " Village Salah Nagar, PO Malsian, Dist. Jalandhar "},
		{"Punjab", "Sham Chaurasi (sc)", "Pawan Kumar Adia", "पंजाब", "Sham Chaurasi (sc)", "Pawan Kumar Adia",  "  9814362962", "", "", " saurabhpawanaadia@gmail.com", "", " H.No. 152-L, Model Town, Hoshiarpur "},
		{"Punjab", "Shutrana (sc)", "Nirmal Singh", "पंजाब", "Shutrana (sc)", "Nirmal Singh",  "  9815017781", "", "", " nsshutrana@gmail.com", "", " Resident-10/6 Gharami Patti Samana Distt, Patiala PB 147101 "}, 
		{"Punjab", "Sri Hargobindpur (sc)", "Balwinder Singh", "पंजाब", "Sri Hargobindpur (sc)", "Balwinder Singh",  "  9815335757", "", "", " ashokbac@yahoo.in", "", " Village Shahbad, PO. Umarpura, Tehsil Batala, District Gurdaspur-143505 "}, 
		{"Punjab", "Sujanpur", "Dinesh Singh", "पंजाब", "Sujanpur", "Dinesh Singh",  "  9815843304", "", "", " bjpmission2017@yahoo.com", "", " Village Pangol tehsil Distt pathankot "}, 
		{"Punjab", "Sultanpur Lodhi", "Navtej Singh", "पंजाब", "Sultanpur Lodhi", "Navtej Singh",  "  9872213256", "", "", " ", "", " Vill.Bussowal Teh. Sultanpur Lodhi "}, 
		{"Punjab", "Sunam", "Aman Arora", "पंजाब", "Sunam", "Aman Arora",  "  9779905555", "", "", " amanarora1280@gmail.com", "", " HNO. 131-B, Ward No.2, Sunam, Dist. Sangrur, Punjab-148028 "}, 
		{"Punjab", "Talwandi Sabo", "Baljinder Kaur", "पंजाब", "Talwandi Sabo", "Baljinder Kaur",  "  8427712105", "", "", " baljinderkauraap2@gmail.com", "", " Ramtirth Jagga Tehsil Talwandi Sabo District Bathinda "}, 
		{"Punjab", "Tarn Taran", "Dharambir Agnihotri", "पंजाब", "Tarn Taran", "Dharambir Agnihotri",  "  9814280180", "", "", " dharambiragnihotri@gmail.com", "", " H.NO. 802 PREM NAGAR JANDIALA ROAD TARN TARAN "}, 
		{"Punjab", "Urmar", "Sangat Singh", "पंजाब", "Urmar", "Sangat Singh",  "  9814225999", "", "", " SSgilzianoffice2017@email.com", "", " Vill. Gilzian P.O. Miani, Tehsil Dasuya District Hoshiarpur "}, 
		{"Punjab", "Zira", "Kulbir Singh", "पंजाब", "Zira", "Kulbir Singh",  "  9855550113", "", "", " kulbirsinghzira@gmail.com", "", " R/O Basti Butwali Dakli Baik Gujara Taiser jila Firojpur "}, 


	};

}