/* Auto-generated file from db2MPjava.php*/

    package in.filternet.jantamalik.Rajya;

    public final class Uttarakhand {

    	public static final String[][] MLAs = {

		{"Uttarakhand", "Almora", "Raghunath Singh Chauhan", "उत्तराखण्ड", "Almora", "Raghunath Singh Chauhan",  "  9412044339", "", "", "", "", " Chinakhan Gharnola Almora Dist Almora "}, 
		{"Uttarakhand", "B.h.e.l. Ranipur", "Adesh Chauhan	", "उत्तराखण्ड", "B.h.e.l. Ranipur", "Adesh Chauhan	",  "  9719000572", "", "", " adeshchouhan20@gmail.com", "", " R/O Vill Post Bhadrabad Haridwar UK "}, 
		{"Uttarakhand", "Badrinath", "Mahendra Prasad", "उत्तराखण्ड", "Badrinath", "Mahendra Prasad",  "  9412953975", " 800671737", "", " mahendra.p.bhatt@gmail.com", "", " Village Bhamanthala, P.O. Thalaband, Teh. Pokhri Dist. Chamoli "}, 
		{"Uttarakhand", "Bageshwar(sc)", "Chandan Ram Dass", "उत्तराखण्ड", "Bageshwar(sc)", "Chandan Ram Dass",  "  9412038757", "", "", " chandan.dass77@gmail.com", "", " Bhagirathi Patralay Bageshwar Distt. Bageshwar "}, 
		{"Uttarakhand", "Bajpur(sc)", "Yashpal Arya", "उत्तराखण्ड", "Bajpur(sc)", "Yashpal Arya",  "  9997196151", "", "", "", "", " Village Chhadiyal Suyal, Post Office Manpur Paschim, Haldwani "}, 
		{"Uttarakhand", "Bhagwanpur(sc)", "Mamta Rakesh	", "उत्तराखण्ड", "Bhagwanpur(sc)", "Mamta Rakesh	",  "  8791820873", "", "", " mamtarakeshmla@gmail.com", "", " Nagar Panchayat & Post Tehsil Bhagwanpur Haridwar "}, 
		{"Uttarakhand", "Bhimtal", "Ram Singh Kaira", "उत्तराखण्ड", "Bhimtal", "Ram Singh Kaira",  "  9758000007", "", "", "", "", " Kedagaon Po. Josuda Dist.Nanital "}, 
		{"Uttarakhand", "Chakrata(st)", "Pritam Singh", "उत्तराखण्ड", "Chakrata(st)", "Pritam Singh",  "  0135-2712216", " 8477888862", "", " singhpsingh12@gmail.com", "", " Village Barnard Bastil, Post Office Barnard, Pargna Jaunsar Babr, Tehsil Tyuni, Dist Dehradun "}, 
		{"Uttarakhand", "Champawat", "Kailash Chandra", "उत्तराखण्ड", "Champawat", "Kailash Chandra",  "  8449088888", "", "", " k_tripati68@yahoo.com", "", " Malli Madali Champatwat Post Office Champawat, Tehsil & Dist Champawat "}, 
		{"Uttarakhand", "Chaubattakhal", "Satpal Maharaj	", "उत्तराखण्ड", "Chaubattakhal", "Satpal Maharaj	",  "  9810990009", "", "", " writer@satpalmaharaj.in", "", " H. No. 45, Vill Sediagad, P.O. Sediakhal, Teh. Chaubattakhal, Distt Pauri Garhwal 246169 "}, 
		{"Uttarakhand", "Dehradun Cantt", "Shri Harbans Kapoor", "उत्तराखण्ड", "Dehradun Cantt", "Shri Harbans Kapoor",  "  9719233999", "", "", " contactharbanskapoor@gamil.com", "", " Resi-223 Indira Nagar Colony PO. New Forest, Dehradun "}, 
		{"Uttarakhand", "Deoprayag", "Vinod Kandari", "उत्तराखण्ड", "Deoprayag", "Vinod Kandari",  "  9412029196", "", "", " vinodkandari@gmail.com", "", " Ganesh Market, Post Shrinagar, District Podi Garhwal "}, 
		{"Uttarakhand", "Dhanolti", "Pritam Singh Panwar", "उत्तराखण्ड", "Dhanolti", "Pritam Singh Panwar",  "  9412077574", "", "", " pritamyamnotri@gmail.com", "", " Dayan Patti Dhanolti, Dist. Tehri Garhwal "}, 
		{"Uttarakhand", "Dharampur", "Vinod Chamoli", "उत्तराखण्ड", "Dharampur", "Vinod Chamoli",  "  9410148510", "", "", " vinod.chamoli103@gmail.com", "", " 103/6, Old Nehru Colony DDN "}, 
		{"Uttarakhand", "Dharchula", "Harish Singh", "उत्तराखण्ड", "Dharchula", "Harish Singh",  "  7055700007", " 9639282500", "", " harishdhami1976@gmail.com", "", " Village Madkot, post Madkot, Tehsil Munasyari Dist Pithoragarh "}, 
		{"Uttarakhand", "Didihat", "Vishan Singh", "उत्तराखण्ड", "Didihat", "Vishan Singh",  "  9411114876", "", "", " bishansinghchuphal.13@gmail.com", "", " Ambedkar Ward Didihat Post Didihat Dist. Pithoragarh "}, 
		{"Uttarakhand", "Doiwala", "Trivendra Singh Rawat", "उत्तराखण्ड", "Doiwala", "Trivendra Singh Rawat",  "  9412053515", "", "", " tsrawatbjp@gmail.com", "", " S-3C-130, Defence Colony, Dehrahdun Uttrakhand "}, 
		{"Uttarakhand", "Dwarahat", "Mahesh Singh Negi", "उत्तराखण्ड", "Dwarahat", "Mahesh Singh Negi",  "  9412085085", "", "", " negimahesh1963@yahoo.in", "", " Vill.Bamanpuri P.O. & Teh. Dwarahat Dist. Almora "}, 
		{"Uttarakhand", "Gadarpur", "Arvind Pandey", "उत्तराखण्ड", "Gadarpur", "Arvind Pandey",  "  9412089301", "", "", "", "", " Santoshnagar Post Gularbhoj, Tehsil Gadarpur, Distt. Udhamsinghnagar, Uttarakhand "}, 
		{"Uttarakhand", "Gangolihat(sc)", "Meena Gangola", "उत्तराखण्ड", "Gangolihat(sc)", "Meena Gangola",  "  9917597083", "", "", "", "", " Village Tuproli, post Sagadi "}, 
		{"Uttarakhand", "Gangotri", "Gopal Singh Rawat", "उत्तराखण्ड", "Gangotri", "Gopal Singh Rawat",  "  9456590802", "", "", " gopalrawat100@gmail.com", "", " Purani Kachahari Road, Post Uttarkashi, Tehasil Makhadi, Dist. Uttarkashi "}, 
		{"Uttarakhand", "Ghanshali(sc)", "Shakti Lal Shah", "उत्तराखण्ड", "Ghanshali(sc)", "Shakti Lal Shah",  "  9639943831", "", "", "", "", " Gram Chaji Malli P-o Chanji Hindrao Ghansali Tehri Garhwal "}, 
		{"Uttarakhand", "Haldwani", "Indira Hridayesh", "उत्तराखण्ड", "Haldwani", "Indira Hridayesh",  "  9837092315", " 05946-220666", "", " dr.indirahridayeshinc@gmail.com", "", " Sankalan civil lines Haldwani, Nainital "}, 
		{"Uttarakhand", "Haridwar", "Mr. Madan Kaushik	", "उत्तराखण्ड", "Haridwar", "Mr. Madan Kaushik	",  "  9837213339", "", "", " madankaushik25@gmail.com", "", " H. No. 224-B, Gali No. 7 , KHanna Nagar, Jwalapur , Dist Haridwar "}, 
		{"Uttarakhand", "Haridwar Rural", "Yatishwaranand	", "उत्तराखण्ड", "Haridwar Rural", "Yatishwaranand	",  "  9837002832", "", "", " swami.yatshwarnand.com", "", " Ved Mandir Jwalapur Haridwar "}, 
		{"Uttarakhand", "Jageshwar", "Govind Singh Kunjwal", "उत्तराखण्ड", "Jageshwar", "Govind Singh Kunjwal",  "  9456590840", " 9412087088", "", "", "", " Village Kunj, Post & Tehsil Jainti, Dist Almora "}, 
		{"Uttarakhand", "Jaspur", "Adesh Singh", "उत्तराखण्ड", "Jaspur", "Adesh Singh",  "  9837033279", "", "", " adeshsinghchauhan93@gmail.com", "", " Village Niwarmundi, Post Office Jaspur, Dist Udham Singh Nagar "}, 
		{"Uttarakhand", "Jhabrera (sc)", "Desraj Karanwal	", "उत्तराखण्ड", "Jhabrera (sc)", "Desraj Karanwal	",  "  9411501545", "", "", " deshraj29vs-jhabrera@gmail.com", "", " 1559 Preet, Vihar Colony, Ganeshpur, Roorkee, Dist Haridwar, Permanent Address-Susadi Khurd, Pargana Monglor, Tehsil Roorkee, Distt Haridwar "}, 
		{"Uttarakhand", "Jwalapur (sc)", "Suresh Rathor	", "उत्तराखण्ड", "Jwalapur (sc)", "Suresh Rathor	",  "  9719411066", "", "", " sureshrathore.uk@gmail.com", "", " C-77A Shastri Nagar, Jwalapur, Haridwar "}, 
		{"Uttarakhand", "Kaladhungi", "Bansidhar Bhagat", "उत्तराखण्ड", "Kaladhungi", "Bansidhar Bhagat",  "  9412087147", "", "", " bansidhar.bhagat3@gmail.com", "", " Village Lohriyasal Malla, Distt. Nainital "}, 
		{"Uttarakhand", "Kapkote", "Balwant Singh", "उत्तराखण्ड", "Kapkote", "Balwant Singh",  "  9412094529", "", "", " balwant_bhauryal@yahoo.com", "", " KUROLI PO. SANETI DISTRICT BAGESHWAR "}, 
		{"Uttarakhand", "Karnprayag", "Surendra Singh", "उत्तराखण्ड", "Karnprayag", "Surendra Singh",  "  9412006166", " 9832423551", "", "", "", " Village Sainiyan, Post Office Shersen, Chamoli "}, 
		{"Uttarakhand", "Kashipur", "Harbhajan Singh Cheema", "उत्तराखण्ड", "Kashipur", "Harbhajan Singh Cheema",  "  9412090555", "", "", " cheemamla@gmail.com", "", " Vill. Tanda Ujjain, Chaitigaon, Kashipur, Dist. Udham Singh Nagar "}, 
		{"Uttarakhand", "Kedarnath", "Manoj Rawat", "उत्तराखण्ड", "Kedarnath", "Manoj Rawat",  "  9412109401", "", "", " manojrawat401@yahoo.co.in", "", " Vill. Bhanaj, P. O. Machkandi, Teh.Ukhimath, Dist. Rudraprayag "}, 
		{"Uttarakhand", "Khanpur", "Kunwar Parnav Singh Champion	", "उत्तराखण्ड", "Khanpur", "Kunwar Parnav Singh Champion	",  "  9759303705", "", "", " pranvchampion@gmail.com", "", " H. NO.80 RANGMAHAL LANDAURA , POST KHAS, JANPAD HARIDWAR "}, 
		{"Uttarakhand", "Khatima", "Pushkar Singh Dhami", "उत्तराखण्ड", "Khatima", "Pushkar Singh Dhami",  "  05943-250444", "", "", " pushkar.dhami@gmail.com", "", " H.No. 112, Vill. Nagta Tarai, Teh. Khatima, Udham Singh Nagar "}, 
		{"Uttarakhand", "Kichha", "Rajesh Shukla", "उत्तराखण्ड", "Kichha", "Rajesh Shukla",  "  9837055963", "", "", "", "", " A-135 Aavas Vikas Kichha "}, 
		{"Uttarakhand", "Kotdwar", "(dr) Harak Singh Rawat	", "उत्तराखण्ड", "Kotdwar", "(dr) Harak Singh Rawat	",  "  9411114793", "", "", "", "", " Shrikhot Ganganali Srinagar "}, 
		{"Uttarakhand", "Laksar", "Sanjay Gupta	", "उत्तराखण्ड", "Laksar", "Sanjay Gupta	",  "  9456590880", "", "", " contect2sanjaygupta@gmail.com", "", " Village & Po. Sultanpur, Adampur, District Haridwar "}, 
		{"Uttarakhand", "Lalkuwa", "Naveen Chandra Dumka", "उत्तराखण्ड", "Lalkuwa", "Naveen Chandra Dumka",  "  9412017266", "", "", "", "", " Village-Bametabangar, Khima, Post Office Halduchaur District Nainital "}, 
		{"Uttarakhand", "Lansdowne", "Daleep Singh Rawat	", "उत्तराखण्ड", "Lansdowne", "Daleep Singh Rawat	",  "  9412441936", "", "", " mahantdiliprawat40@gmail.com", "", " Vill.Ramisera, P.O.Dhontiyal, Badalpur Tala, "}, 
		{"Uttarakhand", "Lohaghat", "Puran Singh Fartyal", "उत्तराखण्ड", "Lohaghat", "Puran Singh Fartyal",  "  9456590892", "", "", " puranfartyal007@gmail.com", "", " Village Kalchuda Post Karankarayat Tehsil Lohaghat Dist champavat "}, 
		{"Uttarakhand", "Manglore", "Qazi Mohd Nizamuddin	", "उत्तराखण्ड", "Manglore", "Qazi Mohd Nizamuddin	",  "  9897250390", "", "", " qazinizamuddin@gmail.com", "", " HOUSE NO. 599/1, MOHD. KILA MANGLORE, DISTRICT HARIDWAR 247656 "}, 
		{"Uttarakhand", "Mussoorie", "Ganesh Joshi", "उत्तराखण्ड", "Mussoorie", "Ganesh Joshi",  "  941205751", " 0135-2710763", "", " joshi.ganesh58@gmail.com", "", " 105A, Neshvilla Road, Dehradun "}, 
		{"Uttarakhand", "Nainital(sc)", "Sanjeev Arya", "उत्तराखण्ड", "Nainital(sc)", "Sanjeev Arya",  "  8057677777", "", "", " sk.arya1978@gmail.com", "", " H.No. 198, Kusum Kheda post Manpur Haldwani, Nainital "}, 
		{"Uttarakhand", "Nanak Matta(st)", "Prem Singh", "उत्तराखण्ड", "Nanak Matta(st)", "Prem Singh",  "  9456590898", "", "", " drprem6969@gmail.com", "", " Village Sraunja Post Lamakheda Tehasil Sitarganj Distt. Udham Singh Nagar "}, 
		{"Uttarakhand", "Narendranagar", "Subodh Uniyal", "उत्तराखण्ड", "Narendranagar", "Subodh Uniyal",  "  9412077900", "", "", " subodhunial@gmail.com", "", " Narendarnagar Dist Tehari Garhwal "}, 
		{"Uttarakhand", "Pauri (sc)", "Mukesh Singh Koli", "उत्तराखण्ड", "Pauri (sc)", "Mukesh Singh Koli",  "  7055594999", "", "", "", "", " Vill. Prachiyali, Po. Prachiyali "}, 
		{"Uttarakhand", "Pirankaliyar", "Furkan Ahmad	", "उत्तराखण्ड", "Pirankaliyar", "Furkan Ahmad	",  "  8791991543", "", "", "", "", " Rampur Roorkee Post Roorkee Dist Haridwar "},
		{"Uttarakhand", "Pithoragarh", "Chandra Pant", "उत्तराखण्ड", "Pithoragarh", "Chandra Pant",  "  9411381940", "", "", " chandrapant1965@gmail.com", "", " Mohalla Khadkot, Post., Teh. & Dist. Pithoragarh "},
		{"Uttarakhand", "Pratapnagar", "Vijay Singh Panwar", "उत्तराखण्ड", "Pratapnagar", "Vijay Singh Panwar",  "  9412026384", "", "", "", "", " Sec.8D H.NO. 435 Buradi, New Delhi "},
		{"Uttarakhand", "Purola(sc)", "Raj Kumar", "उत्तराखण्ड", "Purola(sc)", "Raj Kumar",  "  9412009903", "", "", "", "", " H. No. 2/1, Village Dhari Valli, Post Naugaon, Tehsil Badkot, Dist. Uttarkashi, Uttarakhand "}, 
		{"Uttarakhand", "Raipur", "Umesh Sharma Kau", "उत्तराखण्ड", "Raipur", "Umesh Sharma Kau",  "  9837044988", "", "", " adagauvardoon@gmail.com", "", " 272 Ahosk Vihar Ajabpur Distt Deharadun "}, 
		{"Uttarakhand", "Rajpur Road(sc)", "Khajan Dass	", "उत्तराखण्ड", "Rajpur Road(sc)", "Khajan Dass	",  "  9412920646", "", "", "", "", " R/O 105 Vasant Vihar,Ashirwad Enclave,Dehradun "}, 
		{"Uttarakhand", "Ramnagar", "Diwan Singh Bisht", "उत्तराखण्ड", "Ramnagar", "Diwan Singh Bisht",  "  9837138988", "", "", "", "", " Village Shankarpur Tehsil Rampur "}, 
		{"Uttarakhand", "Ranikhet", "Karan Mahara", "उत्तराखण्ड", "Ranikhet", "Karan Mahara",  "  9411113191", "", "", " karanmahra1972@gmail.com", "", " 91/A Spring field Kumpur Area Ranikhet, Po. Ranikhet, Dist. Almora "}, 
		{"Uttarakhand", "Rishikesh", "Premchand Aggarwal	", "उत्तराखण्ड", "Rishikesh", "Premchand Aggarwal	",  "  9456590815", " 9412055276", "", " mlapremaggarwal@gmail.com", "", " 225, Ganga Vihar Colony, Rishikesh, Dist-Dehradun "}, 
		{"Uttarakhand", "Roorkee", "Pradeep Batra	", "उत्तराखण्ड", "Roorkee", "Pradeep Batra	",  "  09997777877", "", "", " pradeepbatrasafiee@gmail.com", "", " h.No 399/9, Civil Line Rurkee Haridwar "}, 
		{"Uttarakhand", "Rudraprayag", "Bharat Singh", "उत्तराखण्ड", "Rudraprayag", "Bharat Singh",  "  9412052531", "", "", " bharatsingh12@gmail.com", "", " Village Mawana, Post-Dholtir, Janpad Rudraprayag "}, 
		{"Uttarakhand", "Rudrapur", "Rajkumar Thukral", "उत्तराखण्ड", "Rudrapur", "Rajkumar Thukral",  "  9837088688", "9456590896", "", " rajkumarthukral@gmail.com", "", " R/O B 29,Adarsh Colony,Rudrpur Dist Udham Singh Nagar "}, 
		{"Uttarakhand", "Sahaspur", "Sahdev Singh Pundir", "उत्तराखण्ड", "Sahaspur", "Sahdev Singh Pundir",  "  9412007508", " 0135-2773934", "", " sahdevpundir1967@gmail.com", "", " Village & Po Sudhowala, Tehshil Vikasnagar, District Dehradun "}, 
		{"Uttarakhand", "Sitarganj", "Saurabh Bahuguna", "उत्तराखण्ड", "Sitarganj", "Saurabh Bahuguna",  "  9873917277", "", "", " saurabhbahuguna@hotmail.com", "", " 194-A Pairpura Ward No. 9, Opp. Radha Swami Satsang Bhawan Sitarganj "}, 
		{"Uttarakhand", "Someshwar(sc)", "Rekha Arya", "उत्तराखण्ड", "Someshwar(sc)", "Rekha Arya",  "  9927607880 ", " 9410556150", "", " mla.rekhaarya@gmail.com", "", " Village Sunadi, Post Ranman, Tehsil Someshwar, Dist Almoda "}, 
		{"Uttarakhand", "Srinagar", "Dr. Dhan Singh Rawat", "उत्तराखण्ड", "Srinagar", "Dr. Dhan Singh Rawat",  "  8650000797", "", "", " dr.dhansinghrawat@gmail.com", "", " Vill.Naugaon, P.O.-Dungriwal, Patti, Paudi Garhwal "}, 
		{"Uttarakhand", "Sult", "Surendra Singh Jeena", "उत्तराखण्ड", "Sult", "Surendra Singh Jeena",  "  9456590836", "", "", " jeenamla@gmail.com", "", " Village Sadigaon Post. Teh. and Dist. Almora, Uttarakhand "}, 
		{"Uttarakhand", "Tehri", "Dhan Singh Negi", "उत्तराखण्ड", "Tehri", "Dhan Singh Negi",  "  9412312386", "", "", " dsnegi.ntt@gmail.com", "", " Gram Palkot Tihar Gardval "},
		{"Uttarakhand", "Tharali (sc)", "Munni Devi", "उत्तराखण्ड", "Tharali (sc)", "Munni Devi",  "  9675089446", "", "", "", "", " Village Nalgaon Kadakot Post Office Nalgaon, Tehsil Narayanbagad "},
		{"Uttarakhand", "Vikasnagar", "Munna Singh Chauhan", "उत्तराखण्ड", "Vikasnagar", "Munna Singh Chauhan",  "  9412058700", "", "", "", "", " Village Rakhtad Post Nagyat Tehsil Kalsi, Dist Dehradun "},
		{"Uttarakhand", "Yamkeshwar", "Ritu Khanduri Bhushan", "उत्तराखण्ड", "Yamkeshwar", "Ritu Khanduri Bhushan",  "  9818001473", "", "", " ritubhushan@gmail.com", "", " 305, Som Vihar Apartment R.K.Puram, South West, Delhi-110022 "}, 
		{"Uttarakhand", "Yamunotri", "Kedar Singh", "उत्तराखण्ड", "Yamunotri", "Kedar Singh",  "  9456590803", "", "", " kedarsingh@gmail.com", "", " Village Beaf, Patti Geat, Tehsil Badkot, Po. Kharsatni, Dist. Uttarkashi "}, 

	};

}