/* Auto-generated file from db2MPjava.php*/

    package in.filternet.jantamalik.Rajya;

    public final class Uttarakhand {

    	public static final String[][] MLAs = {

		{"Uttarakhand", "Almora", "Raghunath Singh Chauhan", "उत्तराखण्ड", "अल्मोड़ा", "Raghunath Singh Chauhan",  "  9412044339", "", "", "", "", " Chinakhan Gharnola Almora Dist Almora "},
		{"Uttarakhand", "B.H.E.L Ranipur", "Adesh Chauhan", "उत्तराखण्ड", "भेल रानीपुर", "Adesh Chauhan",  "  9719000572", "", "", " adeshchouhan20@gmail.com", "", " R/O Vill Post Bhadrabad Haridwar UK "},
		{"Uttarakhand", "Badrinath", "Mahendra Prasad", "उत्तराखण्ड", "बद्रीनाथ", "Mahendra Prasad",  "  9412953975", " 800671737", "", " mahendra.p.bhatt@gmail.com", "", " Village Bhamanthala, P.O. Thalaband, Teh. Pokhri Dist. Chamoli "},
		{"Uttarakhand", "Bageshwar", "Chandan Ram Dass", "उत्तराखण्ड", "बागेश्वर", "Chandan Ram Dass",  "  9412038757", "", "", " chandan.dass77@gmail.com", "", " Bhagirathi Patralay Bageshwar Distt. Bageshwar "},
		{"Uttarakhand", "Bajpur", "Yashpal Arya", "उत्तराखण्ड", "बाजपुर", "Yashpal Arya",  "  9997196151", "", "", "", "", " Village Chhadiyal Suyal, Post Office Manpur Paschim, Haldwani "},
		{"Uttarakhand", "Bhagwanpur", "Mamta Rakesh", "उत्तराखण्ड", "भगवानपुर", "Mamta Rakesh",  "  8791820873", "", "", " mamtarakeshmla@gmail.com", "", " Nagar Panchayat & Post Tehsil Bhagwanpur Haridwar "},
		{"Uttarakhand", "Bhimtal", "Ram Singh Kaira", "उत्तराखण्ड", "भीमताल", "Ram Singh Kaira",  "  9758000007", "", "", "", "", " Kedagaon Po. Josuda Dist.Nanital "},
		{"Uttarakhand", "Chakrata", "Pritam Singh", "उत्तराखण्ड", "चकराता", "Pritam Singh",  "  0135-2712216", " 8477888862", "", " singhpsingh12@gmail.com", "", " Village Barnard Bastil, Post Office Barnard, Pargna Jaunsar Babr, Tehsil Tyuni, Dist Dehradun "},
		{"Uttarakhand", "Champawat", "Kailash Chandra", "उत्तराखण्ड", "चम्पावत", "Kailash Chandra",  "  8449088888", "", "", " k_tripati68@yahoo.com", "", " Malli Madali Champatwat Post Office Champawat, Tehsil & Dist Champawat "},
		{"Uttarakhand", "Chaubattakhal", "Satpal Maharaj", "उत्तराखण्ड", "चौबत्ताखाल", "Satpal Maharaj",  "  9810990009", "", "", " writer@satpalmaharaj.in", "", " H. No. 45, Vill Sediagad, P.O. Sediakhal, Teh. Chaubattakhal, Distt Pauri Garhwal 246169 "},
		{"Uttarakhand", "Dehradun Cantt.", "Shri Harbans Kapoor", "उत्तराखण्ड", "देहरादून कैंट.", "Shri Harbans Kapoor",  "  9719233999", "", "", " contactharbanskapoor@gamil.com", "", " Resi-223 Indira Nagar Colony PO. New Forest, Dehradun "},
		{"Uttarakhand", "Deoprayag", "Vinod Kandari", "उत्तराखण्ड", "देवप्रयाग", "Vinod Kandari",  "  9412029196", "", "", " vinodkandari@gmail.com", "", " Ganesh Market, Post Shrinagar, District Podi Garhwal "},
		{"Uttarakhand", "Dhanolti", "Pritam Singh Panwar", "उत्तराखण्ड", "धनौल्टी", "Pritam Singh Panwar",  "  9412077574", "", "", " pritamyamnotri@gmail.com", "", " Dayan Patti Dhanolti, Dist. Tehri Garhwal "},
		{"Uttarakhand", "Dharampur", "Vinod Chamoli", "उत्तराखण्ड", "धर्मपुर", "Vinod Chamoli",  "  9410148510", "", "", " vinod.chamoli103@gmail.com", "", " 103/6, Old Nehru Colony DDN "},
		{"Uttarakhand", "Dharchula", "Harish Singh", "उत्तराखण्ड", "धारचूला", "Harish Singh",  "  7055700007", " 9639282500", "", " harishdhami1976@gmail.com", "", " Village Madkot, post Madkot, Tehsil Munasyari Dist Pithoragarh "},
		{"Uttarakhand", "Didihat", "Vishan Singh", "उत्तराखण्ड", "डीडीहाट", "Vishan Singh",  "  9411114876", "", "", " bishansinghchuphal.13@gmail.com", "", " Ambedkar Ward Didihat Post Didihat Dist. Pithoragarh "},
		{"Uttarakhand", "Doiwala", "Trivendra Singh Rawat", "उत्तराखण्ड", "डोईवाला", "Trivendra Singh Rawat",  "  9412053515", "", "", " tsrawatbjp@gmail.com", "", " S-3C-130, Defence Colony, Dehrahdun Uttrakhand "},
		{"Uttarakhand", "Dwarahat", "Mahesh Singh Negi", "उत्तराखण्ड", "द्वारहाट", "Mahesh Singh Negi",  "  9412085085", "", "", " negimahesh1963@yahoo.in", "", " Vill.Bamanpuri P.O. & Teh. Dwarahat Dist. Almora "},
		{"Uttarakhand", "Gadarpur", "Arvind Pandey", "उत्तराखण्ड", "गदरपुर", "Arvind Pandey",  "  9412089301", "", "", "", "", " Santoshnagar Post Gularbhoj, Tehsil Gadarpur, Distt. Udhamsinghnagar, Uttarakhand "},
		{"Uttarakhand", "Gangolihat", "Meena Gangola", "उत्तराखण्ड", "गंगोलीहाट", "Meena Gangola",  "  9917597083", "", "", "", "", " Village Tuproli, post Sagadi "},
		{"Uttarakhand", "Gangotri", "Gopal Singh Rawat", "उत्तराखण्ड", "गंगोत्री", "Gopal Singh Rawat",  "  9456590802", "", "", " gopalrawat100@gmail.com", "", " Purani Kachahari Road, Post Uttarkashi, Tehasil Makhadi, Dist. Uttarkashi "},
		{"Uttarakhand", "Ghanshali", "Shakti Lal Shah", "उत्तराखण्ड", "घनशाली", "Shakti Lal Shah",  "  9639943831", "", "", "", "", " Gram Chaji Malli P-o Chanji Hindrao Ghansali Tehri Garhwal "},
		{"Uttarakhand", "Haldwani", "Indira Hridayesh", "उत्तराखण्ड", "हल्द्वानी", "Indira Hridayesh",  "  9837092315", " 05946-220666", "", " dr.indirahridayeshinc@gmail.com", "", " Sankalan civil lines Haldwani, Nainital "},
		{"Uttarakhand", "Haridwar", "Mr. Madan Kaushik", "उत्तराखण्ड", "हरिद्वार", "Mr. Madan Kaushik",  "  9837213339", "", "", " madankaushik25@gmail.com", "", " H. No. 224-B, Gali No. 7 , KHanna Nagar, Jwalapur , Dist Haridwar "},
		{"Uttarakhand", "Haridwar Rural", "Yatishwaranand", "उत्तराखण्ड", "हरिद्वार ग्रामीण", "Yatishwaranand",  "  9837002832", "", "", " swami.yatshwarnand.com", "", " Ved Mandir Jwalapur Haridwar "},
		{"Uttarakhand", "Jageshwar", "Govind Singh Kunjwal", "उत्तराखण्ड", "जागेश्वर", "Govind Singh Kunjwal",  "  9456590840", " 9412087088", "", "", "", " Village Kunj, Post & Tehsil Jainti, Dist Almora "},
		{"Uttarakhand", "Jaspur", "Adesh Singh", "उत्तराखण्ड", "जसपुर", "Adesh Singh",  "  9837033279", "", "", " adeshsinghchauhan93@gmail.com", "", " Village Niwarmundi, Post Office Jaspur, Dist Udham Singh Nagar "},
		{"Uttarakhand", "Jhabrera", "Desraj Karanwal", "उत्तराखण्ड", "झबरेड़ा", "Desraj Karanwal",  "  9411501545", "", "", " deshraj29vs-jhabrera@gmail.com", "", " 1559 Preet, Vihar Colony, Ganeshpur, Roorkee, Dist Haridwar, Permanent Address-Susadi Khurd, Pargana Monglor, Tehsil Roorkee, Distt Haridwar "},
		{"Uttarakhand", "Jwalapur", "Suresh Rathor	", "उत्तराखण्ड", "ज्वालापुर", "Suresh Rathor	",  "  9719411066", "", "", " sureshrathore.uk@gmail.com", "", " C-77A Shastri Nagar, Jwalapur, Haridwar "},
		{"Uttarakhand", "Kaladhungi", "Bansidhar Bhagat", "उत्तराखण्ड", "कालाढूंगी", "Bansidhar Bhagat",  "  9412087147", "", "", " bansidhar.bhagat3@gmail.com", "", " Village Lohriyasal Malla, Distt. Nainital "},
		{"Uttarakhand", "Kapkote", "Balwant Singh", "उत्तराखण्ड", "कपकोटे", "Balwant Singh",  "  9412094529", "", "", " balwant_bhauryal@yahoo.com", "", " KUROLI PO. SANETI DISTRICT BAGESHWAR "},
		{"Uttarakhand", "Karnprayag", "Surendra Singh", "उत्तराखण्ड", "कर्णप्रयाग", "Surendra Singh",  "  9412006166", " 9832423551", "", "", "", " Village Sainiyan, Post Office Shersen, Chamoli "},
		{"Uttarakhand", "Kashipur", "Harbhajan Singh Cheema", "उत्तराखण्ड", "काशीपुर", "Harbhajan Singh Cheema",  "  9412090555", "", "", " cheemamla@gmail.com", "", " Vill. Tanda Ujjain, Chaitigaon, Kashipur, Dist. Udham Singh Nagar "},
		{"Uttarakhand", "Kedarnath", "Manoj Rawat", "उत्तराखण्ड", "केदारनाथ", "Manoj Rawat",  "  9412109401", "", "", " manojrawat401@yahoo.co.in", "", " Vill. Bhanaj, P. O. Machkandi, Teh.Ukhimath, Dist. Rudraprayag "},
		{"Uttarakhand", "Khanpur", "Kunwar Parnav Singh Champion	", "उत्तराखण्ड", "खानपुर", "Kunwar Parnav Singh Champion	",  "  9759303705", "", "", " pranvchampion@gmail.com", "", " H. NO.80 RANGMAHAL LANDAURA , POST KHAS, JANPAD HARIDWAR "},
		{"Uttarakhand", "Khatima", "Pushkar Singh Dhami", "उत्तराखण्ड", "खटीमा", "Pushkar Singh Dhami",  "  05943-250444", "", "", " pushkar.dhami@gmail.com", "", " H.No. 112, Vill. Nagta Tarai, Teh. Khatima, Udham Singh Nagar "},
		{"Uttarakhand", "Kichha", "Rajesh Shukla", "उत्तराखण्ड", "किच्छा", "Rajesh Shukla",  "  9837055963", "", "", "", "", " A-135 Aavas Vikas Kichha "},
		{"Uttarakhand", "Kotdwar", "Dr. Harak Singh Rawat", "उत्तराखण्ड", "कोटद्वार ", "Dr. Harak Singh Rawat",  "  9411114793", "", "", "", "", " Shrikhot Ganganali Srinagar "},
		{"Uttarakhand", "Laksar", "Sanjay Gupta	", "उत्तराखण्ड", "लक्सर", "Sanjay Gupta	",  "  9456590880", "", "", " contect2sanjaygupta@gmail.com", "", " Village & Po. Sultanpur, Adampur, District Haridwar "},
		{"Uttarakhand", "Lalkuwa", "Naveen Chandra Dumka", "उत्तराखण्ड", "लालकुआं", "Naveen Chandra Dumka",  "  9412017266", "", "", "", "", " Village-Bametabangar, Khima, Post Office Halduchaur District Nainital "},
		{"Uttarakhand", "Lansdowne", "Daleep Singh Rawat", "उत्तराखण्ड", "लैंसडाउन", "Daleep Singh Rawat",  "  9412441936", "", "", " mahantdiliprawat40@gmail.com", "", " Vill.Ramisera, P.O.Dhontiyal, Badalpur Tala, "},
		{"Uttarakhand", "Lohaghat", "Puran Singh Fartyal", "उत्तराखण्ड", "लोहाघाट ", "Puran Singh Fartyal",  "  9456590892", "", "", " puranfartyal007@gmail.com", "", " Village Kalchuda Post Karankarayat Tehsil Lohaghat Dist champavat "},
		{"Uttarakhand", "Manglaur", "Qazi Mohd Nizamuddin	", "उत्तराखण्ड", "मंगलौर", "Qazi Mohd Nizamuddin	",  "  9897250390", "", "", " qazinizamuddin@gmail.com", "", " HOUSE NO. 599/1, MOHD. KILA MANGLORE, DISTRICT HARIDWAR 247656 "},
		{"Uttarakhand", "Mussoorie", "Ganesh Joshi", "उत्तराखण्ड", "मसूरी", "Ganesh Joshi",  "  941205751", " 0135-2710763", "", " joshi.ganesh58@gmail.com", "", " 105A, Neshvilla Road, Dehradun "},
		{"Uttarakhand", "Nainital", "Sanjeev Arya", "उत्तराखण्ड", "नैनीताल", "Sanjeev Arya",  "  8057677777", "", "", " sk.arya1978@gmail.com", "", " H.No. 198, Kusum Kheda post Manpur Haldwani, Nainital "},
		{"Uttarakhand", "Nanak Matta", "Prem Singh", "उत्तराखण्ड", "नानकमत्ता ", "Prem Singh",  "  9456590898", "", "", " drprem6969@gmail.com", "", " Village Sraunja Post Lamakheda Tehasil Sitarganj Distt. Udham Singh Nagar "},
		{"Uttarakhand", "Narendranagar", "Subodh Uniyal", "उत्तराखण्ड", "नरेंद्रनगर", "Subodh Uniyal",  "  9412077900", "", "", " subodhunial@gmail.com", "", " Narendarnagar Dist Tehari Garhwal "},
		{"Uttarakhand", "Pauri", "Mukesh Singh Koli", "उत्तराखण्ड", "पौड़ी", "Mukesh Singh Koli",  "  7055594999", "", "", "", "", " Vill. Prachiyali, Po. Prachiyali "},
		{"Uttarakhand", "Pirankaliyar", "Furkan Ahmad	", "उत्तराखण्ड", "पिरानकालियार", "Furkan Ahmad	",  "  8791991543", "", "", "", "", " Rampur Roorkee Post Roorkee Dist Haridwar "},
		{"Uttarakhand", "Pithoragarh", "Chandra Pant", "उत्तराखण्ड", "पिथौरागढ़", "Chandra Pant",  "  9411381940", "", "", " chandrapant1965@gmail.com", "", " Mohalla Khadkot, Post., Teh. & Dist. Pithoragarh "},
		{"Uttarakhand", "Pratapnagar", "Vijay Singh Panwar", "उत्तराखण्ड", "प्रतापनगर", "Vijay Singh Panwar",  "  9412026384", "", "", "", "", " Sec.8D H.NO. 435 Buradi, New Delhi "},
		{"Uttarakhand", "Purola", "Raj Kumar", "उत्तराखण्ड", "पुरोला", "Raj Kumar",  "  9412009903", "", "", "", "", " H. No. 2/1, Village Dhari Valli, Post Naugaon, Tehsil Badkot, Dist. Uttarkashi, Uttarakhand "},
		{"Uttarakhand", "Raipur", "Umesh Sharma Kau", "उत्तराखण्ड", "रायपुर", "Umesh Sharma Kau",  "  9837044988", "", "", " adagauvardoon@gmail.com", "", " 272 Ahosk Vihar Ajabpur Distt Deharadun "},
		{"Uttarakhand", "Rajpur Road", "Khajan Dass	", "उत्तराखण्ड", "राजपुर रोड", "Khajan Dass	",  "  9412920646", "", "", "", "", " R/O 105 Vasant Vihar,Ashirwad Enclave,Dehradun "},
		{"Uttarakhand", "Ramnagar", "Diwan Singh Bisht", "उत्तराखण्ड", "रामनगर", "Diwan Singh Bisht",  "  9837138988", "", "", "", "", " Village Shankarpur Tehsil Rampur "},
		{"Uttarakhand", "Ranikhet", "Karan Mahara", "उत्तराखण्ड", "रानीखेत", "Karan Mahara",  "  9411113191", "", "", " karanmahra1972@gmail.com", "", " 91/A Spring field Kumpur Area Ranikhet, Po. Ranikhet, Dist. Almora "},
		{"Uttarakhand", "Rishikesh", "Premchand Aggarwal", "उत्तराखण्ड", "ऋषिकेश", "Premchand Aggarwal",  "  9456590815", " 9412055276", "", " mlapremaggarwal@gmail.com", "", " 225, Ganga Vihar Colony, Rishikesh, Dist-Dehradun "},
		{"Uttarakhand", "Roorkee", "Pradeep Batra	", "उत्तराखण्ड", "रुड़की", "Pradeep Batra	",  "  09997777877", "", "", " pradeepbatrasafiee@gmail.com", "", " h.No 399/9, Civil Line Rurkee Haridwar "},
		{"Uttarakhand", "Rudraprayag", "Bharat Singh", "उत्तराखण्ड", "रुद्रप्रयाग", "Bharat Singh",  "  9412052531", "", "", " bharatsingh12@gmail.com", "", " Village Mawana, Post-Dholtir, Janpad Rudraprayag "},
		{"Uttarakhand", "Rudrapur", "Rajkumar Thukral", "उत्तराखण्ड", "रुद्रपुर", "Rajkumar Thukral",  "  9837088688", "9456590896", "", " rajkumarthukral@gmail.com", "", " R/O B 29,Adarsh Colony,Rudrpur Dist Udham Singh Nagar "},
		{"Uttarakhand", "Sahaspur", "Sahdev Singh Pundir", "उत्तराखण्ड", "सहसपुर", "Sahdev Singh Pundir",  "  9412007508", " 0135-2773934", "", " sahdevpundir1967@gmail.com", "", " Village & Po Sudhowala, Tehshil Vikasnagar, District Dehradun "},
		{"Uttarakhand", "Sitarganj", "Saurabh Bahuguna", "उत्तराखण्ड", "सितारगंज", "Saurabh Bahuguna",  "  9873917277", "", "", " saurabhbahuguna@hotmail.com", "", " 194-A Pairpura Ward No. 9, Opp. Radha Swami Satsang Bhawan Sitarganj "},
		{"Uttarakhand", "Someshwar", "Rekha Arya", "उत्तराखण्ड", "सोमेश्वर", "Rekha Arya",  "  9927607880 ", " 9410556150", "", " mla.rekhaarya@gmail.com", "", " Village Sunadi, Post Ranman, Tehsil Someshwar, Dist Almoda "},
		{"Uttarakhand", "Srinagar", "Dr. Dhan Singh Rawat", "उत्तराखण्ड", "श्रीनगर", "Dr. Dhan Singh Rawat",  "  8650000797", "", "", " dr.dhansinghrawat@gmail.com", "", " Vill.Naugaon, P.O.-Dungriwal, Patti, Paudi Garhwal "},
		{"Uttarakhand", "Salt", "Surendra Singh Jeena", "उत्तराखण्ड", "साल्ट", "Surendra Singh Jeena",  "  9456590836", "", "", " jeenamla@gmail.com", "", " Village Sadigaon Post. Teh. and Dist. Almora, Uttarakhand "},
		{"Uttarakhand", "Tehri", "Dhan Singh Negi", "उत्तराखण्ड", "टिहरी", "Dhan Singh Negi",  "  9412312386", "", "", " dsnegi.ntt@gmail.com", "", " Gram Palkot Tihar Gardval "},
		{"Uttarakhand", "Tharali", "Munni Devi", "उत्तराखण्ड", "थराली", "Munni Devi",  "  9675089446", "", "", "", "", " Village Nalgaon Kadakot Post Office Nalgaon, Tehsil Narayanbagad "},
		{"Uttarakhand", "Vikasnagar", "Munna Singh Chauhan", "उत्तराखण्ड", "विकासनगर", "Munna Singh Chauhan",  "  9412058700", "", "", "", "", " Village Rakhtad Post Nagyat Tehsil Kalsi, Dist Dehradun "},
		{"Uttarakhand", "Yamkeshwar", "Ritu Khanduri Bhushan", "उत्तराखण्ड", "यमकेश्वर", "Ritu Khanduri Bhushan",  "  9818001473", "", "", " ritubhushan@gmail.com", "", " 305, Som Vihar Apartment R.K.Puram, South West, Delhi-110022 "},
		{"Uttarakhand", "Yamunotri", "Kedar Singh", "उत्तराखण्ड", "यमुनोत्री", "Kedar Singh",  "  9456590803", "", "", " kedarsingh@gmail.com", "", " Village Beaf, Patti Geat, Tehsil Badkot, Po. Kharsatni, Dist. Uttarkashi "},

	};

}