package in.filternet.jantamalik.Rajya;

public final class VidhayakData {

    public static final String[][] all_MLAs = {
            //    "STATE"	    	"STATE"		    "No."	"Constituency"		    "Name of elected MLA"		    "Party affiliation"		        "चुनाव क्षेत्र"		    "निर्वाचित विधायक का नाम"		    "पार्टी संबद्धता"		    phone		        email		                                address		                                                                                     website
            {	"Bihar"	        ,	"बिहार"	    ,	"1"	,	"AGIAON (SC)"	    ,	"Prabhu Nath Prasad" 	    ,	"Janata Dal (United)"	    ,	"अगिआँव (अ.जा.)"	,	"प्रभु नाथ प्रसाद"	    ,	"जनता दल (यूनाइटेड)"   ,	"9471096769"	,	""	                                     ,	"Village-Devdi, Post-Gadhani, Thana-Charpokhari, Dist-Bhojpur"                                  ,	""	}	,
            {	"Bihar"	        ,	"बिहार"	    ,	"2"	,	"ALAMNAGAR"	        ,	"Narendra Narayan Yadav" 	,	"Janata Dal (United)"	    ,	"आलमनगर"	    ,	"नरेंद्र नारायण यादव"	    ,	"जनता दल (यूनाइटेड)"   ,	"7250351324"	,	""	                                     ,	"House No.42, Village-Balatol, Post-Nayatola, Thana-Puraini, Dist-Madhepura, Pin-852116"        ,	""	}	,
            {	"Bihar"	        ,	"बिहार"	    ,	"3"	,	"ALAULI (SC)"	    ,	"Chandan Kumar" 	        ,	"Rashtriya Janata Dal"	    ,	"अलौली (अ.जा.)"	,	"चंदन कुमार"	        ,	"राष्ट्रीय जनता दल"     ,	"9430446931"	,	""	                                     ,	"Villiage & Post- Khargi Tirasi, Dist- Khagaria"                                                ,	""	}	,
            {	"Uttar Pradesh"	,	"उत्तर प्रदेश"	,	"1"	,	"AGRA CANTT. (SC)"	,	"Girraj Singh Dharmesh" 	,	"Bharatiya Janata Party"	,	"आगरा कैंट"	    ,	"गिर्राज सिंह धर्मेश"	    ,	"भारतीय जनता पार्टी"	    ,	"9760843130"	,	""	                                     ,	"85, Defense Estate, Ph-1, PS- Sadar, Tehsil- Agra, Dist Agra, 282001, Uttar Pradesh"           ,	""	}	,
            {	"Uttar Pradesh"	,	"उत्तर प्रदेश"	,	"1"	,	"VARANASI CANTT"	,	"Saurabh Kumar Srivastava"	,	"Bharatiya Janata Party"	,	"वाराणसी कैंट"	    ,	"सौरभ कुमार श्रीवास्तव"	,	"भारतीय जनता पार्टी"	    ,	"9795350000"	,	"ssaurabhvns75@gmail.com"	            ,	"D63/6B-87 Shivaji Nagar, Tulsipur, Mehmoorganj, Varanasi, Uttar Pradesh"	                    ,	""	}	,
            {	"Uttar Pradesh"	,	"उत्तर प्रदेश"	,	"2"	,	"VARANASI NORTH"	,	"Ravindra Jaisawal"	        ,	"Bharatiya Janata Party"	,	"वाराणसी नाॅर्थ"	    ,	"रविन्द्र जायसवाल"	    ,	"भारतीय जनता पार्टी"	    ,	"9415202394"	,	"rjmla8081@gmail.com"	                ,	"H.No.C-19/27-14-3-1 Lallapura Khurd, Gulabbagh, P.S.-Sigra, Varanasi, Uttar Pradesh"	        ,	""	}	,
            {	"Uttar Pradesh"	,	"उत्तर प्रदेश"	,	"3"	,	"VARANASI SOUTH"	,	"Dr. Neelkanth Tiwari"	    ,	"Bharatiya Janata Party"	,	"वाराणसी साउथ"	,	"डाॅ. नीलकंठ तिवारी"	    ,	"भारतीय जनता पार्टी"	    ,	"9415226166"	,	"neelkanthtiwari.advocate@gmail.com"	,	"Building No. N-16/62E-A, Sudamapur, Vinayaka, Badi Gaibi, Varanasi, Uttar Pradesh" 	        ,	""	}	,
    };
}
