package in.filternet.jantamalik;

public class Election_2019 {
    public static final String[][] green_bucket = {
            //"STATE"   "No.""Constituency"		"Name of elected M.P." "Party affiliation"		"चुनाव क्षेत्र"		"निर्वाचित सांसद का नाम"		"पार्टी संबद्धता"		phone		email		address		website
            {"Andaman and Nicobar Islands", "1", "Andaman and Nicobar Islands", "Ayan Mandal", "All India Trinamool Congress", "Coming soon", "अण्डमान और निकोबार द्वीपसमूह", "अंडमान व नोकोबार द्वीप समूह", "अयन मंडल", "अखिल भारतीय तृणमूल कांग्रेस", "जल्द आ रहा है"},
            {"Andaman and Nicobar Islands", "2", "Andaman and Nicobar Islands", "Gour Chandra Majumder", "IND", "Coming soon", "अण्डमान और निकोबार द्वीपसमूह", "अंडमान व नोकोबार द्वीप समूह", "गौर चंद्र मजुमदार", "निर्दलीय", "जल्द आ रहा है"},
            {"Andaman and Nicobar Islands", "3", "Andaman and Nicobar Islands", "Paritosh Kumar Haldar", "IND", "Coming soon", "अण्डमान और निकोबार द्वीपसमूह", "अंडमान व नोकोबार द्वीप समूह", "परितोष कुमार हलधर", "निर्दलीय", "जल्द आ रहा है"},
            {"Andaman and Nicobar Islands", "4", "Andaman and Nicobar Islands", "Prakash Minj", "Bahujan Samaj Party", "Coming soon", "अण्डमान और निकोबार द्वीपसमूह", "अंडमान व नोकोबार द्वीप समूह", "प्रकाश मिंज", "बहुजन समाज पार्टी", "जल्द आ रहा है"},
            {"Andaman and Nicobar Islands", "5", "Andaman and Nicobar Islands", "S Sudershan Rao", "IND", "Coming soon", "अण्डमान और निकोबार द्वीपसमूह", "अंडमान व नोकोबार द्वीप समूह", "एस सुदर्शन राव", "निर्दलीय", "जल्द आ रहा है"},
            {"Andhra Pradesh", "1", "Amalapuram", "Chinta Anuradha", "YSR Congress Party", "Coming soon", "आन्ध्र प्रदेश", "अमलापुरम", "चिन्ता अनुराधा", "YSR कांग्रेस पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "2", "Amalapuram", "Ganti Harish Madhur", "Telugu Desam Party", "Coming soon", "आन्ध्र प्रदेश", "अमलापुरम", "गँती हरीश मधुर", "तेलुगू देशम पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "3", "Amalapuram", "Mortha Sivarama Krishna", "Pyramid Party of India", "Coming soon", "आन्ध्र प्रदेश", "अमलापुरम", "मर्तव शिवराम कृष्ण", "पिरामिड पार्टी ऑफ इंडिया", "जल्द आ रहा है"},
            {"Andhra Pradesh", "4", "Amalapuram", "Rajani Chelle", "Jana Jagruti Party", "Coming soon", "आन्ध्र प्रदेश", "अमलापुरम", "रजनी चेल्ले", "जन जागृति पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "1", "Anakapalli", "Chintala Partha Sarathi", "Janasena Party", "Coming soon", "आन्ध्र प्रदेश", "अनकापल्ली", "चिन्तला पार्थ सारथी", "जनसेना पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "2", "Anakapalli", "Dr.Beesetti Venkata Satyavathi", "YSR Congress Party", "Coming soon", "आन्ध्र प्रदेश", "अनकापल्ली", "डॉ. बिसेती वेंकट सत्यवती", "YSR कांग्रेस पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "3", "Anakapalli", "K B Swaroop", "Jana Jagruti Party", "Coming soon", "आन्ध्र प्रदेश", "अनकापल्ली", "के बी स्वरूप", "जन जागृति पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "4", "Anakapalli", "Vadlamuri Krishna Swaroop", "Dalita Bahujana Party", "Coming soon", "आन्ध्र प्रदेश", "अनकापल्ली", "वडलामुरी कृष्ण स्वरूप", "दलिता बहुजन पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "1", "Anantapur", "G. Lalitha", "Socialist Unity Centre of India (Communist)", "Coming soon", "आन्ध्र प्रदेश", "अनंतपुर", "जी. ललिता", "भारतीय सोशलिस्ट यूनिटी सेंटर (कम्युनिस्ट)", "जल्द आ रहा है"},
            {"Andhra Pradesh", "2", "Anantapur", "Giddama Ranganayakulu", "Vishwa Jana Party", "Coming soon", "आन्ध्र प्रदेश", "अनंतपुर", "गिद्दा रंगनायकुलु", "विश्व जन पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "3", "Anantapur", "Juturu Chinna Reddy Pavan Reddy", "Telugu Desam Party", "Coming soon", "आन्ध्र प्रदेश", "अनंतपुर", "जटुरु चिन्ना रेड्डी पावन रेड्डी", "तेलुगू देशम पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "4", "Anantapur", "Padchuri Radha Krishna", "Radical Democrats Party", "Coming soon", "आन्ध्र प्रदेश", "अनंतपुर", "पद्चुरी राधा कृष्ण", "कट्टरपंथी डेमोक्रेट पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "5", "Anantapur", "Viswa Prasad Yadav Sankireddy", "IND", "Coming soon", "आन्ध्र प्रदेश", "अनंतपुर", "विश्व प्रसाद यादव शंकरदी", "निर्दलीय", "जल्द आ रहा है"},
            {"Andhra Pradesh", "1", "Araku", "Anumula Vamsi Krishna", "IND", "Coming soon", "आन्ध्र प्रदेश", "अरकू", "अनामुला वामसी कृष्ण", "निर्दलीय", "जल्द आ रहा है"},
            {"Andhra Pradesh", "2", "Araku", "Goddeti Madhavi", "YSR Congress Party", "Coming soon", "आन्ध्र प्रदेश", "अरकू", "गोद्देती माधवी", "YSR कांग्रेस पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "3", "Araku", "Swamula Subrahamanyam", "Jana Jagruti Party", "Coming soon", "आन्ध्र प्रदेश", "अरकू", "स्वमूला सुब्रह्मण्यम", "जन जागृति पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "1", "Bapatla", "China Nageswara Rao Sadhu", "Mundadugu Praja Party", "Coming soon", "आन्ध्र प्रदेश", "बापतला", "चीन नागेश्वर राव साधु", "मुंडदुगु प्रजा पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "2", "Bapatla", "Gadde Haribabu", "Navodayam Party", "Coming soon", "आन्ध्र प्रदेश", "बापतला", "गद्दे हरिबाबू", "नवोदय पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "3", "Bapatla", "Gella Nagamalli", "IND", "Coming soon", "आन्ध्र प्रदेश", "बापतला", "गेला नागामल्ली", "निर्दलीय", "जल्द आ रहा है"},
            {"Andhra Pradesh", "4", "Bapatla", "Golla Baburao", "IND", "Coming soon", "आन्ध्र प्रदेश", "बापतला", "गोल्ला बाबूराव", "निर्दलीय", "जल्द आ रहा है"},
            {"Andhra Pradesh", "5", "Bapatla", "Kanthiraj Devanand", "Bahujan Samaj Party", "Coming soon", "आन्ध्र प्रदेश", "बापतला", "कांतिराज देवानंद", "बहुजन समाज पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "6", "Bapatla", "Thumati Ravi", "All Peoples Party", "Coming soon", "आन्ध्र प्रदेश", "बापतला", "ठुमती रवि", "ऑल पीपुल्स पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "1", "Chittoor", "P. Ramachandran", "IND", "Coming soon", "आन्ध्र प्रदेश", "चित्तूर", "पी. रामचंद्रन", "निर्दलीय", "जल्द आ रहा है"},
            {"Andhra Pradesh", "2", "Chittoor", "Pallipattu. Abhinav Vishnu", "Mundadugu Praja Party", "Coming soon", "आन्ध्र प्रदेश", "चित्तूर", "पल्लीपट्टू. अभिनव विष्णु", "मुंडदुगु प्रजा पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "1", "Eluru", "Josyula China Venkata Suryanarayana", "Pyramid Party of India", "Coming soon", "आन्ध्र प्रदेश", "एलुरु", "जोसियुला चीन वेंकट सूर्यनारायण", "पिरामिड पार्टी ऑफ इंडिया", "जल्द आ रहा है"},
            {"Andhra Pradesh", "2", "Eluru", "Sridhar Kotagiri", "YSR Congress Party", "Coming soon", "आन्ध्र प्रदेश", "एलुरु", "श्रीधर कोटागिरी", "YSR कांग्रेस पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "1", "Guntur", "Doppalapudi Veera Das", "IND", "Coming soon", "आन्ध्र प्रदेश", "गुंटूर", "डोप्पलपुदी वीरा दास", "निर्दलीय", "जल्द आ रहा है"},
            {"Andhra Pradesh", "2", "Guntur", "Jayadev Galla", "Telugu Desam Party", "Coming soon", "आन्ध्र प्रदेश", "गुंटूर", "जयदेव गल्ला", "तेलुगू देशम पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "3", "Guntur", "Mannava Hariprasad", "Communist Party of India (Marxist–Leninist) Red Star", "Coming soon", "आन्ध्र प्रदेश", "गुंटूर", "मानवा हरिप्रसाद", "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) रेड स्टार", "जल्द आ रहा है"},
            {"Andhra Pradesh", "4", "Guntur", "Sarabandi Raju Sikhinam", "Indian Labour Party (Ambedkar Phule)", "Coming soon", "आन्ध्र प्रदेश", "गुंटूर", "सरबंदी राजू सिखिनम", "भारतीय मजदूर पार्टी (अम्बेडकर फुले)", "जल्द आ रहा है"},
            {"Andhra Pradesh", "5", "Guntur", "Ullagi David Jayakumar", "Hardam Manavtawadi Rashtriya Dal", "Coming soon", "आन्ध्र प्रदेश", "गुंटूर", "उल्लागी डेविड जयकुमार", "हरदम मानवतवादी राष्ट्रीय दल", "जल्द आ रहा है"},
            {"Andhra Pradesh", "6", "Guntur", "Umar Basha Shaik", "IND", "Coming soon", "आन्ध्र प्रदेश", "गुंटूर", "उमर बाशा शैक", "निर्दलीय", "जल्द आ रहा है"},
            {"Andhra Pradesh", "7", "Guntur", "Yanamadala Venkata Suresh", "IND", "Coming soon", "आन्ध्र प्रदेश", "गुंटूर", "यनामदला वेंकट सुरेश", "निर्दलीय", "जल्द आ रहा है"},
            {"Andhra Pradesh", "1", "Hindupur", "Gogula Pulakunta Jayanth", "IND", "Coming soon", "आन्ध्र प्रदेश", "हिन्दुपुर", "गोगुला पुलकुंता जयंत", "निर्दलीय", "जल्द आ रहा है"},
            {"Andhra Pradesh", "2", "Hindupur", "Mugi Surya Prakash", "IND", "Coming soon", "आन्ध्र प्रदेश", "हिन्दुपुर", "मुगी सूर्य प्रकाश", "निर्दलीय", "जल्द आ रहा है"},
            {"Andhra Pradesh", "3", "Hindupur", "S. R. Anjaneyulu", "IND", "Coming soon", "आन्ध्र प्रदेश", "हिन्दुपुर", "एस. आर. अंजनैयुलू", "निर्दलीय", "जल्द आ रहा है"},
            {"Andhra Pradesh", "1", "Kadapa", "Ameen Peeran Shaik", "Ambedkar National Congress", "Coming soon", "आन्ध्र प्रदेश", "कडपा", "अमीन पीरन शैक", "अंबेडकर राष्ट्रीय कांग्रेस", "जल्द आ रहा है"},
            {"Andhra Pradesh", "2", "Kadapa", "Chadipirala Adi Narayana Reddy", "Telugu Desam Party", "Coming soon", "आन्ध्र प्रदेश", "कडपा", "चादीपिरला आदि नारायण रेड्डी", "तेलुगू देशम पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "3", "Kadapa", "Nyamatulla Shaik", "IND", "Coming soon", "आन्ध्र प्रदेश", "कडपा", "न्यामतुल्ला शिक", "निर्दलीय", "जल्द आ रहा है"},
            {"Andhra Pradesh", "4", "Kadapa", "Pedakala Varalakshmi", "Pyramid Party of India", "Coming soon", "आन्ध्र प्रदेश", "कडपा", "पेदाकाला वरलक्ष्मी", "पिरामिड पार्टी ऑफ इंडिया", "जल्द आ रहा है"},
            {"Andhra Pradesh", "5", "Kadapa", "Siva Chandra Reddy Komma", "Anna YSR Congress Party", "Coming soon", "आन्ध्र प्रदेश", "कडपा", "शिव चंद्र रेड्डी कोमा", "अन्ना YSR कांग्रेस पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "1", "Kakinada", "Appalakonda Vangalapudi"   , "Mundadugu Praja Party"                                   , "Coming soon", "आन्ध्र प्रदेश", "काकीनाडा", "अपलाकोंडा वंगलपुडी", "मुंडदुगु प्रजा पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "2", "Kakinada", "Donam Neelakantam"         , "All India Praja Party"                                   , "Coming soon", "आन्ध्र प्रदेश", "काकीनाडा", "डोनम नीलकांतम"   , "अखिल भारतीय प्रजा पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "3", "Kakinada", "Godugu Satyanarayana"      , "Communist Party of India (Marxist–Leninist) Liberation"  , "Coming soon", "आन्ध्र प्रदेश", "काकीनाडा", "गोडुगु सत्यनारायण"  , "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) मुक्ति", "जल्द आ रहा है"},
            {"Andhra Pradesh", "4", "Kakinada", "Sunil Kumar Chalamalasetty", "Telugu Desam Party"                                      , "Coming soon", "आन्ध्र प्रदेश", "काकीनाडा", "सुनील कुमार चलमलासट्टी", "तेलुगू देशम पार्टी", "जल्द आ रहा है"},
            {"Andhra Pradesh", "5", "Kakinada", "Vanga Geetha Viswanatham"  , "YSR Congress Party"                                      , "Coming soon", "आन्ध्र प्रदेश", "काकीनाडा", "शवंगा गीता विश्वनाथम्", "YSR कांग्रेस पार्टी", "जल्द आ रहा है"},
            {"Arunachal Pradesh", "1", "Arunachal West", "Jarjum Ete", "Janata Dal (Secular)", "Coming soon", "अरुणाचल प्रदेश", "अरुणाचल पश्चिम", "जर्जुम एते", "जनता दल (सेक्युलर)", "जल्द आ रहा है"},
            {"Arunachal Pradesh", "2", "Arunachal West", "Jomin Nyokir Kara", "All India Forward Bloc", "Coming soon", "अरुणाचल प्रदेश", "अरुणाचल पश्चिम", "जमिन न्योकिर कारा", "ऑल इंडिया फार्वर्ड ब्लाक", "जल्द आ रहा है"},
            {"Arunachal Pradesh", "3", "Arunachal West", "Rumak Jomoh", "IND", "Coming soon", "अरुणाचल प्रदेश", "अरुणाचल पश्चिम", "रमक जोमोह", "निर्दलीय", "जल्द आ रहा है"},
            {"Arunachal Pradesh", "4", "Arunachal West", "Subu Kechi", "Peoples Party of Arunachal", "Coming soon", "अरुणाचल प्रदेश", "अरुणाचल पश्चिम", "सुबु केची", "पीपुल्स पार्टी ऑफ अरुणाचल", "जल्द आ रहा है"},
            {"Bihar", "1", "Aurangabad Bi", "Avinash Kumar", "Peoples Party of India (Democratic)", "Coming soon", "बिहार", "औरंगाबाद बिहा", "अविनाश कुमार", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", "जल्द आ रहा है"},
            {"Bihar", "2", "Aurangabad Bi", "Dhirendra Kumar Singh", "IND", "Coming soon", "बिहार", "औरंगाबाद बिहा", "धीरेन्द्र कुमार सिंह", "निर्दलीय", "जल्द आ रहा है"},
            {"Bihar", "3", "Aurangabad Bi", "Santosh Kumar Sinha", "IND", "Coming soon", "बिहार", "औरंगाबाद बिहा", "संतोष कुमार सिन्हा", "निर्दलीय", "जल्द आ रहा है"},
            {"Bihar", "4", "Aurangabad Bi", "Som Prakash", "Swaraj Party (Loktantrik)", "Coming soon", "बिहार", "औरंगाबाद बिहा", "सोम प्रकाश", "स्वराज पार्टी (लोकतांत्रिक)", "जल्द आ रहा है"},
            {"Bihar", "5", "Aurangabad Bi", "Upendra Prasad", "Hindustani Awam Morcha (Secular)", "Coming soon", "बिहार", "औरंगाबाद बिहा", "उपेंद्र प्रसाद", "हिंदुस्तानी आवाम मोर्चा (सेक्युलर)", "जल्द आ रहा है"},
            {"Bihar", "1", "Gaya", "Dayanand Rajwanshi", "Moolniwasi Samaj Party", "Coming soon", "बिहार", "गया", "दयानंद राजवंशी", "मूलनिवासी समाज पार्टी", "जल्द आ रहा है"},
            {"Bihar", "2", "Gaya", "Dilip Kumar", "Bahujan Samaj Party", "Coming soon", "बिहार", "गया", "दिलीप कुमार", "बहुजन समाज पार्टी", "जल्द आ रहा है"},
            {"Bihar", "3", "Gaya", "Prakash Chandra", "Public Mission Party", "Coming soon", "बिहार", "गया", "प्रकाश चंद्र", "सार्वजनिक मिशन पार्टी", "जल्द आ रहा है"},
            {"Bihar", "4", "Gaya", "Umesh Rajak", "Peoples Party of India (Democratic)", "Coming soon", "बिहार", "गया", "उमेश रजक", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", "जल्द आ रहा है"},
            {"Bihar", "5", "Gaya", "Vijay Kumar Chaudhari", "Janta Dal Rashtravadi", "Coming soon", "बिहार", "गया", "विजय कुमार चौधरी", "जनता दल राष्ट्रवादी", "जल्द आ रहा है"},
            {"Bihar", "1", "Jamui", "Balmiki Paswan", "Hindusthan Nirman Dal", "Coming soon", "बिहार", "जमुई", "बाल्मीकि पासवान", "हिंदुस्तान निर्माण दल", "जल्द आ रहा है"},
            {"Bihar", "2", "Jamui", "Subhash Paswan", "IND", "Coming soon", "बिहार", "जमुई", "सुभाष पासवान", "निर्दलीय", "जल्द आ रहा है"},
            {"Bihar", "3", "Jamui", "Virendra Kumar", "IND", "Coming soon", "बिहार", "जमुई", "वीरेन्द्र कुमार", "निर्दलीय", "जल्द आ रहा है"},
            {"Bihar", "4", "Jamui", "Vishnu Priya", "Bahujan Mukti Party", "Coming soon", "बिहार", "जमुई", "विष्णु प्रिया", "बहुजन मुक्ति पार्टी", "जल्द आ रहा है"},
            {"Bihar", "1", "Nawada", "Aditya Pradhan", "Peoples Party of India (Democratic)", "Coming soon", "बिहार", "नवादा", "आदित्य प्रधान", "पीपुल्स पार्टी ऑफ इंडिया (डेमोक्रेटिक)", "जल्द आ रहा है"},
            {"Bihar", "2", "Nawada", "Mokim Uddin", "Rashtriya Ulama Council", "Coming soon", "बिहार", "नवादा", "मोकिम उद्दीन", "राष्ट्रीय उलमा परिषद", "जल्द आ रहा है"},
            {"Bihar", "3", "Nawada", "Rajesh Kumar", "IND", "Coming soon", "बिहार", "नवादा", "राजेश कुमार", "निर्दलीय", "जल्द आ रहा है"},
            {"Bihar", "4", "Nawada", "Tulsi Dayal", "IND", "Coming soon", "बिहार", "नवादा", "तुलसी दयाल", "निर्दलीय", "जल्द आ रहा है"},
            {"Chhattisgarh", "1", "Bastar", "Paneesh Prasad Nag", "Ambedkarite Party of India", "Coming soon", "छत्तीसगढ़", "बस्तर", "पनेश प्रसाद नाग", "भारत की अम्बेडकरवादी पार्टी", "जल्द आ रहा है"},
            {"Chhattisgarh", "2", "Bastar", "Ramu Ram Mourya", "Communist Party of India", "Coming soon", "छत्तीसगढ़", "बस्तर", "रामू राम मौर्य", "भारतीय कम्युनिस्ट पार्टी", "जल्द आ रहा है"},
            {"Jammu and Kashmir", "1", "Baramulla", "Abdul Qayoom Wani", "Jammu & Kashmir Peoples Democratic Party", "Coming soon", "जम्मू और कश्मीर", "बारामूला", "अब्दुल कयूम वानी", "जम्मू और कश्मीर पीपुल्स डेमोक्रेटिक पार्टी", "जल्द आ रहा है"},
            {"Jammu and Kashmir", "2", "Baramulla", "Syed Najeeb Shah Naqvi", "IND", "Coming soon", "जम्मू और कश्मीर", "बारामूला", "सैयद नजीब शाह नकवी", "निर्दलीय", "जल्द आ रहा है"},
            {"Jammu and Kashmir", "1", "Jammu", "Ajay Kumar", "IND", "Coming soon", "जम्मू और कश्मीर", "जम्मू", "अजय कुमार", "निर्दलीय", "जल्द आ रहा है"},
            {"Jammu and Kashmir", "2", "Jammu", "Anil Singh", "IND", "Coming soon", "जम्मू और कश्मीर", "जम्मू", "अनिल सिंह", "निर्दलीय", "जल्द आ रहा है"},
            {"Jammu and Kashmir", "3", "Jammu", "Lal Singh", "Dogra Swabhiman Sangathan Party", "Coming soon", "जम्मू और कश्मीर", "जम्मू", "लाल सिंह", "डोगरा स्वाभिमान संगठन पार्टी", "जल्द आ रहा है"},
            {"Jammu and Kashmir", "4", "Jammu", "Manish Sahni", "Shiv Sena", "Coming soon", "जम्मू और कश्मीर", "जम्मू", "मनीष साहनी", "शिव सेना", "जल्द आ रहा है"},
            {"Jammu and Kashmir", "5", "Jammu", "Mohd Younis", "Jammu & Kashmir Pir Panjal Awami Party", "Coming soon", "जम्मू और कश्मीर", "जम्मू", "मोहम्मद यूनिस", "जम्मू और कश्मीर पीर पंजाल अवामी पार्टी", "जल्द आ रहा है"},
            {"Jammu and Kashmir", "6", "Jammu", "Sakander Ahmad Nourani", "IND", "Coming soon", "जम्मू और कश्मीर", "जम्मू", "सकंदर अहमद नूरानी", "निर्दलीय", "जल्द आ रहा है"},
            {"Jammu and Kashmir", "7", "Jammu", "Sushil Kumar", "Hindusthan Nirman Dal", "Coming soon", "जम्मू और कश्मीर", "जम्मू", "सुशील कुमार", "हिंदुस्तान निर्माण दल", "जल्द आ रहा है"},
            {"Jammu and Kashmir", "8", "Jammu", "Syed Aqib Hussain", "Independent Peoples Party", "Coming soon", "जम्मू और कश्मीर", "जम्मू", "सैयद अकीब हुसैन", "स्वतंत्र पीपुल्स पार्टी", "जल्द आ रहा है"},
            {"Lakshadweep", "1", "Lakshadweep", "Dr. Mohammed Sadique K P", "Janata Dal (United)", "Coming soon", "लक्षद्वीप", "लक्षद्वीप", "डॉ. मोहम्मद सैडिक के.पी.", "जनता दल (यूनाइटेड)", "जल्द आ रहा है"},
            {"Manipur", "1", "Outer Manipur", "Angam Karung Kom", "Nationalist Congress Party", "Coming soon", "मणिपुर", "बाहरी मणिपुर", "अंगम करुंग कोमा", "राष्ट्रवादी कांग्रेस पार्टी", "जल्द आ रहा है"},
            {"Manipur", "2", "Outer Manipur", "Ashang Kasar", "North East India Development Party", "Coming soon", "मणिपुर", "बाहरी मणिपुर", "अशंग कासर", "नॉर्थ ईस्ट इंडिया डेवलपमेंट पार्टी", "जल्द आ रहा है"},
            {"Manipur", "3", "Outer Manipur", "Hangkhanpau Taithul", "Janata Dal (United)", "Coming soon", "मणिपुर", "बाहरी मणिपुर", "हेंगखानौ तैथुल", "जनता दल (यूनाइटेड)", "जल्द आ रहा है"},
            {"Manipur", "4", "Outer Manipur", "Lorho S. Pfoze", "Naga People's Front", "Coming soon", "मणिपुर", "बाहरी मणिपुर", "लोरो एस. पफोज़े", "नागा पीपल्स फ्रंट", "जल्द आ रहा है"},
            {"Meghalaya", "1", "Shillong", "Jemino Mawthoh", "United Democratic Party", "Coming soon", "मेघालय", "शिलांग", "जेमिनो मावथोह", "मयूनाइटेड डेमोक्रेटिक पार्टी", "जल्द आ रहा है"},
            {"Meghalaya", "2", "Shillong", "T.H.S. Bonney" , "IND"                    , "Coming soon", "मेघालय", "शिलांग", "टीएस बोनी"   , "निर्दलीय"            , "जल्द आ रहा है"},
            {"Meghalaya", "1", "Tura", "Agatha K. Sangma", "National People's Party ", "Coming soon", "मेघालय", "तुरा", "अगाथा के संगमा", "नेशनल पीपल्स पार्टी", "जल्द आ रहा है"},
            {"Mizoram", "1", "Mizoram", "C Lalrosanga", "Mizo National Front", "Coming soon", "मिज़ोरम", "मिज़ोरम", "सी लालसरंगा", "मिज़ो नेशनल फ्रंट", "जल्द आ रहा है"},
            {"Mizoram", "2", "Mizoram", "Lal Hriatrenga Chhangte", "IND", "Coming soon", "मिज़ोरम", "मिज़ोरम", "लाल हिरतेंगा छंगटे", "निर्दलीय", "जल्द आ रहा है"},
            {"Mizoram", "3", "Mizoram", "Lalnghinglova Hmar", "IND", "Coming soon", "मिज़ोरम", "मिज़ोरम", "लालनघिंगलोवा हमार", "निर्दलीय", "जल्द आ रहा है"},
            {"Nagaland", "1", "Nagaland", "Dr. M M Thromwa Konyak", "IND", "Coming soon", "नागालैण्ड", "नगालैंड", "डॉ. एमएम थ्रोम्वा कोन्याक", "निर्दलीय", "जल्द आ रहा है"},
            {"Nagaland", "2", "Nagaland", "Hayithung Tungoe", "National People's Party", "Coming soon", "नागालैण्ड", "नगालैंड", "हेइथुंग तुंगो", "नेशनल पीपल्स पार्टी", "जल्द आ रहा है"},
            {"Nagaland", "3", "Nagaland", "Tokheho Yepthomi", "Nationalist Democratic Progressive Party", "Coming soon", "नागालैण्ड", "नगालैंड", "तोखेहो येप्थोमी", "राष्ट्रवादी डेमोक्रेटिक प्रोग्रेसिव पार्टी", "जल्द आ रहा है"},
            {"Sikkim", "1", "Sikkim", "Biraj Adhikari"      , "Hamro Sikkim Party"      , "Coming soon", "सिक्किम", "सिक्किम", "बिराज अधकारी"   , "हमरो सिक्किम पार्टी", "जल्द आ रहा है"},
            {"Sikkim", "2", "Sikkim", "Dek Bahadur Katwal"  , "Sikkim Democratic Front" , "Coming soon", "सिक्किम", "सिक्किम", "देक बहादुर कटवाल", "सिक्किम डेमोक्रेटिक फ्रन्ट", "जल्द आ रहा है"},
            {"Sikkim", "3", "Sikkim", "Dhiraj Kumar Rai"    , "Sikkim Republican Party" , "Coming soon", "सिक्किम", "सिक्किम", "धीरज कुमार राय"  , "सिक्किम रिपब्लिकन पार्टी", "जल्द आ रहा है"},
            {"Sikkim", "4", "Sikkim", "Indra Hang Subba"    , "Sikkim Krantikari Morcha", "Coming soon", "सिक्किम", "सिक्किम", "इंद्र हैंग सुब्बा"    , "सिक्किम क्रांतिकारी मोर्चा", "जल्द आ रहा है"},
            {"Sikkim", "5", "Sikkim", "Mahendra Thapa"      , "IND"                     , "Coming soon", "सिक्किम", "सिक्किम", "महेंद्र थापा"       , "निर्दलीय", "जल्द आ रहा है"},
            {"Sikkim", "6", "Sikkim", "Narendra Adhikari"   , "Sikkim United Front"     , "Coming soon", "सिक्किम", "सिक्किम", "नरेंद्र अधकारी"     , "सिक्किम संयुक्त मोर्चा", "जल्द आ रहा है"},
            {"Sikkim", "7", "Sikkim", "Rabin Rai"           , "All Indians Party"       , "Coming soon", "सिक्किम", "सिक्किम", "राबिन राय"       , "सभी भारतीय पार्टी", "जल्द आ रहा है"},
            {"West Bengal", "1", "Alipurduars", "Dasrath Tirkey", "All India Trinamool Congress", "Coming soon", "पश्चिम बंगाल", "अलीपुरद्वार लोक", "दशरथ तिर्की", "अखिल भारतीय तृणमूल कांग्रेस", "जल्द आ रहा है"},
            {"West Bengal", "2", "Alipurduars", "Gergory Trikey", "IND", "Coming soon", "पश्चिम बंगाल", "अलीपुरद्वार लोक", "ग्रेगोरी तिर्की", "निर्दलीय", "जल्द आ रहा है"},
            {"West Bengal", "3", "Alipurduars", "Mili Oraon", "Revolutionary Socialist Party", "Coming soon", "पश्चिम बंगाल", "अलीपुरद्वार लोक", "मिलि उरांव", "क्रांतिकारी सोशलिस्ट पार्टी", "जल्द आ रहा है"},
            {"West Bengal", "4", "Alipurduars", "Prasen Jayant Kindo", "IND", "Coming soon", "पश्चिम बंगाल", "अलीपुरद्वार लोक", "प्रसेन जयंत किंडो", "निर्दलीय", "जल्द आ रहा है"},
            {"West Bengal", "1", "Cooch Behar", "Dhananjoy Barman"  , "Welfare Party Of India", "Coming soon", "पश्चिम बंगाल", "कूचबिहार", "धनंजय बर्मन", "वेलफेयर पार्टी ऑफ इंडिया", "जल्द आ रहा है"},
            {"West Bengal", "2", "Cooch Behar", "Naresh Chandra Roy", "IND"                   , "Coming soon", "पश्चिम बंगाल", "कूचबिहार", "नरेश चंद्र रॉय", "निर्दलीय", "जल्द आ रहा है"},
            {"West Bengal", "3", "Cooch Behar", "Nirmal Kumar Roy"  , "IND"                   , "Coming soon", "पश्चिम बंगाल", "कूचबिहार", "निर्मल कुमार रॉय", "निर्दलीय", "जल्द आ रहा है"},
    };

    public static final String[][] red_bucket = {
            //    "STATE"		"STATE"		"No."		"Constituency"		"Name of elected M.P."		"Party affiliation"		"चुनाव क्षेत्र"		"निर्वाचित सांसद का नाम"		"पार्टी संबद्धता"		phone		email		address		website
            {"Bihar", "1", "Gaya" , "Jitan Ram Manjhi" , "Over-aged, Heinous crimes"         , "", "बिहार", "गया", "जीतन राम मांझी", "उम्र ज्यादा, आपराधिक मामले"},
            {"Bihar", "2", "Gaya" , "Vijay Kumar"      , "Not a graduate, Heinous crimes"    , "", "बिहार", "गया", "विजय कुमार"   , "स्नातक नहीं है, आपराधिक मामले"},
            {"Bihar", "1", "Jamui", "Chirag Kumar Paswan", "Heinous crimes"                  , "", "बिहार", "जमुई", "चिराग कुमार पासवान"   , "आपराधिक मामले"},
    };
}
