package in.filternet.jantamalik;

public class Puzzle_Ques {

    public static final String[][] questions = {
            //   "Question"	        "Answer & Option 1"	   "Option 2"           "Option 3"	        "Option 4"
            {"When did you pay tax first time in your life?",
                    "When I bought toffee/biscuit",
                    "My 1st Salary as Income Tax(TDS)",
                    "Family paid the hospital bill when I was born.",
                    "I never paid tax",
                    "आपने जीवन में पहली बार टैक्स कब दिया था?",
                    "जब मैनें टाॅफी या बिस्कुट खरीदी",
                    "मेरी पहली सैलरी पर टैक्स कटा था(टीडीएस)",
                    "मेरे पैदा होनेपर अस्पताल का बिल",
                    "मैंने कभी टैक्स नहीं दिया है"},
            {"How much is central govt budget for 2018-19?",
                    "24 lakh crore",
                    "2.5 lakh crore",
                    "3 lakh crore",
                    "18 lakh crore",
                    "केन्द्र सरकार का 2018-19 का सालाना बजट कितना है?",
                    "24 लाख करोड़",
                    "2.5 लाख करोड़",
                    "3 लाख करोड़",
                    "18 लाख करोड़"},
            {"How do you run the govt?",
                    "Voter -> MP -> Loksabha -> Govt",
                    "Voter -> Govt -> MP -> Loksabha",
                    "Govt -> MP -> Loksabha -> Voter",
                    "MP -> Loksabha -> Govt -> Voter",
                    "आप सरकार कैसे चलाते हैं?",
                    "वोटर -> सांसद -> लोकसभा -> सरकार",
                    "वोटर -> सरकार -> सांसद -> लोकसभा",
                    "सरकार -> सांसद -> लोकसभा -> वोटर",
                    "सांसद -> लोकसभा -> सरकार -> वोटर"},
            {"Which political parties have been found guilty of illegal-foreign-funding in high court?",
                    "BJP and Congress",
                    "Congress only", "SP and BSP",
                    "All parties",
                    "किन राजनीतिक पार्टियों को हाईकोर्ट ने गैरकानूनी-विदेशी-चंदे का दोषी पाया है?",
                    "भाजपा और कांग्रेस",
                    "सिर्फ कांग्रेस",
                    "सपा और बसपा",
                    "सभी पार्टियाँ"},
            {"What is priority of education in central govt budget?",
                    "10", "3", "1", "7",
                    "केन्द्र सरकार के बजट में शिक्षा का कौन सा स्थान है?",
                    "10", "3", "1", "7"},
            {"What is priority of health in central govt budget?",
                    "14", "2", "5", "7",
                    "केन्द्र सरकार के बजट में स्वास्थ्य का कौन सा स्थान है?",
                    "14", "2", "5", "7"},
            {"Does newspapers/news-channels show paid-fake-news frequently?",
                    "Yes", "No", "Don't know", "Rarely",
                    "क्या अाये दिन अखबार और न्यूज चैनल बिकी-झूठी-खबरें दिखाते हैं?",
                    "हाँ", "नहीं", "पता नहीं", "कभी-कभी"},
            {"Do you have contact information of your MP?", "Yes",
                    "No",
                    "Don't know",
                    "Not sure",
                    "क्या आपके पास सांसद की संपर्क जानकारी है?",
                    "हाँ", "नहीं", "पता नहीं", "कह नहीं सकते"},
            {"Should your MP/MLA explain govt budget and spending to people?",
                    "Yes",
                    "No",
                    "Don't know",
                    "Not sure",
                    "क्या आपके सांसद/विधायक को, जनता को, सरकार का बजट और खर्च समझाना चाहिए?",
                    "हाँ", "नहीं", "पता नहीं", "कह नहीं सकते"},
            {"When was the lokpal bill passed by loksabha?",
                    "When people started protesting outside minister/MP house",
                    "When people protested in Ramlila ground",
                    "When Anna went to jail", "Don't know",
                    "लोकसभा ने लोकपाल बिल कब पास किया था?",
                    "जब लोगों ने मंत्री/सांसद के घर के सामने धरना दिया था",
                    "जब लोगों ने रामलीला मैदान में धरना दिया था",
                    "जब अन्ना जेल गए थे",
                    "पता नहीं"},
    };

}
