/* Auto-generated file from db2MPjava.php*/

package in.filternet.jantamalik.Kendra;

public final class LokSabhaGroups {

    public static final String[][] all_groups = {
            // WhatsApp group
            {"Andaman & Nicobar Islands", "Andaman and Nicobar Islands", "https://chat.whatsapp.com/F6Sd3k7uytq1zgTV15JcTm"},
            {"Andhra Pradesh", "Amalapuram", "https://chat.whatsapp.com/Ec7m1YC0TlMLMBemAWwZ2u"},
            {"Andhra Pradesh", "Anakapalle", "https://chat.whatsapp.com/JBEMNxnbhe918ua6Y4sjuD"},
            {"Andhra Pradesh", "Anantapur",  "https://chat.whatsapp.com/IHExiw4blOz25fDbfKAul3"},
            {"Andhra Pradesh", "Araku",  "https://chat.whatsapp.com/K9rhNPtdXMGDDBGewRhqnC"},
            {"Andhra Pradesh", "Bapatla", "https://chat.whatsapp.com/D4tH1aH2cPpGAsk0sU9vfT"},
            {"Andhra Pradesh", "Chittoor", "https://chat.whatsapp.com/GWWw3KmMCJcBaChfxZSTPY"},
            {"Andhra Pradesh", "Eluru", "https://chat.whatsapp.com/FxhxQ7toIBA3l0PVGH3l1u"},
            {"Andhra Pradesh", "Guntur", "https://chat.whatsapp.com/GzMOAMZ9UVSB7eRaM9Oxg3"},
            {"Andhra Pradesh", "Hindupur", "https://chat.whatsapp.com/BIeMLDh5j4b83tICPINM4U"},
            {"Andhra Pradesh", "Kadapa", "https://chat.whatsapp.com/IOlCpIXIOuw5QXFIw15Wsn"},
            {"Andhra Pradesh", "Kakinada", "https://chat.whatsapp.com/HyYvKzcn46hJXwlPDSrcJz"},
            {"Andhra Pradesh", "Kurnool", "https://chat.whatsapp.com/IytzpEbg4Ef9Qk2hGMganP"},
            {"Andhra Pradesh", "Machilipatnam",  "https://chat.whatsapp.com/C8poN2VyNa242xTYLDQXkU"},
            {"Andhra Pradesh", "Nandyal", "https://chat.whatsapp.com/CjyozuAOX4J4C2n5hsyUyR"},
            {"Andhra Pradesh", "Narasaraopet", "https://chat.whatsapp.com/JMjkkKQT9KT8SLPM7EnnBJ"},
            {"Andhra Pradesh", "Narsapuram", "https://chat.whatsapp.com/BPIEFphvHeaCrKQar6DrQP"},
            {"Andhra Pradesh", "Nellore", "https://chat.whatsapp.com/FM0pyrlloKw3LUJ1EQUiaT"},
            {"Andhra Pradesh", "Ongole", "https://chat.whatsapp.com/BzfY1kAVGXs2NLe58Zl2H0"},
            {"Andhra Pradesh", "Rajahmundry", "https://chat.whatsapp.com/FAVW8X6Rf0H936YTFf3lCV"},
            {"Andhra Pradesh", "Rajampet", "https://chat.whatsapp.com/H87LRIPWCJFABJKO45gsZ0"},
            {"Andhra Pradesh", "Srikakulam", "https://chat.whatsapp.com/IsCiCEGlIKd8CjovXFi5b8"},
            {"Andhra Pradesh", "Tirupati", "https://chat.whatsapp.com/Kf8vorpDqdh2XstYwfzZmx"},
            {"Andhra Pradesh", "Vijayawada", "https://chat.whatsapp.com/FfnqTF3xatE61IC9oImqkR"},
            {"Andhra Pradesh", "Visakhapatnam", "https://chat.whatsapp.com/JTIjFxLfnanKD9rMizVOXd"},
            {"Andhra Pradesh", "Vizianagaram", "https://chat.whatsapp.com/IeceM79vfc131Q0EMQt0gT"},
            {"Arunachal Pradesh", "Arunachal East", "https://chat.whatsapp.com/GqkaGpe9Tey6pROQF0XhdU"},
            {"Arunachal Pradesh", "Arunachal West", "https://chat.whatsapp.com/I5qyTWonW81ApR1X2alcyP"},
            {"Assam", "Autonomous District", "https://chat.whatsapp.com/L71srIEbtFvHBzpYnnb1RS"},
            {"Assam", "Barpeta", "https://chat.whatsapp.com/FcH3T6PsGkuERC7mN5mNHu"},
            {"Assam", "Dhubri", "https://chat.whatsapp.com/LfLW5YSuJHPHnffTqp5Imx"},
            {"Assam", "Dibrugarh", "https://chat.whatsapp.com/JmzNSAJoqXZJydhpseMXGB"},
            {"Assam", "Gauhati", "https://chat.whatsapp.com/IAix7naushy50YLH8yz8Ly"},
            {"Assam", "Jorhat", "https://chat.whatsapp.com/FxAFxsyLxcx6VHvjxFw6hx"},
            {"Assam", "Kaliabor", "https://chat.whatsapp.com/HkR7LlAR76ZAMKEyAFnIxL"},
            {"Assam", "Karimganj", "https://chat.whatsapp.com/JMwZbwAsakB9lMsjwXfAfN"},
            {"Assam", "Kokrajhar", "https://chat.whatsapp.com/KOgPvEUxDfkHRRgw1vcPD6"},
            {"Assam", "Lakhimpur", "https://chat.whatsapp.com/C0ztNIJlUkqHNehZzt8Of0"},
            {"Assam", "Mangaldoi", "https://chat.whatsapp.com/Ea2A2CrO2SyF34nDnlHZBz"},
            {"Assam", "Nawgong", "https://chat.whatsapp.com/FxRbI2fLfdV0lSiPQIBlmA"},
            {"Assam", "Silchar", "https://chat.whatsapp.com/H4rgfhwMBsI6Nktu2rZtyk"},
            {"Assam", "Tezpur", "https://chat.whatsapp.com/Fbpu4MKM2TkHgIbPwgtI0Z"},
            {"Bihar", "Araria", "https://chat.whatsapp.com/HMwbHEbdSfS9gWCcBzavkT"},
            {"Bihar", "Arrah", "https://chat.whatsapp.com/Kl1Ylp9p6Y9FJiH7AnuheQ"},
            {"Bihar", "Aurangabad", "https://chat.whatsapp.com/DwT2ygfqUQh0qdSB5ZbBeb"},
            {"Bihar", "Banka", "https://chat.whatsapp.com/CfAvDRPcJ6rFJWVAU0pxSi"},
            {"Bihar", "Begusarai", "https://chat.whatsapp.com/EodwCYnsqna1zoY9ztfNbZ"},
            {"Bihar", "Bhagalpur", "https://chat.whatsapp.com/E8bobynvnYBAXB8RzEk5gL"},
            {"Bihar", "Buxar", "https://chat.whatsapp.com/KOz78MmfxlzJ0lhug1OSDb"},
            {"Bihar", "Darbhanga", "https://chat.whatsapp.com/E2k8ALGtQa4INgEOgOIGr8"},
            {"Bihar", "Gaya", "https://chat.whatsapp.com/D29XIJneKlA6c7dMNsP3Wf"},
            {"Bihar", "Gopalganj", "https://chat.whatsapp.com/EyPrUiaKjnPCWZhLXadq2u"},
            {"Bihar", "Hajipur", "https://chat.whatsapp.com/DgQya4BfYsQ3H7O5O1ayJu"},
            {"Bihar", "Jahanabad", "https://chat.whatsapp.com/C2b8Ed11382ImCGSoquBNG"},
            {"Bihar", "Jamui", "https://chat.whatsapp.com/LbgnD3dmAZ59gUI4U2uZge"},
            {"Bihar", "Jhanjharpur", "https://chat.whatsapp.com/CkW1GqWfM5UHKqS3nZBSEY"},
            {"Bihar", "Karakat", "https://chat.whatsapp.com/Bg7y5R7Z4D3JSccFAE40Ve"},
            {"Bihar", "Katihar", "https://chat.whatsapp.com/HPwdI9dKqVEBRbwOoxrjgi"},
            {"Bihar", "Khagaria", "https://chat.whatsapp.com/GcBgnWaNRdkC0EYI1Yl0cb"},
            {"Bihar", "Kishanganj", "https://chat.whatsapp.com/I9fxay9NgUoJ2fChHNm8nD"},
            {"Bihar", "Madhepura", "https://chat.whatsapp.com/KiX1RAq9WRp1T73ZDKdP3k"},
            {"Bihar", "Madhubani", "https://chat.whatsapp.com/HK0tqBqzcln2FfZYCmxEFY"},
            {"Bihar", "Maharajganj", "https://chat.whatsapp.com/GD7j27J2IwW8JPe2wZo7bd"},
            {"Bihar", "Munger", "https://chat.whatsapp.com/BwQKfMVdOmCJVReWODOfse"},
            {"Bihar", "Muzaffarpur", "https://chat.whatsapp.com/GYq4KGKkKEV57Jm6CmZx9A"},
            {"Bihar", "Nalanda", "https://chat.whatsapp.com/KqfqtfnGP9vGJ1fVd3Lci7"},
            {"Bihar", "Nawada", "https://chat.whatsapp.com/GrrkYTN4VY05G0jOisxeeh"},
            {"Bihar", "Paschim Champaran" , "https://chat.whatsapp.com/GQbn35yquUXJBHfMbQebK4"},
            {"Bihar", "Pataliputra", "https://chat.whatsapp.com/KDpOkfGHCgZIkEEEzS4Zcb"},
            {"Bihar", "Patna Sahib", "https://chat.whatsapp.com/IGwaCgyXrH81n0dj3h5unI"},
            {"Bihar", "Purnia", "https://chat.whatsapp.com/BAlRimvTnMvIzLB1tdNN5y"},
            {"Bihar", "Purvi Champaran", "https://chat.whatsapp.com/JZk9JMi8RCyCioZ3OrMwUl"},
            {"Bihar", "Samastipur", "https://chat.whatsapp.com/D2Kuwl5XIue462xiojNZ0t"},
            {"Bihar", "Saran", "https://chat.whatsapp.com/Ifql4OAvjegCyXiYSKcnwa"},
            {"Bihar", "Sheohar", "https://chat.whatsapp.com/Lc1M4UwyJCK0iRIvBaCpwD"},
            {"Bihar", "Sitamarhi", "https://chat.whatsapp.com/I7FVBnoh5erDpdCYJJWSrd"},
            {"Bihar", "Siwan", "https://chat.whatsapp.com/KreLGtjJBvIDb1SuZWHO1j"},
            {"Bihar", "Supaul", "https://chat.whatsapp.com/GfjPN1iSwIFIxXgdAEdoxt"},
            {"Bihar", "Ujiarpur", "https://chat.whatsapp.com/GtpMAcLoVyX6pKsWAup7nk"},
            {"Bihar", "Vaishali", "https://chat.whatsapp.com/J58nX702rJVBlDzR9MMsXc"},
            {"Bihar", "Valmiki Nagar", "https://chat.whatsapp.com/CNUsW2fP4zF6Ho4BMIUGAi"},
            {"Chandigarh", "Chandigarh", "https://chat.whatsapp.com/FjZPMadtVBaLckbtE7wikj"},
            {"Chhattisgarh", "Bastar", "https://chat.whatsapp.com/LBYMJoWAKEX9wqceaLjIVf"},
            {"Chhattisgarh", "Bilaspur", "https://chat.whatsapp.com/GMoR5W9TXfeIvKcd9TVnLW"},
            {"Chhattisgarh", "Durg", "https://chat.whatsapp.com/LR0j5AgubcP9qBZ0UgKKl8"},
            {"Chhattisgarh", "Janjgir Champa", "https://chat.whatsapp.com/IMut95Yxvyt89CwM5acjDL"},
            {"Chhattisgarh", "Kanker", "https://chat.whatsapp.com/Hjw0dA8l2Pg4B1yjZeGZsZ"},
            {"Chhattisgarh", "Korba", "https://chat.whatsapp.com/HIrqFMr9Fr2JdAAGOv9B4b"},
            {"Chhattisgarh", "Mahasamund", "https://chat.whatsapp.com/LD6MFke6gBI59Fg8114Qtb"},
            {"Chhattisgarh", "Raigarh", "https://chat.whatsapp.com/HaXHhkjWfB0KtIncy2PggS"},
            {"Chhattisgarh", "Raipur", "https://chat.whatsapp.com/CN9W0HrhqMl3nq6488WA0I"},
            {"Chhattisgarh", "Rajnandgaon", "https://chat.whatsapp.com/HCrp6nyTXYYBiXadsrbwcp"},
            {"Chhattisgarh", "Surguja", "https://chat.whatsapp.com/BRurA2qKmwO8ZnGTp7lJFt"},
            {"Dadra & Nagar Haveli", "Dadra and Nagar Haveli", "https://chat.whatsapp.com/Ku4vexPdLT3CKm7nFVv5Do"},
            {"Daman & Diu", "Daman and Diu", "https://chat.whatsapp.com/B6b1yesngqzJOyHdwcWLXI"},
            {"Goa", "North Goa", "https://chat.whatsapp.com/JyzMJFbyxhf0zRvK7UklfZ"},
            {"Goa", "South Goa", "https://chat.whatsapp.com/KY5jaIlbvU36oF1Rkd8PRc"},
            {"Gujarat", "Ahmedabad East", "https://chat.whatsapp.com/FqGWdJpVeijLq8xXEtErFi"},
            {"Gujarat", "Ahmedabad West", "https://chat.whatsapp.com/FQZM0qjx5LT4cDLK50G3u6"},
            {"Gujarat", "Amreli", "https://chat.whatsapp.com/LidNSMq6yUCIOodmXwElLB"},
            {"Gujarat", "Anand", "https://chat.whatsapp.com/HDBCwopWPWd6efIfSkeiKz"},
            {"Gujarat", "Banaskantha", "https://chat.whatsapp.com/C1n6Nb0uhQ3K8Wc7woMtdH"},
            {"Gujarat", "Bardoli", "https://chat.whatsapp.com/KUCMCQSbXed5ydfLLaJ7DG"},
            {"Gujarat", "Bharuch", "https://chat.whatsapp.com/EZ8Cewi0djp7ziRikD43JM"},
            {"Gujarat", "Bhavnagar", "https://chat.whatsapp.com/INLDRSldkCrKJJYij0CiyF"},
            {"Gujarat", "Chhota Udaipur", "https://chat.whatsapp.com/JjQr7ZUUCNkJ8GtBdtGWxD"},
            {"Gujarat", "Dahod", "https://chat.whatsapp.com/J1QH062mAOlGX504FXVTEF"},
            {"Gujarat", "Gandhinagar", "https://chat.whatsapp.com/JRFRMBxlDqc6U1uwLPIPrS"},
            {"Gujarat", "Jamnagar", "https://chat.whatsapp.com/BCFoSw5bixvCV5uHvAkZlK"},
            {"Gujarat", "Junagadh", "https://chat.whatsapp.com/GUBTfkYUbNk2sD548IyRVo"},
            {"Gujarat", "Kachchh", "https://chat.whatsapp.com/CJqRkhGMGsJ8vENukTfkFb"},
            {"Gujarat", "Kheda", "https://chat.whatsapp.com/JvUygDo8EmDAoNxSYkxMWs"},
            {"Gujarat", "Mahesana", "https://chat.whatsapp.com/LgaznHwAzEj0icDzg5AYBP"},
            {"Gujarat", "Navsari", "https://chat.whatsapp.com/FpDxHyUB7EZE9OOYlQY3ah"},
            {"Gujarat", "Panchmahal", "https://chat.whatsapp.com/LJnhRple1rhD4YzwUK2Zy1"},
            {"Gujarat", "Patan", "https://chat.whatsapp.com/I2lybUX51oP17sEH1difgB"},
            {"Gujarat", "Porbandar", "https://chat.whatsapp.com/Bg6jN7e6dZUHpk4VywmSGz"},
            {"Gujarat", "Rajkot", "https://chat.whatsapp.com/CXnaLCIzit41rgpWyPHudt"},
            {"Gujarat", "Sabarkantha", "https://chat.whatsapp.com/Digs9fKdVRNCK55Qis86vl"},
            {"Gujarat", "Surat", "https://chat.whatsapp.com/LKtPECcULbaDVNjkxDeihJ"},
            {"Gujarat", "Surendranagar", "https://chat.whatsapp.com/Kn7j8o38Ezs5sXbgVVUr7F"},
            {"Gujarat", "Vadodara", "https://chat.whatsapp.com/L5Z0mno3iAYKBlp72SQQ06"},
            {"Gujarat", "Valsad", "https://chat.whatsapp.com/IPHbbKyzeTrGls5JHrpDKh"},
            {"Haryana", "Ambala", "https://chat.whatsapp.com/FupJjq7dVT19T98KzwQnhz"},
            {"Haryana", "Bhiwani Mahendragarh", "https://chat.whatsapp.com/HNljJfRHUkz6ndyD3ihfGW"},
            {"Haryana", "Faridabad", "https://chat.whatsapp.com/Fz8N23GqjOL1PTC6mR6Trn"},
            {"Haryana", "Gurgaon", "https://chat.whatsapp.com/GwD69MpM7ovLnx9svphNlM"},
            {"Haryana", "Hisar", "https://chat.whatsapp.com/Cy0D33uARAxBMsllqBv6pg"},
            {"Haryana", "Karnal", "https://chat.whatsapp.com/G3N2qhMT1YvGmnuJswyIZw"},
            {"Haryana", "Kurukshetra", "https://chat.whatsapp.com/J8AlMvq4Gki785frLABE3E"},
            {"Haryana", "Rohtak", "https://chat.whatsapp.com/BhI0Lr43uioKFJZIxl7y87"},
            {"Haryana", "Sirsa", "https://chat.whatsapp.com/KPbZvgsSTFK5mnSdw1gzhJ"},
            {"Haryana", "Sonipat", "https://chat.whatsapp.com/LISW5WNpMa8D6kEHkpj1c8"},
            {"Himachal Pradesh", "Hamirpur", "https://chat.whatsapp.com/GVGkIwaBxt5AUJICVdpFRr"},
            {"Himachal Pradesh", "Kangra", "https://chat.whatsapp.com/KNGINDjfx3z0c3HVIFIdME"},
            {"Himachal Pradesh", "Mandi", "https://chat.whatsapp.com/FAcJROrtu8x3orvb5ZXiTs"},
            {"Himachal Pradesh", "Shimla", "https://chat.whatsapp.com/GawrKiB7m4UIoDa5Epmves"},
            {"Jammu & Kashmir", "Anantnag", "https://chat.whatsapp.com/CTOCqqkPHfR5noKQgigEYa"},
            {"Jammu & Kashmir", "Baramulla", "https://chat.whatsapp.com/HUBI8QzVxulGvVZKnEAob8"},
            {"Jammu & Kashmir", "Jammu", "https://chat.whatsapp.com/CpKpzQaPUN4KExFlZ4vxf6"},
            {"Jammu & Kashmir", "Ladakh", "https://chat.whatsapp.com/IMkH0mFmmRR0VNsc9r39PU"},
            {"Jammu & Kashmir", "Srinagar", "https://chat.whatsapp.com/GJ4PtvI7TVj0qrpR5aMQ2z"},
            {"Jammu & Kashmir", "Udhampur", "https://chat.whatsapp.com/F3TFPrQOUfaIbZEJmacY9G"},
            {"Jharkhand", "Chatra", "https://chat.whatsapp.com/GGbQRcM2eBc47s2PUok4Yx"},
            {"Jharkhand", "Dhanbad", "https://chat.whatsapp.com/EuWqqhF7HpUC7wfILmIstP"},
            {"Jharkhand", "Dumka", "https://chat.whatsapp.com/E39MK5PJRs3CEdCv1v0CqO"},
            {"Jharkhand", "Giridih", "https://chat.whatsapp.com/Ji5KpxrWdnZJMioULw2Rub"},
            {"Jharkhand", "Godda", "https://chat.whatsapp.com/HuoXHk4bB2x2PGkVUCfCVI"},
            {"Jharkhand", "Hazaribagh", "https://chat.whatsapp.com/FbbLTYERSrV4LhvpJbYTRG"},
            {"Jharkhand", "Jamshedpur", "https://chat.whatsapp.com/E4bk4oDOEEQ71Zt2Am1vsO"},
            {"Jharkhand", "Khunti", "https://chat.whatsapp.com/DbKavL0WtMR8llNqivv0Jx"},
            {"Jharkhand", "Kodarma", "https://chat.whatsapp.com/G8V3fHD3Qma2afDpWbzbgN"},
            {"Jharkhand", "Lohardaga", "https://chat.whatsapp.com/C0OykA0IkzsExe2B6tG5Sq"},
            {"Jharkhand", "Palamu", "https://chat.whatsapp.com/GhtIkMkIQBAAA3F0Z5160G"},
            {"Jharkhand", "Rajmahal", "https://chat.whatsapp.com/GfvolfQ7vpB9hb1QHmt6dl"},
            {"Jharkhand", "Ranchi", "https://chat.whatsapp.com/JovatRqigtD3TTYqTm0pQj"},
            {"Jharkhand", "Singhbhum", "https://chat.whatsapp.com/HYs1nJT5fS38v11tR8N7zk"},
            {"Karnataka", "Bagalkot", "https://chat.whatsapp.com/HGg18FvAtMxFrMlHXdVHrn"},
            {"Karnataka", "Bangalore Central", "https://chat.whatsapp.com/GjH98aGQirLItTMRCZ2vsb"},
            {"Karnataka", "Bangalore North", "https://chat.whatsapp.com/GfpNE8YWuKRBDT9ZWXo0IL"},
            {"Karnataka", "Bangalore Rural", "https://chat.whatsapp.com/GdFwfxPIySCHrkT7wuEfTz"},
            {"Karnataka", "Bangalore South", "https://chat.whatsapp.com/B6jTEYTbDzp6DHsWSk7vC0"},
            {"Karnataka", "Belgaum", "https://chat.whatsapp.com/BoE10q12FcKLBuKhbW3KJW"},
            {"Karnataka", "Bellary", "https://chat.whatsapp.com/KkStU01lWfIC3qd3f3NpB4"},
            {"Karnataka", "Bidar", "https://chat.whatsapp.com/HaU26fm6m7b8NAwsRHeFz1"},
            {"Karnataka", "Bijapur", "https://chat.whatsapp.com/CIJJqSsgAlt7L0UFo3qEPN"},
            {"Karnataka", "Chamarajanagar", "https://chat.whatsapp.com/D5LLoB50gK1ItXHhcYL1fc"},
            {"Karnataka", "Chikkballapur", "https://chat.whatsapp.com/KvPJt8VwMq38TvoAvLgerF"},
            {"Karnataka", "Chikkodi", "https://chat.whatsapp.com/IMaIhz3CVkl5GAJTHxxPnb"},
            {"Karnataka", "Chitradurga", "https://chat.whatsapp.com/KPEtELWHN6NEBiDUjX2pIm"},
            {"Karnataka", "Dakshina Kannada", "https://chat.whatsapp.com/JTurnZ1prUhI3LTPFkkhX3"},
            {"Karnataka", "Davanagere", "https://chat.whatsapp.com/BUSRhuGj4xf6frjQjypQCR"},
            {"Karnataka", "Dharwad", "https://chat.whatsapp.com/FXUSe9d8xt4LXSsfG8gVPS"},
            {"Karnataka", "Gulbarga", "https://chat.whatsapp.com/HtmaC4ui0OtGJVWb7bGFqF"},
            {"Karnataka", "Hassan", "https://chat.whatsapp.com/C28XzyyASaX0ICNWhqaE3L"},
            {"Karnataka", "Haveri", "https://chat.whatsapp.com/Hcg70N3tpeMI2OoZn5nXWW"},
            {"Karnataka", "Kolar", "https://chat.whatsapp.com/FQEdH9X2Ie6EVpscP4Dv1N"},
            {"Karnataka", "Koppal", "https://chat.whatsapp.com/LEm1ifo4F8T0jenIudGf8T"},
            {"Karnataka", "Mandya", "https://chat.whatsapp.com/KS0G5PCzm6DAwdJVShe9fl"},
            {"Karnataka", "Mysore", "https://chat.whatsapp.com/FEisEIEk48N88CNu2kfmXP"},
            {"Karnataka", "Raichur", "https://chat.whatsapp.com/K6ONfjbFKxeBx1TcLrzu13"},
            {"Karnataka", "Shimoga", "https://chat.whatsapp.com/D7ScMQi0qmg31QIWCnoO3f"},
            {"Karnataka", "Tumkur", "https://chat.whatsapp.com/J0lV88f0uFwKM7jv5Z9etn"},
            {"Karnataka", "Udupi Chikmagalur", "https://chat.whatsapp.com/LvpP5gKltyk3Jvi3NcHt8E"},
            {"Karnataka", "Uttara Kannada", "https://chat.whatsapp.com/G7rUae6iKQY1eWolCsxELo"},
            {"Kerala", "Alappuzha", "https://chat.whatsapp.com/GSOEgE88MKT7sxAcHvNeso"},
            {"Kerala", "Alathur", "https://chat.whatsapp.com/G7tchQ2bxVA6klcOyWU73J"},
            {"Kerala", "Attingal", "https://chat.whatsapp.com/Bkw9pYwbwXOLocIIsAiVOL"},
            {"Kerala", "Chalakudy", "https://chat.whatsapp.com/KcN4UIeiJflC4sIlh3a6TS"},
            {"Kerala", "Ernakulam", "https://chat.whatsapp.com/KDLwNP4WdvvJZV7wRHZcWf"},
            {"Kerala", "Idukki", "https://chat.whatsapp.com/CbMsZqFJt8sCkwSM9vDmdc"},
            {"Kerala", "Kannur", "https://chat.whatsapp.com/BXJPna1v7ig8rJ82ajijh7"},
            {"Kerala", "Kasaragod", "https://chat.whatsapp.com/ILjrJYL7LaF5tBl4tq4IY8"},
            {"Kerala", "Kollam", "https://chat.whatsapp.com/Jzu2IIvQYXM8Gv3z3wCoI4"},
            {"Kerala", "Kottayam", "https://chat.whatsapp.com/JVUsAwJaXMA4NRLZWmg89f"},
            {"Kerala", "Kozhikode", "https://chat.whatsapp.com/BsA7UEq389D4eEvz4zEa1Q"},
            {"Kerala", "Malappuram", "https://chat.whatsapp.com/LdNIWJWEwMkDnSr2Gd7HWg"},
            {"Kerala", "Mavelikkara", "https://chat.whatsapp.com/GlzCKvQmbpVHoxz8WrX2K6"},
            {"Kerala", "Palakkad", "https://chat.whatsapp.com/FaHwKyTFaajIYxGEur49iO"},
            {"Kerala", "Pathanamthitta", "https://chat.whatsapp.com/FiZmynol88dJ0CE3G3LFHi"},
            {"Kerala", "Ponnani", "https://chat.whatsapp.com/FNbj5qZRIM8ENncC7VqmKU"},
            {"Kerala", "Thiruvananthapuram", "https://chat.whatsapp.com/CtHxYDKu8zJIuPLc0cqfOy"},
            {"Kerala", "Thrissur", "https://chat.whatsapp.com/IXGyHmRoLZk9qZjlXeqy6o"},
            {"Kerala", "Vadakara", "https://chat.whatsapp.com/Irs4V1KWwgD84I4KoJrUOc"},
            {"Kerala", "Wayanad", "https://chat.whatsapp.com/DvRkXSgk5t14sKYiJpb4vC"},
            {"Lakshadweep", "Lakshadweep", "https://chat.whatsapp.com/JMM7fOfKlw33cp42apJTBK"},
            {"Madhya Pradesh", "Balaghat", "https://chat.whatsapp.com/JS3CYvQCpCA9D5Y2HzcdEv"},
            {"Madhya Pradesh", "Betul", "https://chat.whatsapp.com/LH8TxzVCNTOHKXYmy0S8gE"},
            {"Madhya Pradesh", "Bhind", "https://chat.whatsapp.com/Hskz0dpk02TLi5ltCWoKYR"},
            {"Madhya Pradesh", "Bhopal", "https://chat.whatsapp.com/IiFYmoaNAGsCIFBbTCOxEg"},
            {"Madhya Pradesh", "Chhindwara", "https://chat.whatsapp.com/IXgF6uFzGAD2nv3Oj9c2BL"},
            {"Madhya Pradesh", "Damoh", "https://chat.whatsapp.com/HvFpT4oT7n50FfjaZCYd1i"},
            {"Madhya Pradesh", "Dewas", "https://chat.whatsapp.com/GXItrjUMGCdFhNRREApHUQ"},
            {"Madhya Pradesh", "Dhar", "https://chat.whatsapp.com/L2gTvqHnu3XBGL0k6sKVIM"},
            {"Madhya Pradesh", "Guna", "https://chat.whatsapp.com/CBTUBLoFktR4qDvmyxjdTa"},
            {"Madhya Pradesh", "Gwalior", "https://chat.whatsapp.com/KZzgo940A05DDjGyhIN5ij"},
            {"Madhya Pradesh", "Hoshangabad", "https://chat.whatsapp.com/E4Rb6fpBzd8GH7UXiiFZya"},
            {"Madhya Pradesh", "Indore", "https://chat.whatsapp.com/GmEqqKF27cVJdVM2hcX91I"},
            {"Madhya Pradesh", "Jabalpur", "https://chat.whatsapp.com/HlJW0pFwGdIDkOef6jWaR4"},
            {"Madhya Pradesh", "Khajuraho", "https://chat.whatsapp.com/BJAEwC4bnqNJhpUkCUfBF2"},
            {"Madhya Pradesh", "Khandwa", "https://chat.whatsapp.com/DeNqcbpinn51i52Cl9lk8o"},
            {"Madhya Pradesh", "Khargone", "https://chat.whatsapp.com/JW97lenJUxU2OO0epIfKw1"},
            {"Madhya Pradesh", "Mandla", "https://chat.whatsapp.com/BkrATtAoYvEK5rEJwK9Gsz"},
            {"Madhya Pradesh", "Mandsour", "https://chat.whatsapp.com/Gnb2nJv94TH47uT3W6BDfn"},
            {"Madhya Pradesh", "Morena", "https://chat.whatsapp.com/ESdbLlHe7dO5GB9t5TyGAI"},
            {"Madhya Pradesh", "Rajgarh", "https://chat.whatsapp.com/Iz6eSKrokCuHGXJwQ6ibps"},
            {"Madhya Pradesh", "Ratlam", "https://chat.whatsapp.com/ENzlLW8tjVW6zA2ohGKHOs"},
            {"Madhya Pradesh", "Rewa", "https://chat.whatsapp.com/BZKAlV94FuN5dDE4f5pT9O"},
            {"Madhya Pradesh", "Sagar", "https://chat.whatsapp.com/LZu4OB9RqOIBX58afToiN7"},
            {"Madhya Pradesh", "Satna", "https://chat.whatsapp.com/LUhZrb6KUNU9jnYgOQxzV9"},
            {"Madhya Pradesh", "Shahdol", "https://chat.whatsapp.com/EBvgoH9KhTK1nCLeo428SX"},
            {"Madhya Pradesh", "Sidhi", "https://chat.whatsapp.com/Iqm6MTJfuqP8op9Wpe7c32"},
            {"Madhya Pradesh", "Tikamgarh", "https://chat.whatsapp.com/Kj5wgbrdGl0JlUA7UZQ3YA"},
            {"Madhya Pradesh", "Ujjain", "https://chat.whatsapp.com/GgSnjWYhHpU9nwlYitvT3p"},
            {"Madhya Pradesh", "Vidisha", "https://chat.whatsapp.com/KrTqUHkI0enCZsrVDdPW2X"},
            {"Maharashtra", "Ahmednagar", "https://chat.whatsapp.com/JsaJZSsfYb0AtyhWtyDdWo"},
            {"Maharashtra", "Akola", "https://chat.whatsapp.com/F0rWko9XZw306Af1dSMEVA"},
            {"Maharashtra", "Amravati", "https://chat.whatsapp.com/LrDDmNb04ez1q0oNd5nWgQ"},
            {"Maharashtra", "Aurangabad", "https://chat.whatsapp.com/E6VuTYJzNPTHHsthX9IVEP"},
            {"Maharashtra", "Baramati", "https://chat.whatsapp.com/KMgvI3JN2zJ0J1sZrECLeQ"},
            {"Maharashtra", "Beed", "https://chat.whatsapp.com/Jg5PVXJh8SGEGeiYG3vlMH"},
            {"Maharashtra", "Bhandara Gondiya", "https://chat.whatsapp.com/CQYDQJbraLD3G0yU9yKjxo"},
            {"Maharashtra", "Bhiwandi", "https://chat.whatsapp.com/Hilri1rNPSDAjcHE9XX8cY"},
            {"Maharashtra", "Buldhana", "https://chat.whatsapp.com/BjvsJHHzZRhJZrsdl58YF4"},
            {"Maharashtra", "Chandrapur", "https://chat.whatsapp.com/IQVzPdCGgbACIK4nzhqagO"},
            {"Maharashtra", "Dhule", "https://chat.whatsapp.com/HJjb3Fivg0L4DTjkh04XcU"},
            {"Maharashtra", "Dindori", "https://chat.whatsapp.com/DZiUrBucK5kCC8GL5NNwZu"},
            {"Maharashtra", "Gadchiroli Chimur", "https://chat.whatsapp.com/DjBLDTSmZw4GmPSJiThmFv"},
            {"Maharashtra", "Hatkanangle", "https://chat.whatsapp.com/GuyI99594gH1mte9b6TUG5"},
            {"Maharashtra", "Hingoli", "https://chat.whatsapp.com/JHEM7zvpWSB4vXIF90pKGj"},
            {"Maharashtra", "Jalgaon", "https://chat.whatsapp.com/DwaTkqiDFQN0f0fliXP2rX"},
            {"Maharashtra", "Jalna", "https://chat.whatsapp.com/GyCHPU0xuRrGHm4Vbjn2fx"},
            {"Maharashtra", "Kalyan", "https://chat.whatsapp.com/Jk8eD0rbvNTKxo3dhLbl96"},
            {"Maharashtra", "Kolhapur", "https://chat.whatsapp.com/GU2yJL9fVgQ7wKGB3piEzW"},
            {"Maharashtra", "Latur", "https://chat.whatsapp.com/FCp2PXfAt2t8FOnTIG9eb5"},
            {"Maharashtra", "Madha", "https://chat.whatsapp.com/FPqMTq7R6i68vuVLuuYUzn"},
            {"Maharashtra", "Maval", "https://chat.whatsapp.com/KuKDxvTGI4QGMk2KPbT9sx"},
            {"Maharashtra", "Mumbai North", "https://chat.whatsapp.com/Gh9EkrlnZWX1g2c0ocRlxP"},
            {"Maharashtra", "Mumbai North Central", "https://chat.whatsapp.com/LRe2HcCsl4SIbkksXo3AWk"},
            {"Maharashtra", "Mumbai North East", "https://chat.whatsapp.com/Jlcrv7zMOTF9TmzeB4C1to"},
            {"Maharashtra", "Mumbai North West", "https://chat.whatsapp.com/EGZDJeDxAL58hR9G8AOeXO"},
            {"Maharashtra", "Mumbai South", "https://chat.whatsapp.com/DK2369HA5R36C5wgCnkO93"},
            {"Maharashtra", "Mumbai South Central", "https://chat.whatsapp.com/DwZZenLsJZnLtqI7mn9Yk8"},
            {"Maharashtra", "Nagpur", "https://chat.whatsapp.com/IfFoDtSA4F72WVwyLdZXD5"},
            {"Maharashtra", "Nanded", "https://chat.whatsapp.com/LHdD4mYrsthEIVGd9mwHHa"},
            {"Maharashtra", "Nandurbar", "https://chat.whatsapp.com/Bhgx3fTPvMQI7NlErtNFkh"},
            {"Maharashtra", "Nashik", "https://chat.whatsapp.com/LgxvjBXHNxfBJLw1QsKZex"},
            {"Maharashtra", "Osmanabad", "https://chat.whatsapp.com/LIeR1AyQ0Jd8vYY99nxVrJ"},
            {"Maharashtra", "Palghar", "https://chat.whatsapp.com/ESW3WaFRXz47utQPtbJNia"},
            {"Maharashtra", "Parbhani", "https://chat.whatsapp.com/CxFK8yBKGLiBgw6J9WVk9j"},
            {"Maharashtra", "Pune", "https://chat.whatsapp.com/CubadXb6toKBDoB3zN4cWe"},
            {"Maharashtra", "Raigad", "https://chat.whatsapp.com/LXovDAIYSSPCmsXWtZjFMb"},
            {"Maharashtra", "Ramtek", "https://chat.whatsapp.com/Hcu55IGPdkm2mOTySyntW2"},
            {"Maharashtra", "Ratnagiri Sindhudurg", "https://chat.whatsapp.com/FHgeDhypBBvJB36NnW9ILH"},
            {"Maharashtra", "Raver", "https://chat.whatsapp.com/HV2wAzcdDi3CkQzACPTHpk"},
            {"Maharashtra", "Sangli", "https://chat.whatsapp.com/EaJ93TSe7jtAgMxrt5uEGZ"},
            {"Maharashtra", "Satara", "https://chat.whatsapp.com/KYbp7hGJtoZFwhatQwuA2q"},
            {"Maharashtra", "Shirdi", "https://chat.whatsapp.com/DJM3Td6LwAd9evfTrW4JJ0"},
            {"Maharashtra", "Shirur", "https://chat.whatsapp.com/K2Adj7kQdQv6D05G03en2m"},
            {"Maharashtra", "Solapur", "https://chat.whatsapp.com/KHtF1G8NlKS9vXrY08UCzJ"},
            {"Maharashtra", "Thane", "https://chat.whatsapp.com/COaxu5fv8KAD6t5j16hh6u"},
            {"Maharashtra", "Wardha", "https://chat.whatsapp.com/FRqgm0fcOy84jId5sGyW31"},
            {"Maharashtra", "Yavatmal-Washim", "https://chat.whatsapp.com/CgnhG9ZAbCuLlOMwY1O0vl"},
            {"Manipur", "Inner Manipur", "https://chat.whatsapp.com/Kuk7AoB0dpNFYClrUIHEL7"},
            {"Manipur", "Outer Manipur", "https://chat.whatsapp.com/BJU258HQQSMJABJeLFbYlH"},
            {"Meghalaya", "Shillong", "https://chat.whatsapp.com/KdFwHOg3vO3280T7MRFmNC"},
            {"Meghalaya", "Tura", "https://chat.whatsapp.com/BVGixcfajgKFhZGdbomqmq"},
            {"Mizoram", "Mizoram", "https://chat.whatsapp.com/GUSKLTfiRS80ZRoFXsPnZ6"},
            {"Nagaland", "Nagaland", "https://chat.whatsapp.com/DP21Uvl5OTU1llqHKGL3ux"},
            {"National Capital Territory of Delhi", "Chandni Chowk", "https://chat.whatsapp.com/FilP9Xbnhc7IJFkNDdQlre"},
            {"National Capital Territory of Delhi", "East Delhi", "https://chat.whatsapp.com/KeCoaAmWQyL4Xcabh0KzG0"},
            {"National Capital Territory of Delhi", "New Delhi", "https://chat.whatsapp.com/Drx2A3YB7tbAEsLvAQxDJK"},
            {"National Capital Territory of Delhi", "North East Delhi", "https://chat.whatsapp.com/GWq3z1mTZUrCCSBEUKARRD"},
            {"National Capital Territory of Delhi", "North West Delhi", "https://chat.whatsapp.com/KTuR1C8zh60CJtMXvGFPn4"},
            {"National Capital Territory of Delhi", "South Delhi", "https://chat.whatsapp.com/KVqOpZwkIfWFZd519lF6gE"},
            {"National Capital Territory of Delhi", "West Delhi", "https://chat.whatsapp.com/IgPT70lR3htHFniA5ptgCa"},
            {"Odisha", "Aska", "https://chat.whatsapp.com/Koowe6pzQJg54U2Wp62Lsb"},
            {"Odisha", "Balasore", "https://chat.whatsapp.com/HI8z7m45mlpF6EYBrbYhXe"},
            {"Odisha", "Bargarh", "https://chat.whatsapp.com/KhMDPj4BQfi8Tz4ncVMgVC"},
            {"Odisha", "Berhampur", "https://chat.whatsapp.com/IyAu07PdCQl3NGGjN126I3"},
            {"Odisha", "Bhadrak", "https://chat.whatsapp.com/D66gHxyc2aiFfa1kolUK6Q"},
            {"Odisha", "Bhubaneswar", "https://chat.whatsapp.com/FT90v3qnJMEK2sBXKqiZ7L"},
            {"Odisha", "Bolangir", "https://chat.whatsapp.com/GwoDkj0UHa1GqLL2Kl9EQB"},
            {"Odisha", "Cuttack", "https://chat.whatsapp.com/HtB46xH4tk1Ebe71Y8Ced5"},
            {"Odisha", "Dhenkanal", "https://chat.whatsapp.com/FpPZ4kGB0Pz637kt3Fv2k2"},
            {"Odisha", "Jagatsinghpur", "https://chat.whatsapp.com/CZYpggvhT1y4SjxqIVUcSQ"},
            {"Odisha", "Jajpur", "https://chat.whatsapp.com/FxtF1To0RgI7cWMjnRovi2"},
            {"Odisha", "Kalahandi", "https://chat.whatsapp.com/GcyWn8ct7s2I7plYGupvzs"},
            {"Odisha", "Kandhamal", "https://chat.whatsapp.com/ETd0M75wsnpHnLz0yVJVXd"},
            {"Odisha", "Kendrapara", "https://chat.whatsapp.com/BZUlrPtUbeN33HWbt7uIOg"},
            {"Odisha", "Keonjhar", "https://chat.whatsapp.com/Ky9b5tCBIf4JzmaHB7oxTl"},
            {"Odisha", "Koraput", "https://chat.whatsapp.com/Hc4al6n8u0k1LRBfNEJigP"},
            {"Odisha", "Mayurbhanj", "https://chat.whatsapp.com/K4oUZJka5TAC0bpUnO2Dna"},
            {"Odisha", "Nabarangpur", "https://chat.whatsapp.com/JClkKlIYzMg5Ct6smIwiyx"},
            {"Odisha", "Puri", "https://chat.whatsapp.com/DDKioMDoxfaJ5pPnwh5F2S"},
            {"Odisha", "Sambalpur", "https://chat.whatsapp.com/CKazvWR6Xqq8Z2uprVhS90"},
            {"Odisha", "Sundargarh", "https://chat.whatsapp.com/EgtsjuZqBTQJDCuVAYIrsv"},
            {"Puducherry", "Puducherry", "https://chat.whatsapp.com/BAhRL0bCALtKtBj0h8lhuc"},
            {"Punjab", "Amritsar", "https://chat.whatsapp.com/ClI7ji2NJReIPXYILrjFpE"},
            {"Punjab", "Anandpur Sahib", "https://chat.whatsapp.com/Htix8QLaUkUGrSaXNnCtp2"},
            {"Punjab", "Bathinda", "https://chat.whatsapp.com/Fwn0ryLXHvm076momVfAOb"},
            {"Punjab", "Faridkot", "https://chat.whatsapp.com/GLFvQrwkMZAEHKzdUCEVnn"},
            {"Punjab", "Fatehgarh Sahib", "https://chat.whatsapp.com/ENqJDxWsP5lAQjSMc1eQ9K"},
            {"Punjab", "Firozpur", "https://chat.whatsapp.com/HOoxaU6wdMMIe0cSB8co3x"},
            {"Punjab", "Gurdaspur", "https://chat.whatsapp.com/H2rCDqfi1JAKiJFwTSBOVY"},
            {"Punjab", "Hoshiarpur", "https://chat.whatsapp.com/JDdwUHBGKz94HbgddKxSLR"},
            {"Punjab", "Jalandhar", "https://chat.whatsapp.com/ItVxiAdSPbCKZeuPZFNDfM"},
            {"Punjab", "Khadoor Sahib", "https://chat.whatsapp.com/ER85h0pi7RF73A6a5jJQXh"},
            {"Punjab", "Ludhiana", "https://chat.whatsapp.com/COZKGAGrVtlDhKmQbZHDEQ"},
            {"Punjab", "Patiala", "https://chat.whatsapp.com/LddzEjTexJO2xjAOgMVIaa"},
            {"Punjab", "Sangrur", "https://chat.whatsapp.com/CfSZmmJAdScLlvfjs3o8Tg"},
            {"Rajasthan", "Ajmer", "https://chat.whatsapp.com/LNeillASsog2Dy5o7k4f6z"},
            {"Rajasthan", "Alwar", "https://chat.whatsapp.com/Islv4rdJkak2fPcqAcrcke"},
            {"Rajasthan", "Banswara", "https://chat.whatsapp.com/FZSm9rhY8qy3nLJkeHKAZI"},
            {"Rajasthan", "Barmer", "https://chat.whatsapp.com/FzrApCCKyWaK4WodC4Zv1e"},
            {"Rajasthan", "Bharatpur", "https://chat.whatsapp.com/FcCOSNM3ffm1QNe9JZmHMu"},
            {"Rajasthan", "Bhilwara", "https://chat.whatsapp.com/JHzHfsqbDbZFDVoXGola26"},
            {"Rajasthan", "Bikaner", "https://chat.whatsapp.com/LyHfGIKcFm5HhUHZs8FbWR"},
            {"Rajasthan", "Chittorgarh", "https://chat.whatsapp.com/CRdxKzSiDPhKSKvAgCEYzK"},
            {"Rajasthan", "Churu", "https://chat.whatsapp.com/KMh8oqZJOqjDdar2sYlfSm"},
            {"Rajasthan", "Dausa", "https://chat.whatsapp.com/DN0BtL1SfkN5dTCiuDdoef"},
            {"Rajasthan", "Ganganagar", "https://chat.whatsapp.com/HdOQDmyknO3Dm17346xrzX"},
            {"Rajasthan", "Jaipur", "https://chat.whatsapp.com/IYHurEjTGJKAQ6UkRJxxFG"},
            {"Rajasthan", "Jaipur Rural", "https://chat.whatsapp.com/CJ3Q7D30oaOK4dZdCqVDeP"},
            {"Rajasthan", "Jalore", "https://chat.whatsapp.com/HbebS2yLXmx5x3r7zanAkB"},
            {"Rajasthan", "Jhalawar Baran", "https://chat.whatsapp.com/ImaZ8eqfWEI2hLAqzbeMJs"},
            {"Rajasthan", "Jhunjhunu", "https://chat.whatsapp.com/BqWY1jeaKpC8mqFSQC5QCM"},
            {"Rajasthan", "Jodhpur", "https://chat.whatsapp.com/Gaq9Jm3KQ4ZDvYdou1Naxr"},
            {"Rajasthan", "Karauli Dholpur", "https://chat.whatsapp.com/F8BycpLjUlUBLB1JiDuFcV"},
            {"Rajasthan", "Kota", "https://chat.whatsapp.com/BomISekuppbKJuywaUjojD"},
            {"Rajasthan", "Nagaur", "https://chat.whatsapp.com/BqGpj23YBmT47bvJWkV1YX"},
            {"Rajasthan", "Pali", "https://chat.whatsapp.com/Jispz5V8ELoD6Zu5mioTDy"},
            {"Rajasthan", "Rajsamand", "https://chat.whatsapp.com/KgcPOBiEuW5H2PfQiKESMa"},
            {"Rajasthan", "Sikar", "https://chat.whatsapp.com/BCMlEnhAyoV0ypkcfYhqjc"},
            {"Rajasthan", "Tonk Sawai Madhopur", "https://chat.whatsapp.com/BTVFjiv4VK1Ec0TreoB9vU"},
            {"Rajasthan", "Udaipur", "https://chat.whatsapp.com/DhNwAqWIyxB70dz5vibwX5"},
            {"Sikkim", "Sikkim", "https://chat.whatsapp.com/INKwbj8mHfhEmQMNyDch3k"},
            {"Tamil Nadu", "Arakkonam", "https://chat.whatsapp.com/ByUqNOdQGA7DqccZpoFIfx"},
            {"Tamil Nadu", "Arani", "https://chat.whatsapp.com/BQmTgLP0FZv2cICa3dPZ0p"},
            {"Tamil Nadu", "Chennai Central", "https://chat.whatsapp.com/DeSlMJTxQmSHCJrbwrnPvU"},
            {"Tamil Nadu", "Chennai North", "https://chat.whatsapp.com/I40bdJjnBxWITsWxDD41GK"},
            {"Tamil Nadu", "Chennai South", "https://chat.whatsapp.com/BUFXB71XKl8Ko40mS7QoVR"},
            {"Tamil Nadu", "Chidambaram", "https://chat.whatsapp.com/Ko4vZA6aEITHET0ITfKw13"},
            {"Tamil Nadu", "Coimbatore", "https://chat.whatsapp.com/CArErHye06f5XZvkLSktE9"},
            {"Tamil Nadu", "Cuddalore", "https://chat.whatsapp.com/CCI2LH07OTz21XGhtvjCT5"},
            {"Tamil Nadu", "Dharmapuri", "https://chat.whatsapp.com/JZqlax8vDSuLizCpCIALtU"},
            {"Tamil Nadu", "Dindigul", "https://chat.whatsapp.com/DMMYamBtnbwEFBDRYuKGEB"},
            {"Tamil Nadu", "Erode", "https://chat.whatsapp.com/I09JrKqbsf46hNcqiU5xtG"},
            {"Tamil Nadu", "Kallakurichi", "https://chat.whatsapp.com/HPxPV0CPHtZ1DRLInIN7Wb"},
            {"Tamil Nadu", "Kancheepuram", "https://chat.whatsapp.com/KY5xbzNllOMCiexU0iN4eK"},
            {"Tamil Nadu", "Kanniyakumari", "https://chat.whatsapp.com/Icy9qLowEyM37YlJmcDg5m"},
            {"Tamil Nadu", "Karur", "https://chat.whatsapp.com/Lr3hBMy1NgBKVuMn2O3Jyz"},
            {"Tamil Nadu", "Krishnagiri", "https://chat.whatsapp.com/IAP82zetcstIoHw9dYej12"},
            {"Tamil Nadu", "Madurai", "https://chat.whatsapp.com/JKiH4ZafLsl4REYJlZFXP9"},
            {"Tamil Nadu", "Mayiladuthurai", "https://chat.whatsapp.com/Hn4qgShrDDW22DX9oPx9wv"},
            {"Tamil Nadu", "Nagapattinam", "https://chat.whatsapp.com/JYiTTVFeF6LC8TdKwUDu4C"},
            {"Tamil Nadu", "Namakkal", "https://chat.whatsapp.com/H8h1S18VhBzIHd9tkCUg2n"},
            {"Tamil Nadu", "Nilgiris", "https://chat.whatsapp.com/BQ4NbxRfE2E3MeS5DQqXtw"},
            {"Tamil Nadu", "Perambalur", "https://chat.whatsapp.com/L5lvIt8aF9d18UfKwiLXY1"},
            {"Tamil Nadu", "Pollachi", "https://chat.whatsapp.com/LIOcjPgcBoGFXErewjraCx"},
            {"Tamil Nadu", "Ramanathapuram", "https://chat.whatsapp.com/Hvrhx0zJEZ14G1v0ggI3py"},
            {"Tamil Nadu", "Salem", "https://chat.whatsapp.com/Ea0c9CmfNlG7MNgQdnC2vr"},
            {"Tamil Nadu", "Sivaganga", "https://chat.whatsapp.com/KkdY04TWhNCFdpZnRpNFqe"},
            {"Tamil Nadu", "Sriperumbudur", "https://chat.whatsapp.com/FanxRjvU5EM2wnUf6tnLjJ"},
            {"Tamil Nadu", "Tenkasi", "https://chat.whatsapp.com/LoEHlqzGfhgC1jiGfK93lu"},
            {"Tamil Nadu", "Thanjavur", "https://chat.whatsapp.com/LRUF7y7UdjXDxfUy286a4d"},
            {"Tamil Nadu", "Theni", "https://chat.whatsapp.com/Dpbg4oNjG2SAQsVwtahKSW"},
            {"Tamil Nadu", "Thoothukkudi", "https://chat.whatsapp.com/IkPZLmXGeXgEE3xrf44haT"},
            {"Tamil Nadu", "Tiruchirappalli", "https://chat.whatsapp.com/KRdR4j9caan2824nQtyUba"},
            {"Tamil Nadu", "Tirunelveli", "https://chat.whatsapp.com/KtKElfywMyv6i0mP3pmJiG"},
            {"Tamil Nadu", "Tiruppur", "https://chat.whatsapp.com/Ec5gPPYu7QsGtKkq09cxtW"},
            {"Tamil Nadu", "Tiruvallur", "https://chat.whatsapp.com/I33XlyGuacKDp3aSedq7rX"},
            {"Tamil Nadu", "Tiruvannamalai", "https://chat.whatsapp.com/KtxhhAY3Wnf85shtXzFZcp"},
            {"Tamil Nadu", "Viluppuram", "https://chat.whatsapp.com/KFZSQepTdkQBH6a53ax7PB"},
            {"Telangana", "Adilabad", "https://chat.whatsapp.com/EEmtqZ5L6WNKCcbVCXllcB"},
            {"Telangana", "Bhongir", "https://chat.whatsapp.com/HKqxd6EguEI8BS8k4FcBNY"},
            {"Telangana", "Chevella", "https://chat.whatsapp.com/GBCAkL6N4KcJ4Fv8CXijFs"},
            {"Telangana", "Hyderabad", "https://chat.whatsapp.com/IIUYwO46Byi5lfPtyMKppo"},
            {"Telangana", "Karimnagar", "https://chat.whatsapp.com/Bm7F7YLtYRe1lFhu250kVP"},
            {"Telangana", "Khammam", "https://chat.whatsapp.com/G7rv913DQws1t0soIAU3UK"},
            {"Telangana", "Mahabubabad", "https://chat.whatsapp.com/HK1ya7LKh8bKRSyVyq5TtX"},
            {"Telangana", "Mahbubnagar", "https://chat.whatsapp.com/LNVEFMyEvLQKP3WmI8DTPm"},
            {"Telangana", "Malkajgiri", "https://chat.whatsapp.com/KRfS7KydWs2J94Va8wdPia"},
            {"Telangana", "Medak", "https://chat.whatsapp.com/LEud35481kFLJ6I27vRgho"},
            {"Telangana", "Nagarkurnool", "https://chat.whatsapp.com/LnfWvmRrOxmKwsAb1331TB"},
            {"Telangana", "Nalgonda", "https://chat.whatsapp.com/H7fxu4tTp0LFJ5poGUhDYg"},
            {"Telangana", "Nizamabad", "https://chat.whatsapp.com/DIvRjk3jUC06czM3ahCo02"},
            {"Telangana", "Peddapalle", "https://chat.whatsapp.com/GOB3YMukbfp2p9HmcO2eZ1"},
            {"Telangana", "Secunderabad", "https://chat.whatsapp.com/GYM6ipfN96H3AlsHfvjSdB"},
            {"Telangana", "Warangal", "https://chat.whatsapp.com/HBCJllvjIqN5dnZs9NDiDI"},
            {"Telangana", "Zahirabad", "https://chat.whatsapp.com/FspEcq5vgRoHTXjBqTlooC"},
            {"Tripura", "Tripura East", "https://chat.whatsapp.com/ERYgQSYtRfQLrQaVz5gsFm"},
            {"Tripura", "Tripura West", "https://chat.whatsapp.com/KPczJgSF9r7BzWw3toaiy3"},
            {"Uttar Pradesh", "Agra", "https://chat.whatsapp.com/BluHoIsfY4VEjGxocFhbOA"},
            {"Uttar Pradesh", "Aligarh", "https://chat.whatsapp.com/LVLX8lybc4XGKAVBeWQYKi"},
            {"Uttar Pradesh", "Allahabad", "https://chat.whatsapp.com/EnZ7FLH910kCnjk4fdCfly"},
            {"Uttar Pradesh", "Ambedkar Nagar", "https://chat.whatsapp.com/GGm5pOqqOjVKdpIkhW6qZL"},
            {"Uttar Pradesh", "Amethi", "https://chat.whatsapp.com/JfGXJmARuhW4sDaUYxcdQV"},
            {"Uttar Pradesh", "Amroha", "https://chat.whatsapp.com/IFgzZ1JTTHq6qILPXGNILA"},
            {"Uttar Pradesh", "Aonla", "https://chat.whatsapp.com/J0hcB6gJpfTJAa75mb5s4x"},
            {"Uttar Pradesh", "Azamgarh", "https://chat.whatsapp.com/HR99eMXi0zJ1J78eosBFiu"},
            {"Uttar Pradesh", "Badaun", "https://chat.whatsapp.com/HGYxiuRcXK27MlSX8ipYXV"},
            {"Uttar Pradesh", "Baghpat", "https://chat.whatsapp.com/FdE1qfoxSnLLN1nVpqUw1a"},
            {"Uttar Pradesh", "Bahraich", "https://chat.whatsapp.com/DJWpPh40U15EdMhtAXtcyw"},
            {"Uttar Pradesh", "Ballia", "https://chat.whatsapp.com/FEx5wSEiUXvFR99bRXWdGl"},
            {"Uttar Pradesh", "Banda", "https://chat.whatsapp.com/LUma3UrAHnrKaX0ARytd9l"},
            {"Uttar Pradesh", "Bansgaon", "https://chat.whatsapp.com/Jd8cYbRtlnj37cP1AAKbZK"},
            {"Uttar Pradesh", "Barabanki", "https://chat.whatsapp.com/CsBgpbXCH885M8xaAauxcl"},
            {"Uttar Pradesh", "Bareilly", "https://chat.whatsapp.com/IWZ6QWpAD6n3z9RdKnAyze"},
            {"Uttar Pradesh", "Basti", "https://chat.whatsapp.com/EXgj13pXyOvHa8jlPrVSa4"},
            {"Uttar Pradesh", "Bhadohi", "https://chat.whatsapp.com/Ebr3n9NgY662JZ0VpsTXao"},
            {"Uttar Pradesh", "Bijnor", "https://chat.whatsapp.com/I1SGP6pjJcfCfh2nWgjq4S"},
            {"Uttar Pradesh", "Bulandshahr", "https://chat.whatsapp.com/IJjbufpJXvmGKN8s0xFrAe"},
            {"Uttar Pradesh", "Chandauli", "https://chat.whatsapp.com/IzhDpJtA7elKj7Yqr88tpr"},
            {"Uttar Pradesh", "Deoria", "https://chat.whatsapp.com/LK0yIRpwChbI0PYxmiSryz"},
            {"Uttar Pradesh", "Dhaurahra", "https://chat.whatsapp.com/J7nVJvk1qU7FHMp4P7uyLm"},
            {"Uttar Pradesh", "Domariyaganj", "https://chat.whatsapp.com/IduwU2CtWvVJAjbCZLqIu9"},
            {"Uttar Pradesh", "Etah", "https://chat.whatsapp.com/IMFa48mDT3L42L0Kq3RUc4"},
            {"Uttar Pradesh", "Etawah", "https://chat.whatsapp.com/HQm9xlmjQViARL1PINpPed"},
            {"Uttar Pradesh", "Faizabad", "https://chat.whatsapp.com/FAu8UG4JpFuAtQAh8qx4fr"},
            {"Uttar Pradesh", "Farrukhabad", "https://chat.whatsapp.com/D12a3BeVGu8Ddn1it8ovkD"},
            {"Uttar Pradesh", "Fatehpur", "https://chat.whatsapp.com/HrquiThfn0NLlzCSiKNWEq"},
            {"Uttar Pradesh", "Fatehpur Sikri", "https://chat.whatsapp.com/DnQgKLgS6uQ3cR3JZln76R"},
            {"Uttar Pradesh", "Firozabad", "https://chat.whatsapp.com/IA8tomv3faQ6TlwCc3dkZ3"},
            {"Uttar Pradesh", "Gautam Buddha Nagar", "https://chat.whatsapp.com/KGfJWSTUTG1GyNbRe7fokd"},
            {"Uttar Pradesh", "Ghaziabad", "https://chat.whatsapp.com/ECOvb59i2VyJhMwQovZZg5"},
            {"Uttar Pradesh", "Ghazipur", "https://chat.whatsapp.com/ElLMoLX9xIoIZ9p5D7BmXX"},
            {"Uttar Pradesh", "Ghosi", "https://chat.whatsapp.com/FZmVjIjRJ8P0CTf4NytE9c"},
            {"Uttar Pradesh", "Gonda", "https://chat.whatsapp.com/LGhpidfdmM591AOfBB2t0I"},
            {"Uttar Pradesh", "Gorakhpur", "https://chat.whatsapp.com/BSQbmVpipkP0bFpLuXHOGV"},
            {"Uttar Pradesh", "Hamirpur", "https://chat.whatsapp.com/ITfqhfRg19I7Tb4orCutyx"},
            {"Uttar Pradesh", "Hardoi", "https://chat.whatsapp.com/EkTnysGD4IIFl0CISQ1XZL"},
            {"Uttar Pradesh", "Hathras", "https://chat.whatsapp.com/Dap7ApnaBagC9iswFnvA6j"},
            {"Uttar Pradesh", "Jalaun", "https://chat.whatsapp.com/H1YbllWyqRWCBCWCRmWnMk"},
            {"Uttar Pradesh", "Jaunpur", "https://chat.whatsapp.com/HMfvP2j66NN1Z7YnlI3JrO"},
            {"Uttar Pradesh", "Jhansi", "https://chat.whatsapp.com/FgmZC5G51CTEzFXsVWdchV"},
            {"Uttar Pradesh", "Kairana", "https://chat.whatsapp.com/DfnqPsTyoG9C1EQVy100XQ"},
            {"Uttar Pradesh", "Kaiserganj", "https://chat.whatsapp.com/CoXCug2wkgAEwRR41ylSxI"},
            {"Uttar Pradesh", "Kannauj", "https://chat.whatsapp.com/FdRvUrxl5IR23qNHG3a3Ob"},
            {"Uttar Pradesh", "Kanpur", "https://chat.whatsapp.com/Fg5B1a1Mk22KiN5JJQVW7B"},
            {"Uttar Pradesh", "Kaushambi", "https://chat.whatsapp.com/Db7MQaEab59Av5ZjP8Vvfy"},
            {"Uttar Pradesh", "Kheri", "https://chat.whatsapp.com/JMR97WO6FvHLQZ2WacQX9r"},
            {"Uttar Pradesh", "Kushi Nagar", "https://chat.whatsapp.com/LW4SwS8eWjQ4N0FlLcdaVv"},
            {"Uttar Pradesh", "Lalganj", "https://chat.whatsapp.com/IOHn8xG5dVoBnHeLNPIJO6"},
            {"Uttar Pradesh", "Lucknow", "https://chat.whatsapp.com/JY5nFUgg3vZ8wWSLTkZOYv"},
            {"Uttar Pradesh", "Machhlishahr", "https://chat.whatsapp.com/HRQsCo5wH1FFrImFnPO1wr"},
            {"Uttar Pradesh", "Maharajganj", "https://chat.whatsapp.com/DY4v41oliPt2oItDyupXBU"},
            {"Uttar Pradesh", "Mainpuri", "https://chat.whatsapp.com/LaT95ilIIBw0I0MxJMDyev"},
            {"Uttar Pradesh", "Mathura", "https://chat.whatsapp.com/IbLxUDqqKkBHHsxpYlKHYA"},
            {"Uttar Pradesh", "Meerut", "https://chat.whatsapp.com/EdzlUFrGqy3FwKk8UOH1bJ"},
            {"Uttar Pradesh", "Mirzapur", "https://chat.whatsapp.com/Cko9XhANi4aJX9rJzdoYj1"},
            {"Uttar Pradesh", "Misrikh", "https://chat.whatsapp.com/KsaFbwJpNZZ1tQKhIDFHX5"},
            {"Uttar Pradesh", "Mohanlalganj", "https://chat.whatsapp.com/HlsfjSvEtB6LYbzspcMIqm"},
            {"Uttar Pradesh", "Moradabad", "https://chat.whatsapp.com/Dy1ixKYvwx7FeRb9UCFG8t"},
            {"Uttar Pradesh", "Muzaffarnagar", "https://chat.whatsapp.com/BTZvJvJPirR5DghUNVrHrS"},
            {"Uttar Pradesh", "Nagina", "https://chat.whatsapp.com/GaQi4wE0FzCCdbi2nBJyGf"},
            {"Uttar Pradesh", "Phulpur", "https://chat.whatsapp.com/IrtOf9ZhPAW1cooQFvYl5X"},
            {"Uttar Pradesh", "Pilibhit", "https://chat.whatsapp.com/EQ7IvxzqRYDGOO338k7Mav"},
            {"Uttar Pradesh", "Pratapgarh", "https://chat.whatsapp.com/EifVsyHq9OdBovk7xfW4va"},
            {"Uttar Pradesh", "Rae Bareli", "https://chat.whatsapp.com/ByFn2I04BpV4wm6YlfIk4Z"},
            {"Uttar Pradesh", "Rampur", "https://chat.whatsapp.com/KojIbR2TY2G3od8G8HuUpV"},
            {"Uttar Pradesh", "Robertsganj", "https://chat.whatsapp.com/F6eDygzuGYwCNBPhLOFy7C"},
            {"Uttar Pradesh", "Saharanpur", "https://chat.whatsapp.com/FXKKTKalELILpIu5Ho6GKb"},
            {"Uttar Pradesh", "Salempur", "https://chat.whatsapp.com/Jw5eSrHDYiT0Mk0WqxTYl7"},
            {"Uttar Pradesh", "Sambhal", "https://chat.whatsapp.com/IL8uOl2hwGwDU2ztr24gmM"},
            {"Uttar Pradesh", "Sant Kabir Nagar", "https://chat.whatsapp.com/JKAgJgepigMIMlaFnQg3bS"},
            {"Uttar Pradesh", "Shahjahanpur", "https://chat.whatsapp.com/D4tlczwT5Sb5OhvNi55CdV"},
            {"Uttar Pradesh", "Shrawasti", "https://chat.whatsapp.com/BSiXP21l6sdGCNHjYMtU5F"},
            {"Uttar Pradesh", "Sitapur", "https://chat.whatsapp.com/Iplky24gWku8H0VwK4lNzq"},
            {"Uttar Pradesh", "Sultanpur", "https://chat.whatsapp.com/Ks5fID6VlGcGg0WKjrIWLt"},
            {"Uttar Pradesh", "Unnao", "https://chat.whatsapp.com/EFM12Ds6M1YFKc7IcL0f1w"},
            {"Uttar Pradesh", "Varanasi", "https://chat.whatsapp.com/EjYlGYrGOIi6kt98xDjRXo"},
            {"Uttarakhand", "Almora", "https://chat.whatsapp.com/BSIRW7rjMtyFljqtJjX1kM"},
            {"Uttarakhand", "Garhwal", "https://chat.whatsapp.com/J9SsMkOeXm1KByto5DozER"},
            {"Uttarakhand", "Haridwar", "https://chat.whatsapp.com/LFvFjlBB3a74Dp0XL5mpDb"},
            {"Uttarakhand", "Nainital-UdhamSingh Nagar", "https://chat.whatsapp.com/EPisE9CvnqULg9He15W2CP"},
            {"Uttarakhand", "Tehri Garhwal", "https://chat.whatsapp.com/IS5KqpLMZxuFYEwRNuRNAT"},
            {"West Bengal", "Alipurduars", "https://chat.whatsapp.com/CFvb54evJkI42oZZArFbMK"},
            {"West Bengal", "Arambag", "https://chat.whatsapp.com/JFOW2fDIx3o8rGU0H3QApw"},
            {"West Bengal", "Asansol", "https://chat.whatsapp.com/J2SFDFNtU4f8SO2jG11V34"},
            {"West Bengal", "Baharampur", "https://chat.whatsapp.com/KYrjsLuYcr6DexB5D8uk7j"},
            {"West Bengal", "Balurghat", "https://chat.whatsapp.com/CeH0V46HsgLAJOXo5qdJXI"},
            {"West Bengal", "Bangaon", "https://chat.whatsapp.com/JKtIohG9GooJtGK3Q5xcSV"},
            {"West Bengal", "Bankura", "https://chat.whatsapp.com/F6mHdiDENKn0rb8C1Lir7n"},
            {"West Bengal", "Barasat", "https://chat.whatsapp.com/B9dqS5DqtFG4XxRFXTxkvn"},
            {"West Bengal", "Bardhaman Durgapur", "https://chat.whatsapp.com/IjA4kZrsw3KIHDXPGvH7Ml"},
            {"West Bengal", "Bardhaman Purba", "https://chat.whatsapp.com/HMMwc86sE8IAPrtCL0asoQ"},
            {"West Bengal", "Barrackpur", "https://chat.whatsapp.com/CYtJCDOL44v6pckqFm3SFU"},
            {"West Bengal", "Basirhat", "https://chat.whatsapp.com/JcVwcQnKmgECFOiW7W7rTG"},
            {"West Bengal", "Birbhum", "https://chat.whatsapp.com/Bdo3IEaF49a3ttn28aFCnA"},
            {"West Bengal", "Bishnupur", "https://chat.whatsapp.com/G2EuDWxAGfaKCNNwzlbR1I"},
            {"West Bengal", "Bolpur", "https://chat.whatsapp.com/CCoBqdXB82sGpeqGTED4xp"},
            {"West Bengal", "Cooch behar", "https://chat.whatsapp.com/E22dKDq7xJTGkOyarhvdqF"},
            {"West Bengal", "Darjeeling", "https://chat.whatsapp.com/Gjy594mdGc5BKj5Gaqe2CE"},
            {"West Bengal", "Diamond Harbour", "https://chat.whatsapp.com/Kig078NliEL8mNEICe38rA"},
            {"West Bengal", "Dum Dum", "https://chat.whatsapp.com/CuEdiiTt5IQI3cmEMl50Jm"},
            {"West Bengal", "Ghatal", "https://chat.whatsapp.com/IonO9uLf2zq6Xror7kIQUC"},
            {"West Bengal", "Hooghly", "https://chat.whatsapp.com/LEs32paWBZWCqkoc8gYQJ6"},
            {"West Bengal", "Howrah", "https://chat.whatsapp.com/DIABMyR0gAk8pvWK2rqOwD"},
            {"West Bengal", "Jadavpur", "https://chat.whatsapp.com/ByidAvqqhIFAq0LDnJPEr3"},
            {"West Bengal", "Jalpaiguri", "https://chat.whatsapp.com/BfLMghltR1U77RTY8V2YqY"},
            {"West Bengal", "Jangipur", "https://chat.whatsapp.com/FbALeWqSnm2EJAvGdbRksR"},
            {"West Bengal", "Jaynagar", "https://chat.whatsapp.com/DMIbXDJjWEWEf8swwTBl6Y"},
            {"West Bengal", "Jhargram", "https://chat.whatsapp.com/IDeZ8QvecSi6dW0lhUKoYy"},
            {"West Bengal", "Kanthi", "https://chat.whatsapp.com/FxSwdk090EhCNpUxSCdx44"},
            {"West Bengal", "Kolkata Dakshin", "https://chat.whatsapp.com/HkV5cs9pb9qDujW7OihaSF"},
            {"West Bengal", "Kolkata Uttar", "https://chat.whatsapp.com/K4bOzg2KWBAA9TfJHI1ma2"},
            {"West Bengal", "Krishnanagar", "https://chat.whatsapp.com/LvLhoXvsgbc5mW1gPnrfXm"},
            {"West Bengal", "Maldaha Dakshin", "https://chat.whatsapp.com/HfZcMze06AlHWLTvWiSLm6"},
            {"West Bengal", "Maldaha Uttar", "https://chat.whatsapp.com/EURZqFEpgPgIgpWt7L4H7L"},
            {"West Bengal", "Mathurapur", "https://chat.whatsapp.com/Lm6pyekmf7Y5W9ffLH3Na1"},
            {"West Bengal", "Medinipur", "https://chat.whatsapp.com/F6vQORUbvR292dB7tT46SQ"},
            {"West Bengal", "Murshidabad", "https://chat.whatsapp.com/HhYlj5LyjjrIlVE6qAngof"},
            {"West Bengal", "Purulia", "https://chat.whatsapp.com/I7k0u9UPhP9H6oUtDtvBOI"},
            {"West Bengal", "Raiganj", "https://chat.whatsapp.com/IBoVBIbwGId7A37flF1iLj"},
            {"West Bengal", "Ranaghat", "https://chat.whatsapp.com/BssinVmEsBxEFgUud3kEnU"},
            {"West Bengal", "Sreerampur", "https://chat.whatsapp.com/GK6zQRnz7yVEFwcYRYOfYC"},
            {"West Bengal", "Tamluk", "https://chat.whatsapp.com/JcyydQm5PuEHnbGT52U1r1"},
            {"West Bengal", "Uluberia", "https://chat.whatsapp.com/IiVt5TLBzCl10rOTKJFvJm"},
    };

}