/* Auto-generated file from db2MPjava.php*/

package in.filternet.jantamalik.Kendra;

public final class MPdata {

	public static final String[][] all_MPs = {

		{"Andaman & Nicobar Islands", "Andaman and Nicobar Islands", "Kuldeep Rai Sharma", "अण्डमान और निकोबार द्वीपसमूह", "अंडमान व नोकोबार द्वीप समूह", "कुलदीप राय शर्मा",  "9434266877",  "9932086877", "", "antccani@gmail.com", "", "MB 167, MG Road, Junglighat, Port Blair-744103"}, 
		{"Andhra Pradesh", "Amalapuram", "Chinta Anuradha", "आन्ध्र प्रदेश", "अमलापुरम", "चिन्ता अनुराधा",  "8333999234",  "", "", "anuradhachintaysr@gmail.com", "", " D.NO. 1-99, Mogallamuru village, Allavaram Mandal , East Godavari District, Andhra Pradesh"}, 
		{"Andhra Pradesh", "Anakapalle", "Dr.Beesetti Venkata Satyavathi", "आन्ध्र प्रदेश", "अनकापल्ली", "डॉ. बिसेती वेंकट सत्यवती",  "9866837150",  "", "", "venkatasatyavathikandregula@gmail.com", "", "12-4-15/2, SRI VIVEKANANDA NAGAR COLONY, OPP RTC COMPLEX, WARD 30 ANAKAPALLE, VISAKHAPATNAM-531001"}, 
		{"Andhra Pradesh", "Anantapur", "Talari Rangaiah", "आन्ध्र प्रदेश", "अनंतपुर", "तलारी रंगिया",  "9849254712",  "", "", "rangaiah2013@gmail.com", "", "D.NO. 2-32, S.V HOMES,OPP. JNTU Engeering college, ANANTAPUR, ANANTAPUR DISTRICK"}, 
		{"Andhra Pradesh", "Araku", "Goddeti Madhavi", "आन्ध्र प्रदेश", "अरकू", "गोद्देती माधवी",  "9494670368",  "", "", "madhuniha22@gmail.com", "", "R/O Sarabhanna Palem (Post. & Village), Koyyuru Mandal, Visakhapatnam District, A.P. 531084"}, 
		{"Andhra Pradesh", "Bapatla", "Suresh Babu Nandigam", "आन्ध्र प्रदेश", "बापतला", "सुरेश बाबू नंदीग्राम",  "9866562526",  "9705227799", "", "sureshnandigam940@gmail.com", "", "Door No. 2-6B Uddandarayunipalem Village"}, 
		{"Andhra Pradesh", "Chittoor", "N. Reddeppa", "आन्ध्र प्रदेश", "चित्तूर", "एन. रेड्डीप्पा",  "9866224333",  "8099924333", "", "reddeppanallakondagari@gmail.com", "", "Door No. 31-90/16-3, kothaindlu, Punganur Town and Mandal, Chittoor, Dist, AP"}, 
		{"Andhra Pradesh", "Eluru", "Sridhar Kotagiri", "आन्ध्र प्रदेश", "एलुरु", "श्रीधर कोटागिरी",  "9849133338",  "", "", "skotagiri@yahoo.com", "", "H.No.1-57/3,East Edavalli (v),Kamavarapu Kota (M),W.G.DT,Pin Code :534426"}, 
		{"Andhra Pradesh", "Guntur", "Jayadev Galla", "आन्ध्र प्रदेश", "गुंटूर", "जयदेव गल्ला",  "9704697788",  "", "", "jaygalla@gmail.com", "", "3-1-93/4, 6th Lane, Brindavan Gardens, Guntur- 522006"}, 
		{"Andhra Pradesh", "Hindupur", "Kuruva Gorantla Madhav", "आन्ध्र प्रदेश", "हिन्दुपुर", "कुरुवा गोरान्तला माधव",  "9441611777",  "", "", "gorantlamadhav.gm@gmail.com", "", "P.NO.2389,PrabhakarStreet Anantapuramu,Ananatpur Dist."}, 
		{"Andhra Pradesh", "Kadapa", "Yeduguri Sandinti Avinash Reddy", "आन्ध्र प्रदेश", "कडपा", "यदुगुड़ी संदींति अविनाश रेड्डी",  "9989067352",  "", "", "ys.avinash@gmail.com", "", "D.NO. 3-9-76, PULIVENDULA POLYMERS, NEAR VENKATAPPA SCHOOL MAIN BRANCH, BHAKARAPUAM, PULIVENDULA, Y.S.R. KADAPA DIST.-516390"}, 
		{"Andhra Pradesh", "Kakinada", "Vanga Geetha Viswanatham", "आन्ध्र प्रदेश", "काकीनाडा", "वंगा गीता विश्वनाथम्",  "9848018525",  "9848367667", "", "vangageethal.shakthipeetama@gmail.com", "", "D.No.70-7-2/5, Priyanka Residency, NFCL Road, Kakinada, E.G.District, A.P"}, 
		{"Andhra Pradesh", "Kurnool", "Dr Sanjeev Kumar", "आन्ध्र प्रदेश", "कुरनूल", "डॉ संजीव कुमार",  "",  "", "", "", "", ""}, 
		{"Andhra Pradesh", "Machilipatnam", "Balashowry Vallabhaneni", "आन्ध्र प्रदेश", "मछलीपट्टनम", "बालाशोवरी वल्लभानेनी",  "",  "", "", "", "", ""}, 
		{"Andhra Pradesh", "Nandyal", "Pocha Brahmananda Reddy", "आन्ध्र प्रदेश", "नांदयाल", "पोचा ब्रह्मानंद रेड्डी",  "",  "", "", "", "", ""}, 
		{"Andhra Pradesh", "Narasaraopet", "Lavu Sri Krishna Devarayalu", "आन्ध्र प्रदेश", "नरसरोपेट", "लावु श्री कृष्ण देवरयालु",  "",  "", "", "", "", ""}, 
		{"Andhra Pradesh", "Narsapuram", "Kanumuru Raghu Rama Krishna Raju", "आन्ध्र प्रदेश", "नरसापुरम", "कानमुरु रघु राम कृष्ण राजू",  "",  "", "", "", "", ""}, 
		{"Andhra Pradesh", "Nellore", "Adala Prabhakara Reddy", "आन्ध्र प्रदेश", "नेल्लोर", "अदला प्रभाकर रेड्डी",  "",  "", "", "", "", ""}, 
		{"Andhra Pradesh", "Ongole", "Magunta Sreenivasulu Reddy", "आन्ध्र प्रदेश", "ओंगोल", "मगुंटा श्रीनिवासुलु रेड्डी",  "",  "", "", "", "", ""}, 
		{"Andhra Pradesh", "Rajahmundry", "Margani Bharat Ram", "आन्ध्र प्रदेश", "राजमुंदरी", "मरगनी भरत राम",  "",  "", "", "", "", ""}, 
		{"Andhra Pradesh", "Rajampet", "P.V.Midhun Reddy", "आन्ध्र प्रदेश", "राजमपेट", "पीवीमधुन रेड्डी",  "",  "", "", "", "", ""}, 
		{"Andhra Pradesh", "Srikakulam", "Rammohannaidu Kinjarapu", "आन्ध्र प्रदेश", "श्रीकाकुलम", "राममोहननिदु किंजरापु",  "",  "", "", "", "", ""}, 
		{"Andhra Pradesh", "Tirupati", "Balli Durgaprasad Rao", "आन्ध्र प्रदेश", "तिरुपति", "बल्ली दुर्गाप्रसाद राव",  "",  "", "", "", "", ""}, 
		{"Andhra Pradesh", "Vijayawada", "Srinivas Kesineni", "आन्ध्र प्रदेश", "विजयवाड़ा", "श्रीनिवास केसिनेनी",  "",  "", "", "", "", ""}, 
		{"Andhra Pradesh", "Visakhapatnam", "M V V Satyanarayana", "आन्ध्र प्रदेश", "विशाखापत्तनम", "एमवीवी सत्यनारायण",  "",  "", "", "", "", ""}, 
		{"Andhra Pradesh", "Vizianagaram", "Bellana Chandra Sekhar", "आन्ध्र प्रदेश", "विजयनगरम", "बेलना चंद्र शेखर",  "",  "", "", "", "", ""}, 
		{"Arunachal Pradesh", "Arunachal East", "Tapir Gao", "अरुणाचल प्रदेश", "अरुणाचल पूर्व", "तपीर गाओ",  "9811210220",  "", "", "gaotapir@yahoo.com", "", "Ruksin, P.O. & P.S. Ruksin, District East Siang, Arunachal Pradesh-791102"}, 
		{"Arunachal Pradesh", "Arunachal West", "Kiren Rijiju", "अरुणाचल प्रदेश", "अरुणाचल पश्चिम", "किरन रिजीजू",  "8448800661",  "", "", "krijiju@gmail.com", "", "Nakhu, P.O. & P.S. Nafra, West Kameng, Arunachal Pradesh"}, 
		{"Assam", "Autonomous District", "Horen Sing Bey", "असम", "स्वायत्त जिला", "होरन सिंग बे",  "8471802688",  "", "", "horensingbay@gmail.com", "", "Village Rongkethe (Lorulangso),P.O. & P.S., Duphu in the District of Karbi Anglong Assam"}, 
		{"Assam", "Barpeta", "Abdul Khaleque", "असम", "बारपेटा", "अब्दुल खलीक",  "9435115864",  "7002433353", "", "makhaleque@yahoo.com", "", "Vill Bartari Po. Chandmama PS Kalgachia Dist Barpeta Assam"}, 
		{"Assam", "Dhubri", "Badruddin Ajmal", "असम", "धुबरी", "बदरुद्दीन अजमल",  "9435561156",  "9013180448", "", "amarhuzoor@gmail.com", "", "Village Donkigaon, PO. & PS. Hojal, Dist.-Hojal, Assam, 782435"}, 
		{"Assam", "Dibrugarh", "Rameswar Teli", "असम", "डिब्रूगढ़", "रामेश्वर तेली",  "9435039335",  "", "", "rameswartelimp@gmail.com", "", "Tipling Puranaghat, P.O- Jaloni Dibruduwar, P. S. Duliajan, District Dibrugarh, Assam, Pin-786602"}, 
		{"Assam", "Gauhati", "Queen Oja", "असम", "गुवाहाटी", "क्वीन ओजा",  "9435147152",  "", "", "queenoja01@gmail.com", "", "H NO 20, Jivagiri Path, Ashram Road, South Sarania, Behind Ulubari Post Office, P.S. Paltan Bazar, Guwahati-781007, District Kamrup (Metro), Assam"}, 
		{"Assam", "Jorhat", "Topon Kumar Gogoi", "असम", "जोरहाट", "टोपन कुमार गोगोई",  "9435012570",  "9365539105", "", "toponkumargogoi@gmail.com", "", "Bheseli Pather Gaon, P.O. Barasali - 785693"}, 
		{"Assam", "Kaliabor", "Gaurav Gogoi", "असम", "कलियाबोर", "गौरव गोगोई",  "9435706522",  "", "", "gaurav.gogoi@gmail.com", "", "Nazirali, P. O. - Jorhat, District - Jorahat, Assam"}, 
		{"Assam", "Karimganj", "Kripanath Mallah", "असम", "करीमगंज", "कृपानथ मल्लाह",  "9401326719",  "7086612015", "", "knmallah@gmail.com", "", "H. No 2-10-1525 (New 2-10-1145 (old),Jyothinagar,Kuarimnagar"}, 
		{"Assam", "Kokrajhar", "Naba Kumar Sarania", "असम", "कोकराझार", "नाबा कुमार सरानिया",  "",  "", "", "", "", ""}, 
		{"Assam", "Lakhimpur", "Pradan Baruah", "असम", "लखीमपुर", "प्रदन बरुआ",  "",  "", "", "", "", ""}, 
		{"Assam", "Mangaldoi", "Shri Dilip Saikia", "असम", "मंगलदोई", "श्री दिलीप सैकिया",  "",  "", "", "", "", ""}, 
		{"Assam", "Nawgong", "Pradyut Bordoloi", "असम", "नौगांव", "प्रद्युत बोरदोलोई",  "",  "", "", "", "", ""}, 
		{"Assam", "Silchar", "Rajdeep Roy", "असम", "सिलचर", "राजदीप रॉय",  "",  "", "", "", "", ""}, 
		{"Assam", "Tezpur", "Pallab Lochan Das", "असम", "तेजपुर", "पल्लब लोचन दास",  "",  "", "", "", "", ""}, 
		{"Bihar", "Araria", "Pradeep Kumar Singh", "बिहार", "अररिया", "प्रदीप कुमार सिंह",  "9013180185",  "", "", "peadeepsingh.india@gmail.com", "", "Om Nagar, Ward no 8, PO, PS & District Araia, Pin No 854311"}, 
		{"Bihar", "Arrah", "R. K. Singh", "बिहार", "आरा", "आर.के. सिंह",  "9661399999",  "7042799999", "7290079999", "rksingh.ias@gmail.com", "", "903, Mani Orkid, R.P.S. More Bailey Road, Patna 801503"}, 
		{"Bihar", "Aurangabad", "Sushil Kumar Singh", "बिहार", "औरंगाबाद बिहा", "सुशील कुमार सिंह",  "9013180095",  "", "", "sushilsingh.mp@gmail.com", "", "R/O 25 New Area,Aurangabad,Dist Aurangabad Bihar 824101"}, 
		{"Bihar", "Banka", "Giridhari Yadav", "बिहार", "बांका", "गिरधारी यादव",  "9471828916",  "9931555683", "", "giridhariyadavmp@gmail.com", "", "Village Dadva, Post -Simutla(Khrna) Thana Chaandan, Dist Banka Bihar"}, 
		{"Bihar", "Begusarai", "Giriraj Singh", "बिहार", "बेगूसराय", "गिरिराज सिंह",  "9431018799",  "", "", "girirajsinghbjp@gmail.com", "", "Village & PO-Barhiya, Barhiya, Dist-Lakhisarai"}, 
		{"Bihar", "Bhagalpur", "Ajay Kumar Mandal", "बिहार", "भागलपुर", "अजय कुमार मंडल",  "7631836540",  "", "", "", "", "R/O Village Goal Sadak PO- Ghodha Bazar PS Kahel Gaon Dist Bhagalpur 813205"}, 
		{"Bihar", "Buxar", "Ashwini Kumar Choubey", "बिहार", "बक्सर", "अश्विनी कुमार चौबे",  "943108770",  "", "", "ashwinikrchobey@gmail.com", "", "R/o T.N Singh Lane,Manik Sarkar,Aadampur, Bhagalpur"}, 
		{"Bihar", "Darbhanga", "Gopaljee Thakur", "बिहार", "दरभंगा", "गोपालजी ठाकुर",  "9473199995",  "9905267319", "", "gopaljeethkur.dbg@gmail.com", "", "R/O Vill+Po-Padri,PS-Biraul,Dist Darbhanga"}, 
		{"Bihar", "Gaya", "Vijay Kumar", "बिहार", "गया", "विजय कुमार",  "9473270601",  "", "", "vijaykr19elec@gmail.com", "", "Village Bara, PS & PO Barachatti, District Gaya"}, 
		{"Bihar", "Gopalganj", "Dr. Alok Kumar Suman", "बिहार", "गोपालगंज", "डॉ. आलोक कुमार सुमन",  "9431217530",  "", "", "draksumangopalganj@gmail.com", "", "Village-Turkahan, P.O.Gopalganj, H.O.-Gopalganj-841428, Bihar"}, 
		{"Bihar", "Hajipur", "Pashupati Kumar Paras", "बिहार", "हाजीपुर", "पशुपति कुमार पारस",  "9431025999",  "", "", "pashupatikumarparas99@gmail.com", "", "Village Mantri Jee Tola, VillagPO Shaharbanni, PS Alouli, District Khagaria, Bihar"}, 
		{"Bihar", "Jahanabad", "Chandeshwar Prasad", "बिहार", "जहानाबाद", "चंदेश्वर प्रसाद",  "9431020780",  "", "", "cprasad1951@gmail.com", "", "Ro- B-118 Kankarbagh, Housing Colony P.O Lohianagar S.O Town Vill Patna Aachal Patna Sadar Dist. Patna -800020"}, 
		{"Bihar", "Jamui", "Chirag Kumar Paswan", "बिहार", "जमुई", "चिराग कुमार पासवान",  "9013869899",  "", "", "office.chiragpaswan@gmail.com", "", "Mantri Ji Tola Vill, P.O. Sherbanni,P.S.& Block--Alauli Dist.-Khagadiya ,Bihar"}, 
		{"Bihar", "Jhanjharpur", "Ramprit Mandal", "बिहार", "झंझारपुर", "रामप्रीत मंडल",  "9939992757",  "", "", "", "", "R/o Village Durgipatti PO-Hudra Maya+PS-Khutona Dist Madhuvani"}, 
		{"Bihar", "Karakat", "Mahabali Singh", "बिहार", "काराकाट", "महाबली सिंह",  "9431023711",  "", "", "singhmahabali@gmail.com", "", "R/O- Gram-Khiri, Post+Thana- Bhagwanpur, Dist Kaimur Bhabua"}, 
		{"Bihar", "Katihar", "Dulal Chandra Goswami", "बिहार", "कटिहार", "दुलाल चंद्र गोस्वामी",  "",  "", "", "", "", ""}, 
		{"Bihar", "Khagaria", "Choudhary Mahbub Ali Kaisar", "बिहार", "खगरिया", "चौधरी महबूब अली कैसर",  "",  "", "", "", "", ""}, 
		{"Bihar", "Kishanganj", "Dr. Mohammad Jawed", "बिहार", "किशनगंज", "डॉ। मोहम्मद जावेद",  "",  "", "", "", "", ""}, 
		{"Bihar", "Madhepura", "Dinesh Chandra Yadav", "बिहार", "मधेपुरा", "दिनेश चंद्र यादव",  "",  "", "", "", "", ""}, 
		{"Bihar", "Madhubani", "Ashok Kumar Yadav", "बिहार", "मधुबनी", "अशोक कुमार यादव",  "",  "", "", "", "", ""}, 
		{"Bihar", "Maharajganj", "Janardan Singh Sigriwal", "बिहार", "महाराजगंज", "जनार्दन सिंह सिग्रीवाल",  "",  "", "", "", "", ""}, 
		{"Bihar", "Munger", "Rajiv Ranjan Singh", "बिहार", "मुंगेर", "राजीव रंजन सिंह",  "",  "", "", "", "", ""}, 
		{"Bihar", "Muzaffarpur", "Ajay Nishad", "बिहार", "मुजफ्फरपुर", "अजय निषाद",  "",  "", "", "", "", ""}, 
		{"Bihar", "Nalanda", "Kaushlendra Kumar", "बिहार", "नालंदा", "कौशलेंद्र कुमार",  "",  "", "", "", "", ""}, 
		{"Bihar", "Nawada", "Chandan Singh", "बिहार", "नवादा", "चंदन सिंह",  "",  "", "", "", "", ""}, 
		{"Bihar", "Paschim Champaran", "Dr. Sanjay Jaiswal", "बिहार", "पश्चिम चंपारण", "डॉ। संजय जायसवाल",  "",  "", "", "", "", ""}, 
		{"Bihar", "Pataliputra", "Ram Kripal Yadav", "बिहार", "पाटलिपुत्र", "राम कृपाल यादव",  "",  "", "", "", "", ""}, 
		{"Bihar", "Patna Sahib", "Ravi Shankar Prasad", "बिहार", "पटना साहिब", "रविशंकर प्रसाद",  "",  "", "", "", "", ""}, 
		{"Bihar", "Purnia", "Santosh Kumar", "बिहार", "पूर्णिया", "संतोष कुमार",  "",  "", "", "", "", ""}, 
		{"Bihar", "Purvi Champaran", "Radha Mohan Singh", "बिहार", "पूर्वी चंपारण", "राधा मोहन सिंह",  "",  "", "", "", "", ""}, 
		{"Bihar", "Samastipur", "Ramchandra Paswan", "बिहार", "समस्तीपुर", "रामचंद्र पासवान",  "",  "", "", "", "", ""}, 
		{"Bihar", "Saran", "Rajiv Pratap Rudy", "बिहार", "सरन", "राजीव प्रताप रूडी",  "",  "", "", "", "", ""}, 
		{"Bihar", "Sheohar", "Rama Devi", "बिहार", "शिवहर", "रमा देवी",  "",  "", "", "", "", ""}, 
		{"Bihar", "Sitamarhi", "Sunil Kumar", "बिहार", "सीतामढ़ी", "सुनील कुमार",  "",  "", "", "", "", ""}, 
		{"Bihar", "Siwan", "Kavita Singh", "बिहार", "सिवान", "कविता सिंह",  "",  "", "", "", "", ""}, 
		{"Bihar", "Supaul", "Dileshwar Kamait", "बिहार", "सुपौल", "दिलेश्वर कामायत",  "",  "", "", "", "", ""}, 
		{"Bihar", "Ujiarpur", "Nityanand Rai", "बिहार", "उजियारपुर", "नित्यानंद राय",  "",  "", "", "", "", ""}, 
		{"Bihar", "Vaishali", "Veena Devi", "बिहार", "वैशाली", "वीणा देवी",  "",  "", "", "", "", ""}, 
		{"Bihar", "Valmiki Nagar", "Baidyanath Prasad Mahto", "बिहार", "वाल्मीकि नगर", "बैद्यनाथ प्रसाद महतो",  "",  "", "", "", "", ""}, 
		{"Chandigarh", "Chandigarh", "Kirron Kher", "चण्डीगढ़", "चंडीगढ़", "किरन खेर",  "9820067678",  "", "", "kirronkher14@gmail.com", "", "H.No.23, Sector- 7-A, Chandigarh-160018"}, 
		{"Chhattisgarh", "Bastar", "Deepak Kumar Baij", "छत्तीसगढ़", "बस्तर", "दीपक कुमार बैज",  "8817277727",  "9406077448", "", "deepakbaij77727@gmail.com", "", "Vill. Gadiya, Post Gadiya, Tehsil Gadiya Lohandiguda, Distt. Bastar"}, 
		{"Chhattisgarh", "Bilaspur", "Arun Sao", "छत्तीसगढ़", "बिलासपुर", "अरुण साओ",  "9826484954",  "7000877022", "", "arunsaobjp@gmail.com", "", "R/O Dueplex-38, Bhawji Park Ring Road No-02 Bilaspur"}, 
		{"Chhattisgarh", "Durg", "Vijay Baghel", "छत्तीसगढ़", "दुर्ग", "विजय बघेल",  "8770360478",  "9981521150", "", "vijay.baghel1503@gmail.com", "", "Qtr. No. 7B, Road-38, Sec. 05, Bhilai Nagar, Teh. & Dist. Durg, Pin 490006"}, 
		{"Chhattisgarh", "Janjgir Champa", "Guharam Ajgalle", "छत्तीसगढ़", "जांजगीर", "गुहाराम अजगले",  "7771863377",  "", "", "aigalley1969@gmail.com", "", "Gram Po Khaira Chote Teh Sargarh Dist Raigarh 496450"}, 
		{"Chhattisgarh", "Kanker", "Mohan Mandavi", "छत्तीसगढ़", "कांकेर", "मोहन मंडावी",  "9425262179",  "", "", "mandaviml15@gmail.com", "", "House No.63/K, Village-Govindpur, post-Govindpur,Teh-Kanker,Dist-Bastar Kanker, Chattisgarh"}, 
		{"Chhattisgarh", "Korba", "Jyotsna Mahant", "छत्तीसगढ़", "कोरबा", "ज्योत्सना महंत",  "",  "", "", "", "", ""}, 
		{"Chhattisgarh", "Mahasamund", "Chunni Lal Sahu", "छत्तीसगढ़", "महासमुंद", "चुन्नी लाल साहू",  "",  "", "", "", "", ""}, 
		{"Chhattisgarh", "Raigarh", "Gomati", "छत्तीसगढ़", "रायगढ़", "गोमती",  "",  "", "", "", "", ""}, 
		{"Chhattisgarh", "Raipur", "Sunil Kumar Soni", "छत्तीसगढ़", "रायपुर", "सुनील कुमार सोनी",  "",  "", "", "", "", ""}, 
		{"Chhattisgarh", "Rajnandgaon", "Santosh Pandey", "छत्तीसगढ़", "राजनंदगांव", "संतोष पांडे",  "",  "", "", "", "", ""}, 
		{"Chhattisgarh", "Surguja", "Renuka Singh Saruta", "छत्तीसगढ़", "सरगुजा", "रेणुका सिंह सरुता",  "",  "", "", "", "", ""}, 
		{"Dadra & Nagar Haveli", "Dadra and Nagar Haveli", "Delkar Mohanbhai Sanjibhai", "दादरा और नगर हवेली", "दादरा और नगर हवेली", "डेलकर मोहनभाई संजीभाई",  "9624241111",  "", "", "mohandelkardnh@gmail.com", "", "Delkar House, Opposite Shri Vinoba Bhave Civil Hospital, Sanjibhai Delkar Marg, Silvassa, Dadra & Nagar Haveli"}, 
		{"Daman & Diu", "Daman and Diu", "Patel Lalubhai Babubhai", "दमन और दीव", "दमन और दीव", "पटेल लालुभाई बाबूभाई",  "9825122858",  "0260-2230789", "", "damanmp@rediffmail.com", "", "House No. 206-G, Sabri Kutir, Dungri Falia, Kachigam, Nani Daman, Dist - Daman"}, 
		{"Goa", "North Goa", "Shripad Yesso Naik", "गोवा", "उत्तरी गोवा", "श्रीपाद येसो नाइक",  "",  "", "", "", "", ""}, 
		{"Goa", "South Goa", "Cosme Francisco Caitano Sardinha", "गोवा", "दक्षिण गोवा", "कोस्मे फ्रांसिस्को कैइटानो सरडीन्हा",  "",  "", "", "", "", ""}, 
		{"Gujarat", "Ahmedabad East", "Patel Hasmukhbhai Somabhai", "गुजरात", "अहमदाबाद पूर्व", "पटेल हसमुखभाई सोमाभाई",  "9327426122",  "", "", "hasmukh_1160@yahoo.com", "", "32, Vishala Park Society,Ghodasar, Ahmedabad-380050"}, 
		{"Gujarat", "Ahmedabad West", "Dr. Solanki Kiritbhai", "गुजरात", "अहमदाबाद पश्चिम", "डॉ. सोलंकी किरीटभाई",  "9925004644",  "09013180144", "", "sansadkiritsolanki@gmail.com", "", "11 Chirag Bungalow, Kirtan Society Chanip Cross Roas 132 Ring Road Opp Ambedkar Foundation 382480"}, 
		{"Gujarat", "Amreli", "Kachhadiya Naranbhai Bhikhabhai", "गुजरात", "अमरेली", "कछदिया नारनभाई भीखाभाई",  "9925140545",  "", "", "mpamreli@gmail.com", "", "Khodiyar Krupa Kananini Wadi, Chakkargadh Road, Amreli 365601"}, 
		{"Gujarat", "Anand", "Miteshbhai Patel", "गुजरात", "आनंद", "मितेशभाई पटेल",  "9825024935",  "", "", "mitesh@toordal.com", "", "Milankunj Society Wasad Anand"}, 
		{"Gujarat", "Banaskantha", "Parbatbhai Patel", "गुजरात", "बनासकांठा", "परबतभाई पटेल",  "9978405319",  "02737222021", "", "mlatharad@gmail.com", "", "Mukkam-Bhachar,Post-Idhata,Taluka-Tharad,District-Banaskantha"}, 
		{"Gujarat", "Bardoli", "Parbhubhai Nagarbhai Vasava", "गुजरात", "बारडोली", "परभुभाई नगरभाई वसावा",  "9574076555",  "9013869134", "", "mpprabhuvasava@gmail.com", "", "Sathvav, Surat 394160"}, 
		{"Gujarat", "Bharuch", "Mansukhbhai Vasava", "गुजरात", "भरूच", "मनसुखभाई वसावा",  "9427110866",  "02640-224300", "", "mansukhbhaidhanjibhaivasava@gmail.com", "", "Rajendranagar So.Rajpipla Dist- Narmada"}, 
		{"Gujarat", "Bhavnagar", "Dr.Bharatiben Dhirubhai Shiyal", "गुजरात", "भावनगर", "डॉ.भारतीबेन धीरूभाई शियाल",  "9726530182",  "9013869126", "", "mpbhartishyal@gmail.com", "", "Mathavada Talaja Bhavnagar 116 Sumeru Township Dhodha Road Jakatnaka Ring Road Bhavnagar 364002"}, 
		{"Gujarat", "Chhota Udaipur", "Rathva Gitaben Vajesingbhai", "गुजरात", "छोटा उदयपुर", "रथ्वा गीताबेन वजेसिंगभाई",  "9427492618",  "", "", "", "", "Kvant, Chota Udaipur"}, 
		{"Gujarat", "Dahod", "Jasvantsinh Sumanbhai Bhabhor", "गुजरात", "दाहोद", "जसवंतसिंह सुमनभाई भाभोर",  "7575031099",  "", "", "ismpdhd@gmail.com", "", "Bariya Faliyu Singvad Dahod"}, 
		{"Gujarat", "Gandhinagar", "Amit Shah", "गुजरात", "गांधीनगर", "अमित शाह",  "7926881140",  "", "", "amitshah.bjp@gmail.com", "", "16, Sudip Society Riyal Crissant, Jalsa Party Plot, Sarkhej Gandhinagar Highway Thaltej 380059"}, 
		{"Gujarat", "Jamnagar", "Poonamben Hematbhai Maadam", "गुजरात", "जामनगर", "पूनमबेन हेमतभाई मादम",  "9925099881",  "", "", "poonammaadam@gmail.com", "hrmaadam_memorialtrust@yahoo.co.in", "Maadam Fali Navagam Ghed, Jamnagar"}, 
		{"Gujarat", "Junagadh", "Chudasama Rajeshbhai Naranbhai", "गुजरात", "जूनागढ़", "चुडासमा राजेशभाई नारनभाई",  "9879347999",  "", "", "rajnc@yahoo.com", "mp13junagadh@gmail.com", "Chorwal Shakti Garbi Chowk, Mukkam Chorwad,Taluka-Madiya, District-Junagad"}, 
		{"Gujarat", "Kachchh", "Chavda Vinod Lakhamshi", "गुजरात", "कच्छ", "चावड़ा विनोद लखमशी",  "9825105467",  "9825105467", "", "vinod5467@gmail.com", "", "9 Vishva Villa, Nishant Park, College Road Bhuj Kachch 370001"}, 
		{"Gujarat", "Kheda", "Chauhan Devusinh", "गुजरात", "खेड़ा", "चौहान देवूसिंह",  "",  "", "", "", "", ""}, 
		{"Gujarat", "Mahesana", "Shardaben Anilbhai Patel", "गुजरात", "महेसाणा", "शारदाबेन अनिलभाई पटेल",  "",  "", "", "", "", ""}, 
		{"Gujarat", "Navsari", "Patil Chandrakant", "गुजरात", "नवसारी", "पाटिल चंद्रकांत",  "",  "", "", "", "", ""}, 
		{"Gujarat", "Panchmahal", "Ratansinh Rathod", "गुजरात", "पंचमहल", "रतनसिंह राठौड़",  "",  "", "", "", "", ""}, 
		{"Gujarat", "Patan", "Dabhi Bharatsinhji Shankarji", "गुजरात", "पाटन", "डाभी भरतसिंहजी शंकरजी",  "",  "", "", "", "", ""}, 
		{"Gujarat", "Porbandar", "Rameshbhai Dhaduk", "गुजरात", "पोरबंदर", "रमेशभाई धाडुक",  "",  "", "", "", "", ""}, 
		{"Gujarat", "Rajkot", "Kundaria Mohanbhai", "गुजरात", "राजकोट", "कुंदरिया मोहनभाई",  "",  "", "", "", "", ""}, 
		{"Gujarat", "Sabarkantha", "Rathod Dipsinh Shankarsinh", "गुजरात", "साबरकांठा", "राठौड़ दिपसिंह शंकरसिंह",  "",  "", "", "", "", ""}, 
		{"Gujarat", "Surat", "Jardosh Darshnaben Vikrambhai", "गुजरात", "सूरत", "जरदोष दर्शनाबेन विक्रमभाई",  "",  "", "", "", "", ""}, 
		{"Gujarat", "Surendranagar", "Mahendrabhai Munjpara", "गुजरात", "सुरेंद्रनगर", "महेंद्रभाई मुंजपारा",  "",  "", "", "", "", ""}, 
		{"Gujarat", "Vadodara", "Ranjanben Bhatt", "गुजरात", "वडोदरा", "रंजनबेन भट्ट",  "",  "", "", "", "", ""}, 
		{"Gujarat", "Valsad", "Dr.K.C.Patel", "गुजरात", "वलसाड", "Dr.KCPatel",  "",  "", "", "", "", ""}, 
		{"Haryana", "Ambala", "Rattan Lal Kataria", "हरियाणा", "अंबाला", "रतन लाल कटारिया",  "9416499855",  "0172-2555352", "", "rattanlalkatraria.bjp@gmail.com", "", "H. No. 352, Mansa Devi Complex, Sector 4, Panchkula"}, 
		{"Haryana", "Bhiwani Mahendragarh", "Dharambir Singh", "हरियाणा", "भिवानी-महेंद्रगढ़", "धर्मबीर सिंह",  "9013869145",  "01664-244568", "", "office.dharambir@gmail.com", "", "R/ O House No-200-B, Ward NO- 5 Vidya Nagar Hanuman Mandir Meham Road, Bhiwani"}, 
		{"Haryana", "Faridabad", "Krishan Pal", "हरियाणा", "फरीदाबाद", "कृष्ण पाल",  "9811074480",  "", "", "krishanpal.gurjar@bjp.org", "", "H. No. 1302, Sector- 28, Faridabad Dist Faridabad Haryana- 121008"}, 
		{"Haryana", "Gurgaon", "Rao Inderjit Singh", "हरियाणा", "गुडगाँव", "राव इंद्रजीत सिंह",  "9871100010",  "", "", "mpgurgaon@gmail.com", "", "Village and Post Office Rampura, Dist- Rewari (Haryana)"}, 
		{"Haryana", "Hisar", "Brijendra Singh", "हरियाणा", "हिसार", "बृजेन्द्र सिंह",  "8968844667",  "", "", "vennysingh@hotmail.com", "", "village & Post office Dumarkha Kalan,District Jind, Haryana"}, 
		{"Haryana", "Karnal", "Sanjay Bhatia", "हरियाणा", "करनाल", "संजय भाटिया",  "",  "", "", "", "", ""}, 
		{"Haryana", "Kurukshetra", "Nayab Singh", "हरियाणा", "कुरुक्षेत्र", "नायब सिंह",  "",  "", "", "", "", ""}, 
		{"Haryana", "Rohtak", "Arvind Kumar Sharma", "हरियाणा", "रोहतक", "अरविंद कुमार शर्मा",  "",  "", "", "", "", ""}, 
		{"Haryana", "Sirsa", "Sunita Duggal", "हरियाणा", "सिरसा", "सुनीता दुग्गल",  "",  "", "", "", "", ""}, 
		{"Haryana", "Sonipat", "Ramesh Chander Kaushik", "हरियाणा", "सोनीपत", "रमेश चंदर कौशिक",  "",  "", "", "", "", ""}, 
		{"Himachal Pradesh", "Hamirpur", "Anurag Singh Thakur", "हिमाचल प्रदेश", "हमीरपुर हिप्र", "अनुराग सिंह ठाकुर",  "9418000981",  "9876061484", "", "mphamirpur@gmail.com", "", "Village and post office Samirpur, Tehsil Bamsan at Tauni Devi, Dist. Hamirpur H.P."}, 
		{"Himachal Pradesh", "Kangra", "Kishan Kapoor", "हिमाचल प्रदेश", "कांगड़ा", "किशन कपूर",  "9816650007",  "01892228067", "", "shashwatkapoor@yahoo.co.in", "", "Village And PO- Khanyara Teh Dharamshala, Dist Kangra, HP-176218"}, 
		{"Himachal Pradesh", "Mandi", "Ram Swaroop Sharma", "हिमाचल प्रदेश", "मंडी", "राम स्वरूप शर्मा",  "",  "", "", "", "", ""}, 
		{"Himachal Pradesh", "Shimla", "Suresh Kumar Kashyap", "हिमाचल प्रदेश", "शिमला", "सुरेश कुमार कश्यप",  "",  "", "", "", "", ""}, 
		{"Jammu & Kashmir", "Anantnag", "Hasnain Masoodi", "जम्मू और कश्मीर", "अनंतनाग", "हसनैन मसूदी",  "9469337786",  "9797807860", "", "hasmas786@gmail.com", "", "Khrew, P.O Khrew -191103 Tehsil Pampore"}, 
		{"Jammu & Kashmir", "Baramulla", "Mohammad Akbar Lone", "जम्मू और कश्मीर", "बारामूला", "मोहम्मद अकबर लोन",  "9419000812",  "", "", "", "", "R/O Naid Khai Sonawari District Bandipora, Post Office Naid Khai Sonawari"}, 
		{"Jammu & Kashmir", "Jammu", "Jugal Kishore", "जम्मू और कश्मीर", "जम्मू", "जुगल किशोर",  "9419180151",  "", "", "jugal.bjp@gmail.com", "", "Village & Post Kishanpur Kharta, Tehsil Dansal & District Jammu 181224"}, 
		{"Jammu & Kashmir", "Ladakh", "Tsering Namgyal", "जम्मू और कश्मीर", "लद्दाख", "नमस्कारशील को नमस्कार",  "",  "", "", "", "", ""}, 
		{"Jammu & Kashmir", "Srinagar", "Farooq Abdullah", "जम्मू और कश्मीर", "श्रीनगर", "फारूक अब्दुल्ला",  "",  "", "", "", "", ""}, 
		{"Jammu & Kashmir", "Udhampur", "Dr. Jitendra Singh", "जम्मू और कश्मीर", "उधमपुर", "डॉ। जितेंद्र सिंह",  "",  "", "", "", "", ""}, 
		{"Jharkhand", "Chatra", "Sunil Kumar Singh", "झारखण्ड", "चतरा", "सुनील कुमार सिंह",  "9013869161",  "", "", "sunilkr.singh@sansad.nic.in", "", "R/O 133/C/1, Road NO-4 Ashok Nagar PO Ashok Nagar Doranda, PS Argora Dist. Ranchi-834002"}, 
		{"Jharkhand", "Dhanbad", "Pashupati Nath Singh", "झारखण्ड", "धनबाद", "पशुपति नाथ सिंह",  "9431115697",  "9013180201", "", "pashupatinathsingh77@gmail.com", "", "ANUGRAH NAGAR, PO+THANA- DHANSAR, DISTRICT-DHANBAD, JHARKHAND, PIN CODE-828106"}, 
		{"Jharkhand", "Dumka", "Sunil Soren", "झारखण्ड", "दुमका", "सुनील सोरेन",  "9955358778",  "9113786873", "", "", "", "Village Tarbandha, Post Lilatari, Thana Jama Dist. Dumka"}, 
		{"Jharkhand", "Giridih", "Chandra Prakash Choudhary", "झारखण्ड", "गिरिडीह", "चंद्र प्रकाश चौधरी",  "9572863363",  "", "", "cpcajsuparty@gmail.com", "", "R/O Village Sandi,Po-Sandi,Block Chitarpur,Dist Ramgarh"}, 
		{"Jharkhand", "Godda", "Nishikant Dubey", "झारखण्ड", "गोड्डा", "निशिकांत दुबे",  "9811147037",  "9873306633", "", "nishikant.dubey.mp@gmail.com", "", "House No. 101, Ankur Apartment, Bhagalpur, Dr. Rajendra Prasad Road 812002"}, 
		{"Jharkhand", "Hazaribagh", "Jayant Sinha", "झारखण्ड", "हजारीबाग", "जयंत सिन्हा",  "09811716444",  "", "", "jsinhe@gmail.com", "", "76A, Village Hupad, Post Harad, PS-Muffasil Hazaribagh"}, 
		{"Jharkhand", "Jamshedpur", "Bidyut Baran Mahato", "झारखण्ड", "जमशेदपुर", "बिद्युत बरन महतो",  "9470386555",  "8809422696", "", "mpbidyutmahato@gmail.com", "", "R/O Village Krishnapur PO-Industrial Area Adityapur PS-R.I.T (Adityapur ) Dist Seraikela Kharsawan JH 832109"}, 
		{"Jharkhand", "Khunti", "Arjun Munda", "झारखण्ड", "खूंटी", "अर्जुन मुंडा",  "",  "", "", "", "", ""}, 
		{"Jharkhand", "Kodarma", "Annapurna Devi", "झारखण्ड", "कोडरमा", "अन्नपूर्णा देवी",  "",  "", "", "", "", ""}, 
		{"Jharkhand", "Lohardaga", "Sudarshan Bhagat", "झारखण्ड", "लोहरदगा", "सुदर्शन भगत",  "",  "", "", "", "", ""}, 
		{"Jharkhand", "Palamu", "Vishnu Dayal Ram", "झारखण्ड", "पलामू", "विष्णु दयाल राम",  "",  "", "", "", "", ""}, 
		{"Jharkhand", "Rajmahal", "Vijay Kumar Hansdak", "झारखण्ड", "राजमहल", "विजय कुमार हंसदक",  "",  "", "", "", "", ""}, 
		{"Jharkhand", "Ranchi", "Sanjay Seth", "झारखण्ड", "रांची", "संजय सेठ",  "",  "", "", "", "", ""}, 
		{"Jharkhand", "Singhbhum", "Geeta Kora", "झारखण्ड", "सिंहभूम", "गीता कोरा",  "",  "", "", "", "", ""}, 
		{"Karnataka", "Bagalkot", "Gaddigoudar Parvatagouda Chandanagouda", "कर्नाटक", "बागलकोट", "गद्दीगौदर पार्वतगौड़ा चंदनगौड़ा",  "09868180612",  "08357220164", "", "pcgaddigoudar@rediffmail.com", "", "Bdhame Anugraha Gadhigodhara Nevasa LashamiNagara Badame-587201 Dist: Badhame Gialla: Bagalacota"}, 
		{"Karnataka", "Bangalore Central", "P. C. Mohan", "कर्नाटक", "बैंगलोर सेंट्रल", "पी.सी. मोहन",  "9845003600",  "", "", "contact@pcmohan.com", "", "No.1928, 30th Cross, Banshankarii II Stage, Bengaluru -560070"}, 
		{"Karnataka", "Bangalore North", "D.V. Sadananda Gowda", "कर्नाटक", "बैंगलोर उत्तर", "डी.वी. सदानंद गौड़ा",  "9448123249",  "", "", "sadanandagowda@yahoo.com", "", "#108 B, Ranga Nilaya, 5th Cross, 4th Main, MLA Layout, Bhoopasandra, Sanjayanagar, Bengaluru - 560094"}, 
		{"Karnataka", "Bangalore Rural", "D.K. Suresh", "कर्नाटक", "बैंगलोर ग्रामीण", "डी.के. सुरेश",  "09845029142",  "", "", "dksuresh18@gmail.com", "nimmadksureshmp2013@gmail.com", "Doddalahalli Village, Kanakapura Taluk, Ramanagara District, Karnataka-562126"}, 
		{"Karnataka", "Bangalore South", "Tejasvi Surya", "कर्नाटक", "बैंगलोर दक्षिण", "तेजस्वी सूर्या",  "08026724343",  "9916836964", "", "tejasvisurya@gmail.com", "", "No.3/80, 1st A Main Road, Girinagar 1st Phase, Bangalore-560085"}, 
		{"Karnataka", "Belgaum", "Angadi Suresh", "कर्नाटक", "बेलगाम", "अंगदी सुरेश",  "9448110813",  "", "", "suresh.angadimp@gmail.com", "", "Spoorti, Sampige Road, Vishweshwarayya Nagar, Belagavi-590019"}, 
		{"Karnataka", "Bellary", "Y. Devendrappa", "कर्नाटक", "बेल्लारी", "वाई. देवेंद्रप्पा",  "9448425272",  "", "", "ydevendrapp1@gmail.com", "", "#74, 1st Ward, Arasikere Post, Harapanahalli Taluk, Ballari District - 583125"}, 
		{"Karnataka", "Bidar", "Bhagwanth Khuba", "कर्नाटक", "बीदर", "भगवंत खुबा",  "09448115926",  "", "", "mpbidar@gmail.com", "", "Aurad(B) Dist.Bidar"}, 
		{"Karnataka", "Bijapur", "Jigajinagi Ramesh Chandappa", "कर्नाटक", "बीजापुर", "जिगजिनागी रमेश चंदप्पा",  "9449031477",  "", "", "jigajinagiramesh@gmail.com", "", "Bijapura nagar Arakeri Road, Buthanala garden House"}, 
		{"Karnataka", "Chamarajanagar", "V Srinivas Prasad", "कर्नाटक", "चामराजनगर", "वी श्रीनिवास प्रसाद",  "9448448150",  "0821-2511533", "", "srinivasaprasad1949@gmail.com", "", "R/O 91, Bhimasadana, 7th Main, Jayalakshmipuram, Mysore 570012"}, 
		{"Karnataka", "Chikkballapur", "B.N.Bache Gowda", "कर्नाटक", "चिकबल्लपुर", "बी.एन.बचे गौड़ा",  "",  "", "", "", "", "D.no 171 6th cross Tammegowda layout Hosakote 562114"}, 
		{"Karnataka", "Chikkodi", "Annasaheb Shankar Jolle", "कर्नाटक", "चिक्कोडी", "अन्नासाहेब शंकर जोले",  "9900559835 ",  "9900937524", "", "asj9835@gmail.com", "", "Residential of Examba, Taluk Chikodi, Dist Belagavi"}, 
		{"Karnataka", "Chitradurga", "A Narayanaswamy", "कर्नाटक", "चित्रदुर्ग", "ए नारायणस्वामी",  "9900845555",  "", "", "anarayanaswamyanekal5@gmail.com", "", "Munivenkatappa Layout, Chandapura Road, Anekal, Bangalore-562106"}, 
		{"Karnataka", "Dakshina Kannada", "Nalin Kumar Kateel", "कर्नाटक", "दक्षिण कन्नड़", "नलिन कुमार काटेल",  "9448549445",  "", "", "mpdkannada@gmail.com", "nalinkumar.kateel@sansad.nic.in", "15-24-2059/7,Flat No.201,Ashoka Apartment,near Daivajna Kalyana Mantap,Hogiebail Road,Ashok Nagar,Mangaluru-575 006 DK"}, 
		{"Karnataka", "Davanagere", "G M Siddeshwar", "कर्नाटक", "दावनगेरे", "जी एम सिद्धेश्वर",  "9448161799",  "", "", "siddeswaragm@gmail.com", "", "#1906/25, Mallikarjuna, Shabanur Banashankari Badavane, Davangere -577005"}, 
		{"Karnataka", "Dharwad", "Pralhad Joshi", "कर्नाटक", "धारवाड़", "प्रल्हाद जोशी",  "9448283555",  "0836-2211533", "", "prlahadvjoshi@gmail.com", "", "H.NO.122/D kamithartha mayuri estate keshwapur Hubli"}, 
		{"Karnataka", "Gulbarga", "Dr. Umesh G Jadhav", "कर्नाटक", "गुलबर्गा", "डॉ. उमेश जी जाधव",  "9242211591",  "", "", "ugjadhav@yahoo.com", "", "Plot No 132, H.No 1-1882 , N.G.O .Colony , Jewargi Road Gulbarga"}, 
		{"Karnataka", "Hassan", "Prajwal R", "कर्नाटक", "हसन", "प्रज्वल आर",  "9448364483",  "9611111330", "", "prajwal8055revanna@gmail.com", "", "No. 43, Paduvalahippe Village, Paduvalahippe Post, Kasaba Hobli, Holenarasipura Taluk, Hassan District-573211"}, 
		{"Karnataka", "Haveri", "Udasi. S.C.", "कर्नाटक", "हावेरी", "उदासी. एस.सी",  "08379262330",  "9844034575", "", "68southavenue@gmail.com", "", "Hangal Town (Gouli Galli) Tq Hangal Dist Haveri"}, 
		{"Karnataka", "Kolar", "S. Muniswamy", "कर्नाटक", "कोलार", "एस। मुनीस्वामी",  "",  "", "", "", "", ""}, 
		{"Karnataka", "Koppal", "Karadi Sanganna Amarappa", "कर्नाटक", "कोप्पल", "करदी संगना अमरप्पा",  "",  "", "", "", "", ""}, 
		{"Karnataka", "Mandya", "Sumalatha W/O Darshan K.", "कर्नाटक", "मंड्या", "सुमलता डब्ल्यू / ओ दर्शन के।",  "",  "", "", "", "", ""}, 
		{"Karnataka", "Mysore", "Prathap Simha", "कर्नाटक", "मैसूर", "प्रताप सिम्हा",  "",  "", "", "", "", ""}, 
		{"Karnataka", "Raichur", "Raja Amareshwara Naik", "कर्नाटक", "रायचूर", "राजा अमरेश्वर नाइक",  "",  "", "", "", "", ""}, 
		{"Karnataka", "Shimoga", "B.Y.Raghavendra", "कर्नाटक", "शिमोगा", "BYRaghavendra",  "",  "", "", "", "", ""}, 
		{"Karnataka", "Tumkur", "G S Basavaraj", "कर्नाटक", "तुमकुर", "जीएस बसवराज",  "",  "", "", "", "", ""}, 
		{"Karnataka", "Udupi Chikmagalur", "Shobha Karandlaje", "कर्नाटक", "उडुपी चिकमगलूर", "शोभा करंदलाजे",  "",  "", "", "", "", ""}, 
		{"Karnataka", "Uttara Kannada", "Anantkumar Hegde", "कर्नाटक", "उत्तर कन्नड़", "अनंतकुमार हेगड़े",  "",  "", "", "", "", ""}, 
		{"Kerala", "Alappuzha", "A M Ariff", "केरल", "अलाप्पुझा", "ए एम आरिफ",  "9447260665",  "", "", "ariffmla@gmail.com", "", "Arunyam,iruvakode,thiruvambadi P.o Alappuzha. pin code 688002"}, 
		{"Kerala", "Alathur", "Ramya P M", "केरल", "अलथुर", "राम्या पी एम",  "9388849748",  "", "", "ramyaharidasdt@gmail.com", "", "Palat meejnal house,Kuttikattur p.o kozhikode"}, 
		{"Kerala", "Attingal", "Adoor Prakash", "केरल", "अत्तिन्गल", "अदूर प्रकाश",  "9447008166",  "04734-224300", "", "adoorprakash9@gmail.com", "adoorprakashkonni@gmail.com", "Ramanilayam, Konnamankara(Muri), Addor Village, Adoor P.O. Pathanamthitta District Kerala-691523"}, 
		{"Kerala", "Chalakudy", "Benny Behanan", "केरल", "चलाकुडी", "बेनी बिहानन",  "9846184400",  "", "", "bbinc2019@gmail.com", "bennybehananinc@gmail.com", "Kunjuvettikudi House, Thrikkakara P.O. Ernakulam Kochi-682021"}, 
		{"Kerala", "Ernakulam", "Hibi Eden", "केरल", "एर्नाकुलम", "हीबी ईडन",  "04842400567",  "", "", "hibieden@gmail.com", "", "Ambattu House No.35/1319D (Old No.35/326B) George Eden Road Ernakulam Kochi-682017"}, 
		{"Kerala", "Idukki", "Dean Kuriakose", "केरल", "इडुक्की", "डीन कुरीकोज",  "9447877369",  "", "", "deankuriakoseksu@gmail.com", "", "Enanikkal House, paingattoor PO, kadavoor Village"}, 
		{"Kerala", "Kannur", "K Sudhakaran", "केरल", "कन्नूर", "के सुधाकरन",  "9446471300",  "", "", "knrsudhakaran@yahoo.co.in", "", "H.No.01/170, Lal Vihar, Parakandi, Kannur-670001"}, 
		{"Kerala", "Kasaragod", "Rajmohan Unnithan", "केरल", "कासरगोड", "राजमोहन उन्नीथन",  "",  "", "", "", "", ""}, 
		{"Kerala", "Kollam", "Premachandran N K", "केरल", "कोल्लम", "प्रेमचंद्रन एन.के.",  "",  "", "", "", "", ""}, 
		{"Kerala", "Kottayam", "Thomas Chazhikadan", "केरल", "कोट्टायम", "थॉमस चाझिकादान",  "",  "", "", "", "", ""}, 
		{"Kerala", "Kozhikode", "M.K.Raghavan", "केरल", "कोझिकोड", "MKRaghavan",  "",  "", "", "", "", ""}, 
		{"Kerala", "Malappuram", "Kunhalikutty", "केरल", "मलप्पुरम", "कुन्हलिकुट्टी",  "",  "", "", "", "", ""}, 
		{"Kerala", "Mavelikkara", "Kodikunnil Suresh", "केरल", "मवेलीकारा", "कोडिकुन्निल सुरेश",  "",  "", "", "", "", ""}, 
		{"Kerala", "Palakkad", "V K Sreekandan", "केरल", "पलक्कड़", "वीके श्रीकंदन",  "",  "", "", "", "", ""}, 
		{"Kerala", "Pathanamthitta", "Anto Antony", "केरल", "पथानामथिट्टा", "एंटो एंटनी",  "",  "", "", "", "", ""}, 
		{"Kerala", "Ponnani", "E T Mohammed Basheer", "केरल", "पोन्नानी", "ईटी मोहम्मद बशीर",  "",  "", "", "", "", ""}, 
		{"Kerala", "Thiruvananthapuram", "Shashi Tharoor", "केरल", "तिरुवनंतपुरम", "शशि थरूर",  "",  "", "", "", "", ""}, 
		{"Kerala", "Thrissur", "T. N. Prathapan", "केरल", "त्रिशूर", "टीएन प्रतापन",  "",  "", "", "", "", ""}, 
		{"Kerala", "Vadakara", "K. Muraleedharan", "केरल", "वाटकरा", "के मुरलीधरन",  "",  "", "", "", "", ""}, 
		{"Kerala", "Wayanad", "Rahul Gandhi", "केरल", "वायनाड", "राहुल गांधी",  "",  "", "", "", "", ""}, 
		{"Lakshadweep", "Lakshadweep", "Mohammed Faizal Pp", "लक्षद्वीप", "लक्षद्वीप", "मोहम्मद फैजल पीपी",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Balaghat", "Dr. Dhal Singh Bisen", "मध्य प्रदेश", "बालाघाट", "डॉ. ढाल सिंह बिसेन",  "09425019056",  "7000974469", "", "dr.dsbisen@gmail.com", "", "House No. 397 (New 1226), Near D.E.O. Office, CV Raman Rd, Ward, Barapathar, Seoni, Madhya Pradesh 480661"}, 
		{"Madhya Pradesh", "Betul", "Durga Das (D.D.) Uikey", "मध्य प्रदेश", "बेतुल", "दुर्गा दास (डी.डी.) उइके",  "9406959441",  "", "", "dduikey12@gmail.com", "", "Arjun Nagar, Ward No- 2, House No 324/1, Teh & Dist Betul"}, 
		{"Madhya Pradesh", "Bhind", "Sandhya Ray", "मध्य प्रदेश", "भिंड", "संध्या रे",  "9425126705",  "", "", "sandhyaray05@gmail.com", "", "208 Ward No-13, Murena Road Ambah, Tehsil Ambah, District Murena, M.P"}, 
		{"Madhya Pradesh", "Bhopal", "Sadhvi Pragya Singh Thakur", "मध्य प्रदेश", "भोपाल", "साध्वी प्रज्ञा सिंह ठाकुर",  "7898229896",  "", "", "sadhvipragyabjp@gmail.com", "", "126, Rivera Town Phase-2, Mata Mandir Bhopal, Teh-Huzur, Dist-Bhopal M.P"}, 
		{"Madhya Pradesh", "Chhindwara", "Nakul Nath", "मध्य प्रदेश", "छिंदवाड़ा", "नकुल नाथ",  "7162242233",  "", "", "official.nakulnath@gmail.com", "", "Village-Shikarpur Tehsil Mohkhed District Chhindiwara,Madhya Pradesh"}, 
		{"Madhya Pradesh", "Damoh", "Prahalad Singh Patel", "मध्य प्रदेश", "दमोह", "प्रहलाद सिंह पटेल",  "9425155511",  "9013869226", "", "prahaladspatel@gmail.com", "prahaladspatel@rediffmail.com", "F-23, Sainik Colony, Saheed Gulab Singh Ward ,Dist"}, 
		{"Madhya Pradesh", "Dewas", "Mahendra Singh Solanky", "मध्य प्रदेश", "देवास", "महेंद्र सिंह सोलंकी",  "8989900007",  "", "", "mahendrasinghsolanki379@gmail.com", "", "Old House No. 486, New 742, Mahesh Yadav Nagar, Banganga, Indore, M.P."}, 
		{"Madhya Pradesh", "Dhar", "Chhatar Singh Darbar", "मध्य प्रदेश", "धार", "छतर सिंह दरबार",  "9981717171",  "9425914575", "", "dhar_idea108@rediffmail.com", "", "Village Lunhera Sadak Tehasil Manavar, Dist Dhar Madhyapradesh 454446"}, 
		{"Madhya Pradesh", "Guna", "Krishna Pal Singh", "मध्य प्रदेश", "गुना", "कृष्ण पाल सिंह",  "9826507484",  "", "", "krishnapal600@gmail.com", "", "46/a, Ruslla, PO Singhada, Tehsil Mungawali Navin, Tehsil Piparai, Disrict Ashoknagar, MP"}, 
		{"Madhya Pradesh", "Gwalior", "Vivek Narayan Shejwalkar", "मध्य प्रदेश", "ग्वालियर", "विवेक नारायण शेजवलकर",  "9425116300",  "", "", "vivekshejwalkar@gmail.com", "", "Krishan Kripa, Vivkenand Marg, New Sadak Laskhar Gwalior-474001 MP"}, 
		{"Madhya Pradesh", "Hoshangabad", "Rao Uday Pratap Singh", "मध्य प्रदेश", "होशंगाबाद", "राव उदय प्रताप सिंह",  "07793-276822",  "", "", "udaypratap_narsingpur@yahoo.com", "", "P.O.Lolri(Rajmarg)Tehsil Tendukhera,Dist.Narsinghpur(M.P)"}, 
		{"Madhya Pradesh", "Indore", "Shankar Lalwani", "मध्य प्रदेश", "इंदौर", "शंकर लालवानी",  "9893033000",  "9425056000", "", "shankarlalwanibjp@gmail.com", "", "3 Sanket Manishpuri Extention Manishpuri Indore M.P"}, 
		{"Madhya Pradesh", "Jabalpur", "Rakesh Singh", "मध्य प्रदेश", "जबलपुर", "राकेश सिंह",  "9425150851",  "", "", "rakesh.singh@sansad.nic.in", "mpjbp@yahoo.com ", "578, South Civil Lines Jabalpur (MP)"}, 
		{"Madhya Pradesh", "Khajuraho", "Vishnu Datt Sharma", "मध्य प्रदेश", "खजुराहो", "विष्णु दत्त शर्मा",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Khandwa", "Nandkumar Singh Chouhan (Nandu Bhaiya)", "मध्य प्रदेश", "खंडवा", "नंदकुमार सिंह चौहान (नंदू भैया)",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Khargone", "Gajendra Umrao Singh Patel", "मध्य प्रदेश", "खरगोन", "गजेंद्र उमराव सिंह पटेल",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Mandla", "Faggan Singh Kulaste", "मध्य प्रदेश", "मंडला", "फग्गन सिंह कुलस्ते",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Mandsour", "Sudheer Gupta", "मध्य प्रदेश", "मंदसौर", "सुधीर गुप्ता",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Morena", "Narendra Singh Tomar", "मध्य प्रदेश", "मोरैना", "नरेंद्र सिंह तोमर",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Rajgarh", "Rodmal Nagar", "मध्य प्रदेश", "राजगढ़", "रोडमल नगर",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Ratlam", "Guman Singh Damor", "मध्य प्रदेश", "रतलाम", "गुमान सिंह डामोर",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Rewa", "Janardan Prasad Mishra", "मध्य प्रदेश", "रीवा", "जनार्दन प्रसाद मिश्र",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Sagar", "Rajbahadur Singh", "मध्य प्रदेश", "सागर", "राजबहादुर सिंह",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Satna", "Ganesh Singh", "मध्य प्रदेश", "सतना", "गणेश सिंह",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Shahdol", "Himadri Singh", "मध्य प्रदेश", "शाहडोल", "हिमाद्री सिंह",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Tikamgarh", "Virendra Kumar", "मध्य प्रदेश", "टीकमगढ़", "वीरेन्द्र कुमार",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Ujjain", "Anil Firojiya", "मध्य प्रदेश", "उज्जैन", "अनिल फिरोजिया",  "",  "", "", "", "", ""}, 
		{"Madhya Pradesh", "Vidisha", "Ramakant Bhargava", "मध्य प्रदेश", "विदिशा", "रमाकांत भार्गव",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Ahmednagar", "Sujay Radhakrishna Vikhe", "महाराष्ट्र", "अहमदनगर", "सुजय राधाकृष्ण विखे",  "9823212345",  "02422-273466", "", "sujay8998@gmail.com", "", "Vill-Loni Bu. Taluka Rahata, Dist Ahmednagar Pin No. 413736"}, 
		{"Maharashtra", "Akola", "Sanjay Shamrao Dhotre", "महाराष्ट्र", "अकोला", "संजय शामराव धोत्रे",  "07242452000",  "", "", "sanjaysdhotre@gmail.com", "", "Palso(Badhe),Tauka & Dist. Akola (Maharashtra)"}, 
		{"Maharashtra", "Amravati", "Navneet Ravi Rana", "महाराष्ट्र", "अमरावती", "नवनीत रवि राणा",  "9594503503",  "", "", "navneet.rana@rediffmail.com", "", "50, Ganga Savitri, Shankar Nagar, Rajapeth Amravati 444606"}, 
		{"Maharashtra", "Aurangabad", "Imtiaz Jaleel Syed", "महाराष्ट्र", "औरंगाबाद महा", "इम्तियाज जलील सैयद",  "9545522227",  "9823090040", "", "aurangabadmla@gmail.com", "", "Flat no.2 Mannat Park Lane N-12 Aurangabad"}, 
		{"Maharashtra", "Baramati", "Supriya Sadanand Sule", "महाराष्ट्र", "बारामती", "सुप्रिया सदानंद सुले",  "02112-256291",  "", "", "supriyassule@gmail.com", "", "Pawar Bangla, Aamrai, Mu Po: Baramati, Tal: Baramati, Dist: Pune 413102"}, 
		{"Maharashtra", "Beed", "Pritam Gopinathrao Munde", "महाराष्ट्र", "बीड", "प्रीतम गोपीनाथराव मुंडे",  "9664633333",  "", "", "drpritammunde@gmail.com", "", "Nathra, Kouthli, Vaijnath Beed"}, 
		{"Maharashtra", "Bhandara Gondiya", "Sunil Baburao Mendhe", "महाराष्ट्र", "भंडारा-गोंदिया जिला", "सुनील बाबूराव मेंढे",  "8888894134",  "", "", "sunilmendhe@gmail.com", "", "Kamal-Kunj, Madhav Nagar, Khat Road, Bhandara Th. Dist. Bhandara, Maharashtra Pin 441904"}, 
		{"Maharashtra", "Bhiwandi", "Kapil Moreshwar Patil", "महाराष्ट्र", "भिवंडी", "कपिल मोरेश्वर पाटिल",  "09820610040",  "", "", "kapilpatil.mp@gmail.com", "", "Moreshwar Bunglow,at Anjur Dive, Taluka-Bhiwandi,District-Thane"}, 
		{"Maharashtra", "Buldhana", "Prataprao Ganpatrao Jadhav", "महाराष्ट्र", "बुलढाना", "प्रतापराव गणपतराव जाधव",  "8888647777",  "", "", "jadhaoprataprao25@gmail.com", "", "Mavani, Aregaon, Mehkar, Buldhana"}, 
		{"Maharashtra", "Chandrapur", "Dhanorkar Suresh Narayan", "महाराष्ट्र", "चंद्रपुर", "धनोरकर सुरेश नारायण",  "9923232462",  "07176-280586", "", "balu.dhanorkar29@gmail.com", "", "Lakshmi nagar, Abhyankar Ward Varora, Chandrapur"}, 
		{"Maharashtra", "Dhule", "Subhash Ramrao Bhamre", "महाराष्ट्र", "धुले", "सुभाष रामराव भामरे",  "9823160760",  "", "", "drsubhashbhamre11@gmail.com", "", "16, Badgujar Plot Parola Road Dhule"}, 
		{"Maharashtra", "Dindori", "Bharti Pawar", "महाराष्ट्र", "डिंडोरी", "भारती पवार",  "9421507836",  "8552930718", "", "drbhartipawar@gmail.com", "", "Pawar Bunglow, Anand Nagar, Gangapur Road, Nashik"}, 
		{"Maharashtra", "Gadchiroli Chimur", "Ashok Mahadevrao Nete", "महाराष्ट्र", "गढ़चिरोली-चिमूर", "अशोक महादेवराव नेते",  "9420757999",  "9013869260", "", "ashoknetempgad@gmail.com", "", "Kannamvar ward no. 23, Chamorshi Road , Mouza, Po.,Teh. & Dist. Gadchiroli"}, 
		{"Maharashtra", "Hatkanangle", "Dhairyashil Sambhajirao Mane", "महाराष्ट्र", "हातकणंगले", "धरायाशिल संभाजीराव माने",  "9422044444",  "0230-2585733", "", "dhairyasheelmane@gmail.com", "", "347, Rukadi Tal-Hatkanangale Dist-kolhapur"}, 
		{"Maharashtra", "Hingoli", "Patil Hemant Shriram", "महाराष्ट्र", "हिंगोली", "पाटिल हेमंत श्रीराम",  "9422871426",  "7030990000", "", "patilhemant09@gmail.com", "", "Dilipsing Colony, Nanded Tukai House No. 1-10-623 Ravirajnagar Taroda Naka"}, 
		{"Maharashtra", "Jalgaon", "Unmesh Bhaiyyasaheb Patil", "महाराष्ट्र", "जलगांव", "उनमेश भैय्यासाहेब पाटिल",  "9423976388",  "", "", "unmeshbp@yahoo.com", "", "Mouza & Post. Daregaon Teh. Chalisgaon Dist. Jalgaon"}, 
		{"Maharashtra", "Jalna", "Danve Raosaheb Dadarao", "महाराष्ट्र", "जलना", "दानवे रावसाहेब दादराव",  "9868180280",  "9524314444", "", "raosahebdanve2019@gmail.com", "", "Shivaji Nagar Jalana Road Bhokardan Taluka Bhokardan Dist Jalna 431114"}, 
		{"Maharashtra", "Kalyan", "Dr. Shrikant Eknath Shinde", "महाराष्ट्र", "कल्याण", "डॉ. श्रीकांत एकनाथ शिंदे",  "9867112820",  "", "", "shrikantshinde87@yahoo.in", "", "Bunglow No.5,6, Landmark Society, Luiswadi, Thane (W).400604"}, 
		{"Maharashtra", "Kolhapur", "Sanjay Sadashivrao Mandlik", "महाराष्ट्र", "कोल्हापुर", "संजय सदाशिवराव मांडलिक",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Latur", "Sudhakar Tukaram Shrangare", "महाराष्ट्र", "लातूर", "सुधाकर तुकाराम श्रंगारे",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Madha", "Ranjeetsinha Hindurao Naik Nimbalkar", "महाराष्ट्र", "माढा", "रणजीतसिंह हिन्दुराव नाइक निंबालकर",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Maval", "Shrirang Chandu Barne", "महाराष्ट्र", "मावल", "श्रीरंग चंदू बरने",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Mumbai North", "Gopal Chinnaya Shetty", "महाराष्ट्र", "मुंबई उत्तर", "गोपाल चिन्नाया शेट्टी",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Mumbai North Central", "Poonam Vajendla Rao", "महाराष्ट्र", "मुंबई उत्तर मध्य", "पूनम वजेंदला राव",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Mumbai North East", "Manoj Kishorbhai Kotak", "महाराष्ट्र", "मुंबई उत्तर पूर्व", "मनोज किशोरभाई कोटक",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Mumbai North West", "Gajanan Chandrakant Kirtikar", "महाराष्ट्र", "मुंबई उत्तर पश्चिम", "गजानन चंद्रकांत कीर्तिकर",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Mumbai South", "Arvind Sawant", "महाराष्ट्र", "मुंबई दक्षिण", "अरविंद सावंत",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Mumbai South Central", "Rahul Ramesh Shewale", "महाराष्ट्र", "मुंबई दक्षिण मध्य", "राहुल रमेश शेवाले",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Nagpur", "Nitin Jairam Gadkari", "महाराष्ट्र", "नागपुर", "नितिन जयराम गडकरी",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Nanded", "Chikhalikar Pratap Govindrao", "महाराष्ट्र", "नांदेड़", "चिखलीकर प्रताप गोविंदराव",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Nandurbar", "Heena Vijaykumar Gavit", "महाराष्ट्र", "नंदुरबार", "हीना विजयकुमार गावित",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Nashik", "Hemant Tukaram Godse", "महाराष्ट्र", "नासिक", "हेमंत तुकाराम गोडसे",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Osmanabad", "Omprakash Bhupalsinh Alias Pavan Rajenimbalkar", "महाराष्ट्र", "उस्मानाबाद", "ओमप्रकाश भूपालसिंह उर्फ पवन राजनिंबालकर",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Palghar", "Gavit Rajendra Dhedya", "महाराष्ट्र", "पालघर", "गावित राजेंद्र ढेड्या",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Parbhani", "Jadhav Sanjay (Bandu) Haribhau", "महाराष्ट्र", "परभनी", "जाधव संजय (बंधु) हरिभाऊ",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Pune", "Girish Bhalchandra Bapat", "महाराष्ट्र", "पुणे", "गिरीश भालचंद्र बापट",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Raigad", "Tatkare Sunil Dattatray", "महाराष्ट्र", "रायगढ़", "तटकरे सुनील दत्तात्रय",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Ramtek", "Krupal Balaji Tumane", "महाराष्ट्र", "रामटेक", "कृपाल बालाजी तुमणे",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Ratnagiri Sindhudurg", "Vinayak Bhaurao Raut", "महाराष्ट्र", "रत्नागिरी-सिंधुदुर्ग", "विनायक भाउराव राउत",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Raver", "Khadse Raksha Nikhil", "महाराष्ट्र", "रावेर", "खडसे रक्षा निखिल",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Sangli", "Sanjaykaka Patil", "महाराष्ट्र", "सांगली", "संजयकाका पाटिल",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Satara", "Bhonsle Shrimant Chhatrapati Udayanraje Pratapasinh Maharaj", "महाराष्ट्र", "सतारा", "भोंसले श्रीमंत छत्रपति उदयनराजे प्रतापसिंह महाराज",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Shirdi", "Sadashiv Kisan Lokhande", "महाराष्ट्र", "शिरडी", "सदाशिव किसान लोखंडे",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Shirur", "Amol Ramsing Kolhe", "महाराष्ट्र", "शिरुर", "अमोल रामसिंग कोल्हे",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Solapur", "Shri. Sha. Bra. Dr. Jay Siddeshwar Shivachrya Mahaswamiji", "महाराष्ट्र", "सोलापुर", "श्री। शा। ब्रा। डॉ। जय सिद्धेश्वर शिवाचार्य महास्वामीजी",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Thane", "Rajan Baburao Vichare", "महाराष्ट्र", "थाइन", "राजन बाबूराव विचारे",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Wardha", "Ramdas Chandrabhanji Tadas", "महाराष्ट्र", "वर्धा", "रामदास चंद्रभानजी तदास",  "",  "", "", "", "", ""}, 
		{"Maharashtra", "Yavatmal-Washim", "Bhavana Pundlikrao Gawali", "महाराष्ट्र", "यवतमाल-वाशिम", "भावना पुंडलीकराव गवली",  "",  "", "", "", "", ""}, 
		{"Manipur", "Inner Manipur", "Dr Rajkumar Ranjan Singh", "मणिपुर", "इनर मणिपुर", "डॉ. राजकुमार रंजन सिंह",  "9436021753",  "0385-2459986", "", "ranjanrk50@gmail.com", "", "Kongba Nandeibam Leikai, PO. Singjamei, P.S. Irilbung, Dist. Imphal East Manipur"}, 
		{"Manipur", "Outer Manipur", "Lorho S. Pfoze", "मणिपुर", "बाहरी मणिपुर", "लोरो एस। पीफोज़",  "",  "", "", "", "", ""}, 
		{"Meghalaya", "Shillong", "Vincent H. Pala", "मेघालय", "शिलांग", "विंसेंट एच। पाला",  "",  "", "", "", "", ""}, 
		{"Meghalaya", "Tura", "Agatha K. Sangma", "मेघालय", "तुरा", "अगाथा के संगमा",  "",  "", "", "", "", ""}, 
		{"Mizoram", "Mizoram", "C Lalrosanga", "मिज़ोरम", "मिजोरम", "सी लालसरंगा",  "",  "", "", "", "", ""}, 
		{"Nagaland", "Nagaland", "Tokheho Yepthomi", "नागालैण्ड", "नगालैंड", "तोखेहो येप्थोमी",  "",  "", "", "", "", ""}, 
		{"National Capital Territory of Delhi", "Chandni Chowk", "Harsh Vardhan", "दिल्ली", "चांदनी चोक", "हर्षवर्धन",  "9810115311",  "", "", "drhrsvardhan@gmail.com", "", "R/o E-8A/14, Krishna Nagar Delhi 110051"}, 
		{"National Capital Territory of Delhi", "East Delhi", "Gautam Gambhir", "दिल्ली", "पूर्वी दिल्ली", "गौतम गंभीर",  "9818287292",  "", "", "97gambhirgautam@gmail.com", "", "R/O 6B/8, N.E.A. Old Rajinder Nagar, New Delhi 110060"}, 
		{"National Capital Territory of Delhi", "New Delhi", "Meenakashi Lekhi", "दिल्ली", "नई दिल्ली", "मीनाक्षी लेखी",  "",  "", "", "", "", ""}, 
		{"National Capital Territory of Delhi", "North East Delhi", "Manoj Tiwari", "दिल्ली", "नॉर्थ ईस्ट दिल्ली", "मनोज तिवारी",  "",  "", "", "", "", ""}, 
		{"National Capital Territory of Delhi", "North West Delhi", "Hans Raj Hans", "दिल्ली", "उत्तर पश्चिम दिल्ली", "हंस राज हंस",  "",  "", "", "", "", ""}, 
		{"National Capital Territory of Delhi", "South Delhi", "Ramesh Bidhuri", "दिल्ली", "दक्षिण दिल्ली", "रमेश बिधूड़ी",  "",  "", "", "", "", ""}, 
		{"National Capital Territory of Delhi", "West Delhi", "Parvesh Sahib Singh", "दिल्ली", "पश्चिमी दिल्ली", "परवेश साहिब सिंह",  "",  "", "", "", "", ""}, 
		{"Odisha", "Aska", "Pramila Bisoyi", "ओडिशा", "अस्का", "प्रमिला बिसोई",  "7683941934",  "", "", "pramilabisoyi2019@gmail.com", "", "At Cheramaria, Po Nalabanta, Ps Aska(Gm) Pin-761111"}, 
		{"Odisha", "Balasore", "Pratap Chandra Sarangi", "ओडिशा", "बालासोर", "प्रताप चंद्र सारंगी",  "9437033216",  "", "", "pratapchandrasarangi@gmail.com", "", "R/O At/ Gopinathpur, PO- Dhobasila,PS-Nilgiri,Dist, Balasore"}, 
		{"Odisha", "Bargarh", "Suresh Pujari", "ओडिशा", "बारगढ़", "सुरेश पुजारी",  "9437060000",  "", "", "sureshkpujari@gmail.com", "sureshpujarioffice@gmail.com", "Sakhipara, P.o-Samblapur, Ps-Dhanupali, Tah/Dist. Sambalpur -768001"}, 
		{"Odisha", "Berhampur", "Chandra Sekhar Sahu", "ओडिशा", "बेरहामपुर", "चन्द्रशेखर साहू",  "9437072119",  "", "", "sahuchandrasec@gmail.com", "", "Bijipur Main Road PO: Berhampur-760003, PS: Gosaninuagam, District: Ganjam, Odisha"}, 
		{"Odisha", "Bhadrak", "Manjulata Mandal", "ओडिशा", "भद्रक", "मंजुलता मंडल",  "9438751894",  "", "", "manjulatamandal2019@gmail.com", "", "Kanjikhila, PO Ertal, PS Basudevpur, District Bhadrak, Odisha, Pin No 756124, Present Residing At Jagannath Vihar, PO Saladi Colony, Bhadrak, District Bhadrak, Odisha, Pin-756100"}, 
		{"Odisha", "Bhubaneswar", "Aparajita Sarangi", "ओडिशा", "भुवनेश्वर", "अपराजिता सारंगी",  "9873766647",  "", "", "aparajitasarangi@gmail.com", "", "N-4/222, IRC Village Nayapalli Bhubaneswar Odisha"}, 
		{"Odisha", "Bolangir", "Smt. Sangeeta Kumari Singh Deo", "ओडिशा", "बोलंगीर", "श्रीमती. संगीता कुमारी सिंह देव",  "9810152090",  "", "", "sksinghdeo@hotmail.com", "", "Rajkhamar, AT/PO/PS: Patnagarh, Dist.Bolangir, Odisha"}, 
		{"Odisha", "Cuttack", "Bhartruhari Mahtab", "ओडिशा", "कटक", "भर्तृहरि महताब",  "9868180308",  "0671-2508002", "0671-2507568", "bhartruhari.mahtab@gmail.com", "", "At-Beharibagh, P.o- Chandinichowk Ps-Lalbagh Town Dist. Cuttack 753002"}, 
		{"Odisha", "Dhenkanal", "Mahesh Sahoo", "ओडिशा", "ढेंकनाल", "महेश साहू",  "9437040905",  "", "", "", "", "R/O Village Brahman Sasan Talcher Town Ward No-2 PO PS-Talcher Dist Angul Odisha Pin-759107"}, 
		{"Odisha", "Jagatsinghpur", "Rajashree Mallick", "ओडिशा", "जगतसिंहपुर", "राजश्री मल्लिक",  "9438174159",  "", "", "tirtolmla@gmail.com", "", "R/O Ward No-5, At/Po-Tirtol, Dist Jagatsinghpur, Pin 754137"}, 
		{"Odisha", "Jajpur", "Sarmistha Sethi", "ओडिशा", "जाजपुर", "सरमिस्ठा सेठी",  "9861086270",  "", "", "sarmistha.sethi74@gmail.com", "", "Ro- Vill. Samantarapur P.O Samantarapur P.S Jajpur Sadar, Kabirpur Dist. Jajpur Odisha -755009"}, 
		{"Odisha", "Kalahandi", "Basanta Kumar Panda", "ओडिशा", "कालाहांडी", "बसंत कुमार पांडा",  "9437071404",  "", "", "basantapanda.npd@gmail.com", "", "Ward No-5,PO/PS/DIST-Nuapada"}, 
		{"Odisha", "Kandhamal", "Achyutananda Samanta", "ओडिशा", "कंधमाल", "अच्युतानंद सामंत",  "9437000928",  "", "", "achyuta@kiit.ac.in", "", "N3/92,IRC Village,Nayapalli,Bhubaneswar,Odisha-751015"}, 
		{"Odisha", "Kendrapara", "Anubhav Mohanty", "ओडिशा", "केंद्रपाड़ा", "अनुभव मोहंती",  "",  "", "", "", "", ""}, 
		{"Odisha", "Keonjhar", "Chandrani Murmu", "ओडिशा", "क्योंझर", "चंद्रानी मुर्मू",  "",  "", "", "", "", ""}, 
		{"Odisha", "Koraput", "Saptagiri Sankar Ulaka", "ओडिशा", "कोरापुट", "सप्तगिरि संकर उलका",  "",  "", "", "", "", ""}, 
		{"Odisha", "Mayurbhanj", "Bishweswar Tudu", "ओडिशा", "मयूरभंज", "बिशेश्वर टुडू",  "",  "", "", "", "", ""}, 
		{"Odisha", "Nabarangpur", "Ramesh Chandra Majhi", "ओडिशा", "नबरंगपुर", "रमेश चंद्र माझी",  "",  "", "", "", "", ""}, 
		{"Odisha", "Puri", "Pinaki Misra", "ओडिशा", "पुरी", "पिनाकी मिश्रा",  "",  "", "", "", "", ""}, 
		{"Odisha", "Sambalpur", "Nitesh Ganga Deb", "ओडिशा", "संबलपुर", "नितेश गंगा देब",  "",  "", "", "", "", ""}, 
		{"Odisha", "Sundargarh", "Jual Oram", "ओडिशा", "सुंदरगढ़", "जुअल ओराम",  "",  "", "", "", "", ""}, 
		{"Puducherry", "Puducherry", "V. Vaithilingam", "पुदुच्चेरी", "पुडुचेरी", "वी। वैथीलिंगम",  "",  "", "", "", "", ""}, 
		{"Punjab", "Amritsar", "Gurjeet Singh Aujla", "पंजाब", "अमृतसर", "गुरजीत सिंह औजला",  "9872027477",  "", "", "aujla786.gs@gmail.com", "", "Ro- 16-A Guru Amar dass Avenue Block A Amritsar"}, 
		{"Punjab", "Anandpur Sahib", "Manish Tewari", "पंजाब", "आनंदपुर साहिब", "मनीष तिवारी",  "011-26716001",  "", "", "manishtewari01@gmail.com", "", "228-A, Sarabha Nagar, Ludhiana, Punjab Pin Code- 141001"}, 
		{"Punjab", "Bathinda", "Harsimrat Kaur Badal", "पंजाब", "बठिंडा", "हरसिमरत कौर बादल",  "01637244671",  "", "", "harsimratbadal2019@gmail.com", "", "Ro- Village Badal Tehsil Malout Dist. Sri Mukatsar Sahib Punjab"}, 
		{"Punjab", "Faridkot", "Mohammad Sadique", "पंजाब", "फरीदकोट", "मोहम्मद सादिक",  "9814720610",  "", "", "mohdsadique100@gmail.com", "", "H.No.44 Adarsh colony Barewal Awana Ludhiana Tehsil And Dist. Ludhiana"}, 
		{"Punjab", "Fatehgarh Sahib", "Amar Singh", "पंजाब", "फतेहगढ़ साहिब", "अमर सिंह",  "9711342001",  "", "", "dr.amarsingh53@gmail.com", "", "House No. 66, Green City, Barnala Road Raikot"}, 
		{"Punjab", "Firozpur", "Sukhbir Singh Badal", "पंजाब", "फिरोजपुर", "सुखबीर सिंह बादल",  "01637-244671",  "", "", "sukhbirbadal01@gmail.com", "", "Vill. Badal, Teh Malout, Dist Sri Mukatsar Sahib, Punjab"}, 
		{"Punjab", "Gurdaspur", "Ajay Singh Dharmendra Deol (Sunny Deol)", "पंजाब", "गुरदासपुर", "अजय सिंह धर्मेंद्र देओल (सनी देओल)",  "9004711114",  "", "", "ajaysinghdeol@mac.com", "", "T-1 Dharmendra House No 3 Kapul Society 11th Road J.V.P.D Juhu Scheme Vileparle (W) Teh-Andheri Dist. Mumbai Maharashtra-400056"}, 
		{"Punjab", "Hoshiarpur", "Som Parkash", "पंजाब", "होशियारपुर", "सोम प्रकाश",  "9876100022",  "", "", "somparkash.bjp@gmail.com", "", "173, Urban Estate, Phagwara"}, 
		{"Punjab", "Jalandhar", "Santokh Singh Chaudhary", "पंजाब", "जालंधर", "संतोख सिंह चौधरी",  "9814062168",  "0181-2254448", "", "santokhschaudhary@gmail.com", "", "R/O- B-8, 281, Landhra House Nurmahal Road, Phillaur Tehsil Phillaur Dist- Jalandhar"}, 
		{"Punjab", "Khadoor Sahib", "Jasbir Singh Gill", "पंजाब", "खडूर साहिब", "जसबीर सिंह गिल",  "",  "", "", "", "", ""}, 
		{"Punjab", "Ludhiana", "Ravneet Singh Bittu", "पंजाब", "लुधियाना", "रवनीत सिंह बिट्टू",  "",  "", "", "", "", ""}, 
		{"Punjab", "Patiala", "Preneet Kaur", "पंजाब", "पटियाला", "परनीत कौर",  "",  "", "", "", "", ""}, 
		{"Punjab", "Sangrur", "Bhagwant Mann", "पंजाब", "संगरूर", "भगवंत मान",  "",  "", "", "", "", ""}, 
		{"Rajasthan", "Ajmer", "Bhagirath Chaudhary", "राजस्थान", "अजमेर", "भागीरथ चौधरी",  "9414011998",  "", "", "bhagirathchoudhary.25@gmail.com", "", "Choyal House Pani Ke Tanki ke Pass Santi Nagar, Madanganj Kishangarh Ajmer Pin Code 305801"}, 
		{"Rajasthan", "Alwar", "Mahant Balak Nath", "राजस्थान", "अलवर", "महंत बालक नाथ",  "9929491894",  "9215312333", "8295069887", "yogibalaknath19@gmail.com", "", " Village Thedi Gagani (Natho wali) Tehsil and District Hamumangarh Hall Shri Baba Mastnath Math Astalbohar, Rohtak Haryana"}, 
		{"Rajasthan", "Banswara", "Kanakmal Katara", "राजस्थान", "बांसवाड़ा", "कनकमल कटारा",  "9414104796",  "", "", "kanakmalkatara20@gmail.com", "", "PHLATED, PO.-BHILUDA, TEHSIL-SAAGWARA, DIST.-DUNGARPUR, RAJASTHAN"}, 
		{"Rajasthan", "Barmer", "Kailash Choudhary", "राजस्थान", "बाड़मेर", "कैलाश चौधरी",  "9414108663",  "9928608663", "", "kkailashchoudhary@gmail.com", "", "Ward No. 32 Jat Colony, Samdari Road Balotara, Tehsil - Pachpdara"}, 
		{"Rajasthan", "Bharatpur", "Ranjeeta Kumari", "राजस्थान", "भरतपुर", "रंजीता कुमारी",  "6350605203",  "", "", "", "", "Pathan Pada, Bayana District - Bharatpur"}, 
		{"Rajasthan", "Bhilwara", "Subhash Chandra Baheria", "राजस्थान", "भीलवाड़ा", "सुभाष चंद्र बहेरिया",  "9829046344",  "", "", "baheriasc@gmail.com", "", "A-81, SUBHASH NAGAR, NEAR UIT, BHILWARA"}, 
		{"Rajasthan", "Bikaner", "Arjun Ram Meghwal", "राजस्थान", "बीकानेर", "अर्जुन राम मेघवाल",  "9414075910",  "", "", "arjunrammeghwal@gmail.com", "", "R/o Meghwalo Ka Mohalla Kismidesar W.No.23,Post Bhinasar Bikaner"}, 
		{"Rajasthan", "Chittorgarh", "Chandra Prakash", "राजस्थान", "चित्तौड़गढ़", "चंद्र प्रकाश",  "9414111371",  "", "", "cpjoshicor@gmail.com", "", "61, SOMNAGAR-IInd, MADHUWAN SENTHI, CHITTORGARH, RAJASTHAN"}, 
		{"Rajasthan", "Churu", "Rahul Kaswan", "राजस्थान", "चुरू", "राहुल कस्वां",  "9013869339",  "9560111599", "", "rahulkaswan2@gmail.com", "", "VPO KAJRI TEHSIL RAJGARH, CHURU, RAJASTHAN-331301"}, 
		{"Rajasthan", "Dausa", "Jaskaur Meena", "राजस्थान", "दौसा", "जसकौर मीना",  "9414030751",  "", "", "jaskaurmeena@gmail.com", "", "RO Anurag Niwas Ranthambhore Road sawai Madhopur"}, 
		{"Rajasthan", "Ganganagar", "Nihal Chand", "राजस्थान", "गंगानगर", "निहाल चंद",  "01507-221317",  "", "", "nihalchand@gmail.com", "", "Ward No-3 Raysinghnagar Dist, Shriganganagar"}, 
		{"Rajasthan", "Jaipur", "Ram Charan Bohra", "राजस्थान", "जयपुर", "राम चरण बोहरा",  "9829066531",  "9013869343", "9414046046", "ramcharanbohra@gmail.com", "", "F-21, LAL BAHADUR COLONY, LOTUS STREET, 4th AVENUE DURGAPUR, JAIPUR 302018, RAJASTHAN"}, 
		{"Rajasthan", "Jaipur Rural", "Col. Rajyavardhan Rathore", "राजस्थान", "जयपुर ग्रामीण", "कर्नल राज्यवर्धन राठौर",  "9460996611",  "", "", "rathorebjp@gmail.com", "", "C-26, VAISHALI MARG, VAISHALI NAGAR, JAIPUR"}, 
		{"Rajasthan", "Jalore", "Devaji Patel", "राजस्थान", "जालोर", "देवजी पटेल",  "9414158488",  "", "", "jaloremp@gmail.com", "", "R/O 10,Kalbiyo Ka Bas,Jajusan,Teh-Sanchore Dist Jalore,RJ 343041"}, 
		{"Rajasthan", "Jhalawar Baran", "Dushyant", "राजस्थान", "झालावाड़", "दुष्यंत",  "8130486886",  "9414256056", "", "dushyant@dholpurpalace.com", "", "197,Sitaram Colony, Ward No. 2, Dholpur, Dist - Dholpur, Rajasthan"}, 
		{"Rajasthan", "Jhunjhunu", "Narendra Kumar", "राजस्थान", "झुंझुनू", "नरेंद्र कुमार",  "9414080558",  "", "", "narendrapradhanmandawa1@gmail.com", "", "Vill. Kamalsar, Post Diloi South, Bissau, Dist. Jhunjhunu"}, 
		{"Rajasthan", "Jodhpur", "Gajendra Singh Shekhawat", "राजस्थान", "जोधपुर", "गजेंद्र सिंह शेखावत",  "9672000555",  "9414127772", "", "gajendrasinghshekhawat67@gmail.com", "", "PLOT NO.34-A, AJEET COLONY, RATANADA, JODHPUR"}, 
		{"Rajasthan", "Karauli Dholpur", "Manoj Rajoria", "राजस्थान", "करौली-धौलपुर", "मनोज राजोरिया",  "9414389585",  "", "", "dr.manojrajoria001@gmail.com", "", "320 Tagor Nagar, Heerapura, Ajmer road, Jaipur"}, 
		{"Rajasthan", "Kota", "Om Birla", "राजस्थान", "कोटा", "ओम बिरला",  "",  "", "", "", "", ""}, 
		{"Rajasthan", "Nagaur", "Hanuman Beniwal", "राजस्थान", "नागौर", "हनुमान बेनीवाल",  "",  "", "", "", "", ""}, 
		{"Rajasthan", "Pali", "P. P. Chaudhary", "राजस्थान", "पाली", "पीपी चौधरी",  "",  "", "", "", "", ""}, 
		{"Rajasthan", "Rajsamand", "Diya Kumari", "राजस्थान", "राजसमंद", "दीया कुमारी",  "",  "", "", "", "", ""}, 
		{"Rajasthan", "Sikar", "Sumedhanand Saraswati", "राजस्थान", "सीकर", "सुमेधानंद सरस्वती",  "",  "", "", "", "", ""}, 
		{"Rajasthan", "Tonk Sawai Madhopur", "Sukhbir Singh Jaunapuria", "राजस्थान", "टोंक-सवाई माधोपुर", "सुखबीर सिंह जौनपुरिया",  "",  "", "", "", "", ""}, 
		{"Rajasthan", "Udaipur", "Arjunlal Meena", "राजस्थान", "उदयपुर", "अर्जुनलाल मीणा",  "",  "", "", "", "", ""}, 
		{"Sikkim", "Sikkim", "Indra Hang Subba", "सिक्किम", "सिक्किम", "इंद्र हैंग सुब्बा",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Arakkonam", "S. Jagathrakshakan", "तमिल नाडु", "अराकोणम", "एस. जगतरक्षकन",  "9962059260",  "044-24913113", "", "jagatharakonamdmk@gmail.com", "", "No.1, First Main Road, Kasturibai Nagar, Adyar, Chennai - 600020"}, 
		{"Tamil Nadu", "Arani", "Vishnuprasad. M.K", "तमिल नाडु", "अरणि", "विष्णुप्रसाद.एम.के",  "9444089839",  "04424995959", "", "vishnumk@gmail.com", "", "No. 6 First Street, East Abhiramapuram, Mylapore, Chennai - 600004"}, 
		{"Tamil Nadu", "Chennai Central", "Dayanidhi Maran", "तमिल नाडु", "चेन्नई सेंट्रल", "दयानिधि मारन",  "04424371515",  "", "", "dmaranoffice@gmail.com", "", "4, second avenue, Boat club road, R.A. puram , Chennai-600028"}, 
		{"Tamil Nadu", "Chennai North", "Dr. Kalanidhi Veeraswamy", "तमिल नाडु", "चेन्नई उत्तर", "डॉ. कलानिधि वीरस्वामी",  "9884259482",  "", "", "kalanidhiv@yahoo.co.in", "", "A-3, (Old A-39) VI Street, Anna Nagar East, Chennai-600102"}, 
		{"Tamil Nadu", "Chennai South", "Sumathy Alias Thamizhachi Thangapandian", "तमिल नाडु", "चेन्नई दक्षिण", "सुमति अलियास थमिझची थांगपांडियन",  "9841208151",  "", "", "vanapechi@yahoo.co.in", "", "Plot no. 8, First Main road, Raja Nagar, Neelangarai, Chennai-600115"}, 
		{"Tamil Nadu", "Chidambaram", "Thirumaavalavan Thol", "तमिल नाडु", "चिदंबरम", "थिरुमावलवन थोल",  "9789872555",  "", "", "thirumaofficial@gmail.com", "", "keilth street angannur sannasinallur uratchi"}, 
		{"Tamil Nadu", "Coimbatore", "P R Natarajan", "तमिल नाडु", "कोयंबटूर", "पी आर नटराजन",  "9442102325",  "", "", "prncoimbatore@gmail.com", "", "1-E, Annapoorna lay out, New Siddhapudur, Coimbatore - 641044"}, 
		{"Tamil Nadu", "Cuddalore", "T. R. V .S. Ramesh", "तमिल नाडु", "कुड्डालोर", "टी.आर.वी.एस. रमेश",  "9597037470",  "9367626774", "", "srigayathricashew@gmail.com", "", "D.No.65,Kumbakonam Road , Panruti Post & Taluk, Cuddaore Dist-607106"}, 
		{"Tamil Nadu", "Dharmapuri", "Dnv Senthilkumar.S", "तमिल नाडु", "धर्मपुरी", "दीनव सेंथिलकुमार.स.",  "9443372349",  "", "", "drsenthilkumar.s@hotmail.com", "", "12/9-C, Winding Driver Chinnasamy Street, Dharamapuri Post, Dharamapuri Taluk, Dharamapuri District 636701"}, 
		{"Tamil Nadu", "Dindigul", "Velusamy P", "तमिल नाडु", "डिंडीगुल", "वेलुसामी पी",  "7397056761",  "", "", "velusamydmkdgl@gmail.com", "", "2-229 Javathupatti Oddanchattram 624619"}, 
		{"Tamil Nadu", "Erode", "Ganeshamurthi A", "तमिल नाडु", "इरोड", "गणेशमूर्ति ए",  "9842756162",  "9442516162", "", "ganeshamurthi@gmail.com", "", "H-45, Periyar Nagar, Erode-638001"}, 
		{"Tamil Nadu", "Kallakurichi", "Gautham Sigamani Pon", "तमिल नाडु", "कल्लाकुरिची", "गौतम सिगमनी पोन",  "9600011115",  "", "", "drsigas@yahoo.co.in", "", "Ro-6-4,Thirupanazhwar Street Villupuram Pin-605602"}, 
		{"Tamil Nadu", "Kancheepuram", "Selvam.G", "तमिल नाडु", "कांचीपुरम", "सेलवाम.जी",  "9443597043",  "", "", "gselvamdmk@gmail.com", "", "No.148 Mariyamman Kovil Theru, Siruvedal village, Kanchipuram - 631561"}, 
		{"Tamil Nadu", "Kanniyakumari", "Vasanthakumar H", "तमिल नाडु", "कन्याकूमारी", "वसंतकुमार एच",  "9840033350",  "9962633350", "", "hvk3335@gmail.com", "", "26(old.no 27), Natesan Street, T. Nagar, Chennai-600017"}, 
		{"Tamil Nadu", "Karur", "Jothimani S", "तमिल नाडु", "करूर", "जोथिमनी एस",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Krishnagiri", "Dr.A.Chellakumar", "तमिल नाडु", "कृष्णागिरी", "Dr.A.Chellakumar",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Madurai", "Venkatesan S", "तमिल नाडु", "मदुरै", "वेंकटेशन एस",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Mayiladuthurai", "Ramalingam S", "तमिल नाडु", "माइलादुत्रयी", "रामलिंगम एस",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Nagapattinam", "Selvaraj M", "तमिल नाडु", "नागपट्टिनम", "सेल्वराज एम",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Namakkal", "Chinraj A.K.P", "तमिल नाडु", "नमक्कल", "चिनराज ए.के.",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Nilgiris", "A. Raja", "तमिल नाडु", "नीलगिरी", "ए राजा",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Perambalur", "Paarivendhar T R", "तमिल नाडु", "पेरम्बलुर", "परिवारीधर टी.आर.",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Pollachi", "K Shanmugasundaram", "तमिल नाडु", "पोलाची", "के षणमुगसुंदरम",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Salem", "Parthiban.S.R", "तमिल नाडु", "सलेम", "Parthiban.SR",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Sivaganga", "Karti P Chidambaram", "तमिल नाडु", "शिवगंगा", "कार्ति पी चिदंबरम",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Sriperumbudur", "Baalu.T.R.", "तमिल नाडु", "श्रीपेरुमबुदुर", "Baalu.TR",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Tenkasi", "Dhanush M Kumar", "तमिल नाडु", "तेनकासी", "धनुष एम कुमार",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Thanjavur", "Palanimanickam.S.S", "तमिल नाडु", "तंजावुर", "Palanimanickam.SS",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Theni", "P. Raveendranath Kumar", "तमिल नाडु", "तब मैं", "पी। रवींद्रनाथ कुमार",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Thoothukkudi", "Kanimozhi Karunanidhi", "तमिल नाडु", "थूथुकुडी", "कनिमोझी करुणानिधि",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Tiruchirappalli", "Thirunavukkarasar. Su", "तमिल नाडु", "तिरुचिरापल्ली", "थिरुनावुक्कारसर। र",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Tirunelveli", "Gnanathiraviam S", "तमिल नाडु", "तिरुनेलवेली", "ज्ञाननाथिराविम S",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Tiruppur", "Subbarayan.K", "तमिल नाडु", "तिरुपूर", "Subbarayan.K",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Tiruvallur", "Dr.K.Jayakumar", "तमिल नाडु", "तिरुवल्लुर", "Dr.K.Jayakumar",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Tiruvannamalai", "Annadurai C N", "तमिल नाडु", "तिरुवन्नामलाई", "अन्नादुराई सी.एन.",  "",  "", "", "", "", ""}, 
		{"Tamil Nadu", "Viluppuram", "Ravikumar D", "तमिल नाडु", "विलुप्पुरम", "रविकुमार डी",  "",  "", "", "", "", ""}, 
		{"Telangana", "Adilabad", "Bapu Rao Soyam", "तेलंगाना", "आदिलाबाद", "बापू राव सोयम",  "6303141476",  "9573477698", "", "", "", "H.No.1-75 R/o Ghanpur village of Boath Mandal Dist Adilabad"}, 
		{"Telangana", "Bhongir", "Komatireddy Venakat Reddy", "तेलंगाना", "भोंगीर", "कोमाटेड्डी वेंकट रेड्डी",  "09948297777",  "", "", "komatireddynlg@gmail.com", "", "H.No 6-2-842 meerbagh colony,hyd road, nalgonda town nalgonda-508001"}, 
		{"Telangana", "Chevella", "Dr.Gaddam Ranjith Reddy", "तेलंगाना", "चेवेल्ला", "डॉ. गद्दाम रंजीथ रेड्डी",  "9866395845",  "", "", "greddy1962@yahoo.co.in", "", "H.No.8-2-293/82/NL/137-138, MLA & MP Colony Jubilee Hills, Hyderabad-500033"}, 
		{"Telangana", "Hyderabad", "Asaduddin Owaisi", "तेलंगाना", "हैदराबाद", "असदुद्दीन ओवैसी",  "9848013569",  "9868180569", "", "asadowaisi@rediffmail.com", "", " H. No. 8-15-130/AS/1, Shastripuram, Mailardevpally, Ranga Reddy District 500052"}, 
		{"Telangana", "Karimnagar", "Bandi Sanjay Kumar", "तेलंगाना", "करीमनगर", "बंदी संजय कुमार",  "",  "", "", "", "", ""}, 
		{"Telangana", "Khammam", "Nama Nageswr Rao", "तेलंगाना", "खम्मम", "नामा नागसेवक राव",  "",  "", "", "", "", ""}, 
		{"Telangana", "Mahabubabad", "Kavitha Malothu", "तेलंगाना", "महबुबाबाद", "कविता मलोथू",  "",  "", "", "", "", ""}, 
		{"Telangana", "Mahbubnagar", "Manne Srinivas Reddy", "तेलंगाना", "महबूबनगर", "मन्ने श्रीनिवास रेड्डी",  "",  "", "", "", "", ""}, 
		{"Telangana", "Malkajgiri", "Anumula Revanth Reddy", "तेलंगाना", "मल्काजगिरि", "अनमुला रेवंत रेड्डी",  "",  "", "", "", "", ""}, 
		{"Telangana", "Medak", "Kotha Prabhakar Reddy", "तेलंगाना", "मेडक", "कोठा प्रभाकर रेड्डी",  "",  "", "", "", "", ""}, 
		{"Telangana", "Nagarkurnool", "Pothuganti Ramulu", "तेलंगाना", "नगरकुरनूल", "पोथुगांती रामुलु",  "",  "", "", "", "", ""}, 
		{"Telangana", "Nalgonda", "Nalamada Uttam Kumar Reddy", "तेलंगाना", "नलगोंडा", "नालमदा उत्तम कुमार रेड्डी",  "",  "", "", "", "", ""}, 
		{"Telangana", "Nizamabad", "Dharmapuri Arvind", "तेलंगाना", "निजामाबाद", "धर्मपुरी अरविंद",  "",  "", "", "", "", ""}, 
		{"Telangana", "Peddapalle", "Venkatesh Netha Borlakunta", "तेलंगाना", "पेडेपल्लै", "वेंकटेश नेथा बोरलाकुंटा",  "",  "", "", "", "", ""}, 
		{"Telangana", "Secunderabad", "Gangapuram Kishan Reddy", "तेलंगाना", "सिकंदराबाद", "गंगापुरम किशन रेड्डी",  "",  "", "", "", "", ""}, 
		{"Telangana", "Warangal", "Dayakar Pasnori", "तेलंगाना", "वारंगल", "दयाकर पासनोरी",  "",  "", "", "", "", ""}, 
		{"Telangana", "Zahirabad", "B.B.Patil", "तेलंगाना", "जहीराबाद", "BBPatil",  "",  "", "", "", "", ""}, 
		{"Tripura", "Tripura East", "Rebati Tripura", "त्रिपुरा", "त्रिपुरा पूर्व", "रेबती त्रिपुरा",  "",  "", "", "", "", ""}, 
		{"Tripura", "Tripura West", "Pratima Bhoumik", "त्रिपुरा", "त्रिपुरा पश्चिम", "प्रतिमा भौमिक",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Agra", "Satyapal Singh Baghel", "उत्तर प्रदेश", "आगरा", "सत्यपाल सिंह बघेल",  "9412750555",  "0562-2213422", "", "profspsinghbaghel@gmail.com", "", "44 M.I.G., New Shahaganj, Saket Colony, Agra"}, 
		{"Uttar Pradesh", "Aligarh", "Satish Kumar Gautam", "उत्तर प्रदेश", "अलीगढ़", "सतीश कुमार गौतम",  "09013869418",  "05712742425", "", "satishgautambjp@gmail.com", "", "204, Vaishna Apt, Vidya Nagar Colony, Aligarh"}, 
		{"Uttar Pradesh", "Allahabad", "Rita Bahuguna Joshi", "उत्तर प्रदेश", "इलाहाबाद", "रीता बहुगुणा जोशी",  "9810262658",  "", "", "ritabjoshi@hotmail.com", "", "R/O- 8-type, VI- Rajbhawan Colony Lucknow"}, 
		{"Uttar Pradesh", "Ambedkar Nagar", "Ritesh Pandey", "उत्तर प्रदेश", "अंबेडकर नगर", "रितेश पांडे",  "9670055550",  "8887151080", "", "welham789@gmail.com", "", "R/O H NO-90 Mohsinpur Mansurpur Anshiq Teh Akbarpur Dist Ambedkar Nagar 224122"}, 
		{"Uttar Pradesh", "Amethi", "Smriti Irani", "उत्तर प्रदेश", "अमेठी", "स्मृति ईरानी",  "9820075198",  "", "", "smritizirani@gmail.com", "", "A-602, Neptune Apartments, Swami Samarth Nagar 4th Cross Lane, Lokhandwala Complex, Andheri West, Mumbai 400053 Maharashtra"}, 
		{"Uttar Pradesh", "Amroha", "Kunwar Danish Ali", "उत्तर प्रदेश", "अमरोहा", "कुंवर दानिश अली",  "9810873415",  "", "", "kda_jds@yahoo.co.in", "", "Room.no.1228 Bhanda Patti Teh.Hapud Janpad Hapud."}, 
		{"Uttar Pradesh", "Aonla", "Dharmendra Kumar", "उत्तर प्रदेश", "आंवला", "धर्मेंद्र कुमार",  "09013869427",  "8171505427", "", "dharmendrakashyap1203@gmail.com", "", "Gram Kandhar Post Umar Siya Dist- Barelliy"}, 
		{"Uttar Pradesh", "Azamgarh", "Akhilesh Yadav", "उत्तर प्रदेश", "आजमगढ़", "अखिलेश यादव",  "9919099999",  "0522-2986802", "", "yadavakhilesh@gmail.com", "", "R/o- Post Saifai Dist-Itawa"}, 
		{"Uttar Pradesh", "Badaun", "Sangh Mitra Maurya", "उत्तर प्रदेश", "बदायूं", "संघ मित्र मौर्य",  "9415742177",  "", "", "socialsanghmitra@gmail.com", "", "R/O 6/237 E Vipul Khand,Gomati Nagar, Lucknow"}, 
		{"Uttar Pradesh", "Baghpat", "Dr. Satyapal Singh", "उत्तर प्रदेश", "बागपत", "डॉ. सत्यपाल सिंह",  "9820000860",  "", "", "allsatya@gmail.com", "", "H.No 158, Village-Basauli, Baghpat, Uttar Pradesh"}, 
		{"Uttar Pradesh", "Bahraich", "Akshayabar Lal", "उत्तर प्रदेश", "बहराइच", "अक्षयबर लाल",  "9415054009",  "", "", "akshayabarlal@gmail.com", "", " R/O Village Semri PO-Dharmapur PS-Murthiha Teh Mihipurwa Motipur Dist Bahraich"}, 
		{"Uttar Pradesh", "Ballia", "Virendra Singh", "उत्तर प्रदेश", "बलिया", "वीरेन्द्र सिंह",  "9013869481",  "", "", "mastvirendrasingh@gmail.com", "", "Village Dokti, Po. Dokati, Dist Ballia UP"}, 
		{"Uttar Pradesh", "Banda", "R.K. Singh Patel", "उत्तर प्रदेश", "बांदा", "आर.के. सिंह पटेल",  "9415143993",  "8887151037", "", "rksinghpatel59@gmail.com", "", "Village- Baldauganj karvi, Post-Karvi, Dist. Chitrakoot"}, 
		{"Uttar Pradesh", "Bansgaon", "Kamlesh Paswan", "उत्तर प्रदेश", "बांसगांव", "कमलेश पासवान",  "9013180277",  "", "", "kamleshpassi67@gmail.com", "", "Ro- Paswan Niwas Uttari Gate Medical Collage Gorakhpur"}, 
		{"Uttar Pradesh", "Barabanki", "Upendra Singh Rawat", "उत्तर प्रदेश", "बाराबंकी", "उपेंद्र सिंह रावत",  "9415152609",  "8887151069", "", "upendrasinghrawatmla269@gmail.com", "", "Baruaa Majhare Vahabpour Post Achecha Dist. Barabanki"}, 
		{"Uttar Pradesh", "Bareilly", "Santosh Kumar Gangwar", "उत्तर प्रदेश", "बरेली", "संतोष कुमार गंगवार",  "05812577020",  "", "", "santoshgangwar.bareilly@gmail.com", "", "R/O 22 Choudhary Mohalla Po-Gulabnagar ,Bareli UP 243001"}, 
		{"Uttar Pradesh", "Basti", "Harish Chandra Alias Harish Dwivedi", "उत्तर प्रदेश", "बस्ती", "हरीश चंद्र उर्फ हरीश द्विवेदी",  "9013869464",  "", "", "bjpharish@gmail.com", "", "R/O Vill. PO Katya H. NO- 112, Dist. Basti UP"}, 
		{"Uttar Pradesh", "Bhadohi", "Ramesh Chand", "उत्तर प्रदेश", "भदोही", "रमेश चंद",  "9415025711",  "", "", "", "", "Village-Itwa, Post Omai Dist-Mirzapur U.P"}, 
		{"Uttar Pradesh", "Bijnor", "Malook Nagar", "उत्तर प्रदेश", "बिजनौर", "मलूक नगर",  "8800347000",  "", "", "mlooknagar@malooknagar.com", "", "Nagar House, Vidur Kuti Road, Bukhara, Bijnor UP"}, 
		{"Uttar Pradesh", "Bulandshahr", "Bhola Singh", "उत्तर प्रदेश", "बुलंदशहर", "भोला सिंह",  "9013869417",  "", "", "drbholasingh@gmail.com", "", "R/o 123 Bohich Teh Sikarpur Dist Bulandsahar"}, 
		{"Uttar Pradesh", "Chandauli", "Dr. Mahendra Nath Pandey", "उत्तर प्रदेश", "चंदौली", "डॉ. महेंद्र नाथ पांडे",  "9307001007",  "910386979", "9415023457", "drmnpandeymp@gmail.com", "", "Ro- 22/157-7 Sarswati Nagar, Vinayaka, Varanasi"}, 
		{"Uttar Pradesh", "Deoria", "Ramapati Ram Tripathi", "उत्तर प्रदेश", "देवरिया", "रमापति राम त्रिपाठी",  "9415009251",  "", "", "drramapatiramtripathi@gmail.com", "", "Village+Post-Jhudiya, Teh- Khajani, Dist. Gorakhpur"}, 
		{"Uttar Pradesh", "Dhaurahra", "Rekha Verma", "उत्तर प्रदेश", "धौरहरा", "रेखा वर्मा",  "9455004449",  "", "", "rekhaverma9935@gmail.com", "", "R/O Vill. Maksudpur Dist. Lakhimpur Khiri"}, 
		{"Uttar Pradesh", "Domariyaganj", "Jagdambika Pal", "उत्तर प्रदेश", "डुमरियागंज", "जगदम्बिका पाल",  "9013180217",  "9415037381", "", "jagdambikapal@gmail.com", "", "Village- Sadi Post-Madhukarpur, DIstrict Siddarthnagar"}, 
		{"Uttar Pradesh", "Etah", "Rajveer Singh", "उत्तर प्रदेश", "एटा", "राजवीर सिंह",  "9756077777",  "", "", "mpetahrajveersingh@gmail.com", "", "Ro Vill. Madoli Nisfi Asharfabad Post office Th. Atrauly Dist Aligarh"}, 
		{"Uttar Pradesh", "Etawah", "Dr Ram Shankar Katheria", "उत्तर प्रदेश", "इटावा", "डॉ. राम शंकर कठेरिया",  "9013180116",  "0562-2527988", "", "mpagra@gmail.com", "", "Teachers Home Parisar Khandari 41 Etawah"}, 
		{"Uttar Pradesh", "Faizabad", "Lallu Singh", "उत्तर प्रदेश", "फैजाबाद", "लल्लू सिंह",  "9415905607",  "", "", "lallusingh@sansad.nic.in", "", "128A, Saadatganj, District Ayodhya"}, 
		{"Uttar Pradesh", "Farrukhabad", "Mukesh Rajput", "उत्तर प्रदेश", "फर्रुखाबाद", "मुकेश राजपूत",  "05692-224455",  "", "", "mukesh.rajput@sansad.nic.in", "", "Rategunj ITI Chorah Farrukabad"}, 
		{"Uttar Pradesh", "Fatehpur", "Sadhvi Niranjan Jyoti", "उत्तर प्रदेश", "फतेहपुर", "साध्वी निरंजन ज्योति",  "9415532346",  "", "", "sansadsewakendra@gmail.com", "", "Ro- Jal Talab Ramedi, Hamirpur UP"}, 
		{"Uttar Pradesh", "Fatehpur Sikri", "Rajkumar Chahar", "उत्तर प्रदेश", "फतेहपुर सीकरी", "राजकुमार चाहर",  "9411456789",  "", "", "rajkumarchahar9@gmail.com", "", "H.No. 59/121, Ajit Nagar, VIP Road, Khairiya Gate, Agra-282001"}, 
		{"Uttar Pradesh", "Firozabad", "Dr. Chandra Sen Jadon", "उत्तर प्रदेश", "फिरोजाबाद", "डॉ. चंद्र सेन जादोन",  "9412812676",  "", "", "", "", "House no 315, Adhyapak Nagar, Gali no 4, Sirsaganj, Dist-Firozabad, Uttar Pradesh"}, 
		{"Uttar Pradesh", "Gautam Buddha Nagar", "Dr. Mahesh Sharma", "उत्तर प्रदेश", "गौतम बुद्ध नगर", "डॉ. महेश शर्मा",  "0120-2513322",  "", "", "drmahesh3333@gmail.com", "", "404, Sec.15A, Noida-201301 Dist. Gautam budh Nagar UP"}, 
		{"Uttar Pradesh", "Ghaziabad", "Vijay Kumar Singh", "उत्तर प्रदेश", "गाज़ियाबाद", "विजय कुमार सिंह",  "8826611111",  "", "", "veekaysingh@gmail.com", "", "House No. R-2/27 Rajnagar Tehsil and Dist. Ghaziabad"}, 
		{"Uttar Pradesh", "Ghazipur", "Afzal Ansari", "उत्तर प्रदेश", "गाजीपुर", "अफजल अंसारी",  "9415020279",  "", "", "786afzalansari@gmail.com", "", "R/O- Mohalla Jamalpur 2, Shaikhtola Yusufpur, Post- Mohammaddabad, Dist- Ghazipur, U.P Pin Code 233227"}, 
		{"Uttar Pradesh", "Ghosi", "Atul Kumar Singh", "उत्तर प्रदेश", "घोसी", "अतुल कुमार सिंह",  "7408000009",  "", "", "akumarsingh80@gmail.com", "", "R/O- Village/Post- Beerpur, Vikash Khand Thana- Bhawarkol Teh- Mohammadabad Dist Ghazipur"}, 
		{"Uttar Pradesh", "Gonda", "Kirti Vardhan Singh Alias Raja Bhaiya", "उत्तर प्रदेश", "गोंडा", "कीर्ति वर्धन सिंह उर्फ राजा भैया",  "9013869462",  "", "", "kvsng66@gmail.com", "", "Village Mankapur Kot, Post Mankapur, Janpad Gonda Pin Code 271302"}, 
		{"Uttar Pradesh", "Gorakhpur", "Ravindra Shyamnarayan Shukla Alias Ravi Kishan", "उत्तर प्रदेश", "गोरखपुर", "रवींद्र श्यामनारायण शुक्ल उर्फ रवि किशन",  "9839355586",  "", "", "ravikishanbjp@gmail.com", "", "B/1404, Garden Estate Laxminagar, Goregoan (West), Mumbai , Maharashtra"}, 
		{"Uttar Pradesh", "Hamirpur", "Kunwar Pushpendra Singh", "उत्तर प्रदेश", "हमीरपुर उप्र", "कुंवर पुष्पेंद्र सिंह",  "9415145100",  "", "", "pushpendra.chandelmahoba@gmail.com", "", "R/O Ashirwad Bhawan Nayapur Naikana Mahoba Janpath UP"}, 
		{"Uttar Pradesh", "Hardoi", "Jai Prakash", "उत्तर प्रदेश", "हरदोई", "जय प्रकाश",  "9793040006",  "", "", "", "", "R/O Vill. Po. Munda tahsil. Safipur Dist. Unnao"}, 
		{"Uttar Pradesh", "Hathras", "Rajvir Diler", "उत्तर प्रदेश", "हाथरस", "राजवीर दलेर",  "9411803636",  "", "", "", "", "23 Vrajvihar DA Colony Near Banna Devi G.T. Road Aligarh"}, 
		{"Uttar Pradesh", "Jalaun", "Bhanu Pratap Singh", "उत्तर प्रदेश", "जालौन", "भानु प्रताप सिंह",  "9415055465",  "", "", "bhanu@sansad.nic.in", "", "House Malviya nagar coach Dist. Jalaun"}, 
		{"Uttar Pradesh", "Jaunpur", "Shyam Singh Yadav", "उत्तर प्रदेश", "जौनपुर", "श्याम सिंह यादव",  "9319406001",  "9818333999", "", "ssyadav9@rediffmail.com", "", "Address: Village Ranipatti, Post Mokalpur, Dist. Jaunpur Uttar Pradesh 222161"}, 
		{"Uttar Pradesh", "Jhansi", "Anurag Sharma", "उत्तर प्रदेश", "झांसी", "अनुराग शर्मा",  "9839387400",  "9810099772", "", "anurag_Sharma@gmail.com", "", "R/O 371/12 Civil Line Jhansi"}, 
		{"Uttar Pradesh", "Kairana", "Pradeep Kumar", "उत्तर प्रदेश", "कैराना", "प्रदीप कुमार",  "9412558136",  "", "", "pradeepchoudhary1969@gmail.com", "", "Village Dudhala, Post Khas, Pargana Gangoh, Tehasil Nakud Dist. Saharanpur"}, 
		{"Uttar Pradesh", "Kaiserganj", "Brij Bhushan Sharan Singh", "उत्तर प्रदेश", "कैसरगंज", "बृज भूषण शरण सिंह",  "9415109000",  "", "", "bjp2014kaisherganj@gmail.com", "", "R/o Village Po Visnohar pur Janpad Gonda"}, 
		{"Uttar Pradesh", "Kannauj", "Subrat Pathak", "उत्तर प्रदेश", "कन्नौज", "सुब्रत पाठक",  "9839702949",  "", "", "pathakknjsubrat@gmail.com", "", "R/O M.Pathkana Post CHipatti nagar Janpad kannouj"}, 
		{"Uttar Pradesh", "Kanpur", "Satyadev Pachauri", "उत्तर प्रदेश", "कानपुर", "सत्यदेव पचौरी",  "9415051777",  "", "", "sdpachauri1@gmail.com", "", "117/L/ 89 Naveen Nagar kakadev kanpur"}, 
		{"Uttar Pradesh", "Kaushambi", "Vinod Kumar Sonkar", "उत्तर प्रदेश", "कौशाम्बी", "विनोद कुमार सोनकर",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Kheri", "Ajay Kumar", "उत्तर प्रदेश", "खेरी", "अजय कुमार",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Kushi Nagar", "Vijay Kumar Dubey", "उत्तर प्रदेश", "कुशी नगर", "विजय कुमार दुबे",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Lalganj", "Sangeeta Azad", "उत्तर प्रदेश", "लालगंज", "संगीता आजाद",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Lucknow", "Rajnath Singh", "उत्तर प्रदेश", "लखनऊ", "राजनाथ सिंह",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Machhlishahr", "Bholanath (B.P. Saroj)", "उत्तर प्रदेश", "मछलीशहर", "भोलानाथ (बीपी सरोज)",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Maharajganj", "Pankaj Choudhary", "उत्तर प्रदेश", "महाराजगंज", "पंकज चौधरी",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Mainpuri", "Mulayam Singh Yadav", "उत्तर प्रदेश", "मैनपुरी", "मुलायम सिंह यादव",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Mathura", "Hema Malini Dharmendra Deol", "उत्तर प्रदेश", "मथुरा", "हेमा मालिनी धर्मेंद्र देओल",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Meerut", "Rajendra Agarwal", "उत्तर प्रदेश", "मेरठ", "राजेंद्र अग्रवाल",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Mirzapur", "Anupriya Singh Patel", "उत्तर प्रदेश", "मिर्जापुर", "अनुप्रिया सिंह पटेल",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Misrikh", "Ashok Kumar", "उत्तर प्रदेश", "मिसरिख", "अशोक कुमार",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Mohanlalganj", "Kaushal Kishore", "उत्तर प्रदेश", "मोहनलालगंज", "कौशल किशोर",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Moradabad", "Dr. S T Hasan", "उत्तर प्रदेश", "मुरादाबाद", "डॉ। एसटी हसन",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Muzaffarnagar", "Sanjeev Kumar Balyan", "उत्तर प्रदेश", "मुजफ्फरनगर", "संजीव कुमार बाल्यान",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Nagina", "Girish Chandra", "उत्तर प्रदेश", "नगीना", "गिरीश चंद्र",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Phulpur", "Keshari Devi Patel", "उत्तर प्रदेश", "फूलपुर", "केशरी देवी पटेल",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Pilibhit", "Feroze Varun Gandhi", "उत्तर प्रदेश", "पीलीभीत", "फिरोज वरुण गांधी",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Pratapgarh", "Sangam Lal Gupta", "उत्तर प्रदेश", "प्रतापगढ़", "संगम लाल गुप्ता",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Rae Bareli", "Sonia Gandhi", "उत्तर प्रदेश", "रायबरेली", "सोनिया गांधी",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Rampur", "Mohammad Azam Khan", "उत्तर प्रदेश", "रामपुर", "मोहम्मद आज़म खान",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Robertsganj", "Pakauri Lal", "उत्तर प्रदेश", "रोबर्टस गंज", "पखौरी लाल",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Saharanpur", "Haji Fazlur Rehman", "उत्तर प्रदेश", "सहारनपुर", "हाजी फजलुर रहमान",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Salempur", "Ravinder", "उत्तर प्रदेश", "सलेमपुर", "रविंदर",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Sambhal", "Dr. Shafiqur Rehman Barq", "उत्तर प्रदेश", "संभल", "डॉ। शफीकुर रहमान बर्क",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Sant Kabir Nagar", "Praveen Kumar Nishad", "उत्तर प्रदेश", "संत कबीर नगर", "प्रवीण कुमार निषाद",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Shahjahanpur", "Arun Kumar Sagar", "उत्तर प्रदेश", "शाहजहांपुर", "अरुण कुमार सागर",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Shrawasti", "Ram Shiromani", "उत्तर प्रदेश", "श्रावस्ती", "राम शिरोमणि",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Sitapur", "Rajesh Verma", "उत्तर प्रदेश", "सीतापुर", "राजेश वर्मा",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Sultanpur", "Maneka Sanjay Gandhi", "उत्तर प्रदेश", "सुल्तानपुर", "मेनका संजय गांधी",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Unnao", "Swami Sachchidanand Hari Sakshi", "उत्तर प्रदेश", "उन्नाव", "स्वामी सच्चिदानंद हरि साक्षी",  "",  "", "", "", "", ""}, 
		{"Uttar Pradesh", "Varanasi", "Narendra Modi", "उत्तर प्रदेश", "वाराणसी", "नरेंद्र मोदी",  "8980809224",  "", "", "narendramodi@narendramodi.in", "", "R/O. C/1, Someshwar Tenament, Ranip Ahmedabad-382480"}, 
		{"Uttarakhand", "Almora", "Ajay Tamta", "उत्तराखण्ड", "अल्मोड़ा", "अजय टम्टा",  "9013869486",  "9456590857", "", "ajaytamtamp03@gmail.com", "", "Laxmi Nivas, Dugalkhola Almora"}, 
		{"Uttarakhand", "Garhwal", "Tirath Singh Rawat", "उत्तराखण्ड", "गढ़वाल", "तीरथ सिंह रावत",  "9412004626",  "", "", "rawattirathsingh@gmail.com", "", "Village & Post Sinro, Patti Ashwalsiu, District Pauri Garhwal"}, 
		{"Uttarakhand", "Haridwar", "Ramesh Pokhriyal Nishank", "उत्तराखण्ड", "हरिद्वार", "रमेश पोखरियाल निशंक",  "9456597100",  "0135-2746363", "", "drrameshpokhriyal@gmail.com", "", "37/1 Vijay colony, Ravindranath Tagore Marg, Dehradun, Uttarkhand"}, 
		{"Uttarakhand", "Nainital-UdhamSingh Nagar", "Ajay Bhatt", "उत्तराखण्ड", "नैनीताल-उधमसिंह नगर", "अजय भट्ट",  "",  "", "", "", "", ""}, 
		{"Uttarakhand", "Tehri Garhwal", "Mala Rajya Laxmi Shah", "उत्तराखण्ड", "टिहरी गढ़वाल", "माला राज्य लक्ष्मी शाह",  "",  "", "", "", "", ""}, 
		{"West Bengal", "Alipurduars", "John Barla", "पश्चिम बंगाल", "अलीपुरद्वार लोक", "जॉन बारला",  "9733333339",  "", "", "johnbarla97333333@gmail.com", "", "Lakhipara, Tea Garden, P.O. Banarhat, P.S. Banarhat, Dist-Jalpaiguri-735202"}, 
		{"West Bengal", "Arambag", "Aparupa Poddar (Afrin Ali)", "पश्चिम बंगाल", "आरामबाग", "वानर पोद्दार (अफरीन अली)",  "9830011147",  "", "", "aparupa29@gmail.com", "", "28, Gandhi Sarak, P.O-Rishra, P.S.-Serampore, Dt. Hooghly, Pin 712248(WB)"}, 
		{"West Bengal", "Asansol", "Babul Supriya Baral", "पश्चिम बंगाल", "आसनसोल", "बाबुल सुप्रिया बराल",  "9930033334",  "", "", "smallb9@gmail.com", "", "FLAT NO. 2D, 2ND FLOOR, PRATHAMA, 1 NO. MOHISHILA COLONY, BOTTALA, ASANSOL-713303"}, 
		{"West Bengal", "Baharampur", "Adhir Ranjan Chowdhury", "पश्चिम बंगाल", "बरहाम्पुर", "अधीर रंजन चौधरी",  "09868180498",  "", "", "adhir@sansad.inc.in", "begalpcc@gmail.com", " 9, Hari Babur Paschim Goli, PO. - Berhampore, PS - Berhampore Town, Murshidabad, West Bengal 742102"}, 
		{"West Bengal", "Balurghat", "Sukanta Majumdar", "पश्चिम बंगाल", "बेलूरघाट", "सुकांत मजूमदार",  "8768333983",  "9434964125", "", "majumdarwbes@gmail.com", "", "Khadimpur Masterpara P.O.& P.S.Balurghat,Dist.-Dakshin Dinajpur,West Bengal Pin-733101"}, 
		{"West Bengal", "Bangaon", "Shantanu Thakur", "पश्चिम बंगाल", "बंगाव", "शांतनु ठाकुर",  "7797604020",  "9647534453", "", "thakurbari05@gmail.com", "shantanuthakur2019@gmail.com", "Vill-Uttar Chikanpara, P.O. Thakurnagar, P.S-Gaighata, Dist-North 24 Pgs. State-West Bengal, Pin-743287"}, 
		{"West Bengal", "Bankura", "Subhas Kumar Sarkar", "पश्चिम बंगाल", "बांकुड़ा", "सुभास कुमार सरकार",  "9434015474",  "", "", "drsarkar2011@gmail.com", "", "Lokepur, Po-Kenduadihi, PS-Bankura Dist Bankura, West Bengal Pin-722102"}, 
		{"West Bengal", "Barasat", "Dr. Kakoli Ghoshdastidar", "पश्चिम बंगाल", "बारासात", "डॉ. काकोली घोषदस्तीदार",  "9013180190",  "9830159332", "", "kakolighosh.dastidar@gmail.com", "", "Digberia, Uttarpara PO Badu, P.S Madhyamgram, Dist. North 24 Paragans, Kolkata-700128"}, 
		{"West Bengal", "Bardhaman Durgapur", "Surendrajeet Singh Ahluwalia", "पश्चिम बंगाल", "बर्धमान-दुर्गापुर", "सुरेंद्रजीत सिंह अहलूवालिया",  "9868181816",  "01123722826", "01123720747", "ahluwalia.ss@gmail.com", "", "Prakash Niwas,Boring Canal Road(West),Patna 800001"}, 
		{"West Bengal", "Bardhaman Purba", "Sunil Kumar Mondal", "पश्चिम बंगाल", "बर्धमान पूर्ब", "सुनील कुमार मोंडल",  "9474079393",  "9013869526", "6294566780", "sunilkrmondal592@gmail.com", "", "Vill-Kanksa,P.O.Panagarh Bazar ,Dist.Paschim Bardhaman,Pin-713148"}, 
		{"West Bengal", "Barrackpur", "Arjun Singh", "पश्चिम बंगाल", "बैरकपुर", "अर्जुन सिंह",  "9836319507",  "", "", "arjunsinghbjp2019@gmail.com", "", "R/O Holding No. 36, B.L. No. 19/A, Mominpara, Po-PS Jagatdal, Dist 24 Pgs. (N) Pin-743125 WB"}, 
		{"West Bengal", "Basirhat", "Nusrat Jahan Ruhi", "पश्चिम बंगाल", "बशीरहाट", "नुसरत जहान रुही",  "9903605428",  "", "", "njahan72@gmail.com", "", "hiripukur 2nd Lane (Premises No. 1-6), Ward No. 069, Police Station Karaya, Pin 700019, House No. 4F"}, 
		{"West Bengal", "Birbhum", "Satabdi Roy (Banerjee)", "पश्चिम बंगाल", "बीरभूम", "सतबदी रॉय (बनर्जी)",  "9433025125",  "", "", "satabdi2roy@yahoo.com", "", "CITY HIGH, FLAT-12G, 85 PRINCE ANWAR SHAH ROAD, KOLKATA-700033"}, 
		{"West Bengal", "Bishnupur", "Saumitra Khan", "पश्चिम बंगाल", "बिश्नुपुर", "सौमित्र खान",  "9836093100",  "9013869525", "", "saumitrakhan@gmail.com", "", "R/O Vill Durlavpur Post Durlavpur P.S.Gangajal Ghati Dist Bankura Pin-722133 West Bengal"}, 
		{"West Bengal", "Bolpur", "Asit Kumar Mal", "पश्चिम बंगाल", "बोलपुर", "असित कुमार मल",  "9434326655",  "", "", "", "", "Vill Margram P.O & P.S Margran Dist Birbhum"}, 
		{"West Bengal", "Cooch behar", "Sri Nisith Pramanik", "पश्चिम बंगाल", "कूचबिहार", "श्री निसिथ प्रमाणिक",  "9635002108",  "7678599227", "", "pramanikbittu30@gmail.com", "", "R/O Vill.Kharija Baladanga Bhetaguri,PO Bhetaguri,PS Dinhata Dist-Cooch Behar,Pin 736134"}, 
		{"West Bengal", "Darjeeling", "Raju Bista", "पश्चिम बंगाल", "दार्जिलिंग", "राजू बिस्ता",  "9899792706",  "", "", "raju_bist@yahoo.co.uk", "", "R/O 18/75 Road No-75 Punjabi Bagh West Delhi"}, 
		{"West Bengal", "Diamond Harbour", "Abhishek Banerjee", "पश्चिम बंगाल", "डायमंड हार्बर", "अभिषेक बनर्जी",  "9830510000",  "", "", "abhishekbanerjee.mp@gmail.com", "", "30B, Harish Chatterjee Street, Kalighat, Kolkata-700026"}, 
		{"West Bengal", "Dum Dum", "Sougata Ray", "पश्चिम बंगाल", "डम डम", "सौगात रे",  "9830031220",  "9013180175", "", "sougatapolitics_roy@yahoo.co.in", "", "162 D/593 Lake Gardens, Kolkata-700045"}, 
		{"West Bengal", "Ghatal", "Deepak Adhikari", "पश्चिम बंगाल", "घटल", "दीपक अधिकारी",  "9163055555",  "", "", "medevadhikari@gmail.com", "", "R/O 375,Prince Anwar Shah Road 29B Tower-4-South City Kolkata-700068"}, 
		{"West Bengal", "Hooghly", "Locket Chatterjee", "पश्चिम बंगाल", "हुगली", "लॉकेट चटर्जी",  "9830065838",  "9874381789", "", "chatterjee.locket@gmail.com", "", "111, R.N Tagora Road, Kalkata 700076"}, 
		{"West Bengal", "Howrah", "Prasun Banerjee", "पश्चिम बंगाल", "हावड़ा", "प्रसून बनर्जी",  "9830473557",  "9874170000", "", "prasuntmcsc@gmail.com", "", "R/O AA-101 Block-A S.D Tower, Prafulla Kanan West, Kestopur, PS Beguiati, north 24 Parganas, Kolkata-700101"}, 
		{"West Bengal", "Jadavpur", "Mimi Chakraborty", "पश्चिम बंगाल", "जादवपुर", "मिमी चक्रवर्ती",  "8017391214",  "", "", "chakrabortymimi.mc@gmail.com", "", "N-0194, Puratan Pandapara Pashim, Gram Panchayat Khariya, Police Station Kotwali, Dist. Jalpaiguri -735132"}, 
		{"West Bengal", "Jalpaiguri", "Jayanta Kumar Roy", "पश्चिम बंगाल", "जलपाईगुड़ी", "जयंत कुमार रॉय",  "9434875805",  "", "", "jkumroy@gmail.com", "", "Flat No 4F, Shantiniketan, Sushrut Nagar, Darjeeling WB-734102"}, 
		{"West Bengal", "Jangipur", "Khalilur Rahaman", "पश्चिम बंगाल", "जंगीपुर", "खलीलुर रहमान",  "9434065101",  "", "", "khalilurrahmannbw@gmail.com", "", "illage - Debidaspur, P. O. - Kankuria, P.S. - Samserganj, Dist - murshidabad, Pin -742202"}, 
		{"West Bengal", "Jaynagar", "Pratima Mondal", "पश्चिम बंगाल", "जयनगर", "प्रतिमा मंडल",  "9883505957",  "9434739793", "", "pratimamondal66@yahoo.com", "", "7K, Ballygunge Station Road, Kolkata -700019 WB"}, 
		{"West Bengal", "Jhargram", "Kunar Hembram", "पश्चिम बंगाल", "झारग्राम", "कुंअर हेम्ब्रम",  "7001952142",  "", "", "kunarhmbrm@gmail.com", "", "R/O Kanyadoba,PO & PS & Dist-Jhargram,Pin -721507,State WB"}, 
		{"West Bengal", "Kanthi", "Sisir Kumar Adhikari", "पश्चिम बंगाल", "कंठी", "सिसिर कुमार अधकारी",  "9434039494",  "9650080251", "", "sisiradhikari76@yahoo.com", "", "R/O Village Karkuli Po_PS-Contai Dist Purba Medinipur Pin -721401"}, 
		{"West Bengal", "Kolkata Dakshin", "Mala Roy", "पश्चिम बंगाल", "कोलकाता दक्षिण", "माला रॉय",  "",  "", "", "", "", ""}, 
		{"West Bengal", "Kolkata Uttar", "Bandyopadhyay Sudip", "पश्चिम बंगाल", "कोलकाता उत्तर", "बंद्योपाध्याय सुदीप",  "",  "", "", "", "", ""}, 
		{"West Bengal", "Krishnanagar", "Mahua Moitra", "पश्चिम बंगाल", "कृष्णनगर", "महुआ मोइत्रा",  "",  "", "", "", "", ""}, 
		{"West Bengal", "Maldaha Dakshin", "Abu Hasem Khan Chowdhury", "पश्चिम बंगाल", "मालदा दक्षिण", "अबू हसीम खान चौधरी",  "",  "", "", "", "", ""}, 
		{"West Bengal", "Maldaha Uttar", "Khagen Murmu", "पश्चिम बंगाल", "मालदा उत्तर", "खगेन मुर्मू",  "",  "", "", "", "", ""}, 
		{"West Bengal", "Mathurapur", "Choudhury Mohan Jatua", "पश्चिम बंगाल", "मथुरापुर", "चौधरी मोहन जटुआ",  "",  "", "", "", "", ""}, 
		{"West Bengal", "Medinipur", "Dilip Kumar Ghosh", "पश्चिम बंगाल", "मेदिनीपुर", "दिलीप कुमार घोष",  "",  "", "", "", "", ""}, 
		{"West Bengal", "Murshidabad", "Abu Taher Khan", "पश्चिम बंगाल", "मुर्शिदाबाद", "अबू ताहिर खान",  "",  "", "", "", "", ""}, 
		{"West Bengal", "Purulia", "Jyotirmay Singh Mahato", "पश्चिम बंगाल", "पुरुलिया", "ज्योतिर्मय सिंह महतो",  "",  "", "", "", "", ""}, 
		{"West Bengal", "Raiganj", "Debasree Chaudhuri", "पश्चिम बंगाल", "रायगंज", "देबाश्री चौधरी",  "",  "", "", "", "", ""}, 
		{"West Bengal", "Ranaghat", "Jagannath Sarkar", "पश्चिम बंगाल", "रानाघाट", "जगन्नाथ सरकार",  "",  "", "", "", "", ""}, 
		{"West Bengal", "Sreerampur", "Kalyan Banerjee", "पश्चिम बंगाल", "श्रीरामपुर", "कल्याण बनर्जी",  "",  "", "", "", "", ""}, 
		{"West Bengal", "Tamluk", "Dibyendu Adhikari", "पश्चिम बंगाल", "तामलुक", "दिब्येंदु अधकारी",  "",  "", "", "", "", ""}, 
		{"West Bengal", "Uluberia", "Sajda Ahmed", "पश्चिम बंगाल", "उलूबेरिया", "सजदा अहमद",  "",  "", "", "", "", ""}, 

	};

}