/* Auto-generated file from db2MPjava.php*/

package in.jantamalik.Kendra;

public final class LokSabhaGroups {

    public static final String[][] all_groups = {
            // WhatsApp group
            {"Agra", "https://chat.whatsapp.com/BluHoIsfY4VEjGxocFhbOA"},
            {"Aligarh", "https://chat.whatsapp.com/LVLX8lybc4XGKAVBeWQYKi"},
            {"Allahabad", "https://chat.whatsapp.com/EnZ7FLH910kCnjk4fdCfly"},
            {"Ambedkar Nagar", "https://chat.whatsapp.com/GGm5pOqqOjVKdpIkhW6qZL"},
            {"Amethi", "https://chat.whatsapp.com/JfGXJmARuhW4sDaUYxcdQV"},
            {"Amroha", "https://chat.whatsapp.com/IFgzZ1JTTHq6qILPXGNILA"},
            {"Aonla", "https://chat.whatsapp.com/J0hcB6gJpfTJAa75mb5s4x"},
            {"Azamgarh", "https://chat.whatsapp.com/HR99eMXi0zJ1J78eosBFiu"},
            {"Badaun", "https://chat.whatsapp.com/HGYxiuRcXK27MlSX8ipYXV"},
            {"Baghpat", "https://chat.whatsapp.com/FdE1qfoxSnLLN1nVpqUw1a"},
            {"Bahraich", "https://chat.whatsapp.com/DJWpPh40U15EdMhtAXtcyw"},
            {"Ballia", "https://chat.whatsapp.com/FEx5wSEiUXvFR99bRXWdGl"},
            {"Banda", "https://chat.whatsapp.com/LUma3UrAHnrKaX0ARytd9l"},
            {"Bansgaon", "https://chat.whatsapp.com/Jd8cYbRtlnj37cP1AAKbZK"},
            {"Barabanki", "https://chat.whatsapp.com/CsBgpbXCH885M8xaAauxcl"},
            {"Bareilly", "https://chat.whatsapp.com/IWZ6QWpAD6n3z9RdKnAyze"},
            {"Basti", "https://chat.whatsapp.com/EXgj13pXyOvHa8jlPrVSa4"},
            {"Bhadohi", "https://chat.whatsapp.com/Ebr3n9NgY662JZ0VpsTXao"},
            {"Bijnor", "https://chat.whatsapp.com/I1SGP6pjJcfCfh2nWgjq4S"},
            {"Bulandshahr", "https://chat.whatsapp.com/IJjbufpJXvmGKN8s0xFrAe"},
            {"Chandauli", "https://chat.whatsapp.com/IzhDpJtA7elKj7Yqr88tpr"},
            {"Deoria", "https://chat.whatsapp.com/LK0yIRpwChbI0PYxmiSryz"},
            {"Dhaurahra", "https://chat.whatsapp.com/J7nVJvk1qU7FHMp4P7uyLm"},
            {"Domariyaganj", "https://chat.whatsapp.com/IduwU2CtWvVJAjbCZLqIu9"},
            {"Etah", "https://chat.whatsapp.com/IMFa48mDT3L42L0Kq3RUc4"},
            {"Etawah", "https://chat.whatsapp.com/HQm9xlmjQViARL1PINpPed"},
            {"Faizabad", "https://chat.whatsapp.com/FAu8UG4JpFuAtQAh8qx4fr"},
            {"Farrukhabad", "https://chat.whatsapp.com/D12a3BeVGu8Ddn1it8ovkD"},
            {"Fatehpur", "https://chat.whatsapp.com/HrquiThfn0NLlzCSiKNWEq"},
            {"Fatehpur Sikri", "https://chat.whatsapp.com/DnQgKLgS6uQ3cR3JZln76R"},
            {"Firozabad", "https://chat.whatsapp.com/IA8tomv3faQ6TlwCc3dkZ3"},
            {"Gautam Buddha Nagar", "https://chat.whatsapp.com/KGfJWSTUTG1GyNbRe7fokd"},
            {"Ghaziabad", "https://chat.whatsapp.com/ECOvb59i2VyJhMwQovZZg5"},
            {"Ghazipur", "https://chat.whatsapp.com/ElLMoLX9xIoIZ9p5D7BmXX"},
            {"Ghosi", "https://chat.whatsapp.com/FZmVjIjRJ8P0CTf4NytE9c"},
            {"Gonda", "https://chat.whatsapp.com/LGhpidfdmM591AOfBB2t0I"},
            {"Gorakhpur", "https://chat.whatsapp.com/BSQbmVpipkP0bFpLuXHOGV"},
            {"Hamirpur", "https://chat.whatsapp.com/ITfqhfRg19I7Tb4orCutyx"},
            {"Hardoi", "https://chat.whatsapp.com/EkTnysGD4IIFl0CISQ1XZL"},
            {"Hathras", "https://chat.whatsapp.com/Dap7ApnaBagC9iswFnvA6j"},
            {"Jalaun", "https://chat.whatsapp.com/H1YbllWyqRWCBCWCRmWnMk"},
            {"Jaunpur", "https://chat.whatsapp.com/HMfvP2j66NN1Z7YnlI3JrO"},
            {"Jhansi", "https://chat.whatsapp.com/FgmZC5G51CTEzFXsVWdchV"},
            {"Kairana", "https://chat.whatsapp.com/DfnqPsTyoG9C1EQVy100XQ"},
            {"Kaiserganj", "https://chat.whatsapp.com/CoXCug2wkgAEwRR41ylSxI"},
            {"Kannauj", "https://chat.whatsapp.com/FdRvUrxl5IR23qNHG3a3Ob"},
            {"Kanpur", "https://chat.whatsapp.com/Fg5B1a1Mk22KiN5JJQVW7B"},
            {"Kaushambi", "https://chat.whatsapp.com/Db7MQaEab59Av5ZjP8Vvfy"},
            {"Kheri", "https://chat.whatsapp.com/JMR97WO6FvHLQZ2WacQX9r"},
            {"Kushi Nagar", "https://chat.whatsapp.com/LW4SwS8eWjQ4N0FlLcdaVv"},
            {"Lalganj", "https://chat.whatsapp.com/IOHn8xG5dVoBnHeLNPIJO6"},
            {"Lucknow", "https://chat.whatsapp.com/JY5nFUgg3vZ8wWSLTkZOYv"},
            {"Machhlishahr", "https://chat.whatsapp.com/HRQsCo5wH1FFrImFnPO1wr"},
            {"Maharajganj", "https://chat.whatsapp.com/DY4v41oliPt2oItDyupXBU"},
            {"Mainpuri", "https://chat.whatsapp.com/LaT95ilIIBw0I0MxJMDyev"},
            {"Mathura", "https://chat.whatsapp.com/IbLxUDqqKkBHHsxpYlKHYA"},
            {"Meerut", "https://chat.whatsapp.com/EdzlUFrGqy3FwKk8UOH1bJ"},
            {"Mirzapur", "https://chat.whatsapp.com/Cko9XhANi4aJX9rJzdoYj1"},
            {"Misrikh", "https://chat.whatsapp.com/KsaFbwJpNZZ1tQKhIDFHX5"},
            {"Mohanlalganj", "https://chat.whatsapp.com/HlsfjSvEtB6LYbzspcMIqm"},
            {"Moradabad", "https://chat.whatsapp.com/Dy1ixKYvwx7FeRb9UCFG8t"},
            {"Muzaffarnagar", "https://chat.whatsapp.com/BTZvJvJPirR5DghUNVrHrS"},
            {"Nagina", "https://chat.whatsapp.com/GaQi4wE0FzCCdbi2nBJyGf"},
            {"Phulpur", "https://chat.whatsapp.com/IrtOf9ZhPAW1cooQFvYl5X"},
            {"Pilibhit", "https://chat.whatsapp.com/EQ7IvxzqRYDGOO338k7Mav"},
            {"Pratapgarh", "https://chat.whatsapp.com/EifVsyHq9OdBovk7xfW4va"},
            {"Rae Bareli", "https://chat.whatsapp.com/ByFn2I04BpV4wm6YlfIk4Z"},
            {"Rampur", "https://chat.whatsapp.com/KojIbR2TY2G3od8G8HuUpV"},
            {"Robertsganj", "https://chat.whatsapp.com/F6eDygzuGYwCNBPhLOFy7C"},
            {"Saharanpur", "https://chat.whatsapp.com/FXKKTKalELILpIu5Ho6GKb"},
            {"Salempur", "https://chat.whatsapp.com/Jw5eSrHDYiT0Mk0WqxTYl7"},
            {"Sambhal", "https://chat.whatsapp.com/IL8uOl2hwGwDU2ztr24gmM"},
            {"Sant Kabir Nagar", "https://chat.whatsapp.com/JKAgJgepigMIMlaFnQg3bS"},
            {"Shahjahanpur", "https://chat.whatsapp.com/D4tlczwT5Sb5OhvNi55CdV"},
            {"Shrawasti", "https://chat.whatsapp.com/BSiXP21l6sdGCNHjYMtU5F"},
            {"Sitapur", "https://chat.whatsapp.com/Iplky24gWku8H0VwK4lNzq"},
            {"Sultanpur", "https://chat.whatsapp.com/Ks5fID6VlGcGg0WKjrIWLt"},
            {"Unnao", "https://chat.whatsapp.com/EFM12Ds6M1YFKc7IcL0f1w"},
            {"Varanasi", "https://chat.whatsapp.com/EjYlGYrGOIi6kt98xDjRXo"},
    };
}